### ISSUE TITLE
[Bug Report] Button getting disappeared when button is disabled in dark theme

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#7814] opened 2019-07-12 14:34 UTC
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.5

### Steps to reproduce
Enable button property as disabled with dark theme 

### Expected Behavior
Button should not disappeared when it's disabled in dark theme

### Actual Behavior
Getting disappeared 

### Reproduction Link
<a href="https://codepen.io/ksankumar/pen/RzOjqK" target="_blank">https://codepen.io/ksankumar/pen/RzOjqK</a>

**Comment by jacekkarczmarczyk** [comment] 2019-07-12 14:35
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4482

**Closed** 2019-07-12 17:22 UTC
Labels: duplicate
