### ISSUE TITLE
[Bug Report][3.3.2] DataTable loading progress bar is hidden

### ISSUE THREAD

**Issue by kingyue737** [vuetifyjs/vuetify#17523] opened 2023-06-02 08:06 UTC
### Environment
**Vuetify Version:** 3.3.2
**Vue Version:** 3.3.4
**Browsers:** Edge 113.0.1774.57
**OS:** Windows 10

### Steps to reproduce
set `loading` true for a `<v-data-table>`

### Expected Behavior
Users can see progress bar without interaction

### Actual Behavior
Users need to scroll down the table to see the progress bar

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVFFvmzAQ/iuWpSmtFEOzai+IVZ06Tdpb3kMeHLhkXo2x7IOtivLfd4ZACB1tefLdd99394GPzZF/szZqauAJTxFKqyXCQ2YYSxtRSJQC5U5DSDDWiLIqQCeKCr2w4ISVB/ia8TaxBremMONdcfILZAHOE3w+DUhbTvnNtk+FjGikroOakeVFRVeyUOZAaXT1kM619EEBNDQSVWXEqoMe0ng8NzlJ45Gt1OdOWWwNwl9bOWQF7GWtkR075cC9ue0jxhxg7cwl7mbtzSbsy/KCnH0mbHPJsTE1PKhQE2/xHbwH6n+zurs7MDo2ZPN2MZILj9TqYKjao3Q4BT3NH1wmbC+1hwn6DC9EDC/zmne6io7DQE9SV06BXyyHrmAKijqhvIdnBX5IchMs/Je/lzhPfZJu598g5wGfp69dhaDMGwK2q5iX+Okq4n+a4yuCr8nb4XzqDh1IQRoPt4wvuVbm2Ue/fWVoxdq7kPHc0zIM14QWBNH6JI7zwlAlrZhqXGQAY2PLmJYT1f7l8T66jz7HhfLYp4SWOx+1YkFpm5kTNVRluNeilHbStQPazuc7mXFSCvE7IzxSWexqg6oEUVRlO8uqm2WUjsCXYueqP3SbSSTj51fUtgkDf6DVe26pxSvpOGwP/Y0cfTFw4D7qaEIbu5pAr5ydP/WJn5a8pdGLb0fm239wZaSQ)

**Comment by scscgit** [comment] 2023-06-02 09:00
Also you forgot to mention: this only occurs if there are 0 `items`.

**Comment by nekosaur** [comment] 2023-06-02 09:50
Duplicate of https://github.com/vuetifyjs/vuetify/issues/17462

**Closed by nekosaur** 2023-06-02 09:50 UTC
Labels: S: triage
