### ISSUE TITLE
[Bug Report] Arrow dropdown icon doesn't open the datepicker (multiple)

### ISSUE THREAD

**Issue by diavrank** [vuetifyjs/vuetify#12258] opened 2020-09-21 04:49 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4183.102
**OS:** Mac OS 10.15.6

### Steps to reproduce
1.- Have a [datepicker (multiple)](https://vuetifyjs.com/en/components/date-pickers/#date-pickers-multiple) 
2.- Click on the Arrow dropdown icon located on the right side.
4.- Note that datepicker is not opened

### Expected Behavior
I think that default action when click on the arrow icon should be open the datepicker, otherwise I think that icon is unnecessary. This doesn't happen in other components like [multiple combobox](https://vuetifyjs.com/en/components/combobox/#multiple-combobox). In other cases, some [datepickers](https://vuetifyjs.com/en/components/date-pickers/#date-pickers-in-dialog-and-menu) doesn't show the arrow icon, so, this could be another solution.

### Actual Behavior
The arrow ícon does nothing. 

### Reproduction Link
<a href="https://codepen.io/diavrank/pen/ZEWmpze" target="_blank">https://codepen.io/diavrank/pen/ZEWmpze</a>

### Other comments
Have this arrow icon doing nothing is a bit confused for some users. (Reported by a client in a production application).

**Comment by jacekkarczmarczyk** [comment] 2020-09-21 08:39
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10964 https://github.com/vuetifyjs/vuetify/issues/8141

**Closed by jacekkarczmarczyk** 2020-09-21 08:39 UTC
Labels: triage
