### ISSUE TITLE
[Feature Request] Add someone to Vuetify TreeSelect

### ISSUE THREAD

**Issue by DmitrySkibitsky** [vuetifyjs/vuetify#11154] opened 2020-04-18 19:05 UTC
### Problem to solve
This is what I would like to see in Vuetify https://vue-treeselect.js.org/

### Proposed solution
oh may

**Comment by RaiBnod** [comment] 2020-05-30 05:34
Yes, if we include this one it would have been great.

**Comment by Mert75** [comment] 2020-08-14 00:46
Already got the [Treeview](https://vuetifyjs.com/en/components/treeview/) component, perhaps you could integrate this with the VAutocomplete to replicate

**Comment by KaelWD** [comment] 2020-08-14 04:20
Duplicate of #3049

**Closed by KaelWD** 2020-08-14 04:20 UTC
Labels: C: VAutocomplete
