### ISSUE TITLE
[Bug Report] DataTable should reset to first page of results after a search. 

### ISSUE THREAD

**Issue by jennyballard** [vuetifyjs/vuetify#11324] opened 2020-05-05 00:40 UTC
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Windows 10

### Steps to reproduce
In the Codepen example:
Show 3 pages per item. 
Navigate pages until 7-9 of 16 shows. 
Search for the letter 'x'
 

### Expected Behavior
I expect to see the results matching the letter 'x'. I expect the table to start from the first page of matching results.

### Actual Behavior
I see the results matching the letter 'x' starting from the last page of results. As this only shows 2 items it looks like there are only two matches. In fact there are more on the previous pages.
 
The user has to notice that it is on the last page and then go back pages.

### Reproduction Link
<a href="https://codepen.io/jenbee/pen/JjYMboo?editors=1010" target="_blank">https://codepen.io/jenbee/pen/JjYMboo?editors=1010</a>

### Other comments
This is similar but slightly different to #5312 which is fixed. That issue was when no results showed on the last page. This issue is when there are some results for the last page.

**Comment by Khrisseh1995** [comment] 2020-05-06 16:59
I'd like to take a stab at this, but I'm not sure if it's a bug or working as intended?

**Comment by jacekkarczmarczyk** [comment] 2020-05-08 10:52
Related https://github.com/vuetifyjs/vuetify/issues/10949

**Comment by Mert75** [comment] 2020-08-14 19:47
Duplicate of #10949 and #11324

**Closed by Mert75** 2020-08-14 19:47 UTC
Labels: C: VDataTable, duplicate
