### ISSUE TITLE
[Bug Report][3.0.0-beta.10] VImg crashes after Vue-router navigation

### ISSUE THREAD

**Issue by D34DPlayer** [vuetifyjs/vuetify#15761] opened 2022-09-09 01:15 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Vue Version:** 3.2.38
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Linux

### Steps to reproduce
- Navigate to /image to load the image
- Navigate to / to unload it
- Navigate back to /image

### Expected Behavior
The image should be there and no error should happen

### Actual Behavior
Vue crashes

### Reproduction Link
<a href="https://codesandbox.io/s/festive-snyder-ejvdil?file=/src/components/IMG.vue" target="_blank">https://codesandbox.io/s/festive-snyder-ejvdil?file=/src/components/IMG.vue</a>

### Other comments
Traceback:
```
Uncaught (in promise) TypeError: can't access property "value", oldBindings[i] is undefined
    invokeDirectiveHook runtime-core.esm-bundler.js:2779
    patchElement runtime-core.esm-bundler.js:5349
    flushPostFlushCbs runtime-core.esm-bundler.js:339
    flushJobs runtime-core.esm-bundler.js:393
    promise callback*queueFlush runtime-core.esm-bundler.js:280
    queueJob runtime-core.esm-bundler.js:274
    scheduler runtime-core.esm-bundler.js:1803
    triggerEffect reactivity.esm-bundler.js:394
    triggerEffects reactivity.esm-bundler.js:384
    triggerRefValue reactivity.esm-bundler.js:1000
    effect reactivity.esm-bundler.js:1134
    triggerEffect reactivity.esm-bundler.js:394
    triggerEffects reactivity.esm-bundler.js:379
    triggerRefValue reactivity.esm-bundler.js:1000
    set value reactivity.esm-bundler.js:1045
    poll VImg.tsx:166
    pollForSize VImg.tsx:176
    init VImg.tsx:136
```

**Comment by jonrwads** [comment] 2022-09-09 01:44
Experiencing the exact same issue.  It was working fine until I updated dependencies and it broke everything.
Working with:
Vuetify: 3.0.0-beta.8
Vue: 3.2.37

Broken with:
Vuetify: 3.0.0-beta.10
Vue: 3.2.39

**Comment by KaelWD** [comment] 2022-09-09 05:02
Duplicate of #15724

**Closed by KaelWD** 2022-09-09 05:02 UTC
Labels: S: triage
