### ISSUE TITLE
[Feature Request]  Option of Disabling Swipe for v-tabs (touchless mobile)

### ISSUE THREAD

**Issue by RGFanker** [vuetifyjs/vuetify#2711] opened 2017-12-04 14:38 UTC
### New Functionality
In some cases the user may not want to "swipe" to view another tab and instead want to "tap" the tab (like a button). 

### Improvements
For instance, when you have two parent tabs and child tabs within them, the two parent tabs could "swipe", but the child tab "swipe" could be disabled.

### Bugs or Edge Cases it Helps Avoid
If the user unintentionally swipes the screen off what they are currently viewing.

**Comment by jacekkarczmarczyk** [comment] 2017-12-04 17:24
Please provide a codepen and steps to reproduce your problem

**Comment by RGFanker** [comment] 2017-12-04 17:27
Here is the codepen I used as I was discussing the issue with @johnleider . https://codepen.io/kfanker/pen/pdRVPW
You will need to view it in Chrome developer tools or mobile to see the swiping.

**Comment by smares** [comment] 2017-12-04 20:48
Or look at the documentation with a mobile browser. The table at the bottom of most component pages requires horizontal scrolling but as soon as you try to scroll to the right, you switch to the slots tab.

**Comment by johnleider** [comment] 2017-12-04 20:49
Yes! This is very annoying I know. Already on the radar

**Comment by jacekkarczmarczyk** [comment] 2017-12-05 03:25
Then it's a duplicate of https://github.com/vuetifyjs/vuetify/issues/2335

**Closed by jacekkarczmarczyk** 2017-12-05 03:25 UTC
Labels: feature request

**Comment by johnleider** [comment] 2018-11-01 14:49
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
