### ISSUE TITLE
[Feature Request] No persistent v-dialog is closed when click starts in dialog but ends outside it

### ISSUE THREAD

**Issue by adrianByv** [vuetifyjs/vuetify#9228] opened 2019-10-04 11:59 UTC
### Problem to solve
For example, when you have a form or just inputs in a v-dialog and need to select the text usually you start de click at the end of the text and drag to the start. But in most of cases this drag ends out of the dialog. And the dialog is closed.

Our users find this behavior very weird

I also notice another weird behavior, because when you put the dialog persistent and drag like in the example it's doesn't close, but also din't make the dialog bounce (that make when you click outside).

### Proposed solution
The solution should be only close the dialog when the click (start and end) out of dialog. Like when dialog make a bounce if it's persistent

**Comment by jacekkarczmarczyk** [comment] 2019-11-12 05:05
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8055

**Closed by jacekkarczmarczyk** 2019-11-12 05:05 UTC
Labels: triage
