### ISSUE TITLE
[Bug Report][3.3.11] [DatePicker] Infinity loop locale pl 

### ISSUE THREAD

**Issue by rafalpiechowicz** [vuetifyjs/vuetify#17951] opened 2023-08-03 10:06 UTC
### Environment
**Vuetify Version:** 3.3.11
**Last working version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Unfortunate I can't import cdn library of date-fns with pl local in to playground of vuetify. 

### Expected Behavior
Works same at the others local's. For example for 'sv' locale everythings works perfect.

### Actual Behavior
When I choose polish local in the datepicker in the first click after refresh datepicker is bugged and can't select any value.

It's situation when I pressed the value once. 
![image](https://github.com/vuetifyjs/vuetify/assets/116646546/60a5bc62-a2b8-417f-a5d5-51962dc0c1eb)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU01rGzEQ/StCF7fUu4rrQsE4xYHSUw89lF6iHJTdca1k9YE0dhKM/3tH0trebggYcrBXmnnz3htpdLvnuy2gXr/UD5EvuDbeBWR71gRQCH9Kjh3YOjjDJj12Im0P/E6gHzbetMojhB61ailaaSfyd23jGb9nvjuxHdOic43qgFDSwnPGNc5GZL0cu/7fzoe9tIzhBgwsiLGFtdp2+LvsJ53+u8EJO0wTKEkQJi0ZU8XlYuQ6AxkrJk5gRk4X9Pv1s88XwvR/+Cgtn/Ib72tySKe2RDC+I9JvCbLcVcr7vMwb6gWVthD6UA7m3r1uHiEco4ztKuNa6K4lR4go+TkTN+6pUu2DasAioSxu4jnbuM4FqvJBGxVezoXi6EKMbaRIcbkUA/e0jU3QHlkE3JZ0CdCSei7XWBnlaV6cpd7zcck+ESU/HaBMk5X2km8QfVwI0bSWyqhDvQu1BRTWG7EimAhbi9pA1Tqzmtfz+otodcRhuIZoqvvgniIEIpG8v5Ysk6biAqkemRVmsyLRx6pO3cek8YpbkOAOQhXAthDoui5saVQ2bGuUeru1Vy/pEvFxzepzPftaX4lPJDPgHr2+C5gHhPMrIiyFQlMXz9l3fiD0PvKodNo+xtGUNDF3cHv08L7bymyJ6o40+WHK8xGTdKngd/8AvWygLw==)

**Comment by KaelWD** [comment] 2023-08-09 09:23
Duplicate of #17867

**Closed by KaelWD** 2023-08-09 09:23 UTC
Labels: S: triage
