### ISSUE TITLE
[Bug Report] VFileInput does not work with Safari on MacOS or iOS

### ISSUE THREAD

**Issue by fabiopaitra** [vuetifyjs/vuetify#11455] opened 2020-05-21 13:35 UTC
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.1
**Browsers:** Safari
**OS:** Mac OS 10.15.4

### Steps to reproduce
Upload a file into passport for instance

### Expected Behavior
appear the file selected.

### Actual Behavior
appears nothing

### Reproduction Link
<a href="https://codepen.io/anon/pen/RXaPOX?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/RXaPOX?&editable=true&editors=101</a>

### Other comments
As the bug report #7941 states sometimes it works, sometime does not. it's a weird behavior. But it's the same as it.

**Comment by ElijahKotyluk** [comment] 2020-05-22 05:50
Duplicate of #7941

**Comment by lioneaglesolutions** [comment] 2023-05-04 00:09
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).

**Closed by lioneaglesolutions** 2023-05-04 00:09 UTC
Labels: T: bug, platform specific, C: VFileInput
