### ISSUE TITLE
[Bug Report][3.6.13] v-data-table performance issue

### ISSUE THREAD

**Issue by Warnier-zhang** [vuetifyjs/vuetify#20335] opened 2024-08-15 01:25 UTC
### Environment
**Vuetify Version:** 3.6.13
**Vue Version:** 3.4.31
**Browsers:** Chrome 127.0.0.0
**OS:** Windows 10

### Steps to reproduce
43 columns，2550 rows，use too much time and memory，
v-data-table-server：> 40s，> 3G,
v-data-table-virtual：12 ~ 20s，> 2G

### Expected Behavior
less than 10s, < 1G, bad than vuetify 2 datatable

### Actual Behavior
more time and memory

**Comment by blalan05** [comment] 2024-08-15 01:41
what are the contents? Just text or do you have buttons, and other components/elements?

**Comment by Warnier-zhang** [comment] 2024-08-15 02:50
just text 2050rows in one page

**Comment by Warnier-zhang** [comment] 2024-08-15 06:28
reproduction link：
https://play.vuetifyjs.com/#eNqdlEtvm0AQgP/KCFUKVgzGfVxcbCk9VOqhVaT2ZlvyBo8LDi/tgypC/PfOPiCQoCoqB1hmZufxzezuW0/wZHVX12Gj0Nt4scSizpnE3aEEiJvgzCQLJHvIMWgyLhXLtQJgkyI7Ixfbg+dWB89pMvKh5Q8Vk+J9L04x+51KEn+Mol6mLYOG5QpJXrICrWIXr+YCU0rxapQf/YqEZ7UEgVLVJuOsqCsuoQWOlyUkVVErieclVOX3SpW0hA4uvCrghuq90T6ArEohKT9TBWyHXb6/gO0OWptrjmOb/dFKLxUHX6syEq4/0yeGTxF9b28X/U5du9kX1kqk/iAFkJnMcQOnL0QqeNdm3Wn5rHzEJ1JpiD+IzFTbLeyqsx9O9fOyD6Nl2uC5tq/sEe/uv1GKLjgTT2UCF5RJSkUOGTk/Jf6Be4KUCfQ5iipvcARCPwT8V1ZgpeQUkn00D9P8ESj7zOH6EEWvgE396Lxdpa8cXa2jq+N+nXEDxsl+hPLanY6076ShBj9rxLOQyKkDpJjufRHWVGXbqJeuC4Pp+NeB81uHom+ZMV3CmqoeJEM7TYNNTNs4e4T+OZMvQb8V8Szct2L9H6BDkHmI01E2Nv0gT2isKQ4dbn9/NJrhYE/JuIkP3YiHMsVSz7LKqeDRuFqXobmDjGNtEQ7R+/j6Ha/sbUP3jNctS5Xn5nX8C2egkF0=

boats2, is faster
boats1, get data from a fake api, is slow, this is my real condition 

just use v-data-table-virtual as an example , v-data-table-server has the same problem

**Comment by KaelWD** [comment] 2024-08-15 06:39
Duplicate of #18806

**Closed by KaelWD** 2024-08-15 06:39 UTC
Labels: S: needs reproduction, S: triage

**Comment by Warnier-zhang** [comment] 2024-08-15 07:49
i don't think two issues are exactly the same
