### ISSUE TITLE
[Bug Report][3.5.2] `VDataTable` `sort` should use the `value` of the column

### ISSUE THREAD

**Issue by moltinginstar** [vuetifyjs/vuetify#19159] opened 2024-02-02 13:35 UTC
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.15
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click a column to sort by, you will see the value used by `sort`.

### Expected Behavior
`sort` should use the computed `value` of a column if `value` is a function.

### Actual Behavior
`sort` receives `item[key]` instead, which is either `undefined` or the wrong value.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVl+L20YQ/ypT9R5ksOXcJfei2nfcS6G55lJS6IttuD1pbSuRZaFdOzhCLxaE/uFoH9q+FFJoC6WU0JRQaMh9G3HJY75CZncla3WW744jftHu7OzM/GZ+M95ebLDIaR+EoTWfUcM2OpxOQp9wutcPADrzFglDuZQbZxpw4gU0ykVS6BJOWpyc+BTsMSUujVi3b+SrvgG2hzaFSH77xuou3i68wce9Y3FsDWe+f0Qm9HiAF2KYE39GIalcUpGMvRAcnzBh+HFr+9Yt1IF4dSOBTltp6e7aGrrLoph79DG7PAQWkgDmLW+ISkrloy4EGP0FRRmth4nbm7heiy6oiEvu9RDETwu+4qktXN0EBXG4N78ykyKWChBUEaE6Y+o80oKtdV+IdBYUdBH5r/BFSBSdLkDoMCfyQg6M8lkIPglGGAsvqIJGGIctf+oQpFgX+gYN+sYnCnt+OKGMkRFleBwr9zSwiyXgFcGrVoDE6hs2buOhFzGeQDzxXNenuEAq4d6M0UrS6BvN8qpismSmZuFT3ILarutK/ii9r9RyXUdVRykd5OtcK8m/D8NrYMjS1wUKsZQ43p19LYG8O/vmGlDevPj+/IfTK3CcPz19++Ov5788e/PTi6vgZMvfsuU/Wfo0W/6epT9fwJVUS8exZmZev0O6sIHxyAtGTcVYtm/DA+pMI7dTyEmw2GtAF7tdWY2QNVEA908eUodbj+iCmeoq7O9DnDSsiLozh5omcZwm4Ll+eXUdD1EROYmax/FWjHpJclxE0cPtoIGBKxgl4Xo5Lwe9EkKuWOBst+HezOeej9HPiA+iU2AYTSdw8MVnZSLkdMRc9JSTVXyiThoNAGTZKxLF9r5xSBY+0YpTcEhU5N9s+UeW/lU5LXgmfopCtWaPcAL4Os81u+l32fJllp5l6d8bTQtK1hq+RyKO0+HJBtPP0GhBotNs+WqDg3KF6bdhZ3u1Z5xwVvEsCW3D7s7tuuuSwjbwCIdgpRFvUoy704DwMcFRVVuP/7P0zyz9Nlv+l6Uvb1KVQ+rx8Qbjz0VFNibskoo8mDJ9WOnVeH7tCtzZWUvpkPisktNB2RyfiwbynmC/TvQ2Ue3OygbhojtMrN6FeaC+aiSU/VgZMvljpKa7uMdFfre4WTcdGysg2P8iDcXzREuEHBA2mKJ/ZQzSlmakWcMXzqS+JTQsKStdlVWvaCmhrqaqWFESIl1F1kM9Bka0rFepwqYR2jBJE05k8Ji6iJt3v7x/ZKm8esOFSRqNpqgUtUYWzl9MozDZ09MxQOEscOkQ+9nd0Dw1uc7/YNbynMs3J1likv29r4yIYS+eXx8IWR7ADWEVf4ZruIoD6VQ9ybriTD5risMPg6CwJiDUth8+LOWzCx9ZRtI0blt3rO1dQyx2rR1j8B5BYblN)

### Other comments
As a workaround I’m forced to extract the value functions into a map,

```ts
const values = {
  fullName: (item) => $t("full-name", {
    first: ts(item.name.first),
    middle: ts(item.name.middle),
    last: ts(item.name.last),
    age: item.age,
  }),
  views: (item) => item.stats?.views ?? null,
  ...
} satisfies {
  fullName: (item: Account) => string;
  views: (item: Account) => number | null;
  ...
};
```

so I can reuse them in my reimplementation of sort (using the newly added `sortRaw`):

```ts
const headers = [
  {
    title: $t("header.full-name"),
    key: "fullName",
    value: (item) => $t("full-name", {
      first: ts(item.name.first),
      middle: ts(item.name.middle),
      last: ts(item.name.last),
      age: item.age,
    }),
    sortRaw: (a, b) => {
      const aValue = values.fullName(a);
      const bValue = values.fullName(b);

      return aValue.localeCompare(bValue);
    },
  },
  ...
];
```

What I would like to be able to do is define the `value` of each column once and have the default implementation of `sort` use that value instead of `item[key]`.

**Comment by KaelWD** [comment] 2024-02-04 05:44
Duplicate of #18840

**Closed by KaelWD** 2024-02-04 05:44 UTC
Labels: S: triage
