### ISSUE TITLE
[Bug Report] v-textarea does not autogrow with v-stepper

### ISSUE THREAD

**Issue by paul-a-byford** [vuetifyjs/vuetify#10911] opened 2020-03-22 14:02 UTC
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
* Create a v stepper with 3 steps

* On each step create a v textarea with props set; 
    * rows=2
    * auto-grow=true
    * value="A sentence of text that is long enough to fill more than two rows in a v-textarea, so that it should autogrow to show all the text"

### Expected Behavior
The v-textarea fields on each tabs to autogrow to show all the text

### Actual Behavior
* The v-textarea autogrows only on step that is shown first
* The v-textarea does not autogrow on the other steps

### Reproduction Link
<a href="https://codepen.io/pbyford/pen/rNVvegY" target="_blank">https://codepen.io/pbyford/pen/rNVvegY</a>

**Comment by YipingRuan** [comment] 2020-04-26 11:43
Need to use the key attribute to hint the new VNode.

`
<v-textarea :key="currentStep"
`

**Comment by jacekkarczmarczyk** [comment] 2020-05-03 15:40
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7312

**Closed by jacekkarczmarczyk** 2020-05-03 15:40 UTC
Labels: C: VTextarea, T: bug, has workaround
