### ISSUE TITLE
[Feature Request] Fix the inconsistency usage of the "value" property/attribute

### ISSUE THREAD

**Issue by Mashiane** [vuetifyjs/vuetify#12315] opened 2020-09-29 23:19 UTC
### Problem to solve
Vuetify has a lot of components, granted, however there is one property that is being used inconsistenty. The value property. For example, in some components, its used to link to the "v-model" for data setting and retrieval and in some instances its used for visibility.  For example for the v-chip the "active" property is used for visibility, whilst for the bottom navigation drawer buttons it means something else and for the alert it means "visibility" and for checkboxes for example its back to the "value" of the checkbox.

Why is it impossible to have a single property name for "visibility"? and why is "value" used to mean different things depending on the component. One has to keep track of component use of the property each time and remember that for this it means that and not that?

### Proposed solution
Perhaps  define a single property for "visibility" across the complete framework. Use the "value" property for 1 particular purpose across all components. #JustAThought

**Comment by KaelWD** [comment] 2020-09-30 12:34
Duplicate of #11952

**Closed by KaelWD** 2020-09-30 12:34 UTC
Labels: triage
