### ISSUE TITLE
[Bug Report] Tooltip and dialog are not positioned correctly

### ISSUE THREAD

**Issue by koljada** [vuetifyjs/vuetify#9933] opened 2019-12-10 14:29 UTC
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
1. Create an app inside at least 2 parents with relative position.
2. Add a tooltip or dialog component(maybe some other components are affected as well).
3. Hover over tooltip or open a dialog.

### Expected Behavior
Tooltip or dialog is positioned correctly

### Actual Behavior
Tooltip or dialog is positioned incorrectly with some offset

### Reproduction Link
<a href="https://codepen.io/koliada/pen/WNbwQdz?&editable=true&editors=101" target="_blank">https://codepen.io/koliada/pen/WNbwQdz?&editable=true&editors=101</a>

**Comment by johnleider** [comment] 2020-01-10 17:57
Related https://github.com/vuetifyjs/vuetify/issues/2202 and https://github.com/vuetifyjs/vuetify/issues/775 in terms of context, functionality is way different now.

Not sure if this is a caveat or not, @KaelWD thoughts?

**Comment by TrendyTim** [comment] 2020-01-28 03:12
Ive just spent a few hours playing around with this, as i got bitten by it after wring a bunch of components that someone wants to put in a grid that is based on relative positioned divs.

The results of my investigation are that the issue is caused by the cumulative offsetTop and offsetLeft of all the the relative ancestors. 

I'm not sure exactly how to fix it in the code, but i think using MENU_CONTENT_DIV.offsetParent and going up all the offsetParents of the offsetParents and subtracting all their offsetTop and offsetLefts from the current calculated values until there is no more offsetParents (or stop at body, body offsets are seemingly usually 0 but wont hurt to keep it just in case id think).

If the ancestors are not relative the .offsetParent returns the body, so it should not break anything.

Browser support looks sublime (can always fall back to to current broken behaviour if not supported)
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent

I hope that helps and we can get the issue resolved.

----
Examples:
My codepen of a select in a relative parent https://codepen.io/TrendyTim/pen/povBVoR, the pop up is being pushed down by the offsetTop of the relative parent adding BRs to the top of the page shifts the select list that much further away from the input instead of from the top of the page.

offsetLeft, seems to have the same effect as in a boostrap grid its shifted right as well https://codepen.io/TrendyTim/pen/povBLMN/

**Comment by TrendyTim** [comment] 2020-02-20 23:10
@KaelWD  I see this may be in your area of expertise, i tried and failed miserably to integrate my thoughts into the v-menu, even though i know if i do it manually once the menu is shown  it worked. Do you have any time to look into it ?

**Comment by jonbulica99** [comment] 2020-07-21 09:54
BUMP, please take a look into this

**Comment by KaelWD** [comment] 2020-08-21 08:02
Duplicate of #7703

**Closed by KaelWD** 2020-08-21 08:02 UTC
Labels: Framework, T: bug
