### ISSUE TITLE
[Bug Report][3.7.1] Memory leak with VOverlay and VDataTable

### ISSUE THREAD

**Issue by lebinhchieu** [vuetifyjs/vuetify#20422] opened 2024-09-04 13:33 UTC
### Environment
**Vuetify Version:** 3.7.1
**Vue Version:** 3.5.0
**Browsers:** Google Chrome
**OS:** Windows

### Steps to reproduce
1. Install packages, build & preview
2. Access home page via Chrome
3. Open memory in devtools & take a snapshot
4. Open the snapshot, filter `TestObject` => Nothing shows
5. Click `Overlay` or `Data Table` link (both pages create a `TestObject` instance)
6. Click `Back to home` button in the `Overlay` or `Data Table` link to back to home
7. Take a new memory snapshot
8. Filter `TestObject` => a record shows

### Expected Behavior
`TestObject` should be removed

### Actual Behavior
`TestObject` is still there after backing to home
![image](https://github.com/user-attachments/assets/79c7c3d5-8c88-4e72-87f5-5ec5183f5dcc)

### Reproduction Link
[https://github.com/lebinhchieu/vuetify-memory-issue](https://github.com/lebinhchieu/vuetify-memory-issue)

**Comment by Tkyzxim** [comment] 2024-09-04 13:33
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by CyberNick2025** [comment] 2024-10-23 16:08
Hey,
After receiving several complaints that our web application keeps hanging up after some time, we also started looking for the cause and came across v-dialog. 

Thanks to @peter-gy and his bug report [https://github.com/vuetifyjs/vuetify/issues/18880](https://github.com/vuetifyjs/vuetify/issues/18880). By reading his comments I was able to try out the approach he proposed to solve an similar issue. 🎉 

I used function `getEventListeners(document)` in the developer console of Chrome to find out if there is an event listener that is not removed after closing the dialog. I was able to find out that the event listener for the `focusin` event is not removed cleanly and I am now quite sure that this is the cause of the memory leak.

I tried to locally edit the VDialog.mjs to resolve the issue. The event listener is added here:
```javascript
if (IN_BROWSER) {
      watch(() => isActive.value && props.retainFocus, val => {
        val ? document.addEventListener('focusin', onFocusin) : document.removeEventListener('focusin', onFocusin);
      }, {
        immediate: true
      });
    }
```

After adding the following code to the file and restarting the development server I was able to resolve the memory leak:
```javascript
onBeforeUnmount(() => {
      document.removeEventListener('focusin', onFocusin)
    })
```

As this is the first time I added a comment to a GitHub project, I hope my comment was helpful 😄

**Comment by lebinhchieu** [comment] 2024-10-24 04:42
Thanks for your response @CyberNick2025

Hope Vuetify team could fix the issue soon

**Comment by CyberNick2025** [comment] 2024-10-24 13:10
Hi @lebinhchieu ,
on thing that may helps you in the meantime is to set the property `retain-focus` of the v-dialog to false in your code:
`:retain-focus="false"`. If you do not need `retain-focus` to be set to true it may works as a workaround for you. 

https://vuetifyjs.com/en/components/dialogs/#props-retain-focus

**Closed** 2024-11-03 09:27 UTC
Labels: T: bug, C: VOverlay

**Comment by lebinhchieu** [comment] 2025-09-29 10:29
I just upgraded Vue and Vuetify to latest, the issue is still there :(
And I realized that it happens with activator="parent". It seems we need to remove the reference on unmounting

Vue: 3.5.22
Vuetify: 3.10.3
