### ISSUE TITLE
[Bug Report] v-container taking full width even without fluid prop

### ISSUE THREAD

**Issue by kamit-transient** [vuetifyjs/vuetify#8961] opened 2019-09-14 09:26 UTC
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Firefox 60.0
**OS:** Linux x86_64

### Steps to reproduce
Just open any grid example given on Vuetifyjs.com under the grid section. or use below code:
```
 <div id="app">
  <v-app id="inspire">
    <v-container class="red lighten-5">
      <v-row
        class="mb-6"
        no-gutters
      >
        <v-col
          v-for="n in 4"
          :key="n"
        >
          <v-card
            class="pa-2"
            tile
            outlined
          >
            col
          </v-card>
        </v-col>
      </v-row>
  
      <v-row no-gutters>
        <v-col
          v-for="n in 2"
          :key="n"
          :cols="n === 1 ? 8 : 4"
        >
          <v-card
            class="pa-2"
            tile
            outlined
          >
            col-{{ n === 1 ? 8 : 4 }}
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </v-app>
</div>




Script: 

 new Vue({
  el: '#app',
  vuetify: new Vuetify(),
  
})

 ```

### Expected Behavior
V-container shoud horizontally center the content with appropriate spacing depending on device width

### Actual Behavior
its is taking entire viewport width even on md, lg, and xl without fluid prop

### Reproduction Link
<a href="https://codepen.io/kamit_transient/pen/pozZvrp?&editable=true&editors=101#anon-signup" target="_blank">https://codepen.io/kamit_transient/pen/pozZvrp?&editable=true&editors=101#anon-signup</a>

**Comment by KaelWD** [comment] 2019-09-15 10:32
Duplicate of #8517

**Closed by KaelWD** 2019-09-15 10:32 UTC
Labels: triage
