### ISSUE TITLE
[Bug Report][3.0.0-beta.6] v-text-field loading slot not respected

### ISSUE THREAD

**Issue by MoazAlkharfan** [vuetifyjs/vuetify#15615] opened 2022-08-10 16:49 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.6
**Vue Version:** 3.2.36
**Browsers:** Edge 104.0.1293.47
**OS:** Windows 10

### Steps to reproduce
Even the example from the next.vuetify official site doesn't work

- Slap a `loading` attribute into the `v-text-field`
- Add `template` tag with `v-slot:progress` attribute
- Watch the progress slot not getting respected

Even the example from the next.vuetify official site doesn't work
https://next.vuetifyjs.com/en/components/text-fields/#progress

### Expected Behavior
Progress slot getting respected

### Actual Behavior
Progress slot is ignored

### Reproduction Link
<a href="https://codepen.io/pen?&editors=101&prefill_data_id=2e725a03-560b-48c9-a6dd-63aa3543553f" target="_blank">https://codepen.io/pen?&editors=101&prefill_data_id=2e725a03-560b-48c9-a6dd-63aa3543553f/</a>

**Comment by KaelWD** [comment] 2022-08-10 16:56
Duplicate of #15341

We're working on that page right now: #15520

**Closed by KaelWD** 2022-08-10 16:56 UTC
Labels: S: triage
