### ISSUE TITLE
[Feature Request] support layout for phones with screens covering the full device in vuetify3

### ISSUE THREAD

**Issue by vchrisb** [vuetifyjs/vuetify#13358] opened 2021-04-01 07:50 UTC
### Problem to solve
Most phones nowadays have displays with notches and displays stretching the full phone, like iPhone 12. It is more elegant to use this extended space also for web applications, especially for PWAs. Currently for each component that might interfere with theses areas, one has manually add margins or positions to many components. Like `bottom: env(safe-area-inset-bottom) !important;`

### Proposed solution
Give option to use `viewport-fit=cover` and incorporate `safe-area-inset-*` environment variables in necessary components like `v-bottom-navigation`. Maybe similar how ionic is doing it? https://ionicframework.com/docs/theming/advanced

**Comment by KaelWD** [comment] 2021-08-14 10:15
Duplicate of #13025

**Closed by KaelWD** 2021-08-14 10:15 UTC
Labels: S: triage
