### ISSUE TITLE
v-select dropdown fails to close

### ISSUE THREAD

**Issue by zapping** [vuetifyjs/vuetify#733] opened 2017-06-09 09:48 UTC
The dropdown of v-select fails to close when another v-select is clicked. 

### Steps to reproduce
1. Click on a v-select and when the dropdown is visible
2. Click on another v-select.
3. The dropdown of the first v-select fails to close and
4. both the dropdowns of both the select are visible.

### Versions
Latest version of vue and vuetify. 
On all browsers.
Windows OS is what I use.

### What is expected ?
The dropdown of first v-select should close when the dropdown of second v-select becomes visible

### What is actually happening ?
But when you click anywhere else on the browser both the dropdowns close at the same time.

### Reproduction Link
https://vuetifyjs.com/components/selects

**Comment by nekosaur** [comment] 2017-06-09 09:57
Duplicate of https://github.com/vuetifyjs/vuetify/issues/730. Please make sure to have a look at the existing issues before creating a new one.

**Closed by nekosaur** 2017-06-09 09:57 UTC
Labels: duplicate

**Comment by sabinmaz** [comment] 2017-06-12 14:53
when use v-flex or v-card horizontal v-select dropdown won't work why is that
