### ISSUE TITLE
[Bug Report] Bug calendar visualisation 

### ISSUE THREAD

**Issue by Azzeccagarbugli** [vuetifyjs/vuetify#7627] opened 2019-06-21 14:39 UTC
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
Just open the **reproduction link**, there will be no events in the calendar when actually they should be over there, as the [documentation](https://vuetifyjs.com/en/components/calendars#weekly) shows instead 

### Expected Behavior
The calendar **should show** the current events during the week

### Actual Behavior
The calendar **doesn't show** anything at all

### Reproduction Link
<a href="https://codepen.io/anon/pen/YoZVVd?&editable=true&editors=111" target="_blank">https://codepen.io/anon/pen/YoZVVd?&editable=true&editors=111</a>

**Comment by KaelWD** [comment] 2019-06-21 14:49
Duplicate of #6704

**Closed by KaelWD** 2019-06-21 14:49 UTC
Labels: triage
