### ISSUE TITLE
[Bug Report][3.7.3] v-data-table-virtual checkbox selection "select all options"  is slow when there is large data rendered  ﻿

### ISSUE THREAD

**Issue by kiryle** [vuetifyjs/vuetify#20601] opened 2024-10-21 09:11 UTC
### Environment
**Vuetify Version:** 3.7.3
**Vue Version:** 3.5.12
**Browsers:** Chrome 129.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
on the given codepen, select all options in the table.
You'll notice a lag in the selection of the checkbox. The number of rows is around 1000. It looks like the lag is due to the ripple on the checkbox,the transition animation affects performance

### Expected Behavior
The checkbox should be selected without any lag for large datasets also.

### Actual Behavior
The all options checkbox in data-table gets selected after a certain lag

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtlltv2jAUgP/KEesESBDua4sAqX3o9rBp06hWTYBUk5yBhXEix2FjiP8+O+Q+HIHUPhT73PydY5/Ys0PFF3brwfOsXYCVYWUkcesxInEy5wCjXdMhkjQlWTJs7qiQAWFaATBcI3FQ+ON5JRrNK5GGqhhaHtk/ukQmSn/t/m76yNCWkSAcN30p1KKrvXLzyApj8zXS1VoqYb/djmU6fHNHWIBKzsk2Mp6MWudoVR6jViYpNfVtQT0ZJoh/PFdIcPAXCZiEw2kFHaVWj2cAAmUgeDrXXGHKQ5ilMoADSCoZDqGqc4bnvYfVBhBGV1zJfEmEVPMN7tVMg1fh2DjvP/UQHahtuCv9eiYGcieJ4Gsbc4jPyFdyDbWtyZ+FBuYA3wS1EWo3Jn9P683uP5EIg+deq3KOi8x4qc9LsbLZCYAuXlwlX6JaJ68PSzOE3qAgP6U8hG63oAhzUQ5t/VfQaVrl0u52copC3mcBv9pI+BdSgtg1If7HHiEOShHziksQf7h71W9GvOJKMV7fgHdbhte5vxrvhezwe8C5kbBvIiwslhB2wwqaCpg/GJcQTpE8CsS/qtXPl/DOtMP585QA9ssAO/lolwB+ImLpio8BEaoDzyIWgqaIgyJGhHhXusu319eQUXvzRLmpj3umPu4b+rh0j6/v46l0xVbtMtmYO6X4SUm2uVjciPHDGzfyC+XOlFBm2mPTh2Zg6OT7N+7kJ/UZfKaOqU16+VOT2WPDGeyGh/D6Pk6vmuNpoJWnke1uvUBqmiSF7Bsm+yRIHgUzy7IehCD7Wkfz1C11xSnLhbUlXo3CeJIvh+1yX4ZXHIzVZamc5Zr6VnjnzSi8h3RqnSqwiDnT29HSJVX+rzeHZHqEdzcHenzN2kaI2iYVH+tJ/lElTr9qlVEreRpVjg0eMBb+W/wDoPmO6Q==)

**Comment by KaelWD** [comment] 2024-10-25 07:13
Duplicate of #19447

**Closed by KaelWD** 2024-10-25 07:13 UTC
Labels: S: triage
