### ISSUE TITLE
[Feature Request] "mini-variant-width" prop support for <v-list> inside of a <navigation-drawer>

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#3410] opened 2018-02-27 18:14 UTC
### New Functionality
Right now the  `mini-variant-width` prop doesn't work with `<v-list>` elements even though it's the most frequently used component in `<navigation-drawer>`:

https://codepen.io/anon/pen/eyKwJg

You've flagged this issue multiple times as duplicate and yet it still doesn't work with the only component it should work -  `<v-list>`. Am I missing something? Is that the way it should work?

As you can see it in the codepen example, the items of the `<v-list>` aren't being centered when you set a different value of `mini-variant-width` 

### Improvements
It would allow to change the width of the mini variant `<navigation-drawer>` with `<v-list>` component inside of it.

### Bugs or Edge Cases it Helps Avoid
none

**Comment by jaxn** [comment] 2018-03-03 06:27
This is my experience as well. I have some custom CSS in App.vue to work-around

**Comment by KaelWD** [comment] 2018-03-03 06:49
Duplicate of #2606

**Closed by KaelWD** 2018-03-03 06:49 UTC
