### ISSUE TITLE
[Bug Report] v-tab with "to" attribute broken. Аgain.

### ISSUE THREAD

**Issue by buzzzzer** [vuetifyjs/vuetify#3654] opened 2018-03-23 08:28 UTC
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
Toggle tabs

### Expected Behavior
working tab-item content like v1.0.8
https://codepen.io/Buzzzzer/pen/YaQvNP

### Actual Behavior
 tab-item does not work

### Reproduction Link
[https://codepen.io/Buzzzzer/pen/jzwKWG](https://codepen.io/Buzzzzer/pen/jzwKWG)

### Other comments
broken since 1.0.9

**Comment by KaelWD** [comment] 2018-03-23 08:46
You don't have any routes defined? If you're just using a hash instead of an actual route you should use `href`, not `to`: https://codepen.io/anon/pen/JLJZzo?editors=1010

**Comment by buzzzzer** [comment] 2018-03-23 08:58
@KaelWD. 
I use routes like ```http://site.org/foo/bar#one``` and ```http://site.org/foo/bar#two``` to direct link to a tab with href there does not work

in version 1.0.8 "to" attr worked fine

**Comment by KaelWD** [comment] 2018-03-23 12:12
Workaround: https://codepen.io/anon/pen/xWrMwm?editors=1010

**Comment by sindrepm** [comment] 2018-03-24 21:29
Something changed in 1.0.9 with regard to how active tab/slider position is calculated. My code that worked on 1.0.8 breaks on 1.0.9/1.0.10. It has to do with how nested named routes with params are handled.

If you have tabs on a component that is loaded via a route with params, starting from 1.0.9 you have to always include all params in the `:to` prop when linking to a child route or else the tab slider does not move. `vue-router` also prints this warning:

```"[vue-router] missing param for named route 'xxx': Expected 'param' to be defined"```

As far as I know it should not be necessary to re-iterate params that are defined on the parent route as they will be included automatically.

Not sure if this is by design or a bug but as it is a breaking change I would at least have expected a notice about this in the release notes.

Here is a codepen which demonstrates this behavior:
https://codepen.io/anon/pen/rdzqoQ

Change to Vuetify 1.0.8 to see that it works.

**Comment by KaelWD** [comment] 2018-03-25 04:01
@sindrepm That looks like a slightly different problem, could you please open a new issue?

**Comment by johnleider** [comment] 2018-03-25 16:39
@sindrepm this was a mistake on our part, we will release a regression PATCH tomorrow.

**Comment by johnleider** [comment] 2018-03-25 17:10
We have a fix coming. This is a hard thing to get right because we are not able to test vue-router.

**Closed** 2018-03-27 15:14 UTC
Labels: bug
