### ISSUE TITLE
[Bug Report][3.6.X] VNavigationDrawer don't close in mobile

### ISSUE THREAD

**Issue by joaopalopes24** [vuetifyjs/vuetify#19918] opened 2024-05-29 19:59 UTC
### Environment
**Vuetify Version:** 3.6.0
**Vue Version:** 3.4.27
**Browsers:** Chrome 125.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
https://www.loom.com/share/3774741c06454c1696c49dd4867566cf?sid=507a7130-1b75-46ef-ac2f-f99a5a2bd918

In the playground the error is not noticed because we need to start the page with the navigation open, and when we reduce the screen it always remains open. It's even like this in Vuetify's own documentation.

### Expected Behavior
Natigation was closed.

### Actual Behavior
The navigation always remains open.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUsFu2zAM/RVBl25AbAHLsA1BOnQretgO7bDtVvfg2HSiRpYEiXZSBPn3UVKSOmlXFCgSBCH5+Mj3qNsN964S36zN+w74hE8RWqtKhK+FZmzaZ6W18W8MVPlgOtzFMaPLXs5LlEZntStX4FiftaYGdV5wvzCrgh/QjF0fwAV99llimaGmPqMnlZLVctfKzllTKg8FZwhrpOylMjEUjxuIZ1ag6mDD/3Gj6wbUNxb0gDnwDsSGMBkxFQODKPSVkxaZB+yST7K1xiHbMAcN27LGmZadkbdnaanKaE/wtAJB3kWJ7wNxoiISPuLoCdjIeX7vjaazbEJvwSvTWqnA3dgg1xd8wmIl1EqlzOpnzAVpo32+WkC1fCZ/79chV/BfDjy4nsw41LB0c8BUvvpzTRYNinTeThH6heJv8EZ18dAR9r3TNa09wMVtf0SvpJ7/9VdrBO33ouJtCLmN+IKTf5cvSH9cd5yPY1+h6Us+pmtkbWlPnEyFYxqaktZdIFo/EaKqNbXRY5a9yzWg0LYVFwQTrtMoW8hq016M84/5h8+ilh6H+Rx8m82cWZG5xDLQTgQom4dXzNohacSn/EuasEvR65z5MOIJtYjHdJkDXYMLpr9O0knbkayT2hNpR54rqZf+9OH6aPXtG/VGmrs0aDvSnVLx5+4fkViX5A==)

**Comment by KaelWD** [comment] 2024-08-16 09:49
Duplicate of #19800

**Closed by KaelWD** 2024-08-16 09:49 UTC
Labels: S: triage
