### ISSUE TITLE
[Feature Request] DataTable Multiple Column Ordering

### ISSUE THREAD

**Issue by jlfernandesjn** [vuetifyjs/vuetify#3251] opened 2018-02-12 03:10 UTC
### New Functionality
Order data table content by Multiple Column 

### Improvements
It will avoid to use other dataTable plugins keeping theme integration.

### Bugs or Edge Cases it Helps Avoid
Visual theme bugs caused by other dataTable plugins

**Comment by KaelWD** [comment] 2018-03-06 01:07
Duplicate of #2659

**Closed by KaelWD** 2018-03-06 01:07 UTC
Labels: pending review
