### ISSUE TITLE
[Bug Report] sass-loader@9.x.x throws errors if you are sass variables

### ISSUE THREAD

**Issue by AssetKid** [vuetifyjs/vuetify#11892] opened 2020-07-20 12:01 UTC
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Google Chrome, Microsoft Edge, Mozilla Firefox
**OS:** Windows

### Steps to reproduce
* npm install
* npm run serve
* [FAILS DUE TO SASS-LOADER ERRORS]
* downgrade sass-loader to v8.0.2
* npm run serve
* [STARTS SUCCESSFULLY]

### Expected Behavior
Should run after updating to `sass-loader@9.x.x`.

### Actual Behavior
The app does not start due to sass-loader errors.

### Reproduction Link
<a href="https://github.com/assetkid/vuetify-sass-loader-bug" target="_blank">https://github.com/assetkid/vuetify-sass-loader-bug</a>

### Other comments
This only happens if you are using the variables.scss file for custom variables.

* https://vuetifyjs.com/en/customization/sass-variables/

sass-loader@9.0.0 BREAKING CHANGES

* [the prependData option was removed in favor the additionalData option, see docs
](https://github.com/webpack-contrib/sass-loader/releases/tag/v9.0.0)

**Comment by KaelWD** [comment] 2020-07-20 12:06
Duplicate of https://github.com/vuetifyjs/vue-cli-plugins/pull/185

**Closed by KaelWD** 2020-07-20 12:06 UTC
Labels: triage
