### ISSUE TITLE
[Bug Report] Importing stylus file causes some classes to cascade incorrectly

### ISSUE THREAD

**Issue by aaronrosenthal** [vuetifyjs/vuetify#3583] opened 2018-03-15 15:38 UTC
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.162
**OS:** Windows 7

### Steps to reproduce
1) Import main stylus file in main `App.vue` with:

```
<style lang="stylus">
@import '~vuetify/src/stylus/main'
</style>
```

2) Build the Data Iterator example.

### Expected Behavior
The classes from `components/_grid.styl` should take precedence.

### Actual Behavior
The `align-end` class is being overwritten by other classes from `v-list` components.

### Reproduction Link
[https://codepen.io/pen/?&editors=101](https://codepen.io/pen/?&editors=101)

### Other comments
The only workaround I have found is to add:

```
@import '~vuetify/src/stylus/main'
@import '~vuetify/src/stylus/components/_grid'
```

But this may have unintended side effects...

**Comment by KaelWD** [comment] 2018-03-15 15:54
That link is not sufficient to diagnose this issue. Please provide an example project that will demonstrate it. You may be able to use [CodeSandbox](https://codesandbox.io/s/vue) if it doesn't require any advanced configuration.

**Comment by aaronrosenthal** [comment] 2018-03-15 16:12
I'm not an expert on this, but I think it will require advanced configuration to reproduce. The Vue sandbox doesn't have stylus support out-of-the-box and I can't modify its Webpack configuration files, so I'm unable to use it to import stylus files.

**Comment by KaelWD** [comment] 2018-03-17 05:36
You should be able to just add stylus and stylus-loader to the dependencies. We do also accept git repos as reproduction if thatis easier.

**Comment by aaronrosenthal** [comment] 2018-03-22 02:02
I created a git repo as I could not get codesandbox to work:

https://github.com/aaronrosenthal/webpack4-vue-vuetify

Running this you will notice that `class="align-end"` does not work properly when importing Vuetify stylus files. If you uncomment the code in `src\styles\main.styl` then the example will work.

**Comment by nwaughachukwuma** [comment] 2018-03-22 08:49
Am getting this error: 

 ```
 1| @require './settings/*'
   2| @require './generic/*'
   3| @require './elements/*'
   4| @require './tools/*'
---------------^
   5| @require './trumps/*'
   6| @require './components/_tooltips.styl'
   7|
failed to locate @require file ./tools/*.styl
```

What could I be doing wrong

**Comment by jacekkarczmarczyk** [comment] 2018-03-22 08:56
This is not related to this issue, please ask questions on discord channel https://chat.vuetifyjs.com

**Comment by johnleider** [comment] 2018-09-14 13:36
It is sufficient.

**Comment by verstoff** [comment] 2018-09-26 10:38
Reproduced on latest version (1.2.5).
Builded css (vuetify.css) styles order differs from css generated by application when import main.styl. This breaks down the layout in some cases
https://vuetifyjs.com/en/components/data-tables#example-headers for example (Look at the checkboxes)

I think the reason is in the order of imports.

main.styl imports all components `@import './components/*'`
But building vuetify dist has other logic: the component can import another component and break the order

**Comment by hurrycaner** [comment] 2018-10-08 13:58
It's happening in 1.2.6 too

**Comment by johnleider** [comment] 2018-10-09 21:59
I'm unsure how to resolve this atm, help wanted.

**Comment by Traxo7** [comment] 2018-11-11 13:13
I think this line causes trouble for v-select:
https://github.com/vuetifyjs/vuetify/blob/17582f62cd80c7f8f0a6d9cf3cd5cdb6015af806/packages/vuetify/src/stylus/components/_text-fields.styl#L163

I copied relevant stylus to codepen to show the issue:
https://codepen.io/anon/pen/rQMGxG
Hovering over v-select shows text-cursor.
This does not happen when importing .css, but only .styl as far as I can see.

**Comment by Djaler** [comment] 2018-11-21 10:56
This happens to me even if I import `vuetify/dist/vuetify.min.css` instead of stylus file

**Comment by Djaler** [comment] 2018-11-21 10:57
I leave more info and reproduction link there - https://github.com/vuetifyjs/vuetify/issues/5681

**Comment by Djaler** [comment] 2018-11-21 11:07
Also, in my case issue was fixed by removing vuetify-loader

**Comment by Traxo7** [comment] 2018-11-21 16:09
@Djaler Perhaps we should open issue there then if you are sure that's the issue?  
I have not tested it yet.  
 https://github.com/vuetifyjs/vuetify-loader/issues  

META:  
I suggest in the future you edit first comment instead of posting 3 different ones within few mins.

**Comment by sn0rcha** [comment] 2018-12-06 21:05
Can confirm I have the same issue when doing 

```
// Import Vuetify styling
@require '~vuetify/src/stylus/main'
```

The v-select component cursor is not the right one

**Comment by AGPDev** [comment] 2018-12-26 15:58
We have news about this? 
I have problem to customize breakpoints in 1.4-beta.0 because i can replace variables.
I think this issue cause this problem too.

**Comment by js1990** [comment] 2019-04-16 10:26
The "correct" order to import the stylus files inside components would be nice.
Actually i think its just alphabetic, which causes the VSelect cursor: text;

Since we manipulate some variables its required to compile the stylesheet by ourself.
Actually this did it, but we're not able to see any side effects yet.

```styl
@import '~vuetify/src/stylus/main'
@import '~vuetify/src/stylus/components/_select'
```

**Comment by ikudosi** [comment] 2019-04-24 18:57
I am also experiencing the same issue using latest 1.5.13 with stylus. I only see the discrepancies on select component using the multiple flag. If you compare the framework's CSS from https://vuetifyjs.com/ and the stylus output the hierarchy is different.

For example, on vuetify.com this is the following order on common.{hash}.css

```
// line 4381 and imported from _select.styl
.v-input--selection-controls:not(.v-input--hide-details) .v-input__slot {
  margin-bottom: 12px;
}

// line 4852 and imported from _lists.styl
.v-list__tile__action .v-input--selection-controls .v-input__slot {
  margin: 0;
}
```

However.... when using stylus the order is flipped! After looking into it, I believe the issue may stem from 
vuetify/src/stylus/main.styl on the ```@import './components/*'``` statement as I'm going to assume that _lists.styl will run after __select.styl.

For me in my own main.styl override... the following fixes my issue with the the checkbox alignment when using select with multiple though I am not sure if there will be repercussions on this.

```
@import '~vuetify/src/stylus/main'
@import '~vuetify/src/stylus/components/_lists.styl'
```

**Comment by johnleider** [comment] 2019-09-15 19:05
As this issue is focused on v1.x of the framework, this issue is no longer actionable. We have made huge strides to alleviate these issues in v2 and while some issues do still exist, we are actively working to resolve them.

**Closed by johnleider** 2019-09-15 19:05 UTC
Labels: Framework, T: bug, help wanted
