### ISSUE TITLE
[Bug Report] Navigation-drawer disappears when fullscreen dialog opens for the second time

### ISSUE THREAD

**Issue by panjon** [vuetifyjs/vuetify#10561] opened 2020-02-12 21:05 UTC
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.100, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
- open the dialog
- close the dialog
- open the dialog

### Expected Behavior
The navigation-drawer shall be visible

### Actual Behavior
The navigation-drawer is out of viewport

### Reproduction Link
<a href="https://codepen.io/panjon/pen/yLNYxRq?editable=true&editors=101" target="_blank">https://codepen.io/panjon/pen/yLNYxRq?editable=true&editors=101</a>

### Other comments
The problem is that the navigation-drawer get following style when dialog closed:
`transform: translateX(-100%)`

`<aside class="v-navigation-drawer v-navigation-drawer--close v-navigation-drawer--fixed v-navigation-drawer--mini-variant v-navigation-drawer--open-on-hover theme--dark" data-booted="true" style="height: 100%; top: 0px; transform: translateX(-100%); width: 56px;"><div class="v-navigation-drawer__content">`

The translateX should be 0%

**Comment by KaelWD** [comment] 2020-02-13 03:28
This is caused by the `Dependent` mixin

**Comment by chrisdiana** [comment] 2020-05-28 04:49
+1 Seems to also appear with the standard navigation-drawer too on Chrome / Windows 10. Chrome / MacOS doesn't have the issue. Looks to be related to the transform bug as well.

**Comment by chrisdiana** [comment] 2020-05-28 16:38
Found a workaround in the meantime by using `permanent` and `absolute` props:

```
<v-navigation-drawer absolute permanent></v-navigation>
```

**Comment by johnleider** [comment] 2020-12-16 18:09
Duplicate of #10508

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-16 18:09 UTC
Labels: C: VNavigationDrawer, T: bug
