### ISSUE TITLE
[Bug Report] v-navigation-drawer with expand-on-hover and mini variant weird behavior

### ISSUE THREAD

**Issue by jd-0001** [vuetifyjs/vuetify#13327] opened 2021-03-26 06:02 UTC
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.90
**OS:** Linux x86_64

### Steps to reproduce
**Case 1: Icon inside the drawer**

1. Open the drawer by hover over it
2. Click on the Plus icon
3. Click on minus icon
4. Move mouse out of drawer

*(v-main is not getting full width)*

**Case 2: Toggling mini variant from outside of navigation drawer**

1. Open the drawer by hover over it
2. Click on the Plus icon
3. Click on the switch in v-main to enable mini variant

*(navigation drawer isn't going in mini mode)*

### Expected Behavior
**Case 1**: v-main should get full width
**Case 2**: navigation drawer should get mini variant

### Actual Behavior
**Case 1**: v-main is not getting full width
**Case 2**: navigation drawer isn't going in mini mode

### Reproduction Link
<a href="https://codepen.io/jd-0001/pen/JjEPRqY?editors=101" target="_blank">https://codepen.io/jd-0001/pen/JjEPRqY?editors=101</a>

### Other comments
Real world example of mini + expand-on-hover + navigation drawer:
https://pixinvent.com/demo/vuexy-vuejs-admin-dashboard-template/demo-1/dashboard/analytics

**Comment by johnleider** [comment] 2021-07-16 00:22
Duplicate of #13309

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-07-16 00:22 UTC
Labels: C: VNavigationDrawer, S: triage
