### ISSUE TITLE
[Feature Request] Use directive to create dialog/snackbar

### ISSUE THREAD

**Issue by nklayman** [vuetifyjs/vuetify#4081] opened 2018-05-16 21:37 UTC
### Problem to solve
It is quite annoying to have to either create multiple snackbars or add another data value if you want a snackbar to display different values. It would be much easier to be able to create dialogs/snackbars by calling a function, like in [quasar](https://quasar-framework.org/components/notify.html).

### Proposed solution
Use something like:
```javascript
this.$v.snackbar({
  message: 'my message',
  timeout: 5000,
  buttons: [{
    title: 'Checkout',
    action: this.goToLink()
  }],
  closeable:true // shorthand for close button
  // all other props included with snackbar
})
```
for both snackbar and dialog (make sure to keep a way to use html for a dialog)

**Comment by jacekkarczmarczyk** [comment] 2018-05-17 02:03
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3037

**Closed by jacekkarczmarczyk** 2018-05-17 02:03 UTC
