### ISSUE TITLE
[Bug Report] Lazy slider v-model

### ISSUE THREAD

**Issue by mokhosh** [vuetifyjs/vuetify#9111] opened 2019-09-26 12:04 UTC
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
1. put a v-slider in your component
2. `v-model.lazy="page_number"` on the v-slider
3. watch for `page_number` changes and fetch something from your api
4. make a hundred xhr requests per second

### Expected Behavior
Vuejs docs says `.lazy` will update the model on change events instead of input.

### Actual Behavior
Currently it doesn't make a difference if you use `v-model="model"` or `v-model.lazy="model"` on a slider element.

### Reproduction Link
<a href="https://codepen.io/mokhosh/pen/jONRbRa" target="_blank">https://codepen.io/mokhosh/pen/jONRbRa</a>

**Comment by KaelWD** [comment] 2019-09-26 23:24
Duplicate of https://github.com/vuejs/vue/issues/6914

**Closed by KaelWD** 2019-09-26 23:24 UTC
Labels: triage
