### ISSUE TITLE
[Bug Report] Date Picker has wrong year in title and year selector when use locale

### ISSUE THREAD

**Issue by alphaelf** [vuetifyjs/vuetify#3865] opened 2018-04-17 04:14 UTC
### Versions and Environment
**Vuetify:** 1.0.14
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
change locale to `en-u-ca-persian`
everything work fine except __year in title__ and __year selector__
they have one year decrease

### Expected Behavior
title year and year selector must be +1

### Actual Behavior
title year and year selector is -1

### Reproduction Link
[https://codepen.io/anon/pen/Yampdq](https://codepen.io/anon/pen/Yampdq)

**Comment by jacekkarczmarczyk** [comment] 2018-04-17 06:58
Related to https://github.com/vuetifyjs/vuetify/issues/1892

**Comment by jacekkarczmarczyk** [comment] 2018-06-10 11:42
That's actually the same problem, closing as duplicate of #1892

**Closed by jacekkarczmarczyk** 2018-06-10 11:42 UTC
Labels: pending review
