### ISSUE TITLE
[Bug Report] Vuetify CSS bug

### ISSUE THREAD

**Issue by astrahov** [vuetifyjs/vuetify#10589] opened 2020-02-15 17:29 UTC
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Safari 13.0.5, Google Chrome, Safari
**OS:** Mac OS 10.15.3

### Steps to reproduce
- `npm install`
- `npm run serve`
- open site url

### Expected Behavior
Normal height for buttons in BottomNavigation

### Actual Behavior
Height for buttons in BottomNavigation overwritten from `.v-btn:not(.v-btn--round).v-size--default`

### Reproduction Link
<a href="https://github.com/astrahov/Vuetify-CSS-bug" target="_blank">https://github.com/astrahov/Vuetify-CSS-bug</a>

**Comment by astrahov** [comment] 2020-02-15 17:40
Sorry. Banner Sticky - not relevant to this

**Comment by jacekkarczmarczyk** [comment] 2020-02-16 02:40
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8067

**Closed by jacekkarczmarczyk** 2020-02-16 02:40 UTC
Labels: triage
