### ISSUE TITLE
[Bug Report][2.5.6] Sheets don't fit carousel 

### ISSUE THREAD

**Issue by jmarshall9120** [vuetifyjs/vuetify#13983] opened 2021-07-24 20:10 UTC
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 91.0.4472.164
**OS:** Windows 10

### Steps to reproduce
v-sheet set to 100% height will not take up an entire carousel even though its the example you use in the docs.   So to reproduce, simply look at the first carousel example on the vue docs [here](https://vuetifyjs.com/en/components/carousels/#usage)

### Expected Behavior
I would expect the sheet to actually fit the carousel, or an example of proper use to be included in the docs.

### Actual Behavior
!(misfit sheet)[<blockquote class="imgur-embed-pub" lang="en" data-id="a/s1kDr4L"  ><a href="//imgur.com/a/s1kDr4L">miss-fitting v-sheet in v-carousel</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>]

### Reproduction Link
<a href="https://codepen.io/jmarshall9120/pen/QWvORPR" target="_blank">https://codepen.io/jmarshall9120/pen/QWvORPR</a>

**Comment by glen-84** [comment] 2021-07-29 18:19
You can add a `no-gutters` class to the `row`.

**Comment by KaelWD** [comment] 2021-07-30 06:49
Duplicate of #12840

**Closed by KaelWD** 2021-07-30 06:49 UTC
Labels: T: bug, T: documentation
