### ISSUE TITLE
[Bug Report][3.3.20] Navigation Drawer does not properly load in Nuxt SSR

### ISSUE THREAD

**Issue by maxostarr** [vuetifyjs/vuetify#18406] opened 2023-10-05 13:07 UTC
### Environment
**Vuetify Version:** 3.3.20
**Vue Version:** 3.3.4
**Browsers:** Firefox 118.0
**OS:** Windows 10

### Steps to reproduce
Reload the page and observe that the nav drawer does not appear until hydration step.

### Expected Behavior
The nav drawer is rendered properly on the server and does not pop in during hydration.

### Actual Behavior
The nav drawer is not rendered on the server and so pops in during hydration, causing a layout shift.

### Reproduction Link
[https://stackblitz.com/edit/nuxt-starter-qqumnj?file=nuxt.config.ts,plugins%2Fvuetify.ts,app.vue,package.json](https://stackblitz.com/edit/nuxt-starter-qqumnj?file=nuxt.config.ts,plugins%2Fvuetify.ts,app.vue,package.json)

**Comment by KaelWD** [comment] 2023-10-05 13:31
Duplicate of #12883

**Closed by KaelWD** 2023-10-05 13:31 UTC
Labels: S: triage
