### ISSUE TITLE
[Bug Report] Outline icon buttons are a bit off-center

### ISSUE THREAD

**Issue by lobo-tuerto** [vuetifyjs/vuetify#3998] opened 2018-05-06 21:09 UTC
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Firefox 59.0, Google Chrome, Mozilla Firefox
**OS:** Linux x86_64, Linux

### Steps to reproduce
```html
<v-btn small icon outline color="primary"><v-icon small>settings</v-icon></v-btn>
<v-btn small icon color="primary"><v-icon small>settings</v-icon></v-btn>
      
<v-btn icon outline color="primary"><v-icon small>settings</v-icon></v-btn>
<v-btn icon color="primary"><v-icon small>settings</v-icon></v-btn>
      
<v-btn icon outline color="primary"><v-icon>settings</v-icon></v-btn>
<v-btn icon color="primary"><v-icon>settings</v-icon></v-btn>
```

### Expected Behavior
Icons should be correctly centered if they are outlined or not.

### Actual Behavior
Icons are not correctly centered if you go for the outlined version.

### Reproduction Link
[https://codepen.io/lobo-tuerto/pen/odGRmY](https://codepen.io/lobo-tuerto/pen/odGRmY)

![screenshot-2018-5-6 vuetify template 1](https://user-images.githubusercontent.com/5730/39677865-cfaeacb6-5147-11e8-9d23-51f34d8459d0.png)

**Comment by KaelWD** [comment] 2018-05-07 03:39
Duplicate of #3433

**Closed by KaelWD** 2018-05-07 03:39 UTC
