### ISSUE TITLE
[Bug Report] Placeholder text on empty v-select no longer forces label into field border

### ISSUE THREAD

**Issue by antman888** [vuetifyjs/vuetify#13169] opened 2021-02-26 13:19 UTC
### Environment
**Vuetify Version:** 2.4.0
**Last working version:** 2.3.23
**Vue Version:** 2.6.5
**Browsers:** Chrome 88.0.4324.182
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Observe the empty unfocused state of the v-select

### Expected Behavior
Empty and unfocused v-select should appear with label in border, and placeholder text in field.

### Actual Behavior
Label appears in field. When field gets focus, the label moves up into field border, and placeholder text is briefly displayed before options cover it.

### Reproduction Link
<a href="https://codepen.io/antman888/pen/MWbQoqY?editors=1010" target="_blank">https://codepen.io/antman888/pen/MWbQoqY?editors=1010</a>

### Other comments
With v2.3.23, and below, I am able to configure input fields to always have the label in the border by specifying placeholder=" ". This is no longer possible.
I do not want any text in my empty text fields despite this being the pattern recommended by Material Design. The only time placeholder text is ok with me is when it's giving some instruction in a Select/Dropdown.

**Comment by jacekkarczmarczyk** [comment] 2021-02-26 13:31
Duplicate of https://github.com/vuetifyjs/vuetify/issues/12839

**Closed by jacekkarczmarczyk** 2021-02-26 13:31 UTC
Labels: triage
