### ISSUE TITLE
[Feature Request] Highlight selected row in VDataTable

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vuetifyjs/vuetify#17776] opened 2023-07-11 02:07 UTC
### Problem to solve
In Vuetify v2 I was using <VDataTable/> with `single-select` prop and by setting `value` prop I was able to highlight certain row without using `show-select` prop. This was used to navigate to the search result in tabular view of the app.

In Vuetify v3 I can no longer have row highlighting, even with `show-select` prop it doesn't highlight the row, see https://vuetifyjs.com/en/components/data-tables/basics/#selection

### Proposed solution
Here's a patch for v3.3.2 that works for me:

```patch
diff --git a/node_modules/vuetify/lib/components/VTable/VTable.css b/node_modules/vuetify/lib/components/VTable/VTable.css
index 09f8941..500c65d 100644
--- a/node_modules/vuetify/lib/components/VTable/VTable.css
+++ b/node_modules/vuetify/lib/components/VTable/VTable.css
@@ -20,6 +20,9 @@
 .v-table.v-table--hover > .v-table__wrapper > table > tbody > tr:hover td {
   background: rgba(var(--v-border-color), var(--v-hover-opacity));
 }
+.v-table.v-table--hover > .v-table__wrapper > table > tbody > tr.selected td {
+  background: rgba(var(--v-border-color), var(--v-selected-opacity));
+}
 .v-table.v-table--fixed-header > .v-table__wrapper > table > thead > tr > th {
   background: rgb(var(--v-theme-surface));
   box-shadow: inset 0 -1px 0 rgba(var(--v-border-color), var(--v-border-opacity));
diff --git a/node_modules/vuetify/lib/labs/VDataTable/VDataTableRow.mjs b/node_modules/vuetify/lib/labs/VDataTable/VDataTableRow.mjs
index 3bc1ce0..8e5fd09 100644
--- a/node_modules/vuetify/lib/labs/VDataTable/VDataTableRow.mjs
+++ b/node_modules/vuetify/lib/labs/VDataTable/VDataTableRow.mjs
@@ -33,7 +33,8 @@ export const VDataTableRow = defineComponent({
     } = useHeaders();
     useRender(() => _createVNode("tr", {
       "class": ['v-data-table__tr', {
-        'v-data-table__tr--clickable': !!props.onClick
+        'v-data-table__tr--clickable': !!props.onClick,
+        'selected': isSelected([props.item]),
       }],
       "onClick": props.onClick
     }, [props.item && columns.value.map((column, i) => _createVNode(VDataTableColumn, {
@@ -77,4 +78,3 @@ export const VDataTableRow = defineComponent({
     }))]));
   }
 });
-//# sourceMappingURL=VDataTableRow.mjs.map
\ No newline at end of file
diff --git a/node_modules/vuetify/lib/labs/VDataTable/composables/select.mjs b/node_modules/vuetify/lib/labs/VDataTable/composables/select.mjs
index 97e4afc..af03d3a 100644
--- a/node_modules/vuetify/lib/labs/VDataTable/composables/select.mjs
+++ b/node_modules/vuetify/lib/labs/VDataTable/composables/select.mjs
@@ -119,7 +119,7 @@ export function provideSelection(props, _ref9) {
     }
   });
   function isSelected(items) {
-    return wrapInArray(items).every(item => selected.value.has(item.value));
+    return wrapInArray(items).every(item => selected.value.has(item.raw));
   }
   function isSomeSelected(items) {
     return wrapInArray(items).some(item => selected.value.has(item.value));
@@ -170,4 +170,3 @@ export function useSelection() {
   if (!data) throw new Error('Missing selection!');
   return data;
 }
-//# sourceMappingURL=select.mjs.map
\ No newline at end of file
```

**Comment by KaelWD** [comment] 2023-11-13 16:23
Duplicate of #17670

**Closed by KaelWD** 2023-11-13 16:23 UTC
Labels: S: triage
