### ISSUE TITLE
[Bug Report][3.3.9] modelValue of the datepicker not working properly

### ISSUE THREAD

**Issue by quangquyen1410** [vuetifyjs/vuetify#17844] opened 2023-07-20 07:16 UTC
### Environment
**Vuetify Version:** 3.3.9
**Last working version:** 3.3.8
**Vue Version:** 3.3.4
**Browsers:** Edge 114.0.1823.82
**OS:** Windows 10

### Steps to reproduce
Create the Date picker with a v-model (value is an array date).
When we change the date,the modelValue will change and return a date.
When we click save button, the modelValue will change and return an array date.

### Expected Behavior
When we change the date,the modelValue will not change as the same old version or change and return an array date as when we clicked the save button.

### Actual Behavior
When we change the date,the modelValue will be change and return a date.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUktuwjAQvcrIm1IpjhftpihFVOoZusEsQjKUgH+yndAKcfeOnVZQWMAmH8/7zUsWB/bmXDn0yKasiqidqiPOpAGo2m6ARtUhvErW8rXCL9j2IXbrb96giegly0CCDrwlGndds0MPA9e2RUW0fP+oVY+ErcQ/2GgiyIWeKnHmXYXGdy5CwNi7DOu0sz7CATyuC9jXsdnAEdbeanig7A8J01gTIpwc4TWhJwb38E66k8fHhMrcyQlVwDCCZ3AYl0k6VmGp7OckzzLvSNdKjMEoEiuY6swulNtgDVWXuZI1IUg2hcWoJNkmRhemQjStISR5doMvDUZhnBYUPJU5fyqfyhfqIcS/I67qVSizWFJaSnMkw7EErmt34ToOsvPvDpKRUnq/EWFOMOF7EzuNvLU6Z3kes5wdlxg0X3m7D+hJRLLizCYFvsPq1rZkcSUtyG9Azz2aFn364e7b6IJ2vtXF6Gqz/K1T38eCZRoVnyOz5Q+HkBQF)

**Comment by KaelWD** [comment] 2023-08-09 09:26
Duplicate of #17872

**Closed by KaelWD** 2023-08-09 09:26 UTC
Labels: S: triage
