### ISSUE TITLE
[Bug Report] Combobox placeholder is cutoff Autocomplete placeholder only displays on focus when using chips in Chrome

### ISSUE THREAD

**Issue by smoothlikejazz** [vuetifyjs/vuetify#11579] opened 2020-06-08 13:22 UTC
### Environment
**Vuetify Version:** 2.2.32
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Mac OS 10.14.6

### Steps to reproduce
Define a combobox with attributes of "placeholder, multiple, chips, dense" and chips enabled

### Expected Behavior
The placeholder should display when the combobox is not in focus

### Actual Behavior
The placeholder is cutoff when the combobox is not in focus

### Reproduction Link
<a href="https://codepen.io/jasperjackson/pen/xxZGbJB" target="_blank">https://codepen.io/jasperjackson/pen/xxZGbJB</a>

### Other comments
when light debugging if I removed the  max-height: 0, then it works again.
```
 &:not(.v-input--is-focused).v-select--chips input
    max-height: 0 /* this looks like the culprit */
    padding: 0
```
https://github.com/vuetifyjs/vuetify/blob/v2.2.32/packages/vuetify/src/components/VAutocomplete/VAutocomplete.sass

**Comment by Pazza** [comment] 2020-06-09 18:18
This is the same issue as #11553

**Comment by Mert75** [comment] 2020-08-13 23:59
Duplicate of #11553 

If you have any additional questions, please reach out to us in our [Discord community.](https://community.vuetifyjs.com/)

**Closed by Mert75** 2020-08-13 23:59 UTC
Labels: triage
