### ISSUE TITLE
[Bug Report] Page scrollbar should be hidden on fullscreen dialogs

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#4156] opened 2018-05-28 12:29 UTC
### Versions and Environment
**Vuetify:** 1.1.0-beta.0
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 7

### Steps to reproduce
Create a fullscreen dialog with content that exceeds the viewport.

### Expected Behavior
Only one scrollbar should be visible (the one in the dialog), and the underlying page scrollbar should be hidden.

### Actual Behavior
Both scrollbars are visible resulting in bad UX. Also, even if the dialog content does not require scrolling, the page scrollbar is still visible which is confusing as fullscreen dialogs cover the viewport anyway.

### Reproduction Link
[https://codepen.io/anon/pen/YvKxzg](https://codepen.io/anon/pen/YvKxzg)

### Other comments
Suggested solution:
When opening a fullscreen dialog, set `overflow: hidden` on the `html` element.

**Comment by jonataswalker** [comment] 2018-05-28 12:32
Wouldn't be on the `body` element?

**Comment by sindrepm** [comment] 2018-05-28 13:55
@jonataswalker No, the CSS reset explicitly sets `overflow-y: scroll` on the `html` element.

**Comment by johnleider** [comment] 2018-05-28 23:37
I have plans for our css reset for 1.2 (didn't make it to 1.1 because I was moving). This will be included in those changes/updates.

**Comment by zaken** [comment] 2018-06-19 15:29
Same as #3101

**Comment by KaelWD** [comment] 2018-06-19 15:33
Duplicate of #3101

**Closed by KaelWD** 2018-06-19 15:33 UTC
Labels: T: bug

**Comment by jsantanders** [comment] 2018-08-04 23:38
Hi there, exist a workaround?

**Comment by basebandit** [comment] 2018-08-30 11:42
This is how you disable overflow on the html element when dialog opens.
 ```
watch: {
      dialog: function (val) {
        document.querySelector('html').style.overflow = val ? 'hidden' : null
      }
    }
```

**Comment by HamadaFMahdi** [comment] 2019-02-27 08:04
Is that meant to be '===' instead of '=' or am I missing something?
Thanks.

```
watch: {
    dialog: function (val) {
        document.querySelector('html').style.overflow === val ? 'hidden' : null
    }
}
```
