### ISSUE TITLE
[Bug Report] Adding disabled prop to dialog v-btn makes button disappear

### ISSUE THREAD

**Issue by forcryingoutloud** [vuetifyjs/vuetify#12434] opened 2020-10-17 21:02 UTC
### Environment
**Vuetify Version:** 2.3.12
**Vue Version:** 2.5.17
**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 10

### Steps to reproduce
Using the sample code for modals/dialog in the docs, add "disabled" prop to the v-btn.

### Expected Behavior
v-btn should be greyed out and disabled

### Actual Behavior
v-btn disappears

### Reproduction Link
<a href="https://codepen.io/kmstls/pen/yLJOWpe" target="_blank">https://codepen.io/kmstls/pen/yLJOWpe</a>

**Comment by jacekkarczmarczyk** [comment] 2020-10-17 21:25
Duplicate of #4482

**Closed by jacekkarczmarczyk** 2020-10-17 21:25 UTC

**Comment by reynard80** [comment] 2021-05-04 12:56
I've seen the discussion on this issue, but it's an issue for me too. I disable the `dark` prop with the negation of the `disabled` prop as a workaround, but i'd rather have it fixed, if possible.

Thanks!
