### ISSUE TITLE
[Bug Report] Datatable pagination.sync not syncing properly when adding :search props

### ISSUE THREAD

**Issue by ufhy** [vuetifyjs/vuetify#6483] opened 2019-02-13 07:45 UTC
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.5.22
**Browsers:** Opera 57.0.3098.116
**OS:** Windows 10

### Steps to reproduce
adding props :search in v-datatables 

### Expected Behavior
pagination totalItem property cant sync with :total-items v-datatable, when :search props contain string type

### Actual Behavior
pagination must be still active in total more than per page selected

### Reproduction Link
<a href="https://jsfiddle.net/ufhy01/jn3m7fov/6/" target="_blank">https://jsfiddle.net/ufhy01/jn3m7fov/6/</a>

**Comment by ufhy** [comment] 2019-02-13 08:03
are this bug or what?? please youre advice

**Comment by KaelWD** [comment] 2019-02-13 08:06
Duplicate of #3978

**Closed by KaelWD** 2019-02-13 08:06 UTC
