### ISSUE TITLE
[Bug Report][3.3.2] Examples of data tables not are working

### ISSUE THREAD

**Issue by edumaciel10** [vuetifyjs/vuetify#17507] opened 2023-05-31 22:53 UTC
### Environment
**Vuetify Version:** 3.3.2
**Vue Version:** 3.3.4
**Browsers:** Firefox 113.0
**OS:** Windows 10

### Steps to reproduce
None of these examples of documentation are working, they don't show the data table

### Expected Behavior
Show datatables into codepen

### Actual Behavior
Not are showing the data table

### Reproduction Link
[https://codepen.io/edumaciel10/pen/wvYLyQm?editors=101](https://codepen.io/edumaciel10/pen/wvYLyQm?editors=101)

**Comment by KaelWD** [comment] 2023-06-01 08:23
Duplicate of #17386

**Closed by KaelWD** 2023-06-01 08:23 UTC
Labels: S: triage
