### ISSUE TITLE
[Bug Report] v-textarea auto-grow fails to autoshrink under some conditions

### ISSUE THREAD

**Issue by biggyspender** [vuetifyjs/vuetify#7539] opened 2019-06-17 01:15 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Firefox 67.0, Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
`<v-textarea v-model="commentText" auto-grow rows="1" clearable>`

### Expected Behavior
Should shrink back to a single row in all circumstances when text is cleared

### Actual Behavior
fails to shrink after pressing clear button, if keypresses have occurred
also, after setting bound model to empty string, if we preventDefault on the keydown event, also fails to shrink

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-v-textarea-autogrow-problems-wfpg1?fontsize=14&module=%2Fsrc%2FApp.vue" target="_blank">https://codesandbox.io/s/vuetify-v-textarea-autogrow-problems-wfpg1?fontsize=14&module=%2Fsrc%2FApp.vue</a>

### Other comments
fix is calling `this.$nextTick(() => this.$refs.commentTextArea.calculateInputHeight());` when this problem manifests. See repro.

**Comment by flahol** [comment] 2019-07-01 10:49
I think you have a typo error. It is auto-grow and not autogrow
[https://vuetifyjs.com/en/components/textarea#textarea](url)

**Comment by biggyspender** [comment] 2019-07-01 16:13
> 
> 
> I think you have a typo error. It is auto-grow and not autogrow
> [https://vuetifyjs.com/en/components/textarea#textarea](url)

Thx. Updated. The repro does not contain this typo.

**Comment by jacekkarczmarczyk** [comment] 2019-07-07 09:46
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6978

**Closed by jacekkarczmarczyk** 2019-07-07 09:46 UTC
Labels: triage
