### ISSUE TITLE
[Bug Report] persistent property not working on fullscreen dialog

### ISSUE THREAD

**Issue by mozafar** [vuetifyjs/vuetify#9054] opened 2019-09-21 21:26 UTC
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 7

### Steps to reproduce
visit reproduction link and Click on the button, you see a fullscreen dialog and a snackbar, click on snackbar and you can see dialog and snackbar both disappear

### Expected Behavior
when persistent enabled on dialog it should stay open when clicking other components

### Actual Behavior
click on other elements outside of fullscreen dialog close the dialog and persistent prop doesn't work as expected

### Reproduction Link
<a href="https://codepen.io/mozafar-gholami/pen/mdbaWgv?&editable=true&editors=101#anon-signup" target="_blank">https://codepen.io/mozafar-gholami/pen/mdbaWgv?&editable=true&editors=101#anon-signup</a>

**Comment by KaelWD** [comment] 2019-09-22 10:55
Duplicate of #8697 - fullscreen implies hide-overlay

You might also want to follow #7310

**Closed by KaelWD** 2019-09-22 10:55 UTC
Labels: triage
