### ISSUE TITLE
[Feature Request] Expose a way to set activePicker in date-picker

### ISSUE THREAD

**Issue by MohawkMan** [vuetifyjs/vuetify#2818] opened 2017-12-17 17:23 UTC
### New Functionality
My specific case use would be for a birth date selector. In this case it is much more user friendly to have the picker start with the year. For none technical users it isn't always intuitive to click the header to get to the month and year selectors.

### Improvements
I am still working on finding a work around

### Bugs or Edge Cases it Helps Avoid
Not sure it avoids any bugs. this is strictly a UX request

**Comment by KaelWD** [comment] 2017-12-17 22:37
Duplicate of #2422

**Closed by KaelWD** 2017-12-17 22:37 UTC
