### ISSUE TITLE
[Bug Report] Text in avatar does not center inside of v-menu or v-list

### ISSUE THREAD

**Issue by amyngb** [vuetifyjs/vuetify#2836] opened 2017-12-19 22:13 UTC
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.5.13
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 8.1

### Steps to reproduce
In the CodePen, click on correctly functioning avatar to see malfunctioning avatar with text inside of the menu dropdown.

### Expected Behavior
The text should be centered in the avatar just like it is the activator avatar.

### Actual Behavior
The text is not centered in the avatar.

### Reproduction Link
[https://codepen.io/amyngb/pen/GyZYZZ](https://codepen.io/amyngb/pen/GyZYZZ)

**Comment by KaelWD** [comment] 2017-12-19 22:37
Duplicate of #1805

**Closed by KaelWD** 2017-12-19 22:37 UTC
