### ISSUE TITLE
[Bug Report][2.5.10] VCalendar click handler crashes on undefined TouchEvent (MacOS Safari)

### ISSUE THREAD

**Issue by gregveres** [vuetifyjs/vuetify#14360] opened 2021-11-02 14:22 UTC
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Safari
**OS:** Mac OSX

### Steps to reproduce
On Safari on a Mac, got to the codepen and click on the single event defined in the calendar. You will get an exception thrown in the console:
"ReferenceError: Can't find variable: TouchEvent'

This works fine on Chrome on all platforms and works fine on Safari on iOS. 

### Expected Behavior
I would expect the click handler to not crash on Mac Safari.

### Actual Behavior
click handler crashes on mac safari

### Reproduction Link
<a href="https://codepen.io/gregveres/pen/bGrYKbg?editors=1011" target="_blank">https://codepen.io/gregveres/pen/bGrYKbg?editors=1011</a>

### Other comments
I looked at caniuse for TouchEvent and it is not supported on MacOS.
I can't tell where the line where it actually crashes on comes from. I don't know if this is part of VCalendar, Vuetify, or Vue. 
If it is VCalendar or Vuetify, then I assume you need to check for the presence of TouchEvent before checking if the event is a TouchEvent.

**Comment by KaelWD** [comment] 2021-11-02 14:28
Duplicate of #14276

**Closed by KaelWD** 2021-11-02 14:28 UTC
Labels: S: triage

**Comment by gregveres** [comment] 2021-11-02 14:37
sorry for the dup.
