### ISSUE TITLE
[Feature Request] VDataTable emit filtered

### ISSUE THREAD

**Issue by svbeon** [vuetifyjs/vuetify#9762] opened 2019-11-22 11:48 UTC
### Problem to solve
By being able to get the array of filtered items out of the component  I don't have to duplicate the filtering code to get a separate copy of the filtered items that I can then use for, say, making an excel export of the data in the table

### Proposed solution
adding an `$emit('filtered', filtered)` to

https://github.com/vuetifyjs/vuetify/blob/130fa8e1cb08efcd6a8e7faa0d75b87301296b03/packages/vuetify/src/components/VDataTable/VDataTable.ts#L35-L53

**Comment by jacekkarczmarczyk** [comment] 2019-11-22 11:59
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8731

**Closed by jacekkarczmarczyk** 2019-11-22 11:59 UTC
Labels: triage

**Comment by svbeon** [comment] 2019-11-22 12:00
Bah sorry, Somehow I didn't find that one when I searched
