### ISSUE TITLE
[Bug Report][3.1.6] v-select inside a dialog takes several attempts to open if you need to scroll to the dialog activator button

### ISSUE THREAD

**Issue by joergd** [vuetifyjs/vuetify#16777] opened 2023-02-25 08:19 UTC
### Environment
**Vuetify Version:** 3.1.6
**Last working version:** 3.1.2
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
The vertical space in the browser needs to be small enough, so that you need to scroll to the button that activates a v-dialog box.

Inside the dialog, when you then try and open a v-select - it needs several attempts before it is finally rendered properly. It looks like it does render it - but the position and/or z-index is off so you can't see the list when it drops down, or the list is offset from the textbox.

### Expected Behavior
The dropdown list renders properly - visible and properly aligned with the textbox.

### Actual Behavior
The list is either not visible at all, or the list is offset from the textbox.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVVtv0zAU/itHeaAgNSloCKGqmwZDgwckJDbBw7IH1zltTR072Cftqqn/nWOna9LLELR9sc/l+841vntMPlRVtqgxGSYjwrLSgvAiNwCjRSqqKh7jpRTKbG58n73ZngG+Y1FLhAU6UlJoWCpT2CX4SrDUW6CZIFjZGoRDmFgnsQCy4KWzWgObmnAd10TWZFuKQYdjVKgFSC28P8+TcpW+z5MO/xfU2rZ+bPuPjrczdHiao/Kn+F0rrU9y/LGp7Sm+N6EPJzk2DTqpQCf142McgWc8F+mYtrqcpNXWMUjlVCncKk9a1aXUSs5ZVyih7RTOgVyNrcUWM6dvFRr4FM1a2sjERkeDJnygVKIhdDuxc3wNXSsC4LWxBeptKG0M4bdUBc1YJ2qyXU0HNeJK4Yod2VaahmhCpNT+g8oa4nVFt+cF8NU6LEFVvi558biC4BWBKJH6wF4eJSHVDkShKuWlMlNArVjpeWcLC6hqzylB+FSwszJSFaqoDUFNoMWY4QGpgUYoxdQIEFr9rgUv9n4wHKlHzZT7CghQsWw3jX6nbM1vqDiG0JC73hUz8GfFKNHrQ+8qcIvChvM1H1URxZ/RumljcYsPwofDT+FnnCLPXLytbMm3cOR1K7mG8CIsXjj17g9juAiT0iRwUOegeq4LUddp3rG+CkmK23GIG2eTW7U3/DDWVs7hcPInQnse/YsrbT1uJr2d8KNhHeN+UnYHnkUNTbujnY0N6u2bES7NazIadF4ZvvIjoCri8aI6qFUYK4JHcDiBNUycLaHHz1MvoORGh9l6So1NXsb0XgXYBoghkn7SoDB9lf3y1vDb9hj9NwqfJ0OIkiBj9HDPkxlR5YeDQW2q+TSTthxcsm7geLpViWlhy8uz7Cx7nQpdzUT2lpP11FVn6Mt07OzSo2PiPOl3OEhNuE/HeTZqhn+TvWtgN6KUF8EH3AO8AZPwi5s6NAW/Yvwx+ksOe7bH8tgzOcglUK9zs+byamXmfq+y0seq3j1F+P9JRoTgfh9Y1v1kJ0imjY7J/R9e4Zwd)

### Other comments
After repeated attempts, though, the list does render properly.

When your vertical browser space is sufficient, and you don't need to scroll to the dialog activation button, then the list renders fine first time.

**Comment by santiagoaloi** [comment] 2023-02-25 19:12
duplicate #16684

**Comment by joergd** [comment] 2023-02-25 20:39
It's not a duplicate. I raised both issues and they're both different to each other, requiring quite different plays to reproduce.  The first issue only needs limited vertical space. This second requires you to scroll to a dialog activator button (so in a sense limited vertical space), and the v-select has to be inside a v-dialog.  The first issue doesn't have these additional requirements. This issue has everything to do with it being inside a v-dialog - and that you need to scroll to the dialog activator button.

**Comment by WhiteSage** [comment] 2023-02-26 11:53
Note the item list is misplaced even if you reduce the number of v-select items so that the dropdown list fits in the screen.

@joergd thank you for taking the time to create this Play.

**Comment by joergd** [comment] 2023-02-26 15:18
Another way to make the case that these are separate issues, issue #16684 first occurs from v3.1.5 (3.1.4 is working), and this issue first occurs from v3.1.3 (3.1.2 is working).

**Comment by lightwalker01** [comment] 2023-03-02 17:43
@joergd I found a very-dirty-hack to temporary solve the problem.
Please check it on this [Vuetify Play](https://t.ly/9uvt), if you like...

**Comment by KaelWD** [comment] 2023-03-21 05:54
Duplicate of #16770

**Closed by KaelWD** 2023-03-21 05:54 UTC
Labels: T: bug, C: VOverlay
