### ISSUE TITLE
Adding IE11 Support Guidelines to Docs

### ISSUE THREAD

**Issue by thupi** [vuetifyjs/vuetify#463] opened 2017-04-29 00:52 UTC
### Steps to reproduce
Test raised button component in IE11 with long text content.

### Versions
Vue: 2.2.6
Vuetify: 0.11.1
OS: Windows 10
Browser: IE11

### What is expected ?
The buttons must fit the content.

### What is actually happening ?
The button has a fixed size which might be defined by the min-width.

### Solution
As far as my debugging skills reach i was able to discover that a `flex-basis: auto;` on the 'btn__content' class fixes the issue in my environment.

![vuetify-button-flexbox-issue](https://cloud.githubusercontent.com/assets/16625262/25551565/d6afac9a-2c86-11e7-8118-f697634b3af0.PNG)

**Comment by johnleider** [comment] 2017-04-29 16:12
IE10 is not supported and IE11 is hanging on by a thread. When I made this framework I didn't have intentions of supporting IE at all. I understand that this may be a hindrance for developers who cover those browsers, but there are other material frameworks that will.

I'll leave this open for discussion.

**Comment by thupi** [comment] 2017-04-30 18:04
Okay, I did not know that :-) If that is the case, it would be very nice if that would be described in the docs.

I have screened the community for material component libraries and have tested most of them such as Keen-UI and vue-material. The one i selected at the end was vuetify. 

However, most of the components works relativly well in IE11 and only need a bit tweaking in order to make it play well with IE11. 

I hope you will consider support IE11 as a large amount of our users use IE11.

If you deside not to support IE11 i could get away with overwriting some of the classes that needs small tweaks right :-) ?

**Comment by johnleider** [comment] 2017-05-01 12:39
If anyone would like to help test and work on IE it would be most appreciated, if not, I'll look at this when I can.

**Comment by mornir** [comment] 2017-05-02 11:50
Using Vuetify, I am building a small webapp for internal use in my company. Unfortunately all employees are forced to use Internet Explorer (v.11). This is the case in many companies. That is why I think it would be worth the effort to support IE11. Actually, in the current state of Vuetify and with a few polyfills (_assign_, _removeChild_, etc.), it works already quite well. I only ran into two issues:

- The issue brought up here, which can be easily fixed by specifying a minimum width.
- And the button toggle component, which has a serious display bug.

For all the other components, I didn’t encounter any major problems, even for the date picker one.

Like thupi advocates, it would be good idea to mention the supported browsers on Vuetify docs website and in the Github readme, with a warning about IE11.

However, I know that spending time supporting a crappy browser like IE11 is no fun and would be better spent improving other areas of Vuetify. Therefore, I suggest adding a page under the Guides section of the documentation that show the needed polyfills and CSS fixes to achieve basic support.

Lastly, just for information: because of missing polyfills, the docs website doesn’t work at all on IE.

**Comment by johnleider** [comment] 2017-05-02 12:13
Good points. It shall be done!

**Comment by amesas** [comment] 2017-05-04 06:35
IE11 is the most used IE version and unfortunately it will be like this for a long time.

From what I have seen IE11 should be an easy catch, it "mostly works" in all frameworks, even in Vuetify.

If suggesting https://polyfill.io/v2/docs/,  and some minor CSS fixes / additions makes Vuetify work without any probs I would vote going for it.

All our enterprise customers are using IE11 right now.

PS: https://www.netmarketshare.com/ reports 13,62% market share for IE11 right now.

**Comment by mornir** [comment] 2017-05-04 13:56
@thupi I suggest you rename this issue to something like "Adding IE11 Support Guidelines to Docs"

**Comment by thupi** [comment] 2017-05-04 18:39
@mornir You are right, that might make more sense :-)

**Comment by johnleider** [comment] 2017-05-17 03:12
After beginning testing of the new docs, I am unable to reproduce any IE11 specific issues besides an event-source polyfill for webpack. Can anyone here confirm?

**Comment by johnleider** [comment] 2017-05-17 23:04
Looking into this right now!

**Comment by jijoel** [comment] 2017-06-03 07:38
I am very much looking forward to the day that IE support is no longer needed.

In the meantime, it looks like IE 11 chokes on datatables (as they are presented in the documentation). The error given is an "unexpected start tag" (error HTML1503) on every <td> after the <template> tag. IE doesn't render them, so the table doesn't work.

The fix for this was easy, but took me a while to figure out. It would be helpful to have it documented. Instead of entering a <td> tag directly, enter a component that will be rendered by Vue:

    Vue.component('cell',{
      template: '<td><slot></slot></td>',
    });

Now, we can use <cell> instead of <td>, and the datatable works normally (including sorting, filtering, etc).

**Comment by johnleider** [comment] 2017-06-03 16:04
@jijoel Can you produce a codepen demonstrating this issue, or does it happen on the docs as well?

**Comment by mornir** [comment] 2017-06-03 18:40
Data tables in the docs work fine in my IE11 browser.

@johnleider After jijoel's issue has been dealt with, I suggest closing this issue for the following reasons:
1. The original issue brought up by thupi has been fixed in the meantime.
2. Version 0.12.0 fixed a lot of IE11 related issues and you stated that you are aiming at fully supporting IE11.  So there's no need in adding a special section for IE11 in the docs.
3. When people encounter problems with IE11, it is better that they open a new issue rather than replying to this thread.

A big thanks for supporting IE11. I was thrilled to see my app works flawlessly on this browser after I upgraded to v.0.12.0👍

**Comment by jijoel** [comment] 2017-06-03 21:13
@johnleider It happens when I copy Example #1 directly from the docs. [This codepen](https://codepen.io/jijoel/pen/BZaWPL) shows the result:

![image](https://cloud.githubusercontent.com/assets/3487641/26756974/5eea7afc-484a-11e7-85e9-194764300815.png)

[This codepen](https://codepen.io/jijoel/pen/eRYKBb) shows what happens when I use a made-up <cell> tag instead. 

![image](https://cloud.githubusercontent.com/assets/3487641/26757011/4a2131b4-484b-11e7-93c4-c5b71406fd78.png)

Please note that both of the examples rely on polyfill.io, and that I did not include another polyfill that is required for the find function to work. The latter is at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find?v=control.

Regarding closing this issue, I do agree that it's better to open a new issue than to reply to this thread. Maybe we could lock the conversation, but leave it open? Or maybe set up a separate "IE Testing" thread with comments disabled? If there hadn't been a big "Help Wanted" label on this issue, I suspect I would have just assumed it was my own thing, and not written about the workaround that I found for it.

**Comment by johnleider** [comment] 2017-06-03 21:34
The issue has to do with codepen and not Vuetify, data tables look great on IE11.

**Closed by johnleider** 2017-06-03 21:34 UTC
Labels: help wanted

**Comment by jijoel** [comment] 2017-06-03 21:43
I just realized why the datatables in the docs work fine. They're pre-compiled by Vue, so Internet Explorer just sees a complete dom. In an html file, though, where the browser can see tags before the dom is fully built, IE can't handle it.

There aren't any changes needed to vuetify, but maybe a line or two about IE support in the docs? (or, probably, people running in to this can just look up this thread. :-) )

**Comment by johnleider** [comment] 2017-06-03 21:50
You think you could pr the docs and add That?

**Comment by dbebber** [comment] 2017-12-08 01:44
I agree that we all can't wait for IE to die but folks, thats still aways off in the corporate world.  The fact this isn't pointed out on the homepage is very problematic.  I may have just wasted weeks of work.

**Comment by johnleider** [comment] 2017-12-08 02:02
That doesn't make any sense @dbebber , that caveat has nothing to do with Vuetify.

**Comment by dbebber** [comment] 2017-12-08 13:16
You are right, my apologies. Spoke without thoroughly reading everything.

**Comment by throrin19** [comment] 2017-12-18 08:45
With correct settings, vuetify is correctly functionnal with IE10+ :

- Add this polyfills :
    - element-dataset
    - babel-polyfill
- Add this babel presets :
    - es2015
- Add this babel plugins :
    - array-includes

In my case, I use the "A la demande" config with POI.js. I add this settings in the poi.config.js in the `extendWebpack` :

```javascript
config.module.rule('vuetify')
    .test(/vuetify.es5.*?js$/)
    .use('babel-loader')
    .loader('babel-loader');
```

Now it works fine on IE11. But in IE10 I have only one bug : modals and dropdown menu works fine only first time

**Comment by ktiedt** [comment] 2019-02-08 17:49
I realize this is a really old closed ticket, but I am in a role where we must support IE10 and I was curious if @throrin19 ever resolved that last issue they were seeing for IE10?
