### ISSUE TITLE
[Bug Report] Button loader overflow button

### ISSUE THREAD

**Issue by Alex-Sokolov** [vuetifyjs/vuetify#10748] opened 2020-03-05 08:55 UTC
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Windows 10

### Steps to reproduce
- Create button with loading prop
- Set loading flat to true

### Expected Behavior
Loader for x-small buttons will be smaller and not overflow button borders

### Actual Behavior
Loader for x-small buttons same size as for small and overflow button borders

### Reproduction Link
<a href="https://codepen.io/sokolov_alex/pen/rNVGzMG" target="_blank">https://codepen.io/sokolov_alex/pen/rNVGzMG</a>

![image](https://user-images.githubusercontent.com/4497128/75964447-48781e80-5ed8-11ea-868c-dca8c6aca91a.png)

**Comment by fpdrozd** [comment] 2020-03-06 11:07
Duplicate of #9870

**Closed** 2020-03-06 11:16 UTC
Labels: C: VBtn, T: bug
