### ISSUE TITLE
[Bug Report] shallowMount and mount in same test spec

### ISSUE THREAD

**Issue by snelg** [vuetifyjs/vuetify#9151] opened 2019-09-30 15:43 UTC
### Environment
**Vuetify Version:** 2.0.19
**Last working version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
demo.vue
```
<template>
  <v-btn @click="1 === 1">Dummy</v-btn>
</template>
```

demo.spec.js
```
import Vue from 'vue'
import Vuetify from 'vuetify'
import { createLocalVue, mount, shallowMount } from '@vue/test-utils'
import demo from '~/demo.vue'

Vue.use(Vuetify)

describe('demo', () => {
  test('shallow', () => {
    const shallow = shallowMount(demo, {
      localVue: createLocalVue(),
      vuetify: new Vuetify({})
    })

    expect(shallow.isVueInstance()).toBeTruthy()
  })

  test('mount', () => {
    const full = mount(demo, {
      localVue: createLocalVue(),
      vuetify: new Vuetify({})
    })

    expect(full.isVueInstance()).toBeTruthy()
  })
})
```

### Expected Behavior
Tests should not crash

### Actual Behavior
If the "mount" test runs before the "shallowMount" test, then everything works fine.
If the "shallowMount" test runs first, then the "mount" test faceplants:
```
console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
[Vue warn]: Error in callback for immediate watcher "$listeners": "TypeError: Cannot read property '$scopedSlots' of undefined"
    
    found in
    
    ---> <VBtn>
           <Anonymous>
             <Root>
 console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
    TypeError: Cannot read property '$scopedSlots' of undefined
```

### Reproduction Link
<a href="https://github.com/snelg/vuetify-jest-issue" target="_blank">https://github.com/snelg/vuetify-jest-issue</a>

### Other comments
Not a super-high priority for me, since I already have the workaround of making sure at least one test that uses "mount" runs before any tests that use "shallowMount".

**Comment by KaelWD** [comment] 2019-10-01 01:30
Duplicate of https://github.com/vuejs/vue-test-utils/issues/1130

From #8822

**Comment by KaelWD** [comment] 2019-10-25 12:08
Another workaround is to use `sync: false` in the mount options, but it hasn't helped everywhere in my experience.

**Closed by KaelWD** 2019-10-25 12:08 UTC
Labels: Framework, T: bug, T: regression, testing, upstream, wontfix
