### ISSUE TITLE
[Bug Report] When open the v-menu and then scroll the menu stays open

### ISSUE THREAD

**Issue by QTCkarolym** [vuetifyjs/vuetify#6909] opened 2019-04-03 18:15 UTC
### Versions and Environment
Vuetify: 1.5.9
Vue: 2.6.10
Browsers: Chrome 73.0.3683.75 
OS: Windows 10 Pro 17134.648

### Steps to reproduce
the container have a max-height and have  an overflow: auto but the menus inside keep moving with the scroll♥

### Expected Behavior
when scroll should toggle the menu or stay where is open♥

### Actual Behavior
![v-menu](https://user-images.githubusercontent.com/46758150/55502519-18b6fb80-5623-11e9-9970-4bb52d83f10f.gif)

### Reproduction Link
https://codepen.io/qtckarolym/pen/ROWOYy?editors=1010

**Comment by KaelWD** [comment] 2019-04-04 05:26
Duplicate of #795

**Closed by KaelWD** 2019-04-04 05:26 UTC
