### ISSUE TITLE
[Feature Request] V-Data-Table grouping behavior adjusting to behave like vuetify 2 grouping

### ISSUE THREAD

**Issue by Esgator** [vuetifyjs/vuetify#18414] opened 2023-10-06 09:49 UTC
### Problem to solve
The grouping funktion of v-data-table is currently adding a group col with a button to toggle the expand of the group. In vuetify 2 where groups automatically expanded and didn't add a col to the table.

### Proposed solution
Having a prop that can controlle that behavior would be my suggestion.

**Comment by KaelWD** [comment] 2023-10-06 09:50
Duplicate of #17863

**Closed by KaelWD** 2023-10-06 09:50 UTC
Labels: S: triage
