### ISSUE TITLE
RTL not working in lists content

### ISSUE THREAD

**Issue by MehrdadKhanzadeh** [vuetifyjs/vuetify#4780] opened 2018-08-02 18:01 UTC
### Versions and Environment
Vuetify: 1.1.9
Vue: 3.0.0-rc.4
Browsers: Chrome
OS: Windows 10

### Steps to reproduce

I set the "rtl" property of vuetify instance to "true" in "main.js", It works fine on everything but in lists, It just align avatar to right but the list tile contents are still aligned left.

### Expected Behavior

They should align right, too.

### Reproduction Link

https://vuetifyjs.com/en/components/lists#usage--1
You just have to set the vuetify rtl property to true.

### Additional Info
It's obvious that I solved it with custom style but I guess the behavior should be like what I described!

**Comment by jacekkarczmarczyk** [comment] 2018-08-02 20:41
duplicate of https://github.com/vuetifyjs/vuetify/issues/4606

**Closed by jacekkarczmarczyk** 2018-08-02 20:41 UTC
