### ISSUE TITLE
[Feature Request] Add clickable rows to data-tables

### ISSUE THREAD

**Issue by MayScat** [vuetifyjs/vuetify#7976] opened 2019-07-24 18:12 UTC
### Problem to solve
Most of my projects I tend to not put an action header and use the <tr @click=""> for clickable rows, now with 2.0 I cannot find a way to do it.

### Proposed solution
I propose that they add a clickable row option to the data table.

**Comment by jacekkarczmarczyk** [comment] 2019-07-24 18:55
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7491
Added in 2.0 <https://github.com/vuetifyjs/vuetify/pull/7578>

![image](https://user-images.githubusercontent.com/15625235/61820421-34a20f80-ae55-11e9-994b-0f76aed396d7.png)

**Closed by jacekkarczmarczyk** 2019-07-24 18:55 UTC
Labels: triage

**Comment by andersonkxiass** [comment] 2019-08-12 13:03
Some example about how to use the `click:row`?
