### ISSUE TITLE
[Feature Request] how tu disable global ripple 

### ISSUE THREAD

**Issue by lelouch-xue** [vuetifyjs/vuetify#13693] opened 2021-05-21 10:15 UTC
### Problem to solve
how tu disable global ripple 

### Proposed solution
how tu disable global ripple

**Comment by KaelWD** [comment] 2021-05-21 10:17
Duplicate of #9677

**Closed by KaelWD** 2021-05-21 10:17 UTC
Labels: triage

**Comment by miladmeidanshahi** [comment] 2024-04-22 08:07
Hi @KaelWD,
I have set the global ripple to false but not working.

```
import { type ThemeDefinition } from 'vuetify'
import type { ExternalVuetifyOptions } from 'vuetify-nuxt-module'

export default {
  icons: {
    defaultSet: 'md'
  },
  defaults: {
    global: {
      ripple: false
    },
    VBtn: {
      ripple: false
    },
    VTextField: {
      color: 'yellow-200',
      variant: 'outlined',
      bgColor: 'white',
      baseColor: 'gray-100',
    }
  }
} satisfies ExternalVuetifyOptions
```
