### ISSUE TITLE
[Feature Request] [Virtual scroller] Add support for dynamic height items

### ISSUE THREAD

**Issue by alexandre-le-borgne** [vuetifyjs/vuetify#11902] opened 2020-07-21 10:04 UTC
### Problem to solve
https://vuetifyjs.com/en/components/virtual-scrollers/#virtual-scroller

The documentation indicates that "The v-virtual-scroll component supports dynamic height " but this is not the case. The prop "itemHeight" is required.

[Vue warn]: Missing required prop: "itemHeight"
found in
---> <VVirtualScroll>

My list may contain items of different height so I cannot use this component

### Proposed solution
A working example for vue : https://github.com/Akryum/vue-virtual-scroller#dynamicscroller

**Comment by KaelWD** [comment] 2020-07-21 10:05
Duplicate of #11755

**Closed by KaelWD** 2020-07-21 10:05 UTC
Labels: triage
