### ISSUE TITLE
[Feature Request] Vuetify does not offer any functionality to rearrange rows by moving them up and down

### ISSUE THREAD

**Issue by sunteta** [vuetifyjs/vuetify#17724] opened 2023-06-30 06:44 UTC
### Problem to solve
Such a function is very much needed. For example, if the data display in the foreground is controlled in the background, the operator can move up and down through the background data table.

Is there a way to achieve it?

### Proposed solution
Such a function is very much needed. For example, if the data display in the foreground is controlled in the background, the operator can move up and down through the background data table.

Is there a way to achieve it?

**Comment by KaelWD** [comment] 2023-06-30 07:44
Duplicate of #2234

**Closed by KaelWD** 2023-06-30 07:44 UTC
Labels: S: triage
