### ISSUE TITLE
[Bug Report][2.6.4] v-text-field type number

### ISSUE THREAD

**Issue by TitoOlivares** [vuetifyjs/vuetify#15006] opened 2022-04-26 20:27 UTC
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 99.0.4844.84
**OS:** Linux x86_64

### Steps to reproduce
- Create a `v-text-field` type="number"

### Expected Behavior
Just like chrome, in Mozilla Firefox the `v-text-field` type="number" should allow entering only numbers

### Actual Behavior
In mozilla firefox, the `v-text-field` type="number" allows entering letters

### Reproduction Link
<a href="https://codepen.io/tolivaresv/pen/BaJgMbX" target="_blank">https://codepen.io/tolivaresv/pen/BaJgMbX</a>

**Comment by ElijahKotyluk** [comment] 2022-04-28 03:47
Duplicate of #9314

**Closed by ElijahKotyluk** 2022-04-28 03:47 UTC
Labels: wontfix
