### ISSUE TITLE
[Bug Report][3.3.4] Can't find stylesheet to import

### ISSUE THREAD

**Issue by logue** [vuetifyjs/vuetify#17606] opened 2023-06-14 10:50 UTC
### Environment
**Vuetify Version:** 3.3.4
**Last working version:** 3.3.3
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
When I use the SASS variables feature, I get an error that `../../styles/styles.sass` is not found.
For this project, the stylesheet settings should be the same as those pictured on the page below.
https://vuetifyjs.com/en/features/sass-variables/
Because of this, `styles.sass` is not originally in the config and does not exist.

### Expected Behavior
Loading setting.scss.

### Actual Behavior
Some component outputs bellow error.

```
[sass] Can't find stylesheet to import.
  ╷
1 │ @import '../../styles/styles.sass';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
```

### Reproduction Link
[https://codesandbox.io/p/github/logue/vite-vuetify-ts-starter/master?layout=%257B%2522sidebarPanel%2522%253A%2522PR%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clivksiz5000d356q01pnnc1z%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clivkvsa301i5356q20hk9qnv%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clivkvsa301i4356q3hrt7vxo%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clivkvsa301i5356q20hk9qnv%2522%253A%257B%2522id%2522%253A%2522clivkvsa301i5356q20hk9qnv%2522%252C%2522activeTabId%2522%253A%2522clivl9b84014v356qp6hzkv1x%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clivl9b84014v356qp6hzkv1x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5174%252C%2522id%2522%253A%2522clivlbbvp01lf356q9frz0l6i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clivkvsa301i4356q3hrt7vxo%2522%253A%257B%2522id%2522%253A%2522clivkvsa301i4356q3hrt7vxo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clivl6ov5004y356qp7fnrkud%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clivl6pol001wfvhn6reqeih6%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clivl6ov5004y356qp7fnrkud%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D](https://codesandbox.io/p/github/logue/vite-vuetify-ts-starter/master?layout=%257B%2522sidebarPanel%2522%253A%2522PR%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clivksiz5000d356q01pnnc1z%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clivkvsa301i5356q20hk9qnv%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clivkvsa301i4356q3hrt7vxo%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clivkvsa301i5356q20hk9qnv%2522%253A%257B%2522id%2522%253A%2522clivkvsa301i5356q20hk9qnv%2522%252C%2522activeTabId%2522%253A%2522clivl9b84014v356qp6hzkv1x%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clivl9b84014v356qp6hzkv1x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5174%252C%2522id%2522%253A%2522clivlbbvp01lf356q9frz0l6i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clivkvsa301i4356q3hrt7vxo%2522%253A%257B%2522id%2522%253A%2522clivkvsa301i4356q3hrt7vxo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clivl6ov5004y356qp7fnrkud%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clivl6pol001wfvhn6reqeih6%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clivl6ov5004y356qp7fnrkud%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by KaelWD** [comment] 2023-06-14 10:53
Duplicate of #17603

**Closed by KaelWD** 2023-06-14 10:53 UTC
Labels: S: triage
