### ISSUE TITLE
[Bug Report] Text hidden for multi-layer flex tag

### ISSUE THREAD

**Issue by dx0eu** [vuetifyjs/vuetify#8321] opened 2019-08-06 09:33 UTC
### Environment
**Vuetify Version:** 2.0.4
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Mozilla Firefox, Google Chrome
**OS:** Linux, Windows

### Steps to reproduce
No step

### Expected Behavior
Like version of 1.5.16, full display the text

### Actual Behavior
In 2.0.4, this code will hidden 4 text.

### Reproduction Link
<a href="https://codepen.io/anon/pen/GVyXMN?editors=1011" target="_blank">https://codepen.io/anon/pen/GVyXMN?editors=1011</a>

### Other comments
This link is vuetifyjs@1.5.16 demo:  https://codepen.io/anon/pen/aeEayr?&editable=true&editors=101
And vuetifyjs@2.0.4 demo:               https://codepen.io/anon/pen/GVyXMN?editors=1011

**Comment by KaelWD** [comment] 2019-08-06 09:41
Duplicate of #7956

**Closed by KaelWD** 2019-08-06 09:41 UTC
Labels: triage
