### ISSUE TITLE
[Bug] Slider label stuck at zero for decimal interval

### ISSUE THREAD

**Issue by valgaze** [vuetifyjs/vuetify#2232] opened 2017-10-18 17:49 UTC
### Steps to reproduce

- [ ] Create a **[slider component](https://vuetifyjs.com/components/sliders)** with decimal interval ticks and enable thumb-label

```vue
        <v-slider v-model="value1"   
            :snap="true"
            :step="0.01"
            :min="0"
            :max="1"
            :hint="value1"
            thumb-label
            >     
         </v-slider>
```
### Versions
Vue: 2.x
Vuetify: ^0.16.4
OS: Windows/Mac
Browsers: Chrome

### What is expected ?
The thumb label should display the current value 

### What is actually happening ?
With a 0 to 1 interval, the thumb nail is stuck on 0

![label](https://user-images.githubusercontent.com/1396559/31733886-c87c7d0e-b3f1-11e7-91d4-b59b4000b10a.gif)

### Reproduction Link

https://codepen.io/valgaze/pen/dVwxrE?editors=1010

### Culprit:

https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VSlider/VSlider.js#L230

```js
    genThumbLabel (h) {
      return h('v-scale-transition', {
        props: { origin: 'bottom center' }
      }, [
        h('div', {
          'class': 'slider__thumb--label__container',
          directives: [
            {
              name: 'show',
              value: this.isActive
            }
          ]
        }, [
          h('div', { 'class': ['slider__thumb--label', this.thumbColor || this.color] }, [
            h('span', {}, parseInt(this.inputValue))
          ])
        ])
      ])
    },
```

**Comment by valgaze** [comment] 2017-10-18 18:28
ex ```parseInt(0.04); // 0```

Maybe we could do a check for ```step``` to see if it's less and remove parseInt as needed, also perhaps .toFixed to avoid this problem:
![label_noparse](https://user-images.githubusercontent.com/1396559/31735512-013edd62-b3f7-11e7-93af-67c2efa36303.gif)

```js
let label;
if (this.step < 1) {
    label = parseInt(this.inputValue);
} else {
   label = this.inputValue.toFixed(3); // not a lot of room on the label
}

```

**Comment by jacekkarczmarczyk** [comment] 2017-10-19 01:26
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1914

**Closed by jacekkarczmarczyk** 2017-10-19 01:26 UTC
