### ISSUE TITLE
[Feature Request] VTab and VNavigationDrawer should be better animated for touch devices

### ISSUE THREAD

**Issue by jellehak** [vuetifyjs/vuetify#14854] opened 2022-03-21 09:02 UTC
### Problem to solve
Users will receive direct feedback that they can swipe these panels. This is also inline with the material design spec.

### Proposed solution
The VTab, VNagiationDrawer should have some (preview) swipe animation like https://css-tricks.com/the-javascript-behind-touch-friendly-sliders/
This is not blocking but could be left out by default and be activated with a prop like: `touch-animated="true"`

**Comment by KaelWD** [comment] 2022-03-21 09:03
Duplicate of #3262

**Closed by KaelWD** 2022-03-21 09:03 UTC
Labels: S: triage
