### ISSUE TITLE
[Bug Report][3.0.0-alpha.13] VDialog `max-width` not working as expected

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#14766] opened 2022-02-26 08:26 UTC
### Environment
**Vuetify Version:** 3.0.0-alpha.13
**Vue Version:** 3.2.31
**Browsers:** Chrome 98.0.4758.102
**OS:** Windows 10

### Steps to reproduce
- Open https://codepen.io/andrewspy/pen/LYOJOaO
- Set `max-width` to `600px`
- Click "toggle dialog" button

### Expected Behavior
Dialog should be centered with a `max-width` of 600px

### Actual Behavior
Dialog is shifted to the left.

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/LYOJOaO" target="_blank">https://codepen.io/andrewspy/pen/LYOJOaO</a>

### Other comments
It seems like somehow the `max-width` is set on the v-overlay instead of the dialog itself.

**Comment by KaelWD** [comment] 2022-02-26 08:27
Duplicate of #14420

**Closed** 2022-09-15 12:50 UTC
Labels: T: bug, C: VDialog
