### ISSUE TITLE
[Feature Request] Allow auto-highlighting of first result item in v-autocomplete

### ISSUE THREAD

**Issue by MisterGoodcat** [vuetifyjs/vuetify#4681] opened 2018-07-21 19:05 UTC
### What problem does this feature solve?

v-autocomplete only automatically highlights an item in the items list if the list contains only one entry. There are use cases when users don't do a generic, open search (think YouTube), but know exactly what item they want to look up. Well-trained systems (think Solr) are able to return high-quality results with a very high probability that the first item in the result list is the one the user is looking for. 

At the moment, the user needs to actively highlight the item they want using either the "arrow down" key or even the mouse. For an improved UX in particular in scenarios where lots of data needs to be entered that way, it would be a great improvement to have the first item highlighted automatically. That way, users could select the item by simply hitting enter and continue with the next search, without moving their hands to the arrow keys or mouse.

### What is your proposed solution?

* A new prop on v-autocomplete, for example "highlight-first-item"
* Extend [the already existing check](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VAutocomplete/VAutocomplete.js#L207) to consider the prop, like: `val.length === 1 || this.highlightFirstItem`

### Workaround

You can currently achieve something similar by dipping into the undocumented features of v-select by "ref"ing the v-autocomplete component. After fetching the results from the server, you can do something like:

```ts
    Vue.nextTick(() => {
        Vue.nextTick(() => {
            (this.$refs.autocomplete as any).setMenuIndex(0);
        });
    });
```

The nested "nextTick" is necessary because Vuetify does the index selection also in a "nextTick" call. This workaround is ugly, and also doesn't work when the items list is shown initially (could add another nextTick for that :)).

**Comment by KaelWD** [comment] 2018-07-22 01:06
Duplicate of #4207

**Closed by KaelWD** 2018-07-22 01:06 UTC
