### ISSUE TITLE
[Bug Report] v-radio-group does not respect readonly attribute

### ISSUE THREAD

**Issue by HemanthGowda** [vuetifyjs/vuetify#3522] opened 2018-03-09 16:48 UTC
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.13.3

### Steps to reproduce
* Create a `v-radio-group` with options.
* Add readonly attribute to `v-radio-group` and set it to `true`.
* Click on any option

### Expected Behavior
Should not be able to choose any option.

### Actual Behavior
Able to choose option.

### Reproduction Link
[https://codepen.io/HemanthGowda/pen/LdEGGa](https://codepen.io/HemanthGowda/pen/LdEGGa)

**Comment by KaelWD** [comment] 2018-03-14 08:32
Duplicate of #2050

**Closed by KaelWD** 2018-03-14 08:32 UTC
