### ISSUE TITLE
[Bug Report] click event  on checkbox works twice 

### ISSUE THREAD

**Issue by Desmond4724** [vuetifyjs/vuetify#11954] opened 2020-07-28 16:55 UTC
### Environment
**Vuetify Version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Windows 10

### Steps to reproduce
click event  on checkbox works twice 

### Expected Behavior
should work once

### Actual Behavior
click event  on checkbox works twice 

### Reproduction Link
<a href="https://codepen.io/desmond4724/pen/zYrQjBW?editors=1010" target="_blank">https://codepen.io/desmond4724/pen/zYrQjBW?editors=1010</a>

### Other comments
click event  on checkbox works twice

**Comment by KaelWD** [comment] 2020-07-29 07:40
Duplicate of #5968

**Closed by KaelWD** 2020-07-29 07:40 UTC
Labels: triage
