### ISSUE TITLE
[Bug Report] v-data-table v-data-table-header-mobile

### ISSUE THREAD

**Issue by DanielGJohnsen** [vuetifyjs/vuetify#9310] opened 2019-10-10 13:43 UTC
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Render a v-data-table with some headers on a normal screen size. Then make the screen less than 600px.

### Expected Behavior
It should respect the `disable-sort` prop.

### Actual Behavior
A sortBy dropdown will now render in the table header. If you are using internationalization the text will render with the keys.

### Reproduction Link
<a href="https://codepen.io/TheCewn/pen/WNerjbZ?editors=1010" target="_blank">https://codepen.io/TheCewn/pen/WNerjbZ?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment] 2019-11-12 04:30
Your codepen has some errors, please provide a valid reproduction

**Comment by DanielGJohnsen** [comment] 2019-11-13 07:46
@jacekkarczmarczyk valid reproduction in code pen, just make the screen mobile size

**Comment by jacekkarczmarczyk** [comment] 2019-11-13 08:06
Dropdown is disabled, I'm not sure if I understand the issue

**Comment by DanielGJohnsen** [comment] 2019-11-13 13:44
The behavior is different. On larger screen when `:disable-sort="true"` the icons for sorting is hidden.
The same behavior should be reflected on smaller screens, so it makes sense to hide the sorting on smaller screens as well.

**Comment by jacekkarczmarczyk** [comment] 2019-11-13 13:49
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8434

**Closed by jacekkarczmarczyk** 2019-11-13 13:49 UTC
Labels: C: VDataTable, needs more information, triage
