### ISSUE TITLE
[Bug Report][3.4.2] VSelect readonly is still clearable

### ISSUE THREAD

**Issue by mtdvlpr** [vuetifyjs/vuetify#18723] opened 2023-11-19 11:13 UTC
### Environment
**Vuetify Version:** 3.4.2
**Vue Version:** 3.3.8
**Browsers:** Firefox 119.0
**OS:** Windows 10

### Steps to reproduce
```
<v-select
  v-model="msg"
  :items="['selected', 'not selected']"
  readonly
  clearable
/>
```

### Expected Behavior
Readonly select should not be clearable

### Actual Behavior
The clear button is visible and works

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdkE0KwjAQha8yzCYK2oK6EKmCZ3BpXcR0lEL+SGJBSu9u0lpbXCXzZebNe7m26J3Iz9ZmzYvwgEUgZSUPdCo1QNGsubX9tS+E0YHXmtwX9dCTJBFGANCslalIHktU/lni9HCoo7iP/MqGGarYCpg2AX71bT7giFdGy/dEhCTu+F3SiPLRXP7vLpHBfJHPQsXSC1fbtDO8hmy1ssYFaOPCB3TwcEYBi//BUntcarQPEMPAMXUs2GV0u0zig1wUwm6F22yb7TGdu2yDtw86P21i)

**Comment by KaelWD** [comment] 2023-11-19 11:14
Duplicate of #16289

**Closed by KaelWD** 2023-11-19 11:14 UTC
Labels: S: triage
