### ISSUE TITLE
[Bug Report] 'primary' Color Keyword Always Uses White Text for Buttons

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#9775] opened 2019-11-23 16:34 UTC
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.45
**OS:** Windows 10

### Steps to reproduce
Open the codepen and toggle the "change theme" button. Note that the left-hand column's button text color doesn't change like those in the right-hand column.

### Expected Behavior
It should be possible to control button text color using the props provided for that purpose (`dark` and `light`) without having to resort to classes that mimic their behavior (e.g. `:class="$vuetify.theme.isDark ? white--text : custom-dark-text-keyword--text"`).

### Actual Behavior
Button text in the left-hand column is always white for both themes, even if the background color contrast is low. Button text in the right-hand column changes according to the props or theme in use.

### Reproduction Link
<a href="https://codepen.io/185driver/pen/yLLrWPX" target="_blank">https://codepen.io/185driver/pen/yLLrWPX</a>

### Other comments
This behavior may be an intentional design decision, and if so, this issue could be reclassified as a feature-request.  

It is cumbersome to create class-based solutions (using custom color names or not) to work around `dark` and `light` props functionality already so handily available in the framework. 

Pushing this workaround further would be to abandon the use of `primary`, `secondary`, etc. keyword naming in our app themes configuration altogether and use custom-keywords instead (e.g. `'p-primary'`, `'light-purple'`, etc.) but that seems a shame (and is more verbose) than using the built-in names.

My desire is that use of the `primary` color keyword in relation to button text and light/dark theme changes would mimic the behavior of the right-hand column, especially row 1 and/or row 4, which I think would be considered expected behavior under normal circumstances.

**Comment by KaelWD** [comment] 2019-11-24 00:31
Duplicate of #4921

**Closed by KaelWD** 2019-11-24 00:31 UTC
Labels: triage

**Comment by 185driver** [comment] 2019-11-24 00:44
I had seen that, @KaelWD, but I don't think it's the same issue.  In #4921, the submitter asks:

> Can you add a way to automatically set the text color of fields.

This issue is different. It's not about color automation. Rather, it's that using the predefined theme color keywords prevents the use of `light` and `dark` props and generally makes it difficult to change text color away from white. 

Maybe you're thinking instead of a solution that would resolve both issues?  I'm not sure, but either way, thanks for considering this issue.
