### ISSUE TITLE
[Bug Report] alignment issues with the card actions and card body

### ISSUE THREAD

**Issue by mattnathan** [vuetifyjs/vuetify#9829] opened 2019-11-29 11:40 UTC
see https://github.com/vuetifyjs/vuetify/issues/9829#issuecomment-559771489

### Environment
**Vuetify Version:** 2.1.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Load the pen, hover over the button to see that it's wider than it is tall (40px vs 36px)

### Expected Behavior
The button should be round

### Actual Behavior
The button is 40px by 36px

### Reproduction Link
<a href="https://codepen.io/mattnathan/pen/NWPKPZL" target="_blank">https://codepen.io/mattnathan/pen/NWPKPZL</a>

### Other comments
In Vuetify 2.1.11 the button was round but was miss-aligned. In 2.1.12 the alignment was fixed by using `min-width` instead of `width` for icon buttons. 

Unfortunately the `padding: 8px` that the `v-btn` takes pains to not add with icon (round) buttons isn't accounted for when inside a `v-card-actions` which just hard codes the padding to `8px` causing the oval button. See `VCard.sass#90`

**Comment by jacekkarczmarczyk** [comment] 2019-11-29 12:02
Looks like settings both min-width + max-width solves this issue and https://github.com/vuetifyjs/vuetify/issues/8699

**Comment by mattnathan** [comment] 2019-11-29 12:15
Assuming `max-width` will be the same as `min-width` I'd expect this to re-introduce the alignment issue with prefix/suffix icons in a cards content.

I've updated the pen to highlight any alignment issues with the card actions and card body, I can create another issue if you like.

To see the alignment issue just apply the fix (assuming `max-width: 36px` to `v-btn.v-size--default`) and see that the chevrons no longer line up.

**Comment by jacekkarczmarczyk** [comment] 2019-11-29 13:32
No need to create another issue, thanks for update

**Comment by jacekkarczmarczyk** [comment] 2019-12-31 05:40
The oval issue has been fixed with https://github.com/vuetifyjs/vuetify/commit/e02a6d1a5c5cbc91940356ffa3a20e8045da9941, but there's now an issue with alignment, so I'm changing the title and leaving this open

**Comment by johnleider** [comment] 2020-01-03 22:55
Are we talking about this?
![image](https://user-images.githubusercontent.com/9064066/71753932-cb81e780-2e49-11ea-94eb-d83996607166.png)

If so, this is not a bug.

**Comment by jacekkarczmarczyk** [comment] 2020-01-04 04:18
Yes, then I guess that the issue was with 2.1.15 where icons were (unintentionally?) aligned

**Closed by jacekkarczmarczyk** 2020-01-04 04:18 UTC
Labels: C: VBtn, needs more information

**Comment by johnleider** [comment] 2020-01-04 04:20
It they were aligned it was certainly not intentional. `v-card-actions` are only designed to meet the Card specification.
