### ISSUE TITLE
[Bug Report][3.5.2] v-date-picker - can't choose same month

### ISSUE THREAD

**Issue by cvaroregidor** [vuetifyjs/vuetify#19178] opened 2024-02-06 08:14 UTC
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.14
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
Open a date picker, try to select actual month. The component does not do anything. If you select another month it works fine.

### Expected Behavior
Should continue to day selector

### Actual Behavior
You get stuck in the month and can't continue to select day.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQWDAFqFq3IDM5Gyhso4/Kh+oEiqJqBYlATLbRh9uoVKujZKxnomdoogRimOoZKcUCAIDAMjM=)

**Comment by KaelWD** [comment] 2024-02-06 08:18
Duplicate of #19132

**Closed by KaelWD** 2024-02-06 08:18 UTC
Labels: S: triage
