### ISSUE TITLE
vue-cli webpack-advanced not working correctly

### ISSUE THREAD

**Issue by aaronjpitts** [vuetifyjs/vuetify#565] opened 2017-05-21 16:04 UTC
Hello,

Firstly in package.json it tries to install vuetify 0.12 which doesnt' exist and therefore gives an error upon NPM install. So I changed to 0.11.1 to install it.

Then when running npm run dev, I get the below console errors:

```
[Vue warn]: Unknown custom element: <v-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

[Vue warn]: Unknown custom element: <v-navigation-drawer> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

[Vue warn]:  Unknown custom element: <v-navigation-drawer> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

What is the issue? Are these supposed to be new for 0.12?

Many thanks!

**Comment by johnleider** [comment] 2017-05-21 16:36
Webpack advanced has not been officially released yet. The only currently available templates are simple, webpack and webpack-ssr.

**Comment by johnleider** [comment] 2017-05-22 00:46
This should be fixed. If not, open a ticket on the template repo.

**Closed by johnleider** 2017-05-22 00:46 UTC
Labels: question

**Comment by johnboc** [comment] 2017-06-14 12:46
I am trying to use Vuetify with Laravel. Having installed Vuetify using npm install vuetify --save-dev, everything compiles ok running npm run dev. I have taken the code from Simple HTML Quick Start to create a Vue component but the page creates multiple errors, starting with:
app.js:32671 [Vue warn]: Unknown custom element: <v-card> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
This is probably my error some where but could webpack be at fault?
Thanks

**Comment by johnleider** [comment] 2017-06-14 13:16
There is nothing from the posted error that I can use to help you, need more information.

**Comment by johnboc** [comment] 2017-06-14 13:58
This is my admin-sidebar vue component code which generates the following console warning:
[Vue warn]: Unknown custom element: <v-navigation-drawer> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

<template>
<div>
    <v-app>
        <v-navigation-drawer persistent :mini-variant="miniVariant" :clipped="clipped" v-model="drawer">
            <v-list>
                <v-list-item v-for="(item, i) in items" :key="i">
                    <v-list-tile value="true">
                        <v-list-tile-action>
                            <v-icon light v-html="item.icon"></v-icon>
                        </v-list-tile-action>
                        <v-list-tile-content>
                            <v-list-tile-title v-text="item.title"></v-list-tile-title>
                        </v-list-tile-content>
                    </v-list-tile>
                </v-list-item>
            </v-list>
        </v-navigation-drawer>
        <v-toolbar>
            <v-toolbar-side-icon @click.native.stop="drawer = !drawer"></v-toolbar-side-icon>
            <v-btn icon @click.native.stop="miniVariant = !miniVariant">
                <v-icon v-html="miniVariant ? 'chevron_right' : 'chevron_left'"></v-icon>
            </v-btn>
            <v-btn icon @click.native.stop="clipped = !clipped">
                <v-icon>web</v-icon>
            </v-btn>
            <v-btn icon @click.native.stop="fixed = !fixed">
                <v-icon>remove</v-icon>
            </v-btn>
            <v-toolbar-title v-text="title"></v-toolbar-title>
            <v-spacer></v-spacer>
            <v-btn icon @click.native.stop="rightDrawer = !rightDrawer">
                <v-icon>menu</v-icon>
            </v-btn>
        </v-toolbar>
        <main>
            <v-container fluid>
                My Content Here
            </v-container>
        </main>
        <v-navigation-drawer temporary :right="right" v-model="rightDrawer">
            <v-list>
                <v-list-item>
                    <v-list-tile @click.native="right = !right">
                        <v-list-tile-action>
                            <v-icon light>compare_arrows</v-icon>
                        </v-list-tile-action>
                        <v-list-tile-title>Switch drawer (click me)</v-list-tile-title>
                    </v-list-tile>
                </v-list-item>
            </v-list>
        </v-navigation-drawer>
        <v-footer :fixed="fixed">
            <span>&copy; 2017</span>
        </v-footer>
    </v-app>
</div>
</template>

<script>
export default {
    data: function() {
        return {
            clipped: false,
            drawer: true,
            fixed: false,
            items: [{
                icon: 'bubble_chart',
                title: 'Inspire'
            }],
            miniVariant: false,
            right: true,
            rightDrawer: false,
            title: 'Vuetify.js'
        }
    },
    mounted() {
        console.log('Component mounted.')
    }
}
</script>

**Comment by johnboc** [comment] 2017-06-14 14:02
[AdminSidebar.txt](https://github.com/vuetifyjs/vuetify/files/1074821/AdminSidebar.txt)

**Comment by johnleider** [comment] 2017-06-14 16:05
Everything in there looks correct, no issues that I can immediately see. Is there something you can provide me where I can reproduce the issue.

**Comment by johnboc** [comment] 2017-06-14 16:32
Here is the raw html file. vuetify.js is compiled into app.js via webpack
[html.txt](https://github.com/vuetifyjs/vuetify/files/1075278/html.txt)
>

**Comment by johnboc** [comment] 2017-06-14 16:48
This is the app.js file

**Comment by johnboc** [comment] 2017-06-14 16:49
Here
[app.txt](https://github.com/vuetifyjs/vuetify/files/1075308/app.txt)

**Comment by johnleider** [comment] 2017-06-14 16:56
That's not what I mean. Please provide a reproduction link where I can easily see the issue you are having. I can't debug your application.

**Comment by johnboc** [comment] 2017-06-14 17:00
Sorry I see what you mean. Have to shoot out for a few hours but will set up a url for you to see it. Many thanks.

**Comment by johnboc** [comment] 2017-06-14 22:37
I have set up my project on an nginx server and there are no problems. So it must be when the code runs under Laravel's built-in development server. Should I follow this up with Laravel? If so, sorry if I've needlessly taken up your time.

**Comment by johnleider** [comment] 2017-06-14 23:44
Laravel would/should have nothing to do with it. It just looks like you have the wrong vuetify version.

**Comment by johnboc** [comment] 2017-06-15 09:52
I'm using the latest version. The error doesn't occur when I run npm run prod but does when I run npm run dev so I'll look in to that. Thanks for your help and a great looking framework.
