### ISSUE TITLE
[Bug Report] v-btn-toggle strange behaviour

### ISSUE THREAD

**Issue by xmorell** [vuetifyjs/vuetify#3354] opened 2018-02-21 08:51 UTC
### Versions and Environment
**Vuetify:** 1.0.2
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.167
**OS:** Mac OS 10.11.6

### Steps to reproduce
Create a btn-toggle mandatory, select one of the options in the middle and then make the btn-toggle disapear with a v-if, it causes a js error ans even more, sometimes it also changes the selected option

### Expected Behavior
It should just remove the btn-toggle without causing a js error, and it shouldn't change the v-btn-toggle v-model value at any case

### Actual Behavior
It causes a js error ans even more, sometimes it also changes the selected option
select A, hide, show - C is now selected
select B, hide, show - E is now selected

### Reproduction Link
[https://codepen.io/anon/pen/gvzgGo?editors=1010](https://codepen.io/anon/pen/gvzgGo?editors=1010)

**Comment by jacekkarczmarczyk** [comment] 2018-02-21 08:53
To be more precise about "changes the selected option":
- select A, hide, show - C is now selected
- select B, hide, show - E is now selected

**Comment by KaelWD** [comment] 2018-02-21 08:56
Duplicate of #3136

**Comment by KaelWD** [comment] 2018-02-21 09:06
The v-model change is something to check with #3259 though.

**Comment by KaelWD** [comment] 2018-03-07 13:13
#3136 was fixed with #3259, the model changing part of this issue still exists though.

**Closed** 2018-03-07 13:14 UTC
Labels: bug
