### ISSUE TITLE
[Bug Report][2.6.12] Custom control in Carousel. When in slide 0, the button back does nothing.

### ISSUE THREAD

**Issue by Stefanosapk** [vuetifyjs/vuetify#15984] opened 2022-10-27 17:21 UTC
### Environment
**Vuetify Version:** 2.6.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Stay at slide 0 and try to go back, does nothing.

### Expected Behavior
Being at 0 slide and clicking to go back I expect to go to the last slide.

### Actual Behavior
Being in 0 slide, back slide keeps me in the 0 slide

### Reproduction Link
[https://codepen.io/lastm4n/pen/KKepPqB?editors=1111](https://codepen.io/lastm4n/pen/KKepPqB?editors=1111)

**Comment by Z3rio** [comment] 2022-11-02 13:08
This wouldnt be something caused by Vuetify, nor something that can be fixed within Vuetify.
The reason this happens is because the minus removes 1 from the model every time it gets clicked.
So when it is on 0 and gets clicked, it tries to set it to -1, but gets set back to 0 by the carousel because -1 doesnt exist as an item.

Therefore I would recommend using an method to handle the click instead,

Here is an edited version of your codepen, which works. I hope you can take inspiration for it and fix this issue.
https://codepen.io/Zer1o/pen/ZERWWrv?editors=1111

**Comment by Stefanosapk** [comment] 2022-11-02 20:19
Since Vuetify gives you the option to custom control the carousel behaviour, I think they can find a way and should solve it. Right now there is a bug in their component.

**Comment by Z3rio** [comment] 2022-11-02 20:22
No, Vuetify cannot change the functionality of Javascript mate.

**Comment by jacekkarczmarczyk** [comment] 2022-11-02 20:23
When you move from slide 4 (counting from 0) to the next one you one up with slide 5 which does not exists as well, however slide 0 is being displayed instead. Same might be done with slide -1

**Comment by Z3rio** [comment] 2022-11-02 20:24
> When you move from slide 4 (counting from 0) to the next one you one up with slide 5 which does not exists as well, however slide 0 is being displayed instead. Same might be done with slide -1

Yeah I guess I could take a look at this, but until it gets fixed, I would recommend everyone to just use the logic I linked, or something close to it.

**Comment by KaelWD** [comment] 2022-11-03 09:55
The current behaviour is from item-group's `mandatory`, if the model value is not a valid item it selects the first one instead.

**Closed** 2023-09-20 19:44 UTC
Labels: S: triage
