### ISSUE TITLE
[Bug Report] Mobile: Back button does not respect in page modal dialogue.

### ISSUE THREAD

**Issue by gedw99** [vuetifyjs/vuetify#4574] opened 2018-07-11 07:04 UTC
### Versions and Environment
**Vuetify:** 1.1.0-rc.3
**Vue:** 2.5.17-beta.0
**Browsers:** Chrome 67.0.3396.87
**OS:** Android 8.1.0

### Steps to reproduce
Go here:

https://vuetifyjs.com/en/components/dialogs

1. Click the " click me " red button
2. The dialog opens.
3. Now click the mobile back button.

The dialog should close on mobile, rather than doing a full page reload of whatever is in the history.

Btw this is exactly the tactic Google uses to make their web mobile products better. It's a huge cognitive difference for the user experience. I really implore you to consider this.

### Expected Behavior
The dialog should close without a page navigation backwards.

### Actual Behavior
It navigates backwards.

### Reproduction Link
[https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VDialog/VDialog.js](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VDialog/VDialog.js)

### Other comments
I would make a global rule for controlling this that can be customised. This is because there are so many devices these days and embedding options.

For example if using this for an electron desktop you might not want this functionality.

**Comment by KaelWD** [comment] 2018-07-11 07:34
Duplicate of #1793

**Closed by KaelWD** 2018-07-11 07:34 UTC
