### ISSUE TITLE
[Bug Report] Icon :color property not reactive on fa-icons

### ISSUE THREAD

**Issue by delueg** [vuetifyjs/vuetify#5867] opened 2018-12-11 16:40 UTC
### Versions and Environment
**Vuetify:** 1.3.13
**Vue:** 2.5.20
**Browsers:** Chrome 70.0.3538.110
**OS:** Mac OS 10.13.6

### Steps to reproduce
just use fa-icons and change color on runtime

### Expected Behavior
change color

### Actual Behavior
doesn't change color

### Reproduction Link
<a href="https://codepen.io/delueg/pen/xmGEyr" target="_blank">https://codepen.io/delueg/pen/xmGEyr</a>

**Comment by johnleider** [comment] 2018-12-11 16:42
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3505

**Closed by johnleider** 2018-12-11 16:42 UTC
