### ISSUE TITLE
[Bug Report] Double clear icon in clearable text field

### ISSUE THREAD

**Issue by Iworb** [vuetifyjs/vuetify#4083] opened 2018-05-17 07:41 UTC
Just a small issue in `1.1.0-alpha.4` version.
Here's codepen exmaple, just input some text and you will realize what I mean.
https://codepen.io/anon/pen/GdYLzo

**Comment by KaelWD** [comment] 2018-05-17 07:47
Duplicate of #4063

**Closed by KaelWD** 2018-05-17 07:47 UTC
