### ISSUE TITLE
[Bug Report][2.5.8] Top snackbar without app prop is not placed correctly

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#14202] opened 2021-09-27 09:22 UTC
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 93.0.4577.82
**OS:** Windows 10

### Steps to reproduce
According to the docs, snackbar with `app` prop should not overlap with `v-app-bar`.

https://vuetifyjs.com/en/api/v-snackbar/#props-app
![image](https://user-images.githubusercontent.com/17653648/134880622-1d3d18f2-734f-4c13-b781-b853da77f0e9.png)

However, I want this overlapping behavior, so I did not add `app` prop. But as you can see in my example, snackbar WITHOUT `app` prop does NOT overlap with `v-app-bar`.

### Expected Behavior
Snackbar should overlap with the `v-app-bar`.

### Actual Behavior
Snackbar does not overlap with the `v-app-bar` although the `app` prop is not present.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/bGRQKBG" target="_blank">https://codepen.io/mikilll94/pen/bGRQKBG</a>

**Comment by KaelWD** [comment] 2021-09-29 14:07
Duplicate of #11758

**Closed by KaelWD** 2021-09-29 14:07 UTC
Labels: S: triage
