### ISSUE TITLE
[Bug Report] Data-* attribute on v-container, v-layout, v-flex rendered incorrectly (as a class, not as a data-* attribute)

### ISSUE THREAD

**Issue by adi-zz** [vuetifyjs/vuetify#3673] opened 2018-03-26 10:41 UTC
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 7

### Steps to reproduce
`<v-container data-container="data attribute for container">`

### Expected Behavior
`<div data-container="data attribute for container">`

### Actual Behavior
`<div class="container data-container">`

### Reproduction Link
[https://codepen.io/adi-zz/pen/xWXJQw](https://codepen.io/adi-zz/pen/xWXJQw)

**Comment by KaelWD** [comment] 2018-03-26 12:02
Duplicate of #3404

**Closed by KaelWD** 2018-03-26 12:02 UTC
