### ISSUE TITLE
[Feature Request] VTextarea row counter

### ISSUE THREAD

**Issue by Shinigami92** [vuetifyjs/vuetify#9658] opened 2019-11-11 14:51 UTC
### Problem to solve
We have a textarea in our project that we applied a custom row/line counter instead of a character counter

So it counts every `\n` instead of any character

### Proposed solution
Maybe that could be solved with https://github.com/vuetifyjs/vuetify/issues/9548

**Comment by jacekkarczmarczyk** [comment] 2019-11-11 14:53
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8788 and https://github.com/vuetifyjs/vuetify/issues/9548

**Closed by jacekkarczmarczyk** 2019-11-11 14:53 UTC
Labels: triage

**Comment by Shinigami92** [comment] 2019-11-11 15:06
Want to mention that it is not a duplicate of #8788!
