### ISSUE TITLE
[Documentation] Autocomplete advanced slots example

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#9425] opened 2019-10-21 12:59 UTC
### Environment

**Browsers:** Firefox 69.0
**OS:** Windows 10

### Steps to reproduce
1. Type something into the autocomplete
2. It will not show any data

### Expected Behavior
Show data

### Actual Behavior
Does nothing

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/autocompletes#autocompletes" target="_blank">https://vuetifyjs.com/en/components/autocompletes#autocompletes</a>

### Other comments
The coinmarketcap api seems to not allow CORS requests anymore.

**Comment by yooneskh** [comment] 2019-10-22 06:51
It works for me

**Comment by KaelWD** [comment] 2019-10-22 07:34
Duplicate of https://github.com/easylist/easylist/issues/3040

**Closed by KaelWD** 2019-10-22 07:34 UTC
Labels: T: documentation

**Comment by AuspeXeu** [comment] 2019-10-22 12:31
I understand this is a duplicate. But the problem did not get resolved in the referenced issue?! I.e. the example in the documentation still does not work.

**Comment by MajesticPotatoe** [comment] 2019-10-22 12:35
@AuspeXeu 
> Coin price chart doesn't load when using AdBlock.

The example does work, best guess would be that you have some sort of adblock on which is what the linked issue is referencing 

<img width="611" alt="222" src="https://user-images.githubusercontent.com/27827979/67286153-e083e700-f4a6-11e9-8ef9-52a1cf042071.png">

**Comment by AuspeXeu** [comment] 2019-10-22 12:44
@MajesticPotatoe thanks for the clarification ... would assume I am not the only one using it though, right?
