### ISSUE TITLE
[Bug Report][3.7.2] VBtn has no Click event

### ISSUE THREAD

**Issue by ilyfairy** [vuetifyjs/vuetify#20514] opened 2024-09-25 05:27 UTC
### Environment
**Vuetify Version:** 3.7.2
**Vue Version:** 3.5.8
**Browsers:** Edge 129.0.0.0
**OS:** Windows 10, Windows

### Steps to reproduce
The `click` event is triggered, but there is no IntelliSense, and the `onClick` member object cannot be accessed in the JavaScript code.
![image](https://github.com/user-attachments/assets/fc7882c8-1fb2-4f78-8af2-ea4ac0917a34)

### Expected Behavior
require Click event

### Actual Behavior
VBtn has no Click event

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1UE1rAyEQ/SuDlyTQxnuzLv2g155KL90eFpkUW1dFZ7cJy/73OsZACOQizjzfh+9zFilq+RTCdhpRPIiGcAi2J2w7B9BM930I5VoG7R31xmGsq7z8eCYHj9oa/as64UZrO9G+Y6JGMnTmymsyb07ajbzwzGPS0QSChDQGsL37zrqUsirTzBB8JJih+C6wj36AVc5OZn+U2mfYoaO02rEWgEWCEu51ymtQ4PCvcNebrXcvjOxASnjzUEcI0QeMdGR6Rm7kOdRA+QV7/KQDf5pDqVpK1VPzegOqhXlZ2trJtSNyNi7iZJV1xXLHVZbj6x9iwYzr)

**Comment by KaelWD** [comment] 2024-09-25 05:52
Duplicate of #20411

**Closed by KaelWD** 2024-09-25 05:52 UTC
Labels: S: triage
