### ISSUE TITLE
[Bug Report] FontAwesome SVG icons not updating within v-data-table

### ISSUE THREAD

**Issue by lyonsbp** [vuetifyjs/vuetify#6281] opened 2019-01-28 21:32 UTC
### Versions and Environment
**Vuetify:** 1.5.0-beta.2
**Vue:** 2.5.20
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.2

### Steps to reproduce
View data table. 
1. Navigate to next page, notice how icons do not update for any of the rows.
2. Go back to first page.
3. Change items per page from 5 to 10
4. Notice icons for rows 6 and 7 have changed.

### Expected Behavior
Icons will change when navigating v-data-table pages.

### Actual Behavior
Icons do no change, they hold they initial value from the first render.

### Reproduction Link
<a href="https://codesandbox.io/s/xv26l7y3yz" target="_blank">https://codesandbox.io/s/xv26l7y3yz</a>

**Comment by KaelWD** [comment] 2019-01-29 01:50
Duplicate of #3505

**Closed by KaelWD** 2019-01-29 01:50 UTC
