### ISSUE TITLE
[Bug Report] Filtering in Multiple v-select fails

### ISSUE THREAD

**Issue by Geowan** [vuetifyjs/vuetify#6560] opened 2019-02-21 04:42 UTC
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.5.20
**Browsers:** Chrome 70.0.3538.77
**OS:** Linux x86_64

### Steps to reproduce
Select the first v-select then select the next.
 When a  -select is selected the item-text is removed from the selected  

### Expected Behavior
Am trying to ensure that an item is not selected twice hence the need to filter and only display the items not selected for selection in the next v-select

So i expect this not to remove the item-text when an item is selected and removed from the array so that its displayed 

### Actual Behavior
The labels are removed when an item is selected but the value is maintained

### Reproduction Link
<a href="https://codepen.io/geowan/pen/WPWqgb" target="_blank">https://codepen.io/geowan/pen/WPWqgb</a>

**Comment by KaelWD** [comment] 2019-02-21 05:44
Duplicate of #4000

**Closed by KaelWD** 2019-02-21 05:44 UTC
