### ISSUE TITLE
[Bug Report] dev script broken

### ISSUE THREAD

**Issue by byezy** [vuetifyjs/vuetify#13419] opened 2021-04-13 03:29 UTC
### Environment
**Vuetify Version:** 3.0.0-alpha.0
**Vue Version:** 3.0.11
**Browsers:** Chrome 89.0.4389.114
**OS:** Linux x86_64

### Steps to reproduce
The reproduction link is a dummy. Having followed the latest steps in https://next.vuetifyjs.com/en/getting-started/installation/#vite
I can run the build and serve scripts (yarn) but the dev script fails like this:
> yarn dev
yarn run v1.22.10
warning package.json: No license field
$ vite
Pre-bundling dependencies:
  vue
  vuetify
(this will be run only when your dependencies or config have changed)
 > node_modules/vuetify/lib/components/VIcon/VIcon.mjs:11:48: error: Could not resolve "../../util"
    11 │ import { convertToUnit, flattenFragments } from "../../util";
       ╵                                                 ~~~~~~~~~~~~

 > node_modules/vuetify/lib/components/VImg/VImg.mjs:13:32: error: Could not resolve "../../util"
    13 │ import { maybeTransition } from "../../util"; // not intended for public use, this is passed in by vuet...
       ╵                                 ~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 2 errors:
node_modules/vuetify/lib/components/VIcon/VIcon.mjs:11:48: error: Could not resolve "../../util"
node_modules/vuetify/lib/components/VImg/VImg.mjs:13:32: error: Could not resolve "../../util"
... stack details
Environment Info:

  System:
    OS: Linux 5.11 openSUSE Tumbleweed 20210408
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Node: 15.12.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
  npmPackages:
    @vitejs/plugin-vue: ^1.2.1 => 1.2.1 
    @vue/compiler-core:  3.0.11 
    @vue/compiler-dom:  3.0.11 
    @vue/compiler-sfc: ^3.0.5 => 3.0.11 
    @vue/compiler-ssr:  3.0.11 
    @vue/reactivity:  3.0.11 
    @vue/runtime-core:  3.0.11 
    @vue/runtime-dom:  3.0.11 
    @vue/shared:  3.0.11 
    vue: ^3.0.5 => 3.0.11 
    vue-cli-plugin-vuetify: ~2.3.1 => 2.3.1 
    vuetify: ^3.0.0-alpha.0 => 3.0.0-alpha.2 
  npmGlobalPackages:
    @vue/cli: Not Found

### Expected Behavior
Run in dev mode

### Actual Behavior
Fails

### Reproduction Link
<a href="https://codepen.io/byezy/pen/GRrxWMo" target="_blank">https://codepen.io/byezy/pen/GRrxWMo</a>

### Other comments
Good job, getting there guys!

**Comment by KaelWD** [comment] 2021-04-13 04:30
Duplicate of #13362

**Closed by KaelWD** 2021-04-13 04:30 UTC
Labels: triage
