### ISSUE TITLE
[Bug Report] v-tooltip does not work correctly when used inside v-navigation-drawer

### ISSUE THREAD

**Issue by HayGT** [vuetifyjs/vuetify#8304] opened 2019-08-05 14:24 UTC
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
Open the drawer with the first button and see what v-tooltip is displayed correctly.

Now if you scroll down a bit and open the drawer through the second button, you will see that the v-tooltip has flown off.

### Expected Behavior
v-tooltip should be displayed in the position where the button is located, regardless of whether the page is scrolled or not.

### Actual Behavior
v-tooltip is displayed in the place where it was rendered when the page was loaded, that is, at the very top.

### Reproduction Link
<a href="https://codepen.io/anon/pen/LwOvEP" target="_blank">https://codepen.io/anon/pen/LwOvEP</a>

### Other comments
When moving the page, all items remain static in the drawer, except the hint, I don't know, maybe I forgot to connect some prop, or don't use the grid correctly?

**Comment by jacekkarczmarczyk** [comment] 2019-08-05 14:30
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8191

**Closed by jacekkarczmarczyk** 2019-08-05 14:30 UTC
Labels: triage
