### ISSUE TITLE
[Documentation] v-list-item-group doesn't exist even though it is referred to in the documentation

### ISSUE THREAD

**Issue by douira** [vuetifyjs/vuetify#16160] opened 2022-11-24 17:32 UTC
### Environment

**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Look at the documentation page

### Expected Behavior
The examples should work, or the page should not exist and a replacement for the features this component provides should be given.

### Actual Behavior
The examples are broken and testing them in codepen results in the error message that the component can't be found.

### Reproduction Link
[https://next.vuetifyjs.com/en/components/list-item-groups/](https://next.vuetifyjs.com/en/components/list-item-groups/)

### Other comments
The page is also linked to from at least one other page and there may be more https://next.vuetifyjs.com/en/api/v-list-group/

**Comment by jacekkarczmarczyk** [comment] 2022-11-24 17:38
Duplicate of https://github.com/vuetifyjs/vuetify/issues/15981

**Closed by jacekkarczmarczyk** 2022-11-24 17:38 UTC
Labels: S: triage
