### ISSUE TITLE
[Bug Report][3.3.15] VRating doesn't change icon size when using a numeric value for size prop

### ISSUE THREAD

**Issue by oemer-aran** [vuetifyjs/vuetify#18232] opened 2023-09-08 07:46 UTC
### Environment
**Vuetify Version:** 3.3.15
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add a size prop using a numeric value to `v-rating`: `<v-rating model-value="3" size="72"` />`

### Expected Behavior
Icon size changes to 72

### Actual Behavior
Icon size remains 24px (default) and only the space around the icon is bigger.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVM1O4zAQfpWR97CXOtHSXSFVXcRqH2GPhIMbO12D/2Q7oVDl3ZlxKIQiQdVL5Iy/n/nsSW727E8I1dArtmLrrGwwIqurxgGspR6gNSKl3w2TvDNqB/TgrTe9dSCM3jreKpdVbFihIGngUWTttmC9VIYPwvQK+cuGQdJPtNzxZIUxSFnXBzSyT+afxz7TzIi4VWezd/wzPp7v1T8Egu/g8gKkV8l9zyC6TrUZdOtd0VnXBDzZ8/LiE7u/fYx4YfDg472IvncS+kRyGq8ekvGZmjlwz3Ge0Ig/zBJ8I23cDtGHNEMUzdeUL3z03mgnZ3DY76Gsq4IdR6BwtH7zqt8NLhVm8el1yvEOxxbMaHefqrvkHQ7/npANaxOaruBmEmrY/5xDWtV1Kx0iMbkeYuVUrl2wNX42WXeP18tqWf34hS4pH2p485tUFTWSum3ciI7aBh8ztyIc2U4bxbpUqIZK9P5FD9cIq2PvsraKS29LMz+nXmblSiXLN9E/JBVRpGGLmQ01fILVl3HR44N2jYaDihznTqpIv4rTIh3R5rGOtj5EI/eRDnxcsELDk596ZrfPXkWkZw==)

### Other comments
In the reproduction link, I also added an example workaround using the `item` slot of `v-rating` for a potential fix:

```tsx
    <v-rating model-value="3" size="72">
      <template #item="props">
        <v-icon size="72" v-bind="props"> {{ props.icon }} </v-icon>
      </template>
    </v-rating>
```

**Comment by KaelWD** [comment] 2023-09-08 07:50
Duplicate of #16288

**Closed by KaelWD** 2023-09-08 07:50 UTC
Labels: S: triage
