### ISSUE TITLE
[Bug Report][2.5.5] Wrong disabled style for v-btn on Safari 

### ISSUE THREAD

**Issue by jeroendewilde** [vuetifyjs/vuetify#13839] opened 2021-06-24 13:32 UTC
### Environment
**Vuetify Version:** 2.5.5
**Vue Version:** 2.6.14
**Browsers:** Safari
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Install the latest version of Safari for Mac (14.1.1)
2. Toggle the "Disable buttons" checkbox in the Codepen example

Watch the style of the `<v-btn>`. The text button remains greyed out, even if the `disabled` prop is set to false.

### Expected Behavior
Show the correct styles

### Actual Behavior
Incorrect styles

### Reproduction Link
<a href="https://codepen.io/4411jdw/pen/dyvxYoZ" target="_blank">https://codepen.io/4411jdw/pen/dyvxYoZ</a>

**Comment by jacekkarczmarczyk** [comment] 2021-06-24 13:33
Duplicate of https://github.com/vuetifyjs/vuetify/issues/13599

**Closed by jacekkarczmarczyk** 2021-06-24 13:33 UTC
Labels: triage
