### ISSUE TITLE
[Bug Report] v-combobox item-value property does not work like v-autocomplete

### ISSUE THREAD

**Issue by sevillaarvin** [vuetifyjs/vuetify#8965] opened 2019-09-15 05:10 UTC
### Environment
**Vuetify Version:** 2.0.15
**Vue Version:** 2.5.17
**Browsers:** Firefox 69.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Create a v-autocomplete
2. Create a v-combobox
3. Create a data property called item which is an object
4. Create a simple array of any entity, .e.g, players, to be bound on v-autocomplete, with properties id and name for the item-value and item-text, respectively
5. Create another simple array of any entity, e.g., channels, to be bound to v-combobox, with properties id and name for the item-value and item-text, respectively
6. v-model the v-autocomplete to item.player_id
7. v-model the v-combobox to item.channel_id
8. Select an option in v-autocomplete and in v-combobox
9. Note that v-autocomplete binds the item-value (id) but v-combobox ignores the item-value and binds the entire object instead.

### Expected Behavior
v-combobox item-value property should work the same as v-autocomplete

### Actual Behavior
v-combobox binds to v-model the entire object instead of the property specified in item-value

### Reproduction Link
<a href="https://codepen.io/sevillaarvin/pen/ZEzjeao" target="_blank">https://codepen.io/sevillaarvin/pen/ZEzjeao</a>

**Comment by KaelWD** [comment] 2019-09-15 10:30
Duplicate of #5479

**Closed by KaelWD** 2019-09-15 10:30 UTC
Labels: triage

**Comment by pjabang1** [comment] 2020-09-24 11:42
:return-object="false" - Changes the selection behavior to return the object directly rather than the value specified with item-value
