### ISSUE TITLE
[Bug Report] V-select not rendered correctly and menu list not clickable if  items object has key header

### ISSUE THREAD

**Issue by denmasyarikin** [vuetifyjs/vuetify#9344] opened 2019-10-13 16:37 UTC
### Environment
**Vuetify Version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Linux x86_64

### Steps to reproduce
create items with array of object
each object has key `header`

### Expected Behavior
1. display text list item of select as usual, it can be props `item-text` or key `text` by defulat
2. selection items can be selected

### Actual Behavior
1. display text use value of header key
2. selection item can not be selected

### Reproduction Link
<a href="https://codepen.io/denmasyarikin/pen/GRRoYqx" target="_blank">https://codepen.io/denmasyarikin/pen/GRRoYqx</a>

**Comment by KaelWD** [comment] 2019-10-14 05:51
Duplicate of #4148

**Closed by KaelWD** 2019-10-14 05:51 UTC
Labels: triage
