### ISSUE TITLE
[Bug Report] Property 'username' does not exist on type 'Vue | Element | Vue[] | Element[]' - TypeScript

### ISSUE THREAD

**Issue by rostgoat** [vuetifyjs/vuetify#10760] opened 2020-03-06 10:18 UTC
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Linux x86_64

### Steps to reproduce
Trying to focus cursor on input box but get the following error:

```
Property 'username' does not exist on type 'Vue | Element | Vue[] | Element[]'
```

Here is the code

```
this.$nextTick(() => {
        this.$refs.loginForm.username.focus();
      });
```

I'm guessing it needs to be something like

```
  (this.$refs.loginForm.username as SomeType?).focus();
```

except I am not quite sure if this is the correct approach

### Expected Behavior
username field should focus on mount

### Actual Behavior
Error as described in the issue

### Reproduction Link
<a href="https://codepen.io/totto357/pen/djaVLw?editors=1010" target="_blank">https://codepen.io/totto357/pen/djaVLw?editors=1010</a>

**Comment by KaelWD** [comment] 2020-03-06 10:19
Duplicate of #5962

**Closed by KaelWD** 2020-03-06 10:19 UTC
Labels: triage
