### ISSUE TITLE
[Feature Request] Import custom vuetify types

### ISSUE THREAD

**Issue by abdullah10182** [vuetifyjs/vuetify#18173] opened 2023-08-29 18:30 UTC
Question:
Is there a way to import type definitions for eg. "Density", "Variants", "IconValue" and other Vuetify types.

Wondering how to do this, to create custom components with props with these types.
Is this possible?

### Proposed solution
```
import { Density } from 'vuetify/types'

const props = defineProps({
  densifty: {
    type: Density,
    required: true
  },
});
```

**Comment by KaelWD** [comment] 2023-09-06 11:42
Duplicate of #16680

**Closed by KaelWD** 2023-09-06 11:42 UTC
Labels: S: triage
