### ISSUE TITLE
[Bug Report] Combobox v-model does not update when focus is active and button outside is clicked

### ISSUE THREAD

**Issue by K0M15** [vuetifyjs/vuetify#10825] opened 2020-03-13 07:02 UTC
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
* Create v-combobox with v-model.
* Create v-btn with @click => log combobox v-model

### Expected Behavior
When clicked on button after entering text (without selection) and focus is still on v-combobox, v-combobox content is logged.

### Actual Behavior
Last entry is logged.

### Reproduction Link
<a href="https://codepen.io/K0M15CH/pen/abOYpGg?editors=1011" target="_blank">https://codepen.io/K0M15CH/pen/abOYpGg?editors=1011</a>

### Other comments
I tried 
```javascript
    Vue.nextTick().then(/*logcontent*/)
```
but same behaviour was observed.
This behavior was not observed, when `<v-combobox>` is exchanged with `<input type="text>`, so no Vuejs problem

**Comment by KaelWD** [comment] 2020-03-13 07:06
Duplicate of #4679

You should use `setTimeout`

**Closed by KaelWD** 2020-03-13 07:06 UTC
Labels: triage
