### ISSUE TITLE
[Feature Request] Adding Stylus 

### ISSUE THREAD

**Issue by jahangirahmad** [vuetifyjs/vuetify#10271] opened 2020-01-18 16:39 UTC
### Problem to solve
I had some problem with node-sass in some scenario.

### Proposed solution
could you please add stylus-lang too?

**Comment by KaelWD** [comment] 2020-01-19 04:09
Duplicate of #5558

> I had some problem with node-sass

It helps if you say what the problem actually is, but it's probably because you shouldn't be using node-sass: #7323

**Closed by KaelWD** 2020-01-19 04:09 UTC
Labels: triage
