### ISSUE TITLE
[Bug Report] Your Vuetify examples are broken on Codepen

### ISSUE THREAD

**Issue by inkexit** [vuetifyjs/vuetify#8893] opened 2019-09-07 20:58 UTC
### Environment
**Vuetify Version:** 2.0.15
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Open the https://codepen.io/johnjleider/pen/zgxeLQ in Firefox or Chrome.

### Expected Behavior
Expected to work like this: https://vuetifyjs.com/en/examples/layouts/baseline

### Actual Behavior
Menu button is broken, not visible until rollover.  "Source" and "Codepen" buttons as well, not visible until rollover. "Source" and "Codepen" buttons are also not centered horizontal, but are all the way to the left.

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/zgxeLQ" target="_blank">https://codepen.io/johnjleider/pen/zgxeLQ</a>

### Other comments
A lot of the other layouts and UI Components are broken as well.  I copied the code from codepen and tried it in VS Code -- same results.  I was really looking to using Vuetify, however until this bugginess is fixed I can't have any faith in your product.  Please feel free to email forstyjack@gmx.com with any more questions.

**Comment by MajesticPotatoe** [comment] 2019-09-07 21:06
Duplicate of #8032

**Closed by MajesticPotatoe** 2019-09-07 21:06 UTC
Labels: triage
