### ISSUE TITLE
[Bug Report][3.3.6] v-Textfield does only fire click events when clicking the centralmost part

### ISSUE THREAD

**Issue by drhouse82** [vuetifyjs/vuetify#17991] opened 2023-08-08 10:38 UTC
### Environment
**Vuetify Version:** 3.3.6
**Last working version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Firefox 116.0
**OS:** Windows 10

### Steps to reproduce
Click inside the red rectangle, you get a click event.
Click outside the red rectangle (but inside the vuetify input), you get no click event.

### Expected Behavior
click events fired no matter where you click the text field

### Actual Behavior
click events only fired when clicking the central part

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNU81uozAQfpVZX5JIAbrqag8kjbLPUaqVgyeNG2Mse6CJIt69gyEpSg/tARnm5/sZD88X8c+5tG1Q5GJNWDkjCTeFBVgr3UJpZAhPhSA8UVKiJfSFiGkuaJMY3ms0aggBGLlDExsCFeIabZOqVjHeStPgZ2JbGl0ex/r/dUOumbQFOhvk5LtWdMjh98ODO61A6cAqzzloa7TFZGfq8riCFj3pUppEGv1qc6i0UuZGtVlnU7mDw4wt8ts6mxjnz1B67SiW4MnVnkDhXjaG4DKAKUkyh/kCnjYwv0D0lMMsnjPoFsuhrEI61Crk1zaAicsc9o0tSde2B7pVAEjDRuazc93AQbbIV8ATQsVos8W1qhsZhrPrLdxE9wb6uUX92jLVFX1Xe4We5+hObCEcGNTz80tXvUlpafWJNiKIpeAZH0P6FmrLKxKRClGGUIgcngfcQhyIXMizrFSWK/mmdetTi5RZV2W8XKT35+1j+pj+5ZEHuoYS3paQRrAe6aWwHRMOcpJKujvWIRGZR0e8T/025d9J2HJZ5htLusJE1VXU8mfQMgmnGKpk5+v3gJ5BCjGOOdL0gn9A9Z1bpvgCnTEfr2/i0fIF9b/YzxzdtU1d3aW+OBtvuhPdUsQ2HnyULF4+APlJWf8=)

### Other comments
I closed the other issue, because the headline and initial description were far away from the actual problem. #17965

**Comment by drhouse82** [comment] 2023-08-08 11:01
Now, when playing with the reproduction link and setting it to vuetify 3.3.5, it gets clear that the actual html input is filling the entire space, whereas it is contracted to a smaller space for vuetify 3.3.6 and later.

**Comment by KaelWD** [comment] 2023-08-08 11:48
Duplicate of #17865, #16812

**Closed by KaelWD** 2023-08-08 11:48 UTC
Labels: S: triage
