### ISSUE TITLE
Enhancement: Disable scrolling when dialog is open

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#542] opened 2017-05-15 10:17 UTC
If a scrollable page opens a dialog, you can still scroll up and down while the dialog is visible. It happens with all kinds of dialogs, simple, modal and fullscreen. This should be prevented in my opinion as it's being done in Vue Material: https://vuematerial.github.io/#/components/dialog

**Comment by mfferreira** [comment] 2017-05-15 13:25
duplicate of #514

**Closed by mfferreira** 2017-05-15 13:25 UTC
