### ISSUE TITLE
[Bug Report] [Nuxt] CSS not loading in Build Mode

### ISSUE THREAD

**Issue by anishappadoo** [vuetifyjs/vuetify#12063] opened 2020-08-16 15:21 UTC
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Nuxt/Vuetify module Version:** 1.11.2
**Browsers:** Google Chrome
**OS:** Windows 7

### Steps to reproduce
npm run build && npm start

### Expected Behavior
The css should have loaded in production mode.

### Actual Behavior
The css loads in development mode but not in production mode.

### Reproduction Link
<a href="https://www.github.com/" target="_blank">https://www.github.com/</a>

### Other comments
I'm currently using nuxt's vuetify module (version: 1.11.2). In development mode, vuetify's css loads properly. However, in production mode, vuetify's css does not seem to load at all. I have tried implementing vuetify as a plugin (not via the nuxt package) and I got the same issue. I also tried importing the css directly: `import 'vuetify/dist/vuetify.css'` but it didn't work either. I copied vuetify.css and pasted it in the same directory as my .vue file and imported it using: `import './vuetify.css'` but it still didn't work. Even adding the path to vuetify.css inside nuxt.config.js didn't work: `css: ['~/assets/css/vuetify.css']`. It only worked when I copied the whole css from vuetify.css and pasted it in my .vue file between the `<style>` tags.

**Comment by Mert75** [comment] 2020-08-16 20:51
Duplicate of [#372](https://github.com/nuxt-community/vuetify-module/issues/372).

**Closed by Mert75** 2020-08-16 20:51 UTC
Labels: triage
