### ISSUE TITLE
[Feature Request] [v-number-input] set the number of decimal places

### ISSUE THREAD

**Issue by mueller-jens** [vuetifyjs/vuetify#20567] opened 2024-10-11 14:42 UTC
### Problem to solve
The posibility to set a max number of decimal places that can be put in

### Proposed solution
If the number of decimal places is reached, no more nmbers can be written in the text field

**Comment by KaelWD** [comment] 2024-10-12 11:43
Duplicate of #19898

**Closed by KaelWD** 2024-10-12 11:43 UTC
Labels: S: triage
