### ISSUE TITLE
[Bug Report] content-class not being assigned

### ISSUE THREAD

**Issue by birdlavv** [vuetifyjs/vuetify#4128] opened 2018-05-23 18:34 UTC
### Versions and Environment
**Vuetify:** 1.1.0-beta.0
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Mac OS 10.13.4

### Steps to reproduce
Run pen and note that `.the_content_class`  is not assigned to the menu

### Expected Behavior
In previous versions, and as the 1.1.0-beta.0 docs currently note, the menu would have been assigned `.the_content_class`
>`content-class`
>Applies a custom class to the detached element. This is useful because the content is moved to the end of the app and is not targettable by classes passed directly on the component.

https://next.vuetifyjs.com/en/components/selects

### Actual Behavior
`.the_content_class` is not assigned to the detached element

### Reproduction Link
[https://codepen.io/George6789/pen/bMyGPY](https://codepen.io/George6789/pen/bMyGPY)

**Comment by KaelWD** [comment] 2018-05-24 01:10
Duplicate of #4088

**Closed by KaelWD** 2018-05-24 01:10 UTC
