### ISSUE TITLE
[Bug Report] "search-input" in v-autocomplete doesnt meet expectations

### ISSUE THREAD

**Issue by MBERoxit** [vuetifyjs/vuetify#11702] opened 2020-06-22 14:57 UTC
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.106
**OS:** Windows 10

### Steps to reproduce
See example (reproduction link)

### Expected Behavior
I expected to have the search value pre-filled in with items filtered out that do not meet the search-query. But I could have misunderstood how v-autocomplete is meant to work

### Actual Behavior
blank select box

### Reproduction Link
<a href="https://codepen.io/mberoxit/pen/OJMpYrw" target="_blank">https://codepen.io/mberoxit/pen/OJMpYrw</a>

**Comment by KaelWD** [comment] 2020-06-24 07:22
Duplicate of #9757

**Closed by KaelWD** 2020-06-24 07:22 UTC
Labels: triage
