### ISSUE TITLE
[Bug] Gap between navigation drawer and toolbar on XS

### ISSUE THREAD

**Issue by HendrikGrobler** [vuetifyjs/vuetify#1797] opened 2017-09-18 12:20 UTC
### Steps to reproduce
Use a clipped, persistent navigation drawer along with a toolbar and set a contrasting background for app, then change screen size to mobile

### Versions
0.15.7 on all browsers

### What is expected ?
The navigation drawer should be right against the toolbar like on sm and up breakpoints

### What is actually happening ?
There is a gap between the navigation drawer and the toolbar.
Seems to be related to the toolbar height changing from 64px to 56px on mobile

### Reproduction Link
https://codepen.io/anon/pen/YrwPyw (resize the preview area to XS breakpoint)

The navigation drawer component styles current cater for overriding the margin-top of the nav drawer only on landscape orientation. An override for portrait is also needed.

**Comment by HendrikGrobler** [comment] 2017-09-18 12:39
I wanted to do a PR to fix this, but the dev branch's navigation drawer component style is quite different from the 0.15.7 version. The mobile specific and orientation specific heights don't appear to be in use in dev anymore.

**Comment by jacekkarczmarczyk** [comment] 2017-09-18 12:47
The layout has been rewritten in dev branch, please check if the problem is still there, if no then close the issue

**Comment by johnleider** [comment] 2017-09-19 02:38
I can confirm this works great in dev.

**Closed by johnleider** 2017-09-19 02:38 UTC
Labels: pending review
