### ISSUE TITLE
[Bug Report][2.6.3] VApp does not compute correct padding when VNavigationDrawer has expandOnHover and app props

### ISSUE THREAD

**Issue by oliverh-cf** [vuetifyjs/vuetify#14765] opened 2022-02-25 22:04 UTC
### Environment
**Vuetify Version:** 2.6.3
**Last working version:** 2.6.3
**Vue Version:** 2.6.14
**Browsers:** Firefox 97.0
**OS:** Linux

### Steps to reproduce
Can be replicated on a fresh Vuetify instance by adding
`<v-navigation-drawer app expand-on-hover />` between `v-app-bar` and `v-main` in App.vue.

```vue
<template>
  <v-app>
    <v-app-bar app color="primary" dark>
    // ...
    </v-app-bar>

    <v-navigation-drawer app expand-on-hover />

    <v-main>
      <HelloWorld />
    </v-main>
  </v-app>
</template>
```

### Expected Behavior
Expected result: Padding should match the width of the collapsed drawer.

### Actual Behavior
Actual result: Padding matches the width of the expanded drawer.

### Reproduction Link
<a href="https://github.com/oliverh-cf/VNavigationDrawerIssue" target="_blank">https://github.com/oliverh-cf/VNavigationDrawerIssue</a>

### Other comments
Everything was working fine until we ran `npm install` the other day.

**Comment by KaelWD** [comment] 2022-02-26 08:26
Duplicate of #14585

**Closed by KaelWD** 2022-02-26 08:26 UTC
Labels: S: triage
