### ISSUE TITLE
[Bug Report] Radio buttons inline are buggy in a matter of design

### ISSUE THREAD

**Issue by ScreamZ** [vuetifyjs/vuetify#5325] opened 2018-10-14 13:53 UTC
### Versions and Environment
**Vuetify:** 1.2.9
**Last working version:** 1.1.13
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Mac OS 10.14.0

### Steps to reproduce
Just watch the documentation for the component https://vuetifyjs.com/en/components/selection-controls#example-radios-direction

### Expected Behavior
Aligned in row

### Actual Behavior
Not align in row

### Reproduction Link
[https://codepen.io/anon/pen/VEMrRj?&editors=101](https://codepen.io/anon/pen/VEMrRj?&editors=101)

**Comment by ScreamZ** [comment] 2018-10-14 13:55
This seems related to #5255.

Do we have a fix milestone and date ?

Thanks,
Regards

**Comment by KaelWD** [comment] 2018-10-15 05:16
Duplicate of #5255

**Closed by KaelWD** 2018-10-15 05:16 UTC
