### ISSUE TITLE
[Bug Report] v-text-field does not emit change events when triggered programmatically

### ISSUE THREAD

**Issue by vramdal** [vuetifyjs/vuetify#12955] opened 2021-01-14 08:41 UTC
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.141
**OS:** Mac OS 11.0.1

### Steps to reproduce
1. Run the Codepen 
2. Look at the Codepen's preview pane:
a) The upper part has a `v-text-field` with an `@change` handler, which works as expected when interacting with it. Try entering some text and tab away from the field, an alert box will pop up.
b) The lower part shows output from a test run. See the JS pane, line #43. The test mounts the same component, and triggers events on it. The `input` event and the `click` event behaves as expected. The `change` event, on the other hand, is not being emitted.
---- or ----
1. In a test, mount a component that includes a `<v-text-field>` with an `@change` handler
2. Using vue-test-utils, get a reference to the input (`const input = wrapper.find("input")`)
3. Trigger a change event on the input (`input.trigger("change")`)

### Expected Behavior
The function specified in the `@change` attribute is called

### Actual Behavior
The function specified in the `@change` handler is not called. However, when mounting the component in a web browser and interacting with the v-text-field, `change` events are being dispatched when tabbing away from the field, as expected.

### Reproduction Link
<a href="https://codepen.io/vramdal/pen/xxEQVPm" target="_blank">https://codepen.io/vramdal/pen/xxEQVPm</a>

**Comment by KaelWD** [comment] 2021-01-14 08:42
Duplicate of #12805

**Closed by KaelWD** 2021-01-14 08:42 UTC
Labels: triage
