### ISSUE TITLE
[Bug Report] VCombobox can't handle object items properly when return-object is disabled

### ISSUE THREAD

**Issue by HeshamMeneisi** [vuetifyjs/vuetify#10023] opened 2019-12-20 18:51 UTC
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.79
**OS:** Linux x86_64

### Steps to reproduce
Use a `v-combobox` component.

Turn on multiple

Turn off return-object

Set items using the object format: 

```json
{
  text: '',
  value: '', 
}
```

### Expected Behavior
Combobox can handle the data properly, displaying text, highlighting selected items, and internally using value for v-model.

### Actual Behavior
Value is used in display (comma, chips)
Selected items are not highlighted in menu
Values prepopulated in `v-model` are not parsed into objects internally.

### Reproduction Link
<a href="https://codepen.io/heshammeneisi/pen/OJPprzM" target="_blank">https://codepen.io/heshammeneisi/pen/OJPprzM</a>

### Other comments
The issue is easily solvable if VSelect.setSelectedItems is mirrored with a minor change that takes into account `isAnyValueAllowed()` before rejecting `index === -1`.

Bonus:
This also allows isAnyValueAllowed() to be actually functional as a property instead of being a placeholder as of now.

**Comment by KaelWD** [comment] 2019-12-21 01:27
Duplicate of #5479

If you think you have a fix feel free to open a pull request, but it will not be merged if it introduces asymmetric behaviour.

**Closed by KaelWD** 2019-12-21 01:27 UTC
Labels: triage
