### ISSUE TITLE
[Bug Report] Outlined v-text-field with initialized value strikes through label text

### ISSUE THREAD

**Issue by JagvirS** [vuetifyjs/vuetify#10624] opened 2020-02-19 18:11 UTC
### Environment
**Vuetify Version:** 2.1.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
Place a v-text-field with a label and "outlined" prop in two panels of v-expansion-panels component. Assign a value to the text fields on initialization.

### Expected Behavior
The label of all v-text-fields should show in the top left, in a gap in the outline.

### Actual Behavior
The text field outline crosses out the label on any text fields in a panel of the v-expansion-panels component.

### Reproduction Link
<a href="https://codepen.io/jagvir/pen/WNvGQBW" target="_blank">https://codepen.io/jagvir/pen/WNvGQBW</a>

### Other comments
Upon deleting the initialized value, and deselecting the component it will begin to behave as expected.

Works as expected on Codepen.

**Comment by DougStanley14** [comment] 2020-02-28 22:24
Please Address this ASAP - my clients are bothered by this immensely

**Comment by jacekkarczmarczyk** [comment] 2020-02-29 00:34
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7470

You're missing `v-app` in codepen

**Closed by jacekkarczmarczyk** 2020-02-29 00:34 UTC
Labels: triage

**Comment by musasoftlabx** [comment] 2020-03-15 16:01
hi @jacekkarczmarczyk , this seems like a major issue affecting many people. Even with the v-app, it still does the same. I found a temp fix.

Add this to your styles css
**.v-label.theme--light.error--text {
  left: 0 !important;
}
.v-label.v-label--active.theme--light {
  left: -27px !important;
}**

**Comment by jacekkarczmarczyk** [comment] 2020-03-16 04:16
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
