### ISSUE TITLE
[Bug Report] the theme is missing in ie11

### ISSUE THREAD

**Issue by fronterender** [vuetifyjs/vuetify#10563] opened 2020-02-13 05:20 UTC
### Environment
**Vuetify Version:** 2.2.12
**Last working version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 76.0.3809.87, Internet Explorer
**OS:** Windows

### Steps to reproduce
1. vuetify initial
new Vuetify({
       theme: {
           customProperties: true
        }
})
2. in component \<v-checkbox v-model="gender"  label="gender">\</v-checkbox>
3. in script  data () {
    retrun {
      gender: true
    }
}

### Expected Behavior
ie11, the checkbox background color is probably bluein default

### Actual Behavior
ie11,  the checkbox background color is grey

### Reproduction Link
<a href="https://codesandbox.io/s/serene-rhodes-2pqob?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/serene-rhodes-2pqob?fontsize=14&hidenavigation=1&theme=dark</a>

### Other comments
1.bug
When I set the attribute of customPropertise to true,for example
new Vuetify({
theme: {
customProperties: true // There's a side effect，ie11 has a bug,such as v-checkbox,the style is missing
}
})
in order to be compatible with ie11, I have to give up customProperties

2.The document is a bit fuzzy about modifying the default sass variables,In my project, I want the app background and theme to be the same, and they can be modified through configuration, because they are a whole. At the same time, when I write components, I want to reference or modify the default variables. Others have solutions, but I don't understand them. I want to have a detailed solution

**Comment by nekosaur** [comment] 2020-02-19 21:45
IE11 does not support CSS variables which is what `customProperties` is using, so I'd call this a working as intended/wontfix? @jacekkarczmarczyk

**Comment by jacekkarczmarczyk** [comment] 2020-02-29 05:45
Agree, if you want to target IE11 don't use `customProperties`
Please create a separate issue for documenting sass variables with detailed information which part of current docs is not clear/doesn't work, your description is now a big vague

**Closed by jacekkarczmarczyk** 2020-02-29 05:45 UTC
Labels: Service: Theme, platform specific, triage
