### ISSUE TITLE
[Bug Report][3.0.0-beta.5] Hydration with v-navigation-drawer with SSR app

### ISSUE THREAD

**Issue by MrPalixir** [vuetifyjs/vuetify#15453] opened 2022-07-16 18:17 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Safari 15.5
**OS:** Mac OS 10.15.7

### Steps to reproduce
The v-navigation-drawer on SSR is slower to load than the content of v-main. So on my application the page load add after the v-navigation-drawer is add and the content readjusts to it.

### Expected Behavior
An equality of the load time between the v-main and the v-navigation-drawer

### Actual Behavior
The v-navigation-drawer is slower.

### Reproduction Link
<a href="https://codepen.io/mrpalixir/pen/xxWgqLZ?editors=1010" target="_blank">https://codepen.io/mrpalixir/pen/xxWgqLZ?editors=1010</a>

**Comment by KaelWD** [comment] 2022-07-17 02:25
Duplicate of #12833

**Closed by KaelWD** 2022-07-17 02:25 UTC
Labels: S: triage
