### ISSUE TITLE
[Bug Report] Outline form fields within expansion panels label problem

### ISSUE THREAD

**Issue by jondmoon** [vuetifyjs/vuetify#8187] opened 2019-07-30 16:38 UTC
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Windows 10

### Steps to reproduce
Have a outlined form field within an expansion panel with a default value. This makes the legend for the frameset not calculate its width properly so there is a line through the label.

### Expected Behavior
It should work the same way as it does when it is not in an expansion panel.

### Actual Behavior
The label is in the correct position, but because it is not in the legend and the width of the legend is too small, the outline box goes behind the label making it look like there is a line through it.

### Reproduction Link
<a href="https://codepen.io/moon05/pen/gVWOxe" target="_blank">https://codepen.io/moon05/pen/gVWOxe</a>

**Comment by KaelWD** [comment] 2019-07-31 01:02
Duplicate of #7470

**Closed by KaelWD** 2019-07-31 01:02 UTC
Labels: C: VTextField, T: bug
