### ISSUE TITLE
[Bug Report] v-select blank space in selection

### ISSUE THREAD

**Issue by ahmedfaical** [vuetifyjs/vuetify#8785] opened 2019-08-29 12:06 UTC
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.2

### Steps to reproduce
Select a long option you get blank space

### Expected Behavior
No blank space

### Actual Behavior
I get blank space in selection

### Reproduction Link
<a href="https://codepen.io/codinga/pen/BaBpOOx" target="_blank">https://codepen.io/codinga/pen/BaBpOOx</a>

### Other comments
I get blank space in v-select if i select a long option

**Comment by Leespiker** [comment] 2020-04-05 00:15
@ahmedfaical Your [reproduction](https://codepen.io/codinga/pen/BaBpOOx) seems to work fine for me. Can you please post a new one if you're still having issues?

**Comment by jacekkarczmarczyk** [comment] 2020-04-06 04:03
@Leespiker 
![image](https://user-images.githubusercontent.com/15625235/78522072-6208d080-77cc-11ea-8ac2-ef706b28aadc.png)

**Comment by itsalaidbacklife** [comment] 2020-11-10 20:27
Workaround: you can use css to style the input to shrink it and remove it from the flow. 

```
<template>
  <v-select id="my-select" :items="myData"></v-select>
</template>

<style>
  input#my-select {
    position: absolute;
    display: inline;
    width: 0;
    height: 0;
    padding: 0;
  }
</style>
```

**Comment by KaelWD** [comment] 2020-11-26 14:43
Duplicate of #6275

**Closed by KaelWD** 2020-11-26 14:43 UTC
Labels: C: VSelect, T: bug
