### ISSUE TITLE
[Bug Report][3.5.1] VAutoComplete inside VDialog using activator="parent" opened by VBtn inside VRadioGroup shows all options as selected and clicking the checkbox changes the radio model-value

### ISSUE THREAD

**Issue by ChristofferBrenden** [vuetifyjs/vuetify#19096] opened 2024-01-24 10:33 UTC
### Environment
**Vuetify Version:** 3.5.1
**Vue Version:** 3.4.15
**Browsers:** Chrome 120.0.0.0
**OS:** Windows

### Steps to reproduce
In the reproduction link, click the "Open dialog" button and in the dialog click the auto-complete field, all the options have their check-box checked, and clicking the item on the label works, but clicking on the check-box itself causes all check-boxes to change and also the radio model-value to change.

### Expected Behavior
The autocomplete field should work as normally.

### Actual Behavior
Strange/unexpected behavior when selecting/deselecting options.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1VE2P0zAQ/SsjXwJSP3YFvVQtAhXBBYkDSBy2e/Am0zLCiY09LkWr/e+MnaabbMJt8uZl5o3n4+5RBV8uPzi3OEVUa7VhrJ3RjO/2DcDmNNfOZTN/lLZhTQ36C5RBryuy86O30cFpXtsKzXavMrpXV+IzFdYnbSIKh31EoWyWF8+Q/MBNDwD46rCBj6SNPfZhYVYZhD9U8U8Ju7q52auelNYtkC6ZTpqtF9Bpjw0PBHZFal8BE5sk8ZLvJe1KnDOeeeQE+GI91kAuxBoqa6yHQAy6Rp6BvGLAkpGjBynbUSipOQIaEmfASn4YB0SKQQqC1B+JRk1JFVWxYYgMRj9IPkBucyHU+tho0IZ+R70YB0t9jWxLK71GxjEBUsj8eN/QiNa9muKsSdQEId0VO8l1sL4hXcyg2CUVurLJ/iQmVRn+jNYfW8Z3POuQjB9/bS3VF/fTKepomETk2JfHpl/FuEVC+H+PugamoZCGTPRQGMHpUqY9RbqYkzQZVWnMmeUpdsYG7MZUwfvSUPnrOoSwhYM2oZv6lyM+UD0trHMP4AS2CforNEow3sC+mOEKXpF2s7sbkLIPjkDuQr4Rm2XvdshnKD05loHmy++UJpfhETwe4AkO3tZQyNkpEh3yWjC0AreJ8yrdh9fPrusTJl9WLs7Nss0jGdTTTL1ZvF3crlQyVotbdf8PNbVtcw==)

### Other comments
A few workarounds exist which uses another way to activate the dialog other than the `activator="parent"`, such as placing the whole radio-group inside the activator slot of the dialog [workaround 1](https://play.vuetifyjs.com/#eNqFVE2P0zAQ/SujXArStt0V9FK1iFURXJA4gMRhuwc3npQRTmzsSVlU9b8zdpLuNknhZs+8eZ6P53k4ZsHn83vnZocas2W2YiydUYzvthXA6jBVzqVjuuS2YkUV+taUjJqUsXv4TZp/rLfZ4vZ2m539gugY4TANxvJS5UwHxdYL+AjOWxfgdBGSaL3SZKd7b2snkaXVaCQgWXvgZzgsD8rUKDj2NQpsNW89w4AdV8JLxTOpXHdUaTGkpMTA+MRy/eKwgg+pTOGESCrR/82hUCZcT+JsbWp82bH5xRCutFFjoWoT0zsChfvYVBzrY668BiY2MaVzEYPcI2wa6+25AD5bjyWQC3UJ2hrrIRCDKpFvQAQRMGfk2oPU4ijkVO0BDYkzoJaAPh1SHWSa0tvSCRdVOWnSdcVQMxi1k9cAuXkJoVT7SoEy9KtWsz5VlGfNNrfSGWTsuyHSJdV8RSNZbrMhYkmSRxDIw2QjrxTWV6QmNzDZxPeVtvH8UY6kk/kTWr9vEN/wSYV4+P7HllL15HHsgVJmRJJe35NU8TL7/kjEfW0m3bjiT5IBDCYm/uBULt80srTHEZCIeJhwq/mNsQHPoh/C3ueG8p8C7LQ3S7KHNbSyHy145Nt0dY4V0zn//TkiqllC3aaKYRerKjU7bbKLeLmG3JNj0Sq3f5CiLBmO4LGAExTeljCR5TiJcEiKZ2h++jpiXsVV8zoSN1RCkp1usjezt7O7RRYPi9ld9vgXiqiVjQ==) (which would not work if you'd have multiple buttons/dialogs in the radio-group), or by placing the dialog outside the radio-group and opening it with `@click="dialog = true"` on the button and `v-model="dialog"` on the dialog, however you'd be missing the activator-transition [workaround 2](https://play.vuetifyjs.com/#eNp9VMFu2zAM/RXCF29Ak7TYcgmSYUOG7TJghw3YoelBlZiMmGxpEpV1KPrvpWQnsZOiN5rv5fFRJHP7WMWgZ5+8n+4TVotqydh4qxg/bFqA5X6ivC9h+dCuZUUthj5VkkEZcpNdcMnDftI4g3a1qUp2Ux2JJyos9somFA6HhEJZznpkTL7nVvRoexIDxgeWz+8eW/hMyrqdJD9qS/qPpE3JwAp6XcjCovKqh62y8WUTx0zX27DlvtI/MvxbNObX1+Lj1HsHnzevVTDAxDaXPbgfUI6kSW5zBAB8cwEbIB9TA8ZZFyASg2qQr0CmElEzcgogfj1FTe0O0JKAEY38YCyGlKJ4ledsvChRq8mQSS1DYrDqXmoBclcHoVG7VoGy9Dep6Vgo70dip53sDDKOQchS5T1+oBV/m+ocX5A4iEK4rdeiv3WhJVVfQb3OlZVxOf4iIZmS/oou7DrGT3xQMQe//rtGuq3vLuWbZJnE2DhfJj10PR6BgC/P4DAcpZnkwc/mI2j0SstlZIU+vKDkle53eG1dxNeWeLiY4yUeuLw0c4BGa9yJHu44M0aHXF6k3PlyNrh/+Yw6kGdZIu4PgPLGMDxCwC08wTa4Bmr566gzHcoqMnQntsqcN/kW356gY3sZKy0KuJx1daRC9XRVvZu+n97MqxzMpzfV3TMoOmnT)

**Comment by KaelWD** [comment] 2024-01-25 07:51
Duplicate of #16245

**Closed by KaelWD** 2024-01-25 07:51 UTC
Labels: S: triage
