### ISSUE TITLE
[Bug Report] Empty VRow changes spacing of other rows

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#12910] opened 2021-01-06 22:48 UTC
### Environment
**Vuetify Version:** 2.4.2
**Last working version:** 2.3.23
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Windows 7

### Steps to reproduce
Have an empty row to cause the other two rows to lose the gap between them.

### Expected Behavior
Gap remains.

### Actual Behavior
Gap disappears.

### Reproduction Link
<a href="https://codepen.io/teellcory/pen/ZEpRKzP" target="_blank">https://codepen.io/teellcory/pen/ZEpRKzP</a>

**Comment by KaelWD** [comment] 2021-01-07 09:50
Duplicate of #12915

**Closed by KaelWD** 2021-01-07 09:50 UTC
Labels: triage

**Comment by Teellcory** [comment] 2021-01-21 23:16
I don't know if 2.4.3 fixed the one you marked this as a duplicate of, but it did not fix my issue.
