### ISSUE TITLE
[Feature Request] Improve selection behavior when time-pickers use allowed-minutes

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#4196] opened 2018-06-04 14:28 UTC
### Problem to solve
Currently, if you use the ```allowed-minutes``` prop and a user mis-clicks an allowed minute by even a few pixels (i.e. they misclick by a single minute), the time picker will still switch back to the hour selection, but also not select a minute. (You can see this behavior here https://codepen.io/anon/pen/VdeRge)

### Proposed solution
Two possible solutions:

1) Clicking a disallowed minute should do nothing. The time picker should not switch back to the hour picker, and should not select a minute.

2) Clicking a disallowed minute should select the nearest allowed minute. If every 15 minute interval is selectable, and I accidentally click 14, 15 should be auto-selected.

This same behavior applies to ```allowed-hours``` also.

**Comment by nekosaur** [comment] 2018-06-04 14:52
It should simply not switch back to hours display unless you explicitly click the hour in the title.

**Comment by KaelWD** [comment] 2018-06-04 15:02
Duplicate of #3371

**Comment by Dylan-Chapman** [comment] 2018-06-04 15:03
That's a good point and probably an easier solution overall. If that's the case, then this behavior would still apply to the ```allowed-hours``` switching to minute selection on a mis-click.

**Comment by KaelWD** [comment] 2018-06-05 05:47
Yeah this still applies for `allowed-hours`, even with #4198.

**Closed** 2018-06-16 04:00 UTC
Labels: S: has PR, T: bug
