### ISSUE TITLE
[Bug Report] Can't resolve 'vuetify/lib/framework'

### ISSUE THREAD

**Issue by abelardolg** [vuetifyjs/vuetify#12841] opened 2020-12-25 11:30 UTC
### Environment
**Vuetify Version:** 2.4.0
**Last working version:** 2.4.0
**Vue Version:** 2.6.1
**Browsers:** Chrome 87.0.4280.88
**OS:** Linux x86_64

### Steps to reproduce

1. vue create hello-vuetify
2. cd create-hello-vuetify
3. vue add vuetify
4. npm install
5. npm run serve

### Expected Behavior
The initial page of the project is showed

### Actual Behavior
The following message is showed:
./src/plugins/vuetify.js
Module not found: Error: Can't resolve 'vuetify/lib/framework'  in /src/plugins'

### Reproduction Link
<a href="https://github.com/abelardolg/vue-hello-vue" target="_blank">https://github.com/abelardolg/vue-hello-vue</a>

**Comment by KaelWD** [comment] 2021-01-07 10:28
Duplicate of https://github.com/vuetifyjs/vue-cli-plugins/issues/228

**Closed by KaelWD** 2021-01-07 10:28 UTC
Labels: triage
