### ISSUE TITLE
[Bug Report][3.6.7] VSelect dropdown with attach gets opacity from VField

### ISSUE THREAD

**Issue by J-Sek** [vuetifyjs/vuetify#19937] opened 2024-06-03 09:16 UTC
### Environment
**Vuetify Version:** 3.6.7
**Vue Version:** 3.4.27
**Browsers:** Chrome 125.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Use `attach: true` within `menu-props` for VSelect, VAutocomplete or VCombobox

### Expected Behavior
Menu should be fully visible

### Actual Behavior
Menu gets opacity from `.v-field__input` because it is placed inside this div in DOM

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNptkU1uwjAQha8yyiathJuW0g2CSj1BF1VXhIXjDMTCsS17Aq1C7l7nT6TAJrHnfRq/ebOpI+9E8mHt07HCaBmtCEurOOF7qgFWR8at7Y7dRRhNXGp0Q6krelQoaCwAHFlpclTrNDpyVWEaXaSlDO19UIwlabT/p5WoK2adsS1QAyfiooBmypxkTkVQF8/Pl3IyNSMKFIfM/Exc9I3SCBTPusK3x7H7SVIhNVyeDtikn3UIQnHfOsr2bO/wlym5Lwg1m4Mzlc4xZ2oPlrMFZMbl6IYfyxQXhzQKzb66gMK8S6hr6EKB8xliXSkVQ9OskvDO+OYYdnKddlvpl7FKJksKVy+ctAQeqep3JUtrHEENDnfQwM6ZEuKw37jFAUJfT4OPdcs8tE4eL9IQTq+Rq3CiDZsL4qZ3Oky0hJcZkCQVTvFnB8FLmG52Rc1vqPkd6vWGer1DLW6oxR3q7YZ6G6ltG2YfXwguamZtEN1n+wdmufxv)

### Other comments
I wish I could rely on default attachment behavior but...
- menu overlaps `v-app-bar` when I use it with strandard app layout (i.e. static header, footer, scrollable div instide `v-main`) - [[example]](https://play.vuetifyjs.com/#eNptU01vozAQ/SsjLmmluPlougdEI616Xu1htafSg3GGwsZgyxgSlOa/7xiTQEo4II/nzdeb5/dTUBmx+Kn1U1NjEAaRxUJLbnEblwBRw7jW3fFisISbbbTLGxCSV9VrHBSSbeJg+6uFAyYOEi3IvY0WA/6aoOB52VtkE+xyhms61aBJpTqwlvHaKkg+2afBlsn8M7NYsnUcDEGVbSW6HviRZegQIQguxcNquWwyYLBabvTxcQi5Fu/aEaq01BFeOhwc3OwAJTbc5qqkAj/i4Nqh5ozMm5AuqKIAYW+vAWhotUNJcQ2XNY6791+YE+fd5NoVq+4gCixrpo3SDnbi1nKRnae4Q76zGSE2y+V352LarshQ7BN1HHXoM9Ookifdxd8KwV9ScpvlJQytEGySVRu80jRZHBBxTilx+adjioYN4XSCjhf4+oJZWUs5g/M5WlCi29STSoP+rNMETZEqQ2YO1OWa6kC4x9ZdUMk3WjSWlvLebpo06lY9VoW7msjCS7qXMSFGOiYmU6UsGiC1j4dPJBd7+FdXNk9bJqg8mpEQ35RujaNmDmhF93tyqX0yD/OP0D8kOkeL0esksxIm1xYqtLWfKy+0MhZOYDCFM6RGFTCjhz1zcHpipC7b0/3qMA+O8MfB1a/a+6ypceTr1UnOd99cv7gQVnOwuZV0mv3uQLCiJc6/odYT1PoO6nmCer6D2kxQmzuolwnq5YL6cGR6+oi44Dx3RHS/j/99G4Yw)
- same overlapping issue within scrollable `v-dialog` - [[example]](https://play.vuetifyjs.com/#eNrdVEtv2zAM/iuEd0gLRMujaTEEaYChu/e0U9ODIjOxVtkSZNlNEOS/j5Lz8CvDzr0YpviR/Ph8O0S5FaOfxnwvC4zm0cJhahR3uFxlAIuScWPCbxBSLrOTRHIsSxCK5/nzKlpv2dbinim5TRxmbLqKLsBgGkuu9Lb2Fl4FtzGgwpI7qTPy89Swq6GYk07hNZ62MVq2Jviv4BmCfjGqo295wp1rauDiV5doN0p/sj3jhdOrqA3M3V4hAVO+Ywn6bOcguBJ3k/G4TIDNfpgdMCDJ7O7b5i1CgVJO6YsOHwCqto5RUaiSqwK7TADmkroVWBtfvrwXk2JWMGO18cADd46L5NiH/JSxSwgzG4+76lEfdZGg+Fjr3b/IVwH74im+DojfOUKFIgoukRlcKf8XEXPpXur84FH0jbYkSiBn0xm9zD9w7x9oXF50RgPqFqPzXH+BblzHnkb7xtRzEVi1N8h1Fi6YrF22fFE6DxvlhRsBT16be31S0mPj+Xxa4Ju3opUPTTpAKAdQFdpB6gfGcPYEMdso3MGfIndys2eC+oj2ZgLUtLXMYm9czdLy1WAG1SW6lRfFbCXTuIjXDFsHrW7p1ZdT6YXqiDZckZgLK42DHF1RzaJMjbYODmBxA0fYWJ3CgO7yoCqkoEI7CPMHzx5zlxVK3V9Vpy2qdM4WWNOdhpKUbxXJQ+VpDpNhdTvnMHgNIJgM4DhsoaYd1LQH9dBBPfSgZh3UrAf12EE9nlHvvphV+ahw0XHoCxE+738Buozq1Q==)
- menu stays in the same place (detaches from the field) when I use `vue3-perfect-scrollbar`

As mentioned in [#16855](https://github.com/vuetifyjs/vuetify/issues/16855#issuecomment-1965669259) `style="z-index: 3000; position: relative"` could be potential workaround, but it only fixes the most critical interference from checkboxes. I don't want my app to be incosistent by showing some menus translucent and others fully opaque. Can we move menu outside `.v-field__input`?

### My workaround for now

```
:menu-props='{ scrollStrategy: 'close' }`
```

**Comment by LuisFernando-hub** [comment] 2024-09-20 03:59
Hello, i have the problem, i used VSelect in dialog, when i used scroll and selected my options stay bugs

My code, this is inside a dialog VDialog

<VSelect v-model="...." label="Filtro de Exportação" :items="items" density="compact" />

![image](https://github.com/user-attachments/assets/0801307a-b23d-4143-b18e-4105b2bd1fc0)

**Comment by KaelWD** [comment] 2024-09-20 10:27
Duplicate of #16855

**Closed by KaelWD** 2024-09-20 10:27 UTC
Labels: S: triage
