### ISSUE TITLE
[Feature Request] Nested v-autocomplete 

### ISSUE THREAD

**Issue by PsySolix** [vuetifyjs/vuetify#6089] opened 2019-01-09 10:57 UTC
### Problem to solve
Happens all the time, that if you have a nested data structure and you would want to display it in the same way as an other v-autocomplete layout. (so mounted in a v-menu + v-lists)

### Proposed solution
Allow 2 props on v-autocomplete -> "nested" & "nested-key"
if nested = true && nested-key (default ="children")
show it in a nested layout.

**Comment by PsySolix** [comment] 2019-01-09 11:00
Or it would be awesome if you guys can put me in the right direction to customizing myself (screenshot is what I have for structure)

Problems I encounter:
- With the slot="activator" it is hard to check click handlers
- If I want to have chips, I need to use a v-select to trigger the dropdown. But the v-select also needs is own props, like :items, v-model,... 


![image](https://user-images.githubusercontent.com/6713256/50895271-e6bc4180-1405-11e9-9b41-593f7ca9443c.png)

**Comment by PsySolix** [comment] 2019-01-17 10:53
Hey! Thanks for the 'maybe' label, gives hope :-) Do you guys any updates for this? 
In the meantime, do you guys know a way how I can (maybe with a hackish way) mimick the behaviour? 
So what I need for a nested tree component + checkboxes -> 
-The same mount / location way as vuetify:  v-select / v-autocomplete (internally mounts a v-menu outside & calculates positions for the dropdown)
- Nested sructure: Do I just merge children all in one array and maybe differentiate with padding that its nested. Or do you guys know a good way how I can add a v-list loop inside a v-list-tile-content? 

Thanks in advance! 
PS: Keep up the good work!

**Comment by bad4iz** [comment] 2020-01-11 14:52
Duplicate of #3049

**Closed by bad4iz** 2020-01-11 14:52 UTC
Labels: C: VAutocomplete, C: VSelect, T: feature, duplicate, maybe
