### ISSUE TITLE
[Bug Report] Nested v-dialog inside v-menu does not open

### ISSUE THREAD

**Issue by gkatsanos** [vuetifyjs/vuetify#8475] opened 2019-08-12 11:38 UTC
### Environment
**Vuetify Version:** 2.0.5
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Mac OS 10.14.5

### Steps to reproduce
Nest a v-dialog inside a v-menu

### Expected Behavior
The v-dialog shows

### Actual Behavior
The v-dialog doesn't show

### Reproduction Link
<a href="https://codepen.io/gkatsanos-the-bold/pen/XvoZqj" target="_blank">https://codepen.io/gkatsanos-the-bold/pen/XvoZqj</a>

### Other comments
The nested v-dialog inside a v-menu doesn't open.

**Comment by jacekkarczmarczyk** [comment] 2019-08-12 12:22
Possible duplicate of https://github.com/vuetifyjs/vuetify/issues/7021

**Comment by radcki** [comment] 2019-08-15 20:20
To use setTimeout solution presented in #7021 with custom component which is wrapping dialog, something like this seems to work: [https://codesandbox.io/embed/vuetify-dialog-wrapper-inside-menu-kvh0e](https://codesandbox.io/embed/vuetify-dialog-wrapper-inside-menu-kvh0e)

**Comment by gkatsanos** [comment] 2019-08-15 20:24
It does, but I'd like to hope the core of the issue is fixed so we don't rely on setTimeout...

**Comment by johnleider** [comment] 2019-08-31 00:26
Duplicate of #7021

**Closed by johnleider** 2019-08-31 00:26 UTC
Labels: triage

**Comment by gkatsanos** [comment] 2019-09-03 21:10
@johnleider I don't think it's duplicate. Mine is : "does not open" the other ticket is "stays open". Plus I don't use click.stop, I use the activator slot. Please have a look at the codepen.

**Comment by knidhi** [comment] 2019-09-14 09:42
@johnleider I am facing the same issue after upgrading to 2.0.15. Dialogs with menu have stopped working after upgrade.

**Comment by knidhi** [comment] 2019-09-14 14:15
I could open the dialog by adding prop ```close-on-content-click="false"```
codepen: https://codepen.io/nidhik/pen/zYOLrOW

I can live with the open menu, rather than the setTimeout
