### ISSUE TITLE
[Bug Report] v-combobox item selection using keyboard

### ISSUE THREAD

**Issue by mouse9** [vuetifyjs/vuetify#10253] opened 2020-01-17 07:50 UTC
### Environment
**Vuetify Version:** 2.2.4
**Last working version:** 1.5.22
**Vue Version:** 2.6.10
**Browsers:** Chrome 72.0.3626.109
**OS:** Linux x86_64

### Steps to reproduce
1. Search something in  combobox ( in which multiple selection is allowed)
2. Select any entry using keyboard and press enter

### Expected Behavior
only selected item should be selected

### Actual Behavior
Item and free text both are getting selected

### Reproduction Link
<a href="https://codepen.io/yganatra1/pen/bGNxXQX?editable=true&editors=101" target="_blank">https://codepen.io/yganatra1/pen/bGNxXQX?editable=true&editors=101</a>

**Comment by johnleider** [comment] 2020-01-17 19:30
Duplicate of #8841 

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-17 19:30 UTC
Labels: triage
