### ISSUE TITLE
[Bug Report][2.6.4] Wrong item highlighted when using prepend-item slot on v-select

### ISSUE THREAD

**Issue by harrison-childs** [vuetifyjs/vuetify#14957] opened 2022-04-14 08:41 UTC
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Chrome 99.0.4844.51
**OS:** Windows 10

### Steps to reproduce
- Create a v-select with items
- Add a component into the **prepend-item** slot
- Select any item from the list by using mouse and the wrong item is highlighted

### Expected Behavior
The item that is selected using the mouse is the one that is highlighted.

### Actual Behavior
In the codepen example attached, when selecting any item on the list, the highlighted item will always be 2 above the one that was clicked. This appears to be because there are 2 components in the template used in the prepend-item v-slot (v-list-item and v-divider). 

It's like these prepended components are included in the index used to track the highlighted item, hence it's always off by *n* number of prepended components.

### Reproduction Link
<a href="https://codepen.io/harrison-childs/pen/bGaxOVq" target="_blank">https://codepen.io/harrison-childs/pen/bGaxOVq</a>

### Other Comments
This behaviour is also occurring with other selection components like the v-combobox

**Comment by KaelWD** [comment] 2022-04-21 10:18
Duplicate of #14489

**Closed by KaelWD** 2022-04-21 10:18 UTC
Labels: S: triage
