### ISSUE TITLE
[Bug Report] v-autocomplete Readonly

### ISSUE THREAD

**Issue by gianbia** [vuetifyjs/vuetify#10209] opened 2020-01-13 16:53 UTC
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Windows 10

### Steps to reproduce
Click on arrow to open the autocomplete control.

### Expected Behavior
The control should be readonly

### Actual Behavior
The control is in write mode.

### Reproduction Link
<a href="https://codepen.io/gianbia/pen/NWPzwOZ?editable=true&editors=101" target="_blank">https://codepen.io/gianbia/pen/NWPzwOZ?editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment] 2020-01-13 16:57
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9960

**Closed by jacekkarczmarczyk** 2020-01-13 16:57 UTC
Labels: triage
