### ISSUE TITLE
[Bug Report] Select Outline Style Shows Caret on Mobile in Chrome

### ISSUE THREAD

**Issue by chadsaun** [vuetifyjs/vuetify#4695] opened 2018-07-23 16:06 UTC
### Versions and Environment
Vuetify: 1.1.8
Vue: 2.5.16
Browsers: Chrome Mobile
OS: iOS

### Steps to reproduce
Go to this Codepen on Chrome in iOS https://codepen.io/chadsaun/pen/PBprEM and select an item.

### Expected Behavior
When you touch to select an option a caret won't appear in the list of items and won't appear after you select an item.

### Actual Behavior
When you touch to select an option a caret will appear in the background of the list of items. Then after you select an item it will stay there and blink.

### Reproduction Link
https://codepen.io/chadsaun/pen/PBprEM

**Comment by blalan05** [comment] 2019-04-06 01:34
Not seeing this issue on Pixel 3 Chrome 72 and Vuetify 1.5.9. Is this still an issue on IOS and latest Vuetify?

**Comment by jacekkarczmarczyk** [comment] 2019-11-13 07:06
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4506?

**Comment by KaelWD** [comment] 2020-02-07 09:49
Yeah. iOS chrome is just safari with a different UI.

**Closed by KaelWD** 2020-02-07 09:49 UTC
Labels: C: VSelect, T: bug, help wanted
