### ISSUE TITLE
[Documentation] vDataTableHeader is missing

### ISSUE THREAD

**Issue by frbuceta** [vuetifyjs/vuetify#10453] opened 2020-02-04 17:52 UTC
### Environment

**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.3

### Steps to reproduce
Simply missing from the list of components

### Expected Behavior
To appear

### Actual Behavior
No functionality

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/data-tables#api" target="_blank">https://vuetifyjs.com/en/components/data-tables#api</a>

### Other comments
<small>I don't understand how to create such an issue and put this ...</small>

**Comment by jacekkarczmarczyk** [comment] 2020-02-04 17:56
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9402

**Closed by jacekkarczmarczyk** 2020-02-04 17:56 UTC
Labels: triage
