### ISSUE TITLE
[Bug Report] Textfields don't get focus when v-dialog is opened.

### ISSUE THREAD

**Issue by UsmanJavedAttari** [vuetifyjs/vuetify#10363] opened 2020-01-28 16:03 UTC
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Open the Link.
Click on "Open Dialog".
and then try to focus on any input field (the default one and the `v-text-field`).

### Expected Behavior
The fields should be focused.

### Actual Behavior
The fields don't get focus, but the first button in the `v-dialog` gets focus.

### Reproduction Link
<a href="https://codepen.io/inyourface/pen/yLyrWxw" target="_blank">https://codepen.io/inyourface/pen/yLyrWxw</a>

### Other comments
I am using v-dialog and the problem I am facing is that whenever I try to focus any input field whether it's a default `input` or `v-text-field`, the first button in the v-dialog gets focus.
**and if you try to remove the buttons the fields will be focused.**

**Comment by escapedcat** [comment] 2020-01-29 01:49
Might be this https://github.com/vuetifyjs/vuetify/issues/8845#event-2987171751

**Comment by johnleider** [comment] 2020-01-29 04:15
Duplicate of #8845

**Comment by UsmanJavedAttari** [comment] 2020-01-29 04:33
@johnleider can you please explain why my issue is closed?

**Comment by UsmanJavedAttari** [comment] 2020-01-29 04:37
@johnleider can you please explain why my issue is being closed? Have you seen the codepen? I don't have any auto-focus on the inputs. **The issue you mentioned is for input field in the dialog, my issue is all about outside the `v-dialog`.** 
Opening this issue.

**Comment by jacekkarczmarczyk** [comment] 2020-01-29 04:42
It might be duplicate of https://github.com/vuetifyjs/vuetify/issues/8640 tho

**Comment by jacekkarczmarczyk** [comment] 2020-01-29 04:45
Duplicate of #8640

Workaround: https://codepen.io/jkarczm/pen/zYxQKMJ

**Closed by jacekkarczmarczyk** 2020-01-29 04:45 UTC
Labels: C: VTextField, triage
