### ISSUE TITLE
[Bug Report] Radio v-icon not clickable

### ISSUE THREAD

**Issue by TheBraveBunny** [vuetifyjs/vuetify#11037] opened 2020-04-05 23:35 UTC
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
1) Make a v-radio-group with choices in it.
2) Try to change the selected radio by clicking on an icon (the actual radio).
3) Be sad because it doesn't change the selected radio.
4) Try to change the selected radio by clicking on the label text of the radio.
5) Be confused because that works properly.

### Expected Behavior
If you have a v-radio-group with two v-radio in it, you should be able to click on either the VIcon or the VLabel to change the radio selection.

### Actual Behavior
If I click the VLabel part of the v-radio, the @change for that v-radio gets emitted. If I click the VIcon part of the v-radio, nothing gets emitted. Hovering over the VIcon gives me a gray circle instead of the expected blue one. In the Vue Tools tab, VIcon.data.listeners$ is an empty object.

### Reproduction Link
<a href="https://codepen.io/emmacaraher/pen/RwPzYvo" target="_blank">https://codepen.io/emmacaraher/pen/RwPzYvo</a>

### Other comments
I don't know how to isolate it into a Codepen example, but the link has the actual code for the radio. However, it's inside multiple layers of v-cards and v-containers, so I'm not sure if that is affecting anything.

**Comment by jacekkarczmarczyk** [comment] 2020-04-06 04:15
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

- [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
- [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
- [Codepen](https://template.vuetifyjs.com/)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by KaelWD** [comment] 2020-04-06 04:56
Possible duplicate of #5968

**Comment by jacekkarczmarczyk** [comment] 2020-04-21 05:58
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

**Closed by jacekkarczmarczyk** 2020-04-21 05:58 UTC
Labels: C: VRadio, S: needs reproduction

**Comment by Aymkdn** [comment] 2020-04-26 08:33
I've the same issue (radio buttons inside a card, with radio-group outside of the card), but I cannot reproduce the issue in Codepen either…

I resolved it by adding the below CSS rule:
```css
input[type='radio'] ~ .v-icon {
  pointer-events: none;
}
```

**Comment by TheKinng96** [comment] 2023-07-11 00:00
it happens only on mobile, need to let mobile connect to the local environment to test
