### ISSUE TITLE
[Bug Report] auto-select-first on v-combobox prevents new items from being created

### ISSUE THREAD

**Issue by andriasmelianus** [vuetifyjs/vuetify#11956] opened 2020-07-29 04:56 UTC
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Firefox 78.0
**OS:** Linux x86_64

### Steps to reproduce
Follow the codepen link below and type new country name.

### Expected Behavior
New country name (new item) should be added to the selected items, in this case selectedRecords, by hitting [enter] once. And no need to select the available item first.

### Actual Behavior
New country name (new item) added if you hit [enter] twice quickly after the available country is selected.

### Reproduction Link
<a href="https://codepen.io/andriasmelianus/pen/mdVYoBG" target="_blank">https://codepen.io/andriasmelianus/pen/mdVYoBG</a>

### Other comments
As the description of v-combobox, it should be able to enter values that do not exist within the provided items.

**Comment by KaelWD** [comment] 2020-07-29 08:26
Duplicate of #9270

**Closed by KaelWD** 2020-07-29 08:26 UTC
Labels: C: VCombobox, T: bug
