### ISSUE TITLE
[Bug Report] <v-select> item-text with array of strings don't work

### ISSUE THREAD

**Issue by henriq-88** [vuetifyjs/vuetify#7997] opened 2019-07-25 05:21 UTC
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
Create a `<v-select>`
Set an array of strings as `item` prop
Set a function to `item-text` prop

### Expected Behavior
The function inside `item-text` prop gets called and will display the transformed text

### Actual Behavior
The function inside `item-text` prop is ignored and never called

### Reproduction Link
<a href="https://codepen.io/henriq88/pen/JgKJOw" target="_blank">https://codepen.io/henriq88/pen/JgKJOw</a>

**Comment by jacekkarczmarczyk** [comment] 2019-07-25 05:30
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7328

**Closed by jacekkarczmarczyk** 2019-07-25 05:30 UTC
Labels: triage
