### ISSUE TITLE
[Bug Report][3.0.0-beta.3] [VTooltip] Hydration children mismatch when using loop

### ISSUE THREAD

**Issue by brownsugar** [vuetifyjs/vuetify#15307] opened 2022-06-15 17:46 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Vue Version:** 3.2.37
**Browsers:** Chrome 102.0.5005.61
**OS:** Mac OS 10.15.7
**Packages:**
 - Vue v3.2.37
 - Nuxt v3.0.0-rc.4
 - Vuetify v3.0.0-beta.3

### Steps to reproduce
1. Add a `v-tooltip` in `v-btn` just like the example in the [docs](https://next.vuetifyjs.com/en/components/tooltips/#examples)
2. Loop the buttons for 5 times using `v-for`

### Expected Behavior
The tooltips should render the contents through 1 to 5.

### Actual Behavior
All tooltips only rendered the content from the last element (which is 5 here).

### Reproduction Link
<a href="https://codesandbox.io/s/nuxt-3-vuetify-3-tooltip-issue-9j1bt0" target="_blank">https://codesandbox.io/s/nuxt-3-vuetify-3-tooltip-issue-9j1bt0</a>

### Other comments
I'm not sure why but the same reproduction code only works on [StackBlitz](https://stackblitz.com/edit/nuxt-vuetify-template-d1mkny?file=app.vue), the tooltip component does not even appeared on CodeSandbox.

Full output message:
```
[Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom. 
  at <VOverlay modelValue=false onUpdate:modelValue=fn<onUpdate:modelValue> class="v-tooltip"  ... > 
  at <VTooltip activator="parent" location="bottom" > 
  at <VBtn key=1 > 
  at <VContainer> 
  at <VApp> 
  at <App key=1 > 
  at <NuxtRoot>

[Vue warn]: Hydration node mismatch:
- Client vnode: Symbol(Text) 
- Server rendered DOM: <!--]-->  
  at <VBtn key=1 > 
  at <VContainer> 
  at <VApp> 
  at <App key=1 > 
  at <NuxtRoot>

[Vue warn]: Hydration children mismatch in <div>: server rendered element contains more child nodes than client vdom. 
  at <VBtn key=1 > 
  at <VContainer> 
  at <VApp> 
  at <App key=1 > 
  at <NuxtRoot>
```

**Comment by KaelWD** [comment] 2022-06-30 09:21
Duplicate of #15323

**Closed by KaelWD** 2022-06-30 09:21 UTC
Labels: S: triage
