### ISSUE TITLE
[Bug Report][2.7.0] `v-autocomplete` keep selected value even when it's not in items after a change

### ISSUE THREAD

**Issue by CernyMatej** [vuetifyjs/vuetify#17794] opened 2023-07-12 14:20 UTC
### Environment
**Vuetify Version:** 2.7.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1) select an item in `<v-autocomplete />`
2) clear the `:items` array
3) the item remains selected

### Expected Behavior
the v-model value should be `null` when the selected item is no longer in the `:items` array

### Actual Behavior
the v-model value remains the same as before

### Reproduction Link
[https://codepen.io/matejcerny/pen/QWJaVRd](https://codepen.io/matejcerny/pen/QWJaVRd)

**Comment by KaelWD** [comment] 2023-07-12 14:29
Duplicate of #4000

**Closed by KaelWD** 2023-07-12 14:29 UTC
Labels: S: triage
