### ISSUE TITLE
[Bug Report] Editing Values in a sort-able column updates wrong row.

### ISSUE THREAD

**Issue by doublej42** [vuetifyjs/vuetify#10924] opened 2020-03-23 17:21 UTC
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
1. Goto https://vuetifyjs.com/en/components/data-tables/#content-editing
2. Sort by Iron %
3. Edit the value.
4. Note that it has sorted the data and is now editing a different value.

### Expected Behavior
Sorting needs to be disabled while a dialog if open or you have to not update the value as you type.

### Actual Behavior
It sorts the table so if I am editing row 1 and I type 99 it will change the value I'm editing.

### Reproduction Link
<a href="https://codepen.io/doublej42/pen/ZEGMdyW" target="_blank">https://codepen.io/doublej42/pen/ZEGMdyW</a>

### Other comments
Also sorting a column while a dialog is open changes the value it's editing so I can go from editing 1% to 99%

**Comment by MajesticPotatoe** [comment] 2020-03-23 17:36
Duplicate of #3468 / #7149

**Closed by MajesticPotatoe** 2020-03-23 17:36 UTC
Labels: triage

**Comment by doublej42** [comment] 2020-03-23 23:18
> Duplicate of #3468 / #7149

It is a duplicate of #3468 but not #7149. 

Looks like it won't be fixed as the feature is going away in V3

https://github.com/vuetifyjs/vuetify/issues/3468#issuecomment-576029642
