### ISSUE TITLE
[Bug Report] Could not find a declaration file for module 'vuetify'

### ISSUE THREAD

**Issue by ZexuIsMe** [vuetifyjs/vuetify#17274] opened 2023-05-03 08:59 UTC
### Environment

**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
// vuetify
import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'

const vuetify = createVuetify({
    components,
    directives
})

### Expected Behavior
Compilation Successful.

### Actual Behavior
Received the following error message during "npm run dev":

'D:/My Project/image-web-dev/node_modules/vuetify/lib/framework.mjs' implicitly has an 'any' type.
  There are types at 'D:/My Project/image-web-dev/node_modules/vuetify/lib/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vuetify' library may need to update its package.json or typings.

### Reproduction Link
[]()

**Comment by KaelWD** [comment] 2023-05-03 09:04
Duplicate of #15885

**Closed by KaelWD** 2023-05-03 09:04 UTC
Labels: S: triage

**Comment by ZexuIsMe** [comment] 2023-05-03 09:37
The problem has been solved, thank you very much.

**Comment by ZexuIsMe** [comment] 2023-05-03 09:38
> Duplicate of #15885
The problem has been solved, thank you very much.
