### ISSUE TITLE
[Bug Report] TABS get fixed-tabs props in all cases with MS EDGE

### ISSUE THREAD

**Issue by germsb** [vuetifyjs/vuetify#3907] opened 2018-04-23 16:31 UTC
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.16
**Browsers:** Microsoft Edge
**OS:** Linux x86_64

### Steps to reproduce
[See your exemples ](https://vuetifyjs.com/en/components/tabs)
![Imgur](https://i.imgur.com/Pplltsv.png)

### Expected Behavior
Tab wrap the content by default 

### Actual Behavior
Tab get fixed-tabs props in all cases with MS EDGE

### Reproduction Link
[https://codepen.io/anon/pen/xjZpdM?&editors=101](https://codepen.io/anon/pen/xjZpdM?&editors=101)

**Comment by praveenpuglia** [comment] 2018-04-24 07:15
oddly enought, `flex: 0 1 auto` still makes the box grow and take up space in MS Edge! Browser bug? most likely a nested flex bug?

**Comment by KaelWD** [comment] 2018-04-24 07:46
Duplicate of #3211

**Closed by KaelWD** 2018-04-24 07:46 UTC
