### ISSUE TITLE
[Bug Report] Change event retard updating the model in v-autocomplete

### ISSUE THREAD

**Issue by massimolavermicocca** [vuetifyjs/vuetify#6268] opened 2019-01-26 16:51 UTC
### Versions and Environment
**Vuetify:** 1.4.3
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Linux x86_64

### Steps to reproduce
Select any object from the list

### Expected Behavior
Selecting any object from the list, model contains selected object.

### Actual Behavior
Selecting any object from the list, model is empty object.

### Reproduction Link
<a href="https://codepen.io/anon/pen/rPeNBQ" target="_blank">https://codepen.io/anon/pen/rPeNBQ</a>

### Other comments
Hello Guys,
thanks for the incredible work on vuetify!
I am experiencing the following problem:
When I select an object from the autocomplete, the event 'change' fires the method printing the model, but using 'return-object' it shows an empty object.

Another strange behavior I am experiencing, I believe is related to this, is when using the deletable-chips property. The property should clear the model returning empty object but sometimes it's returning null or is not affecting the model. If is required I will open another issue for this.

Thank you so much!

**Comment by jacekkarczmarczyk** [comment] 2019-01-26 16:52
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6136

**Closed by jacekkarczmarczyk** 2019-01-26 16:52 UTC
