### ISSUE TITLE
[Bug Report] Text opacity classes don't inherit component level dark theme

### ISSUE THREAD

**Issue by mvirkkunen** [vuetifyjs/vuetify#12179] opened 2020-09-04 21:49 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Linux x86_64

### Steps to reproduce
Use a `dark` attribute on a component in a generally light themed application and then use classes such as `text--primary` inside the component.

### Expected Behavior
The text color should change according to the component theme.

### Actual Behavior
The text color always follows the application level theme and lack of contrast makes it hard to read.

### Reproduction Link
<a href="https://codepen.io/mvirkkunen/pen/MWyOxwM" target="_blank">https://codepen.io/mvirkkunen/pen/MWyOxwM</a>

### Other comments
This is probably related to [this bit in VApp.sass](https://github.com/vuetifyjs/vuetify/blob/ec7b2e4dacacd247becf15f3f29f5f9fb3e64ba3/packages/vuetify/src/components/VApp/VApp.sass#L3). The resulting selectors look like `.theme--light.v-application .text--primary`, so the text opacity classes only follow the application level theme.

**Comment by KaelWD** [comment] 2020-10-07 08:21
Duplicate of #12010

**Closed by KaelWD** 2020-10-07 08:21 UTC
Labels: sass, triage
