### ISSUE TITLE
[Bug Report] Navigation drawer closed by mouseup outside the navigation drawer

### ISSUE THREAD

**Issue by NikolayCherniy** [vuetifyjs/vuetify#11681] opened 2020-06-19 07:36 UTC
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 83.0.4103.61
**OS:** Linux x86_64

### Steps to reproduce
1. Type some text in a text field (inside the navigation drawer)
2. Start to higlighting text
3. Mouseup outside the navigation drawer

### Expected Behavior
navigation drawer should not be closed

### Actual Behavior
navigation drawer is closed

### Reproduction Link
<a href="https://codepen.io/nikolaycherniy/pen/VwePWPV?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fru%2Fcomponents%2Fnavigation-drawers%2F" target="_blank">https://codepen.io/nikolaycherniy/pen/VwePWPV?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fru%2Fcomponents%2Fnavigation-drawers%2F</a>

**Comment by Maddimax** [comment] 2020-12-04 14:33
Still occurs in 2.4.0_beta0

**Comment by KaelWD** [comment] 2020-12-05 07:42
This is likely caused by the click-outside directive and therefore a duplicate of #5886

**Closed by KaelWD** 2020-12-05 07:42 UTC
Labels: triage
