### ISSUE TITLE
[Bug Report][3.1.2] Vue3 autocomplete chip render bug

### ISSUE THREAD

**Issue by uranik777** [vuetifyjs/vuetify#16570] opened 2023-02-01 22:05 UTC
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Firefox 109.0
**OS:** Windows 10

### Steps to reproduce
1. select any item in list
2. in input field show chip with double text value

### Expected Behavior
-

### Actual Behavior
-

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UctuwjAQ/BXXl7QSJGppLwgQCKntB1TiQDiYZAkufsl2aBHKv3edhBJA7W13Zjw7u14e6cyYeF8CHdKRB2kE8zBJFSGjfZ8ZU5d1IxlXbdeQpdeZxgfg4QQTkglglq1FF9py486tYGsQ45TOuu/pmR9yjOFQsIzmTPCNtoqzqEeiuRbaslyH+hVLntfwG2hbNIoP+GYuFIuDllwV0epsPBkll5lPmyH8u1qtqZceJZ1jYOsyy40nDnwZaC6Ntp4ciYUNqcjGakkivGIUxJlWzhPpCjIO/H30DkJostBW5HfRQzBv7NCI9mjjhSFM/Om0wo84hixpS7iUDkmNBAxnhD6lW++NGyZJqcyuiHGpZIpcYkvluYR+ruV0ED/Fzy9Jzp3v4jE42V9b/eXA4sSU9jrmnm8Ofw1oafR9jAeNbQsFyxurBP33YPsWVA4W7L+5r7QX2a+4m/xhZpWqCm8puNq5qzNmrj7hchUkVY821iiu96CrH4IA+5U=)

### Other comments
screenshot - https://forum.vuejs.org/t/vue3-next-vuetifyjs-com-v-autocomplete-bug-with-chips/135299

**Comment by mhio** [comment] 2023-02-19 09:39
I think this is the same https://github.com/vuetifyjs/vuetify/issues/16186

**Comment by KaelWD** [comment] 2023-04-27 09:06
Duplicate of #16186

**Closed by KaelWD** 2023-04-27 09:06 UTC
Labels: T: bug, C: VAutocomplete
