### ISSUE TITLE
[Feature Request] set max-height in v-input and v-text-field

### ISSUE THREAD

**Issue by wongtalawan** [vuetifyjs/vuetify#9222] opened 2019-10-04 02:04 UTC
### Problem to solve
cant set max-height in v-input and v-text-field it default input max-height: 32px,
It is not flexible to use.

### Proposed solution
add API property or do something to set max-height

**Comment by jacekkarczmarczyk** [comment] 2019-11-13 07:30
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9123 ?

**Comment by wongtalawan** [comment] 2019-11-13 08:55
yes

**Closed** 2019-11-13 09:04 UTC
Labels: C: VTextField, triage
