### ISSUE TITLE
[Feature Request] Double data-tables expanding row toggling 

### ISSUE THREAD

**Issue by brandiwerner** [vuetifyjs/vuetify#5123] opened 2018-09-19 21:26 UTC
### Problem to solve
When there are two data-tables on the same page there is no way that I have found to toggle the expandable rows between the tow tables. What I need to happen is when table 1 has a row expanded I need this row to collapse when the user expands a row on table 2 and vice versa. Here is a codepen with the closest I could get to a solution:  https://codepen.io/BrandiW/pen/WgLPej?editors=1010  As you can see in this codepen I am using a variable called Expanded to currently hide the v-card in the extended row that needs to be shut, but the problem is that it is not actually shutting this row. Thus if you want to open this row back up, you have to double click it (once to shut it and another time to reopen it).

### Proposed solution
I have yet to find an elegant solution to this problem.

**Comment by nekosaur** [comment] 2018-09-20 07:52
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2890

(Not really, but this can be solved by the proposed solution in that issue)

**Closed by nekosaur** 2018-09-20 07:52 UTC
Labels: duplicate

**Comment by VinceWilkie** [comment] 2018-09-20 13:50
There is a simple way to control the expansion of rows by saving `props` to a local variable.
Codepen solution: (https://codepen.io/vincentwilkie/pen/GXzOQx?editors=1010)
