### ISSUE TITLE
[Bug Report][2.5.1] date picker in menu does not open when clicking on text field label

### ISSUE THREAD

**Issue by jimmykodes** [vuetifyjs/vuetify#13711] opened 2021-05-27 00:14 UTC
### Environment
**Vuetify Version:** 2.5.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.212
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click directly on either label in the text box and the date picker does not actually open

### Expected Behavior
The menu should open displaying the datepicker

### Actual Behavior
the label moves up to its intended position, but the menu does not actually pop open

### Reproduction Link
<a href="https://codepen.io/jimmykodes/pen/poerezR" target="_blank">https://codepen.io/jimmykodes/pen/poerezR</a>

### Other comments
that codepen is straight from the vuetify docs, on this page here:
https://vuetifyjs.com/en/components/date-pickers/#formatting
where the issue is also present.

As you can see, this screen recording is coming straight from the vuetify docs page, displaying the issue:
https://user-images.githubusercontent.com/37089863/119746587-a4182a00-be45-11eb-80b0-bb98489b8a23.mov

**Comment by ryanrapini** [comment] 2021-06-04 19:38
Also encountering this issue. Can confirm it is reproducible right in the docs.

**Comment by KaelWD** [comment] 2021-06-05 09:15
Duplicate of #7610

**Closed by KaelWD** 2021-06-05 09:15 UTC
Labels: triage
