### ISSUE TITLE
[Bug Report][3.1.10] wrong place for "v-menu" in all related components in RTL mode

### ISSUE THREAD

**Issue by mahsarajabpour** [vuetifyjs/vuetify#16946] opened 2023-03-18 07:29 UTC
### Environment
**Vuetify Version:** 3.1.10
**Last working version:** 3.1.10
**Vue Version:** 3.2.45
**Browsers:** Chrome 99.0.4844.84
**OS:** Linux x86_64

### Steps to reproduce
based on reproduction link.

### Expected Behavior
If `rtl` mode is true, the `v-menu` should be opened first at the `rtl` location.

### Actual Behavior
If `rtl` mode is true, the `v-menu` opens first at the `ltr` location.

### Reproduction Link
[https://codepen.io/mahsaaarajabpour/pen/qBMyaBa?editors=1010](https://codepen.io/mahsaaarajabpour/pen/qBMyaBa?editors=1010)

### Other comments
affected components:
-   v-menu
-   v-combobox
-   v-tooltip
-   v-select
-   v-autocomplete

**Comment by KaelWD** [comment] 2023-03-20 11:00
Duplicate of #16628

**Closed by KaelWD** 2023-03-20 11:00 UTC
Labels: S: triage
