### ISSUE TITLE
[Feature Request] Ability to provide custom counter text for v-text-field

### ISSUE THREAD

**Issue by downace** [vuetifyjs/vuetify#4370] opened 2018-06-22 05:41 UTC
### Problem to solve
Sometimes we need to display additional text in counter. For example, words count is useful for Google Ads API interfaces where words count is limited

### Proposed solution
Allow `counter` property to be an arbitrary string that will not be converted to number but just displayed to user.

Or allow placing `hint` in place of `counter` (e.g. via `hint-align` property).

**Comment by johnleider** [comment] 2019-06-19 15:46
I'm not opposed to this but unfortunately did not make the cut for v2.0.  We do something similar with data-table `1 of 15` that is an editable prop that we could potentially mimic the behavior.

**Comment by bad4iz** [comment] 2020-01-15 06:16
Duplicate of #9548
here perhaps a better description of the issue

**Closed by bad4iz** 2020-01-15 06:16 UTC
Labels: C: VTextField, T: feature, duplicate, help wanted
