### ISSUE TITLE
[Bug Report] Text not visible in v-carousel

### ISSUE THREAD

**Issue by dirk-ecker** [vuetifyjs/vuetify#11961] opened 2020-07-30 08:43 UTC
### Environment
**Vuetify Version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Opera 68.0.3618.197
**OS:** Windows 10

### Steps to reproduce
Simply look at the pen.

### Expected Behavior
The text in the resulting page should be shown using the default color.

### Actual Behavior
In the result page nothing of the text is visible because of the styling for the outer div that sets color to white.

### Reproduction Link
<a href="https://codepen.io/dirk-ecker/pen/bGEPaeN" target="_blank">https://codepen.io/dirk-ecker/pen/bGEPaeN</a>

**Comment by dirk-ecker** [comment] 2020-07-30 09:39
A workaround is to use the `light` property with `!this.$vuetify.theme.dark`:

`:light="!this.$vuetify.theme.dark"`

**Comment by Danielg212** [comment] 2020-08-04 10:24
+1 
it's a bug, v-carousel add dark-theme class as default.

**Comment by flukedev8** [comment] 2021-05-29 17:47
> A workaround is to use the `light` property with `!this.$vuetify.theme.dark`:
> 
> `:light="!this.$vuetify.theme.dark"`

cofig in:
`      <v-carousel
        :light="!this.$vuetify.theme.dark"
      >
      .......
     </v-carousel>`

Wow it worked. Thx so much 😁😄🤗 +1

**Comment by KaelWD** [comment] 2021-05-29 18:15
Duplicate of #13656

**Closed by KaelWD** 2021-05-29 18:15 UTC
Labels: triage
