### ISSUE TITLE
[Bug Report] v-text-field height props not work...

### ISSUE THREAD

**Issue by ksbgenius** [vuetifyjs/vuetify#8984] opened 2019-09-17 02:02 UTC
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
I set rounded, outlined, height="24", single-line

input text height reduce

but outer wrapper is not change height

### Expected Behavior
all height change

### Actual Behavior
component height change

### Reproduction Link
<a href="https://codepen.io/ksbgenius/pen/pozOROj?&editable=true&editors=101" target="_blank">https://codepen.io/ksbgenius/pen/pozOROj?&editable=true&editors=101</a>

### Other comments
i just reduce component height

height props just input text field 

cannot adjust component height?

**Comment by KaelWD** [comment] 2019-09-17 05:28
Duplicate of #5216

**Closed by KaelWD** 2019-09-17 05:28 UTC
Labels: triage
