### ISSUE TITLE
[Bug Report] Progress bar does not sync value

### ISSUE THREAD

**Issue by Isatol** [vuetifyjs/vuetify#7630] opened 2019-06-21 19:12 UTC
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.7
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
Both values, total and iteraciones must be the same. Click on the button and the progress will start. 

### Expected Behavior
The width of the progress must be equal to valueDeterminate

### Actual Behavior
The width of vuetify progress bar is not the same as the actual progress.

### Reproduction Link
<a href="https://jsfiddle.net/Isatol/1a2rnhvt/26/" target="_blank">https://jsfiddle.net/Isatol/1a2rnhvt/26/</a>

### Other comments
I created a new progress bar to simulate real progress, and it works. This jsfiddle is a simulation of what I am working on. Push a new element in the array and add a new percentage of progress

**Comment by jacekkarczmarczyk** [comment] 2019-06-22 08:04
Progress is delayed because of the transition. Probably there could be a prop setting the transition duration (and optionally easing pattern) or just a transition

**Comment by johnleider** [comment] 2019-06-24 14:38
Duplicate of #3453

**Closed by johnleider** 2019-06-24 14:38 UTC
Labels: triage
