### ISSUE TITLE
[Feature Request] `ThemeDefinition` is not exported

### ISSUE THREAD

**Issue by HippolyteQuief** [vuetifyjs/vuetify#13949] opened 2021-07-20 09:15 UTC
### Problem to solve
In the doc, it is said we can import `ThemeDefinition` but got an error. When checkink `entry.d.ts`, we can see this definition is not exported. 

### Proposed solution
Export `ThemeDefinition` and `ThemeOptions` and `VariationsOptions` or update the doc without `ThemeDefinition`

**Comment by KaelWD** [comment] 2021-07-20 09:28
Duplicate of #13901

**Closed by KaelWD** 2021-07-20 09:28 UTC
Labels: S: triage
