### ISSUE TITLE
v-radio-group can not update data to v-model when get items from async

### ISSUE THREAD

**Issue by guanxudong** [vuetifyjs/vuetify#1820] opened 2017-09-20 10:06 UTC
### Steps to reproduce
get v-radio items data from async

### Versions

v0.15.7

### What is expected ?

v-radio-group will update with selected radio value

### What is actually happening ?

v-radio-group nothing happened

### Reproduction Link

https://codepen.io/guanxudong/pen/OxNoRX?editors=1010#0

**Comment by jacekkarczmarczyk** [comment] 2017-09-20 10:20
Looks like duplicate of https://github.com/vuetifyjs/vuetify/issues/1798

**Closed** 2017-09-20 10:20 UTC
