### ISSUE TITLE
[Bug Report] v-data-table row expansion broken with virtual-rows enabled

### ISSUE THREAD

**Issue by gorsat** [vuetifyjs/vuetify#7862] opened 2019-07-18 03:32 UTC
### Versions and Environment
**Vuetify:** 2.0.0-beta.8
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
create a v-data-table with expansion rows and virtual rows

### Expected Behavior
rows expand as usual
(or they don't expand at all and it's documented)

### Actual Behavior
rows don't expand when you click on them
then, if you change the number of rows per page, you'll see that all the rows you had clicked on before are now expanded

### Reproduction Link
<a href="https://codepen.io/OGCoder/pen/EqxaeG" target="_blank">https://codepen.io/OGCoder/pen/EqxaeG</a>

**Comment by KaelWD** [comment] 2019-07-23 09:22
Duplicate of #7591

**Closed by KaelWD** 2019-07-23 09:22 UTC
Labels: triage
