### ISSUE TITLE
[Bug Report] Footer for VDataIterator overlaps itself in IE

### ISSUE THREAD

**Issue by ScottSEA** [vuetifyjs/vuetify#10879] opened 2020-03-18 17:24 UTC
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Create a VDataIterator or VDataTable with a footer.  View it in IE11.

### Expected Behavior
It should look like it does in all the other browsers

### Actual Behavior
It overlaps itself and the dropdown "ItemsPerPage" doesn't have any elements showing as shown in [this screenshot](https://imgur.com/a/0ProQPD).

### Reproduction Link
<a href="https://github.com/PleaseSeeComments" target="_blank">https://github.com/PleaseSeeComments</a>

### Other comments
See [this screenshot](https://imgur.com/a/0ProQPD)

**Comment by ElijahKotyluk** [comment] 2020-03-18 21:24
Duplicate of #9185

**Closed** 2020-03-18 21:33 UTC
Labels: duplicate, triage
