### ISSUE TITLE
[Bug Report][2.5.10] v-autocomplete selection menu stays fixed during inner scrolling

### ISSUE THREAD

**Issue by fbe106360** [vuetifyjs/vuetify#14689] opened 2022-02-04 07:05 UTC
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Google Chrome, Chrome 96.0.4664.175, Mozilla Firefox, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
- Create a container with a fixed height, and add overflow (see codepen).
- Place several v-autocompletes in the container so that you get an inner scroll bar.
- Open the items of a v-autocomplete and start scrolling through the container. 

### Expected Behavior
The selection items of the v-autocomplete should stay attached to the opened autocomplete and should move with it when scrolling.

### Actual Behavior
The menu of the v-autocomplete stays fixed during inner scrolling and is not attached to the opened/focused autocomplete

### Reproduction Link
<a href="https://codepen.io/fbeyeler/pen/dyZpXLp" target="_blank">https://codepen.io/fbeyeler/pen/dyZpXLp</a>

**Comment by KaelWD** [comment] 2022-02-04 07:15
Duplicate of #795

**Closed by KaelWD** 2022-02-04 07:15 UTC
Labels: S: triage

**Comment by wtser** [comment] 2022-03-15 05:10
same problem to me
