### ISSUE TITLE
[Feature Request][3.3.9] datatable

### ISSUE THREAD

**Issue by kazuihitoshi** [vuetifyjs/vuetify#17849] opened 2023-07-21 00:40 UTC
### Environment
**Vuetify Version:** 3.3.9
**Vue Version:** 3.2.37
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
# Table responsive
Reducing the width does not result in a responsive display

### Expected Behavior
When the width is reduced, it is written vertically as a response jib.

### Actual Behavior
A horizontal scroll bar appears, and the full picture cannot be seen without scrolling operation.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtlm1P2zAQx7+KFWkCJJL0GYg6xAR7YOzF3k6UF25yLR6OHdluWYf63Xdu0jZxk9JKy6v4zv/z7852co9v3qcsC+Yz8CJvaCDNODVwPRKEDOd+Qg31DR1zsAZC5n4qE+AfR54GDrGBZOTlnugZaAJKo6t423gYRrX2BLQGZTYOa/fnlM8AnYKmsHboZ/nq5wvkhphTbSOgaU4Nk8Jv53Ovh2EZErGHYSkHHOpYscys8oE/mVSGJDChM27IWx7bqsnp2XpIiAIzU2I7Rp4i14g8Pp1vzUWeaN3aSFlnH8MMh4ic3OXJk9N2qzXFiGrOxPTspBTOPpSzqcDZ2lBlXKdGeptlRCaUa3C8L7BAoS1jVbesjN42QLeUS8VAn5wX0nhtaJR8ochvoQvFhJrmybdUjXVlemwtzYKfShpgoiLJcluz6F5JVHzYKhgaqtPLW7Y+gvv3zBbRpqvkXxDkl5zOdjdjXa2ItPtXjg/rEpFB0NqRYP4R6fQce5FkRHo7EpsNrrBvQ2vR72MgsQKaEk1F8sri52b+Tveijv+qiX9neom/+5/4P+ONZ2oP86BTx9xuLrpLtoHeleTQ1SwPgb6dZTF9ca5fmbrb6tdRdwO3ogX04OhKXx4N/RU/Q6DGeFaSPeD9wXHl7rlXYkPeDVxXcUaqKxyC/h04X5AxULGH/KK25K0m8KvGy7krycGr1kO4f0jOWSazPdRXtce7FbjmNXV138vUtczVMIcwf5MCFrFMx83QvZZLUZzuBujLxtM9CNxNy7F7VfMh3HdSzPZ8u3v92kJ3+k3no1/9llWuZP3B7hxf7AdmHvDX2kjdb9dWutN4HQduPTfU7h7kzM13cfszXeYvuRMHw7BotbxzjzPxooPfWgpsKlc5jrxYY+O3+e9il2hMpqMwjBOBM7GpZHMVCDChyNIQ21HDJoubboDfizBh2qxNPqdjHayC2UhPI7HEBVlqWzs/pZmzau5YrVzUeuRhJDt+B+EGp4VqJgxLwU9kumLp5SwlcwA69cdKvmJfgUFGXlGg1TIW+ICl3ssWl9gJHdoWEpSvQGATCurQjBxZOSvHtZNZsdFLb3nurWRY+BWy9/QPkUMvNg==)

### Other comments
I really liked the responsive design that was supported by Datatable in vuetify2.
I expected the same behavior in vuetify3, but it does not seem to have the responsive behavior.

Datatable for vuetify3
https://vuetifyjs.com/en/components/data-tables/basics/
The overflowing part is referenced by a horizontal scrollbar
datatable for vuetify2 
https://v2.vuetifyjs.com/en/components/data-tables/
Vertical scrolling, one-page reference
Is this a future work?
We would also like to know if there is any limited release module that addresses this issue.

**Comment by KaelWD** [comment] 2023-09-25 13:11
Duplicate of #16784

**Closed by KaelWD** 2023-09-25 13:11 UTC
Labels: S: triage
