### ISSUE TITLE
[Bug Report] Navigation drawer overlay not covering App bar

### ISSUE THREAD

**Issue by Julius2001** [vuetifyjs/vuetify#8196] opened 2019-07-30 19:39 UTC
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Create App with temporary Navigation drawer and App bar.

### Expected Behavior
The Navigation drawer's overlay should cover every other element except the Navigation drawer itself.

![expected](https://user-images.githubusercontent.com/27251239/62159550-4a5e7b80-b312-11e9-932d-b198e3d3e9a4.jpg)

### Actual Behavior
The overlay does not cover the App bar.

![actual](https://user-images.githubusercontent.com/27251239/62159566-51858980-b312-11e9-8c23-5f71065f4ec3.jpg)

### Reproduction Link
<a href="https://codepen.io/anon/pen/zgwvMK" target="_blank">https://codepen.io/anon/pen/zgwvMK</a>

**Comment by KaelWD** [comment] 2019-08-06 03:54
Duplicate of #8040

**Closed by KaelWD** 2019-08-06 03:54 UTC
Labels: C: VNavigationDrawer, T: bug, T: regression
