### ISSUE TITLE
[Bug Report][3.7.0]  v-treeview attribute select-strategy = "classic" fails when item-children Prop Is passed

### ISSUE THREAD

**Issue by Marcellia** [vuetifyjs/vuetify#20346] opened 2024-08-16 03:44 UTC
### Environment
**Vuetify Version:** 3.7.0
**Vue Version:** 3.4.27
**Browsers:** Chrome 126.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open the playground for Selectable Icons: Visit the Vuetify Treeview #selectable-icons documentation (https://vuetifyjs.com/en/components/treeview/#selectable-icons). In the playground, provide a custom list where the dependents or another key is used to represent the children. Add the item-children attribute to the <v-treeview> component to specify the key for child items (e.g., dependents). Additionally, set the select-strategy to "classic".

### Expected Behavior
classic: Selecting a parent node will cause all children to be selected, parent nodes will be displayed as selected if all their descendants are selected. Only leaf nodes will be added to the model.

### Actual Behavior
Selecting a parent node does not cause all children to be selected, leaf nodes are not added to the model.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9Vk1v4zYQ/SuEL94FzHidpmlrxEGTbYEetmjR7C32gZbGFhuKFEhKXjfIf++Q+qSkZB3sxyG2OTN8Q755M8z948ToaH6TZWdFDpPl5MpCmglm4XotCbkqaMR07H/7lVVKbJkmkRJKr9aTTPOU6eN6Qna4qYrDyBqFFNQIZZeZhgxkDVSB8UhJYizT9jqNOTVcFKAPTMPVvHRieLChyk4ttwKuP6iICZIoazL8c3tCf3OYeXAnZ2hCmwyIrtWh3YMXVyI8rmOCWvjUXrM+lgYoOBy6ZoI3T1UMYmlAQGQhRrZc4HoShi05ns6g03/3vc5Io4SLWIPEoNjTCNIOIndMGPCsYZijc6vUA9bmgarcCi4HiTniWNApl8jM6EZ05eMn8gRjuGTpENcFFEzkLoDHfXdJBzVWY9r9EWMiwYzhUT/Q6nz0WP04DTbXkqrtv4g7lottBXTt177+Vc26JUbzsMbe6qXQ0UbMCx6DJqhXy1GFHrIyhpG41TWLK/DiHNskdTq4XE9OkhYi9jXFd5WOzgTIvU3IarUi7/qcPIAj1lep7/JsOydmo8kl2Slp6QH4PrFUuE/iPXsNR5IxelEuI5Qc6BArOCshd55sclS5RjEWSqMQyFbDATQHE9xrjhcLetuTYCKthKCfsDZMGm45Toe9VnlGEuSVKkkFsKLt65a9hGeh0TG18wPqTakBxJoR/hZFj7oaNiG2YUkZH/E4AtDVAJ2Nqb4lNmV0MeKtBqbjdeitxmMgd+jz7RXN/3NtZVImRN/rRei4CEWExhFmX6H7elXOx2Zc1nIfk34taeYJM92xurVYgpLRf8CAxZ4omOZMOotzoOHXSPDooRI6WZH7DTaMy4Obw/YyGYuqM1Q/AzfGt/dkWZ9j/GVR2NSgrLpsdooFksY4dPArKGp1g7vexvYm7jlsPZ3DB4x3+amNuAheLFxi/XhmcZzZvCwuTzOlLXnE4bebkQOzUUKeyE6rlEzxHZ+WJOD1jG1bEInE8Df3m7etsyJ4aD9m4xv8K1U7yts81rfk8ZIsZvXKdcmSTG+EILf1EaaNt33IlqTCCbBqvPNmRwfzvWY7O4b6AvIAvc7wQ7C7e/IU0SMmyYvpPpPSp/V5LmY18K3Gp0wcZQV5nM5ChA15GqSoUX5sUO6skuAhuNyfArHpWfoRo+xcPsfO77lWGXw1dn7qsAOH39RJN6o3/xxsRkbJX2kKe/Y1eOl6u56BUn8ZU+qfHEdv04FfJtTFu+dqUf4n/FKuk+uwWDRcfkyA3IgogZQb+5pyLM4bjD+AxUfyUeHo1d+xFouwqTviyPLtl5bh4rkyvOf26BthmOR0/tsGv8U3nuHI/Vtx+Tr+LxuMD2yfS24ZHufbkF9bS4t7Ka7m5XOFD9XkaSZzIfzH5n+wewL7)

**Comment by yuwu9145** [comment] 2024-08-16 04:54
It's because each leaf node has `item-children` "dependents" which make them as a parent node

https://play.vuetifyjs.com/#eNq1Vktv4zYQ/iuEL94FzHidpmlrxEGTbYEetmjR7C3OgZbGFhuKFEhKXjXIf++QelJS3HQfh9jmPDnffDPM/dPM6Gh5k2VnRQ6z9ezKQpoJZuF6Kwm5KmjEdOx/+5NVSuyYJpESSm+2s0zzlOlyOyN7dKrt0LKJQgpqhLLrTEMGsglUB+ORksRYpu11GnNquChAH5mGq2WlRPPAoc5OLbcCrj+oiAmSKGsy/HM+ob69zDKoyQla0zYDRtfq2Plg4UqE13VIUAufujKba2mAgsOxLyZYeapiEGsDAiILMaLlDLez0GzN8XYGlf57qHVCGiVcxBokGsUeRpB2ZLlnwoBHDc0cnDulHrE3j1TlVnA5SswxjgWdconITDqiKp++kQcYzSVLx3GdQcFE7gx4PFRXcFBjNaY9lGgTCWYMj4aGVueT1xraabC5llTt/sa4U7nYTkBffu37X/es32IUj3vspZ4KPW7EvOAxaIJ8tRxZ6EPWwtASXd2wuAavznFMUseDy+3sVdTCiENO8X3NozMB8mATstlsyLshJo/ggPVdGqo82k6J2WhySfZKWnoEfkgsFe6TeM1BQ0kyRi+qY4SUAx3GCu5KyJ0Hm5Qq10jGQmkkAtlpOILmYIK6llhYMNseBBNpJQT9hL1h0nDLcTsctMozkiCuVEkqgBXdXHfoJTwLhQ6pvV9QbyoOYKwF4W+R9Mir8RDiGFaQ8QmNAwBVbaCzKdZ3wKaMria09cJ0uI619XoM6A5DvD2j+T9urEzKhBhqPQkdFiGJUDiB7P/gfXOq9mO7Lhu6T1G/oTTzgJn+Wt1ZbEGF6F9gwOJMFExzJp3EKVDwcyR49FgTnWzI/QMOjMuDzuF4mYxF9R3qn4Ea7bs6WTbEGH9ZJDY1SKs+mr1mgaQxLh38CppaV3A3cOwqcc9hp+ldPkC8j08jxEPwYuER+8czi+vM5lVzeZopbckTLr/9ghyZjRLyTPZapWSO7/i8AgHLM7YbQQQSzd/cP7ztlDXAY3mZTTv4V6pRVNU8NVXyeE1Wi+bkpmRN5jdCkNvmCvNW2z1ka1LHCWI18c5bj17M95rt7VTUE5FH0ZsM3wXe/ZunGD1ikpxM9x8pfVqf52LRBL7V+JSJUtYhyzl5HoVsvL5vve6skuBduDxMuTwMJEOLyeovX6r+11yrDL5a9T/0qofjL2qygsb4x8AYESJ/pCkc2OfU3df2NSOm/TTFtN85rs52gr6MaKt3L2Fd/Sd7KtercV6tWuw+JkBuRJRAyo09BffqvPX5DVhcko8KV6X+hlivwqHrNTvLd18K88VLML/ntvREHid5Pb7dQN7iG8xwJf6puDyN72Xr84EdcsktM18L3EZaSdymvlpWzwU+FLPnhcyF8B8P/wJklNas

**Comment by KaelWD** [comment] 2024-08-16 07:57
Duplicate of #18172

**Closed by KaelWD** 2024-08-16 07:57 UTC
Labels: S: triage
