### ISSUE TITLE
[Bug Report][3.4.0] VDataTableVirtual does not react to changes in items after first (non-empty) item list is displayed

### ISSUE THREAD

**Issue by luddwichr** [vuetifyjs/vuetify#18663] opened 2023-11-12 11:57 UTC
### Environment
**Vuetify Version:** 3.4.0
**Vue Version:** 3.3.8
**Browsers:** Firefox 119.0
**OS:** Linux

### Steps to reproduce
Open [Playground](https://play.vuetifyjs.com/#eNp1kMFuwyAMhl/F8qWJtJBJ3WGK0mp9gD1B04NLqIpGEgQmlyjvPiCa1kN7AsOnz799XtA7WZ+sFXNQ2GDLarCGWB27EaCdK7I2X3Nx5RG+pNHy59ChjqgXNvh7scxkgmrgm/guHI39NBTlWnZ4PPU9bA+Q+LbOkn9jT0wV09WoataOAxlosvivQYdQP8NfYanDlrmtH2aJpZdOWwavOGwj6cFOjmEBp26wws3FkLu4hl36lNPoOWf2cEhEcb6USbppogDXN9yLvfjEdH6Id7z8ApSDbls=) and click on "Add random item". After the first click, both data tables are updated. After subsequent clicks, only `VDataTable` reacts to the changes of `items`.

### Expected Behavior
Items are always re-rendered by `VDataTableVirtual` after updates of `items`.

### Actual Behavior
The items are only rendered once by `VDataTableVirtual` and subsequent updates are ignored.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1kMFuwyAMhl/F8qWJtJBJ3WGK0mp9gD1B04NLqIpGEgQmlyjvPiCa1kN7AsOnz799XtA7WZ+sFXNQ2GDLarCGWB27EaCdK7I2X3Nx5RG+pNHy59ChjqgXNvh7scxkgmrgm/guHI39NBTlWnZ4PPU9bA+Q+LbOkn9jT0wV09WoataOAxlosvivQYdQP8NfYanDlrmtH2aJpZdOWwavOGwj6cFOjmEBp26wws3FkLu4hl36lNPoOWf2cEhEcb6USbppogDXN9yLvfjEdH6Id7z8ApSDbls=)

### Other comments
May be related to [this issue](https://github.com/vuetifyjs/vuetify/issues/18658)

**Comment by KaelWD** [comment] 2023-11-13 16:08
Duplicate of #18648

**Closed by KaelWD** 2023-11-13 16:08 UTC
Labels: S: triage
