### ISSUE TITLE
[Feature Request] 24px in Spacing playground

### ISSUE THREAD

**Issue by edbryanrosete** [vuetifyjs/vuetify#7727] opened 2019-07-02 20:04 UTC
### Problem to solve
Can we add a margins with 24px in size? currently there is only 5 sizes, which converted 0=0px, 1=8px, 2=16px, 3=32px, 4=48px, 5=64px

### Proposed solution
add 2.5=24px 

Please email me at edwinbryanrosete75@gmail.com for any questions or to know more details.

**Comment by jacekkarczmarczyk** [comment] 2019-07-07 09:54
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7733

**Closed by jacekkarczmarczyk** 2019-07-07 09:54 UTC
Labels: triage
