### ISSUE TITLE
[Bug Report] v-select with chips

### ISSUE THREAD

**Issue by Kleemer** [vuetifyjs/vuetify#6793] opened 2019-03-22 04:18 UTC
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.10
**Browsers:** Chrome 72.0.3626.121
**OS:** Mac OS 10.14.3

### Steps to reproduce
- Create a v-select with chips
- Type a long option in the select item list
- Choose this option

### Expected Behavior
If the text is too long, I want my chips to still be contained in the v-select, which means it should truncate the text (or allow the chip to grow vertically maybe?)

### Actual Behavior
The chip overflows and is breaking the layout

### Reproduction Link
<a href="https://codepen.io/Kleemer/pen/vPQMoo?&editable=true&editors=101" target="_blank">https://codepen.io/Kleemer/pen/vPQMoo?&editable=true&editors=101</a>

### Other comments
I don't know how new this is, I created my reproduction from the official v-select example with chips.

**Comment by jacekkarczmarczyk** [comment] 2019-03-22 04:37
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5584

**Closed by jacekkarczmarczyk** 2019-03-22 04:37 UTC
