### ISSUE TITLE
[Bug Report] VTextarea outlined scroll bug (Windows)

### ISSUE THREAD

**Issue by RP-KentaroAoki** [vuetifyjs/vuetify#12075] opened 2020-08-19 03:31 UTC
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Windows

### Steps to reproduce
None (just scroll in v-textarea)

### Expected Behavior
The scrollbar should not overlap the outline

### Actual Behavior
Scrollbar overlaps outline
![scroll](https://user-images.githubusercontent.com/69883661/90590513-b496d680-e21b-11ea-8dbc-a4cfcdc77961.png)

### Reproduction Link
<a href="https://codepen.io/KentaroAoki/pen/oNxzbEa?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fja%2Fcomponents%2Ftextarea%2F" target="_blank">https://codepen.io/KentaroAoki/pen/oNxzbEa?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fja%2Fcomponents%2Ftextarea%2F</a>

**Comment by johnleider** [comment] 2020-12-08 16:01
workaround: https://codepen.io/johnjleider/pen/BaLzbPY

**Comment by johnleider** [comment] 2020-12-08 16:06
Actually this is basically a duplicate of #6733. Closing in favor of that.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-08 16:06 UTC
Labels: C: VTextarea, T: bug
