### ISSUE TITLE
[Bug Report] mini-variant-width break layout

### ISSUE THREAD

**Issue by Dev1lDragon** [vuetifyjs/vuetify#9902] opened 2019-12-06 13:49 UTC
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
when use string in mini-variant-width, it break layout on resise

### Expected Behavior
mini-variant-width same output with number and string

### Actual Behavior
mini-variant-width="64" -> not break layout
mini-variant-width="64px" -> break layout

### Reproduction Link
<a href="https://codepen.io/dev1ldragon/pen/QWwjjdJ" target="_blank">https://codepen.io/dev1ldragon/pen/QWwjjdJ</a>

**Comment by johnleider** [comment] 2020-01-03 23:41
Workaround: https://codepen.io/johnjleider/pen/povdZZV

Duplicate of #9066

**Closed by johnleider** 2020-01-03 23:41 UTC
Labels: triage
