### ISSUE TITLE
[Bug Report] Failed to decode image, trying to render anyway

### ISSUE THREAD

**Issue by hackerESQ** [vuetifyjs/vuetify#11292] opened 2020-05-01 03:50 UTC
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Safari
**OS:** Mac OS 10.14.6

### Steps to reproduce
Use svg file in <v-img> and use Safari 13.0.1 browser. Review console and see Warn message.

### Expected Behavior
No warn message.

### Actual Behavior
Warning message:
```
[Vuetify] Failed to decode image, trying to render anyway

src: http://lumify.test/static/lumify_logo_white.svg
Original error: Invalid image type.

found in

---> <VImg>
       <RouterLink>
         <VAppBar>
           <AppBar> at resources/js/components/partials/AppBar.vue
             <VApp>
               <DefaultLayout> at resources/js/components/layouts/DefaultLayout.vue
                 <App> at resources/js/components/App.vue
                   <Root>
```

### Reproduction Link
<a href="https://codepen.io/hackeresq/pen/zYvEKbG" target="_blank">https://codepen.io/hackeresq/pen/zYvEKbG</a>

### Other comments
SVG renders just fine....But the warn message should not be logged.

**Comment by jacekkarczmarczyk** [comment] 2020-05-02 09:17
It's resolved in 2.3 beta
https://github.com/vuetifyjs/vuetify/commit/755dc3d0380ac9a02d6e67a77a8603f222238169#diff-c59b56f0b995189a2c2bb7bb0dcde9be
https://codepen.io/hackeresq/pen/zYvEKbG

Duplicate of https://github.com/vuetifyjs/vuetify/issues/6755

**Closed by jacekkarczmarczyk** 2020-05-02 09:17 UTC
Labels: triage
