### ISSUE TITLE
[Bug Report] v-tabs centered not centered on smaller screens

### ISSUE THREAD

**Issue by WIStudent** [vuetifyjs/vuetify#8527] opened 2019-08-14 15:42 UTC
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
1. Open codepen (vuetify example) on a small screen (seems to affect the breakpoints xs, sm and md)
2. Switch on centered
3. Tabs are not centered but alligned to the left

### Expected Behavior
Tabs should be centered.

### Actual Behavior
Tabs are alligned to the left
![2019-08-14 17_41_28-Window](https://user-images.githubusercontent.com/2707930/63035076-cb914300-beba-11e9-9bce-1ff405613f0f.png)

### Reproduction Link
<a href="https://codepen.io/wistudent/pen/RwbawBy" target="_blank">https://codepen.io/wistudent/pen/RwbawBy</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-14 15:43
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8294

**Closed by jacekkarczmarczyk** 2019-08-14 15:43 UTC
Labels: triage

**Comment by amenabe22** [comment] 2020-11-26 10:25
You guys are absolute dicks
