### ISSUE TITLE
[Bug Report] The checkbox is not updated from the repository

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#2741] opened 2017-12-07 11:20 UTC
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.5.9
**Browsers:** Firefox 57.0
**OS:** Windows 10

### Steps to reproduce
https://codepen.io/cawa-93/pen/xPNoMd

### Expected Behavior
In the first scenario, it was expected that the checkbox will process the value change in the store and update.

In the second scenario, it was expected that since the checkbox uses the v-model directive, it emits an @input event.

In general, it was expected that in all scenarios the value will be updated in the store and then in the checkbox itself.

### Actual Behavior
The first scenario:
The directives are used: v-bind:value and v-on:change. When the checkbox changes, the value in the store changes. But the value of the checkbox does not change.

Second scenario:
The following directives are used: v-bind:value and v-on:input. When you change the checkbox, the value in the store does not change.

The third scenario:
The directive v-model is used. A computed property is passed to the directive. When the checkbox changes, the value in the store and in the checkbox changes.

### Reproduction Link
[https://codepen.io/cawa-93/pen/xPNoMd](https://codepen.io/cawa-93/pen/xPNoMd)

**Comment by KaelWD** [comment] 2017-12-07 11:46
Duplicate of #2605

**Closed by KaelWD** 2017-12-07 11:46 UTC
