### ISSUE TITLE
[Bug Report] v-select with readonly set to true is not fully locked

### ISSUE THREAD

**Issue by fadafez** [vuetifyjs/vuetify#10162] opened 2020-01-08 23:34 UTC
### Environment
**Vuetify Version:** 2.2.2
**Last working version:** 2.1.12
**Vue Version:** 2.6.11
**Browsers:** Firefox 71.0
**OS:** Windows 10

### Steps to reproduce
I've got the following v-select element, encapsulated in a custom component:
  
<v-select :clearable="!locked"
            :filled="filled"
            :item-text="getFullname"
            :items="agentsList"
            :label="label"
            :loading="loading"
            :multiple="multi"
            :placeholder="placeholderText"
            :readonly="locked"
            :required="required"
            :rules="rules"
            item-value="agentId"
            v-model="selectedData" />

While these are the properties received by my component;

 props: {
      'filled'          : { type: Boolean, required: false, default: UIOptions.input_filled_default },
      'multi'         : { type: Boolean, required: false, default: false },
      'label'          : { type: String, required: false },
      'value'         : { required: false },
      'required'   : { type: Boolean, required: false, default: false },
      'locked'      : { type: Boolean, required: false, default: false }
    },

### Expected Behavior
- The element must be locked (click doesn't open the dropdown list)
- The dropdown down-arrow icon on the right must be hidden, if possible

### Actual Behavior
- Click on the select value does nothing (correct behaviour)
- Clicking on the down-arrow icon shows the dropdown list, then the user can change the input value.

### Reproduction Link
<a href="https://codepen.io/funderbenz/pen/LYEdVoO" target="_blank">https://codepen.io/funderbenz/pen/LYEdVoO</a>

### Other comments
I don't know why this happens, looks like the problem is related to the down arrow icon which shouldn't be there when the input has the readonly === true. 

Looking at the documentation, in the playground I can see that enabling readonly actually hides the arrow and locks the dropdown as expected. I don't know why in my application the behaviour is different.

Edit: Looks like a regression as the read-only property was working fine in version 2.1.12, I've tested 2.1.14 and the problem came out. 

Thank you

**Comment by KaelWD** [comment] 2020-01-10 07:37
Duplicate of #9960

> in the playground I can see that enabling readonly actually hides the arrow
The one in the playground has `append-icon=""`

**Closed by KaelWD** 2020-01-10 07:37 UTC
Labels: triage

**Comment by fadafez** [comment] 2020-01-14 21:44
> 
> 
> Duplicate of #9960
> 
> > in the playground I can see that enabling readonly actually hides the arrow
> 
> The one in the playground has `append-icon=""`

duh! >_< 
Thanks

....I feel a bit stupid now :(
