### ISSUE TITLE
[Bug Report][3.5.10] Incorrect VTextField validation error transition

### ISSUE THREAD

**Issue by mdoesburg** [vuetifyjs/vuetify#19443] opened 2024-03-20 13:39 UTC
### Environment
**Vuetify Version:** 3.5.10
**Last working version:** 3.5.7
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Type a random letter in the text field. Use backspace to remove the random letter. See the incorrect animation/transition between errors.

### Expected Behavior
I expect the errors to transition correctly.

### Actual Behavior
The errors don't transition correctly causing a visual bug.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUkuPmzAQ/iuzViXsBswm21ZqSqLdQw+9VT0WsxJNHMmSedQ26YPw3zs20LArrbSc5nvMiPnGeU+sOaQPbcvPnSRbktmDUa0DK13X7kUNoKq2MQ56MPIEA5xMU0GE5kjUXj40tXXglNMSdt5Do69GalWpujR/kPDdEbtaZVUqPVu9cJVMp6VFqfcUoONnp4w8buFc6g7H7+HmZiwvF4i+TTKP4tEfJi/M05h5els6J00Nu5kGSB8pzR+zPWW5EIXAj8eftkLYe0GKFUX4ssresgsVhK8EYeyeojnPb5OPRb+O7wbf+QpQ4Aial8nfh+S7EInnV2hgq4kr+k08MPYmnX/Z4FlwhWkV7qR1NOzLQiRfagTqCDLxUXA8kW8aQj6DqLN0vC7eFYGTVatLJ8OVs3NyakwV6oAwM1eqWpqJCqRpfv2Hk0tjutruBFlvBAFbYfVBkIUr+Jz87ZKTkvq4FADOSdUcpcamcDxBnsrb8CJQzUPB5xcRj0+Fh6bieZcuf4SRn0MKT9V0+f9pWOC6IOLrhqO6DMEzU0hZukiPDDG54+/4Zk188Z6vb0nxD6x/AAo=)

**Comment by KaelWD** [comment] 2024-03-22 06:43
Duplicate of #19446

**Closed by KaelWD** 2024-03-22 06:43 UTC
Labels: S: triage
