### ISSUE TITLE
[Bug Report][3.0.0-beta.4] VOverlay SSR hydration errors

### ISSUE THREAD

**Issue by BlackYuzia** [vuetifyjs/vuetify#15323] opened 2022-06-20 19:12 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.4
**Vue Version:** 3.2.37
**Browsers:** Chrome 102.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Make a component from "https://next.vuetifyjs.com/en/components/overlays/#advanced"
2. Make v-for for cards
3. Hover on card
4. Profit!

### Expected Behavior
Hover and overlays work's fine inside v-for

### Actual Behavior
Hover didn't work, you get errors in console, also overlay didn't display.

### Reproduction

```js
<template>
    <v-row>
        <v-col cols="12" sm="6" md="4" lg="3" v-for="i in 10" :key="i">
            <v-hover v-slot="{ isHovering, props }">
                <v-card class="mx-auto" max-width="344" v-bind="props">
                    <v-img src="https://cdn.vuetifyjs.com/images/cards/forest-art.jpg"></v-img>

                    <v-card-text>
                        <h2 class="text-h6 primary--text">
                            Magento Forests
                        </h2>
                        Travel to the best outdoor experience on planet Earth. A vacation you will never forget!
                    </v-card-text>

                    <v-card-title>
                        <v-rating :value="4" dense color="orange" background-color="orange" hover class="mr-2">
                        </v-rating>
                        <span class="primary--text text-subtitle-2">64 Reviews</span>
                    </v-card-title>

                    <v-overlay :model-value="isHovering" contained scrim="#036358" class="align-center justify-center">
                        <v-btn flat>See more info</v-btn>
                    </v-overlay>
                </v-card>
            </v-hover>
        </v-col>
    </v-row>
</template>
```

### Screenshots

This work's for one element / card.
![image](https://user-images.githubusercontent.com/25010528/174664807-8521388a-cb27-4e15-ba54-7476b881f8dc.png)

This breaks for a few elements in **v-for**
![image](https://user-images.githubusercontent.com/25010528/174664857-d8419c79-2bf4-42c9-876e-def258aff7f7.png)

![image](https://user-images.githubusercontent.com/25010528/174664978-4c68a38f-8807-4baa-adae-3230a57352bd.png)
![image](https://user-images.githubusercontent.com/25010528/174664980-f5fac873-d1ad-444b-b998-3c4cbbeaf201.png)

PS: I a bit sleepy, I make a reproduce link a bit later.

**Comment by KaelWD** [comment] 2022-06-21 07:15
Works for me.

**Comment by BlackYuzia** [comment] 2022-06-21 07:23
yep, I found what problem. You should use keepalive

**Comment by BlackYuzia** [comment] 2022-06-21 07:24
https://gitlab.com/BlackYuzia/nuxt-vuetify/-/tree/bug-tracker

Check this repo @KaelWD

**Comment by BlackYuzia** [comment] 2022-06-21 07:30
Also, you could go to - https://nuxt3.starserv.ru/bug-002
There you can find this bug too.

**Comment by KaelWD** [comment] 2022-06-21 09:32
The actual bug is this, it has nothing to do with keep-alive or v-for
![Screenshot_20220621_193106](https://user-images.githubusercontent.com/16421948/174767394-b9e2c808-e9d2-415d-9cb2-138f4fbe6bf5.png)

**Comment by Vincebe** [comment] 2022-08-08 11:39
Is there a workaround?

**Comment by KaelWD** [comment] 2022-08-08 11:50
https://next.vuetifyjs.com/en/components/no-ssr/

**Comment by zylstraj** [comment] 2022-10-19 18:31
So the workaround for this is the `v-no-ssr`. Is there a fix for this with the latest version of vuetify beta or is the workaround the only way to avoid this for now? Because experiencing this same issue with the v-tooltip or same as #[15307](https://github.com/vuetifyjs/vuetify/issues/15307)

**Comment by magyarb** [comment] 2022-11-18 11:55
Thanks for the fix! In the demo, it looks like it is solved. But if you use layouts and pages in nuxt3, the same problem appears again (and duplicates the buttons next to the v-menu in the toolbar).

@KaelWD could you please reopen this issue until it is fully fixed?

Here is the reproduction link:
https://stackblitz.com/edit/node-htkewu

**Comment by KaelWD** [comment] 2022-12-06 16:37
Related: #15951
Nuxt uses suspense which is really annoying to intercept from inside.

**Comment by magyarb** [comment] 2022-12-07 15:27
For me, `<client-only>` solves this problem, and is a good enough workaround until this issue is fixed.

**Comment by ThomasBerne** [comment] 2022-12-09 20:39
It appens also on the v-select.

**Closed** 2022-12-13 14:43 UTC
Labels: T: bug, upstream, SSR, C: VOverlay

**Comment by roseMix** [comment] 2023-02-19 17:32
@KaelWD I'm still having this exact same issue with VOverlay on the latest version of Nuxt (3.2.2) and Vuetify (3.1.5).

`<client-only>` workaround works.

**Comment by tokidoki11** [comment] 2023-03-22 00:42
Happening on v-menu as well on version 3.18


I wonder why this is closed

**Comment by johnleider** [comment] 2023-03-22 04:16
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
