### ISSUE TITLE
[Bug Report] v-textarea auto-grow doesn't auto-shrink after contents emptied when focus stays in textarea element

### ISSUE THREAD

**Issue by oliviermills** [vuetifyjs/vuetify#6978] opened 2019-04-12 21:19 UTC
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Mac OS 10.14.0

### Steps to reproduce
Create a textarea with an auto-grow and rows=1, and have a btn in the "append" slot empty the contents of the text. The textarea doesnt shrink.  **Note: it DOES work correctly if you use the append-outer slot.**

### Expected Behavior
The textarea should shrink

### Actual Behavior
The textarea doesn't recalc the height when its focus is on it.

### Reproduction Link
<a href="https://codepen.io/omills/pen/NmvrMw" target="_blank">https://codepen.io/omills/pen/NmvrMw</a>

**Comment by jacekkarczmarczyk** [comment] 2019-06-01 16:33
Is it only macos issue? Can't reproduce it on chrome/win

**Comment by KaelWD** [comment] 2019-06-01 16:45
I had it on linux too, doesn't seem to happen any more though for some reason. Chrome update maybe?

**Comment by KaelWD** [comment] 2019-06-01 16:59
Downloaded 73.0.3683.0 and still couldn't reproduce again.

**Comment by KaelWD** [comment] 2019-06-01 17:04
Ah, you have to type. Just having text in there initially isn't enough.

**Comment by jacekkarczmarczyk** [comment] 2019-06-02 05:25
fixed by https://github.com/vuetifyjs/vuetify/pull/7363

**Closed by jacekkarczmarczyk** 2019-06-02 05:25 UTC
Labels: C: VTextarea, S: has PR, T: bug
