### ISSUE TITLE
[Bug Report] footer size doesn't take into account the drawer width

### ISSUE THREAD

**Issue by FlorianPons** [vuetifyjs/vuetify#11012] opened 2020-04-03 07:17 UTC
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Firefox 74.0
**OS:** Windows 10, Linux

### Steps to reproduce
v-app with inset v-footer and a clipped v-navigation-drawer with property right and a modified width. The footer size doesn't take into account the drawer width.

### Expected Behavior
The v-footer should user the remaning width only.

### Actual Behavior
The v-footer considère the drawer is with default width.

### Reproduction Link
<a href="https://codepen.io/florian_pons/pen/YzXbwQG" target="_blank">https://codepen.io/florian_pons/pen/YzXbwQG</a>

**Comment by ElijahKotyluk** [comment] 2020-04-04 05:45
Duplicate of #8128

**Comment by KaelWD** [comment] 2020-04-04 07:07
Duplicate of #10968

**Closed by KaelWD** 2020-04-04 07:07 UTC
Labels: C: VFooter, T: bug, duplicate

**Comment by Pnem** [comment] 2020-06-13 11:38
For a workaround you could use a computed property watching for the vuetify breakpoint width and return "30%" of the window width as a number.

https://codepen.io/hjmd/pen/eYJzZYv 

Also I used a conditional (ternary) operator to set the drawer width to 300 (px) if the window size goes below the lg breakpoint.
