### ISSUE TITLE
[Bug Report] VDatePicker Scrolling Blurs Dates Together

### ISSUE THREAD

**Issue by Logikgate** [vuetifyjs/vuetify#11371] opened 2020-05-11 14:09 UTC
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Mac OS 10.15.4

### Steps to reproduce
Use a trackpad to scroll on the date picker.  Even minor scroll events cause the dates to fly by and blur together. Using a mouse scroll wheel with detents works well since one detent equals one month change but when using a trackpad to scroll the animation is less predicable. 

### Expected Behavior
Reacting to scrolling should be throttled so the animation has time to catch up and so the user can see  what months they are scrolling through.

### Actual Behavior
Scrolling the date picker, especially with a sensitive trackpad, causes the dates to blur together and makes it very difficult to use accurately.

### Reproduction Link
<a href="https://codepen.io/logikgate/pen/oNjybYo" target="_blank">https://codepen.io/logikgate/pen/oNjybYo</a>

**Comment by jacekkarczmarczyk** [comment] 2020-05-11 14:17
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5546

**Closed by jacekkarczmarczyk** 2020-05-11 14:17 UTC
Labels: triage
