### ISSUE TITLE
[Bug Report][3.1.3] VListItem bug when rerenders occur within VAppBar?

### ISSUE THREAD

**Issue by ffxsam** [vuetifyjs/vuetify#16576] opened 2023-02-02 19:10 UTC
### Environment
**Vuetify Version:** 3.1.3
**Last working version:** 3.1.0
**Vue Version:** 3.2.47
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click "Menu"
2. Click a theme button
3. "getUid" error occurs

### Expected Behavior
I'd expect no errors.

### Actual Behavior
Error occurs. In my own environment, it prevents the theme switch from fully occurring.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlWG2P2zYS/iuM74OdwJIul+IO8K0327ukSIFs03bT9kPdD7JE20wkUhApb9yt/3sfvogiZXuboCnQtTjD4czw4cxD/vow+bpp0n1HJ4vJlaJ1U+WKXq84IVf7JG8a89N81Dnj7gvfJduTosqlXK4mtUr+vZp4mdEu8rYMRvxYougnFQkger+jNb27Z6rY0ZaUVNFCJYJXB5KNVHu3knXeWkkhKtHCCcY3YjWxYyXlkqkDRgtRN3mhesGCVnSfKyY4ZF/Z0SFCZzdRTFX0mrzXf8hVNhY4/T5Z5B8QUx5HC/kt8nVLeadjUOY/Oy+LszyYx3eUMEjOZawffzTfF7N91zUvY8sn9q4ybG4fJYR+452v+B0FgU9ZtKxRRFLVNaTK+RbpVdJhgtWNaBV5IC3dkCPZtKImUyBuGgk7SQ0MQg3FNofpfwO1GChWL82iUY3laI7fh169H+g1rzLrPpydzCd2FoJu0g9ScByLB20MADMCBLUgZkSPwYL+Xk12SjVykWUdbz5uU6Auu4EsazuuWE2TUtQ3L9J/pV/9B7mVKhxPqayTdSvuJXz/APPzwLhOwKUFnBh2n6cvrFk3pE2emMpgf0/bpAVUaUvbR/0e6Ua+j2Qn/us1jyt+RC4rxj/KURoLaVL4629W5WTvdB16BE4hmObkPse8ORH8ViCjtIzgha09QddrvmV8wFiaKT2aUDOcKqknZdmAyrws34v/2ejmZEvVN5jnvr2Vm6xTrJJZJYq8SqQSbb41y694IbhUpGlFI8mSIMzdK7rJu0rJmU5HSTdY93stvnKgyp49I29YSSWBa+Snb0nOS0ysKkSJgrhh266lRHTKyHEcMbllug6ZUMizrK+Buoq+w5yXC7IWoqI5N8fieD17aoDhFhwUF2STV5IaIXbwaRDBAyl22AebxDlhnCmWV+x3Ws71Nr27cwLjwx1VivEt8rMcJX6mbVqL8iCN4EcUhaXezas372/fvmL71xVGuSJ/EN5V1fVM/9+6YnZ7Fi4xJ7OnZHltQwk8jJTSfV51VJtAdrNoS2dTJNDMmMa+D3OOdm0PsVmwItuQWZAKNwnBqK7Vye51glh7HZd8lwt1qLDhGiC8FPcpcPZ/NK4Oy91p0akBkkviEmUD86YOEqXZVtKlM4xzDc+5SluKml3QWbaaZMjddPpU25lWbLtTUyR8WubtRwtcbXHYWO3AYHa5dJo2NVpVR2lQng5w8kH2vpkE/2zchwW7qrdgbQwqwewzW2tVXOT63+nmYY1B1WseCQXEQ9uAhDuT7gQhbG3l/OpTmwkTurNof4wNfw4azWSXwDGMtPutczy2DYepRGlVCepxvq5owtHHE4xQwkWic43TPoACHyltWwG0fyeic7cBpEsXii7Z+lfQDfERc5UnSYIWzCTR7A9/PnQacYLcU1Lk3FUSU5fe3U0lKboWXWKUVpIk1hhsWB9x9lHfA796ttbzS4gSY8MKLCcEw1krniix3fbB7hOmLT0ZINhbAokRJa10Gwm2wq/jKKSkSBeA7afVqL05yvnBWclRaLmCJsqvTnfZK94UFSs+pij9DaRjXgk/PcaxgmbMJUvud0xR8D70t4ImsuPcr4uc6J2hJVT/OQxKoAMjnxJZ51U1jBu8QGBOVD/cM+eL69dC8OQ+/4REJEVLZYGt+psO6KLwBesD8gI85G8taY9jvKjmqQM2ztFVXRaJLERDNe1NPcDsEdszydaswg1iQXasxG3CnBBXRRdB6TJnPzJwU9OS5boY0g1tJU4jsJVIsJuaLohOUFj7nb2+7MIcjp92znLRETkBNbrIpc+RnXNUum+/Qb2x7Xdmev/Qn6NObhv0uFHoH64cXkeF0VoQ8hW0+lYULbFCxTLObjpe6OvYCU9wLX1wJeAShkWMxJZCvsGBrcDMlmSGbN/qrfiho+3hLYjr671ulr53k9A/X3JpWmuSQWXU2c41F90E+5CHqm80020lcK5Tnp+zTF726QuR5DvJMYrNoMmHMDAEY8vEN5s+hjXfonUYsTHvNRinc/8ZuRUglyA7EjdoatFzl29Q97xGf2Mo6Z5WOEBtWovfQU/zVLTbjPLkp7usFIXMfqHr7Ovvv83iXchAv/RfynEFcTYdYzWZPjRUbEZhp5hjdq+faLPfYyfM/19MnE1tW/ZsL0SN78mjTo5+a3NAnr+4vI5f4hHDrs/qPx74l3iCB8e54+YjHqOTPPlSXIazLyTg8uTTI/QX4B4FHzBMPctfVLzn586o1uwpi/5j6fb4ihLM/Oz7ii3BKLzhE8EXXEgvVOQveLXoayeIffezbkPoU6Pa+RhBA8/BxDHnCYz1jVJfVd0z2FooBY9wnY95S/C+hc3Cq5nhSA/uMnsMH/xsj8eKa1QnKBkVKOgUumbs35OiTnzu8QrfFc5S/JilR8CR1jua49UhetF6iy6PJsY47jLxK9nFSb1BELCamEc9OG32I3rGjJKAInvulQ+cEzs2fqS8yCiHf44JbXAB2+RJk1cAod8efzeJvYmfDs84ef4lMsbfZ9j0ydMJivMG1o7HiXZ4+z0kz1eTwGg/N3hA9NtrXhOBiTElmxznE/vEhLNn3rMmv/0Jn9liLQ==)

**Comment by KaelWD** [comment] 2023-02-03 16:59
Duplicate of #16558

**Closed by KaelWD** 2023-02-03 16:59 UTC
Labels: S: triage
