### ISSUE TITLE
[Bug Report] Vuetify  2.4.0 depressed outlined button missing transparent background

### ISSUE THREAD

**Issue by shadow81627** [vuetifyjs/vuetify#12869] opened 2021-01-02 03:31 UTC
### Environment
**Vuetify Version:** 2.4.0
**Last working version:** 2.3.21
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Windows 10

### Steps to reproduce
Add `depressed` and `outlined` to a btn.

### Expected Behavior
The button should have a transparent background.

### Actual Behavior
The depressed outlined button background is no longer transparent in version 2.4.0 in the previous version of vuetify the background was transparent. This is causing lighthouse to fail contrast check for my buttons.

### Reproduction Link
<a href="https://codepen.io/damienrobinson/pen/qBaoBeB" target="_blank">https://codepen.io/damienrobinson/pen/qBaoBeB</a>

### Other comments
It seems like the issue was introduced in the [button plain attribute feature pull request](https://github.com/vuetifyjs/vuetify/pull/12814/files#diff-38fd440a782bc28724fa945ed4c02d0635fae24d42626b5e5fc975b571ca315aL257).

[Vuetify 2.3.21 codepen of expected functionality](https://codepen.io/damienrobinson/pen/BaLryBd) where the button background is transparent.

[My websites Vuetify 2.4.0 update preview](https://daim-git-renovate-lock-file-maintenance.damienrobinson.vercel.app/contact) the contact form submit button fails lighthouse contrast check because the background is not transparent.

[My websites production running vuetify 2.3.21](https://daim.dev/contact) where the button background is transparent.

This combination of attributes is taken from [Zero Theme Free base btn component](https://store.vuetifyjs.com/products/zero-theme-free)

**Comment by KaelWD** [comment] 2021-01-02 05:52
Duplicate of #12845

**Closed by KaelWD** 2021-01-02 05:52 UTC
Labels: triage
