### ISSUE TITLE
[Bug Report][3.1.4] VExpandTransition does nothing

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#16656] opened 2023-02-13 20:21 UTC
### Environment
**Vuetify Version:** 3.1.4
**Last working version:** 2.6.12
**Vue Version:** 3.2.47
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Reproduce exemple as in documentation : https://vuetifyjs.com/en/styles/transitions/#expand-x

<v-expand-transition>
        <v-card
          v-show="expand"
          height="100"
          width="100"
          class="mx-auto bg-secondary"
        ></v-card>
      </v-expand-transition>

### Expected Behavior
The card to have an expand animation.

### Actual Behavior
No animation at all.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFVE2PmzAQ/StTn3alGJLsqgdKovTQf9BDpWUPDjjBG7CRbfKhVf57x4YAIdlKW1UqJzPz/N6bGdsv7+R7VQX7mpOIxJaXVcEsXyYSIN5TrQ5uBfBWGys2p0VCUi4t1wlJZJMx9lRwjJdC0pyLbW4jmH2dVsdvDgPgqTxZqgpIC2YMok2uhdwlpM36/Nq2lO67AEtG5w1RG1eF0hivtCiZPg1Tq7QQ6Q5z/FgxmcECvjSrHtTJAfxoQD81k0ZYoTrtOPRWEDrw1hBR26EHTK40prM+ALCnJleHzsrQJUDTJUzOptPrzEFkNr+X6LpxpKy2CtZbaniqZDZqwdKZd2b6vmLgI/MerIqu0jgT+6HUM+Qiy7ikpqSOIFMHiSOLQ8T1m/7xYO/WNRrtvJ/tgON2uL8+Od7j3w74qpL/N+E7/vsZN2u80biOw8FNx1+TalFZD0IqpS1kfMPqwsJ7Q5MxyyJ4eITFEh7amMeibAQbVhg+uY7Or8PnR784O+1WjUyIKJ0YLVkVvBkl8Qny3EmbMAmJLg4Sgm+U+09Ibm1lojCsZbXbBqkqwxXmQl1LK0qOx7RcPQVPwZSyospZ8Izn1dhhOuB4otfYCsM1CiekNek13Dv3kU6bRvrZhbYNOcobqhD591xTzWXGtXs1/2B/hL1XwghyU0bb4TN2tsBbaEZNTY1v6MvF4afqw/c98ARu96sTOU/IlUdU9fvI628Bk/De)

**Comment by KaelWD** [comment] 2023-03-01 09:42
Duplicate of #16137

**Closed by KaelWD** 2023-03-01 09:42 UTC
Labels: S: triage
