### ISSUE TITLE
[Bug Report] Wrapping vuetify inputs does not allow inheriting slots

### ISSUE THREAD

**Issue by StevenIYoo** [vuetifyjs/vuetify#10665] opened 2020-02-24 22:09 UTC
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.106
**OS:** Windows 10

### Steps to reproduce
Wrap v-text-field into it's own wrapper component and pass up its slots.
Try to use append slot in wrapper component.
Slot not working

### Expected Behavior
Should be able to pass slots up to wrapper component

### Actual Behavior
Slots not being passed up to wrapper

### Reproduction Link
<a href="https://codepen.io/yooste1989/pen/GRJrxVm" target="_blank">https://codepen.io/yooste1989/pen/GRJrxVm</a>

### Other comments
Passing slots to wrapper works on the v-data-table component.

**Comment by KaelWD** [comment] 2020-02-25 04:55
Duplicate of #10215

**Closed by KaelWD** 2020-02-25 04:55 UTC
Labels: triage
