### ISSUE TITLE
[Feature Request] [VNavigationDrawer] Update mini-variant prop when using expand-on-hover

### ISSUE THREAD

**Issue by phiter** [vuetifyjs/vuetify#8803] opened 2019-08-30 14:27 UTC
### Problem to solve
I need to know if the `navigation-drawer` is in mini or open state when I'm using `expand-on-hover` with it.
Currently there's no way of knowing and using `:mini-variant.sync` does not update the data on hover.

### Proposed solution
Make the `:mini-variant.sync` update the data I pass to it even if I use `expand-on-hover`.
Or just trigger an event when I hover this component.

---

Here's a [reproduction link](https://codepen.io/phiter/pen/PoYKzqa?&editable=true&editors=101) of the thing I tried which doesn't work:

**Comment by jacekkarczmarczyk** [comment] 2019-08-30 14:34
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8133

**Closed by jacekkarczmarczyk** 2019-08-30 14:34 UTC
Labels: triage
