### ISSUE TITLE
[Bug Report] Menu issue inside bottom nav

### ISSUE THREAD

**Issue by codewp** [vuetifyjs/vuetify#4375] opened 2018-06-22 17:44 UTC
Versions and Environment
Vuetify: 1.0.19
Vue: 2.5.16
Browsers: Chrome 67.0.3396.87
OS: Windows 7

Steps to reproduce
In the page, there is bottom nav and inside it, there is a menu with "Add" text, when you click on its menu should open on top of bottom nav but it will open under bottom nav.

Expected Behavior
The menu should open on top of bottom nav.

Actual Behavior
The menu will open under bottom nav.

Reproduction Link
https://codepen.io/anon/pen/yEjwMr

**Comment by johnleider** [comment] 2018-06-22 23:59
You are missing a few things in that codepen. Such as `v-app` which is a requirement for `v-menu` currently.

**Comment by codewp** [comment] 2018-06-24 07:04
@johnleider 
I added `v-app` to codepen and also it couldn't fix the issue.
Please let me know how can I fix this issue?

**Comment by KaelWD** [comment] 2018-12-17 14:35
Duplicate of #5044

**Closed by KaelWD** 2018-12-17 14:35 UTC
Labels: T: bug
