### ISSUE TITLE
[Bug Report] Can't select the same item in combobox

### ISSUE THREAD

**Issue by butaminas** [vuetifyjs/vuetify#9575] opened 2019-11-05 07:00 UTC
### Environment
**Vuetify Version:** 1.5.20
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Mac OS 10.15.1

### Steps to reproduce
if you select 'Programming' in the combo box and type 'prog' and select the suggested 'Programming' again, the text field still shows 'prog'.

You can also replicate this on the official combobox page of v15 docs.

### Expected Behavior
When you type in the combobox and select the same a suggested item that was previously selected - it is not being selected.

### Actual Behavior
When an item is selected in the combo box and you try to select it again - it is not being selected.

### Reproduction Link
<a href="https://codepen.io/bob-lee/pen/qBWVQrd" target="_blank">https://codepen.io/bob-lee/pen/qBWVQrd</a>

**Comment by runyasak** [comment] 2019-11-05 12:15
There occurs on Vuetify 2 also. Please, resolve this bug.

**Comment by butaminas** [comment] 2019-11-05 12:23
> There occurs on Vuetify 2 also. Please, resolve this bug.

Strangely enough, the v2 example on the docs page is working as expected: https://vuetifyjs.com/en/components/combobox

So not sure when was this fixed or on how many versions does this bug occurs but it really needs to be fixed.

**Comment by KaelWD** [comment] 2019-11-07 14:12
Duplicate of #7259

**Closed by KaelWD** 2019-11-07 14:12 UTC
Labels: triage
