### ISSUE TITLE
[Bug Report] Vuetify carousel delimiter's order

### ISSUE THREAD

**Issue by blue14753** [vuetifyjs/vuetify#12949] opened 2021-01-13 07:00 UTC
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 87.0.4280.88
**OS:** Linux

### Steps to reproduce
When I add a new number at the front of nums, the carousel doesn't have the correct order.
For example, the initial nums are [1,2,3,4,5], then click the add button. It should refresh with the new order.

### Expected Behavior
nums = [66,1,2,3,4,5]
the carousel's order shows by 66,1,2,3,4,5

### Actual Behavior
nums = [66,1,2,3,4,5]
the carousel's order shows by 1,2,3,4,5,66

### Reproduction Link
<a href="https://codepen.io/blue14753/pen/RwGeYZq" target="_blank">https://codepen.io/blue14753/pen/RwGeYZq</a>

**Comment by blue14753** [comment] 2021-01-20 07:48
I have found a temporary resolve,
I used the async & await function, let clean nums before the update nums,
then the carousel will show the correct order.

**Comment by KaelWD** [comment] 2021-07-30 06:46
Duplicate of #12818

**Closed by KaelWD** 2021-07-30 06:46 UTC
Labels: C: VCarousel, S: triage
