### ISSUE TITLE
appended icon disappears on click in v-text-field

### ISSUE THREAD

**Issue by wildan2711** [vuetifyjs/vuetify#1360] opened 2017-08-15 09:35 UTC
### Steps to reproduce
Use `dark` and `append-icon` props on `v-text-field` in a `v-toolbar`.

### Versions

Latest Vue, Vuetify, only tested in Chrome on Ubuntu.

### What is expected ?

The appended icon is persisted on the `v-text-field`.

### What is actually happening ?

The appended icon disappears.

### Reproduction Link

https://codepen.io/wildan2711/pen/mMqbzP

**Comment by jacekkarczmarczyk** [comment] 2017-08-15 09:45
This issue refers to the appended icon, it's related to https://github.com/vuetifyjs/vuetify/issues/972 which refers to the bottom line

**Comment by johnleider** [comment] 2017-08-17 16:45
I mean, this is something we could improve, but the icon doesn't disappear, it just gets the same color as the background because inputs use the application primary color and you put them inside of a nav as the applications primary color.

**Comment by johnleider** [comment] 2017-09-04 19:11
This is essentially a duplicate of #972 for all intents and purposes. Removing this in favor of that.

**Closed by johnleider** 2017-09-04 19:11 UTC
Labels: enhancement
