### ISSUE TITLE
[Feature Request] ondragend event for v-slider

### ISSUE THREAD

**Issue by kubaPod** [vuetifyjs/vuetify#4123] opened 2018-05-23 10:04 UTC
### Problem to solve
It would be nice to have a built-in, robust way to trigger an action when user released the slider after dragging it. 

`mouseup` is not robust because it can be triggered without dragging and will miss being triggered if cursor was moved outside before releasing. Similar issues are with `click` etc. Even if I watch the variable it is tough to catch 'end of drag' situation.

https://codepen.io/anon/pen/yjrKmQ

### Proposed solution
ondragend event for v-slider

**Comment by KaelWD** [comment] 2018-05-23 10:09
Duplicate of #3116 and #2591

**Closed by KaelWD** 2018-05-23 10:09 UTC
