### ISSUE TITLE
[Bug Report][2.5.8] V-Tabs do not render correctly inside a V-Menu

### ISSUE THREAD

**Issue by MattyChambad** [vuetifyjs/vuetify#14088] opened 2021-08-25 08:47 UTC
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.12
**Browsers:** Chrome 89.0.4389.116, Other
**OS:** Windows 10

### Steps to reproduce
* Click the button to toggle a v-if to show a `v-card` displays `v-tabs` component with the arrows correctly.
* Click a button in a `v-menu` with a `v-card` initially renders the `v-tabs` component without the arrows and requires a second interaction for them to appear   

### Expected Behavior
That rendering is consistent in both cases with arrows being shown. 

### Actual Behavior
The `v-menu` variant fails to render the arrows consistent with the displaying of a card not inside a `v-menu`

### Reproduction Link
<a href="https://codepen.io/Chambad/pen/eYRYaPN" target="_blank">https://codepen.io/Chambad/pen/eYRYaPN</a>

**Comment by KaelWD** [comment] 2021-12-14 08:48
Duplicate of #4733

**Closed by KaelWD** 2021-12-14 08:48 UTC
Labels: C: VTabs, S: triage
