### ISSUE TITLE
[Bug Report][3.3.21] VAutocomplete selection slot not used while dropdown is open

### ISSUE THREAD

**Issue by MelvinFrohike** [vuetifyjs/vuetify#18454] opened 2023-10-12 15:07 UTC
### Environment
**Vuetify Version:** 3.3.21
**Vue Version:** 3.3.4
**Browsers:** Safari 17.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
When creating a VAutocomplete with objects as items and using the selection slot, the selection slot is only used when the automcomplete dropdown is not open. If the dropdown is open, the selection is displayed using the item-title prop.

### Expected Behavior
When the selection slot is defined it should be used whether the dropdown is open or not.

### Actual Behavior
The defined slot is used when the dropdown is closed. The item-title prop is used when the dropdown is open.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdkjFP6zAQx7/KPb8hPKlJH5QBRQWJDRYWJBiaDia5VpYc27KdMET57pydtDh0Y3Jy97/7/e/s3cCcrdePxhR9h6xkW4+tkdzjQ6UAtn3OjYmf8afWynOh0M6hSdF5XWuqQo+nMECft7pBeV8xhxJrj80blx1W7FtSCoI5UsQzzYRA7oWXSFnF20VZTPahGSX5McmdXZGv0xzwd+ILrUg+xGoYK5ZoAYYpXlj+WQQcjCPkiyhxKJj0Xy8WdQENhWfeCozVxl1gaXlSOJ9HT33+IVRDNVFbMTjN/6PoN26D34SVWr6cI0jTOz0niLC4yzMiVCyfRuwRX84CQL+utsJ4auQ7A5KrI03oadxYJlqjrYcBLB5ghIPVLWT0MLNQSmnl0R54jfAcNjZM9LCCEl69Feq4mkI0fwkvXfuBNgTIZjjIovPQuiPcB8BV9oRSanjXVjZ/sn+pKL7IMmJ2e5LvQmrmzcDsIKzz2UyckLc3ERdjP9QOqXOzlN9tZncA+5S+3HI0uw1WHq6ir93/PZndrqdV0uLYuGKbYlPcsum8uWb7L7eLMXM=)

### Other comments
This makes for a confusing UI if the slot definition differs from the item-title. Note that this does not happen with the chip slot. There the slot definition is used whether the dropdown is open or not.

**Comment by KaelWD** [comment] 2023-10-24 12:46
Duplicate of #17573

**Closed by KaelWD** 2023-10-24 12:46 UTC
Labels: S: triage
