### ISSUE TITLE
[Feature Request] Bottom Navigation Hide on scroll inverse

### ISSUE THREAD

**Issue by stephenjason89** [vuetifyjs/vuetify#11944] opened 2020-07-27 06:30 UTC
### Problem to solve
Usually you want the bottom navigation to hide when being scrolled down and show when scrolled up.
The current implementation hides the navbar when scrolling up and shows it when scrolling down.

### Proposed solution
Would love to have an inverse
Thank you

**Comment by danbeneventano** [comment] 2020-08-11 00:28
What I did to solve this problem while we wait for a fix is I wrapped my `v-bottom-navigation` in a `v-app-bar` with `hide-on-scroll`. The scroll behavior is correct with v-app-bar. I had to use some CSS to make it look right

**Comment by canhkieu** [comment] 2020-09-04 23:48
May be change to 
`hide-on-scroll="up | down"`

**Comment by stephenjason89** [comment] 2020-09-06 11:21
> May be change to
> 
> ```
> hide-on-scroll="up | down"
> ```

I think, this would be the right way to go.
 
To go one more step further, an overlay scrollbar would be a nice feature to have. (vuetify can't track scroll if you use a package for overlay scrollbar like https://kingsora.github.io/OverlayScrollbars/#!overview)

You'll have to implement it yourself to make it work.

**Comment by andrewspy** [comment] 2020-09-15 02:30
@danbeneventano Can you share the exact implementation while waiting for the fix?

**Comment by danbeneventano** [comment] 2020-09-19 00:06
@andrewspy 
```
<template>
  <v-app-bar
    app
    bottom
    hide-on-scroll
    class="bottomappbar"
  >
    <v-bottom-navigation
      grow
      class="elevation-0"
    >
    </v-bottom-navigation>
  </v-app-bar>
</template>

<style scoped>
.bottomappbar >>> .v-toolbar__content {
  padding: 0;
  margin: 0;
}

.v-app-bar >>> .v-app-bar--fixed {
  top: initial !important;
  bottom: 0 !important;
}

.v-app-bar.v-app-bar--fixed {
  top: initial !important;
  bottom: 0 !important;
}

.v-app-bar--fixed {
  top: initial !important;
  bottom: 0 !important;
}

.v-app-bar {
  top: initial !important;
  bottom: 0 !important;
}
</style>
```

**Comment by andrewspy** [comment] 2020-09-19 19:47
@danbeneventano Thanks for sharing, managed to fix the style. Ideally, bottom nav should also auto reveal when reaching end of scroll else there will be an empty white space. Let's hope vuetify team can address that soon. Thanks!

**Comment by johnleider** [comment] 2020-12-10 18:30
Duplicate of #8173

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-10 18:30 UTC
Labels: C: VBottomNavigation, T: feature

**Comment by Calvin-Huang** [comment] 2022-01-24 21:02
@danb10 Appreciate for your sharing. @johnleider seems didn't comprehended what problem is.....

Here is the correct behavior from Android.

![scroll-to-hide-when-scrolling-down](https://i.stack.imgur.com/7ekze.gif)

**Comment by dhakalsamundra** [comment] 2022-08-26 10:47
@Calvin-Huang , can I see the code of the above sample?

**Comment by opeen** [comment] 2023-03-21 14:52
Could you share the code of the above sample?
