### ISSUE TITLE
[Bug Report] V-toolbar: Extension slot not working with the new Vue 2.6 slot syntax

### ISSUE THREAD

**Issue by razorfever** [vuetifyjs/vuetify#6371] opened 2019-02-05 16:48 UTC
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.1
**Browsers:** Chrome 74.0.3693.0
**OS:** Mac OS 10.14.0

### Steps to reproduce
Open the expansion slot demo for the v-toolbar in codepen and convert the syntax to match the new slot syntax in Vue 2.6

### Expected Behavior
Title shows up in the expansion slot

### Actual Behavior
Title does not show up in the expansion slot

### Reproduction Link
<a href="https://codepen.io/anon/pen/OdxLxM?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/OdxLxM?&editable=true&editors=101</a>

**Comment by DRoet** [comment] 2019-02-06 09:37
Try upgrading to vue 2.6.2, it seems to work: <https://codepen.io/anon/pen/yZzqgq?&editable=true&editors=101>

**Comment by KaelWD** [comment] 2019-02-06 09:39
Duplicate of https://github.com/vuejs/vue/issues/9421

**Closed by KaelWD** 2019-02-06 09:39 UTC
