### ISSUE TITLE
[Bug Report] v-switch with ripple false has almost no click space

### ISSUE THREAD

**Issue by Renato66** [vuetifyjs/vuetify#4837] opened 2018-08-10 22:49 UTC
### Versions and Environment
**Vuetify:** 1.1.10
**Vue:** 2.5.17
**Browsers:** Opera 54.0.2952.64
**OS:** Windows 10

### Steps to reproduce
if you click on input checkbox it will change the value

### Expected Behavior
?

### Actual Behavior
?

### Reproduction Link
[https://codepen.io/renato66/pen/QBYKxo](https://codepen.io/renato66/pen/QBYKxo)

### Other comments
fixing by using the class on the second component

**Comment by KaelWD** [comment] 2018-08-11 04:40
Duplicate of #4696

**Closed by KaelWD** 2018-08-11 04:40 UTC
