### ISSUE TITLE
[Feature Request] VDataIteratorItem Type Export

### ISSUE THREAD

**Issue by SelfhostedPro** [vuetifyjs/vuetify#19309] opened 2024-02-29 23:27 UTC
### Problem to solve
Exporting the type in order to allow users to have type safety easily when using the items in the same component.

### Proposed solution
Exporting type VDataIterator  from /vuetify/lib or whichever location is prefered.

**Comment by KaelWD** [comment] 2024-03-01 04:26
Duplicate of #16680

**Closed by KaelWD** 2024-03-01 04:26 UTC
Labels: S: triage
