### ISSUE TITLE
[Bug Report] hide-no-data + multiple inside auto-complete breaks filtering from second item and above

### ISSUE THREAD

**Issue by MauricioRodolfo** [vuetifyjs/vuetify#5855] opened 2018-12-10 11:58 UTC
### Versions and Environment
**Vuetify:** 1.3.12
**Vue:** 2.5.19
**Browsers:** Chrome 71.0.3578.80
**OS:** Windows 10

### Steps to reproduce
With the hide-no-data AND multiple tags inside auto-complete:
- Type BitCoin
- Select first result
- Attempt to filter "Bitcoin Scrypt" <-- When 'Bitcoin Sc' is typped all options should dissapear

When filterring the first item, the search works as intended.

### Expected Behavior
Working filter on auto-complete with 'hide-no-data' AND 'multiple' selections

### Actual Behavior
The second or above selected item is not correctly filtered

### Reproduction Link
<a href="https://codepen.io/mauriciorodolfo/pen/Ydzmgd" target="_blank">https://codepen.io/mauriciorodolfo/pen/Ydzmgd</a>

### Other comments
- Tested on 1.4.0-alpha.0 as well, same result.
- Forked examples on Cryptocurrency from vuetify docs and added 'hide-no-data' AND 'multiple' to the auto-complete.

**Comment by KaelWD** [comment] 2018-12-10 11:59
Duplicate of #4580

**Closed by KaelWD** 2018-12-10 11:59 UTC
