### ISSUE TITLE
[Bug Report] v-edit-dialog missing buttons after update to 2.2.12

### ISSUE THREAD

**Issue by Qadosch** [vuetifyjs/vuetify#10572] opened 2020-02-13 14:49 UTC
### Environment
**Vuetify Version:** 2.2.12
**Last working version:** 2.2.8
**Vue Version:** 2.6.10
**Browsers:** Firefox 72.0
**OS:** Windows 10

### Steps to reproduce
[Reference](https://vuetifyjs.com/en/components/data-tables#content-editing)

I use the code similar to the reference

### Expected Behavior
Expected Save / Cancel buttons

### Actual Behavior
No Buttons

### Reproduction Link
<a href="https://codepen.io/dontknowhowthisshitworksdontevencare" target="_blank">https://codepen.io/dontknowhowthisshitworksdontevencare</a>

### Other comments
similar to [10532 ](https://github.com/vuetifyjs/vuetify/issues/10532)

**Comment by MajesticPotatoe** [comment] 2020-02-13 14:54
Duplicate of #10522. was only merged just yesterday, so will be in next patch.

**Comment by nainardev** [comment] 2020-02-13 14:54
`Reproduction link` not working

**Closed by MajesticPotatoe** 2020-02-13 14:54 UTC
Labels: triage

**Comment by Qadosch** [comment] 2020-02-13 15:10
ah, seems i missunderstood releasenotes for v2.2.12
