### ISSUE TITLE
[Feature Request] Add option to clear typed query when selecting an autocomplete item

### ISSUE THREAD

**Issue by mrgarethprice** [vuetifyjs/vuetify#18428] opened 2023-10-09 22:13 UTC
### Problem to solve
Adding multiple items to an autocomplete via the keyboard is quite a painful user experience as the previous 'query' remains appended after the value is added (until the field is blurred).

Many users will not know to hit ESC to close the dropdown and refocus the input, and even if they do so they currently have to manually delete their previous search term.

### Proposed solution

Some form of "clear query on selection" prop that adds the selected item, removes the previously typed query, and focuses the input to automatically accept a new value.

Bonus points for an option which shows the dropdown on focus.

Nice one!

**Comment by hanzelkatomas** [comment] 2023-10-24 14:59
Yes. I ran into similar problem. This would be nice.

**Comment by KaelWD** [comment] 2023-12-29 15:07
Duplicate of #6842

**Closed by KaelWD** 2023-12-29 15:07 UTC
Labels: S: triage
