### ISSUE TITLE
[Bug Report][3.4.0] VAutocomplete not updating items correctly when multiple and hide-selected props enabled

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuetifyjs/vuetify#18645] opened 2023-11-09 21:32 UTC
### Environment
**Vuetify Version:** 3.4.0
**Last working version:** 3.3.23
**Vue Version:** 3.3.8
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Open selection
2. Select any number of items
3. Click outside of the field to close the menu
4. Select field again
5. Delete items using backspace
6. Notice the menu items are not being added back to the menu
7. Click outside of the field to close the menu
8. Select field again
9. Notice all items are showing again

### Expected Behavior
Items should add back to the menu when removed from the field.

### Actual Behavior
Items are not being added back correctly, so the menu is not showing the correct data when using the item slot.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrdVM9L7EAM/lfCvEPfg93u88dBllUQQfHgScGD9VDbrA5MO8NMuiql/7uZ6ep2uiIK4sHDsknmS/I1X8hNK5wtZsfGpKsGxVwsCCujcsKjrAZYrKa5McEMTqFrymWNdh0KQasf39w1SgH/3GEmdnYzcXQt6QHOuTA4pWkxC4iPUzaPPYmGdKGZGBIOnwBW00qXqDjvkbtccv0L72cihqn8LoCOh4VGmLlkip7BTXKSK7nUtpZ5MoHkRCtt81J7+5RNWYbwGWp73yOu8Cl33rh+1pWs75PbcfGqUSS5bRx9kCVOHSosCMvhUzQAHsGrKvDHk2SOLXhjAsZq46AbjWw9NiUdTT2Ox3Qn65LzAj4TMCdJCjngn9PgcA3w4rxljUnMot3YhGN9hsJ+RmpoW4i0g67byvR+v2dfXTzd0M/sHjf6nev3XQIPB/SxxpvSm3Pzzg3awqy5hosVbSu7rrDSEDikpj9osjLaErRgcQkdLK2uIOEjmPS9uK6j0WIeeuzfpi5xyR3LfzEu+r5t6GLWU+DmopuIvXQvPRD+fz/9L25fAKYepo4=)

**Comment by KaelWD** [comment] 2023-11-13 16:52
Duplicate of #18648

**Closed by KaelWD** 2023-11-13 16:52 UTC
Labels: S: triage
