### ISSUE TITLE
[Bug Report][3.1.5] incorrect overlay position  in RTL locale

### ISSUE THREAD

**Issue by abumalekFayed** [vuetifyjs/vuetify#16718] opened 2023-02-20 08:15 UTC
<img width="693" alt="er2" src="https://user-images.githubusercontent.com/47514686/220049640-0bfa8ffa-432c-492b-9ad2-9adc40378665.png">
<img width="694" alt="er1" src="https://user-images.githubusercontent.com/47514686/220049663-75890391-a1e7-4b7c-8a8d-7ba6c584ccd0.png">
### Environment
**Vuetify Version:** 3.1.5
**Last working version:** 3.1.0
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
correct css for rtl 

### Expected Behavior
correct position of overlay

### Actual Behavior
float overlay to left

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#...)

**Comment by abumalekFayed** [comment] 2023-02-20 08:55
this problem started from version 3.1.1 and not found in 3.1.0

**Comment by KaelWD** [comment] 2023-02-23 15:55
Duplicate of #16628

**Closed by KaelWD** 2023-02-23 15:55 UTC
Labels: duplicate, S: triage
