### ISSUE TITLE
v-combobox does not auto-close when :items is bound to inline array

### ISSUE THREAD

**Issue by sebastiaan-de-vries** [vuetifyjs/vuetify#5038] opened 2018-09-05 03:36 UTC
## Versions and Environment
Vuetify: 1.2.2
Vue: 2.5.17
Browsers: Chrome & Firefox
OS: Linux

## Steps to reproduce
Click on the combobox and select a value.

## Expected Behavior
The combobox should close

## Actual Behavior
When :items is bound to a variable in the model, containing an array, everything works fine.
When it is bound to an array directly in the HTML, the combobox does not close.

Reproduction Link
https://codepen.io/CPSebastiaan/pen/JaJwYg

**Comment by KaelWD** [comment] 2018-09-05 05:29
Duplicate of #4663

**Closed by KaelWD** 2018-09-05 05:29 UTC
