### ISSUE TITLE
[Feature Request] snackbar plugins

### ISSUE THREAD

**Issue by YngJiaBao** [vuetifyjs/vuetify#19031] opened 2024-01-12 01:32 UTC
### Problem to solve
They are useful for alerting the user of an event and can even engage the user through actions. Also known as a toast or snackbar,like quasar Notify plugins

### Proposed solution
add vuetify plugins,like quasar plugins

**Comment by KaelWD** [comment] 2024-01-12 01:46
Duplicate of #2384

**Closed by KaelWD** 2024-01-12 01:46 UTC
Labels: S: triage
