### ISSUE TITLE
v-text-field of type file should return File

### ISSUE THREAD

**Issue by plokko** [vuetifyjs/vuetify#5192] opened 2018-09-29 13:43 UTC
v-text-field of type file  return a "fake path" string (ex: "C:\fakepath\my-uploaded-file.pdf" ) in both input and change events instead of a File class, required for Ajax uploads.

Example of an html uploader:
```
<template>
   <input type="file" @change="onFileChange" />
</template>
<script>
    export default {
    methods:{
            onFileChange(e) {
                let files = e.target.files || e.dataTransfer.files;
                this.$emit('input',files) //or return files[0] if it's not "multiple"
                this.$emit('change',files)
            },
   }
}
</script>
 ```

**Comment by KaelWD** [comment] 2018-09-29 15:10
Duplicate of #238

**Closed by KaelWD** 2018-09-29 15:10 UTC
