### ISSUE TITLE
[Bug Report] tooltips doesn't work and can't dynamically change icons with Fontawesome 

### ISSUE THREAD

**Issue by dmaloof** [vuetifyjs/vuetify#11140] opened 2020-04-16 15:12 UTC
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
adding tooltips or trying to dynamically change any fontawesome icon cause the problem

### Expected Behavior
tooltips should be shown, and icons should change

### Actual Behavior
Tooltips are not working and can't change icons dinamycally

### Reproduction Link
<a href="https://codepen.io/dmaloof/pen/YzyqXKr" target="_blank">https://codepen.io/dmaloof/pen/YzyqXKr</a>

**Comment by dmaloof** [comment] 2020-04-16 15:59
also sorting a datable with any column with icons doesn't work

**Comment by billsliu** [comment] 2020-04-16 19:42
Change the fontawesome SVG icon to regular fontawesome icon, then the problem will be gone, the SVG icon has some bugs for a long time. I recommend you to use regular icon at this time.

**Comment by KaelWD** [comment] 2020-04-16 20:01
Duplicate of #3505

**Closed by KaelWD** 2020-04-16 20:01 UTC
Labels: triage
