### ISSUE TITLE
[Bug Report][3.1.4] [v-ripple] - Ripple persists if left + right clicked fast

### ISSUE THREAD

**Issue by Troplo** [vuetifyjs/vuetify#16631] opened 2023-02-10 03:42 UTC
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0, Google Chrome, Microsoft Edge, Opera
**OS:** Linux x86_64, Windows, Linux, Mac OSX

### Steps to reproduce
- Find an element that has a v-ripple
- Left + Right clicking the element multiple times will cause the ripples to persist making the element unreadable, hovering over the element with your mouse will slowly remove the ripples individually.

### Expected Behavior
All existing ripples are removed before creating a new one.

### Actual Behavior
Ripples persist despite another one being created on the element.

### Reproduction Link
[https://github.com/Troplo/template-vuetify-crash](https://github.com/Troplo/template-vuetify-crash)

### Other comments
This happens on both Vuetify 2 & 3. Try it on the official Vuetify documentation for example.
Video: https://i.troplo.com/i/cf05004c47d0.mp4

**Comment by KaelWD** [comment] 2023-02-10 04:20
Duplicate of #4185

**Closed by KaelWD** 2023-02-10 04:20 UTC
Labels: S: triage
