### ISSUE TITLE
[Bug Report][3.3.11] VDatePicker failed in fr, de, ...

### ISSUE THREAD

**Issue by ellis2323** [vuetifyjs/vuetify#17948] opened 2023-08-02 14:10 UTC
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Google Chrome, Safari, Microsoft Edge
**OS:** Windows, Mac OSX

### Steps to reproduce
If you select the first date-picker (locale: sv), everything works. If you select a date in the french one between 25 and 30, it failed. The v-date-picker is very slow in fr. You can reproduce the bug with de locale.

### Expected Behavior
fr locale must work

### Actual Behavior
work only with en or sv locale

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUstOwzAQ/JXFl4JUx0JwqgqCG3/Aoe4hTTbF1C/ZbhCq+u+snUBLe6nUW3Y8uzM7m8WOvXpf9VtkMzZPaLyuEz5LCzDvee19+SxF42yqlcUwQgXUrqk1ch9cr1oMMNRPksVesj9iobY0mHvVbIg2C7VdZ1pX64iSQc+Na1ETkmm5GcRBR5wJXeShC1d4yM0Xecgv/7PJyBDdXBxFSmVsgvIJIqbtkKwy3oUEOwjYwR664AxM6BqTTAeguTGBiWt4yozbyRtq7eDdBd3eTO4OlMHxyDrBY3/A52KwQOJsygZ1bmpffUZn6RfY5VY5PkTJZlCQjJGrXEv2kZKPMyGa1lIbJab6UFlMwnojXogmwtYmZZC3zrw8VA/Vo2hVTMdwhdHwVXBfEQMNkWx6JJNU932B1MgsCvf3g8SIcV2vYtY4my1IsMfAA1o6IdKRL1vppO14rZOns9Wy+l7aPQWuld3Ek6ybWHJe/Jq8bucyLY9aZsX9lBWjJD10sOUP1K1O4g==)

**Comment by rafalpiechowicz** [comment] 2023-08-04 08:59
Same with pl language

**Comment by ellis2323** [comment] 2023-08-09 08:46
It works for me in the 3.3.12 version. Thanks.

**Comment by KaelWD** [comment] 2023-08-09 09:22
Duplicate of #17867

**Closed by KaelWD** 2023-08-09 09:22 UTC
Labels: S: triage
