### ISSUE TITLE
[Bug Report] Inappropriate behavior in AutoComplete

### ISSUE THREAD

**Issue by joaoeudes7** [vuetifyjs/vuetify#10408] opened 2020-02-01 05:16 UTC
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Firefox 73.0
**OS:** Linux x86_64

### Steps to reproduce
Add component v-autocomplete;
Create variable to v-model e set a default value
Add property in v-model of component

### Expected Behavior
Default value shows in component

### Actual Behavior
Not show Default value because not exists in variable of items

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-issue-auto-completete-5hzvv" target="_blank">https://codesandbox.io/s/vuetify-issue-auto-completete-5hzvv</a>

### Other comments
In some moments we want to show only a default value, and consequently we do not load the items to choose from and I think it is unnecessary to check whether the value of the v-model exists within the items array

**Comment by KaelWD** [comment] 2020-02-01 06:22
Duplicate of #4000

**Closed by KaelWD** 2020-02-01 06:22 UTC
Labels: triage
