### ISSUE TITLE
[Feature Request] To be able to create tooltips on prepended icons

### ISSUE THREAD

**Issue by twill4** [vuetifyjs/vuetify#9769] opened 2019-11-22 21:30 UTC
### Problem to solve
I have a v-list component that i'm using :prepend-icon to add my icons to all of my list items. Instead of prependicon i did the following. This has resulted in the icon acting as a child of the desired list item title
 <v-tooltip v-model="reveal" right >
            <template v-slot:activator="{ on }">
                <v-icon v-on="on" >{{item.icon}}</v-icon>
                </template>
                <span >{{item.text}}</span>
              </v-tooltip>

### Proposed solution
it would be amazing if i could use a prop like :icon-tooltip="item.text" specifically for when icons are prepended.

**Comment by jacekkarczmarczyk** [comment] 2019-12-02 17:41
I think it's a job for a slot

**Comment by jacekkarczmarczyk** [comment] 2019-12-05 05:18
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4582

**Closed by jacekkarczmarczyk** 2019-12-05 05:18 UTC
Labels: triage
