### ISSUE TITLE
[Feature Request] Add replacement image to v-img on error

### ISSUE THREAD

**Issue by Dev1lDragon** [vuetifyjs/vuetify#11221] opened 2020-04-24 09:58 UTC
### Problem to solve
When image cannot be fetched from server replacing them with one default image

### Proposed solution

- add prop `errorSrc`

- add data `loadingError`

- in `computed.normalisedSrc` add:

```
if((!this.src || this.loadingError) && this.errorSrc) {
    return typeof this.errorSrc === 'string' ? {
        src: this.errorSrc,
        srcset: this.srcset,
        lazySrc: this.lazySrc,
        aspect: Number(this.aspectRatio || 0)
    } : {
        src: this.errorSrc.src,
        srcset: this.srcset || this.errorSrc.srcset,
        lazySrc: this.lazySrc || this.errorSrc.lazySrc,
        aspect: Number(this.aspectRatio || this.errorSrc.aspect || 0)
    };
}
```

- in `methods.onError` add:

```
if (this.errorSrc) {
    this.loadingError = true;
    if (!this.isLoading) this.init(undefined, undefined, true);else this.loadImage();
}
```

- in `watch.src` add:

```
this.loadingError = false;
```

- add(if needed):

```
watch.errorSrc() {
  // Force re-init when errorSrc changes
  if (!this.isLoading) this.init(undefined, undefined, true);else this.loadImage();
},
```

**Comment by KaelWD** [comment] 2020-10-08 18:04
Duplicate of #5876

**Closed by KaelWD** 2020-10-08 18:04 UTC
Labels: C: VImg, triage
