### ISSUE TITLE
[Bug Report] v-img with svg is not loading in Edge

### ISSUE THREAD

**Issue by DeepDiver1975** [vuetifyjs/vuetify#6316] opened 2019-02-01 09:02 UTC
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Microsoft Edge
**OS:** Linux x86_64

### Steps to reproduce
<v-img src="https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Canada.svg">

### Expected Behavior
svg is displayed in Edge

### Actual Behavior
svg is not displayed in Edge

### Reproduction Link
<a href="https://codepen.io/anon/pen/exvygV" target="_blank">https://codepen.io/anon/pen/exvygV</a>

### Other comments
As far as my debugging goes image.onload is not called and the vuetify code cannot properly set the background image as result

**Comment by KaelWD** [comment] 2019-02-01 09:06
Does it work in an `<img>` tag?

**Comment by KaelWD** [comment] 2019-02-01 09:13
Just spun up a VM and it doesn't, so this has nothing to do with us.

**Comment by DRoet** [comment] 2019-02-01 09:14
@KaelWD it does work in an `img`

**Comment by DeepDiver1975** [comment] 2019-02-01 09:18
So - I simply cannot use v-img with Edge? Is that what you are trying to tell me?

**Comment by KaelWD** [comment] 2019-02-01 09:21
You can, just not with that image. When I tested it with an img tag instead edge just showed a black cross

**Comment by DeepDiver1975** [comment] 2019-02-01 09:30
I'm using Edge 42.17134.1.0

**Comment by DRoet** [comment] 2019-02-01 09:32
took me a while to fucking find it, but im using 42.17134.1.0 aswell

**Comment by KaelWD** [comment] 2019-02-01 09:43
So I checked again and it has decided to load now for some reason, but there's a weird css issue preventingthe v-img from having any width.

**Comment by daniandl** [comment] 2019-03-01 08:47
Sorry to necro, but have there been any updates regarding this? I think I'm facing this issue in Edge 41 with regular images, no svg. There seems to be no width whatsoever. The only time the image is visible, is if there's content inside the <v-img> tag.

**Comment by Mikilll94** [comment] 2019-03-27 17:02
I also have the same problem. The image is not showing in Microsoft Edge. On other browsers image is showing correctly.

Here is my code:

```
        <v-layout>
          <v-flex xs12 sm8 offset-sm2>
            <v-container fluid>
              <v-img :src="require('../assets/sample_image.jpg')"/>
            </v-container>
          </v-flex>
        </v-layout>
```

I was testing on Microsoft Edge 41.16299.967.0

**Comment by zajca** [comment] 2019-05-16 13:42
I have same issue on edge same version like @daniandl (this is older but supported version of edge, not sure about 44.17763 which is current)
Bug can be seen in documentation page, this is output:
![screenshot_2019-05-16-153902](https://user-images.githubusercontent.com/180148/57858341-24383d80-77f1-11e9-870c-7758cca273ae.png)
![screenshot_2019-05-16-153844](https://user-images.githubusercontent.com/180148/57858343-24383d80-77f1-11e9-8bd5-c7e9a1d026b7.png)

**Comment by hungnm10** [comment] 2019-07-23 02:53
Is there any update related this issue? I have a same issue with v-img in Edge.

**Comment by fuchsvomwalde** [comment] 2019-07-27 20:09
I can confirm that the bug. Please clone and start this very simple landing page with around 100 SVGs: https://github.com/hackerstolz/climathon-spa/tree/v.1.0.0
Only a few are displayed, but for almost 90% of the SVG images the `backgound-image` attribute is not written into the DOM. From my perspective it's very unlikely that there is a specific problem with the SVG images. All other browsers – desktop as well as mobile – are displaying the SVGs within the `v-img` component correctly.

**Comment by alfredriesen** [comment] 2019-09-01 20:32
Some Edge Version continue not to display v-img. Are there any afforts to solve this problem?

**Comment by alfredriesen** [comment] 2019-09-01 20:35
@KaelWD can you explain this strange behaviour you commented above? About "there's a weird css issue preventing the v-img from having any width"

**Comment by ziggybrew** [comment] 2019-09-09 18:09
On Edge 40.15063.674.0

Just ran into this issue using png, jpg, and svg and no images showed up using the <v-img> tag in Edge. Has anyone found a fix for this yet? I ended up switching the tags to just regular <img> tags for now

**Comment by SaschaAusUlm** [comment] 2019-09-19 06:15
We are running into the same issue with png images. Some show up. Some don't.

Edge 41.16299.1004.0

shows the problem.

Edge 44.18362.329.0

doesn't. It needs to be fixed. Of course we could remove all v-img tags with img .... but that doesn't seem a practical solution.

**Comment by 12s** [comment] 2019-10-01 21:50
v-img not working for me in edge 41.16299 as well.

This ticket is from Feb. 1.  Is there no plan to fix?

**Comment by michaelscheurer** [comment] 2019-11-13 16:59
Same Issue here.

**Comment by 12s** [comment] 2019-11-13 17:02
FYI, I got around it by using <v-sheet tag="img" :src="{url}"  > and edge could render images that way. edge has a problem using the background-img css param from my testint

**Comment by michaelscheurer** [comment] 2019-11-13 17:11
> 
> 
> FYI, I got around it using:
> `<v-sheet tag="img" :src="{url}" > `
> edge could render images that way. edge has a problem using the background-img css which v-img is using

Thanks for the hint. I just got a white rectancle instead. Wired.

**Comment by michaelscheurer** [comment] 2019-11-13 17:31
Found a working solution with vuetify's <v-img. You have to use the aspect-ration attribute.

Like so

```
<v-img
    :src="require('@/assets/whatever.svg')"
    :aspect-ratio="1"
></v-img>
```

**Comment by DeepDiver1975** [comment] 2020-03-10 14:50
We no longer use vuetify and also no longer support ie -> close
THX for all you support

**Comment by DRoet** [comment] 2020-03-10 15:02
should probably still keep this open for the other people

**Comment by wuori** [comment] 2020-04-03 04:52
FYI: I was able to get `v-img` using SVG to display correctly in IE (both v11 and Edge) by specifying `height` instead of `width` and using the `contain` property, like below:

`<v-img contain height="45" align="center" style="margin: 0 auto;" src="https://website.com/logo-dark.svg" alt="Logo" />`

Not sure why this fixes it vs. using width and contain, but it does.

**Comment by douglasg14b** [comment] 2020-05-26 19:09
Having the same issue with Firefox.... `v-img` doesn't display SVG images....

Seems like a bit of an issue.

**Comment by pecataToshev** [comment] 2020-06-06 05:28
Same issue on Firefox 76.0.1

**Comment by kairos0ne** [comment] 2020-06-15 14:54
Experiencing a similar issue now on all browsers. Chrome Firefox and Edge. 

`<v-img
            class="logo"
            v-if="theme.logo"
            position="left"
            :src="theme.logo"
            contain
          ></v-img>`

Tried all workarounds mentioned above and no luck. 

Shows jpeg png etc but not svg.

**Comment by wuori** [comment] 2020-06-19 01:14
@kairos0ne Did you try it with setting a `height` value?

**Comment by SaschaAusUlm** [comment] 2020-07-03 06:51
What version of Vuetify are you guys using?

**Comment by wuori** [comment] 2020-07-10 05:10
@SaschaAusUlm The incident I started chiming in with was `2.2.17`

**Comment by johnleider** [comment] 2020-12-03 19:33
This is resolved on the latest Edge which uses Chromium (I believe) and I can no longer reproduce the issue.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-03 19:33 UTC
Labels: C: VImg, T: bug, platform specific
