### ISSUE TITLE
[Bug Report] V-Autocomplete Solo-inverted not changing colour of caret,icons etc when focused

### ISSUE THREAD

**Issue by markcouvaras** [vuetifyjs/vuetify#9295] opened 2019-10-09 09:10 UTC
### Environment
**Vuetify Version:** 2.1.2
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
The issue is that once the v-autocomplete has focus the caret, dropdown arrow and any prepended or appended inner-icons should turn to black or default text colour but in this case they remain white so are not visible.

### Expected Behavior
They should be visible in dark form so that the user can see the caret, dropdown arrow and icons

### Actual Behavior
They remain white in this particular case

### Reproduction Link
<a href="https://codepen.io/maciz84/pen/dyyozpv?&editable=true&editors=101" target="_blank">https://codepen.io/maciz84/pen/dyyozpv?&editable=true&editors=101</a>

**Comment by MajesticPotatoe** [comment] 2019-10-09 14:44
duplicate of #8827

**Closed by MajesticPotatoe** 2019-10-09 14:44 UTC
Labels: triage
