### ISSUE TITLE
text field bottom bar moves to the top in flex container after transition

### ISSUE THREAD

**Issue by abelovic** [vuetifyjs/vuetify#508] opened 2017-05-09 20:43 UTC
I have found an issue with the text box inside a flex container. It only happens after a transition i.e. slide left/right/up/down although it seems to be fine with a fade.

May be related to this: https://github.com/vuetifyjs/vuetify/issues/193 except like above it works fine when not using a transition.

Here is a [codepen](https://codepen.io/ad_bel/pen/mmXePm) demonstrating the issue.  When the page first loads as you can see the textbox works as expected. When you click on the page1 link and then come back the textbox is messed up. If you remove all flex inside the page it seems to work fine too even with transitions.

Pretty bizzare. I have used this type of markup with vue-material and it worked fine :/

**Comment by abelovic** [comment] 2017-05-10 15:41
Did some more testing and it appears only to be an issue in Chrome. It works fine in both Edge and Firefox.
I just updated to the latest: Version 58.0.3029.110 (64-bit) which didn't help :(

**Comment by mfferreira** [comment] 2017-05-10 15:47
@abelovic For future reference, can you post some screenshots exposing the issue?

**Comment by abelovic** [comment] 2017-05-10 16:15
@mfferreira - Sorry ...here is an image. I had to animate it since it jumps with set focus. Since the gif loops it is hard to tell that it only works when you reload the page. After you transition it always jumps like in the screenshot. Almost seems like a relative/absolute position issue on the set focus.

![giphy](https://cloud.githubusercontent.com/assets/5751400/25908927/3429e064-3571-11e7-8129-b6b827959c8e.gif)

**Comment by johnleider** [comment] 2017-05-10 16:39
After looking through the codepen, you have some interesting styles. One in particular is setting the page position to absolute. This seems to be causing a rendering issue with the slide transition within chrome.

You'll notice if you change the transition to fade, it will always work properly. If you remove the absolute positioning from the .page class, everything works fine.

https://codepen.io/johnjleider/pen/dWdQrW

**Comment by abelovic** [comment] 2017-05-10 16:57
@johnleider - thanks for the feedback! Well this is a sample from my actual application so I tried to model the codepen css as close as i could to what I actually use. I do extensive animations/transitions with greensock & ramjet so there are cases when absolute positioning is needed :/ Also if you remove flex it is fine as well. Very strange.

I can try and work around that (as you suggested) if we can't figure it out but it seems like the positioning on a container way up in the chain should not impact these components especially if we put a place relative positioning on its parent :/ I recently moved from vue-material to vuetify and didn't have any issues with the positioning done in this manner (a straight port). So far I have also not seen this on any other vuetify component other than the text field.

**Comment by abelovic** [comment] 2017-05-10 17:08
Also why is this closed? It should be a bug because it is not respecting document flow from its parent container. Instead it is behaving erratically because absolute positioning is used somewhere in the css? It may only happen in Chrome under these conditions (that we have found so far) and may not be an easy fix but it is a bug :/

**Comment by johnleider** [comment] 2017-05-10 19:19
Correct me if I'm wrong, but this is more of a rendering issue with Chrome and less of an issue with Vuetify. You can test that by using another transition that does not cause a 3d translate on the DOM, such as fade.

**Comment by abelovic** [comment] 2017-05-10 21:03
@johnleider - well it is a rendering issue with Chrome (which is also the #1 browser) in the way that the false element you create for the input field is positioned inside its container. I tried to fix it in dev tools as well but it is hard because it changes on the on focus event. I haven't looked at the source yet but is there not another way to position that element? I assuming it is by absolute positioning? Maybe setting its parent as relative to force it to work within its document flow?

I would be concerned that if you close this it will undoubtedly pop up again. Using vue transition for sliding i.e. css transform is pretty common and it would be top level so it would be pretty easy to have a component inside this to have absolute positioning. We can't say someone can't use absolute positioning with vuetify text fields! lol

Why not leave open with label help wanted (or something similar) and see if the community has some ideas? If you close it people won't see it unless they encounter it as well. I don't think leaving hard to fix issues open means the product is not any good or not active. It just means you are still looking for a viable solution (with workarounds in the meantime) which to me is totally acceptable  :)

Just my 2 cents...

BTW This is a excellent library. Thank you for your great work as well as your quick responses!

**Comment by johnleider** [comment] 2017-05-10 21:51
I'll re-evaluate this later tonight.

**Comment by johnleider** [comment] 2017-05-10 22:44
Are you by chance running on linux? At work I was able to reproduce this but on every other device at home I am not.

**Comment by johnleider** [comment] 2017-05-11 12:58
I have put some time into this and concluded that this is something I cannot fix. I am only able to reproduce the issue on linux based systems using chrome, and can confirm it is a rendering bug. There are 3 layers of elements with relative positioning that would catch this element, even if I did something wrong, all which are having no effect.

The element that is catching it, the form, has no positioning, and with turning on and off the positioning of the ```.page``` class, forces the re-render and everything is fine. As stated above with my example, the issue can be avoided by making a small modification to your styling.

I'm going to close this as I do not feel that it is a reasonable bug to spend time on. Thank you for your post and effort in resolving this issue.

**Closed by johnleider** 2017-05-11 12:58 UTC
Labels: pending review

**Comment by abelovic** [comment] 2017-05-11 15:36
@johnleider - No I am on Windows 10.

I totally understand - thanks for taking the time to look into it! :)
