### ISSUE TITLE
[Bug Report][2.6.14]  v-data-table custom sort not working when setting server-items-length property

### ISSUE THREAD

**Issue by hienhoang272** [vuetifyjs/vuetify#17011] opened 2023-03-27 02:44 UTC
### Environment
**Vuetify Version:** 2.6.14
**Vue Version:** 2.6.14
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Add the ":server-items-length" property to a v-data-table component with any value.
2. Click on the sort icon for any column in the table.
Notice that the table does not sort according to the selected column, and the custom sort method is not called.
3. Remove the ":server-items-length" property from the v-data-table component.
4. Click on the sort icon for any column in the table.
Notice that the table sorts correctly according to the selected column, and the custom sort method is called.

### Expected Behavior
the table sorts correctly according to the selected column

### Actual Behavior
the table does not sort according to the selected column

### Reproduction Link
[https://codepen.io/fuliver123/pen/abaXQrE](https://codepen.io/fuliver123/pen/abaXQrE)

**Comment by KaelWD** [comment] 2023-03-27 12:34
Duplicate of #14645

**Closed by KaelWD** 2023-03-27 12:34 UTC
Labels: S: triage
