### ISSUE TITLE
[Documentation] Cannot Build. Module not found: Error: Can't resolve 'vuetify/es5/[*]'

### ISSUE THREAD

**Issue by aDotInTheVoid** [vuetifyjs/vuetify#9997] opened 2019-12-18 00:00 UTC
### Environment

**Browsers:** Firefox 71.0
**OS:** Mac OS 10.14

### Steps to reproduce
```bash
$ yarn
$ yarn build
```

### Expected Behavior
Run's without errors

### Actual Behavior
[Full Error](https://pastebin.com/z20k2USL)
Relevent exerpt
```
vuetifyjs.com:     ERROR in ./src/examples/scroll/usage.vue?vue&type=script&lang=js& (/Users/nixon/dev/web/hack-n-slash/vuetify/node_modules/babel-loader/lib!/Users/nixon/dev/web/hack-n-slash/vuetify/node_modules/vue-loader/lib??vue-loader-options!./src/examples/scroll/usage.vue?vue&type=script&lang=js&)
vuetifyjs.com:     Module not found: Error: Can't resolve 'vuetify/es5/services/goto/easing-patterns' in '/Users/nixon/dev/web/hack-n-slash/vuetify/packages/docs/src/examples/scroll'
vuetifyjs.com:      @ ./src/examples/scroll/usage.vue?vue&type=script&lang=js& (/Users/nixon/dev/web/hack-n-slash/vuetify/node_modules/babel-loader/lib!/Users/nixon/dev/web/hack-n-slash/vuetify/node_modules/vue-loader/lib??vue-loader-options!./src/examples/scroll/usage.vue?vue&type=script&lang=js&) 99:0-69 112:27-34
vuetifyjs.com:      @ ./src/examples/scroll/usage.vue?vue&type=script&lang=js&
vuetifyjs.com:      @ ./src/examples/scroll/usage.vue
vuetifyjs.com:      @ ./src/examples lazy-once ^\.\/.*\.vue$ namespace object
vuetifyjs.com:      @ /Users/nixon/dev/web/hack-n-slash/vuetify/node_modules/babel-loader/lib!/Users/nixon/dev/web/hack-n-slash/vuetify/node_modules/vue-loader/lib??vue-loader-options!./src/components/doc/Example.vue?vue&type=script&lang=js&
vuetifyjs.com:      @ ./src/components/doc/Example.vue?vue&type=script&lang=js&
vuetifyjs.com:      @ ./src/components/doc/Example.vue
vuetifyjs.com:      @ ./src/components sync \.vue$
vuetifyjs.com:      @ ./src/components/index.js
vuetifyjs.com:      @ ./src/main.js
vuetifyjs.com:      @ ./src/entry-client.js
```

### Reproduction Link
<a href="https://vuetifyjs.com/ NOT APPLICABLE" target="_blank">https://vuetifyjs.com/ NOT APPLICABLE</a>

**Comment by MajesticPotatoe** [comment] 2019-12-18 00:12
duplicate of #8300

**Closed by MajesticPotatoe** 2019-12-18 00:12 UTC
Labels: triage
