### ISSUE TITLE
[Bug Report][3.2.2] V-Dialog after scroll does not work correctly with dropdown menu (V-Autocomplete, V-Select and etc)

### ISSUE THREAD

**Issue by sadiolem** [vuetifyjs/vuetify#17292] opened 2023-05-04 09:15 UTC
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1) Scroll down page content
2) Open dialog
3) Click on input

### Expected Behavior
Dropdown menu opens

### Actual Behavior
Dropdown menu does not open (or it's shifted somewhere down so you can't see it)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtmjtvE0EQx7/K6BpAsu9EQAJFBgUJOjpElUux2R07Q/aVfThBUb47s3e2uCRSGijHbrwzc/P67TXW//y++xJjv6/YnXabgi5aVfDz6AE2+7WKcfo5HZwiD9qqnD+NXVTrj2N3cLL7GNc+Y/c9JHRAMVcHJtiQIFMB5bCsQAefURcsNYEyFClr8jtAS+zMaPgBQKrZBQOtH36YvCZDpvoCtYBVl5wesMypEZzaeQXK0k1VPfwsgJ4c5wZH7ceej8qt4KZSBh9ySdUA3mHSVFSh4KFaq5wOc+YWRJlapSklRQ4GVNy4457CPACXKj18bSlVLQiUKncyz8prShgTXqE3mHhwNuyDrZHLIbfDkwLmjKDJ2uOGeKAK27ojVcC3hiCqxIeaevh2pzEW5IVl4h0ErRVqjtM1klGclcfyEFMgg75tsW2qwao2qjY3hO2WNCkwmDE1rwu2taHagojXkQ97ra4fu9HzVyAKRIEoEAWiQBSIAlEgCkSBKBAFokAUiAJRIApEgfh/Ico/qPI+CkSBKBAFokAUiAJRIApEgSgQBaJAFIgCUSAKRIEoEF+AeJSkDn81qaxevSwezrQlfc3q1XwVbr+SsmEHn4DXiixlbTYwk3EzTPHLx2cHsAo2GLSPUixksFOoVsks1bClCWlrCYwhWuRFnhJfjyaiPX+7gpMVvLsYOxiWSbj+oyzNMHdwlOOyoelxZ6EuH2al7mZYKHj5mHWiWPhyltrc1C5lgXumvIUH2Kbg4BVLf1+14HY7OHS5GQ57vVU245ul+4dX+vpSpScBm2GuxnW6VTeX4h5j/ysHz+Li+9bqeHDksTuFydJs3EI7j91VKTGfDkP18XrX88KGM/YNDTw5XJvgzt71J/37D4OhXJb2HrNbX6Zwy9eEK47dapG80Pb34wLaeI5ikrRPvccy+OiGQ+RU4mSucDCt+YrlVuJZ6oHr7TGt0/TKYHpxjiexj2Z54ns2T6v5MPoH3q0lf52frFXnaaXnx9b+adApWct00Qo+rLq5US49PdFd/AEZTuyu)

### Other comments
And dropdown menu opens correctly only on second click

**Comment by KaelWD** [comment] 2023-05-04 09:19
Duplicate of #16770

**Closed by KaelWD** 2023-05-04 09:19 UTC
Labels: S: triage
