### ISSUE TITLE
[Bug Report] v-icon props no longer passed through to custom component

### ISSUE THREAD

**Issue by david-nguyen** [vuetifyjs/vuetify#12551] opened 2020-11-03 21:03 UTC
### Environment
**Vuetify Version:** 2.3.11
**Last working version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 86.0.4240.111
**OS:** Windows 10

### Steps to reproduce
When using v-icon, props assigned are longer passed through to the child custom component. While inspecting the props are visible in attrs but not assigned further.

### Expected Behavior
props are passed through

### Actual Behavior
props are not passed to custom component

### Reproduction Link
<a href="https://github.com/david-nguyen/vuetify-bug-props" target="_blank">https://github.com/david-nguyen/vuetify-bug-props</a>

**Comment by david-nguyen** [comment] 2020-11-03 21:06
![image](https://user-images.githubusercontent.com/1424016/98040515-9fbeed80-1ddd-11eb-844c-3068063ded5f.png)
![image](https://user-images.githubusercontent.com/1424016/98040559-aea5a000-1ddd-11eb-820e-b74a7abdf414.png)

**Comment by johnleider** [comment] 2020-12-03 17:16
You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

* [Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)
* [Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
* [Codepen](https://template.vuetifyjs.com)
* [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
* A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by david-nguyen** [comment] 2020-12-03 17:21
sorry repro updated.

**Comment by johnleider** [comment] 2020-12-03 17:39
Closing as duplicate of https://github.com/vuetifyjs/vuetify/issues/6403

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-03 17:39 UTC
Labels: C: VIcon, S: needs reproduction, T: bug, T: regression

**Comment by david-nguyen** [comment] 2020-12-03 17:44
Is this really a feature request? It was working in 2.3.10
