### ISSUE TITLE
[Feature Request] There is no way to get 'primary', 'accent' etc colours in Sass

### ISSUE THREAD

**Issue by mattgreenfield** [vuetifyjs/vuetify#9023] opened 2019-09-19 08:46 UTC
### Problem to solve
I want to be able to use `$primary` in my Sass to get the primary theme colour set in the Vuetify config. e.g. 
```scss
.block::after {
    background-color: map-get($primary, 'base');
}
```

I've notice that I can get the many colours using `map-get($purple, 'base')` [here](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/styles/settings/_colors.scss) but this is not available for the theme colours defined [here](https://vuetifyjs.com/en/customization/theme#customizing).

### Proposed solution
I imagine there will need to be something that generates these variables/maps at build time. It would not be possible to change the value with JS at runtime unless using CSS custom properties.

It would be great if these values changed based on which theme was set (light or dark) in `~vuetify/src/styles/settings/_theme.scss`

**Comment by KaelWD** [comment] 2019-09-24 05:27
Duplicate of #8149

**Closed by KaelWD** 2019-09-24 05:27 UTC
Labels: triage
