### ISSUE TITLE
[Feature Request] Improve style of DatePicker Range to reflect Material Design

### ISSUE THREAD

**Issue by Shinigami92** [vuetifyjs/vuetify#11174] opened 2020-04-21 08:37 UTC
### Problem to solve
Currently when we use a `v-date-picker` with `range`, the selection are styled as each single day is a circle. (https://vuetifyjs.com/en/components/date-pickers/#date-pickers-range)

The Material Design Guidelines show this in a different way:
https://material.io/components/pickers#desktop-pickers

Example: https://kstatic.googleusercontent.com/files/61ad374cd9722b64a94970bb196187a0ac6be84d0db7c956080deeb9e28e096a8bb5a12da3d0f3b2d0c7ed6f8ce3e428e2252f232a15e8e49a1c606f7a028da3

You can see that the `start` and `end` are connected with styled rows in another color.

### Proposed solution
Improve the styling so it reflects Material Design Guidelines

**Comment by jacekkarczmarczyk** [comment] 2020-04-21 08:51
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9608

**Closed by jacekkarczmarczyk** 2020-04-21 08:51 UTC
Labels: triage

**Comment by Shinigami92** [comment] 2020-04-21 09:52
Ah ok, didn't know thats a `MD2` thing
Also the duplicate issue addresses another thing (month-overflow)
And this issue was only intended to use the MD2 styling instead of circles
But I'm fine with the duplication
