### ISSUE TITLE
[Bug Report] Breakpoints not updating correctly on resize

### ISSUE THREAD

**Issue by Meffesino** [vuetifyjs/vuetify#12020] opened 2020-08-07 12:50 UTC
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Windows 10

#### This is the process as expected:

- **Load page at sm size** and move mouse over check icon: Tooltip is shown (as expected)
- Resize page to md size and hover over check icon: Tooltip is not shown (as expected)
- Resize page back to sm size and hover over check icon: Tooltip is not shown (as expected)

#### This is the error:

- **Load the page at md size** and move mouse over check icon: Tooltip is not shown (as expected)
- Resize page to **sm size** and hover over check icon: Tooltip is not shown (**should be shown**)

### Expected Behavior
When the page is **loaded at md+ size**:
- tooltip is not shown 
- re-size screen to sm: tooltip should be shown.

### Actual Behavior
Tooltip is not shown at sm screen size, when page is loaded at md+ screen size. 

But is working correctly as expected, when page is loaded at sm screen size and resize to any size.

### Reproduction Link
<a href="https://codepen.io/Meffesino/pen/ZEWYxyR" target="_blank">https://codepen.io/Meffesino/pen/ZEWYxyR</a>

**Comment by johnleider** [comment] 2020-12-08 21:42
Duplicate of #11101

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-08 21:42 UTC
Labels: triage
