### ISSUE TITLE
[Bug Report] V-Autocomplete does not display slotted label with "filled" property.

### ISSUE THREAD

**Issue by Threnos** [vuetifyjs/vuetify#12370] opened 2020-10-07 16:12 UTC
### Environment
**Vuetify Version:** 2.3.13
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Linux x86_64

### Steps to reproduce
In codepen you will see three v-autocomplete inputs.
The first one shows actual bug - custom label from slot is not shown when input has "filled" property.
The second shows that without "filled", custom label is there as expected.
On the third we can see that custom slot renders with "filled" prop and with "label" prop set.

### Expected Behavior
Can set my own label using slot with "filled" alternate input style.

### Actual Behavior
Whatever goes into slot does not render.

### Reproduction Link
<a href="https://codepen.io/threnos/pen/wvWvrvd" target="_blank">https://codepen.io/threnos/pen/wvWvrvd</a>

### Other comments
For now I will use third variant, as it allows to achieve expected result.

**Comment by KaelWD** [comment] 2020-10-07 16:13
Duplicate of #11533

**Closed by KaelWD** 2020-10-07 16:13 UTC
