### ISSUE TITLE
[Bug Report] Select in full mode dialog

### ISSUE THREAD

**Issue by snezhkoigor** [vuetifyjs/vuetify#2831] opened 2017-12-19 09:48 UTC
### Versions and Environment
**Vuetify:** 1.0.0-alpha.3
**Vue:** 2.5.11
**Browsers:** Safari 11.0.2
**OS:** Mac OS 10.13.2

### Steps to reproduce
click to open dialog and try to select something

### Expected Behavior
wanna see select items

### Actual Behavior
not see by wrong z-index

### Reproduction Link
[https://codepen.io/snezhkois/pen/ZvWWgg](https://codepen.io/snezhkois/pen/ZvWWgg)

**Comment by KaelWD** [comment] 2017-12-19 09:49
Duplicate of #2111

**Closed by KaelWD** 2017-12-19 09:49 UTC
