### ISSUE TITLE
[Bug Report] VSelect: close menu on icon click

### ISSUE THREAD

**Issue by OstapL** [vuetifyjs/vuetify#8916] opened 2019-09-10 12:05 UTC
### Environment
**Vuetify Version:** 2.0.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.4

### Steps to reproduce
- click on select
- expect menu
- Click on icon

### Expected Behavior
open and close the select menu by click on the icon 

### Actual Behavior
menu not closing by click

### Reproduction Link
<a href="https://codepen.io/OstapL/pen/wvwmyyV" target="_blank">https://codepen.io/OstapL/pen/wvwmyyV</a>

**Comment by MajesticPotatoe** [comment] 2019-09-10 12:09
This is resolved by setting the following:
`:menu-props="{ closeOnClick: true }"`

**Comment by MajesticPotatoe** [comment] 2019-09-10 12:17
nvm that. this is still there. prop above can stand as a temp workaround.

**Comment by OstapL** [comment] 2019-09-10 12:36
@MajesticPotatoe yes, I know about closeOnClick, but even with this it's not working
https://codepen.io/OstapL/pen/wvwmyyV

**Comment by jacekkarczmarczyk** [comment] 2019-09-10 17:04
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6564

**Closed by jacekkarczmarczyk** 2019-09-10 17:04 UTC
Labels: C: VSelect, T: bug
