### ISSUE TITLE
[Bug Report] Tooltip content doesn't scroll inside

### ISSUE THREAD

**Issue by iamr0man** [vuetifyjs/vuetify#12847] opened 2020-12-27 10:04 UTC
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 10.14.6

### Steps to reproduce
Add style overflow ```<div style="max-height: 150px; overflow: auto;" v-html="comment.Comment" />```

### Expected Behavior
Ability to scroll content inside tooltip.

### Actual Behavior
Scroll doesn't appear

### Reproduction Link
<a href="https://codesandbox.io/s/zen-moser-w9gwo?file=/src/components/Comment.vue" target="_blank">https://codesandbox.io/s/zen-moser-w9gwo?file=/src/components/Comment.vue</a>

**Comment by KaelWD** [comment] 2020-12-27 10:07
Duplicate of #12838

**Closed by KaelWD** 2020-12-27 10:07 UTC
Labels: triage
