### ISSUE TITLE
[Bug Report] Forms inside V-Menu don't work properly

### ISSUE THREAD

**Issue by d-mellen** [vuetifyjs/vuetify#5468] opened 2018-10-29 09:05 UTC
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Put a text-field inside a v-menu and then a v-form around the text-field (doesn't matter if the form is inside the menu or outside)

### Expected Behavior
Pressing enter in the text-field should fire the submit method

### Actual Behavior
Submit method doesn't get called

### Reproduction Link
[https://codepen.io/anon/pen/QZPExW](https://codepen.io/anon/pen/QZPExW)

### Other comments
An alternative would be to dettach the menu from the input component(s), but then the size of the menu has to be defined manually. Additionally the submit button doesn't get fired when selecting it by tabbing through the element and then pressing enter.

**Comment by KaelWD** [comment] 2018-10-29 11:09
Duplicate of #2988, related to #4974

**Closed by KaelWD** 2018-10-29 11:09 UTC
