### ISSUE TITLE
[Feature Request] all form components need props for resize.

### ISSUE THREAD

**Issue by MicroDreamIT** [vuetifyjs/vuetify#13002] opened 2021-01-22 19:15 UTC
### Problem to solve
v-text-field
v-select
v-autocomplete
etc components dont have options to resize. It will be nice to have options like small, x-small etc options

### Proposed solution
It will be nice to have options like small, x-small etc options

**Comment by KaelWD** [comment] 2021-06-21 16:31
Duplicate of #3220, #9579

**Closed by KaelWD** 2021-06-21 16:31 UTC
Labels: C: VInput, T: feature
