### ISSUE TITLE
[Bug Report] Time Picker problem in menu and dialog

### ISSUE THREAD

**Issue by nasermirzaei89** [vuetifyjs/vuetify#9260] opened 2019-10-07 13:17 UTC
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.13.6

### Steps to reproduce
Use time picker in dialog or menu
See the Reproduction link  or [Vuetify Documentations](https://vuetifyjs.com/en/components/time-pickers#in-dialog-and-menu)

### Expected Behavior
It should show the clock

### Actual Behavior
It doesn't show the clock

### Reproduction Link
<a href="https://codepen.io/nasermirzaei89/pen/MWWYaZM" target="_blank">https://codepen.io/nasermirzaei89/pen/MWWYaZM</a>

**Comment by MajesticPotatoe** [comment] 2019-10-07 13:23
duplicate of #9084 (reopened)
Has to do with `full-width` prop

**Closed by MajesticPotatoe** 2019-10-07 13:23 UTC
Labels: triage
