### ISSUE TITLE
[Bug Report] Label aligment on full-width textareas

### ISSUE THREAD

**Issue by monsdroid** [vuetifyjs/vuetify#4639] opened 2018-07-17 15:27 UTC
### Versions and Environment
Vuetify: 1.1.4
Vue: 2.5.16
Browsers: Chrome 67.0.3396.99
OS: Windows 10

### Steps to reproduce
v-textarea with label and full-width

### Expected Behavior
same as without full-width, label on top

### Actual Behavior
label keeps position inside full-width

### Reproduction Link
https://codepen.io/monsdroid/pen/KBMzVa?editors=1010

**Comment by praveenpuglia** [comment] 2018-07-18 11:29
Looking into it.

**Comment by praveenpuglia** [comment] 2018-07-24 07:10
Hi @monsdroid . Sorry! Haven't been able to look into it due to personal things. I'll check it out as soon as I can.

**Comment by praveenpuglia** [comment] 2018-07-31 07:37
@KaelWD , @johnleider  - is this really required ?
https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_text-fields.styl#L260-L261

this is causing the bug. I don't think floating labels are tested with the texarea with the `full-width` prop set. The bug can also be seen at https://vuetifyjs.com/en/components/text-fields#example-full-width-with-character-counter

## Steps to reproduce
- Remove the content of the message field. See the cursor and the label placement. 

If we remove the top calculation for the textarea label, it works as expected.

**Comment by praveenpuglia** [comment] 2018-07-31 08:14
Further investigation. 
![image](https://user-images.githubusercontent.com/313363/43446886-a8d09b9a-94c7-11e8-8124-f038aaf0bac2.png)


Both of these styles force the label to come down. I am not sure of the required behaviour with all the combinations of `single-line` and `full-width` props

**Comment by praveenpuglia** [comment] 2018-09-18 05:06
Didn't realize I got assigned to it. Will check it out today.

**Comment by kaminilsen** [comment] 2019-01-29 03:03
Are there any updates on this?

**Comment by catonalake** [comment] 2019-02-17 21:45
Also wondering if there was any progress on the v-textarea label relocation when users start to enter data :)

**Closed** 2020-01-09 20:59 UTC
Labels: C: VTextarea, T: bug
