### ISSUE TITLE
[Bug Report] v-checkbox is not working while clicking on the checkbox with @click event

### ISSUE THREAD

**Issue by mahammad8564** [vuetifyjs/vuetify#10666] opened 2020-02-25 07:32 UTC
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Linux x86_64

### Steps to reproduce
- Have a checkbox with @click event (with @change event is working)
- Click on the checkbox, not the label (click on the label is working)

### Expected Behavior
It should be working while clicking on the checkbox with @click event

### Actual Behavior
not working while clicking on the checkbox with @click event

### Reproduction Link
<a href="https://codepen.io/mahammad8564-the-animator/pen/RwPKqYR?editable=true&editors=101" target="_blank">https://codepen.io/mahammad8564-the-animator/pen/RwPKqYR?editable=true&editors=101</a>

**Comment by KaelWD** [comment] 2020-02-25 07:35
Duplicate of #5968

**Closed by KaelWD** 2020-02-25 07:35 UTC
Labels: triage
