### ISSUE TITLE
[Bug Report] v-tabs not centered under sm

### ISSUE THREAD

**Issue by JonathanVandal** [vuetifyjs/vuetify#8804] opened 2019-08-30 14:29 UTC
### Environment
**Vuetify Version:** 2.0.10
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Resize the page until mobile (sm / xs) and the tabs are not centered. There is a margin left.

### Expected Behavior
Centered v-tabs like before in 1.5. Here is a codepen in 1.5 https://codepen.io/Johngtrs/pen/QWLMEbo

### Actual Behavior
v-tabs are not centered and there is a margin left.

### Reproduction Link
<a href="https://codepen.io/Johngtrs/pen/RwbZRPx" target="_blank">https://codepen.io/Johngtrs/pen/RwbZRPx</a>

### Other comments
I just took codepen from the vuetify documentation, I didn't change the code.

**Comment by jacekkarczmarczyk** [comment] 2019-08-30 14:33
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8294

**Closed by jacekkarczmarczyk** 2019-08-30 14:33 UTC
Labels: triage
