### ISSUE TITLE
[Feature Request] Auto import mdijs icons

### ISSUE THREAD

**Issue by ctwhome** [vuetifyjs/vuetify#11706] opened 2020-06-23 04:49 UTC
### Problem to solve
Hi! it would be lovely to have in your babel plugin an option to auto-import v-icon with @mdijs.
A real example from my code:
```
import {
  mdiChevronRight,
  mdiChevronLeft,
  mdiApplication,
  mdiHomeOutline,
  mdiDatabaseSync,
  mdiFileLockOutline,
} from '@mdi/js'

export default {
  data() {
    return {
      mdiChevronRight,
      mdiChevronLeft,
      mdiApplication,
      mdiHomeOutline,
      mdiDatabaseSync,
      mdiFileLockOutline,


```

### Proposed solution
That would save some newcomers "brain-glitch" :) (coming from font icons) and for the rest to worry less about another dependency in the code.

**Comment by KaelWD** [comment] 2020-06-23 05:13
Duplicate of https://github.com/vuetifyjs/vuetify-loader/issues/86

**Closed by KaelWD** 2020-06-23 05:13 UTC
Labels: triage
