### ISSUE TITLE
[Bug Report] Failing transitions on some Safari 9

### ISSUE THREAD

**Issue by neelance** [vuetifyjs/vuetify#3760] opened 2018-04-04 10:53 UTC
### Versions and Environment
**Vuetify:** 1.0.12
**Vue:** 2.5.16
**Browsers:** Safari
**OS:** Mac OSX

### Steps to reproduce
Use Safari 9 (we have 9.1.2). Open https://vuetifyjs.com/en/.

### Expected Behavior
The page shows up.

### Actual Behavior
The page stays blank.

### Reproduction Link
[https://jsfiddle.net/bbphrr5u/](https://jsfiddle.net/bbphrr5u/)

### Other comments
There seems to be some issue with the transitions. The same happens with our own page, so I figured that https://vuetifyjs.com/en/ might be a good way to reproduce. I hope my assumption is correct that your homepage is supposed to work on Safari 9, as the framework itself is advertised as supporting that version?

**Comment by johnleider** [comment] 2018-04-04 15:49
Your assumption is correct, looking into it.

**Comment by chewy94** [comment] 2018-04-04 17:25
I have used BrowserStack to emulate Safari v9.x.x (Mac El Capitan, Safari 9.1.3) and cannot reproduce the issue. The site loads up just fine and I also tested other components that use transitions without issue.

There is a console error of `Viewport argument key "minimal-ui" not recognized and ignored.`

Still looking deeper into the issue.

**Comment by chewy94** [comment] 2018-04-04 17:28
After researching, `minimal-ui` is not related to this issue at all. It has something to deal with the address bar shrinking to give the view port more room

**Comment by neelance** [comment] 2018-04-05 11:05
I now tried a VirtualBox with vanilla El Capitan. It has Safai 9.0 and it works fine. Might work fine for the same reason that BrowserStack is working fine. Alternatively the old MacBook we have is somehow special. We really need some other actual old MacBook to confirm.

**Comment by johnleider** [comment] 2018-04-05 12:48
In light of this, I will be closing this issue. If a method of reproduction outside of the old mac book comes about, we can re-open and re-visit.

**Comment by neelance** [comment] 2018-04-05 12:51
@johnleider If that's you policy, then could you still claim "Safari 9 supported", even if it breaks on all actual installations of Safari 9?

**Comment by neelance** [comment] 2018-04-05 12:59
@johnleider I'm sorry to being annoying, but the target group of our project is older people and many of our customers have Safari 9 on their MacBooks that they never updated. We're currently losing a significant amount of revenue because of this and this is why I started investigating.

Since Safari versions are tied to OS X versions and OS X versions are tied to MacBook versions, saying "We don't support Safari 9 on old MacBooks" effectively means "We don't support Safari 9 at all", since there are no new MacBooks with Safari 9, you can't even install it on those.

**Comment by johnleider** [comment] 2018-04-05 13:05
It might be best for you to come to the community and work through testing and fixing locally. If we have no way to reproduce this, we have no way to fix it. If your MacBook is the only device we have right now exhibiting the behavior, we're going to need your help in resolving this.

https://community.vuetifyjs.com

**Comment by neelance** [comment] 2018-04-05 13:10
I'm already working on it. I'm currently trying to downgrade an old MacBook of mine to El Capitan. Takes some time, though.

I'm only a bit annoyed that you closed the issue so quickly. We should at least get a second data point from a different actual MacBook to see if this potentially affects all Safari 9 users or not. If it does, then claiming "Safari 9 is supported" is simply wrong. That it works in BrowserStack and VirtualBox only proves that it works fine in virtual machines.

**Comment by neelance** [comment] 2018-04-05 13:13
fyi: A few months ago our site worked mostly fine on that particular MacBook that is now broken. Today it stays blank due to the transition bug. This indicates a regression.

**Comment by neelance** [comment] 2018-04-05 14:35
All right, El Capitan finally got installed and I had a Safari 9.1.2 for testing. And it turns out that it works fine. This is enough proof for me that this is not a general issue with Safari 9. We can keep this issue closed for now. I'll investigate the other MacBook soon (it is not my own). If I can find the reason why it doesn't work, then I will open a new issue.

**Comment by johnleider** [comment] 2018-04-05 15:03
Forgot to re-open.

**Comment by neelance** [comment] 2018-04-05 15:10
@johnleider Thanks. :) I've changed the title so it reflects the current understanding of this bug.

**Comment by johnleider** [comment] 2018-04-05 15:11
Don't forget to pop into the community. Makes it easier to do joint debugging.

**Comment by neelance** [comment] 2018-04-06 10:41
I found something that can be reproduced: Many transitions happen twice on Safari 9. For example if I go to https://vuetifyjs.com/en/getting-started/quick-start and expand sections of the menu, they open, close and open again. I can also reproduce it on VirtualBox. Solving it might also solve the other issue, since it is also related to transitions.

@chewy94 Would you mind testing this on BrowserStack? I don't have an account.

**Comment by chewy94** [comment] 2018-04-06 13:47
I can confirm that the behavior you have discovered does happen on browserstack (Safari 9.1)

**Comment by johnleider** [comment] 2020-01-19 18:52
I cannot reproduce this issue in browserstack Safari 9.1

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-19 18:52 UTC
Labels: Framework, help wanted, platform specific

**Comment by SlappyAUS** [comment] 2020-09-05 11:24
I am having this issue with Safari 13.1.2 on macOs 10.15.6
https://vuetifyjs.com/en/components/cards/
errors out with: Viewport argument key "minimal-ui" not recognized and ignored.
It breaks the layout.
