### ISSUE TITLE
[Bug Report][3.1.5] Epiphany browser compatibility issue

### ISSUE THREAD

**Issue by TeodoraMiu** [vuetifyjs/vuetify#16735] opened 2023-02-21 11:26 UTC
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.2.47
**Browsers:** Other
**OS:** Linux

### Steps to reproduce
1. Epiphany 42.4 is needed in order to reproduce this issue.
2. In the base directory of the repo, run 'yarn dev'.
3. Open localhost:3000 in the Epiphany browser. 
4. Click on the "Activator Slot" menu, and then click anywhere to close the menu.
5. Open the browser inspector. A warning and an error should appear in the browser console.

### Expected Behavior
The menu should close without errors or warnings.

### Actual Behavior
The menu closes, but a warning ('Unhandled error during execution of watcher callback') and error ('Unhandled Promise Rejection: ReferenceError: Can't find variable: cancelIdleCallback') are shown.

### Reproduction Link
[https://github.com/TeodoraMiu/epiphany_vuetify_issue](https://github.com/TeodoraMiu/epiphany_vuetify_issue)

### Other comments
I was using Vuetify with [Tauri](https://github.com/tauri-apps/tauri) in order to build an application. Since Tauri uses Epiphany as its default browser, I noticed that when I used a Menu component from Vuetify (v-menu), I would get this error and I would be unable to, for example, use Vue Router to switch to another window view. 
Linked to https://github.com/vuejs/core/issues/7770

**Comment by KaelWD** [comment] 2023-02-21 11:27
Duplicate of #16613

**Closed by KaelWD** 2023-02-21 11:27 UTC
