### ISSUE TITLE
[Bug Report] v-dialog doesn't display slot if slot is rendered later

### ISSUE THREAD

**Issue by Chovin** [vuetifyjs/vuetify#9377] opened 2019-10-16 14:33 UTC
### Environment
**Vuetify Version:** 2.1.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
use v-dialog with an activator slot that is rendered after v-dialog renders

### Expected Behavior
slot is visible

### Actual Behavior
slot is rendered as a child of the v-dialog DOM element, making it not visible

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-8vd6g" target="_blank">https://codesandbox.io/s/vue-template-8vd6g</a>

### Other comments
trying to toggle between two buttons that open their corresponding dialogs: https://codesandbox.io/s/vue-template-25evs (use for this makes more sense when the v-dialogs are their own custom components)

trying that same thing in 2.0.20 https://codesandbox.io/s/vue-template-1uu87
it works until you try to login again. the login button never reappears.

**Comment by mandaputtra** [comment] 2020-12-29 15:01
Why is this won't be fixed? Is there any way ti implement this?

**Comment by lioneaglesolutions** [comment] 2023-05-04 01:47
This issue is being closed due to inactivity. If this is still present in the latest version, please submit a new issue with a reproduction.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).

**Closed by lioneaglesolutions** 2023-05-04 01:47 UTC
Labels: wontfix, T: documentation
