### ISSUE TITLE
[Bug Report] v-calendar clips long events at the end of a day

### ISSUE THREAD

**Issue by LightSnowDev** [vuetifyjs/vuetify#6487] opened 2019-02-13 11:46 UTC
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Chrome 73.0.3683.27
**OS:** Windows 10

### Steps to reproduce
Make an event so long it overlaps two days.
In the codepen example the event "smash potatoes" is bugged.

### Expected Behavior
The event should reappear the next day with the remaining time.

### Actual Behavior
The event is not displayed the next day (gone).

### Reproduction Link
<a href="https://codepen.io/anon/pen/exjRGm" target="_blank">https://codepen.io/anon/pen/exjRGm</a>

**Comment by blalan05** [comment] 2019-02-13 14:02
Duplicate of #6307

**Closed** 2019-02-13 14:05 UTC
Labels: S: has PR, duplicate
