### ISSUE TITLE
[Feature Request] v-date-input type and format

### ISSUE THREAD

**Issue by Cirrusware** [vuetifyjs/vuetify#20353] opened 2024-08-17 13:28 UTC
### Problem to solve
Before in V2, we had picker from date, month or year.

### Proposed solution
Reintroduce type to define (date, month, year) and props:
- day-format
- month-format
- year-format
- weekday-format

**Comment by KaelWD** [comment] 2024-09-06 09:46
Duplicate of #19803

**Closed by KaelWD** 2024-09-06 09:46 UTC
Labels: S: triage
