### ISSUE TITLE
[Bug Report][3.1.5] VColorPicker

### ISSUE THREAD

**Issue by joshuakaleb0424** [vuetifyjs/vuetify#16697] opened 2023-02-17 02:05 UTC
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.2.45
**Browsers:** Firefox 111.0
**OS:** Linux

### Steps to reproduce
1. Input a hex value for the input
2. Press enter or click outside the input field

### Expected Behavior
Color picker will switch to the inputted hex color

### Actual Behavior
Color picker's value becomes #FFAFAF

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVkctOwzAQRX9l8CYgNbZ4baq0Kjv+gEXTRUmmxTR+yHYKqMq/M3YS1IdAYpe5Mz73zmR5YE/W8n2LbMqKgMo264DzUgMU+3xtbfpMhVpLPVSprkxjXG5ltUM3ygDK1Dgr2Rt+lmxU54U4HR+hJP9QY9H7FeIoB5W+ctIG8Bja2JbKGhfgAA430MHGGQUZLZDF4cpoH0D5Lcxi/zp7xqYx8GJcU19lNxHe4wjEJqxnUQjL373RdINDzFIODV+yKSQlauQRa1ouBOunQrTa7ra8MkosqCdcq4NUmNdGLe75HX94FLX04Vjn6FX+6syHR0eOJZscwYPcfP1mMLSJe8sH7CBF5AVKEH+PLneoa3T0f/7KfTZ7kv2sd5E/enal7uiWjdQ7f3bGyqcTLsdo/1pMSc0TIL5eRZNuwvpwZJcesNU33iTo3w==)

**Comment by KaelWD** [comment] 2023-02-17 05:01
Duplicate of #16672

**Closed by KaelWD** 2023-02-17 05:01 UTC
Labels: S: triage
