### ISSUE TITLE
[Bug Report] Datepicker in birthday mode does not respect the 

### ISSUE THREAD

**Issue by pancake-boy** [vuetifyjs/vuetify#9514] opened 2019-10-30 02:31 UTC
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. https://vuetifyjs.com/en/components/date-pickers#examples
2. scroll down to birthday picker
3. Edit in codepen
4. set picker-date to "2000" or "2000-11" or "2000-06-15"

### Expected Behavior
Year scrolled to 2000

### Actual Behavior
The title is set to 2000 but the year still shows 2019

### Reproduction Link
<a href="https://codepen.io/anthonyhaha/pen/abbLWxw?&editable=true&editors=101" target="_blank">https://codepen.io/anthonyhaha/pen/abbLWxw?&editable=true&editors=101</a>

### Other comments
the goal is to improve usability so older people don't need to scroll so much from the top

**Comment by johnleider** [comment] 2020-01-14 01:09
Duplicate of #9587

**Closed by johnleider** 2020-01-14 01:09 UTC
Labels: C: VDatepicker, triage
