### ISSUE TITLE
[Bug Report] v-select with return-object misbehave on tab-in

### ISSUE THREAD

**Issue by marchign** [vuetifyjs/vuetify#2893] opened 2017-12-29 17:50 UTC
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.2
**Browsers:** Chrome 63.0.3239.84
**OS:** Mac OS 10.11.6

### Steps to reproduce
Select 'North Carolina';
press tab until the next field get focus;
press shift-tab to transfer focus again to v-select field;
press tab again to transfer focus to next field.

### Expected Behavior
the menu should remain closed and 'North Carolina' should be the selected value.

### Actual Behavior
When the v-select gains focus it opens the menu even if a value is already selected, when it loose focus the second time the field value changes to the first value of the list.

### Reproduction Link
[https://codepen.io/marchign/pen/xpdZaG?editors=1010](https://codepen.io/marchign/pen/xpdZaG?editors=1010)

### Other comments
It is possible to obtain the expected behaviour removing the return-object directive or using the same id used for the text (ie remove `'id-'+` from line 21).

**Comment by KaelWD** [comment] 2018-01-19 11:03
Duplicate of #2754

**Closed by KaelWD** 2018-01-19 11:03 UTC
Labels: bug
