### ISSUE TITLE
[Bug Report] v-menu: remove offset from the top edge of the screen

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#12009] opened 2020-08-06 11:52 UTC
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.122
**OS:** Linux x86_64

### Steps to reproduce
Repo link is the sample from the docs.
Try clicking on the picture at the very top edge of the screen. 
It does not matter how close the click is to the edge, the absolute menu top position is at least 12px.
The same behavior has v-menu + activator + nudgeTop property - there's no way to show the menu closer than 12px from the top edge of the screen.

I'm currently implementing the design with a rather narrow navbar, and I need the menu to be opened at the 8px from the top. 

### Expected Behavior
If we really need the restriction to 12px from the edges, the last should be optional. 

### Actual Behavior
It's impossible to show the menu so that the distance between the it's top border and the screen top is less than 12px.

### Reproduction Link
<a href="https://codepen.io/kasheftin/pen/ZEWYzMX" target="_blank">https://codepen.io/kasheftin/pen/ZEWYzMX</a>

**Comment by Kasheftin** [comment] 2020-08-06 12:11
As a quick work-around for this I was able to use `content-class="menu-offset-class"` and `.menu-offset-class { margin: -10px 0 0 0; }`

**Comment by achiyahb** [comment] 2021-02-22 10:39
@Kasheftin  worked for me also, thank you!!

**Comment by KaelWD** [comment] 2021-07-15 06:02
Duplicate of #11818

**Closed by KaelWD** 2021-07-15 06:02 UTC
Labels: C: VMenu, T: enhancement, T: feature
