### ISSUE TITLE
tabs don't follow the route

### ISSUE THREAD

**Issue by crearis** [vuetifyjs/vuetify#291] opened 2017-03-30 13:41 UTC
### Steps to reproduce
1. go to https://dasei-2ef39.firebaseapp.com/
> it should serve you with navigation options:
- workshops/test1
- workshops/test2

2. clicking on them correctly updates the route (nav-list change)
BUT: Tabs visually remain on route /
AND: inspecting the DOM SHOWS TWO active tabs!! ('/' alias DAS Ei + 'Workshops')

### MY CODE 
A) vue-code
```
<v-tabs grow icons ScrollBars=false>
        <v-tab-item slot="activators" ripple href='/' :router="true" :nuxt="true" class="foldertab foldertab-big grey darken-2">
          DAS Ei
          <v-icon><img src="~assets/img/logo_on.gif" height="50" width="50" alt="DAS Ei Logo"></v-icon>
        </v-tab-item>
        <v-tab-item slot="activators" ripple href='/workshops/' :router="true" :nuxt="true" class="foldertab grey darken-2">
          Workshops
          <v-icon>bubble_chart</v-icon>
</v-tab-item>
        <v-tab-content v-bind:id="'/'" slot="content" class="home-text grey darken-1">
          <p>DAS Ei - theaterpädagogisches Institut Bayern e.V<br>
          Fürtherstraße 174a<br>
          90429 Nürnberg</p>
          <br>
          <p>Tel: 0911/7808476<br>
          Fax: 0911/3236691<br>
          eMail: info@dasei.eu</p>
          <br>
          <p>Seminar München:<br>
          Hermann-Lingg-Straße 2</p>
        </v-tab-content>
        <v-tab-content v-bind:id="'/workshops/'" slot="content">
        </v-tab-content>
```
        

### Details of Error-State in the browser
FIRST TAB
```
<a href="/" class="tab__item tab__item--active">
        DAS Ei
        <i class="material-icons icon"><img src="/_nuxt/img/logo_on.e4e2b5d.gif" alt="DAS Ei Logo" height="50" width="50"></i></a>
```

SECOND TAB
```
<a href="/workshops/" class="tab__item--active tab__item">
        Workshops
        <i class="material-icons icon">bubble_chart</i></a>        <i class="material-icons icon">bubble_chart</i>
```

### Versions

0.9.4
Firefox + Chrome
I work through windows

### Reproduction Link

https://dasei-2ef39.firebaseapp.com/

**Comment by johnleider** [comment] 2017-04-04 00:59
this is a duplicate of #273, going to go ahead and close this.

**Closed by johnleider** 2017-04-04 00:59 UTC
Labels: bug

**Comment by crearis** [comment] 2017-04-05 11:03
Sorry for this … initially I had just requested help … then you asked me to open the issue, later I recognized it might be a duplicate … since I am a newcomer I still have to learn

Von: John Leider [mailto:notifications@github.com]
Gesendet: Dienstag, 4. April 2017 02:59
An: vuetifyjs/vuetify <vuetify@noreply.github.com>
Cc: Hans Doenitz <hans.doenitz@dasei.eu>; Author <author@noreply.github.com>
Betreff: Re: [vuetifyjs/vuetify] tabs don't follow the route (#291)


this is a duplicate of #273<https://github.com/vuetifyjs/vuetify/issues/273>, going to go ahead and close this.

**Comment by johnleider** [comment] 2017-04-05 12:36
No worries. Thank you for your support.
