### ISSUE TITLE
[Feature Request] Programmatic global Alert or Snackebars, Dialog

### ISSUE THREAD

**Issue by azhengyongqin** [vuetifyjs/vuetify#13641] opened 2021-05-12 11:37 UTC
### Problem to solve
`Alert`, `Snackebars`, and `Dialog` is a very frequently used component, but they are inconvenient to use now and are too intrusive to HTML

### Proposed solution

**Alert**
reference: https://element.eleme.cn/#/en-US/component/message#message
```js
this.$vuetify.$alert({
    message: 'Congrats, this is a success message.',
    type: 'success',
    duration: 2000
});
```

---

**Dialog**
reference: https://element.eleme.cn/#/en-US/component/dialog
```js
this.$vuetify.$dialog(
    {
        title: 'Title',
        content: 'This is content...',
        showCancelButton: true,
        confirmButtonText: 'OK',
        cancelButtonText: 'Cancel',
        type: 'warning'
    }).then(() => {
        console.log("click OK");
    }).catch(() => {
        console.log("click Cancel");
    })
```

---

**SnackBars**
Same as above

---

**Other scenes**
If you provide a programmatic method of use.
Then I can handle my `axios` interceptor uniformly, and when respons to a certain `StatusCode`, I can directly pop up an error Alert
```js
axios.interceptors.response.use(
    response => {
        const res = response.data
        if (res.code !== 200) {
            Vuetify.$alert({
                message: res.message,
                type: 'error',
                duration: 2000
            })
        }
    },
    error => {
        Vuetify.$alert({
            message: error.message,
            type: 'error',
            duration: 2000
        })
        return Promise.reject(error)
    }
);

```

I saw someone put forward this request in 2018. Can you tell me the reason for not adopting this suggestion?

**Comment by KaelWD** [comment] 2021-05-17 08:09
Duplicate of #3037

**Closed by KaelWD** 2021-05-17 08:09 UTC
Labels: triage

**Comment by kieuminhcanh** [comment] 2023-04-09 01:01
@azhengyongqin 

I have created a project to provide toasters, dialogs, alerts, confirms, and prompts. It's also support show component in dialog.

Source: https://github.com/kieuminhcanh/vuetify-notifier

Demo: https://kieuminhcanh.github.io/vuetify-notifier
