### ISSUE TITLE
[Bug Report] <v-btn disabled> can still be clickable and open <v-menu>

### ISSUE THREAD

**Issue by henriq-88** [vuetifyjs/vuetify#5851] opened 2018-12-10 00:42 UTC
### Versions and Environment
**Vuetify:** 1.3.12
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Mac OS 10.14.1

### Steps to reproduce
Create a `<v-menu>` with a nested `<v-btn slot="activator" disabled>`

### Expected Behavior
Not to open the `<v-menu>`

### Actual Behavior
The `<v-btn disabled>` can still open the `<v-menu>`

### Reproduction Link
<a href="https://codepen.io/henriq88/pen/WLNJRe?&editable=true&editors=101" target="_blank">https://codepen.io/henriq88/pen/WLNJRe?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment] 2018-12-10 01:35
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1911

To disable menu you need to disable menu, not the contents of the menu activator

**Closed by jacekkarczmarczyk** 2018-12-10 01:35 UTC
