### ISSUE TITLE
[Bug Report] v-select with chips and no "styling" props, opening of the selection menu is not triggered when chips are clicked

### ISSUE THREAD

**Issue by Thyme1152** [vuetifyjs/vuetify#10805] opened 2020-03-10 15:57 UTC
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Mac OS 10.14.4

### Steps to reproduce
* Create a simple list with `chips` and `multiple` props
* Click on a chip and note that the selection menu does not open
* Add a styling prop such as `solo`, `filled` or `outlined`
* Click a chip again and note that the selection menu now opens

### Expected Behavior
The selection menu is supposed to open when you click a chip on a v-select with chips, whether it has styling props or not.

### Actual Behavior
The menu doesn't open. 

### Reproduction Link
<a href="https://codepen.io/thyme1152/pen/NWqXJZe" target="_blank">https://codepen.io/thyme1152/pen/NWqXJZe</a>

### Other comments
This is currently observable in the documentation for `v-select`, under "Light theme".

**Comment by KaelWD** [comment] 2020-03-10 16:07
Alright guys which one is it? #10774

**Comment by mdebortoli** [comment] 2020-03-15 14:06
@KaelWD I think both are the same issue. The dropdown drawer will open or not when clicking on the chips, depending on the props selected on the component. In the case of my report (#10774), I think it's pointless to open the drawer when removing an item so I believe it's a bug.

**Comment by Vercadium** [comment] 2020-03-18 13:15
> @KaelWD I think both are the same issue. The dropdown drawer will open or not when clicking on the chips, depending on the props selected on the component. In the case of my report (#10774), I think it's pointless to open the drawer when removing an item so I believe it's a bug.

Agreed; having the select open when removing a chip is an unexpected UX and feels like a bug.

**Comment by TrobbinsForNow** [comment] 2020-03-25 18:02
@KaelWD I'll echo what @mdebortoli and @Vercadium said - the menu shouldn't open when removing a chip. I found this discussion when intending to open an issue after the closure of #5428. I can't speak to the issue here, but I'm fully in support of #10774 

Here's a simpler codepen for reference to show this bug with a v-select, outlined and not:
https://codepen.io/trobbins2/pen/yLNQNyv?editors=1011

**Comment by johnleider** [comment] 2020-04-04 18:52
Duplicate of #10774

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-04-04 18:52 UTC
Labels: triage
