### ISSUE TITLE
Backlighting on valid v-radio-group

### ISSUE THREAD

**Issue by true-tema** [vuetifyjs/vuetify#2222] opened 2017-10-18 06:36 UTC
### Versions
Vuetify 0.16, Vue.js v2.5.2, Google Chrome  61.0.3163.100 

### What is expected ?
Backlighting the item's v-radio-group red color when the item is validated on submit form.

### What is actually happening ?
Backlighting the item's v-radio-group black color when the item is validated on submit form.

### Reproduction Link
https://codepen.io/true_tema/pen/NaewLQ?editors=1011

**Comment by nekosaur** [comment] 2017-10-18 06:38
Duplicate of #2212

**Closed by nekosaur** 2017-10-18 06:38 UTC
Labels: duplicate
