### ISSUE TITLE
[Bug Report][3.3.11] Performance issue on VDatePicker when in VMenu

### ISSUE THREAD

**Issue by yannmichaux** [vuetifyjs/vuetify#17970] opened 2023-08-05 20:27 UTC
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Setup your vuetify project
2. Create a VTextField within a VMenu and use VTextField as activator
3. Add a VDatePicker inside the VMenu
4. Choose a date on VDatePicker
5. Check the console for a warning about maximum recursive updates

### Expected Behavior
VDatePicker work without performance issue

### Actual Behavior
VDatePicker may freeze the page when user click on it

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUs1unDAQfpWRL0mkNVaUntAmStXHCDl4YWjcGNuyB5Jqxbt3MOwKyCVSL8vOeL6f+eyXs/gZQjH0KEpxJOyC1YRPlQM4DlKHkP/movaOtHEYl1Zuduh6OHki30FZW59QepdH0ZGsranfHyvRapuwElcgQy9SMMhkPZW6JjNo8pHHzxCiDwnGDSTrEX6SbA3aZn0AzHIyrmFsRlZie1p2vkErB2175JmGdfcjvifLy+1orT6hZcQbWuvhw0fW3QDVeie1ye/qeZKTgZPAyD6zlasJeDMNyml579KK7ajmbC/xc7nNf+rM17OR5TLV0QRi6+43yxCHkQGmCz4SnKHBlll+ea4dXxKM0Ea+vRt+AzcTAQB+5lEe1L3N3zXg9jx74gV0Cbd38PgEl17uYgmut3bujHfTd/o9qtkZuxEHMduRnQ7Fn+Qdv75MUS0H7LqEhbQSbG2q+R6IQiqVqhvHMA7SDLFwSMqFTj3zmIq9I9OhbHz3/FA8FD9UYxKt2wWmTp6i/0gYmaQSh5UMmfbvN6SWyaxwfz9LLD3JbyZNGl+4FQsOGGVE12DE+N2VdrD1WrujL6vl7Cs3cuD8ut/TLus65ZxfLib/b+fMNlG9TorjQWSjLD0jxOs/+FFs3A==)

### Other comments
Using "eager" props on VDatePicker seem to reduce the time for the bug to appear, and, it appears only the first time we select a date

**Comment by ellis2323** [comment] 2023-08-06 10:27
What's your locale ? DatePicker seems slow with locale different than 'en' or 'sv'.

**Comment by yannmichaux** [comment] 2023-08-08 06:57
I'm using the "fr" locale and "en" as fallback with vue-i18n v9

**Comment by avarixe** [comment] 2023-08-08 16:10
VDatePicker seems to freeze regardless of whether you have it inside a VMenu or not. It's the `hide-actions` prop that is affecting this:

https://play.vuetifyjs.com/#eNqlUktOwzAQvcrIG0CqYyFYRQGBOAZhYeIpGPyT7QRQ1bszdgJE7aYSmyTzPO8zEz/u2H0IzTQia1mX0QYjM972DqCbuAyhftZi8C5L7TAuUAUzfma+1WgUtNYrNHySZsSbninS6Rn4MRsiKTDyGQ3hr2iMhw8fjaJjsRYrFB708I4RJl7l/oRetUIuh6y9S7+0ThzmKsgcuxOrcahMQ9QhUw73Qqo59awStA0+ZtiBwi2pPHiqHboMe9hGb+GMdnNWBADws7ZSoxxNfa8J57s5E+WVLZxfwM0t/GAVxRbcaMyM7C/Kuzw7MSejNGzD5jjcytC8Je/or1SJfjmg1C0soj2jaKWmpeYcUivEoBzRaG96io3DLFyw4o7aRBxd1ha58vbuqrlqroXSKa/hBpPlz9F/JIwk0rPNyibr7dcJVktndbi8nC0WjNMFSMXjSFuQ4YSRR3QKI8ZTRzqgrcc6ODoare6+d3taON3O93Sw6yHVPT/+hPzfzFWtSD0Vx/2G1aBkPTPY0zfomC1o

**Comment by ellis2323** [comment] 2023-08-09 08:45
It works like expected with the 3.3.12 version for me.

**Comment by KaelWD** [comment] 2023-08-09 09:23
Duplicate of #17867

**Closed by KaelWD** 2023-08-09 09:23 UTC
Labels: S: triage
