### ISSUE TITLE
[Feature Request] Date range picker not following MD specs

### ISSUE THREAD

**Issue by ThomasKuhlmann** [vuetifyjs/vuetify#10845] opened 2020-03-15 11:21 UTC
### Problem to solve
The current date range picker is simply a single date picker that highlights multiple dates. But a date range is not the same as multiple selected dates, so the visual feedback from the vuetify picker is incorrect.

### Proposed solution
Follow MD specs: https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F1ow2svD50eumJzHFJUZc4PLKZCAJJCYsX%2Fpicker-desktop-singledate-selectdate.mp4

**Comment by KaelWD** [comment] 2020-03-15 12:57
Duplicate of #9608

material.io didn't have range pickers when this was implemented.

**Closed by KaelWD** 2020-03-15 12:57 UTC
Labels: triage

**Comment by ThomasKuhlmann** [comment] 2020-03-15 13:04
Sorry about the duplicate!
