### ISSUE TITLE
[Feature Request] Please publish the basic tree-view component，Please，Please，Please

### ISSUE THREAD

**Issue by lowece** [vuetifyjs/vuetify#17789] opened 2023-07-12 02:47 UTC
### Problem to solve
Please publish the basic tree-view component，Please，Please，Please

### Proposed solution
Please publish the basic tree-view component，Please，Please，Please

**Comment by KaelWD** [comment] 2023-07-12 14:38
Duplicate of #13518

**Closed by KaelWD** 2023-07-12 14:38 UTC
Labels: S: triage
