### ISSUE TITLE
[Feature Request] [Feature Request] Add supoort for inertia.js Link component in Vuetify

### ISSUE THREAD

**Issue by omsrivastava** [vuetifyjs/vuetify#19149] opened 2024-02-01 19:41 UTC
### Problem to solve
Unable to use inertiajs Link with vuetify components like - v-list-item, v-btn

### Proposed solution
There should be an option to use inertiajs Link with vuetify

**Comment by KaelWD** [comment] 2024-02-02 02:38
Duplicate of #11573

**Closed by KaelWD** 2024-02-02 02:38 UTC
Labels: S: triage
