### ISSUE TITLE
[Bug Report] v-select value is not serialized on form submit

### ISSUE THREAD

**Issue by enterlight** [vuetifyjs/vuetify#6961] opened 2019-04-10 12:07 UTC
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.5.17
**Browsers:** Chrome 73.0.3683.86
**OS:** Windows 10

### Steps to reproduce
Create a v-select inside a v-form.  Set :items=['a','b','c'] and name="letters"
Run and select 'a'
Submit the form and look at formdata.  

### Expected Behavior
name should be 'a'

### Actual Behavior
name is 'undefined'

### Reproduction Link
<a href="https://codepen.io/bibi123/pen/EJWmmG?editors=1111" target="_blank">https://codepen.io/bibi123/pen/EJWmmG?editors=1111</a>

**Comment by KaelWD** [comment] 2019-04-10 12:21
Duplicate of #6310

**Closed by KaelWD** 2019-04-10 12:21 UTC
