### ISSUE TITLE
[Bug Report] v-menu outputs block element if using v-slot syntax with activator

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#7194] opened 2019-05-13 08:22 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Windows 10

### Steps to reproduce
Create a `v-menu` with an activator using the `v-slot` syntax.

### Expected Behavior
`.v-menu` element should not occupy space or alter the rendering in the DOM in any way.

### Actual Behavior
`.v-menu` has `display: block` which breaks inline elements.

### Reproduction Link
<a href="https://codepen.io/anon/pen/xNEExG" target="_blank">https://codepen.io/anon/pen/xNEExG</a>

### Other comments
When using the old `slot="activator"` the class `.v-menu--inline` is added to the element. This is added here: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VMenu/VMenu.js#L227

It should probaby be changed to use `$scopedSlots` instead.

**Comment by KaelWD** [comment] 2019-05-13 10:37
Duplicate of #6951

**Closed by KaelWD** 2019-05-13 10:37 UTC
Labels: triage
