### ISSUE TITLE
[Feature Request] Button with tooltip component

### ISSUE THREAD

**Issue by kevinmnm** [vuetifyjs/vuetify#17497] opened 2023-05-30 17:56 UTC
### Problem to solve
I wrap `<v-btn>` component into `<v-tooltip>` component extensively (especially if it's an icon button) and I'm sure I'm not alone. It'll be very helpful to have native Vuetify component that fulfills this role instead of me having to create a custom wrapper component (or wrap every time). 

## Current Approach:
```html
<v-tooltip>
   <template v-slot:activator="{ props }">
      <v-btn v-bind="props">
         <v-icon>mdi-menu</v-icon>
      </v-btn>
   </template>
   <span>Menu!</span>
</v-tooltip>
```

## Proposed Solution:
```html
<v-btn tooltip="Menu!">
   <v-icon>mdi-menu</v-icon>
</v-btn>
```

**Comment by lioneaglesolutions** [comment] 2023-05-30 20:03
I feel like this would be trying to combine too many props into on component - position, location, enabled etc. @johnleider?

**Comment by johnleider** [comment] 2023-05-30 21:18
We plan to handle this a bit differently. Watch https://github.com/vuetifyjs/vuetify/pull/17395

**Comment by KaelWD** [comment] 2023-05-31 04:59
Duplicate of #9610

**Closed by KaelWD** 2023-05-31 04:59 UTC
Labels: duplicate
