### ISSUE TITLE
[Bug] Wrong margin of last radio in a row

### ISSUE THREAD

**Issue by Djaler** [vuetifyjs/vuetify#5270] opened 2018-10-11 13:42 UTC
Version and Environment
Vuetify: 1.2.8
Vue: 2.5.17
Browsers: Chrome
OS: Linux

Steps to reproduce
Put some radio inputs in a row

Expected Behavior
They should have the same vertical position.

Actual Behavior
Vertical position of the last radio is different from the others 

Reproduction Link
https://codepen.io/anon/pen/GYEZLN

**Comment by kevinmarrec** [comment] 2018-10-11 13:50
Additionally, the bug is visible in the documentation itself : 
https://vuetifyjs.com/en/components/selection-controls#example-radios-direction

**Comment by KaelWD** [comment] 2018-10-11 14:29
Duplicate of #5255

**Closed by KaelWD** 2018-10-11 14:29 UTC
