### ISSUE TITLE
[Feature Request] treeview track indeterminate nodes

### ISSUE THREAD

**Issue by snoopy83101** [vuetifyjs/vuetify#9736] opened 2019-11-20 02:32 UTC
### Problem to solve
treeview partially selected?

when selection-type = 'leaf'

i hope get partially node.  But I can't do it.. 

 

### Proposed solution
I think this is a functional defect

**Comment by snoopy83101** [comment] 2019-11-20 02:34
![image](https://user-images.githubusercontent.com/24613784/69204248-513f2180-0b81-11ea-9154-e2d393989bf6.png)

**Comment by Leespiker** [comment] 2020-04-05 07:45
In the meantime, [here's a way](https://codepen.io/Leespiker/pen/abOgJXo) to track indeterminate and non-leaf nodes in leaf mode.

**Comment by KaelWD** [comment] 2020-07-15 10:16
Duplicate of #6590

**Closed by KaelWD** 2020-07-15 10:16 UTC
Labels: C: VTreeview, T: feature
