### ISSUE TITLE
[Feature Request] Expansion Lists inside Autocomplete

### ISSUE THREAD

**Issue by lloydbanks** [vuetifyjs/vuetify#7593] opened 2019-06-20 09:23 UTC
### Problem to solve
Here's an example of how Autocomplete supports a group of elements https://codepen.io/lloydbanks/pen/RzozLV?editors=1010

The problem is, a quite number of items make it awkward to use.

### Proposed solution
Solution: hide nested elements by default and show them on click.

We already have "Expansion Lists" here https://vuetifyjs.com/en/components/lists#expansion-lists
So it would be great to use this feature inside Autocomplete component.

Thanks.

**Comment by KaelWD** [comment] 2019-06-20 09:29
Duplicate of #6089

**Closed by KaelWD** 2019-06-20 09:29 UTC
Labels: triage
