### ISSUE TITLE
[Bug Report] v-select does not show select items on iOS when in toolbar

### ISSUE THREAD

**Issue by meungo** [vuetifyjs/vuetify#7531] opened 2019-06-16 08:43 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** iOS, Mac OSX

### Steps to reproduce
Open the codepen on iOS (only have reproduced this on iPad Pro) click on button. The select do not show the select items

### Expected Behavior
Display select items as it does on Window OS for example

### Actual Behavior
Does not display the select items

### Reproduction Link
<a href="https://codepen.io/meungo/pen/WqwNyr" target="_blank">https://codepen.io/meungo/pen/WqwNyr</a>

### Other comments
Seems similar to issue https://github.com/vuetifyjs/vuetify/issues/2111

**Comment by KaelWD** [comment] 2019-06-16 09:26
Duplicate of #5351

**Closed by KaelWD** 2019-06-16 09:26 UTC
Labels: duplicate
