### ISSUE TITLE
[Feature Request] create waterfall layout component

### ISSUE THREAD

**Issue by zhaop33** [vuetifyjs/vuetify#8873] opened 2019-09-06 00:51 UTC
### Problem to solve
How could I create a waterfall layout component? I use like this,But it didn't show as expected
![image](https://user-images.githubusercontent.com/27794742/64393351-8e683d00-d083-11e9-9576-53f5ed512f3a.png)

### Proposed solution
create a waterfall layout component

**Comment by ibrahimBeladi** [comment] 2019-09-06 02:18
I guess you mean **masonry layout**. Rename the issue title for better discoverability and visibility.

**Comment by KaelWD** [comment] 2019-09-06 06:40
Duplicate of #4091

**Closed** 2019-09-06 06:40 UTC
Labels: duplicate
