### ISSUE TITLE
Parallax component doesn't work when src linked to local assets folder

### ISSUE THREAD

**Issue by YassineBoudriga** [vuetifyjs/vuetify#4668] opened 2018-07-19 15:35 UTC
### Versions and Environment
Vuetify: 1.1.7
Vue: 2.5.16
Browsers: Chrome and Edge
OS: Windows 10

### Previously worked in:
Vuetify:
Vue:

### Steps to reproduce

Use the Vuetify Parallax component inside of a Vue component and link the src to an image inside of the assets folder, import the component in App.vue and use it.
### Expected Behavior

Parallax to show the image 
### Actual Behavior

No image, just an icon appears in the middle

### Reproduction Link

Can't reproduce on Codepen.io, needs vue-cli and the asset folder to see the bug.
---

**Comment by jacekkarczmarczyk** [comment] 2018-07-19 16:13
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1656

**Closed by jacekkarczmarczyk** 2018-07-19 16:13 UTC
