### ISSUE TITLE
[Bug Report] updating expansion panels data causes incorrect index to be given

### ISSUE THREAD

**Issue by gotenxds** [vuetifyjs/vuetify#11225] opened 2020-04-24 14:14 UTC
### Environment
**Vuetify Version:** 2.2.23
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
in codepen:
Click the expansion panels, see index changes to 0 for the first panel and 1 for the second panel.
This is Ok

Click on the ADD MORE button, to add another item to the top of the list.

click on the first expansion panel, see that selected index is 2, but index of the item in the list is actually 0

### Expected Behavior
Clicking on expansion panel should update with the correct index of the item in the actual data array

### Actual Behavior
The expansion list is rendered correctly (in correct order) but items have incorrect indexes when updating v-model

### Reproduction Link
<a href="https://codepen.io/gotenxds/pen/GRpWEvO?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fexpansion-panels%2F" target="_blank">https://codepen.io/gotenxds/pen/GRpWEvO?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fexpansion-panels%2F</a>

**Comment by kflavin** [comment] 2020-05-10 18:48
I'm experiencing this in 1.5.14 as well.

**Comment by gotenxds** [comment] 2020-07-12 14:48
This begins to become quite old but progression was done here, this bug makes expansion panels unusable with dynamic lists, any plans on fixing this?

**Comment by Mert75** [comment] 2020-08-14 19:38
Kind of similar to #11405 where it happens on a VListItemGroup

**Comment by adatdeltax** [comment] 2021-01-29 14:52
Has anyone found a workaround for this issue?.

**Comment by parktheredcar** [comment] 2021-01-29 15:14
I ended up switching from using 1 `v-expansion-panels` element with N `v-expansion-panel` elements, to using N `v-expansion-panels` elements with 1 `v-expansion-panel` each, and managing open/closed state myself. Not ideal maybe but the page looks and behaves like it should now.

**Comment by johnleider** [comment] 2021-06-22 21:33
Duplicate of #8001

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-06-22 21:33 UTC
Labels: C: VExpansionPanel, P: high, T: bug
