### ISSUE TITLE
[Bug Report][3.1.13] `v-tabs` incorrect initial tab on SSR

### ISSUE THREAD

**Issue by trandaison** [vuetifyjs/vuetify#17110] opened 2023-04-09 02:29 UTC
### Environment
**Vuetify Version:** 3.1.13
**Vue Version:** 3.2.41
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 12.5.1

### Steps to reproduce
The code below works perfectly on client-side rendering. But with SSR, it's not working. 
```vue
<template>
  <v-tabs v-model="tab" align-tabs="title">
    <v-tab
      v-for="item in tabs"
      :key="item"
      :value="item"
      :to="{ query: { tab: item } }"
    >
      {{ item }}
    </v-tab>
  </v-tabs>
</template>

<script setup lang="ts">
  const tabs = ref(['web', 'videos']);
  const tab = ref('videos');
</script>
```

### Expected Behavior
Both SSR and CSR the initial tab will be the `videos` tab.

### Actual Behavior
On SSR, the initial tab was the first tab. On CRS, it was the `videos` tab.

### Reproduction Link
[https://stackblitz.com/edit/github-1ddaaf?file=pages%2Findex.vue](https://stackblitz.com/edit/github-1ddaaf?file=pages%2Findex.vue)

**Comment by KaelWD** [comment] 2023-04-09 03:55
Duplicate of #15207

**Closed by KaelWD** 2023-04-09 03:55 UTC
Labels: S: triage
