### ISSUE TITLE
[Bug Report] When hide or reopen VDialog, the transition is not working

### ISSUE THREAD

**Issue by shanlh** [vuetifyjs/vuetify#10528] opened 2020-02-09 08:03 UTC
### Environment
**Vuetify Version:** 2.2.11
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.3

### Steps to reproduce
Click the "CLICK ME" button, and click "I ACCEPT" button, the VDialog's hide transition is not working, also when I reopen the Dialog.

### Expected Behavior
Have the hide/show transition, same as V2.2.8

### Actual Behavior
Not working

### Reproduction Link
<a href="https://codepen.io/johnnydan/pen/xxGbaPG?editable=true&editors=101" target="_blank">https://codepen.io/johnnydan/pen/xxGbaPG?editable=true&editors=101</a>

**Comment by KaelWD** [comment] 2020-02-09 08:06
Duplicate of #10506

**Closed by KaelWD** 2020-02-09 08:06 UTC
Labels: triage
