### ISSUE TITLE
[Bug Report] Footer - text is not centered when using "absolute" prop

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#9492] opened 2019-10-28 17:30 UTC
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
1. Go to the codepen.
2. As you can see text in footer is not centered. It is much closer to the right side than to the left.

### Expected Behavior
Text in footer should be centered

### Actual Behavior
Text in footer is not centered

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/QWWMvwo" target="_blank">https://codepen.io/mikilll94/pen/QWWMvwo</a>

### Other comments
Problem occurs only when using "absolute" prop on footer. If you remove "absolute" prop, text is perfectly centered.

**Comment by jacekkarczmarczyk** [comment] 2019-11-11 08:18
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9372

**Closed by jacekkarczmarczyk** 2019-11-11 08:18 UTC
Labels: triage
