### ISSUE TITLE
[Bug Report][2.3.16] v-tabs-slider

### ISSUE THREAD

**Issue by telion2** [vuetifyjs/vuetify#14429] opened 2021-11-23 17:44 UTC
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.11
**Browsers:** Firefox 94.0
**OS:** Ubuntu undefined

### Steps to reproduce
Hi, I think I go a bug with the v-tabs-slider. When mounting it, it doesn't calculate the correct width to display as you can see in the picture provided. When resizing the window, it corrects itself. 
The Code I use: 
```
... 
<v-tabs
        color="#e20074"
        center-active
        show-arrows="false"
        v-model="tab"
      >
        <v-tab
          class="tabTitle"
          v-for="(tabItem, index) in redirections"
          :key="index"
        >
          {{ tabItem.name }}
        </v-tab>
      </v-tabs>
...
mounted() {
    this.tab = this.redirections.length > 1 ? 1 : 0;
},
computed:{
    redirections() {
      return [
        {
          key: "myAccount",
          name: this.$t("myAccount"),
          color: "",
        },
        ...
      ]
    }
}
```

### Expected Behavior
The slider immediately calculates the correct size. On Update (or whenever the watcher is triggered) is too late. 

### Actual Behavior
The slider calculates the size, when one of its watchers is triggered. If they are not triggered for whatever reason, the slider gets the wrong width. It also might be the case that the calculation is wrong, but since it works when resizing the window e.g., I guess it's the reactivity. 

### Reproduction Link
<a href="https://codepen.io/erichaemmerle/pen/rNzgPrj" target="_blank">https://codepen.io/erichaemmerle/pen/rNzgPrj</a>

### Other comments
I blame: https://github.com/vuetifyjs/vuetify/blob/8bb752b210d25fbebcea12cd073d2ce4986f5e12/packages/vuetify/src/components/VTabs/VTabs.ts#L128
Because the way I interpret it, is that the watcher call "callSlider" (https://github.com/vuetifyjs/vuetify/blob/8bb752b210d25fbebcea12cd073d2ce4986f5e12/packages/vuetify/src/components/VTabs/VTabs.ts#L150) 
but the watcher is only called on update and not immediately. 

The solution I propose is to create the watchers like this: 
```
watch:{
    alignWithTitle: {
      handler() {
          this.callSlider()
      },
      immediate: true,     //calls the watcher at the latest on mounted
    },
}
```

**Comment by telion2** [comment] 2021-11-23 17:46
![Screenshot from 2021-11-23 18-45-31](https://user-images.githubusercontent.com/30474592/143077056-d4942abe-40b9-4b08-b0e2-3786f9161c0c.png)

**Comment by telion2** [comment] 2021-11-23 17:53
I personally solved it by forcing the watchers to trigger like this: 

```
mounted() {
    this.$vuetify.application.left = 1;
    setTimeout(() => {
      this.$vuetify.application.left = 0;
    }, 200);
  },
```
Basically v-tabs-slider watches $vuetify.application.left and calls "onResize". I overwrite that value and change it back again after some time. 
This however is quite a dirty workaround, and one where I am not sure how stable it is.

**Comment by KaelWD** [comment] 2021-11-23 17:57
It is already called on mounted: https://github.com/vuetifyjs/vuetify/blob/8bb752b210d25fbebcea12cd073d2ce4986f5e12/packages/vuetify/src/components/VTabs/VTabs.ts#L143-L147

Duplicate of #4733

**Closed by KaelWD** 2021-11-23 17:57 UTC
Labels: S: triage
