### ISSUE TITLE
[Bug Report] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Nandiin** [vuetifyjs/vuetify#8144] opened 2019-07-29 13:03 UTC
### Environment
**Vuetify Version:** 1.5.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
1. open the reproduction link
2. open browser console to inspect the error message.
3. click the upper button in the repro demo.
4. the error occurrs

### Expected Behavior
Should work without throwing any errors.

### Actual Behavior
Throwing Maximum call stack size exceed

### Reproduction Link
<a href="https://codepen.io/anon/pen/BXpPRM" target="_blank">https://codepen.io/anon/pen/BXpPRM</a>

### Other comments

This is not the same as #5633

This usecase is simplified from my real project and and the `v-if`s on the `v-dialog`s are indispensable. 

The original scenario is: We implemented a "dynamic" dialog factory -- `Vue.prototype.$dialog('Title', 'body')` would show a pre-configured dialog with the given title and body, freeing us from explicit `v-dialog` markups here and there. 

Internally, `$dynamic` function pushes a dialog configuration object (with the information like title, body etc) into a `vuex` managed array and there is a `dialog-container` component at the app root which loop-renders `v-dialogs` according to that array. This loop-rendering is what `v-if` in the demo is simulating -- `v-dialog` components would be mounted on-demand and destroyed when hidden. Visibility (i.e. `v-model` or `value` prop) of a `v-dialog` component cannot be true initially as we need the animation to happen. Instead, we set it to true in the `mounted` lifecycle.

As far as I understand, by probing into the code, `v-dialog` tries to keep one of its focusable descedent being focused as long as it is the top-most dialog. And the `Maximum call stack exceed` error happens when I try to push a new dialog from another dialog since somehow those two dialogs both believe themselves being the top-most and thus scramble for the focus.

I tired to delay (nextTick, setTimeout) the visibility toggling logic, which lies inside mounted lifecycle, and it does prevent the error from being thrown but results in a corrupted entering animation. This attempt can be examined by clicking the lower button in the repro demo. The animation is highly unstable: it sometimes looks like vibrating and sometimes fails to animate. If you see a "smooth" animation, please try a few times more.

Since the delay does elminate the error, I doubt that `getMaxZIndex` method in `stackable` mixin is misbehaving when there is a new dialog being inserted. Postponing the auto-focus logic might be a fix.

P.S. Both approaches [work nicely](https://codepen.io/anon/pen/qeRJXd) with `vuetify@2.0.2` (haven't tested my real project on 2.0.2 as a reliable regression test is required to guard the migration)

**Comment by Nandiin** [comment] 2019-07-29 13:08
The same in `vuetify@1.5.16` ([Repro link](https://codepen.io/anon/pen/rXjqyR))

**Comment by KaelWD** [comment] 2019-07-29 13:13
Duplicate of #6892

I thought we'd released the backport already but apparently not.

**Closed by KaelWD** 2019-07-29 13:13 UTC
Labels: triage

**Comment by Nandiin** [comment] 2019-07-30 02:18
@KaelWD, can you tell me how could I locally tweak this? I can't see any relavent difference in the `stackable` and `VDialog` between v1.5.14 and v2.0.2.
