### ISSUE TITLE
[Bug Report] The built-in translation of the data-picker component is not working

### ISSUE THREAD

**Issue by AGDholo** [vuetifyjs/vuetify#13450] opened 2021-04-20 02:45 UTC
### Environment
**Vuetify Version:** 2.4.10
**Vue Version:** 3.0.11
**Browsers:** Edge 89.0.774.77
**OS:** Windows 10

### Steps to reproduce
1. set locale="zh-hans"
2. select data
3. output text is "x selected", not "选择"

### Expected Behavior
Should be translated correctly.

### Actual Behavior
Show original text

### Reproduction Link
<a href="https://codepen.io/agdholo/pen/QWdZwjY?editors=101" target="_blank">https://codepen.io/agdholo/pen/QWdZwjY?editors=101</a>

**Comment by jacekkarczmarczyk** [comment] 2021-04-20 08:25
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9586

**Closed by jacekkarczmarczyk** 2021-04-20 08:25 UTC
Labels: triage
