### ISSUE TITLE
[Bug Report] Height v-menu when not displayed

### ISSUE THREAD

**Issue by jessielaf** [vuetifyjs/vuetify#8863] opened 2019-09-05 11:31 UTC
### Environment
**Vuetify Version:** 2.0.14
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Create v-menu with v-text-field as activator

### Expected Behavior
You don't see anything of the v-menu

### Actual Behavior
The v-menu adds a little of height

### Reproduction Link
<a href="https://codepen.io/Jessielaff/pen/MWgrWJz" target="_blank">https://codepen.io/Jessielaff/pen/MWgrWJz</a>

### Other comments
You can see the height when removing the element .v-menu.v-menu--inline

**Comment by jacekkarczmarczyk** [comment] 2019-09-05 12:37
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6951

**Closed by jacekkarczmarczyk** 2019-09-05 12:37 UTC
Labels: triage
