### ISSUE TITLE
[Feature Request] Timeout for the v-alert

### ISSUE THREAD

**Issue by varadekd** [vuetifyjs/vuetify#12358] opened 2020-10-06 04:15 UTC
### Problem to solve
Having a timeout attribute will ease of lot of work from the people using v-alert at multiple places. If this is to be done in one place it is okay, But if there are many places where the same thing is called it is hard to write this piece of code. 

### Proposed solution
Write now I am solving this by wrapping the alert component inside my own component which takes a timeout as a prop and according to that, I triggered the setTimeout function. It would be nice to have something similar to this.

**Comment by Dan-Correia** [comment] 2020-10-11 01:32
Although I don't agree with the decision, this is a duplicate of [#10344](https://github.com/vuetifyjs/vuetify/issues/10344).

**Closed** 2020-10-11 01:43 UTC
