### ISSUE TITLE
[Bug Report][3.4.2] VDatatable with multiple header rows creating an extra row after a certain size

### ISSUE THREAD

**Issue by emmet-opinionx** [vuetifyjs/vuetify#18712] opened 2023-11-17 13:49 UTC
### Environment
**Vuetify Version:** 3.4.2
**Vue Version:** 3.3.7
**Browsers:** Firefox 119.0
**OS:** Windows 10

### Steps to reproduce
Created a datatable with nested children, have more than 6 headers with children.

### Expected Behavior
The children should appear on the same row

### Actual Behavior
children wrap to and extra row

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9lU1ugzAQha8y8oYNP8UkTYtIpN6hu8DCgVGDSqiFTaQqyt1rMLS4C+JFyGrw88N+gz4x+wsRTR68ce6fWyQxSSSeeMUk7tIaIDl7BZPMk+xQYScAxEdkBTZim5LhKSXDTqne7fS+jmq38D7xW+k1O+FUFh7HxuPsA9XmWu/skmB6p0qRBJNIainypuQSBMqW9yHzr1pIGMLAFvb6hgvIUlYYg/PeVccFlUKtQgeu7ryFasu8KTJMusB/7yjnx7IqGqzjMZ15smgP5uGrv5A3nGtr5/PUmQ1Pv5/izg1srGO9WDtfH9lA+GSdK5wgdcs6oPWgHgZGbaz2xIUGcov3YGA7b7WHLjSoW7wHg9xZK7XHjtpjZ1qXbpcakM9b7Qml9oTSGUIz/cvWQ6OfQt3IUGoS6MmiZgq5uiTyI39DurryKcl+ALaRBWU=)

**Comment by KaelWD** [comment] 2023-11-18 16:21
Duplicate of #18679

**Closed by KaelWD** 2023-11-18 16:21 UTC
Labels: S: triage
