### ISSUE TITLE
[Bug Report][3.3.1] Memory Leak When Configuring Vuetify on Nuxt3 SSR App during High Traffic

### ISSUE THREAD

**Issue by smiura6** [vuetifyjs/vuetify#17473] opened 2023-05-27 10:25 UTC
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.4
**Browsers:** Google Chrome
**OS:** Windows
**Node Version:** 18.16.0
**Nuxt Version:** 3.5.1
**Nitro Version:** 2.4.1
**Package Manager:** npm@9.5.1
**Builder:** vite

### Steps to reproduce
1. Set up Vuetify on Nuxt3.
■plugins\vuetify.js
    ```
    import { createVuetify } from 'vuetify'
  
    const vuetify = createVuetify({
      ssr: true
    });

    export default defineNuxtPlugin(nuxtApp => {
      nuxtApp.vueApp.use(vuetify)
    });
    ```
    ■nuxt.config.ts
    ```
    export default defineNuxtConfig({
      css: ['vuetify/lib/styles/main.sass'],
      build: {
        transpile: ['vuetify'],
      },
      vite: {
        define: {
          'process.env.DEBUG': false,
        },
      }
    });
    ```
2. Building the application that was created by combining Nuxt3 SSR and Vuetify.  
3. Start the server in inspector mode.  
```node --inspect-brk=9229 .output\server\index.mjs```
4. Access the following in the browser.
```chrome://inspect```
5. Measure the memory usage after accessing the app once and after accessing it 10,000 times post-launch.

### Expected Behavior
Due to garbage collection, memory usage remains constant without accumulation.

### Actual Behavior
The memory usage increases as follows.

| Number of accesses | Memory usage |
| --- | ---|
| 1 | 15.7MB |
| 10,000 | 83.3MB |

■1 access
![image](https://github.com/vuetifyjs/vuetify/assets/29689514/1cffc2a5-3cfd-4f8f-af12-8ea1c3c858e9)

■10,000 accesses
![image](https://github.com/vuetifyjs/vuetify/assets/29689514/fbcc13f4-2c86-47a4-a514-b47a52cb6dce)

### Reproduction Link
[https://github.com/smiura6/nuxt3-vuetify-memory-test](https://github.com/smiura6/nuxt3-vuetify-memory-test)

**Comment by GaetanWi** [comment] 2023-07-07 13:57
Any follow up on this ? 
Same problem here, on our app, with memory leak as soon as we're loading Vuetify in our Nuxt app.

**Comment by Etsurosu** [comment] 2023-07-07 15:40
Same behavior here
Don't need high traffic, can reproduce with the nuxtjs template + vuetify basic setup

**Comment by KaelWD** [comment] 2023-07-10 14:40
Duplicate of #16156

Could've saved myself like an hour if I'd just started with that lol

**Closed by KaelWD** 2023-07-10 14:40 UTC
Labels: S: triage

**Comment by memic84** [comment] 2023-10-04 10:08
Running on latest version, and seeing probably the same memory issue in: https://github.com/vuetifyjs/vuetify/issues/18393
