### ISSUE TITLE
[Feature Request] Does v-select have the function of tree structure？

### ISSUE THREAD

**Issue by C-viya** [vuetifyjs/vuetify#12895] opened 2021-01-05 10:23 UTC
### Problem to solve
There are some sitation need to see the hierarchy of options.
Does v-select have the function of tree structure？I didn't find this when I read the documents and materials.
It seems that the assignment needs to be queried from ‘items’

### Proposed solution
Is it possible to assign an array of values directly to the v-select？(checkbox)
String assignment similar to input.(radio)
`<template>
  <v-select
    :value="valueTitle"
    :clearable="clearable"
    :label="label"
    :item-text="itemText"
    :item-value="itemValue"
    :chips="chips"
  >
    <template v-slot:prepend-item>
      <v-treeview
        :items="items"
        return-object
        activatable
        hoverable
        dense
        transition
        @update:active="active"
      >
      </v-treeview>
    </template>
  </v-select>
</template>`

**Comment by KaelWD** [comment] 2021-01-06 09:33
Duplicate of #3049

**Closed by KaelWD** 2021-01-06 09:33 UTC
Labels: triage
