### ISSUE TITLE
[Bug Report] Multiple sliders change to the same position

### ISSUE THREAD

**Issue by WuerfelDev** [vuetifyjs/vuetify#3621] opened 2018-03-19 22:32 UTC
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Firefox 59.0, Mozilla Firefox, Google Chrome
**OS:** Ubuntu undefined, Linux

### Steps to reproduce
slide one slider but move the mouse while holding down to the height of the other slider

### Expected Behavior
it should only slide the active slider, where i had the mousedown

### Actual Behavior
it slides both to the same x positioin

### Reproduction Link
[https://codepen.io/anon/pen/MVJJBE](https://codepen.io/anon/pen/MVJJBE)

**Comment by jacekkarczmarczyk** [comment] 2018-03-20 01:24
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3567

**Closed by jacekkarczmarczyk** 2018-03-20 01:24 UTC
