### ISSUE TITLE
[Feature Request] [v-data-table] Add index to item.<name> slot 

### ISSUE THREAD

**Issue by mahammad-sixberries** [vuetifyjs/vuetify#12495] opened 2020-10-23 13:46 UTC
### Problem to solve

```
item.name - Slot to customize a specific column
{
  item: any,
  header: DataTableHeader,
  value: any
}
```

not able to access index in item.name slot

### Proposed solution
 add index to item.name slot like item slot

**Comment by jacekkarczmarczyk** [comment] 2020-10-24 15:35
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10646

**Closed by jacekkarczmarczyk** 2020-10-24 15:35 UTC
