### ISSUE TITLE
[Feature Request] custom theme background palettes

### ISSUE THREAD

**Issue by npfoss** [vuetifyjs/vuetify#9620] opened 2019-11-07 21:24 UTC
### Problem to solve
The current dark theme is nice, but if you wanted to make it, say, discord's color palette, you'd have to manually change the style on everything from the app to nav bars to cards. This is a [common problem](https://stackoverflow.com/questions/50243769/vuetify-how-to-set-background-color).

### Proposed solution
It would be nice to be able to pass something to the theme like so:
```js
  theme: {
    themes: {
      dark: {
        background: {
          base: '#2f3136',
          lighten1: '#36393f',
        },
      },
    },
  },
```
and then the app background would be `background.base`, cards and nav bars would be `background.lighten1`, etc. Also nice because there would be fewer constants hard-coded into Vuetify.

**Comment by jaxn** [comment] 2019-11-08 00:37
I think it would be great if there were no hard coded colors outside of `colors.scss`. In our project, we use `$ui` so that we can use `$ui.lighten-1` for backgrounds or text or whatever else is needed.

**Comment by KaelWD** [comment] 2021-06-19 10:10
Duplicate of #9873

**Closed by KaelWD** 2021-06-19 10:10 UTC
Labels: duplicate
