### ISSUE TITLE
[Bug Report] Data Table : Rows per page values truncated on Firefox

### ISSUE THREAD

**Issue by sudoloic** [vuetifyjs/vuetify#6848] opened 2019-03-27 10:24 UTC
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.10
**Browsers:** Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Set `rows-per-page-items` attribute to `v-data-table` with enough values to have a scrollbar and with values of 3 digits or more. i.e. `:rows-per-page-items="[25,50,100,200,300,400]"`

### Expected Behavior
Values should be correctly displayed (no ellipsis)

### Actual Behavior
Values are truncated and suffixed with ellipsis

### Reproduction Link
<a href="https://codepen.io/anon/pen/ywWZXy" target="_blank">https://codepen.io/anon/pen/ywWZXy</a>

**Comment by nekosaur** [comment] 2019-03-27 11:32
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6362

**Closed by nekosaur** 2019-03-27 11:32 UTC
Labels: duplicate
