### ISSUE TITLE
[Bug Report][3.3.3] vAutocomplete performance issue with large amount of data

### ISSUE THREAD

**Issue by hd-luisaguilar** [vuetifyjs/vuetify#17556] opened 2023-06-07 16:37 UTC
### Environment
**Vuetify Version:** 3.3.3
**Last working version:** 2.6.15
**Vue Version:** 3.3.4
**Browsers:** Edge 114.0.1823.41
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click autocomplete
2. Select any item
3. Clear current selection

### Expected Behavior
You should be able to pick an item, clear the current selection and open again the list to pick another one

### Actual Behavior
When we have a large amount of data, it makes the vAutocomplete really slow and even makes the app to crash

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVOFO4zAMfhUrfzrE2nLc/eoNxD3ASfefIpS17hZIkypJywHau+Mk7Va2SQCCJP4+f3Zsp/fv7E/XZUOPrGArh20nucPbUgGshrTipg77eNLKcaHQQCN7MQEBMvplfxy5EujP3pTsx3XJZmCAee90pSkYOpxDAEPa6hol+Q1c9mhL9hkvBCXpZVFii8qdECqJ3PC1PNKVfB1U/4nqGbiC0f3Y26unTjiJxFW8xbOEkBoRRH0MD9wIrhxhuneSinXCMOh6o1K9fsLKzaF8XsE8lPBQYjofahzRsRmxV94Sm7XKZ12ko62M6Fxg4f9OGwc1NryXDt6jWs0dL2BxATe3sBht8Z62gPuk0TpZQrLmxi+NeHsLx57Wh+XEjr0qQPVS7o1Th0hlYu4uxs0Ld9W2mFKYBCiJvYU6qZXVEjOpN4skECiy2wqbRfbFRN1N6uO6xkYb/Kt75eaKZIQFTRwouIGr37Ss4Prqyu8uLz9FznOoDHIn1AZio2CLZjZRPjXnIVKa+VHZ6gISsj+KOk3gEtS+Gv7HDxThfnk8RRveCvlKeNycYfCNd6f/57C6Nmip2Mm4O+HsDttQxak/Wdfb7YKSPhR0Xk86rPL9FLElo7F+ttmT1Yq+GeH2JassPURqdHQs2da5zhZ5XtWKmPSgxWAyhS5XXZvT18aJ5vXuZ0a/eS2sm0wpPVObBTGv9FCqHQUUrZ/btOXdUdQIhMhjF+iz0dObLb5K4Y5ouaEBES2mtW5DLr9iLjNzhrZN1/TyLBoSKdlYzhDGJ/yNUF/dlkKcSOcUb0CTGlQ1DZ757o2O3Oa3OoJObja2esd2SxbcqPAhZfbwAW7I12s=)

**Comment by KaelWD** [comment] 2023-06-07 16:41
Duplicate of #16318

**Closed by KaelWD** 2023-06-07 16:41 UTC
Labels: S: triage

**Comment by gabaum10** [comment] 2023-06-07 16:43
@KaelWD we're seeing this in 3.3.3.  did you look at the sandbox that was provided?

**Comment by KaelWD** [comment] 2023-06-07 16:45
#16318 is still open

**Comment by gabaum10** [comment] 2023-06-07 16:46
Oh!  Sorry, I missed that myself 😅
