### ISSUE TITLE
[Bug Report] Inconsistent display of "clearable" icon in Firefox when using Font Awesome 

### ISSUE THREAD

**Issue by epicyclist** [vuetifyjs/vuetify#12143] opened 2020-08-28 21:36 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Firefox 80.0
**OS:** Mac OS 10.14

### Steps to reproduce
See the reproduction link.

### Expected Behavior
Icons will not change their styling, regardless of the library or browser in use.

### Actual Behavior
Icons change their styling.

### Notes

Different versions of Firefox can be found [here](https://ftp.mozilla.org/pub/firefox/releases/).

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-2-fontawesome-5-firefox-and-the-clearable-icon-gntxg" target="_blank">https://codesandbox.io/s/vuetify-2-fontawesome-5-firefox-and-the-clearable-icon-gntxg</a>

**Comment by KaelWD** [comment] 2020-08-30 12:53
Duplicate of #10623

**Closed by KaelWD** 2020-08-30 12:53 UTC
Labels: C: VIcon, T: bug
