### ISSUE TITLE
[Bug Report][3.5.6] Hydration mismatch occurs when using multiple layout elements in nuxt (Can work in some cases)

### ISSUE THREAD

**Issue by Nisekoi5** [vuetifyjs/vuetify#19271] opened 2024-02-25 03:44 UTC
### Environment
**Vuetify Version:** 3.5.6
**Vue Version:** 3.4.19
**Browsers:** Chrome 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
Visit the playground `page-1`, open the console and refresh the page. Two `Hydration style mismatch on` warnings appear.
You can prevent this by adjusting the order of elements, as `page-2` does.
Click `Page 2 - Normal work` to refresh the page, and no `Hydration style mismatch on` warning appears.

### Expected Behavior
No need to adjust the order of elements

### Actual Behavior
Only works in a specific order of elements (no pattern found)

### Reproduction Link
[https://stackblitz.com/edit/github-vwrj4w?file=pages%2Fpage-1.vue](https://stackblitz.com/edit/github-vwrj4w?file=pages%2Fpage-1.vue)

### Other comments
I've seen
https://github.com/vuetifyjs/vuetify/issues/19015  
https://github.com/vuetifyjs/vuetify/issues/19014
It seems that this problem has not been solved yet

**Comment by KaelWD** [comment] 2024-02-26 05:17
Duplicate of #19015

![Screenshot_20240226_161633](https://github.com/vuetifyjs/vuetify/assets/16421948/5cd8ad83-2ee9-48da-aeef-e6f3201fbe70)
![Screenshot_20240226_161659](https://github.com/vuetifyjs/vuetify/assets/16421948/e56b1f40-1371-4be5-b9d0-03b7d7a0637d)

**Closed by KaelWD** 2024-02-26 05:17 UTC
Labels: S: triage
