### ISSUE TITLE
[Bug Report][3.1.1] Can't type letters to search for items in VSelect

### ISSUE THREAD

**Issue by joergd** [vuetifyjs/vuetify#16413] opened 2023-01-11 07:31 UTC
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a VSelect with items. When the VSelect has focus, and you type a letter that is included in one of the items, it should highlight the first item .... but any 'search' input like that is ignored. I think a normal HTML select would allow you to search by typing in letters on the focused select control.

### Expected Behavior
Should highlight item

### Actual Behavior
Ignores search

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9Uc1O8zAQfJWVL7k0tvh+LlW+ik9I9AFA4tD04Cbb1uDYlu0EKtR3Zx2nVSmCRIpmZzaz6/Hqnf13jg89sjmrInZOy4iL2gBUQymdG+FYdFKZqaL6JKRnqQaEuEcIqLGJsLFvsLVNH0CaNgkG4sEhaIwRPRRViN6a3WJZiQkVUFKfChD2ttfTP9nCGlii9TslgXN+ni/cotp4kT9ndijzCrWpY3oBtNyg/lezh8yz1Jq1uaLjBpJWxZ3Uamu9UbKYQXFntfWytQnfE1TtSE9bJPiIbzIk8HSwnTK7Yp2Ms+2iEqctTtkRcQ4vFTnWSlzETWVovHKRMox9ljNBkM2Y6pz1kWwcfw7W0GW9jyeZhFCzOYxM4ug2U12zfYwuzIXojXvZ8cZ24pY04XsTVYdla7vb3/wX//NXtCrES55j6MqNt68BPU2s2ezCPKrt4bsBk0y+N/wm205UsvxiJch/QF96NC169D/ufdX7afcr7cv+aeaxNkfKUivzEq5ibMIY4WqdWo4zlq2peTwHW38AlBAJrg==)

**Comment by johnleider** [comment] 2023-01-22 23:19
This functionality that wasn't ported over.

**Comment by 1Luc1** [comment] 2023-04-27 18:46
Just tested with the latest version and seems to be fixed.

**Comment by KaelWD** [comment] 2023-04-28 08:12
Duplicate of #16055

**Closed by KaelWD** 2023-04-28 08:12 UTC
Labels: T: bug, C: VSelect
