### ISSUE TITLE
[Documentation] Not search working 

### ISSUE THREAD

**Issue by tejas-ezee** [vuetifyjs/vuetify#10993] opened 2020-04-01 13:29 UTC
### Environment

**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
search any content not provide results. 

### Expected Behavior
search 

### Actual Behavior
search 

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/quick-start/" target="_blank">https://vuetifyjs.com/en/getting-started/quick-start/</a>

### Other comments
search

**Comment by jacekkarczmarczyk** [comment] 2020-04-01 13:32
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10991

**Closed by jacekkarczmarczyk** 2020-04-01 13:32 UTC
Labels: triage
