### ISSUE TITLE
[Bug Report] Avatar in VMenu in VToolbar will disappear while resize the screen

### ISSUE THREAD

**Issue by vip30** [vuetifyjs/vuetify#2609] opened 2017-11-22 12:14 UTC
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.8
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 10

### Steps to reproduce
1. Resize the screen by enlarge and shrink
1. The avatar disappeared

### Expected Behavior
The avatar should exist on the same place

### Actual Behavior
The avatar disappeared

### Reproduction Link
[https://codepen.io/anon/pen/NwMWOP?editors=1000](https://codepen.io/anon/pen/NwMWOP?editors=1000)

### Other comments
The issue exists after upgrade to 2.5.4

**Comment by jacekkarczmarczyk** [comment] 2017-11-22 12:19
Duplicate of #2550

**Closed by jacekkarczmarczyk** 2017-11-22 12:19 UTC
