### ISSUE TITLE
[Bug Report] autoSelectFirst doesn't work with VCombobox 

### ISSUE THREAD

**Issue by tafel** [vuetifyjs/vuetify#7687] opened 2019-06-27 10:38 UTC
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chromium 75.0.3770.90
**OS:** Ubuntu undefined

### Steps to reproduce
With [auto-select-first] prop, type a text in combobox and hit [Enter] or [Tab], then type a text in autocomplete and hit [Enter] or [Tab].

### Expected Behavior
First item must be selected in the field, for the combobox and for the autocomplete field. Their v-model values must be the [value] field of their selected item.

### Actual Behavior
The first item is not selected for the combobox. Plus, its v-model equals the content of the combo search field.

### Reproduction Link
<a href="https://codepen.io/anon/pen/BgmzeB" target="_blank">https://codepen.io/anon/pen/BgmzeB</a>

### Other comments
The documentation doesn't specify that [auto-select-first] is disabled for v-combobox. And anyway, it would be great to have these two working together. 

I understand that combobox should create new entries. But if [auto-select-first] is true, I think it's correct to expect that [Enter] or [Tab] select first existing entry instead of creating  a new one.

**Comment by johnleider** [comment] 2019-07-01 17:02
This still persists in v2.0. Moving to post release bug fix.

**Comment by johnleider** [comment] 2019-07-02 14:44
Duplicate of #6607

**Closed by johnleider** 2019-07-02 14:44 UTC
Labels: T: bug
