### ISSUE TITLE
Date Picker displays 1 day ahead

### ISSUE THREAD

**Issue by janhox** [vuetifyjs/vuetify#2224] opened 2017-10-18 06:45 UTC
After upgrading to 0.16.7 my date picker components all display a date that is 1 day ahead of the actual selected date on the picker except for the last day of the month.
The same behaviour can be seen on the Vuetify Picker Component page, eg. #5.
See examples below.
How to correct this ?
Thanks.

<img width="650" alt="screen shot 2017-10-18 at 08 44 29" src="https://user-images.githubusercontent.com/24571106/31704237-b71fef16-b3e0-11e7-9083-6d5aa4fc4a91.png">

<img width="485" alt="screen shot 2017-10-18 at 08 44 14" src="https://user-images.githubusercontent.com/24571106/31704241-bc11e6b4-b3e0-11e7-9cde-4d4e17bd84a3.png">

**Comment by jacekkarczmarczyk** [comment] 2017-10-18 06:54
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2022

**Closed by jacekkarczmarczyk** 2017-10-18 06:54 UTC

**Comment by janhox** [comment] 2017-10-18 07:11
Thanks. Adding :date-format="date => new Date(date).toISOString().substr(0, 10)" :formatted-value.sync="datePickerSelectFormat" works for me.
