### ISSUE TITLE
[Feature Request] data-table headers add unit key

### ISSUE THREAD

**Issue by augnustin** [vuetifyjs/vuetify#14808] opened 2022-03-09 11:55 UTC
### Problem to solve
`<data-table />` are super powerful, this is amazing!

My data has units, so I display them in the header. Eg. `Coverage (%)`

But, it would make sense to repeat it in the columns. Especially when the unit is `%`, reading:
```
Coverage
-------
36%
25%
```
is much clearer than reading:
```
Coverage (%)
-------
36
25
```
I could add the unit in the value string, but then it would not be sortable out-of-the-box. I could create custom templates for those, but this makes things much more complicated.

### Proposed solution
Simply add a `unit: String` key in the `:headers` specification, that would be visible in the table but wouldn't affect sorting.

Eventually a `unitPosition: 'before' | 'after'` may be necessary.

Or another solution would be that `:items` values accept an object: `{value: 36, text: '36%'}`, this would be more general, but less simple to use.

**Comment by KaelWD** [comment] 2022-03-09 13:02
Effectively a duplicate of #7066. I don't think just `unit` would ever be added, if this ever happens it makes more sense to do it in a way that allows for generic formatting.

**Closed by KaelWD** 2022-03-09 13:02 UTC
Labels: S: triage
