### ISSUE TITLE
[Bug] Inputs does not validate/show error until blurred

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#2396] opened 2017-11-01 10:15 UTC
### Versions and Environment
Vuetify: v0.16.9
Vue: v2.5.2
Browsers: Chrome
OS: Windows

### Steps to reproduce
Create a text field with validation rules which initially evaluates to "true" (valid). Then e.g. click a button which makes the validation fail.

### Expected Behavior
The input (text field) should transition to the error state and show error message immediately.

### Actual Behavior
The state of the input does not change until you blur the text field.

### Reproduction Link
https://codepen.io/anon/pen/yPYyEg

### Other comments
It seems that the `validate-on-blur` prop does not work.

**Comment by jacekkarczmarczyk** [comment] 2017-11-01 10:45
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2342

**Closed by jacekkarczmarczyk** 2017-11-01 10:45 UTC

**Comment by sindrepm** [comment] 2017-11-01 14:10
@jacekkarczmarczyk it is probably related, but #2342 applies only to 0.17.0-beta.1 but works on 0.16.9. The issue I describe is different as it is present also in 0.16.9, which is why I did not think it was a duplicate.

**Comment by KaelWD** [comment] 2017-11-01 14:34
Just had a looks at your codepen, that is never something that would work and it isn't intended to. You have to use the `error-messages` prop to set a custom error message in real-time.
