### ISSUE TITLE
[Bug Report][3.3.4] Text overflow on v-combobox

### ISSUE THREAD

**Issue by CarnivalBen** [vuetifyjs/vuetify#17596] opened 2023-06-13 22:11 UTC
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Firefox 114.0
**OS:** Windows 10

### Steps to reproduce
Create fixed width `v-combobox`.
Fill with text long enough to overflow.
Text overflows outside of the box.

### Expected Behavior
No text overlow, same as `v-text-field`

### Actual Behavior
Text overflows.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFk81O4zAQx1/F8oVLHWuX3T1UBbHvwI1wcOIpMfhL9iQNQn13xgmFqAgBAgkpUuz5+s3fHl898P8xVkMPfM03CC5ahXBee8Y2g2iDa0ITxrJlbBAuaLBnNcex5rPNqmayXHYmM/oUe855iuiMBqEBlbGZAlWP4eAaVDLKI1lDj9Z40AePihG8FsZ7SMK0wVOM00bcJPMc01qVS8Wd+P2XORS//s2e84186ZyUfIMWtjPYsTBA2tqwE6MgURr8D0h8q4k3RCOMKLYGrP6M7EXWj17iSx+kaCMX00nb3CYTkWXAPk7zSoCMDEd2Npc+UU2rYXvTGXt3+5X1SYHPOALxFSeVd7m6zcHTo3kotJq3Odd8za5mds07xJjXUrbaUySduRlS5QGlj07Sc0Ozvb84rU6rP1KbjAeToNvI1VSsVLqu/Z6AxsWQUDgVj6izYyJPlmKjSmX/TgsXFCZT79E4utnglr0szBVkJ5oUdhkSFan5aoEpDX8A9Z5aQrwqLYlHky4STRAkSB9VdJS2ZB65Xikr9H057/2KT2l08PP/+hGuXLwO)

### Other comments
`<v-combobox />`, `<v-combobox class='overflow-x-hidden' />`, and <`v-text-field` /> are shown in the repro for comparison.

Additionally, if `overflow-x-hidden` is set, then it no longer overflows but it does overlap the `append-inner-icon`. On a side note, this also seems to affect the label on a `variant='outlined'` by cropping off the top.

**Comment by CarnivalBen** [comment] 2023-06-13 22:12
![image](https://github.com/vuetifyjs/vuetify/assets/3448911/6c38a1df-b4f0-4abf-a019-e4913b2a360e)

**Comment by MetRonnie** [comment] 2023-08-22 11:57
It looks like
```css
.v-combobox__selection {
  overflow-x: hidden;
}
```

is the best workaround

![image](https://github.com/vuetifyjs/vuetify/assets/61982285/a1c6209e-0ec9-4641-8bb1-d79f0dafe749)


[Playground link](https://play.vuetifyjs.com/#eNqlUttO4zAQ/RXLL7zUsXbZ3YduQew/7BtGyImn1OCb7ElahPrvTOIUovIAElKk2HM5Z84c377wfyk1Qw98zTcIPjmNcK0CY5tBdNG3sY2H8crYIHw04K4Ux4PiNeZ0O0X+72xh9Gn21jNX7KwBYQC1dYUKdY/xlBp0tjogRWOPzgYwp4xOCYIRNgTIwnYxUI03Vjxk+1bTOV1GxL34+Zt5FD/+1Mz1Rr5PTko2ciGLrqXLNiErgH2ahBJ8QYYHdlWBL3TbGdg+7Kx7evzO+WIkr3QzNT67utzmfcT7+wIOOrQxsJc6QRwgb13ci8N63J+B8HdMHCe8GYOvOK3sqTSPJQYyb2pVvCtF8TW7rUCK7xBTWUvZmUCVZJ8dchMAZUheku1ot883l81l80saW/AUEmRsaSawEelOhSMRWp9iRuF1OmOtiYl5lqA4IY33T0a4oTKZ+4DW0zOJfjnLItxA8aLNcV8gE4jiqwXNOPAXqD5TSxQfoCXxkRki03OEDPmris7alpxnqQ/KZqeP/LjiUxstvv7vXgFtbkI0)

**Comment by KaelWD** [comment] 2023-09-11 09:36
Duplicate of #17348

**Closed by KaelWD** 2023-09-11 09:36 UTC
Labels: S: triage
