### ISSUE TITLE
V-list-tile with v-model - active state not working

### ISSUE THREAD

**Issue by ianrothmann** [vuetifyjs/vuetify#1383] opened 2017-08-17 17:16 UTC
### Steps to reproduce
Create a v-list with v-list-tiles. Set v-model on a list tile to a true boolean variable.
### Versions

0.14.11
### What is expected ?

According to the docs, v-model toggles the list tile active state. You should see the active state.
### What is actually happening ?

Not seeing the active state.
### Reproduction Link

https://codepen.io/anon/pen/prpqrM?editors=1010#0

**Comment by nekosaur** [comment] 2017-08-17 17:43
Duplicate of #1374

**Closed by nekosaur** 2017-08-17 17:43 UTC

**Comment by cypherix93** [comment] 2017-08-25 23:55
I don't think this is a duplicate. In this scenario, the class `list__tile--active` does not even get applied on the `v-list-tile`. This issue is unrelated to vue-router. Please advise.

Screenshot from OP's repro link:

![screenshot_62](https://user-images.githubusercontent.com/6885927/29736427-f37ea678-89ce-11e7-93d5-94eec6e1ec69.png)

**Comment by nekosaur** [comment] 2017-08-26 06:34
I can confirm that this is fixed in current dev.

**Comment by SmellydogCoding** [comment] 2018-01-23 19:12
I can confirm that this is either not fixed or I'm experiencing something different.
Code:
`<router-link to="/s2p1" tag="v-list-tile" active-class="active">`
`<v-list-tile-content>`
`<v-list-tile-title> 2.1 - Area of a Swimming Pool</v-list-tile-title>`
`<\v-list-tile-content>`
`<\router-link>`
Result:
![image](https://user-images.githubusercontent.com/20384042/35295556-64dfed56-0047-11e8-9a68-50ab4b49c787.png)
