### ISSUE TITLE
[Bug Report] v-icon tooltips not displayed on Firefox

### ISSUE THREAD

**Issue by oliviergaucher** [vuetifyjs/vuetify#3063] opened 2018-01-22 00:38 UTC
### Versions and Environment
**Vuetify:** 1.0.0-beta.4
**Vue:** 2.5.13
**Browsers:** Mozilla Firefox 56.0
**OS:** Mac OS 10.12.6

### Steps to reproduce
Use v-tooltip component on toggle button (v-btn-toggle > v-btn > v-tooltip > v-icon).
The tooltip appears fine on Chrome but not Firefox

### Expected Behavior
Expect tooltip to show on mouse-over on the icon on any browser.

### Actual Behavior
No tooltip is displayed on mouse-over on the icon on Firefox.

### Reproduction Link
[https://codepen.io/ogaucher/pen/EorLQN](https://codepen.io/ogaucher/pen/EorLQN)

**Comment by nekosaur** [comment] 2018-07-07 09:10
Still an issue on 1.1.1 https://codepen.io/anon/pen/ZRgObR

**Comment by jacekkarczmarczyk** [comment] 2018-07-07 09:17
And in IE11

**Comment by dima74** [comment] 2018-11-09 13:35
Related bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1084196 (which probably is duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1089326, which is likely to be fixed soon). Anyway, you can vote for both bugs!

**Comment by KaelWD** [comment] 2019-02-03 15:14
Solution is to put the tooltip on the button instead, which makes more sense anyway. You can use the new scoped slot in 1.4 to avoid messing up the styles: https://codepen.io/anon/pen/PVjqYN

**Closed by KaelWD** 2019-02-03 15:14 UTC
Labels: T: bug, platform specific
