### ISSUE TITLE
[Feature Request] Create light or dark mode agnostic classes

### ISSUE THREAD

**Issue by victornpb** [vuetifyjs/vuetify#6205] opened 2019-01-19 13:00 UTC
### Problem to solve
Currently if you want to change the default colors of an element you do by adding material color classes with modifiers. But by doing this you loose the seamless transition from light to dark mode, you have to manually manage those cases.

Even worse lets say you're on default light mode, and you want a slightly darker shade of white for a background:

If you just add `darken-2` it doesn't do anything, so you have to add `white darken-2`.
But thats permanently makes the background light even when you switch to dark mode.

So you have to 
`:class="['grey', $vuetify.dark ? 'lighten-2' : 'darken-2']"`

### Proposed solution
Make a generic `background` and `foreground` classes that would be "dark" or "light" depending on the mode you're in.

Add a `.bg` and `.fg` classes as well as expose `--bg` and `--fg`  so one could use those in css variables

### Problem to solve (2)
The lighten and darken modifiers doesn't make much sense when you talk about `background` and `foreground` because when you are on dark mode it doesn't make sense to darken black, or lighten white.

### Proposed solution (2)

So my final proposal would be something like this

| class | Light           | Dark            |
|-------|-----------------|-----------------|
| bg    | white           | black           |
| bg-1  | white darken-1  | black lighten-1 |
| bg-2  | white darken-2  | black lighten-2 |
| fg    | black           | white           |
| fg-1  | black lighten-1 | white darken-1  |
| fg-2  | black lighten-2 | white darken-2  |

This would make possible to make light and dark components that transition seamless between modes and still looks nice on both.
![image](https://user-images.githubusercontent.com/3372598/51427139-edec0800-1bda-11e9-8a85-7ba264f2af92.png)

![image](https://user-images.githubusercontent.com/3372598/51427097-9d74aa80-1bda-11e9-801a-44a77f98fc98.png)

Continuing on that thought I think we also should have like the option to set what `primary` and `primary--text` will look like on dark and light mode
![image](https://user-images.githubusercontent.com/3372598/51427200-29d39d00-1bdc-11e9-975d-c8a0703b8af9.png)

Because sometimes it doesn't look good for every color

**Comment by victornpb** [comment] 2019-01-19 18:59
This idea could extend to the generated colors of the theme

So `primary` would be something like

```scss
.light .primary-1{
     @mixin .primary
     @mixin .darken-1
} 

.dark .primary-1{
     @mixin .primary
     @mixin .lighten-1
}
```

**Comment by KaelWD** [comment] 2019-01-20 04:18
Somewhat duplicate of #1599, we are already planning to revisit the theme system for 2.0 so this doesn't need to be tracked separately.

**Closed by KaelWD** 2019-01-20 04:18 UTC
Labels: T: enhancement, T: feature, duplicate
