### ISSUE TITLE
When using fullscreen dialog, there is a problem with the scrollbar of the page.

### ISSUE THREAD

**Issue by QQ34205037** [vuetifyjs/vuetify#5990] opened 2018-12-27 16:21 UTC
First of all, I'm sorry for my terrible English.
In vuetify, when I open a fullscreen dialog, the scroll bar of the page is temporarily hidden, and if I open another dialog in this fullscreen dialog and then I close it, the scroll bar is redisplayed, but it should actually be displayed after the fullscreen dialog is closed.

- Versions and Environment

Vuetify: 1.3.15
Vue: 2.5.16
Browsers: Chrome 71.0.3578.98
OS: macOS Mojave 10.14.2

- Steps to reproduce

see https://vuetifyjs.com/en/components/dialogs

**Comment by KaelWD** [comment] 2018-12-27 16:21
Duplicate of #5356

**Closed by KaelWD** 2018-12-27 16:21 UTC
