### ISSUE TITLE
[Bug Report] v-text-field label bug when used with prepend-inner-icon in activator slot

### ISSUE THREAD

**Issue by Excalibaard** [vuetifyjs/vuetify#9900] opened 2019-12-06 08:56 UTC
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Ubuntu undefined

### Steps to reproduce
Use a v-text-field inside the activator slot of a v-menu, and apply a prepend-inner-icon to the text-field.

### Expected Behavior
The field label of the text-field transform/translates into the correct position, above the prepend-inner-icon, as per example 2.

### Actual Behavior
The field label transform/translates into the position as if prepend-icon is used, as per example 3. Since prepend-inner-icon has the border gap in a different position, the label overlaps and becomes illegible, as per example 1.

### Reproduction Link
<a href="https://codepen.io/Excalibaard/pen/KKwdPMy" target="_blank">https://codepen.io/Excalibaard/pen/KKwdPMy</a>

**Comment by jacekkarczmarczyk** [comment] 2019-12-10 11:57
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9801

**Closed by jacekkarczmarczyk** 2019-12-10 11:57 UTC
Labels: triage
