### ISSUE TITLE
[Bug Report][3.6.7] 'lazy' v-model modifier not working in vuetify

### ISSUE THREAD

**Issue by laventnc** [vuetifyjs/vuetify#19875] opened 2024-05-23 17:58 UTC
### Environment
**Vuetify Version:** 3.6.7
**Vue Version:** 3.4.27
**Browsers:** Chrome 124.0.0.0
**OS:** Windows 10

### Steps to reproduce
Type in the vuetify text-field, and notice the `.lazy` modifier doesn't apply.
Type in the pure html input, vue's `.lazy` modifier works fine

### Expected Behavior
vuetify components shouldn't break vue functionality

### Actual Behavior
vuetify fields don't work with `.lazy` modifier

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUktu2zAQvcpAG7eARTVOVoYSpDfoougmyoKSxjZr/sCPEtfQ3TuU5Fh13ADZCBrO8P2GT8fMu6b4bi3rImbrrAyorOQBHyoNUHY5t3b4HQrFhZ6qoQ74GvKNQNkCNU2Lkkn+53BfZcpvqwyK83ArurcC4OfBIggNYYeQQGAE4bXpcAlcE57AF+i4jAjNjuvtMO6QSwhC4foMVdYPxyPR9X1Z1Ge+YiSciaUD0aKDRnLvk8RDfjdpfJsS2sZwxcuKBn04SKSyNo5g1nBjX8EbKVqoJW/2H9n9EV3ST9hLiF7oLVDajDHQJkz2Wog6CElYkbBPplbXXY3/s32kYtxUWcw2SKVvnLABPIY4LlIoa1yAI4W5gR42zihYkJzFGENjtA9A1HCfJr4sfkUMYnNYfP2nu5q1U6ssRiKiyJbZyEHyLPvtjaZ3dUy3q6nhq2wNw0k6I+5UV9kuBOvXRRG13W9ZY1TxSL3CpWAU5q1Rj7fsln3LubQ7zu4oDB/mbYZe5bUzLx4dEVfZcsaRTPyPZ2oT/M0JdjpKkO+gCsLv0OUONb0EdB/Kv5i9ZuFi5J2NRN1XuqdkpdB7fxFq44dAn04KP+VPCc0GgHT7OZH0Sx2lHD7PfwG8ZFoU)

### Other comments
This has been [brought up before](https://github.com/vuetifyjs/vuetify/issues/16637), although the issue was closed as 'not planned' for some reason with no response from the developers.

**Comment by KaelWD** [comment] 2024-05-24 02:51
Duplicate of #5759

This isn't "breaking vue functionality", modifiers are only defined for built-in elements.

**Closed by KaelWD** 2024-05-24 02:51 UTC
Labels: S: triage

**Comment by laventnc** [comment] 2024-06-27 21:46
@MajesticPotatoe fair enough but the linked feature request is one of a few duplicates, with the source being over 6 years old for old versions of vuetify.

I'm still confused how this isn't consider a breaking:
> This isn't "breaking vue functionality", modifiers are only defined for built-in elements.

I may be splitting hairs here, but according to the [vue documentation](https://vuejs.org/guide/essentials/forms.html#lazy), lazy works by instead listening to the `change` event.. which vuetify inputs no longer seem to emit.

I'm curious why it isn't as simple as just adding the 'change' event, as I believe this was in vuetify 2

**Comment by MajesticPotatoe** [comment] 2024-06-27 22:22
@laventnc The linked FR is still open and valid. If it was to be worked on it would implemented in the current version (v3).
