### ISSUE TITLE
Select component comes in from top left in Safari browsers

### ISSUE THREAD

**Issue by brouwno** [vuetifyjs/vuetify#1003] opened 2017-07-16 09:01 UTC
Description
When using the Select component in a Safari browser (mac or iPhone/iPad), the select menu comes flying in from the top left of the screen to the select component.
When opening the Select again, the menu opens directly at the Select component.
When using another browser it works fine.

How to reproduce
In a Safari browser, go to https://vuetifyjs.com/components/selects and open a Select. You will see the select menu coming in from the top left

What is expected?
The menu opening directly at the Select component

**Comment by johnleider** [comment] 2017-07-16 14:56
Duplicate of #828

**Closed by johnleider** 2017-07-16 14:56 UTC
