### ISSUE TITLE
[Bug Report] Autocomplete. Bad mobile UX

### ISSUE THREAD

**Issue by lloydbanks** [vuetifyjs/vuetify#9131] opened 2019-09-27 14:53 UTC
### Environment
**Vuetify Version:** 2.1.0-beta.1
**Vue Version:** 2.6.10
**Browsers:** Chrome
**OS:** Android

### Steps to reproduce
To understand the issue, please look at screenshot https://i.ibb.co/BqLBB9c/Screenshot-20190927-170004.png

1. Open on mobile https://vuetifyjs.com/en/components/autocompletes#playground
2. Click on input and choose any state to close the dropdown
3. Click on input again

### Expected Behavior
Ability to see what you're typing
No need in auto selection

### Actual Behavior
Search input is not visible. You can see only dropdown list
Unwanted auto selection causes pop-up menu (cut/copy/etc..)

### Reproduction Link
<a href="https://jsfiddle.net/lloydbanks/rbzsunoj/" target="_blank">https://jsfiddle.net/lloydbanks/rbzsunoj/</a>

**Comment by yooneskh** [comment] 2019-10-01 21:11
Your jsfiddle is only an image, it would have been better if it was a full sample. i think you can use the offset-y prop so the menu does not overlap the select field.

**Comment by johnleider** [comment] 2019-10-15 16:01
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by lloydbanks** [comment] 2019-10-15 17:06
Well, the actual reproduction link could be found in the "steps to reproduce" section. It leads to your official docs website.

But I've also updated my [JSFiddle](https://jsfiddle.net/lloydbanks/rbzsunoj/) sample.

If you have any additional questions, please let me know.
Thank you.

**Comment by KaelWD** [comment] 2019-11-07 13:04
Duplicate of #4059

**Closed by KaelWD** 2019-11-07 13:04 UTC
Labels: S: needs reproduction, triage
