### ISSUE TITLE
[Bug Report] VCard inside VCarousel applied dark theme 

### ISSUE THREAD

**Issue by aldarund** [vuetifyjs/vuetify#10015] opened 2019-12-19 18:14 UTC
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.79
**OS:** Windows 10

### Steps to reproduce
-

### Expected Behavior
vcard is light theme

### Actual Behavior
vcard is dark theme

### Reproduction Link
<a href="https://codepen.io/aldarund/pen/YzPZGxm?&editable=true&editors=101" target="_blank">https://codepen.io/aldarund/pen/YzPZGxm?&editable=true&editors=101</a>

### Other comments
Even if :dark=false it still applies dark theme, and by default it also applies dark instead of light

**Comment by johnleider** [comment] 2020-01-10 17:19
The way carousel handles dark is wrong. While it supposed to be the default, it should be done through setting the default value of **dark** to true.

**Comment by bad4iz** [comment] 2020-02-10 05:17
Duplicate of #8392

**Closed by bad4iz** 2020-02-10 05:17 UTC
Labels: C: VCarousel, T: bug, duplicate

**Comment by PriimeTime** [comment] 2020-02-24 14:09
Would be really good if this was finally fixed, just saying.

**Comment by sugoidesune** [comment] 2020-06-03 18:02
Yes please. This cost me an hour of looking for the error on my side haha
