### ISSUE TITLE
[Bug Report] Duplicated groups in `v-data-table` when used with Nuxt.js

### ISSUE THREAD

**Issue by lennoximus** [vuetifyjs/vuetify#12105] opened 2020-08-24 14:13 UTC
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.10
**Browsers:** Chrome 84.0.4147.135
**OS:** Windows 7

### Steps to reproduce
1. Visit the provided sandbox.
2. Look at the grouping in the second table.

### Expected Behavior
Elements should be grouped as follows:
```
First group
1, 2, 3, 5
Second group
4
Third group
6
```

### Actual Behavior
Elements are grouped as:
```
First group
1, 2, 3
Second group
4
Again, the first group
5
Third group
6
```

### Reproduction Link
<a href="https://codesandbox.io/s/sleepy-diffie-xtn81" target="_blank">https://codesandbox.io/s/sleepy-diffie-xtn81</a>

### Other comments
Problem appears if `server-items-length` is specified. Not sure, if that's the case, though.

**Comment by nekosaur** [comment] 2020-08-25 12:37
Duplicate of https://github.com/vuetifyjs/vuetify/issues/11349

**Closed by nekosaur** 2020-08-25 12:37 UTC
Labels: C: VData, C: VDataTable, duplicate
