### ISSUE TITLE
[Bug Report] Closing v-dialog too quickly does not remove the overlay

### ISSUE THREAD

**Issue by Macoshark** [vuetifyjs/vuetify#9943] opened 2019-12-11 09:16 UTC
### Environment
**Vuetify Version:** 2.1.14
**Vue Version:** 2.6.10
**Browsers:** Firefox 71.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. Create a layout that has a v-dialog with the "persistent" attribute
2. Show the dialog
3. Close the dialog before it has had time to animate fully

### Expected Behavior
The underlying UI is usable, the dialog is not visible

### Actual Behavior
The overlay behind the dialog remains visible and it blocks the use of the underlying UI

### Reproduction Link
<a href="https://codepen.io/leethaksor/pen/BayKxrG" target="_blank">https://codepen.io/leethaksor/pen/BayKxrG</a>

### Other comments
I'm using the v-dialog to show a "Loading..." indicator when my app is loading data from the server. Sometimes the server responds "too quickly" and the dialog is closed before it has had time to fully open and it goes into an invalid state.

**Comment by jacekkarczmarczyk** [comment] 2020-01-11 12:19
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9588

**Closed by jacekkarczmarczyk** 2020-01-11 12:19 UTC
Labels: triage
