### ISSUE TITLE
[Bug Report][2.2.20] autocomplete search-input clears when highlight with cursor

### ISSUE THREAD

**Issue by salalaslam** [vuetifyjs/vuetify#11053] opened 2020-04-08 06:54 UTC
### Environment
**Vuetify Version**: 2.2.20
**Vue Version**: 2.6.11
**Browsers**: Chrome 80.0.3987.149
**OS**: Mac OS 10.15.3

### Steps to reproduce
•Type anything in an autocomplete search-input.
•now highlight text using mouse/trackpad/cursor from right side, like you do to edit and drag the cursor a bit outside the autocomplete's edge.
•the text is gone. you have to re-focus the search-input to type something

### Expected Behavior
text should not clear when selecting like this.

### Actual Behavior
text clears

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-4t6h3" target="_blank">https://codesandbox.io/s/vue-template-4t6h3</a>

**Comment by salalaslam** [comment] 2020-04-08 06:55
![Kapture 2020-04-08 at 2 58 03](https://user-images.githubusercontent.com/2707973/78753760-d475de00-798f-11ea-8e00-9b7b5a5ee4b9.gif)

**Comment by KaelWD** [comment] 2020-04-08 07:08
Related to #5018
Duplicate of #9920

click-outside needs to make sure mousedown wasn't on the element.

**Comment by salalaslam** [comment] 2020-04-08 07:15
The click (mousedown) starts on the element, and ends (mouseup) outside the element, as shown in the attached gif.

**Comment by KaelWD** [comment] 2020-04-08 07:19
I know, click-outside is only looking at the mouseup.

**Comment by Landen13** [comment] 2020-09-11 17:14
Firefox works fine. Reproduced in Chrome.

**Comment by KaelWD** [comment] 2021-08-04 15:02
Duplicate of #5886

**Closed by KaelWD** 2021-08-04 15:02 UTC
Labels: C: VTextField, T: bug, Vuetify 3 - Phase 3
