### ISSUE TITLE
[Feature Request] Density scaling option

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#11519] opened 2020-05-28 22:13 UTC
### Problem to solve
The md2 spec for [applying density](https://material.io/design/layout/applying-density.html#components) mentions a multi-level approach rather than one that is on-off. Would it be possible in v3 to enable this kind of option at both the component and global (app) level?

One option (though a breaking change) would be to remove the `dense` prop and replace it with a `density` prop that accepts number or string values. Another option would be to retain the `dense` prop (boolean) but add a `density-level` prop (number/string) to go with it. The `dense` prop would still be boolean, but would have some default value applied if the `density-level` prop was missing.

Thanks for considering!

### Proposed solution
Multi-level density capability as described in the md2 spec.

![image](https://user-images.githubusercontent.com/1835454/83198572-10622f80-a105-11ea-9c75-a3319b21b393.png)

**Comment by jacekkarczmarczyk** [comment] 2020-06-11 10:53
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3220

**Closed by jacekkarczmarczyk** 2020-06-11 10:53 UTC
Labels: triage
