### ISSUE TITLE
[Feature Request] Multiple Snakbar without npm or Vuex

### ISSUE THREAD

**Issue by rotnet** [vuetifyjs/vuetify#15792] opened 2022-09-17 19:19 UTC
### Problem to solve
Cannot show multiple snackbars without overwriting

### Proposed solution
Create a prop that connects the snackbar queuing, like all the snacks and toast that exist in others frameworks

**Comment by KaelWD** [comment] 2022-09-17 19:20
Duplicate of #2384

**Closed by KaelWD** 2022-09-17 19:20 UTC
Labels: S: triage
