### ISSUE TITLE
[Bug Report] Text field `autofocus` does not work (sometimes only the first open)

### ISSUE THREAD

**Issue by francoishill** [vuetifyjs/vuetify#9883] opened 2019-12-05 03:23 UTC
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
Add `a v-text-field` with a `autocomplete` prop inside a `v-dialog`
Open the dialog (field might focus the first time)
Close the dialog
Open the dialog again (the field does not focus)

### Expected Behavior
The text field should focus

### Actual Behavior
The text field does not focus

### Reproduction Link
<a href="https://codepen.io/francoishill/pen/ExajyZy?editors=1111" target="_blank">https://codepen.io/francoishill/pen/ExajyZy?editors=1111</a>

**Comment by francoishill** [comment] 2019-12-05 03:24
Text Fields with autofocus don't consistently work in dialog #1731

**Comment by KaelWD** [comment] 2019-12-05 03:24
Duplicate of #8845

**Closed by KaelWD** 2019-12-05 03:24 UTC
Labels: triage
