### ISSUE TITLE
[Bug Report] Closing dialog from parent pulses open persistent dialog in child 

### ISSUE THREAD

**Issue by Webifi** [vuetifyjs/vuetify#9921] opened 2019-12-09 20:51 UTC
### Environment
**Vuetify Version:** 2.1.13
**Last working version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
1. Open dialog 1
2. In dialog 1, open dialog 2.
3. Close dialog 2
4. Notice that dialog 1 pulses, like it's trying to be closed, but prevented by persistent flag

Issue is in Vuetify 2.1.7 to 2.1.13

Non-working example (Vuetify 2.1.7):
https://codepen.io/webifi/pen/eYmJjwY

Working example (Vuetify 2.1.6):
https://codepen.io/webifi/pen/OJPMwqZ

### Expected Behavior
Open dialog shouldn't pulse, or otherwise try to be closed, when other dialog closes

### Actual Behavior
Open dialog pulses

### Reproduction Link
<a href="https://codepen.io/webifi/pen/eYmJjwY" target="_blank">https://codepen.io/webifi/pen/eYmJjwY</a>

### Other comments
This is likely related to #9907

Note that from Version 2.1.7 to 2.1.10, dialog 1 will not close, even without the persistent flag.  However, in 2.1.10 and after, closing the second dialog will issue an errant close on dialog 1 if it is not set persistent.   Seems possible that the same issue introduced in 2.1.7 that's triggering persistent close-rejection pulse animation may be the root of issue #9907?

**Comment by jacekkarczmarczyk** [comment] 2019-12-10 11:50
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9675

**Closed by jacekkarczmarczyk** 2019-12-10 11:50 UTC
Labels: triage

**Comment by KaelWD** [comment] 2019-12-10 14:24
Duplicate of #9675
