### ISSUE TITLE
[Feature Request] `v-snackbar` should take `app` properties of relevant components into account

### ISSUE THREAD

**Issue by Traxo7** [vuetifyjs/vuetify#4468] opened 2018-07-03 13:54 UTC
### Problem to solve
`v-snackbar` is shown in front of `v-toolbar`, `v-footer` and `v-drawer`.  
Afaiu [material specs](https://material.io/design/components/snackbars.html#placement) that should not happen.

### Reproduction link:  
https://codepen.io/anon/pen/qKwWmW

### Proposed solution
`v-snackbar` should take into account presence of aforementioned components which use `app` attribute, and should be position accordingly. 

### comments
relevant issues:
https://github.com/vuetifyjs/vuetify/issues/1772
https://github.com/vuetifyjs/vuetify/issues/1784

Thus afaiu it can't be resolved with `absolute` property.

**Comment by KaelWD** [comment] 2018-07-03 14:07
Also #1852

**Comment by hounded** [comment] 2019-01-20 21:43
Unsure if this is the best way to do it but fixed it for me 
```
  <v-snackbar
      v-model="snack"
      :timeout="6000"
      :color="snackColor"
      :multi-line=true
      :top=true
      style="z-index: 1080"
    >
```

**Comment by johnleider** [comment] 2019-06-19 16:05
I still intend to implement this but unfortunately did not make the cut for v2.0. Mainly because We plan to separate fab from v-btn in order to give it applicationable support as well. Thank you for your patience.

**Comment by Shinigami92** [comment] 2020-03-19 12:27
Is there a fix in sight? Can I help in any way?

**Comment by Shinigami92** [comment] 2020-03-28 14:29
The bug seems to occur only within a `VExpansionPanel` 🤔 
When I define a `VSnackbar` e.g. whithin `VCard`, everything works just fine

But it's a little bit bad for me, cause in a production app, we have a Component that renders a `VExpansionPanel` and is used in a `v-for` and every panel has a `VSnackbar`. So I have to create a complex setup to extract this `VSnackbar` out of the Component and move it out of the `VExpansionPanels`

**Comment by johnleider** [comment] 2020-05-22 19:57
resolved by #11448

**Closed by johnleider** 2020-05-22 19:57 UTC
Labels: C: VSnackbar, S: has PR, T: bug, T: feature

**Comment by KosratDAhmad** [comment] 2020-06-12 19:26
The `app` prop is by default `true` and there is no way to turn it to `false` in the version `2.3.0` please fix it.

**Comment by MajesticPotatoe** [comment] 2020-06-12 19:39
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
