### ISSUE TITLE
[Bug Report][3.3.3] v-select not respecting item-disabled

### ISSUE THREAD

**Issue by dandormont** [vuetifyjs/vuetify#17558] opened 2023-06-07 20:58 UTC
### Environment
**Vuetify Version:** 3.3.3
**Last working version:** 2.3.23
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Go to above link. Click the items in the select box.

### Expected Behavior
The item marked as disabled should be disabled.

### Actual Behavior
The item marked as disabled is not disabled.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUstO5DAQ/JVeX7IrTWIts6doWMGNP+BAOGSSHjD4JbsTQKP8O20noGiGAxKn2O2qrqru3B3FtffVOKCoxY7QeN0S/m8swG4sW+/zMV86Z6lVFsNSykXCVyoPCnUPY2lcj/qyESY+NALkB1Wec5kZUWNHUCsWjUzK309aIs3qO7lyxdfYBeUJItIwm1PGu0BwhIAHmOAQnIGCAxUJDsDSkYAtwWVC/C5uUGsHty7o/lfxZw3KFhbY3Wz0CKRIYw3F32IDY6uH+QzT5hRwsQJcfAXYrgDp3KvY7jX2NVAYcCHcs6OdnENyPLERc77StL56is7yno4JyBPLDzyzGnIl1Th3ujfikcjHWsqut0zjvagxVBZJWm/kFcNkGCwpg2XvzNW22lb/JBuidbnCaMp9cC8RAzdpxBIpy5A6vH1DakFmhe2ssJRK3e5jkjhrLVlvxFAGtD0GDN9NdEJbpzp5OkuW1KfGTjxvrexzPBl1F/OYl5/ih5Fzs7zrJDhtRPbJypkg7t8B6D8shA==)

**Comment by KaelWD** [comment] 2023-06-08 05:57
Duplicate of #15933

**Closed by KaelWD** 2023-06-08 05:57 UTC
Labels: S: triage

**Comment by harkus** [comment] 2023-12-07 21:08
@dandormont 
Try this format instead:
items: [
        { name: 'foo', props: { disabled: true } },
        { name: 'bar', props: { disabled: false } },
        { name: 'fizz' },
        { name: 'buzz' },
      ],
