### ISSUE TITLE
[Bug Report] "Random height" of v-divider & v-select's border

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#3588] opened 2018-03-16 15:47 UTC
### Versions and Environment
**Vuetify:** 1.0.6
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.162
**OS:** Windows 10

### Steps to reproduce
Notice how all the `v-divider` components and bottom borders of `v-select` are all differ in height visually, depending on the page zoom (usually seen in this range 100% - 125%) and lots of other variables (even adding padding somewhere on the top might affect all the following elements). 

You can even see it on the Vuetify's docs page:

It's very noticeable on the `v-select` components  with `class="input-group--focused"` usually when you have several of the them on the same they look very different depending on their placement and surrounding components.

### Example 1:
![c1](https://user-images.githubusercontent.com/13764106/37530390-78b32e3e-294a-11e8-919a-505d2be2c30d.png)

### Example 2:
![c3](https://user-images.githubusercontent.com/13764106/37559341-2feb2eea-2a35-11e8-81b0-3427b7850456.png)

### Example 3:
![c2](https://user-images.githubusercontent.com/13764106/37530394-7a6295b2-294a-11e8-9840-25f1d9419486.png)

### Expected Behavior
To have the same height visually. 

### Actual Behavior
Described above

### Reproduction Link
[https://codepen.io/anon/pen/BrLNPa?editors=1000](https://codepen.io/anon/pen/BrLNPa?editors=1000)

**Comment by johnleider** [comment] 2018-03-16 23:36
I'm not sure what we can do about this. The element is not 2px, it's 1px, but there is a visual anomaly when zooming in.

**Comment by AlexSHoffman** [comment] 2018-03-17 01:23
@johnleider Hmm, I tried to change some styling around a bit, I'm not sure, but it looks like using different implementation of these styles could fix it, for example:

###  Fix for `v-select`:
- Instead of using `height: 2px;` in selector `.input-group__details:before`
- Add `border-top: 2px solid rgba(0,0,0,0.42);` into selector `.input-group__details { }` 


###  Fix for `v-divider`:
- Instead of using `height: 1px; min-height: 1px;` in selector `.divider`
 - Add `border-bottom: 1px solid rgba(0,0,0,0.12);` into selector `.divider`

/Need testing

**Comment by johnleider** [comment] 2018-03-17 01:24
If you are already testing implementations, feel free to PR

**Comment by KaelWD** [comment] 2018-03-17 02:33
Duplicate of #3090

**Closed** 2018-05-31 07:32 UTC
Labels: T: bug
