### ISSUE TITLE
[Feature Request] Warnings in addition to errors in forms

### ISSUE THREAD

**Issue by sense-it-gmbh** [vuetifyjs/vuetify#8796] opened 2019-08-30 06:52 UTC
### Problem to solve
There isn't a real problem. Though it would be nice to have the ability to display warnings next to inputs, colored in the default warning color.

### Proposed solution
A second set of rules for all input components that support rules so far. These rules only display warnings just like errors but in the default warning color. Warnings don't affect the validation state of the form.

#### Example use-case:

For a password input it would be good to ensure at least 8 characters (error-rule) but warn if there are less than 10 (warning-rule). This way the user can be noticed that the password is possibly insecure without being to restrictive (users usually hate long passwords).

**Comment by KaelWD** [comment] 2019-08-30 06:55
Duplicate of #4819

**Closed by KaelWD** 2019-08-30 06:55 UTC
Labels: triage
