### ISSUE TITLE
[Feature Request] Table - Mobile view (small screen)

### ISSUE THREAD

**Issue by bobemmen** [vuetifyjs/vuetify#6331] opened 2019-02-02 22:01 UTC
### Problem to solve
Table viewing as 'cards' in Mobile view (small screens).

### Proposed solution
 Such as seen in Buefy (https://buefy.github.io/documentation/table

**Comment by jacekkarczmarczyk** [comment] 2019-02-03 07:13
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5234

**Closed by jacekkarczmarczyk** 2019-02-03 07:13 UTC

**Comment by HuthDev** [comment] 2019-04-08 19:59
Test
