### ISSUE TITLE
[Bug Report] Usage of slots with empty slotProps leading slots are not shown

### ISSUE THREAD

**Issue by elibolonur** [vuetifyjs/vuetify#12583] opened 2020-11-10 17:19 UTC
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.183
**OS:** Mac OS 10.15.6

### Steps to reproduce
1. Use `<v-text-field>` and try to use any slot (i.e. append) to inject anything inside
2. Add slot props on the slot when it  does not provide it -> `#append="props"`

### Expected Behavior
Even if props are not provided by the component, it should still show the slot

### Actual Behavior
It is not showing the slot content

### Reproduction Link
<a href="https://codepen.io/onelly/pen/xxOQgPQ" target="_blank">https://codepen.io/onelly/pen/xxOQgPQ</a>

### Other comments
I am not sure if this is a bug or expected behaviour but this I have realised when I was trying to create a wrapper component around `v-text-field`

Now when I want to dynamically generate all the slots and pass the slot props to the parent I use something like this: 
```
// child.vue
<v-text-field>
  <template v-for="slot in slots" #[slot]="props">
    <slot :name="slot" :props="props" />
  </template>
</v-text-field>
```
This is just automatically generating slots inside child component -> v-text-field, if the parent is sending any slot. But as long as I am using `#[slot]="props"` the slots that has not any slotProps are not shown. Using the slot as `#[slot]` solves the issue but then I don't have any access to the props from the parent.

**Comment by jacekkarczmarczyk** [comment] 2020-11-10 17:26
Technically duplicate of https://github.com/vuetifyjs/vuetify/issues/10215 but I think that using $scopedSlots instead of $slots in VInput should be easy to do and IMHO issue could stay open

**Comment by johnleider** [comment] 2021-07-14 17:22
The append slot isn't scoped and shouldn't be used as such. This will naturally be resolved as part of Vuetify 3.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-07-14 17:22 UTC
Labels: C: VInput
