### ISSUE TITLE
[Bug Report][2.5.3] v-tabs-slider incorrect width on initial render

### ISSUE THREAD

**Issue by davidbielik** [vuetifyjs/vuetify#13744] opened 2021-06-02 22:24 UTC
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.13
**Browsers:** Chrome 90.0.4430.212
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Hard Refresh (CMD+SHIFT+R)
2. Look at the active v-tabs-slider

### Expected Behavior
slider should not exceed the width of the tab

### Actual Behavior
slider exceeds the width of the tab

### Reproduction Link
<a href="https://codepen.io/codepen123456789/pen/XWMZPON" target="_blank">https://codepen.io/codepen123456789/pen/XWMZPON</a>

### Other comments
switching between tabs to re-render it, causes it to resume the correct width. the initial rendering seems to be incorrect based on how quickly the tab contents/icon loads

**Comment by jacekkarczmarczyk** [comment] 2021-06-05 17:01
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4733

**Closed by jacekkarczmarczyk** 2021-06-05 17:01 UTC
Labels: triage
