### ISSUE TITLE
[Feature Request]  rendering custom markup

### ISSUE THREAD

**Issue by Alhar6i** [vuetifyjs/vuetify#17341] opened 2023-05-10 15:20 UTC
### Problem to solve
Feat: a slot that allows for rendering custom markup before the list item.

### Proposed solution
Let's take the Autocomplete component as an example. One can use this feature to provide a handy approach for adding new items to the list without leaving the current page.
The markup can be for example 'Add new item', and when the user clicks on it a window for adding the new item can be disapplied.

**Comment by KaelWD** [comment] 2023-05-10 15:21
Duplicate of #4061

**Closed by KaelWD** 2023-05-10 15:21 UTC
