### ISSUE TITLE
[Bug Report] v-text-field not update data bound by v-model when input a Chinese character with Chinese input method (IME)

### ISSUE THREAD

**Issue by CLDXiang** [vuetifyjs/vuetify#11207] opened 2020-04-23 18:31 UTC
### Environment
**Vuetify Version:** 2.2.23
**Last working version:** 2.2.22
**Vue Version:** 2.6.10
**Browsers:** Chrome 84.0.4121.0
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. input a Chinese character with IME
2. click outside

### Expected Behavior
The character should remain in the text area, which indicates that the bound value was updated

### Actual Behavior
The character disappeared

### Reproduction Link
<a href="https://codepen.io/cldxiang/pen/MWaJRNO" target="_blank">https://codepen.io/cldxiang/pen/MWaJRNO</a>

### Other comments
1. Only happen when input with IME, it works correctly when simply pasting a Chinese character. e.g. paste '文'
2. Also work correctly when deleting a Chinese character
3. if you input a English character after the Chinese character, it will correctly update the bound data. e.g. input '中文' with IME, then input 'en', then data will be correctly updated to '中文en'

**Comment by jacekkarczmarczyk** [comment] 2020-04-23 18:33
possible duplicate of https://github.com/vuetifyjs/vuetify/issues/11190

**Comment by johnleider** [comment] 2020-04-24 14:17
Duplicate #11190

**Closed by johnleider** 2020-04-24 14:17 UTC
Labels: triage
