### ISSUE TITLE
[Bug Report] button tag lost renderization

### ISSUE THREAD

**Issue by ppKrauss** [vuetifyjs/vuetify#3535] opened 2018-03-11 14:42 UTC
### Versions and Environment
**Vuetify:** 1.0.6
**Vue:** 2.5.15
**Browsers:** Chrome 64.0.3282.167
**OS:** Linux x86_64

### Steps to reproduce
1. run codepen
2. click a item
3. click a button ("TEST" or "Toggle")

### Expected Behavior
expect to see button as traditional Vue button

### Actual Behavior
no effect, no rendering

### Reproduction Link
[https://codepen.io/ppKrauss/pen/oqXYox?editors=1010](https://codepen.io/ppKrauss/pen/oqXYox?editors=1010)

**Comment by jacekkarczmarczyk** [comment] 2018-03-11 15:01
duplicate of https://github.com/vuetifyjs/vuetify/issues/2848

**Closed by jacekkarczmarczyk** 2018-03-11 15:01 UTC

**Comment by ppKrauss** [comment] 2018-03-11 15:44
Ok, it is not a bug,  there are some documentation about "not use button" and use `v-btn`
