### ISSUE TITLE
[Feature Request] How to perform non-autofocus after Combobox is cleared？

### ISSUE THREAD

**Issue by qinkaiyuan** [vuetifyjs/vuetify#7178] opened 2019-05-10 11:30 UTC
### Problem to solve
I need to not autofocus after clearing the Combobox

### Proposed solution
add property  cleared-autofocus:Boolean  default = false or true 

I tried this way，it isn't executed 

    <v-combobox ref="keywords" class="app-search"
                        v-model="inputKeywords"
                        multiple
                        clearable
                        deletable-chips
                        :items="states"
                        @click:clear="clearInput"
                        @change="clearInput"
                        @input="clearInput"
                        chips
            ></v-combobox>

    clearInput() {
                this.$refs.keywords.blur()
                setTimeout(() => {
                    this.$refs.keywords.blur()
                }, 1)
            },

now, 

I succeeded using the method below：

        <v-combobox ref="keywords" class="app-search"
                        v-model="inputKeywords"
                        append-icon="clear" multiple
                        deletable-chips
                        :items="states"
                        @change="clearInput"
                        @input="clearInput"
                        @click:append="clearInput"
                        chips
            ></v-combobox>

    clearInput() {
                this.$refs.keywords.blur()
                this.inputKeywords = []
                setTimeout(() => {
                    this.$refs.keywords.blur()
                }, 1)
            },

**Comment by jacekkarczmarczyk** [comment] 2019-06-01 15:42
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4135

**Closed by jacekkarczmarczyk** 2019-06-01 15:42 UTC
Labels: triage
