### ISSUE TITLE
[Bug Report] v-autocomplete menu wont close on select, if items come from a function

### ISSUE THREAD

**Issue by sourenaraya** [vuetifyjs/vuetify#5139] opened 2018-09-21 07:02 UTC
### Versions and Environment
**Vuetify:** 1.2.4
**Vue:** 2.5.16
**Browsers:** Chrome 69.0.3497.81
**OS:** Linux x86_64

### Steps to reproduce
Click in the input, menu will pop-up, click on one of the items once. Menu will stay opened untill second click.

This happens only when v-select has `v-model` set and `:items` binded to a function. 

### Expected Behavior
Menu actually closes on first click.

### Actual Behavior
Menu stays opened untill second click on the same item

### Reproduction Link
[https://codepen.io/souren-araya/pen/qMgjJm](https://codepen.io/souren-araya/pen/qMgjJm)

**Comment by jacekkarczmarczyk** [comment] 2018-09-21 07:33
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4663

**Closed by jacekkarczmarczyk** 2018-09-21 07:33 UTC
