### ISSUE TITLE
[Bug Report] Problem with v-text-field and type=number in Safari

### ISSUE THREAD

**Issue by pmiguelmartins** [vuetifyjs/vuetify#10745] opened 2020-03-04 20:40 UTC
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Safari 13.0.5
**OS:** Mac OS 10.15.3

### Steps to reproduce
Write letters in field .... 

then click clear button

### Expected Behavior
Only accept numbers

Empty field after clear button

### Actual Behavior
Permit write letter inside field and if there is letters when clear doesn't clear

### Reproduction Link
<a href="https://codepen.io/pmiguelmartins/pen/gOpGrKG" target="_blank">https://codepen.io/pmiguelmartins/pen/gOpGrKG</a>

### Other comments
if I write letters when clear doesn't clear...

MacOs and Ipad safari

**Comment by jacekkarczmarczyk** [comment] 2020-03-07 06:25
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8749

@johnleider 
https://github.com/vuetifyjs/vuetify/pull/8808#issuecomment-526683876

Native inputs behave the same (https://codepen.io/jkarczm/pen/yLNPoVJ) so we may say that's is't not a bug from the dev perspective, but it's different from the end user point of view and if all it takes to improve it is oneliner PR I don't think we should reject it. Thoughts?

**Comment by johnleider** [comment] 2021-07-14 18:01
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-07-14 18:01 UTC
Labels: C: VTextField, T: question, duplicate
