### ISSUE TITLE
[Feature Request] Add ability to control font size (accessibility)

### ISSUE THREAD

**Issue by sagikarni** [vuetifyjs/vuetify#3805] opened 2018-04-07 20:08 UTC
### Problem to solve
Ability to build accessible websites.
The font size in the elements are defined as px.
Using rem units will allow end users to set the font size to their desired size. 

### Proposed solution
Use rem

**Comment by johnleider** [comment] 2018-04-09 16:44
Duplicate of #3401

**Closed by johnleider** 2018-04-09 16:44 UTC
Labels: pending review
