### ISSUE TITLE
[Feature Request] Is there a splitter control?

### ISSUE THREAD

**Issue by softwareguy74** [vuetifyjs/vuetify#7839] opened 2019-07-15 22:43 UTC
### Problem to solve
Splitter component

### Proposed solution
Splitter component

**Comment by jacekkarczmarczyk** [comment] 2019-07-15 22:49
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5994

**Closed by jacekkarczmarczyk** 2019-07-15 22:49 UTC
Labels: triage
