### ISSUE TITLE
[Bug Report] Radio Button Color Prop Doesn't Propogate to Hover

### ISSUE THREAD

**Issue by mirikerstein** [vuetifyjs/vuetify#11290] opened 2020-05-01 03:31 UTC
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 3.0.0-beta.4
**Browsers:** Chrome 81.0.4044.129
**OS:** Windows 10

### Steps to reproduce
Simply create a v-radio-group and assign a color to the color prop.

### Expected Behavior
If you hover over any radio buttons within the group, the color of the hover should be that which you assigned to the color prop.

### Actual Behavior
 If you hover over any inactive radio buttons within the group, the color of the hover will still be blue.

### Reproduction Link
<a href="https://codepen.io/mkers/pen/JjYrRBG" target="_blank">https://codepen.io/mkers/pen/JjYrRBG</a>

**Comment by jacekkarczmarczyk** [comment] 2020-05-03 14:51
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10979

**Closed by jacekkarczmarczyk** 2020-05-03 14:51 UTC
Labels: C: VCheckbox, C: VRadio, S: has PR, triage
