### ISSUE TITLE
[Bug Report][2.6.3] Custom component as v-menu activator is not rendered based on the display breakpoint

### ISSUE THREAD

**Issue by jgunawancode** [vuetifyjs/vuetify#14655] opened 2022-01-27 12:49 UTC
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.14
**Browsers:** Firefox 96.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Resize the window to be less than default medium breakpoint in Vuetify

### Expected Behavior
Custom component is displayed as the `v-menu` activator

### Actual Behavior
Custom component is not displayed as the `v-menu` activator

### Reproduction Link
<a href="https://codepen.io/jgunawan-dc/pen/XWzJqRy" target="_blank">https://codepen.io/jgunawan-dc/pen/XWzJqRy</a>

### Other comments
The custom component is displayed if I use `v-show`. But if I use `v-show`, the menu is not displayed under the activator after a page resize.

**Comment by KaelWD** [comment] 2023-04-28 11:56
Duplicate of #9377

**Closed by KaelWD** 2023-04-28 11:56 UTC
Labels: S: triage
