### ISSUE TITLE
[Bug Report][3.1.14] v-slider thumb circle does not move

### ISSUE THREAD

**Issue by craigbroadbear** [vuetifyjs/vuetify#17159] opened 2023-04-16 02:49 UTC
### Environment
**Vuetify Version:** 3.1.14
**Last working version:** 3.0.5
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
Try and move the large circle in the middle of the slider, it does not move.

### Expected Behavior
The large circle moves with the value of the slider

### Actual Behavior
Circle does not move from center.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUt1uwiAUfhXClSYWrLosaapxzyFeVIsbG38B7LaYvvtOoc20Xugd5zuc7+fA7oLfrCXNmeMCl4ErK6vAN0wjVNaiiQc4NpmXouYulQg1mTI1l2uGE54zPLSORhoHDeMq/c7/cVkd4kDsD/CmpAM1SEUsStOkXdIrR1D6oxM2RFP8xxoXUM1P1VkGdEl8dRWqAk2maL1Bkx5DqPdYoPnsFloU6GWMLQuUzwewncZD21npxfEMS6G/PPn0RsPSogrE8p7hAu3SHMMfIVhfUHqsNdyEXYnGEc0D1VZRWHcQp9/tkuQkX0FYHwYsgz15Etk6qj3TLSgK1aXNVGVHsqkRpfu4DANTVz/wsIVr1J11EIpntVFgZkFWr8nMFU64V9nBmW/PHbAw3K8m6nSOn9B6mBc07rgpCDbcZY5reBb4e09mGo3d5Br17rL1j93idobTHCw/ucb7PxHfBwk=)

**Comment by websitevirtuoso** [comment] 2023-04-16 08:03
Please read documentation carefully
```
<template>
  <v-app>
    <v-slider
      v-model="slider1"
      color="orange"
      label="color"
    ></v-slider>

   
  </v-app>
</template>

<script>
  export default {
    data: () => ({
      slider1: 0,
      slider2: 50,
      slider3: 100,
    }),
  }
</script>
```

**Comment by craigbroadbear** [comment] 2023-04-16 11:20
What am I missing?  I copied the example from the vuetify docs and it works
fine in earlier versions of vuetify.

**Comment by websitevirtuoso** [comment] 2023-04-16 17:24
v-app is main tag for vuetify. when you build app you must use it 1 time.
In vuetify 2 we also had it and the same requirement

**Comment by craigbroadbear** [comment] 2023-04-16 23:17
Thank you, that does the trick.  Note it did work fine in vuetify 3.0.5 for
some reason.

**Comment by websitevirtuoso** [comment] 2023-04-16 23:43
If possible please close this issue

**Closed** 2023-04-16 23:44 UTC
Labels: S: triage

**Comment by craigbroadbear** [comment] 2023-04-16 23:48
The v-app fix works.  I suggest this requirement be made clearer in the documentation on v-slider or the dependency removed.

**Comment by websitevirtuoso** [comment] 2023-04-16 23:50
Yes. Maybe. I think you can creat PR in documentation to create a note about this.
v-app has to be used not only for v-slider. for all components

**Comment by KaelWD** [comment] 2023-04-17 05:44
Duplicate of #16586
