### ISSUE TITLE
[Bug Report] VToolbar height is broken

### ISSUE THREAD

**Issue by gadelkareem** [vuetifyjs/vuetify#7807] opened 2019-07-11 14:29 UTC
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
toolbar height is half the page

### Expected Behavior
toolbar should be correct height

### Actual Behavior
check the example

### Reproduction Link
<a href="https://codepen.io/gadelkareem/pen/pXYWmL" target="_blank">https://codepen.io/gadelkareem/pen/pXYWmL</a>

### Other comments
something wrong with flex-basis:auto

**Comment by johnleider** [comment] 2019-07-14 01:16
This is because the root of `v-app` is a flex column and the toolbar now has **flex: 1 1 auto**. As a work around for now you can apply the _shrink_ class:

https://codepen.io/johnjleider/pen/QXRdom

Or you can wrap it in a div:
https://codepen.io/johnjleider/pen/RzmKOo

Or you can put it inside content, many options.

**Comment by johnleider** [comment] 2020-01-16 17:00
Closing as this is currently the expected behavior.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-16 17:00 UTC
Labels: C: VToolbar, P: low, T: bug, has workaround
