### ISSUE TITLE
[Bug Report] Inconsistent input heights

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#10723] opened 2020-03-02 23:52 UTC
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Windows 7

### Steps to reproduce
1. Dense text field is marginally smaller than dense select/autocomplete when all are empty.
2. Dense select & dense autocomplete are the same size, until you select an option, making dense select even taller.

### Expected Behavior
All the same height all of the time

### Actual Behavior
Different heights under same/different conditions

### Reproduction Link
<a href="https://codepen.io/teellcory/pen/abOyOep" target="_blank">https://codepen.io/teellcory/pen/abOyOep</a>

**Comment by jacekkarczmarczyk** [comment] 2020-03-02 23:54
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10635

**Closed by jacekkarczmarczyk** 2020-03-02 23:54 UTC
Labels: triage
