### ISSUE TITLE
[Bug Report][3.2.2] grid v-col xs has no effect

### ISSUE THREAD

**Issue by lpfy** [vuetifyjs/vuetify#17317] opened 2023-05-08 08:52 UTC
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
resize window, xs specified in v-col doesn't take effect. The HTML generated as 
`<div class="v-col-sm-4 v-col-md-3 v-col" xs="12"> 1 </div>`

### Expected Behavior
`<div class="v-col-sm-4 v-col-md-3 v-col-xs-12 v-col"> 1 </div>`

### Actual Behavior
`<div class="v-col-sm-4 v-col-md-3 v-col" xs="12"> 1 </div>`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUdFuwjAM/JUoL3uhjShomxCb2HcQHkprtGxNGiWh24T677PTgloQiGlv9uV8F5/XB/5mbdrsgS/4MoC2VR7gVRrGlk2SWxvL2Ohcmb6LfVGbgBC4ExhhV38NgJ5ZMV2+SD6TnHmNxRyLb4/FNJN8RGdsOpoWcfyq4uNR8fmGYvYXxdMfSeiq5Oy2JCHDIDrGOC/CTplS06W9FIMrYOsLp2xgHsKenpW2tQvswBzsWMt2rtbsAc/3QGSa7vjI5BPekdHFph++NnjiA5nJ/sFLvmARIQxFqJf8PQTrF0IUpcGxEirVuNRAEMZqsUKacHsTlIakrPVqlmbp/EmUyochnoLXyRYz8OBQRfLJwCeo3c8dXj0zWmSdQw8lVb71ZHEhLdCvAZc4MCU4cPeudDY2Wuvs7WI1sm+laTHxSplPfxZ24WPQ6+Mv/7VzFCOlDRm2E959FK3jBN/8AsYvKxw=)

**Comment by yuwu9145** [comment] 2023-05-08 11:13
there is no xs breakpoint, you should use `cols="12"`.

[demo](https://play.vuetifyjs.com/?preview=false#eNqlUdFuwjAM/JUoL7zQRhS0TYhN7DsID6U1WrYmjZLQaUL999lpQS1oiIk3+3K+i8+bI3+3Nm0OwJd8FUDbKg/wJg1jqybJrY1lbHSuTN/FvqhNQAjcGYywq78HQM+smC5fJZ9LzrzGYoEFoh7LWSb5aICx2WheRIE/NZ9Omi83NbP/aJ7/SUI3ROe3RQkZxtExxqkRdk6Wmi7zlRjcAltfOGUD8xAO9Ky0rV1gR+Zgz1q2d7VmEzzihMg03fGRyae8I6OLTT99bfDQRzKT/YOXfMkiQhiKUC/5RwjWL4UoSoNjJVSqcamBIIzVYo004Q4mKA1JWev1PM3SxbMolQ9DPAWvkx1m4MGhiuTTgU9Q+587vHpmtMg6hx5KqnznyeJKWqBfAy5xYEpw4O5d6WJstNbF29VqZN9K02LilTJf/iLswsegN6dfPrRzFCOlLRm2U959FK3jBN/+AhRDLW4=)

**Comment by KaelWD** [comment] 2023-05-08 11:15
Duplicate of #8997

**Closed by KaelWD** 2023-05-08 11:15 UTC
Labels: S: triage
