### ISSUE TITLE
[Bug Report] v-overlay is not removed if browser tab is backgrounded.

### ISSUE THREAD

**Issue by zaun** [vuetifyjs/vuetify#9398] opened 2019-10-18 01:12 UTC
### Environment
**Vuetify Version:** 2.1.5
**Last working version:** 1.5.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
1) Set a timeout to open dialog in 10 seconds
1) Open a dialog
2) Set a timeout that will close the dialog in 10 seconds
3) Open a new browser tab
4) Wait 15 seconds
5) Return to the test tab, the dialog is gone but the overlay is visible

### Expected Behavior
The overlay is removed

### Actual Behavior
The overlay is not removes

### Reproduction Link
<a href="https://codepen.io/jzaun/pen/mddrXeE" target="_blank">https://codepen.io/jzaun/pen/mddrXeE</a>

### Other comments
The issue is that the [removeOverlay](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/mixins/overlayable/index.ts#L105) adds a listener for `transitionend `. This event is [not fired](https://stackoverflow.com/questions/41779371/on-transitionend-event-not-fire-when-chrome-tab-is-in-background) if the tab is in the background.

**Comment by KaelWD** [comment] 2019-11-07 13:27
Duplicate of #8625

Thanks for digging into it though

**Closed by KaelWD** 2019-11-07 13:27 UTC
Labels: triage
