### ISSUE TITLE
[Bug Report] While open, V-Dialog prevents editing of textarea in other popup

### ISSUE THREAD

**Issue by xyannik** [vuetifyjs/vuetify#10346] opened 2020-01-27 14:13 UTC
### Environment
**Vuetify Version:** 2.2.6
**Last working version:** 2.0.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Click on "Open Dialog" to open a Vuetify-Dialog. Then click on "Open Textarea Popup" and try to edit the textarea in the second popup, it will not be editable.

### Expected Behavior
The textarea should be editable.

### Actual Behavior
Text in textarea can neither be edited, nor selected (used to work in vuetify 2.0.19)

### Reproduction Link
<a href="https://jsfiddle.net/xYannik/pL5vm028/1/" target="_blank">https://jsfiddle.net/xYannik/pL5vm028/1/</a>

### Other comments
Our use case for this: We use TinyMCE inside v-dialog. TinyMCE has their own popup to allow editing the HTML-source, which is now not possible anymore. I tried fixing the issue with different z-index combinations, but it seems to be a JS problem when detecting clicks.

**Comment by KaelWD** [comment] 2020-01-27 14:45
Duplicate of #6892

**Closed by KaelWD** 2020-01-27 14:45 UTC
Labels: triage
