### ISSUE TITLE
[Bug Report] v-combobox doesn't lose focus when empty

### ISSUE THREAD

**Issue by d3radicated** [vuetifyjs/vuetify#10612] opened 2020-02-19 07:48 UTC
### Environment
**Vuetify Version:** 2.2.13
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.106
**OS:** Mac OS 10.15.3

### Steps to reproduce
1. Click on the combobox to focus the field.
2. Click outside the combobox to blur.

### Expected Behavior
The combobox should return back to the initial state.

### Actual Behavior
The combobox is still styled like it's focused.

### Reproduction Link
<a href="https://codepen.io/dEradicated/pen/PoqzLoK" target="_blank">https://codepen.io/dEradicated/pen/PoqzLoK</a>

**Comment by KaelWD** [comment] 2020-02-19 08:16
#10525

**Comment by KaelWD** [comment] 2020-02-19 08:36
Duplicate of #10606

**Closed** 2020-02-19 09:13 UTC
Labels: C: VCombobox, T: bug, T: regression
