### ISSUE TITLE
Disabled prop for form to disable all children

### ISSUE THREAD

**Issue by raharida** [vuetifyjs/vuetify#1889] opened 2017-09-26 05:48 UTC
This is a feature Request

I would like to have a property in the v-form to disable all the children. Right now if a developer has to disable all the fields in a form , he has to add disabled prop to all children which becomes cumbersome and difficult to maintain and prone to errors , for ex: if developer misses to add the property to one of the elements 

TIA

**Comment by KaelWD** [comment] 2017-09-26 05:50
Duplicate of #1707

**Closed by KaelWD** 2017-09-26 05:50 UTC
