### ISSUE TITLE
[Bug Report][2.5.2] Select list in navigation drawer hover doesn't stay open.

### ISSUE THREAD

**Issue by OblivionSY** [vuetifyjs/vuetify#13736] opened 2021-06-01 19:25 UTC
### Environment
**Vuetify Version:** 2.5.2
**Vue Version:** 2.6.11 (Used in Nuxt 2.14.6)
**Browsers:** Chrome 90.0.4430.212
**OS:** Windows 10

### Steps to reproduce
In the repo link, hover over the menu and try and select something from the drop down select list. The navigation drawer collapses back and select moves (though is still visible)

### Expected Behavior
menu remains open while menu contents are still active.

### Actual Behavior
Menu collapses back

### Reproduction Link
<a href="https://codepen.io/OblivionSY/pen/poepmvE" target="_blank">https://codepen.io/OblivionSY/pen/poepmvE</a>

**Comment by KaelWD** [comment] 2021-06-01 19:43
Duplicate of #13555

**Closed by KaelWD** 2021-06-01 19:43 UTC
Labels: triage
