### ISSUE TITLE
[Bug Report] Select Input Menu Hidden Bug on Safari when using Full Screen Dialog

### ISSUE THREAD

**Issue by JasonGrant** [vuetifyjs/vuetify#3552] opened 2018-03-12 19:00 UTC
### Versions and Environment
**Vuetify:** 1.0.6
**Vue:** 2.5.13
**Browsers:** Safari
**OS:** Mac OS 10.12.4

### Steps to reproduce
If using the reproduction link on Safari on a Mac (Version 10.1 (12603.1.30.0.34)) or on iOS Safari or Chrome on iOS, when you click on the select input the menu is behind the dialog.

If you find the created menu in the inspector and manually change the z-index from 8 to 202 it will display the select list. A z-index of less than 201 will be hidden.

The same issue does not appear in Chrome or Firefox.

### Expected Behavior
I expect to see the menu list when clicking on a select input when using Safari.

### Actual Behavior
Menu list is hidden by full screen dialog

### Reproduction Link
[https://codepen.io/mrjasongrant/full/LdpbdE/](https://codepen.io/mrjasongrant/full/LdpbdE/)

**Comment by KaelWD** [comment] 2018-03-20 12:50
Duplicate of #2111

**Closed by KaelWD** 2018-03-20 12:50 UTC
Labels: bug, help wanted
