### ISSUE TITLE
[Feature Request] v-menu will only appeared after all page content was rendered.

### ISSUE THREAD

**Issue by everyx** [vuetifyjs/vuetify#10180] opened 2020-01-10 08:06 UTC
### Problem to solve
I use v-menu in a site top navigation of my site , but i found that the v-menu will only appeared after page content was rendered, can we have anyway to let the template content of v-menu shown always.

I hope the following pictures will give you an idea of what I mean.

![bug](https://user-images.githubusercontent.com/1665522/72135597-deecff80-33c1-11ea-9f14-eb82e88beb03.gif)

```Vue
<v-menu offset-y open-on-hover>
<template v-slot:activator="{ on }">
  <v-btn class="px-1 mx-2" :to="{name: 'products'}" height="100%" text v-on="on">PRODUCTS</v-btn>
</template>

<v-list v-if="$store.state.products_categories != ''">
    <v-list-item v-for="product in $store.state.products_categories" :key="product.slug">
    <v-btn :to="{name:'products-category-id',params:{id: product.slug}}" text>{{ product.name }}</v-btn>
    </v-list-item>
</v-list>
</v-menu>
```

### Proposed solution
Let v-menu template content appeared in its place and no need to wait.

**Comment by jacekkarczmarczyk** [comment] 2020-01-15 06:42
Please provide the codepen reproduction

**Comment by KaelWD** [comment] 2020-01-15 06:51
Duplicate of #7422

**Closed by KaelWD** 2020-01-15 06:51 UTC
Labels: S: needs reproduction, triage
