### ISSUE TITLE
[Feature Request] :class binding for individual <tr> elements within <v-data-table>

### ISSUE THREAD

**Issue by goofballtech** [vuetifyjs/vuetify#8624] opened 2019-08-20 02:18 UTC
### Problem to solve
Currently the only way to apply any styling to each row is to use the items prop. This also removes the ability to have expandable rows and selections as those elements will be over-written with the modified  [tr] and [td] components. 

### Proposed solution
add an additional prop that binds to the class of each <tr> to allow specific styling basic on some per-item logic during table render

**Comment by sh7dm** [comment] 2019-08-20 10:29
@nekosaur do we need this?

**Comment by nekosaur** [comment] 2019-08-20 14:00
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8401

**Closed by nekosaur** 2019-08-20 14:00 UTC
Labels: C: VDataTable, duplicate
