### ISSUE TITLE
[Feature Request] PICKERS - Color picker

### ISSUE THREAD

**Issue by lewisdj** [vuetifyjs/vuetify#4666] opened 2018-07-19 11:15 UTC
### Problem to solve
I would like the user to be able to set the background color of a card. To do this a color picker would be perfect. we currently have support for date and time pickers but not color. 

### Proposed solution
implement a simple color picker that enables the user to pick a color. Defaults should be the theme. But advanced / additional colors can be selected if required. This would also benefit dashboard admins being able to set their theme colors.

**Comment by KaelWD** [comment] 2018-07-19 11:35
Duplicate of #2717

**Closed by KaelWD** 2018-07-19 11:35 UTC
