### ISSUE TITLE
[Bug Report] Icons jump when mini navigation drawer opens

### ISSUE THREAD

**Issue by ThomasKuhlmann** [vuetifyjs/vuetify#8178] opened 2019-07-30 10:54 UTC
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.13.6

### Steps to reproduce
Hover over the menu

### Expected Behavior
The icons should either stay in place or gracefully move to their new position

### Actual Behavior
menu icons jump to their new position, opening the menu like that feels very abrupt

### Reproduction Link
<a href="https://codepen.io/thomaskuhlmann/pen/EqWejv?&editable=true&editors=101" target="_blank">https://codepen.io/thomaskuhlmann/pen/EqWejv?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment] 2019-07-30 12:59
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8007

**Closed by jacekkarczmarczyk** 2019-07-30 12:59 UTC
Labels: triage
