### ISSUE TITLE
[Bug Report][2.5.4] Reset Time Picker on clear

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#13819] opened 2021-06-18 18:41 UTC
### Environment
**Vuetify Version:** 2.5.4
**Vue Version:** 2.6.14
**Browsers:** Chrome 91.0.4472.106
**OS:** Windows 7

### Steps to reproduce
Set any time.
Hit clear

### Expected Behavior
The Time Picker would reset back to the hours section.

### Actual Behavior
The Time Picker stays in the minutes section.

### Reproduction Link
<a href="https://codepen.io/teellcory/pen/dyvrQoL" target="_blank">https://codepen.io/teellcory/pen/dyvrQoL</a>

### Other comments
This may already be possible, but I did not see a way to programmatically switch it back. The usage scenario would be if someone enters a time, closes it, clears it, opens it again: they would want to start from the hours again, not the minutes.

**Comment by jacekkarczmarczyk** [comment] 2021-06-18 18:50
https://codepen.io/jkarczm/pen/MWpxzyO

`selecting` could actually be a synced prop, anyway that's not a bug, so closing the issue

**Closed by jacekkarczmarczyk** 2021-06-18 18:50 UTC
Labels: triage
