### ISSUE TITLE
[Bug Report] vuetify combobox change event fires twice

### ISSUE THREAD

**Issue by salalaslam** [vuetifyjs/vuetify#8425] opened 2019-08-09 10:42 UTC
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
in the reproduction link provided, navigate options of combobox using arrow keys and select option by pressing enter, you can see in console that the event is called twice, which results in the value of attached model i.e. to null or the value of search-input

### Expected Behavior
upon selection change event shouldn't be called twice, or atleast the model should have the selected option

### Actual Behavior
upon selection change event is called twice, and the model results in having no value

### Reproduction Link
<a href="https://jsfiddle.net/2f0y7gv3/3/" target="_blank">https://jsfiddle.net/2f0y7gv3/3/</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-09 10:48
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8154

**Closed by jacekkarczmarczyk** 2019-08-09 10:48 UTC
Labels: triage
