### ISSUE TITLE
[Feature Request] Support input of type file

### ISSUE THREAD

**Issue by DarkIsDude** [vuetifyjs/vuetify#3183] opened 2018-02-04 01:12 UTC
### New Functionality
`<v-text-field label="Image" v-model="wine.file" type="file" required></v-text-field>`

### Improvements
I don't have work-arounds actually but it will be a good feature

### Bugs or Edge Cases it Helps Avoid
I will try to make specific CSS... And maybe a PR but it will be a good help :)

**Comment by KaelWD** [comment] 2018-02-04 04:21
Duplicate of #238

**Closed by KaelWD** 2018-02-04 04:21 UTC
