### ISSUE TITLE
[Bug Report][3.3.12] <v-date-picker> with <v-locale-provider locale="ru-RU"> breaking on dd.mm.yyyy manual input

### ISSUE THREAD

**Issue by Endermanch** [vuetifyjs/vuetify#18051] opened 2023-08-14 19:30 UTC
### Environment
**Vuetify Version:** 3.3.12
**Vue Version:** 3.3.4
**Browsers:** Edge 115.0.1901.203
**OS:** Windows 10

### Steps to reproduce
1. Switch the view from calendar to input;
2. Input any date in the `dd.mm.yyyy` format - as per Russian locale spec;
3. Press "OK".

### Expected Behavior
Date in the `dd.mm.yyyy` format

### Actual Behavior
Date in the `mm.dd.yyyy` format

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlk81u00AQx19l6ktB6tol5RS1qEUc4EIlWsSh6WFjT+JtvB/srl2iKhKUAwc48QDwCgUR0QO8g/NGzNppm6QgkPDJO/Ob+c/M7hydRXvGxFWJUTfa9ihNwT0+6CmA7YpxY5rf5pBq5blQaOemxljolBfIjNWVyNBCe97pRbZkz573omuW6DXG4AC9F2oIKTdeaAUeX3mQXJW8KMYgHChM0TluxzEcWq4clRO4EY4dcIsghXMhgaDYHOd6cKUfA2OrkntKE2khL4cI/XIIp8LnTXBGrYIR6Yi8JO1z7kF4yDQ6eLp/CK40RlsyZLGU8Zg+GGgrieJEh8qFMqVfFa1YSMzaxDd2gK7UGRas4kUZRlQ+FNbnTw72e9EiVbG+UBn5qSnjln0u16eMZyc8ReWZpBvJ3aI/1YW2FNonBTa0OF4O98I3l1N/nL2vv9TT2ev6cnZeT6H+Vl/Mzmdvl/EcOc204euvRL8h9vIPbMpVSr2FqYSAT4T+qKf1z/pimdOja+ZzkJ9TVMbswzLZzPYabiog6Xm930Pm2bs2tp7+LpJecoq5LtoWOpvxZifubHY6y+xuacJtrVwNT1+WwuIj8iziyc3TT269/atNIc/yqgRLu0nbycKG0dGlVhgPDn3ZLpqQzYM7A4sDmMDAagnrtJzrAQ/XqxytixvCTiDurD/GotDwQtsiW1u/GwTalJQs2ojabExyE584rWjDz0KW3txBb6sLjSXYSCWce1HuvXHdJEkzRWE0FVHZWKFPlJHJLmGJLZUXElmm5e5WvBXfTzLh/KI5RidZ3+pTRzt5QkIbCzJeDOhd/lVqTjYK9zqtxNzGCt53QeNW7oQEK7TMoqIrofX7x5ZWwhbbWnHdai2oT3pqQgMvhBq5lVmnrpnz0VWR/9dzky2kOg6Kk42oKZSk24jo+BcF6wbi)

**Comment by KaelWD** [comment] 2023-08-15 09:11
Duplicate of #17615

**Closed by KaelWD** 2023-08-15 09:11 UTC
Labels: S: triage
