### ISSUE TITLE
[Bug Report][3.0.0-beta.13] VTooltip maxWidth / openDelay defaults not accepted / VOverlay must be used

### ISSUE THREAD

**Issue by seanogdev** [vuetifyjs/vuetify#15911] opened 2022-10-16 23:40 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Vue Version:** 3.2.41
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
VTooltip should accept independent defaults for these settings so they dont affect the VDialogs etc..

### Expected Behavior
The defaults for VOverlay are accepted instead in VTooltip

### Actual Behavior
VTooltip defaults are ignored

### Reproduction Link
<a href="https://codepen.io/seanogdev/pen/NWMmxzP" target="_blank">https://codepen.io/seanogdev/pen/NWMmxzP</a>

**Comment by KaelWD** [comment] 2022-10-30 14:44
Duplicate of #15967

**Comment by KaelWD** [comment] 2022-10-30 14:45
Even if this hadn't been fixed you could do
```js
VTooltip: {
  VOverlay: {
    maxWidth: 400,
    openDelay: 300,
  }
},
```

**Closed by KaelWD** 2022-10-30 14:44 UTC
Labels: S: triage
