### ISSUE TITLE
[Documentation] The Japanese version of the site could not be browsed

### ISSUE THREAD

**Issue by hirobel** [vuetifyjs/vuetify#13431] opened 2021-04-16 06:51 UTC
### Environment
**Vuetify Version:** 2.4.9

**Browsers:** Chrome 89.0.4389.114
**OS:** Mac OS 10.15.7

### Steps to reproduce
visit https://vuetifyjs.com/ja/

### Expected Behavior
japanese page is displayed

### Actual Behavior
A blank page is displayed

### Reproduction Link
<a href="https://vuetifyjs.com/ja/" target="_blank">https://vuetifyjs.com/ja/</a>

### Other comments
The Japanese version of the site could not be browsed.

When I visit https://vuetifyjs.com/ja/, I get the following error:
`` ```
. * \. Json $ namespace object: 13 Uncaught (in promise) Error: Cannot find module'./ja.json'
    at. * \. Json $ namespace object: 13
`` ```

I'm sorry if it's already being fixed there.

**Comment by KaelWD** [comment] 2021-04-16 06:55
Duplicate of #13415

**Closed by KaelWD** 2021-04-16 06:55 UTC
Labels: triage
