### ISSUE TITLE
[Bug Report] v-Incorrect behavior for v-radio when value="null"

### ISSUE THREAD

**Issue by wsmarsh** [vuetifyjs/vuetify#11284] opened 2020-04-30 19:38 UTC
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.129
**OS:** Windows 10

### Steps to reproduce
1) Create a radio-group with 2 v-radio components, with v-model="example"
2) Set the value for 1 v-radio to null (:value="null")
3) Set the value for the other v-radio to, say 1
4) Set the value of example=null

 

### Expected Behavior
1) When loading the component with example=null, the v-radio whose value="null" should be selected
2) When selecting v-radio option whose :value="null", the value of example should update to null also

### Actual Behavior
1) When loading the component with example=null, the v-radio whose value="null" is not selected
2) When selecting v-radio option whose :value="null", the value of example is set to 0, NOT null

### Reproduction Link
<a href="https://codepen.io/wsmarsh/pen/pojWJLg?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fselection-controls%2F" target="_blank">https://codepen.io/wsmarsh/pen/pojWJLg?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fselection-controls%2F</a>

**Comment by jacekkarczmarczyk** [comment] 2020-04-30 19:57
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9073

**Closed by jacekkarczmarczyk** 2020-04-30 19:57 UTC
Labels: triage
