### ISSUE TITLE
[Bug Report][3.2.2] v-text-field, variant outlined has no rounded edges

### ISSUE THREAD

**Issue by m4lt3** [vuetifyjs/vuetify#17276] opened 2023-05-03 09:37 UTC
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Firefox 113.0
**OS:** Linux x86_64

### Steps to reproduce
- npm init vue@latest. 
- npm add vuetify
- follow "Manual steps" Installation instruction
- Create Text field outlined variant

### Expected Behavior
The text field has rounded edges as shown in https://vuetifyjs.com/en/components/text-fields/

### Actual Behavior
text field has no rounded edges. Edges can not be rounded with the "rounded" property or manual css styling

### Reproduction Link
[https://github.com/m4lt3/vuetify_bug_textfield](https://github.com/m4lt3/vuetify_bug_textfield)

### Other comments
Also tested in chrome Version 112.0.5615.165 (Official Build) (64-bit)

Issue also appears for others (https://stackoverflow.com/questions/75823857/is-there-a-way-to-create-a-rounded-vuetify-outlined-text-field-in-vuetify3-wi)

**Comment by KaelWD** [comment] 2023-05-03 09:42
Duplicate of #16586

**Closed by KaelWD** 2023-05-03 09:42 UTC
Labels: S: triage
