### ISSUE TITLE
[Bug Report] v-text-field--outlined border gap for active label too narrow if value is set while component is hidden

### ISSUE THREAD

**Issue by haggys22** [vuetifyjs/vuetify#9165] opened 2019-10-01 13:43 UTC
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Vivaldi 2.7.1628.33
**OS:** Linux x86_64

### Steps to reproduce
0. Open the JSFiddle
1. Click on 'Tab 2'
2. Click on 'Tab 1'
3. Click on 'SET MODEL' button
4. Click on 'Tab 2'

### Expected Behavior
The border gap for the text fields in 'Tab 2' and the 'v-show' card should fit the active label (see cards 'always visible' and 'v-if' for comparison)

### Actual Behavior
The gap is too narrow such that the border appears behind the label

### Reproduction Link
<a href="https://jsfiddle.net/r160uxpq/" target="_blank">https://jsfiddle.net/r160uxpq/</a>

### Other comments
* This affetcs only text fields that are rendered but hidden by CSS when the value is set ('Tab 2' and 'v-show')
* This doesn not affect text fields that are rendered and visible when the value is set ('always visible' card)
* This does not affect text fields that are not rendered when the value is set ('v-if' card)
* This also affects other outlined form elements (like v-select and v-textarea)

**Comment by haggys22** [comment] 2019-10-01 13:52
Related: #9156

**Comment by BjornLuG** [comment] 2019-10-02 03:41
Found the bug here.

https://github.com/vuetifyjs/vuetify/blob/98902556ef4a2652ee43b0a6b64c398a05317d3e/packages/vuetify/src/components/VTextField/VTextField.ts#L454

Apparently, measuring the size of a `display: none` element will always return 0, hence with the above formula's '+6', it only creates a 6px gap.

Ideas:
1. Before measuring the offsetWidth, check if visible, then calculate it, else watch for changes,
2. Clone the label, measure width, and delete.
3. Have an `opacity: 0` or `visibility: hidden` label, and measure from there.

From the above, no. 3 seems the simplest and non-hacky. But I'm curious to know if there's any other better implementation.

**Comment by haggys22** [comment] 2019-10-09 12:17
@BjornLuG I don't think no. 3 is a solution as `display: none` on any parent element takes precedence over `opacity: 0` or `visibility: hidden` on the label

IMO no. 1 is the best solution, e.g. by watching for `this.$refs.label.offsetParent` changes and calculating the width if `offsetParent !== null`

**Comment by BjornLuG** [comment] 2019-10-09 12:55
@haggys22 I actually meant like having a copy of the label in the root body, which is unaffected by the `display: none` and to measure from there. But now that I think of it, it's not quite a feasible solution after all. I take back what I said about non-hacky lol

No.1 seems like a good idea too,  but Vue can't watch DOM element's properties, so it would be hard to watch the value unless it's a`setInterval` function which is very inefficient.

No. 2 is probably the safest way to get the label properties, provided that it won't be called rapidly.

All 3 solutions seem to have its own caveat that I'm not sure Vuetify would sacrifice. Plus, they're few more other components doing something similar to this too, so I guess some refactoring is needed to fix this. Unless there's a better solution, it would be up to the maintainers to decide if it's worth to fix this bug.

**Comment by haggys22** [comment] 2019-10-10 11:17
I've found a clean (at least what I think) but yet (probably) unfeasible solution as it depends on the experimental [IntersectionObserver API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)

**Comment by BjornLuG** [comment] 2019-10-10 13:19
Yeah, the IntersectionObserver is probably the most straight forward solution here, but this would change Vuetify's currently [supported browsers](https://vuetifyjs.com/en/getting-started/quick-start#supported-browsersl).

I think it's cool to have this in and have it work with modern browsers. It'll won't be much of a big deal if the bug only happens on older browsers anyway.

Maybe add a check to see if IntersectionObserver is defined before calling it, so it'll won't log errors.

I'm still curious of what the maintainers think of this idea though, I think it's good for a PR.

**Comment by jacekkarczmarczyk** [comment] 2020-01-11 13:12
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9156

**Closed by jacekkarczmarczyk** 2020-01-11 13:12 UTC
Labels: C: VTextField, triage
