### ISSUE TITLE
[Bug Report] Autocomplete update:search-input event not working

### ISSUE THREAD

**Issue by kanteankit** [vuetifyjs/vuetify#6669] opened 2019-03-05 10:21 UTC
### Versions and Environment
**Vuetify:** 1.5.4
**Vue:** 2.6.8
**Browsers:** Chrome 72.0.3626.119
**OS:** Linux x86_64

### Steps to reproduce
In the attached codepen:
1) Type something in the autocomplete component
2) See the console for a message if the `update:search-input` event is fired.

### Expected Behavior
The event handler should be called

### Actual Behavior
The event handler is not called.

### Reproduction Link
<a href="https://codepen.io/anon/pen/eXdopJ?editors=1011" target="_blank">https://codepen.io/anon/pen/eXdopJ?editors=1011</a>

### Other comments
I saw this issue: https://github.com/vuetifyjs/vuetify/issues/5046, but, the solution provided there shows the use of `<script>` tag which won't happen in real world app.

**Comment by KaelWD** [comment] 2019-03-05 10:23
Duplicate of #5046

The event is camelCase, you can't listen to it in a HTML template.

**Closed by KaelWD** 2019-03-05 10:23 UTC
