### ISSUE TITLE
[Bug Report] VListItem with 'to' and 'inactive' gives error 'The .native modifier for v-on is only valid on components but it was used on <div>'

### ISSUE THREAD

**Issue by dzhamshed** [vuetifyjs/vuetify#10011] opened 2019-12-19 09:25 UTC
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Firefox 71.0
**OS:** Fedora undefined

### Steps to reproduce
Create a v-list-item with 'to' and 'inactive' attributes together. (Go to the codepen link)

### Expected Behavior
Work without errors.

### Actual Behavior
Gives error: The .native modifier for v-on is only valid on components but it was used on <div>

### Reproduction Link
<a href="https://codepen.io/dzhamshed/pen/qBERemg" target="_blank">https://codepen.io/dzhamshed/pen/qBERemg</a>

**Comment by KaelWD** [comment] 2019-12-19 09:48
Duplicate of #9999

**Closed by KaelWD** 2019-12-19 09:48 UTC
Labels: triage
