### ISSUE TITLE
[Bug Report][3.1.14] [v-combo] Placeholders no longer show up

### ISSUE THREAD

**Issue by Flamenco** [vuetifyjs/vuetify#17157] opened 2023-04-15 15:50 UTC
### Environment
**Vuetify Version:** 3.1.14
**Last working version:** 3.1.13
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
See reproduction

### Expected Behavior
Placeholders visible

### Actual Behavior
Placeholders missing

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUUtOwzAQvYrlTUCqbVDZULWonKPuIp8pMfgn2w2gKndnnKRSaFlUYueZN/M+492JvnrPuyPQFV0nMF6XCV6kJWTdsdL74TkUplR2qoa6dqZylfsiCLkG9EZSE98kJUhRQ+t0A2FTtKC1K4iHEFVMYBObwUSc6cWMPxej8lrMHGEZ66B8IhHSMcPKeBcSOZEAB9KTQ3CGFBilyMO1szERdEQ2Gb8rivtMOFLgMl3QcR+FPX+PzuIFTllfTkCUdEWGTu4hb64lbVPycSVE3Vhcw+CqC9xCEtYbscUxEY42KQOscWa75Ev+wErt25I/iwZvMIc5RMOq4D4jBCSTdDGTS+rwfYPkNIlKj/zxaZSYekyXVcwaV9wCBTsILIDFf4Bwa7SLtb/iXYxcRcwueml7/ACt7Ee8uH0dh7vvzmb/l31gy1T7rNgv6C/DaGHcpPsfclgGJw==)

### Other comments
Regression from previous release

**Comment by KaelWD** [comment] 2023-04-16 06:03
#17120, #4000

`''` is technically a value

**Comment by Flamenco** [comment] 2023-04-16 08:32
Perhaps, but in a combo, when the user clears the input, it is to be expected that the placeholder returns, otherwise it leaves an input with no context.  Also persistent-placeholder is set.

**Comment by KaelWD** [comment] 2023-11-27 12:40
Duplicate of #16372

**Closed by KaelWD** 2023-11-27 12:40 UTC
Labels: S: triage
