### ISSUE TITLE
[Bug Report][3.1.10] v-switch thumb blends with background (dark theme)

### ISSUE THREAD

**Issue by kappaflow** [vuetifyjs/vuetify#16929] opened 2023-03-16 18:23 UTC
### Environment
**Vuetify Version:** 3.1.10
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add v-switch on a dark theme

### Expected Behavior
The thumb should be visible and look according to Material Design Guidelines similar to thumb in Chrome (like incognito mode, Block 3rd party cookies switch)
![2023 03 16_incognito_thumb](https://user-images.githubusercontent.com/68439996/225716890-36f57151-64b7-4bf7-8056-6cabc07b6bea.PNG)

### Actual Behavior
The thumb is almost not distinguishable

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUttu2zAM/RVCL2mB2G53wYbMHbpv2LCXqg+qzSxaLFkQ5XRD4H8vdUnapmiB6sHWIY/OISnd7MVuwqDX/+u/JFZCGzf6AHvoPKqAv3MOZlj70cCicBfSSov/ErUbLQUoCbh6fvBsLy1A2KDBFaQ9QI9rNQ3hVw4ueuW3i2VMzfydz79JK5bih3M1a3JFLXVeu/A9MoplUTgKqqDg7PwAATyGydtHDECD7tGv4PLiIlnFNedNdE2gbY5ObUDjBm4jura93oHur6RQzkkRQzK0u4pRKooXI9og8jAGRcRMp6rPmcrcxKZ7HboNDOoOByb8TJApbXPIMTtxYyCKJRxRNmobriP9nxTHMBcNxD1n2rELHmO+zsoox9c7Wh5nGoosCZLieC0yPoSIpdiE4GjVNJN12z91N5rmmnONn2zQBqt+NNcf6w/1py9cEoWn8RrJVHd+vCf07ChFmXYSjw/iNYOSZt3L+muWLaGKR0ZR94VewyY79JVHy5eL/s3iT7jPGjjJvWiiPJCZBzpou6WTWXaU5nhzKO393SWFePw2usxLkatjv3RC3D4AH+A4/w==)

### Other comments
For a dark theme such colors make it look about right:
```
.v-switch__thumb {
  color: rgb(var(--v-theme-surface-variant)) !important;
}
.v-switch__track:not(.v-selection-control--dirty .v-switch__track) {
  background-color: rgb(var(--v-theme-surface-variant)) !important;
}
```

**Comment by KaelWD** [comment] 2023-03-23 13:33
Duplicate of #16363

**Closed by KaelWD** 2023-03-23 13:33 UTC
Labels: S: triage
