### ISSUE TITLE
[Bug Report] Dropdown with tooltip opens on top left of window

### ISSUE THREAD

**Issue by oanstein** [vuetifyjs/vuetify#9284] opened 2019-10-08 14:05 UTC
### Environment
**Vuetify Version:** 2.1.1
**Last working version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Mac OS 10.15

### Steps to reproduce
Click on menu with tooltip

### Expected Behavior
Opens menu below button

### Actual Behavior
Opens menu top left corner of window

### Reproduction Link
<a href="https://codepen.io/Lowryderch/pen/oNNgOBw?&editable=true&editors=101" target="_blank">https://codepen.io/Lowryderch/pen/oNNgOBw?&editable=true&editors=101</a>

**Comment by MajesticPotatoe** [comment] 2019-10-08 14:06
duplicate of #8846

**Closed by MajesticPotatoe** 2019-10-08 14:06 UTC
Labels: triage
