### ISSUE TITLE
[Bug Report] Undefined variable: "$chip-label-color".in /rails_project_path/node_modules/vuetify/dist/vuetify.min.css

### ISSUE THREAD

**Issue by somazx** [vuetifyjs/vuetify#2625] opened 2017-11-23 19:56 UTC
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.2
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.12.6

### Steps to reproduce
The link above doesn't actually recreate it. I apologize. However ...

I'm working with Rails 5.1 and have add the following lines to my vue.js file which is the central place to initialize vue in that environment.

```
import Vuetify from 'vuetify'
Vue.use(Vuetify)
import('vuetify/dist/vuetify.min.css')
```

which results in the following errors
      Undefined variable: "$chip-label-color".
      in /Users/andreaskoch/Code/safetyevolution/node_modules/vuetify/dist/vuetify.min.css (line 6, column 134917)
 @ ./~/vuetify/dist/vuetify.min.css 4:14-200
 @ ./app/javascript/packs/vue.js
 @ multi (webpack)-dev-server/client?http://safetyevolution.dev:8080 ./app/javascript/packs/vue.js

### Expected Behavior
webpack: Compiled successfully.

### Actual Behavior
webpack: Failed to compile.

### Reproduction Link
[https://codesandbox.io/s/6p91xxp7w](https://codesandbox.io/s/6p91xxp7w)

### Other comments
There is only one instance of dollar sign in that dist file (or the non minified version) ,"$chip-label-color". If I replace it with a valid css value, then webpack finished compiling.

Someone else has also raised he issue on stackoverflow https://stackoverflow.com/questions/47452077/how-to-configure-the-webpacker-to-work-with-stylus-so-i-can-use-vuetify

**Comment by jacekkarczmarczyk** [comment] 2017-11-23 20:11
duplicate of https://github.com/vuetifyjs/vuetify/issues/2623

**Closed by jacekkarczmarczyk** 2017-11-23 20:11 UTC
