### ISSUE TITLE
[Bug Report] [Bug Report] Button stays in hover state after being pressed on mobile 

### ISSUE THREAD

**Issue by Fr3027** [vuetifyjs/vuetify#9020] opened 2019-09-19 03:19 UTC
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Android

### Steps to reproduce
Press the regular button

### Expected Behavior
After pressing the button is done, it should have the same state/color as before pressing it.

### Actual Behavior
After the button was pressed, it stays in the hover state until I press somewhere else on the page

### Reproduction Link
<a href="https://codepen.io/fr3027/pen/aboRPYq?editors=1010" target="_blank">https://codepen.io/fr3027/pen/aboRPYq?editors=1010</a>

### Other comments
Following https://github.com/vuetifyjs/vuetify/issues/8572 , it has no problem on laptop now , but on Android device, it still has hover state after the button was pressed.

**Comment by Fr3027** [comment] 2019-09-19 03:24
![23D054B3-4E30-497B-85FF-2FFF5193503B](https://user-images.githubusercontent.com/38545119/65211057-009f3f80-dad0-11e9-9999-4057f049d3b1.png)
below are actual behavior.

**Comment by sh7dm** [comment] 2019-09-19 05:52
Duplicate of #8655

**Closed by sh7dm** 2019-09-19 05:52 UTC
Labels: triage
