### ISSUE TITLE
Data tables bug: "rows per page" dropdown is clipped

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#631] opened 2017-05-30 10:10 UTC
### Steps to reproduce

Check out the example with pagination controls:
https://vuetifyjs.com/components/data-tables

When trying to change the "Rows per page" dropdown, the menu is clipped and only partially visible. I don't remember this issue being present on Vuetify 0.11.

### Versions

Vue 2.3.3, Vuetify 0.12.2, latest Chrome on Win10

### What is expected ?
The dropdown menu should show regardless of its parent container.

### What is actually happening ?
The parent div `.table__overflow` sets `overflow-y: hidden` which I believe is causing the issue. 

### Reproduction Link
https://vuetifyjs.com/components/data-tables

**Comment by cawa-93** [comment] 2017-05-30 10:34
This issue has already been solved. See #585

**Comment by johnleider** [comment] 2017-05-30 12:19
Duplicate of https://github.com/vuetifyjs/vuetify/issues/585

**Closed by johnleider** 2017-05-30 12:19 UTC
Labels: duplicate
