### ISSUE TITLE
v-select autocomplete not hiding search input after loosing focus 

### ISSUE THREAD

**Issue by vizo** [vuetifyjs/vuetify#1966] opened 2017-09-30 11:53 UTC
### Versions
0.15

### What is expected ?
Invisible search input after selecting item with long text and after losing focus.

### What is actually happening ?
After loosing focus, search field is still visible under selected item.
It only happens if selected item have long text and if v-select is autocomplete, not single-line. 

### Reproduction Link
https://codepen.io/vizo/pen/EwXJJP

**Comment by johnleider** [comment] 2017-10-02 13:27
Duplicate of #1691

**Closed by johnleider** 2017-10-02 13:27 UTC
Labels: bug
