### ISSUE TITLE
[Bug Report][3.0.4] v-btn-toggle and v-tabs with default value are not displayed as active on pageload in Nuxt3

### ISSUE THREAD

**Issue by codeflorist** [vuetifyjs/vuetify#16252] opened 2022-12-09 14:55 UTC
### Environment
**Vuetify Version:** 3.0.4
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Linux

### Steps to reproduce
1. install nuxt3 and add vuetify according to https://github.com/vuetifyjs/vuetify/discussions/16024
2. set the following `app.vue`:
```
<template>
  <div>
    <v-btn-toggle v-model="toggle">
      <v-btn value="value1">value1</v-btn>
      <v-btn value="value2">value2</v-btn>
    </v-btn-toggle>
    <v-tabs v-model="tab">
      <v-tab value="tab1">tab1</v-tab>
      <v-tab value="tab2">tab2</v-tab>
    </v-tabs>
  </div>
</template>
<script>
export default {
  data: () => ({
    toggle: 'value2',
    tab: 'tab1',
  }),
};
</script>
```

### Expected Behavior
the `v-btn-toggle` element should have the `value2` button rendered as active. (it works, if `value1` is used as default.)

the `v-tabs` should have it's first tab active.

### Actual Behavior
the default values are not represented via active buttons.

### Reproduction Link
[https://stackblitz.com/edit/nuxt-starter-cettc4?file=app.vue](https://stackblitz.com/edit/nuxt-starter-cettc4?file=app.vue)

### Other comments
i was not able to reproduce this behaviour with a pure vue+vuetify+vite setup, so i assume it has something to do with Nuxt.

**Comment by yuwu9145** [comment] 2022-12-09 22:21
It works all good without nuxt: [vuetify playground sample link](https://play.vuetifyjs.com/#eNrFVMFSpDAQ/ZUuLmqVgLLuhcUpt/YzxEOAdoYdSFJJQKcs/307IUGYcWf35inJy8vr14+Qx7fop5TJOGCUR4XBXnbM4KbkAEXTjqDNocP7MpKsaVq+zSG7ka9l5AhE2d1uxrgyPDZiu+2wSAnwW3KzYyMdgZF1A94C09DgMxs6Ay9C7TW8tGYnBgNSiarDXhepDGeXmjDGvWiwIxMTcDuXD8ypBBGmUrQ/TYrUbZ9lZ4Gdrdl+5U18NBW0ls1ly+YUaho0tL5QBtVgjODAhYEK7SFWm3ZEEDyISbbFTrAmlP6/IKz1rwrCfXjDKvpqy09+lA7jhzkXpw2XXEDPjEEF7XO4GkL5qK7m9MwOgeSD3ifZzaEln6RmnS3zIqVVVgTM3dPcJmUH2yuNZ5g2JTusmX6lV+ko1rQi3ioxSAqiITv1Dut9JV7XmSVJwhS6n8I2WAulsDbdYdXQUuyjL4euO3MQdKxyhHAPTi+Gtey4/zhMDZ/ek+PD83py+GE7dDxr/vKAVZ3bCCyvHJbTK5TSM0SzIl08ToWuVSsNzfBVCmXmS/ZmjzTMsBwur+B+A5cOAfBPRw4XUwIX10s8C3g246wizN6JgLj+TnjBaw5GDejA9ysa3n9Yy95mdB21vfUZ90wmv7Xg9Ng6Y6Xf0GWUT+YtRq+xXZfRzhip8zQduNxvk1r06QPtpWrgpu0xbkT/8C3JkrvvFJI2SzxB3ceVEi8aFVUsI+/XiZv2+fC3An6bdG+Su0nWQ1byRCol/RFVrJA3qFCd9X3EXXk/2jvx75KlXCnLruV7fRRjrV2Ej0+W8n4dTdJEdn1ET38A+eA77A==)

**Comment by lioneaglesolutions** [comment] 2023-05-03 10:29
Seems like a Nuxt problem...

Wrap the `v-btn-toggle` in `ClientOnly` from Nuxt and it solves the issue. Not 100% sure why it works but seems to be the way with Nuxt...

@johnleider

**Comment by KaelWD** [comment] 2023-05-03 10:30
Duplicate of #15207

**Closed by KaelWD** 2023-05-03 10:30 UTC
