### ISSUE TITLE
[Bug Report] FAB in v-menu slot not positioned as expected

### ISSUE THREAD

**Issue by blalan** [vuetifyjs/vuetify#5189] opened 2018-09-28 19:59 UTC
### Versions and Environment
**Vuetify:** 1.2.5
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 7

### Steps to reproduce
add v-btn to v-menu activator slot with absolute bottom right fab props.

### Expected Behavior
The second example shows where the FAB "should be" (read is located when not in the slot but outside the v-menu altogether). Which then requires: a v-model, a click handler, attach prop, etc

### Actual Behavior
As you can see in the top example, the FAB is floating over the title while in the activator slot and not positioned to the bottom right of the toolbar.

### Reproduction Link
[https://codepen.io/anon/pen/vVEBzm](https://codepen.io/anon/pen/vVEBzm)

**Comment by SnakeyHips** [comment] 2018-10-04 08:11
Using "fixed right top" on the v-btn instead of "absolute right bottom" fixes it for me so see if that works?

**Comment by blalan** [comment] 2018-10-04 12:53
Updated codepen with this suggestion... It does appear better. However, its not perfectly aligned as the example below it... Might just have to be one of those things I say "Close enough" to.

**Comment by KaelWD** [comment] 2018-10-26 08:52
Duplicate of #3107

**Closed by KaelWD** 2018-10-26 08:52 UTC
