### ISSUE TITLE
'v-stepper-step' text color is too dark in 'v-app dark'

### ISSUE THREAD

**Issue by azaars** [vuetifyjs/vuetify#951] opened 2017-07-11 04:40 UTC
### Steps to reproduce

1. Copy `v-stepper` block of example **6 Vertical stepper** from Stepper Documentation
2. Paste within `v-app`.
3. Add `dark` props in `v-app`.

### Versions

0.13.1

### What is expected ?

The text color within `v-stepper-step` should have a much lighter tone to contrast with the dark background.
### What is actually happening ?

The text color within `v-stepper-step` stays black and the text color withing `small` stays dark grey.
### Reproduction Link

https://vuetifyjs.com/components/steppers

**Comment by johnleider** [comment] 2017-07-11 12:20
Stepper has not been themed yet for dark.

**Comment by nekosaur** [comment] 2017-07-19 15:07
Duplicate of #937

**Closed by nekosaur** 2017-07-19 15:07 UTC
Labels: duplicate, enhancement
