### ISSUE TITLE
[Bug Report] v-menu & v-tooltip for activator wrong position

### ISSUE THREAD

**Issue by yurriiy** [vuetifyjs/vuetify#9293] opened 2019-10-09 06:39 UTC
#8613 # Environment
**Vuetify Version:** 2.1.2
**Last working version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
The same problem can be seen in the documentation 
https://vuetifyjs.com/en/components/menus - Menu with activator and tooltip

### Expected Behavior
Correct menu display according to parameters

### Actual Behavior
Menu shows in left upper corner of screen
![test](https://user-images.githubusercontent.com/38867716/66457820-470a0d80-ea82-11e9-8141-f637ab671999.png)

### Reproduction Link
<a href="https://codepen.io/yurriiy/pen/vYYOxaR" target="_blank">https://codepen.io/yurriiy/pen/vYYOxaR</a>

**Comment by KaelWD** [comment] 2019-10-09 07:42
Duplicate of #8846

**Closed by KaelWD** 2019-10-09 07:42 UTC
Labels: T: bug, T: regression
