### ISSUE TITLE
[Bug Report] Combobox add 2 items when pressing enter on a search item

### ISSUE THREAD

**Issue by gotson** [vuetifyjs/vuetify#8841] opened 2019-09-04 03:18 UTC
### Environment
**Vuetify Version:** 2.0.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Android 9, Windows

### Steps to reproduce
- in the tags field, type `g`
- press the `arrow down` to select the first option `Gaming`
- press `enter`

### Expected Behavior
1 chip is added: `Gaming`

### Actual Behavior
2 chips are added: `Gaming` and `g`

### Reproduction Link
<a href="https://codepen.io/gotson/pen/GRKOoeb" target="_blank">https://codepen.io/gotson/pen/GRKOoeb</a>

**Comment by sh7dm** [comment] 2019-09-08 18:38
workaround: https://github.com/vuetifyjs/vuetify/issues/8842#issuecomment-528250028

**Comment by rcreynolds53** [comment] 2019-09-18 17:22
Work around does not work for autocomplete

**Comment by sh7dm** [comment] 2019-09-18 18:24
@rcreynolds53 could you provide a repro for that?

**Comment by rcreynolds53** [comment] 2019-09-18 20:22
@sh7dm 

So the steps I took to reproduce it 

- Create a v-menu with an activation slot 
- Put the v-autocomplete inside the content of the v-menu 
**- Set the v-autocomplete to attached = true** 
-press the arrow down to select an option
press enter

Observe that the event fires twice 

I was able to fix this by specifying that the :attached="False" on the v-autocomplete, now it only fires adds one of the items not two

**Comment by sh7dm** [comment] 2019-09-19 05:43
@rcreynolds53 please open an issue, this seems to be a new bug.

**Comment by Nico264** [comment] 2019-10-19 14:43
The workaround suggested in https://github.com/vuetifyjs/vuetify/issues/8842#issuecomment-528250028 stopped working starting for this with Vuetify 2.0.19 ([2.0.18](https://codepen.io/Nic264/pen/JjjbEwy) vs [2.0.19](https://codepen.io/Nic264/pen/QWWGdVe)).

The workaround still works for https://github.com/vuetifyjs/vuetify/issues/8842, but not for https://github.com/vuetifyjs/vuetify/issues/8841 anymore. The text field is still cleared, but too late, both input events already happened.

**Comment by lephuongbg** [comment] 2019-11-13 23:59
@sh7dm Please kindly remove `has workaround` label as it is no longer applied.

**Comment by haggys22** [comment] 2019-12-05 16:24
My findings for a real fix:

1. Type `g`, navigate to `Gaming` with arrow keys
2. Press `enter`
    * `VCombobox.onKeyDown()` (VCombobox:115)
    1. The selected option is selected (i.e. `Gaming`)
        * VCombobox:118: `VSelect.onKeyDown()`
        * VSelect:621: `VMenu.changeListIndex()`
        * VMenu:254: `VListItem.click()`
        * VListItem:126: `$emit('click')`
        * VSelectList:175 (`genTile()`, VSelectList:149): `$emit('select')`
        * VCombobox:158 (`selectItem("Gaming")`, VCombobox:153): `VAutocomplete.selectItem("Gaming")`
        * VAutocomplete:347: `VSelect.selectItem("Gaming")`
        * VSelect:756: `VCombobox.setValue(["Gaming"])`
        * VCombobox:171: `VSelect.setValue(["Gaming"])`
        * VSelect:808: `this.internalValue = ["Gaming"]`
    2. At this point: `internalValue = ["Gaming"]`, `searchValue = "g"`, `internalSearch = "g"`, but `selectedItems = []` and the input field still displays only `g`
        * VCombobox:128: `VCombobox.onEnterDown()`
        * VCombobox:104: `$nextTick()`
    3. At this point: `internalValue = ["Gaming"]`, `searchValue = "g"`, `internalSearch = "g"`, `selectedItems = ["Gaming"]` and the input field displays the `Gaming` chip and `g`
        * VComboBox:107: `VCombobox.updateSelf()`
        * VCombobox:197: `VCombobox.updateTags()`
    4. **Here the bad things start to happen** (as `internalSearch = "g"`)
        * VCombobox:229: `VCombobox.selectItem("g")`
        * VCombobox:158: `VAutocomplete.selectItem("g")`
        * VAutocomplete:347: `VSelect.selectItem("g")`
        * VSelect:756: `VCombobox.setValue(["Gaming", "g"])`
        * VCombobox:171: `VSelect.setValue(["Gaming", "g"])`
        * VSelect:808: `this.internalValue = ["Gaming", "g"]`

As soon as I find a proper way of resetting the `searchValue`/`internalSearch` without breaking anything I will create another PR

**Comment by haggys22** [comment] 2019-12-05 17:09
I've found a solution to restore the behavior of vuetify 1.5.18 (see this fiddle: https://jsfiddle.net/wqb0cj28/), where after pressing `enter` only the selected menu item was added as a chip, but the search value was not cleared.

The workaround by manually resetting the search value also worked back then: https://jsfiddle.net/d90mpot2/

If this behavior is close enough to a fix i will create a PR tomorrow, otherwise I will further look for a solution which also resets the search value

PS: Opinions of @johnleider @nekosaur @sh7dm @jacekkarczmarczyk @MajesticPotatoe on this are very appreciated

**Comment by johnleider** [comment] 2020-01-16 01:00
Duplicate of #6697

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-16 01:00 UTC
Labels: C: VCombobox, T: bug
