### ISSUE TITLE
[Bug Report][2.6.0-beta.0] VCalendar retains 7 columns in "week" view regardless of number of "weekdays"

### ISSUE THREAD

**Issue by pumpknhd** [vuetifyjs/vuetify#14389] opened 2021-11-06 16:55 UTC
### Environment
**Vuetify Version:** 2.6.0-beta.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 95.0.4638.69
**OS:** Windows 10

### Steps to reproduce
Select Week view. Then select Mon-Fri. 

### Expected Behavior
I expect to see only 5 days

### Actual Behavior
You get 7 days (with Mon & Tues) repeated on the right side.

### Reproduction Link
<a href="https://codepen.io/pumpknhd/pen/VwzXrzv" target="_blank">https://codepen.io/pumpknhd/pen/VwzXrzv</a>

### Other comments
Reference Issue #10440

**Comment by KaelWD** [comment] 2021-11-07 09:12
You can use `type="custom-weekly"` with the `start` and `end` props to specify the visible range.

**Comment by pumpknhd** [comment] 2021-11-07 17:07
Thank you. Workaround isn't great because it removes the .next() and .prev() ability.

**Comment by boobo94** [comment] 2022-03-12 13:11
Is happening for me too.

Codepen from documentation - https://vuetifyjs.com/en/components/calendars/#usage

## How to reproduce

type: week
weekdays: Mon - Fri

It shows the columns: Mon,Tue,Wed,Thu,Fri[,Mon,Tue], last 2 shouldn't be there.

It looks that here we have added `v-calendar-daily_head-day v-future` and `v-calendar-daily__day v-future`, but all the rest (the good ones) have the class `v-past`.

**Comment by KaelWD** [comment] 2022-03-13 14:31
This must be caused by a browser bug or something, I can't reproduce it anymore with chrome/firefox 98

**Comment by boobo94** [comment] 2022-03-13 16:15
> This must be caused by a browser bug or something, I can't reproduce it anymore with chrome/firefox 98

Tested on Mac 

- Firefox 98.0 (64-bit)
- Safari Version 15.3 (17612.4.9.1.8)
- Chrome Version 99.0.4844.51 (Official Build) (x86_64)

Tested on Safari mobile and chrome android.

Attaching a picture
<img width="1784" alt="Screen Shot 2022-03-13 at 18 14 09" src="https://user-images.githubusercontent.com/16722674/158068767-58e546cc-8306-4603-a02b-8b9e5db89c94.png">

**Comment by KaelWD** [comment] 2022-03-13 16:33
I tested
- Linux (Kubuntu 20.04, Kernel 5.4.0-100):
  - Chrome 98.0.4758.102
  - Firefox 98.02
  - GNOME Web 41.3 (WebKitGTK 2.34.5)
- Android 7.0 (MIUI 10.2):
  - Chrome 99.0.4844.58
  - Firefox 98.1.1
- MacOS (browserstack):
  - Chrome 99.0.4844.51
  - Safari 15.3
  - Safari 14.1
  - Safari 13.1
  - Safari 12.1
iPhone 13 (browserstack):
  - Safari 15.3

GNOME Web and iOS Safari show 7 days, everything else was fine.

**Comment by boobo94** [comment] 2022-03-13 17:29
> I tested
> 
>     * Linux (Kubuntu 20.04, Kernel 5.4.0-100):
>       
>       * Chrome 98.0.4758.102
>       * Firefox 98.02
>       * GNOME Web 41.3 (WebKitGTK 2.34.5)
> 
>     * Android 7.0 (MIUI 10.2):
>       
>       * Chrome 99.0.4844.58
>       * Firefox 98.1.1
> 
>     * MacOS (browserstack):
>       
>       * Chrome 99.0.4844.51
>       * Safari 15.3
>       * Safari 14.1
>       * Safari 13.1
>       * Safari 12.1
> 
>     * iPhone 13 (browserstack):
>       
>       * Safari 15.3
> 
> 
> GNOME Web and iOS Safari show 7 days, everything else was fine.

That's interesting.

And you tried with `type = week` and `weekdays = Mon - Fri`? Is strange that if I switch `type=month` it works perfect.

**Comment by KaelWD** [comment] 2022-03-14 05:08
Just checked again and it now shows 5 days on everything, so it could be timezone related. It was monday morning here but sunday evening UTC before, now it's monday for both.

**Comment by boobo94** [comment] 2022-03-14 07:51
> Just checked again and it now shows 5 days on everything, so it could be timezone related. It was monday morning here but sunday evening UTC before, now it's monday for both.

I think you're right.

I tried again today 14.03.2022 07:47 UTC and all works perfectly (only Monday-Friday displayed), then changed the date-time of my computer to 13.03.2022 7:47 UTC and the problem appears (shows Monday-Friday, Monday, Tuesday).

So as a conclusion I think the problem happens when weekdays=[1,2,3,4,5] and the current day is Saturday(6) or Sunday(0).

**Comment by boobo94** [comment] 2022-11-09 15:48
Hi. Do you have any suggestions or any dirty fix for this?

**Closed** 2023-09-20 19:15 UTC
Labels: T: bug, C: VCalendar, has workaround

**Comment by abierbaum** [comment] 2024-01-06 14:03
Did anyone ever find a workaround for this besides hiding columns with CSS?
