### ISSUE TITLE
v-select autocomplete with object items

### ISSUE THREAD

**Issue by thoss** [vuetifyjs/vuetify#1922] opened 2017-09-28 06:46 UTC
### Steps to reproduce
Open the select box, select an item and reopen the select again

### Versions
Vue: latest,
Vuetify: latest,
OS: Windows 10,
browsers: Only chrome tested

### What is expected ?
After selecting an item and reopen the select box I would expect to see all Items

### What is actually happening ?
After reopen the select box I only see the selected one, the autocomplete term is evaluated immediately

### Reproduction Link
[https://codepen.io/anon/pen/qPmrpr](https://codepen.io/anon/pen/qPmrpr)

**Comment by KaelWD** [comment] 2017-09-28 06:54
Duplicate of #1890

**Closed by KaelWD** 2017-09-28 06:54 UTC
Labels: bug, duplicate
