### ISSUE TITLE
[Bug Report][3.1.5] Tooltips in safari throws "ReferenceError: Can't find variable: cancelIdleCallback"

### ISSUE THREAD

**Issue by Martin-N** [vuetifyjs/vuetify#16720] opened 2023-02-20 09:27 UTC
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.2.47
**Browsers:** Safari 16.2
**OS:** Mac OS 10.15.7

### Steps to reproduce
In safari hover over tooltip activator then leave to dismiss tooltip

### Expected Behavior
No errors

### Actual Behavior
Get "ReferenceError: Can't find variable: cancelIdleCallback" error.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUctugzAQ/BXLl1wCVl+qFNEq/Yfe4hwImNSJX7IXmgrx710bUpFErVRxYXdnZ2bHm56+OZd3raArWoDQTpUgXrkhpOiy0rn0mwpdSkMqVYbwwmmdNUqcyKENIJuvrBIGhCelkntzLiIgq6xqteF0oklEYK0C6QiIEyDV+1jOMIg6OyFdFpSFVVmB7EqwHhd64rx1gQwXK4l6BwY3dtLUiEsoxEwCBUvzuQqbHcwhfhE0+fsBTgngJEYwZoPFGM4lhylC5aUDEgS0cSy1sx5IT7xoyEAabzVZYNqLuDliEUWXdASigssPwRp8jT4K8WmAd6xI6sQeEsSa0w8AF1aMtcYd93llNVvjjPnWgNQiq61eP+T3+eMzq2WAeT8XQWc7bz+D8KjI6XJGHt/0N4FpjLx3+dNIO7Ui5Q0VQ/5O+MwLUwsv/J++r7AX3q9mN/6j5sDNgFkqaY7hKsYqpAg3Z2v/OkxLkyeCuL2NIsOSjuZQLi3Q7TfllxhV)

### Other comments
The error causes the rest of the app to stop working. For example, navigation stops working. This only happens in safari.

**Comment by KaelWD** [comment] 2023-02-20 09:28
Duplicate of #16613

**Closed by KaelWD** 2023-02-20 09:28 UTC
Labels: S: triage
