### ISSUE TITLE
[Bug Report] Clearable V-Text-Field turns its v-model to null when clear icon is clicked, which can cause errors. An empty string would be better

### ISSUE THREAD

**Issue by cooperfrench95** [vuetifyjs/vuetify#11474] opened 2020-05-25 06:50 UTC
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
The `clearable` version, which turns `searchValue` to `null`:

```html
<v-text-field
        v-model="searchValue"
        clearable
      />
```

### Expected Behavior
Clicking 'clear' will turn the v-model to an empty string.

### Actual Behavior
Clicking the clear icon turns the v-model to null.

### Other comments
The following turns the v-model to an empty string, which is a lot better if you're for example doing something like `this.searchValue.toLowerCase()`

```html
<v-text-field
        v-model="searchValue"
        append-icon="close"
        @click:append="searchValue = ''"
      />
```

**Comment by KaelWD** [comment] 2020-05-25 07:10
Duplicate of #4144

**Closed by KaelWD** 2020-05-25 07:10 UTC
Labels: triage

**Comment by akowald** [comment] 2023-05-09 21:22
This fix got regressed, so the bug is still open. See link below for the offending line of code. A workaround is to reset the value when the `@click:clear` event is emitted.

https://github.com/vuetifyjs/vuetify/blob/9cff4ed1a5efd6e3ab14a1201ff59ec95e9f8a0b/packages/vuetify/src/components/VTextField/VTextField.tsx#L129
