### ISSUE TITLE
[Feature Request] Support for `<inertia-link>`

### ISSUE THREAD

**Issue by ThaDaVos** [vuetifyjs/vuetify#15291] opened 2022-06-14 14:08 UTC
### Problem to solve
I am using a Laravel Jetstream stack with Vuetify 3 and Vue 3 - sadly when I use the `v-btn` it reloads the whole webpage instead of using the nicely provided progressbar and acting like a spa. I also noticed in the docs of `v-btn` that there is no mention of `nuxt` prop - so I am curious - is it possible to implement this again in Vuetify 3 and also include support for InertiaJs?

This one misses now according to the docs: https://vuetifyjs.com/en/api/v-btn/#props-nuxt

Also see the old issue: https://github.com/vuetifyjs/vuetify/issues/11573

### Proposed solution
Re-introduce the props for setting special types of links, or at least introduce a way for the user/developer to make it compatible with whatever link type possible (preferably globally so it only has to be setup once.

Something like one of these two:

1. `<v-btn inertia href="/some/path">Go here</v-btn>`
2. See below:
```Typescript
createVuetify({
  linkResolver: (props, { slots, emit, attrs }) => /** Render function like system to render the correct component */
});
```
and then just use  `<v-btn link href="/some/path">Go Here</v-btn>`

**Comment by martinEtflais** [comment] 2022-06-14 15:36
Why dont you just wrap the v-btn with Link from Inertia?

**Comment by KaelWD** [comment] 2022-08-01 10:03
Duplicate of #11573

**Closed by KaelWD** 2022-08-01 10:03 UTC
Labels: S: triage
