### ISSUE TITLE
[Bug Report][3.6.14] The v-chip closes on the v-for reactive when the id is updated, removing two follower items

### ISSUE THREAD

**Issue by Roi467** [vuetifyjs/vuetify#20288] opened 2024-08-06 09:39 UTC
### Environment
**Vuetify Version:** 3.6.14
**Vue Version:** 3.5.0-alpha.5
**Browsers:** Chrome 127.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
I have created two arrays
The first uses the v-chip and the second uses a span tag
Clicking on closable should remove the item / same for span 

### Expected Behavior
Only one v-chip element needs to be removed

### Actual Behavior
With the updated key, it removes the follower element

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9kttqhDAQhl9lkAVX8EBvxS3tO/RuXdhsHGnYqCGJ0hJ8947GrL0qhUJvdGb85vA7c3aR0bx4VSqfRozKqLLYKcksPtc9QDVlTKnVXB3+LpR3AKasHfSpjo6MWzFhCqL5SED0sEBvaGwdBbS84yeR14Pz7JwdHNHzdUcmpgXrLVHDaKXosdm/cTkYdpMY/BcuBb+XSxgpIfTLjaI4HqlyCk9JyN+mB3AOfHuYZygXl0iyN3WFl0f4FjCKbeYPYhfoH8TmSuOEa0ro+Fe5Sx2/ZFLut1wV37ZPruFaKAsG7eiPQHRq0BYcaAy1odVDBzFdT+z/HB96Yx9HAKcHezzH7MbjFMKrwTa+JHtOUPabHJp/HY7Giua0H6VcH5cvxBLnDQ==)

**Comment by Miltonbhowmick** [comment] 2024-08-06 12:48
Hey @Roi467,
It is solved by using one common deletion function for both `span` & `v-chip`.

```
const handleDeletion = idx => {
    chipTest.value.splice(idx, 1)
    spanTest.value.splice(idx, 1)
  }
  ```
  
  One thing i have changed that i have used `ref` instead of `reactive`. `ref` is easy to maintain any type of values.

**Comment by Roi467** [comment] 2024-08-06 15:49
Hey @Miltonbhowmick 
 The span is only to display the issue
 
 I mean when you remove the item with key: abc-0 it splices it correctly but on the view it removes the following chip as well
 but if you remove the abc-1 it's fine
 and it happens only when they are following each other and the new key is the same as removed since the VUE updated the view

**Comment by b-maslennikov** [comment] 2024-08-12 13:11
sounds like a bug. but anyway... why you do this? just remove @click.close prop and it will work as expected

**Comment by b-maslennikov** [comment] 2024-08-12 13:15
`@click:close` does not override the original close handler. it's provides you and ability to do something additional. just remove it and it will work. or use slots to add your own button with your own logic.

[playground](https://play.vuetifyjs.com/#eNq1kk1ugzAQha8yQpEIEj/qFpGqvUN3IVIcM6hWDFi2Qa0s7t4B49BVlU03MIO/ebzhcXaR0bx4VyqfRozKqLLYKcksvtY9QDVlTKm1XBv+KZRvAKasHfSpjo6MWzFhCqL5SkD0sEAfaGwdBbS84zeR14Pz7JwdHNHzdUcmpgXrLVHDaKXosdnPuBwMu0n0/eYGwDnwcjDPUC4taVK9uS28XcK3B0axrfzD/AL9o3mANy4Fv+dK44TrSHhjbhSd4JG0U3hJgsLT6y46PjTa3KdWFb/SpNZwLZQFg3b0oYpODdqCA41BG1o9dBDT3xD7L8eH3thHqHB6sMdzzG48TiHcGmzjS7LPhM2emSH/qzmyFc1pP0q5Xi4/+KHXrw==)

**Comment by KaelWD** [comment] 2024-08-16 09:24
Duplicate of #16364

**Closed by KaelWD** 2024-08-16 09:24 UTC
Labels: S: triage

**Comment by hanamurayuki** [comment] 2025-09-19 09:25
It works using
```
<v-chip
  v-for="(value, key, index) in filterParams"
  closable
  :key="key"
  @click:close="clearFilter(key)"
>
```
instead of
```
<v-chip
  v-for="(value, key, index) in filterParams"
  closable
  :key="index"
  @click:close="clearFilter(key)"
>
```
