### ISSUE TITLE
[Bug Report] [Bug Report] Making boxes readonly will not prevent deleting if clearable is true

### ISSUE THREAD

**Issue by mrksoftware** [vuetifyjs/vuetify#9760] opened 2019-11-22 08:29 UTC
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Add readonly and clearable props

### Expected Behavior
Selected value is not deleted when pressing on the X (clearable)

### Actual Behavior
The selected value is deleted.

### Reproduction Link
<a href="https://codepen.io/mrksoftware/pen/oNNOzoE" target="_blank">https://codepen.io/mrksoftware/pen/oNNOzoE</a>

**Comment by mrksoftware** [comment] 2019-11-22 08:29
Related to #8867

**Comment by KaelWD** [comment] 2019-12-02 13:24
Duplicate of #7111

**Closed by KaelWD** 2019-12-02 13:24 UTC
Labels: C: VAutocomplete, C: VCombobox, duplicate
