### ISSUE TITLE
[Performance] Datepicker re-renders when another input change

### ISSUE THREAD

**Issue by Aterbonus** [vuetifyjs/vuetify#2305] opened 2017-10-24 02:33 UTC
There is a performance issue with the datepickers. A similar issue occurs with [v-select](https://github.com/vuetifyjs/vuetify/issues/2080).

![screenshot_20171023_232706](https://user-images.githubusercontent.com/15003767/31922260-5cd98abc-b84a-11e7-8c3c-374893cb238e.png)
### Steps to reproduce
Open the datepickers dialogs, select a date for each one and type in the text field.

### Versions
Vue: 2.5.2
Vuetify: 0.16.9
Chrome 61.0.3163.100

### What is expected ?
Datepicker shouldn't be re-rendered.

### What is actually happening ?
Datepicker is re-rendered. Typing in other inputs is slowed.

### Reproduction Link
[Codepen](https://codepen.io/Aterbonus/pen/aLrRpV)

**Comment by jacekkarczmarczyk** [comment] 2017-10-24 07:41
Simplified codepen https://codepen.io/anon/pen/VMONQz

**Comment by KaelWD** [comment] 2017-10-24 12:42
Until this is fixed in Vue, it might be possible to mitigate this problem by using `Intl.DateTimeFormat` as [recommended by MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString#Performance). 
`dateGenButtonText ()` is currently very slow as it calls `toLocaleDateString` ~30 times each render cycle.

**Comment by johnleider** [comment] 2017-11-12 23:59
I realize this was re-opened because one of the performance fixes that @jacekkarczmarczyk implemented did not go live with his initial pull request. With that being said, I reproduced your scenario but with 100 instead of 6 `v-date-picker`'s. With 6x CPU Throttling, it only had a very minimal delay.

There is always room for improvement, but I would consider more than 100 v-date-pickers to be a large outlier. Keep in mind, this was done on 0.17 branch.

**Closed by johnleider** 2017-11-12 23:59 UTC
Labels: pending review
