### ISSUE TITLE
[Feature Request] export validatable  mixin for use in custom form input component

### ISSUE THREAD

**Issue by klmdb** [vuetifyjs/vuetify#7325] opened 2019-05-29 12:06 UTC
### Problem to solve
I am trying to integrate a custom component meant to be used in a v-form and I would like to be able to use it in the same way that I would expect to use other form components. Specifically to be able to use validation rules and the 'required' attribute.

### Proposed solution
export the mixins on the global vuetify object

**Comment by KaelWD** [comment] 2019-06-11 07:15
Duplicate of #3464

**Closed by KaelWD** 2019-06-11 07:15 UTC
Labels: C: VForm, T: enhancement, T: feature

**Comment by klmdb** [comment] 2019-07-11 07:29
This ticket is closed, but the issue is not resolved at all.

The linked issue proposes a way to deal with the example I provided, yes. What I request in this post, however, is to provide a different - imo better - solution: export the mixins that vuetify uses internally so that we can use them to create custom components that can hook into existing vuetify behavior.

This way we wouldn't need to re-implement the validatable mixin (or all the other form-related input features), but can instead apply the existing mixins.

**Comment by KaelWD** [comment] 2019-07-11 08:11
You can import them if you want to, it's all available on npm. We don't want to recommend that people do this though as it means any change to what should be a private api could break other projects.

**Comment by pikilon** [comment] 2020-06-11 15:01
@klmdb  I used a workaround  that might be useful, I add a hidden field next to the component (maybe you can implement it inside)

```html
  <v-time-picker v-model="time" format="24hr" :disabled="!day" />
  <v-text-field v-model="time" :rules="rules.time" type="hidden" />
```
