### ISSUE TITLE
[Bug Report] Calendar drag-and-drop

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#11616] opened 2020-06-12 12:35 UTC
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Firefox 77.0
**OS:** Windows 10

### Steps to reproduce
1. Open the link
2. Try to drag an event from one day to another.
3. Realise this will only work if you grab the title, if you grab the body of the event, i.e. the part that is just colour, it will only be draggable vertically within the same day but not across days.

### Expected Behavior
Drag an event everywhere wherever you grab it.

### Actual Behavior
Cannot be dragged to another day if grabbed by the event body

### Reproduction Link
<a href="https://codepen.io/auspex/pen/xxZVadq?editable=true&editors=111%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fcalendars%2F&__cf_chl_jschl_tk__=17ce2bfa35fad9178579060025f664e85ba57b4b-1591965049-0-AeqAP_DrxotXCVSFDg4CbR6NqoXiHKxX4Cn9XPjqRcH-H4QPPbFpUOaaE_1Cw8YT4F0BZC0mDHCkU6YRYXRae0IcW0w1sHnuQ4aYjHUhc77GxHc2c3-vF4YlibAqggN0AQGs6XHJPqImPtJuSez0RM2OT4shwbS_aNxQgW-OLdlCTvP0FU4VLHYrJlLyK_Pm0vz15Sqp9sJnVCIHorqXnNCp5972f_Oue-1R7U3SfN1sg_zlkCGBjXqpuYY1I_5QBQnkvqvYmPYK8_-uShw3PzpZ-fEk8-7OgrujV2azDGm5WO_WbUagLO1aEtr0Hz9LKiHU_ydKQlc-AZOorhCFtvxYdiOul3UaDYr6RSraAao8yAmzZclzILW3VmkiJrJkyq8g3Mi9KVneIJN4zO31nelf8nmS0_9hAfU1FC5OiyEHjGacAiVWadChMCrzQqEo_29gf1Lm6Slgyt1tLmN-39p2Yck0ihg610ruZhaXGdJEMZr0hk1PlFEmTXI7NcWoWWMbGw6PLmtHzQqztB2aUu431LBXS5z69W6h06fZNX71" target="_blank">https://codepen.io/auspex/pen/xxZVadq?editable=true&editors=111%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fcalendars%2F&__cf_chl_jschl_tk__=17ce2bfa35fad9178579060025f664e85ba57b4b-1591965049-0-AeqAP_DrxotXCVSFDg4CbR6NqoXiHKxX4Cn9XPjqRcH-H4QPPbFpUOaaE_1Cw8YT4F0BZC0mDHCkU6YRYXRae0IcW0w1sHnuQ4aYjHUhc77GxHc2c3-vF4YlibAqggN0AQGs6XHJPqImPtJuSez0RM2OT4shwbS_aNxQgW-OLdlCTvP0FU4VLHYrJlLyK_Pm0vz15Sqp9sJnVCIHorqXnNCp5972f_Oue-1R7U3SfN1sg_zlkCGBjXqpuYY1I_5QBQnkvqvYmPYK8_-uShw3PzpZ-fEk8-7OgrujV2azDGm5WO_WbUagLO1aEtr0Hz9LKiHU_ydKQlc-AZOorhCFtvxYdiOul3UaDYr6RSraAao8yAmzZclzILW3VmkiJrJkyq8g3Mi9KVneIJN4zO31nelf8nmS0_9hAfU1FC5OiyEHjGacAiVWadChMCrzQqEo_29gf1Lm6Slgyt1tLmN-39p2Yck0ihg610ruZhaXGdJEMZr0hk1PlFEmTXI7NcWoWWMbGw6PLmtHzQqztB2aUu431LBXS5z69W6h06fZNX71</a>

### Other comments
Seems like .v-event-draggable can do horizontal drags but the body of the event element cannot.

**Comment by johnleider** [comment] 2020-06-13 01:00
Is this an example from the docs or something? We haven't committed to drag and drop functionality in the framework as far as I'm aware. @ClickerMonkey will have to chime in

**Comment by AuspeXeu** [comment] 2020-06-13 15:39
It's from the docs directly, yes. I just played around there.

**Comment by ClickerMonkey** [comment] 2020-06-15 15:35
Looks like a firefox specific issue, will look into it further.

**Comment by ClickerMonkey** [comment] 2020-06-15 16:00
The example will have to be updated. This CSS can change to the following:

```css
.v-event-draggable {
user-select: none;
-webkit-user-select: none;  
padding-left: 6px;
}
```

to

```css
.v-event-draggable {
padding-left: 6px;
}
.v-event-timed {
user-select: none;
-webkit-user-select: none;  
}
```

That's some odd FF behavior!

**Closed** 2020-06-16 00:05 UTC
Labels: C: VCalendar, T: documentation

**Comment by d-damien** [comment] 2021-10-04 19:32
Looks like it's back (Firefox 92, but it's been there a while). Has Vuetify automated tests on Firefox ?

**Comment by johnleider** [comment] 2021-10-06 02:46
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
