### ISSUE TITLE
[Bug Report][3.4.9] V-Calendar: Dark theme on week view-mode doesnt render

### ISSUE THREAD

**Issue by MauricioRodolfo** [vuetifyjs/vuetify#18988] opened 2024-01-05 21:41 UTC
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.5
**Browsers:** Edge 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
- Set theme to dark
- set view-mode to week

### Expected Behavior
Apply theme correctly

### Actual Behavior
Theme doesnt apply and everything is white

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNk91ugkAQhV9lsjdoIoqISSXYpEnjC9SrihcURyUFdrM74oXx3TuAf61iSUh2OXuY802YXRyE0fHgTal+sUPhi4AwU2lE+BrmAEFhR0oBbTHDaShWkf4ORXVSncUypyjJUZ+kWoxSzNkJhZ3JFab8XWY2oYAiwX0lsbJH5ErgY4E5GRbqDRcPBtcS56RS+hVVKgzG+2BwA8yvJtaJIjBIu/IYIMmU1AQH0LiGI6y1zMDiXq3SDsB1DUGdDlNY1ImHcz+UUIo+WLNEG7J6Z9lQpMmHHPfwztEdy3Vcz3aGtuvOHdd3HH4+re7Fz900uT1/9Ncdy1RqDv1KGfOkHk/rHdkHcgurNmijuTO+D2tCY/dLM5rGS2Qj2Xyb6LZgD6KegE2awTYaMf8XbSZ3mrZt2Lzqfw5bsrHbu3c/YVveTiFfEx5BntPO4mHfw+usLLvl6NfDzmMujj0x6nv9sajXiVj+AAR6FJE=)

### Other comments
Dark Theme works only on month and day view modes

**Comment by SunnyNagam** [comment] 2024-05-02 19:19
Hey I see this bug was fixed with a merge 2 weeks ago and releases in 3.5.18, when I install that version the bug is fixed as expected. But when I install the latest version (3.6.3 currently) the fix is gone again and the issue is still here, was the fix reverted or undone for some reason?

**Closed** 2024-05-07 16:13 UTC
Labels: T: bug, C: VCalendar
