### ISSUE TITLE
[Bug Report]Here is a mistake in vtreeview

### ISSUE THREAD

**Issue by murfey-sea** [vuetifyjs/vuetify#5840] opened 2018-12-07 01:00 UTC
en. this is very important. i give some items to vtreeview, and the type of item.id is String, you should return a String value ,  should not return a Number value.
https://codepen.io/murfey-sea/pen/bmxvvL
backend, item.id generate by SnowFlake, then convert Long to String for compatible with js, should i change SnowFlake algorithm? or, should i change ui component?

**Comment by jacekkarczmarczyk** [comment] 2018-12-07 01:54
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5711

**Closed by jacekkarczmarczyk** 2018-12-07 01:54 UTC
