### ISSUE TITLE
[Bug Report][3.4.10] The absence of the @submit event when in the VForm present  VSelect  and pressing Enter when focusing on the VTextField.

### ISSUE THREAD

**Issue by lna1989** [vuetifyjs/vuetify#19060] opened 2024-01-17 14:32 UTC
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.4.14
**Browsers:** Yandex 23.9.1.1077, Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
1.) Click on the link to reproduction and turn on DevTools
2.) Switch the focus to the first field with "Hello world!"
3.) Press "Enter" on the keyboard
4.) Make sure that there is no "onSubmit" message in the console (but it should be)
5.) Switch the focus to the second field with "Hello world!"
6.) Press "Enter" on the keyboard
7.) Make sure that there is "onSubmit" message in the console

### Expected Behavior
The "submit" event should always be triggered when pressing "Enter" under standard conditions of use, as with native forms.

### Actual Behavior
The "submit" event does not occur

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUrFu2zAQ/ZVXLnIAWaobT4EdtAVaNEOnDh2iDLJ0sohSJEFSRgLD/96jZFsy2i0b7+7d471393wU3lX5F2uzQ0/iQWwCdVaVgR4LDWwOy9La4TkEldGhlJrcOTUkG+M6fPb9rpMhs44OpMO2EEb/GlKFuIIZrmhPup5lgKcGoSUMNG3p4UlRFVIEeg3fJakaUnO16j1KXYN/8B6F+KYDuULA6Ng+J/xDbztTujrFE+jVMhmCYVrirmmqyBr/ZU3eKEqx6xnXSo/akIc2Yc7Zsg+kZ0Lyf5SwFePoOCw7U5NiE8bEzxjxjw+S3fWcfl6ln9L7dP3CyfyWIqpeNoPsieZqxYVpatrk4wbeu5GvrF42Z/PBLnTSe6n3vIeWNJjDvbE7eh9rDd9A9n8L3jl/DG+vLGbGI9zks+Pk0FdO2sAjh368UdlZ4wKOcNTghMaZDgnfdRLhGDYd4deVYIvVVLgdkmvMskh+kFIGv41T9YfkbkJfzGTc4g7bRxxHAedzypTZL5ILaGw8RQnj0DyuOKXiPltnq7U4Pz6Kl78LByJt)

**Comment by KaelWD** [comment] 2024-01-19 10:41
Duplicate of #2159

**Closed by KaelWD** 2024-01-19 10:41 UTC
Labels: S: triage
