### ISSUE TITLE
[Feature Request] Can we add a functional global message prompt component?

### ISSUE THREAD

**Issue by UnforgetMemory** [vuetifyjs/vuetify#18168] opened 2023-08-29 10:06 UTC
### Problem to solve
I think the message component developed by ElementPuls developers is quite good, with external interface calls and duplicate message merging. I think this will be convenient for many novice developers with similar ideas to avoid duplicate wheel building. (Although V-snackbar can be used as a roundabout wrapper call)
我觉得ElementPuls开发者们做的message组件就不错，还具有外部接口调用和重复消息合并，我想这个会方便很多有类似想法的菜鸟开发者们，避免重复造轮子。（虽然可以使用v-snackbar迂回式的包装调用）

### Proposed solution
like ElementPlus or Ant-Design-Vue

**Comment by KaelWD** [comment] 2023-08-29 10:09
Duplicate of #2384

**Closed by KaelWD** 2023-08-29 10:09 UTC
Labels: S: triage
