### ISSUE TITLE
[Bug Report] Tab selection indicator is not positioned correctly if parent is initially hidden

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#3302] opened 2018-02-16 13:57 UTC
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132, Google Chrome
**OS:** Mac OS 10.13.3

### Steps to reproduce
Open the dialog using the provided button. See the slider underneath the tab captions is not displayed. Click on "Manual" and it will appear.

### Expected Behavior
The selected indicator should already be present when the bottom-sheet is shown.

### Actual Behavior
The selected indicator only appears after the selection has changed.

### Reproduction Link
[https://codepen.io/anon/pen/OQOrbX](https://codepen.io/anon/pen/OQOrbX)

**Comment by KaelWD** [comment] 2018-02-16 14:04
Duplicate of #1978

**Closed by KaelWD** 2018-02-16 14:04 UTC
