### ISSUE TITLE
[Bug Report] Expanded table without headers set expanded slot colspan to 0

### ISSUE THREAD

**Issue by Moedav** [vuetifyjs/vuetify#3419] opened 2018-02-28 10:56 UTC
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 7

### Steps to reproduce
1. Create data table
2. set hide-headers and dont set headers
3. create template slot for items with multiple columns
4. create template slot for expand

### Expected Behavior
The expanded slot should be as big as the complete row for expanded item

### Actual Behavior
But the expanded slot is only as big as the first column of the item that is expanded

### Reproduction Link
[https://codepen.io/anon/pen/MQZBww](https://codepen.io/anon/pen/MQZBww)

### Other comments
Expanded table without headers set expanded slot colspan to 0 even if i have multiple columns set in the items row. 
Maybe you want this functionality but why do I have to set headers if I hide them?

**Comment by nekosaur** [comment] 2018-02-28 11:38
Related to https://github.com/vuetifyjs/vuetify/issues/3338

**Comment by KaelWD** [comment] 2018-04-30 14:28
Duplicate of #3338

**Closed by KaelWD** 2018-04-30 14:28 UTC
Labels: bug
