### ISSUE TITLE
[Bug Report][3.0.0-beta.1] v-select not working with array of objects (item-text and item-value attributes)

### ISSUE THREAD

**Issue by AryeBorgen** [vuetifyjs/vuetify#15069] opened 2022-05-08 09:17 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Last working version:** 2.6.5
**Vue Version:** 3.2.33
**Browsers:** Chrome 100.0.4896.127
**OS:** Windows 10

### Steps to reproduce
follow the codepen link 

### Expected Behavior
render the objects and get specific value for each

### Actual Behavior
not working

### Reproduction Link
<a href="https://codepen.io/aryb428/pen/OJQMZpo?editors=101" target="_blank">https://codepen.io/aryb428/pen/OJQMZpo?editors=101</a>

**Comment by nekosaur** [comment] 2022-05-08 11:01
Duplicate of https://github.com/vuetifyjs/vuetify/issues/14783

**Closed by nekosaur** 2022-05-08 11:01 UTC
Labels: S: triage
