### ISSUE TITLE
[Bug Report][3.4.1] V Datatable breaking responsive in 3.4.1

### ISSUE THREAD

**Issue by clementvp** [vuetifyjs/vuetify#18689] opened 2023-11-15 13:44 UTC
### Environment
**Vuetify Version:** 3.4.1
**Vue Version:** 3.3.8
**Browsers:** Firefox 119.0
**OS:** Mac OS 10.15

### Steps to reproduce
V 3.4.1 break responsive in Data Table, see reproduction Link and play with the vuetify version ( works in 3.4.0 NOT in 3.4.1)

### Expected Behavior
Good Responsive Looking

### Actual Behavior
Bad Responsive looking, no horizontable scrolling bar in the table on small sized screen

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtlktu2zAQhq8y0MYtYMt62JJsKAFqJ0iBtkDRAt3EXjDSxCKqFyTKqBsE6B16lN6gR+lJSuoR0Y6C2FkGWlH6Z4b8fkrE8PpOyTNv/C5N1W2BylxxGUZpSBier2IAdzvyCSMjRm5CFALAPEDiY5afrZT6aaXUEcprhV6OjSpeRt9xx/WYRCjL+SjFbJSSDfLgtIqcu2N5TU7hjiUk/pp7GU0Z5MiKtIT0kjhnUMPAGVxXK9wBoyzEOQw+7zISUX8whC0JC6EIkgHcDw8zPyYeYTSJpdSwkTrSl2LlrPBEHC44oVRXUtWxMtTWVwM8THNBI4xznpcP6hQAEtJNLKbBmGHW6l5AQz9DHqpt7hO9R7oJGLyJ3kooQSm2APslC5LjQcENl55K/5aERSQK/v6RS7alLBet66fedm+7t93b7m2/Dttr0YWbrlu2cannNiWiwfK5rjIkDOr+C8ktXNGfpN2CprfyzMvNLmVtpDLKdX1iqVarCz9cNUxNnbRqhSz0qWMazlTa5IMuLL6DCjxN+/frtzG1NFgsm+xHX7U2IeF/CMhtxrv8KQZMS0ZtDOhT1ewwoE9se3KMAfsY8i/oN5t/GrPWQWxoXbyWZjizI3hnx/Au+BF5IbCu6o+QdceR/50W2tA0aybZeQLa0k78PViA8LXgt8cO9E/4g3pJB7sl7d7DXkuahG3a2sx+FptTLy/3qfmZdcfVxZlfmZX7oWKqpmorYpyourL+D+96dXg=)

**Comment by johnleider** [comment] 2023-11-15 17:01
Duplicate of #18679

**Closed by johnleider** 2023-11-15 17:01 UTC
Labels: S: triage

**Comment by KaelWD** [comment] 2023-11-17 02:05
26c9ccb
