### ISSUE TITLE
[Bug Report] Error when creating a new Vuetify project with TypeScript

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12809] opened 2020-12-19 22:01 UTC
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 11.0.1

### Steps to reproduce
1. Create a new project using Vue CLI.
`vue create example-project`
Select TypeScript without class-component syntax. Rest of options does not matter.
2. Add Vuetify to the project using `vue-cli-plugin-vuetify`
`vue add vuetify`
3. Launch the project.
`npm run serve`
4. There is a TypeScript error.

```
ERROR in /Users/xyz/Desktop/vuetify-color-picker/src/plugins/vuetify.ts(2,21):
2:21 Could not find a declaration file for module 'vuetify/lib/framework'. '/Users/xyz/Desktop/vuetify-color-picker/node_modules/vuetify/lib/framework.js' implicitly has an 'any' type.
  Try `npm install @types/vuetify` if it exists or add a new declaration (.d.ts) file containing `declare module 'vuetify/lib/framework';`
    1 | import Vue from 'vue';
  > 2 | import Vuetify from 'vuetify/lib/framework';
      |                     ^
    3 | 
    4 | Vue.use(Vuetify);
    5 | 
```

### Expected Behavior
There should be no TypeScript error when creating a new project using `vue-cli-plugin-vuetify`.

### Actual Behavior
There is a TypeScript error when creating a new project using `vue-cli-plugin-vuetify`.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/VwKWJzy" target="_blank">https://codepen.io/mikilll94/pen/VwKWJzy</a>

**Comment by laxmikanta415** [comment] 2020-12-20 05:04
Hi @Mikilll94  i found this is same as your reported issuse, can you please have a look and see if that fixes your problem.

**Comment by Mikilll94** [comment] 2020-12-20 10:10
@laxmikanta415 
What do mean exactly? I know that I have created two issues at the same time. The second one is here: https://github.com/vuetifyjs/vuetify/issues/12810#issuecomment-748572030

but this is something completely different issue.

I have provided you clear reproduction steps and even a repro project, thus you should have no problems with reproduction of this bug.

**Comment by laxmikanta415** [comment] 2020-12-20 14:37
@Mikilll94 i was not referring to your issue , i was referring to the solution mentioned on another issue reported earlier. i have updated the url in my previous comment , please do have a look if that solves the problem.

**Comment by Mikilll94** [comment] 2020-12-20 22:12
@laxmikanta415
Nope, the solution mentioned in this thread is not working for me. I have added "vuetify" to "types" in `tsconfig.json`.

![Screenshot 2020-12-20 at 23 07 24](https://user-images.githubusercontent.com/17653648/102725594-20976180-4318-11eb-8434-76e3bf0f2ad5.png)

But I am still getting this error:

![Screenshot 2020-12-20 at 23 10 54](https://user-images.githubusercontent.com/17653648/102725680-d06ccf00-4318-11eb-84fd-8c970faaa009.png)


To reproduce this just create a basic app using `vue-cli-plugin-vuetify`. This is very to reproduce.

**Comment by laxmikanta415** [comment] 2020-12-21 05:38
@Mikilll94  Instead of `import Vuetify from 'vuetify/lib/framework';` use   `import Vuetify from 'vuetif';`
That solved the issue for me.

**Comment by Mikilll94** [comment] 2020-12-24 11:46
@laxmikanta415
1. Unfortunately this is not a solution. I want to gain compilation performance benefits using approach from here: https://vuetifyjs.com/en/features/sass-variables/#compilation-time
2. After all, when scaffolding new Vuetify project with TypeScript there should be no error.

**Comment by KaelWD** [comment] 2021-01-07 10:30
Duplicate of https://github.com/vuetifyjs/vue-cli-plugins/issues/228

**Closed by KaelWD** 2021-01-07 10:30 UTC
Labels: triage
