### ISSUE TITLE
[Bug Report][3.0.0] VSelect keyboard scrolling in list not working as expected

### ISSUE THREAD

**Issue by gustav-leffler** [vuetifyjs/vuetify#16062] opened 2022-11-10 12:35 UTC
### Environment
**Vuetify Version:** 3.0.0
**Vue Version:** 3.2.13
**Browsers:** Chrome 107.0.0.0
**OS:** Windows 10

### Steps to reproduce
Hightlighted item not fully visible:
1. Click the v-select
2. Press the down arrow on your keyboard.

Page scrolling when list scroll reached end:
1. Webpage needs to be scrollable.
2. Click the v-select
3. Repeatedly press the down arrow.

### Expected Behavior
After one press down, the first item in the list should be visible.

The page should not scroll when navigating the List using arrow keys.

### Actual Behavior
The first item is only partly visible, the list has scrolled down.

The page also scrolls when navigating the list using arrow keys.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUctuwjAQ/JWVL2kl8gBuKFSqkNreW7UHzMENC7jyS7aJQFH+vRsSCPi0szM7uxqvG1YfMcrdOfsLbMGkdtZHaKDyKCJ+9xy0sPNWQzJoE264wdNFWlkTIgwELB8Hn5r2mRs2Ya/OZaShDWWovHQRAsaje+GmzPsGlQQiaqdonhBAWafCdRqgR0ALaQZ0wQEVVvHaAFDiF9WSs8++z0ZmIck4ELVOVkLJnfVGimQCycoq68XWdvUblXJ7ab+j9fte8YUnEbri52y1NPtk82Cs0RxT563r3BstTh8o94e4gFlRtKMyH+/eyhoqJUI3EJyoyDOlg1KKwSrFGYR4VkgkbUsPvdu0KOoDZzcTgJtdTn7XiPK7jDrQp1fmd6mydsLm2SybzulX5lmRFWzzD8YYozc=)

**Comment by KaelWD** [comment] 2022-11-10 12:50
Duplicate of #16034

**Closed by KaelWD** 2022-11-10 12:50 UTC
Labels: S: triage
