### ISSUE TITLE
[Feature Request] Please add Draggable to Treeview

### ISSUE THREAD

**Issue by Rasool-deldar** [vuetifyjs/vuetify#13322] opened 2021-03-25 14:24 UTC
### Problem to solve
This feature makes it easy for the user to drag between their categories within Treeview

### Proposed solution
Please add this feature to Treeview in the best way possible

**Comment by KaelWD** [comment] 2021-04-09 07:13
Duplicate of #5585

**Closed by KaelWD** 2021-04-09 07:13 UTC
Labels: triage
