### ISSUE TITLE
[Bug Report][3.1.4] VBtn - Icon doesn't render when button used as parent menu activator

### ISSUE THREAD

**Issue by joel-wenzel** [vuetifyjs/vuetify#16636] opened 2023-02-10 21:16 UTC
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a v-btn with icon prop and a nested v-menu with activator="parent" 

### Expected Behavior
icon should be rendered

### Actual Behavior
it is not

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVU9tunDAQ/RXLqrSttECr9GlFovQD+lblJc6DF4asG3yRPdBGK/49YwMrlk2i5Alm5sw5c/P9kfcdoGqe87+B77jSznpkR1Z5kAh3Y4wNrPFWs82E3QgjDPxP0MqagGwKsOvzxK9HYRjDA2jYEWkNjexa/DPam1Y9HnDDhm0ETbFAuGgydvcbTHeyGBu/I3gQZvgmDN/yX87lJE6llwjataR9ExFln0nn0m8ytFRmsphAcqC17V76yScwOfdomKKOrgX/UrU2gOCsl15Jg+RqiF3wm7JIwJlt5P9Q5tzEKUtTi0xWqHqJ1hPQSQ8mQpfABK2kr1demiwEXCGpuAtodEapZcnLJlL35DifScqaxxaNcaBlsRg0maHyyiELgF0Mny7IQ7O8m3QzZTGiCUe7G6Gk4ej4rKEdpmWLKRAEP61fxDONtuAHRBd2RdEZ9/SYV1YXtxQrfGdQachqq2+v8qv8eyZbd5D5z6JWAZfhHILO9t7+C+BJWPB0UpNGvNq3dKYw0f+YaefHQ5QXVAXx9+Az2mgNHvy75a+wr7Wwgly0MT8MmmyrzFNYDbUKaaD3c4Wf6k8rkyeCmP0QRYYtP6uRVFMef3gBGbFlPg==)

**Comment by KaelWD** [comment] 2023-02-11 17:03
Duplicate of #16060

**Closed by KaelWD** 2023-02-11 17:03 UTC
Labels: S: triage
