### ISSUE TITLE
[Bug Report] App bar height does not evaluate % value when positioned absolutely

### ISSUE THREAD

**Issue by flamestream** [vuetifyjs/vuetify#9771] opened 2019-11-22 22:15 UTC
### Environment
**Vuetify Version:** 2.1.11
**Last working version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a <v-app-bar> element with % height and absolute flag.

### Expected Behavior
Bar to fill the view.

### Actual Behavior
Bar has a height of 100px.

### Reproduction Link
<a href="https://codepen.io/flamestream/pen/WNNWKQX" target="_blank">https://codepen.io/flamestream/pen/WNNWKQX</a>

**Comment by johnleider** [comment] 2020-01-16 16:59
Duplicate of #3938 , #5198 , #6140 , #6328

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-16 16:59 UTC
Labels: duplicate
