### ISSUE TITLE
[Feature Request](v-carousel) remove initial transition

### ISSUE THREAD

**Issue by Ewocker** [vuetifyjs/vuetify#4443] opened 2018-07-01 19:36 UTC
### Problem to solve
On load, the carousel component always have a loading transition, for issue "feat(v-carousel): add height attribute #4139" if user start using this as background in v1.2.0, there will always be a empty period than the first carousel item transition in.

### Proposed solution
Disable the initial load transition.

**Comment by KaelWD** [comment] 2018-08-26 06:15
Duplicate of #3459

**Closed by KaelWD** 2018-08-26 06:15 UTC
Labels: duplicate
