### ISSUE TITLE
[Bug Report] Error opening menu with v-date-picker and v-text-field [filled]

### ISSUE THREAD

**Issue by Flashantik** [vuetifyjs/vuetify#12610] opened 2020-11-13 15:13 UTC
### Environment
**Vuetify Version:** 2.3.17
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.198
**OS:** Linux x86_64

### Steps to reproduce
click on the top of text-field

### Expected Behavior
v-date-picker hould open

### Actual Behavior
textfield on focus but v-date-picker is not showing

### Reproduction Link
<a href="https://codepen.io/Flashantik/pen/KKMJVVv" target="_blank">https://codepen.io/Flashantik/pen/KKMJVVv</a>

**Comment by jacekkarczmarczyk** [comment] 2020-11-13 15:20
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7610

**Closed by jacekkarczmarczyk** 2020-11-13 15:20 UTC
