### ISSUE TITLE
[Bug Report][3.0.0] `v-menu` is not working

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#16051] opened 2022-11-09 06:56 UTC
### Environment
**Vuetify Version:** 3.0.0
**Vue Version:** 3.2.42
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Just refer to the above example

### Expected Behavior
v-menu work like previous

### Actual Behavior
There is a console error. `_ref2 is not iterable`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVMFu3CAQ/ZUpPTiR1t5o29PKiRT10kulSj30EHIgNo5oMCDAVlaW/71AbC94s6kqtbf4Yo/fY+bNPOBuQLdKFX1H0R6VptJMWTDUduoGC9YqqS0MoGkDIzRatpA5aoYFFpUUxkJrHuHa4xfZV8q5hJ9S8/pDdjkTmKWtcRS4wwKmZwDLLKd7yL5wVj3BN5rBuPmfOOxixj0W5falV9elC5xGxYmlLgIo+5wo3z4AtmXNeqg4MeYaozpvOH2GX52xrDnkRpGK5kTLTtQYhQVhdUtFN0UunnNDnxsu7Z5UlvXESu0SDqC0VAbGZfmU4sE6WXMMUEke+EqzlugDRjHo2EzUAXW5YizKCXA71wUvI6q2DeWOgrfJNCZBnBk/q0ii/5N7d1MtTRB64YENOF30+dK9XrZBqnv/RA+OGjgrpCe8o69hSUexiDw4fjMMoVIRIhhH39yak7a+oNEAknZ9ODm6OBzZc8aaJdt3oqmwsLg+Z1l2yhHyWQJ7vRtWwz8//r8z4C0L3jJhZcM/MOKcFSdmJHaku/c1c5g/Fp6dH+e/NPIn536wB87EY2zdmYonNn5c13w/SifelVt3tU5f842b3D1o3KBPxa74vEP+46q4Qve/AUI6+hc=)

**Comment by KaelWD** [comment] 2022-11-09 06:59
https://next.vuetifyjs.com/en/components/menus/#usage
https://next.vuetifyjs.com/en/components/overlays/#activator

**Comment by alokVishu** [comment] 2022-11-09 07:15
We are on the verge of the release so is there any workaround for now?

**Comment by markmirandilla** [comment] 2022-11-09 07:35
Experiencing the same issue, it also affects the v-select dropdown menu and tooltip. It's a show-stopper bug and hoping for a workaround :(

**Comment by markmirandilla** [comment] 2022-11-09 07:42
The workaround is to revert to 3.0.0-beta.15

**Comment by KaelWD** [comment] 2022-11-09 07:45
This is caused by https://github.com/vuejs/core/pull/5033, revert to vue 3.2.41

**Comment by markmirandilla** [comment] 2022-11-09 07:53
> 3.2.41

Thanks! reverting to vue 3.2.41 temporarily fixed the issue

**Comment by KaelWD** [comment] 2022-11-09 09:03
https://jubianchi.github.io/semver-check/#/^3.2.41/3.2.42

**Comment by HAFTSTUDIO** [comment] 2022-11-09 09:14
Thanks, the workaround worked with the exact version constraint.

**Comment by KaelWD** [comment] 2022-11-09 13:10
Fixed in Vue 3.2.43

**Closed by KaelWD** 2022-11-09 13:10 UTC
Labels: T: bug, P: critical, upstream, has workaround, C: VOverlay
