### ISSUE TITLE
[Bug Report] Data table not updating

### ISSUE THREAD

**Issue by swirlingsand** [vuetifyjs/vuetify#10193] opened 2020-01-11 01:58 UTC
### Environment
**Vuetify Version:** 2.2.3
**Last working version:** 1.5.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
***** This is not https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats ****
The property is clearly already there!

Go to reproduction: https://codepen.io/aaaaaaaaaaaaaaaaaaa/pen/dyPmMWv

Click "Fail" on first one, works as expected, word changes to failed
Click "Fail" on tool tip (any of spinning ones), the props.item.status does not update

### Expected Behavior
It to detect update

### Actual Behavior
It fails to detect update

### Reproduction Link
<a href="https://codepen.io/aaaaaaaaaaaaaaaaaaa/pen/dyPmMWv" target="_blank">https://codepen.io/aaaaaaaaaaaaaaaaaaa/pen/dyPmMWv</a>

### Other comments
There's something strange "blocking" it. ie even the {{props.item.status}} outside of tooltip does not render. yet if inspect in dev tools it has clearly updated.

**Comment by KaelWD** [comment] 2020-01-11 02:55
Duplicate of #10190 so we can keep the discussion in one place.

**Closed by KaelWD** 2020-01-11 02:55 UTC
Labels: triage
