### ISSUE TITLE
[Bug Report] v-img loads image twice instead of once

### ISSUE THREAD

**Issue by tommerrett** [vuetifyjs/vuetify#12061] opened 2020-08-16 08:56 UTC
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Mac OS 10.15.5

### Steps to reproduce
Attempt to load an image using v-img

### Expected Behavior
The image will load exactly once in a single network request

### Actual Behavior
The image is loaded twice using two network requests

### Reproduction Link
<a href="https://codepen.com/coder-tom/pen/OJNNoep" target="_blank">https://codepen.com/coder-tom/pen/OJNNoep</a>

**Comment by KaelWD** [comment] 2020-08-16 08:57
Duplicate of #9153

**Closed by KaelWD** 2020-08-16 08:57 UTC
Labels: triage
