### ISSUE TITLE
[Feature Request] Extend `v-date-picker` support for times and time ranges

### ISSUE THREAD

**Issue by napei** [vuetifyjs/vuetify#17722] opened 2023-06-30 00:50 UTC
### Problem to solve
Currently the `v-date-picker` component can do only dates, and ranges of dates. For applications such as building dashboards to see data over time similar to Grafana, it would be handy to also be able to specify the time at both ends of a date range with the existing date picker UI. Ideally, wrapped into one control.

### Proposed solution
I am currently using https://github.com/Vuepic/vue-datepicker but a native Vuetify implementation would be great. Further on the time-range selection, "shortcuts" would also be a welcome addition, or at least a slot for them similar to how MUI works, https://mui.com/x/react-date-pickers/date-range-picker/#add-shortcuts or even a "time range picker" which is a whole separate control to focus on time ranges like Grafana does while still providing multiple day selection.

#### Grafana's UI
![image](https://github.com/vuetifyjs/vuetify/assets/8946502/522e0217-baa5-4901-bbe9-372a4c5599f5)

#### `vue-datepicker` UI
![image](https://github.com/vuetifyjs/vuetify/assets/8946502/e893ae55-13a1-4469-8b63-e82a189704f8)

**Comment by digisomni** [comment] 2023-10-17 06:54
+1 for this. This would be a really handy component for dashboards at that point. I tried the same component but it's not slotting well into our Vuetify app atm, a Vuetify component to handle the cases will just flow more naturally.

**Comment by lokeswari9** [comment] 2023-11-19 19:23
I am currently migrating from Vuetify 2 to Vuetify 3 in my project and i have an similar https://v2.vuetifyjs.com/en/components/date-pickers/#dialog-and-menu date picker from selecting max to min values, I am getting this error when i click on my text field to change or enter a new date vuetify.mjs:356 Uncaught (in promise) TypeError: comparing.getDate is not a function
    at isSameDay (vuetify.mjs:356:1)
    at Proxy.isSameDay (vuetify.mjs:436:1)
    at eval (VDatePickerMonth.mjs:95:1)
    at Array.some (<anonymous>)
    at eval (VDatePickerMonth.mjs:95:1)
    at Array.map (<anonymous>)
    at ReactiveEffect.eval [as fn] (VDatePickerMonth.mjs:83:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:1)
    at get value [as value] (reactivity.esm-bundler.js:1135:1)
    at Proxy.eval (VDatePickerMonth.mjs:151:1)

Do we already have this working in vuetify and we are just missing the documentation for vuetify 3 or still its not implemented as it says in this issue. I am currently blocked with this right now for my project migration 

My current Versions
Vue: 3.3.8
Vuetify: 3.4.2

**Comment by johnleider** [comment] 2023-11-20 22:37
Duplicate of #459

**Closed by johnleider** 2023-11-20 22:37 UTC
Labels: C: VDatePicker, S: triage
