### ISSUE TITLE
[Bug Report] v-tabs slider not displayed when v-tabs in menu or not visible

### ISSUE THREAD

**Issue by freakzlike** [vuetifyjs/vuetify#5660] opened 2018-11-20 07:29 UTC
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Windows 10

### Steps to reproduce
Click on the menu button. The tabs will be displayed without the slider. When selecting another tab the slider will be displayed.

### Expected Behavior
Slider to be visible when initial open the menu.

### Actual Behavior
Slider will not be displayed on initial.

### Reproduction Link
<a href="https://codepen.io/freakzlike/pen/BGmVNo" target="_blank">https://codepen.io/freakzlike/pen/BGmVNo</a>

### Other comments
When calling `callSlider()` after 100ms after opening the menu the slider will be displayed

**Comment by jacekkarczmarczyk** [comment] 2018-11-20 14:53
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1978

**Closed by jacekkarczmarczyk** 2018-11-20 14:53 UTC
