### ISSUE TITLE
Feature Request:: Expandable rows for Datatable (like ElementUI)

### ISSUE THREAD

**Issue by smtlk** [vuetifyjs/vuetify#1189] opened 2017-07-31 09:01 UTC
**Feature Request**

I think it would be awesome if Vuetify had expandable table rows like Element UI does, it allows us to keep additional data that either 
A. Is not important enough for the main table display (details)
B. Is too large to fit the Datatable column

For instance in my app i have UUIDs that i need to fit into a Datatable, they don't fit any column so it would be better if i had an expandable panel for each row where i could fit data like this.

**Comment by nekosaur** [comment] 2017-07-31 09:04
Duplicate of #858

**Closed by nekosaur** 2017-07-31 09:04 UTC
Labels: duplicate
