### ISSUE TITLE
[Bug Report][3.1.3] Filtering Autocompletes - Search is reset when pressing enter

### ISSUE THREAD

**Issue by MarinaMWestling** [vuetifyjs/vuetify#16597] opened 2023-02-06 14:05 UTC
### Environment
**Vuetify Version:** 3.1.3
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Type cal inside the autocomplete field
2. Press Enter

### Expected Behavior
If there is only one option inside the dropdown and the user presses enter it should auto select that option for the user.

### Actual Behavior
Pressing enter clears the search filter. All options reappear.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUctuwjAQ/JXIl1wSuxU9RSkCIbU/UKkHwsGQBVzih2yHFiH+vWtD2hDaSr2td2ZnZtfzI5kaQ/ctkIKUHqRpuIdxpZKk3OfcmFjGh+RCfb946/VKIx08nJtJ0vAlNI8VmfYx0qGFQHmH8Dyd8UastVWCp1mSznSjLa91qJ+wFHVsP4O2mzPjBT64C8XrQUuhNumikx2X7DpLlxDbX4EjJ65Sst6KJCNCGm09Mg19c1rhDY5hoLoAriJFEjuhh0cK74psvTeuYKxVZreh6MwmiDHbKi8k5LWWkxEd0bucN2bL6QOrhfN9mIKT+dLqdwcWjSuS9Ty8WB9+87nAKH9PR2fZSytI3kgx1N+DzS2oGizYP+MPuD+tMKDcrBGsT5U64WUboXZucNSViweddwn/tR/+O40CYXoRTE4ZucqIrnGOLD4Bs2juSA==)

**Comment by mhio** [comment] 2023-03-19 04:30
related #16508

**Comment by lioneaglesolutions** [comment] 2023-05-03 10:45
Closing as duplicate of https://github.com/vuetifyjs/vuetify/issues/16508

**Closed by lioneaglesolutions** 2023-05-03 10:45 UTC
Labels: S: triage
