### ISSUE TITLE
[Feature Request] Allow v-select display v-model value not included inside items

### ISSUE THREAD

**Issue by WilliamColmenares** [vuetifyjs/vuetify#10986] opened 2020-03-31 22:24 UTC
### Problem to solve
Sometimes, you show multiple dropdowns to users, so they can select one option and in the next one, do not show this option that has been already selected (for example, translations: if a user selects english the second dropdown shouldn't display english because has been already selected, should only display spanish, portuguese, etc).

If I just create a function to remove values that has been already selected the selected value is not displayed anymore to users.  

### Proposed solution
Allow v-select retrieve v-model values not included inside items.

**Comment by billsliu** [comment] 2020-04-01 00:12
This is rare usage case, it should not contain in vuetify, it should handle by developer.

**Comment by KaelWD** [comment] 2020-04-01 07:37
Duplicate of #4000

**Closed by KaelWD** 2020-04-01 07:37 UTC
Labels: triage

**Comment by henon** [comment] 2020-09-17 09:35
> This is rare usage case, it should not contain in vuetify, it should handle by developer and this is quite easy to solve by the developer.

Would be very helpful if you outlined how, please.
