### ISSUE TITLE
[Bug Report] Dialog width auto doesn't set width to auto

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#12114] opened 2020-08-25 11:41 UTC
### Environment
**Vuetify Version:** 2.3.9
**Vue Version:** 2.6.12
**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.15.3

### Steps to reproduce
Add `width="auto"` on a `v-dialog`
```
<v-dialog
  width="auto"
>
```

### Expected Behavior
The dialog css width prop to be set to "auto"

### Actual Behavior
The css width prop is set to "100%"

### Reproduction Link
<a href="https://codepen.io/thomaskientz/pen/bGpqwOJ" target="_blank">https://codepen.io/thomaskientz/pen/bGpqwOJ</a>

### Other comments
[Docs are mentioning](https://vuetifyjs.com/en/components/dialogs/#dialogs) that the default value of width is "auto", but instead it is "100%".

**Comment by johnleider** [comment] 2020-12-08 21:48
Duplicate of #6919

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-08 21:48 UTC
Labels: C: VDialog, duplicate
