### ISSUE TITLE
[Bug Report][2.5.0] v-data-table grouping title using wrong header attribute

### ISSUE THREAD

**Issue by Direct-eks** [vuetifyjs/vuetify#13968] opened 2021-07-23 02:29 UTC
### Environment
**Vuetify Version:** 2.5.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 91.0.4472.164
**OS:** Windows 10

### Steps to reproduce
v-data-table, when enabling "group-by" prop, and when grouping is in effect, the title bar of the group in the table is not showing the "text" attribute of the given header.

### Expected Behavior
When grouping is in effect, the gourping title shows the "text" attribute of the given header.
In my example, the Chinese "text" attribute 结账单号 should be shown on the title when grouping is in effect.

### Actual Behavior
When grouping is in effect, the gourping title seems to be using the "value" attribute of the given header, but not the "text" attribute.
In my example, the Chinese "text" attribute is not showing on the title when grouping is in effect, but the corresponding "value" attribute "checkoutEntrySerial" was shown.

### Reproduction Link
<a href="https://codepen.io/Direct-eks/pen/OJmOLxo" target="_blank">https://codepen.io/Direct-eks/pen/OJmOLxo</a>

### Other comments
Also, I noticed that the "group" selection on the title bar of the table, does not have i18n support.

**Comment by KaelWD** [comment] 2022-07-06 17:23
Duplicate of #11516

**Closed by KaelWD** 2022-07-06 17:23 UTC
Labels: duplicate
