### ISSUE TITLE
[Feature Request] label for v-text-field on the left or right site

### ISSUE THREAD

**Issue by haexhub** [vuetifyjs/vuetify#4006] opened 2018-05-08 12:04 UTC
### Problem to solve
If you have business applications with many prefilled text fields on a site, its quite hard to read the small labels of the text fields. For readability it would be nice to have an alternative option, to place the label of text fields on the right or left site.

### Proposed solution
Please provide an alternative v-text-field, where you can place the label on the right or left site.

**Comment by KaelWD** [comment] 2018-05-08 12:11
duplicate of #1782

Are you saying you want the text and label on *opposite* sides?

**Comment by haexhub** [comment] 2018-05-08 12:51
Hi. No I want the label of input fields seperated from the input field itself. 
In this example the label is at the top of the input field:

![image](https://user-images.githubusercontent.com/29780781/39757989-dd2132a0-52ce-11e8-9f91-a35135fa3adc.png)

At this example its on the left side
![image](https://user-images.githubusercontent.com/29780781/39758100-3c952840-52cf-11e8-84d2-242604ad9da0.png)

And it would be nice to have an option, where the label should be placed.

**Comment by AlexSHoffman** [comment] 2018-05-08 20:16
@haexhub well, you can already do it just by adding description inside `<v-subheader>`:

```
<v-subheader>Normal with hint text/label</v-subheader>
```

Example from [docs](https://vuetifyjs.com/en/components/text-fields#introduction):

![image](https://user-images.githubusercontent.com/13764106/39780599-7d7dde56-5315-11e8-9222-acf4803ee72e.png)

**Comment by johnleider** [comment] 2018-05-08 21:47
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

This is something that can be easily solved in userland.

**Closed by johnleider** 2018-05-08 21:47 UTC
