### ISSUE TITLE
[Bug Report][3.1.4] Tooltip Error on Safari

### ISSUE THREAD

**Issue by gabrieljbaker** [vuetifyjs/vuetify#16642] opened 2023-02-12 10:36 UTC
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.2.47
**Browsers:** Safari
**OS:** Mac OS 10.15.7

### Steps to reproduce
Hover over the tooltip and notice the errors in safari console related to requestidlecallback being undefined. 

### Expected Behavior
No errors in console.

### Actual Behavior
Errors in console. 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUc1OAjEQfpXaC5qwW42eCBK9+QAkHiiHsjtApX9pB9QQ3t1pWQiCmnjbr998PzM72fLnEOrNGviADxFsMAphJB1jw02lQiifBVilXYcKRvjAaq7BtIxI34J5lNymheRMnM7N0I3YGBIWkfcGdWCqQb1R6CNpgorgkGTGNwq1d/SGPki+l2m3YONONhRHi1EB2bxrSOhYMYN9+aE4WYpgaqIOyBLgOtPaBh+RbVmEOduxefSW9egavTzceEetaSX2mPnr3gsY49mrj6a96t1k870dGfE+33tRiVC/Je/ooNvcRXZEknzAykt+o4yMJV8ihjQQYu3CalE33oon4kRcO9QWqtbbp/v6vr6tlAlLVT+IVic8pWtItppF/54gUrDk/ZMM1PPP33I6muzvDrbdU7a8sBLkv4FY0c9qIUL8s/7Z7E8rnI1crJGjd9Lt6LJGu1U6O2qTykEnh4b/2s9qVxeDrJ7mkF2ff+tIqUXHp1+cdwwc)

**Comment by KaelWD** [comment] 2023-02-12 11:48
Duplicate of #16613

**Closed by KaelWD** 2023-02-12 11:48 UTC
Labels: S: triage

**Comment by gabrieljbaker** [comment] 2023-02-12 13:55
Ah, thanks @KaelWD - apologies I didn’t see the other one.
