### ISSUE TITLE
[Feature Request] Number of column should be fixed in data table

### ISSUE THREAD

**Issue by RohanGau** [vuetifyjs/vuetify#12966] opened 2021-01-15 10:20 UTC
### Problem to solve
Right now I'm using v-data-table but I want to fix some column when I scroll horizontally there is no bind value to do this functionality over data table.
I would like to request you please implement this functionality also as soon as possible

Thank you, 
Rohan Kumar

### Proposed solution
basically fixed prop should be available in header props where we can easily enable by passing boolean value same as sortable prop in header props

**Comment by jacekkarczmarczyk** [comment] 2021-01-15 10:22
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4652

**Closed by jacekkarczmarczyk** 2021-01-15 10:22 UTC
Labels: triage
