### ISSUE TITLE
[Bug Report] Vuetify not working with .scss file

### ISSUE THREAD

**Issue by rafaelmaiach** [vuetifyjs/vuetify#7795] opened 2019-07-11 01:14 UTC
### Versions and Environment
**Vuetify:** 2.0.0-beta.7
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
`npm run serve`

### Expected Behavior
Application working without errors

### Actual Behavior
Running development mode shows a message about vue.config.js
`Expected ";" on @import "~@/scss/main.scss"`

If I add the missing ";" the error persists but change the message to:
`Semicolons aren't allowed in the indented syntax.`

### Reproduction Link
<a href="https://github.com/rafaelmaiach/vuetify-issue" target="_blank">https://github.com/rafaelmaiach/vuetify-issue</a>

### Other comments
I followed the SASS Variables setup on Vuetify version 2 website.
It said about a chainWebpack config if I was using .sass files, but I'm using .scss files, that's why this step is not configurable.

This problem also makes I'm unable to use custom variables on the application.

The repository was created with Vue CLI 3 and vuetify added using the steps informed on Release 2.0.0-beta.0

**Comment by KaelWD** [comment] 2019-07-11 01:19
Duplicate of https://github.com/vuejs/vue-cli/issues/4116

**Closed by KaelWD** 2019-07-11 01:19 UTC
Labels: triage

**Comment by rayfoss** [comment] 2019-08-22 14:52
I can confirm @vue/cli-service 3.11 fixed this issue for me... just had to load a blank sass file next to all my scss.

**Comment by Giildo** [comment] 2019-09-13 09:09
@rayfoss Can you give us an example? Please :smile:

**Comment by rayfoss** [comment] 2019-09-13 13:57
I just came here to the party for the bugs

vue.config.js:
```
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        data: `@import "@/styles/_variables.sass"` // empty file
      },
      // pass options to sass-loader
      scss: {
        // so this assumes you have a file named `src/variables.scss`
        data: `@import "@/styles/_variables.scss"; @import "@/styles/_mixins.scss";`
      }
    }
  }
}
```

**Comment by daxdax89** [comment] 2019-09-30 10:37
I still have this issue

**Comment by mwauramuchiri** [comment] 2019-11-05 08:27
> I just came here to the party for the bugs. @Giildo
> 
> Remember this only works with @vue/cli-service 3.11 or later
> vue.config.js:
> 
> ```
> module.exports = {
>   css: {
>     loaderOptions: {
>       sass: {
>         data: `@import "@/styles/_variables.sass"` // empty file
>       },
>       scss: {
>         // My very particular set of styles I have acquired over a long career
>         data: `@import "@/styles/_variables.scss"; @import "@/styles/_mixins.scss";`
>       }
>     }
>   }
> }
> ```

This worked for me. Thanks!
