### ISSUE TITLE
[Bug Report] Buttons Erroneously Changing Color

### ISSUE THREAD

**Issue by galperi1** [vuetifyjs/vuetify#8526] opened 2019-08-14 15:34 UTC
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
While on a laptop with a usb connected mouse, click any Vuetify button with your mouse and track-pad at the same time. When I clicked both at the same time, the color of the button lightens. If repeated enough times the button will turn completely white. For this reproduction link you can just right and left click with your mouse at the same time on the hello button for the bug to show up.

### Expected Behavior
The button should stay the same color no matter how it is clicked.

### Actual Behavior
Entire button turns completely white after enough "double clicks" 

### Reproduction Link
<a href="https://jsfiddle.net/gwalperi/xfmc3b9h/3/" target="_blank">https://jsfiddle.net/gwalperi/xfmc3b9h/3/</a>

### Other comments
If the button changes the page when clicked, the same bug happens, but is not noticeable due to the fact that you are no longer on the same page. I was able to replicate this bug on the official Vuetify website as well as with any button in my projects.

**Comment by jacekkarczmarczyk** [comment] 2019-08-14 15:35
Your reproduction uses vuetify 0.14.8, the bug has been already fixed

**Comment by galperi1** [comment] 2019-08-14 15:55
This is can be replicated on the Vuetify website right now.

**Comment by jacekkarczmarczyk** [comment] 2019-08-14 15:59
You're right, but next time please provide the correct reproduction

**Comment by galperi1** [comment] 2019-08-14 16:07
Will do sorry about that.

**Comment by jacekkarczmarczyk** [comment] 2019-08-14 18:46
That actually duplicate of https://github.com/vuetifyjs/vuetify/issues/4185

**Closed by jacekkarczmarczyk** 2019-08-14 18:46 UTC
Labels: C: VBtn, T: bug
