### ISSUE TITLE
[Bug Report][3.7.3] Treeview Indentation when there is no children

### ISSUE THREAD

**Issue by joshuaeobrian** [vuetifyjs/vuetify#20635] opened 2024-10-29 12:38 UTC
### Environment
**Vuetify Version:** 3.7.3
**Last working version:** 2.7.2
**Vue Version:** 3.5.12
**Browsers:** Chrome 130.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a tree view with a mix of elements with children and no children.

### Expected Behavior
Elements with no children should have the same indent as elements with children. So items don't look like they are nested under other items when they are not.

This is also previous behavior in vuetify 2

### Actual Behavior
Elements with no children do not match the alignment of elements with children

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1VUtP4zAQ/iujXApS2W66PJaoVOruXvaye0FcKAfXnqqWHDs4kxSE+t9x0oa4TdoGAZc8PPN9nz0v378EqeWDSZJ8yzMMomBEGCeKEY6nGmCUn5FFzCUuIZLOlN5Mg/I9DcajQW113qOBB3W/KbcyoZIGnxJjCQTOWaYIXoo1AMGIRXByCjdjONmsAZTsEdxX/1C5b8wigrDvr5AkhRH03BmU5Iyk0SlEvS0fvpBKWNQR6Ewpz7Tyvhs6F606fwzPYtR0QMTbfIO4Ir/cwvoCLhEk58+79AclWmUqqasGjy/n8t8mdVSulCz5f/bfyKQW+AQRUNrbim0TdF2DZsZQSpYlB4EPLatNz12vXY/WXITf9yYjdvVsJVPDz0tHuF2/n5+PcFjHNj+bke6UkPCHj+LMim6wcx+2dAVg3Kz44jz61oMtHO7r4aVWhol39PCa7rI+7H9OZobWnTUR8+ZhN4CrGvDP5BgfR3jddJuRKYrPIRYUq11I9yhct0bhTgo0Hxxjw/2tU+2+oXC8ddbUYR2JXyyVHBR7NlkxeCFOztvrawP1OmAicqY5CiDkCy0fM+xC4DXDRClgMycMLClGlJC2DXp08qyJvXb5q8maYi8m31cNw4va/bfRc3Qh4wiyQIqMF5edI2C57FYb1erqtPxYFbf22z0drPrl7Vg8Hl4Bs7n13Q==)

**Comment by KaelWD** [comment] 2024-10-29 12:44
Duplicate of #20421

**Closed by KaelWD** 2024-10-29 12:44 UTC
Labels: S: triage
