### ISSUE TITLE
[Bug Report] V-Dialog doesn't dismiss correctly if opened and closed while in a different tab.

### ISSUE THREAD

**Issue by Pazza** [vuetifyjs/vuetify#9792] opened 2019-11-25 23:19 UTC
### Environment
**Vuetify Version:** 2.1.11
**Last working version:** 1.5.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.15.1

### Steps to reproduce
Follow example. Click button then immediately change tabs. count to 5 and then return. During this time a dialog will be displayed and then hid again.

### Expected Behavior
Dialog should open and close while in a different tab. 

### Actual Behavior
Dialog appears to have been shown but the overlay background remains and blocks interaction. Browser has to be refreshed to correct.

### Reproduction Link
<a href="https://codepen.io/pazza/pen/pooXzqP" target="_blank">https://codepen.io/pazza/pen/pooXzqP</a>

**Comment by jacekkarczmarczyk** [comment] 2019-11-26 03:11
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8625

**Closed by jacekkarczmarczyk** 2019-11-26 03:11 UTC
Labels: triage
