### ISSUE TITLE
[Bug Report] Use dark theme with disable icons

### ISSUE THREAD

**Issue by catsmeatman** [vuetifyjs/vuetify#11723] opened 2020-06-25 10:29 UTC
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.15.5

### Steps to reproduce
1. Create <v-btn icon disabled><v-icon>mdi-heart</v-icon></v-btn>
2. Add dark in <v-btn icon dark disabled><v-icon>mdi-heart</v-icon></v-btn>
3. See bug

### Expected Behavior
Icons will bee gray color

### Actual Behavior
Icons is not show

### Reproduction Link
<a href="https://codepen.io/pawel-golubew/pen/YzwQeXz" target="_blank">https://codepen.io/pawel-golubew/pen/YzwQeXz</a>

**Comment by jacekkarczmarczyk** [comment] 2020-06-25 10:36
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4482

**Closed by jacekkarczmarczyk** 2020-06-25 10:36 UTC
Labels: triage
