### ISSUE TITLE
[Bug Report][3.2.2] VAutocomplete breaks when selection slot is defined

### ISSUE THREAD

**Issue by efthymiou** [vuetifyjs/vuetify#17320] opened 2023-05-08 13:31 UTC
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Click on the select
2. Pick an item
3. Click out of the select box

### Expected Behavior
After 2. the selected item should be rendered according to the selection slot.

After 3. the item should still be selected.

### Actual Behavior
After 2. the item is not rendered in a visible way.
After 3. the value is cleared and selection is lost

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU0Fu2zAQ/MqCPqQFLLF1kItqB8knegl9oKU1ypYiCZJyWgj6e5eUnNiyDgHCi03O7MzOknrp2bNz5alDVrFtxNZpGfFRGIDtqZDO5b9500plpt15JUoXbW2pDCNeg2lRlW1Q7wRrZJSC3TK0PGT8edKBVw4BNdZRWQNB27hUVWsZAlW1snhYwitFURIh/84ZsxQ5yTk6rN7cqbyHJACDYAs1aa36kVJGFTXCMKwWtPnVXC+B6/nNYefxPenflPTxp9Qdwg7INk2UDLecaOdbIsG3a8rq+QKvGqBtqL1ykcYcuwSr1lkfoQePRxjg6G0Ld/Qi7oSprQlxdNol+IvptP764wzk6U7Iy9hCD6fUYgXf15BnUoFgR2sFg2E9o2wuKAfpJ8o+6W/52CS1x9Zs7JCiufJ3sIaeap+k6HozQBdcQT5JZ9R52gv2K0YXKs7rxlAZPUN18qXByI1r+RPRuO9MVC0WjW2f7sv78ltxwCjLB96oEC/REkNbHLx9DehJS7ApSnaL6vjvA44Tk4w25WZ0mI4K+ghCsriR5uR3Ql94NA16pBF9LNisbCHcjHETMDUxCDPQ9LUyf8Js8HXIQ58u/ZPJs1hS2ifDYc0u26UGch3b/wdOK3LG)

### Other comments
It seems that there are some conditions that check if slots.selection is defined in the select() function of VAutocomplete, as well as the isFocused watcher.

**Comment by KaelWD** [comment] 2023-05-08 15:21
Duplicate of #17291

**Closed by KaelWD** 2023-05-08 15:21 UTC
Labels: S: triage
