### ISSUE TITLE
[Feature Request] Enable ellipsis on columns of a data-table 

### ISSUE THREAD

**Issue by martn001** [vuetifyjs/vuetify#10143] opened 2020-01-07 13:45 UTC
### Problem to solve
It's currently impossible for enabling ellipsis on tables. My website doesn't display well, because every text is just to big inside the data-table. Because the data-table should be responsive, I can't make the text shorter.

___
![image](https://user-images.githubusercontent.com/8685175/71899051-32114900-315b-11ea-8803-ed6b1fbe1619.png)
____

I would like to see ellipsis in the future, otherwise my data-table looks like this: https://codepen.io/martn001/pen/ZEYrGxW

I would like `white-space: nowrap` with a max-width of column header.

### Proposed solution
Created a boolean for enabling ellipsis on tables columns.

**Comment by jacekkarczmarczyk** [comment] 2020-01-11 07:44
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8474

**Closed by jacekkarczmarczyk** 2020-01-11 07:44 UTC
Labels: triage
