### ISSUE TITLE
[Bug Report] In v-edit-dialog component large property - does not work 

### ISSUE THREAD

**Issue by savylovskij** [vuetifyjs/vuetify#10518] opened 2020-02-08 16:06 UTC
### Environment
**Vuetify Version:** 2.2.10
**Last working version:** 2.2.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.87
**OS:** Windows 7

### Steps to reproduce
Good afternoon. The v-edit-dialog component has a large property which is "Attaches a submit and cancel button to the dialog" but it does not work on version 2.2.10

### Expected Behavior
The v-edit-dialog component has a large property which is "Attaches a submit and cancel button to the dialog" is work

### Actual Behavior
Good afternoon. The v-edit-dialog component has a large property which is "Attaches a submit and cancel button to the dialog" but it does not work on version 2.2.10

### Reproduction Link
<a href="https://codepen.io/savylovskij/pen/wvaBpJy?editable=true&editors=101" target="_blank">https://codepen.io/savylovskij/pen/wvaBpJy?editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment] 2020-02-09 02:50
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10468

**Closed by jacekkarczmarczyk** 2020-02-09 02:50 UTC
Labels: C: VEditDialog, S: has PR, T: bug
