### ISSUE TITLE
text box focus when pressing outside the actual input

### ISSUE THREAD

**Issue by cayaner** [vuetifyjs/vuetify#2101] opened 2017-10-09 13:01 UTC
### Versions
vuetify v0.16.4

### What is expected ?
when pressing outside the actual input element but inside the text field it is supposed to get focused.

### What is actually happening ?
when pressing outside the actual input element but inside the text field it is not getting focused.

### Reproduction Link
https://codepen.io/cayaner/pen/GMxPRd

**Comment by jacekkarczmarczyk** [comment] 2017-10-09 13:05
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1829

**Closed by jacekkarczmarczyk** 2017-10-09 13:05 UTC
