### ISSUE TITLE
[Bug Report] v-badge with icon gets broken when window is resized

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#2603] opened 2017-11-22 09:03 UTC
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.7
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 7

### Steps to reproduce
Add a couple of `v-badge` components with a `v-icon` as the `badge` slot.
Resize the window and watch how the badge gets broken.
You can also toggle the "Console" in the Codepen interface a few times which will show the same effect.
The way I first noticed the bug was with the "Exciting announcement" badge in the nav drawer on the docs page.

### Expected Behavior
The badge should stay unchanged.

### Actual Behavior
The badge is removed and icon just shows instead.

I have debugged the markup before/after and it seems that the surrounding span which has the `badge__badge` class is simply removed

Before: 
```
...
<span class="badge__badge red">
   <i data-v-fd715c0e="" aria-hidden="true" class="material-icons icon icon--right theme--dark">plus_one</i>
</span>
...
```
After:
```
...
   <i data-v-fd715c0e="" aria-hidden="true" class="material-icons icon icon--right theme--dark">plus_one</i>
...
```

### Reproduction Link
[https://codepen.io/anon/pen/rYdbdr](https://codepen.io/anon/pen/rYdbdr)

### Other comments
I guess it must be something to do with how the slot is used/manipulated inside the component, but it is very weird that it happens on window resize. Also, the behavior differs slightly if you put the v-badge inside a navigation drawer or toolbar.

**Comment by sindrepm** [comment] 2017-11-22 09:09
Note: this is possibly related to #2550.

**Comment by jacekkarczmarczyk** [comment] 2017-11-22 09:47
Simplified testcase https://codepen.io/anon/pen/XzEwwX?editors=1010

**Comment by jacekkarczmarczyk** [comment] 2017-11-22 10:13
Duplicate of #2550

**Closed by jacekkarczmarczyk** 2017-11-22 10:13 UTC
Labels: pending review
