### ISSUE TITLE
[Feature Request] Please add standard form support for selects and selection controls

### ISSUE THREAD

**Issue by jwhentsch** [vuetifyjs/vuetify#3465] opened 2018-03-04 17:22 UTC
### New Functionality
It'l allow me to incorporate these nice elements into my so far plain rails-driven app. As a workarround can you or someone else please advice me how to implement a <form-wrapper> component, which wraps all these <v-select>-elements to make them standard-form-compatible?

### Improvements
I tried to implement a wrapper to put arround <v-checkbox> and <v-select>. But a the moment I fail on implementing a "name"-attribute. And I can't figure out how the "name"-attribute is supported by <v-text-field>.

### Bugs or Edge Cases it Helps Avoid
At the moment, I test vuejs and vuetify against webcomponents/polymer. I like the completeness of the ui-elements and the ease incorporation of vuejs and vuetify within rails/webpack/turbolinks (with webcomponents/polymer that's a nightmare).

**Comment by jwhentsch** [comment] 2018-03-05 18:14
In the meantime I have implemented a <form-element-wrapper> which almost works but a problem with v-model in scoped-slot environment stops me from success.

[form-element-wrapper-vue.txt](https://github.com/vuetifyjs/vuetify/files/1782049/form-element-wrapper-vue.txt)

The problem is at 'v-model="slotscope.value"'. I can not operate the switch - but if I change the value with vue-dev-tool then the switch slides - STRANGE.

Ich I take the v-switch (or v-checkbox) directly into my element (not in a slot) then with 'v-model="value"' everything works as expected.

So is that a Bug? Is it in the vuetify-elements or in vuejs?

I'm brandnew in vuejs and vuetify and English is not my mother language.

So every help is very welcome.

thanks from Germany!

jwh

**Comment by jwhentsch** [comment] 2018-03-05 18:39
well, and I tested it with v-select as well, same problem. I can change the value of the select with the vue.js dev-tools and the selected item changes. But it doesn't work the other way round.

**Comment by jwhentsch** [comment] 2018-03-06 22:47
OK, finally, I figured out (by testing my wrapper wrapping arround a standard input - element) that scoped slots may not work with two-way-sync by now - I' ll try to ask at vuejs.org for a change.

Here my request is still - please make your selectors "standard-form" compatible - same as the v-text-field is already - MANY THANKS !!!

**Comment by nekosaur** [comment] 2018-03-08 10:31
What exactly do you mean by standard form support? If you are having specific problems with v-select or other input controls perhaps this is a bug report instead of a feature request?

**Comment by jwhentsch** [comment] 2018-03-08 10:58
With standard form support I mean adding a "name" property to the selects (like it is with the v-text-input) Then you could put the v-select, v-checkbox and v-switch just into a regular <form>-element provide the name and the "start"-value to the value-property and the support for the "old"-world would be fine. Of course you have to load vuejs and vuetify, have to instantiate at least one vue-instance and have to wrap the whole form by <v-app>.
Because the v-select's don't have the "name"-support (the docs say you MUST use v-model) I can put a regular <input hidden> aside each v-select-like element and couple it with v-model and v-bind. But than I have no markup-way to set the start value. Thats why I try (as a vue-newbee and relative JS-hater) to implement a wrapper which hooks up this regular input-element and which has an input-value-property to set the start value. This wouldn't be necessary, if the v-select's have that "standard-form-support" already aboard. I don't see the point, why v-text-input has support for it whereas v-select's don't.
Clearly, that's all not needed in the whole new single page app world. But vuejs claimes to be able to renew just parts of older solutions step by step. And the wonderfull vuetify-components may help to renew those old-style-web-apps even step by step.

Do you see my problem/feature-request now. Sorry for my bad English. In my own mother language I could explain it way better.

But again - thanks for your responce and thanks to all the people, who made those fantastic looking vuetify-stuff at all.

**Comment by nekosaur** [comment] 2018-03-08 11:48
Ah, I understand. With the input refactor we're working on for 1.1 we're hoping to include native input elements where appropriate.

I will be closing this issue since it is pretty much a duplicate of https://github.com/vuetifyjs/vuetify/issues/838 where we are tracking this feature.

**Closed by nekosaur** 2018-03-08 11:48 UTC
Labels: duplicate
