### ISSUE TITLE
[Bug Report][2.6.2] v-menu reposition on content resize

### ISSUE THREAD

**Issue by questionhound2** [vuetifyjs/vuetify#14595] opened 2022-01-12 13:00 UTC
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 2.6.14
**Browsers:** Chrome 96.0.4664.110
**OS:** Windows 10

### Steps to reproduce
- open the menu, items will be automatically added to the menu after half a second

### Expected Behavior
Menu should reposition so everything is visible if there is enough space.

### Actual Behavior
Need to scroll to see newly added items.

### Reproduction Link
<a href="https://codepen.io/questionhound2/pen/vYeQeZR" target="_blank">https://codepen.io/questionhound2/pen/vYeQeZR</a>

**Comment by KaelWD** [comment] 2022-01-12 13:05
Duplicate of #9878

**Closed by KaelWD** 2022-01-12 13:05 UTC
Labels: S: triage
