### ISSUE TITLE
[Bug Report] v-autocomplete click action in slot stopped working as expected

### ISSUE THREAD

**Issue by albertovincenzi** [vuetifyjs/vuetify#12636] opened 2020-11-17 15:52 UTC
### Environment
**Vuetify Version:** 2.3.17
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.193
**OS:** Windows 10

### Steps to reproduce
After upgrading from 2.3.16 to 2.3.17, I started facing the following issue:
on v-autocomplete slot, I used @click event to open a dialog form.
The v-autocomplete field is in a dialog, so I'm opening a new one on top of it.
With the new version, the new dialog (openClientCreation function) doesn't open and the original dialog (which have persistent property) zoom in like when you click outside.

### Expected Behavior
click on list-item open new dialog

### Actual Behavior
click doesn't open dialog and parent dialog behavior is like click outside

### Reproduction Link
<a href="https://codepen.io/albertovincenzi/pen/oNLOjMp" target="_blank">https://codepen.io/albertovincenzi/pen/oNLOjMp</a>

**Comment by KaelWD** [comment] 2020-11-17 15:52
Duplicate of #12586

**Closed by KaelWD** 2020-11-17 15:52 UTC
