### ISSUE TITLE
Vuetify Datatable Pagination messed up

### ISSUE THREAD

**Issue by donPuerto** [vuetifyjs/vuetify#607] opened 2017-05-26 01:53 UTC
![image](https://cloud.githubusercontent.com/assets/9329005/26477587/2e91d12c-41f9-11e7-88d1-9068cfcbc050.png)

**Comment by johnleider** [comment] 2017-05-26 02:11
Duplicate of #585

**Closed by johnleider** 2017-05-26 02:11 UTC
Labels: duplicate
