### ISSUE TITLE
[Bug Report] VFooter is not responsive with `app` + `absolute` props set

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#12569] opened 2020-11-06 21:28 UTC
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.183
**OS:** Windows 10

### Steps to reproduce
1. Open codepen.
2. Resize window to different breakpoints.

### Expected Behavior
VFooter should be responsive to the content

### Actual Behavior
VFooter is not responsive to different breakpoints.

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/mdEGwxO" target="_blank">https://codepen.io/andrewspy/pen/mdEGwxO</a>

**Comment by KaelWD** [comment] 2020-11-06 23:39
Duplicate of #12313

**Closed by KaelWD** 2020-11-06 23:39 UTC
