### ISSUE TITLE
[Feature Request] Send notifications with v-alert from the code

### ISSUE THREAD

**Issue by frbuceta** [vuetifyjs/vuetify#9665] opened 2019-11-12 00:06 UTC
### Problem to solve
Let's get in the case that we have a plugin that is the API and this breaks, I need to send the user an alert but I can't because I can't call this from that JS file

### Proposed solution
Something like this: https://bootstrap-vue.js.org/docs/components/toast#advanced-usage

**Comment by jacekkarczmarczyk** [comment] 2019-11-12 02:50
Duplicate of #3037 / #2384

**Closed by jacekkarczmarczyk** 2019-11-12 02:50 UTC
Labels: triage
