### ISSUE TITLE
[question] v-date-picker range

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#432] opened 2017-04-24 19:04 UTC
Any plans for ```v-date-picker``` supports range selection? Like this:
![5c04caab55](https://cloud.githubusercontent.com/assets/339596/25353996/da49e992-2939-11e7-9a16-d0adaf7a5f83.jpg)
P.S. Thanks for adding pickers and other updates!

**Comment by nekosaur** [comment] 2017-04-24 19:13
Duplicate of #419

**Closed by nekosaur** 2017-04-24 19:13 UTC
Labels: duplicate
