### ISSUE TITLE
[Bug Report][3.0.1] Autocomplete - popup position changes on refocus

### ISSUE THREAD

**Issue by mexican-jack** [vuetifyjs/vuetify#16075] opened 2022-11-12 11:47 UTC
### Environment
**Vuetify Version:** 3.0.1
**Vue Version:** 3.2.45
**Browsers:** Edge 107.0.1418.35
**OS:** Windows 10

### Steps to reproduce
- click on the auto complete and type "a"
- wait for results - autocomplete options should load
- observe the auto-complete popup situated below the autocomplete - with the input focused
- close the autocomplete
- click on the autocomplete
- observe that the popup not takes the whole viewport height and covers the input of the autocomplete

### Expected Behavior
the popup should always be below the autocomplete input.

### Actual Behavior
the popup is covering the input, as a result, your input cannot be seen.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9VU1z2jAQ/StbXzBTkEm/Dh6STmZ6yUxmmpkcQw7CXkCpkFxLpqGE/96VbGzLkMLBy+7Tevft0/J0iG6Lgu0qjNJobnFbSG7xZqEAFtZ957nYgbF7ideLaMvLtVBTq4v0ajYrXheRR54+nT3fTXlldaYpH1rsg3bTrc5RumzuuYguBFODvMw2hKmNEJQKqtNQ0D8HMal5LtTaRc19bYeIjchxqvQ055af+Q1KzCzm/YB7y9QK6xn4gSYrRWGFVmFaj9pxWTnU7cNdGJV86Vt+qJZSZEDxQd1Ee4YbLXMsCfZoeWnB7guqHqyGxwssFCUWqPKpyLRyZObCt7TkxrVxji/RVqWa6uULddgFbuZJOCs/0XlCYydrnvQkQT/r5j0EXwtNRea44pW0cKhTuhJSiMdwfQNx4yNvx9q92AqbwrfZ5BREZUuBJoWn59bXzi6FFZcG20AtD1CVlK2v7jZwHsdk1Kbrq6KRpqcSAVYCZW5cla2LXrmC+IPdCMP8O8YNYVTVKVPHIvz0LLJfuDdx7wzb8iImp+u+l7o9FvgACNk20ejfCSiFLuUTYZ7h7Q1GKuGjAH3sfhzHJ/vYUegux6DHpgyfvqHdl+zs86JJWMZCT/Fw7Ye1Zz0fk6jWdgM3ddbhpMP2vl84b+hCYDybXD4/ho8wYoyNwkTpeaL+lIZz4saItYoPx0l9bgKHoK+Ov0tcumdt/eHWCa1lqVYexDS2gOckgTtP/4bvELgsked7WCIqcPupv1+c7Hznfl4dm7OTAPt9/Sdvib8rNMHq6lKfbtOlnCGCRmzLihZ28NJ7/lfIva8dhKLrVKurw6yQiIlHG2sLkyYJLwQr/KojyzBdrpNGbqMe0wDMblDFJRqnPXqwF6NVPH4fM7hAtUIPpxUCRyqfkCGor/ZGwU73re7onyx4YXMi05WyhKdwcOvC4jKniBjL8p3qtEQm9dohgoODNCuhuJT7uFmcZzPxS7DjZahMWgXzpNnN0XESfWaf2JevkTNm7Cp6/gfvyFYo)

**Comment by setaman** [comment] 2022-11-16 17:43
Due to this issue and the fact that the text input overflows the chips makes the autocomplete currently completely unusable.

![Unbenannt](https://user-images.githubusercontent.com/15034996/202254007-7164bf07-a3ab-40c5-84ed-d15f34c036b8.png)

**Comment by mexican-jack** [comment] 2022-11-16 18:10
i have found a temporary solution on the autocompletes, which is to pass menu props `:menu-props="{maxHeight:300,eager:true}"`
eager appears to fix it

**Comment by setaman** [comment] 2022-11-16 18:27
@mexican-jack thanks a lot! That is a way better now. But the menu still of course overlap the input in some circumstances

**Comment by KaelWD** [comment] 2022-11-29 06:34
Duplicate of #15587

**Closed by KaelWD** 2022-11-29 06:34 UTC
Labels: S: triage
