### ISSUE TITLE
[Bug Report] v-data-table does not show boolean values

### ISSUE THREAD

**Issue by deitass** [vuetifyjs/vuetify#8949] opened 2019-09-13 13:59 UTC
### Environment
**Vuetify Version:** 2.0.17
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. the data into the v-data-table contains a boolean field. For example:
{
          name: 'Frozen Yogurt',
          calories: false,
          fat: 6.0,
          carbs: 24,
          protein: 4.0,
          iron: '1%'
        }
2. The column displays an empty value instead of the expected true/false value

### Expected Behavior
the table displays true, false, or empty depending on the values of the item

### Actual Behavior
the table always displays an empty value independent of the values in the item

### Reproduction Link
<a href="https://codepen.io/deitass/pen/jONKvGY?editors=1010" target="_blank">https://codepen.io/deitass/pen/jONKvGY?editors=1010</a>

**Comment by MajesticPotatoe** [comment] 2019-09-13 14:05
duplicate of #8554

**Closed by MajesticPotatoe** 2019-09-13 14:05 UTC
Labels: triage
