### ISSUE TITLE
[Feature Request] When we have an notify component like 'PNotify'  using vuetify?

### ISSUE THREAD

**Issue by AnodoubleA** [vuetifyjs/vuetify#9816] opened 2019-11-28 01:58 UTC
### Problem to solve
To stack the notifies.

We have a lot of message to show, but the Snackbar component just a singleton，so  new message will cover old message, but we dont want that.

### Proposed solution
Just like 'PNotify' to stack the messages.

**Comment by MajesticPotatoe** [comment] 2019-11-28 02:01
duplicate of #2384

**Closed by MajesticPotatoe** 2019-11-28 02:01 UTC
Labels: triage
