### ISSUE TITLE
[Bug Report] Will it be fix at v3.0 (Titan) Date picker in 'FA-local' ? 

### ISSUE THREAD

**Issue by artmarydotir** [vuetifyjs/vuetify#12390] opened 2020-10-10 04:29 UTC
### Environment
**Vuetify Version:** 2.3.13
**Vue Version:** 2.6.12
**Browsers:** Firefox 81.0
**OS:** Ubuntu undefined

### Steps to reproduce
yes its a duplicate issue.

it was a bug from **version 1**. and the issue is still open, [this issue](https://github.com/vuetifyjs/vuetify/issues/1892)
its been two years 
will you please tell us if is gonna fix in **vuetify v3**? or its not in vuetify roadmap? 🙏 

### Reproduction Link
<a href="https://codepen.io/artmarydotir/pen/PozwgyY" target="_blank">https://codepen.io/artmarydotir/pen/PozwgyY</a>
the picture below show the differences .

![Screenshot from 2020-10-10 07-55-00](https://user-images.githubusercontent.com/11363931/95645626-ef0b4a00-0acd-11eb-9ea1-df07943e81b1.png)

**Comment by KaelWD** [comment] 2020-10-10 06:15
Duplicate of #1892

See https://github.com/vuetifyjs/vuetify/issues/1892#issuecomment-576700700, this probably won't be done in v3 as there's a shitload of other work that needs to be done. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Closed by KaelWD** 2020-10-10 06:15 UTC
Labels: duplicate
