### ISSUE TITLE
[Bug Report][3.0.0-beta.3] Errors are not colored in red in VTextField

### ISSUE THREAD

**Issue by throrin19** [vuetifyjs/vuetify#15340] opened 2022-06-24 13:46 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Last working version:** 3.0.0-beta.2
**Vue Version:** 3.2.36
**Browsers:** Chrome 102.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Set an error message on vuetify beta2 VTextField : the VTextField is red
- Upgrade to Beta3 or 4 : the VTextField is not red

### Expected Behavior
Show the VTextField in error (red)

### Actual Behavior
Don't show the VTextField in error

### Reproduction Link
<a href="https://codesandbox.io/s/nervous-albattani-xxn0go?file=/src/App.vue" target="_blank">https://codesandbox.io/s/nervous-albattani-xxn0go?file=/src/App.vue</a>

**Comment by KaelWD** [comment] 2022-06-24 13:52
Duplicate of #15209

**Closed by KaelWD** 2022-06-24 13:52 UTC
Labels: S: triage
