### ISSUE TITLE
[Bug Report][3.2.2] V-Autocomplete's multiple props has invalid type: false | undefined

### ISSUE THREAD

**Issue by velly** [vuetifyjs/vuetify#17289] opened 2023-05-04 03:09 UTC
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
No step

### Expected Behavior
muliple is boolean

### Actual Behavior
false | undefined

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUEtOwzAQvYrxJiA1Nmp3VYvKhkvUXaTJBEzjj+xJAFW5O+MklaKWRSV28+bzPrM/81fvRdcCX/MNgvFNgfCiLGObLi+8H8oBmELbCQ0Y4RvzWkNTMRq6Cpqt4ia+K87k5UrOzhIYCTdyJkQwlkF7ZBGwTWNtvAvIzixAzXpWB2dYRg6ztFw6G5GRDNum+WP2VpyAKh9c1ZbwkD0l/pGRuPiCj3Tkw4vP6CzlPCc7ahpExdds6KQeySSs+Aeij2spy8rSGYXTXRAWUFpv5I7WZGgtagN55cxuJVbiOT8CFmIlKx1xPhUQTX4M7itCIC7FFzM11PXPHYrTJgktxXJUmFp5UxxjkrihlqTXQcgD2AoChHuDXZ39Ee5q4yZgMtEr29P3G21P8erxZRyevr94/VfygSwxHZJgv+Bzu2RguOOHX1gG+e0=)

**Comment by velly** [comment] 2023-05-04 03:12
Cannot assign type 'boolean' to type 'false'.
index.d.ts(2236, 9): Required type is from property "multiple"， "Partial<{ reverse: boolean; type: string; error: boolean; active: boolean; direction: "horizontal" | "vertical"; transition: NonNullable<string | boolean | (TransitionProps & { ...; })>; ... 33 more ...; filterKeys: NonNullable<...>; }> & ... 6 more ... & Record<...>" 

**(property) multiple?: false | undefined**

**Comment by KaelWD** [comment] 2023-05-04 03:24
Duplicate of #17211

**Closed by KaelWD** 2023-05-04 03:24 UTC
Labels: S: triage
