### ISSUE TITLE
[Bug Report][3.0.6] VSwitch on dark is almost invisible

### ISSUE THREAD

**Issue by mostley** [vuetifyjs/vuetify#16363] opened 2023-01-03 10:33 UTC
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add Switch to a UI using Dark theme

### Expected Behavior
Switch to be visible

### Actual Behavior
Switch has same color as background

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UMtugzAQ/BVrz2CnzwOiVfodcQ4UtsUFG8s2RFXEv3ftUIkSNTfvzOzMeA9neLOWTyNCAWVAbfsq4Ks0jJVTXlnLQosaXyQ0leskJCZxulJmmdLsTyrULav7ynuS6z6/20lg4ndDrFbiQN70LsUqUxrIQGk7uEBay7/8YKjWOa7IhfASCpaQiFHvOEtoQ7C+EGI0tvvk9aDFnjjhRhOUxrwZ9P6B3/PHJ9EoH9Y4R6/zdzecPDpKlJCtzIP6+P4vYKHJd8efL7YLFC2vrAT5T+hyh6ZBh+5m7432T/cNd9U/Zs7SzHTLXpnOb85Y+3TCwzFK5gwu1iRO/4DjD3bCrbM=)

### Other comments
Can also be seen in the Documentation: https://next.vuetifyjs.com/en/components/switches/

Workaround for now: Using color="primary" helps to see the active state or use inset to have the lighter colored track surround the thumb that has the same color as the background.

**Comment by KaelWD** [comment] 2023-10-15 12:52
Duplicate of #18089

**Closed by KaelWD** 2023-10-15 12:52 UTC
Labels: S: triage
