### ISSUE TITLE
[Bug Report][3.1.15] VAutocomplete with chips overlays search text on top of chips

### ISSUE THREAD

**Issue by treardon17** [vuetifyjs/vuetify#17207] opened 2023-04-22 00:53 UTC
### Environment
**Vuetify Version:** 3.1.15
**Vue Version:** 3.3.0-beta.1
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Focus on the VAutocomplete configured for chips.

### Expected Behavior
The "search" text will appear to the right of the chip, or the chip should disappear.

### Actual Behavior
The "search" text appears on _top_ of the chip.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUUtOwzAQvYrxpiA1NhViU7Wo7LgBi7qLfCbUEH9kT4JQlbszTlIpallUYueZN/M+4/2Jv3ovuhb4mm8QjG9yhBdlGdt0We798BwKk2s7VSPYoisdLQACO2qLW8Vr54o8KM48hKgjgsUsQYzWXQUNjZj4QXh51D4yeWaXM/pUjMIbOTNEZSyD9sgiYJtgbbwLyE4sQM16Vgdn2IKSLNJw6WxERmJsm/D7xRs0jWPvLjTV3eIhkY90RMSXfOQiE158RmfpGKfkRU1AVHzNhk7qkUaqFT8i+riWsqwsrVE+3QVhAaX1Ru5oTIbWojaQVc7snsSTeMwKwFysZEXXmaMCosmK4L4jBOJSfDlTQ13/3KA4TZLQSqyeR4mplzV5EZPGFbckwQ5CFsBWEIA+77ZkF2t/pLuYuEqYTPTK9nT+RtuveHH5Mg5X35+9/i/6wJaoDkmxX/K5X3IwLvLDLzvcCHQ=)

### Other comments
I think this PR is relevant: https://github.com/vuetifyjs/vuetify/pull/16579, but I'm not completely sure. This is not an issue for VAutocomplete's configured with the chip feature turned off, but for my use case I need to show an icon/avatar inside the select box.

**Comment by mhio** [comment] 2023-04-25 04:12
related #16186 #16570

**Comment by OscarGTH** [comment] 2023-04-25 13:21
This bug can be reproduced in the documentation as well:
https://vuetifyjs.com/en/components/autocompletes/#usage

**Comment by KaelWD** [comment] 2023-04-27 09:07
Duplicate of #16186

**Closed by KaelWD** 2023-04-27 09:07 UTC
Labels: S: triage

**Comment by sohepalslamat** [comment] 2023-04-27 13:21
To fix this problem just add:
```css
.v-autocomplete.v-text-field input {
    position: inherit;
  }
  ```
