### ISSUE TITLE
[Bug Report] v-combobox `outlined` with `background-color` removes the outline effect

### ISSUE THREAD

**Issue by davidbielik** [vuetifyjs/vuetify#10044] opened 2019-12-26 06:04 UTC
### Environment
**Vuetify Version:** 2.1.15
**Last working version:** 1.5.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.13.6

### Steps to reproduce
* v2.x * actual behavior
`<v-combobox outlined background-color="purple"/>`

* v1.x * expected behavior
` <v-combobox outline background-color="purple"/>`

### Expected Behavior
background-color applies to the outlined border

### Actual Behavior
background-color applies to entire element, effectively removing the outlined effect.

compared to v1.5 behavior: ` <v-combobox outline background-color="purple"/>`

**Comment by jacekkarczmarczyk** [comment] 2020-01-11 13:09
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5422

**Closed by jacekkarczmarczyk** 2020-01-11 13:09 UTC
Labels: triage
