### ISSUE TITLE
[Feature Request] Add prop "disabled" to v-form that will disable all children input elements

### ISSUE THREAD

**Issue by milost1982** [vuetifyjs/vuetify#10267] opened 2020-01-18 11:34 UTC
### Problem to solve
This solves the common problem of having to disable all form elements when some processing is in progress. 

Currently we have to set "disabled" to each child element of the form separately which has downsides:
- developers commonly forgot or miss to do this
- repeatable unnecessary code

### Proposed solution
Add prop "disabled" to v-form that will disable all children input elements.

**Comment by jacekkarczmarczyk** [comment] 2020-01-18 12:04
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1707

**Closed by jacekkarczmarczyk** 2020-01-18 12:04 UTC
Labels: triage
