### ISSUE TITLE
[Bug Report] v-tabs shows wrong active color on dark theme with dark v-app-bar/v-toolbar

### ISSUE THREAD

**Issue by divinespear** [vuetifyjs/vuetify#12748] opened 2020-12-09 06:31 UTC
### Environment
**Vuetify Version:** 2.3.20
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88, Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
1. create `v-app-bar` or `v-toolbar` with `dark` prop
2. create `v-tabs` inside created at step 1
3. change `$vuetify.theme.dark` to `true`

### Expected Behavior
active color should keep white (or something light)

### Actual Behavior
active color changes primary color so invisible or hard to see

### Reproduction Link
<a href="https://codepen.io/divinespear/pen/OJRRXMW" target="_blank">https://codepen.io/divinespear/pen/OJRRXMW</a>

**Comment by dchinu97** [comment] 2020-12-12 15:16
@KaelWD I would like to work on this issue, can I give it a shot?

**Comment by KaelWD** [comment] 2020-12-12 15:22
Sure.

**Comment by dchinu97** [comment] 2020-12-12 21:39
@KaelWD It seems like this issue is a duplicate of [12179](https://github.com/vuetifyjs/vuetify/issues/12179). When dark attribute is used over the light-themed application the application level theme is being used via selector .v-application .primary--text and color="primary" is same as that so text is not visible. I think these changes are already planned for v3

**Comment by Theta-Dev** [comment] 2021-03-21 14:15
Here is a quick and dirty fix for this issue if you dont want to wait for v3.

```
/* Fixing selected tab invisible in dark mode */
.v-tabs-slider-wrapper, .v-tab--active {
  color: #fff !important;
}
```

**Comment by 6XGate** [comment] 2021-06-29 15:27
This actually stopped us from using Vuetify, would be nice if the dark theme was corrected throughout.

**Comment by rhythmone** [comment] 2021-11-03 13:49
I am seeing this behavior on ALL active objects while is dark theme; doesn't seem to be limited to v-tabs. Am I missing something? I set theme to 'dark' and then cannot see a v-switch (same as described above). Am I presuming this is a known issue AND will NOT be fixed cause everyone is looking in v3?

**Comment by KaelWD** [comment] 2021-11-03 15:42
Yes this has been fixed in v3. In v2 only one theme can be active at a time, so a dark component in a light theme still has to use the light theme colors.

**Closed** 2023-09-20 19:15 UTC
Labels: T: bug, C: VTabs, has workaround, S: bulk closed
