### ISSUE TITLE
[Feature Request] Style Compability with Boostrap

### ISSUE THREAD

**Issue by jcjabros** [vuetifyjs/vuetify#5496] opened 2018-10-31 16:19 UTC
### Problem to solve
Projects created with bootstrap cause styles incompatibilities when adding vuetify.js to the project.

### Proposed solution
Add a prefix to all CSS classes to differ from classes with the same name from other frameworks.
Ex: .display-4 to .vtify-display-4.

**Comment by KaelWD** [comment] 2018-10-31 16:30
Duplicate of #1561

Why don't you ask bootstrap to prefix their classes instead?

**Closed by KaelWD** 2018-10-31 16:30 UTC

**Comment by jcjabros** [comment] 2018-11-01 00:53
Because Bootstrap is older than vuetify and one of the most used frameworks.So it will work on created projects or frameworks like Laravel that use Bootstrap for the styles components.

**Comment by sbefort** [comment] 2019-03-13 04:06
> Why don't you ask bootstrap to prefix their classes instead?

Maybe because you copied their class names like d-flex?
