### ISSUE TITLE
[Bug Report] Issue with combination of hide-headers and expanded slot in DataTables

### ISSUE THREAD

**Issue by Thyvo** [vuetifyjs/vuetify#5559] opened 2018-11-09 10:03 UTC
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.16
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 10

### Steps to reproduce
Link discribes the issue (make sure to expand the data table)
Collspan is not updated when not using headers for the expanded row
My current workaround is by adding `:headers="[null, null, null, null]" to the v-data-table component

### Expected Behavior
Collspan to be 4
`<td colspan="4" class="v-datatable__expand-col v-datatable__expand-col--expanded"></td>`

### Actual Behavior
`<td colspan="0" class="v-datatable__expand-col v-datatable__expand-col--expanded"></td>`

### Reproduction Link
<a href="https://jsfiddle.net/eywraw8t/453096/" target="_blank">https://jsfiddle.net/eywraw8t/453096/</a>

**Comment by KaelWD** [comment] 2018-11-09 10:06
Duplicate of #3338

**Closed by KaelWD** 2018-11-09 10:06 UTC
