### ISSUE TITLE
[Bug Report] Timeline does not work correctly in RTL with all cards on the same side

### ISSUE THREAD

**Issue by fabienbellanger** [vuetifyjs/vuetify#7724] opened 2019-07-02 13:15 UTC
### Versions and Environment
**Vuetify:** 1.5.16
**Last working version:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Vivaldi 2.6.1566.44
**OS:** Linux x86_64

### Steps to reproduce
Just add v-timeline on rtl veutify

### Expected Behavior
Edge of card should point to avatar(icon/dots)
Aligment are not correct

### Actual Behavior
They point to other side (opposite)
Good aligment of cards and the line

### Reproduction Link
<a href="https://codesandbox.io/embed/vue-template-wniur" target="_blank">https://codesandbox.io/embed/vue-template-wniur</a>

**Comment by KaelWD** [comment] 2019-07-02 13:20
Duplicate of #7465

**Closed by KaelWD** 2019-07-02 13:20 UTC
Labels: triage
