### ISSUE TITLE
Bug in v-menu: background is #fff in dark theme

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#1261] opened 2017-08-05 11:12 UTC
### Versions
vuetify@0.14.8

### What is expected ?
Dark background in `<v-menu>`

### What is actually happening ?
background is `#fff`

### Reproduction Link
https://codepen.io/cawa-93/pen/JyEPjN?editors=1010

**Comment by johnleider** [comment] 2017-08-07 00:57
Duplicate of #1222

**Closed by johnleider** 2017-08-07 00:57 UTC
