### ISSUE TITLE
[Bug Report][3.1.5] When I use the v-select component with multiple selections and try to select items from the drop-down menu  an error appears: Unhandled Promise Rejection: ReferenceError: Can't find variable: cancelIdleCallback. I checked with other browsers and the problem is only in safari

### ISSUE THREAD

**Issue by yungx21sxx** [vuetifyjs/vuetify#16712] opened 2023-02-19 10:20 UTC
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.2.47
**Browsers:** Safari 16.2
**OS:** Mac OS 10.15.7

### Steps to reproduce
When I try to choose something

### Expected Behavior
I just want everything to work without errors and the modal window was not blocked

### Actual Behavior
An error occurs and the modal window stops responding to user actions

### Reproduction Link
[https://github.com/yungx21sxx/allStarDetailing/blob/main/components/Modal.vue](https://github.com/yungx21sxx/allStarDetailing/blob/main/components/Modal.vue)

**Comment by KaelWD** [comment] 2023-02-19 10:22
Duplicate of #16613

**Closed by KaelWD** 2023-02-19 10:22 UTC
Labels: S: triage
