### ISSUE TITLE
[Feature Request] text field number issue

### ISSUE THREAD

**Issue by PRANAVAN12** [vuetifyjs/vuetify#12580] opened 2020-11-10 06:35 UTC
### Problem to solve
V-text-fields number Validation field allows e letter 

### Proposed solution
V-text-fields Number Validation Makes Allows only Numbers

**Comment by KaelWD** [comment] 2020-11-10 06:44
Duplicate of #3118

**Closed by KaelWD** 2020-11-10 06:44 UTC
