### ISSUE TITLE
[Bug Report] Github repo for vuetify-vscode extensions is not accessible

### ISSUE THREAD

**Issue by rioukevin** [vuetifyjs/vuetify#9929] opened 2019-12-10 07:55 UTC
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Hi,

The repo for vuetify vscode extension is giving a 404 not found,
To reproduce, you can access to the repo (here)[https://github.com/vuetifyjs/vuetify-vscode ] (https://github.com/vuetifyjs/vuetify-vscode)[https://github.com/vuetifyjs/vuetify-vscode]

*Have a nice day and be happy*
Thank you

### Expected Behavior
Acces to the repositories

### Actual Behavior
None

### Reproduction Link
<a href="https://github.com/keriou/keriou" target="_blank">https://github.com/keriou/keriou</a>

### Other comments
Thank you ;-)

**Comment by jacekkarczmarczyk** [comment] 2019-12-10 07:57
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9435

**Closed by jacekkarczmarczyk** 2019-12-10 07:57 UTC
Labels: triage
