### ISSUE TITLE
[Bug Report] Drawer mini is jumps when on left side.

### ISSUE THREAD

**Issue by twoco** [vuetifyjs/vuetify#8007] opened 2019-07-25 09:57 UTC
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
You see it when toggle mini flag or active expand-on-hover.
Set `expand-on-hover=true` and hover on it. Toggle right (left) align.

https://vuetifyjs.com/en/components/navigation-drawers

![demo](https://user-images.githubusercontent.com/53160891/61864567-f0088980-aed1-11e9-9f5c-c52547d4b6e2.gif)

### Expected Behavior
The drawer should smoothly translate between mini and expended. Also on left side. 

### Actual Behavior
The content jumps when it is on the left side. On the right side it's smooth. 

### Reproduction Link
<a href="https://codepen.io/anon/pen/PMzBRZ?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/PMzBRZ?&editable=true&editors=101</a>

**Comment by twoco** [comment] 2019-07-25 10:00
I think it will be fixed when the content align is set to left. It looks like it's set on right. So it shrinks from right side and looks like it jumps.

**Comment by johnleider** [comment] 2019-07-25 14:26
Ultimately has to do with the fact that content is default aligned to the left which naturally makes it look better on right drawers. You can see there is no different with the transition slowed down.

With that being said, this is something I tackled in testing and was unable to solve. Will take another look.

**Comment by beerwin** [comment] 2020-01-07 14:13
A small help for fixing this (unfortunately I don't have enough time to make a PR -- i used CSS hacks to fix it for myself)

I think, this CSS rule causes the jumps: 

`.v-navigation-drawer--mini-variant .v-list-item {
  -webkit-box-pack: center;
  -ms-flex-pack: center;
  justify-content: center;
}`

I know, that centering the list item contents here helps in the alignment of the icon in the mini variant, but it causes more issues than it solves. The list item contents should be aligned to start (as they are in the normal drawer), and the icons have a size or spacing enough to look nice with the mini drawer (even if the latter has to be set by the user).

**Comment by johnleider** [comment] 2020-01-17 19:39
Duplicate of #2830 

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-17 19:39 UTC
Labels: T: bug, help wanted

**Comment by BennyCus** [comment] 2020-04-01 11:26
simple solution:
just put " class='justify-start' " to the v-list-item and your save

**Comment by inyoursafespace** [comment] 2020-04-01 11:41
worked fine to me:
just add class="justify-start pl-5" to all "v-list-item".

**Comment by 4KDA** [comment] 2021-09-13 09:21
> worked fine to me:
> just add class="justify-start pl-5" to all "v-list-item".

Thanks!

**Comment by johnleider** [comment] 2021-09-14 17:12
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
