### ISSUE TITLE
[Bug Report] IE 11 compatiblity

### ISSUE THREAD

**Issue by usb248** [vuetifyjs/vuetify#4167] opened 2018-05-30 20:10 UTC
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
For example, open the v-navigation-drawer

### Expected Behavior
It should work for IE11 I think.

### Actual Behavior
Error : SCRIPT445: Object doesn't support this action

### Reproduction Link
[https://codepen.io/anon/pen/eKmMqZ](https://codepen.io/anon/pen/eKmMqZ)

### Other comments
Normally, according to the doc on https://vuetifyjs.com/en/getting-started/quick-start#ie11-support. We only need to include babel-polyfill... but not only.
new Event' does not work in IE11 (and Safari)...
This line : window.dispatchEvent(new Event('resize')); need a polyfill for CustomEvent.
[See compatiblity](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent)

**Comment by johnleider** [comment] 2018-05-31 03:50
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4031

**Closed by johnleider** 2018-05-31 03:50 UTC
