### ISSUE TITLE
[Documentation] VCalendar - Slot usage example is not working

### ISSUE THREAD

**Issue by raphael-jolimoi** [vuetifyjs/vuetify#9744] opened 2019-11-20 14:25 UTC
### Environment

**Browsers:** Chrome 78.0.3904.87
**OS:** Linux x86_64

### Steps to reproduce
If you look at the code and the result, you can see that the slot is actually not working. Just the fact that the custom classes are not in the result shows it. Also the object eventsMap doesn't exist.

I succeeded in using the slot in my code though.

### Expected Behavior
Slot usage example should be working

### Actual Behavior
Slot doesn't seem to do anything

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/calendars#weekly" target="_blank">https://vuetifyjs.com/en/components/calendars#weekly</a>

**Comment by milost1982** [comment] 2019-11-30 20:56
I have also reported an issue (##8525) related to the same problem several months ago. Still no response from @ClickerMonkey who is author of calendar component for Vuetify...

**Comment by KaelWD** [comment] 2019-12-02 13:42
Duplicate of #8525

**Closed by KaelWD** 2019-12-02 13:42 UTC
Labels: C: VCalendar, T: documentation
