### ISSUE TITLE
[Bug Report] v-select default value gets reset after form reset

### ISSUE THREAD

**Issue by kunalahirrao** [vuetifyjs/vuetify#11489] opened 2020-05-26 12:56 UTC
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Windows 10

### Steps to reproduce
Resetting value manually For eg: this.defaultValue = ""

### Expected Behavior
Reset form should reset the form but should keep selected in place

### Actual Behavior
It resets the defaultValue

### Reproduction Link
<a href="https://codepen.io/spider007/pen/PoPgvrp" target="_blank">https://codepen.io/spider007/pen/PoPgvrp</a>

**Comment by KaelWD** [comment] 2020-05-26 13:49
Duplicate of #3316

**Closed by KaelWD** 2020-05-26 13:49 UTC
Labels: triage

**Comment by kunalahirrao** [comment] 2020-05-26 14:15
That means we have to reset the defaultValue manually by setting this.defaultValue=""
