### ISSUE TITLE
[Bug Report] User input for combobox does not bind to v-model unless element loses focus

### ISSUE THREAD

**Issue by tmpjr** [vuetifyjs/vuetify#9732] opened 2019-11-19 18:01 UTC
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Mac OS 10.14.6

### Steps to reproduce
Select an option from the drop down and click the check icon button. Observe in console that the object is properly bound to v-model. Now, clear and enter some custom text and then click the button again. Observe console output. Do the same steps over again, but this time make sure the combobox loses focus by clicking outside the element somewhere. Then repeat clicking the button.

### Expected Behavior
I expect v-model to properly bind the user input or the selected drop down without the combobox losing focus.

### Actual Behavior
Only selecting a drop down value works as expected. Input text from the combobox is not bound to v-model if the combobox does not lose focus.

### Reproduction Link
<a href="https://codepen.io/tmpjr/pen/JjjxjGR" target="_blank">https://codepen.io/tmpjr/pen/JjjxjGR</a>

**Comment by KaelWD** [comment] 2019-11-20 04:23
Duplicate of #4679

**Closed by KaelWD** 2019-11-20 04:23 UTC
Labels: triage
