### ISSUE TITLE
[Feature Request] Multiple Labels on VSwitch

### ISSUE THREAD

**Issue by jlgoff3** [vuetifyjs/vuetify#12999] opened 2021-01-21 15:20 UTC
### Problem to solve
A potential use case for a switch is to label it on either side with two mutually exclusive options (e.g. a light/dark mode switch). This differs from a checkbox by explicitly labelling the separate states, rather than expecting the user to know the default state (e.g. a dark mode checkbox expects the user to know that the default is light mode). For 3 or more mutually exclusive options, radio buttons are fine, but they use a lot of vertical space for only 2 options, which could be solved with a switch. This is beyond the Material design spec for switches, but I believe it's a common enough pattern to be addressed.

### Proposed solution
Currently, VSwitch supports both a label prop and a label slot. This can remain the same, allowing for backward compatibility and consistent default behavior according to Material Design.
I'm proposing the introduction of two new prop/slot pairs, named label-left and label-right, allowing developers to describe their default option and the alternate option. label will continue to fill the label-right slot by default. This would also solve the use case of Issue #7283.

**Comment by ibrahimBeladi** [comment] 2021-02-04 08:39
There's a hacky workaround using `append` and `prepend` slots.
However, having `label-left` and `label-right` will be cleaner and less hacky.

**Comment by scscgit** [comment] 2021-02-07 14:52
I'd like to also ask about the possibility of introducing **vertical labels**, i.e. above and below the switch, for the scenarios when we may need to place multiple switches horizontally next to each other in a narrow space (for example inside a table header slot).

Theoretically there's at least the `hint` which could be used with `persistent-hint`, but it doesn't use any proper attributes, isn't exposed as a slot (has small font), and there's no way to easily center the larger of both of them.

As a part of brainstorming for this issue, a new parameter `label-direction` could optionally support an array of (4) enum strings, in which case there would be multiple slots (e.g. `label-above`) exposed.

**Comment by jacekkarczmarczyk** [comment] 2021-02-07 14:56
@ibrahimBeladi 

> However, having label-left and label-right will be cleaner and less hacky.

it would be rather `label` and `label-opposite` or something like this, much better in terms of RTL

**Comment by johnleider** [comment] 2021-11-23 19:05
duplicate of #7283

**Closed by johnleider** 2021-11-23 19:05 UTC
Labels: T: feature, C: VSwitch
