### ISSUE TITLE
[Bug Report] IE11 - cursor flashes after selection

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#10504] opened 2020-02-07 09:41 UTC
### Environment
**Vuetify Version:** 2.2.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Problem exists only on IE11.

1. Click the dropdown to expand it.
2. As you can see, flashing cursor is visible.

![ie_cursor_flashing](https://user-images.githubusercontent.com/17653648/74018434-3321da00-4996-11ea-88a8-d10199ea5ed5.gif)

Because CodePen does not support IE11 you can check that in your local environment or just go to the Vuetify docs on IE11. 
https://vuetifyjs.com/en/components/selects#selects

### Expected Behavior
There should be no flashing cursor.

### Actual Behavior
The cursor is flashing.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/bGdGPOo" target="_blank">https://codepen.io/mikilll94/pen/bGdGPOo</a>

**Comment by KaelWD** [comment] 2020-02-07 09:49
Duplicate of #4506

**Closed by KaelWD** 2020-02-07 09:49 UTC
Labels: triage
