### ISSUE TITLE
[Bug Report] v-file-input is unable to be worked on IE11

### ISSUE THREAD

**Issue by choi-sum** [vuetifyjs/vuetify#8670] opened 2019-08-22 04:26 UTC
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Internet Explorer
**OS:** Windows 7

### Steps to reproduce
<v-file-input> does not work in IE11

<v-file-input label="File input" :readonly="false" @change="upload" v-model="test"></v-file-input>

data: () => ({
    test: [],
  }),
methods: {
    upload(file) {
      console.log('CHANGE:',file);
}

### Expected Behavior
Files[] object is expected to be return in 'change' event and v-model.
File name should be displayed in the text area after selecting a file

### Actual Behavior
empty file object is return and no file name is displayed.  Two change events is triggered and the second one will empty the file object.

### Reproduction Link
codeped does not support IE, so unable to write reproduction code on it.

**Comment by nekosaur** [comment] 2019-08-23 07:03
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8693

**Closed by nekosaur** 2019-08-23 07:03 UTC
Labels: duplicate
