### ISSUE TITLE
v-tabs-slider moving out of position

### ISSUE THREAD

**Issue by SquareBeard** [vuetifyjs/vuetify#2071] opened 2017-10-08 00:14 UTC
### Steps to reproduce
Click on the top left "hamburger" icon to toggle the navigation drawer

### Versions
0.16.3

### What is expected ?
The v-tabs-slider should stay under the active tab.

### What is actually happening ?
The v-tabs-slider moved during the resize.

### Reproduction Link
https://codepen.io/anon/pen/bovboW

**Comment by jacekkarczmarczyk** [comment] 2017-10-08 01:18
Duplicate of https://github.com/vuetifyjs/vuetify/issues/684

**Closed by jacekkarczmarczyk** 2017-10-08 01:18 UTC
Labels: pending review
