### ISSUE TITLE
[Bug Report] Navigation mini variant not resizing content when using mini-variant-width with expand-on-hover

### ISSUE THREAD

**Issue by stephenhoran** [vuetifyjs/vuetify#10929] opened 2020-03-24 16:19 UTC
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.2
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.14.6

### Steps to reproduce
Codepen does not reflect expand-on-hover properly.

- Mouse over mini variant, it expands and content in v-content shifts properly
- Mouse off and mini variant returns however often the v-content does not shift back correctly

### Expected Behavior
Expect v-content to shift back as it does without using mini-variant-width prop.

### Actual Behavior
Content is often shifted as if the navigation bar is fully expanded.

### Reproduction Link
<a href="https://codepen.io/horan116/pen/XWbxzMd" target="_blank">https://codepen.io/horan116/pen/XWbxzMd</a>

### Other comments
This was a work around but in place to workaround issue #10862. Once that issue is resolved this should no longer be needed however does appear to be a bug.

**Comment by naime-hossain** [comment] 2020-05-07 08:20
Did you find any work around ?

**Comment by prasannapattam** [comment] 2020-08-24 01:20
There is no workaround. Other related bugs (#10862, #10903) are closed without any fix. 
I think the workaround could be don't use expandOnHover from inside the navigation drawer

**Comment by johnleider** [comment] 2020-12-16 18:17
Duplicate of #8223

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-16 18:17 UTC
Labels: C: VNavigationDrawer, T: bug
