### ISSUE TITLE
[Bug Report] v-card not rendering as expected

### ISSUE THREAD

**Issue by MickaMx** [vuetifyjs/vuetify#6771] opened 2019-03-20 13:42 UTC
### Versions and Environment
**Vuetify:** 1.5.4
**Vue:** 2.5.17
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
Clone the Git,
Run npm run serve
Open it on IE11

### Expected Behavior
The "Recherche" button should be inside the V-card

### Actual Behavior
The button is not totally inside 

### Reproduction Link
<a href="https://github.com/MickaMx/Vuetify_issue_IE11" target="_blank">https://github.com/MickaMx/Vuetify_issue_IE11</a>

**Comment by johnleider** [comment] 2019-03-21 16:36
Duplicate of #6671

**Closed by johnleider** 2019-03-21 16:36 UTC
Labels: duplicate
