### ISSUE TITLE
[Bug Report] Slider not visible on v-tabs when nested in v-dialog

### ISSUE THREAD

**Issue by aquintero** [vuetifyjs/vuetify#4520] opened 2018-07-06 20:45 UTC
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
1) Open v-dialog with nested tabs using activator slot (bug does not occur when setting :value="true")
2) Slider is not visible

### Expected Behavior
Slider should be underneath selected tab

### Actual Behavior
slider height is 0

### Reproduction Link
[https://codepen.io/anon/pen/dKBxpR](https://codepen.io/anon/pen/dKBxpR)

### Other comments
Current work around is to reuse the dialog state to conditionally render the nested v-tabs.
The bug seems to occur when tabs are rendered to the DOM but not the screen.

**Comment by jacekkarczmarczyk** [comment] 2018-07-06 21:03
Duplicate of #1978

**Closed by jacekkarczmarczyk** 2018-07-06 21:03 UTC
Labels: duplicate
