### ISSUE TITLE
[Bug Report][2.5.3] v-btn 

### ISSUE THREAD

**Issue by SadPossum** [vuetifyjs/vuetify#13779] opened 2021-06-09 13:08 UTC
### Environment
**Vuetify Version:** 2.5.3
**Vue Version:** 2.6.1
**Browsers:** Firefox 89.0
**OS:** Windows 10

### Steps to reproduce
when clicking and quickly changing the right and left mouse buttons, the button color button color state is not reset

### Expected Behavior
the color state of the button should be reset

### Actual Behavior
button color state is not reset

### Reproduction Link
<a href="https://codepen.io/sadpossum/pen/MWpBZpQ" target="_blank">https://codepen.io/sadpossum/pen/MWpBZpQ</a>

![изображение](https://user-images.githubusercontent.com/61198926/121360164-d8f3a900-c93c-11eb-8a0c-4dff57bcd7ca.png)

**Comment by jacekkarczmarczyk** [comment] 2021-06-09 13:10
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4185

**Closed by jacekkarczmarczyk** 2021-06-09 13:10 UTC
Labels: triage
