### ISSUE TITLE
[Bug Report] v-btn disappears when dark prop and disabled prop used together

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#4682] opened 2018-07-21 22:20 UTC
### Versions and Environment
Vuetify: 1.1.7
Vue: 2.5.16
Browsers: Chrome 68
OS: WIndows 10

### Steps to reproduce
In the codepen, toggle the `dark` and `disabled` props using the provided buttons so that both are set to `true`, then note that the green button disappears rather than taking on a disabled state.

### Expected Behavior
Combining the `dark` prop with the `disabled` prop on a `v-btn` when using a darker background color should not cause the button to disappear. Though removing the dark prop allows the button to disable/enable normally, using the `dark` prop should not cause this unexpected behavior.

### Actual Behavior
Combining the `dark` prop with the `disabled` prop on a `v-btn` causes it to disappear. Removing the `dark` prop causes the `disabled` prop to function normally.

### Reproduction Link
https://codepen.io/185driver/pen/vagvdy?editors=1011
---

I found three closed issues that are similar to this issue but different, so would like to suggest this issue as a bug to be addressed:
[687](https://github.com/vuetifyjs/vuetify/issues/687) [578](https://github.com/vuetifyjs/vuetify/issues/578) [189](https://github.com/vuetifyjs/vuetify/issues/189)

**Comment by KaelWD** [comment] 2018-07-22 04:12
Duplicate of #4482

**Closed by KaelWD** 2018-07-22 04:12 UTC
