### ISSUE TITLE
[Bug Report] Icon types are not complete

### ISSUE THREAD

**Issue by P4sca1** [vuetifyjs/vuetify#7889] opened 2019-07-20 17:32 UTC
### Versions and Environment
**Vuetify:** 2.0.0-beta.9
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.15.0

### Steps to reproduce
-

### Expected Behavior
In `vuetify/types/services/icons.d.ts`:

`VuetifyIconOptions.iconFont` is missing `faSvg`.

The `VuetifyIcons` interface seems to be missing `file: VuetifyIcon`.

(Note that the codepen is just a dummy pen and does not contain relevant info for this issue.)

### Actual Behavior
-

### Reproduction Link
<a href="https://codepen.io/anon/pen/PMqmJG" target="_blank">https://codepen.io/anon/pen/PMqmJG</a>

**Comment by johnleider** [comment] 2019-07-20 19:20
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7387

**Closed by johnleider** 2019-07-20 19:20 UTC
Labels: triage
