### ISSUE TITLE
[Feature Request] v-menu open at custom location

### ISSUE THREAD

**Issue by nickmayn** [vuetifyjs/vuetify#16665] opened 2023-02-14 20:22 UTC
### Problem to solve
When migrating from vuetify 2 to vuetify 3 the property on v-menu to place it in a custom position was removed. The properties are listed below:

- position-x
- position-y 

### Proposed solution
These features should be added back into the v-menu to enable a popup that can be anywhere the user specifies on the screen. For my particular use case this involves being able to link custom points in mapbox to the information and having a card that hovers next to the point.

**Comment by websitevirtuoso** [comment] 2023-02-14 21:57
We have this feature. we can set offset from element. You should double check documentation

**Comment by nickmayn** [comment] 2023-02-14 22:47
offset currently has no documentation and when I try to pass it as a list to the existing v-menu component it also fails to update properly.

![Image 2-14-23 at 5 44 PM](https://user-images.githubusercontent.com/33676065/218880244-79ba89e0-9c78-42c4-8e41-fa83c9a9fcbc.jpeg)

passing into the v-menu like so

```
<v-menu
  :offset="[500,500]"
>
  <v-card>
     .....
  </v-card>
</v-menu>
```

**Comment by laplacetw** [comment] 2023-02-15 02:45
I try the codepen  below with Edge ver.110.0.1587.41 .
https://codepen.io/laplacetw/pen/ExexOMZ

The "location" / "offset" of V-Menu API can work fine individually after rendered. But there are some problems If we trigger it the second time or using both of them.

**Comment by nickmayn** [comment] 2023-02-15 02:55
So part of the issue too is when using the v-menu I am not tying it to a vuetify component. Essentially I am trying to render information about a point being rendered with mapbox when I hover over it. Due to this I can't just attach it to the location of a vuetify component. I need to be able to reach in and grab the points position on the screen and then render the v-menu where the point is at. This is where it was nice to hard set the position-x and the position-y. See example here: https://codepen.io/dzhamshed/pen/wvGwrqz

**Comment by KaelWD** [comment] 2023-02-15 05:31
Duplicate of #15658

**Closed by KaelWD** 2023-02-15 05:31 UTC
Labels: S: triage
