### ISSUE TITLE
[Bug Report] Material Icon missing

### ISSUE THREAD

**Issue by marcovc** [vuetifyjs/vuetify#4172] opened 2018-05-31 18:10 UTC
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.117
**OS:** Linux x86_64

### Steps to reproduce
1. render a "label_off" icon

### Expected Behavior
Should look like the "label_off" icon in Material Design Icons website.

### Actual Behavior
Looks like the "label" icon in Material Design Icons website, with some extra space.

### Reproduction Link
[https://codepen.io/donpuerto/pen/EQoJYQ/](https://codepen.io/donpuerto/pen/EQoJYQ/)

**Comment by KaelWD** [comment] 2018-05-31 18:15
Duplicate of #4107

**Closed by KaelWD** 2018-05-31 18:15 UTC
