### ISSUE TITLE
[Feature Request] Add right side version of Vertical tabs (mirrored) with API

### ISSUE THREAD

**Issue by kappaflow** [vuetifyjs/vuetify#16933] opened 2023-03-16 19:44 UTC
### Problem to solve
Sometimes you need to add tabs on the right side (mirrored) for a more accessible navigation, but currently its impossible to do with `v-tabs` API .

### Proposed solution
Add API option that set the border to the opposite (right) side like [in this example](https://play.vuetifyjs.com/#eNrNWFuPEzcU/iunedkiZSZcilptlwoErdSHIiRKXwhCzoyTmPXYgy/ZRWj/e79je3JnYcuteYhin+NzP99x/PL9aBVlUPN39Rs/Oh2prrcu0HtqnBRB/pNpdEVzZzs6KbwnUzM18jKxNtb4QIVAD3YP/vh+aojCUnbylNJvolbORdTh77x50gp3fjJm0hW+r279OjWj8ehR39eQCYvOfONUH35jjqKySFgLFEHQj7eGJZGTITqzWcMCMYMq2wdlTXUnq+PPVf7BmtPibLLWdubDOy3xo15VOJ6/WeY0dMpUF6oNy1Oaq1AhAkGaQD/k4AkT4AOE5SOvX3utWumyOVrOwylF4+UeP6xWiyVot/NhWFL0nwXZ9Rox5RCctWpFqn0wHYm+n454axrOVhVWKUL4YOWXEvIbLbwHZy+q+5kVvIm7Ea4d2POJYK2eCbfZIyRWW8fHneqEezcdbYhbZ7dPV0EFmPzCw9tnzs6VlmeTfeqW2g1te5c9HExvq7mWl8RflbMXyYs93RfKtPaCVlVnW6lxBjEv3h7hqxSiSSuhowTrUBAH/OkERwmqRa69o+QqyMtjZDCs87H3eS5bElq9jaIjFLFTjfTUieiUr+mJNbKh3voonURT6T4GZJ6Ea2JNf1k3UyQamkvN3L8HBSFzGRdKBEK24JqxhjrUP8hJE2k1k87WR22csJE3sv4pFKrexw7l6qMfk4vBYbVSQcgxraQPahY1dmQcU2c1b8ATqcekRcNmPZJGCkNBah3hOds6phmsNC2OedmO1wEQDWSIEJRnv8ZkomkgoERP2xnahwNxuPM8+h4ClfcyhcQor8mrQAIK2Rz8XILBSYdf2Ykbx2hdpt2sun2khvLn2VL47GvLHVXTH9E3sEq+jXJYzKXrACHw37bKgtaUlD/DSRCkB3NJJQX4aN2YgjKNaiOQR4ad1YLXHqiBPoSoMXFwIGttyEwLxAYlIy3FkHRe4/zh7nXFP1D3OxDbWy14o/68+y37MzcZZ2Boo61SwtxpUN8oWC5FxJ367QQh8j4IUFOpE5Bd8nyEO+jXUvFoEu4VUmDh3cyaClK1Jbe5d9E9YBgTcg6GsEELHggsKKNG6ccBU3KRwEBUvWhVr3yjzCLXHmEsCmCCdY2q6XF0YqYwKnFmEbUgL3ol0WabUkpdJ6PyANehx4fmxPSSrlVca6ijmp5yRNC+BInQ+qUQZyf8Geq+U04w0pQB50o6JyCvBG0AlXV6cuetGbiRCSQAIdszBBmEpomdBxQCnNSQTKA757umPw0tsVhyioAyktIdQFCrGuCERxAydAzjYGNI0dsvBS5CTrC3rcrw8sWSgjTzxQ8YJnL+E+pswbhtBbAfbsYFnM6A20SHmZHSxJgEmxdOrFQr4PwChdlhuA3zKk2axnYoPEs41aCSQwEyhCYpbwI6FBiXC46RLOnJ3VOUFVrO75DJYV7ImEfKF4pKnscwo4+OR1ueXCWxJSJDn9b0AuYKp9jGdb8NzpcZWWqN3NIarshethgZTzhyqeWuHx5fZ5zlK8oKBhrB7m0uKekC8hHbkbo2crEj3xsoyRNr+/LAAw1tBMhCd6dp9yb6sHZ5KIwB9PKw3EYFaVRXkj8uPZPvFkOPQ/1WY+Q5yY34fx6E977lICzwcnB54PQD4ghYmHKyC7dz0SiEl+9g3MEJFZDx74Cen1VnX6d3HjsBB8VCMTD8p5jmKOYo5MHP3uFPJNdzdiEh62ZqR7jYIf65b1O3pHkxLiFXiHkq/t2pidt7j/GhEKQsD+bllOKvRsZRtrbc4hXOuYT7g3PfsYs2tIP/qWLmd+Xs/W3cJbbKYcag8UBG2QbVCL3Pc82/ZP6kP/FcFusng/u3+8tdrkMI4JcGBXT6xD+qiRXAdyS4XasqdIrFcDkWWT55JLLQ/+lGfeB2/hGjtG3Ov5ZFH4DJj4dJel/1aLDPiVXZ8zsPHXjTWK+3Kjo9x2CZ3mvSmlf5LWc4dDbZev/hZ6n0QIV2DDGzrV+s8GyWX5SqTvR4zrMGz2fp1WlaCH46Wj/DoaSj5PV0tAyh96eTSTT9+aLGbJ08BG3iUDQYj1Vru4f36rv1Tz/DJB+292vpu2qGlxk8+UDjdFRe1pJwfgD8kIJChtw79S9ZbNmqNILHcg/kTaAEbVg55BBo7q41fo93x4E92oET5THwCgHVypz7vVg2PsXx5WDazb1LEvj4K9ZyNR5l66AvnRi9+hfxkpyY)
```
.v-tab__slider {
  left: unset;
  right: 0;
}
```

**Comment by KaelWD** [comment] 2023-06-07 04:10
Duplicate of #8766

**Closed by KaelWD** 2023-06-07 04:10 UTC
Labels: S: triage
