### ISSUE TITLE
[Bug Report] Filled text fields and date/time pickers

### ISSUE THREAD

**Issue by hackerESQ** [vuetifyjs/vuetify#9075] opened 2019-09-24 03:06 UTC
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Edge 78.0.244.0, Google Chrome, Mozilla Firefox, Safari
**OS:** Mac OS 10.14.6

### Steps to reproduce
See reproduction [link](https://codepen.io/hackeresq/pen/eYOxGzg?editors=1010). Try hovering/click the label on the "filled" text fields. 

### Expected Behavior
The .v-input__slot darkens in color indicating that clicking should enable the date picker. 

### Actual Behavior
The date/time pickers do not open when clicking on the .v-input__slot element, which is counterintuitive.  

### Reproduction Link
<a href="https://codepen.io/hackeresq/pen/eYOxGzg?editors=1010" target="_blank">https://codepen.io/hackeresq/pen/eYOxGzg?editors=1010</a>

**Comment by valentingavran** [comment] 2019-09-24 08:32
I noticed that too

**Comment by jacekkarczmarczyk** [comment] 2019-11-13 07:16
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7610

**Closed by jacekkarczmarczyk** 2019-11-13 07:16 UTC
Labels: C: VTextField, triage
