### ISSUE TITLE
[Feature Request] VContainer safe-area-inset property

### ISSUE THREAD

**Issue by valentingavran** [vuetifyjs/vuetify#13118] opened 2021-02-16 12:02 UTC
### Problem to solve
Devices with a notch need specific paddings in landscape mode when using the meta attribute `viewport-fit=cover`.

Currently there is the possibility to add the following CSS class to the `VContainer` if someone wants to use the predefined device paddings provided by `safe-area-inset`:

```CSS
.use-safe-area{
padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);
}
```

But the problem is that in portrait mode or on devices without a notch, the default paddings of the `VContainer` are overwritten, since `safe-area-inset-*` returns 0px.

### Proposed solution
There should be a `VContainer` property that fixes this problem. It checks if `safe-area-inset-*` is greater than 0px and then sets this value as the new `VContainer` padding. However, if the `safe-area-inset-*` padding is 0px, the default `VContainer` padding should be used.

**Comment by KaelWD** [comment] 2021-08-14 10:15
Duplicate of #13025

**Closed by KaelWD** 2021-08-14 10:15 UTC
Labels: S: triage
