### ISSUE TITLE
[Bug Report][3.3.13] v-tooltip next to suspense crash the browser

### ISSUE THREAD

**Issue by Zehir** [vuetifyjs/vuetify#18097] opened 2023-08-20 14:52 UTC
### Environment
**Vuetify Version:** 3.3.13
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Windows 10

### Steps to reproduce
Remove the comment around the v-tooltip in App.vue
Chrome and edge crashed

### Expected Behavior
Not having the browser to crash

### Actual Behavior
He crashed

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVE1rGzEQ/SuKLnbAWgWSk3FCSi89FlroIZuD7B03avWFNF43GP/3jrRrZ3ddSgrFYHtm3rynedrZpwP/EELV7oAv+Sptog7IEuAuPNSOMW2Dj8gOLMKWHdk2estmBJ4Nih+9DX2lkjnIbARYyY6OiChAsMEohEK7aoUKnUIJNt6h0g5in6LklRDn/61A7w3qwBB+4X3Nv3Zhzc94Qp0UWCuS8bhUG9StQh+p4cBC9CGx46ilUK/RUcdau4ZwBUWYXmAlS32oIkeDdKnz+fKomD9CvJW/7FIAl94aKJdtelgVtwY8E2QmHjuTM51xo3PwBe/uQlgVqh/JO7rMQ26o+wLNtGQlk3N0Pzmu+QtiSEspN42jtgaMbmPlAKULVj4STMadQ21BNN4+3la31Z1sdMJhuoJkxTr6fYJIJDVfDGRQb1/fIdUjSeGuuhHKhBdV3XRKfUkYtU5Z6kJCkm4LUURwDUSI751s0jacblK6mDCrH2t3JN+Ndj/TxPJNKnY/nQ75X0YvpJnxuRM+Ldq/rm0uG0BmXz9TVidg98zBnvXRfLtztDfesXmE5E0L16fnpo/ns09gjGfffDTN1ey6mEHf+VdKRg9sIvb0nXhJ/U/oKUTtlR4ciDB/f3Xkl4DYajANLa71ZChtLtHVnMmL1TgueLlZsmxkMX/+DV07pac=)

### Other comments
Exist in  3.4.0-alpha.0  and 3.0.0

I first discovery this issue in my setup without crashing the browser and while reproducing the issue on the playground I crashed the browser. I don't know if the 2 issues are related or not.

In my setup I get this error message :

```
[Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. 
  at <BaseTransition onAfterLeave=fn<onAfterLeave> appear=true persisted=true  ... > 
  at <Transition name="fade-transition" appear=true persisted=true  ... > 
  at <MaybeTransition appear=true persisted=true transition="fade-transition"  ... > 
  at <VOverlay ref=Ref< Proxy(Object) {…}[[Handler]]: Object[[Target]]: Object[[IsRevoked]]: false > class="v-tooltip" style= {}  ... > 
  at <VTooltip location="right" activator="parent" > 
  at <VDefaultsProvider key="content-defaults" disabled=true defaults= {VIcon: {…}} > 
  at <VBtn height="48" block="" variant="outlined"  ... > 
  at <VHover> 
  at <BtnRoundedCircle to="/" > 
  at <VListItem key=2 class="ma-1 justify-center" > 
  at <PerfectScrollbar> 
  at <VListChildren items= [] > 
  at <VList id="#nav-level-one-list" nav="" class="d-flex flex-column pa-0"  ... > 
  at <VNavigationDrawer width="72" permanent="" > 
  at <NavSidebarLevelOne> 
  at <VLayout> 
  at <Default onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {…} > > 
  at <RouterView> 
  at <VApp> 
  at <App>
```

If I remove the `await` on the `Comp.vue` it's  not crashing
If I remove the tooltip it's not displaying any errors

**Comment by KaelWD** [comment] 2023-08-21 06:41
It's a vue bug.

Duplicate of #17718

**Closed by KaelWD** 2023-08-21 06:41 UTC
Labels: S: triage

**Comment by Zehir** [comment] 2023-08-21 07:26
If anybody find this issue in the future you can use this workaround by using the [defineAsyncComponent](https://vuejs.org/guide/components/async.html) method;

[play.vuetifyjs.com](https://play.vuetifyjs.com/#eNqtVMFu2zAM/RXOlyRAbAVrT1kStNhlxwEtsEPdgxPTqzZZEiTZWRD430fJTmI7wdZDTzYfH/lISuLLMXrUOqkrjJbRyu4M1w4sukpvUgnAS62MgyMYLKCBwqgSJkSepHLgzrHgEh/tQe6+KgIlSjfin9lPQu0vpJaSMI/4MgJzp6R14CFY38w9nc5gvekyTvvhs1kqV6xthFogw2GpReYwNLSq40y3vQWDlFxG6U0HBdApJRzX4PCPW6fRc2um0ZlDrFNWqGMrlFtmO8frzClDAUfQRmkLzSAkpN46SRFbLnPiBRZxOoEVC/6+ChsU30Ln+i7YU2U1SnthEeYnslmFwfSCR0yfbTgCj7QTGohH86gddlxmOvlllaT7cvQBaeegRpYQEI/RUXg7jd6c03bJ2C6XFJaj4LVJJDomdckeiMZMJR0vMc5V+XCX3CX3LOfW9eEEbRlvjdpbNJQkjeY9GceLwzukOiYp3CeLOBP6LUsWrVLnikW2tV7qSoKRbo0mNihzNGje29korN/dyHXVoVdvUtnQ3AWXv+1o5Dsbxv1yKvJDWg9JfcbXVvj0pm5uhv/uBgCBDsrDd8K5RXrIEvfQWdOikvRglISpQatEjbPT3QHKF5Dp5BsKoeCHMiL/NKF37Z0Nfds/xro9UdqflJ2quB0xJmX7jPcKO+dr8X6Rl9po13Tl0QSe6Vqq6rSDrsqefekqncPnxaK1Gv/591ryyyYuOIqcFkSp6AxpQ1DVaQTs6jU28yhcJjqlwalGr38BHPDqRA==)
