### ISSUE TITLE
[Feature Request] Tag for flex or button component to make width / height match

### ISSUE THREAD

**Issue by ch-luke** [vuetifyjs/vuetify#2964] opened 2018-01-09 00:25 UTC
### New Functionality
Easily create square cards / buttons

https://codepen.io/chluke/pen/wppZRV

### Improvements
"v-flex height-match-width" or "v-btn square"

This would be sweet.

### Bugs or Edge Cases it Helps Avoid
Can't see any.

**Comment by ch-luke** [comment] 2018-01-16 20:21
Yeah defo!

**Comment by peluprvi** [comment] 2018-04-26 20:39
Related to https://github.com/vuetifyjs/vuetify/issues/1536 and https://github.com/vuetifyjs/vuetify/issues/2389

**Comment by KaelWD** [comment] 2018-07-03 11:42
Duplicate of #1536

**Closed by KaelWD** 2018-07-03 11:42 UTC
Labels: T: feature
