### ISSUE TITLE
[Bug Report] Menu as popover clipped on first open

### ISSUE THREAD

**Issue by wanton7** [vuetifyjs/vuetify#3732] opened 2018-04-02 06:55 UTC
### Versions and Environment
**Vuetify:** 1.0.11
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.109
**OS:** Android 7.1.1

### Steps to reproduce
Go to https://vuetifyjs.com/en/components/menus
Bottom of page click "menu as popover" and menu will be clipped and wrong position. When you open it second time or even scroll page it goes to correct position.

### Expected Behavior
Popover to be placed correctly.

### Actual Behavior
Popover is clipped right side of screen.

### Reproduction Link
([https://vuetifyjs.com/en/components/menus](https://vuetifyjs.com/en/components/menus))

![img_20180402_093551](https://user-images.githubusercontent.com/1009930/38186450-c51fab44-365b-11e8-89e7-c368e02e6430.jpg)

**Comment by KaelWD** [comment] 2018-05-15 16:51
Duplicate of #3438

**Closed by KaelWD** 2018-05-15 16:51 UTC
Labels: T: bug
