### ISSUE TITLE
[Bug Report][2.5.1] Tabs v-model doesn't track actual tab index if tabs change

### ISSUE THREAD

**Issue by Agendum** [vuetifyjs/vuetify#13731] opened 2021-06-01 03:26 UTC
### Environment
**Vuetify Version:** 2.5.1
**Vue Version:** 2.6.11
**Browsers:** Edge 91.0.864.37
**OS:** Windows 10

### Steps to reproduce
1. Go to the JSFiddle
2. Click on different tabs to see the red index change.
3. Use the Left/Right buttons to move tabs around.
4. Click on different tabs to see the red index change.

### Expected Behavior
The viewable tab changes in the header, and the index (derived from v-model of the tabs controls) correlates to the index of the tab as it is viewed.

### Actual Behavior
Though the viewable tab does change in the header, the index (derived from v-model of the tabs controls) correlates to the order or the tabs when they were initially added? It is unclear how that correlation occurs.

### Reproduction Link
<a href="https://jsfiddle.net/CodeVirtue/e89g4ayz/" target="_blank">https://jsfiddle.net/CodeVirtue/e89g4ayz/</a>

### Other comments
By not having the v-model correlated to the viewable index, three problems occur:
1) I have no way of saying "show the first tab" unless I manually keep track of where I think indexes should be -- unless...
2) If I get data from a server to show for the tabs which has overlapping data (see clone button), I have no idea of actually knowing where Vuetify put the tabs.
3) The only way to work around this is to add :key on v-tabs and v-tabs-items, but this causes a full re-render of all tabs and in some cases this can be expensive if the tab is showing lots/complex data.

**Comment by UglyHobbitFeet** [comment] 2022-03-22 18:24
I found a workaround although I'd appreciate an actual fix.  The workaround is to give a key to force the component to refresh.  In my case the following worked since I dynamically add tabs and display them sorted by name. I never remove tabs.

    <v-tabs v-model="myModel" :key="`vtab_${myTabs.length}`">

and

    <v-tabs-items v-model="myModel" :key="`vtab_${myTabs.length}`">

**Comment by KaelWD** [comment] 2023-03-23 13:41
Duplicate of #10540

**Closed by KaelWD** 2023-03-23 13:41 UTC
Labels: C: VTabs, S: triage
