### ISSUE TITLE
[Bug Report] [v-select] click icon and menu didn't drop down

### ISSUE THREAD

**Issue by l02162010** [vuetifyjs/vuetify#11115] opened 2020-04-15 04:05 UTC
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. set menu-prop = { closeOnClick: true }
2. click arrow down icon
3. menu didn't drop down

### Expected Behavior
click arrow down icon and menu will drop down

### Actual Behavior
menu didn't drop down

### Reproduction Link
<a href="https://codepen.io/l02162010/pen/mdeeNZj" target="_blank">https://codepen.io/l02162010/pen/mdeeNZj</a>

**Comment by Kutkov** [comment] 2020-10-05 08:00
I faced the same problem. I need to close the select menu when clicking on a text field, the menu prop ```{ closeOnClick: true }``` solves the problem with closing, but a bug of the opening arrow not working appears.

**Comment by johnleider** [comment] 2020-12-08 15:27
Marking this as a maybe. The value isn't technically passed through but it does affect the icon. At the least we will make sure that this works for v3, if they are even still options at that point.

**Comment by KaelWD** [comment] 2020-12-11 09:49
Duplicate of #9533

**Closed by KaelWD** 2020-12-11 09:49 UTC
Labels: duplicate
