### ISSUE TITLE
[Feature Request] Select autocomplete should allow overriding highlight function just as with the filter function

### ISSUE THREAD

**Issue by udany** [vuetifyjs/vuetify#4417] opened 2018-06-28 15:37 UTC
### Problem to solve
Currently I want to be able to ignore diacritics in autocomplete mode, such as in this example:
https://codepen.io/anon/pen/XYyBXe

But while I can get the filtering right, when I type "Sao" you'll see it higthlights the entire option, I'd like to be able to override that behavior as well.

### Proposed solution
In components/VSelect/mixins/select-autocomplete.js:35 you have genFiltered and on line 52 you have the function getMaskedCharacters, if I could override either of those as it happens with the filter function it would be awesome.

All it'd probably take is moving them into a prop.

**Comment by KaelWD** [comment] 2018-11-20 13:31
Possible duplicate of #3194

**Comment by johnleider** [comment] 2019-06-19 15:48
This unfortunately did not make the cut for official v2.0 release.

**Comment by coyotte508** [comment] 2019-11-07 15:15
I've thought about this (encountered this issue and reimplemented the item slot to handle it).

I was wondering if instead of overriding the highlight function, maybe it would be possible for the filter function to be like this:

```
type filterFunction = (item: object, queryText: string, itemText: string) => boolean | [number, number]
```

Instead of a `boolean`, it could return `false` if not matched, and a `[start, end]` range of matched characters if matched.

The current spec (returning `true` if matched) would still be supported, in which case it would fall back to the current behavior.

This change would also have the side effect of calling `filter` twice: once in the "filter" stage, once in the match stage.

I might be interested in implementing this - but I'd like to know if this design is ok.

**Comment by KaelWD** [comment] 2019-11-07 15:29
Yeah I could get behind that. 

> once in the "filter" stage, once in the highlight stage

I feel like it should be possible to only do it once.

**Comment by bad4iz** [comment] 2020-01-10 16:51
[the solution is here](https://github.com/vuetifyjs/vuetify/issues/3341)

**Comment by mitar** [comment] 2020-01-10 19:10
So this is not yet fixed? Maybe reopen?

**Comment by renoirb** [comment] 2020-11-11 19:10
For reference, the sorting/filtering function for this use-case might benefit leveraging both [`Intl.Collator` compare method][intl-collator-compare] and normalize all accents from [`String.normalize`][string-normalize]


```js
const name1 = 'São Paulo';
// Remove accents from a string for comparison
const normalize = (input) => input.normalize('NFD').replace(/[\u0300-\u036F]/g, '')

const name1NFC = name1;
const name2NFC = normalize(name1);

console.log(`${name1NFC}, ${name2NFC}`);
// > "São Paulo, Sao Paulo"
```

[intl-collator-compare]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator "Intl.Collator"
[string-normalize]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize "String.prototype.normalize()"

**Comment by KaelWD** [comment] 2021-10-04 16:21
Duplicate of #3194

**Closed by KaelWD** 2021-10-04 16:21 UTC
Labels: duplicate, help wanted, T: feature, C: VAutocomplete
