### ISSUE TITLE
[Bug Report] Expansion panel bug

### ISSUE THREAD

**Issue by furyscript** [vuetifyjs/vuetify#4272] opened 2018-06-11 14:30 UTC
### Versions and Environment
**Vuetify:** 1.1.0-beta.2
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.79
**OS:** Linux x86_64

### Steps to reproduce
https://codepen.io/anon/pen/JZWLYY

### Expected Behavior
First time, if I click first expansion panel for close it, it should work

### Actual Behavior
If I click second time for close it, it works, but it's wrong

### Reproduction Link
[https://codepen.io/anon/pen/JZWLYY](https://codepen.io/anon/pen/JZWLYY)

**Comment by KaelWD** [comment] 2018-06-11 14:58
Duplicate of #4132

**Closed by KaelWD** 2018-06-11 14:58 UTC
