### ISSUE TITLE
[Feature Request] Set body's background color to the one of v-application

### ISSUE THREAD

**Issue by filips123** [vuetifyjs/vuetify#14750] opened 2022-02-20 20:40 UTC
### Problem to solve
Firefox can automatically [adapt scrollbar colors](https://bugzilla.mozilla.org/show_bug.cgi?id=1578377) for dark-themed pages. However, for determining page background color, it checks `:root`'s, `html`'s and `body`'s color, while Vuetify only sets background color on the `v-application` (`#app`) element. This causes Firefox to think the page still uses a light theme and applies light scrollbars.

### Proposed solution
When changing/applying `v-application`'s background color, Vuetify should also set `:root`'s, `html`'s and `body`'s background color to the same color.

While I think this should be enabled by default (it enhances UX and can fix some accessibility problems due to scrollbar contrast), it should probably be possible to control this behavior using some theme option when initializing Vuetify (in case it causes conflicts on some websites).

**Comment by KaelWD** [comment] 2022-02-21 03:56
Duplicate of #8638

**Closed by KaelWD** 2022-02-21 03:56 UTC
Labels: S: triage
