### ISSUE TITLE
[Feature Request] Creating Scheduling Component

### ISSUE THREAD

**Issue by AlexayEugine** [vuetifyjs/vuetify#4834] opened 2018-08-10 08:15 UTC
### Problem to solve
I want to show scheduling events with in calendar.
but also need to drag and drop events on calendar and resizing days of event.
Please make it.

### Proposed solution
Please make it.

**Comment by KaelWD** [comment] 2018-08-10 08:40
Duplicate of either #989 or #1915

**Closed by KaelWD** 2018-08-10 08:40 UTC
