### ISSUE TITLE
[Feature Request] FileUpload component availability 

### ISSUE THREAD

**Issue by nni123** [vuetifyjs/vuetify#1543] opened 2017-08-31 07:06 UTC
Library is awesome not question about it.

Any plan to add FileUpload component. It will complete the requirement for our UI.

We love material UI design..very well done...

Thanks

**Comment by jacekkarczmarczyk** [comment] 2017-08-31 07:07
Planned for Frontend Pack https://github.com/vuetifyjs/vuetify/issues/238

**Comment by nekosaur** [comment] 2017-08-31 07:31
Duplicate of #238

**Closed by nekosaur** 2017-08-31 07:31 UTC
Labels: duplicate
