### ISSUE TITLE
[Bug Report] v-tab's tabs are not aligned in mobile / tablet view when stacked vertically

### ISSUE THREAD

**Issue by dikesh** [vuetifyjs/vuetify#8426] opened 2019-08-09 10:54 UTC
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
1. Use v-tags with vertical (=true) prop
2. Open output in mobile mode

### Expected Behavior
All tabs should be left aligned

### Actual Behavior
First tab is not aligned. Extra margin gets added to first tab.

### Reproduction Link
<a href="https://codepen.io/dikeshjariwala/pen/WVKqjz/right" target="_blank">https://codepen.io/dikeshjariwala/pen/WVKqjz/right</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-09 10:57
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8294

(not exactly but same cause)

**Closed by jacekkarczmarczyk** 2019-08-09 10:57 UTC
Labels: triage
