### ISSUE TITLE
[Bug Report][3.0.0-beta.1] v-text-field doesn't display "0" with v-model

### ISSUE THREAD

**Issue by Talw3g** [vuetifyjs/vuetify#15039] opened 2022-05-04 16:28 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Firefox 99.0
**OS:** Windows 10

### Steps to reproduce
Link the value of a v-text-field to a variable = 0 (number), using v-model.

### Expected Behavior
The "0" should appear inside the text field.

### Actual Behavior
The "0" only appears when editing the text field.

### Reproduction Link
<a href="https://codepen.io/talw3g/pen/qBxdVPq" target="_blank">https://codepen.io/talw3g/pen/qBxdVPq</a>

### Other comments
It works fine with any value other than 0.

**Comment by KaelWD** [comment] 2022-05-04 16:31
Duplicate of #14942

**Closed by KaelWD** 2022-05-04 16:31 UTC
Labels: S: triage
