### ISSUE TITLE
[Bug Report][3.0.0-beta.5] v-tabs don't render selection

### ISSUE THREAD

**Issue by tamsler** [vuetifyjs/vuetify#15421] opened 2022-07-11 23:00 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click on any of the tab items e.g. 
Item One
Item Two
Item Three
And the tab selection indicator is now showing

### Expected Behavior
Selected tab item should have selection bar underneath

### Actual Behavior
Selected tab item does not show selection bar underneath 

### Reproduction Link
<a href="https://codepen.io/tamsler/pen/ExEyJyN" target="_blank">https://codepen.io/tamsler/pen/ExEyJyN</a>

**Comment by KaelWD** [comment] 2022-07-12 07:30
Duplicate of #15376

**Closed by KaelWD** 2022-07-12 07:30 UTC
Labels: S: triage
