### ISSUE TITLE
[Bug Report] Tab not using full width of Toolbar

### ISSUE THREAD

**Issue by nirmalraghavan** [vuetifyjs/vuetify#6386] opened 2019-02-06 11:43 UTC
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.2
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 7

### Steps to reproduce
1. Add `<v-tabs>` to the extended `<v-toolbar>`
2. Remove all padding and margin

### Expected Behavior
`<v-tab>` should use full width of `<v-toolbar>`

### Actual Behavior
There's any empty margin/padding between toolbar and tabs.

### Reproduction Link
<a href="https://codepen.io/anon/pen/mvBpJp?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/mvBpJp?&editable=true&editors=101</a>

**Comment by KaelWD** [comment] 2019-02-06 11:44
Duplicate of #4420

**Closed by KaelWD** 2019-02-06 11:44 UTC
