### ISSUE TITLE
[Feature Request] Disable hover on DataTable

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#10297] opened 2020-01-22 16:00 UTC
### Problem to solve
don't change row color when hovering over any row

### Proposed solution
add new prop, something like 'disable-hover'

**Comment by nekosaur** [comment] 2020-01-22 16:35
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5787

**Closed by nekosaur** 2020-01-22 16:35 UTC
Labels: C: VDataTable, duplicate

**Comment by mowolf** [comment] 2022-01-13 16:33
Just disable the background color change via css:

```
.v-data-table__wrapper > table > tbody > tr:hover {
  background: inherit !important;
}
```

**Comment by acro5piano** [comment] 2022-04-21 16:25
@mowolf Thanks!
