### ISSUE TITLE
[Bug Report] Vuetify Assumes All Apps Should Have "overflow-y: scroll" on HTML Element

### ISSUE THREAD

**Issue by auzmartist** [vuetifyjs/vuetify#10559] opened 2020-02-12 18:27 UTC
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Apply Vuetify styles to any app.

### Expected Behavior
Vuetify should not apply a scrollbar to the HTML element by default.

### Actual Behavior
A scrollbar is applied to the page.

### Reproduction Link
<a href="https://codepen.io/auzmartist/pen/dyoYKpO" target="_blank">https://codepen.io/auzmartist/pen/dyoYKpO</a>

### Other comments
There is an easy workaround in this case, but I find that vuetify is too opinionated about this rule. Is it needed?

**Comment by KaelWD** [comment] 2020-02-13 03:27
Duplicate of #864, #1197

**Closed by KaelWD** 2020-02-13 03:27 UTC
Labels: triage
