### ISSUE TITLE
[Bug Report] Popover Menu on Fixed Element Should Also Be Fixed

### ISSUE THREAD

**Issue by big213** [vuetifyjs/vuetify#5891] opened 2018-12-14 06:24 UTC
### Versions and Environment
**Vuetify:** 1.3.14
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 7

### Steps to reproduce
Place a popover menu inside a fixed toolbar element.

### Expected Behavior
Popover menu content (activated by clicking on the right-most button) remains fixed and tied to the fixed toolbar element as the page is scrolled.

### Actual Behavior
Popover menu content moves with the page as it is scrolled.

### Reproduction Link
<a href="https://codepen.io/big213/pen/GPoBQg?&editable=true&editors=101" target="_blank">https://codepen.io/big213/pen/GPoBQg?&editable=true&editors=101</a>

### Other comments
I thought that adding `fixed` to `v-menu` would solve this issue, but it did not. It appears that changing the css for `.v-menu__content` to `position: fixed` resolves the issue, so the problem can be solved via scoped css, but I think it should be the default behavior.

**Comment by KaelWD** [comment] 2018-12-14 08:13
Duplicate of #1551

**Closed by KaelWD** 2018-12-14 08:13 UTC
