### ISSUE TITLE
Select menu with auto option opens at wrong position

### ISSUE THREAD

**Issue by tyio** [vuetifyjs/vuetify#714] opened 2017-06-07 09:29 UTC
### Steps to reproduce
- Use select component
- Set auto option
- Perform selection multiple times in a row

### Versions
Vuetify: 0.12.7

### What is expected ?
Select menu opens at the same position

### What is actually happening ?
Select menu opens at different positions every time selection is performed

### Reproduction Link
https://codepen.io/tyio/pen/OgVdMV

P.S. Please, add also auto option to the API documentation.

**Comment by johnleider** [comment] 2017-06-07 10:54
Duplicate of #702. Will get auto into docs ty.

**Closed** 2017-06-07 10:54 UTC
Labels: duplicate

**Comment by mornir** [comment] 2017-06-07 10:58
I've just submitted a pull request for the docs.

**Comment by do-web** [comment] 2017-08-01 19:31
Sorry but Version 0.14.7 has still the problem with the wrong position

**Comment by johnleider** [comment] 2017-08-01 19:49
At least on mobile, I don't see this still happening.

**Comment by ivorycherry9** [comment] 2017-10-12 18:45
I'm getting this same issue on latest version. Seems to be due to my form controls being inside a bootstrap modal, as the offset of the selectmenu/pickermenu is exactly the offset of where my modal window is.
