### ISSUE TITLE
[Feature Request] margin slot activator

### ISSUE THREAD

**Issue by lordenas** [vuetifyjs/vuetify#6382] opened 2019-02-06 10:02 UTC
### Problem to solve
I am trying to add the "reset Form" method in a modal window. And run it by clicking on 
```
<v-btn
slot="activator"
@click="resetform()"
>
add
 < / v-btn>
```

  But, the button has a margin and if you click on this margin, the reset form method will not work.
<img width="876" alt="screenshot at feb 06 13-01-10" src="https://user-images.githubusercontent.com/15974195/52333855-562a4e80-2a0f-11e9-9477-d0c05aeb13e3.png">
### Proposed solution
I think I need to add a method to the v-dialog__activator

**Comment by KaelWD** [comment] 2019-02-06 10:04
Duplicate of #3033, this was resolved by #5318

**Closed by KaelWD** 2019-02-06 10:04 UTC
