### ISSUE TITLE
[Bug Report] [Question] Issue about a-la-carte (bundle analyzer)

### ISSUE THREAD

**Issue by PhuHoaframgia** [vuetifyjs/vuetify#9666] opened 2019-11-12 02:22 UTC
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.87
**OS:** Mac OS 10.14.6

### Steps to reproduce
this is my module:
![image](https://user-images.githubusercontent.com/23466462/68635734-0b081380-052c-11ea-9682-d060ee060265.png)

import in main.js
![image](https://user-images.githubusercontent.com/23466462/68635697-f297f900-052b-11ea-84f5-2ca34e87b452.png)

result is:
![image](https://user-images.githubusercontent.com/23466462/68635848-5ae6da80-052c-11ea-91e6-a70e30b2a2e2.png)

i follow a-la-carte  
i wonder that why it injects all components to the project?
how to fix it?

### Expected Behavior
Just inject the imported components

### Actual Behavior
a-la-carte  

### Reproduction Link
<a href="https://user-images.githubusercontent.com/23466462/68635848-5ae6da80-052c-11ea-91e6-a70e30b2a2e2.png" target="_blank">https://user-images.githubusercontent.com/23466462/68635848-5ae6da80-052c-11ea-91e6-a70e30b2a2e2.png</a>

**Comment by jacekkarczmarczyk** [comment] 2019-11-12 04:13
Is this screenshot from `yarn serve` or `yarn build`?

Here is mine from serve:
![image](https://user-images.githubusercontent.com/15625235/68641250-dcdeff80-053c-11ea-8526-60e58b245bf9.png)

and from build:
![image](https://user-images.githubusercontent.com/15625235/68641370-2e878a00-053d-11ea-8955-1dbb072dfbb5.png)


As you see the final build is treeshaken, problem is only in dev move

Possibly related: https://github.com/vuetifyjs/vuetify-loader/issues/44

**Comment by PhuHoaframgia** [comment] 2019-11-12 04:30
hi @jacekkarczmarczyk 
that's screen which i run "npm serve"
i just import vdialog but that why it injects all components to the project?

**Comment by PhuHoaframgia** [comment] 2019-11-12 04:31
you mean that will be ignore when we run "npm run build"?

**Comment by jacekkarczmarczyk** [comment] 2019-11-12 04:46
It should be, just run the build and check. Also try this https://github.com/vuetifyjs/vuetify-loader/issues/44#issuecomment-551173005

**Comment by PhuHoaframgia** [comment] 2019-11-12 07:56
hi @jacekkarczmarczyk 
i tried this
https://github.com/vuetifyjs/vuetify-loader/issues/44#issuecomment-551173005
seems this just works for the components which no js
i use VCard it works
but for Vdialog. i got this error
![image](https://user-images.githubusercontent.com/23466462/68651321-b5e2f680-0559-11ea-8e75-404ebf08d20f.png)

**Comment by KaelWD** [comment] 2019-11-12 09:51
Duplicate of https://github.com/vuetifyjs/vuetify-loader/issues/98

You also haven't imported Vuetify in the module.

**Closed by KaelWD** 2019-11-12 09:51 UTC
Labels: triage
