### ISSUE TITLE
[Bug Report] V-Btn with dark theme is not visible when disabled in app with light theme

### ISSUE THREAD

**Issue by AnjanishKumar** [vuetifyjs/vuetify#5624] opened 2018-11-15 19:52 UTC
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Linux x86_64

### Steps to reproduce
create a `v-btn` with prop `dark` in the light theme application and set the prop `disabled` to `true`.

### Expected Behavior
The button component should be visible in disabled state.

### Actual Behavior
The button becomes invisible.

### Reproduction Link
<a href="https://codepen.io/anjanish-kumar/pen/xQrGPO" target="_blank">https://codepen.io/anjanish-kumar/pen/xQrGPO</a>

**Comment by KaelWD** [comment] 2018-11-16 05:37
Duplicate of #4482

**Closed by KaelWD** 2018-11-16 05:37 UTC
