### ISSUE TITLE
[Feature Request] New prop max-height for v-textarea

### ISSUE THREAD

**Issue by alex-w0** [vuetifyjs/vuetify#10793] opened 2020-03-09 19:06 UTC
### Problem to solve
Would be nice to have a new prop on the component v-textarea where I can define the max-height of the field. I'm using the prop auto-grow where I would like to define how high the component can grow until it becomes a scrollbar.

### Proposed solution
Adding new prop max-height

**Comment by johnleider** [comment] 2020-04-04 17:29
Duplicate of #10009

**Closed by johnleider** 2020-04-04 17:29 UTC
Labels: triage
