### ISSUE TITLE
[Feature Request] Theme stylesheet: Automatically generate inverted text color from background color

### ISSUE THREAD

**Issue by Janne252** [vuetifyjs/vuetify#8587] opened 2019-08-17 09:03 UTC
### Problem to solve
Usually a theme's primary color is dark enough that to ensure readability and a proper contrast ratio, the text color has to be white. Meaning that if you apply the theme class `primary` to any element, you often also have to include `text--white` class or `dark` property if the target supports it.

 

### Proposed solution
Wouldn't it make sense if the css class `primary` also set the `color` property to an automatically generated color? Bulma does this by using either slightly transparent black or white based on the luminance value of the color: https://github.com/jgthms/bulma/blob/master/sass/utilities/functions.sass

This way when using theme colors as background colors you don't have to explicitly set the text color as well. This could be an optional flag in the settings or a modifier css class, like `text--auto-invert`.

Another option is to check if the contrast ratio of the background color vs. the default text color is high enough - if not, invert it.

**Comment by KaelWD** [comment] 2019-08-17 09:09
Duplicate of #4921

**Closed by KaelWD** 2019-08-17 09:09 UTC
Labels: duplicate
