### ISSUE TITLE
[Bug Report] Badges inside v-toolbar-items are misaligned

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#7274] opened 2019-05-23 01:46 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Ubuntu undefined

![image](https://user-images.githubusercontent.com/1400380/58219990-de341b80-7cc1-11e9-82bb-9bf0520fb256.png)

### Steps to reproduce
Create a badge inside of a v-toolbar-items block

### Expected Behavior
It stays aligned like in a toolbar

### Actual Behavior
The contents of the badge (ie. an icon) are aligned at the top of the v-toolbar-items block

### Reproduction Link
<a href="https://codepen.io/anon/pen/qGpzXG" target="_blank">https://codepen.io/anon/pen/qGpzXG</a>

### Comments

I can't find any documentation on `v-toolbar-items` ??

**Comment by jacekkarczmarczyk** [comment] 2019-05-29 01:35
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6146

**Closed by jacekkarczmarczyk** 2019-05-29 01:35 UTC
Labels: triage
