### ISSUE TITLE
[Bug Report] Weird bottom navigation style behavior

### ISSUE THREAD

**Issue by Liu6972319** [vuetifyjs/vuetify#13622] opened 2021-05-08 12:02 UTC
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 4.5.11
**Browsers:** Chrome 89.0.4389.90
**OS:** Linux x86_64

### Steps to reproduce
After the project is packaged
    Open the homepage
    v-bottom-navigation style is out of order
    but dev env orderly
    Compare button style discovery `.v-btn:not(.v-btn--round).v-size--default` has higher priority than `.v-item-group.v-bottom-navigation .v-btn`
    Try to replace import Vuetify from'vuetify/es5/index';
    The style is correct

### Expected Behavior
import Vuetify from 'vuetify' and import Vuetify from 'vuetify/lib'
    style start

### Actual Behavior
 Wrong style.js loading order

### Reproduction Link
<a href="https://codepen.io/liu6972319/pen/ZEeYdJX" target="_blank">https://codepen.io/liu6972319/pen/ZEeYdJX</a>

**Comment by jacekkarczmarczyk** [comment] 2021-05-17 19:28
You're codepen doesn't display anything. Moreover it's likely to be a duplicate of https://github.com/vuetifyjs/vuetify/issues/8067 which is going to be fixed in Vuetify 3
Closing for now, but feel free to add a link to working reproduction if you have one though

**Closed by jacekkarczmarczyk** 2021-05-17 19:28 UTC
Labels: C: VBottomNavigation, CSS specificity, S: needs reproduction, duplicate
