### ISSUE TITLE
[Bug Report] v-autocomplete buggy reopen auto selecting a value

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#4831] opened 2018-08-09 16:12 UTC
### Versions and Environment
**Vuetify:** 1.1.10
**Vue:** 2.5.17
**Browsers:** Chrome 65.0.3325.162
**OS:** Linux x86_64

### Steps to reproduce
- Type 'ala' into the v-autocomplete box;
- Press down arrow, then enter to select the first result;

### Expected Behavior
Value should be selected, then the autocomplete list should be hidden and do not appear again.

### Actual Behavior
Autocomplete list disappears and then reopens.

### Reproduction Link
[https://codepen.io/kasheftin/pen/djwYrO](https://codepen.io/kasheftin/pen/djwYrO)

### Other comments
That's the slightly modified code from this example, https://github.com/vuetifyjs/vuetifyjs.com/blob/master/src/examples/autocompletes/asynchronous.vue. The last has strange restriction in watch handler (val && val !== this.select && this.querySelections(val)) it's not acceptable if the component uses return-object or when it should show preliminary results for the empty search. Anyway, reassigning the items property should now open the list.

**Comment by KaelWD** [comment] 2018-08-09 16:21
Duplicate of #4663

**Closed by KaelWD** 2018-08-09 16:21 UTC
