### ISSUE TITLE
[Bug Report] dialog is disabled when you select a text and release on overlay

### ISSUE THREAD

**Issue by danielpfs** [vuetifyjs/vuetify#7121] opened 2019-05-02 01:52 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.6
**Browsers:** Chrome 73.0.3683.103
**OS:** Linux x86_64

### Steps to reproduce
Open dialog
Click and hold with left button mouse the text from dialog
Drop the selection on overlay

### Expected Behavior
Dialog keeps active after you select the text

### Actual Behavior
Dialog is disabled when you select the text

### Reproduction Link
<a href="https://codepen.io/anon/pen/KYjRYp" target="_blank">https://codepen.io/anon/pen/KYjRYp</a>

**Comment by KaelWD** [comment] 2019-05-02 09:06
Duplicate of #6969

**Closed by KaelWD** 2019-05-02 09:06 UTC
Labels: triage
