### ISSUE TITLE
[Bug Report] Module parse failed: Identifier 'installComponents' has already been declared

### ISSUE THREAD

**Issue by yiyan0** [vuetifyjs/vuetify#10237] opened 2020-01-16 11:22 UTC
### Environment
**Vuetify Version:** 2.2.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
npm run serve

### Expected Behavior
Compiled successfully

### Actual Behavior
error  in ./src/App.vue

Module parse failed: Identifier 'installComponents' has already been declared (32:7)
File was processed with these loaders:
 * ./node_modules/vuetify-loader/lib/loader.js
 * ./node_modules/vuetify-loader/lib/loader.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader/lib/index.js
 * ./node_modules/eslint-loader/index.js
You may need an additional loader to handle the result of these loaders.
| 
| /* vuetify-loader */
> import installComponents from "!../node_modules/vuetify-loader/lib/runtime/installComponents.js"
| import { VApp } from 'vuetify/lib/components/VApp';
| import { VAppBar } from 'vuetify/lib/components/VAppBar';

### Reproduction Link
<a href="https://codepen.io/yiyan0/pen/yLyxbZj" target="_blank">https://codepen.io/yiyan0/pen/yLyxbZj</a>

**Comment by KaelWD** [comment] 2020-01-16 11:24
Duplicate of vuetifyjs/vuetify-loader#20

**Closed by KaelWD** 2020-01-16 11:24 UTC
Labels: duplicate, layer 8 issue
