### ISSUE TITLE
[Bug Report] vMenu hidden behind vDialog in fullscreen

### ISSUE THREAD

**Issue by acorbel** [vuetifyjs/vuetify#3163] opened 2018-02-02 14:46 UTC
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Create a vDialog and add a simple vMenu in it. 

### Expected Behavior
vMenu should have a z-index greater than the upper vDialog. 

### Actual Behavior
Menu z-index is 8 and vDialog is about 20x.

### Reproduction Link
[https://codepen.io/anon/pen/NyxdRb](https://codepen.io/anon/pen/NyxdRb)

### Other comments
Quick fix: add style="z-index:2000" on vMenu

**Comment by jingzheshan** [comment] 2018-02-12 08:06
@johnleider I sent you a patch before. v-menu need recalculate the highest active index.

**Comment by KaelWD** [comment] 2018-02-12 08:45
Duplicate of #2111

**Closed by KaelWD** 2018-02-12 08:45 UTC
Labels: help wanted
