### ISSUE TITLE
[Bug Report] Cannot read property 'height' of null

### ISSUE THREAD

**Issue by oixan** [vuetifyjs/vuetify#10626] opened 2020-02-19 21:30 UTC
### Environment
**Vuetify Version:** 2.2.13
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.116
**OS:** Windows 10

### Steps to reproduce
Just try to type: PROGRAMMING.

The error will show in the console.

This error broke up all combobox in my website.

### Expected Behavior
Show Vmenu Control

### Actual Behavior
Vmeno Control dont show up

### Reproduction Link
<a href="https://codepen.io/oixan/pen/yLNaagY?editors=1010" target="_blank">https://codepen.io/oixan/pen/yLNaagY?editors=1010</a>

**Comment by KaelWD** [comment] 2020-02-20 06:10
Duplicate of #10606

**Closed by KaelWD** 2020-02-20 06:10 UTC
Labels: triage
