### ISSUE TITLE
[Feature Request] V-Tree-View should return nodes instead of IDs in v-model and active.sync

### ISSUE THREAD

**Issue by BlackConure** [vuetifyjs/vuetify#6040] opened 2019-01-02 18:31 UTC
### Problem to solve
Many applications require more information regarding what node was selected or activated.   By returning an array of keys in the v-model or in active.sync, requires the application to parse through the hierarchy to pull the requisite data.    

### Proposed solution
If the node was returned instead of just the key, no additional client logic would be required.   The additional data components can be embedded in the node itself.

**Comment by nekosaur** [comment] 2019-01-05 12:50
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5881

**Closed by nekosaur** 2019-01-05 12:50 UTC
Labels: T: enhancement, T: feature, duplicate
