### ISSUE TITLE
[Bug Report][3.7.1] v-date-input not using locale (via v-locale-provider) when entering date manually in text field

### ISSUE THREAD

**Issue by JustCodingSomeThings** [vuetifyjs/vuetify#20433] opened 2024-09-06 09:42 UTC
### Environment
**Vuetify Version:** 3.7.1
**Vue Version:** 3.5.1
**Browsers:** Firefox 130.0
**OS:** Windows 10

### Steps to reproduce
Give Focus to the v-date-input's text field (for manual date entry), and immediately press ENTER (so don't change the actual bound date).

### Expected Behavior
v-date-input should emit the correct expected date (via @update:model-value), since v-date-input is using a v-locale-provider with the nl locale set on it.

### Actual Behavior
v-date-input seems to perform a 'text field input string to native Date' conversion to emit via @update:model-value, but does not honour the v-locale-provider's set locale. In this case, with the locale nl set, the day and month is 'swapped' in detemining the emitted Date value.

Since the v-locale-provider is responsible for properly rendering a Date value using the correct locale string format, I would expect that this is also used when manually entering a date in the v-date-input's text field.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVw1v2zYQ/SucMMDuYFlOi2KA53YZ1g5otzZDlxYYqgKhLdrmKpECSdkJgvz3vSMpm1a6ougqBIrIO97Hu8cj/f42s2ZV7Drh5Ppm+o/N5plsWm0cu2UrI7gT74KM3bG10Q0bRd1RqUolrr3qSivrWBSwJ6cLx7elYsxtRSPmzH8zVok172p3GSZHtdxs3WhCsjv/rvWK10f1fjhSdf76j9GEFQWzwjE/ZE6zpWB6Jwyv66jbm7p7UKps4nP8pW2nCBEJLuzKyNaRia59SqrHlHXTdk5UE2bEOk3Zp8vIsTZyIxWvWYUc5+w3sTQdNzfsDBA8nM1mEx9aZ6XaMK7Yi78uvCazzmCKjAS4ejvPIOyNwAaZAIRK7BlJxiOayGcP89nZCMkc1/ehkhZhHocBbsY2wo0f9AD6wC2yrG+QmOuMooKcpkI4SiWd5LW0GEG+y0mQSwXLI8t2vO48stHgXrrtp/RCCTwMsKnqCZSkRYTGiJXzIahKGMtmZ5SYz3j87Fn+6lX+N54HCCPxIp1lTly7tRR1FQAInNiM+2/GrlI0EAKyd8IgBFVhNUJc67rWe6qJ4k7uhAeXwkvib+XqozDzq94s4D76+ky5YlnoieB+RjloBpozwmjsYUWpwhwxlv6vO7VyUivWtRSc50Kv2e+KzfgqhZ5tuWWikUi9GiTtV7Kd5Ow82Js3uhL1O5qeX8VEyWBw0SdETNO1mKZgX/lifn8bTEpQkauV0OuA6M9sJO2IYa9C6fXF5eiO8SDpNSO8Bx9EpK1QvdoeOVhRgyhIggIekOvPF7/+/vwNe/uCWCV6UgUGwyUGAuUFUaLtrd4LtIZJcEJLiEzMs4kWdBZ+1togPoKQq4o9f30JD5C1RliIg6few2rL1SZxMCaeR8pDrDRtftgkS41W2CL0VfEb5snYtehWVBK7520LPalia8h9/oAc4VpU3lflbsAGqkSDqPjmSAR4Nu4wG1ctitDl0N8wcAJ7H+Z9t1vscrj2n37QcKniCONK7g4D37dPKoDgQSlKdG9C/MsblG6XBwTy1uidxOYOzYH27rEhh+fQFhZLw4oTV2RVm4/W1wOWWmHQLTBouHO+n57s3sDAuIe9GzSuWBh6vFLAlsqClVoNnQL90Jy4FZP7zfyASpHCMsAopS9MfSV7k5jIhhtG+q2IfLQ4YPTQ4f8ndlL0TzN86NLq9EzY6w6p4WynnuoNotanFDCCUhPKs+MlV1S8o7mHiC8cydR8BK8Y2tTX1XjxXZ5T+uCtB/k/j71JPPqDwnBX5PnQ5lIiyHu7LJL65IzvBwMj952E8ZMyU3WZJape+egkFYB0FRbsSBqE2ak4nBe533JQTAMbqp6cMIcVx2PsVP/pokiDSjODYJDasTpJrUjv0MJoEJrbokiaHobW3dSh/2Fp3zpbXlWo1pydzdpr//rp2D/jAtwfnQVp13KDC7JWuEH61QEFieZ70VJrsWV2uLGWGe6iev/SzznTiXjel5njBpcTmi4zYR+X2UECvDo0yijB3RpaB+ES/emtQT1JOi3uLXsjcFB3FEZQWXaqQmSJXsvdNg2R5s6LH2jmfelvyPj+cHo9KbNaLqPGISTMVro5fEwlblp8SZHTTDh1ttpC1VsDlvgDiOGSjVK1AxiD4BQ+XLlDIlvnWjsvilWlsAyMkjszVcIVqm2Kc6gVpsP2b0SOWM4fTR9PH4Eb1qXTU2GbfGn03goDIwko8TfLF7iKmvDw4/QseIhTec2XllzcM13AH1pdHu67VI0vy2iwLM1qILqXWYL43UR1de1fH/4FRJ+CSQ==)

![v-date-input-pagee](https://github.com/user-attachments/assets/ba66faef-599c-467a-b9aa-298547e5980b)

![app vue](https://github.com/user-attachments/assets/4ef73939-1ad7-4a5f-adfa-71b8e681750c)
![vuetify-js](https://github.com/user-attachments/assets/4bda8987-4d43-454c-b728-3935cfd09e55)

**Comment by KaelWD** [comment] 2024-09-06 09:46
Duplicate of #19803

**Closed by KaelWD** 2024-09-06 09:46 UTC
Labels: S: triage
