### ISSUE TITLE
[Bug Report][2.6.4] V-select - wrong item highlighted on click when using with prepend-item slot

### ISSUE THREAD

**Issue by all43** [vuetifyjs/vuetify#14980] opened 2022-04-22 05:44 UTC
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 100.0.4896.127
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Create v-select with prepend-item slot with list-item(s) or divider(s) number in the slot
2. Select any item which is not in the beginning of the list

### Expected Behavior
Only selected item being highlighted

### Actual Behavior
Highlighted item shifted by number of list-items (or dividers) in prepend-item slot.
Imagine list structure like this:
- Prepend 1
- Prepend 2
- Selectable 1
- Selectable 2
- Selectable 3
If you click on selectable 3, selectable 1 will be highlighted as well

### Reproduction Link
<a href="https://codepen.io/allforfree/pen/VwyNYaM" target="_blank">https://codepen.io/allforfree/pen/VwyNYaM</a>

### Other comments
I don't know if it is related or it is another bug, but when using v-select with prepend-item slot with Vue dev tools enabled I'm getting console error `assert: staticList should not be called if slots are used`, wasn't able to reproduce this in a separate project. I have checked component code and my guess that slots might not be detected during creation time, but already present while calling staticList.

**Comment by KaelWD** [comment] 2022-04-22 06:36
Duplicate of #14489

**Closed by KaelWD** 2022-04-22 06:36 UTC
Labels: S: triage
