### ISSUE TITLE
[Bug Report][3.0.0-beta.2] Ripple + Menu + Mobile = :(

### ISSUE THREAD

**Issue by SuperCuber** [vuetifyjs/vuetify#15127] opened 2022-05-20 16:52 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.2
**Last working version:** 3.0.0-beta.1
**Vue Version:** 3.2.34
**Browsers:** Firefox 100.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
1. Switch browser to mobile mode (with touch emulation)
2. Click on the button
3. Move cursor to the rest of the card
4. Check console

### Expected Behavior
No errors

### Actual Behavior
Error: `Uncaught DOMException: Node.removeChild: The node to be removed is not a child of this node`

### Reproduction Link
<a href="https://codepen.io/SuperCuber2/pen/poawpxb" target="_blank">https://codepen.io/SuperCuber2/pen/poawpxb</a>

### Other comments
This doesn't seem to actually impact anything user-facing

**Comment by KaelWD** [comment] 2022-05-20 17:00
Duplicate of #13457

Thanks for the reproduction, nobody else managed to make one yet.

**Closed by KaelWD** 2022-05-20 17:00 UTC
Labels: S: triage
