### ISSUE TITLE
[Feature Request] Date Range Picker

### ISSUE THREAD

**Issue by wernerm** [vuetifyjs/vuetify#1646] opened 2017-09-09 15:57 UTC
A component that facilitates the selection of a pair of dates, which can be implemented as generic start and end dates.

### What will it allow you to do that you can't do today?

The current `v-date-picker` only allows for selection of a single date at a time. A date range picker will facilitate the selection of a pair of dates.

### How will it make current work-arounds straightforward?

Currently two separate `v-date-picker`s will have to be used with code to facilitate synchronising their dates. Here's an example of a crude workaround utilising `v-date-picker` that I have implemented for a recent project:

![screenshot_20170909_174819](https://user-images.githubusercontent.com/411270/30241625-64e7803c-9587-11e7-99f7-c61edc1382a7.png)

### Inspiration

Element UI's datepicker's functionality serves as inspiration:

![screenshot_20170909_173006](https://user-images.githubusercontent.com/411270/30241497-e9819b64-9584-11e7-8bde-3c474dcabd4f.png)

Specific features requested:

- Displaying more than one calendar month at a time
- Synchronised paging of months
- Scoped slots for save and cancel, and scoped slots for predefined actions and date ranges (eg to add action buttons to select "next 30 days",  "last year", etc)

**Comment by bdeo** [comment] 2017-09-28 13:56
Is there a target release for this?

**Comment by paladin2005** [comment] 2017-09-29 17:05
@wernerm can you share your custom-date-range html template?

**Comment by OtavioCostaLima** [comment] 2017-09-30 11:08
apoio

**Comment by donPuerto** [comment] 2017-09-30 11:50
This is also from google data studio
![image](https://user-images.githubusercontent.com/9329005/31045533-5e76bc1c-a618-11e7-9a40-a06323039845.png)

![image](https://user-images.githubusercontent.com/9329005/31045537-7366f146-a618-11e7-8ffd-1f36be5a73fe.png)

![image](https://user-images.githubusercontent.com/9329005/31045544-95ed7f28-a618-11e7-8dec-e9b3e76561c9.png)

**Comment by EvanZ** [comment] 2017-12-06 15:47
Came here for this too. Was just looking at Google Analytics design.

https://storage.googleapis.com/zamir-images/Screen%20Shot%202017-12-06%20at%207.45.26%20AM.png

**Comment by smtlk** [comment] 2017-12-24 11:36
Supporting this request, it's an important part of most people's UI and using two date pickers is often a bit unnatural.

**Comment by jmauerhan** [comment] 2018-01-03 17:07
I'd like this for time ranges as well!

**Comment by praveenpuglia** [comment] 2018-02-03 13:13
This may seem like promoting it but till the time a fully built one comes in vuetify, I made up my own solution. It's not perfect but it does the job. 

Feel free to help it make better. :)

https://github.com/praveenpuglia/vuetify-daterange-picker

**Comment by renztoygwapo** [comment] 2018-02-07 08:36
any updates for the date picker range request?

**Comment by maxcook** [comment] 2018-03-03 10:55
This is such an important feature for many apps.
+1

**Comment by usb248** [comment] 2018-03-09 13:53
+1

**Comment by samirph** [comment] 2018-03-13 13:10
On every Vuetify version update I wonder if date range/period support was added
+1

**Comment by toinbis** [comment] 2018-03-19 18:37
+1

**Comment by vincebanzon** [comment] 2018-04-24 14:01
I hope they're working on it by now.

**Comment by NikoNagy** [comment] 2018-06-18 13:46
Any update on this ? 

Can we hope to see this in [Front-End Pack](https://github.com/vuetifyjs/vuetify/milestone/8) ? 🤞 

Thanks for your work.

**Comment by mariokresic** [comment] 2018-07-25 16:45
Hello everyone,
temporary this function can be achieved with the events functionality. Events array should contain all dates from DateStart to DateEnd and custom-class for event-color. Custom class must be modified so it highlights selected dates-range.

I hope this will help someone.

**Comment by praveenpuglia** [comment] 2018-07-25 18:55
@mariokresic I have been thinking of doing this in https://github.com/praveenpuglia/vuetify-daterange-picker but afraid of when that might break so didn't do it. Would you like to send a PR and add that functionality there? That would be great :)

**Comment by mariokresic** [comment] 2018-07-26 14:36
@praveenpuglia I will try to do it this weekend :)

**Comment by acidjazz** [comment] 2018-08-11 08:39
@mariokresic how about sharing the code used for that image as well?

**Comment by Fohlen** [comment] 2018-10-26 17:21
My current workaround for this feature is as follows:

```
<template>
  <div>
   <v-date-picker
     v-model="dates"
     :min="min"
     :max=""
  </div>
</template>

import addMonths from 'date-fns/add_months'
import subMonths from 'date-fns/sub_months'
import subDays from 'date-fns/sub_days'

<script>
export default {
  data () {
    return {
      dates: []
    }
  },
  computed: {
    min () {
      let min
      if (this.dates.length < 1) {
        min = subMonths(new Date(), 6)
      } else {
        min = subDays(new Date(this.dates[0]), 1)
      }
      return min.toISOString()
    },
    max () {
      let max
      if (this.dates.length <= 1) {
        max = addMonths(new Date(), 6)
      } else if (this.dates.length > 1) {
        max = new Date(this.dates[1])
      } else {
        max = addMonths(this.dates[0], 6)
      }
      return max.toISOString()
    },
    dateRange () {
      let sortedDates = this.dates.sort((a, b) => {
        if (a > b) {
          return 1
        } else if (a < b) {
         return -1
        } else {
         return 0
        }
      })

      return {
        start: sortedDays[0],
        end: sortedDays[sortedDays.length - 1]
      } 
    }
  }
}
```

The way this _"hack"_ works is:

- once a date is selected, min selection is restricted (no previous date can be selected)
- once a second date is selected, max selection is restricted (no further date can be selected)
- now you can only select dates between these two
- we will sort the outcome ascendingly, first to last
- the first and last events must be start and end dates

If you want to use this then you will probably need to substitute `date-fns` by something you fancy.
One can probably also enhance this by making `:events` all dates between start and end, so it appears to be marked.
Only downside: you can select more than two dates, which is confusing to the user. However I consider that more of a edge case because the majority of users (especially mobile) will *never* try this.
Hope it helps somebody!

**Comment by ngloom** [comment] 2018-11-07 03:08
Date range picker is a key component for time span related system (like dashboard)
still looking forward for your official support. 
Ps, thanks for the great work !

**Comment by danchapuk** [comment] 2018-11-18 10:00
Anyone know of a good fix for this yet? Standard stuff really for dashboards and booking apps. Thanks in advance :)

**Comment by curiousPup** [comment] 2018-12-28 11:21
Any updates on this?

**Comment by ngloom** [comment] 2019-01-09 04:11
Hi, guys, 
After working with vuetify for a while,  I begin to like Vuetify. But sadly **Date Range Picker** is a very important component for our system, i didn't find any good enough solution by now. 

So i just find one ugly but works Way, by Using [ElementUI Date Picker](http://element.eleme.io/#/en-US/component/date-picker), hope to provide a solution for those need it .

just add this in plugins/vuetify.js
```js
import { DatePicker } from 'element-ui';
import 'element-ui/lib/theme-chalk/index.css';
import lang from 'element-ui/lib/locale/lang/en'
import locale from 'element-ui/lib/locale'

// configure language
locale.use(lang)

Vue.component(DatePicker.name, DatePicker);

Vue.use( Vuetify, { ...
```
and you can using date picker range in system 

```html
<el-date-picker v-model='range' type="daterange"/>
```
and the final result is as below .

![qq20190109-115941-hd](https://user-images.githubusercontent.com/495831/50876325-77dfe800-1407-11e9-8d2a-a45059186150.gif)




At the end ,
1. Element UI is not designed for mobile usage, so it might work well there; 
2. The temporary solution is **ugly**, and still waiting for the official version;
3. Really appreciate for the great work, thanks guys.

**Comment by postmastery** [comment] 2019-01-20 16:42
Vueify is the most comprehensive modern open source UI Controls library I found. But the omission of a date range picker is quite annoying, and also suprising. It's commonly used in reporting applications. 

Besides Element UI, Syncfusion includes a date range picker in its ESJ 2 toolkit for Vue. It supports:

- min, max date
- min, max days in range
- range preset buttons

![syncfusion-daterange-picker](https://user-images.githubusercontent.com/5999630/51442136-0727ae00-1cda-11e9-847d-ec1981ef8da3.png)

**Comment by effysetumeni** [comment] 2019-02-06 07:17
any updates on the date picker ? @johnleider

**Comment by mgohin** [comment] 2019-02-13 09:06
Perfect solution @Darkside73 👍

**Comment by nevendyulgerov** [comment] 2019-02-18 09:33
Here's my solution to this problem. A combo between `vuetify` and [vue-flatpickr-component](https://www.npmjs.com/package/vue-flatpickr-component). I am using a `v-text-field` on top of the default `flatpickr` input field to maintain UI consistency with `vuetify`:

```javascript
<template>
  <div data-component="date-picker">
    <v-text-field
      v-model="date"
      type="text"
      label="Select date range"
      class="date-time-field"
      prepend-inner-icon="date_range"
      :background-color="colors.shades.white"
      box
      @focus="toggleDatePicker"
    />

    <flat-pickr
      ref="datePicker"
      v-model="dateText"
      :placeholder="placeholder"
      :config="dateConfig"
    />
  </div>
</template>

<script>
  import colors from 'vuetify/es5/util/colors';
  import flatPickr from 'vue-flatpickr-component';
  import 'flatpickr/dist/flatpickr.css';

  export default {
    components: {
      flatPickr
    },
    props: {
      date: {
        type: String,
        required: true
      },
      placeholder: {
        type: String,
        default: ''
      },
      config: {
        type: Object,
        required: true
      },
      onChange: {
        type: Function,
        required: true
      }
    },
    data() {
      return {
        dateText: '',
        dateConfig: {},
        isOn: false,
        colors
      };
    },
    watch: {
      dateText(nextDateText) {
        const formattedNextDate = nextDateText.replace('to', '-');

        this.onChange(formattedNextDate);
      }
    },
    created() {
      this.dateConfig = {
        ...this.config,
        onOpen: () => {
          this.isOn = true;
        },
        onClose: () => {
          this.isOn = false;
        }
      };
    },
    methods: {
      toggleDatePicker() {
        this.isOn = !this.isOn;

        if (this.isOn) {
          this.openDatePicker();
        } else {
          this.closeDatePicker();
        }
      },
      getDatePickerInstance() {
        return this.$refs.datePicker.$vnode.elm._flatpickr;
      },
      openDatePicker() {
        const datePicker = this.getDatePickerInstance();
        datePicker.open();
      },
      closeDatePicker() {
        const datePicker = this.getDatePickerInstance();
        datePicker.close();
      }
    }
  };
</script>

<style lang="stylus" scoped>
  [data-component="date-picker"] {
    position: relative;

    .date-time-field {
      z-index: 10;
    }

    .flatpickr-input {
      position: absolute;
      top: 0;
      left: 0;
    }
  }
</style>
```

**Comment by a-di-ez** [comment] 2019-03-01 10:33
My version of @Darkside73 idea:
https://gist.github.com/a-di-ez/e89d381e95e9745b2a88854f148137bb

**Comment by jonnylink** [comment] 2019-05-20 19:39
Is this on the roadmap at all? Just wondering if I should check back or move on.

**Comment by nekosaur** [comment] 2019-05-20 20:40
It is. Hopefully makes it in to 2.0, but no guarantees

**Comment by peluprvi** [comment] 2019-05-29 14:07
Another design approach by https://github.com/leavjenn/SmoothDateRangePicker

![date_range_picker](https://user-images.githubusercontent.com/1561360/58563615-d7e1fa00-8201-11e9-9a8e-57a85ccda829.png)

**Comment by johnleider** [comment] 2019-06-19 23:12
We haven't forgotten about this. It's understood that this is a highly requested feature and it is something we definitely intend to implement. Most of our resources have been allocated towards the v2.0 release, which is a herculean task and detracts from getting to some features. We thank you for understanding and your patience.

If you would like to collaborate on adding this feature to our existing date-picker, please message me in the discord community.

**Comment by alvinthen** [comment] 2019-06-24 01:44
A collab with https://vcalendar.io/ would be great

**Comment by ngloom** [comment] 2019-07-24 09:05
Vuetify 2.0 is released today and still no date range picker   T.T

**Comment by Tinoooo** [comment] 2019-07-24 09:08
@ngloom The date range picker was not planned for Vuetify 2.0

**Comment by ngloom** [comment] 2019-07-24 09:13
@Tinoooo  such a bad news on such a good day

**Comment by siba2893-avantica** [comment] 2019-08-14 17:23
Please pay attention to this feature request. It's a basic need in most apps. I had to use 2 date pickers on my app to fill this need.

**Comment by YipingRuan** [comment] 2019-08-31 06:40
@johnleider 
A naive thinking 

- Use v-date-picker prop "value" to hold array of size 2, [from, to] (have either 0 or 2 items)
- Calculate full array of dates, and send to "VDatePickerDateTable" (converted to the existing "multiple" feature).

![image](https://user-images.githubusercontent.com/5492274/64060199-ffc76c00-cbfb-11e9-958c-a34adea67891.png)

**Comment by esynaps** [comment] 2019-09-20 11:40
It would be great to have time pickers too. In the end it would give a DateTimeRangePicker

**Closed** 2019-10-01 18:01 UTC
Labels: C: New Component, C: VDatepicker, T: feature, help wanted

**Comment by th3n3wguy** [comment] 2019-10-06 21:21
I just need to jump in here and give an absolutely MASSIVE :+1: to the work by @YipingRuan. I am using this feature in my application now and it is amazingly simple.

**Comment by Chandrasekarone** [comment] 2020-02-26 12:27
I've added date range highlighter in this codepen https://codepen.io/chansv/pen/OJVWBbG?editors=0010

**Comment by LaravDev** [comment] 2020-12-20 19:25
Hopefully this is not forgotten, absolutely a great feature to add

**Comment by YipingRuan** [comment] 2020-12-21 02:47
> Hopefully this is not forgotten, absolutely a great feature to add

https://v2.vuetifyjs.com/en/components/date-pickers/#date-pickers-range

**Comment by buzzy** [comment] 2021-06-28 20:18
Why does it say "2 selected" when you select a range? Makes absolutely no sense. Why would it not reflect the number of days that are between the dates? Writing "2 selected" when the user clearly sees that X number of days are selected is very confusing. I understand that the underlying array has 2 dates, but that is not what should be shown to the end user.

**Comment by jacekkarczmarczyk** [comment] 2021-06-28 20:19
https://github.com/vuetifyjs/vuetify/issues/9586

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
