### ISSUE TITLE
[Feature Request] Alert timeout

### ISSUE THREAD

**Issue by cbmahoney** [vuetifyjs/vuetify#13574] opened 2021-04-28 18:06 UTC
### Problem to solve
v-alerts should have some kind of timeout function built in

### Proposed solution
I actually think there should be a single component for alerts and snackbars. Both components have things I wish the other did also. For example, the timeout on alerts, or give some of the same styling props from alerts to snackbar. Also the dismissible prop for alert would also be a good one for snackbar.

**Comment by jacekkarczmarczyk** [comment] 2021-05-17 19:34
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10344

**Closed by jacekkarczmarczyk** 2021-05-17 19:34 UTC
Labels: C: VAlert
