### ISSUE TITLE
v-radio do not display selected correctly if we add v-radio on the fly

### ISSUE THREAD

**Issue by mementototem** [vuetifyjs/vuetify#1907] opened 2017-09-27 05:30 UTC
### Steps to reproduce

Add more `v-radio` by using data that update on the fly (via `array.push()` or new data set) then random select the newly added.

### Versions
- Vue 2.4.4
- Vuetify 0.15.7

### What is expected ?
`v-radio` will display correctly, value of `v-radio` will populate to `v-radio-group`.

### What is actually happening ?
`v-radio` does not display selected item correctly and selected value do not populate to `v-radio-group`.

### Workaround

Update selected value by method that call when `@click.native` on `v-radio`. (**only** newly add `v-radio`)

### Reproduction Link

https://codepen.io/mementototem/pen/boqrQX?editors=1011

Try to select some value and then click `Add Bugs` button, then select newly add value.

**Comment by jacekkarczmarczyk** [comment] 2017-09-27 05:38
It's already fixed on dev branch

**Closed by jacekkarczmarczyk** 2017-09-27 05:38 UTC

**Comment by KaelWD** [comment] 2017-09-27 05:40
Duplicate of #1798
