### ISSUE TITLE
[Bug Report][3.4.9] Invalid aria-owns in v-menu activator. 

### ISSUE THREAD

**Issue by maja-fredstrom** [vuetifyjs/vuetify#19250] opened 2024-02-21 08:22 UTC
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.3.0
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a simple web page with a simple menu. 
Open the menu.
Scan the page with "axe DevTools - Web Accessibility Testing
4.74.1" extension to chrome .

### Expected Behavior
No accessibility issue

### Actual Behavior
You get this accessibility issue:
Ensures all ARIA attributes have valid values.
Element Location:
button[aria-owns="v-menu-759"]
<button data-v-b9767396="" type="button" class="v-btn v-btn--elevated v-theme--light bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated" targetref="[object Object]" aria-haspopup="menu" aria-expanded="true" aria-owns="v-menu-759">
To solve this problem, you need to fix the following:
Invalid ARIA attribute value: aria-owns="v-menu-759"

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtUj1v4zAM/Ss8LWqB2DlcbzkjLXC4G7p07tB0UGymECJLgsS4LQz/91Jy3dieO4kf75FPJJ96EUO9/et92Z1RVGJH2HqjCO/2FmDXFcr7bGandpaUthg+QzlI+EbFUaNpoCta16C53Ys2vuwFbOe4Fu0ZKuNqRdpZxkzmXnzBGDgJ4GLROKpUTbpT5AIzevDB+QjDgpKrH8hC7UyG+aBbFd5ZQKPCiQsdtG1ynMlMhf9sNO7Vwm6bmfP+29kEZuGuMDrSumuKFZoZ3OSYe18lbwPcEN+u+YHkc1OoTvjO+ZxYyV+WKkiTwbu+z9QyezAMSeoas1Azzy8+tJKeAmkX01rZXe41Rca1r4axi3XQniAincer0K13gaCHgEcY4BhcC5IvSY6z47qRgG8BbhPiSt6jMQ4eXTDND3l9geQhMehp1NRD/l8F8p/R9QkeUMKw+e4c/Jqyzxcl01FmNZKclxuQB0fk2mRFUoGSgbZJT42WMMhcwOCFzuwMSTMcp8bzEsNG3JQ35U+R3t/lH/H8AZVEF4o=)

### Other comments
You are not able to scan the menu in reproduction link, because the menu is located in an iframe.

**Comment by KaelWD** [comment] 2024-02-21 08:25
Duplicate of #19054

**Closed by KaelWD** 2024-02-21 08:25 UTC
Labels: S: triage
