### ISSUE TITLE
[Bug Report] VAutocomplete within VDialog may get perma-stuck open on VDialog close

### ISSUE THREAD

**Issue by Dylan-Chapman** [vuetifyjs/vuetify#4601] opened 2018-07-12 19:14 UTC
### Versions and Environment
**Vuetify:** 1.1.4
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
1. Open dialog
2. Select autocomplete value (may have to double click the value to get the menu to close..?)
3. Close dialog

### Expected Behavior
Dialog closes, no lingering autocomplete dropdown

### Actual Behavior
Autocomplete dropdown re-opens and gets stuck when dialog is closed

### Reproduction Link
[https://codepen.io/anon/pen/RBPYyP](https://codepen.io/anon/pen/RBPYyP)

### Other comments
This only happens if you don't blur the autocomplete after selecting an item and before closing. With Codepen, I could only replicate it inconsistently, and only with an ```items``` defined as an inline array (as opposed to being defined in ```data()```. However, in my own application, it's happening with ```items``` being defined in ```data()```.

**Comment by KaelWD** [comment] 2018-07-12 19:25
Duplicate of #4585

**Closed by KaelWD** 2018-07-12 19:25 UTC

**Comment by Dylan-Chapman** [comment] 2018-07-19 22:10
This still appears to be a problem in 1.1.7. Just...less consistent? The above codepen still reproduces the problem.
