### ISSUE TITLE
Full screen dialogs do not allow page to scroll after closing

### ISSUE THREAD

**Issue by StratusBase** [vuetifyjs/vuetify#747] opened 2017-06-11 17:43 UTC
### Steps to reproduce
- Open reproduction link.
- Go to "#3 Fullscreen" Demo
- Click "Open Dialog", then close the dialog, then try to scroll...

Another thing I will point out is if you re-open a different (not fullscreen) dialog, and close it, you can regain scrolling abilities.... Hopefully this helps.

### Versions
v0.12.7

### What is expected ?
When a dialog is closed, the browser can scroll.

### What is actually happening ?
The following CSS applied to the html tag never gets removed, thus disabling scrolling and making the screen look odd...

```
overflow-y: hidden;
padding-right: 17px;
```

### Reproduction Link
https://vuetifyjs.com/components/dialogs

**Comment by johnleider** [comment] 2017-06-11 23:27
Duplicate of #700 and #739. Please attempt to search for issue before posting.

**Closed by johnleider** 2017-06-11 23:27 UTC
