### ISSUE TITLE
[Bug Report][3.7.4] v-slide-group: can never see some of the items in full. 

### ISSUE THREAD

**Issue by WhiteSage** [vuetifyjs/vuetify#20711] opened 2024-11-17 12:09 UTC
### Environment
**Vuetify Version:** 3.7.4
**Vue Version:** 3.4.27
**Browsers:** Firefox 132.0
**OS:** Windows 10

### Steps to reproduce
If a v-slide-group width is not a multiple of the width of the individual items then some items will never be shown in full. This makes interacting with them really awkward, and the behavior cannot be tweaked as v-slide-group has no property to edit the slide displacement.

### Expected Behavior
Always slide to the start of the first item which overflows, or to the end.

### Actual Behavior
Slide the width of the parent component.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUstuwjAQ/JWVL73EAQEtUkRfX9BDj4SDmyzg4tiW7fBQlH+vHRdiyCk7M94Z73rdkU+t82OLpCArh40WzOFbKQFWR2r3iC78A1SCWftakuZMWetUSSLcsDM98drtPfUynUZ4OB4bCF4j3RnV6ogB2L06UWaMOtkI/asf9ZT7NFcK4Ei3yngTCVzC7PnqH77igJfApFhopZxHO+D2GwVWDusMnNrtBEI/Sm/ug/+Pk2PtO1dKDK5jD3iHJ214w8zlCQpoZY1bLrFOzZNpMTq7Z/zV/JE6hT4qwauDV8d0qT5JB/ClHVfSQteBhL5Pgk+G5OMgff04yetO7qm46ICFTftqNbm9AZIRweXB5r9WSf86upJU1pakWG96z/FGK+Now3QiiGAQdX1P+ozM80U+W3r5PF/mC5I50+LmD2KPud0=)

### Other comments
The bug persists in the latest version as shown by the playground code which originates from the official documentation ( https://vuetifyjs.com/en/components/slide-groups/ ).

A workaround would be appreciated.

Related v2 issues:
https://github.com/vuetifyjs/vuetify/issues/10475
https://github.com/vuetifyjs/vuetify/issues/15916
https://github.com/vuetifyjs/vuetify/issues/12780

**Comment by KaelWD** [comment] 2024-11-20 05:59
Duplicate of #15916

**Closed by KaelWD** 2024-11-20 05:59 UTC
Labels: S: triage
