### ISSUE TITLE
[Bug Report] Misaligned prepended icon on single-line full-width v-input-text

### ISSUE THREAD

**Issue by fabcall** [vuetifyjs/vuetify#5723] opened 2018-11-23 18:54 UTC
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Edge 17.17134, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Add a prepended icon to a single-line full-width v-input-text

### Expected Behavior
When adding a prepended icon to a single-line full-width v-input-text, it should be aligned within the input.

### Actual Behavior
When adding a prepended icon to a single-line full-width v-input-text, it's placed higher than then input baseline.

### Reproduction Link
<a href="https://codepen.io/fabcall/pen/VVxaxd" target="_blank">https://codepen.io/fabcall/pen/VVxaxd</a>

**Comment by jacekkarczmarczyk** [comment] 2018-11-25 05:48
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4544

**Closed by jacekkarczmarczyk** 2018-11-25 05:48 UTC
