### ISSUE TITLE
[Bug Report][3.3.5] VDatePicker not returning the selected value if any other locale except en is selected and it always returns a date - 1 day

### ISSUE THREAD

**Issue by Techbinator** [vuetifyjs/vuetify#17682] opened 2023-06-23 10:32 UTC
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1) When setting a locale any other then the en the computed value set property does not return the selected value. In the reproduction link unfortunately for some reason the import { de, en, fr, it } from 'vuetify/locale'; in the vuetify.js file does not find them(vs on local dev where the import works). In order to reproduce it just uncomment the code in vuetify.js and Dp.vue.
2) In Dp.vue i always need to date.setDate(date.getDate() + 1); 

### Expected Behavior
1) Should return the proper value when another locale is selected in the 
``` const calendarDate = computed({
     set(newValue) {
```
2) Should get the newValue with the actual selected date without the need to always add 1 day ` date.setDate(date.getDate() + 1);`

### Actual Behavior
1) Does not return the selected calendar value if another locale is selected, instead of an array of dates it returns an empty object
2) Should return the selected date

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlV1tv2zYU/iuc9mAbs6QW7TbAy6UDugEFhjRAg7zYeZAl2mYskQJJ2TEC//d9h6QudoKhWf1ikzzX71w9f452DbdidUgeTTSLRFUrbdkzyzXPLL/3b+zIVlpVbBRoRwuZpiulmVEVZ6A0SjK7EYYVihsmlWV7pbdswzVngp44K3iliK3TUPAp43IKyVMm7LmKtFR5VvLRHwu5kPzJ8eRKGssCAbs8tXH8vJCMNFV85qSvsqa0d/48KjK9HbHjlGjSIBtk/lhxY7I1N57v1KrAQd/HyUJG0+jPuk5gA8C6sLyqS5hwRUQXuzira/fTHWCtzYTkOlzh8nPNdnGlCl5eLqICjIuIpS1Hes5CN17iRTrQhKPJtagtM9w2XmEHquarIZIIVPcI5f4+ST87D/BIzx5VsgaQgn8s+Z59xnE8gcMXqVcGNfDdi4qrrEa6KAkMHISL8GAWUQCV7qCCzotoY21tZmmaFxJs8F7sdCK5TWVdpZ9AlupGWlHxuFDVpw/Jh+RjWghjh9cJN1W81GpvuIaQReQCE9RQ/L9DVaB0Gn71GsJVXGZLQypeiE6hb8d1rLkskM36ez06Yxt6dfb0wjPSfkS6Ae9SyK05gzo3DuZ5a+QPueyEkaQHr9Bnxmu5XXHZeJV9Crs7x87YLC+V4bGSLou5tHFeinwLqlVWGmRCIJNNseaxFuuNxdvHd+2D1Zk0wgolcW2oPuP+qiVSqxWSPj74UyVkvBeF3YAja6zyVG09tQ6wn7Pcil1mlQbdM6u1qg0Ajvq63MWWP9l4JXhZtJdDP4WsG0sl0dpBH+DnHs/v7aHmXXkPpS2FLJwFSZI4I6b0i+i+kPzb1q6W54oaQG9Y1ydOIuOsJxlxDbSRn4G5N56glOh/p3ZuRMFjAgbVf3K353xbZIfu0gpbkj896wxpBAMOTu2Zgvm7h56wc5kIb515zsme4pNDNmQS2s9JqvTx6UO54RmKBsicgwCoBih0/ZPknjfQk/aJMMo1DKDe5WW1vRQTBK3YGTylcYLDX5WwOOSqgtW8mFK7HHZbN6xoXDCxckPPDxqGwQhlzCrIGWNsZvJgN3LN+FPOYQiXE6L2c9LwkucQznZZ2ThWGqcatmqJ2zBNh5g72RW3G+WTl9S386Ax/B9vw/kIh62e1vd/TPxGoyXRIL7s2caTns6/J96uS8zUzuEgw1fWZQDLIeenMtUqZeM9sXYTItTKzA2b0HPxCZN7xvo51D76aUw0J0XzUuLX5SNAZJlhRHCHu4vbTFuRlRf3d6iov11BXb2idDxhl1ds/Hx8Xekgi9+mlRzxzG9TewwB8AhzJGAHsMvG8XzU1GTZrEd49EBMA7aTbMHeFPK3C86aWxjQu+Ozjc1dQJNe8AO7vmbzB2/RABkkIG0NjmYo52S1aAnQIloBLq+WzdqnZrvYwcWs3KMFkVzjl0cSsRd2w5Sk04GV2NlYI93XQTVYPJslstzNnKH0djquwdwsE7jeDsBH0/5KhTENN+n73397/6GPDXQmsMCloDsAJp+P7Bf2PsSFPhSV8SthQNvAzYCQulFXP67XnUHpoj0IXDd43hC186BdJ1Z9+fb1m9VCrseT6wTNm+y9G00QCoroKDSD/xFRX6Ad5Ulg8w3Pt9QJHTkaGTwX/XzFw/inm6ZaYu0R5ia76RdPBxvBfYftD2vo0II3wI0l6k3Ad/6FaUTLsCOmx8EiTCPEHko/e1yI5m7o41+GRfHNZhiiy63ABhTqLkylGNNQ5LSIOKX/xSkk/gXEpsaGs2ysxd+rgECYveiOqARnM7yEbcGe6DiN3KqJXc7tfNHDv885g4U=)

**Comment by kingyyy** [comment] 2023-06-25 08:32
Same problem here when set locale "ar" nothing works

**Comment by KaelWD** [comment] 2023-06-28 09:18
Duplicate of #17615

**Closed by KaelWD** 2023-06-28 09:18 UTC
Labels: S: triage
