### ISSUE TITLE
[Bug Report][2.6.1] On mobile, we can scroll the content behind a full screen v-dialog

### ISSUE THREAD

**Issue by ikushum** [vuetifyjs/vuetify#14939] opened 2022-04-08 05:38 UTC
### Environment
Vuetify Version: 2.6.0
Vue Version: 2.6.11
Browsers: Chrome 99.0.4844.59
OS: iOS 15.3

### Steps to reproduce
1. Create a vertically long page that can be scrolled downwards. (height: 3000px should be enough).
2. Add a full-screen v-dialog inside the page.
4. Use this UI on your phone.
5. Open the dialog.
6. Try to vertically scroll downwards inside the dialog.

### Expected Behavior
Nothing should happen.

### Actual Behavior
The content behind the dialog is scrolled and when you close the dialog, you end up somewhere in the middle of the page.

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-2-forked-0kimug?file=/src/App.vue" target="_blank">https://codesandbox.io/s/vuetify-2-forked-0kimug?file=/src/App.vue</a>

### Other comments
This issue doesn't exist when reproduced on codepen. Could reproduce only on codesandbox

**Comment by KaelWD** [comment] 2022-04-08 05:41
Duplicate of #3875

**Closed by KaelWD** 2022-04-08 05:41 UTC
Labels: S: triage
