### ISSUE TITLE
[Bug Report] Navigation drawer width problem when toggle between mini and normal width

### ISSUE THREAD

**Issue by s13571** [vuetifyjs/vuetify#10641] opened 2020-02-21 10:31 UTC
### Environment
**Vuetify Version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.116
**OS:** Mac OS 10.15.3

### Steps to reproduce
1. Create Navigation drawer as in the codepen, with width 200px and possible mini variant which is toggled by clicking button (for instance)
2. Navigation drawer is in normal mode at the beggining (not mini)
3. Click button and change navigation drawer to be mini
4. Click again and go back to normal mode, drawer is no longer moving content but showing on top of everything

### Expected Behavior
When toggle between mini (true or false) expect content next to navigation drawer to move with it

### Actual Behavior
When toggle between mini (true or false) navigation drawer is showing on top of everything (covering content and app bar)

### Reproduction Link
<a href="https://codepen.io/BartyLA/pen/jOPVPBy" target="_blank">https://codepen.io/BartyLA/pen/jOPVPBy</a>

**Comment by whoistobias** [comment] 2020-02-22 20:21
This is a duplicate of #8223. @s13571 There's actually a pretty easy workaround for the time being. I'll mark this one as a duplicate since the other issue covers it already.

**Closed** 2020-02-22 20:21 UTC
Labels: C: VNavigationDrawer, duplicate
