### ISSUE TITLE
[Bug Report] Unable to set initial value to input-search for async v-autocomplete

### ISSUE THREAD

**Issue by birdlavv** [vuetifyjs/vuetify#4329] opened 2018-06-18 01:22 UTC
### Versions and Environment
**Vuetify:** 1.1.0-beta.3
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Mac OS 10.13.5

### Steps to reproduce
Open pen and note how the `:search-input` is not visibly being set. This prevents users from seeing the value of the autocomplete when the value is fetched from a remote source.

### Expected Behavior
That the `:search-input` would be set during its initial load, as it does when the `:items` are not async - https://codepen.io/George6789/pen/aKVYzE

### Actual Behavior
The `:search-input` is not being set on the initial load.

### Reproduction Link
[https://codepen.io/George6789/pen/ZRarPp](https://codepen.io/George6789/pen/ZRarPp)

**Comment by jacekkarczmarczyk** [comment] 2018-06-18 17:06
Looks related to #4000 (maybe even the same issue)

**Comment by johnleider** [comment] 2018-06-19 19:53
Duplicate of #4000

**Closed by johnleider** 2018-06-19 19:53 UTC
