### ISSUE TITLE
[Bug Report] v-select with no items does not display "no data" tile

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#2936] opened 2018-01-04 22:10 UTC
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.84
**OS:** Windows 7

### Steps to reproduce
Create a `v-select` with empty items array.

### Expected Behavior
When clicked, the menu should show one disabled list tile with the value from the `no-data-text` prop.

### Actual Behavior
Menu does not show.

### Reproduction Link
[https://codepen.io/anon/pen/wprgvx](https://codepen.io/anon/pen/wprgvx)

### Other comments
The menu and list tile is actually added to DOM, but stays hidden because of [this check](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VSelect/mixins/select-computed.js#L101). It sets `display: none` if length of ìtems` array is 0.

**Comment by KaelWD** [comment] 2018-01-05 01:45
Duplicate of #2081

**Closed by KaelWD** 2018-01-05 01:45 UTC
