### ISSUE TITLE
[Feature Request] clearable icon should not display for readonly fields

### ISSUE THREAD

**Issue by mahammad8564** [vuetifyjs/vuetify#9848] opened 2019-12-02 13:10 UTC
### Problem to solve
User can clear the value for readonly fields

### Proposed solution
Hide the clearable icon when readonly is true just like the disabled option.

**Comment by KaelWD** [comment] 2019-12-02 13:22
Duplicate of #7111

**Closed by KaelWD** 2019-12-02 13:22 UTC
Labels: triage
