### ISSUE TITLE
[Feature Request] Scrollable DataTable body

### ISSUE THREAD

**Issue by gdavis2** [vuetifyjs/vuetify#7404] opened 2019-06-05 13:26 UTC
### Problem to solve
I would like to have a datatable that has a fixed header/footer with a scrollable body. This would be useful in conjunction with pagination features where, say, 100 items are rendered, but due to screen size, only 30 can be viewable at a time. I can work around this with clever css so that the table is scrollable, but the header and footer scroll in/out of view. This is extremely useful if I want the table to take up all of the available screen space where headers/footers/pagination are always visible.

### Proposed solution
It would be nice if this were a simple property on the v-data-table component (like scrollBody) but I suspect it's a little more complex than that and may need to work in conjunction with the layout settings as well.

**Comment by jacekkarczmarczyk** [comment] 2019-06-05 13:28
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1547

**Closed by jacekkarczmarczyk** 2019-06-05 13:28 UTC
Labels: triage
