### ISSUE TITLE
implement in v-text-field text-align

### ISSUE THREAD

**Issue by JeanGoncalves** [vuetifyjs/vuetify#2045] opened 2017-10-06 14:49 UTC
### Steps to reproduce

``` <v-text-field type="number" align="right"></v-text-field> ```

### What is expected ?
``` <v-text-field type="number" align="right"></v-text-field> ```

**Comment by jacekkarczmarczyk** [comment] 2017-10-06 14:52
This is a feature request - please use the feature request template
```
- Answer those questions:
  - What will it allow you to do that you can't do today?
  - How will it make current work-arounds straightforward?
  - What potential bugs and edge cases does it help to avoid?
```

**Comment by KaelWD** [comment] 2017-10-06 15:13
Duplicate of #1782

**Closed by KaelWD** 2017-10-06 15:13 UTC
