### ISSUE TITLE
[Feature Request] Out of the box support progressive image

### ISSUE THREAD

**Issue by ekoeryanto** [vuetifyjs/vuetify#3448] opened 2018-03-02 22:23 UTC
### New Functionality
VParallax, VCard, etc with progressive image support

### Improvements
it will allow our site event faster

### Bugs or Edge Cases it Helps Avoid
Slow loading on big picture load

**Comment by KaelWD** [comment] 2018-06-09 13:31
Duplicate of #2951 and #2696

**Closed by KaelWD** 2018-06-09 13:31 UTC
Labels: T: feature
