### ISSUE TITLE
[Bug Report] v-combobox does not close when pressing the arrow.

### ISSUE THREAD

**Issue by RoyBkker** [vuetifyjs/vuetify#9393] opened 2019-10-17 14:45 UTC
### Environment
**Vuetify Version:** 2.1.4
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Linux

### Steps to reproduce
Open the combobox by pressing the arrow on the right. Press the arrow again. 

### Expected Behavior
Combox should close / disappear

### Actual Behavior
Combox stays open.

### Reproduction Link
<a href="https://codepen.io/RoyBakker/pen/JjjRKBO?&editable=true&editors=101#anon-login" target="_blank">https://codepen.io/RoyBakker/pen/JjjRKBO?&editable=true&editors=101#anon-login</a>

**Comment by jacekkarczmarczyk** [comment] 2019-11-09 09:22
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6564

**Closed by jacekkarczmarczyk** 2019-11-09 09:22 UTC
Labels: triage
