### ISSUE TITLE
[Bug Report][3.1.15] Navigation drawer overlay doesn't appear on RTL mode

### ISSUE THREAD

**Issue by smortexa** [vuetifyjs/vuetify#17205] opened 2023-04-21 22:18 UTC
### Environment
**Vuetify Version:** 3.1.15
**Vue Version:** 3.2.47
**Browsers:** Google Chrome
**OS:** Mac OSX, Android

### Steps to reproduce
- Set an RTL locate
- Use `<v-navigation-drawer>` with any location
- Open the drawer

### Expected Behavior
Showing the overlay with navigation drawer and close the drawer when clicking on the overlay in RTL mode.

### Actual Behavior
The overlay won't appear, and the drawer won't close when clicking outside the drawer.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVc1S2zAQfhXVl8AMsqGU6YwLGdoDt946vWAOir1J1MiSRlISApN370qyHduBAvXFknb17be/un9ONmtwfL5L/9gkT3itlXHkmZQGmIPfUUb2ZG5UTSaN7qSQhYTHoFoqaR1pBORmePHkuZCEuCXUkCNoBXO2Fu5X3E8EXyzdhOzPvJJQJRNey2/i1x5N5mwSdOI3Z0LMWLlCAchW4EH2p4VMzpLvWqfIB725dlBrgXSmXul6Q0tmqrAOO6Z1s8HtJ0r9md1ZvERnzKBnQpmbIqkANNVrowWQipkVSHpZJNPrrK89JZQiWAcX0L3gwLvF04bXzOyK5CDSGF0uQbr2qOPVh6KSbSjHgJMNM5xJh2AOHl2RkNtS8HKVWqe0Z2zYFgwm41NcNWzHMD2+wYxTCgNrqONOwPTnjsy5AOtvDiWja1azEkyMR1yOFGbuBcaeAO7qitOaLSQWS8MStT8KgDxd5+V/3K+Us3QDxnEsuAFMA3EI3jDHGEm+YI4rSZtId2Y3tFYViC4b/XT7slTG18CL6RbcdoXgv5zjBYtI4d8HCky9+oDqEash6ZpxSazbCUDIJfgmzMnV+bl+/Ia+D5j4fqE+Xr1jQrB/ycEGaapty4UgGCXA1gnTAtuezJRzuEQtW2PboprlT0AsTgmQNu0ZQ97H1vypp9v2bMxD7ObmAm6us16f4xbRuY4gzZBqBk87XCrmWE5OTsnNlMQRFU6DH7mfLxa6ebMwaq1zItdCdGchDzm5P9DvTS1Mr+8SnE53SvXnFtYEE+swz4aCOAD/AfSDmZeBsCA/BHTHn55eoTSSvM1p/RrUbCQ5QD20w/oUF3G5Za5c9qZ+CLdPTc+oW3KbdjMtpKcVttjxv/e10GQfHwLB5criu6YkvgUBr0hKiw3UpQ7r3zlt8ywrK4ma2LB8Y1IJLpO6zppX7fYyvUgvrrIKG609o4LNbBrQPNQDvj5oMT6fWLJ6ZDYKgunGscI/vH7/BodbVMvMWjpeAw6qGsl8Tr98jWR65ylYfIiM2lowiFIkTWSCHc/4Hbbe9BdtHGFnaBBnJzUgKzB+0L3Pp9G1gV8j2ZFvTbL3yf4sifcw+JF18vAXahC2zA==)

### Other comments
In RTL mode, the navigation drawer overlay doesn't appear or has wrong place outside of layout.

**Comment by hamedg68** [comment] 2023-04-22 19:55
I also have the same issue

**Comment by TouatiDev** [comment] 2023-04-29 07:35
i got the same issue and i fixed it by adding this to my CSS style

```css
.v-locale--is-rtl .v-navigation-drawer__scrim {
  inset: unset !important;
}
```

**Comment by hamedg68** [comment] 2023-04-29 19:05
@TouatiDev thanks it solved the issue

**Comment by KaelWD** [comment] 2023-05-01 17:31
Duplicate of #16261

**Closed by KaelWD** 2023-05-01 17:31 UTC
Labels: S: triage
