### ISSUE TITLE
[Bug Report] Input underlines are disappeared

### ISSUE THREAD

**Issue by TheRatG** [vuetifyjs/vuetify#4171] opened 2018-05-31 07:25 UTC
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Mac OS 10.13.4

### Steps to reproduce
Change zoom of page, for example -50%.

### Expected Behavior
Show input underline

### Actual Behavior
Input underline has gone

### Reproduction Link
[https://codepen.io/pen/?editors=1000](https://codepen.io/pen/?editors=1000)

### Other comments
Screenshots:

. https://pasteboard.co/HnGT72s.png
. https://pasteboard.co/HnGTenh.png
. https://pasteboard.co/HnGU370.png

**Comment by KaelWD** [comment] 2018-05-31 07:31
Duplicate of #3090

**Closed by KaelWD** 2018-05-31 07:31 UTC
