### ISSUE TITLE
[Bug Report] v-autocomplete component with readonly property enabled is not readonly

### ISSUE THREAD

**Issue by GrRivero** [vuetifyjs/vuetify#10213] opened 2020-01-14 10:43 UTC
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Windows 10

### Steps to reproduce
1.- Click in arrow to desplegate menu
2.- Click in menu option

### Expected Behavior
Not desplegate menu and not selectable option

### Actual Behavior
Desplegable menu and selectable option

### Reproduction Link
<a href="https://codepen.io/GrRivero/pen/wvBxwJd" target="_blank">https://codepen.io/GrRivero/pen/wvBxwJd</a>

**Comment by KaelWD** [comment] 2020-01-14 10:44
Duplicate of #9960

**Closed by KaelWD** 2020-01-14 10:44 UTC
Labels: triage
