### ISSUE TITLE
[Bug Report] Tabs in Expansion Panel Bug

### ISSUE THREAD

**Issue by cn-xufei** [vuetifyjs/vuetify#7398] opened 2019-06-05 03:26 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.9
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.5

### Steps to reproduce
If the tab items overflow their container, pagination controls will appear.
BUT
In Expansion Panel it not work

### Expected Behavior
Hope pagination controls will appear.

### Actual Behavior
pagination controls not appear

### Reproduction Link
<a href="https://codepen.io/cn-xufei/pen/EzJXQQ" target="_blank">https://codepen.io/cn-xufei/pen/EzJXQQ</a>

**Comment by jacekkarczmarczyk** [comment] 2019-06-05 03:52
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6626

**Closed by jacekkarczmarczyk** 2019-06-05 03:52 UTC
Labels: triage
