### ISSUE TITLE
[Bug Report] Default theme applied for a moment on page reload

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#10033] opened 2019-12-23 08:42 UTC
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.79
**OS:** Linux x86_64

### Steps to reproduce
- clone repo
- yarn install
- yarn dev
- open browser
- refresh page

### Expected Behavior
App bar and button colors are primary

### Actual Behavior
App bar and button colors are dark initially and then become primary (see attached demo)
![Peek 2019-12-23 10-34](https://user-images.githubusercontent.com/339596/71346575-dcd91300-2570-11ea-9747-da4676f06d08.gif)

### Reproduction Link
<a href="https://github.com/Darkside73/nuxt-vuetify-theme" target="_blank">https://github.com/Darkside73/nuxt-vuetify-theme</a>

**Comment by KaelWD** [comment] 2019-12-23 09:09
Duplicate of #9499

**Closed by KaelWD** 2019-12-23 09:09 UTC
Labels: triage
