### ISSUE TITLE
[Bug Report] Combobox input not cleared after selection

### ISSUE THREAD

**Issue by maxcorbeau** [vuetifyjs/vuetify#10393] opened 2020-01-30 15:18 UTC
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 75.0.3770.80
**OS:** Linux x86_64

### Steps to reproduce
-Enable the "Multiple" option
-Start typing "pro"
-Select "Programming"

### Expected Behavior
-Upon selecting an option, the previously typed input ("pro")  should be cleared, thus allowing users to immediately start typing/searching for another option

### Actual Behavior
-Despite the option being selected, the input "pro" remains, forcing users to remove what they've just typed in order to start typing and looking for another option to add

### Reproduction Link
<a href="https://codepen.io/maxcorbeau/pen/dyPBoKY?editable=true&editors=101" target="_blank">https://codepen.io/maxcorbeau/pen/dyPBoKY?editable=true&editors=101</a>

### Other comments
This is a bug as it completely kills the UX: when users select an option, there is no need for them to select it again (it's already selected), thus there is no point in leaving their input, instead the input should be cleared so that users can start typing another string, to select another option. This is even made worse by the hint message that is immediately displayed and says there is no option matching (since it was already selected).

See how multi combobox should work:
https://yaireo.github.io/tagify/
https://github.com/jshjohnson/Choices
https://github.com/select2/select2
https://github.com/shentao/vue-multiselect
https://github.com/Mobius1/Selectr
https://selectize.github.io/selectize.js/

The reproduction link I gave is a unchanged copy of https://vuetifyjs.com/en/components/combobox#no-data-with-chips

**Comment by edwardsph** [comment] 2020-01-30 16:19
So you you raised this bug - I just came across the same issue and found your bug top of the issue list. Thanks.

**Comment by johnleider** [comment] 2020-01-30 19:01
Duplicate of #5926

If you have any additional questions, please reach out to us in our Discord community.

**Closed by johnleider** 2020-01-30 19:01 UTC
Labels: triage

**Comment by maxcorbeau** [comment] 2020-01-31 08:02
IMO should be marked as duplicate of https://github.com/vuetifyjs/vuetify/issues/8842 (seeks same behaviour) not https://github.com/vuetifyjs/vuetify/issues/5926 (seeks the opposite behaviour)
