### ISSUE TITLE
[Bug Report][3.5.15] Calender events

### ISSUE THREAD

**Issue by sema005** [vuetifyjs/vuetify#19580] opened 2024-04-10 11:39 UTC
### Environment
**Vuetify Version:** 3.5.15
**Last working version:** 2.6.4
**Vue Version:** 3.4.19
**Browsers:** Chrome 123.0.0.0
**OS:** Windows 11

### Steps to reproduce
Click the prev and next buttons build inside the calender component
Added text under the calender to show what event its triggered

### Expected Behavior
Expect it to emit the "prev" and "next" emits

### Actual Behavior
It only emits the "update:model-value"

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUtFqq0AQ/ZXBFw00Cfc+igkNZCmFNi3BhkLTB9FJFFZ3WVfbEPz37q5xtWlaaB/U8ZyZObNz9uXolCKeLjif1BU6vhNIzDmNJM63BUBQjwV7g5hGZTnbOruM0nGK2T6VW8ckmJSYUVCPzvj33xItFVEskkh0EIDAncqzuNMz9ThnCVKtw+KqHFI+1lhILdAGQ04pM6EYLrI8EochJQ8cFZOzQqZD/LrAd6kI/SG64SeSC6xNP6y/khVP1HJ8M+m4jmilBVrwXmMbDfUV82DaL6HbmIYY/bS/fmd8bkRBimy/R4GJD8cjmGOHHQRNE0z5hXY6VoapOJgOjFS/ZSwyLk0SvnMmJCS4iyoq4di2USeIfPBGMJuDd8IAjBM+vBT4BkvVzBu9XnVca4UizyA7pg/u6mFF3BPdjE5BjjJliaq0MtYIpW9BbW1RMooTyvaeuyLPIZANWYUQrm9vbsiaLN3RwOw0Kydne5qpCWyZ2+U2dl7r8Q+6j2uy+YNuX3ZB9/zCeAcsv5/g6XG5CAncPyzJHWwWd0/kV5NcKL88V/tt9OWx18VproqKUvN6/QBe4kG8)

**Comment by blalan05** [comment] 2024-07-13 03:49
Duplicate of #19020

**Closed by blalan05** 2024-07-13 03:49 UTC
Labels: S: triage
