### ISSUE TITLE
[Bug Report] <v-tooltip> with <v-btn> is moved too much to the left

### ISSUE THREAD

**Issue by infinity0n3** [vuetifyjs/vuetify#3622] opened 2018-03-19 22:52 UTC
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.16
**Browsers:** Chrome 63.0.3239.108
**OS:** Linux x86_64

### Steps to reproduce
Add a tooltip around a button inside a <v-toolbar>. You'll notice the icon being pushed the to left. The example shows how the button is position without and with tooltip.

### Expected Behavior
Button should be at the same position as without a tooltip.

### Actual Behavior
Button is pushed to the left.

### Reproduction Link
[https://codepen.io/keslerd/pen/vRgxBY?editors=1000](https://codepen.io/keslerd/pen/vRgxBY?editors=1000)

**Comment by infinity0n3** [comment] 2018-03-20 00:49
Adding `not(.tooltip)` to toolbar style at [&__content, &__extension ... :last-child](https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_toolbar.styl#L62) seems to fix the issue. Probably should be applied to `:first-child` too.

**Comment by praveenpuglia** [comment] 2018-03-20 11:56
Possibly a duplicate of #3205 ?

**Comment by KaelWD** [comment] 2018-03-20 12:47
Not quite: that was about height, this is about margins.

**Comment by KaelWD** [comment] 2018-07-29 09:53
This was fixed by #4305

**Closed by KaelWD** 2018-07-29 09:53 UTC
Labels: T: bug
