### ISSUE TITLE
[Bug Report][3.0.4] VTab generates invalid keyframe background-color value

### ISSUE THREAD

**Issue by tve** [vuetifyjs/vuetify#16258] opened 2022-12-10 03:54 UTC
### Environment
**Vuetify Version:** 3.0.4
**Vue Version:** 3.2.45
**Browsers:** Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
- open codepen in firefox (used 107.0 on linux)
- open browser console (not just codepen console)
- flip between tabs and watch warning in console:
```
Keyframe property value “” is invalid according to the syntax for “background-color”. animation.ts:46:23
Keyframe property value “” is invalid according to the syntax for “transform”.
```
- using a breakpoint, this is caused by https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VTabs/VTab.tsx#L98

### Expected Behavior
No warnings

### Actual Behavior
```
Keyframe property value “” is invalid according to the syntax for “background-color”. animation.ts:46:23
Keyframe property value “” is invalid according to the syntax for “transform”.
```

### Reproduction Link
[https://codepen.io/codesurfr/pen/MWXRvWv](https://codepen.io/codesurfr/pen/MWXRvWv)

### Other comments
I'm flagging this because it is polluting the browser log with warnings and I can't see other actually useful warnings. Dunno what your policy on such warnings is. The warnings are not shown in an up-to-date vivaldi browser, for example.

**Comment by KaelWD** [comment] 2022-12-11 13:14
Duplicate of #15696

**Closed by KaelWD** 2022-12-11 13:14 UTC
Labels: duplicate

**Comment by wizzer129** [comment] 2023-02-15 04:39
Experiencing same warning issue with VTabs

**Comment by JonPichel** [comment] 2023-03-15 16:09
Same for me, when changing the selected tab.

**Comment by djeetee** [comment] 2023-04-15 16:45
Same here. any resolution or workaround? thanks
