### ISSUE TITLE
Timepicker input doesn't update textfield when value is pre-set

### ISSUE THREAD

**Issue by keystorm** [vuetifyjs/vuetify#1839] opened 2017-09-22 16:56 UTC
### Versions
Vuetify 0.15.7
Chrome 61

### What is expected ?
A default value is pre-fed to an in menu time picker via `v-model`. Time can be changed by using the picker and the new value is displayed in the text field.

### What is actually happening ?
Whenever a new time is picked, the new value is not shown by the `v-text-field`; the original value persists. The same happens in modal.

### Reproduction Link
https://codepen.io/anon/pen/GMjGgZ

**Comment by johnleider** [comment] 2017-09-22 23:03
Duplicate of #1812

**Closed by johnleider** 2017-09-22 23:03 UTC
