### ISSUE TITLE
[Feature Request] v-autocomplete and v-select-list filtering behavior

### ISSUE THREAD

**Issue by userquin** [vuetifyjs/vuetify#6610] opened 2019-02-26 11:23 UTC
### Problem to solve
When filtering items with custom filter prop function, once the menu popup appear, the selected text can be wrong.
For example, I have to support spanish and french languages, so items returned by the server can contain some accents, for example á, ê, etc...
I have made a simple normalizeString function like this (using ES5 normalize string function):
```javascript
const normalizeString = (s, transform = s => s.toLocaleLowerCase()) => {
  let normalized = transform(s);
  if (String.prototype.normalize) {
    try {
      normalized = normalized.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    } catch (e) {
      // just ignore
    }
  }
  return normalized;
};

module.exports = normalizeString;
```
then map the items adding a string to the item with the normalized text:
```javascript
async normalizeTexts(items) {
  return items.map(item => {
    return Object.assign(item, {
      "n-t": normalizeString(item[this.itemText])
    });
  });
}
```
then create a function to filter them, that will be configure as the filter for v-autocomplete:
```javascript
filterItems(item, queryText, itemText) {
  if (queryText === null || queryText.length === 0) {
    return true;
  }
  return (
    itemText &&
    itemText.length > 0 &&
    item["n-t"].indexOf(normalizeString(queryText)) > -1
  );
}
```
```html
<v-autocomplete :filter="filterItems"></v-autocomplete>
```
When the popup menu is shown, v-select-list uses its own split algorithm using the original text, but accented chars doesn't match, so the component just select all text.

![image](https://user-images.githubusercontent.com/6311119/53408823-c9e0cb00-39bf-11e9-85a3-08189a5e43f0.png)

In this example **GUADALAJARA** AND **SALAMANCA** have its masked chars correct but **ÁLAVA** and **MÁLAGA** have its  masked chars wrong (just select full text), should be both **ÁLA**.

And cannot access the v-select-list via v-autocomplete or via its menu ref to change its behavior.

### Proposed solution
Provide a callback from the v-autocomplete to allow configure it on v-select-list.

**Comment by KaelWD** [comment] 2019-02-26 11:46
Duplicate of #3194

**Closed by KaelWD** 2019-02-26 11:46 UTC
