### ISSUE TITLE
[Bug report] Time picker in dialog not updating text field display properly.

### ISSUE THREAD

**Issue by snarlynarwhal** [vuetifyjs/vuetify#1887] opened 2017-09-26 00:34 UTC
Bug report
================
If you only change the hour for a time picker (in dialog), the text field display won't update. It doesn't work in the docs either, so I'll just link to [that codepen](https://codepen.io/anon/pen/JrEOOG).

### Steps to reproduce
* Focus on the time picker text field to open the dialog
* Change only the hour then click save.

### Versions

Vue: 3.10.10
Vuetify: 3.10.10
OS: Google Chrome 60.0.3112.113

### What is expected ?
I expect the text field to update as soon as I click save.

### What is actually happening ?
It does not update unless I also change the minutes or am/pm.

### Reproduction Link
This is the [exact example from the docs.](https://codepen.io/anon/pen/JrEOOG)

**Comment by johnleider** [comment] 2017-09-26 01:15
Duplicate of #1839 which is a duplicate of #1812 

🥇

**Closed by johnleider** 2017-09-26 01:15 UTC

**Comment by snarlynarwhal** [comment] 2017-09-26 02:09
Oops I think I only searched open issues on accident, sorry about that
