### ISSUE TITLE
[Bug Report] v-Dialog dark background doesn't show

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#5564] opened 2018-11-09 17:57 UTC
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
on wide screen, if you open dialog, there is dark background
then close dialog
then resize window to mobile (<600px), and open dialog, it should open full screen
then you resize window to wide again, and it should change from full screen to overlay popup style
notice the dark background is missing

### Expected Behavior
The dark background shows again when resizing to wide screen which changes the dialog from full screen to popup style.

### Actual Behavior
the dark background is missing

### Reproduction Link
<a href="https://codepen.io/anon/pen/RqRZLq" target="_blank">https://codepen.io/anon/pen/RqRZLq</a>

**Comment by KaelWD** [comment] 2018-11-10 01:02
Duplicate of #2201

**Closed by KaelWD** 2018-11-10 01:02 UTC
