### ISSUE TITLE
[Bug Report] Navigation drawer overlay touch doesn't close drawer on iOS Safari

### ISSUE THREAD

**Issue by richardtallent** [vuetifyjs/vuetify#2770] opened 2017-12-11 06:04 UTC
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.5.9
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.13.2

### Steps to reproduce
1. On iOS device, touch the hamburger icon to open the nav drawer.
2. Click on an area of the gray overlay outside the nav drawer.

### Expected Behavior
Clicking outside the drawer should hide the drawer.

### Actual Behavior
Tested on iPhone X, touching the gray overlay area has no impact.

### Reproduction Link
[https://codepen.io/richardtallent/pen/rpBMKL](https://codepen.io/richardtallent/pen/rpBMKL)

### Other comments
This works as expected on desktop browsers (tested in OS X Chrome and Safari, latest public versions). It also works properly on the Silk browser on my Amazon Fire tablet. Did not have an iPad or an older iPhone handy to test.

**Comment by KaelWD** [comment] 2017-12-11 06:17
Duplicate of #2544 

I don't know why that was fixed on dev instead of master, but it might be possible to back-port it to 0.17.

**Closed by KaelWD** 2017-12-11 06:17 UTC

**Comment by richardtallent** [comment] 2017-12-11 06:21
Ah! I saw "temporary" on that one and thought it might be unrelated (since the one I was using was "fixed"). Glad a fix is already in the pipeline!

**Comment by KaelWD** [comment] 2017-12-11 06:38
https://github.com/vuetifyjs/vuetify/releases/tag/v1.0.0-alpha.2

**Comment by KaelWD** [comment] 2017-12-26 18:00
This has gone out with 0.17.6 too https://github.com/vuetifyjs/vuetify/releases/tag/v0.17.6
