### ISSUE TITLE
Add option to specify parent container for menus (detachable components)

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#1177] opened 2017-07-29 21:56 UTC
Currently, the `menu__content` element is placed as a direct child of the `[data-app]` element. This imposes some issues e.g. when the activator element is located inside a div with `overflow: auto`. The menu will display in the correct position initially, but when scrolling the container the menu does not scroll with the content - it stays fixed because it is absolute position relative to the root container.

See: https://codepen.io/anon/pen/NvxpwN

I suggest to add a prop to `v-menu` that let you specify the parent container for the menu (as a querySelector argument). If it is not specified, it should use the default (`[data-app]`). Maybe it should be made part of the `detachable` mixin.

- What will it allow you to do that you can't do today?

It will make it possible to open menus inside a scrollable container and have the menu scroll with the content.

  - How will it make current work-arounds straightforward?

Not sure about any current work-arounds.

**Comment by nekosaur** [comment] 2017-07-30 14:00
Duplicate of #795

**Closed by nekosaur** 2017-07-30 14:00 UTC
Labels: duplicate
