### ISSUE TITLE
[Bug Report] with composition api the v-text-field does not update

### ISSUE THREAD

**Issue by udisun** [vuetifyjs/vuetify#13095] opened 2021-02-12 11:19 UTC
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.150
**OS:** Windows 10

### Steps to reproduce
try to click `up arrow` on your keyboard in each of the text fields.
on the native input you can't go above 185 as the `watch` function limits it and works.
on the `v-text-field` this does not work.

### Expected Behavior
updating v-text-field `v-model` value will correctly update the rendered value

### Actual Behavior
updating v-text-field `v-model` value does update the value as can be seen on the console.log but does not update the rendered value.

### Reproduction Link
<a href="https://codesandbox.io/s/vue-composition-text-field-issue-fhvkg?file=/pages/index.vue" target="_blank">https://codesandbox.io/s/vue-composition-text-field-issue-fhvkg?file=/pages/index.vue</a>

**Comment by KaelWD** [comment] 2021-02-12 12:15
Duplicate of #2931

https://codesandbox.io/s/vue-composition-text-field-issue-forked-sxd68?file=/pages/index.vue

**Closed by KaelWD** 2021-02-12 12:15 UTC
Labels: triage
