### ISSUE TITLE
[Bug Report] Transition to mini variant of navigation drawer goes wrong with icons.

### ISSUE THREAD

**Issue by Krahegwen** [vuetifyjs/vuetify#9498] opened 2019-10-29 07:29 UTC
### Environment
**Vuetify Version:** 2.1.7
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Windows 10

### Steps to reproduce
Click on the navigation drawer to maximize or minimize it.

### Expected Behavior
The drawer should maximize or minimize and the icons of the list should remain in the same position one the transition.

### Actual Behavior
When minimized the text of each entry goes hidden and the icons jump to the horizontal center.

### Reproduction Link
<a href="https://codepen.io/krahegwen/pen/VwwzEVd" target="_blank">https://codepen.io/krahegwen/pen/VwwzEVd</a>

**Comment by myleslee** [comment] 2019-10-31 00:29
I applied custom CSS to make icons stay put between the transition. But it would be nice to make it happen from the core.

**Comment by jacekkarczmarczyk** [comment] 2019-11-09 09:12
https://github.com/vuetifyjs/vuetify/issues/2606#issuecomment-482429042

**Comment by ricardovanlaarhoven** [comment] 2019-11-27 15:03
@myleslee What's your temporary solution?

**Comment by actualankitjain** [comment] 2019-12-26 10:41
@myleslee It would be great if you can share the custom CSS.

**Comment by johnleider** [comment] 2020-01-17 19:39
Duplicate of #2830, #8007

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-17 19:39 UTC
Labels: C: VNavigationDrawer
