### ISSUE TITLE
[Bug Report] v-overlay scrolling behavior inverted

### ISSUE THREAD

**Issue by tobiasfeil** [vuetifyjs/vuetify#10661] opened 2020-02-24 15:14 UTC
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.116
**OS:** Linux x86_64

### Steps to reproduce
scroll down

### Expected Behavior
while overlay is visible, the overlay isn't scrollable, making it impossible to see overflowing text thereof. Instead, the body behind it is scrollable

### Actual Behavior
The reverse - body scrolling is locked and only the overlay is scrollable

### Reproduction Link
<a href="https://codepen.io/tobiasfeil/pen/ExjZXVd" target="_blank">https://codepen.io/tobiasfeil/pen/ExjZXVd</a>

**Comment by johnleider** [comment] 2020-03-16 16:30
Duplicate of #10856

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-03-16 16:30 UTC
Labels: triage
