### ISSUE TITLE
[Feature Request] Required prop in v-text-field

### ISSUE THREAD

**Issue by Tharun-coder** [vuetifyjs/vuetify#15829] opened 2022-09-30 14:05 UTC
### Problem to solve
It makes ease to mark a v-text-field required without any extra efforts.

### Proposed solution
If required is true then red asterisk can be added to the text field and on submit error text can be shown like "This field is required".

**Comment by KaelWD** [comment] 2022-10-08 09:27
Duplicate of #11279

**Closed by KaelWD** 2022-10-08 09:27 UTC
Labels: S: triage
