### ISSUE TITLE
[Bug Report] Unable trigger menu independently of card with click event

### ISSUE THREAD

**Issue by mcfarljw** [vuetifyjs/vuetify#3888] opened 2018-04-20 01:02 UTC
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.117
**OS:** Mac OS 10.13.4

### Steps to reproduce
1. Click on the menu

### Expected Behavior
The menu can be clicked and opened independently of the card click event.

### Actual Behavior
The card event fires followed by the menu opening when clicking on the menu.

### Reproduction Link
[https://codepen.io/anon/pen/BxyXMO](https://codepen.io/anon/pen/BxyXMO)

### Other comments
My main goal is to be able to click on a card to navigate to more details, but also allow for some quick actions using a menu.

**Comment by KaelWD** [comment] 2018-04-20 06:50
Duplicate of #3333

**Closed by KaelWD** 2018-04-20 06:50 UTC
