### ISSUE TITLE
[Bug Report] Timeline with "dense" set does not show the content of the "opposite" slot

### ISSUE THREAD

**Issue by sw34** [vuetifyjs/vuetify#6955] opened 2019-04-09 19:10 UTC
### Versions and Environment
**Vuetify:** 1.5.10
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Windows 10

### Steps to reproduce
I took your opposite slot example, added "dense" to the timeline and the opposite slot does not show.

### Expected Behavior
My intention was to have a timeline that has all the items to one side (preferably right as dense does) and keep the opposite slot.

If I do this not using dense, the left side is a huge waste of space as it centers the timeline, even though the content on the left is small compared to the right.

### Actual Behavior
opposite slot not shown

### Reproduction Link
<a href="https://codepen.io/anon/pen/gygzvY?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/gygzvY?&editable=true&editors=101</a>

### Other comments
if this was the intended functionality, is there a way to shift the timeline to the left so the content of the screen is on the left?

**Comment by blalan05** [comment] 2019-04-10 02:10
This is working as currently intended. 
With some custom css you could make it work: <https://codepen.io/anon/pen/NmdJJZ>

**Comment by KaelWD** [comment] 2019-04-10 05:33
Duplicate of #6594

**Closed by KaelWD** 2019-04-10 05:33 UTC
Labels: C: VTimeline, T: enhancement, pending review
