### ISSUE TITLE
[Bug Report] v-button inside v-dialog isn't block

### ISSUE THREAD

**Issue by km2442** [vuetifyjs/vuetify#6295] opened 2019-01-30 12:24 UTC
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Just open Reprodution link, v-button inside v-dialog isn't block

### Expected Behavior
V-button inside v-dialog should be block, like button outside v-dialog

### Actual Behavior
V-button inside v-dialog isn't block

### Reproduction Link
<a href="https://codepen.io/km2442/pen/KJNyJX" target="_blank">https://codepen.io/km2442/pen/KJNyJX</a>

**Comment by jacekkarczmarczyk** [comment] 2019-01-30 12:32
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5596

https://codepen.io/anon/pen/XONVZw

**Closed by jacekkarczmarczyk** 2019-01-30 12:32 UTC
