### ISSUE TITLE
[Feature Request] Dropdown Time Picker needed

### ISSUE THREAD

**Issue by max-fletcher** [vuetifyjs/vuetify#13985] opened 2021-07-25 07:05 UTC
### Problem to solve
I see that the current version of Vuetify has no dropdown time picker. It has a clock UI that some of my clients find very counterintuitive to use.

### Proposed solution
If possible, please add a dropdown time picker like the time picker that the current version of HTML has. And perhaps for the long run, you may even try developing a date-time picker, that has both date and time. The current version of HTML has one but it doesn't work on firefox. It will be up to us devs to figure out how to use the date-time string anyway.

**Comment by KaelWD** [comment] 2021-07-25 07:20
Duplicate of #6957

> try developing a date-time picker

#459

**Closed by KaelWD** 2021-07-25 07:20 UTC
Labels: S: triage
