### ISSUE TITLE
[Bug Report] The right border of the navigation scrolls, if the menu is longer than the content

### ISSUE THREAD

**Issue by faebeee** [vuetifyjs/vuetify#7096] opened 2019-04-29 13:23 UTC
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.6
**Browsers:** Chrome 74.0.3729.108
**OS:** Mac OS 10.14.4

### Steps to reproduce
https://vuetifyjs.com/en/components/navigation-drawers#navigation-drawer

### Expected Behavior
Right border is permanently visible

### Actual Behavior
Right border scrolls with content and disappears

### Reproduction Link
<a href="https://codesandbox.io/s/vue" target="_blank">https://codesandbox.io/s/vue</a>

### Other comments
Can also be reproduced here https://vuetifyjs.com/en/components/navigation-drawers#navigation-drawer

**Comment by jacekkarczmarczyk** [comment] 2019-04-30 03:06
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3498

**Closed by jacekkarczmarczyk** 2019-04-30 03:06 UTC
Labels: triage
