### ISSUE TITLE
[Bug Report] VCalendarCategory : Bad columns construction

### ISSUE THREAD

**Issue by devoluti0n** [vuetifyjs/vuetify#12970] opened 2021-01-15 16:12 UTC
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.141
**OS:** Windows 10

### Steps to reproduce
- Create a VCalendar with category mode.
- Set more than 2 days to display
- Set a fixed number of categories, like 2

### Expected Behavior
- We should have 1 day body for each day.
- We should also have one column for each category in that day
- And then each events for that category

Bonus: We should be able to filter days defined in weekdays props

### Actual Behavior
We can see that we have 2 columns instead of five. And events are blindly added to that

### Reproduction Link
<a href="https://codepen.io/devoluti0n/pen/wvzRWgq" target="_blank">https://codepen.io/devoluti0n/pen/wvzRWgq</a>

### Other comments
- In VCalendarCategory.js line 69, days should be based on days length, not categories length.
- From that, we should have a loop in genDayBody for each parsed category, and not only one, so that events are in their specific categories.
- And from that, events should be specific to their categories (I didn't search for the duplication reason yet)

**Comment by MajesticPotatoe** [comment] 2021-01-15 16:21
related/duplicate of #12967

**Comment by KaelWD** [comment] 2021-02-23 08:37
Duplicate of #12967

**Closed by KaelWD** 2021-02-23 08:37 UTC
Labels: C: VCalendar, T: bug, T: regression
