### ISSUE TITLE
[Bug Report] Returns object instead of Id in v-combobox

### ISSUE THREAD

**Issue by anoop-ananthan** [vuetifyjs/vuetify#7311] opened 2019-05-28 08:14 UTC
### Versions and Environment
**Vuetify:** 2.0.0-alpha.20
**Vue:** 2.6.10
**Browsers:** Firefox 67.0
**OS:** Ubuntu undefined

##### Issue 1

1. Place a `v-combobox` control 
1. Assign a list  to `:items` ,  set `item-text` & `item-value`, `v-model`  properties
1. Run the application
1. Select an item from the control

##### Issue 2
1. Add another property `:return-object="false"` to change this behavior to returning Id instead

##### Issue 1
1. `v-model` will be updated with `Id`

##### Issue 2
Text of the control shows the field assigned as `item-text`

##### Issue 1
`v-model` will be updated with `Object`

##### Issue 2
1. Text of the control is now Id

### Reproduction Link
<a href="https://codepen.io/paanoop/pen/JqBGYZ" target="_blank">https://codepen.io/paanoop/pen/JqBGYZ</a>

**Comment by KaelWD** [comment] 2019-05-28 08:30
Duplicate of #5479

**Closed by KaelWD** 2019-05-28 08:30 UTC
Labels: triage
