### ISSUE TITLE
[Bug Report][3.3.0] VImg don't respect `aspect-ratio` prop

### ISSUE THREAD

**Issue by smortexa** [vuetifyjs/vuetify#17415] opened 2023-05-20 20:18 UTC
### Environment
**Vuetify Version:** 3.3.0
**Last working version:** 3.2.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.5616.197
**OS:** Mac OSX

### Steps to reproduce
- Use an image with `4:3` intrinsic aspect ratio with `VImg`
- Use `:aspect-ratio="16 / 9"` prop

### Expected Behavior
The image aspect ratio must respect `aspect-ratio` prop.

### Actual Behavior
The intrinsic aspect ratio will be applied.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUcluwjAQ/ZXIZ2wX0kWNUkQ/oWfCwTgGTL3JY4IqxL93nKhlO0BO8Ru/bTw/kM8QWLdTpCJ1UjYYkdS0cUVRd1Tbdf4bPmkEwEdDlmu63+ikGnKaFdJ3Kp7OlYCgZKJRJO2RM34tePF+zoAoEd+kFKDiXLaO7YUxQQQVQaxE1Ex6y1/GfFLy8msiV4ltw/qkMK15nw+j1vw/NxkRo903sC14h40O+XpDJEBDqmI+kC9tt9Aqo7vInErcBctxF0mvfmYlK9kTbzWkP4gasQTWi2WlReOOaKht8DFRK8KV6zDonXskY6iUz3cizPAajzuXtFW09RazTNjz2xDmDGcKLF1GvwcVUaUhozOfnPgBr3t10eJGmqMfvjeNyrUq4sM/WOmKdlHranZTLdsf88aPIzLwcPd9aLL4BYcR5+w=)

### Other comments
Maybe https://github.com/vuetifyjs/vuetify/pull/17090

**Comment by jscottsf** [comment] 2023-05-20 22:07
Having the same issue. Thx for logging this.

**Comment by KaelWD** [comment] 2023-05-21 05:53
Duplicate of #17413

**Closed by KaelWD** 2023-05-21 05:53 UTC
Labels: S: triage
