### ISSUE TITLE
[Bug Report] Timepicker Minutes selection closes Dialog if minutes is outside of dialog

### ISSUE THREAD

**Issue by blalan** [vuetifyjs/vuetify#5599] opened 2018-11-13 13:45 UTC
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 7

### Steps to reproduce
Open Time Picker, Select any hour, Select 30 minutes.

### Expected Behavior
Time to be saved, and timepicker menu to be closed, but the dialog remain open.

### Actual Behavior
Both the time picker and the dialog close together.

### Reproduction Link
<a href="https://codepen.io/anon/pen/zMNdJr" target="_blank">https://codepen.io/anon/pen/zMNdJr</a>

### Other comments
Similar issue to #5200, but worse. In that issue, the click happens outside of timepicker and dialog. Here click happens inside of timepicker but outside of dialog.

**Comment by cb109** [comment] 2018-11-13 13:49
It's actually the same thing. Read the text above the second gif on #5200

**Comment by blalan** [comment] 2018-11-13 13:50
Oh, read that issues, but missed that line. Thanks.

**Comment by jacekkarczmarczyk** [comment] 2018-11-13 13:53
Duplicate of #5200

**Closed by jacekkarczmarczyk** 2018-11-13 13:53 UTC
Labels: pending review
