### ISSUE TITLE
[Bug Report][3.2.1] Compact autocomplete component height shrinks when empty

### ISSUE THREAD

**Issue by joshas** [vuetifyjs/vuetify#17240] opened 2023-04-27 19:18 UTC
### Environment
**Vuetify Version:** 3.2.1
**Vue Version:** 3.2.47
**Browsers:** Firefox 112.0
**OS:** Linux x86_64

### Steps to reproduce
Click on "Clear" icon in first autocomplete.

### Expected Behavior
Both autocomplete components height remain the same.

### Actual Behavior
Both autocomplete components height shrinks down, more noticeable on underlined variant. Start typing text, it will be partially covered by dropdown list.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrVU9tu2zAM/RVBL2mB2MIu2AAjDTpsv7CnOg+KRWPaZMnQxVtb+N9HSU5rOyiaPvbBkMlDkYc81N0j/db35RCAVnTnoesV97CvNSG7oWi4Fek/W0Z7LjVY0qogT0CCrPn7ZE6xiuDnbmr6paYzLKE8eNMYrAUe5hAhQ9EZAQqvDVwFcDVd4pVEjjFrOteoAO2kv0c4ZueNXwcofkzJv2eYFOQHtDyos8BGAbf8qBb09ju25D7vGSFs+J1O4acWYBVqKy4aBDLkVnLtMUl44epbhhXt5xXK6LRreRWjJ+/ijs2WFE3XWNn7FAX/emM9tp8UJY85m+CeV+TqmtzsydXkIyQNriJ3m9aYzZZsjtzGo5UPD8kMeB62p+isQoV4jF54K6KDUpNvvE4/Y6Q5EaNbisP548rfzmh8Y4kBKuNQNqyf79X0l/e9qxhrhMZI1F4OttTgme47hq/Ty/b+9lP5sfzAhHT+5CpQSlemZDHTodYjFpRdHETR8X5VNQOp8jQJ3LAA0X6Fwi2GMRu0lx0UwnSJy+evmczMX4LriiNq6cBilppOk0l1IuMLar3WLpY4S82w3gC2sBDXEeylLa2uLdpaYWetTVKPdNzSfA9nn0jTw3+eoKJZ)

### Other comments
"default" and "comfortable" density variants works as expected.

**Comment by yuwu9145** [comment] 2023-04-27 22:09
#16901

**Comment by yuwu9145** [comment] 2023-04-28 01:11
Tested it can be fixed by #17175

**Comment by KaelWD** [comment] 2023-04-28 08:05
Duplicate of #16901

**Closed by KaelWD** 2023-04-28 08:05 UTC
Labels: S: triage
