### ISSUE TITLE
[Bug Report][3.3.4] Watching error state of text field doesnt work

### ISSUE THREAD

**Issue by rohrii** [vuetifyjs/vuetify#17646] opened 2023-06-18 20:02 UTC
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows

### Steps to reproduce
1. Place an input field in your app and add validation
2. Add a template ref
3. Add a watcher which observes the error property on the field
4. log the current error state to console

### Expected Behavior
The error state is correctly tracked by the watcher (Runs when input changes error state)

### Actual Behavior
The watcher is only ran once when the component is rendered.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUsGOmzAQ/ZWRLyRSsCttT1GSbr8j5MDCkLg1tmsb0iqbf+/YBgVlD12pJ5j3ZubNe3C8se/W8nFAtmW7gL1VdcBDpQF2Y1lbm15T0ddST1WqA/4OZSdRtTMI4LDbV0xqO4SKPWAaNi0qonp/XhJbNyj0hB9hhP0BRq5Qn8MFDvAF3t+hcPhrkA7bAk6POTEfJRZXxSLfuxMLH1T6xkkbwGMYsh3ZW+MC3OK5G7jWobnAHTpneigoiSJOATRG+wB0MOxj46oo1ksimZwoPShFJORdq3zdah0dpTY+1mrAbxydM26TaYIif5tNyQ5WhK0fSFYyCrky51WRBS+1h1pD2hQPyo13QOXxH6PSgzbXKCzbxWh+SQ8CdyLHRUGxDctJUciW//BG0z+SJOgTJ8JXbDuLVoyii3XFLiFYvxWiaTWN0YeXo+Mag9C2F6/UJtygg+yxbE3/+sJf+FfRSh+WMEffl2/OXD06WlKxKbYkE2T35xNSU+dSYYJKVb/5KPFhtSC9EV3pULfo0H3W0dPYUvOJ+uAsqlP8d8pbSf3TP0Xd+BTzcT7yvyynZXHTKQreNyw1knJ+nv4CQhFOtw==)

**Comment by KaelWD** [comment] 2023-06-19 02:21
Duplicate of #17502

**Closed by KaelWD** 2023-06-19 02:21 UTC
Labels: S: triage
