### ISSUE TITLE
[Bug Report] Fab close icon misaligned with speed-dial

### ISSUE THREAD

**Issue by cairinmichie** [vuetifyjs/vuetify#3221] opened 2018-02-08 12:20 UTC
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.140
**OS:** Mac OS 10.13.3

### Steps to reproduce
Use a Fab with two icons and speed dial. the close icon becomes misaligned.

### Expected Behavior
The close icon should not be misaligned.

### Actual Behavior
The icon is offset to the bottom right.

### Reproduction Link
[https://codepen.io/anon/pen/WMRvJM?&editors=111](https://codepen.io/anon/pen/WMRvJM?&editors=111)

**Comment by KaelWD** [comment] 2018-02-08 12:23
Duplicate of #3207

**Closed by KaelWD** 2018-02-08 12:23 UTC
