### ISSUE TITLE
[Bug Report] v-model of v-text-field is not bind values if using IME

### ISSUE THREAD

**Issue by kentokento** [vuetifyjs/vuetify#11212] opened 2020-04-24 01:48 UTC
### Environment
**Vuetify Version:** 2.2.23
**Last working version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.113
**OS:** Mac OS 10.14.6

### Steps to reproduce
Watch the v-model value of v-text-field.
The following modifications are affected.
https://github.com/vuetifyjs/vuetify/pull/11134

### Expected Behavior
Just like when typed alphabets

### Actual Behavior
v-model value is not reflected

### Reproduction Link
<a href="https://codepen.io/kentokento/pen/mdeRLRv" target="_blank">https://codepen.io/kentokento/pen/mdeRLRv</a>

**Comment by johnleider** [comment] 2020-04-24 18:20
Duplicate of #11190

**Closed by johnleider** 2020-04-24 18:20 UTC
Labels: triage
