### ISSUE TITLE
[Bug Report] Want to fill v-content to 100%, but default component size is used. The container will not automaticall

### ISSUE THREAD

**Issue by applett** [vuetifyjs/vuetify#10878] opened 2020-03-18 17:19 UTC
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Firefox 74.0
**OS:** Windows 7

### Steps to reproduce
Hi, please see the codesandbox https://codesandbox.io/s/flamboyant-swirles-zgd1m . It requires vuetify and zingcharts installed. I am trying to get the chart to fill the maximum it can (ie the full height of the container) but it keeps coming out at 480px (the default for the chart). I have tried other chart libs and all the same. 

This is the section with the problem, in App.vue:

    <v-content >
      <v-container fluid fill-height >
       <v-flex text-xs-center fill-height >
    
          
          

          <chart/>

        </v-flex>
      </v-container>
    </v-content>

### Expected Behavior
Charts (and any other components) would like to fill to 100% of the container. However there is no specified height on the container. Does the container not calculate a size to pass down to its ? elements ?

### Actual Behavior
the components use the default size

### Reproduction Link
<a href="https://codesandbox.io/s/flamboyant-swirles-zgd1m" target="_blank">https://codesandbox.io/s/flamboyant-swirles-zgd1m</a>

### Other comments
Hi, appreciate this might not be a bug, and happy to re-grade to feature request, or be enlightened to my own level  of incompetence.

Many thanks

**Comment by Dev-Oli** [comment] 2020-04-02 14:56
This seems to be a known but ignored bug (as the ticket is already closed), see: https://github.com/vuetifyjs/vuetify/issues/8608
Maybe nesting another v-container -which feels a bit "hacky"- works for you too.

**Comment by johnleider** [comment] 2020-12-16 17:23
Duplicate of #8608

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-16 17:23 UTC
Labels: C: VGrid, T: bug
