### ISSUE TITLE
[Bug Report] v-carousel component in v-tab-item , when switch back then images was gone!

### ISSUE THREAD

**Issue by AnodoubleA** [vuetifyjs/vuetify#7769] opened 2019-07-07 11:32 UTC
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
1. Put v-carousel in v-tab-item
2. Switch to other tab and wait a moment(Like an image switch time).
3. Then switch back to v-tab who contain v-carousel .
4. v-carousel images will not show!

### Expected Behavior
Image show

### Actual Behavior
Image not show , because the <div> tag with 'v-window__container' class  height become to zero!

### Reproduction Link
<a href="https://codepen.io/this is wrong link" target="_blank">https://codepen.io/this is wrong link</a>

**Comment by jacekkarczmarczyk** [comment] 2019-07-07 11:41
Looks like duplicate of https://github.com/vuetifyjs/vuetify/issues/7686

**Closed by jacekkarczmarczyk** 2019-07-07 11:41 UTC
Labels: S: needs reproduction, triage
