### ISSUE TITLE
[Bug Report]  app-bar outlined option does not effect on elevation and does not add thin border

### ISSUE THREAD

**Issue by dani1373** [vuetifyjs/vuetify#11886] opened 2020-07-18 21:07 UTC
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.15.4

### Steps to reproduce
Use outlined prop in app-bar 

### Expected Behavior
Regarding documentaion:
Removes elevation (box-shadow) and adds a thin border.

### Actual Behavior
Nothing

### Reproduction Link
<a href="https://codepen.io/dani1373/pen/MWKzQZr" target="_blank">https://codepen.io/dani1373/pen/MWKzQZr</a>

### Other comments
You can put your app-bar in a sheet and use outlined in your v-sheet and then make your app-bar flat to have the functionality expected.

**Comment by VictorHVS** [comment] 2020-11-10 13:49
any news about that?

**Comment by NabeelAhmed314** [comment] 2020-12-09 10:06
I have tried recreating this issue. According to the latest version of documentation the outlined prop does nothing and i have also reviewed the code for VAppBar and their is no use for outlined prop. I think this issue should be marked as feature request and not as bug report. Let me know if you have any more leads for this issue.

This is the link to documentation of props for VAppBar:
https://vuetifyjs.com/en/api/v-app-bar/#props

**Comment by baermathias** [comment] 2021-07-30 15:29
A temporary solution with some inline styling:

```html
<v-app-bar 
  app 
  flat
  style="border-bottom: 1px solid #d2d2d2 !important;"
>
```

**Comment by johnleider** [comment] 2021-11-30 16:25
After reviewing this issue again, I do not think that this is a bug.  The only components that support a colored outline are `v-alert` and `v-btn`. `v-app-bar` ultimately extends `v-sheet` and has access to the property, but does not have a difference in behavior.

For that reason and because there is a workaround, I'm going to mark this as working as intended.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-11-30 16:25 UTC
Labels: T: bug, C: VAppBar
