### ISSUE TITLE
[Bug Report] Component in v-menu not render on mounted

### ISSUE THREAD

**Issue by Feofilakt** [vuetifyjs/vuetify#13139] opened 2021-02-20 02:57 UTC
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 3.0.5
**Browsers:** Chrome 87.0.4280.141
**OS:** Windows 8.1

### Steps to reproduce
Press button
Open console

### Expected Behavior
two numbers

### Actual Behavior
zero and number

### Reproduction Link
<a href="https://codepen.io/Feofilakt/pen/PobKmaX?editors=1010" target="_blank">https://codepen.io/Feofilakt/pen/PobKmaX?editors=1010</a>

### Other comments
Based on https://vuetifyjs.com/en/components/menus/#popover-menu

**Comment by KaelWD** [comment] 2021-02-22 06:22
It takes two frames to determine the content height: https://codepen.io/kaelwd/pen/WNoEBzB?editors=1010

I'm going to mark this as a duplicate of #4454 because they have the same cause.

**Closed by KaelWD** 2021-02-22 06:22 UTC
Labels: triage
