### ISSUE TITLE
[Feature Request] digital time picker

### ISSUE THREAD

**Issue by lfgtavora** [vuetifyjs/vuetify#14097] opened 2021-08-29 04:58 UTC
### Problem to solve
Current time picker is analog and confusing for some users

### Proposed solution
Nowadays we have new version of time picker in Material design, simple and easier: https://material.io/components/time-pickers#behavior

**Comment by MajesticPotatoe** [comment] 2021-08-29 05:13
duplicate of #6957

**Closed by MajesticPotatoe** 2021-08-29 05:13 UTC
Labels: S: triage
