### ISSUE TITLE
[Bug Report] v-select is clearable when set it readonly

### ISSUE THREAD

**Issue by tantee** [vuetifyjs/vuetify#9723] opened 2019-11-19 05:50 UTC
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
1. Add v-select, set its choice and value
2. set :readonly=true
3. set :clearable=true

### Expected Behavior
Clear button should be disable when it's set to be readonly

### Actual Behavior
Clear button is working, data is clear whether it's set to be readonly

### Reproduction Link
<a href="https://codepen.io/tantee/pen/WNNPQjm" target="_blank">https://codepen.io/tantee/pen/WNNPQjm</a>

**Comment by jacekkarczmarczyk** [comment] 2019-11-19 05:59
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7111

**Closed by jacekkarczmarczyk** 2019-11-19 05:59 UTC
Labels: triage
