### ISSUE TITLE
[Bug Report][3.3.19] v-select no longer respects global hideDetails setting

### ISSUE THREAD

**Issue by johannesss** [vuetifyjs/vuetify#18350] opened 2023-09-27 12:58 UTC
### Environment
**Vuetify Version:** 3.3.19
**Last working version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Add global `hideDetails` setting

### Expected Behavior
details should only be shown if there are any

### Actual Behavior
details are shown regardless of setting

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUc1OwzAMfhWTS4ZUWqFxYeqQkDjwAAgO6w6lc9egNIkSd4Cmvjtu0k1jl/jv82f7y+Yogm+Kw4Ck2t/8K4iVUL2znuAIjcea8D3VYITW2x7kjJWVqQz+RGhjTSCYC7D+37g4VgaAOuxxBdEH2GFbD5reUlJqte9IZqlWFJMdYzTjwrlxr+1nrc8hQKd2+IJUK80gWQ9kTzyJYXrH28qILB767FzOe/KVJWHvNK/5NMHKw13tXHRjwBcxp0E/p2IyoMaGYKW4NawrsZHWoMxA0jdPZdN5RLmtBBQnpuKaasqkSWVxsQGHofHKEQSkIS1y/geP7aX6UXmYRe/DngVnxEK+otYWPqzXuxvJJ5dFomQyMWZimS/zB5ZhsvePYvsHTpylFA==)

**Comment by KaelWD** [comment] 2023-09-30 10:46
Duplicate of #18342

**Closed by KaelWD** 2023-09-30 10:46 UTC
Labels: S: triage
