### ISSUE TITLE
[Feature Request] Multi column sorting on datatables

### ISSUE THREAD

**Issue by LanFeusT23** [vuetifyjs/vuetify#3659] opened 2018-03-23 17:35 UTC
### Problem to solve
Multi sorting will allow to keep certains column permanently sorted in a certain way.

For example if I were to default sort my table by name, but then wanted to sort by age, all users of the same age should be sorted by name as well.

### Proposed solution
Add a "sort-by" array option

**Comment by jacekkarczmarczyk** [comment] 2018-03-24 14:03
Duplicate of #2659

**Comment by jacekkarczmarczyk** [comment] 2018-03-24 14:03
exactly 1000 issues between dups ;)

**Closed by jacekkarczmarczyk** 2018-03-24 14:03 UTC
