### ISSUE TITLE
[Bug Report][3.1.3] rtl issue with navigation-drawer

### ISSUE THREAD

**Issue by mohammad-zr** [vuetifyjs/vuetify#16590] opened 2023-02-04 15:46 UTC
### Environment
**Vuetify Version:** 3.1.3
**Vue Version:** 3.2.47
**Browsers:** Edge 109.0.1518.70
**OS:** Windows 10

### Steps to reproduce
drawer opens but no overlay shown and also not able to close it again (by clicking outside)

### Expected Behavior
show overlay on drawer opening and close drawer by clicking on overlay

### Actual Behavior
no overlay showing

### Reproduction Link
[https://codesandbox.io/s/sleepy-glitter-i44265?file=/src/main.js](https://codesandbox.io/s/sleepy-glitter-i44265?file=/src/main.js)

**Comment by KaelWD** [comment] 2023-02-04 18:16
Duplicate of #16261

**Closed by KaelWD** 2023-02-04 18:16 UTC
Labels: S: triage
