### ISSUE TITLE
[Bug Report] Closing a dialog in fullscreen dialog shows scrollbar

### ISSUE THREAD

**Issue by janfokke** [vuetifyjs/vuetify#11445] opened 2020-05-19 16:18 UTC
### Environment
**Vuetify Version:** 2.2.28
**Vue Version:** 2.6.11
**Browsers:** Firefox 76.0
**OS:** Windows 10

### Steps to reproduce
<b>UI Structure</b>    View -> Dialog1 -> Dialog2
      

If you open fullscreen Dialog1 it hides the scrollbar of the view.
If you then open Dialog2 and close it, it activates the scrollbar of the view while Dialog1 is still showing.

### Expected Behavior
The scrollbar should remain hidden

### Actual Behavior
The scrollbar shows while the fullscreen dialog is still up

### Reproduction Link
<a href="https://codepen.io/janfokke/full/pojqJZM" target="_blank">https://codepen.io/janfokke/full/pojqJZM</a>

**Comment by YipingRuan** [comment] 2020-05-23 08:14
When Dialog 1 open, class added to html:
<html lang="en" class="overflow-y-hidden">

When Dialog 2 open, the class is removed by "removeOverlay" call.

**Comment by KaelWD** [comment] 2020-05-23 11:39
Duplicate of #5356

**Closed by KaelWD** 2020-05-23 11:39 UTC
Labels: C: VDialog, T: bug
