### ISSUE TITLE
[Bug Report] v-dialog in loop get "Maximum call stack size exceeded Vuetify" error

### ISSUE THREAD

**Issue by yznetaX** [vuetifyjs/vuetify#11479] opened 2020-05-25 14:42 UTC
### Environment
**Vuetify Version:** 2.2.29
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Windows 10

### Steps to reproduce
1- set v-model on dialog and this dialog is inside loop of data coming from server
2- get dialog = false in data
3- on close click this dialog = false

### Expected Behavior
the dialog will closed with out error of Maximum call stack size exceeded

### Actual Behavior
when i click on this dialog 3 time i get error and all the app stop and wreck

### Reproduction Link
<a href="https://codepen.io/yazanAlhaffar/pen/gOayPLE?__cf_chl_jschl_tk__=3e92d62893d408b2a1a8a214a7bbfc020affc5e7-1590417495-0-AQUac2_Ndjkl3frFW_dulCXk8346YQQu6Afd9hMqY3tfeZGO3ghFjTHGk1HByQ-q2A4gdnjof0Foo56uMG489IEH4TpUiVztaiKEdwk3GuLGqeTMI6KxRno8Ba_hesWsIIIkhOYaDNm-zuVk3lbYCJ-sMUhGDHtX4KNc7nUu-Ga3jNvqh8qntGBgGFJDliSGp_MV0aC3dnXbRLf8B8L3xkZUjQqghQAcFUxPw2kFh8nQc_AehZK7y2wyuIPk7D4FkNTC4VcAaVAnrUcvSLU8MIrj3-2mYKj4VrNfWccZm0fcaCpFXEgPfHpqEVVh1bf48Widh4sJ2F6CfwlJ-z0PA8qNUoM4ysmgYZ0PwZgpyuPc6UWsp3L-vHKL85iy84b-pQ" target="_blank">https://codepen.io/yazanAlhaffar/pen/gOayPLE?__cf_chl_jschl_tk__=3e92d62893d408b2a1a8a214a7bbfc020affc5e7-1590417495-0-AQUac2_Ndjkl3frFW_dulCXk8346YQQu6Afd9hMqY3tfeZGO3ghFjTHGk1HByQ-q2A4gdnjof0Foo56uMG489IEH4TpUiVztaiKEdwk3GuLGqeTMI6KxRno8Ba_hesWsIIIkhOYaDNm-zuVk3lbYCJ-sMUhGDHtX4KNc7nUu-Ga3jNvqh8qntGBgGFJDliSGp_MV0aC3dnXbRLf8B8L3xkZUjQqghQAcFUxPw2kFh8nQc_AehZK7y2wyuIPk7D4FkNTC4VcAaVAnrUcvSLU8MIrj3-2mYKj4VrNfWccZm0fcaCpFXEgPfHpqEVVh1bf48Widh4sJ2F6CfwlJ-z0PA8qNUoM4ysmgYZ0PwZgpyuPc6UWsp3L-vHKL85iy84b-pQ</a>

**Comment by KaelWD** [comment] 2020-05-25 14:45
Duplicate of #11009

This was already answered on discord: 
![image](https://user-images.githubusercontent.com/16421948/82823059-33fd5e00-9eea-11ea-8278-15d8b2dc4aa2.png)

**Closed by KaelWD** 2020-05-25 14:45 UTC
Labels: triage

**Comment by yznetaX** [comment] 2020-05-25 14:47
no that not the answer
and i get nothing for my issue

**Comment by francisjr1997** [comment] 2020-12-09 08:56
use <v-dialog :retain-focus="false">

**Comment by francisjr1997** [comment] 2020-12-09 09:00
[(https://codepen.io/francisjr97/pen/XWjjNeV)]

**Comment by francisjr1997** [comment] 2020-12-09 09:00
[(https://codepen.io/francisjr97/pen/XWjjNeV)](url)
