### ISSUE TITLE
[Feature Request] Prevent routing in mobile when tab the native back button if dialog in open state

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#3085] opened 2018-01-23 14:34 UTC
@KaelWD 
### New Functionality
Android mobile hybrid app:: We have 2 pages and imagine and in 2nd page with v-select options, dialogs, date-picker and else

1.  Click the Select option in 2nd page, once opened select option - tab the mobile native back button(Android)
2. See the screen. Select option got closed(Expected behaviour), and page navigated to previous page(Un-expected behaviour)

How can we prevent page routing  for click native back button, when select option opened

### Improvements
beforeRouteLeave in event components and checking whether select, dialogs, date-picker in open state

### Bugs or Edge Cases it Helps Avoid
Vuetify may prevent routing if any modal opened like date-picker, dialogs, select and so

**Comment by ksankumar** [comment] 2018-01-26 14:59
For temp fix

beforeRouteLeave: function (to, from, next) {
                var active_window = this.$refs, isNotActive = true;
                for (var ref in active_window) {
                    if (active_window[ref].isActive) {
                        active_window[ref].isActive = false;
                        isNotActive = false;
                        next(false);
                    }
                }
                isNotActive && next();
            }

**Comment by KaelWD** [comment] 2018-02-11 15:18
Original conversation:
![image](https://user-images.githubusercontent.com/16421948/36074923-fd5b1742-0f9a-11e8-95c3-b07af1adb665.png)

**Comment by ksankumar** [comment] 2018-02-13 14:55
@KaelWD @johnleider 

Is there any plan to fix in next release?

**Comment by KaelWD** [comment] 2018-05-16 15:03
Duplicate of #1793

**Closed by KaelWD** 2018-05-16 15:03 UTC
Labels: T: feature, help wanted
