### ISSUE TITLE
[Bug Report] v-bottom-sheet : persistent won't work with hide-overlay is set to true

### ISSUE THREAD

**Issue by whbjzzwjxq** [vuetifyjs/vuetify#9012] opened 2019-09-18 19:19 UTC
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
set both "persistent" and "hide-overlay" to true in v-bottom-sheet
then click outside of bottom-sheet

### Expected Behavior
the sheet do NOT close

### Actual Behavior
the sheet close

### Reproduction Link
<a href="https://codepen.io/whbjzzwjxq/pen/YzKJvKo?editors=1010" target="_blank">https://codepen.io/whbjzzwjxq/pen/YzKJvKo?editors=1010</a>

**Comment by MajesticPotatoe** [comment] 2019-09-18 19:23
duplicate of #8880 / #8697

**Closed by MajesticPotatoe** 2019-09-18 19:23 UTC
Labels: triage
