### ISSUE TITLE
[Bug Report] Works poorly with cef chromium

### ISSUE THREAD

**Issue by Ainur777** [vuetifyjs/vuetify#13112] opened 2021-02-15 13:34 UTC
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 88.0.4324.150, Other
**OS:** Linux x86_64, Windows

### Steps to reproduce
You need to click on the menu, button and v-overflow-btn several times. Doesn't always work the first time.
Vuetify works with chrome, firefox but doesn't work with cef chromium
Short video:
https://www.loom.com/share/331f43f39795478887de5459c64a2e08
https://loom.com/share/083922a724f04f6c88d68f907f1bc2b2

### Expected Behavior
Displays a menu, any action on the first press.

### Actual Behavior
Need to press several times

### Reproduction Link
<a href="https://codesandbox.io/s/vue-template-z08d0?from-embed=&file=/src/App.vue" target="_blank">https://codesandbox.io/s/vue-template-z08d0?from-embed=&file=/src/App.vue</a>

### Other comments
I have been studying this problem for a long time. She always stays ...

**Comment by Ainur777** [comment] 2021-02-15 13:45
https://www.loom.com/share/331f43f39795478887de5459c64a2e08

**Comment by KaelWD** [comment] 2021-05-16 03:25
Duplicate of #7800

**Closed by KaelWD** 2021-05-16 03:25 UTC
Labels: triage
