### ISSUE TITLE
[Documentation] Filter break js

### ISSUE THREAD

**Issue by Dev1lDragon** [vuetifyjs/vuetify#14137] opened 2021-09-07 14:17 UTC
### Environment

**Browsers:** Chrome 93.0.4577.63
**OS:** Windows 10

### Steps to reproduce
start to type 3/4 characters in filter.

### Expected Behavior
Filtering

### Actual Behavior
`vue.runtime.common.prod.js:6 TypeError: Cannot read properties of undefined (reading 'key')`
![image](https://user-images.githubusercontent.com/9211475/132360148-b3901fb4-8188-4911-ac60-eb525504118a.png)

### Reproduction Link
<a href="https://vuetifyjs.com/en/" target="_blank">https://vuetifyjs.com/en/</a>

**Comment by KaelWD** [comment] 2021-09-07 14:51
Duplicate of #14133

**Closed by KaelWD** 2021-09-07 14:51 UTC
Labels: S: triage
