### ISSUE TITLE
[Bug Report] Autocomplete search and select does not persist the selection 

### ISSUE THREAD

**Issue by kanteankit** [vuetifyjs/vuetify#6293] opened 2019-01-30 11:44 UTC
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Linux x86_64

### Steps to reproduce
I have modified the example `Searching an API` given in the docs, so that whatever keyword user types, it is sent as a query param in the API url. Here are the repro steps:

1) In the input box, search for the keyword `cat` and select some items. They will be visible as selected chips in the input.
2) Click outside the input box to close the dropdown.
3) Now search for `dog` in the input box. You'll see that your previous selections go away from the input. The model still has the selected items,but, they do not show up in the input.

My use case is to call an API when user starts typing in the input box. When the items are fetched, user can select multiple items.So, user can do the first search, select some items and then do another search and select some more items. They all should be shown as selected in the input box. This is not happening.

### Expected Behavior
When user searches for another keyword, the previous selections should persists. So, in my example, the `cat` related chips should be visible. When user searches for `dog`, only the dropdown should change and allow the user to select more items.

### Actual Behavior
When user searches for another keyword, the input box is cleared of the previous selections, even though the `v-model` still has those items

### Reproduction Link
<a href="https://codepen.io/anon/pen/vbyevz?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/vbyevz?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment] 2019-01-30 12:22
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4000

**Closed by jacekkarczmarczyk** 2019-01-30 12:22 UTC
