### ISSUE TITLE
[Feature Request] Introduce page mode in v-virtual-scroll

### ISSUE THREAD

**Issue by knidhi** [vuetifyjs/vuetify#17818] opened 2023-07-16 05:52 UTC
### Problem to solve
User should be able to use v-virtual-scroll without setting a height on the parent. In the absence of height, v-virtual-scroll should utilize the available viewport to check which items should be visible.

### Proposed solution
Introduce a page mode to support this feature request.

Reference: https://github.com/Akryum/vue-virtual-scroller/blob/master/packages/vue-virtual-scroller/README.md#page-mode

**Comment by KaelWD** [comment] 2023-07-16 05:57
Duplicate of #17801

**Closed by KaelWD** 2023-07-16 05:57 UTC
Labels: S: triage
