### ISSUE TITLE
[Bug Report] v-text-field within v-dialog - text cursor does not appear in correct spot when on iPhone

### ISSUE THREAD

**Issue by Mathem8tic** [vuetifyjs/vuetify#2785] opened 2017-12-13 06:06 UTC
### Versions and Environment
**Vuetify:** 1.0.0-alpha.2
**Vue:** 2.5.10
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
https://vuetifyjs.com/components/dialogs

Open example #5 Forms and click on the fields...

### Expected Behavior
The text cursor would appear in the correct field

### Actual Behavior
The text cursor sometimes appears to be many pixels below or above the field, yet the inputted text does appear in the correct spot.

### Reproduction Link
[https://codepen.io/anon/pen/baNdXV?&editors=101](https://codepen.io/anon/pen/baNdXV?&editors=101)

**Comment by jacekkarczmarczyk** [comment] 2017-12-13 07:40
Please update the reproduction link (save it first before copying the link)

**Comment by Mathem8tic** [comment] 2017-12-13 09:25
My apologies, correct link added.

**Comment by Mathem8tic** [comment] 2017-12-22 08:18
Can I do anything to help?  I'm happy to assist with this issue.

**Comment by Mathem8tic** [comment] 2018-01-11 15:02
Any recommendations on this?  I swapped out the text fields for regular html 5 inputs and they have the same issue.   This is an issue preventing a launch of multiple sites so hopefully I can get a work around besides dumping the dialogs all together...

**Comment by nekosaur** [comment] 2018-01-11 15:14
Which iPhone and iOS version? Just checked the codepen on iPhone SE with iOS 10.2 and could not reproduce in any of the text fields

**Comment by Mathem8tic** [comment] 2018-01-11 16:24
Using a Iphone 7 version 11.1 currently.  I have tried on a few other Iphones with the same result.  Everything seems to work accept when interacting with they keyboard.  I think the change of height related to the keyboard opening is what bumps the cursor out of alignment with the selected field.

**Comment by nekosaur** [comment] 2018-03-08 11:11
More information

https://hackernoon.com/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug-aaf66c7ba3f8
https://bugs.webkit.org/show_bug.cgi?id=176896

There seems to be conflicting information on if this bug is fixed in iOS 11.3 beta or not

**Comment by jrast** [comment] 2018-05-10 16:57
According to the first link posted by @nekosaur, the bug is fixed in iOS 11.3.

**Comment by KaelWD** [comment] 2018-05-10 17:01
Can anyone confirm that it's fixed now?

**Comment by jrast** [comment] 2018-05-10 17:04
Sorry, I don't have a iOS device, so I can't test. I just stubled across this issue and thought I update it with the news in the linked article.

**Comment by johnleider** [comment] 2018-05-15 00:50
Can anyone that has an iPhone test this on v1.1 alpha?

**Comment by bdeo** [comment] 2018-05-15 01:08
I can’t seem to reproduce in either original code pen or the same code pen with @next vuetify urls on iPhone X, Safari on latest OS.  Only place where I can come up with a shifted cursor is during autocomplete suggestions which appears to be functioning as expected. I cannot repro anything even like in the links posted by neko.

**Comment by sebastianmacias** [comment] 2018-06-06 02:56
I'm having the same issues with the cursor being out of place in safari/chrome ios when using forms inside a dialog (fullscreen and not in fullscreen mode) in text boxes and also in selects with auto-completion. What makes it very interesting is that it doesn't always happen. I'm having these issues in a client's project so I'm not free to submit the code but I will try to figure out a way to reproduce it. I might be able to post a screencast. 

"vuetify": "^1.0.18"

**Comment by johnleider** [comment] 2018-06-06 02:57
@sebastianmacias This thread is specifically talking about v1.1-alpha+ . If you are having an issue on v1.0 branch, please check to see if it has already been reported or create a new issue with the issue creator.

**Comment by sebastianmacias** [comment] 2018-06-06 02:58
> Can anyone that has an iPhone test this on v1.1 alpha?

I will test it shortly and post what I find

**Comment by sebastianmacias** [comment] 2018-06-06 03:31
Tested with 1.1.0-alpha.4 and 1.1.0-beta.2. Same outcome as 1.0.18. 

Here is an [screencast](https://youtu.be/Qb8CUGk-VnQ).

**Comment by sebastianmacias** [comment] 2018-06-06 03:47
Here is another example with 1.1.0-alpha.4: https://youtu.be/m4nBYlyDNj8

**Comment by johnleider** [comment] 2018-06-06 03:48
What are you using to test on mobile?

**Comment by sebastianmacias** [comment] 2018-06-06 03:50
> What are you using to test on mobile?

browserstack.com, however this bug was reported by a person using a his actual iPhone X

**Comment by sebastianmacias** [comment] 2018-06-06 03:51
If you want I can send you the credentials to test it on our staging server and give you access to my browserstack.com account

**Comment by sebastianmacias** [comment] 2018-06-06 05:30
The issue can be fixed by changing the position of the dialog to absolute. Here is an: [screencast](https://youtu.be/CP9n7PU6mn8)

**Comment by avengerweb** [comment] 2019-08-09 02:03
Not reproducable, officaly fixed in iOS 11.3 for all actual devices (iPhone 5S+)

**Closed** 2019-08-09 02:09 UTC
Labels: C: VDialog, T: bug, help wanted, platform specific
