### ISSUE TITLE
[Bug Report][3.0.3] My basic form bugs at validation/reset due to null v-model

### ISSUE THREAD

**Issue by etienne-monier** [vuetifyjs/vuetify#16216] opened 2022-12-05 14:00 UTC
### Environment
**Vuetify Version:** 3.0.3
**Vue Version:** 3.2.45
**Browsers:** Firefox 107.0
**OS:** Ubuntu undefined, Linux

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVNtS2zAQ/ZVF0xmSmdim0L6YJBOmT33r9BXzoNgboiJbqi6GFPLvXckmOJcWMpPYezt79miV22d2o3XaemQ5mzqsteQO50UDMG2TUjWOiwZNdESXUY/zHxK5RfBaKl4Bh5WQmE6zLriX2Rk9lgT62lnBPl8WDErJbTA0Ty4KtsuMuStlajC4onB4pew2qVWFkhwtl6Iij+R/Nkk0uBOqGQCcpD4IDYkNm9IUiWi0d4S9jL1uureCHabvf3LjJYZZbkftGGZzODtr4eUFzr+ToCAsjfLbC4PV+d3epH1rEu6t9yHdPVXfH8JqXtLMoax/PZG0dA04fHLhPJQh3miMMqTpopSifCCHQYuOuP4MzwBGJR9Csr4s0dohlvXLWgSwbwZpt06jnZoz+E4dYxSM1uJtu2KifF29AdQhxDQbrDiZtjRCB83xSSvjoMIV99LBcyimxeI5jMaz+SjaAHHdcnDGY3Bsx5PwqNGtVWXzrgrotEm00fjVBHBrYdNPtM82DbzTPuG6i28jCAC3m6aETq1hNfG3rmsNM+CPXLgjxP4e4A60K1N0L6W6H8Xw+BqGDcPvlrKn2U4ENmGiDjokNdfpL6sa+lOIPIo+QAe7G5OuIslAdsHWzmmbZ5lv9MN9Wqo6W1AsM75xosakUvXiKr1Mv3zNKmHd0J+irZMlHZdFQx0L1osRwZ1Ybf7VoA8T7kV61cH2rgB5BJURfosmMdhUaJCW/T+8D3L3uB/EjvhHaUlZtp2wro5UjSTZ3V/1k6hZ)

### Steps to reproduce
Test 1: without file
1. click on reset

Test 2 : with file
1. Upload a dump file,
2. click on "reset"

Test 3 : with or without file:
1. (optional) Upload a file
2. click on create

### Expected Behavior
I expect the form to be reseted or validated whatever its state.
I also expect the file input to allow uploading a file or deleting it whatever the buttons I touched before that.

### Actual Behavior
The console simply throws 
```
TypeError: model.value is null
    default VFileInput.tsx:206
    normalized runtime-dom.esm-browser.js:5667
    renderFnWithContext runtime-dom.esm-browser.js:2351
    setup VField.tsx:276
    renderComponentRoot runtime-dom.esm-browser.js:2397
    componentUpdateFn runtime-dom.esm-browser.js:7111
    run runtime-dom.esm-browser.js:537
    update runtime-dom.esm-browser.js:7154
    updateComponent runtime-dom.esm-browser.js:6979
    processComponent runtime-dom.esm-browser.js:6912
    patch runtime-dom.esm-browser.js:6512
    patchKeyedChildren runtime-dom.esm-browser.js:7274
    patchChildren runtime-dom.esm-browser.js:7217
    processFragment runtime-dom.esm-browser.js:6897
    patch runtime-dom.esm-browser.js:6505
    patchKeyedChildren runtime-dom.esm-browser.js:7274
    patchChildren runtime-dom.esm-browser.js:7217
    patchElement runtime-dom.esm-browser.js:6731
    processElement runtime-dom.esm-browser.js:6592
    patch runtime-dom.esm-browser.js:6509
    patchKeyedChildren runtime-dom.esm-browser.js:7274
    patchChildren runtime-dom.esm-browser.js:7217
    patchElement runtime-dom.esm-browser.js:6731
    processElement runtime-dom.esm-browser.js:6592
    patch runtime-dom.esm-browser.js:6509
    componentUpdateFn runtime-dom.esm-browser.js:7120
    run runtime-dom.esm-browser.js:537
    update runtime-dom.esm-browser.js:7154
    updateComponent runtime-dom.esm-browser.js:6979
    processComponent runtime-dom.esm-browser.js:6912
    patch runtime-dom.esm-browser.js:6512
    componentUpdateFn runtime-dom.esm-browser.js:7120
    run runtime-dom.esm-browser.js:537
    update runtime-dom.esm-browser.js:7154
    callWithErrorHandling runtime-dom.esm-browser.js:1662
    flushJobs runtime-dom.esm-browser.js:1889
```

### Other comments
I saw [this issue](https://github.com/vuetifyjs/vuetify/issues/15568) before, but I don't think that's the same issue. I definitely can not make my own work.

**Comment by KaelWD** [comment] 2022-12-05 14:03
Duplicate of #16053

**Closed by KaelWD** 2022-12-05 14:03 UTC
Labels: T: bug, C: VFileInput

**Comment by etienne-monier** [comment] 2022-12-05 14:15
Ok, thanks a lot !
