### ISSUE TITLE
[Bug Report] VCombobox  selecting with keyboard when searching selects and creates new item at the same time

### ISSUE THREAD

**Issue by jimnojin** [vuetifyjs/vuetify#9809] opened 2019-11-27 11:35 UTC
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Mac OS 10.15.1

### Steps to reproduce
1. Type something to search - eg. 'vue'
2. Use arrows to select item from the list - eg. first one, 'Vue'
3. Hit Enter

### Expected Behavior
If item is selected and Enter is pressed, that item is selected and search is cleared

### Actual Behavior
Selected item is selected AND new item is created - both 'Vue' and 'vue'

### Reproduction Link
<a href="https://codepen.io/jimnojin/pen/MWWMNwz" target="_blank">https://codepen.io/jimnojin/pen/MWWMNwz</a>

### Other comments
Directly selecting item with mouse seems to work, but it does not clear the search (expected behaviour?)

**Comment by skortabeast** [comment] 2019-11-28 12:12
@jimnojin similar problem https://github.com/vuetifyjs/vuetify/issues/9758

**Comment by johnleider** [comment] 2020-01-16 00:57
Duplicate of #6697

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-16 00:57 UTC
Labels: C: VCombobox, T: bug, duplicate
