### ISSUE TITLE
[Bug Report] Invalid CSS in distributed CSS files

### ISSUE THREAD

**Issue by JurgenJocubeit** [vuetifyjs/vuetify#2528] opened 2017-11-16 07:03 UTC
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Safari 11.0
**OS:** Mac OS 10.12.6

### Steps to reproduce
```
import 'vuetify/dist/vuetify.min.css'
```

or 

```
require('vuetify/dist/vuetify.min.css')
````

in main application.js to include the vuetify stylesheet.

### Expected Behavior
CSS file is imported or required without error since it is a post-processed file.

### Actual Behavior
Results in an error: Undefined variable: "$list-tile-active-color".

### Reproduction Link
[https://codesandbox.io/s/kwlkw57nwv](https://codesandbox.io/s/kwlkw57nwv)

### Other comments
Error occurs at line 7841 of vuetify.css:

```css
.list__tile--active {
  color: $list-tile-active-color;
}
```

**Comment by KaelWD** [comment] 2017-11-16 07:15
Duplicate of #2497

**Closed by KaelWD** 2017-11-16 07:15 UTC
