### ISSUE TITLE
[Feature Request] Description under radio-group and checkbox element

### ISSUE THREAD

**Issue by ghost** [vuetifyjs/vuetify#8238] opened 2019-08-01 09:12 UTC
### Problem to solve
Is it possible to put a description text under a radio-group element?
 
``` "answers": [
        {
          "text": "Angular",
          "value": "Angular",
          "description": "Lorem ipsum dolor sit..."
        },
        {
          "text": "React",
          "value": "React",
          "description": "Lorem ipsum dolor sit..."
        },
        {
          "text": "Vue.js",
          "value": "Vue.js",
          "description": "Lorem ipsum dolor sit..."
        }
      ]
```

The field "description" should be under the label of the v-radio. If the description text overcomes a certain length, the hint "more..." will fold-out the entire text. The same goes for v-checkbox

Screenshot of a prototyp
![radio_elements](https://user-images.githubusercontent.com/38941038/62280972-323f4700-b44d-11e9-9bce-911e9736c422.PNG)

### Proposed solution

```<v-radio-group v-model="selectedAnswer" @change="onRadioGroupChange">
      <v-radio
        v-for="answer in question.answers"
        :key="answer.value"
        :label="answer.text"
        :value="answer.value"
        :description="answer.description" // prop for description
      ></v-radio>
    </v-radio-group>
```

**Comment by johnleider** [comment] 2021-11-23 20:01
duplicate of #6576

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-11-23 20:01 UTC
Labels: T: feature, C: Selection controls
