### ISSUE TITLE
[Feature Request] Timeline Control

### ISSUE THREAD

**Issue by jfuehner** [vuetifyjs/vuetify#3100] opened 2018-01-25 11:01 UTC
### New Functionality
Would love to see a timeline control with similar capabilities to http://visjs.org/examples/timeline/other/timezone.html. This timeline control would allow me to provide my users with the ability to fast forward/rewind data to points in time.

### Improvements
Currently there is nothing offered within the Vuetify suite of controls providing a work-around for such a control.

### Bugs or Edge Cases it Helps Avoid
n/a

**Comment by KaelWD** [comment] 2018-01-25 12:07
Duplicate of #1340

**Closed by KaelWD** 2018-01-25 12:07 UTC
Labels: pending review

**Comment by nekosaur** [comment] 2018-01-25 12:14
If the linked issue is not what you were after, I'd like to add that this is a _very_ specific component. I feel like it might be a better idea to wrap the one you linked to as a standalone vue (and or vuetify) component, and not something that would be included in vuetify.

**Comment by KaelWD** [comment] 2018-01-25 12:17
Yeah I guess it's not the same thing at all, I just saw "timeline". I do agree that this is probably outside the scope of this project, but if you want to build it yourself using vuetify components we'd be happy to link to it on https://github.com/vuetifyjs/awesome-vuetify
