### ISSUE TITLE
[Bug Report][2.6.1] v-slide-group rtl not work

### ISSUE THREAD

**Issue by nonomaxxis** [vuetifyjs/vuetify#14543] opened 2021-12-24 15:45 UTC
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 3.2.26
**Browsers:** Chrome 96.0.4664.110
**OS:** Windows 10

### Steps to reproduce
have 15 card but show only 6.5 card.

### Expected Behavior
show 15 card

### Actual Behavior
show only 6.5 card

### Reproduction Link
<a href="https://codepen.io/GarnetCMS/pen/bGoYpJb" target="_blank">https://codepen.io/GarnetCMS/pen/bGoYpJb</a>

### Other comments
hi, its not work correctly in RTL mode. i have 15 card but show only 6.5 card.

**Comment by KareemDa** [comment] 2021-12-25 16:53
@KaelWD 
this problem is the same problem #14529 (Vtab also contain a slide group).

I've opend  a PR to fix it, please check #14538

**Comment by KaelWD** [comment] 2021-12-27 08:18
Duplicate of #

**Closed by KaelWD** 2021-12-27 08:18 UTC
Labels: S: triage
