### ISSUE TITLE
[Bug Report] Custom filters on VDataTable columns are not evaluated if the search term does not match other columns

### ISSUE THREAD

**Issue by Ignigena** [vuetifyjs/vuetify#11179] opened 2020-04-22 01:12 UTC
### Environment
**Vuetify Version:** 2.3.0-beta.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Mac OS 10.15.4

### Steps to reproduce
- Add a custom `filter` function to any column header config
- This custom filter should represents a unique match that won't exist on any other column (example in the Codepen link is a case sensitive comparison to the Dessert name)
- Use a search term that should only match a row on the column with a custom filter

### Expected Behavior
The custom filter should match the row before and after the search term is entered.

### Actual Behavior
The custom filter is run before any search term is entered. Once a search term is entered it will never match the row because `headersWithCustomFilters` are run after matches are determined by `headersWithoutCustomFilters`

### Reproduction Link
<a href="https://codepen.io/Ignigena/pen/dyYOmxj?editors=1011" target="_blank">https://codepen.io/Ignigena/pen/dyYOmxj?editors=1011</a>

**Comment by jacekkarczmarczyk** [comment] 2020-04-26 19:57
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9887
@Ignigena please confirm i'm right and update your PR description (`closes #xxx`) or let me know if that's another issue

**Closed by jacekkarczmarczyk** 2020-04-26 19:57 UTC
Labels: triage

**Comment by Ignigena** [comment] 2020-04-27 14:49
@jacekkarczmarczyk Yes, it looks like this is a duplicate of that issue. Thank you! Missed that when I was searching for related issues.
