### ISSUE TITLE
[Feature Request] Missing v-select itemText and itemValue props

### ISSUE THREAD

**Issue by abumalekFayed** [vuetifyjs/vuetify#15071] opened 2022-05-08 10:06 UTC
### Problem to solve
When  data source for v srlect is array of objects i cant define value and display text as it found in vuetify 2

### Proposed solution
Adding value and text props

**Comment by nekosaur** [comment] 2022-05-08 11:02
Duplicate of https://github.com/vuetifyjs/vuetify/issues/14783

**Closed by nekosaur** 2022-05-08 11:02 UTC
Labels: S: triage
