### ISSUE TITLE
[Bug Report] Checkbox hover color is different than applied color

### ISSUE THREAD

**Issue by Raja4567** [vuetifyjs/vuetify#10980] opened 2020-03-30 23:14 UTC
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.15.4

### Steps to reproduce
Apply a different color other than vuetify's primary color. 
Hover over the checkbox and still the primary color is being shown.

This is also happening in V-Radio and

### Expected Behavior
The hover color , if not selected should be the same as the applied color

### Actual Behavior
The hover color is when not selected is always primary color

### Reproduction Link
<a href="https://codepen.io/Krato_74/pen/OJVdrYG" target="_blank">https://codepen.io/Krato_74/pen/OJVdrYG</a>

**Comment by KaelWD** [comment] 2020-03-31 04:23
Duplicate of #10979

**Closed by KaelWD** 2020-03-31 04:23 UTC
Labels: triage
