### ISSUE TITLE
[Bug Report] Nav drawer scrim not covering app bar

### ISSUE THREAD

**Issue by ChrisLandowski** [vuetifyjs/vuetify#8313] opened 2019-08-06 00:09 UTC
### Environment
**Vuetify Version:** 2.0.4
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Safari 12.1.2, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer
**OS:** Mac OS 10.14.6, Windows, Android, iOS, Mac OSX

### Steps to reproduce
Open the pen on a small screen or window and click the nav bar icon to display the nav drawer and scrim.

### Expected Behavior
The scrim should cover the app bar and block access to the add button.

### Actual Behavior
The scrim is behind the app bar and the add button is clickable.

### Reproduction Link
<a href="https://codepen.io/ChrisLandowski/pen/rXpjBm" target="_blank">https://codepen.io/ChrisLandowski/pen/rXpjBm</a>

### Other comments
This same problem also exists on the Vuetify documentation site.
Changing the z-index on the style tag from 5 to 10 should resolve the problem.

**Comment by KaelWD** [comment] 2019-08-06 03:54
Duplicate of #8040

**Closed by KaelWD** 2019-08-06 03:54 UTC
Labels: triage
