### ISSUE TITLE
Wrong Date displayed v-date-picker

### ISSUE THREAD

**Issue by nassimBo55** [vuetifyjs/vuetify#2259] opened 2017-10-20 07:06 UTC
### Steps to reproduce
Just go to [v-date-picker component](https://vuetifyjs.com/components/pickers#example-5) and you will see the bug. The date displayed inside the component box is correct but the **"original date"** and formatted date are wrong (it shows the next day)

### Versions

vuetify:  0.16.7
chrome: 61.0

### What is expected ?
Display the date correctly

### What is actually happening ?
The picker date works fine but when it displays the date it shows the next day, not the current one.

### Reproduction Link
Select a date and checkout the displayed "original date".
https://codepen.io/anon/pen/JrzKVW

Thanks for the great work

**Comment by jacekkarczmarczyk** [comment] 2017-10-20 07:20
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2022

**Closed by jacekkarczmarczyk** 2017-10-20 07:20 UTC
