### ISSUE TITLE
[Feature Request] V-Toolbar Auto Height

### ISSUE THREAD

**Issue by skylordjason** [vuetifyjs/vuetify#6328] opened 2019-02-01 20:55 UTC
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Use <v-toolbar> and apply a height prop set to "auto"

### Expected Behavior
Change the height of the toolbar based on the element's content

### Actual Behavior
Works, but throws an error about a failed custom validator.

### Reproduction Link
<a href="https://codepen.io/anon/pen/yZbYOB" target="_blank">https://codepen.io/anon/pen/yZbYOB</a>

**Comment by KaelWD** [comment] 2019-02-02 02:15
Duplicate of #3938

**Closed by KaelWD** 2019-02-02 02:15 UTC
Labels: T: feature
