### ISSUE TITLE
Selecting an item from v-select using enter closes surrounding v-edit-dialog

### ISSUE THREAD

**Issue by mueller-berlus** [vuetifyjs/vuetify#2165] opened 2017-10-13 09:04 UTC
### Steps to reproduce
Select an item using the enter key from a v-select that resides inside a v-edit-dialog.

### Versions

Vue 2.4.4
Vuetify 0.16.6
Chrome 58.0.3029.110 (64-bit)

### What is expected ?

I would expect the v-edit-dialog to stay open.

### What is actually happening ?

The v-edit-dialog closes.

### Reproduction Link

https://codepen.io/anon/pen/rGZObq

**Comment by jacekkarczmarczyk** [comment] 2017-10-13 09:15
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2092

**Closed by jacekkarczmarczyk** 2017-10-13 09:15 UTC
