### ISSUE TITLE
[Feature Request] Add longpress directives to Vuetify components

### ISSUE THREAD

**Issue by Alex-Mastin** [vuetifyjs/vuetify#8604] opened 2019-08-18 02:36 UTC
### Problem to solve
A common way to modify data is to add a button which calls a function to perform some logic. There are certain cases however where adding an edit button would ruin the aesthetic of the application or simply just doesn't make sense. Vuetify does work well as a collection of mobile-friendly UI components, but lacks some of the functionality that mobile UI components commonly have.

Being able to longpress on an element for extra functionality would add a lot of potential for mobile-focused applications, and would make it easier to create progressive web applications which are near indistinguishable from native apps.

### Proposed solution
Add a `@longpress` directive to any components where it makes sense. Components would then have a `start` and `end` event where a function could be called. 

For example, after longpressing an element, the `start` event would fire and a dialog could appear with a list of options for the user to choose from. 

There are some npm packages available which add this functionality in already, but I think it would be nice to see it included with Vuetify as it would open up a lot of possibilities, and it also is part of the Material Design specs.

**Comment by HeadAdmiral** [comment] 2019-08-18 03:10
Also just found out that you can do `window.navigator.vibrate(ms)` to vibrate the device, so you could even add vibration on `longpress` as well.

**Comment by KaelWD** [comment] 2024-01-23 03:10
Duplicate of #5322

**Closed by KaelWD** 2024-01-23 03:10 UTC
Labels: duplicate

**Comment by jiangzik** [comment] 2024-07-19 16:32
I need longpress
