### ISSUE TITLE
Allow using objects <v-breadcrumbs-item> href prop like in <v-toolbar-item>

### ISSUE THREAD

**Issue by sebastianmacias** [vuetifyjs/vuetify#554] opened 2017-05-18 06:09 UTC
Currently <v-breadcrumbs-item> 'href' only allows strings to define the URL. 
Objects should be passed to the router "to" prop just like  <v-toolbar-item>.

**Comment by johnleider** [comment] 2017-05-18 16:46
Duplicate of #352 , already implemented.

**Closed by johnleider** 2017-05-18 16:46 UTC
