### ISSUE TITLE
[Bug Report] VDialog VOverlay on background tab

### ISSUE THREAD

**Issue by buzzzzer** [vuetifyjs/vuetify#8625] opened 2019-08-20 08:26 UTC
### Environment
**Vuetify Version:** 2.0.7
**Last working version:** 1.5.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
1. Open codepen link in background  tab. 
2. Wait  a couple of seconds.
3. Activate browser tab. 
VDialog closed, but VOverlay still present

### Expected Behavior
kill VOverlay 

### Actual Behavior
VOverlay locks window

### Reproduction Link
<a href="https://codepen.io/Buzzzzer/pen/YzKGLoO?editors=1010" target="_blank">https://codepen.io/Buzzzzer/pen/YzKGLoO?editors=1010</a>

**Comment by malkhuzayyim** [comment] 2019-12-02 10:18
Just wanted to note a current existing workaround:

Just skip using the dialog and use the v-overlay directly with a v-card, seems to work fine as compared to "persistent" dialog, and somewhat similar result, just no default animations as offered by the dialog

**Comment by ashkan90** [comment] 2019-12-27 11:30
`
<v-overlay :value="hold" :opacity="0.3">
    <v-card
      color="blue darken-2"
      dark width="300">
      <v-card-text>
        Loading... Please wait.
        <v-progress-linear
          indeterminate
          color="white"
          class="mb-0"
        ></v-progress-linear>
      </v-card-text>
    </v-card>
  </v-overlay>
`
this might be a different alternative until the problem is solved.

**Comment by Pazza** [comment] 2020-02-10 14:37
After 6 months of no fix, is this bug lost in the cracks or is there no trivial way to fix?

**Comment by ananthachetan** [comment] 2020-04-05 14:15
Hello.. When can we expect a fix for this?

**Comment by johnleider** [comment] 2020-04-07 22:26
There was an existing PR that was abandonned and it wasn't until recently that a new PR was opened. We are always looking for passionate developers to help us with building the framework. If you have any questions, reach out to me in the community, https://community.vuetifyjs.com . 

Thank you everyone for your patience.

**Closed** 2020-04-07 22:27 UTC
Labels: C: VDialog, T: bug

**Comment by nekooee** [comment] 2021-03-23 10:14
my vuetify version is 2.4.3 but not resolved the problem and the background of the loading dialog doesn't remove if users in another browser tab. :(

**Comment by johnleider** [comment] 2021-03-23 16:19
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
