### ISSUE TITLE
[Bug Report][2.5.8] example page error https://vuetifyjs.com/en/examples/wireframes/discord/

### ISSUE THREAD

**Issue by mtrucc** [vuetifyjs/vuetify#14060] opened 2021-08-15 23:42 UTC
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.13
**Browsers:** Chrome 92.0.4515.107
**OS:** Mac OS 10.15.7

### Steps to reproduce
open https://vuetifyjs.com/en/examples/wireframes/discord/

### Expected Behavior
can open

### Actual Behavior
can open

### Reproduction Link
<a href="https://codepen.io/mtrucc/pen/bGWJmrB" target="_blank">https://codepen.io/mtrucc/pen/bGWJmrB</a>

**Comment by KaelWD** [comment] 2021-08-16 16:33
Duplicate of #12854

**Closed by KaelWD** 2021-08-16 16:33 UTC
Labels: T: bug, T: documentation, S: triage
