### ISSUE TITLE
[Bug Report][3.0.0-beta.2] v-select and v-combobox lists are hidden behind v-dialog

### ISSUE THREAD

**Issue by ThibaultNocchi** [vuetifyjs/vuetify#15167] opened 2022-05-30 08:52 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.2
**Vue Version:** 3.2.36
**Browsers:** Firefox 100.0, Google Chrome
**OS:** Linux x86_64, iOS

### Steps to reproduce
- Use v-select or v-combobox in a v-dialog
- Open the dialog and the select list

### Expected Behavior
The list should appear in front of the dialog

### Actual Behavior
The list appears behind the dialog

### Reproduction Link
<a href="https://github.com/ThibaultNocchi/vuetify3-vselect-dialog" target="_blank">https://github.com/ThibaultNocchi/vuetify3-vselect-dialog</a>

### Other comments
Tested on FF, Chromium and iOS. They all don't work as intended.
![IMG_2815](https://user-images.githubusercontent.com/1619359/170955539-317ea0e4-ac97-4ba4-b896-5af9a7354e57.PNG)

**Comment by KaelWD** [comment] 2022-05-30 08:58
Duplicate of #15134

**Closed by KaelWD** 2022-05-30 08:58 UTC
Labels: S: triage

**Comment by ThibaultNocchi** [comment] 2022-05-30 09:49
Sorry, searched for "v-select" in the issues and not "VSelect". Have a nice day!
