### ISSUE TITLE
[Bug] Updating v-model for v-text-field from key press handlers is broken

### ISSUE THREAD

**Issue by an-sh** [vuetifyjs/vuetify#1974] opened 2017-10-01 09:59 UTC
### Steps to reproduce

Create a text field with a v-model and try to update it inside key events handlers. 

### Versions

0.15.7

### What is expected ?

The text field is updated with a value assigned to v-model inside a key event handler.

### What is actually happening ?

v-model is updated but the v-text-field displayed value remains the same (lazyValue still contains the old value)

### Reproduction Link

https://codepen.io/anon/pen/eGEdvx

**Comment by KaelWD** [comment] 2017-10-01 10:20
Duplicate of #1726

**Closed by KaelWD** 2017-10-01 10:20 UTC
