### ISSUE TITLE
[Bug Report] VIcon CSS "race condition" with Material Icons CSS

### ISSUE THREAD

**Issue by dominik-bln** [vuetifyjs/vuetify#7746] opened 2019-07-04 10:04 UTC
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
Inspect the Icon CSS in the Codepen and reorder the load order of Material Icons and Vuetify CSS via the settings. The `.material-icons` style overwrite `.v-icon` styles if loaded last.

In our production builds the Vuetify CSS files usually arrive first at the client and the CSS that comes along from the Material Icons CDN is often second. When this happens the icons can look different because both `.v-icon` and `.material-icons` have the same specificity and the styling to arrive last "wins".

### Expected Behavior
VIcon always has the same CSS.

### Actual Behavior
VIcon styling differs by CSS load order.

### Reproduction Link
<a href="https://codepen.io/dominik-bln/pen/JQBGXj" target="_blank">https://codepen.io/dominik-bln/pen/JQBGXj</a>

### Other comments
https://stackoverflow.com/a/1321722/169773

**Comment by dominik-bln** [comment] 2019-07-04 10:04
![Screenshot 2019-07-04 at 11 23 37](https://user-images.githubusercontent.com/855119/60658605-d71d3300-9e53-11e9-983a-d2bfcc80438c.png)

**Comment by sh7dm** [comment] 2019-07-09 10:22
Fixed in 4b19e34

**Comment by jacekkarczmarczyk** [comment] 2019-07-10 08:31
reverted in 7f0ba3899177d582002d4e29a50c63109994e3e6

**Comment by jacekkarczmarczyk** [comment] 2019-07-10 08:33
And duplicate of https://github.com/vuetifyjs/vuetify/issues/5741

**Closed by jacekkarczmarczyk** 2019-07-10 08:33 UTC
Labels: P: low, T: bug

**Comment by dominik-bln** [comment] 2019-07-10 16:51
@jacekkarczmarczyk I'm confused, now both issues are closed and the change has been reverted. Is this a "Won't fix" for you or is there another change I'm not seeing?

I don't think the answer in the other issue really addresses the problem as loading material icons from CDN is described in the docs:

https://vuetifyjs.com/en/framework/icons#install-material-icons

**Comment by MajesticPotatoe** [comment] 2019-07-10 17:11
This issue was closed initially because a change was made to fix it. That change was incorrect, and was reverted which reopened the issue. It was closed again because it was a duplicate of 5741. 5741 was closed by the OP, not sure why (probably because he tried the comment that was posted and it worked? who knows).

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.

**Comment by jacekkarczmarczyk** [comment] 2019-07-10 18:30
The fix is to simply add vuetify css after material icons as stated in the #5741 (regardless of how do you load them - from cdn or using `import`). Afaik it doesn't matter which styles are **loaded** first (and if it does please provide a reproduction)
