### ISSUE TITLE
[Feature Request] VFileInput: add a placeholder prop

### ISSUE THREAD

**Issue by antoinematyja** [vuetifyjs/vuetify#20744] opened 2024-11-28 18:06 UTC
### Problem to solve
The VFileInput component has a `label` prop but not a `placeholder` prop, which is mandatory to have consistent input styles on forms having text inputs and file inputs.

### Proposed solution
Add a `placeholder` prop to the VFileInput component, and simply pass its value to the VField used inside the component.

This was already asked here: https://github.com/vuetifyjs/vuetify/issues/15928

A solution was proposed: use the label, but it is not ideal as the text displayed in the input will have the style of the label which is different from the style of a placeholder (usually a lighter color).
See for example: https://play.vuetifyjs.com/#eNqNUUGOgzAM/EqU87LcVyzSPmBPe1x6AGKKJWOi4FStqv69JtCW3lCkKB5PJp7M/9VOoc1/vP88RbBfthAYPNUCZcXGFKes9j4dU9GOLDUyhBVKoMBZsg6BnNGbLfQjOQjflf29mA7DJAbZR6lsWeRbtmrsVJlAH3a7ZDokyBbiChrjA3hgl6GqqKCuZ0vdpQ6rp0d/cJhktjyqG6BlGOkxPGd5MSbkoz5N+jsPMA36Gmi/326MQfpdfhvh8i82A8rMmqs1LK3e05qRJcwi34Rsbx8cidJ2uAMWWKvC

**Comment by KaelWD** [comment] 2024-12-02 10:37
Duplicate of #19837

**Closed by KaelWD** 2024-12-02 10:37 UTC
Labels: S: triage
