### ISSUE TITLE
[Bug Report] v-text-field v-model not updated immediately on android chrome

### ISSUE THREAD

**Issue by WIStudent** [vuetifyjs/vuetify#11243] opened 2020-04-27 13:43 UTC
### Environment
**Vuetify Version:** 2.2.25
**Last working version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Android

### Steps to reproduce
1. Open linked codepen in Android Chrome
2. Enter a word into the textfield

### Expected Behavior
The counter should increase with each character, the next button should be enabled as soon as the textfield contains at least one character.

### Actual Behavior
The counter is only updated after the autocomplete composition is finished by chrome. Likewise the v-model isn't updated immediately, causing the next button not to enable until the user either enters a blank character or closes the keyboard.

![demo](https://user-images.githubusercontent.com/2707930/80378775-77d65680-889d-11ea-9218-a32511db6156.gif)

### Reproduction Link
<a href="https://codepen.io/wistudent/pen/pojPmVw" target="_blank">https://codepen.io/wistudent/pen/pojPmVw</a>

### Other comments
This was probably introduced by the changes made in 2.2.23 and 2.2.24 concering the IME string composition:
> VTextField: skip value property update if IME composing string (#11134) (c02be82), closes #5748
> VTextField: update value on compositionend (#11194) (f51bef6), closes #11190 #5748

If this is the new intented behaviour a new property to force the immediate update would be helpful.

**Comment by neenus** [comment] 2020-04-28 15:15
I would love to see a fix for this as well

**Comment by kouqon** [comment] 2020-04-29 18:42
What I want to do is match VTextField behavior to HTMLInputElement on Vue.

https://vuejs.org/v2/guide/forms.html#Basic-Usage
> For languages that require an IME (Chinese, Japanese, Korean, etc.), you’ll notice that v-model doesn’t get updated during IME composition. If you want to cater to these updates as well, use the input event instead.

[On this patch](https://github.com/kouqon/vuetify/commit/aeb24db2862ff3c697f786dad9b3f7b710b179c7) VTextField behave as the following:
* @input event emit on every character input
* v-model and value property update if not on composing with IME
* @change event emit on blur or input enter key (not on composing)
* counter update on every character input

I'm starting to wonder if this behavior is what everyone want.
Is it better to revert to pre-v2.2.22 behavior?

**Comment by WIStudent** [comment] 2020-04-29 20:30
Interesting, I tried a new demo with HTMLInputElement and see the same issue. 
https://codepen.io/wistudent/pen/JjYyOdm

Android Chrome fires a new compositionStart and compositionEnd event for each new word, not only when writing in Chinese, Japanese, Korean, etc. but also when writing in English or German.

Although the input event can be a replacement for the v-model, it doesn't fix the problem with vuetify's built in counter. Seeing that this affects possibly all languages on Android Chrome I would suggest to revert this change and reintroduce it in a future minor or major update (not patch update), when the impact on other vuetify components (like counter, etc) is better understood.

**Comment by kouqon** [comment] 2020-04-30 02:53
This behavior is what I expected on [the patch](https://github.com/kouqon/vuetify/commit/aeb24db2862ff3c697f786dad9b3f7b710b179c7):
https://codepen.io/kouqon/pen/GRprMPm

v-model updated on "update:value" event. counter is updating on every input.

Anyway this change may cause many unexpected behavior on text input components. I'll withdraw commits and re-propose on next branch.

**Closed** 2020-04-30 14:54 UTC
Labels: C: VTextField, platform specific, triage

**Comment by myleslee** [comment] 2020-05-08 13:01
Actually this is just how compositionStart and compositionEnd are supposed to work. The word being entered is not sent to the input element until it's been confirmed with the Enter key, so the counter should not change until the input is given a definite value. 

I tried WIStudent's example  https://codepen.io/wistudent/pen/pojPmVw on an Android phone. If I switch the input method to English, the counter just works for each input event because compositionStart and compositionEnd won't stand in the way when the input method/keyboard  layout is set to English (pure English). When I switch to Chinese input method, the counter won't be updated until I confirm the Chinese character by pressing Enter and make it to the input element. It just seems very natual for IME users because it is just the way it is for many years.

**Comment by jacekkarczmarczyk** [comment] 2020-05-08 13:11
> If I switch the input method to English, the counter just works for each input event

What do you exactly mean? I've just checked Firefox/Chrome on Android and counter stays 0 (and button disabled) until i confirm the word

![image](https://user-images.githubusercontent.com/15625235/81408788-269c5180-913e-11ea-9033-42f89940879d.png)

**Comment by neenus** [comment] 2020-05-08 14:49
> Actually this is just how compositionStart and compositionEnd are supposed to work. The word being entered is not sent to the input element until it's been confirmed with the Enter key, so the counter should not change until the input is given a definite value.
> 
> I tried WIStudent's example https://codepen.io/wistudent/pen/pojPmVw on an Android phone. If I switch the input method to English, the counter just works for each input event because compositionStart and compositionEnd won't stand in the way when the input method/keyboard layout is set to English (pure English). When I switch to Chinese input method, the counter won't be updated until I confirm the Chinese character by pressing Enter and make it to the input element. It seems very natural for IME users because that's the way it is for many years.

I'm not too sure how you checked it but I'm checking on chrome on Android and English language still only shows characters after you tap on space or confirm work in the autosuggest bar

**Comment by pepperbc** [comment] 2020-07-02 00:32
> > Actually this is just how compositionStart and compositionEnd are supposed to work. The word being entered is not sent to the input element until it's been confirmed with the Enter key, so the counter should not change until the input is given a definite value.
> > I tried WIStudent's example https://codepen.io/wistudent/pen/pojPmVw on an Android phone. If I switch the input method to English, the counter just works for each input event because compositionStart and compositionEnd won't stand in the way when the input method/keyboard layout is set to English (pure English). When I switch to Chinese input method, the counter won't be updated until I confirm the Chinese character by pressing Enter and make it to the input element. It seems very natural for IME users because that's the way it is for many years.
> 
> I'm not too sure how you checked it but I'm checking on chrome on Android and English language still only shows characters after you tap on space or confirm work in the autosuggest bar

I can confirm I am having the exact same issue on Android in (American) English.
