### ISSUE TITLE
Vuetify on Android 4.2.2

### ISSUE THREAD

**Issue by vinodhum** [vuetifyjs/vuetify#3340] opened 2018-02-20 05:00 UTC
Hi,
I am trying to build hybrid app for android 4.2.2.
out of the box Vue works fine on Android 4.2.2 but when I try to add vuetifyjs to vue js app is not loading.
it just shows white screen on load.

here are the steps I fallowed.

$ vue init webpack my-project
$ cd my-project
$ npm install
$ npm run dev
This one works fine on 4.2.2

but when i try
$ npm install -g vue-cli
$ vue init vuetifyjs/webpack my-project
$ cd my-project
$ npm install
$ npm run dev
This is showing white screen

is this knows issue or if vuetify/vuejs is supported or not on Android 4.2.2 ?

**Comment by nekosaur** [comment] 2018-02-20 10:54
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2388

**Closed by nekosaur** 2018-02-20 10:54 UTC
Labels: duplicate
