### ISSUE TITLE
[Bug Report] Ripple overlay on buttons don't disappear after clicking alternatively between left and right mouse buttons

### ISSUE THREAD

**Issue by phiter** [vuetifyjs/vuetify#6734] opened 2019-03-14 18:47 UTC
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.6.9
**Browsers:** Chrome 73.0.3683.75
**OS:** Linux x86_64

### Steps to reproduce
Just spam click both mouse buttons on top of the button, the ripple overlays won't go out unless you pass the mouse over and out of the button. 

### Expected Behavior
The ripples should just go away.

### Actual Behavior
Some ripples remain until you hover in and out of the button, so they leave one by one.

### Reproduction Link
<a href="https://8nprqr70vj.codesandbox.io/" target="_blank">https://8nprqr70vj.codesandbox.io/</a>

![Peek 2019-03-14 15-42](https://user-images.githubusercontent.com/12252332/54383240-5f42b700-4670-11e9-9ab0-ab77fc024301.gif)

**Comment by phiter** [comment] 2019-03-14 18:53
Ok I actually found a better way to reproduce this other than spamming the buttons:

Click with right button, then left, take the cursor out of the button and repeat as many times as you need:

![Peek 2019-03-14 15-53](https://user-images.githubusercontent.com/12252332/54383657-530b2980-4671-11e9-9642-751571a644ed.gif)

**Comment by KaelWD** [comment] 2019-03-15 01:57
Duplicate of #4185

**Closed by KaelWD** 2019-03-15 01:57 UTC
Labels: duplicate
