### ISSUE TITLE
[Bug Report][3.5.6] v-select checked status and clear icon not working

### ISSUE THREAD

**Issue by eolamisan** [vuetifyjs/vuetify#19306] opened 2024-02-29 15:33 UTC
### Environment
**Vuetify Version:** 3.5.6
**Vue Version:** 3.4.15
**Browsers:** Edge 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
v-select with FontAwesome icons doesn't update the icons checked vs unchecked.
Steps: Check item, uncheck item. 

### Expected Behavior
The icon is unchecked.

### Actual Behavior
The checked icon doesn't update. It still shows checked.

### Reproduction Link
[https://codesandbox.io/p/sandbox/using-vue-fontawesome-in-vue-3-forked-28yvmk](https://codesandbox.io/p/sandbox/using-vue-fontawesome-in-vue-3-forked-28yvmk)

### Other comments
Click clear icon.
Expected: the items are cleared.
Actual: it doesn't clear items selected.

**Comment by KaelWD** [comment] 2024-02-29 16:17
Duplicate of #3505

You cannot use dom.watch with vue

**Closed by KaelWD** 2024-02-29 16:17 UTC
Labels: S: triage

**Comment by eolamisan** [comment] 2024-02-29 17:40
The ticket was closed as not planned. What does it mean? v-select does not support FA?

**Comment by KaelWD** [comment] 2024-03-01 00:42
https://vuetifyjs.com/en/features/icon-fonts/#fa-5-svg
