### ISSUE TITLE
[Bug Report][3.6.10] OTP Input Autofill not working on desktop

### ISSUE THREAD

**Issue by igonzalezprs** [vuetifyjs/vuetify#20063] opened 2024-06-26 15:47 UTC
### Environment
**Vuetify Version:** 3.6.10
**Last working version:** 2.6.10
**Vue Version:** 3.4.21
**Browsers:** Chrome 126.0.0.0
**OS:** Windows 10

### Steps to reproduce
- Clone the repo
- Install dependencies
- Serve project
- Add a One Time Password manager (1Password was used to reproduce the error)
- Click "Autofill"

### Expected Behavior
- Input and ref are filled

### Actual Behavior
- Input shows for a moment the correct password but then clears. Ref remains empty the whole time. Copying and pasting works fine. Manually putting the input works too.

![Untitled](https://github.com/vuetifyjs/vuetify/assets/38574813/53c91e86-fa70-4a9d-b767-e63e3f6a9303)

### Reproduction Link
[https://github.com/igonzalezprs/vuetify-otp-bug](https://github.com/igonzalezprs/vuetify-otp-bug)

**Comment by louisodint** [comment] 2024-09-20 08:41
Hi,
I encouter the same problem but with Keepass

**Comment by Scaenicus** [comment] 2024-10-01 10:25
See #18678

**Comment by MatthewAry** [comment] 2024-11-17 05:22
Duplicate of https://github.com/vuetifyjs/vuetify/issues/18678

**Closed by MatthewAry** 2024-11-17 05:22 UTC
Labels: S: triage
