### ISSUE TITLE
[Feature Request] Replace Stylus with SASS

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#2371] opened 2017-10-30 08:29 UTC
### New Functionality
I have been a long lover of Stylus and I was really glad to see that Vuetify is using it. But after some time I realized that [Stylus development has stagnated](https://github.com/stylus/stylus/graphs/contributors) and this really means it is easy to hit issues, especially as CSS continues to be developed.

I would propose that Stylus is replaced with SASS.

### Improvements
This would make it future proof and as Vuetify is closing to 1.0 is probably the last moment to do so. Especially as we will be developing themes and so on.

### Bugs or Edge Cases it Helps Avoid
There are many bugs reported but not addressed to Stylus, which all software which depends on it can then have. This is especially a problem if one does not want to use a compiled dist version of Vuetify CSS, but import directly Stylus code.

**Comment by johnleider** [comment] 2017-11-01 00:20
(╯°□°)╯︵ ┻━┻

**Comment by KaelWD** [comment] 2017-11-01 05:09
Duplicate of #1857, but worded a bit better.

**Comment by bonatoc** [comment] 2017-11-01 12:27
I just installed sass-loader and node-sass locally, and I can use either stylus or sass in my .vue files. You can choose to ignore working with stylus and use only sass.
FYI, this is true testing from [this HNPWA template](https://github.com/vuejs/vue-hackernews-2.0) with Vuetify added.

**Comment by mitar** [comment] 2017-11-01 17:00
But to configure a theme, or access other Vuetify variables, you have to use Stylus,.

**Comment by johnleider** [comment] 2017-11-01 17:02
Only for about another week :)

**Comment by mitar** [comment] 2017-11-01 17:19
Oh. :-) I hope I will be able to access variables (like padding amounts, etc.) in a week as well. This is very useful to define additional CSS rules matching the same sizes.

**Comment by johnleider** [comment] 2017-11-01 17:25
Absolutely, none of that changes, just easier to specify theme specific colors.

**Comment by mitar** [comment] 2017-11-01 17:30
OK, but one cannot access variables from SCSS, no? Maybe could variables be exported as CSS variables?

**Comment by mitar** [comment] 2017-11-01 17:30
And I still worry that core Stylus styles might break. :-(

**Comment by johnleider** [comment] 2017-11-01 17:32
I have no idea where you get that notion from, if you want we can continue this conversation on https://chat.vuetifyjs.com

**Comment by johnleider** [comment] 2017-11-06 01:56
Duplicate of #1857

**Closed by johnleider** 2017-11-06 01:56 UTC
Labels: feature request

**Comment by mrts** [comment] 2017-11-27 20:35
... and #586

I bet this will keep popping up. Would it make sense to arrange a fundraiser for SASS support?

**Comment by johnleider** [comment] 2017-11-27 20:37
Never really thought of that.

**Comment by mrts** [comment] 2017-12-13 08:30
And here is some evidence that this will keep popping up more and more as Vuetify gains popularity: http://stateofjs.com/2017/css/results

18 K people have used and will use SASS, only 9% (1.7 K / 18 K) say that they will not use it again, whereas 2,4 K people have used and will use Stylus, but 80% (1.9 K / 2.4 K) will not use it again.

Maybe the SASS-to-Stylus-and-back-again toolchain would really be a way forward? So that people could freely choose during project generation:

> Use SASS or Stylus? SASS

**Comment by mrts** [comment] 2017-12-17 11:48
I investigated Stylus code a bit and it looks neat and easily extensible. I propose to fork Stylus and implement compilation to SASS right inside Stylus itself.

[stylus.js](https://github.com/stylus/stylus/blob/dev/lib/stylus.js) is the compiler library entry point. As far as I can see, the only thing required is to implement a custom [Compiler](https://github.com/stylus/stylus/blob/dev/lib/visitor/compiler.js) and this doesn't look too scary given that the CSS compiler is only 500 lines.

@johnleider would you endorse this and add official SASS support to the project generator if someone else takes care of the Stylus-to-SASS part?

**Comment by johnleider** [comment] 2017-12-18 12:09
Yes

**Comment by mrts** [comment] 2017-12-18 20:50
Perfect, thank you!

**Comment by maziarz** [comment] 2018-01-02 13:50
This would be awesome! Where to start?

**Comment by pSchaub** [comment] 2018-01-02 13:54
@johnleider Would you agree a PR if we partially change from stylus to SCSS/SASS (step-by-step)?
Or do you want one huge PR to change everything at once?

**Comment by maziarz** [comment] 2018-01-02 13:56
Without starting a war, i would vouch

**Comment by maziarz** [comment] 2018-01-02 13:58
Without starting a war, i would vouch for SCSS..

**Comment by mrts** [comment] 2018-01-02 16:07
@pSchaub , @maziarz - @johnleider did not agree with migrating to SCSS/SASS all over. He agreed to support add official SASS/SCSS support to the project generator if someone else takes care of the Stylus-to-SASS/SCSS part in Stylus.

**So the first step is to start playing with Stylus to see how easy it is to convert/compile .sty files to .scss files.**

[stylus.js](https://github.com/stylus/stylus/blob/dev/lib/stylus.js) is the compiler library entry point. As far as I can see, the only thing required is to implement a custom [Compiler](https://github.com/stylus/stylus/blob/dev/lib/visitor/compiler.js). The CSS compiler is only 500 lines, but compiling to SASS/SCSS may be more complex.

**Comment by hellosylvee** [comment] 2018-01-25 15:42
what's the current status on this? Is the compilation still in the works?

**Comment by mrts** [comment] 2018-01-25 17:21
@hellosylvee - there is a clear plan how to implement the compilation (see https://github.com/vuetifyjs/vuetify/issues/2371#issuecomment-354801336), but no-one has stepped up to do it yet. I myself cannot do it currently.

**Comment by jaunkst** [comment] 2018-03-23 23:51
Might be able to transpile the stylus to scss/sass by using the stylus Parser to gain access to the AST from stylContent. Would need to run a spike on it out but it should be possible.

**Comment by mrts** [comment] 2018-03-24 10:19
@jaunkst, sounds like a plan :)

**Comment by shadowcodex** [comment] 2018-03-29 03:35
@jaunkst @mrts I have already started work on the stylus to scss conversion. I’ll have it done soon :tm:

**Comment by shadowcodex** [comment] 2018-03-29 03:40
I’m doing it by hand to ensure code completion, readability, and correctness.

**Comment by raditsp** [comment] 2018-05-21 16:51
👍

**Comment by nmsmith22389** [comment] 2018-07-25 05:53
I converted all of the styles over to scss. It might still need a few tweaks but it's working great so far!

**Comment by AlexandreBonneau** [comment] 2018-10-02 22:06
This is great @nmsmith22389 !

But...what now?

The 5th of November 2017, John closed this issue since it had a [duplicate](https://github.com/vuetifyjs/vuetify/issues/1857)...but that duplicate was closed on the 23th of September 2017.
So there aren't really any way to follow-up on this issue since none are opened as of now; not cool!

So...thanks to @nmsmith22389, which did a [*monumental amount of work*](https://github.com/vuetifyjs/vuetify/issues/1857#issuecomment-331664593), we now have a stylus-free Vuetify.

Since Stylus is still [slowly](https://www.slant.co/versus/762/764/~stylus_vs_sass) [dying](https://github.com/stylus/stylus/graphs/contributors) *(issues piling up, lack of support for new CSS features like grid and custom properties..)*, perhaps it's time to move on and merge those changes? :innocent:

What do you think?

**Comment by johnleider** [comment] 2018-10-05 18:45
@nmsmith22389 Can you come to the community and chat with me? https://chat.vuetifyjs.com

**Comment by nicokoenig** [comment] 2018-11-14 08:36
@johnleider any updates here?

**Comment by simonmaass** [comment] 2018-12-13 08:18
same here - would love to see scss support

**Comment by dzcpy** [comment] 2019-02-08 20:30
`less` please, it's faster and no need to install native modules

**Comment by mrts** [comment] 2019-04-01 21:41
Stylus will be replaced with SCSS in version 2.0, see https://github.com/vuetifyjs/vuetify/issues/6676

**Comment by edwinharly** [comment] 2019-08-15 13:05
Currently I'm depending on the vuetify 1.5 styl files, if I want to upgrade to v2, do I have to convert all to sass ???

**Comment by pschaub** [comment] 2019-08-15 16:38
You could try out tools to convert styl to sass:
https://www.npmjs.com/package/stylus-converter

I did not try it out. Maybe there are better tools.

**Comment by eing-ooca** [comment] 2019-09-06 08:32
> Currently I'm depending on the vuetify 1.5 styl files, if I want to upgrade to v2, do I have to convert all to sass ???

i wanna know too TT

**Comment by jacekkarczmarczyk** [comment] 2019-09-06 10:11
If you want to use vuetify variables you need to use sass, if you don't use them you can keep your .styl files
