### ISSUE TITLE
[Bug Report] Date time Picker year in fa wrong

### ISSUE THREAD

**Issue by btechn01** [vuetifyjs/vuetify#8091] opened 2019-07-27 07:22 UTC
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
Hi,

Just set locale to "fa" in v-date-picker and set date to now and in year it show 1397 but in "fa" year is 1398

### Expected Behavior
in persian calender it year shows 1397

### Actual Behavior
in persian calender now is 1398

### Reproduction Link
<a href="https://codepen.io/anon/pen/aeBWpv" target="_blank">https://codepen.io/anon/pen/aeBWpv</a>

**Comment by jacekkarczmarczyk** [comment] 2019-07-27 09:04
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1892

**Closed by jacekkarczmarczyk** 2019-07-27 09:04 UTC
Labels: triage
