### ISSUE TITLE
[Bug Report] The propery label of v-radio-group doesn't respect the padding-bottom

### ISSUE THREAD

**Issue by zem83** [vuetifyjs/vuetify#11987] opened 2020-08-03 07:17 UTC
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.6.1
**Browsers:** Chrome 84.0.4147.105
**OS:** Linux x86_64

### Steps to reproduce
1. open Codepen link;
1. click Change View button and choose the most right editor layout;
1. reduce the left column until the radio group label overflows the choices;

### Expected Behavior
The radio group label does not overflow the choices, applying the padding-bottom instruction.

### Actual Behavior
The radio group label overflows the choices.

### Reproduction Link
<a href="https://codepen.io/zem83/pen/vYGBKmx?editors=1010" target="_blank">https://codepen.io/zem83/pen/vYGBKmx?editors=1010</a>

![image](https://user-images.githubusercontent.com/28530533/89155909-142d8a80-d56a-11ea-8304-2bdee900ebed.png)

**Comment by KaelWD** [comment] 2020-08-03 07:23
Duplicate of #11976

**Closed by KaelWD** 2020-08-03 07:23 UTC
Labels: triage
