### ISSUE TITLE
[Bug Report] V-Chip close icon aligned false with mdi/js

### ISSUE THREAD

**Issue by Oli22** [vuetifyjs/vuetify#10597] opened 2020-02-17 14:57 UTC
### Environment
**Vuetify Version:** 2.2.12
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.106
**OS:** Windows 10

### Steps to reproduce
Use a closable v-chip with @mdi/js as iconfont

### Expected Behavior
Icon to be aligned right like in vuetify 2.2.8
[CodeSandbox](https://codesandbox.io/s/vuetify-228-ch5sb?fontsize=14&hidenavigation=1&theme=dark)

### Actual Behavior
Icon is aligned false

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-2212-pnqyd?fontsize=14&hidenavigation=1&theme=dark" target="_blank">https://codesandbox.io/s/vuetify-2212-pnqyd?fontsize=14&hidenavigation=1&theme=dark</a>

**Comment by MatthiasDamm** [comment] 2020-02-18 10:34
Same here

**Comment by MatthiasDamm** [comment] 2020-02-18 10:34
The svg generated icon has width and height of 32

**Comment by KaelWD** [comment] 2020-02-18 10:47
Duplicate of #10480

**Closed by KaelWD** 2020-02-18 10:47 UTC
Labels: duplicate
