### ISSUE TITLE
[Bug Report] vue-tel-input-vuetify won't show duplicate iso2 countries in dropdown

### ISSUE THREAD

**Issue by mikeproofmarket** [vuetifyjs/vuetify#13390] opened 2021-04-07 13:25 UTC
### Environment
**Vuetify Version:** 2.2.32
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.114
**OS:** Windows 10

### Steps to reproduce
We want to add Canada to the list of "onlycountries" but it does not appear because it has the same +1 iso2 code as USA so it seems to be filtered out.

### Expected Behavior
We expect to see Canada and US in dropdown list

### Actual Behavior
Only the first one defined seems to appear

### Reproduction Link
<a href="https://codepen.io/gasha1/pen/BapwWzV?editors=0010" target="_blank">https://codepen.io/gasha1/pen/BapwWzV?editors=0010</a>

**Comment by jacekkarczmarczyk** [comment] 2021-04-07 13:28
Codepen shows empty screen and there are some errors in console
Also like to be duplicate of https://github.com/vuetifyjs/vuetify/issues/5378

**Comment by jacekkarczmarczyk** [comment] 2021-04-22 13:38
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

**Closed by jacekkarczmarczyk** 2021-04-22 13:38 UTC
Labels: S: needs reproduction, triage
