### ISSUE TITLE
[Bug Report] Datepicker rendering transparent box

### ISSUE THREAD

**Issue by MickaMx** [vuetifyjs/vuetify#7953] opened 2019-07-24 07:50 UTC
### Environment
**Vuetify Version:** 2.0.0
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
-Take the documentation exemple
-Remove the min-width="290px" props
-Click on the text field 

### Expected Behavior
no transparent box should appears

### Actual Behavior
a transparent box appears on the right side of the date picker

### Reproduction Link
<a href="https://codepen.io/Jarvot/pen/bXprjQ" target="_blank">https://codepen.io/Jarvot/pen/bXprjQ</a>

**Comment by jacekkarczmarczyk** [comment] 2019-07-26 22:56
Duplicate of https://github.com/vuetifyjs/vuetify/issues/780
I'll leave it open as a documentation issue, examples should use "auto" instead of "290px"

**Closed** 2021-01-07 16:02 UTC
Labels: T: documentation
