### ISSUE TITLE
[Feature Request] Flat v-stepper

### ISSUE THREAD

**Issue by xon52** [vuetifyjs/vuetify#9940] opened 2019-12-11 04:15 UTC
### Problem to solve
v-stepper currently has a default elevation that needs a work-around to remove.

### Proposed solution
Add a flat property which will remove this in the same way as v-card has a flat property.

**Comment by jacekkarczmarczyk** [comment] 2020-02-15 04:34
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4076

**Closed by jacekkarczmarczyk** 2020-02-15 04:34 UTC
Labels: C: VStepper, T: feature
