### ISSUE TITLE
[Feature Request] Simple information dialog API

### ISSUE THREAD

**Issue by CutePikachu** [vuetifyjs/vuetify#12048] opened 2020-08-13 04:15 UTC
### Problem to solve
Use javascript code to open a simple dialogue supporting info, success, warning and error styles like sweet alert(https://sweetalert.js.org/).  

### Proposed solution
Code here https://github.com/t4t5/sweetalert can be used as guidance.

**Comment by KaelWD** [comment] 2020-08-13 07:11
Duplicate of #3037

Not to say that it's entirely ruled out but it's not a feature we're currently pursuing.

**Closed by KaelWD** 2020-08-13 07:11 UTC
Labels: triage
