### ISSUE TITLE
Data table edit dialogs don't appear on empty cells

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#1795] opened 2017-09-18 11:39 UTC
### Steps to reproduce
 - Create a data table with a `v-edit-dialog` containing a text field
 - Click the cell
 - Delete all the text and dismiss the edit dialog
 - Try to open the edit dialog agian

### Versions
Vuetify 0.15.7

### What is expected ?
If a cell is empty the edit dialog activator should fill the entire thing. 

### What is actually happening ?
The dialog activator is only as wide as the text, so it ends up being 0px

### Reproduction Link
https://codepen.io/anon/pen/wrKymV?editors=1010

**Comment by jacekkarczmarczyk** [comment] 2017-09-18 11:53
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1282

**Comment by KaelWD** [comment] 2017-09-18 16:39
Ah thanks, I didn't see that one. I'll leave this open because I believe a sensible default is needed.

**Comment by Webifi** [comment] 2017-09-21 18:11
This really seems more like a bug than an "enhancement".

When the inline-editor's activator is based on the size of a text value then even a non-empty but short values, like "i", makes opening the inline editor very non-material-ui friendly.  It becomes an extremely small target to click or touch.   Then in the case of an empty value, the activator is simply gone.

IMHO, the entire cell should activate the inline editor by default.

**Comment by MiguelMora** [comment] 2018-02-13 10:43
I have not found more components using the small-dialog style, so I'm using this css code as a workaround
`
div.small-dialog {
    width: 100%
}
`

**Closed** 2018-04-17 11:25 UTC
Labels: bug
