### ISSUE TITLE
[Feature Request] Add Text Field-Style Highlighting in Select-with-Autocomplete

### ISSUE THREAD

**Issue by dwyer14** [vuetifyjs/vuetify#2390] opened 2017-10-31 20:16 UTC
### New Functionality
Tab into a V-Select (with autocomplete) and immediately start typing/overwriting, instead of having to select all, backspace/delete, and then type. 

To see the difference, visit https://vuetifyjs.com/components/text-fields#example-16 and enter a zipcode and country. Then tab back and forth between the two (zipcode being the V-Text-Field and country being the V-Select w/ autocomplete). Text fields are highlighted on focus, while Select fields are not.

### Improvements
Makes the behavior of text-like fields more consistent.

### Bugs or Edge Cases it Helps Avoid
Does away with the need for custom text-highlighting on focus.

**Comment by jacekkarczmarczyk** [comment] 2017-10-31 22:04
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2255

**Closed by jacekkarczmarczyk** 2017-10-31 22:04 UTC
Labels: duplicate
