### ISSUE TITLE
[Bug Report] active v-select options in scrollable container do not scroll with container 

### ISSUE THREAD

**Issue by Webifi** [vuetifyjs/vuetify#9484] opened 2019-10-27 20:39 UTC
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Windows 10

### Steps to reproduce
Click "Open Dialog" to open dialog.
Click "Select Something Else" to display select options
Use mouse wheel to scroll content in dialog.
Notice  select options do not scroll with dialog content.

### Expected Behavior
Select options should scroll with dialog content.

### Actual Behavior
Select options no not scroll with dialog content.

### Reproduction Link
<a href="https://codepen.io/webifi/pen/ExxXMrM?editors=1010" target="_blank">https://codepen.io/webifi/pen/ExxXMrM?editors=1010</a>

### Other comments
I tried attach="#a_dialog" (the id of the v-card in the dialog) on the v-select, but that just renders the select options at the top of the dialog content, not under the input as desired.

Perhaps a  :menu-props={attach: '#a_dialog'} would get the options rendered in the v-card div and position it off the v-select's input, but v-select doesn't seem to pass 'attach' from menu-props on to the menu.

**Comment by jacekkarczmarczyk** [comment] 2019-11-13 07:58
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5654
https://codepen.io/jkarczm/pen/yLLxxMx?editors=1010

**Closed by jacekkarczmarczyk** 2019-11-13 07:58 UTC
Labels: triage
