### ISSUE TITLE
[Bug Report] VDivider styles are broken after update to 1.1.5

### ISSUE THREAD

**Issue by DotNetGit** [vuetifyjs/vuetify#4645] opened 2018-07-18 00:18 UTC
### Versions and Environment
**Vuetify:** 1.1.5
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
1. Update Vuetify to 1.1.5;
2. Check example from https://vuetifyjs.com/ru/components/buttons from "In toolbar" section or try the same code in codepen;

### Expected Behavior
Check here https://codepen.io/anon/pen/yqJppN?&editors=101

### Actual Behavior
Follow the link https://codepen.io/anon/pen/BPzJwM?&editors=101

### Reproduction Link
[https://codepen.io/anon/pen/BPzJwM?&editors=101](https://codepen.io/anon/pen/BPzJwM?&editors=101)

**Comment by KaelWD** [comment] 2018-07-18 03:08
Duplicate of #4641

**Closed by KaelWD** 2018-07-18 03:08 UTC
