### ISSUE TITLE
[Bug Report] v-tabs & v-data-table & responsive & event when drag and drop & priority

### ISSUE THREAD

**Issue by tfossoul** [vuetifyjs/vuetify#7217] opened 2019-05-15 09:28 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Google Chrome
**OS:** Android

### Steps to reproduce
Create a vuetify project with a v-tabs with 3 panels.
On the first panel, create a v-data-table with several columns.
In a xs responsive windows try to drag and drop the v-data-table to see the columns that are on the right.

You will see that the v-tabs event is triggered and the page move to the second panel

### Expected Behavior
when you drag and drop in a v-data-table which is inside a v-tabs, the v-tabs event shoudn't be triggered.
We should have a priority.

### Actual Behavior
You will see that the v-tabs event is triggered and the page move to the second panel

### Reproduction Link
<a href="https://codepen.io/anon/pen/dENemM#anon-login" target="_blank">https://codepen.io/anon/pen/dENemM#anon-login</a>

**Comment by KaelWD** [comment] 2019-05-15 10:12
Duplicate of #2335

**Closed by KaelWD** 2019-05-15 10:12 UTC
Labels: triage
