### ISSUE TITLE
[Bug Report] v-list-group does not use $scopedSlots

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#9281] opened 2019-10-08 12:29 UTC
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
The `append-icon` and `prepend-icon` slots on `v-list-group` does not support the `v-slot` syntax.
If you change to `slot="prependIcon"` it works, but this syntax has been deprecated.

### Expected Behavior
It should be possible to bind the slots using modern Vue v-slot binding.

### Actual Behavior
Slots does not work with current syntax.

### Reproduction Link
<a href="https://codepen.io/sindrepm/pen/gOObqLV" target="_blank">https://codepen.io/sindrepm/pen/gOObqLV</a>

### Other comments
Most likely this happens because `$slots` is used instead of `$scopedSlots` in https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VList/VListGroup.ts#L128.

The same problem may apply to other components as well.

**Comment by MajesticPotatoe** [comment] 2019-10-08 12:53
duplicate of #8676

**Closed by MajesticPotatoe** 2019-10-08 12:53 UTC
Labels: triage
