### ISSUE TITLE
[Bug Report][3.4.11] VForm validation not working if input has dynamic name property

### ISSUE THREAD

**Issue by bbraun92** [vuetifyjs/vuetify#19084] opened 2024-01-22 12:37 UTC
### Environment
**Vuetify Version:** 3.4.11
**Last working version:** 2.7.1
**Vue Version:** 3.4.15
**Browsers:** Firefox 121.0
**OS:** Mac OS 10.15

### Steps to reproduce
- Create a v-form, two way bind a boolean to it
- Nest a v-text-field within, bind a dynamically generated string to its name property

### Expected Behavior
v-form keeps valid up to date

### Actual Behavior
valid is never updated

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNplULtugzAU/ZVbL4DamEZpWikikbp16dIOHUIGFwyx5AeyDaqE+PdecFKIOtn33GOfx7Enzhbpa9PQruVkRzLPVSOZ54dcA2TdijXNdJ2GwmjPhOb2Ak1gZayCbqVMyeU+Jx2ToszJH2PieP7jV5XgspxhgJ1miuOTmvsPpkujPr0Vuo6TnNzQbCu5Q94xxs8T2B8ATyq5rv0ZDvB4uuXPXipjlqulp3Rpao6D8JgHgSvU96OaKGEYLj0g57aIEQk9ZemiPxxdYUXjwXHfhhqFaoz10IPlFQxQWaMgwuqjIIj/Og9oG/YjI46iZIaDjbComHQcd+O2anXhhdHwr0fog2WL+lZD/M78mdqJgst7WCfUmwt585xQ1367ML1Muph4lleuvrp641Ia+DJWlnejwywNQTEiGR7Ihj7R9ZaMly1dk9MveR++AQ==)

**Comment by KaelWD** [comment] 2024-01-23 03:30
Duplicate of #18759

**Closed by KaelWD** 2024-01-23 03:30 UTC
Labels: S: triage
