### ISSUE TITLE
[Feature Request] Add Property to Dialog to allow destruction of dialog contents after dialog is closed

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#7939] opened 2019-07-23 17:59 UTC
### Problem to solve
When a dialog is activated, the contents of it's slot is created and persists until it is forcibly unloaded by v-if or when parent of v-dialog is destroyed.

However, depending on what the dialog is being used for there can be a need for the contents of the dialog to be completely destroyed after it's closed. However if we try to forcibly dialog contents when it's closed, it wrecks the closing animation and creates a jarring experience. Thus to prevent this, the dialog has to be destroyed on a delay in order to prevent breakage of the closing animation.

### Use case for this feature

A dialog is used to add users to the recipients of an email. When users are selected and added to the recipient list, the users should be removed from the selection UI in the dialog as they have already been added.

However the dialog contents gets the user list data upon creation. We could perform a getUsers request to the server after we click the apply button but that could amount to unnecessary requests to the server. Instead the preferred solution is to get a new list of users every time the dialog is opened. The easiest way to do this is to destroy the selection UI and component after the dialog is closed and create the dialog contents fresh every time its opened.

### Proposed solution
Add a property to the v-dialog API which will allow for the dialog to destroy its contents after it's closed.

**Comment by jacekkarczmarczyk** [comment] 2019-07-23 19:01
Related:
https://github.com/vuetifyjs/vuetify/issues/1687
https://github.com/vuetifyjs/vuetify/issues/4502
https://github.com/vuetifyjs/vuetify/pull/4518

**Comment by KaelWD** [comment] 2019-08-07 10:03
Duplicate of #6764

**Closed by KaelWD** 2019-08-07 10:03 UTC
Labels: T: feature
