### ISSUE TITLE
[Bug Report] Form Validation:  Cannot read property '$vnode' of null'

### ISSUE THREAD

**Issue by jvbianchi** [vuetifyjs/vuetify#5819] opened 2018-12-05 14:23 UTC
### Versions and Environment
**Vuetify:** 1.3.12
**Vue:** 2.5.18-beta.0
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
Leave the fields blank and click on submit twice

### Expected Behavior
No error

### Actual Behavior
Only happens with Vue version 2.5.18-beta.0
A error is thrown: 
```
"[Vue warn]: Error in nextTick: 'TypeError: Cannot read property '$vnode' of null'"
```
![image](https://user-images.githubusercontent.com/13983663/49519577-75c6be80-f888-11e8-841f-e73748de7400.png)

### Reproduction Link
<a href="https://codepen.io/anon/pen/RqzPMx?editors=1011" target="_blank">https://codepen.io/anon/pen/RqzPMx?editors=1011</a>

**Comment by jvbianchi** [comment] 2018-12-05 14:37
might be related with this commit in the vue repository: https://github.com/vuejs/vue/commit/f43ce3a5d8f73e273f2d03c9d86ea5662cda481a
![image](https://user-images.githubusercontent.com/13983663/49520476-7d876280-f88a-11e8-93da-da414de8d2b5.png)

**Comment by KaelWD** [comment] 2018-12-05 14:54
Duplicate of https://github.com/vuejs/vue/issues/9149

**Comment by jacekkarczmarczyk** [comment] 2018-12-05 15:33
Reopening until we'll find the minimal reproduction, atm it's https://codepen.io/anon/pen/wQLGdx?editors=1010

**Comment by jvbianchi** [comment] 2018-12-05 20:04
Duplicate of vuejs/vue#9151

**Closed** 2018-12-06 10:54 UTC
Labels: upstream
