### ISSUE TITLE
[Feature Request] Carousel prev and next icon background

### ISSUE THREAD

**Issue by lucaros97** [vuetifyjs/vuetify#8072] opened 2019-07-26 19:02 UTC
### Problem to solve
Change background of prev and next icons in Carousel.In the v1.5 when light theme applied icons where shown as "flat" without background.  

v1.5
<img width="102" alt="Schermata 2019-07-26 alle 20 58 27" src="https://user-images.githubusercontent.com/8333004/61975121-96df4980-afe8-11e9-8f46-98411f623e94.png">

v2.0
<img width="109" alt="Schermata 2019-07-26 alle 20 58 42" src="https://user-images.githubusercontent.com/8333004/61975131-9d6dc100-afe8-11e9-877a-0c320b8f6ebf.png">

### Proposed solution
Add a props to v-carousel for setting arrows background

**Comment by jacekkarczmarczyk** [comment] 2019-07-26 19:05
That looks like regression

**Comment by nekosaur** [comment] 2019-08-09 17:32
Fixed in https://github.com/vuetifyjs/vuetify/pull/8122

**Closed by nekosaur** 2019-08-09 17:32 UTC
Labels: C: VCarousel, T: regression
