### ISSUE TITLE
[Bug Report] v-datatable checkbox selection is slow when there is large data rendered

### ISSUE THREAD

**Issue by kanteankit** [vuetifyjs/vuetify#5986] opened 2018-12-27 06:08 UTC
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.5.17
**Browsers:** Chrome 71.0.3578.98
**OS:** Linux x86_64

### Steps to reproduce
In the given codepen, select a row in the table. 
You'll notice a lag in the selection of the checkbox. The number of rows is around 1800. It looks like the lag is due to the ripple on the checkbox,but, I may be wrong here.
My use case required a different background-color for the selected rows. The lag is prominently visible if we use a different background color for the `active` rows

### Expected Behavior
The checkbox should be selected without any lag for large datasets also.

### Actual Behavior
Checkbox in data-table gets selected after a certain lag

### Reproduction Link
<a href="https://codepen.io/anon/pen/oJeBjJ" target="_blank">https://codepen.io/anon/pen/oJeBjJ</a>

**Comment by KaelWD** [comment] 2018-12-27 12:02
Duplicate of #2574

**Closed by KaelWD** 2018-12-27 12:02 UTC

**Comment by kanteankit** [comment] 2018-12-27 12:49
@KaelWD 
On #2574, you mentioned that with 500 rows there is no issue. I updated your codepen with latest Vuetify and renderd 1800 rows. The checkbox gets selected after a lag.
Codepen: https://codepen.io/anon/pen/KbvQKj?editors=1111
Can you please let me know if this is still related to vuejs/vue#6351 or is it something that vuetify needs to fixed.

**Comment by KaelWD** [comment] 2018-12-28 03:43
#2574 was complaining about a **serious** performance problem with 150, I demonstrated a **minor** problem with 500. This is a problem with vue and complex components, the only way we could fix it is to remove features.

**Comment by timothymarois** [comment] 2019-06-20 04:53
Seeing this issue here. Incredibly taxing on the system trying to select all on large data sets. Once selecting all, trying to unselect just one takes a good few minutes. Need a resolution to this.

**Comment by iurisilvio** [comment] 2020-02-10 14:54
We had this issue with a huge table, with vuetify 1.5 and vuetify 2 (different projects). For a large number of rows it is almost unusable, because it rerender everything for every action on the table. @lrosemberg investigated and found the problem and a solution.

For vuetify 2, your custom slots should be components instead of inline templates.

I changed the vuetify datatable example to validate the issue and the solution.

Original code:

 * https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/data-tables/simple/select.vue
 * https://vuetifyjs.com/pt-BR/components/data-tables#selectable-rows

Fixed example (check console logs to understand): https://codepen.io/iurisilvio/pen/XWbbKOP

For vuetify 1.5 we have a solution too, but because you don't have the `show-select` directive, it is tricky to make checkbox work without this behaviour.

**Comment by Roman86** [comment] 2022-08-04 10:28
in short: don't call any functions inside of table cell slots - in this case they would be called on each selection change. Instead, put your function calls deeper - inside components, or outside of table (memoizing call results in data object).
Thanks @iurisilvio for the fixed example

**Comment by eric-gonzalez-tfs** [comment] 2023-01-17 18:10
> We had this issue with a huge table, with vuetify 1.5 and vuetify 2 (different projects). For a large number of rows it is almost unusable, because it rerender everything for every action on the table. @lrosemberg investigated and found the problem and a solution.
> 
> For vuetify 2, your custom slots should be components instead of inline templates.
> 
> I changed the vuetify datatable example to validate the issue and the solution.
> 
> Original code:
> 
> * https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/data-tables/simple/select.vue
> * https://vuetifyjs.com/pt-BR/components/data-tables#selectable-rows
> 
> Fixed example (check console logs to understand): https://codepen.io/iurisilvio/pen/XWbbKOP
> 
> For vuetify 1.5 we have a solution too, but because you don't have the `show-select` directive, it is tricky to make checkbox work without this behaviour.

Thanks for the insight here @iurisilvio.

Was facing the same issue with the `v-treeview` component that had a large amount of `v-checkbox`es. Seperating it into it's own component did the trick.
