### ISSUE TITLE
[Feature Request] Mobile breakpoint classes props

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5609] opened 2018-11-14 10:46 UTC
### Problem to solve
In project, I had to define different breakpoint for mobile and desktop. In mobile case the class would be for sm, and for desktop smAndUp. 

Now this can be done with doing command: 
`<div :class="$vuetify.breakpoint.smAndUp ? 'class1' : 'class2'">`

However this might be confusing. Especially if you have different classes for: desktop, laptop, mobile, tablet, etc...

### Proposed solution
Maybe it would be easier to define individual prop for mobile and maybe desktop to differentiate this: 

```
<div 
class="classForAll"
mobile="classForXsOnly"
desktop="classForMdAndUp"
laptop="classForMdOnly"
tablet="classForSmOnly">
```

**Comment by MajesticPotatoe** [comment] 2018-11-14 16:21
Seems like a duplicate of #2928
as jacek mentions in the post, follow these PRs: #4705 and #4675

**Comment by johnleider** [comment] 2019-01-23 15:47
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2019-01-23 15:47 UTC
