### ISSUE TITLE
[Bug Report][3.4.0] VDataTable uses an invalid rowspan.

### ISSUE THREAD

**Issue by damyo** [vuetifyjs/vuetify#18786] opened 2023-11-28 08:05 UTC
### Environment
**Vuetify Version:** 3.4.0
**Vue Version:** 3.3.4
**Browsers:** Chrome 119.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Define multiple headers (10 or more).
2. Set up nested headers using children in the objects in headers.
3. Place a mix of those with and without children.

Since we didn't use children inside children, headers should end up containing two rows.
However, there is an unknown third row.

My guess is that it has something to do with the priorityQueue in the composables/headers file.
```js
if (item.priority > priority) {
  queue.splice(i, 0, {
    element,
    priority
  });
  added = true;
  break;
}
```
I could be wrong, but I believe this is what is causing the rows to be added.

### Expected Behavior
A header consisting of two rows should be rendered.

### Actual Behavior
A header with three rows is rendered.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtlluO2jAUhrdylBcGCUJIIFzEIBVmNJXaSlUr9WWYB09yIFFzk+OgoQipe+hSuoMupSupHRJwIlJxqdR54CnJ//s35zt2cB7XSkyt1psoUpcJKkNlxNCPPMJwPAsARsumTRhpMvLsoRAAhg4SG2l8O1Oyu5mSOS7PCj295qp4aH7FFdcD4qMsx80IaTMiC+Rmd+uMRy35N3kVo5ZUEn+MLepGLC0PX6KQMrBxThKPwXo7tUgP4aYOt2O4yTSArNghPOYKwBqYyzwcQu3jihLftWsNWBIvEYootgabxqHR70OLMDcMpOFeLlVEpmEQM5pYYgzccRgpa0lealXMcVSR+1vYBe9cH4OYzx7XpKEAxHMXgSgAA4a06FmO69kUuS01rFjPW3QXDoMbvy6V5KRisahibEJiLIWeufS3yJfQS3wR+vVTji1TuRx8kp6urakMnlBiZUfPfH+uG/m/rNa1o/9oI7/+Rl68XfaqjXGMlJVOTnkG0SE+/QNFwiBrIIRzeHC/kSJwfkry0feLVcSK7rY+7rU7pmoWPbENuKMbmtopOtuVFl63b+j9bqnFpbNVrIQKfKj2+/sPvWtqMJnKicp1ziAlvHcOmVN+jp8DaJhljByw3VWNCsB2p9frHAvYO5XsE9r54p3HpFUQ6VoVj6np/cGRPINTeSb8hbsQqK22DyK1+/3y/txD6ZpmDkrIFVCmdsH2Yw7C54R/g1agfcAX1wor2MxS13drVdIlLKOnDXpHYXGq6f1hqvxvZVNPbzbi8373Qa9sGoqhGupAEdeOaihPfwAQRmRe)

**Comment by KaelWD** [comment] 2023-11-28 08:25
Duplicate of #18679

**Closed by KaelWD** 2023-11-28 08:25 UTC
Labels: S: triage
