### ISSUE TITLE
[Bug Report][3.0.0-beta.0] Vuetify Automcomplete for Grouped list items not working

### ISSUE THREAD

**Issue by SukhvirKM** [vuetifyjs/vuetify#15007] opened 2022-04-27 10:12 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.13
**Browsers:** Chrome 100.0.4896.127
**OS:** Mac OS 10.15.7

### Steps to reproduce
https://next.vuetifyjs.com/en/components/autocompletes/

Check on Slots : Item and Selection
The Selectbox with people group is empty

### Expected Behavior
List should be with people name and avatar

### Actual Behavior
List is empty

### Reproduction Link
<a href="https://codesandbox.io/s/vibrant-wildflower-t8b5l5?file=/plugins/vuetify.js" target="_blank">https://codesandbox.io/s/vibrant-wildflower-t8b5l5?file=/plugins/vuetify.js</a>

**Comment by KaelWD** [comment] 2022-06-16 15:43
Duplicate of #15280

**Closed by KaelWD** 2022-06-16 15:43 UTC
Labels: S: triage
