### ISSUE TITLE
[Bug Report] Button is not showing when disabled and dark theme is enabled

### ISSUE THREAD

**Issue by singleparadox** [vuetifyjs/vuetify#10724] opened 2020-03-03 01:12 UTC
### Environment
**Vuetify Version:** 2.1.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 80.0.3987.122
**OS:** Windows 10

### Steps to reproduce
1. Use the v-btn component
2. Set disabled as button property
3. Set dark as button property

### Expected Behavior
Button should not be clickable but shown

### Actual Behavior
Button is hidden

### Reproduction Link
<a href="https://codepen.io/null/pen/ExjvVLb" target="_blank">https://codepen.io/null/pen/ExjvVLb</a>

**Comment by singleparadox** [comment] 2020-03-03 01:16
My current workaround is adding class="white--text".

**Comment by jacekkarczmarczyk** [comment] 2020-03-03 04:23
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4482

**Closed by jacekkarczmarczyk** 2020-03-03 04:23 UTC
Labels: triage

**Comment by Steve-Mcl** [comment] 2020-03-16 22:47
@jacekkarczmarczyk  I'm curious as to why this issue has been closed & marked as a duplicate to an issue that was closed September 2018. The problem occurs for me too (dark + disabled == hidden)

An I missing something?

**Comment by jacekkarczmarczyk** [comment] 2020-03-17 02:07
You just shouldn't use dark on disabled buttons if not on dark background (and light if not on light background):
https://codepen.io/jkarczm/pen/GRJdPBO
