### ISSUE TITLE
[Bug Report][3.0.0-beta.5] Combobox v-model data binding does not work like expected

### ISSUE THREAD

**Issue by anne-schwarz-osp** [vuetifyjs/vuetify#15418] opened 2022-07-11 14:59 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.36
**Browsers:** Chrome 103.0.0.0
**OS:** Windows 10

#### Steps to reproduce
1. Click into the `v-combobox`
2. Enter some chars

#### Expected Behavior
- The predefined string is visible inside the `v-combobox`
- The textcursor is at the end of the string
- Entering chars extends the string

#### Actual Behavior
- The combobox seems to be empty
- Entering chars overwrites the whole predefined string

#### Steps to reproduce
1. Click at the appended close icon to delete the string
2. Click into the `v-combobox`
3. Enter some chars

#### Expected Behavior
- The combobox is empty
- I can enter a new string
- Only the new string is stored in the v-model variable

#### Actual Behavior
- The value entered before resetting it is displayed again
- Entering chars extends the string

### Reproduction Link
<a href="https://codepen.io/anne-schwarz-osp/pen/mdxEKmy?editors=1010" target="_blank">https://codepen.io/anne-schwarz-osp/pen/mdxEKmy?editors=1010</a>

### Other comments
I assumed that the combo box behaves like a v-text-field but with bonus functionality. The text field itself works pretty fine and I can reset the value passed to it. But for the combo box the connection to `v-model` seems to not work correctly.

**Comment by KaelWD** [comment] 2022-08-08 17:05
Duplicate of #15151

**Closed** 2022-10-18 15:25 UTC
Labels: T: bug, C: VCombobox
