### ISSUE TITLE
[Bug Report] Scrollable Dialog scrollbar appears on top of element in RTL

### ISSUE THREAD

**Issue by ekleel** [vuetifyjs/vuetify#7146] opened 2019-05-07 05:45 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.6
**Browsers:** Chrome 74.0.3729.131
**OS:** Mac OS 10.14.4

### Steps to reproduce
The bug appears to be limited to Chrome (Chrome 74.0.3729.131) and Chrome in Android. I've provided a Codepen that shows the scrollbar in the scrollable dialog component on top of the element that it's scrolling in RTL direction. Just set the css direction to RTL on the html tag.
```
html {
  direction: rtl;
}
```

### Expected Behavior
The scrollbar should be fixed to the left side of the element that it's scrolling through.

### Actual Behavior
The scrollbar appears on top of the element that it's scrolling through. You can see the scrollbar here:
https://imgur.com/XcVBhhs

### Reproduction Link
<a href="https://codepen.io/ekleel/pen/Jqowpq" target="_blank">https://codepen.io/ekleel/pen/Jqowpq</a>

### Other comments
It might also be important to note that the scrollbar is completely hidden in the LTR direction in Chrome. I'm not sure if that is the desired results but I though I mention it.

**Comment by jacksarle** [comment] 2019-05-07 16:49
Vuetify: 1.5.11
Vue: 2.6.10
Browsers: Chrome 76.0.3783.0
OS: Windows 10

With the above setup this works as you describe in the expected behavior. So it seems to potentially be a Mac OS problem.

**Comment by ekleel** [comment] 2019-05-07 17:06
I'm not sure. Because I've tested Safari and Firefox and both work as expected. But in Chrome it doesn't. I've also tried Chrome in Android and the issue is there too. See the image below followed by device specs.

https://imgur.com/a/AxsGkxP

Browsers: Chrome 74.0.3729.136
OS: Android 9
Device: Google Pixel 2

**Comment by ibrahimBeladi** [comment] 2019-05-07 22:06
This should be invalid, because the way of switching to RTL is by using `$vuetify.rtl = true`
Use this change and if the bug persists, update this issue.

**Comment by ekleel** [comment] 2019-05-08 00:54
I've tried that but I don't think it's related to the issue because everything else works as expected in RTL mode. I usually use this to enable RTL mode:
```
Vue.use(Vuetify, {
  rtl: true
})
```

**Comment by KaelWD** [comment] 2019-05-08 04:34
Browser bug, I don't think we can do anything about this one. 
It's even worse on my phone:
![Screenshot_2019-05-08-14-33-34-720_com android chrome](https://user-images.githubusercontent.com/16421948/57349695-6c76b080-719e-11e9-8dd5-2596d980bdba.png)

**Comment by KaelWD** [comment] 2019-07-20 08:56
Seems to be fixed in chrome 75.

**Closed by KaelWD** 2019-07-20 08:56 UTC
Labels: T: bug, help wanted, platform specific
