### ISSUE TITLE
problem with rendering icons

### ISSUE THREAD

**Issue by OkaSroka** [vuetifyjs/vuetify#5219] opened 2018-10-04 14:27 UTC
Hi all,
a have serious issue with loading icons,
![zrzut ekranu 2018-10-04 o 07 20 06](https://user-images.githubusercontent.com/23402645/46480444-212e9680-c7a6-11e8-975d-ada54bfce83a.jpg)
![zrzut ekranu 2018-10-04 o 07 20 38](https://user-images.githubusercontent.com/23402645/46480460-255ab400-c7a6-11e8-86cc-452cce1c7f71.jpg)
![zrzut ekranu 2018-10-04 o 07 20 16](https://user-images.githubusercontent.com/23402645/46480465-2855a480-c7a6-11e8-9051-438990874b17.jpg)
![zrzut ekranu 2018-10-04 o 07 20 46](https://user-images.githubusercontent.com/23402645/46480467-2a1f6800-c7a6-11e8-8ba3-b76a20fe0bd3.jpg)
as you see from the pictures during loading page I have very ugly text at the beginning, then after couple seconds or minutes ( it depends from internet connection ) icons are rendered properly
How can I hide this text during loading?
any ideas?
I tried to load this font earlier (before content is mounted) but this solution does not work.
Even set timeout does not work
at the beginning I had text and then icons.

Any ideas why??

**Comment by KaelWD** [comment] 2018-10-04 16:13
Duplicate of google/material-design-icons#158

Either use a font loader, or switch to a different non-ligature icon front such as MDI or FA5

**Closed by KaelWD** 2018-10-04 16:13 UTC

**Comment by OkaSroka** [comment] 2018-10-08 07:05
I use ready component, so how can I change that icons to non-ligature icon front? font loader does not work here. The issues still exists.

**Comment by OkaSroka** [comment] 2018-10-08 09:05
ok i will try this: https://vuetifyjs.com/en/framework/icons
maybe different icons will help
thx

**Comment by OkaSroka** [comment] 2018-10-09 06:17
Changing to another library does not help at all. Instead of text you get squares (Font awesome).
What you have to do- change font to base64 - on mac it works great (they are loaded even earlier), and on windows you have to additionally do that:
set in css for icons opacity to 0.01, and width for example to 24px
then in App.vue (your main component) on update use setTimeout and change this style to opacity: 1 and width for example - unset
