### ISSUE TITLE
[Bug Report] VTextField Border is not aligned correctly with outlined and reverse prop in browser mozilla firefox

### ISSUE THREAD

**Issue by nekochan7** [vuetifyjs/vuetify#10798] opened 2020-03-10 02:37 UTC
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.10
**Browsers:** Mozilla Firefox
**OS:** Windows

### Steps to reproduce
create vtextfield with prop outlined and reverse. Aligned only correctly in chrome browser but in other browser ex. mozilla firefox legend not aligned correctly. like in the screenshot that I attached in comment.

### Expected Behavior
label and legend should be in right position in mozilla firefox

### Actual Behavior
only label in right position and legend still in left in mozilla firefox

### Reproduction Link
<a href="https://codepen.io/neko-chan/pen/xxGpYPm" target="_blank">https://codepen.io/neko-chan/pen/xxGpYPm</a>

**Comment by li-liez** [comment] 2020-03-10 02:39
![bug-vuetify-2 2 15](https://user-images.githubusercontent.com/14250248/76274335-f7d73b80-62b2-11ea-9601-f2cf4a050bd2.png)

**Comment by jacekkarczmarczyk** [comment] 2020-03-10 02:51
> ### Expected Behavior
> label and legend should be in right position

![image](https://user-images.githubusercontent.com/15625235/76274986-b6e02680-62b4-11ea-9e0b-2cafe758ac2d.png)

You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. Please open a new issue with the missing information.

Thank you for your contribution and interest in improving Vuetify. If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Comment by li-liez** [comment] 2020-03-10 03:38
@jacekkarczmarczyk I'am sorry for missing information, label and legend just correctly in CHROME browser. but in other browser ex. mozilla firefox legend not aligned correctly. like in the screenshot that I attached in comment.

**Comment by jacekkarczmarczyk** [comment] 2020-03-10 03:41
Sorry, but a screenshot is not a valid reproduction, please create a minimal codepen/codesandbox/github repo that reproduces the issue

**Comment by li-liez** [comment] 2020-03-10 03:45
@jacekkarczmarczyk this is my codepen https://codepen.io/neko-chan/pen/xxGpYPm. it is correctly on chrome but not in mozilla firefox.

**Comment by jacekkarczmarczyk** [comment] 2020-03-10 03:46
Sorry, missed information about Firefox

**Comment by tronolives** [comment] 2020-03-11 03:48
@jacekkarczmarczyk or anyone interested, I believe I have a fix for this, but I'm fairly new and would appreciate advice.
Replacing VTextField.sass:418 `text-align: right` with `margin-inline-start: auto` does the trick on Chrome, Firefox, and Safari and some initial smoke testing shows that it works fine.

Can you think of a reason why this would not be a sufficient fix? If not, do you have any suggestions for further testing? ( I can't test Windows/Edge)
Thanks :^)

**Comment by fpdrozd** [comment] 2020-03-11 08:58
@tronolives It does not work in Edge for me. But I tried `margin-left: auto` instead and it works fine as well (in Edge too).

Still don't know if it's a sufficient fix.

**Comment by li-liez** [comment] 2020-03-13 04:39
for now, add this line stylesheet code in the App.vue 

.v-application--is-ltr .v-text-field--outlined.v-text-field--reverse legend {
    margin-inline-start: auto !important;
    margin-left: auto !important;
  }

**Comment by KaelWD** [comment] 2021-02-03 15:15
Don't close issues just because you've found a workaround, it's still a bug.

**Comment by dchinu97** [comment] 2021-02-03 15:42
@KaelWD Can please you assign this to me?

**Comment by KaelWD** [comment] 2021-02-04 05:55
Duplicate of #10277

**Comment by dchinu97** [comment] 2021-02-04 05:58
@KaelWD Can you please review this PR 🙂?

**Closed** 2021-02-05 12:46 UTC
Labels: C: VTextField, T: bug, platform specific
