### ISSUE TITLE
[Bug Report] Jest & localVue – cannot run more than one test case

### ISSUE THREAD

**Issue by iwyg** [vuetifyjs/vuetify#9915] opened 2019-12-09 09:53 UTC
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. create a component which utilises vuetify components. e.g.

```vue
<template>
<div>
  <v-container>
    <v-btn>{{name}}</v-btn>
  </v-container>
</div>
</template>
<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  props: {
    name: {
      type: String as () => string,
      default: () => 'foo'
    }
  }
});
</script>
```

2. create a spec for said component using jest + testcase:

```ts
import { createLocalVue, mount } from '@vue/test-utils';
import HelloWorld from '@/components/Foo.vue';
import { VueConstructor } from 'vue';
import Vuetify from 'vuetify';

describe('Foo.vue', () => {
  let localVue: VueConstructor
  beforeEach(() => {
    localVue = createLocalVue();
    localVue.use(Vuetify);
  });

  it('testA', () => {
    const name = 'bar';
    const wrapper = mount(HelloWorld, {
      localVue,
      propsData: { name },
    });
    expect(wrapper.find('.v-btn').text()).toMatch(name);
  });

  it('testB', () => {
    const name = 'bar';
    const wrapper = mount(HelloWorld, {
      localVue,
      propsData: { name },
    });
    expect(wrapper.find('.v-btn').text()).toMatch(name);
  });
});
```

3. run spec, e.g. yarn test:unit

### Expected Behavior
Tests should pass

### Actual Behavior
Running test cases individually will result in each test case passing.
Running the whole spec, or more test cases at once will result in this error:

```bash
Foo.vue
    ✓ testA (91ms)
    ✕ testB (7ms)

  ● Foo.vue › testB

    [vue-test-utils]: find did not return .v-btn, cannot call text() on empty Wrapper

      26 |       propsData: { name },
      27 |     });
    > 28 |     expect(wrapper.find('.v-btn').text()).toMatch(name);
         |                                   ^
      29 |   });
      30 | });
      31 |

      at throwError (node_modules/@vue/test-utils/dist/vue-test-utils.js:1417:9)
      at ErrorWrapper.text (node_modules/@vue/test-utils/dist/vue-test-utils.js:2216:3)
      at Object.it (tests/unit/example.spec.ts:28:35)

  console.error node_modules/vuetify/dist/vuetify.js:36680
    [Vuetify] Multiple instances of Vue detected
    See https://github.com/vuetifyjs/vuetify/issues/4068

    If you're seeing "$attrs is readonly", it's caused by this

  console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
    [Vue warn]: Unknown custom element: <v-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

    found in

    ---> <Anonymous>
           <Root>

  console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
    [Vue warn]: Unknown custom element: <v-btn> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

    found in

    ---> <Anonymous>
           <Root>
```

### Reproduction Link
<a href="https://codesandbox.io/s/github/iwyg/vue-jest-issues" target="_blank">https://codesandbox.io/s/github/iwyg/vue-jest-issues</a>

**Comment by KaelWD** [comment] 2019-12-09 10:05
Duplicate of #4964

**Closed by KaelWD** 2019-12-09 10:05 UTC
Labels: triage
