### ISSUE TITLE
[Bug Report][3.6.12] VCalendar event slot doesn't work

### ISSUE THREAD

**Issue by buddy94** [vuetifyjs/vuetify#20153] opened 2024-07-12 13:54 UTC
### Environment
**Vuetify Version:** 3.6.12
**Vue Version:** 3.4.31
**Browsers:** Chrome 126.0.0.0
**OS:** Windows 10

### Steps to reproduce
Just try the  <template #event="{ event, day }"> in the calendar! Doesn't do anything.

In comparison <template #header="{ title }"> works fine

### Expected Behavior
With the event slot you can customize the event as you wish

### Actual Behavior
Doesn't do anything

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNlGFrglAUhv/KwX1wQS01g01qMNhi3xcMln1weipJr3K9GkP87ztetVZmEyLvfXl5z3PP9bjKlYS745c4fshSVCxlJjCMA0fgs80AZtnIiWO5lBs3YsLxGfJaqkQnQOY5HLJRGHkYzG0lTLa2ApmPBymRckDck2RhhkwkJFQLWzkm1XlNfbjboeMhJ2sOwhcBQtFyv0sLCEzERcz47BytbFldRsvVEDznR+bDW7mXiddCZuPTeZu2lNJZX0qlattZAm0Tl/uxgARFWnXVD+OIC8iB4wYK2PAoBJVuQi3tAJRLHFWrYA6rqmLe0Mi2WKAufJ4IddjIiXC4sIDhAV6p9L1qaIY50vSRYSw1w9I0+n2pg6OfTtPlNq3JpduNgohT0e+AMGu1qJ8tsg+kI3h90CZLbdou1oVG7sduNI7Hkp1ky53P+4JdKXUD7KkbbMsR2b9oiyjlYteHzZT3qfdkI7fZdneyddB9Rnzvs20/PH3S/3Uj97TtvtG69d8hoU8OTQiN0f3q6rXop1d5PSgns5pFmkKlGLI0COTf+hf0O2vV)

**Comment by blalan05** [comment] 2024-07-13 03:18
Duplicate of #19020

**Closed by blalan05** 2024-07-13 03:18 UTC
Labels: S: triage
