### ISSUE TITLE
[Bug Report] Clickable cards change color permanently after right clicking when holding left click or vice versa

### ISSUE THREAD

**Issue by nishanksisodiya** [vuetifyjs/vuetify#11089] opened 2020-04-12 13:45 UTC
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163, Other
**OS:** Windows 10

### Steps to reproduce
1. Create a dark vue app and card make the card clickable with ```@click="'#'"``` and disable context menu (I'm doing it in electron which dont have context menu by default).

2. Then Right click on the card while holding left click or vice versa

3. Release both. oops! Card color didnt return to normal

if you do this multiple times card will evantually turn white making text unreadable

### Expected Behavior
Card return to original color after releasing click

### Actual Behavior
Card didnt return to original color after releasing click

### Reproduction Link
<a href="https://codepen.io/nony14/pen/KKdpzqm" target="_blank">https://codepen.io/nony14/pen/KKdpzqm</a>

**Comment by jacekkarczmarczyk** [comment] 2020-04-12 13:46
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4185

**Closed by jacekkarczmarczyk** 2020-04-12 13:46 UTC
Labels: triage
