### ISSUE TITLE
[Bug Report][3.1.2] Icon inside append-inner slot is being flipped (v-select, v-autocomplete)

### ISSUE THREAD

**Issue by BessetThomas** [vuetifyjs/vuetify#16506] opened 2023-01-24 08:26 UTC
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
Click on the `v-select` / `v-autocomplete`, the icon inside the slot is being flipped, like the select's arrow.

### Expected Behavior
Icon isn't flipped

### Actual Behavior
Icon is flipped

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtVDty2zAQvQoGjRqRnDhJw1E89hlSCioochMhxm+AJT0Zje6eBUAx/CQp4tZUIezb3befR/B45c/OlUMPvOYHBO1Ug/AoDGOHoWicS8dk6Eaa0crOHm1rKQEQhBGYf6o5g/oi+PPMy3SvUNJR8Hs+Y7WkaoEijztrYLdnO3y16c8D7E7z0Cl9QtqLdOFuTk2ND5n3bqaJ2FAEZbGmicB0hTQG/CKPBkJrY50V3ZaiRTk0aD31fmXOWxfYTfB1F5FRttZQ2lmajoJTqOAsomTqThYXUK5opW/jbh4PVU5Zd1AtdPn9KOtBM9pEr8vFLMSzHeYPNDFwLuPkmMkcQEGLW4G/Zvx/FH0X7C2CZUHu95KA6WImOdOVXaSSGVovHbIA2Gd3BujI91xqZz0SjSt/BGvoQ3CNbGJ00AZqlpCI0Zci2oJfEF2oq6o37uV7SW9Q9US+yvcGpYais/rpY/lQfvpcdTLgHC8h6OLs7WsATxUF38/IUX77+bcCo5t4P5QPmXaEIuWGqiL+AXzh6QUCD/6ffa9iF72vfJv+Y82bMDfapZLmJazW2Ia0wuMphtz2PFNTcJqDn34Bnim0qw==)

**Comment by KaelWD** [comment] 2023-05-15 08:20
Duplicate of #4447

**Closed by KaelWD** 2023-05-15 08:20 UTC
Labels: S: triage
