### ISSUE TITLE
[Bug Report][3.3.18]  [VSelect] hideDetails auto doesn't work anymore

### ISSUE THREAD

**Issue by Choupierre** [vuetifyjs/vuetify#18360] opened 2023-09-28 08:08 UTC
### Environment
**Vuetify Version:** 3.3.18
**Last working version:** 3.3.17
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Windows 10

### Steps to reproduce
Change the Vuetify version between 3.3.17 and 3.3.18 to see the problem.

### Expected Behavior
The details should hide if hideDetails is on auto and are empty

### Actual Behavior
The details appear if hideDetails is on auto and are empty

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkc8OgjAMxl+l6UVN+CPqwRA08TnEA4GqSxhbtsLF+O524MFwxNP2fW1/ab5eX+hdnV6sTYaeMMeCSdu2YjqXHUAxxJW143cUtem4Uh25rzWanlqqGYZYm4baU4naP0qEXAnKi7xuoyza3cR6qobihgTRhkLVsxE3XQbLZzR2PS2n/TlWpPNwgjNlV6Q/mYr0tVOWwRP3U7RKW+MYXuDoDm+4O6NhJedYhXYA4XoGWQFOoWOdbQJzosg8viPcJ/vkgNObHfH2AW6jkyg=)

**Comment by KaelWD** [comment] 2023-09-28 08:47
Duplicate of #18342

**Closed by KaelWD** 2023-09-28 08:47 UTC
Labels: S: triage
