### ISSUE TITLE
[Bug Report] Display bug on v-window on first change

### ISSUE THREAD

**Issue by ligne13** [vuetifyjs/vuetify#7244] opened 2019-05-20 07:57 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Mac OS 10.14.4

### Steps to reproduce
The first transition when switching from item 1 to another is buggy. The item is visible while moving upwards. 
Then it's OK.

### Expected Behavior
It should me masked.

### Actual Behavior
The mask does not work on first transition.

### Reproduction Link
<a href="https://codepen.io/ligne13/pen/rgzPVd" target="_blank">https://codepen.io/ligne13/pen/rgzPVd</a>

**Comment by KaelWD** [comment] 2019-05-20 08:00
Duplicate of #7102

**Closed by KaelWD** 2019-05-20 08:00 UTC
Labels: triage
