### ISSUE TITLE
[Bug Report][2.6.3] VTabs has unused space on the left on mobile when tabs are overflowing

### ISSUE THREAD

**Issue by gotson** [vuetifyjs/vuetify#14751] opened 2022-02-21 03:39 UTC
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 3.2.31
**Browsers:** Chrome 98.0.4758.102
**OS:** Mac OS 10.15.7

### Steps to reproduce
When tabs are overflowing, on desktop the arrows would show for navigation. The documentation says:

> For mobile devices, arrows will only display with the show-arrows prop.

When `show-arrows` is disabled on Mobile, empty space for the arrow is still shown on the left side of the tabs (but not on the right side).

If `show-arrows`

### Expected Behavior
left side of the items should not be used by empty space
<img width="393" alt="Screenshot 2022-02-21 at 11 34 34" src="https://user-images.githubusercontent.com/2139133/154885279-319606a4-7c39-4b79-b3b3-c106c9f5361d.png">

### Actual Behavior
left side of the items is used by empty space
<img width="390" alt="Screenshot 2022-02-21 at 11 31 07" src="https://user-images.githubusercontent.com/2139133/154885266-bb115b99-a47c-4b43-b276-9469b6f326c8.png">
<img width="388" alt="Screenshot 2022-02-21 at 11 32 07" src="https://user-images.githubusercontent.com/2139133/154885269-03686e38-d188-4666-a707-94921a86dc65.png">

### Reproduction Link
<a href="https://codepen.io/gotson/pen/dyZmQvw" target="_blank">https://codepen.io/gotson/pen/dyZmQvw</a>

**Comment by KaelWD** [comment] 2022-02-21 03:41
There is supposed to be padding there, but it shouldn't clip the tab contents when scrolled.

**Comment by gotson** [comment] 2022-02-21 03:45
> There is supposed to be padding there, but it shouldn't clip the tab contents when scrolled.

why should there be padding on mobile ? the screen is already small, it doesn't make sense to use that space to show nothing, especially since the space on the right doesn't have padding, no?

**Comment by KaelWD** [comment] 2022-02-21 03:49
Material design spec says:

> On mobile and desktop, offset the first tab on the left to signal that tabs are scrollable

**Comment by gotson** [comment] 2022-02-21 03:51
> Material design spec says:
> 
> > On mobile and desktop, offset the first tab on the left to signal that tabs are scrollable

fair enough.

**Comment by KaelWD** [comment] 2022-03-03 06:02
Duplicate of #10358

**Closed by KaelWD** 2022-03-03 06:02 UTC
Labels: T: bug, C: VTabs
