### ISSUE TITLE
[Bug Report] Elements of mini drawer aren't re-centered when specified different mini-variant-width

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#3007] opened 2018-01-14 00:06 UTC
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
- Create a mini variant drawer (just open reproduction link)

- Add `mini-variant-width` attribute with value of something like 55

### Expected Behavior
Elements to be centered. 

Otherwise why does it even allow you to change the width if all the elements aren't going to be centered?

### Actual Behavior
Elements aren't centered in mini drawer

### Reproduction Link
[https://codepen.io/anon/pen/eyKwJg](https://codepen.io/anon/pen/eyKwJg)

**Comment by jacekkarczmarczyk** [comment] 2018-01-14 01:59
Duplicate of #2606

**Closed by jacekkarczmarczyk** 2018-01-14 01:59 UTC

**Comment by AlexSHoffman** [comment] 2018-02-24 19:06
@jacekkarczmarczyk 
@johnleider 

The `mini-variant-width` prop is still doesn't work properly in the v1.0. The elements aren't being centered:
https://codepen.io/anon/pen/eyKwJg

Am I missing something? Why does this prop even exist if it doesn't work as expected?
