### ISSUE TITLE
Combining Dark and Disabled Attribute to Button Make it Disappear

### ISSUE THREAD

**Issue by jefrydco** [vuetifyjs/vuetify#5313] opened 2018-10-12 13:04 UTC
### Versions and Environment
Vuetify: 1.2.8
Vue: 2.5.17
Browsers: Chrome 69.0.3497.100
OS: Fedora 28

### Steps to reproduce

Combine dark and disabled attribute to button.

### Expected Behavior

Button doesn't disappear

### Actual Behavior

Button disappear

### Reproduction Link

https://codepen.io/jefrydco/pen/mzMrwK
---

**Comment by jacekkarczmarczyk** [comment] 2018-10-12 13:06
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4482

**Closed by jacekkarczmarczyk** 2018-10-12 13:06 UTC
