### ISSUE TITLE
[Feature Request] Year picker

### ISSUE THREAD

**Issue by literakl** [vuetifyjs/vuetify#10320] opened 2020-01-24 16:45 UTC
### Problem to solve
I want to select a year when somebody was born. The date picker does not have a year granularity at this moment.

### Proposed solution
Enhance date picker so it can select a year from the list. I can supply a screenshot from other component:
![image](https://user-images.githubusercontent.com/6383287/73086620-3ebecc80-3ed1-11ea-8e98-a9f4876e6ad8.png)

**Comment by jacekkarczmarczyk** [comment] 2020-01-24 16:49
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9096

**Closed by jacekkarczmarczyk** 2020-01-24 16:49 UTC
Labels: triage
