### ISSUE TITLE
[Bug Report] v-select drop down list with autocomplete and hide details prop doesn't render the dropdown list properly

### ISSUE THREAD

**Issue by stoked74** [vuetifyjs/vuetify#2427] opened 2017-11-06 16:14 UTC
### Versions and Environment
**Vuetify:** 0.17.0-beta.2
**Vue:** 2.5.3
**Browsers:** Chrome 62.0.3202.75
**OS:** Mac OS 10.13.1

### Steps to reproduce
Create a v-select with hide-details prop and the autocomplete prop and expand the drop down.

### Expected Behavior
The drop down list should appear below the select.

### Actual Behavior
The dropdown appears above the select input making it very difficult to type in the input. This is likely due to the drop down not compensating for the details container not being there.

### Reproduction Link
[https://codepen.io/smitchell/pen/MOezyE](https://codepen.io/smitchell/pen/MOezyE)

**Comment by KaelWD** [comment] 2017-11-07 02:28
Duplicate of #2377

**Closed by KaelWD** 2017-11-07 02:28 UTC
Labels: pending review
