### ISSUE TITLE
[Bug Report] VMenu with transition opens randomly in wrong place

### ISSUE THREAD

**Issue by aldarund** [vuetifyjs/vuetify#10338] opened 2020-01-26 17:33 UTC
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
just click on button and it will sometime open properly to left, but sometime to the right. 
https://www.dropbox.com/s/evzjs5qm1gev4jh/2020-01-26_20-34-34.mp4?dl=0

### Expected Behavior
Always opens to the left

### Actual Behavior
opens randomly and not consistent

### Reproduction Link
<a href="https://codepen.io/aldarund/pen/vYEPZdb?editors=1010" target="_blank">https://codepen.io/aldarund/pen/vYEPZdb?editors=1010</a>

### Other comments
any workarounds maybe?

**Comment by KaelWD** [comment] 2020-01-27 05:54
Duplicate of #8454

**Closed by KaelWD** 2020-01-27 05:54 UTC
Labels: triage
