### ISSUE TITLE
[Feature Request] Where is my VDataTable Component in Vuetify 3 ?

### ISSUE THREAD

**Issue by muzanella11** [vuetifyjs/vuetify#16338] opened 2022-12-28 02:03 UTC
### Problem to solve
Dear team,
I've some problem when migrating and using vuetify 3 in nuxt 3, the problem is I can't find the VDataTable component in vuetify 3, will it be removed or will it remain in vuetify 3?
I think this component has helped me a lot and maybe a lot of people there when making applications with this vuetify.
Please quickly consider this DataTable component, otherwise I have to add my own custom DataTable component.

### Proposed solution
I hope the VDataTable component returns quickly in vuetify 3 as it helps a lot. Otherwise I have to make my own custom component :(

**Comment by KaelWD** [comment] 2022-12-28 06:51
Duplicate of #13479

**Closed by KaelWD** 2022-12-28 06:51 UTC
Labels: S: triage
