### ISSUE TITLE
[Bug Report] v-data-table expand not working when group-by is active

### ISSUE THREAD

**Issue by dark-matter-matters** [vuetifyjs/vuetify#7866] opened 2019-07-18 14:46 UTC
### Versions and Environment
**Vuetify:** 2.0.0-beta.8
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Create a v-data-table with properties group-by and show-expand.

### Expected Behavior
Rows should be expandable when using group-by aggregation.

### Actual Behavior
Expansion arrows are shown but not functionnal, rows won't expand. 

### Reproduction Link
<a href="https://codepen.io/anon/pen/VowBRG" target="_blank">https://codepen.io/anon/pen/VowBRG</a>

**Comment by KaelWD** [comment] 2019-07-23 09:20
Duplicate of #7862

**Closed by KaelWD** 2019-07-23 09:20 UTC
Labels: triage
