### ISSUE TITLE
[Bug Report][3.5.7] TextField: Cursor repositioned on :type change when 'hint' attribute is missing/empty

### ISSUE THREAD

**Issue by TheTrigger** [vuetifyjs/vuetify#19343] opened 2024-03-06 09:31 UTC
### Environment
**Vuetify Version:** 3.5.7
**Last working version:** 3.0.0-alpha.11
**Vue Version:** 3.4.21
**Browsers:** Google Chrome, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
1. Place the cursor in the middle of the password field (text selection is also possible).
2. Change the password visibility using the inner icon.

If the text field has the "hint" attribute, the behavior is as expected. However, if the text field is without the "hint" attribute or if it's empty, the cursor loses its position.

With the latest version (3.5.8), this incorrect behavior occurs regardless of the "hint" attribute's presence.

This issue does not occur in FireFox.

### Expected Behavior
The cursor remains in its original position

### Actual Behavior
The cursor moves to position 0 (left)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrdVE1PwzAM/Ssmlw6JrtoAIU0dH3fElQPjkLUps9Y2UeJ2TNP+O0nbsX4dECfELX5+frXsV78dmNFR8KTUtCwEW7CQRKZSTuJ+lQOEpc+Vqp5VEMmcOOZCN1AFJlJn33GXBklaYNxKVmktdx2oqUl7IMCr1FvMP2CyQ9rABnMCTqRxXZC47JOtBolP8hMUadxPApR+JmORLldMcWN2UscrNmTZLqR2HI0Z1/sxSs4z0VKZjXEWtFeOVKLBdSrgATzXmwcL8E6F3mihHbfIYx9zOz0f7SC7KlmMvtgLXyZJJdbEo1qPUYrRtqPYElvCRfMcq3WztuRnDlRwOLUMplB2qQajQvNh2WB/YdDeSX/nNlkv/UdeeJEEtoezH2RBf9QS839oid/utot1//yaNbgoFm2dlCHJIfVVCoPWtbKhiTQqAiOoqI8WZkpqggNokcAREi0z8Oyh81zSqho6e3vpSBPPmArxKjPVlPN8HCPhqXFWC4P6c/ZD7HjFrqc30/mMucft9I69fwGpW4Fn)

### Other comments
I have reviewed similar issues, but I am still opening this one because the problem persists in version 3.5.8 even with the "hint" attribute present. Additionally, it seems to work correctly in version 3.0.0-alpha11

**Comment by KaelWD** [comment] 2024-03-06 23:55
Duplicate of #16109

**Closed by KaelWD** 2024-03-06 23:55 UTC
Labels: S: triage

**Comment by muzakon** [comment] 2025-04-20 20:55
The problem still occurs on Chrome even in the latest version of Vuetify (3.8.2)

Besides it, when clicking the label, the cursor set the beginning of the input even though if it HAS "hint" property.

Reproduction link:
https://play.vuetifyjs.com/#eNqtVNtu2zAM/RXGL26B2FlSbCiCJFs/oMMwDHtpClS16UaYLGm6JAvS/Pto+RLHBdpt2IMBSjzHvByKd4fImmxyo3W69RjNo4XDUgvmcLWWAIttUihTBjucMiUd4xINFMLzvHEEl1G77thgBdBnl+toOltHYEuyPqyjHirgHP5yScFR5H0HwDYpVY6CSJpZu1MmX0fniDnTGmWecEkZJZySI7DdqN0UPkJc5jzBPcYw7+xEFUX84i9ur7FPrBIKrDbuC8qGS0eMGwcCmXVwDdmGGZY5NHaIFewxFPGZGskE7LjbBD5UYYZgycoqFS61d8n0XTIdAj5lgmc/zgrvUl/CKBhDzpYZzkLCXuZoBOk3aOVqMenr0NeRHCQi3fxXbbsCTprN/koz4wVW0e+CkRr86bnBfAz1ueTy/jWdQ7C3dc4EeTo9nozyOqEXkXk77OC/zcR3bvmjwLemgDr8yhR0JTX6D9B/ou3pfHrFtbd57vU2oJtmHSwmvT1BR5sZrh1YdF4HLC+1Mg4OYLCAIxRGlRDTionrQaIfU4uCVpT2oY7YijiniRUeYbmC0ag2n58h/tq403hc40lkglawbSpQPtHDWi2p7xX4lsszBVoOloyLW+ayzRwuLivuw7cN1tfAZA7tLMBeeUBJXMwhVzJ2UFa0h/CjY7+M9vVRqRcFExYvz32VMpXPGd93dZFqb/ylnULCLCZ1R6mX0XEcXaXv0+lVVBnX6Swahyjjs9Vd393/Bi0zuws=
