### ISSUE TITLE
[Bug Report] GoTo function not working in scrollable dialog

### ISSUE THREAD

**Issue by infiniityr** [vuetifyjs/vuetify#6933] opened 2019-04-05 17:15 UTC
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Mac OS 10.14.1

### Steps to reproduce
Create a dialog with a scrollable card.
Add content in card-text so that it is scrollable.
Try to execute the goTo() function on an existing field.

I also tried it with a Timeline element.

### Expected Behavior
Should go to the wanted item (here field 3)

### Actual Behavior
Does not move.

### Reproduction Link
<a href="https://codepen.io/anon/pen/vMKKJM" target="_blank">https://codepen.io/anon/pen/vMKKJM</a>

**Comment by KaelWD** [comment] 2019-04-06 02:24
Duplicate of #3510

**Closed** 2019-09-24 19:02 UTC
Labels: Service: Goto, T: documentation, duplicate
