### ISSUE TITLE
[Feature Request] Scroll bar

### ISSUE THREAD

**Issue by Roshmia** [vuetifyjs/vuetify#10139] opened 2020-01-07 11:16 UTC
### Problem to solve
scroll bar looks old fastion

### Proposed solution
if the scroll bar imporved in all the place like combobox, autocomplete, select, tables.. it would be better in looking

**Comment by KaelWD** [comment] 2020-01-10 07:40
Duplicate of #5196

**Closed by KaelWD** 2020-01-10 07:40 UTC
Labels: triage
