### ISSUE TITLE
[Bug Report] Datatable: colspan error in expand row when headerless

### ISSUE THREAD

**Issue by Gnoc** [vuetifyjs/vuetify#3568] opened 2018-03-14 10:29 UTC
### Versions and Environment
**Vuetify:** 1.0.7
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.146
**OS:** Windows 10

### Steps to reproduce
If not provide :heahers='headers' like this
<v-data-table hide-headers>
![image](https://user-images.githubusercontent.com/10009897/37397122-5894488e-27ad-11e8-8e40-e6e715572e72.png)

the conspan in expand row will be equal to 0.
![image](https://user-images.githubusercontent.com/10009897/37397148-68b2698a-27ad-11e8-8531-77f6fff444cd.png)

### Expected Behavior
Expand row with colspan 100%

### Actual Behavior
Expand row with colspan=0

### Reproduction Link
[https://codepen.io/gnocnguyen/pen/JLGVKJ](https://codepen.io/gnocnguyen/pen/JLGVKJ)

**Comment by KaelWD** [comment] 2018-03-14 10:37
Duplicate of #3419

**Closed by KaelWD** 2018-03-14 10:37 UTC

**Comment by do-web** [comment] 2019-02-12 22:27
This is not fixed!

**Comment by jacekkarczmarczyk** [comment] 2019-02-13 02:39
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
