### ISSUE TITLE
[Bug Report][3.4.3] v-date-picker not able to switch locale with default settings

### ISSUE THREAD

**Issue by jtuchel** [vuetifyjs/vuetify#18777] opened 2023-11-27 10:35 UTC
### Environment
**Vuetify Version:** 3.4.3
**Vue Version:** 3.4.0-alpha.1
**Browsers:** Firefox 119.0
**OS:** Linux x86_64

### Steps to reproduce
French locale is passed to locale provider but component is using english locale

### Expected Behavior
Component should use french locale

### Actual Behavior
Component is using english locale

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUk1PwzAM/StRLgOpTYS2A5q6afwJLoRDP1wIa9IoycrQ1P+Om0RjKxzGpar9nv3s57ycqLM1Hw7gZfvFPhxdU6lMbz05kdpC6eE5YmQkre0VWSTuQugzEXSG4JzBu74uO0Ci0HAM1LrXzpOEk821wt1JaEJi0ZqE4CdcgF5kMdWWXVeV9f4qqcC58g0cFuIUGY5ExgBN3/FeaJqFTZ+MYaiPaxYelOlQfjvRiiEvjQm/IYi6ubH9IBuwaY6NoK0VNNECscEOuZH1Huy24Ndx6obZWbsoifmoWfCLWXDQaGyuSoMX6TUOG9wQCXCCnv0RFLeZYkHfvTduzXndaCxroJODZRo810bxHdK4PWgvFeRNr3ZLtmQr3kjnL9MMnMor2386sNhE0GRvkJmOdINUYqLCij1EhZTKu7Jyk8SfrdN7+ZfCkj3yTlaplEvdwJGpeXeO2wxgcwuIW8AL3ubXrOzSsxn0y7fw9PDl0TGjoQzPGgyhr9/rtSuX)

### Other comments
If using no Vuetify configuration `export const vuetify = createVuetify()` you get a warning

> Vuetify: Translation key "$vuetify.datePicker.title" not found in "fr", trying fallback locale

I don't need custom settings so I would prefer a Vuetify instance with default configuration.

**Comment by KaelWD** [comment] 2023-11-27 11:19
Duplicate of #18685, your repro is using 3.4.1

> I don't need custom settings so I would prefer a Vuetify instance with default configuration

For english text but french date formatting you would instead use 
```
date: {
  locale: {
    en: 'fr',
  }
}
```

**Comment by KaelWD** [comment] 2023-11-27 13:12
Yeah there's no way to do it without configuration. The other option is `messages: { fr: en }` if you have to use locale provider for some reason.

**Closed** 2023-11-27 13:13 UTC
Labels: S: triage
