### ISSUE TITLE
[Bug Report][2.5.10] VCalendar context menu event do not emit Mouse x,y data of native event. 

### ISSUE THREAD

**Issue by Meplos** [vuetifyjs/vuetify#14298] opened 2021-10-19 14:49 UTC
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 94.0.4606.81
**OS:** Linux x86_64

### Steps to reproduce
Open your console and right click on time or day calendar.

In logs nativeEvent is not pass for time and day contextmenu event. 
When you click on the event NativeMouseEvent is pass.  

### Expected Behavior
When you click on the calendar you must have nativeEvent 

### Actual Behavior
nativeEvent is pass only when you click on an custom event

### Reproduction Link
<a href="https://github.com/Meplos/calendar-bug" target="_blank">https://github.com/Meplos/calendar-bug</a>

**Comment by KaelWD** [comment] 2021-11-03 09:57
Duplicate of #9485

**Closed by KaelWD** 2021-11-03 09:57 UTC
Labels: C: VCalendar, S: triage
