### ISSUE TITLE
[Bug Report] v-calendar inconsistent start date type

### ISSUE THREAD

**Issue by adamrainsby** [vuetifyjs/vuetify#6556] opened 2019-02-20 17:22 UTC
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.109
**OS:** Mac OS 10.14.2

### Steps to reproduce
Click the forward or back buttons to change the start date of the calendar. Notice that the start date is a string. Now click on one of the dates on the calendar. The start date is now an object.

### Expected Behavior
Start date type should be consistent. Calling $refs.calendar.prev() and clicking a date on the calendar should both either set the start date to either a string or an object.

### Actual Behavior
Calling $refs.calendar.prev() or $refs.calendar.next() on a calendar sets start date to a string whereas clicking a date sets the start date to an object.

### Reproduction Link
<a href="https://codepen.io/anon/pen/XOQeNv?&editable=true&editors=111" target="_blank">https://codepen.io/anon/pen/XOQeNv?&editable=true&editors=111</a>

**Comment by KaelWD** [comment] 2019-02-21 05:33
Duplicate of #6552

**Closed by KaelWD** 2019-02-21 05:33 UTC
