### ISSUE TITLE
[Bug Report] v-autocomplete placeholder appears only on click

### ISSUE THREAD

**Issue by Cesarevich** [vuetifyjs/vuetify#12327] opened 2020-10-01 11:45 UTC
### Environment
**Vuetify Version:** 2.3.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4183.121
**OS:** Linux

### Steps to reproduce
https://vuetifyjs.com/en/components/autocompletes/#item-and-selection
open example in https://codepen.io/ and add placeholder="test test"
Placeholder appears only on v-autocomplete input click on blur disappears

### Expected Behavior
Placeholder seen as usual without necessity to click on input

### Actual Behavior
Placeholder seen only on input click

### Reproduction Link
<a href="https://codepen.io/Cesarevich/pen/bGpPBYy?editors=1010" target="_blank">https://codepen.io/Cesarevich/pen/bGpPBYy?editors=1010</a>

**Comment by KaelWD** [comment] 2020-10-01 11:54
Duplicate of #11553

**Closed by KaelWD** 2020-10-01 11:54 UTC
Labels: triage

**Comment by Cesarevich** [comment] 2020-10-01 12:57
Duplicate
