### ISSUE TITLE
[Feature Request] [Documentaion] what the heck is ` v-on="on"` ?

### ISSUE THREAD

**Issue by yuminatwca** [vuetifyjs/vuetify#7043] opened 2019-04-22 19:05 UTC
### Problem to solve
the data table component has something ` v-on="on"  `? What is that ? There is nothing in Vuejs documentation nor Vuetify documentation.

I want to customized it ,but don't know how I do it.

### Proposed solution
Write some proper documentation about this part. Thanks.

**Comment by MajesticPotatoe** [comment] 2019-04-22 19:06
Duplicate of #6866

**Closed by MajesticPotatoe** 2019-04-22 19:06 UTC
Labels: duplicate
