### ISSUE TITLE
[Bug Report] v-data-table value only accepts lowercase for custom formatting

### ISSUE THREAD

**Issue by amizer12** [vuetifyjs/vuetify#13311] opened 2021-03-23 13:17 UTC
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.90
**OS:** Mac OS 11.2.3

### Steps to reproduce
in JS section change value name from:
value: 'createdtime'
into
value: 'createdTime'

and function related to this field custom formatting will not launch. Despite the other naming ignore picking up proeplry andbeing case sensitivite - the value definition for header HAVE to be all lowercase no matter what - this is either a bug or a limitation - onew way or another i didn`t find this mentioned in any docs on vuetify site hence raising that here as i lost probably more than one hour trying to figure it out so nobody else need to go through it :)

### Expected Behavior
 .

### Actual Behavior
 .

### Reproduction Link
<a href="https://codepen.io/amizer12/pen/qBRWRMJ" target="_blank">https://codepen.io/amizer12/pen/qBRWRMJ</a>

**Comment by KaelWD** [comment] 2021-03-23 13:19
Duplicate of #13310

**Closed by KaelWD** 2021-03-23 13:19 UTC
Labels: triage
