### ISSUE TITLE
[Bug Report] Using custom SVG Icon causes errror on VSelect

### ISSUE THREAD

**Issue by blowsie** [vuetifyjs/vuetify#11047] opened 2020-04-07 13:16 UTC
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.5.12
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Use vselect component with this root configuration 

ps. im not sure how to use this in codepen

```js
// src/plugins/vuetify.js

import Vue from 'vue'
import Vuetify from 'vuetify/lib'

import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { faCaretDown } from '@fortawesome/pro-light-svg-icons'

Vue.component('font-awesome-icon', FontAwesomeIcon)
library.add(faCaretDown)

Vue.use(Vuetify)

export default new Vuetify({
  icons: {
    values: {
      // set menu to light (default is solid)
      dropdown: {
        component: 'font-awesome-icon',
        props: {
          icon: ['fal', 'caret-down']
        },
      },
    },
  },
})
```

### Expected Behavior
Runs without errors

### Actual Behavior
Logs error

vue.runtime.esm.js?0e6f:619 [Vue warn]: The .native modifier for v-on is only valid on components but it was used on <svg>.

### Reproduction Link
<a href="https://codepen.io/blowsie/pen/ExjqGBJ" target="_blank">https://codepen.io/blowsie/pen/ExjqGBJ</a>

### Other comments
Could be reproduced with free icon set if needed

**Comment by jacekkarczmarczyk** [comment] 2020-04-07 13:26
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9999

**Closed by jacekkarczmarczyk** 2020-04-07 13:26 UTC
Labels: triage
