### ISSUE TITLE
[Bug Report] items props not working well with objects in Selects component

### ISSUE THREAD

**Issue by endmaster0809** [vuetifyjs/vuetify#11718] opened 2020-06-24 12:22 UTC
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.106
**OS:** Mac OSX

### Steps to reproduce
When I use items props of Selects component with Object, It doesn't display all items which have the same value.
Please reference the reproduction link above.

### Expected Behavior
Render all items which have the same value.

### Actual Behavior
Only display one item among items that have the same value.

### Reproduction Link
<a href="https://codepen.io/endmaster0809/pen/NWxgWro" target="_blank">https://codepen.io/endmaster0809/pen/NWxgWro</a>

**Comment by jacekkarczmarczyk** [comment] 2020-06-24 12:47
Duplicate of https://github.com/vuetifyjs/vuetify/issues/11608

**Closed by jacekkarczmarczyk** 2020-06-24 12:47 UTC
Labels: triage
