### ISSUE TITLE
pagination bar number button error

### ISSUE THREAD

**Issue by JinSung-Hwang** [vuetifyjs/vuetify#1888] opened 2017-09-26 04:38 UTC
### Versions

 mac chrome 
    "vue": "^2.4.2",
    "vuetify": "^0.15.1",

### What is expected ?

page buttons number fix
### What is actually happening ?

i implements pagination that rowperpage is 10 and total visible is 7
my itemsarray has 100 items   
i quickly clicked page number button ( not nextbutton and previewbutton )
then page button number error
1 2 36 .. 8 9 10

**Comment by jacekkarczmarczyk** [comment] 2017-09-26 04:39
Please provide the reproduction link

**Comment by JinSung-Hwang** [comment] 2017-09-28 04:16
<div id="app">
  <v-app id="inspire">
    <div class="text-xs-center">
    <v-pagination :length="15" v-model="page" :total-visible="7"></v-pagination>
  </div>
  </v-app>
</div>


new Vue({
  el: '#app',
  data () {
      return {
        page: 1
      }
    }
})


https://codepen.io/pen/?editors=1010
vuetifyjs site  https://vuetifyjs.com/components/pagination
  limit  
im using #3 limit
many click number buttons

**Comment by KaelWD** [comment] 2017-09-28 09:06
That isn't a reproduction link, make a codepen from this template: https://template.vuetifyjs.com

**Comment by JinSung-Hwang** [comment] 2017-09-28 10:24
https://codepen.io/upsidedownkingdom/pen/OxmOjW

the code in url is same that is https://vuetifyjs.com/components/pagination #3 limit

**Comment by KaelWD** [comment] 2017-09-28 12:44
I'm sorry, I can't see what the issue is, it works fine for me. Can you please try to explain it better?

**Comment by JinSung-Hwang** [comment] 2017-09-29 05:06
u many click number button then u find issue

**Comment by nekosaur** [comment] 2017-09-29 10:20
You will have to be more specific with the reproduction steps, or show is in a gif or something. I can't seem to find any problem either.

**Comment by KaelWD** [comment] 2017-09-29 10:28
Ah, maybe this? 
![image](https://user-images.githubusercontent.com/16421948/31012292-9f1df0a6-a554-11e7-95bf-ab33e490355f.png)

There is a `...` between 14 and 15 even though they are consecutive.

**Comment by JinSung-Hwang** [comment] 2017-09-29 10:56
oh..  i didnt know that upload pichure

![2017-09-26_12 56 03](https://user-images.githubusercontent.com/29647648/31013162-ce53d4ee-a54f-11e7-8d0b-3675366dcae2.png)

**Comment by peluprvi** [comment] 2017-10-02 12:55
@KaelWD I think that `...` issue you provide is new one. Happens when going from page 1 to page 3 or from page 15 to 13: https://codepen.io/anon/pen/BwdMoV

@JinSung-Hwang Please, can you provide some more details:
- Can you provide the sequence you clicked to get this issue (in page numbers, like I did above to @KaelWD )?
- This happens on https://codepen.io/anon/pen/BwdMoV ?
- How many pages do you have, or what variables you are using for the pagination element?

**Comment by nekosaur** [comment] 2017-10-21 11:14
Closing due to lack of reproduction.

**Closed by nekosaur** 2017-10-21 11:14 UTC
Labels: need reproduction
