### ISSUE TITLE
[Bug Report][3.0.0-beta.10] v-img undefined (reading 'value')

### ISSUE THREAD

**Issue by insekticid** [vuetifyjs/vuetify#15755] opened 2022-09-08 08:12 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Vue Version:** 3.2.38
**Browsers:** Edge 105.0.1343.27
**OS:** Linux

### Steps to reproduce
error is triggered after isBooted.value = true

### Expected Behavior
no exception

### Actual Behavior
exception

### Reproduction Link

```
<template>
    <div>
        <v-img src="https://cdn.vuetifyjs.com/images/cards/sunshine.jpg" height="200px" cover eager></v-img>
    </div>
</template>

```

![image](https://user-images.githubusercontent.com/177340/189063947-952dfe64-b103-47dc-baff-de678143a993.png)

code to reproduce
```
<template>
    <div>
        <v-img src="https://cdn.vuetifyjs.com/images/cards/sunshine.jpg" height="200px" cover eager></v-img>
    </div>
</template>
```

error is triggered after  `isBooted.value = true`
https://github.com/vuetifyjs/vuetify/blob/a291148b53566fa78eae0815bcda4d58fca5d644/packages/vuetify/src/components/VImg/VImg.tsx#L263

**Comment by KaelWD** [comment] 2022-09-08 08:21
Duplicate of #15724

**Closed by KaelWD** 2022-09-08 08:21 UTC
Labels: S: triage
