### ISSUE TITLE
[Bug Report] Vuetify doesn't work properly with FontAwesome SVGs

### ISSUE THREAD

**Issue by ffxsam** [vuetifyjs/vuetify#12747] opened 2020-12-08 22:57 UTC
### Environment
**Vuetify Version:** 2.3.20
**Vue Version:** 2.6.12
**Browsers:** Firefox 83.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. Create and include a FontAwesome SVG kit
1. Add an icon, e.g. `<v-icon>fas fa-trash</v-icon>`
1. Flip to dark mode

### Expected Behavior
Icon should be white (as when using FontAwesome webfont mode)

### Actual Behavior
Icon remains the same color (the theme class is not updated on the svg)

### Reproduction Link
<a href="https://codepen.io/ffxsam/pen/jOMMEpO" target="_blank">https://codepen.io/ffxsam/pen/jOMMEpO</a>

**Comment by KaelWD** [comment] 2020-12-09 04:12
Duplicate of #3505

**Closed by KaelWD** 2020-12-09 04:12 UTC
Labels: triage

**Comment by ffxsam** [comment] 2020-12-09 05:56
@KaelWD I see that issue was closed but I don't see a fix or workaround. Could you please point out what I'm missing?

**Comment by KaelWD** [comment] 2020-12-09 06:07
https://vuetifyjs.com/en/features/icons/#font-awesome-svg-icons

**Comment by ffxsam** [comment] 2020-12-09 15:41
Thanks! This is a bit more overhead than just including FontAwesome's kit URL, unfortunately. There are some benefits to using FontAwesome kits + `<v-icon>`:

1. Only the icons used in the code are pulled from FontAwesome's CDN. No need to manually import every icon used throughout the app as with the FontAwesome NPM solution. (yes, you can simply import `fas` but at the cost of bundle size)
1. We can still use `<v-icon>` and benefit from shortcuts like `<v-icon left>` when styling buttons.

I think I'll stick with FA webfonts for the time being.

**Comment by KaelWD** [comment] 2020-12-09 15:54
In v2.4 you can use the new global `icons.component` property to integrate something like iconify: #7821
