### ISSUE TITLE
The <v-text-field return-masked-input> is not the same as the masked input field.

### ISSUE THREAD

**Issue by azaars** [vuetifyjs/vuetify#2096] opened 2017-10-09 12:11 UTC
### Steps to reproduce

1. Set `mask="phone"` and `return-masked-input`
2. Type numbers
3. Type alphabets

### Versions
0.16.4

### What is expected ?
The returned `input` value must exactly be the same as what is displayed in the `input` field.

### What is actually happening ?
1. The returned value appears a few steps behind the `input` value as characters are progressively inserted.
2. The returned value contains illegal characters according to the mask rule.

### Reproduction Link
https://codepen.io/azaars/pen/XeEYpq

**Comment by KaelWD** [comment] 2017-10-09 12:15
Possible duplicate of #2057

**Comment by azaars** [comment] 2017-10-09 12:39
Yeah, maybe. But this is specific to the `return-masked-input` bug.

**Closed** 2017-10-18 01:05 UTC
Labels: bug
