### ISSUE TITLE
[Feature Request] Easily positionning a fab in top of a footer (position relative to other components)

### ISSUE THREAD

**Issue by slimee** [vuetifyjs/vuetify#2895] opened 2017-12-29 18:21 UTC
### New Functionality
Currently if you have a footer and a bottom right button, the button will be bad positionned.
A good position for my bottom right button when using a footer (the button should go up)

### Improvements
It would be nice if the bottom attribute will take care of the existence of a footer. The button should be at the bottom, but upper than the footer instead of walk on it.

### Bugs or Edge Cases it Helps Avoid
A layout conflict between the footer and the fab.

**Comment by slimee** [comment] 2017-12-29 18:22
Maybe a more general system would be nice, like new attributes defining relative positionning:

<button top-of="footer" right/>
<footer/>

**Comment by johnleider** [comment] 2017-12-31 01:01
Along with this update, I want to integrate snackbar into the application so that, per spec, the fab can be moved up if a snackbar comes under it.

**Comment by KaelWD** [comment] 2018-02-22 03:35
Snackbars are already covered under #1852

**Comment by morgler** [comment] 2018-08-30 09:32
Looking forward to this feature! Is there a workaround I could use in the meantime?

**Comment by morgler** [comment] 2018-08-30 10:06
Btw: just saw, that this behavior is **not** in line with Material Design guidlines:

![](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1gXnDalMO0XMkGKSe-fqAfbSX_4kk9z-9%2Fanatomy-fab-dont.png)

The FAB should rather overlap the bottom bar like so:

![](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1hIkcwMS6C3V2ZdFJmYV_VAIWPfU6dxXC%2Fanatomy-fab-overlap.png)

I will try to alter my mixin from above to create this recommended behavior.

**Comment by johnleider** [comment] 2019-06-19 20:28
Unfortunately this did not make the cut for v2.0 as we intend to pull the `v-btn` **fab** functionality into its own component to better scope this functionality and not to bloat `v-btn` any further.

Thank you to everyone for your patience on this.

**Comment by johnleider** [comment] 2021-06-15 13:45
Closing as duplicate of #1852

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-06-15 13:45 UTC
Labels: C: New Component, C: VBtn, T: feature
