### ISSUE TITLE
[Bug Report] Data-table headers width doesn't work

### ISSUE THREAD

**Issue by vcastro45** [vuetifyjs/vuetify#5072] opened 2018-09-11 07:52 UTC
### Versions and Environment
**Vuetify:** 1.2.2
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.81
**OS:** Windows 10

### Steps to reproduce
Create a data-table and add a "width" attribute to a header object

### Expected Behavior
The column corresponding to the header object with the "width" attribute must have the desired width.

### Actual Behavior
The width attribute is added to the DOM but this HTML attribute is deprecated for HTML5 and does nothing (cf: https://www.w3schools.com/TAGS/att_th_width.asp)

### Reproduction Link
[https://codepen.io/anon/pen/wEyZwN?editors=1010](https://codepen.io/anon/pen/wEyZwN?editors=1010)

### Other comments
The suggested work-around provided by W3C that say to use the "width" CSS property doesn't work for this component.

**Comment by WhatFreshHellIsThis** [comment] 2018-11-22 18:37
Yes, removing the v-flex around it fixes the issue but then the whole layout is broken!?  What to do?

**Comment by saitam1** [comment] 2019-02-07 10:38
I am not using `v-flex`, but it doesn't work either!
```
<template>
    <div>
        <v-container class="my-5">
            <v-data-table></v-data-table>
        </v-container>
    </div>
</template>
```
Inside headers I tried to set width as follows: `width: '20%'`, `width: '100px'`, `width: '150'`, but none of them had an impact on the data tables header width

**Comment by sorxrob** [comment] 2019-02-16 09:32
@saitam1 Do you have a fix for this already? Adding width keys to the headers array is not working. Setting a class also is not working. This is a long time issue already.

I hope someone found an issue and does mind to share their solution...

**Comment by baermathias** [comment] 2019-02-16 14:18
It works better like this `width: '100%'` as like this `width: '30px'`.
But it is not really working as needed :-/

**Comment by CodeMonkeyG** [comment] 2019-03-13 00:57
I spent hours fighting this today. Nearly lost my mind. The fix for me?
```
<v-data-table class="my-awesome-table"></v-data-table>

<style>
  .my-awesome-table{
    table-layout : fixed;
  }
</style>
```

Suddenly the widths in the header configs were honored.

**Comment by 360hnjd-fe** [comment] 2019-03-27 09:23
Pit father

**Comment by 360hnjd-fe** [comment] 2019-03-27 09:25
Not repaired yet?

**Comment by huynd8295** [comment] 2019-03-29 09:09
I have the same problem, the width attribute doesnt seem to work at all.

**Comment by guastallaigor** [comment] 2019-04-11 16:49
Same here, `table-layout: fixed` didn't work in my case for some reason. Any other workaround?

**Comment by guastallaigor** [comment] 2019-04-11 16:49
Same here, `table-layout: fixed` didn't work in my case for some reason. Any other workaround?

**Comment by laurengranada** [comment] 2019-04-16 18:24
My Before:
![before](https://user-images.githubusercontent.com/21206416/56233915-c1188700-6049-11e9-9eb2-6f44bf4017b6.PNG)

My After:
![after](https://user-images.githubusercontent.com/21206416/56233916-c1b11d80-6049-11e9-80d5-a5fffb643c18.PNG)

my code:
```
<v-data-table ... class="mi-dataTable elevation-1">
    <template slot="headers" slot-scope="props">
         <tr class="mid-headercell">
             <th class="midh-text"  v-for="header in props.headers"
                >{{header.text}}
             </th>
         </tr>
     </template>
     <template v-slot:items="props">
           <td class-"mid-item">{{props.item.desc}}</td>
            ....
    </template>
</v-data-table>
```
and the css that fixed my problem!: 

`table-layout: fixed` as well as the `padding: 0px` for my headercell

```
.mi-dataTable{
     table-layout: fixed;
     .mid-headercell{
            text-align: left;
            background-color: $blue_accent;
            .midh-text{
                    padding: 0px;
                    padding-left: 2.5%;
                    color: white;
                    font-weight: 400;
             }
      }
}
```

Hope this helps someone else!

**Comment by hlohrenz** [comment] 2019-04-26 15:04
So the thing that solved it for me was adding this styling to the th tags inside the table's header:
```
table.v-table
  thead
    th
      white-space: normal // Default was nowrap which was causing the headers to not shrink down
```

**Comment by getsong** [comment] 2019-05-14 04:31
This works for me:
`headers: [
          {value: 'index', text: '#', sortable: false, width: '5%'},
          {value: 'id', text: 'Id', width: '5%'},
          {value: 'headerA', text: 'headerA', width: '10%'},
          {value: 'headerB', text: 'headerB', width: '10%'},
          {value: 'headerC', text: 'headerC', width: '12%'},
          {value: 'headerD', text: 'headerD', width: '12%'},
          {value: 'headerE', text: 'headerE', width: '6%'},
          {value: 'headerF', text: 'headerF', width: '12%'},
          {value: 'headerG', text: 'headerG', width: '18%'}
]`
Here is the css that make it work:
`<style>
  .class-on-data-table table {
    table-layout: fixed;
  }
</style>`
css `<style>` should not be `scoped` in order to style the table element, which is a in child component.

**Comment by ricardovanlaarhoven** [comment] 2019-05-21 14:56
Will this issue get fixed for 1.5 or only 2.0 ?

**Comment by allochi** [comment] 2019-05-22 06:55
It doesn't work for me too, I had to wrap the content with a `div` and set its width with a style 

```html
<td>
    <div style="width: 300px">...</div>
</td>
```

not the best solution, but it works for now.

**Comment by WhatFreshHellIsThis** [comment] 2019-05-22 16:33
Serious bug in major component over 8 months old now, can this be prioritized higher?

**Comment by nekosaur** [comment] 2019-05-23 10:11
Prioritization happens based on the availability of contributors. PRs are always welcome.

**Comment by CynthiaSuwi** [comment] 2019-05-28 06:03
> It doesn't work for me too, I had to wrap the content with a `div` and set its width with a style
> 
> ```
> <td>
>     <div style="width: 300px">...</div>
> </td>
> ```
> 
> not the best solution, but it works for now.

Great thanks to @allochi ! It is the best solution I found till now : )

Hope Vuetify team could fix the issue asap.

**Comment by Oscarz90** [comment] 2019-07-05 21:52
It doesnt work, I've tried many of the options published here

**Comment by nekosaur** [comment] 2019-07-22 09:36
Repro in 2.0 https://codepen.io/gilderbairn/pen/rXOyWL

**Closed** 2019-08-12 18:46 UTC
Labels: C: VDataTable, S: has PR, T: bug, T: enhancement

**Comment by klaveren** [comment] 2019-10-31 20:07
I have used windows size to fix this problem.

vue:
`  <v-container v-resize="onResize">
    <v-card :width="windowSize.x">
      <v-data-table />
    </v-card>
  </v-container>`

js: 
`    data() {
      return {
        search: '',
        headers: [],
        windowSize: {
          x: 0,
          y: 0,
        }
      }
    },
    mounted () {
      this.onResize()
    },
    methods: {
      onResize () {
        this.windowSize = { x: window.innerWidth, y: window.innerHeight }
      }
    }`

**Comment by kajirikajiri** [comment] 2020-03-25 08:10
```vue
<td style="min-width:55px;width:55px;max-width:55px"></td>
```

**Comment by ijunaid8989** [comment] 2020-07-29 17:39
nothing works

**Comment by ElSamhaa** [comment] 2020-10-08 16:58
why has this been closed?

**Comment by jacekkarczmarczyk** [comment] 2020-10-08 17:01
Because it's fixed

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.

**Comment by ElSamhaa** [comment] 2020-10-08 17:05
@jacekkarczmarczyk sorry to bother you, but in my own experience, the issue was not resolved even once and I don't think this is a regression. I am still experiencing the non-honored widths without the suggested `table-layout: fixed`

**Comment by iec989** [comment] 2020-10-28 14:31
Same thing here, it doesn't look like it's been solved

**Comment by jacekkarczmarczyk** [comment] 2020-10-28 14:36
https://github.com/vuetifyjs/vuetify/issues/5072#issuecomment-705701103

**Comment by nmalchy** [comment] 2020-10-28 17:02
Not working for me as well, using "vuetify": "^2.3.3", do I need to upgrade or should it have been fixed prior to this version?

**Comment by truemoroz** [comment] 2021-05-05 08:39
> [#5072 (comment)](https://github.com/vuetifyjs/vuetify/issues/5072#issuecomment-705701103)

It's not fixed at all. Show working example, please

**Comment by jacekkarczmarczyk** [comment] 2021-05-05 09:08
not working: https://github.com/vuetifyjs/vuetify/issues/5072#issuecomment-513718309
working: https://codepen.io/gilderbairn/pen/rXOyWL

![image](https://user-images.githubusercontent.com/15625235/117119119-ea6ff100-ad91-11eb-88ab-7e3d9e7272d3.png)

 If you believe that this issue has not been correctly resolved, **please create a new [issue](https://issues.vuetifyjs.com)** showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).
