### ISSUE TITLE
[Bug Report] Content behind a dialog scrolls on mobile devices

### ISSUE THREAD

**Issue by mikewisian** [vuetifyjs/vuetify#5353] opened 2018-10-19 03:56 UTC
### Versions and Environment
**Vuetify:** 1.3.0
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100, Safari, Mozilla Firefox
**OS:** Android, iOS

### Steps to reproduce
On a mobile browser (any iOS or Android device), load the page and click the button to open the modal. Tap and hold outside of the dialog borders to scroll up or down.

### Expected Behavior
Background content doesn't scroll.

### Actual Behavior
Background content scrolls, and dialog occasionally jumps in and out of position while scrolling.

### Reproduction Link
[https://codesandbox.io/s/my6rzvpx6x](https://codesandbox.io/s/my6rzvpx6x)

### Other comments
This can also be reproed on the [Vuetify dialog documentation](https://vuetifyjs.com/en/components/dialogs).

**Comment by KaelWD** [comment] 2018-10-20 07:55
Cannot reproduce on android chrome.

**Comment by mikewisian** [comment] 2018-10-23 18:14
> Cannot reproduce on android chrome.

Apologies, it looks like I was mistaken about it reproing on Android Chrome. The issue appears to only be on iOS using Safari or Chrome. Here is a screen capture of the issue (iOS 12.0.1/Safari):

https://streamable.com/4627r

**Comment by KaelWD** [comment] 2018-10-24 03:32
Duplicate of #3875

**Closed by KaelWD** 2018-10-24 03:32 UTC
Labels: duplicate, platform specific
