### ISSUE TITLE
[Feature Request] DataTables with drag and drop sortable rows

### ISSUE THREAD

**Issue by AlexanderZon** [vuetifyjs/vuetify#4511] opened 2018-07-06 12:56 UTC
### Problem to solve
I'm creating a module that requires the in-row editable datatable, almost requires that the rows could be sorted manually because the data has a hierarchy and need to be changed all the time

### Proposed solution
The solution could be a drag and drop feature into datatables component, that have a @dragged and a @dropped event to handle the order of items and send the changed data to the server.

P.D.: sorry for my bad english.

**Comment by KaelWD** [comment] 2018-07-06 13:04
Duplicate of #2234

**Closed by KaelWD** 2018-07-06 13:04 UTC
