### ISSUE TITLE
Outline Text Field: label not according to spec

### ISSUE THREAD

**Issue by duebbert** [vuetifyjs/vuetify#4938] opened 2018-08-22 16:02 UTC
### Versions and Environment
Vuetify: 1.2.0-beta.2
Vue: 2.5.17
Browsers: Chrome
OS: Windows 10

### Steps to reproduce
Create a text field: `<v-text-field label="Outline" value="'test'" outline></v-text-field>`

### Expected Behavior
The text field should show as per Material Design spec, i.e. the label on the top outline: https://material.io/design/components/text-fields.html#spec
![image](https://user-images.githubusercontent.com/2813849/44475355-af9eec80-a62c-11e8-8b9d-09499ac6cea8.png)

### Actual Behavior
The label appears inside the outline, not on top of the line:
![image](https://user-images.githubusercontent.com/2813849/44475470-00aee080-a62d-11e8-956a-e5bb35284ca6.png)

### Reproduction Link
https://codepen.io/anon/pen/XPbXyd

**Comment by KaelWD** [comment] 2018-08-22 17:05
Duplicate of #4073

**Closed by KaelWD** 2018-08-22 17:05 UTC

**Comment by AlexVFornazieri** [comment] 2019-02-28 17:45
Hey @duebbert and all,

This feature was really fixed? The "duplicate of" issue apparently  no  show any solution for that and the current Vuetify version reproduce same reported behavior. I need same Material outlined in my project, anyone have a hotfix?

Thanks all

**Comment by duebbert** [comment] 2019-03-01 10:04
Hi @AlexVFornazieri ,

No nothing was fixed on this and all issues raising this problem were just closed as duplicates, so I'm not sure it's even planned. @johnleider did comment in #4073 that this is an MD2 spec item but I cannot see this in Vuetify2 or in any roadmap. @KaelWD do you know?

Many thanks

**Comment by KaelWD** [comment] 2019-03-01 10:39
It'll be in 2.0
