### ISSUE TITLE
[Feature Request] New select-color property on data table

### ISSUE THREAD

**Issue by dmcknight26** [vuetifyjs/vuetify#8952] opened 2019-09-13 19:27 UTC
### Problem to solve
Currently (Vuetify 2) if you enable the select functionality in a data table all checkboxes that appear in the table are gray.  This new feature would allow developers to customize the appearance with other controls in the system by being able to specify the color they should appear as, e.g. 'primary'.

### Proposed solution
Add a new `select-color` property to data tables and, when using the default slots, have it apply to the checkbox that appears in the header as well as the checkboxes that appear on each row.

**Comment by megaroeny** [comment] 2021-05-05 14:59
I'd love to see this too, since the default "gray" selection color isn't very distinct within a busy UI. This would align with other elements that have selections, like list items and selection controls.

**Comment by KaelWD** [comment] 2021-05-05 15:01
Duplicate of #8348

**Closed by KaelWD** 2021-05-05 15:01 UTC
Labels: C: VDataTable, T: feature
