### ISSUE TITLE
[Bug] v-avatar inside list tile action too generic CSS overrides

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#2227] opened 2017-10-18 08:43 UTC
### Steps to reproduce

If you place a `v-avatar` inside a `v-list-tile-action` it always gets its styles overridden which causes problems for some use cases. See https://codepen.io/anon/pen/oGJEOY

### Versions
Latest

### What is expected ?
`v-avatar` should not take any style overrides in `v-list` unless it is placed inside a `v-list-tile-avatar` component.

### What is actually happening ?
The following CSS applies overrides to `v-avatar` even if it is placed outside the `v-list-tile-avatar` component.

```
.list__tile .avatar, .list__tile__action {
    -webkit-box-pack: start;
    -ms-flex-pack: start;
    justify-content: flex-start;
    min-width: 56px;
}
```
I think it would be better if the above CSS is changed to:
```
.list__tile__avatar, .list__tile__action {
    -webkit-box-pack: start;
    -ms-flex-pack: start;
    justify-content: flex-start;
    min-width: 56px;
}
```
### Reproduction Link
https://codepen.io/anon/pen/oGJEOY

**Comment by johnleider** [comment] 2017-11-18 19:30
Duplicate of #1805

**Closed by johnleider** 2017-11-18 19:30 UTC
Labels: enhancement
