### ISSUE TITLE
[Feature Request] menuable updateDimensions dosent take into account right of the activator / window menus goes offscreen

### ISSUE THREAD

**Issue by martea** [vuetifyjs/vuetify#6421] opened 2019-02-08 14:18 UTC
### Problem to solve
Adapt menu popups so they dont go off screen.

### Proposed solution
```
  var _this = this;
            this.checkForWindow();
            this.checkForPageYOffset();
            var dimensions = {};
            // Activator should already be shown
            if (!this.hasActivator || this.absolute) {
                dimensions.activator = this.absolutePosition();
            } else {
                var activator = this.getActivator();
                dimensions.activator = this.measure(activator);
                dimensions.activator.offsetLeft = activator.offsetLeft;
                 // IMPLEMENTATION SUGGESTION
                //TODO:CHECK THAT ACTIVATOR menu element is within the screen showing by the user. 
                //https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect
                // thinking something like this.
                // if(offsetLeft + widthOfElemnt > window.innerWidth){
                //     detachedElementOffsetLeft: (offsetLeft - ( offsetLeft + widthOfElemnt - windowInnerWidth)
               //}
               
 

                if (this.isAttached) {
                    // account for css padding causing things to not line up
                    // this is mostly for v-autocomplete, hopefully it won't break anything
                    dimensions.activator.offsetTop = activator.offsetTop;
                } else {
                    dimensions.activator.offsetTop = 0;
                }
            }
            // Display and hide to get dimensions
            this.sneakPeek(function () {
                dimensions.content = _this.measure(_this.$refs.content);
                _this.dimensions = dimensions;
            });
```

**Comment by KaelWD** [comment] 2019-02-08 14:34
Looks like it's supposed to be a bug report, possible duplicate of #6294. If it's a bug report check for existing issues first and use the correct template with a reproduction link, and if you want to suggest code changes then open a PR because that's unreadable.

**Closed by KaelWD** 2019-02-08 14:34 UTC
