### ISSUE TITLE
[Bug Report] Mobile keyboard reopens after selecting a suggestion from v-select

### ISSUE THREAD

**Issue by mimischi** [vuetifyjs/vuetify#3879] opened 2018-04-19 14:07 UTC
I briefly mentioned it in the `#need-help` channel, because I thought I was doing something wrong and missed an option for `v-select`.

### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.16
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Android

### Steps to reproduce
1) Click on input field. It should now be focused and your keyboard opens up. Also suggestions are shown.
2) Select a suggestion by tapping.
3) Keyboard closes after tapping briefly.
4) Input refocuses and keyboard reopens.

### Expected Behavior
The input is not refocused and the keyboard is not re-opened, after selecting a suggestion.

### Actual Behavior
Input refocuses and keyboard reopens.

### Reproduction Link
[https://codepen.io/anon/pen/dePJeW?&editors=101](https://codepen.io/anon/pen/dePJeW?&editors=101)
This Codepen is just a copy of the code example from the docs: https://vuetifyjs.com/en/components/selects#example-autocomplete

### Other comments
@nekosaur was not able to reproduce it on iOS with Safari. So its either a Chrome/Firefox thing or related to how Android handles things?

**Comment by johnleider** [comment] 2018-05-14 12:38
This should be resolved on v1.1 due to the changes in how we process those events. Would it be possible to check using `vuetify@next` in the pen?

**Comment by KaelWD** [comment] 2018-05-14 12:45
Confirmed fixed on https://next.vuetifyjs.com/en/components/selects#example-autocomplete with chrome 66

**Comment by mimischi** [comment] 2018-05-14 12:54
Looks like it's also fixed in Firefox on my Android device. The keyboard does not close-reopen anymore, just stays open after selecting an option.

**Comment by johnleider** [comment] 2018-05-14 12:54
I'll consider this resolved then.

**Closed by johnleider** 2018-05-14 12:54 UTC
Labels: platform specific

**Comment by johnleider** [comment] 2018-08-25 15:00
If you are still experiencing issues, please create a new issue as this one was resolved, ty.
