### ISSUE TITLE
[Bug Report] Sortable shows up on v-data-table at xs size

### ISSUE THREAD

**Issue by nzprog** [vuetifyjs/vuetify#8062] opened 2019-07-26 15:33 UTC
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Linux x86_64

### Steps to reproduce
Resize browser to xs alternative version and sort option allowed selecting all fields.

This codepen is altered from documentation with "sortable: false" added to all the fields.
 

### Expected Behavior
Only show options that are sortable and no sortable select is none are sortable.

### Actual Behavior
It shows all options which are not "sortable" to be sorted by.

### Reproduction Link
<a href="https://codepen.io/nzprog/pen/bXwXvo" target="_blank">https://codepen.io/nzprog/pen/bXwXvo</a>

### Other comments
Dont know the version of vue on codepen.  first time using codepen

**Comment by ibrahimBeladi** [comment] 2019-07-26 20:48
Duplicate of #8036.

**Closed** 2019-07-26 20:50 UTC
Labels: triage
