### ISSUE TITLE
[Bug Report][3.3.3] VRating doesn't respect size prop at all

### ISSUE THREAD

**Issue by km2442** [vuetifyjs/vuetify#17571] opened 2023-06-09 16:51 UTC
### Environment
**Vuetify Version:** 3.3.3
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 11

### Steps to reproduce
Size of the icon does not change, only spacing between icons is changing. It is example from [docs](https://vuetifyjs.com/en/components/ratings/#size), but it's not working also on custom components.

### Expected Behavior
Size of the icon does change, while using the `size` prop

### Actual Behavior
Size of the icon does not change, only spacing between icons is changing.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtk29rwjAQxr9KuNemgTkYSCfucxhfxPZ02ZK0JGnnJn73XVI6RAeKlEJp7s/veS5c10d4a9ui7xAWUEa0rVERl9IxVta6Z5VRIbxKqPnO4IGlF68a01nHlNF7xyt0Eb2E3EJNPfcqarcfjozZpkbDe2U6JMxcwpgI+idFDjxYZcwYX5ZiJBDxQeZkxEncGOX3OCnxwKdnvjz9jyOUoEWgr1L8rQfMwGj3GYqP0DhanGOqk1CFIGHB1gNHwnuMbVgIUdWOKklf975wGIVrraCVi3r3vZoX9JBEiGOIptuGIsMSaSPdiQS1bRsfuVXtheqQyMo5kmJESucbFlZUJnznorbI68ZmL8+Dl7NwgcHyrW++AnqCSJidySTDd0jdmpYkrtCC9Hr03KOr0aef7L6JLtrOp7pIXU2W1E/pvk8zyG108dkybH4Bfm1W/g==)

**Comment by KaelWD** [comment] 2023-06-13 07:37
Duplicate of #16288

**Closed by KaelWD** 2023-06-13 07:37 UTC
Labels: S: triage
