### ISSUE TITLE
[Bug Report] Сrossed out label

### ISSUE THREAD

**Issue by c-tn** [vuetifyjs/vuetify#9743] opened 2019-11-20 13:05 UTC
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Just set the init value for datepicker with `outlined` attribute in textarea

### Expected Behavior
![Expected](https://i.ibb.co/syXsRPv/expected.png)

### Actual Behavior
![Actual](https://i.ibb.co/nk6mkKd/actual.png)

### Reproduction Link
<a href="https://codepen.io/c_tn/pen/VwwRwRy?editors=1010" target="_blank">https://codepen.io/c_tn/pen/VwwRwRy?editors=1010</a>

**Comment by MajesticPotatoe** [comment] 2019-11-20 13:09
duplicate of #9225

**Closed by MajesticPotatoe** 2019-11-20 13:09 UTC
Labels: triage
