### ISSUE TITLE
[Bug Report][2.5.9] Very bad performance when using large number of text fields inside data table

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#14232] opened 2021-10-04 21:19 UTC
### Environment
**Vuetify Version:** 2.5.9
**Vue Version:** 2.6.14
**Browsers:** Chrome 94.0.4606.61
**OS:** Windows 10

### Steps to reproduce
1. Type something fast in one of the text fields.
2. As you can see, there is a huge lag.

![VTextfield_performance_bug](https://user-images.githubusercontent.com/17653648/135925879-fabb711d-77a0-46b9-b752-f43daf1457ee.gif)

### Expected Behavior
There should be no lag when typing something fast in the text field.

### Actual Behavior
There is a huge lag when typing something fast in the text field.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/oNwrgeQ" target="_blank">https://codepen.io/mikilll94/pen/oNwrgeQ</a>

**Comment by KaelWD** [comment] 2021-10-05 17:25
Duplicate of #6201

**Closed by KaelWD** 2021-10-05 17:25 UTC
Labels: S: triage

**Comment by Mikilll94** [comment] 2021-10-05 18:12
@KaelWD Why have you closed this? The issue which you mentioned is closed but as you can see in my CodePen the performance issue still exist in my case.

**Comment by KaelWD** [comment] 2021-10-07 17:23
We've already spent a lot of time trying to improve this without much luck. It was much worse before v2.0.19 but I think the remaining problems are limitations of vue 2 and our component structure. I haven't done any performance testing on vuetify 3 yet but it should be much faster.

**Comment by SethnBardsley** [comment] 2022-01-21 07:45
@Mikilll94 
As a work around consider replacing v-model="item.value" with :value="item.value" @change="item.value = $event"
This may have knock on effects that would require testing, however it does solve a lot of the optimization issues.
Just keep in mind that @change only tiggers when you click away from the input.

**Comment by WieFel** [comment] 2023-02-13 10:28
Still experiencing the same problem on Vue `2.7.14`.

Working solution I came up with is to wrap (at least) the part containing the `v-text-field` with `v-lazy` (more info [here](https://vuetifyjs.com/en/components/lazy/)).
Like this, the v-textfields are lazily loaded and for me the page works way smoother.
