### ISSUE TITLE
[Feature Request] About "v-expansion-panel-header"

### ISSUE THREAD

**Issue by Benkee** [vuetifyjs/vuetify#10749] opened 2020-03-05 10:17 UTC
### Problem to solve
There are none (to my knowledge) options to align "expanding arrow icon" on the left site.

### Proposed solution
Make a v-expansion-panel-header prop. that the icon can be placed on "start", not just "end".
Maybe something like "align-start".

**Comment by KaelWD** [comment] 2020-03-09 08:52
Duplicate of #9698

**Closed by KaelWD** 2020-03-09 08:52 UTC
Labels: triage
