### ISSUE TITLE
[Bug Report] Expansion Panel animation slow

### ISSUE THREAD

**Issue by victorst79** [vuetifyjs/vuetify#8903] opened 2019-09-09 14:43 UTC
### Environment
**Vuetify Version:** 2.0.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10, Android, iOS

### Steps to reproduce
I have a native android application with a webview, as a default browser I have used my device's browser (Xiaomi Redmi 6A) and also with Google Chrome, but even so the deployment animation of the expansion panel looks very slow and annoying.

I have performed tests with other devices and the fault also occurs in their devices.

### Expected Behavior
Expansion-panel animation be fluid.

### Actual Behavior
Animation of panel expansion very slow and low fluid.

### Reproduction Link
<a href="https://codepen.io/victorst/pen/VwZQoYj" target="_blank">https://codepen.io/victorst/pen/VwZQoYj</a>

### Other comments
I have verified that this problem only occurs with a production version. In development the animations work correctly on this devices.

**Comment by victorst79** [comment] 2019-09-24 14:59
any update on this?

**Comment by KaelWD** [comment] 2019-09-25 00:57
Duplicate of #8298

**Closed by KaelWD** 2019-09-25 00:57 UTC
Labels: triage
