### ISSUE TITLE
[Bug Report][3.0.0-beta.1] There is No tag field in Vuetify

### ISSUE THREAD

**Issue by ps000-simreka** [vuetifyjs/vuetify#14970] opened 2022-04-20 10:47 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Last working version:** 3.0.0-alpha.13
**Vue Version:** 3.2.33
**Browsers:** Chrome 100.0.4896.127
**OS:** Windows 10

### Steps to reproduce
Dear sir/Madam
There is No tag field in Vuetify 

### Expected Behavior
There is No tag field in Vuetify

### Actual Behavior
There is No tag field in Vuetify

### Reproduction Link
<a href="https://codepen.io/virtualadrian/pen/pOeVPX" target="_blank">https://codepen.io/virtualadrian/pen/pOeVPX</a>

### Other comments
There is No tag field in Vuetify

**Comment by KaelWD** [comment] 2022-04-20 10:51
Duplicate of #14969

**Closed by KaelWD** 2022-04-20 10:51 UTC
Labels: S: triage
