### ISSUE TITLE
[Documentation] doc for v-list-item-group and prop "value" is incorrect

### ISSUE THREAD

**Issue by MathieuDerelle** [vuetifyjs/vuetify#12320] opened 2020-09-30 13:48 UTC
### Environment
**Vuetify Version:** 2.3.12
**Vue Version:** 2.5.18
**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.7

### Steps to reproduce
read the doc ^^

### Expected Behavior
As shown in the examples
https://vuetifyjs.com/en/components/list-item-groups/#props
v-model is used to select item(s)

So the correct description should be "value(s) of selected item(s)" 

Which could be applied to v-item-group's value description too, the current description :
"The designated model value for the component." does not explain anything

### Actual Behavior
doc states "Expands / Collapse list group"
(which is the actual description of v-list-group's value)

### Reproduction Link
<a href="https://vuetifyjs.com/en/api/v-list-item-group/" target="_blank">https://vuetifyjs.com/en/api/v-list-item-group/</a>

**Comment by MajesticPotatoe** [comment] 2021-06-25 01:05
This has been resolved.
duplicate of #12835

**Closed by MajesticPotatoe** 2021-06-25 01:05 UTC
Labels: C: VList, T: documentation
