### ISSUE TITLE
[Bug Report][3.0.0-beta.12] v-dialog not centered

### ISSUE THREAD

**Issue by BennieVE** [vuetifyjs/vuetify#15843] opened 2022-10-05 09:47 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.12
**Last working version:** 3.0.0-beta.10
**Vue Version:** 3.2.38
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
create a dialog with an element that has limited width. Activate the dialog

### Expected Behavior
Dialogs must be centered

### Actual Behavior
Dialog is left justified

### Reproduction Link
<a href="https://codepen.io/christiaanben/pen/poVZerB" target="_blank">https://codepen.io/christiaanben/pen/poVZerB</a>

**Comment by moltinginstar** [comment] 2022-10-10 04:47
Not sure if this is intended behavior, but setting the width on `v-dialog` instead of the child element solves the issue.

**Comment by Flamenco** [comment] 2022-10-10 06:40
Set the width on the dialog instead of the card.

```js
<v-dialog v-model="dialog" width='32em'>
```

**Comment by stratdev3** [comment] 2022-10-17 21:56
By default, dialog is width 100% minus the margin.
If you set the width and max-width on the card which is left align from its (background transparent) parent (the v-dialog), you think of a bug but the render is correct.

The way of using width is to set it on the v-dialog like you said.

It's not a bug and you can close the issue

**Closed** 2022-10-24 20:51 UTC
Labels: layer 8 issue, C: VDialog
