### ISSUE TITLE
[Bug Report] VIcon SVG Vertical Alignment in VListItemIcon

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#10472] opened 2020-02-05 16:59 UTC
### Environment
**Vuetify Version:** 2.2.9
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.87
**OS:** Windows 10

### Steps to reproduce
Open the repro and note the `mdiClose` icons at the end of each list item row.

### Expected Behavior
The svg icons should be vertically aligned center.

### Actual Behavior
The svg icons are vertically aligned about 4px lower than center.

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-mdisvg-v-icon-spacing-bug-wpx3g" target="_blank">https://codesandbox.io/s/vuetify-mdisvg-v-icon-spacing-bug-wpx3g</a>

### Other comments
This appears to be a regression from v2.2.8.

**Comment by DRoet** [comment] 2020-02-06 07:38
duplicate of https://github.com/vuetifyjs/vuetify/issues/10480

**Closed by DRoet** 2020-02-06 07:38 UTC
Labels: triage
