### ISSUE TITLE
[Feature Request] v-select multiple not showing items having same name but different id

### ISSUE THREAD

**Issue by sidhant-rajan** [vuetifyjs/vuetify#7014] opened 2019-04-17 14:58 UTC
### Problem to solve
I have an array of objects. For some objects in the array, the property `name` is the same but `id` is different. So, `v-select` should show all the items of the array but it is removing duplicate objects based on `name` property of an object. 

It can help users in many cases where the object is different but `name` in the object is similar.

### Proposed solution
I went through the `v-select` code and found that the items are filtered out. I am not sure if this is causing this issue or not?

### How to reproduce

Consider an array
```
items: [{ "name": "Test1",  "id": 1 }, { "name": "Test1",  "id": 2 }]
```
And i want the whole object as return value so i can't explicitly set `item-value`.
Then, v-select with `multiple` attribute on shows only one item :(

**Comment by KaelWD** [comment] 2019-04-17 15:00
Possible duplicate of #4633

We have a bug report template for a reason.

**Comment by sidhant-rajan** [comment] 2019-04-17 15:05
> Possible duplicate of #4633
> 
> We have a bug report template for a reason.

I have added the `how to reproduce` section. Can you just take a look at it?

**Comment by KaelWD** [comment] 2019-04-17 15:08
> i want the whole object as return value 

`return-object`

item-text and item-value are required to identify each object if you aren't using the default structure.

**Closed by KaelWD** 2019-04-17 15:08 UTC
Labels: S: needs reproduction, triage
