### ISSUE TITLE
[Bug Report] v-card inside v-dialog then v-card-text has no top padding

### ISSUE THREAD

**Issue by poganytamas** [vuetifyjs/vuetify#8679] opened 2019-08-22 13:31 UTC
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
When a v-card is not embedded into a v-dialog, then v-card-text has top padding. When it is inside a v-dialog, then it loses the top padding.

### Expected Behavior
v-card-text should have top padding

### Actual Behavior
v-card-text loses top padding

### Reproduction Link
<a href="https://codepen.io/poganytamastsys/pen/ZEzLGLO" target="_blank">https://codepen.io/poganytamastsys/pen/ZEzLGLO</a>

**Comment by obennaci** [comment] 2019-09-04 10:56
This seems to be caused by https://github.com/vuetifyjs/vuetify/pull/8382 which assumes every dialog has a title.
We could add top padding if `v-card-text` is the first child

**Comment by johnleider** [comment] 2021-05-22 20:42
fixed in #13674

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-05-22 20:42 UTC
Labels: C: VCard, C: VDialog, T: bug
