### ISSUE TITLE
DropDown AutoComplete Not working

### ISSUE THREAD

**Issue by montepjones** [vuetifyjs/vuetify#1408] opened 2017-08-18 15:55 UTC
### Steps to reproduce
https://vuetifyjs.com/components/selects
#5 is not working

### Versions

Whatever is on the current homepage
### What is expected ?

Type ahead dynamically change the list

### What is actually happening ?

List is not changing. Was working on 0.14.8. 
### Reproduction Link

https://vuetifyjs.com/components/selects
#5

**Comment by montepjones** [comment] 2017-08-18 16:24
could just be the site?
https://codepen.io/montepjones/pen/qXxVyW

**Comment by johnleider** [comment] 2017-08-19 00:30
duplicate of #1321

**Closed by johnleider** 2017-08-19 00:30 UTC
Labels: duplicate
