### ISSUE TITLE
[Bug Report] VInput: outlined fieldset legend clipped when dynamically shown

### ISSUE THREAD

**Issue by Pwntus** [vuetifyjs/vuetify#7470] opened 2019-06-11 21:54 UTC
### Versions and Environment
**Vuetify:** 2.0.0-beta.1
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Linux x86_64

### Steps to reproduce
1. Create an outlined `VTextField`, `VTextarea` or `VSelect` with a default value so that the fieldset legend is initially set/shown at the top.

2. Place the previously created element in a wrapper with `display: none`.

3. Dynamically (through JavaScript) change the wrapper style to `display: block`.

### Expected Behavior
The fieldset legend will have a width in pixels corresponding to the fieldset legend text width. This makes the outlined border not "strike" the fieldset legend text.

### Actual Behavior
The fieldset legend will have a width of `6px` regardless after the wrapper style is dynamically changed, thus making it appear "clipped" with the outlined border.

### Reproduction Link
<a href="https://codepen.io/anon/pen/mZyEmE" target="_blank">https://codepen.io/anon/pen/mZyEmE</a>

**Comment by jacekkarczmarczyk** [comment] 2019-06-12 05:58
This is because of how we calculate the dimensions of the label - offsetWidth is 0 when it's hidden. Probably could be done by creating a visible copy of the label, but that could be inefficient with a large amount of inputs, I'd say this is `won't fix` and advise to use `v-if` instead of hiding the fields with css

**Comment by Pwntus** [comment] 2019-06-12 15:53
Yes, it's true that in most cases `v-if` would solve the current issue. However, there are cases where you don't want to use `v-if`, such as preserving the "state" of the wrapper content while hiding the wrapper.

Very related is the following issue, where `v-if` is used to show/hide the wrapper but the `label` property is dynamically changed after the fieldset legend has been rendered: https://codepen.io/anon/pen/agOzJv

A visible copy of the label sounds like a workaround and, as you suggest, should probably be avoided. I haven't studied the code behind this but maybe the calculation of the dimensions should be revisited to be more flexible?

**Comment by jacekkarczmarczyk** [comment] 2019-06-12 16:01
Before first showing you don't need any state, possible workaround: https://codepen.io/anon/pen/zVGxbB

**Comment by Pwntus** [comment] 2019-06-12 16:09
Take for an example: a "Vuetify form builder" (this is in fact what I'm building in my application) where a user-provided JSON-string is parsed and rendered as a Vuetify-form with different elements utilizing `VTextField`. It is currently impossible to dynamically render the final `VTextField` element without running into issues with clipping fieldset legends.

**Comment by johnleider** [comment] 2019-06-14 15:24
Beyond the suggestion that @jacekkarczmarczyk provided, you could also use a dynamic key to force re-rendering of the inputs. This will also retain the state of the inner items.

https://codepen.io/johnjleider/pen/rExOod

Otherwise, there is not much we can do.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2019-06-14 15:24 UTC
Labels: C: VTextField, triage

**Comment by Pwntus** [comment] 2019-06-14 16:32
Thanks for all input, using a dynamic key solves the issue :smile:

**Comment by pklitscher** [comment] 2019-08-07 09:40
Team, 

I am having this problem using inputs inside `<v-window>`. I have tried the v-if and dynamic key hack but it doesn't seem to be working. I am assuming because the label is calculated while it is still transitioning. The only way I can come up with is a showContent value toggled using a timeout. But that is getting pretty hacky and difficult to manage. Putting inputs inside a window doesn't seem out of pattern is there a better way to manage this.

https://codepen.io/pklitscher/pen/gVvjwZ?editors=1010

**Comment by n3ps** [comment] 2019-09-19 18:23
Same problem if the input fields are within an `<iframe>`.

**Comment by BenjaminBorlet** [comment] 2019-10-02 08:15
Same issue inside v-stepper

**Comment by Alluuu** [comment] 2019-10-19 12:07
Same thing with expansion panel. And even when using the v-if, it's still clashing/collapse'ing into the label.

I have dynamically generated expansion panels with v-for, and even if I make the v-if based on the index in v-expansion-panel v-model (didn't find any other good way) it still clashes.

I have form elements in every expansion panel content that I wanted visible upon opening.

**Comment by Alluuu** [comment] 2019-10-19 12:26
Tried also to make the key dependent by the opening state:
`<v-expansion-panels v-model="openTab">`
and
`<v-expansion-panel-content>
          <div v-for="(field, index) in baseFields" :key="index + '-' + openTab">
            <v-text-field
...`

But all it did was slow down (complete lagging) the opening and closing process, but clashing remained

**Comment by DukeOfChutney** [comment] 2019-10-22 16:08
My workaround was inspired by [this similar Material-UI issue](https://github.com/mui-org/material-ui/issues/14530), where one suggestion was to make the label border white. 

Using [this Stackoverflow](https://stackoverflow.com/questions/50985783/vuetify-css-not-working-taking-effect-inside-component) answer as guidance: 

```
    >>>label{
        background-color:white 
    }
```

**Comment by mahammad8564** [comment] 2019-10-30 12:17
> Same issue inside v-stepper

got the same issue

**Comment by mahammad8564** [comment] 2019-10-30 12:35
> Same issue inside v-stepper

`
<v-stepper-items>
  <v-stepper-content step="1">
    <step-one v-if="step == 1" />
  </v-stepper-content>
  <v-stepper-content step="2">
    <step-two v-if="step == 2" />
  </v-stepper-content>
  <v-stepper-content step="3">
    <step-three v-if="step == 3" />
  </v-stepper-content>
</v-stepper-items>
`

**Comment by mahammad8564** [comment] 2019-10-30 12:49
> Same issue inside v-stepper

@BenjaminBorlet, try this.

`<v-stepper-items> <v-stepper-content step="1"> <div v-if="step == 1" /> </v-stepper-content> <v-stepper-content step="2"> <div v-if="step == 2" /> </v-stepper-content> <v-stepper-content step="3"> <div v-if="step == 3" /> </v-stepper-content> </v-stepper-items>`

**Comment by anjayluh** [comment] 2019-11-01 05:46
@TrobbinsForNow your temporal fix works for me for now. I would love a permanent fix but let me use this for now. Thanks

**Comment by ErneMiralles92** [comment] 2019-11-19 15:11
I had the same problem and I fix it setting the v-text-field initial value in the mounted().

**Comment by spencercap** [comment] 2019-11-20 05:51
Note that there are some undesired results that seam related to this issue when introducing the `prepend-inner-icon` attribute too:
https://codepen.io/spencercap/pen/vYYbbqg 

<img width="200" alt="Screen Shot 2019-11-19 at 9 50 50 PM" src="https://user-images.githubusercontent.com/4987509/69212610-ac87fa00-0b16-11ea-835a-4734b3011195.png">

**Comment by wendelicious** [comment] 2019-12-12 06:48
^^^ I am experiencing what @spencercap

**Comment by danielchodusov** [comment] 2019-12-17 12:23
I'm having the same problem with v-text-field with dynamic label in tabs. Tried to add key on v-text-field but didn't really help. Any help how to fix this, would be really appreciated. 

```
<v-tab-item key="tab-item-pick" value="tab-pick">
    <v-text-field autofocus hide-details :loading="urlLoading" v-model="selectedImageNodeSrc" :label="$t('href_link')" outlined clearable></v-text-field>
</v-tab-item>
```


![ezgif-4-22256f5692e2](https://user-images.githubusercontent.com/4260378/70995154-24beec80-20d0-11ea-8ff4-d817181a26ae.gif)

**Comment by spencercap** [comment] 2020-01-09 09:47
@danielchodusov looks like you just need some padding or margin between your tabs items and content. (not a text-field issue)

**Comment by spencercap** [comment] 2020-01-09 10:13
@Alluuu I forked your pen with a minor tweak - putting the key on the `v-expansion-panel-content` element - and it seems to work.

fixed outlined text-field label overlap inside expansion panel:
https://codepen.io/spencercap/pen/XWJEMrq

**Comment by musasoftlabx** [comment] 2020-03-15 16:08
hi @jacekkarczmarczyk , this seems like a major issue affecting many people. Even with the v-app, it still does the same. I found a temp fix.

Add this to your styles css in the component.
.v-label.theme--light.error--text {
left: 0 !important;
}
.v-label.v-label--active.theme--light {
left: -27px !important;
}

This issue affects outlined inputs in expansion panels & steppers
For instance, this,
![image](https://user-images.githubusercontent.com/13678931/76705316-35432b00-66f0-11ea-90bb-0c44f36a689d.png)

Changes to this
![image](https://user-images.githubusercontent.com/13678931/76705257-bcdc6a00-66ef-11ea-90ec-cb134dc22fb6.png)

**Comment by tmcdos** [comment] 2021-04-10 12:24
The problem arises when the icon comes from a webfont - the width of the **prepend-inner** slot is calculated in `vuetify/lib/components/VTextField/VTextField.js` at function `setPrependWidth()`. But this function is called before the browser has completed loading the webfont - so we get wrong width which is not updated unless the browser window is resized.
To fix the issue, `prependWidth` should be converted to a computed property:
```javascript
computed:
{
      prependWidth() {
      if (this.$el && this.outlined)
      {
        const prepend = this.$el.querySelector('.v-input__prepend-inner');
        if (prepend) return prepend.offsetWidth;
      }
      return 0;
    },
    .....
}
```
and the body of the original `setPrependWidth()` function should be commented out.
The patch is attached.
[vuetify#2.4.6.patch.txt](https://github.com/vuetifyjs/vuetify/files/6289820/vuetify.2.4.6.patch.txt)

**Comment by johnleider** [comment] 2021-04-14 02:06
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
