### ISSUE TITLE
[Bug Report][3.3.1] v-select does not close after the menu item is activated by keydown and another v-select is opened by clicking

### ISSUE THREAD

**Issue by martinjirku** [vuetifyjs/vuetify#17488] opened 2023-05-29 09:51 UTC
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click on "Select1"
2. use the arrow down to highlight the first item
3. click on "Select2" to open it

### Expected Behavior
"Select1" will be closed and "Select2" opened

### Actual Behavior
"Select2" opens, but "Select1" stays opened

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1U01v2zAM/SucLt6A2EI+TkY6dLfdd9ihysG1mVWrviApGYrA/32UbLSO0xZFi9oHm+Qjn/j8fHNiP5yrjgdkNdtG1E41Eb8LA7A9lo1z+TUHrTWxkQb9mMpJb/89hiNKTRI5FVBhG6dJgFY1IVwJJolSsPMaHaHFO6s69IT4lbuXc1Ct0RxK561LY07nRbqEEfHp7i/aE3HqvLnohBPc40MNywVEGRXWUOTnsoB+8SJ6NUOvnkPvzo/Bp9LxuXafJ+bqHWqsZ/utX1VjM0NvPqhGip+sNlSnbkyZwaxbPjExhaH10kUIGA+Dl6V21kc6qMc99LD3VkNB/i8SnLS0JkTQ4Q9cJcTX4icqZeG39ar7UnxLBMNIGsYWbJhW6sZVf4M19BNlK9K3yIUgWA2jOQUjlhQLdhejCzXnbWeorUMlj74yGLlxml8TjPuDiVJj2Vl9va7W1YZ3MsRpusKgy1sSJaCnIYKN+maaKPcPb6AakZlhOTCMqVI1tyFRXIzmxHdEX3o05Cn0b91o1jbdala62Cyx98L0pLeS5j7MpG5Dlnn07gdXzsPSpF0i7Bcsn5OYcwPb/QdRGIh5)

**Comment by heaven-born** [comment] 2023-05-30 18:28
Look like the issues are related, so in addition to this bug I see one more problem: once `ref` value attached to `menu`  becomes 'true' it never changes even when the menu is closed. And probably because of this, it is not possible to open the menu again by changing the ref and not possible to close it by changing the ref value.

**Comment by KaelWD** [comment] 2023-06-11 06:23
Duplicate of #16819

**Closed by KaelWD** 2023-06-11 06:23 UTC
Labels: T: bug, C: VSelect
