### ISSUE TITLE
[Bug Report][3.0.6] Items overlap input in autocomplete

### ISSUE THREAD

**Issue by HendrikJan** [vuetifyjs/vuetify#16365] opened 2023-01-03 15:14 UTC
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.45
**Browsers:** Google Chrome, Firefox 108.0
**OS:** Ubuntu undefined

### Steps to reproduce
* Open the reproduction in Google Chrome
* Click on the autocomplete input
* See that there are so many options that they overlap the input field so you cannot see what you are typing

### Expected Behavior
The list of items show above or below the input (depending on where the most space is) when there are many items

### Actual Behavior
The list of items goes from the top to the bottom of the browser window, overlapping the input field

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVE1v4jAQ/SsjSytalSRVd7dapbTqXvbjtIfurekhgQG8dWzLdigV4r/vjEMQIbQqB2DmvXmeef543Ijv1qarBkUuJgFrq8qAd4UGmKyS0tr4NwZ1KfUuAngwNU4qt4//4jocxr/Q9XFzGB1XP6DCaa/+jw3SaN9LrdCp0h6mfmvbhC7gfptgpoZmwIBduvvQAGaG6rYQcydRz3whjim5JAM8MSwa0hgSVqWTpQ6sIZXC2ZAxXUrrB0llfFkpTE6jRhlHkpVqMFk4fE2UXCwD6uRqqK/KKs7QOjbEeYIkyKCQSLqsTwwRKauSVnuTUjcqSHagl9/b3n3254XM9cqEnOcj0Q1YZ6wfx6VgW4hBZdwtZlNlJfWMPeeSQkAe6ChRzLWpK1/StsW7SdZWDLvIesf23QZZ9OMNKulDwpQhyuep3/gpTt7txNEwJ7m+qQb0hTONPcWPduz7+7gnXHZ4S7rrTen9/Y6cePN7MhT6qZM2gMfQMCxra1yADTicwxbmztQwoqdkxOQpXd9AuXjX4JY5Z49P5zcd0t6xHgBQ6LlxcEadwfr28gbWk2/8fXFxDhvG26I0nt7UNn55FtMA7GsOox9xORjBBazHLRItJOgn/7bIp2uGtueF3saxsnYumkiMRTsUuWHTf95oehbjErQpEaCdztteOEfDclyIZQjW51nWaPu8SMnd7J6wzDU6yBqTmanvP6dX6Zev2Yw27TCfoq+TypkXj45WLMSu7yge5Pz1rQV2MOleptet7C7FkgOpjPTpBU0cGUSPs3u37yNur/cjbNB/9JasJS+V1M/+yMapjxY+PjFlOxatNJHjHOLpP8398ZM=)

### Other comments
Firefox tends to hang with the above reproduction sometimes.

**Comment by mhio** [comment] 2023-01-04 04:45
When setting a `menu-props`/`maxHeight` limit to work around this, you might run into https://github.com/vuetifyjs/vuetify/issues/16257

**Comment by KaelWD** [comment] 2023-01-04 17:33
Duplicate of #15587

**Closed by KaelWD** 2023-01-04 17:33 UTC
Labels: S: triage
