### ISSUE TITLE
[Bug Report] <v-text-field outline> inconsistent height compared to <v-select outline> <v-combobox outline> etc

### ISSUE THREAD

**Issue by henriq-88** [vuetifyjs/vuetify#5701] opened 2018-11-22 02:18 UTC
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Mac OS 10.14.1

### Steps to reproduce
Create a `<v-text-field>` with the `outline` prop.
Create a `<v-select>` with the `outline` prop.
Compare the heights.

### Expected Behavior
The `<v-text-field>` should be as tall as the `<v-select>`.

### Actual Behavior
The `<v-text-field>` is not as tall as the `<v-select>`.

### Reproduction Link
<a href="https://codepen.io/henriq88/pen/JepvaN?&editors=101" target="_blank">https://codepen.io/henriq88/pen/JepvaN?&editors=101</a>

### Other comments
`<v-text-field solo>`, `<v-text-field box>`, and `<v-text-field flat>` are consistent with their corresponding sister components though, as seen in the included reproduction link.

**Comment by jacekkarczmarczyk** [comment] 2018-11-22 04:02
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5485

**Closed by jacekkarczmarczyk** 2018-11-22 04:02 UTC
