### ISSUE TITLE
[Feature Request] Both v-dialog and its nested v-time-picker are surprisingly closed with a single click

### ISSUE THREAD

**Issue by cb109** [vuetifyjs/vuetify#5200] opened 2018-10-01 14:10 UTC
### Versions and Environment
Vuetify: 1.2.5
Vue: 2.5.1
Browsers: Chrome 68
OS: Ubuntu 18.04

### Steps to reproduce

Open the dialog, open the time picker, choose any hour and then click a minute value so that the area where you click is outside of the v-dialog's frame (but still inside the v-dialog).

### Expected Behavior

The time picker should close, but the dialog should not.

### Actual Behavior

Both the time picker and the dialog are being closed.

### Reproduction Link

https://codepen.io/cb109/pen/RePBrV?editors=1011
---

### Additional Comments:

As john has stated, clicking outside BOTH the time picker and the dialog is actually expected to close the both of them, as we can see here:
![peek 2018-10-01 15-51](https://user-images.githubusercontent.com/6052590/46293616-55326d80-c594-11e8-871e-ccf988d44803.gif)

However, clicking inside the time picker, even if that area is not enclosed by the dialog's frame, should not close the dialog, but does, as we can see here:
![peek 2018-10-01 16-01](https://user-images.githubusercontent.com/6052590/46293649-69766a80-c594-11e8-82f0-77bae7356057.gif)

**Comment by cb109** [comment] 2018-10-01 14:12
We can have a basic workaround by setting the dialog as `persistent` as long as the time picker is opened, see: https://codepen.io/cb109/pen/xyGaNJ?editors=1011

**Comment by johnleider** [comment] 2018-10-06 02:28
I don't know if this is something we can actually do anything for unless we make `v-menu` a dependent implementing component. Thoughts @vuetifyjs/dev-team

**Comment by husayt** [comment] 2018-12-14 19:39
I have also stumbled upon this one. After couple of hours gave up on timepicker.

**Comment by KaelWD** [comment] 2018-12-15 14:31
Duplicate of #5310, this doesn't have anything specific to pickers.

**Comment by lebesnec** [comment] 2018-12-19 21:50
For some reason the date picker doesn't have this problem...

**Comment by lebesnec** [comment] 2018-12-19 21:53
And since my dialog is in a different component than the time picker I can't use the workaround :(

**Comment by jacekkarczmarczyk** [comment] 2018-12-20 03:19
Another workaround (green works, red doesn't): https://codepen.io/anon/pen/qLRZXz?editors=1010

**Comment by KaelWD** [comment] 2018-12-20 03:34
I was mistaken, skimmed over the issue thinking the first gif was the problem.

**Comment by loveyourstack** [comment] 2019-02-25 12:51
Just noting that it's the click **down** which closes the time picker, and the ensuing click **up** closes the dialog. A workaround for a (patient) user is to click the time, hold down the mouse, move the pointer to within the dialog, and release it.

**Closed** 2019-03-20 15:21 UTC
Labels: T: bug
