### ISSUE TITLE
[Bug Report] Buttons should not force text to uppercase

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [vuetifyjs/vuetify#10693] opened 2020-02-27 22:49 UTC
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Firefox 73.0
**OS:** Windows 10

### Steps to reproduce
Not required

### Expected Behavior
Buttons should display text as received *not* force it to upper case.

### Actual Behavior
Uppercases any text without the ability to stop that from happening.  

### Reproduction Link
<a href="https://codepen.io/johnjleider/pen/MWYdwXx" target="_blank">https://codepen.io/johnjleider/pen/MWYdwXx</a>

### Other comments
This may also be a serious localization issue as well.

**Comment by KaelWD** [comment] 2020-02-28 03:11
Duplicate of #3948

**Comment by WhatFreshHellIsThis** [comment] 2020-02-28 15:58
Hold up a second @KaelWD . I did a search before posting this and didn't find anything because 3948 confusingly uses the term "capslock" in the title instead of upper case or uppercase which is what this technically is.  Also, #3948 has several comments about how this is documented and it's just not, even when I follow the links people posted.  Also there was apparently a change with helper classes which closed that issue but, when you look into it does *not* have any class related to this issue.   This is not documented properly anywhere and there are several conflicting messages in that case.  I don't see how 3948 helps or resolves this issue.  At the very least there should be some guidance on this in the documentation as it appears to be a common issue.  Rather than closing this can we change it to fix the missing documentation or do you really think something was fixed in #3948 and I'm missing it?

**Comment by KaelWD** [comment] 2020-02-29 04:21
`class="text-none"` still works, and there's a `$btn-text-transform` sass variable.

**Comment by johnleider** [comment] 2020-12-16 17:45
This is part of the material design specification and can be modified through sass and css utility classes.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-16 17:45 UTC
Labels: C: VBtn, T: documentation, duplicate
