### ISSUE TITLE
[Bug Report] v-app-bar hide-on-scroll is hiding when forcing scroll top (Safari only)

### ISSUE THREAD

**Issue by guilhermewaess** [vuetifyjs/vuetify#10533] opened 2020-02-10 13:09 UTC
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Safari
**OS:** Mac OS 10.14.5

### Steps to reproduce
1- Enable design mode on safari
2- Scroll to the bottom until the bar disappears
3- Using the mac trackpad or the mobile scroll, scroll back to the top, bouncing a bit on top

### Expected Behavior
The app-bar should be visible.

### Actual Behavior
The app bar disappears like scrolling to the bottom

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-scroll-bug-ios-cheqn" target="_blank">https://codesandbox.io/s/vuetify-scroll-bug-ios-cheqn</a>

### Other comments
I've got this bug happening on safari running inside an iPhone X, but it's also possible to reproduce on safari desktop.

![2020-02-10 13-59-33 2020-02-10 14_00_54](https://user-images.githubusercontent.com/5339165/74152438-93bb4c00-4c0e-11ea-8192-09a6aa9237fa.gif)

Thank you to @yannbf, helping to reproduce the bug

**Comment by KaelWD** [comment] 2020-02-10 13:21
Duplicate of #9993

**Closed by KaelWD** 2020-02-10 13:21 UTC
Labels: triage
