### ISSUE TITLE
Ripples are part of the selection area for radio buttons and checkboxes.

### ISSUE THREAD

**Issue by FINDarkside** [vuetifyjs/vuetify#5233] opened 2018-10-06 14:36 UTC
### Versions and Environment
Vuetify: 1.2.6
Browsers: Chrome 69, Edge 17, Firefox 62
OS: Windows 10

### Expected Behavior
Ripples don't affect the hitbox of the component.

### Actual Behavior
Ripples affect the hitbox of the component. Also, because they are so huge, you can actually click a radio button, but another radio button gets selected because the hitboxes overlap. I'm not exactly sure if this is intended, but considering how badly the areas overlap even in the vuetify demo page, I doubt it. Here's image demonstrating hitboxes: https://i.imgur.com/Rwfs2ei.png

The placing of the buttons is from: https://vuetifyjs.com/en/components/selection-controls#example-radios-colors
### Reproduction Link
[CodePen](https://codepen.io/anon/pen/qJaVVJ)

**Comment by johnleider** [comment] 2018-10-09 15:43
Duplicate of #2661

**Closed by johnleider** 2018-10-09 15:43 UTC
