### ISSUE TITLE
[Bug Report][3.1.15] closable VChip in v-for loop removed twice

### ISSUE THREAD

**Issue by DanielBuchberger** [vuetifyjs/vuetify#17200] opened 2023-04-21 12:54 UTC
### Environment
**Vuetify Version:** 3.1.15
**Vue Version:** 3.2.47
**Browsers:** Firefox 112.0
**OS:** Ubuntu undefined

### Steps to reproduce
Close first chip (foo)

### Expected Behavior
remove 1 chip

### Actual Behavior
2 chips are removed

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUMluwjAQ/ZWRLwEpiUUXVUKA6HcQDlkmwiWxLdukaqP8e8c2VBQuSD3Zb5a3zG5k71rnwwnZkq0c9rorHW4KCbAaslLr8A2gL4U8o4Drg9AwZK0y64LNBO2mIOYgJPi/LRjUnbJl1SFs607Ux6XHSMOhn1tNRZyJFBbzgm1gHMMiTNOKR/aLNsFfcQ+irRW/skvQ1kZoBxbdybdFr5VxMILBFiZojeohoZyJH66VtC76hLWfmO2SVqkkhaQqTXy+k/3cq0ReYmQpi6TkRucfVkm62ehNUaTQoNBLCBVfIzGPC3ZwTtsl53Ujaa3BTgwml+i41D3f0hg3J+lEj1mj+u1z/pS/vPFGWHddz9H2WWXUp0VDLAVLr3ScaL8e0DpPksQiX7xGiXMt68rKeo07bk6CA5rMoGzQoHk0083an1w3vbtsXn4q5EQn74Q82ptr1zZcendx+b/Qgc1T7b3ilLLolLTjCtv/AL5QDUc=)

### Other comments
It seems that the items array is spliced correctly (1 item is removed).
When deleting the last chip, it behaves as expected.

**Comment by runyasak** [comment] 2023-04-21 15:37
`splice` would get deleted items as return value.
You can read more from [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice#return_value).

Please, change to `slice`, so it works as your expectation.

[Demo here](https://play.vuetifyjs.com/#eNqlUMluwjAQ/ZWRLwEpiUUXVUKA6HcQDlkmwiWxLdukaqP8e8c2VBQuSD3Zb5a3zG5k71rnwwnZkq0c9rorHW4KCbAaslLr8A2gL4U8o4Drg9AwZK0y64LNBO2mIOYgJPi/LRjUnbJl1SFs607Ux6XHSMOhn1uq4UyksJgXbAPjGPZgmlY8kl+kCf5qexBdrfiVW4K2NkI7sOhOvi16rYyDEQy2MEFrVA8JxUz8cK2kddEmrP3EbJe0SiUpJFVp4vOd7OdeJfISI0tZJCU3Ov+wStLJRm+KEoUGZV5CqPgaiXlcsINz2i45rxtJaw12YjC5RMel7vmWxrg5SSd6zBrVb5/zp/zljTfCuut6jrbPKqM+LRpiKVh6peNE+/WA1nmSJBb54jVKnGtZV1bWa9xxcxIc0GQGZYMGzaOZbtb+5Lrp3WXz8lMhJzp5J+TR3ly7tuHSu4vL/4UObJ5q7xWnlEWnpB1X2P4Ha6oM1w==)

**Comment by KaelWD** [comment] 2023-04-21 17:16
Duplicate of #16364

**Closed by KaelWD** 2023-04-21 17:16 UTC
Labels: S: triage
