### ISSUE TITLE
[Bug Report] Width of v-footer is not properly set when using both inset and absolute

### ISSUE THREAD

**Issue by cecilwei** [vuetifyjs/vuetify#9372] opened 2019-10-16 07:52 UTC
### Environment
**Vuetify Version:** 2.1.4
**Last working version:** 1.5.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.15.0

### Steps to reproduce
In vuetify 1.5, we were using `<v-footer app inset absolute>` to allow footer to stay at bottom and not overlapped with navigation drawer. In the footer, we have our content aligned to the end, which is not visible in vuetify 2 as the footer is grow beyond the right margin of the whole app.

### Expected Behavior
The right margin of v-footer stays within v-application.

### Actual Behavior
The right margin of v-footer exceeds the boundary of v-application.

### Reproduction Link
<a href="https://codepen.io/orino76/pen/eYYzBqJ" target="_blank">https://codepen.io/orino76/pen/eYYzBqJ</a>

**Comment by Mikilll94** [comment] 2019-11-11 12:36
Is it going to be solved? Because right now **v-footer** component is useless when having navigation drawer.

**Comment by c0lt** [comment] 2019-11-11 14:27
As a temporary fix, you could use this code in your CSS:
```
.v-footer--absolute {
  width: auto !important;
}
```
or add it as style-prop to v-footer `style="width: auto !important"`

**Comment by c0lt** [comment] 2019-11-15 14:47
see https://github.com/vuetifyjs/vuetify/issues/8128

**Comment by jacekkarczmarczyk** [comment] 2019-11-15 14:51
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8128

**Closed by jacekkarczmarczyk** 2019-11-15 14:51 UTC
Labels: C: VFooter, triage
