### ISSUE TITLE
[Bug Report] Tooltip HTML places activators as siblings, instead of children

### ISSUE THREAD

**Issue by xyannik** [vuetifyjs/vuetify#8777] opened 2019-08-29 07:46 UTC
### Environment
**Vuetify Version:** 2.0.11
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Create a tooltip with a span as activator.
https://imgur.com/a/W22KGHU

### Expected Behavior
The span should be placed as a child of `.v-tooltip`

### Actual Behavior
The span is placed as a sibling after `.v-tooltip`

### Reproduction Link
<a href="https://jsfiddle.net/oqa58hjr/" target="_blank">https://jsfiddle.net/oqa58hjr/</a>

### Other comments
Is this expected behaviour, or a bug? Wouldn't want to change my CSS everywhere, only to see it changed again in the next update.
https://imgur.com/a/W22KGHU

**Comment by jacekkarczmarczyk** [comment] 2019-08-29 07:47
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6951

**Closed by jacekkarczmarczyk** 2019-08-29 07:47 UTC
Labels: triage
