### ISSUE TITLE
[Bug Report][3.1.15] TS props error on custom HTML attributes (id, data-testid)

### ISSUE THREAD

**Issue by lucaspagliari1bigmedia** [vuetifyjs/vuetify#17196] opened 2023-04-20 21:37 UTC
### Environment
**Vuetify Version:** 3.1.15
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a component using `<script lang="ts">` and assign a custom attribute such as id, type or data-testid, this shows an error on vscode about prop's type

### Expected Behavior
Can assign custom attributes to vuetify components, such as id, type, data-testid or test-id

### Actual Behavior
Can only assign attributes that are defined on components props

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkctu20AMRX+FnY1bwNIgfaCA4RTprh9QoIsoi7GGSqedFziUW8Pwv5cjuYnibAJkp8vhvYekbo/qa87tfkS1UVvGkL1h/NJFgO2+MTlPn5MIxsWzmvSQKDxoAK3h+yEjIFEiECcaKpAicK2aaMEaNg1jYWcfbRLE+JebwaG3IJRk0V93KpT7Ti0ttXZo+rFwCo0kKL2AS8qOZ5T0lXEXHIv9sWWrnwxc5cM+VcybbvXiAiJLTy4zFOQxgzfxXsK5dEpeXciJGI5AOMAJBkoBVnLGVTX2KRYGWQGu6/vb1Tf0PsGPRN6+Wb2roDlagtRazVkyUG5/lRTlTxzrXN35QYAbmCq1JoyqO/WTOZeN1r2NYpOruT21EVnHHPSNtGkaI7uAjU3h5kP7vv34WVtXeFlvsYRmR+lPQZKUTq0XHHbD4QWsc6cgrtqrTzPiXGu82ZXKeJatBbhHagijRUJ66U4Xtid7Xbw9263iT108ycm9i7/LxbX7Ml369v+Ur1t6SqtRd5V4Wqt5UmHPFnX3D98JJsw=)

### Other comments
![ts error vuetify](https://raw.githubusercontent.com/lucaspagliari1bigmedia/issues-print/main/ts-error-vuetify.png)

**Comment by yuwu9145** [comment] 2023-04-20 23:24
#17082

**Comment by lucaspagliari** [comment] 2023-04-20 23:24
I've opened this issue with my work account, but i just found another issues related to it in vue.js/language-tools repo

[Issue#2636](https://github.com/vuejs/language-tools/issues/2636#issue-1677260193) 

i don't this is a vuetify problem, but if anyone had any ideia i'm open to it

**Comment by lucaspagliari** [comment] 2023-04-20 23:26
@yuwu9145 I'll keep an eye on it
thanks!

**Comment by mdoesburg** [comment] 2023-04-21 00:10
Having the same issue while using `data-testid` on `v-btn`.

**Comment by lucaspagliari** [comment] 2023-04-21 02:55
@mdoesburg 
if you're using vscode with Volar extension 

try downgrading the extension from 1.4 to 1.3.19, it fixes this problem

but this is just a palliative solution... hope it helps ;)

**Comment by KaelWD** [comment] 2023-04-21 15:56
Duplicate of #17069

**Closed by KaelWD** 2023-04-21 15:56 UTC
Labels: S: triage
