### ISSUE TITLE
[Feature Request] Create Infinite Scrollable Virtual Data Table.

### ISSUE THREAD

**Issue by desaisoftwaree** [vuetifyjs/vuetify#17409] opened 2023-05-20 04:26 UTC
### Problem to solve
To handle millions of rows we will require both, Virtual Data table with infinite scroll ability to show fewer data on the screen with a virtual data table and data fetching when a user reaches the end of a document.

### Proposed solution
Add infinite scroll ability to Virtual Data Table.

**Comment by lioneaglesolutions** [comment] 2023-05-22 19:03
@johnleider any plans for this? Thought maybe this was already done?

**Comment by lioneaglesolutions** [comment] 2023-05-22 19:24
Duplicate of https://github.com/vuetifyjs/vuetify/issues/15561

**Closed** 2023-05-23 16:27 UTC
Labels: duplicate, T: feature

**Comment by tdoan2010** [comment] 2024-12-06 15:24
This is marked as completed, but how can I use it? The [documentation](https://vuetifyjs.com/en/components/data-tables/virtual-tables/#basic-example) doesn't show how to use it. Even the example on the page is not working.

**Comment by aniler0** [comment] 2024-12-09 13:13
Same problem here. You're marked as completed but there is no documentation about using. Such a bad library for styling.

**Comment by chris-vergilio** [comment] 2025-01-10 16:53
Judging from the close on #15561, this feature isn't planned or going to be implemented

**Comment by hkao1210** [comment] 2025-01-21 19:31
Ridiculous
