### ISSUE TITLE
[Bug Report] FaSvg not fully supported

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#12150] opened 2020-08-30 15:03 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.135
**OS:** Windows 7

### Steps to reproduce
Click on the envelope.

### Expected Behavior
@click should fire.

### Actual Behavior
Nothing, because the listener is on a commented out button and not the svg.

### Reproduction Link
<a href="https://codepen.io/teellcory/pen/mdPwvjj" target="_blank">https://codepen.io/teellcory/pen/mdPwvjj</a>

**Comment by KaelWD** [comment] 2020-08-30 15:14
Duplicate of #3505

**Closed by KaelWD** 2020-08-30 15:14 UTC
Labels: triage
