### ISSUE TITLE
[Bug Report] ClickOutside of a `v-menu` triggers another non-related `v-on:click`

### ISSUE THREAD

**Issue by kuanyui** [vuetifyjs/vuetify#5310] opened 2018-10-12 01:54 UTC
### Versions and Environment
Vuetify: 1.2.4
Vue: 2.5.17
Browsers: Firefox 62 & Chromium 69 
OS: Chakra Linux

### Steps to reproduce

```pug
  v-app
    v-content
      v-container
        .outside(@click='msg("outside")')  // [2] Then click here, the v-menu closed though, outside's @click also be trigger
          .STOP-EVENT(@click.stop="msg('v-btn to open a v-menu')")
            v-menu(@click.stop="msg('this did not work')")
              v-btn(slot="activator") .......  // [1] Click this, v-menu opened
              v-list ........
```

### Expected Behavior

When a `v-menu` is opened, clicking outside of it should only close that `v-menu` only, without triggering any other `v-on:click` on the web page. (This is also the expected behavior of an Android application)

### Actual Behavior

Clicking outside when a `v-menu` is opened, though the `v-menu` is closed successfully, but will also accidentally trigger unrelated click event listener.

### Reproduction Link

This is a real world demo:
https://codepen.io/anon/pen/jemoPm?editors=1011

This is a minimalist demo:
https://codepen.io/anon/pen/WaOYEy?editors=1111

---

**Comment by KaelWD** [comment] 2018-10-12 06:47
Duplicate of #1433, I don't think that should've been closed though.

**Comment by manueltaber** [comment] 2018-10-26 14:58
Really need this feature, since in a form with a lot of buttons it's difficult to close the menu. On Android this is the default behaviour...

**Comment by zajca** [comment] 2018-11-22 09:10
Since my issue was closed there is one big problem with vuetify select. When menu is open it's completely cover input field. It's cool but in UX manner not usable since it covers arrow which is intuitive way to close without selecting item. Best way to get out of this would be option to render menu under input not cover it.

**Comment by KaelWD** [comment] 2018-11-22 09:21
That also doesn't follow their own guidelines. You can use `menu-props="offsetY"` to prevent the overlap.

**Comment by KaelWD** [comment] 2019-03-20 14:35
Had a shot at this a while ago, whoever tries next should explore an invisible overlay instead of hacking up click-outside.

**Comment by KaelWD** [comment] 2021-08-11 17:15
In v3 you can use `scrim="transparent"` to block clicks on the rest of the page.

**Closed** 2021-08-11 18:03 UTC
Labels: T: enhancement, C: VMenu
