### ISSUE TITLE
[Feature Request] Optionally hide error messages, warnings and logs (like "Image load failed")

### ISSUE THREAD

**Issue by ibrahimBeladi** [vuetifyjs/vuetify#10888] opened 2020-03-19 16:34 UTC
### Problem to solve
Some messages like "Image load failed" message (and others) pollute the console. It will be hard to debug when there are tens or hundreds of errors and warning and logs in the console.

### Proposed solution
I know it is a bad practice, but sometimes, it is needed. I would suggest to have a way to disable some type(s) of errors/warnings. 

#### Messages
1. Image load failed (#6755)
1. Translation key "..." not found, falling back to default

Feel free to comment your suggestions.

**Comment by jacekkarczmarczyk** [comment] 2020-03-22 02:20
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6755

**Comment by ibrahimBeladi** [comment] 2020-03-22 05:34
Not exactly a duplicate. I want to introduce global settings for the console messages. One instance of that is the image load failure.

**Comment by jacekkarczmarczyk** [comment] 2020-03-22 05:52
I see, I've reopened it but please remove reference to VImg from the title, also can you provide other examples where of messages that hiding them would give any benefit? Afaik most of them show the error in code (invalid css color, missing slot-scope etc)

**Comment by ibrahimBeladi** [comment] 2020-03-22 05:57
I will reword the title.

I do not recall the others yet. But everyone can feel free to mention what messages they want to hide.

**Comment by KaelWD** [comment] 2020-03-22 06:58
If there's a specific message you're seeing too much of you can very easily filter it from devtools: https://superuser.com/a/1028554/448703

**Comment by little3201** [comment] 2020-05-21 00:48
and <v-img> can't ues local image path like <v-img src="@/assets/logo.png">, it not work

**Comment by johnleider** [comment] 2020-05-31 20:23
resolved by #10909 

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-05-31 20:23 UTC
Labels: Framework, T: feature
