### ISSUE TITLE
[Bug Report] in v-select default value not set 

### ISSUE THREAD

**Issue by piyushSinghalDemo** [vuetifyjs/vuetify#4288] opened 2018-06-13 06:57 UTC
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.2
**Browsers:** Firefox 59.0
**OS:** Windows 10

### Steps to reproduce
i have json array as items key ({'text':"",value:{}}) here value is an object, and then if will give default value to v-select model then i am not getting default value on that select. 

### Expected Behavior
if there is default in v-model that should be set on v-select

### Actual Behavior
getting blank v-selct

### Reproduction Link
[https://codepen.io/piyushSinghalDemo/pen/YvQyox](https://codepen.io/piyushSinghalDemo/pen/YvQyox)

**Comment by KaelWD** [comment] 2018-06-13 07:01
Duplicate of #4000

**Closed by KaelWD** 2018-06-13 07:01 UTC

**Comment by piyushSinghalDemo** [comment] 2018-06-13 07:53
Actually in my case , i am trying to remove any item and if i do not use set-timeout still there is same issue, as per your reference #4000 not getting solution.

**Comment by jacekkarczmarczyk** [comment] 2018-06-13 07:55
It's more like a dup of #4020, #3862 and maybe more

**Comment by piyushSinghalDemo** [comment] 2018-06-14 09:28
As per my understanding i need to set value as string not json object, however in my case i am showing multiple table column as option, as i have multiple table so there may be possibility that i ll get same column name in different table,so at the time of default select value i ll have to define table and column name to identify a unique value,

So is there any way to resolve this issue ?

**Comment by jacekkarczmarczyk** [comment] 2018-06-14 09:33
Not sure what tables have to do with selects, please continue the discussion on discord and provide the codepen
