### ISSUE TITLE
[Bug Report][3.7.1] Treeview load-children not working when expanding using arrow icon after upgrading

### ISSUE THREAD

**Issue by kensington133** [vuetifyjs/vuetify#20460] opened 2024-09-11 12:00 UTC
### Environment
**Vuetify Version:** 3.7.1
**Last working version:** 3.6.15
**Vue Version:** 3.5.4
**Browsers:** Firefox 130.0
**OS:** Mac OS 10.15

### Steps to reproduce
The example is taken directly from the load-children section of the [Vuetify Docs](https://vuetifyjs.com/en/components/treeview/#load-children)

1. Click on the arrow icon to expand/open a node
2. The icon updates to show that it expanded, but the loading state isn't shown and the children are not loaded

(Note that clicking the item does work, it's only on the arrow icon where it fails to load the children)

### Expected Behavior
The loading state is shown, then the children are loaded and displayed correctly

### Actual Behavior
No loading state is shown, the arrow changes to show that it is open but no children are shown

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrVWG1P3DgQ/ivu6gTLqdml14KqPeBUaNWTri8I6PUDVFdvMrtxcezIdnZZEP/9xnayiZMs0G93SGgTezwvzzwztnN5N9AqHr/J89GigMFkcGAgyzk1cHQlCDlYRDFViXtev0WGGQ4k5lTrw6vBdB4xkbC5JAZuTLRMmQH/mO5dDcqlhHzRoMhbpiA2Uq1KheOmRhRd21FyWS2s7OQ0enU1qEZ/FNqw2QrHdU5jiKZglgCiElibtT5LTvDf6mg65OaMAlgwWBuzf4sokwnwCY0NWyASCS50z1Cbb8rJHIQTsg+hyASxyKxh99ua45ImUZwynigQKDMDE6cWppYg+i4Vzi+pEkzMw8kEhGbG4hDLDJEw4bS169FFCUGzVghuekF5YadZEk6W8dMph+awjTKSIoo5i6+bE0ZR6wuTZRqDPDi8K24hdJpLM8kVoDIL3Z1zhdwH+SlzxGIpcAWbodwzKzaqQOtIE5IlLKJxLAthWoqQa1ZT6NE4oHstWfGi5pGlquRrjjrPErZgCdJ6AcqwmPIjK1UOhpK4tDZQMTqJZhxufK3EIAyoOgEhTXWsJOfRCv2qMCaWfJZ0hcH6ayFxgE6E4Vf4aeBYgdBKde2TL9x979RcwSribJ4aTPkLMpMC6xvsux9tK9Fm5YhGcVZEaGo2IT6w30PRVtrOnVOEuiYR5gcDCSPzHaMdHHAdkBTL6xpcdyjjHbXZ3WgsJton2U1ECyPbMhm9iZYsMSnKvdrdbU/PkDoPxLVumAhmh6k4SW15BQEHySqnWzYd0OzW4vz6dXeyY8fXUDbvjiNI2PxRz/fUmFxPxmNnkVKlR0yOf7nzDtx/73Ohxi+bRvt9Eq4a0HA3chz3qrtT6csWFfcI6v+tp9IJubsj6/Ta3kbu77um0pddI0iq0MoUO+DT7EBGGe811GbqA5Z0MU2BJtjMg5qaSo4kfcSBAktkY7BdH+ottsvBuoO1GldLqLEZ97YLDrNOK8DtgM5RoGG9LdJXEUGf7DWmLFQkg+hVmbAe+fVm353zXmmjZHsn3VA8J3ZbFatJH4n9htAXxFEzZW5nFquKow+v/I+F/xWmuN/Az4bf04RobwNKFdhW932M7WYN2NIb3dR4sHHMweCqf6aciuve3tPEv1TnoKe93eh/k47TVIqfTkYTi9wq2EhCO4rV3jojBZeAaqjnSNJzWGorbSgLzl74igpZ7lsUHtM0HgfcFqHJIbn0irb/wJMdaC0VA32xyuHw2OZ/ywueu8PHCVMxh60Yj5cpnLiT8ynVBvh7PNGJctytPU+ZMuexlPkniK+3YOWHvzLUiC9TdNkNfBHMPn+iplCUb81ozCj/kzLltaMLuLoedWs+Srye0DiFj3QuimwrXYufYsDMDmV4cEud8IkUMfZ0SLb0NRNe7IIKO2Bk7kQuCjWlYvv5JhzOCzG3tAT9GBjvFV3t/vYEHN6t4AwTHEBxRpmG5N1NjNWUdJA4C8Z8fgBzjRgAXtbiBgpWNKXGv3y1N8YGHhdLTAG6XaPxlqrrY3RCrAH5gAVjrRwXD6ByqsCTCrmJMT+CjE9kG5i/A1DOC5Uri0EAyxsxV6seYkiRQAcRx9gaiVJqDYYn62esqXkTk/OMBYh4Z9tofJLmQkr7thmUM7waJU8rmdKLBiSf8aZDPSk8dbnU0MVic61shmSuaJ6y2CeO3d7SACQbbQujYzxJNRECxbDqGhh9sL25yxjmfjYD9FehzJOq6EUTGXTxFpSjzCNseQszWnDzpPLpIGNvSqIJTVBJFhIk+kOldErxtY3JSaH4yiPyzV9bfQfOKZ42sf9m2ISPiIAlOVUyw4iGWFmSL3DuCLcWc8EyQJvV6HNcsLPjFcFNLpXBzxQuaHLnUU8Q3QkZ7tj1w3Ks/OAAE3L5rUwODrk8TIgoOF8P2i8QgZQ9E+vGyP0OPvhHe/YqsFtNKtP+o4e2xtcjhChAxopqoylP3eHeaE9vE7LtPtBU7Fnv8eUHiQkxKdPujK4DkfvGG0LcHqy255ZXbEaGz5xGD80Ikz836U7lLlYyzBhuFPW3hip1LMG8NZZe7paZDeKtvR2hnmRoH21O7C/emMnh4SFqwlSGDttf/7Sk+M2qgW0VCAKFzSOR2RuXwAqvemEGJpUJJq3Ovl6JmNQfwcjQJirAYzwmZ5BJ5B0TBO/seHdKNUE7RNPyk2IptpLFNoplNAGki2EZu8V9F5F5RibrcNDmkrKS5sMXe7u7JWkDjJxHw+3qivxDS4GnlhhSvK0hSmaV42elBOwpf+yg3G4YIGSEHULYyrC44s/IKhja8mjL2AlXEME3rlFe6HQ4Grl1O611sYV/CMolzSZechjZ74R2rJatidZMSotsnix+5rA6fF1+pCYdzbiUaugevQJc+WslUpGyQ2v/i7fUg3F5thvcP3eFPHg52h+92Bt8+xf6a7mR)

### Other comments
I previously raised this issue here [#20450](https://github.com/vuetifyjs/vuetify/issues/20450) but wasn't 100% clear with my reproduction steps as I didn't realise it worked when clicking on the item itself but was broken when clicking on the arrow icon

**Comment by KaelWD** [comment] 2024-10-17 07:12
Duplicate of #20360

**Closed by KaelWD** 2024-10-17 07:12 UTC
Labels: T: bug, C: VTreeview, labs
