### ISSUE TITLE
[Bug Report] Wrong button label color in Safari 14.1 when going from disabled to enabled state

### ISSUE THREAD

**Issue by ffxsam** [vuetifyjs/vuetify#13625] opened 2021-05-09 21:59 UTC
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.12
**Browsers:** Safari 14.1
**OS:** Mac OS 10.15

### Steps to reproduce
1. Go to repro link
1. Uncheck the checkbox

### Expected Behavior
Button label color should be white

### Actual Behavior
Button label is... something else. Semi-transparent white?

### Reproduction Link
<a href="https://codepen.io/ffxsam/pen/LYWVdYQ?editors=101" target="_blank">https://codepen.io/ffxsam/pen/LYWVdYQ?editors=101</a>

### Other comments
AFAIK, this doesn't happen on Safari 14.0 and under, or any other browser.

**Comment by KaelWD** [comment] 2021-05-09 23:29
Duplicate of #13599

**Closed by KaelWD** 2021-05-09 23:29 UTC
Labels: triage
