### ISSUE TITLE
[Bug Report][3.2.5] DataTableHeader 

### ISSUE THREAD

**Issue by constantijn** [vuetifyjs/vuetify#17394] opened 2023-05-16 21:48 UTC
### Environment
**Vuetify Version:** 3.2.5
**Vue Version:** 3.3.2
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
In version 3.2.5 this line of code:  
`import {DataTableHeader} from 'vuetify/labs/VDataTable'`  
gives the error:  
`TS2459: Module '"vuetify/labs/VDataTable"' declares 'DataTableHeader' locally, but it is not exported.`  
I'm forced to use that type because otherwise:  
`const headers  = [ {title: "Name", align: "start", key: "name"} ]`  
trips up the linter with:  
`error TS2322: Type '({ title: string; align: string; key: string; } | { title: string; key: string; align?: undefined; })[]' is not assignable to type 'DataTableHeader[] | DataTableHeader[][] | undefined'.`  
and:  
` Type 'string' is not assignable to type '"start" | "end" | undefined'.`  

### Expected Behavior
Working build

### Actual Behavior
`npm run build` crashes with a typescript error.

### Reproduction Link
[https://jsfiddle.net/hxj4vst6/](https://jsfiddle.net/hxj4vst6/)

### Other comments
Can you please export the typescript type for `DataTableHeader`? IntelliJ suggests this as the fix, which alters the file downloaded from NPM, which is not exactly a real fix, but it does work.

**Comment by webdevnerdstuff** [comment] 2023-05-18 21:01
Is there any benefit to using the DataTableHeader over the `headers` slot? That's what I usually use at least.

**Comment by KaelWD** [comment] 2023-05-19 13:52
Duplicate of #16680

**Closed by KaelWD** 2023-05-19 13:52 UTC
Labels: S: triage
