### ISSUE TITLE
[Feature Request] v-calendar add event on click on cells

### ISSUE THREAD

**Issue by roseyda** [vuetifyjs/vuetify#19284] opened 2024-02-26 20:10 UTC
### Problem to solve
Please add the quivalent of click:date, click:event, ... like in vuetify 2 

### Proposed solution
Add @click events

**Comment by theadell** [comment] 2024-04-21 12:20
Any update on this? Doing this manually is such a pain. it seems like a basic feature that should be built-in into the v-calendar component

**Comment by ivan006** [comment] 2024-05-14 18:04
Wait how do you do it manually?

**Comment by ivan006** [comment] 2024-05-14 18:04
> Any update on this? Doing this manually is such a pain. it seems like a basic feature that should be built-in into the v-calendar component


Wait how do you do it manually?

**Comment by blalan05** [comment] 2024-07-13 03:17
Duplicate of #19020

**Closed by blalan05** 2024-07-13 03:17 UTC
Labels: S: triage
