### ISSUE TITLE
[Feature Request] Add VTreeView to 3.x

### ISSUE THREAD

**Issue by BookerLiu** [vuetifyjs/vuetify#16214] opened 2022-12-05 01:47 UTC
### Problem to solve
I want using VTreeView in 3.x, but i can't fount VTreeView with 3.x

### Proposed solution
I hope it can be added to the 3.x version, thanks

**Comment by KaelWD** [comment] 2022-12-05 05:07
Duplicate of #13518

**Closed by KaelWD** 2022-12-05 05:07 UTC
Labels: S: triage
