### ISSUE TITLE
[Bug Report] V-Autocomplete Menu overlaps input if screen size too small.

### ISSUE THREAD

**Issue by Bastian-Notter** [vuetifyjs/vuetify#12106] opened 2020-08-24 14:46 UTC
### Environment
**Vuetify Version:** 2.3.9
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.135
**OS:** Mac OS 10.15.6

### Steps to reproduce
1) Have an autocomplete.
2) Have a screen size where it will not fit the 304px menu-size above or below the autocomplete.
3) Open the autocomplete.

### Expected Behavior
Shrink the menu maybe or scroll so the autocomplete is at the very top of the page if possible

### Actual Behavior
The autocomplete menu starts to overlap with the input.

### Reproduction Link
<a href="https://codepen.io/BastianNotter/pen/dyMNwov?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fautocompletes%2F" target="_blank">https://codepen.io/BastianNotter/pen/dyMNwov?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fautocompletes%2F</a>

### Other comments
If you want to easily recreate the issue on the codepen just shrink the view down to about 300px and type in 'a', you should be able to see the issue then.

**Comment by scscgit** [comment] 2021-02-14 19:11
Too bad there are no updates for almost a year for such an important issue, as any autocomplete with a large quantity of data (e.g. from API) easily becomes quite useless from UX perspective, making it impossible for end users to even click to select/copy/paste the input text, while they obviously can't see what they've currently typed.

To brainstorm possible solutions, other than detecting remaining page height dynamically, the input could pop out and be displayed above the list of options; possibly even being displayed as a new dialog, or I could imagine there to be at least a button that "maximizes" the list of options, making them cover the entire page instead of being forced "below" or "above" the input (as the current height feels just too arbitrary without giving the user any choice). I'm also wondering if there's any Material Design guideline regarding this, as I barely found something about [dropdown menus](https://material.io/components/menus#dropdown-menu).

If someone is too desperate, I've found one possible workaround of limiting this to around 42-46% of screen height by putting this inside your component:
```css
<style>
.v-autocomplete__content {
  max-height: 46vh !important;
}
</style>
```
instead of `max-height: 304px`.

Issue illustrated as still occurring in version 2.4.4:
![image](https://user-images.githubusercontent.com/3118390/107885625-ba842080-6efb-11eb-8948-a7ff9c0bc3e2.png)

**Comment by KaelWD** [comment] 2021-05-05 14:25
Duplicate of #4059

**Closed by KaelWD** 2021-05-05 14:25 UTC
Labels: triage
