### ISSUE TITLE
[Bug Report] Fullscreen v-dialogs close when clicking external v-snackbar or v-overlays

### ISSUE THREAD

**Issue by Hdbcoding** [vuetifyjs/vuetify#8890] opened 2019-09-07 15:03 UTC
### Environment
**Vuetify Version:** 2.0.15
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
Open a fullscreen v-dialog. Trigger an v-snackbar which is not within the open v-dialog to show a message. Click on a close button within the v-snackbar to dismiss the v-snackbar.

e.g.:
`
<v-dialog fullscreen>open this</v-dialog>
<v-snackbar>open, then click on this</v-snackbar>
`

### Expected Behavior
The v-snackbar closes, but the v-dialog stays open.

### Actual Behavior
Both the v-snackbar and the v-dialog close.

### Reproduction Link
<a href="https://codepen.io/hdbcoding/pen/KKPQVzE" target="_blank">https://codepen.io/hdbcoding/pen/KKPQVzE</a>

### Other comments
This same behavior also happens for v-overlays which are outside of the open fullscreen v-dialog.

This bug does **not** occur when opening an external v-dialog. If you open a fullscreen v-dialog, then open another v-dialog which is not within the first fullscreen v-dialog, you can close the second v-dialog **without** immediately closing the first.

This bug also does **not** occur for non-fullscreen dialogs. If the initial dialog is not fullscreen, you can open external overlays and snackbars on top of it, and close them, and it will not close the initial dialog, as expected.

The codepen shows the results of opening a dialog with options for fullscreen or persistent. Within the dialog you can open and close snackbars, overlays, and dialogs that are either within the html of the open dialog or outside of it. Importantly, this shows that `persistent` is **not** a workaround for this issue.

**Comment by jacekkarczmarczyk** [comment] 2019-09-07 15:36
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7310

**Closed by jacekkarczmarczyk** 2019-09-07 15:36 UTC
Labels: triage
