### ISSUE TITLE
[Bug Report] v-datepicker year picker is not keyboard accessible

### ISSUE THREAD

**Issue by antman888** [vuetifyjs/vuetify#12257] opened 2020-09-21 04:05 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.83
**OS:** Mac OS 10.15.6

### Steps to reproduce
1. Click on the "Birthday date" field
2. Observe year picker is displayed
3. Press tab key

### Expected Behavior
Focus should go into the year list and allow selection via keyboard.

### Actual Behavior
Focus goes to the next input element.

### Reproduction Link
<a href="https://codepen.io/antman888/pen/NWNErjm?editors=1010" target="_blank">https://codepen.io/antman888/pen/NWNErjm?editors=1010</a>

### Other comments
The codepen is based off the [birthday picker in the docs.](https://codepen.io/antman888/pen/NWNErjm?editors=1010)

This only affects the year picker. You can also get to the year picker via the normal date picker using the keyboard where the result is the same.

Steps to reproduce part 2:

1. Untick the "Year Picker" checkbox
2. Click on the "Birthday date" field
3. Observe the date picker is displayed
4. Press the tab key to focus on the picker
5. Tab to the Month/Year button and press enter
6. Tab to the Year button and press enter

Results are as above. You cannot select the year via the keyboard.

**Comment by jacekkarczmarczyk** [comment] 2020-09-21 08:36
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5629

**Closed by jacekkarczmarczyk** 2020-09-21 08:36 UTC
Labels: triage
