### ISSUE TITLE
Full Screen Dialog disables scroll on close 

### ISSUE THREAD

**Issue by alanaberdeen** [vuetifyjs/vuetify#739] opened 2017-06-10 12:39 UTC
Hey, 

I came across something a little funny on the documentation site and I don't think it's been mentioned here. Essentially once you have triggered and then closed the 'fullscreen dialog' example the page is unresponsive to scrolling. Not a big deal but thought you might like to know. 

Cheers

### Steps to reproduce
1. See documentation example for a fullscreen dialog here: 
https://vuetifyjs.com/components/dialogs

2. Click 'open dialog' to trigger fullscreen 

3. Close dialog via x in top left. 

4. Page no longer responsive to scrolling. 

### Versions
Tried it in Chrome and Safari, Mac and PC.

### Reproduction Link

See this page: 
https://vuetifyjs.com/components/dialogs

**Comment by marcpaskell** [comment] 2017-06-10 13:29
Yep - looks like "style="overflow-y: hidden; padding-right: 17px;" is left on html element

**Comment by johnleider** [comment] 2017-06-10 15:06
duplicate of #700

**Closed by johnleider** 2017-06-10 15:06 UTC
