### ISSUE TITLE
[Bug Report] v-row (v-grid) vertical spacing issue with the latest release

### ISSUE THREAD

**Issue by halimb** [vuetifyjs/vuetify#12983] opened 2021-01-18 14:09 UTC
### Environment
**Vuetify Version:** 2.4.2
**Last working version:** 2.3.23
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Linux x86_64

### Steps to reproduce
The default vertical spacing has been collapsed in the latest release, in `v-row` s, breaking most layouts in my app. 

Here's how it was working before: 
v 2.3.23: https://codepen.io/unhalium/pen/VwKgQex ✅

Here's how it is now:
v 2.4.2: https://codepen.io/unhalium/pen/MWjLQpj  ❌

If this is an intended breaking change, how do you suggest to fix it globally without going through every single component in my code base?

### Expected Behavior
default vertical spacing in nested v-rows

### Actual Behavior
no vertical spacing

### Reproduction Link
<a href="https://codepen.io/unhalium/pen/MWjLQpj" target="_blank">https://codepen.io/unhalium/pen/MWjLQpj</a>

**Comment by KaelWD** [comment] 2021-01-18 14:13
This is explained in the release notes: https://github.com/vuetifyjs/vuetify/releases/tag/v2.4.0

Duplicate of #12848

You haven't really explained how this is broken, the first codepen is demonstrating bug #11408

**Closed by KaelWD** 2021-01-18 14:13 UTC
Labels: triage
