### ISSUE TITLE
[Bug Report] The full screen Dialog gets closed when dragging-out from a v-color-picker in v-menu

### ISSUE THREAD

**Issue by martn001** [vuetifyjs/vuetify#12461] opened 2020-10-21 08:49 UTC
### Environment
**Vuetify Version:** 2.3.13
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 10

### Steps to reproduce
When you try to select a color inside the menu, but when you drag your cursor outside the menu, the dialog will close. This will happen, even when I set a prop namend `close-on-click="false"` on the menu.

### Expected Behavior
The dialog should not closes when dragging outside the color-picker.

### Actual Behavior
I created a component with a `v-color-picker` inside a `v-menu`. Then I placed my component in a fullscreen dialog.

### Reproduction Link
<a href="https://codepen.io/martn001/pen/vYKXvdL" target="_blank">https://codepen.io/martn001/pen/vYKXvdL</a>

### Other comments
When adding the option `persistent` it prevent the dialog from closing, but with a bouncing animation. I would like to see an option with preventing the dialog from closing and without any animation.

**Comment by KaelWD** [comment] 2020-10-21 08:52
Duplicate of #9283

**Closed by KaelWD** 2020-10-21 08:52 UTC
