### ISSUE TITLE
[Feature Request] add support for fixed columns on v-data-table

### ISSUE THREAD

**Issue by lichnow** [vuetifyjs/vuetify#4652] opened 2018-07-18 10:23 UTC
### What problem does this feature solve?
1.set data-table's min-width for overflow-x scroll without by setting css `.v-table width`
2.when table in overflow model, fixed one column.

### What is your proposed solution?
now i use css solve it,but best solution is set it by component props , so it is possible do it?

the element ui's effect exp:

![](http://static.phpna.com/images/20180718182331.png)

**Comment by lzhoucs** [comment] 2018-09-07 19:36
I implemented a version of it in my fork: https://github.com/lzhoucs/vuetify/pull/4
Here is the demo: https://codepen.io/lzhoucs/pen/dqZvXr

**Comment by borisdayma** [comment] 2019-03-28 23:28
@KaelWD I think this issue was not a duplicate of #1547, which is related to fixed header.
This one is related to having a fixed column, as seen on the demo, item 1, provided by @lzhoucs 
@nekosaur Just referencing you this issue in case you're interested as I know you're currently working on v2

**Comment by brooklynb7** [comment] 2019-04-21 12:02
> I implemented a version of it in my fork: [lzhoucs#4](https://github.com/lzhoucs/vuetify/pull/4)
> Here is the demo: https://codepen.io/lzhoucs/pen/dqZvXr

This implementation is really cool !

**Comment by KaelWD** [comment] 2019-04-21 12:34
@borisdayma It was my understanding that this was going to be done as part of that

**Comment by KaelWD** [comment] 2019-04-21 12:36
:angry:

**Comment by agusdutra** [comment] 2019-06-27 17:55
hi, is there any update on this? thanks

**Comment by morficus** [comment] 2019-07-11 20:26
@lzhoucs - you should open a PR against this issue with your implementation

**Comment by georgeglessner** [comment] 2019-07-12 04:04
Really would like to see this feature. I know fixed header is coming in 2.0, but is fixed column also coming?

**Comment by pengiundev** [comment] 2019-07-22 11:46
+1 for fixed columns, too

**Comment by pengiundev** [comment] 2019-07-22 14:35
There's actually a css only solution which works with 2 or more columns, too if you know the width of them
https://stackoverflow.com/a/50516259

**Comment by ehouarn-perret** [comment] 2019-10-30 22:19
Is there anything new about that feature request?

**Comment by inaLar** [comment] 2019-11-12 14:07
Hi, Is this feature supposed to work in 2.1.4 ?

**Comment by nekosaur** [comment] 2019-11-12 15:30
No, this has not been implemented

**Comment by YangAi** [comment] 2020-02-29 01:58
This function would be really helpful if there are lots of columns in the datatable. if we could fix the ID/name and action column, it would save plenty of time scrolling back and forth.

**Comment by Chris2011** [comment] 2020-03-06 10:51
@lzhoucs hey, I saw your repo, is it possible, that you can please rewrite your implementation to fitted into that, so that you can create a new PR?

**Comment by zhitnyakov** [comment] 2020-05-02 18:26
Here is my solution for that.
I've used `position: sticky` CSS directives.

Repo - [https://github.com/zhitnyakov/vuetify-fixed-columns](https://github.com/zhitnyakov/vuetify-fixed-columns)
Demo - [https://zhitnyakov.github.io/vuetify-fixed-columns/dist/](https://zhitnyakov.github.io/vuetify-fixed-columns/dist/)

**Comment by Chris2011** [comment] 2020-05-04 15:55
I did it with sticky too, it works quite well.

**Comment by morficus** [comment] 2020-05-04 16:12
** cries in IE11 **

<img src="https://media.giphy.com/media/AauJT0w8cJoSQ/giphy.gif" />

**Comment by morficus** [comment] 2020-05-04 16:17
I'm actually a big fan of a CSS-only approach since it is probably the cleanest and most performant way to achieve this with out having duplicate markup and doing the "double-table" trick.

**Comment by dilapitan** [comment] 2020-05-11 07:22
@zhitnyakov thanks for this! it also worked for me too 😄

**Comment by tsangwe** [comment] 2020-05-20 08:31
@zhitnyakov I am trying to have the first 3 columns sticky by changing to td:nth-child(-n + 3)
but ended up only the 3rd column sticky

**Comment by zhitnyakov** [comment] 2020-05-20 08:41
> td:nth-child(-n + 3)

I'm not so good in such special CSS selectors&
Just using `td:nth-child(1), td:nth-child(3), td:nth-child(3)` for 3 fixed cols

**Comment by nekochan7** [comment] 2020-09-16 03:54
@zhitnyakov thanks. it also worked for me. https://codesandbox.io/s/vue-template-forked-do39f?file=/src/components/DataTableFixed.vue

**Comment by itsalaidbacklife** [comment] 2021-02-11 16:38
Was this issue closed because it was implemented in the Titan sprint of Vuetify 3? Or because it was abandoned and will not be implemented? We are faced with a strict design requirement to implement this, so we need to homebrew our own solution if none is available. What's the plan for this feature?

**Comment by KaelWD** [comment] 2021-02-11 16:39
![image](https://user-images.githubusercontent.com/16421948/107667615-d9a86580-6ce3-11eb-9c9a-eb19fa464a8b.png)

**Comment by itsalaidbacklife** [comment] 2021-02-11 16:43
ahh My apologies! Misread the tag on the closed duplicate [#12966](https://github.com/vuetifyjs/vuetify/issues/12966).

**Comment by dantovalphas** [comment] 2021-09-18 01:56
Only add this class in configuration headers

```css
.fixedcol {
    position: sticky; 
    width: 200px; 
    right: 0;
    text-align: center !important;
 }
```

**Comment by TingNLP** [comment] 2022-06-24 08:39
> Only add this class in configuration headers
> 
> ```css
> .fixedcol {
>     position: sticky; 
>     width: 200px; 
>     right: 0;
>     text-align: center !important;
>  }
> ```

Can you give a example? 
thank you

And how to fixed last one or last N column?

**Comment by TingNLP** [comment] 2022-06-24 10:15
> 



> > Only add this class in configuration headers
> > ```css
> > .fixedcol {
> >     position: sticky; 
> >     width: 200px; 
> >     right: 0;
> >     text-align: center !important;
> >  }
> > ```
> 
> @dantovalphas Can you give a example? thank you
> 
> @zhitnyakov How to fixed last one or last N column? thank you
sorry, I have noticed @asrori7  give a example,  but I cant't work with multiple last n chlid by use **td:nth-last-child(1), td:nth-last-child(2), td:nth-last-child(3)**

**Comment by clement-hyperplan** [comment] 2023-04-19 08:35
Hi ! @dannycoulombe solution is working great. Just had to remove the `+ left;` on css left property calculation on that line `left += (column.width || 0) + left;`.

Thank you very much !

**Comment by dannycoulombe** [comment] 2023-04-19 17:17
> Hi ! @dannycoulombe solution is working great. Just had to remove the `+ left;` on css left property calculation on that line `left += (column.width || 0) + left;`.
> 
> Thank you very much !

Just curious. What issue was it causing? I will update my snippet accordingly.

**Comment by clement-hyperplan** [comment] 2023-04-19 17:34
> > Hi ! @dannycoulombe solution is working great. Just had to remove the `+ left;` on css left property calculation on that line `left += (column.width || 0) + left;`.
> > Thank you very much !
> 
> Just curious. What issue was it causing? I will update my snippet accordingly.

I think the column width is taken into account twice. So you have to go with `left = (column.width || 0) + left;` or `left += column.width || 0` but not both. So the **third** column was stuck too far out from left.

**Comment by velly** [comment] 2023-05-30 07:47
Looking foward to this feature.

**Closed** 2023-09-20 19:54 UTC
Labels: T: feature, C: VDataTable

**Comment by trgianghuynh1808** [comment] 2024-11-28 07:59
> I wrote a directive in TS that handles all that. Add `fixed: true` to your desired columns and `v-fixed-columns` ...
> Hi @dannycoulombe tks, the directive is a good idea, I applied it for my case, and it work well. So I agreed with @clement-hyperplan , In my case, I still need to remove `+ left`



In my case, I'm using NuxtJS, I used `plugins` to define directive, 

```
// -- plugins/fixed-column-directive.ts

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.vueApp.directive('fixed-columns', {
    mounted(el, binding) {
      applyCallback(el, binding);
    },
    unmounted(el, binding) {
      unbindCallback(el);
    },
  });
});
```

To get the props in the component that used the directive
```
// -- plugins/fixed-column-directive.ts -  applyCallback()

 // *INFO: use biding value like this: "v-fixed-columns='fixedColumnsDirectiveProps'"
  const columns: Array<{ [key: string]: any }> = binding.value.headers;
  const showSelect = Boolean(binding.value.isShowSelect);
```

**Comment by hxnzyl** [comment] 2024-12-05 09:08
You can defined a global class, add it to VTable "class".
This is an example of a fixed right column:
`
.v-table-sticky {
  & thead tr th:last-child,
  & tbody tr td:last-child {
    background-color: #fff;
    position: sticky;
    right: 0;
  }
}
`
