### ISSUE TITLE
Parallax can't find image - based on the parallax demo project

### ISSUE THREAD

**Issue by gfelot** [vuetifyjs/vuetify#1656] opened 2017-09-10 15:48 UTC
### Steps to reproduce
I setup a new project with `vue init vuetifyjs/webpack-advanced` and adding the Parallax demo. I wanted to split each parts (header/footer/sections) as standalone components.

The 2 sections with the parallax cannot find the source image. I have two 404 errors on the console.
I'm sure about the relative path I put because the main LOGO  has the same base path than the two others and it rendered (`../assets/vuetify.png` vs `../assets/hero.jpeg`, see below)

### Versions
Vue : 2.4.2
Vuetify: 0.15.0
MacOS: 10.12.6
Chrome: 60.x

### What is expected ?
Can see the source img in the 2 parallax sections.

### What is actually happening ?
Can't see the source img in the 2 parallax sections.

### Reproduction Link
I don't know how to give you reproduction link so here the code I have.

img available on `/src/assets/hero.jpeg`

`/src/components/Hero.vue`
```javascript

<template>

  <div class="">

    <section>
      <v-parallax src="../assets/hero.jpeg" height="600">
        <v-layout column align-center justify-center class="white--text">
          <img src="../assets/vuetify.png" alt="Vuetify.js">
          <h1 class="white--text mb-2 display-3">Golf Watcher</h1>
          <div class="headline mb-3 text-xs-center">Powered by Vuetify</div>
          <v-btn class="blue lighten-2 mt-5" dark large href="/pre-made-themes">
            Get Started
          </v-btn>
        </v-layout>
      </v-parallax>
    </section>

  </div>

</template>

<script>
export default {
  data () {
    return {

    }
  }
}
</script>

<style scoped>

</style>
```

Do you think the issue is here because of vue-router that cannot give the path or something ?

EDIT: I made a test. If I just change the `<v-parallax>` for a `<img>` I have the img. So there is a real problem with the `src props` of `v-parallax`

**Comment by johnleider** [comment] 2017-09-10 16:09
This is essentially the same as #1239 for future me.

**Comment by gfelot** [comment] 2017-09-10 16:16
I'm still with `npm run dev` compared to this issue.

**Comment by johnleider** [comment] 2017-09-11 19:44
Going to close this as a duplicate of #1239 since it is really the same thing after digging in. I've requested help on the other ticket as well since this is a conflict with vue-loader and how it handles assets.

**Closed by johnleider** 2017-09-11 19:44 UTC
Labels: bug

**Comment by esodot** [comment] 2017-11-17 14:24
Thanks now its working, took me just 2 hours to find it :)

**Comment by gileneusz** [comment] 2018-01-24 16:51
please make a comment on template project file that this bug occurs, It's almost half a year and this is not fixed yet, and I wasted an hour to find this page and solution, thanks!

**Comment by johnleider** [comment] 2018-01-24 16:54
@gileneusz you mean like in the Frequently Asked Questions section?

![image](https://user-images.githubusercontent.com/9064066/35345252-2665b31a-00fd-11e8-9c71-fbd2cfd22608.png)

Even just using the search in the docs yields a result:

![image](https://user-images.githubusercontent.com/9064066/35345307-4930f9ea-00fd-11e8-8def-0dbfcb0fa8dd.png)


This information could be present in other areas, sure, and we welcome any PR's that help make the project better. In terms of triage though, we have added information to help users.

**Comment by gileneusz** [comment] 2018-01-25 15:37
I need more practice with the search button and I should reed more documentation. Anyway, the same problem is with Selects -> Scoped slots. It's not trivial for new users, they want all out of the box. However this framework is great. At this time that's the only major problem I've faced using it.

**Comment by kyriediculous** [comment] 2018-03-27 21:42
@johnleider update your codepens then instead of acting up.

**Comment by kyriediculous** [comment] 2018-03-27 21:43
@johnleider that's not a solution and just plain stupid. If you can't make simple paths work before building then there is no point in using vuetify over bootstrap-vue.

**Comment by johnleider** [comment] 2018-03-27 21:49
We need to update our documentation and my response was not very professional, so I apologize. I'll work on this tonight, thank you for your patience.

**Comment by kyriediculous** [comment] 2018-03-27 21:52
Sorry I'm having a bad day, my comment wasn't very friendly.

What i mean is that it's kind of ... a not so short workaround to make a seperate function and having to pass it as props to every child component that needs to use an image from assets.

Of course I could just cdn all images but yeah... who does that in development.

**Comment by johnleider** [comment] 2018-03-27 21:57
I'll do some research for the best patterns or already implemented
practices to handle this. It has unfortunately always been low on triage
for me and it is very hard to meet the needs of every developer.

This doesn't mean we cannot do better and I'm always on the lookout for
individuals to help with contribution.

**Comment by kyriediculous** [comment] 2018-03-27 23:24
Using a method threw an error for me by the way.
Directly using `:src="require('../assets/img.png')` did work 
However I ran into issues when trying to resize my overly large image so I abolished including an image source on the v-parallax tag and added it in css : 
```
  <v-parallax style="height:100vh;">
      <v-layout column align-center justify-center>
         <img src="@/assets/logo.png" alt="logo" height="200">
      </v-layout>
    </v-parallax>

.parallax {
    background: rgb(69,72,77); /* Old browsers */
    background: -moz-radial-gradient(ellipse at center, rgba(69,72,77,.5) 0%,rgba(0,0,0,.9) 100%), url('../assets/hero.jpeg') no-repeat;  /* FF3.6-15 */
    background: -webkit-radial-gradient(ellipse at center, rgba(69,72,77,.5) 0%,rgba(0,0,0,.9) 100%), url('../assets/hero.jpeg') no-repeat;  /* Chrome10-25,Safari5.1-6 */
    background: radial-gradient(ellipse at center, rgba(69,72,77,.5) 0%,rgba(0,0,0,.9) 100%), url('../assets/hero.jpeg') no-repeat; /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#45484d', endColorstr='#000000',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
    background-size:cover;
}
```

**Comment by dohomi** [comment] 2018-05-01 05:34
I did a little bit of research: only Chrome (and Opera) browser can handle `:src="someLazyLoadedImgSrc"` correctly, all other browser will fail showing an incomplete half-sized image. Seems that the other browser fires the load event of the img too early.

**Comment by rondaniel00** [comment] 2018-07-12 19:11
@johnleider 
Hi,
I noticed that if I move the assets folder to /public then it will work.
Is this information helps ?
