### ISSUE TITLE
[Bug Report] Ripple not centered for dense radio/checkbox controls

### ISSUE THREAD

**Issue by benjaminpwarren** [vuetifyjs/vuetify#10382] opened 2020-01-29 21:06 UTC
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.66, Mozilla Firefox, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
Use the `dense` prop on `v-checkbox` or `v-radio-group` and hover over the control.

### Expected Behavior
The hover ripple is centered on the control.

### Actual Behavior
The ripple is offset to the left.

### Reproduction Link
<a href="https://codepen.io/benjaminpwarren/pen/BayeORa" target="_blank">https://codepen.io/benjaminpwarren/pen/BayeORa</a>

### Other comments
This is actually because the `v-input--selection-controls__input` maintains its 24x24 dimensions and only its child `v-icon` changes dimensions to 20x20.

The below fixes this issue (but I haven't checked for adverse effects).

````
.v-input--selection-controls.v-input--dense:not(.v-input--switch) .v-input--selection-controls__input {
  width: 20px;
  height: 20px;
}
````

**Comment by KaelWD** [comment] 2020-01-29 23:33
Duplicate of #10336

**Closed by KaelWD** 2020-01-29 23:33 UTC
Labels: triage
