### ISSUE TITLE
[Bug Report][3.5.2] VDatePicker with date-fns adapter error Invalid time value

### ISSUE THREAD

**Issue by XuHaoJun** [vuetifyjs/vuetify#19145] opened 2024-02-01 05:58 UTC
### Environment
**Vuetify Version:** 3.5.2
**Vue Version:** 3.4.15
**Browsers:** Edge 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. set vuetify date adapter to DateFnsAdapter

### Expected Behavior
show DatePicker component

### Actual Behavior
nothing to show and with error Invalid time value

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVE1z0zAQ/StCF5ehtlpKL5nAtEAZ4AAMbeGAObj2JlGjr5HkNEwm/521pDiJC51cbGv37dvdtyv/WlFna7ZowfPJn+Le0RHl0mjryYrUFioPP6KPrMnEakmyhM1KlYDvEfRBucumMh5sQl00aM25ZuE9UW6L7yxX6tYl5Mx740aMtcrMp0WtZR9ycVacFadM6LoSwEDlt9eFvO+YSgXLwFVr5TxJJZHX+yUfrUpFiJ+BhBEJ34Q0MKla4W+iMRN8OvPZcfQx1r3X4RST9mGbYwYqoiOqq7THVFGA0UCQRD4gJATUqJciYSJp91w/LxU9DrO5NKbABnEwYw/SCAx508HGi7wyJnyGA0rhK67AJlMwBikNr+doHrP9c4pE635oZ4nMY7aTEY+uttx44sC3MXG/KhYmuwsSRkTSdKSb4mQQcZR9BCE0+amtaJ5l2OKYRUokw269w4AJn+IaaoX9BqlKiithuAD71XiOhCXtRSxphXwPn4PN2xaSjhgzg3r+D/u9W3a2kn6z4MAuoKS9z1d2Cj66r66/wBK/e6fUTSsQ/YTzOzgt2q7GCHvbqgbL3sGFaj8Fzbia3rirpQflNk11hW5Xq6So47snWt+Wi9ckxOHaBB3jVHJZmYGS0bFPg1liuZt7WDcKwxoQfGELBZ4pI9kFwphtlecS8kZLvJqvitNz1nDnd+0FOJnfWf2A4iLLTu/pjh6QKyExxXnxMmZIplxUd65L8YiahWHa3IJqwHaiH9bSIGyvrYHv/61t/lcHJB382l4g5w7Ro5/mIW0MY5D6pDhJ1Ju9oOtjGnvD/QjC0t9/ASmP/FY=)

### Other comments
[fix(VDatePicker): use start of month for month model](https://github.com/vuetifyjs/vuetify/commit/9eb82db11638f3b7fbb5d1e89652b2262b3a68a6)

```js
// adapter.parseISO(`${year.value}-${month.value + 1}-01`),
// that date string not work with date-fns 
adapter.parseISO('2024-2-01');
```
downgrade to v3.5.1, it will work

**Comment by KaelWD** [comment] 2024-02-15 03:26
Duplicate of #19196

**Closed by KaelWD** 2024-02-15 03:26 UTC
Labels: duplicate
