### ISSUE TITLE
[Bug Report] v btn outlined

### ISSUE THREAD

**Issue by wonderf** [vuetifyjs/vuetify#9898] opened 2019-12-06 06:52 UTC
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
change property height

### Expected Behavior
change size.

### Actual Behavior
size change for height > 50

### Reproduction Link
<a href="https://codepen.io/wengog/pen/eYmNwKp" target="_blank">https://codepen.io/wengog/pen/eYmNwKp</a>

**Comment by KaelWD** [comment] 2019-12-06 06:57
1. that's a text field not a button
2. duplicate of #5216

**Closed by KaelWD** 2019-12-06 06:57 UTC
Labels: triage
