### ISSUE TITLE
Support onSelect/onRemove events in v-autocomplete/v-combobox(multiple)

### ISSUE THREAD

**Issue by santhikumar43** [vuetifyjs/vuetify#5265] opened 2018-10-11 07:57 UTC
### What problem does this feature solve?
I have two **auto-completes** one is **Include** another one is **Exclude**. **Include** contains list of items, **Exclude** has copy of the same items. Here **Exclude** has the highest priority, if i select any option in the **Exclude**, if that option is already available in the **Include** need to removed in the list. Like wise if i remove selected option in the **Exclude**, that option should add it to **Include** list.
If i use `@change`, in both cases like adding/removing selected option will be triggered. Using `@change` need to compare the selected list each and every time to check option is added/removed.

### What is your proposed solution?
If there is something like `@select` `@remove` (on select, on remove of the options), it will be helpful.

**Comment by KaelWD** [comment] 2018-10-11 08:14
Duplicate of #4054

**Closed by KaelWD** 2018-10-11 08:14 UTC
