### ISSUE TITLE
[Bug Report] Container with fill-height and row with fill-height overflow

### ISSUE THREAD

**Issue by Feromrk** [vuetifyjs/vuetify#10554] opened 2020-02-12 12:14 UTC
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Linux x86_64

### Steps to reproduce
v-container with fill-height
some v-rows with visual content
last v-row with fill-height

### Expected Behavior
last v-row takes remaining screen space

### Actual Behavior
last v-row overflows by the height of the other rows before

### Reproduction Link
<a href="https://codepen.io/m0lg4n/pen/JjdOYLW?editors=1010" target="_blank">https://codepen.io/m0lg4n/pen/JjdOYLW?editors=1010</a>

### Other comments
also there is no useful information about height settings in the docs ([https://vuetifyjs.com/en/components/grids](https://vuetifyjs.com/en/components/grids)).

**Comment by johnleider** [comment] 2020-02-26 21:34
Duplicate of #9773

**Comment by Feromrk** [comment] 2020-02-28 11:47
@johnleider I don't think this is a duplicate. The problem at #9773 is the horizontal centering, whereaes the problem here is the vertical fill height. I was unable to find a solution so that the grid fills the entire available height of the screen. Also I don't see any documentation on that.

**Comment by jakeflorentine** [comment] 2020-03-11 15:15
Is there any known work around for this issue?

**Comment by Feromrk** [comment] 2020-03-13 10:53
@jakeflorentine I tried finding a solution for hours, but couldn't get it to work. Maybe thats because i'm new to js/css. I guess you have to work your way through CSS somehow. Let me know if you find out something useful please =)

**Comment by jakeflorentine** [comment] 2020-03-13 19:12
@Feromrk My solution was with setting display to grid on the v-container. While this isn't the most ideal solution, it provided me the result I needed for my current project.

**Comment by Feromrk** [comment] 2020-03-17 00:00
@jakeflorentine thanks for sharing!

**Comment by thomasrosdahl** [comment] 2020-04-19 09:39
Is this supposed to work or is there an alternative (correct way) of achieving the following grid layout without the overflow? https://codepen.io/m0lg4n/pen/JjdOYLW?editors=1010

**Comment by Feromrk** [comment] 2020-04-20 10:25
@thomasrosdahl I will take your link as the reproduction link for the original post, since it's more clear. This seems like a basic feature, I can't imagine that there is no correct way. Haven't found it though.

**Comment by thomasrosdahl** [comment] 2020-11-09 12:25
Any update on this? It's currently impossible to use grid system (v-container, v-row) in conjunction with fill-height without overflowing and causing unnecessary vertical scroll bar.

**Comment by simonmaass** [comment] 2020-11-20 13:07
wow this just cost me 1h of fiddling around thinking i dont get the grid system...

**Comment by KaelWD** [comment] 2020-11-20 13:39
This isn't possible to do with the utility classes thanks to the overly-specific rules added in #9189. Making `.container.fill-height` a flex column instead would probably fix #8608 too without requiring workarounds for basic stuff like this but may break existing layouts. 

It can be worked around with a few lines of CSS however: https://codepen.io/kaelwd/pen/jOrjNRZ

**Comment by simonmaass** [comment] 2020-11-20 14:10
if i do this it fixed the overflow horizontal and the height overflow:

```
.container.fill-height > .row {
  max-width: initial;
  width: 100%;
}

.container.fill-height {
  flex-direction: column !important;
  align-items: initial !important;
}

.container.fill-height>.row {
  flex: 1 1 auto !important;
}
```

**Comment by KaelWD** [comment] 2021-01-12 15:46
The specific `.fill-height` overrides have been removed in v3 (#12822) so this should no longer be a problem.

**Closed by KaelWD** 2021-01-12 15:46 UTC
Labels: C: VGrid, T: bug, has workaround
