### ISSUE TITLE
[Bug Report] Text input and Select input do not line up together

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#7015] opened 2019-04-18 00:17 UTC
### Versions and Environment
**Vuetify:** 1.5.12
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Ubuntu undefined

### Steps to reproduce
Have a select and a text input on the same row

### Expected Behavior
They line up cleanly

### Actual Behavior
They do not line up cleanly

### Reproduction Link
<a href="https://codepen.io/douglasg14b/pen/LvQKJQ" target="_blank">https://codepen.io/douglasg14b/pen/LvQKJQ</a>

**Comment by ibrahimBeladi** [comment] 2019-04-18 01:21
You can either play around with the CSS, or apply small-chips to v-select to resolve this issue.

**Comment by douglasg14b** [comment] 2019-04-18 01:31
@ibrahimBeladi Thanks!

In that case I believe the docs should mention this as a "gotcha" for forms with multiple input types (if it doesn't already and I just missed this).

**Comment by KaelWD** [comment] 2019-04-18 01:54
Duplicate of #5485

**Closed by KaelWD** 2019-04-18 01:54 UTC
Labels: triage
