### ISSUE TITLE
[Bug Report] lags on v-stepper

### ISSUE THREAD

**Issue by Flashantik** [vuetifyjs/vuetify#7212] opened 2019-05-14 18:16 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Windows 10

### Steps to reproduce
After render the componnet vStepper FIRST (!) step has lag

### Expected Behavior
no lags

### Actual Behavior
has lags

### Reproduction Link
<a href="https://codepen.io/Flashantik/pen/wbgwGR" target="_blank">https://codepen.io/Flashantik/pen/wbgwGR</a>

### Other comments
Even if a component has been removed through v-if it will still have this problem. There are no problems in the browser in MS Edge.  GIF https://user-images.githubusercontent.com/25429994/57721066-ea99f200-768b-11e9-8624-f26d7890c051.gif

**Comment by DRoet** [comment] 2019-05-15 07:52
Seeing this aswell, however it seems like this has been fixed in `2.0` already

**Comment by scp-nm** [comment] 2019-05-22 14:35
This is a widespread problem (affects tabs too) and I'm keen on seeing this fixed prior to `2.0` release.
Simply try any of the tabs examples on the Vuetify docs site:
https://vuetifyjs.com/en/components/tabs
Is there any update from the Vuetify team as to when we can expect this to be fixed?

**Comment by jimmaaay** [comment] 2019-06-25 07:24
Noticing this behaviour intermittently when using the stepper component and going back to a previous step. Any updates?

**Comment by johnleider** [comment] 2019-07-29 12:49
Duplicate of #7102

**Closed by johnleider** 2019-07-29 12:49 UTC
Labels: triage
