### ISSUE TITLE
[Bug Report] Icons in label show three dots in Firefox

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#12285] opened 2020-09-25 14:57 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Firefox 76.0
**OS:** Mac OS 10.15

### Steps to reproduce
Use a `<v-icon>` inside a `<template v-slot:label>` of a VTextField.

### Expected Behavior
The icon to show up

### Actual Behavior
Three dots are displayed

### Reproduction Link
<a href="https://codepen.io/thomaskientz/pen/OJNqMde" target="_blank">https://codepen.io/thomaskientz/pen/OJNqMde</a>

### Other comments
I have used the exact same exemple as in https://vuetifyjs.com/en/components/text-fields/#label-slot

Just open the doc with Firefox to reproduce.

**Comment by jacekkarczmarczyk** [comment] 2020-09-25 15:01
Duplicate of https://github.com/vuetifyjs/vuetify/issues/12229

**Closed by jacekkarczmarczyk** 2020-09-25 15:01 UTC
Labels: triage
