### ISSUE TITLE
[Bug Report] v-time-picker menu input ampm-in-title display format

### ISSUE THREAD

**Issue by mitch-cooper** [vuetifyjs/vuetify#10192] opened 2020-01-10 22:52 UTC
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Windows 10

### Steps to reproduce
Create v-time-picker component with the input/menu and "ampm-in-title" property
Select any time

### Expected Behavior
Expect the input format to match the title in the time picker (Ex. "9:30 pm/PM" to display in input).

### Actual Behavior
Input still displays military time format (Ex. "21:30", just as it is without the "ampm-in-title" property).

### Reproduction Link
<a href="https://codepen.io/Solithic/pen/YzPLZgX?editors=1010" target="_blank">https://codepen.io/Solithic/pen/YzPLZgX?editors=1010</a>

### Other comments
Not sure if this is intended functionality, but would be a slight QOL fix. Thank you!

**Comment by jacekkarczmarczyk** [comment] 2020-01-11 04:58
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4240

**Closed by jacekkarczmarczyk** 2020-01-11 04:58 UTC
Labels: triage
