### ISSUE TITLE
[Bug Report][3.0.5] Bug on reset form with VInputFile

### ISSUE THREAD

**Issue by ghettoDdOS** [vuetifyjs/vuetify#16296] opened 2022-12-19 14:13 UTC
### Environment
**Vuetify Version:** 3.0.5
**Vue Version:** 3.2.45
**Browsers:** Yandex 22.11.0.2484
**OS:** Linux x86_64

### Steps to reproduce
On reset VInputFile i have error
VFileInput.tsx:206 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')

### Expected Behavior
Normaly reset input

### Actual Behavior
Throws error 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UMtOwzAQ/BXLl4LUxIjHpUpRufATdQ9psgHT+CHbKaqq/DvrByWkgpyyM+OZ3dme6Ysx5XEAuqKVa6wwnjjwg3nmSkijrSdnYqEjI+mslmSB0gVXjVbOk05bSdaBvrm9YKIHl8HtDuGKJVs0xMGDNH3tASdCqmNRm5BE8MNB1kLlKSMxAa3WnIZfTi90IDGqEMoMPoFooFvogzYswWmC+3ofwVcESZJHhk2iot/eK+JPBlBrAUvAtKaH2lYscj/ROIdt4kXfwGX3MKSrKja5li5p6hOVpvxwWmHj5/CAZwIXXpGIBAx7DjOn794bt2JsUObwVjZasg1yzA7KCwlFq+XmobwvH59YK5yf4iU4Weyt/nRgMZHT5cTci+70V0Cm0feuzLYZCpZXVgz9j2ALC6oFC/bfvWfaX7vPuKv9Q+bI1Yhd9kId3KzGxsUKt7sgGZc0WaM43kF3X4VU9K0=)

**Comment by KaelWD** [comment] 2022-12-20 10:36
Duplicate of #16053

**Closed by KaelWD** 2022-12-20 10:36 UTC
Labels: S: triage
