### ISSUE TITLE
[Bug Report] v-tooltip | created span adds space to layout

### ISSUE THREAD

**Issue by jkieberking** [vuetifyjs/vuetify#7118] opened 2019-05-01 15:11 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Mac OS 10.14

### Steps to reproduce
(the codepen below is from the v-tooltip docs)
1) inspect any of the `<span class="v-tooltip v-tooltip--bottom"></span>` elements in the codepen

### Expected Behavior

1) add this style:
```
.v-tooltip.v-tooltip--bottom {
   display: none
}
```
the tooltip still shows correctly, but the layout is not disturbed

### Actual Behavior
in "Steps to Reproduce" above ^

### Reproduction Link
<a href="https://codepen.io/anon/pen/zXVBMY" target="_blank">https://codepen.io/anon/pen/zXVBMY</a>

### Other comments
this is causing issues for us when trying to add a tooltip to a td element in a v-data-table component: 
https://imgur.com/a/bZ9MSeN
( the fields are not aligned with the headers)

**Comment by KaelWD** [comment] 2019-05-02 09:12
Duplicate of #6951

**Closed by KaelWD** 2019-05-02 09:12 UTC
Labels: triage
