### ISSUE TITLE
[Bug Report][2.5.6] Fields are not connected to their "details" (accessibility)

### ISSUE THREAD

**Issue by paul-thebaud** [vuetifyjs/vuetify#13965] opened 2021-07-22 16:47 UTC
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.14
**Browsers:** Chrome 91.0.4472.114
**OS:** Ubuntu

### Steps to reproduce
* Create a field (for example "v-text-field") with validation rules.
* Input anything in field to have an error on it.

### Expected Behavior
Errors or hints should be connected to the field using an "aria-describedby" attribute pointing to the "messages" container (with a random ID for example).

### Actual Behavior
There is no "aria-describedby" attribute on fields.

### Reproduction Link
<a href="https://codepen.io/paul-thebaud/pen/xxdXmzx" target="_blank">https://codepen.io/paul-thebaud/pen/xxdXmzx</a>

### Other comments
This issue is related to the following comment : https://github.com/vuetifyjs/vuetify/issues/8431#issuecomment-519954338 (never answered/resolved).

**Comment by KaelWD** [comment] 2021-08-19 12:45
Duplicate of #13874

**Closed by KaelWD** 2021-08-19 12:46 UTC
Labels: T: enhancement, a11y, C: VTextField
