### ISSUE TITLE
[Bug Report] Unable to add line break in hint - does not parse br tag anymore

### ISSUE THREAD

**Issue by pamantea** [vuetifyjs/vuetify#10674] opened 2020-02-25 19:25 UTC
### Environment
**Vuetify Version:** 2.2.14
**Last working version:** 2.1.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Create any type of input with a hint text. 
Add < br > tag to add a line break in the hint text.

### Expected Behavior
text to be parsed and line break to be added

### Actual Behavior
<br> tag is printed in the UI

### Reproduction Link
<a href="https://codepen.io/pamantea/pen/bGdqVaq" target="_blank">https://codepen.io/pamantea/pen/bGdqVaq</a>

### Other comments
I noticed the change on version 2.2.4 but updating the version on Codepen, this seems to happen since 2.0 and does not seem to be working on latest version 2.2.14 as well.

**Comment by myleslee** [comment] 2020-02-26 01:40
According to <https://github.com/vuetifyjs/vuetify/releases/tag/v2.1.9>, you need to use slot syntax to support HTML output.
```
<v-checkbox
  color="secondary"
  v-model="v"
  hint="Test how line breaks work in different versions of Vuetify, based on latest updates. <br> Please note: This should be in a different line." persistent-hint label="Testing hint in Vuetify">
  <template v-slot:message="{message, key}">
    <div v-html="message" :key="key"></div>
  </template>
</v-checkbox>
```
<img width="448" alt="Screen Shot 2020-02-26 at 09 33 55" src="https://user-images.githubusercontent.com/108758/75303525-f43bc180-587b-11ea-9415-c94f86bafd85.png">

**Comment by jacekkarczmarczyk** [comment] 2020-02-26 02:00
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9647
That was changed in https://github.com/vuetifyjs/vuetify/commit/d6473f3452840964846baeb9b21dbb54a73edc1f, as @myleslee use slot

**Closed by jacekkarczmarczyk** 2020-02-26 02:00 UTC
Labels: triage

**Comment by pamantea** [comment] 2020-02-26 14:32
Thanks for the quick response! 

I had tried to look for it but could not find that change. Thanks again! :)
