### ISSUE TITLE
[Bug Report] can't set position-x, position-y for v-menu with absolute and attach

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#11913] opened 2020-07-22 16:36 UTC
### Environment
**Vuetify Version:** 2.3.5
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Linux x86_64

### Steps to reproduce
- click on the picture;

### Expected Behavior
v-menu has to be shown in 100px/100px coords relatively to the attach container (and top left corner of the image)

### Actual Behavior
v-menu node is attached correctly, but the position is incorrect (it's 0, 0 instead of 100,100) 

### Reproduction Link
<a href="https://codepen.io/kasheftin/pen/KKVJRwR" target="_blank">https://codepen.io/kasheftin/pen/KKVJRwR</a>

**Comment by lmindwarel** [comment] 2020-07-30 14:55
Same problem here, top and left css rules are not calculated when attach prop is true.

**Comment by KaelWD** [comment] 2020-07-31 16:19
Duplicate of #6877

**Closed by KaelWD** 2020-07-31 16:19 UTC
Labels: triage
