### ISSUE TITLE
[Bug Report] v-autocomplete: further options are not always loaded

### ISSUE THREAD

**Issue by joke1** [vuetifyjs/vuetify#5649] opened 2018-11-18 13:05 UTC
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Windows 10

### Steps to reproduce
Search the dropdown for "a" and select all options without scrolling the results.

### Expected Behavior
After a selection of x options, further matching options should be loaded.

### Actual Behavior
After all initially available options have been selected (20 items), no more matching options will be loaded as there is no scrollbar left to trigger the reload.

### Reproduction Link
<a href="https://codepen.io/joke1/pen/BGwBGY" target="_blank">https://codepen.io/joke1/pen/BGwBGY</a>

### Other comments
Affects v-autocomplete and v-combobox with multiple & hide-selected settings.

**Comment by johnleider** [comment] 2019-08-05 16:53
We have a poor mans virtual scroll in which we only load so many items and continue to increase that as the user scrolls. This isn't triggered when the items aren't scroll and simply selected.

Will need to look into a way of determining total visible items in this case to ensure we always populate 20 and in reality, an actual virtual-scroller would end up eliminating the need to hack it like this.

**Comment by borekl** [comment] 2020-01-21 15:07
This is fairly unfortunate and I consider this quite a significant problem. Using `$refs.select.lastItem = N` to increase the number of items loaded is an workaround for some situations, but this needs some better resolution.

**Comment by rpankaj** [comment] 2020-02-19 06:21
This problem still exists. Do we have any solution?
I got into this while using **v-combobox** (version - 1.5.11)

**Comment by johnleider** [comment] 2020-03-11 17:39
Duplicate of #2660 unfortunately. We can probably remove that number at this point, this just got swept under the rug. Thank you for your patience.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-03-11 17:39 UTC
Labels: C: VAutocomplete, C: VCombobox, C: VSelect, T: bug
