### ISSUE TITLE
[Bug Report] VDatePicker shows wrong weeknumber at end of year

### ISSUE THREAD

**Issue by abbierwolf** [vuetifyjs/vuetify#10925] opened 2020-03-24 06:37 UTC
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.4
**Browsers:** Firefox 74.0, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer
**OS:** Ubuntu undefined, Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
Open reproduction link and look at last week of date picker 1 and first week of date picker.

### Expected Behavior
Expected the same weeknumber for the last week of the year and the first week of the next year

### Actual Behavior
The weeknumbers differ the last week is numbered 53 and the first week is numbered 1

### Reproduction Link
<a href="https://codepen.io/abbierwolf/pen/YzXJqvN" target="_blank">https://codepen.io/abbierwolf/pen/YzXJqvN</a>

### Other comments
I have a solution and I will make it available through a pull-request

**Comment by jacekkarczmarczyk** [comment] 2020-03-24 06:47
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9764

**Closed by jacekkarczmarczyk** 2020-03-24 06:47 UTC
Labels: triage
