### ISSUE TITLE
[Bug Report][2.5.8] Combobox: item value displayed instead text

### ISSUE THREAD

**Issue by mattbtrick** [vuetifyjs/vuetify#14458] opened 2021-12-03 03:37 UTC
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.7
**Browsers:** Chrome 96.0.4664.45
**OS:** Windows 10

### Steps to reproduce
Load the code pen.

### Expected Behavior
Item text should be displayed when set initial value via v-model

### Actual Behavior
Item value is displayed

### Reproduction Link
<a href="https://codepen.io/mbronkema/pen/NWaqLeP?editors=101" target="_blank">https://codepen.io/mbronkema/pen/NWaqLeP?editors=101</a>

**Comment by KaelWD** [comment] 2021-12-14 08:29
Duplicate of #5479

**Closed by KaelWD** 2021-12-14 08:29 UTC
Labels: S: triage
