### ISSUE TITLE
"Required" attribute for <v-select> doesn't work

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#1120] opened 2017-07-24 15:48 UTC
### Steps to reproduce

Open https://codepen.io/anon/pen/RZwBwd, fill in the text field and submit the form

### Versions

0.14.5

### What is expected ?

Javascript form validation should block submitting the form

### What is actually happening ?

Form gets submitted although the required field has no value

### Reproduction Link

https://codepen.io/anon/pen/RZwBwd

**Comment by johnleider** [comment] 2017-07-25 01:44
Duplicate of #1070

**Closed by johnleider** 2017-07-25 01:44 UTC
Labels: pending review

**Comment by jacekkarczmarczyk** [comment] 2017-07-25 06:57
It's not exactly same as #1070, I'm talking about the browser form validation which is not working here because there is no input/select element in the generated markup

http://imgur.com/a/jfeOX
http://imgur.com/a/hQOQZ

Adding <input type="text"> with the same size and position as the div with the value (for correct browser message position) seems to be enough.

The reason why I think it's important is not only the convenience of the browser built-in validation but also the consistency of the components - if the "required" prop triggers the validation for <v-text-field> it should also work for <v-select>. Or it shouldn't work for both of them.

Anyway, great job with the framework! I'm planning to create some pull request in the future, just need to get familiar with the github workflow

**Comment by johnleider** [comment] 2017-07-25 14:14
I don't have any intentions to support standard html validation, sorry. Thank you for your feedback.
