### ISSUE TITLE
Tooltip getting clipped by sidebar

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#1022] opened 2017-07-17 19:18 UTC
See https://codepen.io/anon/pen/KqLdvY?editors=1010

Tooltips are getting clipped by the size of the sidebar (or maybe overlapped by the main container).

Vue 2.3.4
Vuetify 0.13.1

**Comment by nekosaur** [comment] 2017-07-19 10:03
Duplicate of #999

**Closed by nekosaur** 2017-07-19 10:03 UTC
Labels: duplicate
