### ISSUE TITLE
[Bug Report][2.5.6] sometimes text cursor does not appear in text fields on iPhone

### ISSUE THREAD

**Issue by dzhiharev** [vuetifyjs/vuetify#13933] opened 2021-07-16 12:53 UTC
### Environment
**Vuetify Version:** 2.5.6
**Last working version:** 2.3.0
**Vue Version:** 2.6.12
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Bug can be reproduced on Vuetify documentation page:
1. open https://vuetifyjs.com/en/components/text-fields/ on iPhone
2. click to first text field

### Expected Behavior
field focused, text cursor is visible, text can be typed

### Actual Behavior
field focused, text can be typed, text cursor is invisible

### Reproduction Link
<a href="https://codepen.io/dzhiharev/pen/dyWWGbW" target="_blank">https://codepen.io/dzhiharev/pen/dyWWGbW</a>

### Other comments
I can provide video recorded in iOS Simulator.
Problem did not exists in version 2.3.0 but reproduced at least in 2.3.23.
Inspecting changes in rendered HTML/CSS between 2.3.0 and 2.3.23 I discovered that there was only changes in styles and specifically in `transition` property in rule:
```
.v-text-field > .v-input__control > .v-input__slot {
    transition: background 0.3s cubic-bezier(0.25, 0.8, 0.5, 1);
}
```
this property exists in 2.3.0 and not exists in 2.3.23+
Adding this property back resolves issue (verified on 2.3.23 and 2.4.0)

**Comment by KaelWD** [comment] 2021-07-16 12:58
Duplicate of #13628

**Closed by KaelWD** 2021-07-16 12:58 UTC
Labels: S: triage
