### ISSUE TITLE
[Feature Request] Custom element in v-form

### ISSUE THREAD

**Issue by Bogdah9** [vuetifyjs/vuetify#7458] opened 2019-06-11 07:10 UTC
### Problem to solve
Hello, how can I connect my custom element to the v-forms. I found the register method, but I don’t know what kind of props my component should have.
My custom element : `<template>
    <div class="v-input my-input v-text-field v-input--is-label-active v-input--is-dirty error--text  ">
        <div class="v-input__control">
          <div class="v-input__slot">
            <div class="v-text-field__slot"><masked-input placeholder="Date" mask="11 / 11 / 1111" /> 
          </div>
          </div>
          <div class="v-text-field__details">
            <div class="v-messages">
              <div class="v-messages__wrapper"></div>
            </div>
          </div>
          <div class="v-text-field__details">
            <div class="v-messages theme--light error--text">
              <div class="v-messages__wrapper">
              </div>
            </div>
          </div>
        </div>
    </div>
</template>`
### Proposed solution

Preferably the path for the validate function and other parameters

**Comment by KaelWD** [comment] 2019-06-11 07:15
Duplicate of #3464

**Closed by KaelWD** 2019-06-11 07:15 UTC
Labels: triage
