### ISSUE TITLE
[Bug Report][2.5.8] v-autocomplete/v-select menu jumps to active list item when selecting new items

### ISSUE THREAD

**Issue by treardon17** [vuetifyjs/vuetify#14065] opened 2021-08-18 17:44 UTC
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 92.0.4515.131
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Go here: https://codepen.io/treardon17/pen/QWvXmWv
2. Click autocomplete to open menu
3. Scroll to bottom of menu and select the "CLICK ME" item

### Expected Behavior
The menu will maintain its current scroll position so I can continue to select items around it

### Actual Behavior
The menu scrolls to the "SCROLL TO" menu item, forcing me to continually scroll to the bottom of the list to select the other items I want

### Reproduction Link
<a href="https://codepen.io/treardon17/pen/QWvXmWv" target="_blank">https://codepen.io/treardon17/pen/QWvXmWv</a>

### Other comments
This is particularly frustrating when dealing with very large datasets, and the data is at the bottom of the list. The list always scrolls to the currently "active" list item. If arrow keys are used to change the current "active" item, the list will then scroll to the new "active" item in the list. NOTE: this behavior is _not_ present when using arrow keys to highlight a row and the return key to select. It is only present when selecting a list item with a mouse click.

**Comment by stas-kh** [comment] 2021-08-19 14:43
I face the same issue.

I think it's well described here with another example:
https://github.com/vuetifyjs/vuetify/issues/11969

But unfortunately there is no solution yet. I think you're totally right, this issue is related to the active element, in particular to the one that has class `v-list-item--highlighted`.

**Comment by treardon17** [comment] 2021-08-19 15:20
@stas-kh thanks for pointing out that existing open issue. I'll keep you posted if I find a good workaround 😊

**Comment by stas-kh** [comment] 2021-08-19 15:21
I refactored a bit the fix from #11969 and it helped me to deal with the issue.

You can find it below:

```html
// Template
<v-autocomplete
  ref="autoComplete"
  v-model="selectedItems"
  :items="itemsList"
  autocomplete="off"
  return-object
  multiple
  label="Variables"
/>
```

```javascript
// Component
watch: {
  selectedItems(newVal, oldVal) {
    /*
    * Fixing weird Vuetify's autocomplete behavior using the fix from here:
    * https://github.com/vuetifyjs/vuetify/issues/11969#issuecomment-727664375
     */

    let lastChangedItem;
    if (newVal.length > oldVal.length) {
      lastChangedItem = newVal[newVal.length - 1];
    } else if (newVal.length < oldVal.length) {
      lastChangedItem = oldVal.find(x => !newVal.includes(x));
    } else {
      lastChangedItem = newVal;
    }

    const changedListItemIndex = this.selectedItems.findIndex(item => item[this.itemValue] === lastChangedItem);

    this.$nextTick(() => {
      this.$refs.autoComplete.setMenuIndex(changedListItemIndex);
    });
  }
}

**Comment by KaelWD** [comment] 2021-08-19 15:30
Duplicate of #11969

@stas-kh Please open a PR if you think that's a suitable fix.

**Closed by KaelWD** 2021-08-19 15:30 UTC
Labels: S: triage

**Comment by treardon17** [comment] 2021-08-19 20:45
@KaelWD I believe I found the core issue. Here is a PR https://github.com/vuetifyjs/vuetify/pull/14070
