### ISSUE TITLE
[Bug Report] Tooltip not displaying in dialog when scrolled down in page

### ISSUE THREAD

**Issue by stanzakh** [vuetifyjs/vuetify#8736] opened 2019-08-27 00:32 UTC
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
1. Create an element that requires you to scroll down (e.g. add margin top)
2. Make the element activate a dialog
3. Put a tooltip into dialog
4. Try to hover over tooltip

### Expected Behavior
The tooltip should display

### Actual Behavior
No tooltip is displayed

### Reproduction Link
<a href="https://codepen.io/stanzakh/pen/vYBmBye" target="_blank">https://codepen.io/stanzakh/pen/vYBmBye</a>

### Other comments
I tried using every related component prop in the documentation, including the layout-related props and I also tried attaching it to various different DOM elements using the attach prop, but it still does not seem to work. When inspecting the element in Chrome, I observed that the tooltip is opening but it is off the screen, so apparently the offsets may not be calculated correctly in this case.

**Comment by shatzi** [comment] 2019-09-02 05:13
Attaching the tooltip to elements on the dialog doesn't seem to fix this issue as well.

**Comment by KaelWD** [comment] 2019-11-10 08:21
Duplicate of #8894

And you need a direction prop on the tooltip (top/bottom/left/right)

**Closed by KaelWD** 2019-11-10 08:21 UTC
Labels: C: VTooltip, triage
