### ISSUE TITLE
[Bug Report] Current Time in timepicker

### ISSUE THREAD

**Issue by hrvylein** [vuetifyjs/vuetify#3158] opened 2018-02-01 11:16 UTC
### Versions and Environment
**Vuetify:** 1.0.0-beta.5
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Click on the preselected hour and minute to reproduce the bug.

### Expected Behavior
The selected time should be selected.

### Actual Behavior
Picker won't save the selected time

### Reproduction Link
[https://next.vuetifyjs.com/en/components/time-pickers](https://next.vuetifyjs.com/en/components/time-pickers)

**Comment by jacekkarczmarczyk** [comment] 2018-02-01 12:06
Can't reproduce it, please provide more details about the reproduction steps and link to the codepen

**Comment by d3radicated** [comment] 2018-02-01 13:43
I don't know if this is related but `clearable` doesn't work on the `v-text-field` when used with `v-time-picker`.

https://codepen.io/dEradicated/pen/MQapyd

**Comment by hrvylein** [comment] 2018-02-01 20:44
@d3radicated thanks for creating that codepen.

I made two gifs to show what is not working right now.

Selecting the preselected current time, won't select it.
https://github.com/hrvylein/files/blob/master/datepicker.gif

Selecting time different from current time, will select it.
https://github.com/hrvylein/files/blob/master/datepicker_working.gif

**Comment by jacekkarczmarczyk** [comment] 2018-02-02 05:50
That's actually looks to be fixed in b.6 as there is no more current time displayed when value is null

**Closed by jacekkarczmarczyk** 2018-02-02 05:50 UTC
Labels: bug, emergent
