### ISSUE TITLE
[Bug Report] vAutocomplete doesn't close menu when items change

### ISSUE THREAD

**Issue by johnkingsley** [vuetifyjs/vuetify#4756] opened 2018-07-31 00:10 UTC
### Versions and Environment
**Vuetify:** 1.1.8
**Last working version:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Firefox 61.0
**OS:** Ubuntu undefined

### Steps to reproduce
At the codepen:
1. Choose an item on the vAutocomplete
2. Notice the menu doesn't close

### Expected Behavior
The menu should close after selecting an item.

### Actual Behavior
The menu doesn't close.

### Reproduction Link
[https://codepen.io/anon/pen/djJrpx](https://codepen.io/anon/pen/djJrpx)

### Other comments
I'm pretty sure this bug is due to change https://github.com/vuetifyjs/vuetify/commit/d4732ec0b8b5d80578c4c6d8ce0cc4bf3447a307

Perhaps the if-statement should also check that this.hideNoData is true?
(I'm basing this on the comment of the commit)

**Comment by KaelWD** [comment] 2018-07-31 14:09
Duplicate of #4663

**Closed by KaelWD** 2018-07-31 14:09 UTC
