### ISSUE TITLE
v-text-field is not working properly in v-stepper

### ISSUE THREAD

**Issue by pejold** [vuetifyjs/vuetify#1015] opened 2017-07-17 06:43 UTC
### Steps to reproduce
Using v-text-field in v-stepper-content

### Versions

0.14.1

### What is expected ?

No errors.

### What is actually happening ?

Type anything in v-text-field will cause error when v-text-field is in v-stepper-content

`[Vue warn]: Invalid prop: type check failed for prop "value". Expected Number, String, got Event.`

It was working with version 0.13.0

### Reproduction Link

https://jsfiddle.net/8xsbeogb/

**Comment by nekosaur** [comment] 2017-07-17 07:33
Duplicate of #1012

**Closed by nekosaur** 2017-07-17 07:33 UTC
Labels: bug, duplicate
