### ISSUE TITLE
[Bug Report][3.7.1] Reactivity Problem in opened v-model in v-list

### ISSUE THREAD

**Issue by Profiidev** [vuetifyjs/vuetify#20466] opened 2024-09-12 07:19 UTC
### Environment
**Vuetify Version:** 3.7.1
**Vue Version:** 3.5.4
**Browsers:** Chrome 128.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Click in the text field
2. Search for "ch"
3. "Parent" is not expanded
4. Click on the empty space
5. Click back in the text field
6. "Parent" now expanded

### Expected Behavior
"Parent" should be expanded while searching

### Actual Behavior
"Parent" expands after reopening

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtWFuP4zQU/ivePuymUtvZXRAPpdNluAiBFoFgEQ/TEcokbmut64TE6XQY+t/5fI2TOu0sog9tYh+f63cu7u3TqK6yq5uynO0bOpqPFnVWsVKSmsqmJDwVm+vVSNar0XIlCGG7sqgkeSJZsSsbSfMJqeh6Qh5SmW3JkayrYkdWI7Bajb5cCXVk3YhMskKQnK3XtKIio4ubZZLOyc3t3YTc69+x/iZP6gABS9lUgqSzNeOSVkmyH5PrJXlxP2Mi401Oa6yMwZ+QY08IEzhQU/3yH8U8Q0r9uNtRWbHs29amD8vkMCcflLBH/Qth+HbCskLUknC6luQ6cEVyALkR4mgqttn2iB4n5OCIrNa3s9lMcZsQPOgjd6Gq9KADpd2xTjNKvq+KpqT5TSMLFTtOJf1B0p1TTzLJ6ZzUMEpsnDpbxnMo8M6t33ZEGG2fCAObGvremlMES5bbavRLivNyNZp4ZnPQjb5RL+SNWncvb1ejO3KcRHj8LjZGd3XgEgnYeJK7o/IiXTNBf6mKsl5YXedDzkC0jsvEONpYV1MOLNFc7SobDbefipzyhfPJMnlS62nDJYwDixgDLVFxQLoEJ4GSgLgoqYANcaKWTNKDwkdLtExWo9Uo5GQQ3ert0jVJNMRt0NmaJIrZbJ/yhpLr62v4EozcvgebdptFBaLf33HULpHcOyEJU/Lad+SQJvnurybldcJmOoQTbZLRYkz++SekZzMPw1ld7GiSZKEJ7oMQKpVgakdA1mFtLfCsYT7OjK3fDdGsbOqtU6x/whqNn87GcexBOfa+2KVlYswPdVV6Cmj5pNKWkWPAR6kjvLVBENSn3cDh9sWXLuOUM7Z3TenKQiERG7klS/K6J5ZEfCNivrGo6D1afwlPanND/6gH3Tc0BidQaEL+7MMT5p6iMtRJFR5Tlqxkz9tX645X6jeumk1I/dY9o1bfFwWnqeg1h/rNTBbviyzl9H3xQKtv0pom47ZD1G9j+/GuoWvUz2uVk4nKmw9hzfXmnUusBGTwz6ZFSUAhkN39/Retpl7igHZprquFphuskF5LFRtFGcPr1RXRrYXVhs0s3LBrJOUVTfNHXyDfOSLFuVs1Lfg6llgMduAK9r/SXbGnWnyN5mdl6anE8TSb7alOifeYCppvhGCiw9PaHqQClLgROaKoFYnJN0adKhAaG9cgpJiQ29YPtovoHCCU17Tnlp/lllYPDOuIsm3YKbTUiCSy8DpccouaOqL+UNUsdIlLySEDbZltI9kaYHO5Z0cAKvXrlk27E/ThNy0EKkZms3gI4/6DnA/FZsOpdpNbjXvDi/WnjTrGrdcnCd83NbCpTDGtFWuSmkNhMhhuL1+anXiDUKirEF3ObXRbVqcZZtiG1RvH/6AwB+gEGBr4vfUokEPJPc1StRzzw0Nai1eSNGWeKniDQXv4kcoZ+brZvCM//ka+22MWJO+LoiTfouL5sqAdHIlar1sHk33iJUz6XvGd2Hy6u53NsWt7qsO8bnd6LVABYou2qzLnTL6cg7lR4qRrnqbqYDGI8j6ZtvTEZVsAeQGrAsFd00Mt+olnm8PiytwEMb3hBfEuOeKrZ7nFfqpa9nTNKLcu2LKcTnMqU8ZtadtPd2pMVrdH0KKD69V5igDuKVa7UGonEMx/Zm5pl8xhO0Z6VSCh5oWcpyXGgXzKhKCVHzWh4r3UDc6iB5kJobucTTNe1HSasSrjuKW2JPspW5/Rq0OaViwVEtTQhIlw66uMs+wjdkJ/d6buaIUNx5g4FmIU9ibw6tXQLNaqsVxcaZc4L151IoqFnO3hgnVRQXddrdDkRE4PY9VHO7ra/wKsm5FbpfOdPkAW+qIGaXidf6SPakPV0hGp2d8q9IcpT6sNnI96ybXAsmK7tHoMOON+Z65r5HhUqisx3hYvvi4xsXWEq2SG+KXqSIAw9r3FsNA9A5xUNI7N3ECiEFOgRKJIASMmiGuMjAFINHhTaVS2V1u3xzEEqtqErftCygL2uq1dephuqbqjY/Pz1x5KoRs5Q+PIqUBBsJkzN2MujpiHjnPCLDAx075CqDpXP7g4iICpBB0+Xva003dsN+NpXWt7qpxW0/tpHRjVSZpO7+/TzHW56ukQknT0iWV44PYnUqq7PEDeNSM0RbvC4E9jC/QR6oigsqKqlkRIu8ynSiP1P5BE245S29Sg2cf74hAncLViVsuiVEmni0Q4ho/7nmw/p/X29NNW4G4lGeZ6MVIxdOz49LNhKgVpJhUC1T0CfjsjXWUwsLtjAjHpldAe13ZK6EAPd7qwUvkWr/rKy5f/H7/FMCv0mpCDPTFEP2SkLtcOP3E8gqAPyBjG+4W+s6nrpwuk7unbL1TxtLXXQAAVGGyCUjqgRD+NQ8m9reBUn6VvoN188P/2acfiln/qOVcJDQVK4dmqdGrL86vBp9WCi5XgcjKfprIt73Fyn8fa+CGqZ6bmJSg+C4hnYKhBqCFnQzuAtmGs+R3dw6LdzbYEPXAPIMxW3EvNaAgVn4KJC4i4hIdPQsOza/rlev4swJyHyzPAMgiVFigXa9MQViK8HakfE81saC46eGlvOljq1TT8//4IHeoME1oOw/UrdkbHiWg41193/wKX1CBc)

**Comment by Profiidev** [comment] 2024-09-12 07:29
Edit: It used to work in Vuetify v3.6.15 and does not work since v3.7.0

**Comment by KaelWD** [comment] 2024-09-18 04:42
Duplicate of #20354

**Closed by KaelWD** 2024-09-18 04:42 UTC
Labels: S: triage
