### ISSUE TITLE
[Feature Request] Allow drag on the v-range-slider

### ISSUE THREAD

**Issue by mbegg** [vuetifyjs/vuetify#11227] opened 2020-04-24 23:47 UTC
### Problem to solve
I set the min and max on the range slider to say 0 and 50, on the client view I select the range 5 to 10. It would be great to then be able to click between the thumb labels and 'slide the interval anywhere between min and max

### Proposed solution
Allow for mouse down to grab the current interval and allow for the range to slide up and down between min and max. If there is a way to currently do this with the mousedown event i would love to know :-)

**Comment by jacekkarczmarczyk** [comment] 2020-04-26 19:15
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9593

**Closed by jacekkarczmarczyk** 2020-04-26 19:15 UTC
Labels: triage
