### ISSUE TITLE
[Bug Report] Navigation drawer mini variant doesn't push content if width is specified

### ISSUE THREAD

**Issue by adriankreutz** [vuetifyjs/vuetify#9066] opened 2019-09-23 10:22 UTC
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
- setup a vue application with vuetify's app bar and navigation drawer with mini-variant.sync, as seen in the codepen example
- if the width is specified on the navigation drawer then the content will not be pushed aside, if you remove the attribute then the content will be moved when the navigation drawer is resized

### Expected Behavior
the content should be pushed when the navigation drawer expands from mini to "fullsize"

### Actual Behavior
the navigation drawer overlaps the content instead of pushing it

### Reproduction Link
<a href="https://codepen.io/adriankz/pen/WNeLBOw?editors=1010" target="_blank">https://codepen.io/adriankz/pen/WNeLBOw?editors=1010</a>

**Comment by afzalsayed96** [comment] 2019-11-21 14:43
Came here to report the same

**Comment by Requinschats** [comment] 2019-12-03 23:10
Here to report the same

**Comment by Requinschats** [comment] 2019-12-09 16:13
Any news ? @adriankreutz

**Comment by johnleider** [comment] 2020-01-03 23:14
Workaround: https://codepen.io/johnjleider/pen/gObXjoM?editors=1010

**Comment by johnleider** [comment] 2020-01-03 23:43
Duplicate of #8223 - It may not seem like it on the surface, but they stem from the same issue.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-03 23:43 UTC
Labels: C: VNavigationDrawer, T: bug, has workaround
