### ISSUE TITLE
[Bug Report] Icon (prepend inner) color on focused textfield (inverted, flat) in dark appbar doesn't change due to #fff !important

### ISSUE THREAD

**Issue by escapedcat** [vuetifyjs/vuetify#10353] opened 2020-01-28 02:26 UTC
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Mac OS 10.14.6

### Steps to reproduce
Use a "solo-inverted, flat, prepend-inner-icon" textfield within a "dark" appbar.

### Expected Behavior
Icon should have a different color on focused textfield (not be overwritten by `#fff !important`).  
Like with a non "dark" appbar the icon has different colors on non-focused/focused textfield. 

### Actual Behavior
Icon color doesn't change on focus due to:

```
.v-application .white-text {
  color: #fff !important;
  caret-color: #fff !important;
}
```

### Reproduction Link
<a href="https://codepen.io/escapedcat/pen/xxbewPP" target="_blank">https://codepen.io/escapedcat/pen/xxbewPP</a>

**Comment by johnleider** [comment] 2020-02-01 20:44
Duplicate of #8827

**Closed by johnleider** 2020-02-01 20:44 UTC
Labels: triage
