### ISSUE TITLE
[Feature Request] Add support for "box" layout for select fields

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#3935] opened 2018-04-26 15:38 UTC
### Problem to solve
Select fields currently stand out if using the "box" for v-text-fields as they don't currently support the box display.  

### Proposed solution
Add support, whatever that means.

**Comment by KaelWD** [comment] 2018-04-26 15:49
Duplicate of #1973

**Closed by KaelWD** 2018-04-26 15:49 UTC
