### ISSUE TITLE
[Bug Report] First tab in vertical tabs on mobile like display has a problematic margin

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#8664] opened 2019-08-21 17:12 UTC
![Screen Shot 2019-08-21 at 11 08 23 AM](https://user-images.githubusercontent.com/157217/63452809-76968500-c404-11e9-9771-a17de4b3eba3.png)

### Environment
**Vuetify Version:** 2.0.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Open codepen
Make window narrow such as to trigger mobile css breakpoints
Observe layout of first vertical tab

### Expected Behavior
First tab should be aligned with its sibling tabs.

### Actual Behavior
First tab has a left margin of 52px applied.

### Reproduction Link
<a href="https://codepen.io/MatthewAry/pen/JjPbvbX" target="_blank">https://codepen.io/MatthewAry/pen/JjPbvbX</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-22 09:00
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8294

**Closed by jacekkarczmarczyk** 2019-08-22 09:00 UTC
Labels: triage
