### ISSUE TITLE
[Bug Report][3.0.0-beta.15] v-select keyboard accessibility 

### ISSUE THREAD

**Issue by NoclainBenjamin** [vuetifyjs/vuetify#15974] opened 2022-10-26 07:47 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.15
**Vue Version:** 3.2.41
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
Focus the select field and press space to open it.
In Vuetify 3 you can't navigate on select option with keyboard arrows (up and down)

### Expected Behavior
Navigation in select options with arrows (up and down)

### Actual Behavior
Not possibility to navigate in select options with keyboard

### Reproduction Link
[https://codepen.io/NoclainBenjamin/pen/wvXvLMZ](https://codepen.io/NoclainBenjamin/pen/wvXvLMZ)

**Comment by KaelWD** [comment] 2022-10-26 07:49
Duplicate of #15428

**Closed by KaelWD** 2022-10-26 07:49 UTC
Labels: S: triage
