### ISSUE TITLE
[Bug Report][3.3.7] v-menu closes on click keyboard tab

### ISSUE THREAD

**Issue by booscaaa** [vuetifyjs/vuetify#17775] opened 2023-07-10 20:33 UTC
### Environment
**Vuetify Version:** 3.3.7
**Last working version:** 2.6.16
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
- Access the reproduction link
- Click on Filter Button 
- Select the Status on Autocomplete
- Click tab on keyboard

### Expected Behavior
Change the focus to next input field.

### Actual Behavior
Close v-menu

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVltr2zAU/itnZpAWqrhXBiEtHRtj73vYQ12oYp80WmVJSHLaEvLfdyQ5jWOnJWx5ss/5zu07F+dulX01ZrxsMJtkU4+1kdzjTaEApkvGjYmP8aXUynOh0LaiKKxRNTAppXbItIoYVJ6VUpRP10U259JhkYFB64QLqg54xruYN6/kd5MHLJmT2k946cWSe20JvgJjtXGw3jGJycy86koAFigeF56MLq+KbFdVahndzWRDwXs6yZ0jXS3ZeV9nLBpUFRNUaoBUgs2F9Gj7QEpHqIogMd2+9iYZTfNB1l0e8k5DOmLqBbcV1EKxZ1H5BQW5Oj0lmr3wEuntR5tRn6Bgxjy++B1FVFn9DBUql3rfUxJZgbDAyRkxMoCkYWm8LjXlix6HAADJZyjJwy/PfTMgJP0mgioOYe5G4QnORieQns5H9/tNSonc8pncG5MGVFcxqvsgaqhb+FdChfxp2PbB8iEx1Dxi5Z8JC42g4UFZvXHzHV1JfdymXSXBngwPTihIqbu7sxCQe4dhMyVh5bRy2114CbswnJvBzgHMpC6f+sKP9o36xK3gKmzqnMZ9qD946wBu327PO4D3V29n+ToktVzsbGZSbU8hCcIt3JzL2InuvQySdE57Wz11pRXGg0PfpGsraqOthxVYnMMa5lbXMKILPUpHgPw6D7V7hOuAOBr9RCk1/NZWVp9Gx1tIGvkWpRopO7owV7uarS7xQ9qjY7i+gVUqiUu0/ujh8yq5HS85dXINDD6vgrP2/SHGWIcqU11UUXaSpZJYzc34j9OKvjXRa9EqaC8nmzhFRqWG9yJbeG/cJM/LSpEZLYRY2rFCnytT57cEy22jvKiRVbq+vRhfjC/zij4zXfEYXc1mNP8OLTkpspNOGC/mrweEapExwpcUoRUxWlwXQgxc5xRviZZZGlu0YQ4Pq6hn1q2qpxpU1jK/Jr6lUE+uR3XpIs13myT/q+ToLHi6TwG/0Vlq/0Vk65MsZk3iaJ7d/wUpoXYa)

**Comment by avarixe** [comment] 2023-07-17 22:21
duplicate of #17645?

**Closed** 2023-07-18 04:13 UTC
Labels: S: triage
