### ISSUE TITLE
[Documentation] Issue with Bottom sheet playground

### ISSUE THREAD

**Issue by LucasGalhardoLima** [vuetifyjs/vuetify#8180] opened 2019-07-30 12:47 UTC
### Environment

**Browsers:** Opera 60.0.3255.95
**OS:** Linux x86_64

### Steps to reproduce
Set to hide the overlay, then click on "open playground"; when you close the bottom sheet and enable the overlay again a overlay will appear and cover the entire screen.

### Expected Behavior
The overlay should open just when the button is clicked.

### Actual Behavior
The overlay appears by only disabling the switch.

### Reproduction Link
<a href="https://vuetifyjs.com/pt-BR/components/bottom-sheets" target="_blank">https://vuetifyjs.com/pt-BR/components/bottom-sheets</a>

**Comment by MajesticPotatoe** [comment] 2019-07-30 12:49
Duplicate of #8142

**Closed by MajesticPotatoe** 2019-07-30 12:49 UTC
Labels: triage
