### ISSUE TITLE
[Bug Report] v-edit-dialog missing buttons

### ISSUE THREAD

**Issue by emrahatalay** [vuetifyjs/vuetify#10532] opened 2020-02-10 06:19 UTC
### Environment
**Vuetify Version:** 2.2.11
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
      <v-edit-dialog 
        :return-value.sync="xx"
         large
         cancel-text="txtCancel"
         save-text="txtSave"
         @save="hello(item)"
        >
          {{ xx }}
          <template v-slot:input>
            <v-text-field
              v-model="xx"
              class="mt-5 pt-0"
             />
           </template>
        </v-edit-dialog>

### Expected Behavior
'Save' and 'Cancel' buttons should shown

### Actual Behavior
...

### Reproduction Link
<a href="https://codepen.io/eatalay/pen/MWwwWKm" target="_blank">https://codepen.io/eatalay/pen/MWwwWKm</a>

**Comment by jacekkarczmarczyk** [comment] 2020-02-10 06:52
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10522

**Closed by jacekkarczmarczyk** 2020-02-10 06:52 UTC
Labels: triage
