### ISSUE TITLE
[Documentation] Wrong Codepen Example Code of Stepper Component

### ISSUE THREAD

**Issue by yamamo-t** [vuetifyjs/vuetify#10614] opened 2020-02-19 08:48 UTC
### Environment

**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.3

### Steps to reproduce
Access the document page and display the example of the Stepper Component

### Expected Behavior
Display the first content of the Stepper Content

### Actual Behavior
Not display any contents and the number color of current steps is gray

### Reproduction Link
<a href="https://vuetifyjs.com/ja/components/steppers#usage" target="_blank">https://vuetifyjs.com/ja/components/steppers#usage</a>

**Comment by KaelWD** [comment] 2020-02-19 08:57
Duplicate of #10270

**Comment by yamamo-t** [comment] 2020-02-19 09:03
```js
new Vue({
  el: '#app',
  vuetify: new Vuetify(),
  data () {
    return {
      e1: 1, // not 0
    }
  },
})
```

**Closed** 2020-02-19 13:47 UTC
Labels: C: VStepper, T: documentation
