### ISSUE TITLE
[Feature Request] Support to time select component

### ISSUE THREAD

**Issue by bonboyaju19** [vuetifyjs/vuetify#7789] opened 2019-07-10 14:08 UTC
### Problem to solve
For example, when you want to create a UI like a timer, Time piclers can only represent time point, not time interval.
A timer does not need to represent AM or PM.
And, a timer can count minutes or seconds, not hours
But, Time pickers do not support to that.

### Proposed solution
Support to time select like Ruby on Rails.
Or, support to new property: "disuse-hours" and "disuse-minutes" to TIme pickers.

Best Regards.

**Comment by jacekkarczmarczyk** [comment] 2019-07-10 15:29
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2763

**Closed by jacekkarczmarczyk** 2019-07-10 15:29 UTC
Labels: triage
