### ISSUE TITLE
[Bug Report][2.2.19] clicking prepend-icon in v-text-field should bring up v-menu when used in v-time-picker

### ISSUE THREAD

**Issue by milost1982** [vuetifyjs/vuetify#10964] opened 2020-03-29 12:22 UTC
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Click on v-text-field input, time picker is activated.
Click on icon in v-text-field, time picker is not activated.

### Expected Behavior
Time picker is activated when icon is clicked in text field

### Actual Behavior
Time picker is not activated 

### Reproduction Link
<a href="https://codepen.io/milost1982/pen/OJVdLPJ?editors=1010" target="_blank">https://codepen.io/milost1982/pen/OJVdLPJ?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment] 2020-03-29 12:58
Technically it's duplicate of https://github.com/vuetifyjs/vuetify/issues/8141, however i'm leaning to a version that if no `click:prepend`/`click:append` listener is defined then clicking on the icon should run the `click` listener
@vuetifyjs/core-team ?

**Comment by milost1982** [comment] 2020-04-03 20:10
@jacekkarczmarczyk could you please tell me how can I add click listener on prepend/append icon if my v-text-field is inside slot template? Eg:
          <template v-slot:activator="{ on }">
            
            <v-text-field
              v-model="date"
              label="Picker in menu"
              prepend-icon="event"
              readonly
              v-on="on"
            ></v-text-field>
          </template>

I create the example based on docs so you can see it here:
https://codepen.io/milost1982/pen/YzXbvyx?editors=1010

**Comment by jacekkarczmarczyk** [comment] 2020-04-03 20:17
`@click:prepend="on.click"`

**Closed** 2023-08-09 12:57 UTC
Labels: T: bug, C: VTextField
