### ISSUE TITLE
[Bug Report][3.1.11] horizontal Rangeslider slider-thumb not slideable in navigation-drawer

### ISSUE THREAD

**Issue by FloKaemmerer** [vuetifyjs/vuetify#17143] opened 2023-04-13 13:41 UTC
### Environment
**Vuetify Version:** 3.1.11
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add a Horizontal range Slider inside a navigation drawer.
can also be wrapped in a v-card.

vertical Rangesliders work as expected

### Expected Behavior
The Rangeslider Range can be changed using the slider Thumbs

### Actual Behavior
Slider thumbs stay centered in the Rangeslider.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUstu4zAM/BVBl+4CkZWge9kgXXS/I8pBsZlWrSQLFOOiCPLvpWw3zaNAXzqZ5HCGHHq5k/9TqrotyLlcEITkLcE/E4VYdMrb53ZLHBkyxHG0nbuz5NqoGrRPgCIBBhshFpDoH8PQxjtQ2bsG8DX99joV2gb8jZEDvZGnmAPTyKdPCQ/lI8GcbM2VAh0/L2W/NBmh7QCzXTvv6Pl8wvIah1AXJxjNUHK19d/ZpCQvbB0bS+1wgoU+ug6HuUaXSGSgbeKMC6lFEjuBsBF7scE2iCs+61WhMtEDiYFK3BTIr+V0ImbT1e+hdLrvG2RALPQgxjJyIgclFWyqHnIb+b/Z9RpjIRs5F32m5HiCEht5T5TyXOu6idzGLrsOqwikYwr6lmEat5FcANW04fa6uq6myvp0b6u/unGZjssV5KDW2D5lQCYzcnIkR27DB/tQckSy0qya/Rkkxhx7vs5F44JbsyD7pBAi349/oU+udtb23npnkIsVyxR7E/d8AO/iYz7zvs6978vXYX+2e89WqFZFcT+RJwPzCEOnXL0AfixbGQ==)

**Comment by websitevirtuoso** [comment] 2023-04-13 16:45
I think you forget to wrap everything into <v-app>

**Comment by websitevirtuoso** [comment] 2023-04-13 18:11
like
```
<template>
  <v-app>
  <v-layout>
		<v-navigation-drawer permanent>
      <v-range-slider
                v-model="layout"
            >
            </v-range-slider>
      
      <v-spacer></v-spacer>
                  <v-range-slider
                v-model="traversability"
                direction="vertical"
            >
            </v-range-slider>
  </v-navigation-drawer>
    </v-layout>
    </v-app>
</template>
```

v-app is main tag for vuetify.

**Comment by FloKaemmerer** [comment] 2023-04-13 19:58
the v-app fixes it, but I'm wondering why the vertical slider does not need to be wrapped in v-app.

I'd fuess there is still something off here.

**Comment by KaelWD** [comment] 2023-04-14 08:18
Duplicate of #16586

**Closed by KaelWD** 2023-04-14 08:18 UTC
Labels: S: triage
