### ISSUE TITLE
[Bug Report][3.3.7] Date Picker selects a day behind between Oct 10th and Dec 31st any year

### ISSUE THREAD

**Issue by TB1786** [vuetifyjs/vuetify#17773] opened 2023-07-10 16:26 UTC
### Environment
**Vuetify Version:** 3.3.7
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows

### Steps to reproduce
View on components page in documentation https://vuetifyjs.com/en/components/date-pickers/

### Expected Behavior
Expect the selected date to be the one you click.

### Actual Behavior
The selected date is 1 day before the one you select.

### Reproduction Link
[https://codepen.io/TB1786/pen/RwqjJzL](https://codepen.io/TB1786/pen/RwqjJzL) Pen does not work

### Other comments
This issue is on any year between October 10th and December 31st

**Comment by avarixe** [comment] 2023-07-10 19:13
this looks to be happening whenever the month and date are both 2 digits (i.e. 10/10 - 10/31, 11/10 - 11/30, 12/10 - 12/31). 11/9 was selected with no issues

here's a reproduction link that works: https://play.vuetifyjs.com/#eNqlkMFuwyAMhl8l4hzg0EmTomjqnqP0QIOnsQaDDM00VXn3AU2lKL1U6g1+//4/24cr+wxBTBdgHesTuDDqBB8Km6afuA6hPutn8Ji0RaBFqqLJbh7scAZq5N0rt+ai3LJ6uWKwllkXPCXudBA/0WMe4loa1FKIinVNVYqWpyx/xb5TCrGTcjCY2wyMdiKBkCQGJ/fZJumCyTrgxrv9TuzEmzQ2prUsIDp+Iv8bgXKIYu0Kk+zX3xOoxVkJ7zfCIvFRn2JBPETLzJuAOAEaIKBnN9q0rbfalB42K/RZ4ZzvPVo8x82ph1jPfLgP+dLKNawkHQtwblmdM5NrAzv+A4Lr0UQ=

**Comment by KaelWD** [comment] 2023-08-09 09:24
Duplicate of #17615

**Closed by KaelWD** 2023-08-09 09:24 UTC
Labels: S: triage
