### ISSUE TITLE
[Bug Report] v-slider causing  "Uncaught TypeError: Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by JeffersonSchuler** [vuetifyjs/vuetify#7347] opened 2019-05-31 03:33 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.5

### Steps to reproduce
Slide the slider from left to right.

### Expected Behavior
No error message logged.

### Actual Behavior
Uncaught TypeError: Cannot read property 'id' of undefined
    at VueComponent.getValue (VTabsItems.js?aac8:41)
    at VueComponent.prev (VWindow.js?f665:94)
    at VueComponent.prev (VTabsItems.js?aac8:54)
    at handleGesture (touch.js?c341:14)
    at _touchend (touch.js?c341:32)
    at HTMLDivElement.touchend (touch.js?c341:63)

### Reproduction Link
<a href="https://codepen.io/jeffersonschuler/pen/RmqgVo" target="_blank">https://codepen.io/jeffersonschuler/pen/RmqgVo</a>

**Comment by jacekkarczmarczyk** [comment] 2019-05-31 03:37
Can't reproduce on chrome

**Comment by JeffersonSchuler** [comment] 2019-05-31 03:39
I am using Chrome on Mojave.

**Comment by jacekkarczmarczyk** [comment] 2019-05-31 03:41
Ok, I got it, but had to switch to mobile view

**Comment by JeffersonSchuler** [comment] 2019-05-31 03:42
Oddly, it does not occur if you slide from right to left.

**Comment by jacekkarczmarczyk** [comment] 2019-05-31 03:47
You're markup is completely wrong (like opening tag and then closing another tag) and there's no `v-tab-item`
https://codepen.io/anon/pen/gJQRjG?editors=1000

**Closed by jacekkarczmarczyk** 2019-05-31 03:47 UTC
Labels: triage

**Comment by JeffersonSchuler** [comment] 2019-05-31 03:59
The v-tab-item was a paste issue.  With it removed, the issue is still there.  Can you point out what you mean by "You're markup is completely wrong (like opening tag and then closing another tag) "?

Thanks.

**Comment by jacekkarczmarczyk** [comment] 2019-05-31 04:00
```html
          <v-tabs-items v-model="tab">
            <div v-show="currentTab === 0">
              </v-tabs-items>
                <v-slider
                    v-model="level"
                    step="10">
                </v-slider>
            </v-container>
```

**Comment by JeffersonSchuler** [comment] 2019-05-31 04:24
My apologies, on what was pasted in the code pen.  This should be formatted correctly, and produces the same error.

<div id="app">
   <v-app>
      <v-content>
         <v-container grid-list-xl>
            <v-tabs
               v-model="tab"
               align-with-title
               color="white">
               <v-tabs-slider color="yellow"></v-tabs-slider>
               <v-tab
                  v-for="(item, index) in tabItems"
                  :class="{active: currentTab === index}"
                  @click="currentTab = index"
                  :key="item">
                  {{ item }}
               </v-tab>
            </v-tabs>
            <v-tabs-items v-model="tab">
               <div v-show="currentTab === 0">
                  <v-slider
                     v-model="level"
                     step="10">
                  </v-slider>
               </div>
            </v-tabs-items>
         </v-container>
      </v-content>
   </v-app>
</div>

**Comment by JeffersonSchuler** [comment] 2019-05-31 04:29
I reformatted the code: https://codepen.io/jeffersonschuler/pen/RmqgVo

It is still producing the same error.

**Comment by jacekkarczmarczyk** [comment] 2019-05-31 04:31
Still you have no `v-tab-item` in your markup, see my codepen in previous comment

**Comment by JeffersonSchuler** [comment] 2019-05-31 04:41
Ok, I see what you mean now.  Thank you.  The error is gone.
