### ISSUE TITLE
[Bug Report][3.0.0-beta.9] v-img with eager apply a display none on img (nuxt js)

### ISSUE THREAD

**Issue by db-conception** [vuetifyjs/vuetify#15678] opened 2022-08-24 08:59 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.9
**Vue Version:** 3.0.0-rc.6
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a nuxt project 3.0.0-rc.6

Past my package.json : 
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "start": "node .output/server/index.mjs",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "test": "jest"
  },
  "devDependencies": {
    "@babel/core": "^7.18.10",
    "@babel/preset-env": "^7.18.10",
    "babel-jest": "^28.1.3",
    "jest": "^28.1.3",
    "nuxt": "3.0.0-rc.6",
    "sass": "^1.54.0",
    "sass-loader": "^13.0.2"
  },
  "dependencies": {
    "@nuxtjs/composition-api": "^0.33.0",
    "@pinia/nuxt": "^0.3.0",
    "pinia": "^2.0.16",
    "vuetify": "^3.0.0-beta.9"
  }
}

```
Then in nuxt.config.js add :
```
build: {
      transpile: ["vuetify"]
    }
css:[
      "vuetify/lib/styles/main.sass"
    ],
```
Then in a page, add v-img
```
<v-img 
            :src="desti.picture"
            cover 
            :eager="true"
            class="dp-background"> 
        </v-img>
```

### Expected Behavior
The image should be shown

### Actual Behavior
The image is not displayed. Because a css display: none is applied

### Reproduction Link
<a href="https://codepen.io/db-conception/pen/ExEJoPJ" target="_blank">https://codepen.io/db-conception/pen/ExEJoPJ</a>

### Other comments
Sorry i am not comfortable with code pen to create a nuxt project with...

https://i.imgur.com/t1Vsh3p.png

https://i.imgur.com/IB1HGeH.png

**Comment by malkomich** [comment] 2022-09-05 18:11
It looks like the `display: none` is set when the `eager` property is on, but when they do not have `eager` property, the `img` tag is just removed from DOM.

It only happens to me when I have the cache enabled, if I disable cache in the Browser Dev Tools it works fine.

I had to set a `display: block !important` globally to `.v-img img` tags, together with the `eager` property. It is the only workaround I found meanwhile the error is identified.

**Comment by db-conception** [comment] 2022-09-05 19:16
> It looks like the `display: none` is set when the `eager` property is on, but when they do not have `eager` property, the `img` tag is just removed from DOM.
> 
> It only happens to me when I have the cache enabled, I access to any link and go back to get the components mounted again. If I disable cache in the Browser Dev Tools it works fine.
> 
> I had to set a `display: block !important` globally to `.v-img img` tags, together with the `eager` property. It is the only workaround I found meanwhile the error is identified.

Yes I did too the glitch with display block for the moment. It's very strange.

**Comment by johnleider** [comment] 2022-11-30 20:56
closing in favor of #15832 since it has a reproduction

**Closed by johnleider** 2022-11-30 20:56 UTC
Labels: S: needs reproduction, S: triage

**Comment by fareed13** [comment] 2023-02-11 20:19
> closing in favor of #15832 since it has a reproduction

Why we are getting this issue in vuetify 3.1.4 ?

Currently I'm using vuetify 3.1.4 version and getting v-img display none or i used globally display block to resolve but it didn't work then i add eager true to load v-img tag in dom also add aspect ratio 1.5 for image visibility on browser after these three step image show can anyone help me out is this is glitch?

Even If i print {{media}} what src i'm getting while dynamically components using it shows the src and image is perfectly open in new tab but still didn't load in Dom 

 
Anyhow v-img is working fine when give src hard coded or through data property binding :src"myImage"

**Comment by db-conception** [comment] 2023-02-12 13:05
> > closing in favor of #15832 since it has a reproduction
> 
> Why we are getting this issue in vuetify 3.1.4 ?
> 
> Currently I'm using vuetify 3.1.4 version and getting v-img display none or i used globally display block to resolve but it didn't work then i add eager true to load v-img tag in dom also add aspect ratio 1.5 for image visibility on browser after these three step image show can anyone help me out is this is glitch?
> 
> Even If i print {{media}} what src i'm getting while dynamically components using it shows the src and image is perfectly open in new tab but still didn't load in Dom
> 
> Anyhow v-img is working fine when give src hard coded or through data property binding :src"myImage"

Hi,

It the css glitch doesn't work. It's probably a css priority problem. Can you show us all css rules applied to the display none element please ? Or just add '!important' after having check that your selector target the well element.

**Comment by fareed13** [comment] 2023-02-12 22:14
> > > closing in favor of #15832 since it has a reproduction
> 
> > 
> 
> > Why we are getting this issue in vuetify 3.1.4 ?
> 
> > 
> 
> > Currently I'm using vuetify 3.1.4 version and getting v-img display none or i used globally display block to resolve but it didn't work then i add eager true to load v-img tag in dom also add aspect ratio 1.5 for image visibility on browser after these three step image show can anyone help me out is this is glitch?
> 
> > 
> 
> > Even If i print {{media}} what src i'm getting while dynamically components using it shows the src and image is perfectly open in new tab but still didn't load in Dom
> 
> > 
> 
> > Anyhow v-img is working fine when give src hard coded or through data property binding :src"myImage"
> 
> 
> 
> Hi,
> 
> 
> 
> If the css glitch doesn't work. It's probably a css priority problem. Can you show us all css rules applied to the display none element please ? Or just add '!important' after having check that your selector target the well element.

Thanks for your reply i tested it's working fine in new project. Issue maybe in my project i will resolve it my own now.
