### ISSUE TITLE
[Feature Request] Date + time picker both in one component  required

### ISSUE THREAD

**Issue by shahzaibanwar009** [vuetifyjs/vuetify#6050] opened 2019-01-04 05:08 UTC
### Problem to solve
this can solve a problem of picking date and time in one way

### Proposed solution
add time feature along with date calander

**Comment by jacekkarczmarczyk** [comment] 2019-01-04 05:10
Duplicate of https://github.com/vuetifyjs/vuetify/issues/459

**Closed by jacekkarczmarczyk** 2019-01-04 05:10 UTC
