### ISSUE TITLE
[Bug Report][3.3.7] Crousel Direction not working

### ISSUE THREAD

**Issue by Arshad1114** [vuetifyjs/vuetify#17781] opened 2023-07-11 05:08 UTC
### Environment
**Vuetify Version:** 3.3.7
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Create a crousel and make it cycle and try verticle location

### Expected Behavior
Images scroll vertically

### Actual Behavior
Images scrolling horizontally

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFks9uwyAMxl8l4tzAYZMmVdnUPUfpgYLXkoU/wiTTVPXdBzRdk/bSaZp2gw/bP/sz6wN59Z4OPZAlaSIY34kIL9xWVTPUwvtyLBfpbBTaQhilkyiC6xG6SukAMmpnnzkZIEQtRcfJd+gsuNYJdHmpKgwype1j9LhkTCqbG4r67bNFKp1h2ogdIEv5Cply8h1p63ecTGtIl7AXgf0Feu8idP+Dxt7iPrn/A3rDLvDzGrM022NWTmtu2GT9ZEG08S7E2ghPW3Q2/Y9DTuDjA3KyrIqStdR5vs/HaVFBp4dALURmvWGrFMZCb6M2UCtnVg/0gT4ypTFOZQpo6m1wHwghFeFkMcFkg+5AjZGF8HQijFLdiS1mxE1plnjJyzqAVRCSqXdOdJU2nerq6WayTD9ye0x+d9rmfz2zWmKxeX1u8lcjl2K50iYDjwtS+kzkkkA2Xy1DTtE=)

**Comment by johnleider** [comment] 2023-07-11 21:48
duplicate of https://github.com/vuetifyjs/vuetify/issues/17586

**Closed by johnleider** 2023-07-11 21:48 UTC
Labels: T: bug, C: VCarousel
