### ISSUE TITLE
[Bug Report] Modal not locking body scroll

### ISSUE THREAD

**Issue by kennedyoliveira** [vuetifyjs/vuetify#9676] opened 2019-11-13 04:55 UTC
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Can be reproduced on desktop browser with mobile view enable or in a mobile device
1 -> Open a modal
2 -> Click on a non-scrollable part of the modal and move it around, it will scroll the body

### Expected Behavior
Should NOT scroll the body while the modal is open

### Actual Behavior
The body is being scrolled

### Reproduction Link
<a href="https://codepen.io/kennedyoliveira/pen/BaaOVoO?editors=0110" target="_blank">https://codepen.io/kennedyoliveira/pen/BaaOVoO?editors=0110</a>

### Other comments
I was not able to describe it effectively, but here is a quick video demonstrating the problem https://drive.google.com/file/d/14F-hEW0lxPjWQKVUSQN0NnKB0BG2UEnV/view?usp=sharing

It only happens in a mobile view, with a bigger screen it doesn't happen, you can do that on basically any example in the dialogs documentation https://vuetifyjs.com/en/components/dialogs

**Comment by jacekkarczmarczyk** [comment] 2019-11-13 08:14
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8105

**Closed by jacekkarczmarczyk** 2019-11-13 08:14 UTC
Labels: triage
