### ISSUE TITLE
[Bug Report] Nested VDialogs inside full screen dialog remove overflow-y-hidden class from html element.

### ISSUE THREAD

**Issue by KovalRomanK** [vuetifyjs/vuetify#12001] opened 2020-08-05 07:58 UTC
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Windows 10

### Steps to reproduce
Open the first dialog. Then open the second dialog. When you click outside the second dialog and close it the `overflow-y-hidden` class will be removed from the html element even though the first, fullscreen, dialog is still visible. 

### Expected Behavior
The overflow remains hidden while the fullscreen dialog is open.

### Actual Behavior
The overflow goes back to normal.

### Reproduction Link
<a href="https://codepen.io/romankoval10/pen/PoNopxV?editors=1010" target="_blank">https://codepen.io/romankoval10/pen/PoNopxV?editors=1010</a>

### Other comments
This bug is visible in the Vuetify documention too, under [nested dialogs](https://vuetifyjs.com/en/components/dialogs/#nested-dialogs). I think a dialog should only remove the `overflow-y-hidden` class if that dialog is the one that added it. In that case maybe a new class can be created that the dialogs will toggle and check if it exists on mount such as `dialog-overflow-y-hidden`.

**Comment by fkoeppling** [comment] 2020-10-12 17:48
Encountered the same issue, leads to layout shifting when the scrollbar pops in and out. 
One could counter this with some logic to reapply the `overflow: hidden` if not all Dialogs are set to `false`.
I might try that and share my findings...

**Comment by KaelWD** [comment] 2020-10-13 06:41
Duplicate of #5356

**Closed by KaelWD** 2020-10-13 06:41 UTC
Labels: triage

**Comment by tr-evo** [comment] 2024-06-27 16:54
It appears the bug is still present in version 2.6.14, despite this issue being closed.
