### ISSUE TITLE
[Enhancement] scroll-threshold expects Number got String

### ISSUE THREAD

**Issue by neXorianus** [vuetifyjs/vuetify#3269] opened 2018-02-13 17:18 UTC
### Versions and Environment
**Vuetify:** 1.0.0
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Mac OS 10.12.6

### Steps to reproduce
add `scroll-threshold="100"` to any toolbar

### Expected Behavior
the number used in the attribute (as string) is used

### Actual Behavior
`[Vue warn]: Invalid prop: type check failed for prop "scrollThreshold". Expected Number, got String.`

### Reproduction Link
[https://codepen.io/anon/pen/yvoOEV](https://codepen.io/anon/pen/yvoOEV)

### Other comments
Workaround is to use v-bind:
`:scroll-threshold="100"`

**Comment by johnleider** [comment] 2018-02-13 23:14
This is not a bug but an enhancement. Technically that prop is designated as a Number.

**Comment by blalan05** [comment] 2019-04-02 16:17
This seems fixed in 2.0 alpha

**Closed by blalan05** 2019-04-02 16:17 UTC
Labels: T: enhancement
