### ISSUE TITLE
[Bug Report] Data Table Header width does not accept number values

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#8686] opened 2019-08-22 16:32 UTC
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a data table and specify headers and items.
Give one of the headers a width property. Give that property a number.

### Expected Behavior
API Documentation for the headers prop states that you can give a header object a width property with a number data type. However it seems that it does not work.
https://vuetifyjs.com/en/components/data-tables#api

### Actual Behavior
Only strings in the format of `200px` are accepted and not numbers. Numbers for widths are ignored.

### Reproduction Link
<a href="https://codepen.io/MatthewAry/pen/mdbRPoY" target="_blank">https://codepen.io/MatthewAry/pen/mdbRPoY</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-22 16:33
Fixed in https://github.com/vuetifyjs/vuetify/pull/8592

**Comment by jacekkarczmarczyk** [comment] 2019-08-22 16:34
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8591

**Closed by jacekkarczmarczyk** 2019-08-22 16:33 UTC
Labels: triage
