### ISSUE TITLE
[Bug Report] color prop not working on stepper step

### ISSUE THREAD

**Issue by andywhite8** [vuetifyjs/vuetify#3809] opened 2018-04-08 11:21 UTC
### Versions and Environment
**Vuetify:** 1.0.13
**Vue:** 2.5.16
**Browsers:** Chrome 63.0.3239.84
**OS:** Mac OS 10.13.4

### Steps to reproduce
Add the color prop to a v-stepper-step tag

### Expected Behavior
Change the color of the step circle

### Actual Behavior
No change

### Reproduction Link
[https://codepen.io/andywhite8/pen/ZxmdQx](https://codepen.io/andywhite8/pen/ZxmdQx)

**Comment by KaelWD** [comment] 2018-04-09 05:13
Duplicate of #3276

**Closed by KaelWD** 2018-04-09 05:13 UTC
