### ISSUE TITLE
[Bug Report] v-bottom-navigation's v-btn are't Vertical Centralization

### ISSUE THREAD

**Issue by cheneyweb** [vuetifyjs/vuetify#8067] opened 2019-07-26 16:46 UTC
### Environment
**Vuetify Version:** 2.0.1
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
use v-bottom-navigation follow the doc

### Expected Behavior
the text and icon Vertical Centralization

![image](https://user-images.githubusercontent.com/24515746/61967412-cc475f80-b007-11e9-9cc1-c67a7acb5592.png)

### Actual Behavior
the text and icon Centralized at the top

![image](https://user-images.githubusercontent.com/24515746/61967433-d9644e80-b007-11e9-9eaf-1b952ceefc1b.png)

### Reproduction Link
<a href="https://codepen.io/cheneyweb/pen/MNeEVe" target="_blank">https://codepen.io/cheneyweb/pen/MNeEVe</a>

**Comment by jacekkarczmarczyk** [comment] 2019-07-26 18:43
Can't reproduce in codepen
![image](https://user-images.githubusercontent.com/15625235/61974006-c2ad0000-afe5-11e9-8c35-8d12ac6e9c93.png)

**Comment by cheneyweb** [comment] 2019-07-27 02:05
> Can't reproduce in codepen
> ![image](https://user-images.githubusercontent.com/15625235/61974006-c2ad0000-afe5-11e9-8c35-8d12ac6e9c93.png)

I don't know why it work find with codepen，but It do have problem with my localhost env.

even I ceate a new vue project with vue-cli and follow the doc to install plugin，I only write one v-bottom-navigation for test，and this problem still happen.

It really confuse me

**Comment by cheneyweb** [comment] 2019-07-27 03:22
@jacekkarczmarczyk 

Finally, I find out how to fix this problem!

I have try a lot of times，and I find out if I append     <v-app-bar app/> in the App.vue，the style of v-bottom-navigation will be correct  !!!

I don't know why, but it work for me now.

and I still hope vuetify can fix this style problem as soon as possiable

![image](https://user-images.githubusercontent.com/24515746/61989357-bf0a8f00-b060-11e9-9278-5003b72e780f.png)

**Comment by jacekkarczmarczyk** [comment] 2019-07-27 09:27
If the buttons show differently in dev and production mode please provide similar information like in another bottom nav issue (screenshots of devtool in both modes etc), otherwise we will have to close the issue as not being able to reproduce (and therefor provide a fix)

**Comment by cheneyweb** [comment] 2019-07-27 16:27
> If the buttons show differently in dev and production mode please provide similar information like in another bottom nav issue (screenshots of devtool in both modes etc), otherwise we will have to close the issue as not being able to reproduce (and therefor provide a fix)

Here is the npm run serve result：

![image](https://user-images.githubusercontent.com/24515746/61996990-7d63fd80-b0cd-11e9-9087-482e92de66bf.png)

And Here is the npm run build result：
![image](https://user-images.githubusercontent.com/24515746/61997028-ea779300-b0cd-11e9-8a90-ae04cd4c3944.png)
![image](https://user-images.githubusercontent.com/24515746/61997036-0f6c0600-b0ce-11e9-81ea-862ee7721c86.png)

And If I kill the .v-btn:not(.v-btn--round).v-size--default    height:36px style，everything is ok

![image](https://user-images.githubusercontent.com/24515746/61997056-4fcb8400-b0ce-11e9-9fac-345e88e68671.png)

![image](https://user-images.githubusercontent.com/24515746/61997060-61149080-b0ce-11e9-837d-240ffea584b5.png)

**Comment by qinkaiyuan** [comment] 2019-09-25 04:42
```
<style>
    .v-item-group.v-bottom-navigation .v-btn.v-size--default {
        height: inherit;
    }
</style>
```

**Comment by Meowzz95** [comment] 2020-05-06 15:30
Hi, any progress on this bug? I have the same issue here...

vue serve:
![image](https://user-images.githubusercontent.com/22430379/81196370-86d1ad00-8ff1-11ea-9431-a20e2ee47525.png)

production build:
![image](https://user-images.githubusercontent.com/22430379/81196403-93ee9c00-8ff1-11ea-8e30-63dfcf7323d5.png)

**Comment by johnleider** [comment] 2020-12-10 17:28
This is hard to reproduce simply because we have no control over CSS ordering and it's random. With this being said, this will not be an issue for the framework in version 3.

I'm going to close this as a duplicate of #5681 and #3583 as it pertains to them.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-10 17:28 UTC
Labels: C: VBottomNavigation, CSS specificity, T: bug, good first issue, has workaround

**Comment by kasperskov909** [comment] 2021-02-04 15:17
FYI I can reproduce in Vuetify 2.3.9.

The build config renders some button styling with explicit height above the regular height:inherit from .v-item-group.v-bottom-navigation button styling.

**Comment by neelansh15** [comment] 2021-02-25 09:05
Adding on to this, 
 - I had the issue where the bottom nav would sink in and disappear even without the `hide-on-scroll` prop. I just had the `fixed` and `app` props. It was surprisingly fixed by setting body overflow to hidden in the layout.
 - Also, in **dark mode** the background colour was lighter for the buttons and the padding was lesser in prod than in `yarn dev`.  

Here is my complete bug fix in the style section of my default layout:
```css
body{
  overflow: hidden;
}
.v-item-group.v-bottom-navigation .v-btn.v-size--default {
    height: inherit;
    background: #2e2e2e;
    padding: 0 1.3rem;
}
```

**Comment by johnleider** [comment] 2021-02-25 13:42
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
