### ISSUE TITLE
[Feature Request] How add swiper like vue-awesome-swiper in navigation drawer?

### ISSUE THREAD

**Issue by tuanpn** [vuetifyjs/vuetify#11845] opened 2020-07-13 08:40 UTC
### Problem to solve
I made a hybrid app with Vuetify,
How add swiper in navigation drawer? (like vue-awesome-swiper)

### Proposed solution
navigation drawer can swiper like native app

**Comment by KaelWD** [comment] 2020-07-29 08:41
Duplicate of #3262

**Closed by KaelWD** 2020-07-29 08:41 UTC
Labels: triage
