### ISSUE TITLE
[Bug Report] V-Alert is always in dark mode (in combination with type prop)

### ISSUE THREAD

**Issue by Dominic-Marcelino** [vuetifyjs/vuetify#11021] opened 2020-04-04 15:19 UTC
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create an alert with a "type"-property and check the inspector-tools about the classes

### Expected Behavior
Main theme (if not defined different)

### Actual Behavior
The rendered component always get's the class "theme--dark"

### Reproduction Link
<a href="https://codepen.io/dom_codes/pen/qBdzBbo" target="_blank">https://codepen.io/dom_codes/pen/qBdzBbo</a>

**Comment by afenton90** [comment] 2020-06-08 14:27
I came across this today. Seems the issue is all over the place with `theme--dark` getting applied even when `theme.dark = false`

**Comment by KaelWD** [comment] 2020-06-08 15:41
https://github.com/vuetifyjs/vuetify/blob/15ba83bb6c81b683c7bc4d9092676da8d9a05faf/packages/vuetify/src/components/VAlert/VAlert.ts#L166-L171

Not sure what the justification for this is, I think it's like v-btn and assumes theme colours are always dark. We need to implement automatic contrast to remove this. https://github.com/vuetifyjs/vuetify/blob/001af08aeed2a65455429c3a928c9e56262c0882/packages/vuetify/src/components/VBtn/VBtn.sass#L4-L13

**Comment by johnleider** [comment] 2020-06-08 21:03
Yes this is bad and yes auto contrast detection is a day one v3 feature. Welcome to code from the beginning of the framework.

**Comment by clixmat** [comment] 2020-07-05 11:59
Hello everyone, do we have a fix that can help us with this?

**Comment by johnleider** [comment] 2021-07-01 20:31
fixed in #13855

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-07-01 20:31 UTC
Labels: C: VAlert, T: bug
