### ISSUE TITLE
[Theme Generator] Theme Generator not working - errors in the console

### ISSUE THREAD

**Issue by babinos87** [vuetifyjs/vuetify#9506] opened 2019-10-29 15:02 UTC
### Environment

**Browsers:** Firefox 69.0
**OS:** Ubuntu undefined

### Steps to reproduce
Go to https://theme-generator.vuetifyjs.com/. Choose any color. An error should be printed in the console. 

Happens both in Firefox and Chromium on my Lubuntu 18.04.

### Expected Behavior
Not sure how this site works since I tried for the first time, I guess it would export me the theme's properties?

### Actual Behavior
Error in the console. Nothing happens when I hit the export button.

### Reproduction Link
<a href="https://theme-generator.vuetifyjs.com" target="_blank">https://theme-generator.vuetifyjs.com</a>

Chromium error:
`
vue.runtime.esm.js:1737 TypeError: Cannot read property 'base' of undefined
    at a.getHexValue (ExportModal.vue:79)
    at a.i (ExportModal.vue?14ae:1)
    at a.t._render (vue.runtime.esm.js:4540)
    at a.r (vue.runtime.esm.js:2784)
    at sn.get (vue.runtime.esm.js:3138)
    at new sn (vue.runtime.esm.js:3127)
    at ze (vue.runtime.esm.js:2791)
    at a.sr.$mount (vue.runtime.esm.js:7995)
    at init (vue.runtime.esm.js:4133)
    at v (vue.runtime.esm.js:5604)
`

FF error:
`
TypeError: "this.colors[r(...)(...)] is undefined"
    getHexValue ExportModal.vue:79
    i ExportModal.vue:1
    VueJS 19
        _render
        r
        get
        sn
        ze
        $mount
        init
        v
        p
        O
        j
        vo
        _update
        r
        get
        run
        tn
        fe
        oe
vue.runtime.esm.js:1737
`

**Comment by MajesticPotatoe** [comment] 2019-10-29 15:15
Theme generator is old and hasn't been maintained for some time. There are plans to rework this at some point in the future. I'll leave this open for now as a reminder, but its also being tracked in #7047

**Comment by jacekkarczmarczyk** [comment] 2020-01-22 17:52
Duplicate of https://github.com/vuetifyjs/theme-generator/issues/9

**Closed by jacekkarczmarczyk** 2020-01-22 17:52 UTC
Labels: T: documentation
