### ISSUE TITLE
[Bug Report] Prepend inner icons and prefixes break labels for inputs in eagerly loaded content 

### ISSUE THREAD

**Issue by naffarn** [vuetifyjs/vuetify#8538] opened 2019-08-15 01:02 UTC
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
Add the following components to a `<v-dialog />` with the `eager` prop:
```
<v-text-field label="Label" prepend-inner-icon="event" outlined />
<v-text-field label="Label" prefix="$" />
```

### Expected Behavior
When the `prepend-inner-icon` field is focused, the label should move up above the icon to the left of the field, to the space provided for it, and not overlap the outline.
When the `prefix` field is unfocused, the label should sit to the right of the prefix text.

### Actual Behavior
When the `prepend-inner-icon` field is focused, the label should moves up vertically, and overlaps the field outline.
When the `prefix` field is unfocused, the label overlaps the prefix text.

### Reproduction Link
<a href="https://codepen.io/naffarn/pen/yLBOaQX" target="_blank">https://codepen.io/naffarn/pen/yLBOaQX</a>

### Other comments
The `outlined` prop isn't necessary to reproduce this bug, but it highlights the positioning issues for the icon field when it's focused. The same behavior happens in normal inputs, there just isn't an outline to be overlapped.
This issue also applies to other inputs such as selects and autocompletes.

**Comment by jacekkarczmarczyk** [comment] 2019-08-17 11:31
Duplicate of #7470

Workaround: https://codepen.io/jkarczm/pen/pozbwgO

**Closed by jacekkarczmarczyk** 2019-08-17 11:31 UTC
Labels: triage
