### ISSUE TITLE
[Bug Report][2.5.9] v-checkbox checks/unchecks when clicking far away from the label

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#14228] opened 2021-10-03 21:27 UTC
### Environment
**Vuetify Version:** 2.5.9
**Vue Version:** 2.6.14
**Browsers:** Chrome 94.0.4606.61
**OS:** Windows 10

### Steps to reproduce
1. Click on the right side of the checkbox far away from the label.
2. The checkbox checks/unchecks.

You can also see this bug on the GIF below (click the GIF to zoom it):

![vcheckbox_bug](https://user-images.githubusercontent.com/17653648/135772020-5ce007f6-ae0f-4d69-b1d8-372ac0efad25.gif)

### Expected Behavior
Checkbox should only check/uncheck when clicking on the checkbox or its label.

### Actual Behavior
Checkbox checks/unchecks when clicking far away from the label.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/vYZwmOG?editors=101" target="_blank">https://codepen.io/mikilll94/pen/vYZwmOG?editors=101</a>

### Other comments
You can also easily reproduce this bug in the Vuetify docs:
https://vuetifyjs.com/en/components/checkboxes/#usage

**Comment by KaelWD** [comment] 2021-10-04 05:04
Duplicate of #12278

**Closed by KaelWD** 2021-10-04 05:04 UTC
Labels: S: triage
