### ISSUE TITLE
[Bug Report] Data Table footer does not render properly in IE11

### ISSUE THREAD

**Issue by JeffreyStevens** [vuetifyjs/vuetify#9790] opened 2019-11-25 19:49 UTC
![Good Footer - Chrome](https://user-images.githubusercontent.com/34170674/69572717-5be72580-0f8a-11ea-8eb5-552f8406d291.jpg)
![Bad Footer - IE](https://user-images.githubusercontent.com/34170674/69572719-5e497f80-0f8a-11ea-92fc-13e3779a01a0.jpg)

### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Internet Explorer
**OS:** Mac OS 10.14.6

### Steps to reproduce
You can see it in IE in our actual application but I can't get codepen to run in IE.

### Expected Behavior
Footer 'Rows per page', selection drop down, pagination text, before and after icons run together (overlay each other).

### Actual Behavior
Footer 'Rows per page', selection drop down, pagination text, before and after icons should not overlay each other.

### Reproduction Link
<a href="https://codepen.io/jeff1132/pen/zYYQoZp" target="_blank">https://codepen.io/jeff1132/pen/zYYQoZp</a>

**Comment by JeffreyStevens** [comment] 2019-11-27 14:21
Current fix in my SCSS file:

```
//------------------------------------------------------------
// These are workarounds to fix the footer display in IE11.
//------------------------------------------------------------
.v-dialog .v-data-footer__select {
  flex: 1 1 auto;

  .v-select {
    flex-basis: 50px; // set minimum width of select menu
  }
}

.v-list-item .v-list-item__content {
  flex-basis: 25px; // set minimum width of menu item
  overflow: auto; // override overflow: hidden

  // The following is for Chrome select drop-down.
  .v-list-item__title {
    width: fit-content;
  }
}

```

**Comment by zayats103** [comment] 2019-12-04 08:53
I also have same problems with footer in IE so it would be nice to have this fixed.

**Comment by jacekkarczmarczyk** [comment] 2019-12-04 12:45
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9527

**Closed by jacekkarczmarczyk** 2019-12-04 12:45 UTC
Labels: C: VDataTable, platform specific, triage
