### ISSUE TITLE
[Bug Report] expension panels open laggy

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#10140] opened 2020-01-07 12:51 UTC
### Environment
**Vuetify Version:** 2.2.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
In the codepen click on the blue blocks to open the next expansion panel

### Expected Behavior
open fluently

### Actual Behavior
it opens laggy, perhaps because the v-for is still rendering

### Reproduction Link
<a href="https://codepen.io/ricardovanlaarhoven/pen/WNbwvev" target="_blank">https://codepen.io/ricardovanlaarhoven/pen/WNbwvev</a>

### Other comments
perhaps the expension panel is just missing an eager prop?

**Comment by YipingRuan** [comment] 2020-01-08 08:57
FPS remains high at 60, maybe the animation curve need to be adjust?
![panel](https://user-images.githubusercontent.com/5492274/71964050-d5379080-3237-11ea-8fdf-ff8ce4a57255.gif)

**Comment by KaelWD** [comment] 2020-01-08 09:05
Not performance or animation related, it opens fine if eager or the header is clicked on.

**Comment by ricardovanlaarhoven** [comment] 2020-01-08 14:19
How could i make it eager?

> perhaps the expension panel is just missing an eager prop?

Does the eager option exist? is it just undocumented?

**Comment by MajesticPotatoe** [comment] 2020-01-08 14:26
![123123](https://user-images.githubusercontent.com/27827979/71985629-f036e000-31f8-11ea-9317-cf5ceb337f85.png)

**Comment by ricardovanlaarhoven** [comment] 2020-01-08 14:31
ah sorry! you are right!
I did check the expansion panel**s** and the expansion panel component but not the content..

thanks!

**Comment by arxanas** [comment] 2020-03-30 06:50
The issue happens whenever you control the panel content externally. It reproduces in this example in the docs as well: https://vuetifyjs.com/en/components/expansion-panels/#external-control

It's very strange that the user clicking a panel to open it doesn't trigger the lag, but programmatically opening it does. I think this should be treated as a bug.

I also looked in the wrong place in the documentation. If not a bug, it should at least be addressed in the documentation, and the "external control" example should be updated to use `eager` and explain why it's necessary.

**Comment by alechewitt** [comment] 2020-04-19 23:02
Just trying out Vuetify today and I've also noticed this behaviour. As @arxanas says, it only happens when you programmatically open the panel for the the first time. Setting `eager` to  `true` on the `v-expansion-panel-content` prevents it happening.

**Comment by Gu3** [comment] 2021-06-02 14:36
Hi, 
some trick to improve this behaviour is to add "accordion" option inside the expansion-panels tag
`<v-expansion-panels v-model="panel" accordion>`
That will be kill the space between two panels and the expansion will be less laggy...

**Closed** 2021-06-02 16:34 UTC
Labels: C: VExpansionPanel, T: bug, has workaround
