### ISSUE TITLE
[Feature Request] VDialog does not have animation events

### ISSUE THREAD

**Issue by SanBen** [vuetifyjs/vuetify#7195] opened 2019-05-13 09:01 UTC
### Problem to solve
React to animation end and start of dialogs

### Proposed solution
Implement v-on:after-enter and v-on:before-enter for vDialog as are available for other components:
https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks

https://github.com/vuetifyjs/vuetify/issues/3454#issuecomment-415984337

**Comment by KaelWD** [comment] 2019-05-13 10:35
Duplicate of #6504

**Closed by KaelWD** 2019-05-13 10:35 UTC
Labels: triage
