### ISSUE TITLE
[Bug Report][3.0.0-beta.0] Form rules not reactive in new vuetify 3 project

### ISSUE THREAD

**Issue by PierreBrisorgueil** [vuetifyjs/vuetify#14931] opened 2022-04-07 07:05 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Safari 15.4
**OS:** Mac OS 10.15.7

### Steps to reproduce
1/ vue create my-beta-app
  ❯ Default (Vue 3 Preview) ([Vue 3] babel, eslint)
2/ vue add vuetify
  ❯ Vuetify 3 Preview (Vuetify 3)
3/ Replace "src/components/HelloWorld.vue" by first [form example](https://next.vuetifyjs.com/en/components/forms/) in documentation 

### Expected Behavior
mail rule should be reactive 

### Actual Behavior
mail rule isn't tested, no error is displayed with a wrong mail, it works in the [form example](https://next.vuetifyjs.com/en/components/forms/) page

### Reproduction Link
<a href="https://github.com/PierreBrisorgueil/Vue3FormExample" target="_blank">https://github.com/PierreBrisorgueil/Vue3FormExample</a>

### Other comments
maybe linked to https://github.com/vuetifyjs/vuetify/issues/14901

**Comment by KaelWD** [comment] 2022-04-07 07:10
Duplicate of #14901

**Closed by KaelWD** 2022-04-07 07:10 UTC
Labels: S: triage

**Comment by PierreBrisorgueil** [comment] 2022-04-07 07:44
👍 @KaelWD I preferred to make another example because, on a clean repo, the error is never displayed unlike the example of https://github.com/vuetifyjs/vuetify/issues/14901 which is reactive at the start
