### ISSUE TITLE
[Bug Report][3.1.8] v-autocomplete and v-select incorrect height when model value is empty or null

### ISSUE THREAD

**Issue by volarname** [vuetifyjs/vuetify#16901] opened 2023-03-13 10:50 UTC
### Environment
**Vuetify Version:** 3.1.8
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
1 - put several types of vuetify form components in one horizontal line, including v-text-field, v-autocomplete and v-select
2 - set v-select and v-autocomplete model value to null or emtpy string - this means they are not selected by default
3 - check height of components and bottom border of components

### Expected Behavior
the height and bottom line of components should be at same position vertically

### Actual Behavior
v-select and v-autocomplete height is incorrect and the bottom line doesnt match

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNVEFu2zAQ/ArBi1rAElskh8JwivQdpg+UtG7YUCRBrtwEhv+eXUkOFCdOkEMA37Qz1MxwV9r1Xv6Jsdr1IJdyhdBFZxB+ay/EaleaGIfHoeiM9aJxJucbLaMpr7WcyIFO4f9zOQBNcHPe9BiaQPqAIJaWrFhnXRhjioUo6rouNlqKFny2+EgUHzYNEkbeoQVHGB2m2pl6VlEmMMnUDtQsAHmqlxmEeC9eBgcNXmAwhAcstxZc+2aEWQZKysAxxFh+ZM3IfHSfneTOJGs8kl/vW0jOemjJ9mIHfCbvZQ/+XOiv/yC44h9/3AhUjCthpWargsrcJBtRZMCeadvFkFDsRYKtOIhtCp0oaMcUfLgJPqOgTokb5r99P0KUb4KKgsCVGlVJTy7kKElZYvUvB0/bas+R9ERkLZdiQBgjK661vEOMealU7+P934qapG6JU6n3aDso29DdXlVX1Y/SuHhnqmvV2oxzuoLclTX1I0MiYy0XMw+028dzPhNN8j+rX6PsBJU0j8y6r/QUmewglQl4ypDevcPJ2bfucXLk1V3Y+qD9gdpLn9R9Pulsk4euro8JP3/JQYFf37DLYSFfhCTb4UW5eQKcAQYZ)

**Comment by KaelWD** [comment] 2023-04-28 08:13
Duplicate of #15980

**Closed by KaelWD** 2023-04-28 08:13 UTC
Labels: T: bug, C: VField
