### ISSUE TITLE
[Bug Report] Unable to close v-select after pressing the tab key

### ISSUE THREAD

**Issue by c-tn** [vuetifyjs/vuetify#5471] opened 2018-10-29 10:55 UTC
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Linux x86_64

### Steps to reproduce
* open v-select
* press tab key
* try closing v-select without selecting a value

### Expected Behavior
closed v-select

### Actual Behavior
nothing

### Reproduction Link
[https://codepen.io/c_tn/pen/JmVWKB?editors=1010](https://codepen.io/c_tn/pen/JmVWKB?editors=1010)

**Comment by KaelWD** [comment] 2018-10-29 11:01
Since 1.2.0-beta.3: https://codepen.io/anon/pen/EdJWbp?editors=1010

**Comment by MatheusSouzaCC** [comment] 2018-12-19 10:08
Any workaround ?

**Comment by MatheusSouzaCC** [comment] 2018-12-20 10:24
I updated to version 1.3.15 and the problem is now fixed. 
Duplicate of [#5774](https://github.com/vuetifyjs/vuetify/issues/5774) (closed).

**Comment by KaelWD** [comment] 2018-12-20 10:32
Thanks, fixed by 8a2a1a1b6974ec264e974866b0775f2820dc3503 in 1.3.14

**Closed by KaelWD** 2018-12-20 10:32 UTC
Labels: T: bug, T: regression
