### ISSUE TITLE
[Bug Report] v-autocomplete menu overlaps inputfield

### ISSUE THREAD

**Issue by BestLice** [vuetifyjs/vuetify#13605] opened 2021-05-05 14:19 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Open codepen on an iPad and open the autocomplete field. 
The first entries will overlap the inputfield and your are not able to see, what you've had typed.

### Expected Behavior
The menu stays under the inputfield

### Actual Behavior
The first entries overlap the inputfield

### Reproduction Link
<a href="https://codepen.io/Harry1337/pen/qBrBERN" target="_blank">https://codepen.io/Harry1337/pen/qBrBERN</a>

**Comment by KaelWD** [comment] 2021-05-05 14:25
Duplicate of #4059

**Closed by KaelWD** 2021-05-05 14:25 UTC
Labels: triage

**Comment by usmanarain350** [comment] 2024-10-17 05:49
> ### Environment
> **Vuetify Version:** 2.3.10 **Vue Version:** 2.6.12 **Browsers:** Safari **OS:** iOS
> 
> ### Steps to reproduce
> Open codepen on an iPad and open the autocomplete field. The first entries will overlap the inputfield and your are not able to see, what you've had typed.
> 
> ### Expected Behavior
> The menu stays under the inputfield
> 
> ### Actual Behavior
> The first entries overlap the inputfield
> 
> ### Reproduction Link
> https://codepen.io/Harry1337/pen/qBrBERN



Vue component method to handle autofill for email and password fields
```
mounted() {
  this.checkAutofill();
},

methods: {
  checkAutofill() {
    // Select only the email and password input fields for autofill detection
    const els = this.$el.querySelectorAll('input[type="email"], input[type="password"]');
    els.forEach((el) => {
      el.addEventListener('animationstart', (event) => {
        if (event.animationName === 'onAutoFillStart') {
          const label = el.parentElement.querySelector('label');
          // Add the active class to the label if it exists
          if (label) {
            label.classList.add('v-label--active');
          }
        }
      });
    });
  },
}
```
Add the following to your CSS:

```
@keyframes onAutoFillStart {}
input:-webkit-autofill {
  animation-name: onAutoFillStart;
  animation-duration: 0.01s;
}
```
