### ISSUE TITLE
[Bug Report] Cannot detect which slot is active 

### ISSUE THREAD

**Issue by asadkhalid305** [vuetifyjs/vuetify#11606] opened 2020-06-11 12:15 UTC
### Environment
**Vuetify Version:** 1.5.5
**Vue Version:** 2.6.8
**Browsers:** Safari 13.1
**OS:** Mac OS 10.15.4

### Steps to reproduce
Enter any text in combobox, if there is no matching item available both v-slot:no-data and v-slot:prepend-item are getting active.

### Expected Behavior
Only v-slot:no-data should get active if there is no matching item available. 

### Actual Behavior
When I enter any text, if there is no matching item available both v-slot:no-data and v-slot:prepend-item are getting active.

### Reproduction Link
<a href="https://codepen.io/asad-ullah-khalid/pen/vYLGEZa" target="_blank">https://codepen.io/asad-ullah-khalid/pen/vYLGEZa</a>

### Other comments
I want to know if there is anyway we can stop no-data and prepend-item getting active at once?

**Comment by KaelWD** [comment] 2020-10-09 15:12
Duplicate of #11546

**Closed by KaelWD** 2020-10-09 15:12 UTC
Labels: triage
