### ISSUE TITLE
[Bug Report] VSkeletonLoader: presence of transition prop prevents correct parsing of type prop.

### ISSUE THREAD

**Issue by dschreij** [vuetifyjs/vuetify#11795] opened 2020-07-06 09:43 UTC
### Environment
**Vuetify Version:** 2.3.3
**Vue Version:** 2.6.11
**Browsers:** Chromium 83.0.4103.61
**OS:** Ubuntu undefined, Linux, Windows, Mac OSX

### Steps to reproduce
Add a v-skeleton-loader component and use an `@` multiplier in its type, or specify a comma-separated list of skeleton components. This works fine. Now add a `transition="fade-transition"` parameter to the v-skeleton-loader component. Only the first skeleton component is visible and @ modifiers, or anything else of the comma separated list are not processed anymore.

### Expected Behavior
The value for `type` is correctly processed, including `@` modifiers and comma separated lists when a transition prop is present.

### Actual Behavior
Only the first item specified by `type` appears and @ values and comma separated values are ignored.

### Reproduction Link
<a href="https://codepen.io/dschreij/pen/xxZYMLd" target="_blank">https://codepen.io/dschreij/pen/xxZYMLd</a>

**Comment by johnleider** [comment] 2021-06-22 22:10
Duplicate of #9410

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-06-22 22:10 UTC
Labels: S: triage
