### ISSUE TITLE
[Bug Report] Hiding of #activator template inside transition component

### ISSUE THREAD

**Issue by LiquidSolid** [vuetifyjs/vuetify#9276] opened 2019-10-08 09:30 UTC
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Linux x86_64

### Steps to reproduce
Click "show" button, then content in `v-slide-y-transition` will change. Then, click "close" button, and before transition toggles back, `<template #activator>` (outlined button) in `v-menu` will hide.

### Expected Behavior
The entire contents of the element with `v-menu` before the transition will not be changed

### Actual Behavior
The entire contents of the element with `v-menu` changes before the transition

### Reproduction Link
<a href="https://codepen.io/liquid-solid/pen/yLLyRNV" target="_blank">https://codepen.io/liquid-solid/pen/yLLyRNV</a>

### Other comments
Sorry for my bad english )

**Comment by the-owl** [comment] 2019-11-02 22:10
I think it's actually the same issue as https://github.com/vuetifyjs/vuetify/issues/7422

It's quite annoying when you have animated page transitions because all activator buttons disappear before transition ends.

However, I have found a hacky workaround that works in my case. You can create a wrapper component that wraps `v-menu` in some dom node, like this:
```vue
<template>
  <div>
    <v-menu ref="menu">
      <template #activator="{ on }">
        <button v-on="on">test</button>
      </template>
      <div>test</div>
    </v-menu>
  </div>
</template>

<script>
export default {
  beforeDestroy() {
    this.$refs.menu.activatorNode = null;
  },
}
</script>
```
This helps because `activatorNode` can no longer be removed in `beforeDestroy`, and will be destroyed by Vue along with its parent node. https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/mixins/detachable/index.ts#L97

**Comment by jacekkarczmarczyk** [comment] 2019-11-13 07:40
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7422

**Closed by jacekkarczmarczyk** 2019-11-13 07:40 UTC
Labels: triage

**Comment by bendytree** [comment] 2021-09-01 20:29
Stealing from @the-owl's solution, here's a simple mixin. Not sure, but it may need to run on `v-tooltip` as well.

```
Vue.mixin({
  beforeDestroy() {
    if (this.$options.name === 'v-menu') {
      this.activatorNode = null;
    }
  },
});
```
