### ISSUE TITLE
[Bug Report][3.3.9] v-list - unwanted scrolling up in iOS

### ISSUE THREAD

**Issue by PurpleTape** [vuetifyjs/vuetify#17841] opened 2023-07-19 21:17 UTC
### Environment
**Vuetify Version:** 3.3.9
**Vue Version:** 3.3.4
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
1. Scroll scrollable area
2. Click on "click me"

### Expected Behavior
Scrolling up does not happen

### Actual Behavior
Scrolling up is happening

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUk1vnDAQ/SuWz2u8bXoppVHanirlnEvIwYA366y/ZA/srqL97xlsSAi5RIq4MO/NvDfz4P6Z/vG+GHpJS1qBNF4LkNe1JaQamPA+vaaidRaEsjJMEIKdGkirRYy/axrb4LSu6SuL/N2tirAAZug/GpGB7VzAQUWUJd+3NSXlQZ5H4J1InvoLlgwiKGEBO3a4JPa3TieFRvcSZ/5p1R6IkRUf21FiJdL0AM4u2ibg3X78dcHlIRl9O5zj5XMyfB3NiOTkKr5IFEvMSHkgUULvryuey4mCs865FzlJ8pz13SDDTrsjO5ckM78yYcSJ7aV63EOJ8W39acIbd2JxLzp3LMk2Pd8m7jJuNBvRDVXGuwDMCF88RWfxD0ie+AUSEWtazlvUFH+Rsa7pHsDHkvO2szjWSa2GUFgJ3HrDb7CNh96CMpJ1ztxcFVfFD4wrwhIuZDSsCe4YZUCRmm4WNqB2509YTZ3J4Wd2mCCmRRNHiw/SHP0wTxak7WSQ4bMXrcaWV62oD5dNwV8wb63sIa6ibmOK+X5e8ksnJ7FR6WE0vGxo2hOd0wB9eAEXKkRX)

### Other comments
When the `v-list` is inside the scroll, then when you click on something clickable inside the `v-list`, the scroll up occurs in iOS.
This happens only on the first click inside the `v-list`. With subsequent clicks, this is not observed

https://github.com/vuetifyjs/vuetify/assets/9420536/83b85f8a-c24a-4f0a-b094-ae35f8b2c3ad

**Comment by KaelWD** [comment] 2023-11-17 05:40
Duplicate of #18223

**Closed by KaelWD** 2023-11-17 05:40 UTC
Labels: S: triage
