### ISSUE TITLE
[Bug Report] outlined form inputs & controls in hidden context

### ISSUE THREAD

**Issue by Dev1lDragon** [vuetifyjs/vuetify#9614] opened 2019-11-07 15:37 UTC
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.87
**OS:** Windows 10

### Steps to reproduce
Use component from 'Form inputs & controls' in hidden context witch 'outlined' property

### Expected Behavior
Render label background on shown

### Actual Behavior
Label background is rendered on construct and not when shown

### Reproduction Link
<a href="https://codepen.io/dev1ldragon/pen/RwwyBGR?editors=1010" target="_blank">https://codepen.io/dev1ldragon/pen/RwwyBGR?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment] 2019-11-09 06:02
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9225 
(which is a duplicate of other issue btw)

**Closed by jacekkarczmarczyk** 2019-11-09 06:02 UTC
Labels: triage
