### ISSUE TITLE
[Bug Report] v-select Prefix text misalignment 

### ISSUE THREAD

**Issue by creativenoobie** [vuetifyjs/vuetify#5098] opened 2018-09-16 10:47 UTC
### Versions and Environment
**Vuetify:** 1.1.16
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.92
**OS:** Linux x86_64

### Steps to reproduce
Open the reproduction link.
Select any option from the Menu

### Expected Behavior
Prefix text should not overlap with `label` or selected option

### Actual Behavior
Prefix text overlaps the selected option as well `label`

### Reproduction Link
[https://codepen.io/anon/pen/oPPwXM?&editors=101](https://codepen.io/anon/pen/oPPwXM?&editors=101)

**Comment by jacekkarczmarczyk** [comment] 2018-09-16 19:13
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3485

**Closed by jacekkarczmarczyk** 2018-09-16 19:13 UTC
