### ISSUE TITLE
[Bug Report][2.5.8] Random scroll when using v-select or autocomplete in multiple mode

### ISSUE THREAD

**Issue by juhasev** [vuetifyjs/vuetify#14125] opened 2021-09-04 15:58 UTC
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.6
**Browsers:** Chrome 92.0.4515.159
**OS:** Mac OS 10.15.7

### Steps to reproduce
Size your browser tab small so that v-select list items becomes scrollable. Select last item or items that require scrolling down. Select an item and uncommanded scroll occurs.

### Expected Behavior
Scroll position should stay

### Actual Behavior
Scroll position jumps

### Reproduction Link
<a href="https://codepen.io/juhasev/pen/jOwMmVE?editors=1010" target="_blank">https://codepen.io/juhasev/pen/jOwMmVE?editors=1010</a>

**Comment by XoldpandaX** [comment] 2021-09-05 06:57
I have the same problem. Interesting that if you open the list for the first time it behaves as expected, no scrolling.
However, if you open the list again it behaves as @juhasev said

**Comment by WhoisUnknown** [comment] 2021-09-06 14:39
This issue related with highlighting the first selected item on opening. The scroll moves to the last element we focused on inside v-select.

If you try to select an element using the key. Everything works perfectly

**Comment by juhasev** [comment] 2021-09-06 15:03
@WhoisUnknown Are you saying there is a word around? What do you mean by "Select an element using the key"?

**Comment by WhoisUnknown** [comment] 2021-09-06 15:24
> @WhoisUnknown by keyboard

**Comment by WhoisUnknown** [comment] 2021-09-06 15:24
@juhasev by keyboard

**Comment by KaelWD** [comment] 2021-09-06 15:57
Duplicate of #11969

**Closed by KaelWD** 2021-09-06 15:57 UTC
Labels: S: triage

**Comment by juhasev** [comment] 2021-09-07 00:47
FYI #11969 contains a nice work around!
