### ISSUE TITLE
[Bug Report] autoSelectFirst on v-combobox doesn't work

### ISSUE THREAD

**Issue by lephuongbg** [vuetifyjs/vuetify#6607] opened 2019-02-26 03:21 UTC
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.119
**OS:** Linux x86_64

### Steps to reproduce
1. Set `autoSelectFirst` to `true` on v-combox component
2. Typing in keyword

### Expected Behavior
First row should be selected

### Actual Behavior
First row is not selected

### Reproduction Link
<a href="https://jsfiddle.net/185fmdh2/" target="_blank">https://jsfiddle.net/185fmdh2/</a>

### Other comments
`autoSelectFirst` is implemented in VAutocomplete by `onFilteredItemsChanged ()` method, while in VCombobox this function is overriden to be empty. I don't know why it should be empty (no comment explaining the decision in the code) so I won't be able to make a pull request. Hopefully this will be fix soon.

**Comment by douglasg14b** [comment] 2019-04-15 07:28
Also seeing this.

Spent way too long trying to figure out if I was doing something wrong, turns out it just doesn't work.

**Comment by felicz** [comment] 2019-05-20 20:55
I'm having the same issue here. The behavior just doesn't match the docs and, as @lephuongbg said, the method that should handler this is overwritten with no explanation...

**Comment by johnleider** [comment] 2019-07-02 15:59
This was caused by us ignoring **onFilteredItemsChange** which handled this selection. The reason was so the user could enter loosely close items and not trigger, but that doesn't make much sense as the functionality would only occur if that prop was explicitly used, in which case you know what you're signing up for. This will go out with v2.0.

**Closed** 2019-07-02 16:57 UTC
Labels: C: VCombobox
