### ISSUE TITLE
[Bug Report] Data table doesn't apply page to option props

### ISSUE THREAD

**Issue by kosheydev** [vuetifyjs/vuetify#8389] opened 2019-08-08 13:13 UTC
### Environment
**Vuetify Version:** 2.0.5
**Last working version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
I create a data table with the option props, where the option object contains two properties:
itemsPerPage = 5
page = 2

itemsPerPage works correctly
page don't working, page = 1, why?

### Expected Behavior
option: {itemPerPage: 5, page: 2}

### Actual Behavior
Always page = 1 when mounted component data table

### Reproduction Link
<a href="https://codepen.io/kosheydev/pen/wVmVYo?&editable=true&editors=101" target="_blank">https://codepen.io/kosheydev/pen/wVmVYo?&editable=true&editors=101</a>

**Comment by nekosaur** [comment] 2019-08-08 13:44
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8266

**Closed by nekosaur** 2019-08-08 13:44 UTC
Labels: duplicate
