### ISSUE TITLE
[Bug Report] Dont delete v-dialog elements from DOM after close or save value

### ISSUE THREAD

**Issue by kyusupov33** [vuetifyjs/vuetify#4624] opened 2018-07-16 16:52 UTC
### Versions and Environment
Vuetify: ^1.0.19
Vue: ^2.5.16
Browsers: Chrome
OS: Windows 7

### Problem:
Is it possible to delete an element from DOM after closing the dialog?
![image](https://user-images.githubusercontent.com/29026701/42771970-938aeaca-8931-11e8-96df-44761c732dc4.png)

**Comment by xmoroccan** [comment] 2018-07-26 20:10
I'm facing the same problem, and this problem happens when I open the dialog without using activator slot, and the dialog seems to open five dialogs!

as image uploaded by @kyusupov33 shown, and this is an image from Vue DevTools, when I close the dialog update event fire five times !!

![image](https://user-images.githubusercontent.com/20878658/43285884-4e68c752-9118-11e8-8510-135e54ddb1ff.png)

**Comment by jacekkarczmarczyk** [comment] 2018-09-14 20:15
Another usecase for https://github.com/vuetifyjs/vuetify/pull/4518

**Comment by KaelWD** [comment] 2019-04-18 04:18
Duplicate of #6764

**Closed by KaelWD** 2019-04-18 04:18 UTC
Labels: C: VDialog, T: enhancement
