### ISSUE TITLE
[Bug Report][3.0.0-beta.6] Wrong textarea height in VTextarea

### ISSUE THREAD

**Issue by 0140454** [vuetifyjs/vuetify#15545] opened 2022-07-29 19:08 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.6
**Last working version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Set `rows="1"` and `auto-grow` on VTextarea
2. Type multiple line text in VTextarea

### Expected Behavior
The height of textarea tag increased.

### Actual Behavior
The height of textarea tag is always 28px.

### Reproduction Link
<a href="https://codepen.io/0140454/pen/qBodJoR" target="_blank">https://codepen.io/0140454/pen/qBodJoR</a>

### Other comments
Video

[screen-capture.webm](https://user-images.githubusercontent.com/1191368/181827700-8a1b314e-4cac-4c51-af6f-45555104011b.webm)

**Comment by 0140454** [comment] 2022-07-30 10:11
By the way, the width of textarea sizer is also wrong. It doesn't fit VTextarea fully.

**Comment by KaelWD** [comment] 2022-08-05 10:57
Duplicate of #15375

**Closed by KaelWD** 2022-08-05 10:57 UTC
Labels: duplicate
