### ISSUE TITLE
[Bug Report][3.6.11] VCalendar Event slot doesn't work in day or week view

### ISSUE THREAD

**Issue by adamjimenez** [vuetifyjs/vuetify#20097] opened 2024-07-04 10:11 UTC
### Environment
**Vuetify Version:** 3.6.11
**Vue Version:** 3.4.31
**Browsers:** Chrome 126.0.0.0
**OS:** Windows 10

### Steps to reproduce
See the custom slot
Change the view to day

### Expected Behavior
custom slot should show

### Actual Behavior
custom slot doesn't show

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1Vttu4zYQ/ZWpi8JyLV+SzS5S10nRZlv0JdgFNmgf4jww4sgilqIEivLGMPzvHVI3SnaC9qF5iMS5HB4ezoz1eBgVOlr8mufzXYmj1WhtMM0lM3i7UQBrLnbuhV53syJBNBBJVhQ3mxGfxRJfNiNIUGwTQ5b3V7QyQla5TRJKjExjANjN0oyjpHCzz3Ez6jwrQXtbZOsofE+zZcpml75dsmeH9JfAb3BPsL5zx7RgyvLKSiOFQu57OaoCu2UiOM44GiZk0Vhv14uG/r870DfEr5ztz56p9v2nY53L+R9O5Qz2agc37R86YhIVZ7rD1hgTidbuU2wF2TFZ9q8Yd6iMPXP10vPt6BZd6rnaaLQ4J3NLlKg25Qvfux0o/ADuDY6bkRdY13ZUFiZLoZCZgTjTcKij50YYiXA8rhddC1RitQ1idRvqclbSBsPL3ShaFpEWeRUi0jzTBg5QFvjR0j9CrInYmLrSiHg/tgkA+OLCOMaslBRe7caZYSsIJnBzC0FtA7ASrmCcZsok49C3Fit4bOwwtnLaJ0k6fmrjapEpchnCRQiXIbwL4SqE9yF8OAmziJ1GBxoCpB5t/qVUMIMvzNAGrhhewYNji+in32cuvVRe+jA3hOXb6X9o8Vr6G4kh/I08PE2mzF5aJ0UTpGgW2SsMJp2vqnZydqYok5nu6zZ+JoTuqsggFBfbrGfiiPksL3Uu+6HRnpFMnmGrEfuWTDO17WdR0J7qR39FNbvoPB1NJ8mA5j0VtlDbHtCfmRS2gnzb54dPvfWDZjuUPdPvVpie5TehTTJEustUjBpV1Gf/mWnjBTasj5P6Jc1KZZBTZ7RdEWWqMMA4yw1quGn6LZi0B05EMd+iccyKrp0ACkPbrZrcuVt+ij+yfTAwUfmYJOjqYNLwcaWgeIdBiz6CM7yRf6x5NgWYokkyTvfT8vSoV4xDuyUldiGNClVVkgiPT9V48Z2pUORxCCcu9kIuQh067CQgT0ABVsIHkRJ7akHC6tYTWMD1h6ul/TvL6M7eGsG4m9CKBxY2rMCncLkkCbo8O7QDSZ8lgjKWP9Nj7aHQejrtnbytAClJd38XmkvvaITeEMxpeCx04fiTIGnup/XOFlptvKO+AkT57e0OkGcwtPwAPzmtzqEVSE9+lhdNufqMv8Dl9TWs4HoCP9ZYryGdEPOucTrcrXcPzYyb52WR+F3TDpFVxa0aKI++7J59Tj+nW5OQDBfe+Oz1n+M1cLmmqugNPG7M1ltXI/d068r+1taVkiv4rnrpeZuWdO++JA677bH6g6fp4xai6dc7SyJwUb2C1WhKreqvEsf0FMMehoXwfC7xnplkHsuMwINnOhyji7ywleAc9IvAs9Q25RTYELh60pnWi/ZTZXQMVSml+/f0D1yXh2Q=)

**Comment by blalan05** [comment] 2024-07-13 03:23
Duplicate of #19020

**Closed by blalan05** 2024-07-13 03:23 UTC
Labels: S: triage
