### ISSUE TITLE
Identifier 'installComponents' has already been declared

### ISSUE THREAD

**Issue by JeremyWalters** [vuetifyjs/vuetify#5377] opened 2018-10-22 08:09 UTC
Hi, I am running a Vue/typescript/vuetify(a la carte) project. 

Upgraded to version 1.3.1.
Added the vuetify-loader plugin to `vue.config.js`

vue: 2.5.17
vuetify-loader: 1.0.5
vue-cli-plugin-vuetify: 0.3.0
vuetify: 1.3.1

Error: 

```
Module parse failed: Identifier 'installComponents' has already been declared (53:7)
You may need an appropriate loader to handle this file type.
|
| /* vuetify-loader */
> import installComponents from "!../../../node_modules/vuetify-loader/lib/runtime/installComponents.js"
| import { VBtn } from 'vuetify/lib'
| import { VCard } from 'vuetify/lib'
```

**Comment by KaelWD** [comment] 2018-10-22 12:16
Duplicate of vuetifyjs/vuetify-loader#20

**Closed by KaelWD** 2018-10-22 12:16 UTC
