### ISSUE TITLE
[Bug Report] Sparkline Bar Type does not load colors

### ISSUE THREAD

**Issue by adarshmadrecha** [vuetifyjs/vuetify#9817] opened 2019-11-28 05:55 UTC
### Environment
**Vuetify Version:** 2.1.12
**Last working version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
1. Create a standard sparkline component
2. Change the `type` to `bar`
3. The colours disappear (i.e. only Black)

### Expected Behavior
The colours should not be gone if the `type` is changed.

### Actual Behavior
The colour turns to black if the type is set to "bar"

### Reproduction Link
<a href="https://codepen.io/adarshmadrecha/pen/QWWegoq" target="_blank">https://codepen.io/adarshmadrecha/pen/QWWegoq</a>

**Comment by adarshmadrecha** [comment] 2019-11-28 05:58
This issue can also be seen in action in the sparkline documentation
https://vuetifyjs.com/en/components/sparklines#playground

![image](https://user-images.githubusercontent.com/11911938/69780712-01400a80-11d2-11ea-85e3-44959d25b6f1.png)

**Comment by jacekkarczmarczyk** [comment] 2019-11-28 06:26
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9421

**Closed by jacekkarczmarczyk** 2019-11-28 06:26 UTC
Labels: triage
