### ISSUE TITLE
[Bug Report] Readonly Prop Disables Date Picker Textfield

### ISSUE THREAD

**Issue by blalan05** [vuetifyjs/vuetify#11550] opened 2020-06-03 14:35 UTC
### Environment
**Vuetify Version:** 2.3.0-beta.7
**Last working version:** 2.3.0-beta.5
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Windows 10

### Steps to reproduce
Add readonly prop to the v-text-field of datepicker

### Expected Behavior
Text field is readonly (not disabled) but the Date Picker still functions
<a href="https://codepen.io/blalan05/pen/oNjRyLQ" target="_blank">https://codepen.io/blalan05/pen/oNjRyLQ</a>
### Actual Behavior
Textfield is disabled and Date Picker doesn't function. Time Picker is also borked.

### Reproduction Link
<a href="https://codepen.io/blalan05/pen/QWjRrXj" target="_blank">https://codepen.io/blalan05/pen/QWjRrXj</a>

**Comment by KaelWD** [comment] 2020-06-03 14:38
Duplicate of #11504

**Closed by KaelWD** 2020-06-03 14:38 UTC
Labels: duplicate

**Comment by brugomes** [comment] 2024-08-24 02:46
Was this published?  I'm still facing this problem.
