### ISSUE TITLE
[Bug Report] v-combobox in form does not submit on first click

### ISSUE THREAD

**Issue by arneysebaert** [vuetifyjs/vuetify#5470] opened 2018-10-29 10:24 UTC
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.16
**Browsers:** Chrome 69.0.3497.100
**OS:** Mac OS 10.14.0

### Steps to reproduce
Use a v-combobox in a form, type something in the combobox and submit the form with a button. The form wont submit, the combobox will just lose focus. (the log in the codepen is empty) A second submit will actually submit the form. (the log will have your typed string)

### Expected Behavior
Submit the form on first submit.

### Actual Behavior
When using a v-combobox in a form the v-combobox prevents the form from submitting on the first submit click. 
When you press the submit button of the form the first time the combobox loses focus, pressing the button a second time submits the form. 

### Reproduction Link
[https://codepen.io/arneysebaert/pen/qJwRqm?editors=1111](https://codepen.io/arneysebaert/pen/qJwRqm?editors=1111)

**Comment by KaelWD** [comment] 2018-10-29 10:53
Duplicate of #4679

**Closed by KaelWD** 2018-10-29 10:53 UTC
