### ISSUE TITLE
[Bug Report] autocomplete doesn't show group titles on searching

### ISSUE THREAD

**Issue by user93472389** [vuetifyjs/vuetify#7802] opened 2019-07-11 09:05 UTC
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.5.17
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Use a v-autocomplete with Group Titles { header: "Group Title" }. Type a string into the textfield to search an item.

### Expected Behavior
The group titles should stay visible. Only the items should be filtered.

### Actual Behavior
The group titles disappear on typing a search string, except you type "e", "o", "j", "c" or "b".

### Reproduction Link
<a href="https://codepen.io/anon/pen/rERxJj?&editable=true&editors=101#anon-login" target="_blank">https://codepen.io/anon/pen/rERxJj?&editable=true&editors=101#anon-login</a>

### Other comments
The example in codepen is taken from the official vuetify documentation examples.

**Comment by jacekkarczmarczyk** [comment] 2019-07-11 09:08
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7424

**Closed by jacekkarczmarczyk** 2019-07-11 09:08 UTC
Labels: triage
