### ISSUE TITLE
[Feature Request] DataTables

### ISSUE THREAD

**Issue by iwarnock78** [vuetifyjs/vuetify#3822] opened 2018-04-10 14:00 UTC
### Problem to solve
Not being able to exclusively select only one row at a time.

### Proposed solution
Add support for single selection of items by row. 
This would mean that when selecting a row, all other rows would become deselected.

**Comment by KaelWD** [comment] 2018-04-10 14:05
Duplicate of #2960

**Closed by KaelWD** 2018-04-10 14:05 UTC
