### ISSUE TITLE
[Feature Request] Navigating the table using the keyboard (arrow keys)

### ISSUE THREAD

**Issue by turopoff** [vuetifyjs/vuetify#16182] opened 2022-11-28 11:36 UTC
### Problem to solve
Navigating the table using the keyboard (arrow keys)

### Proposed solution
Navigation using keyboard:
1. Up Key - Previous row;
2. Down Key - Next row;
3. Page Up - Previous page;
4. Page Down - Next Page;

**Comment by KaelWD** [comment] 2022-11-28 14:22
Duplicate of #9164

**Closed by KaelWD** 2022-11-28 14:22 UTC
Labels: S: triage
