### ISSUE TITLE
[Bug Report][2.5.1] Tab slider is not redrawing when tab size changes

### ISSUE THREAD

**Issue by Agendum** [vuetifyjs/vuetify#13734] opened 2021-06-01 05:44 UTC
### Environment
**Vuetify Version:** 2.5.1
**Vue Version:** 2.6.11
**Browsers:** Edge 91.0.864.37
**OS:** Windows 10

### Steps to reproduce
1. Go to the JSFiddle
2. Click on the Long Tab Names button
3. Click on the Short Tab Names button

### Expected Behavior
If the tab size changes, the underlying slider should also change to match the size.

### Actual Behavior
The slider size stays the same until the user changes the tab, which causes the slider to redraw.

### Reproduction Link
<a href="https://jsfiddle.net/CodeVirtue/3w96sjx4/" target="_blank">https://jsfiddle.net/CodeVirtue/3w96sjx4/</a>

### Other comments
Only work-around I could figure out is to force a full re-render of the entire v-tabs and v-tabs-items controls using :key.

**Comment by KaelWD** [comment] 2021-06-01 07:13
Duplicate of #6466

**Closed by KaelWD** 2021-06-01 07:13 UTC
Labels: triage
