### ISSUE TITLE
[Feature Request] Allow clearing of text after selecting an option on combobox

### ISSUE THREAD

**Issue by anthonycheng12** [vuetifyjs/vuetify#6900] opened 2019-04-02 14:50 UTC
### Problem to solve
This is codepen is from the vuetify combobox examples: https://codepen.io/anthony-cheng/pen/vMOjja?&editable=true&editors=101

The issue is if you type in something like "prog" then click programming the programming chip is created but then the "prog" text is still there after selecting an option. Is there a feature we can add to not allow the text to show after being selected?

### Proposed solution
Add a prop to allow the remaining text to be cleared after selecting an option.

**Comment by KaelWD** [comment] 2019-04-02 15:03
Duplicate of #6842

**Closed by KaelWD** 2019-04-02 15:03 UTC
