### ISSUE TITLE
Update Outlined Inputs & Controls to match latest Material Design Components specification

### ISSUE THREAD

**Issue by struers-mfr** [vuetifyjs/vuetify#4731] opened 2018-07-27 08:30 UTC
The current version of all input (text fields) components with outline prop defined is not matching the current Material Design specification https://material.io/design/components/text-fields.html#spec in focused state

### What problem does this feature solve?
It should add notched outline svg layer that will have place for label that will move in this place after component will be focused.

### What is your proposed solution?
API should remain the same as before in all affected components, it should only update the visual representation of focused state of the components

![outlined textfield](https://user-images.githubusercontent.com/31610030/43310508-066954b0-9188-11e8-9cc6-7cfaa0389e9f.png)
Here are examples of implementation in Google Material Components for web

https://material-components.github.io/material-components-web-catalog/#/component/text-field

**Comment by KaelWD** [comment] 2018-07-27 08:42
Duplicate of #4364

**Closed by KaelWD** 2018-07-27 08:42 UTC
