### ISSUE TITLE
[Feature Request] Add allowed years and allowed months to the date picker

### ISSUE THREAD

**Issue by dev-oups** [vuetifyjs/vuetify#13165] opened 2021-02-26 08:47 UTC
### Problem to solve
Allow user to quickly find allowed dates in the calendar.
e.g. some days in Jan 2012 and some days in Jun 2020.

### Proposed solution
Add "allowed-years" and "allowed-months" properties with the same behaviour as the "allowed-dates" property.
These properties will be called when the year or month view are displayed.
Callback parameters may be "2018" and "2018-12" in place of "2018-12-21".

**Comment by KaelWD** [comment] 2021-02-26 08:51
This should just be part of allowed-dates. If an entire month/year is not allowed it should be greyed out.

**Comment by KaelWD** [comment] 2021-02-26 08:51
Duplicate of #9784

**Closed by KaelWD** 2021-02-26 08:51 UTC
Labels: C: VDatepicker, T: enhancement

**Comment by dev-oups** [comment] 2021-02-26 09:21
For performance issue it may not request all dates for the tens of years in the list in the year view or the 365 dates in the month view.
Because of that i propose to create specific properties depending on the current view mode.

This behaviour is already implemented to manage the available months for the month mode of the calendar.
