### ISSUE TITLE
[Bug Report][3.0.0-beta.11] v-timeline dots is not align center when you set size="small"

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15797] opened 2022-09-19 13:06 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Vue Version:** 3.2.39
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
Try to set the dots size="small" 

### Expected Behavior
Dots should be aligned center

### Actual Behavior
dots do not align center

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/JjvNmRp?editors=101" target="_blank">https://codepen.io/Alokdev/pen/JjvNmRp?editors=101</a>
![image](https://user-images.githubusercontent.com/80033712/191023965-89dd9bb2-af11-4ed8-85b3-a383133d6975.png)

**Comment by KaelWD** [comment] 2022-09-20 10:03
Duplicate of #8437

**Closed by KaelWD** 2022-09-20 10:03 UTC
Labels: S: triage
