### ISSUE TITLE
[Feature Request] Bind Snackbar to Vue prototype as a function

### ISSUE THREAD

**Issue by hjlld** [vuetifyjs/vuetify#2776] opened 2017-12-12 07:45 UTC
### New Functionality
Snackbar, toast,  notification and dialog as the messaging components are used frequently in development, which should be bound to vue prototype as a function, like element-ui. For example:

```
Vue.prototype.$message = function(msgType, position, color, content, ifShowClose, timeout) {
  //msgType = 'v-snackbar' || 'v-dialog' || ...
}
```

### Improvements
So developers can give out a message easily by: 

`this.$message('v-snackbar', 'top', 'error', 'Bad response from server', true, 3000)`

### Bugs or Edge Cases it Helps Avoid
none

**Comment by KaelWD** [comment] 2017-12-12 10:58
Technically a duplicate of #2384

This won't be on the vue prototype, but we may implement a message queue in the snackbar components itself so you can manage them with something like Vuex.

**Closed by KaelWD** 2017-12-12 10:58 UTC

**Comment by hjlld** [comment] 2017-12-12 17:05
@KaelWD  Thanks a lot for the reply. I don't know exactly how you plan to design this message queue, but not all Vue.js projects use something like Vuex to share and store data. Even if in the message queue, developers should not add <v-snackbar> manually to every route-component / component / page, because almost everyone of them needs to deal messaging. I think binding it to Vue.prototype is an easy way to realize the expectation. Don't make it too difficult to use. PS: I agree that there should be only one snackbar shown in the same time.
