### ISSUE TITLE
[Bug Report] Select component 'no-data-text' doesnt work

### ISSUE THREAD

**Issue by takotuesday** [vuetifyjs/vuetify#3427] opened 2018-02-28 20:17 UTC
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Create a select with an empty list of items. Add no-data-text property.

### Expected Behavior
Given text will display when list is empty

### Actual Behavior
No text appears when list is empty

### Reproduction Link
[https://codepen.io/anon/pen/mXvVxy?&editors=101](https://codepen.io/anon/pen/mXvVxy?&editors=101)

**Comment by KaelWD** [comment] 2018-03-01 03:02
Duplicate of #2081

**Closed by KaelWD** 2018-03-01 03:02 UTC
