### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] `v-text-field` cause error in Vite

### ISSUE THREAD

**Issue by yaquawa** [vuetifyjs/vuetify#14665] opened 2022-01-28 20:43 UTC
![image](https://user-images.githubusercontent.com/13927101/151618651-16e5403d-d3cf-4c1a-991b-247b22c08744.png)

### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.29
**Browsers:** Chrome 97.0.4692.99
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Install vuetify with Vite
2. use `v-text-field`
3. check the console of browser

### Expected Behavior
No error shown.

### Actual Behavior
Error shown.

### Reproduction Link
<a href="https://github.com/yaquawa/vuetify-vite" target="_blank">https://github.com/yaquawa/vuetify-vite</a>

**Comment by mathe42** [comment] 2022-01-30 19:09
Not shure if it the same problem I got (so my fix might fix this too):

Add `import * as directives from "vuetify/directives";` to src/plugins/vuetify and change your createVuetify call to `createVuetify({directives})`.

As mentioned I didn't test your repo with this fix!

**Comment by KaelWD** [comment] 2022-01-31 12:43
Duplicate of #14578

**Closed by KaelWD** 2022-01-31 12:43 UTC
Labels: S: triage
