### ISSUE TITLE
[Bug Report] Creating new values using Combobox with auto-select-first prop

### ISSUE THREAD

**Issue by hansenconnor** [vuetifyjs/vuetify#11790] opened 2020-07-04 21:44 UTC
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 83.0.4103.106
**OS:** Windows 10

### Steps to reproduce
See reproduction link

### Expected Behavior
Expected functionality is that new values can be created when pressing enter when the Combobox is focused AND has auto-select-first prop.

### Actual Behavior
Pressing enter does not create a new entry in a Combobox with the auto-select-first prop.

### Reproduction Link
<a href="https://jsfiddle.net/connorhansen/y8j27g3e/1/" target="_blank">https://jsfiddle.net/connorhansen/y8j27g3e/1/</a>

**Comment by KaelWD** [comment] 2020-07-29 08:27
Duplicate of #9270

**Closed by KaelWD** 2020-07-29 08:27 UTC
Labels: triage
