### ISSUE TITLE
[Bug Report] Tabs on mobile do not overflow

### ISSUE THREAD

**Issue by krisl21** [vuetifyjs/vuetify#3918] opened 2018-04-24 14:48 UTC
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.15
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
Tabs in a **dialog** do not overflow on mobile. The last tabs are out of the visible range (the tabscontent is not slideable). Clicking on a tab doesn't move the tabs to the left

### Expected Behavior
Able to slide to the tabs out of visible range

### Actual Behavior
Tabs are sticky (no left/right overflow)

### Reproduction Link
[https://codepen.io/krisl21/full/BxKJRj](https://codepen.io/krisl21/full/BxKJRj)

**Comment by KaelWD** [comment] 2018-04-24 15:30
Duplicate of #1978

**Closed by KaelWD** 2018-04-24 15:30 UTC
