### ISSUE TITLE
[Bug Report] Double first page and "more" buttons in v-data-table in v-expansion-panel

### ISSUE THREAD

**Issue by denisemenov** [vuetifyjs/vuetify#10826] opened 2020-03-13 07:28 UTC
### Environment
**Vuetify Version:** 1.5.24
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
1. Add expansion panel
2. Add data table to expansion panel
3. Open expansion panel
4. Look a pagination

### Expected Behavior
No double "more" button and "first page" button in pagination

### Actual Behavior
If the elements are enough for only one page, then the "first page" button and "more" button appears twice.

![Pagination bug](https://i.ibb.co/YyzW86z/Fire-Shot-Capture-252-Vuetify-Example-Pen-codepen-io.png)

### Reproduction Link
<a href="https://codepen.io/denisemenov/pen/oNXqBaj" target="_blank">https://codepen.io/denisemenov/pen/oNXqBaj</a>

**Comment by KaelWD** [comment] 2020-03-13 07:31
Duplicate of #2434

**Closed by KaelWD** 2020-03-13 07:31 UTC
Labels: triage

**Comment by denisemenov** [comment] 2020-03-13 11:14
@KaelWD `lazy` doesnt fix it for expansion-panel.
