### ISSUE TITLE
Menu auto open and will not close when autocomplete component changes underlying 'items'

### ISSUE THREAD

**Issue by tianhai82** [vuetifyjs/vuetify#5116] opened 2018-09-19 09:02 UTC
### Versions and Environment
Vuetify: 1.2.4
Vue: 2.5.17
Browsers: Chrome 69
OS: Windows 10

### Steps to reproduce
1. Select an item in the Autocomplete widget
2. Click the 'Change' button to change the 'items' in the Autocomplete component
3. The dropdown menu will pop up. Choose any item, the dropdown menu is still there. Click outside of the dropdown menu, the dropdown menu still will not go away.

### Expected Behavior
Autocomplete should behave normally when underlying 'items' array is changed

### Actual Behavior
Changing underlying array will cause the dropdown menu to be shown.

### Reproduction Link
https://codepen.io/tianhai82/pen/RYEWwj

**Comment by KaelWD** [comment] 2018-09-19 09:11
Duplicate of #4663

**Closed by KaelWD** 2018-09-19 09:11 UTC
