### ISSUE TITLE
[Bug Report] detachable positioning issues with wrapped content

### ISSUE THREAD

**Issue by andrewtoups** [vuetifyjs/vuetify#9745] opened 2019-11-20 17:31 UTC
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
1. Render the data-table inside a containing element with the css `position` property set to `relative`.
2. Place additional page content outside of the containing element and before the component in the document flow.
3. Click the "rows per page" dropdown.
4. The position of the dropdown will be misaligned.

### Expected Behavior
The calculated position of the dropdown should always be set relative to the location of the component on the page.

### Actual Behavior
The calculated position of the dropdown is offset by the same height as all content above the component.

### Reproduction Link
<a href="https://codepen.io/andrewtoups/pen/WNNmxja" target="_blank">https://codepen.io/andrewtoups/pen/WNNmxja</a>

### Other comments
While this is somewhat of an edge case, `position: relative` is a relatively ubiquitous property on container elements used in a variety of web layouts and should be accounted for. It likely isn't an issue in pure vuetify layouts but one of the appeals of this framework is the ability to pick and choose components and mix them with your existing work.

In my case I'm using this layout as a widget that can be inserted on any website and it really needs to play nice with common css layout strategies. Even if I had direct control over the rest of the document there are still cases where you would need to have a vuetify data-table inside a container with `position: relative` set.

**Comment by johnleider** [comment] 2020-01-10 17:07
I'm not sure if this can be solved. Using margin around the surrounding v-app container is what causes this.

**Comment by andrewtoups** [comment] 2020-01-10 17:15
Correct me if I'm wrong but as far as I can see there is no margin surrounding the v-app container in the linked codepen. See that there is no margin added in the css I used in the codepen link:

```
header {
  margin: 75px auto;
  text-align: center;
}

.content-container {
  position: relative;
}
```

And the `header` element does not contain the `#app` element.

I believe it's happening because the v-app container has siblings with relative positioning. I don't think that's an unrealistic use case.

Here is a codepen where instead of margin the header's height is just set by a very large font size. The issue still occurs:
https://codepen.io/andrewtoups/pen/BayxzLM

**Comment by nekosaur** [comment] 2020-02-29 12:54
This is not specific to v-data-table but an issue with v-select and all other components that detach elements.

**Comment by jbgury** [comment] 2020-05-14 15:58
I described other cases in this codepen https://codepen.io/jbgury/pen/mdeGRxP which has the issue. I tried to use the "attach" attribute but without any success.
Detected the issue on : v-tooltip, v-menu (and indirect use of v-menu : v-combobox, v-select)

**Comment by Tofandel** [comment] 2020-07-24 09:19
This is the same issue as #7703

**Comment by KaelWD** [comment] 2020-08-21 08:02
Duplicate of #7703

**Closed by KaelWD** 2020-08-21 08:02 UTC
Labels: C: VSelect, T: bug

**Comment by Kiran-Kumar-Desu** [comment] 2022-03-03 07:50
Hi Team,
