### ISSUE TITLE
[Feature Request] VNavigationDrawer MiniVariant close animation - display content until smaller width

### ISSUE THREAD

**Issue by BryonCLewis** [vuetifyjs/vuetify#10258] opened 2020-01-17 15:07 UTC
### Problem to solve
Improve consistency between opening and closing of the MiniVariant VNavigationDrawer.

### Proposed solution

Small thing that might improve consistency.  As of now with a miniVariant vNavigation drawer with sync enabled when closing the navigation drawer it will first hide the content and then animate to the smaller (80px) width.  This causes a jump in the positioning if the VNavigationDrawer and then it will slide back.  Doesn't really look smooth.  Either delay the hiding of the content until after the small width is reached.  This will causes a better closing animation similar to the opening animation.

https://vuetifyjs.com/en/components/navigation-drawers#mini
Can be seen in the demo.  Also can use ChromeDev tools and slow down the animation to see.

**Comment by johnleider** [comment] 2020-01-17 19:40
Duplicate of #2830, #8007, #9498, #10254

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-17 19:40 UTC
Labels: triage
