### ISSUE TITLE
[Documentation] Suggestion for example-script simplification to achieve easy reading

### ISSUE THREAD

**Issue by willyong82** [vuetifyjs/vuetify#11351] opened 2020-05-08 04:58 UTC
### Problem to solve
I'm reffering to current https://vuetifyjs.com/en/components/grids/#one-column-width  documentation for v2.2.7 as example

    <template>
      <v-container class="grey lighten-5">
        <v-row
          class="mb-6"
          no-gutters
        >
          <v-col
            v-for="n in 3"
            :key="n"
            :cols="n === 2 ? 6 : undefined"
          >
            <v-card
              class="pa-2"
              outlined
              tile
            >
              {{ n }} of 3 {{ n === 2 ? '(wider)' : '' }}
            </v-card>
         </v-col>
        </v-row>
        <v-row no-gutters>
          <v-col
            v-for="n in 3"
            :key="n"
            :cols="n === 2 ? 5 : undefined"
          >
           <v-card
              class="pa-2"
              outlined
              tile
            >
              {{ n }} of 3 {{ n === 2 ? '(wider)' : '' }}
            </v-card>
          </v-col>
        </v-row>
      </v-container>
    </template>

not requiring usage of FOR loop in this simple case
prefer plain template for readability

### Proposed solution
prefer collapsing codes like below, it may be harder to look but easier than digesting the FOR-loop version

    <template>
      <v-container class="grey lighten-5">
        <v-row class="mb-6" no-gutters>
          <v-col cols="undefined"> 
            <v-card class="pa-2" outlined tile> 1 of 3 </v-card>
          </v-col>
          <v-col cols="6">
            <v-card class="pa-2" outlined tile> 2 of 3 (wider) </v-card>
          </v-col>
          <v-col cols="undefined">
              <v-card class="pa-2" outlined tile> 3 of 3 </v-card>
          </v-col>
        </v-row>
        <v-row no-gutters>
        <v-row class="mb-6" no-gutters>
          <v-col cols="undefined"> 
            <v-card class="pa-2" outlined tile> 1 of 3 </v-card>
          </v-col>
          <v-col cols="5">
            <v-card class="pa-2" outlined tile> 2 of 3 (wider) </v-card>
          </v-col>
          <v-col cols="undefined">
              <v-card class="pa-2" outlined tile> 3 of 3 </v-card>
          </v-col>
        </v-row>
      </v-container>
</template>

also prefer it opened into another container like DIALOG which in almost fullscreen size to improve readabiliy
but this won't be necessary as the smart "copy the code" button are already provided and we could always easily copy and examine the code in our preferably local editor

End words, hopefully this is not just a matter of my PERSONAL taste, please be sure to consult to other users and developers before revising

**Comment by jacekkarczmarczyk** [comment] 2020-05-08 08:25
Duplicate of https://github.com/vuetifyjs/vuetify/issues/11340

**Closed by jacekkarczmarczyk** 2020-05-08 08:25 UTC
Labels: triage
