### ISSUE TITLE
[Bug Report] v-autocomplete suggestions are covering input field in mobile devices with small screens 

### ISSUE THREAD

**Issue by bubundas17** [vuetifyjs/vuetify#13200] opened 2021-03-03 07:37 UTC
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.11
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Android, iOS

### Steps to reproduce
Open the link from a mobile with small screen or from chrome dev tools with mobile view and select Moto G4 and type something,  

### Expected Behavior
the suggestion list should go below  the input field no matter what the screen size is so that the user can see what he is actually typing. 
![image](https://user-images.githubusercontent.com/26280146/109770194-421e9e80-7c21-11eb-97fa-6255645f6b6a.png)

### Actual Behavior
In small enough display the suggestions going over the text input field making the so that the user cannot see what is being typed there. 
![image](https://user-images.githubusercontent.com/26280146/109770109-261afd00-7c21-11eb-8cc8-db7920da2505.png)

### Reproduction Link
<a href="https://codepen.io/bubundas17/full/yLVEJOv" target="_blank">https://codepen.io/bubundas17/full/yLVEJOv</a>

**Comment by KaelWD** [comment] 2021-03-04 06:25
Duplicate of #4059

Just making the menu shorter isn't a good solution, it gets very small when the keyboard is open.

**Closed by KaelWD** 2021-03-04 06:25 UTC
Labels: triage

**Comment by bubundas17** [comment] 2021-03-04 06:43
@KaelWD It's good and all, But the issue was created over 2 years ago and not solved yet.

**Comment by timraasveld** [comment] 2022-12-27 11:12
I made a dirty workaround based on using  a fullscreen`position: fixed` display on small viewports (such as mobile with the keyboard open):

https://codepen.io/timraasveld/pen/yLqeOYG (make the preview less than 700px height to see it)
