### ISSUE TITLE
[Feature Request] Capacity change overlay style for single v-dialog

### ISSUE THREAD

**Issue by usb248** [vuetifyjs/vuetify#5751] opened 2018-11-28 10:44 UTC
### Problem to solve
Any easy way to change overlay style for a **single** v-dialog.
![sans-titre-1](https://user-images.githubusercontent.com/7659927/49146404-6385d700-f302-11e8-979f-139c5ddf903e.png)

Actually only solution is to override CSS for all v-dialog or so much code ... not very optimized : 
https://codepen.io/cb109/pen/pQxjMy?editors=1011

### Proposed solution
`content-class` prop add class to `.v-dialog` (see above). I suggest to add classes on parent node `.v-dialog__content` in order to can do : .`v-dialog__content.my_custom_class + .v-overlay.v-overlay--active::before`.

**Comment by FranciscoG** [comment] 2020-05-17 16:55
+1
My need is that I want to add a grid container class to `.v-dialog__content ` so I can then use the `content-class` prop to add my `cols-#`

**Comment by johnleider** [comment] 2020-11-19 19:47
duplicate of #4807

**Closed by johnleider** 2020-11-19 19:47 UTC
Labels: C: VDialog, T: feature
