### ISSUE TITLE
BUG: date pickers 1 day delay 

### ISSUE THREAD

**Issue by xmorell** [vuetifyjs/vuetify#2315] opened 2017-10-25 10:22 UTC
**Steps to reproduce**

Create a date picker

**Versions**

I've noticed this bug in V0.16.9,  In version 0.15.6 it works fine

**What is expected ?**

The picker should show at the calendar the  actual day 

**What is actually happening ?**

Actually it will show the day before. Example: today is Wed, 25 Oct, if I go to the date picker I will see that the selected option is Wed, 24 Oct (??? this day doesn't exist), at the top, the message will be Tue, 24 Oct (this day does exist, but is not the actual day.)

I'm from Spain, maybe is due to the different timezones 

**Reproduction Link**

https://vuetifyjs.com/components/pickers   Example 1

**Comment by jacekkarczmarczyk** [comment] 2017-10-25 10:36
Duplicate of #2022

**Closed by jacekkarczmarczyk** 2017-10-25 10:36 UTC
