### ISSUE TITLE
text-field label misplaced while shaking

### ISSUE THREAD

**Issue by mueller-berlus** [vuetifyjs/vuetify#1215] opened 2017-08-02 10:19 UTC
### Steps to reproduce
Create a text-field with prepending icon. Let the validation of said text-field fail.

### Versions
Vue: 2.4.2
Vuetify: 0.14.7
Chrome: 58
OS: Ubuntu 16.04

### What is expected ?
The label should shake "in place".

### What is actually happening ?
The label moves to the left into the icon.

### Reproduction Link
https://codepen.io/anon/pen/LjZqvK

**Comment by nekosaur** [comment] 2017-08-02 10:51
Duplicate of #1141

**Closed by nekosaur** 2017-08-02 10:51 UTC
Labels: duplicate
