### ISSUE TITLE
[Bug Report][3.1.9] $chip-border-width: doesn't work when chip is used inside a tab (perhaps any VBtn)

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#16913] opened 2023-03-15 10:27 UTC
### Environment
**Vuetify Version:** 3.1.9
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
```
<v-tabs color="accent" :model-value="activeTab">
    <v-tab
    >
      <span class="mr-3">Hello</span>
      <v-chip variant="outlined" color="black" size="small">
        11
      </v-chip>
    </v-tab>
  </v-tabs>
```

```
@forward 'vuetify/settings' with (
  $chip-border-width: 2px, //@TODO doesnt work inside a btn
);
```

### Expected Behavior
A 2px width border

### Actual Behavior
a 1 px width border

<img width="453" alt="image" src="https://user-images.githubusercontent.com/1246691/225281773-00c9fa4c-07b1-4890-be97-c7167ea188bc.png">

**Comment by johnleider** [comment] 2023-03-15 17:45
This is not a reproduction. Please don't make me do the digging, give me something to work with.

Thank you :)

**Comment by ricardovanlaarhoven** [comment] 2023-03-17 08:19
Could you help me how to create a reproduction with sass variables?
i wasn't able to do this with the vuetify playground from discord.

**Comment by johnleider** [comment] 2023-03-17 17:39
Create a new project using **yarn create vuetify** and publish it to GitHubl; link it here.

**Comment by KaelWD** [comment] 2023-04-28 12:17
This has nothing to do with tabs, `variant="outlined"` has no way to set border width

**Comment by KaelWD** [comment] 2023-04-28 12:18
Duplicate of #16786

**Closed by KaelWD** 2023-04-28 12:18 UTC
Labels: S: needs reproduction, S: triage
