### ISSUE TITLE
Menu more items

### ISSUE THREAD

**Issue by FilippiSilva** [vuetifyjs/vuetify#2104] opened 2017-10-09 13:46 UTC
New Feature on **Menu**

On the google drive, the menus have items with more items, this would help in specifying the item, for example:

- tools
    - move
    - zoom
    - invert

![deepinscreenshot_20171009102947](https://user-images.githubusercontent.com/4635445/31340691-5afc4360-acdd-11e7-8d19-352a14dafab7.png)

**Comment by nekosaur** [comment] 2017-10-09 13:57
Duplicate of #1877

**Closed by nekosaur** 2017-10-09 13:57 UTC
Labels: duplicate
