### ISSUE TITLE
[Bug Report] Bug Date Picker when display years selector at extremities (<0, >9999)

### ISSUE THREAD

**Issue by Rovelak** [vuetifyjs/vuetify#9988] opened 2019-12-17 07:02 UTC
### Environment
**Vuetify Version:** 2.1.14
**Vue Version:** 2.6.11
**Browsers:** Firefox 71.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
When the displayed year is between [1-99] or [9900-9999] and you try to display the year selector an error is thrown. In the provided Codepen click on "January 10", it will display the Month selector, then click on 10 to display the Year selector : an error in thrown, nothing is shown. 

That's because Vuetify tries to display +/- 100 years around the displayed year. So, if we display year 50, Vuetify will try to display years [-50-0], but those years are invalid as Vuetify's implementation for IS 8601 negative dates is wrong : the ISO 8601 format for negative dates is -yyyyyy-mm-dd and not -yyyy-mm-dd as you would expect. 
On the other extreme we face the same problem : if you display year 9950 and try to access the year selector Vuetify will try to display years [10000-10050] which are all invalid with ISO 8601.

### Expected Behavior
No error should be thrown. The list of years should be displayed, at least to year 1 and year 9999. Ideally, negative dates should also be supported at least to -9999, or to -999999 as we should respect the ISO 8601 format. 

### Actual Behavior
An error is thrown. In Firefox the error is "RangeError: date value is not finite in DateTimeFormat.format()", and in Chrome "RangeError: Invalid time value".

### Reproduction Link
<a href="https://codepen.io/Rovelak/pen/ZEYBoVP" target="_blank">https://codepen.io/Rovelak/pen/ZEYBoVP</a>

**Comment by jacekkarczmarczyk** [comment] 2019-12-17 08:13
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7401

**Closed by jacekkarczmarczyk** 2019-12-17 08:13 UTC
Labels: C: VDatepicker, duplicate
