### ISSUE TITLE
[Bug Report] v-menu suppresses event propagation (of embedded hyperlinks)

### ISSUE THREAD

**Issue by danielschwab** [vuetifyjs/vuetify#9944] opened 2019-12-11 12:27 UTC
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chromium 78.0.3904.108
**OS:** Linux x86_64

### Steps to reproduce
Put anything with an attached event listener inside of the defualt slot of a v-menu and and this will prevent event propagation so that all event listeners will not get called. 

### Expected Behavior
We use rails-ujs to accomplish remote links with different request method (e.g. DELETE). This is done by attaching event-listeners on link tags. These event listeners should get called.

### Actual Behavior
Link is triggered but not to event listeners, so the request is always a GET and not a DELETE.

### Reproduction Link
<a href="https://codepen.io/daniel_schwab/pen/NWPNOqK" target="_blank">https://codepen.io/daniel_schwab/pen/NWPNOqK</a>

### Other comments
https://github.com/vuetifyjs/vuetify/blob/432c4db29a521323e0c2b40a6a164cc99c0fbcb3/packages/vuetify/src/components/VMenu/VMenu.ts#L324

Here the event propagation is stopped. Menu seems to work even with this line commented out.

**Comment by KaelWD** [comment] 2019-12-13 05:11
Duplicate of #6654

**Closed by KaelWD** 2019-12-13 05:11 UTC
Labels: triage
