### ISSUE TITLE
[Bug Report] High CPU usage in Safari on docs page + in webpack/simple bolerplate

### ISSUE THREAD

**Issue by outluch** [vuetifyjs/vuetify#2773] opened 2017-12-11 21:14 UTC
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.5.9
**Browsers:** Safari 11.0.2
**OS:** Mac OS 10.13.2

### Steps to reproduce
Open docs OR sample project https://github.com/vuetifyjs/webpack) in safari and open Activity monitor. Observe 99% CPU on that tab

### Expected Behavior
Not so high CPU usage without activity in tab

### Actual Behavior
CPU = 99%

### Reproduction Link
[https://github.com/vuetifyjs/webpack](https://github.com/vuetifyjs/webpack)

**Comment by johnleider** [comment] 2017-12-11 21:43
What are your Mac's specs?

**Comment by outluch** [comment] 2017-12-11 21:45
i7 2.2 GHz. It is pro 15 2014.
I honestly think it is some kind of loop. But I couldnot check that with safari dev tools. No profiler there 👎

**Comment by outluch** [comment] 2017-12-11 21:47
Hmm. Now I dont observe problem with webpack template. But in Docs I do.

**Comment by johnleider** [comment] 2017-12-12 12:43
All of docs? Specific page? Please provide information as if **you** were trying to debug this.

**Comment by outluch** [comment] 2017-12-12 23:41
Ok. I've found way to profile page.
Look: http://take.ms/5uZrW
Honestly, dont know what to look at next..

**Comment by ajsutton** [comment] 2018-01-05 20:25
For the record, I can reproduce this as well with the same constant cycle of safari invalidating the layout and the recomputing it.  It appears to happen with 1.0-beta1 and 2 and to a lesser extent the latest stable version (can reproduce at https://vuetifyjs.com/vuetify/quick-start).  With 0.17 it's not in quite so tight a loop and so uses about 50% of CPU instead of 100%.

Seems to be related to v-navigation-drawer.  Just:
<pre>
  &lt;v-app>
    &lt;v-navigation-drawer app>&lt;/v-navigation-drawer>
  &lt;/v-app>
</pre>
is enough to trigger it, but &lt;v-app> by itself is not.  It also doesn't happen if you omit the app param from v-navigation-drawer.

**Comment by ajsutton** [comment] 2018-01-05 20:46
Problem disappears if in the web inspector you disable the inline style rule:
max-height: calc(100% - 0px);

Unfortunately it also occurs with clipped navigation drawers which have max-height: calc(100% - 64px) which makes avoiding the calc much more difficult.  This is a safari bug but it renders vuetify pretty unusable on Safari, especially with a laptop as the fans quickly spin up and battery drains very quickly.

**Comment by outluch** [comment] 2018-01-05 21:06
Thanks for your investigation. I think it is huge problem. Safari is not IE6. It is mainstream browser.

**Comment by ajsutton** [comment] 2018-01-05 21:16
It's not as simple as just having max-height with a calc though. I'm currently trying to build a reduction to identify the exact combination of styles that trigger the issue. Even though JavaScript execution isn't turning up in the profiler, without the vue/vuetify js in place the problem doesn't occur so it's some combination of styles and javascript.

**Comment by outluch** [comment] 2018-01-05 22:18
Hey! 
After looking at this https://github.com/vuetifyjs/vuetify/blob/7cd0f31de96e7a189bc9477e9b2386973d701104/src/components/VNavigationDrawer/VNavigationDrawer.js#L317
I ran vuetify docs in safari resonsive mode and no bug :)

**Comment by ajsutton** [comment] 2018-01-05 23:19
Bisecting on the dev branch, the first revision this problem occurs on is https://github.com/vuetifyjs/vuetify/commit/6c612c560ce19ca8c815aa5ea731b4f56ed48aea

but I don't see how it's related.

**Comment by ajsutton** [comment] 2018-01-06 01:54
Bisecting on the dev branch but ensuring we remove font awesome from dev/index.html each time points to https://github.com/vuetifyjs/vuetify/commit/d6343519f40dca2815e09d5ab85617cc5cd99756 which is  more believable since it ties into how the data-booted="true" attribute is added and we know that's a key component of the issue.

**Comment by ajsutton** [comment] 2018-01-07 21:44
I still haven't been able to pin down the exact cause of this but have found a simple work around anyone struggling with this can apply in the meantime. Add the css below to your app:
.navigation-drawer {
    transition-property: transform,width,box-shadow !important;
}

It's fairly likely there needs to be some extra properties added to that list to cover all the possible ways that navigation drawer can animate (hence this hasn't been committed to codebase) but it's enough to cover at least the basic cases.  The key property not to add is max-height, doing so will trigger the high CPU usage again.

**Comment by ajsutton** [comment] 2018-01-08 04:21
Confirmed this is caused by a Safari bug.  Minimal replication is available at https://www.symphonious.net/bugs/vuetify2773/

It has already been fixed in the current Safari Technology Preview so should be fixed in the next Safari release.  However, it's an annoying enough problem that I'd recommend putting the work around in to vuetify for at least the 1.0 release.  I'll submit a pull request to do that shortly.

**Closed** 2018-01-10 01:41 UTC
Labels: bug, help wanted
