### ISSUE TITLE
[Feature Request] New component VCounter

### ISSUE THREAD

**Issue by vw-bmacher** [vuetifyjs/vuetify#8363] opened 2019-08-07 20:09 UTC
### Problem to solve
Simple component that can in- or decrease a counter. I was facing this problem in a recent project and couldn't find a proper component.

### Proposed solution
Just the counter with an arrow to increase and an arrow to decrease the counter. By clicking on the counter it is swapped with an input. A prototype can be found under the following link: https://stackblitz.com/edit/vuetify-v-counter. There could be an option to change the position of the arrows to be above and under the counter.

BTW: I would love to implement the component :-)

**Comment by nekosaur** [comment] 2019-08-09 10:23
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7374

**Closed by nekosaur** 2019-08-09 10:23 UTC
Labels: duplicate
