### ISSUE TITLE
[Documentation] Make searchbar for version 1.5. as for 2.0 in documentantion.

### ISSUE THREAD

**Issue by tomasfil** [vuetifyjs/vuetify#8306] opened 2019-08-05 15:20 UTC
### Problem to solve
Much easier navigation. 

### Proposed solution
Make the same search mechanism for vuetify documentation page as version 2.0 had. I think 1.5 had it as well, I have no idea why that was removed (if it was). I am not moving to 2.0 till more clear resources are avaible for upgrading, because I tried that and I couldnt get it work, it even broke IE 11, which was working before (critical for my company). And before 2.0 is in more mature state,

**Comment by jacekkarczmarczyk** [comment] 2019-08-05 16:07
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8034

**Closed by jacekkarczmarczyk** 2019-08-05 16:07 UTC
Labels: T: documentation
