### ISSUE TITLE
[Bug Report][3.4.8] property "total-visible" at VPagination not work

### ISSUE THREAD

**Issue by ftrsoft** [vuetifyjs/vuetify#18920] opened 2023-12-22 07:48 UTC
### Environment
**Vuetify Version:** 3.4.8
**Vue Version:** 3.3.9
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
When I have 5 pages and set total-visible = "4" I see next variants at pagination:
*  1 2 3 ... 5 
*  1 ... 3 ... 5
*  1 ... 3 4 5

### Expected Behavior
Should count the number of elements between the outermost buttons

### Actual Behavior
-

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtmEtv2zgQgP8KIewiCRDJbzcR3GIX6W6bPoBci6YHWprYRGlSoEZu0iD/vaSeFC0ZNtBDD9ZF0gxn+M2DtMWvz16qosG/SRJsM/BCb4GwSThFeHMvCFls/Zgi9ZEuORgBIVt/I2PgYUJX8PreM7d7r1CFa6AxqFSLy6daw7RbI48hTUGho/ATUH7pMBfcgbqrHeckmqUi0wgplxiiTEpVDorwiP4DAx5XQu0+Z/W3lGfdvosr4jQ1dAn1x7Z8zWLwY0DKeNpIOV0C16NvjTei0YmdBHNtmNB6f9SS0UctG81sGT4lBktkmyUoW/FPlui8wx588lrPqlK4FXj+F2xB4CUZDS8aJ28WAzsnVRIHVn178rqUiHLTpDZm2zpDucNIz2aiRpOtelxeBJ0JJigyWTovrrJnnHYpS8RBrHBd6m5kJtAZgBKpTgJLmW5CPW5q6/Mwm1kb6oHG7gravNpdrUVOUhZppFiC+Vh4TKRCEsMDzTiS58KhsT6/qN4IUYCZEs07yTsiJKPLRmIXLyQzS1OulZB8tcO2nJmLcrYSITlLkSo8s6zN9R2etErQDbiaVNObKEPyQHkKjhYZGtXZ22JVkvPRcLgi+nHLxOqi7eul9fZc295QLhWD9OyyxIgqQa/J/1RPZfyXFg8U+wffULVMW8MjI+k3uFMSgYmWSVLI+o1uldQWfzcWTAvaw79Zz9U2tr9mpiAmXCV/giBf5CrbLV2VLd0ss2tHp/MSknkw3DHR8YdkPHXkZZAhme6YmGja7bhT0E702whIpIBuSEpF/INF637+8eRVF/91H//OcIt/8pv4/9P7FlN7mOfjLuZRf9Jdshp616SAbkd5CPRNlkT0+85SbqgnQ3v7qKkngZvREnp+dKavjoZ+p3cMUEvdK/Ee8Nn8uHRP3SVRk08CV1X2SHuGQ9A/AOdPZAlU7CF/1ZnyYR/4de/i3DUpwNvSQ7g/Sc5ZIpM91Ned7T0MXHFF3a67Td3J3HZzCPN7KeApkptlP/R06FKU3d0DfdXb3fPALVqBPW2LD+F+K0W2Z++ezjoTPZ719cesvZe1lmR3Y4+PT/ZHhh/1T2sv9WzUmelx73Kcu/msqd0aFMzHr8UT8gn5hHxCPiGfkE/IfxBy8/X7UjxUSv1nLskQ4rCJqT7Isc9I6lOSzxTXQQSMn+OapUH1KR0U50BkQHKxfVxyUU9dzlncNchiUJ/VeC+X3iTQnwWeuU+DK+/bL7u2FWg=)

**Comment by KaelWD** [comment] 2024-01-31 08:10
Duplicate of #18853

**Closed by KaelWD** 2024-01-31 08:10 UTC
Labels: S: triage
