### ISSUE TITLE
[Bug Report] Inset footer is causing some rendering issues with navigation drawer

### ISSUE THREAD

**Issue by BruceBradford** [vuetifyjs/vuetify#4727] opened 2018-07-26 16:28 UTC
### Versions and Environment
**Vuetify:** 1.1.8
**Last working version:** 1.1.6
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 7

### Steps to reproduce
1. Build a navigation drawer (mini set to true in my case)
3. Add page content. The page content should be large enough to cause vertical scrolling
4. Scroll the page up and down and observe the rendering of the navigation drawer

### Expected Behavior
Navigation should not cease to render 

### Actual Behavior
1. Navigation drawer ceases to render.
2. It appears as if the navigation drawer is translucent and you can see the footer behind the drawer. 

### Reproduction Link
[https://codepen.io/anon/pen/zLdZBE](https://codepen.io/anon/pen/zLdZBE)

**Comment by scp-nm** [comment] 2018-07-27 07:22
Hi,
I'm getting the same, and this is easily reproducible on the Layout Sandbox - simply change footer to 'inset':
https://vuetifyjs.com/en/examples/layouts/sandbox

**Comment by steinwachs** [comment] 2018-08-02 07:39
I can confirm both the issue and the last working version (1.1.6). It is present both in 1.1.9 and 1.2.0-beta.0 as well.

**Comment by KaelWD** [comment] 2018-08-02 07:44
This was caused by cc4959f0f68487d9359d8bec48f14e36a42e7cf2 and 517e64aba7b60391fc9e255a3b8eba49876a3436, we need a better system to fix all these issues.

**Comment by colegasgroupdev** [comment] 2018-08-08 05:30
Does anyone have a work around for this?

**Comment by KaelWD** [comment] 2018-09-05 14:10
Duplicate of #4686

**Closed by KaelWD** 2018-09-05 14:10 UTC
Labels: T: bug

**Comment by EstefanTT** [comment] 2019-03-04 21:50
There is a fun work around ...

You store in VueX store the value True/False of the drawer and change its state when you open and close it. 
Then, you define a margin for the content of the Footer only displayed when the value of the Drawer is "true". 

**store/index.js** 

`import Vuex from 'vuex'

const drawer = () => {
  return new Vuex.Store({
    state: () => ({
        drawer: false
    }),
    mutations: {
        drawerToggle (state) {
            state.drawer = !state.drawer
        }
    }
  })
}

export default drawer`

**TheNavbar.vue **

`<Template>
<v-toolbar app>
<v-toolbar-side-icon @click="$store.commit('drawerToggle')"></v-toolbar-side-icon>
(...)
<v-navigation-drawer v-model="drawerState" app class="indigo darken-1">
(...)

<script>
(...)
  computed: {
    drawerState () {
      return this.$store.state.drawer
    }
  }
`

**TheFooter.vue **

`<Template>
(...)
 <strong :class="drawerState"> This is the Footer content </strong>
(...)

<script>
(...)
    computed: {
        drawerState () {
            return this.$store.state.drawer ? 'footerMargin' : ''
        }
(...)
`

I hope it helps, I'm a noob so ask if something is not clearly explained ;)
