### ISSUE TITLE
[Feature Request] Data table component grouping

### ISSUE THREAD

**Issue by GaborTorma** [vuetifyjs/vuetify#10425] opened 2020-02-02 16:26 UTC
### Problem to solve
Translation or changing to icon then group word in header.

### Proposed solution
I want to change the group word to my own language or better i want to change it to and icon.

**Comment by jacekkarczmarczyk** [comment] 2020-10-24 16:19
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8186

**Closed by jacekkarczmarczyk** 2020-10-24 16:19 UTC
Labels: C: VDataTable, T: feature
