### ISSUE TITLE
[Feature Request] Responsive grid gutters using breakpoints

### ISSUE THREAD

**Issue by jaminroe** [vuetifyjs/vuetify#6369] opened 2019-02-05 16:03 UTC
### Problem to solve
Currently, the layout grid is static and I don't see a way to use breakpoints so gutters are responsive between device sizes. 
For example: On a large display, I want the gutters to be 24px and anything less than or equal to a medium device, I want it to have 16px gutters.

### Proposed solution
Have an API option for the layout grid, to use breakpoints in combination with the grid list classes. Thanks!

**Comment by johnleider** [comment] 2019-02-15 16:39
Duplicate of #6020

**Closed by johnleider** 2019-02-15 16:39 UTC
