### ISSUE TITLE
[Bug Report] DataTable expand icon has incorrect svg size and is offset with mdiSvg icons

### ISSUE THREAD

**Issue by funkybg** [vuetifyjs/vuetify#10483] opened 2020-02-06 10:29 UTC
### Environment
**Vuetify Version:** 2.2.10
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.3

### Steps to reproduce
1. expand any table row

### Expected Behavior
Svg expand icons in data tables should behave the same way as other icon fonts

### Actual Behavior
Svg expand icons in data tables are offset

### Reproduction Link
<a href="https://codepen.io/mmartev/pen/abObwGr" target="_blank">https://codepen.io/mmartev/pen/abObwGr</a>

**Comment by rachael-smith** [comment] 2020-02-06 19:03
should be fixed with this fix 

[Bug Report] [VTextField] Clear icon (svg) mis-alignment #10480

**Comment by KaelWD** [comment] 2020-02-07 05:45
Duplicate of #10480

**Closed by KaelWD** 2020-02-07 05:45 UTC
Labels: triage
