### ISSUE TITLE
[Documentation] Undocumented VTabs prop changes with deprecated console message

### ISSUE THREAD

**Issue by 185driver** [vuetifyjs/vuetify#11641] opened 2020-06-15 15:54 UTC
### Environment

**Browsers:** Chrome 84.0.4147.45
**OS:** Windows 10

### Steps to reproduce
Open the codepen. Note the (somewhat cryptic) codepen console message.
`[Vuetify] [UPGRADE] 'true' is deprecated, use 'mobile' instead.`

### Expected Behavior
1. Well-defined deprecation message.
1. Updated VTabs documentation for show-arrows (maybe to match VSlideGroup docs?).
1. Note the deprecated changes in the v2.3.0 upgrade guide.

### Actual Behavior
1. Somewhat cryptic deprecation message in the console. Unless the only component in the file is VTabs, we can't tell that the message relates to the VTabs component. There's also no indication that this message relates to the `show-arrows` prop.
1. Conflicting (old) VTabs documentation for `show-arrows` prop.
1. No mention to look for and update the `show-arrows` VTabs prop in the upgrade guide.

### Reproduction Link
<a href="https://codepen.io/185driver/pen/MWKjyGm?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2F" target="_blank">https://codepen.io/185driver/pen/MWKjyGm?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2F</a>

### Other comments
The change to `show-arrows` appears to have occurred in PR [#11480](https://github.com/vuetifyjs/vuetify/commit/9f6f5a58481e5de6e95f8e7a84242cced940d70c#diff-a57019eb9533e577ff638592bb1c1771R37) and was applied to VSlideGroup.

I'm not including the VTabs `show-arrows` prop wording here, as I imagine it is out-of-date, and superseded by the VSlideGroup wording (?).

The current documentation wording for the `show-arrows` prop in VSlideGroup reads:
```
Controls the display of the previous and next arrows. 
By default, arrows will only display on desktop size screens when the container is overflowed. 
A value of `true` enables the display of arrows on mobile. 
A value of `desktop` forces arrows on desktop and a value of `always` forces 
arrows on both *mobile* and *desktop*.
```
However, the deprecation warning says that a `true` value is deprecated and to use `mobile` instead. This conflicts with the docs for VSlideGroup and VTabs as both mention that using `true` is acceptable and neither mentions the use of a `mobile` prop being available or preferred.

That would seem to indicate either the deprecation message is incorrect, or the docs are, or both.

**Comment by KaelWD** [comment] 2020-06-15 16:00
Duplicate of #11620

**Closed by KaelWD** 2020-06-15 16:00 UTC
Labels: triage
