### ISSUE TITLE
[Bug Report] Reactivity lost when overriding value in event handler

### ISSUE THREAD

**Issue by solvemon** [vuetifyjs/vuetify#10582] opened 2020-02-14 13:10 UTC
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.87
**OS:** Linux x86_64

### Steps to reproduce
In the attached example, the input selector does not like you to set the value 'c' and will in its input handler change it to 'a'. The two native controls, input and select both work as expected: when selecting C, the value is changed to A.

### Expected Behavior
The components (v-text-field and v-combobox) should not be allowed to display the value 'c'

### Actual Behavior
For the two Vuetify components, this works the _first_ time, but if you select C multiple times, it will not change, until you change to a legal value again.

### Reproduction Link
<a href="https://codepen.io/solvemon/pen/GRJoBZB" target="_blank">https://codepen.io/solvemon/pen/GRJoBZB</a>

**Comment by KaelWD** [comment] 2020-02-14 13:13
Duplicate of #2931

**Closed by KaelWD** 2020-02-14 13:13 UTC
Labels: triage
