### ISSUE TITLE
v-select initial value is not set when items are bound asynchronously

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#1873] opened 2017-09-25 15:17 UTC
### Steps to reproduce

Create a `v-select` and fill its `items` prop asynchronously.
Specify an initial selected value through the `value` prop or `v-model`.
The select has an empty selection after the items are loaded.

I am pretty sure this was working pre-0.15 so I suspect something has changed with regard to how the v-model is re-evaluated after the ìtems` prop change.

### Versions
Latest

### What is expected ?
The selected item should be set once the items are loaded.

### What is actually happening ?
The selected item remains null/undefined.

### Reproduction Link
https://codepen.io/anon/pen/pWRvWy

**Comment by jacekkarczmarczyk** [comment] 2017-09-25 15:36
Duplicate of #1743

**Closed by jacekkarczmarczyk** 2017-09-25 15:36 UTC
