### ISSUE TITLE
[Feature Request] Autocomplete with icons/images

### ISSUE THREAD

**Issue by Extarys** [vuetifyjs/vuetify#5556] opened 2018-11-08 21:50 UTC
### Problem to solve
My database return a list of countries: 
```
[
  {
    iso: 'CAN',
    name: 'Canada'
  },
  {
    iso: 'USA',
    name: 'United States'
  }
]
```

I would like to show an autocomplete dropdown field with the country icon on the left with the name, but the value to be 'CAN'.

### Proposed solution
```
<v-autocomplete
                    v-model="country"
                    :items="states" // Array of object
                    :items-name="name" // Object name
                    :items-icons="iso + '.png'"
                    :items-value="iso" // Or _index for item index in array?
                    persistent-hint
                  />
```

**Comment by KaelWD** [comment] 2018-11-09 03:30
Duplicate of #4169

**Closed by KaelWD** 2018-11-09 03:30 UTC
