### ISSUE TITLE
[Feature Request] Treeselect Component Required

### ISSUE THREAD

**Issue by ShilpaKumari123** [vuetifyjs/vuetify#10819] opened 2020-03-12 10:08 UTC
### Problem to solve
If we have chechbox inside checkbox like treeview in select, treeselect can solve such problem.

### Proposed solution
https://vue-treeselect.js.org/ ---

**Comment by KaelWD** [comment] 2020-03-12 10:10
Duplicate of #3049

**Closed by KaelWD** 2020-03-12 10:10 UTC
Labels: triage
