### ISSUE TITLE
[Feature Request] Add slider height property to v-tabs and to v-tabs-slider

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#7971] opened 2019-07-24 16:25 UTC
### Problem to solve
Depending on the custom theme and coloring decisions of the application in use, a default slider height of 2px might not be obvious enough for users. Currently there is no property available to us to adjust the slider height shown when using v-tabs

### Proposed solution
Add a 'slider-height' property to the v-tabs component and add a 'height' property to the v-tabs-slider component to allow developers to adjust the height of the slider.

**Comment by jacekkarczmarczyk** [comment] 2019-07-24 16:36
duplicate of https://github.com/vuetifyjs/vuetify/issues/7683

**Closed by jacekkarczmarczyk** 2019-07-24 16:36 UTC
Labels: triage
