### ISSUE TITLE
[Bug Report] Ugly prefix when it have long text

### ISSUE THREAD

**Issue by Djaler** [vuetifyjs/vuetify#5492] opened 2018-10-31 14:01 UTC
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Linux x86_64

### Steps to reproduce
Create text-field with long prefix

### Expected Behavior
It should just push content

### Actual Behavior
Content climbs on it

### Reproduction Link
[https://codepen.io/anon/pen/xyoyzB?&editors=101](https://codepen.io/anon/pen/xyoyzB?&editors=101)

**Comment by jacekkarczmarczyk** [comment] 2018-10-31 14:07
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3485

**Closed by jacekkarczmarczyk** 2018-10-31 14:07 UTC
