### ISSUE TITLE
[Feature Request] Data table component grouping selection

### ISSUE THREAD

**Issue by GaborTorma** [vuetifyjs/vuetify#10426] opened 2020-02-02 16:29 UTC
### Problem to solve
Need to set what field available for grouping.

### Proposed solution
Create a directive for setting up which field is groupable.

**Comment by quantumwebco** [comment] 2020-02-14 16:12
https://github.com/vuetifyjs/vuetify/pull/9937

Apparently they're not gonna do it until v3. Seems odd that it's not really a feature request it's more of a missing bit of functionality that should have been built in from the start and should be very simple to implement.

**Comment by nekosaur** [comment] 2020-02-22 15:33
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8281

**Closed by nekosaur** 2020-02-22 15:33 UTC
Labels: C: VDataTable, duplicate
