### ISSUE TITLE
[Bug Report] Navigation-drawer strange behavior

### ISSUE THREAD

**Issue by QTCkarolym** [vuetifyjs/vuetify#7068] opened 2019-04-24 17:26 UTC
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
It happens when i take all the letters inside the input and put the cursor outside the drawer and then i delete the content of the input i select before, the drawer the right side and stay show♥

### Expected Behavior
The drawer should be hidden when i closed♥

### Actual Behavior
The drawer is open and i'm not opening the drawer♥
![drawer](https://user-images.githubusercontent.com/46758150/56680663-aa031600-6695-11e9-9b88-98bc1b9dd936.gif)

### Reproduction Link
<a href="https://codepen.io/qtckarolym/pen/eoQYqL" target="_blank">https://codepen.io/qtckarolym/pen/eoQYqL</a>

**Comment by aburai** [comment] 2019-04-24 17:45
seems like something is setting the focus to the input, that causes the drawer to get visible

**Comment by KaelWD** [comment] 2019-04-25 01:51
Still a duplicate of #6969

**Closed by KaelWD** 2019-04-25 01:51 UTC
Labels: triage
