### ISSUE TITLE
[Bug Report][2.5.8] persistent-placeholder prop doesn't display placeholder text for v-file-input

### ISSUE THREAD

**Issue by phylot** [vuetifyjs/vuetify#14139] opened 2021-09-08 10:05 UTC
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.1
**Browsers:** Chrome 92.0.4515.159
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a v-file-input with a label, placeholder, and add the 'persistent-placeholder' prop.

### Expected Behavior
The placeholder text should display at all times.

### Actual Behavior
The placeholder text doesn't display until the v-file-input is focused / clicked.

### Reproduction Link
<a href="https://codepen.io/zerobob/pen/VwWPrLd?editors=1010" target="_blank">https://codepen.io/zerobob/pen/VwWPrLd?editors=1010</a>

**Comment by zetaraku** [comment] 2021-09-12 03:17
Is this issue a duplicate of #13969 ?

**Closed** 2021-09-17 09:11 UTC
Labels: S: triage, C: VFileInput
