### ISSUE TITLE
[Bug Report][3.1.4] v-menu content container not positioned correctly on RTL

### ISSUE THREAD

**Issue by fahmifitu** [vuetifyjs/vuetify#16628] opened 2023-02-09 20:56 UTC
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click on the button activators the first time (*position error*)
2. click to close the menu
3. Click again (positioned correctly)

### Expected Behavior
it should be positioned at the bottom of the buttons

### Actual Behavior
it's positioned on the far left

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUz1v2zAQ/SssOygFLKlFMhlOkW4dOxTtEGagJdpmzS8cT24Dw/+9R0qyZaUpkEXQfb17d3z3eOSHTqHePFe/Il9ybYMHZEfWgJKofvQxdmIb8JYVQ24hnHDqT05tvIvIhgC7vy68OQrHmPGNNGrJsnExCwnFondtpDFr2ewnzlP+4k7ZVMlatZGdwe+9XRi93WGRk04fhOML/iWEiljQDCtUNhgi8TkhrA6lDCH/ZsNK7QYr28QfyaXg7MzuNToazXi4FzyAthKeBT+nfJOgHDLZoD5I9JD2cS61ynV5SNTeUfnaI3or+CU9YWaECWRPRkLLGiNjzCnlHSWwVd0HLqzJkZqMQ5FJdCcjvkLgAjBuiL2fcjqyAD5EdprTSsugr3Zt3gblJF6oIl73Tlyulv+GsWZDja758+S08QmT0T/uVV8yYwM6IIsKuxQ+yxrUZirmLORewTZuSb0Uvym+KmM8++nBtO8KUteq7uEIiITWYxGJQCfjHQku61oMAVrNWekiHVeyBd8hhris686F/bZqvK0fKFZD51BbVbbePtxWt9XHUpqwk9Vd3eqI03Cloi3X4H9HBdRY8OF0co90a6/1GcIE/2mEHU+eIF9A1YR/UFCSPFsFCv5Lf5b7rxFmKS/GyLdOV0ybNdrt42ypTcwLfRwZvmk+q12VAVL1U2pyWvArjtQ11/Gnv8SJpRs=)

**Comment by fahmifitu** [comment] 2023-02-09 21:38
used to work in 3.1.2

**Comment by Nikakto** [comment] 2023-02-12 09:38
confirmed for 3.1.4

**Comment by Nikakto** [comment] 2023-02-16 14:14
3.1.5 still not fixed.

**Comment by fahmifitu** [comment] 2023-02-22 20:08
exists in 3.1.6

**Comment by yeya** [comment] 2023-02-28 15:25
BTW when installing locally per docs with `yarn create vuetify` it's happening only in build version, and only the first time.

The second time or in dev mode it's working great.

![Vuetify3RTL](https://user-images.githubusercontent.com/6382246/221898572-8846f7cd-f2e7-4be7-8120-60f8e5ffb345.gif)

**Comment by yeya** [comment] 2023-03-01 09:38
v3.1.7 - still not fixed...

**Comment by yeya** [comment] 2023-03-01 17:27
I think the issue coming from this [commit](https://github.com/vuetifyjs/vuetify/commit/a11138e5f75a9ef81bb3b39daeb8bd1cb07997cb)

The `v-overlay__content` gets negative `left` value instead of positive.

In meantime I'm using a really nasty fix.

I added `@update:menu` to call a function that manually set it back to positive

``` 
@update:menu="menuOpened"

menuOpened(isOpen) {
      if (!isOpen) return;

      setTimeout(() => {

        const menu = document
          .querySelector('.v-overlay-container')
          .querySelector('.v-overlay__content');

        if (!menu) return;

        if (!menu.style.left.startsWith('-')) return;

        menu.style.left = menu.style.left.replace('-', '');

      }, 1);

    }
```
The `setTimeout` is required because the update:menu is fired before the overlay is mounted.

**Comment by Taha-Rehany** [comment] 2023-03-14 12:25
Any Updates?!

**Comment by Taha-Rehany** [comment] 2023-03-14 12:26
> I think the issue coming from this [commit](https://github.com/vuetifyjs/vuetify/commit/a11138e5f75a9ef81bb3b39daeb8bd1cb07997cb)
> 
> The `v-overlay__content` gets negative `left` value instead of positive.
> 
> In meantime I'm using a really nasty fix.
> 
> I added `@update:menu` to call a function that manually set it back to positive
> 
> ```
> @update:menu="menuOpened"
> 
> menuOpened(isOpen) {
>       if (!isOpen) return;
> 
>       setTimeout(() => {
> 
>         const menu = document
>           .querySelector('.v-overlay-container')
>           .querySelector('.v-overlay__content');
> 
>         if (!menu) return;
> 
>         if (!menu.style.left.startsWith('-')) return;
> 
>         menu.style.left = menu.style.left.replace('-', '');
> 
>       }, 1);
> 
>     }
> ```
> 
> The `setTimeout` is required because the update:menu is fired before the overlay is mounted.

Not working !

**Comment by yeya** [comment] 2023-03-14 13:49
It is working for me.
If you want my help send a playground link.

**Comment by abumalekFayed** [comment] 2023-03-15 21:57
Any update? this issue stop me from using the latest version.

**Comment by abumalekFayed** [comment] 2023-03-15 22:05
This problem found on all overlays as autocomplete select combobox and menu.

**Comment by shymaaMohmed** [comment] 2023-03-21 15:20
exists in 3.1.4

**Comment by abumalekFayed** [comment] 2023-03-23 05:45
This problem found in the first appearance of overlay and when menus or v-select or v-autocomplete closed and opened again the overlay appears in the correct position.

**Comment by shymaaMohmed** [comment] 2023-03-23 09:21
> I think the issue coming from this [commit](https://github.com/vuetifyjs/vuetify/commit/a11138e5f75a9ef81bb3b39daeb8bd1cb07997cb)
> 
> The `v-overlay__content` gets negative `left` value instead of positive.
> 
> In meantime I'm using a really nasty fix.
> 
> I added `@update:menu` to call a function that manually set it back to positive
> 
> ```
> @update:menu="menuOpened"
> 
> menuOpened(isOpen) {
>       if (!isOpen) return;
> 
>       setTimeout(() => {
> 
>         const menu = document
>           .querySelector('.v-overlay-container')
>           .querySelector('.v-overlay__content');
> 
>         if (!menu) return;
> 
>         if (!menu.style.left.startsWith('-')) return;
> 
>         menu.style.left = menu.style.left.replace('-', '');
> 
>       }, 1);
> 
>     }
> ```
> 
> The `setTimeout` is required because the update:menu is fired before the overlay is mounted.

Not working correctly

**Comment by mohammad-zr** [comment] 2023-04-05 16:50
any update on this issue? It's super important but not fixed yet

**Comment by abumalekFayed** [comment] 2023-04-05 16:58
Unfortunately this issue assigned to 3.x.x milestone this mean no dead line for fix this problem.
This issue limit using vuetify from all RTL community .

**Comment by Mostafa-Shalaby** [comment] 2023-04-05 18:42
Okay so, this issue is quite serious, and i needed a fix deployed asap, thus i toke it up on myself to do so.

First let me list my findings before showing off my bandaid solution to the issue.

This issue affects any controls that use **VOverlay**, in any way shape and form. This means is due to the changes introduced  to the **Location Strategy of VOverlay** in v3.1.3 (I.e. the logic that place the overlay in on the screen relative to its parent)

From what i experienced the following components are affect:
1. VTooltip
2. VMenu
3. VSelect
4. VAutocomplete
5. VDataTableFooter (Labs component that use VSelect)

Since i need Vueitify datatable and some of the fixes with latest patches, i could not wait any long so i looked into a fix of the sort. So onto the bandaid fix, the idea behind it, is very simple, extend the components, try to fix the menu behavior then replace the global imports for those component, so the rest of the application can use the modified component.

<details>
<summary>
**VTooltip Click Here**
</summary>

1. First i created an component called CustomVToolTip with the following code
```
<template>
  <VTooltip @update:modelValue="toolTipOpened">
    <template
      v-for="(slot, index) of Object.keys($slots)"
      :key="index"
      v-slot:[slot]="slotProps"
    >
      <slot v-bind="slotProps" :name="slot"></slot>
    </template>
  </VTooltip>
</template>

<script setup lang="ts">
// This import is needed to prevent recursion (From Global Imports)
import { VTooltip } from "vuetify/components/VTooltip";

// [BAND AID FIX] For the menu opening in a outside
// of the window way For the first time for RTL View
const toolTipOpened = (isOpen: boolean) => {
  if (!isOpen) return;
  setTimeout(() => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const menus = (document as any).querySelectorAll(
      ".v-overlay-container .v-overlay.v-tooltip .v-overlay__content"
    );
    if (!menus) return;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    menus.forEach((menu: any) => {
      if (!menu.style.left.startsWith("-")) return;
      const windowWidth = window.screen.width;
      const width = menu.offsetWidth;
      const left = Number(menu.style.left.replace("px", ""));
      menu.style.left = windowWidth - Math.abs(left - width) + "px";
    });
  });
};
</script>

<style scoped></style>
```
2. In your main.ts (After `createVuetify`), or in a custom plugin you can inject/register your component in place of the one registered by Vuetify like so
```
import CustomVTooltip from "../fix/custom-v-tooltip.vue";
app.component("VTooltip", CustomVTooltip);
```
</details>

<details>
<summary>
**VSelect, VAutoComplete, VMenu, Fix Click Here**
</summary>

1. First i created an component called CustomVSelect with the following code, (for other compoents it's same solution but different events to hock onto)
- For VMenu hock onto the `@update:model-value` 
- For VSelect and VAutocomplete hock onto the `@update:menu`
```
<VSelect>
  <VuetifySelect @update:menu="menuOpened">
    <template
      v-for="(slot, index) of Object.keys($slots)"
      :key="index"
      v-slot:[slot]="slotProps"
    >
      <slot v-bind="slotProps" :name="slot"></slot>
    </template>
  </VSelect>
</template>

<script setup lang="ts">
// This import is needed to prevent recursion (From Global Imports)
import { VSelect } from "vuetify/components/VSelect";

// [BAND AID FIX] For the menu opening in a outside
// of the window way For the first time for RTL View
// This should be disabled when Vuetify fixes the issue
const menuOpened = (isOpen: boolean) => {
  if (!isOpen) return;
  setTimeout(() => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const menus = (document as any).querySelectorAll(
      ".v-overlay-container .v-overlay .v-overlay__content"
    );
    if (!menus) return;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    menus.forEach((menu: any) => {
      if (!menu.style.left.startsWith("-")) return;
      const right = menu.style.right;
      const left = menu.style.left;
      menu.style.left = right;
      menu.style.right = left.replace("-", "");
    });
  });
};
</script>

<style scoped></style>
```
3. In your main.ts (After `createVuetify`), or in a custom plugin you can inject/register your component in place of the one registered by Vuetify like so
```
import CustomVSelect from "../fix/custom-v-select.vue";
app.component("VSelect", CustomVSelect);
```

</details>
Things to note, i am using composition api with setup tag, so you have to adjust it to your own code base.

This code extends all the slots, events and props of the original function, so it should feel seamless if you are using global imports, but it would be a bit painful for you if  you locally import your Vuetify components

This solution is a bandaid solution, there is still weird closing animation that occur when opening the overlay, but that happens very briefly and i think... this solution is atleast a decent stop gap one.

Happy coding.

**Comment by yeya** [comment] 2023-04-06 18:20
> const toolTipOpened = (isOpen: boolean) => {\n  if (!isOpen) return;\n  setTimeout(() => {\n    // eslint-disable-next-line @typescript-eslint/no-explicit-any\n    const menus = (document as any).querySelectorAll(\n      \".v-overlay-container .v-overlay.v-tooltip .v-overlay__content\"\n    );\n    if (!menus) return;\n    // eslint-disable-next-line @typescript-eslint/no-explicit-any\n    menus.forEach((menu: any) => {\n      if (!menu.style.left.startsWith(\"-\")) return;\n      const windowWidth = window.screen.width;\n      const width = menu.offsetWidth;\n      const left = Number(menu.style.left.replace(\"px\", \"\"));\n      menu.style.left = windowWidth - Math.abs(left - width) + \"px\";\n    });\n  });\n}

Very nice, thanks for sharing.

Looks like you build it based on my code. But it covers much more.

**Closed** 2023-04-19 14:04 UTC
Labels: T: bug, rtl, C: VOverlay

**Comment by mohammad-zr** [comment] 2023-10-29 20:23
![image](https://github.com/vuetifyjs/vuetify/assets/1607415/5329de55-f785-4d52-b7ba-e09f8cf2378d)


I'm using latest version of Vuetify (3.3.23) and some of our users reported that sometimes v-select opens in an incorrect position. Unfortunately I can't reproduce issue yet
Can anyone help through this issue?

**Comment by johnleider** [comment] 2023-10-31 16:35
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or create a new [discussion](https://discussions.vuetifyjs.com).

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
