### ISSUE TITLE
[Feature Request] DateTimePicker

### ISSUE THREAD

**Issue by cn-xufei** [vuetifyjs/vuetify#2674] opened 2017-11-30 06:49 UTC
# New Functionality

Components  —  Pickers

Hope to choose the time while choosing the date

Element.io has a similar feature http://element-cn.eleme.io/#/zh-CN/component/datetime-picker

I think it'd be cool if this was available in vuetify too:clap:

**Comment by jacekkarczmarczyk** [comment] 2017-11-30 07:07
duplicate of https://github.com/vuetifyjs/vuetify/issues/459

**Closed by jacekkarczmarczyk** 2017-11-30 07:07 UTC
