### ISSUE TITLE
[Bug Report][3.0.0-beta.5] `v-select` get validation error on form reset

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15487] opened 2022-07-21 12:27 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.5060.114
**OS:** Windows 10

### Steps to reproduce
Try to select any dropdown option of select and reset the form using reset btn.

### Expected Behavior
It should reset the form with a validation error. same as vuetify 2

### Actual Behavior
It validates select and throws errors.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/oNqWQxq?editors=101" target="_blank">https://codepen.io/Alokdev/pen/oNqWQxq?editors=101</a>
![chrome-capture-2022-6-21](https://user-images.githubusercontent.com/80033712/180213235-67fdadd5-3ea2-4f00-8b08-69a6decb2e22.gif)

**Comment by alokVishu** [comment] 2022-07-21 12:29
Also, checkbox and label does not get danger color and border .

**Comment by johnleider** [comment] 2022-07-21 18:29
duplicate of #15479

**Closed by johnleider** 2022-07-21 18:29 UTC
Labels: S: triage
