### ISSUE TITLE
[Feature Request] Turn off group for selected column in the datatable, similar to sortable false.

### ISSUE THREAD

**Issue by baldeepsinghkwatra** [vuetifyjs/vuetify#8281] opened 2019-08-03 09:01 UTC
### Problem to solve
There are times when we want to restrict grouping for a particular column. 

### Proposed solution
If a flag can be exposed in the column header JSON as allowGroup : false. (defaults to true)
So basically 'show-group-by' turns on grouping in data table, for all columns but we can pass a flag for the selected column where we don't want grouping.

**Comment by baermathias** [comment] 2020-11-11 14:51
Is this still an issue? Because according to the [docs ](https://vuetifyjs.com/en/components/data-tables/#grouping), you can use the groupable property on header items to disable the group button.

        headers: [
          {
            text: 'Dessert (100g serving)',
            align: 'start',
            value: 'name',
            groupable: false,
          },
          { text: 'Category', value: 'category', align: 'right' },
          { text: 'Dairy', value: 'dairy', align: 'right' },
        ],

For me it doesn'twork, cause I am using `"vuetify": "^2.2.15"` in my project, so I have to upgrade (hopefully without breaking anything). But it might work in the newest version (?)

**Comment by KaelWD** [comment] 2020-11-12 03:02
Duplicate of #10889

**Closed by KaelWD** 2020-11-12 03:02 UTC
Labels: C: VDataTable, T: feature
