### ISSUE TITLE
[Bug Report][2.4.9] Date-Picker menu with `open-on-focus` attribute opens and closes directly on click into the input field

### ISSUE THREAD

**Issue by qstiegler** [vuetifyjs/vuetify#13891] opened 2021-07-06 12:51 UTC
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.12
**Browsers:** Chrome 91.0.4472.114
**OS:** Mac OS 10.15.7

### Steps to reproduce
If you focus the  `Test input` input field of the code example and press tab, it directly opens the date picker as expected. But if you click into the `Test date picker` input field by mouse, the date picker shows for a millisecond and closes directly again.

### Expected Behavior
It would be perfect if the date picker overlay opens when you enter the input (either by pressing tab while being on the input field before or by clicking with the mouse into the input field) and additionally the date picker should close if you press tab again and move to the next input in the form

### Actual Behavior
With `open-on-focus` attribute it works with tab and without the attribute it works on mouse click. It should work both.

### Reproduction Link
<a href="https://codepen.io/qstiegler/pen/mdmVgrO" target="_blank">https://codepen.io/qstiegler/pen/mdmVgrO</a>

**Comment by vcavallo** [comment] 2021-07-27 22:22
Duplicate or very similar to this quite old issue: https://github.com/vuetifyjs/vuetify/issues/9129

**Comment by qstiegler** [comment] 2021-08-17 06:25
Yes it's similar but why does it not get prioritised if it is already so old? Many people get through forms by clicking tab-key or using the autocomplete on the phone. If the date picker doesn't not open, the user thinks it's a regular input element.

**Comment by johnleider** [comment] 2023-08-08 23:48
Closing as a duplicate of #9129

**Closed by johnleider** 2023-08-08 23:48 UTC
Labels: C: VMenu, S: triage
