### ISSUE TITLE
[Bug Report][3.4.1] Unwanted Scrolling to Top in v-list with v-list-group

### ISSUE THREAD

**Issue by briantsaunders** [vuetifyjs/vuetify#18693] opened 2023-11-15 16:27 UTC
### Environment
**Vuetify Version:** 3.4.1
**Vue Version:** 3.3.8
**Browsers:** Firefox 119.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. Click on any text at the top of the page (like this bullet point)
2. Scroll to the bottom of the page
3. Click and drag the handle

### Expected Behavior
You can drag the v-list-item around and the scroll position stays put. 

### Actual Behavior
You can drag the v-list-item around but the page scrolls to the top. 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVl9v4zYM/yqE99AWja3bbgcMmS/obS2wG4a9dBg2NH1QbCXRKkuCJOfSBfnuo2TZjp00C7ABQSxR/PMjRVJ82iXWFGRTM8eXr9lfNpkmvNLKONhBYRh17PfmDPawNKqCq8h7NZdzybaBtVDSOogH8HEoeL2bSwC3ZhWbQlgDlGxJa+F+a4hXgq/W7mriz/b4v7+Zy2QSgH3SOkO9iCp3rNIC1c48W75JqdZhGTaIwFEumYmkhkhNCUuU6YgdOXXcCTaDhy1FrQzUEh4Lo4SAn+tKww/1CnIyYD1WYetFOIJCUGs/zhPHti79YqieJwfsKKBnuXVGydXs0TFtwSkwTBtV1gWb5iSe5aR1KIopMdgjRfARBeBHwYsXUBKofAWPAKjz0UYj2rvll5quGFwL/oLUNbewqIVgDrTi0mGsBybIkQ1vNQYHgXt9C+UcpsKB9jfEGnBUllAaugrca9yJY/6cjLzFoI30xTA9bDUrHCv7wMGfqoaCys7ISLBQJZttUsGtSzmmUU4CBahRNULz8Dwy2/ioleWOY0Cto68WdO2yIdDRLb2F81Phair+N5SLurnWcJcN1JBI8arPYOwSuU3YU+WAiTN0q0Ey9u3RX+gveACbtEJ4Yuq5MPc3VNTMjhK/F/mMDqHIUhnkveblBLgs2fYGP9CKwvSFveIxL/06nPud/57Q20FMVxggDdOgphVHVwP5hBgKtq0EvqKF4xvqVN83TtvwF4JADafSe+uUpOIkqCMLGiudyfJNVmS+x4T4KZTFGa6AhWOfA/+HGKqSpz6V0rUy/G/f/0QaEWIAyDmD5AKLORk03H8LzlGXPGKOZfD51/uHPw6qYrdrUgH2+wuE70eS5Rkxn/eX4Rtwnk6Zc9HoxE+nXE66EhiXU3Pi62nUDI+qr3+NDiu1pbYPod8OXkJPaR7KgQe4xRbCdaOpe/D7tJhAhywuQwUfzACp9VSLgmESAIizQHza25e+UKhcMuls9/jDoZ2W1JsbULzVSPGTQZgdqKNTWNYSSxer4fqm12uYq43s9xB7yxSenju9MV9adc2sUr6hERsWPpz4VnIca959j58cPvjv7e0Blx9vuM0aY5mu7fqad+/qwB5uMIHb0OOQ08Q+rajG4UtJHHSCVmxj4QDbYhc3bLI18/t5snZO2ykhRSlRDNsw35hMMkekrsgdshFTS8crlpaqunufvc++IyUG95CcMVulC6O+WGZQyTyJAQlm/OB2ganIiRa+zb5uLERSKujCehNHqgna2zCTGuyKzDBzqUcjsUOvRkdnPevz9jL/ev67b7J32Qdyi9rnSbxM/OElCi5f7Oj+Chvu7uk/RjCoeW4M7SdJcBotBvbk+R/KZIBB)

### Other comments
Appears there might be a bug in v-list when used with v-list-group that has `value`, `subgroup`, and `props` configured that causes unwanted scrolling under certain circumstances.  When removing `value`, `subgroup`, and `props` the bug is no longer present but the expansion functionality is no longer there.

I found similar issues that appeared related:

[Unexpected page scrolling when click a non-link VListItem with any focusable children](https://github.com/vuetifyjs/vuetify/issues/18223)

[v-list - unwanted scrolling up in iOS](https://github.com/vuetifyjs/vuetify/issues/17841)

**Comment by TheJaredWilcurt** [comment] 2023-11-15 17:04
Changing this:
```html
<v-list-group :value="id" subgroup class="mb-2">
  <template #activator="{ isOpen, props }">
    <v-list-item v-bind="props" variant="tonal" class="mb-2">
```
to this:
```html
<v-list-group class="mb-2">
  <template #activator="{ isOpen, props }">
    <v-list-item variant="tonal" class="mb-2">
```
(Removing `:value="id"`, `subgroup`, and `v-bind="props"`).

Fixes the scrolling bug issue, but then it breaks the expanding feature for the list groups.

**Comment by KaelWD** [comment] 2023-11-17 05:39
Duplicate of #18223

**Closed by KaelWD** 2023-11-17 05:39 UTC
Labels: S: triage
