### ISSUE TITLE
[Bug Report] [Bug] Web component with Vuetify CSS rendering

### ISSUE THREAD

**Issue by ScottBreyer96** [vuetifyjs/vuetify#10438] opened 2020-02-03 14:14 UTC
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.15.2
Hello,
I am currently working on the creation of a web component. I use the command "view build --target wc --name my-custom-element ./src/main.js" to create my web components from Vue components. When I use Vuetify to create a tree or an array of data in a Vue component, there are no problems, but when converting to a Web component, I have problems with the font, display and animation in the tree.

Here is my code and screenshots, thank you.

----------------- Treeview in Vue component -----------------
![Capture d’écran 2020-02-03 à 12 53 03](https://user-images.githubusercontent.com/39304258/73659990-97435600-4697-11ea-97fe-674aed929134.png)
![Capture d’écran 2020-02-03 à 12 53 10](https://user-images.githubusercontent.com/39304258/73659996-990d1980-4697-11ea-9d82-966a604b75ac.png)

----------------- Treeview in Web component -----------------

![Capture d’écran 2020-02-03 à 12 52 53](https://user-images.githubusercontent.com/39304258/73660057-bf32b980-4697-11ea-8d23-635bbd1dd7b1.png)

----------------- DataTable in Vue component -----------------

![Capture d’écran 2020-02-03 à 12 53 23](https://user-images.githubusercontent.com/39304258/73660063-c3f76d80-4697-11ea-82ac-eb7309858dab.png)

----------------- DataTable in Web component -----------------

![Capture d’écran 2020-02-03 à 12 53 33](https://user-images.githubusercontent.com/39304258/73660075-c9ed4e80-4697-11ea-8d75-1f30cd530cf4.png)

### Steps to reproduce
Create project vue
Create Component "vue-component.vue" with the code in the git depot

Replace main.js by :

import Vue from 'vue'
import App from './App.vue'
import vuetify from './plugins/vuetify';
import wrap from '@vue/web-component-wrapper';
import "vuetify/dist/vuetify.min.css";
import VueComponent from './components/vue-component'

const CustomElement = wrap(Vue, VueComponent);

Vue.use(vuetify);

new Vue({
vuetify,
render: h => h(App)
}).$mount('#app')
window.customElements.define('vue-component', CustomElement);

Replace App.vue by :

<script> import HelloWorld from './components/HelloWorld'; import VueComponent from './components/vue-component';
export default {
name: 'App',
components: {
HelloWorld,
VueComponent
},
data: () => ({
//
}),
};
</script>

Execute command : vue build --target wc --name my-custom-element ./src/main.js
### Reproduction Link

https://github.com/ScottBreyer96/Vuetify

**Comment by NoahStahl** [comment] 2020-02-05 02:08
I'm also struggling with the right way to integrate Vuetify into a Vue-based Web Component using the "--target wc" build option. The best I've found so far is to include the dist styles in my .vue component file:

```
<style src="vuetify/dist/vuetify.min.css"></style>
```

Otherwise, just by importing the plugin file and Vuetify components directly, the styles don't seem to be brought in. Is this the best way? Mainly I want to be careful on bundle size, as it seems the CSS is included twice in the built bundle file.

It works fine in a normal app, just the Web Component build target that changes things.

**Comment by KaelWD** [comment] 2020-02-05 04:49
Duplicate of #7622

**Closed by KaelWD** 2020-02-05 04:49 UTC
Labels: triage

**Comment by atulsourcecode** [comment] 2020-02-05 19:17
I am also facing css issue while using Vuetify components in vue web components. Styling looks weird in web component
