### ISSUE TITLE
[Bug Report][3.4.10] Cannot set default background color of the buttons inside a v-btn-toggle component. 

### ISSUE THREAD

**Issue by RejownAhmed** [vuetifyjs/vuetify#19076] opened 2024-01-19 15:15 UTC
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.4.13
**Browsers:** Chrome 120.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Use the v-btn-toggle component and see that there is no option to set default bg color for the buttons inside. 

### Expected Behavior
Should have a prop to set the default bg color

### Actual Behavior
No option to set the default bg

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU01v1DAQ/SuDJbQgNbtZtVyqFAlOHBEcemA5OMkkMTgey55kWVX970ySTZNV1V5685uP98bj518PKoZi98X7bd+hulUZY+utZvx8cABZn2jvx+MICnKsjcNwDgF8PUGJle4sA+qigbxjJhchNtTZEnKEiAxMoKHoIlMLBVkKVxA77ymixK2pG575IopGqcNpqgMdgRuEXBd/60CdK+G+MaJDng05MBGqMeoIjg0G3M5EMm3OLmGqa4tzEKBPWirR3h2UXAx10K7Ag1ryo6pkF8F1ttUyG1M4rRqsjlEajsk+TeGP3NFUpyR6XWCSIx8RHYw8WCbpmqvXwWjH0lrJvpfM02rnO8ztUmnrg4IGh4UJukn9P8FHU3Ij8Dp9L6jXtkNBz2YX5h8TUbYbeZfUc8nXNZaBvLF2JTrBC83vEnqz4O2iWGkb5cWeJB25iwcU8p8c9MD2suw5c3bH7G8JXhp8iEz+z3arfyEwFsF4HrzdTd/DtJ4CwwMErOARqiBO38iX2gzlg61cZGhjDXdDxYfNN7SW4J6CLd9tPi4liyvnymGnQ0W2m0RFTj1eqevtzXb/SZ0Pe/X7Pwn2Ldw=)

**Comment by yuwu9145** [comment] 2024-01-21 11:48
Perhaps we should introduce a new prop, something like `default-color` to customise  none-selected button colours? @johnleider @KaelWD

**Comment by KaelWD** [comment] 2024-01-21 12:58
Duplicate of #16686

**Closed by KaelWD** 2024-01-21 12:58 UTC
Labels: S: triage
