### ISSUE TITLE
[feature request] Allow boolean "false"  in selectable component's true-value and false-value props to invert switch state for boolean value.

### ISSUE THREAD

**Issue by Webifi** [vuetifyjs/vuetify#1633] opened 2017-09-08 03:21 UTC
In some cases, I run into boolean values that I want to display inverted from how they are stored. For example, a record may have a boolean "disabled" field, but I want the UI to show a switch as on when enabled (false).

It'd be nice if selectable components (Switches, Checkboxes, etc.) could have their true-value set to a Boolean of false.   This should allow setting :true-value="false" and :false-value="true" to be used as a way of inverting the switch, so a false boolean value would show the switch on. 

I should be able to take care of it by using  :value="!myBoolean" and @input="myInvertMethod" instead of v-model, but since true-value and false-value are almost there...

**Comment by jacekkarczmarczyk** [comment] 2017-09-08 07:11
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1369

Related: 
https://github.com/vuetifyjs/vuetify/issues/1454
https://github.com/vuetifyjs/vuetify/issues/1596 (PR https://github.com/vuetifyjs/vuetify/pull/1598)

**Comment by johnleider** [comment] 2017-09-08 12:30
@jacekkarczmarczyk is correct, this is a duplicate. It will be done however, thank you!

**Closed by johnleider** 2017-09-08 12:30 UTC

**Comment by imShara** [comment] 2018-06-07 09:14
How to use this with v-model, when two-way data binding enabled?

**Comment by johnleider** [comment] 2018-06-07 13:13
If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.
