### ISSUE TITLE
Input label is misaligned when error animation is active and input has an icon prepended.

### ISSUE THREAD

**Issue by alex-oleshkevich** [vuetifyjs/vuetify#1208] opened 2017-08-01 21:39 UTC
### Steps to reproduce

1. Add a required input;
2. Focus it by clicking it;
3. Click outside of the input;
4. Observe the animation.

### Versions
Vuetify; 0.14.7 
Vue: 2.4.2
Browser: Chrome 60
OS: Arch Linux

### What is expected ?
The label should not overlap the prepended icon on animation.

### What is actually happening ?
The label overlaps the icon.

### Reproduction Link
https://codepen.io/anon/pen/yoJVao

### Movie
https://youtu.be/j73j2gm0yOw

**Comment by johnleider** [comment] 2017-08-02 01:29
Duplicate of #1141

**Closed by johnleider** 2017-08-02 01:29 UTC
Labels: pending review
