### ISSUE TITLE
[Bug Report] clearable not working with date picker in menu

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#10335] opened 2020-01-26 08:19 UTC
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Linux x86_64

### Steps to reproduce
select range, clear it, then select other range

### Expected Behavior
select all days between selected range 

### Actual Behavior
selecting only 2 days without days between them

### Reproduction Link
<a href="https://codepen.io/kareemda/pen/qBEvQgM" target="_blank">https://codepen.io/kareemda/pen/qBEvQgM</a>

**Comment by KaelWD** [comment] 2020-01-26 09:11
Duplicate of #9529

**Closed by KaelWD** 2020-01-26 09:11 UTC
Labels: duplicate
