### ISSUE TITLE
v-select duplicates display in some cases

### ISSUE THREAD

**Issue by spaquet** [vuetifyjs/vuetify#1758] opened 2017-09-15 23:03 UTC
### Steps to reproduce
See https://codepen.io/spaquet/pen/BwNeOa

### Versions
Tested on 0.15.7

### What is expected ?
Value in a chips

### What is actually happening ?
Value is displayed twice. once in a chips and once outside the chips

### Reproduction Link
https://codepen.io/spaquet/pen/BwNeOa

**Comment by johnleider** [comment] 2017-09-16 04:22
It is only displayed outside of chips because of the nature of **chips** with autocomplete.  Notice it goes away when you blur.

**Comment by johnleider** [comment] 2017-09-16 04:23
This is also a duplicate of #1740 which will more than likely be closed as well.

**Closed by johnleider** 2017-09-16 04:23 UTC
Labels: wontfix

**Comment by spaquet** [comment] 2017-09-16 16:34
@johnleider blur is not an option. When you have to enter multiple tags then autocomplete is interfering in the process creating a terrible user experience.

**Comment by johnleider** [comment] 2017-09-16 16:35
If you are entering multiple tags, you should be using the **multiple** prop.

**Comment by spaquet** [comment] 2017-09-18 20:11
Same behavior...

**Comment by spaquet** [comment] 2017-09-18 20:12
I found a workaround by using a scoped template to manage the chips. But then, closing chips becomes suddenly more complex...

**Comment by johnleider** [comment] 2017-09-18 20:12
https://codepen.io/anon/pen/pWgrza
