### ISSUE TITLE
[Bug Report] weird behaviour with tabs

### ISSUE THREAD

**Issue by rveruna** [vuetifyjs/vuetify#7628] opened 2019-06-21 15:54 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.7
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
on your website is the same behaviour. hard refresh, go to tabs, then the very first click to next item the animation goes all the way to the left

### Expected Behavior
to behave the same as any click on next

### Actual Behavior
the animation goes all the way to the left

### Reproduction Link
<a href="https://codepen.io/vahdet/pen/dqmXbY" target="_blank">https://codepen.io/vahdet/pen/dqmXbY</a>

### Other comments
ignore the codepen. it is happening on your website as u have a bug there

**Comment by johnleider** [comment] 2019-06-24 16:08
Duplicate of #7108

**Closed by johnleider** 2019-06-24 16:08 UTC
Labels: triage
