### ISSUE TITLE
[Bug Report] V-Menu is not positioned with the position-x/y attributes when the attach attribute is set

### ISSUE THREAD

**Issue by dzhamshed** [vuetifyjs/vuetify#11991] opened 2020-08-03 16:55 UTC
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.6.11
**Browsers:** Firefox 79.0
**OS:** Linux

### Steps to reproduce
1. Create a v-menu and attach it another element with attach attribute
2. Position it with position-x/y attributes
3. It appears only on the left top corner, thus it does not see the position-x/y attributes
Example:
```html
<div id="myDiv" style="width: 500px; height: 500px; position:relative;"></div>
<v-menu absolute attach="#myDiv" :position-x="100" :position-y="100">Some items</v-menu>
```

### Expected Behavior
It should be positioned as mentioned by position-x/y attributes.

### Actual Behavior
It always positioned on the top-left corner.

### Reproduction Link
<a href="https://codepen.io/dzhamshed/pen/wvGwrqz" target="_blank">https://codepen.io/dzhamshed/pen/wvGwrqz</a>

**Comment by KaelWD** [comment] 2020-08-04 07:18
Duplicate of #6877

**Closed by KaelWD** 2020-08-04 07:18 UTC
Labels: triage
