### ISSUE TITLE
[Feature Request] Create component for WYSIWYG HTML editor

### ISSUE THREAD

**Issue by tbhaxor** [vuetifyjs/vuetify#9359] opened 2019-10-15 12:32 UTC
### Problem to solve
I wanted to implement the rich text editor in the project.

### Proposed solution
Create a usable component for WYSIWYG HTML editor as there in [quasar](https://quasar.dev/vue-components/editor)

**Comment by DRoet** [comment] 2019-10-15 12:45
duplicate of https://github.com/vuetifyjs/vuetify/issues/3550

**Closed by DRoet** 2019-10-15 12:45 UTC
Labels: duplicate
