### ISSUE TITLE
[Bug Report] Combobox search term remains after clicking an item in the list

### ISSUE THREAD

**Issue by gotson** [vuetifyjs/vuetify#8842] opened 2019-09-04 03:21 UTC
### Environment
**Vuetify Version:** 2.0.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Android 9, Windows

### Steps to reproduce
- in the tags field, type `gam`
- click on the proposed item: `Gaming`

### Expected Behavior
- 1 chip is added: `Gaming`
- the search term `gam` is cleared

### Actual Behavior
- 1 chip is added: `Gaming`
- the search term `gam` remains in the text input

### Reproduction Link
<a href="https://codepen.io/gotson/pen/GRKOoeb" target="_blank">https://codepen.io/gotson/pen/GRKOoeb</a>

**Comment by wannfq** [comment] 2019-09-04 04:47
I posted this clip on Discord channel
https://cdn.discordapp.com/attachments/340215499398840331/616102819417554988/Screen_Recording_2019-08-28_at_10.50.40_AM.mov

**Comment by gotson** [comment] 2019-09-05 05:45
> I posted this clip on Discord channel
> https://cdn.discordapp.com/attachments/340215499398840331/616102819417554988/Screen_Recording_2019-08-28_at_10.50.40_AM.mov

Thanks, but for me it's a different bug, i filled another issue here: https://github.com/vuetifyjs/vuetify/issues/8841

**Comment by wannfq** [comment] 2019-09-05 08:05
Found workaround on this
```
...
<VCombobox
    ...
    // Add these 2 attributes into the component
    :search-input.sync="searchInput"
    @change="searchInput = ''"
>
</VCombobox>

...
data() {
  return {
    ...
    searInput: "",  
  }      
}
```

**Comment by gotson** [comment] 2019-09-05 08:13
Thanks @wannfq, it works for both #8842 and #8841 ([codepen](https://codepen.io/gotson/pen/oNvoRRv))

**Comment by bludnic** [comment] 2019-10-05 15:34
Acording to this test, `internalSearch` should not be cleared. VCombobox is inherited from the VAutocomplete. Should their behavior be different in this regard?
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete2.spec.ts#L395

**Comment by florealcab** [comment] 2019-11-27 13:23
The workaround proposed by @wannfq does not work anymore for vuetify 2.1, is there an other workaround to fix it?

**Comment by johnleider** [comment] 2020-01-20 23:14
Duplicate of #6459

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment] 2020-01-31 07:52
#6459 is for v-autocomplete and is just ux, not an actual problem. In v-combobox the remaining text gets unintentionally added as an item when the field is blurred.

**Comment by johnleider** [comment] 2020-01-31 17:29
I can agree with that assessment. It would have to be introduced in a minor though.

**Closed** 2021-02-23 07:36 UTC
Labels: C: VCombobox, T: bug, has workaround
