### ISSUE TITLE
[Bug Report] v-speed-dial close icon is not centered

### ISSUE THREAD

**Issue by phil-eepos** [vuetifyjs/vuetify#3217] opened 2018-02-08 09:56 UTC
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Just use the current documentation of the floating action button at: https://next.vuetifyjs.com/en/components/floating-action-buttons
When you click on the speed-dial-button to open it, you will see that the close icon is not at the center of the button.

### Expected Behavior
Close icon is in the center of the speed-dial-component

### Actual Behavior
Close icon is at the right bottom of the button

### Reproduction Link
[https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/floating-action-buttons/speedDial.vue](https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/floating-action-buttons/speedDial.vue)

**Comment by KaelWD** [comment] 2018-02-08 10:08
Duplicate of #3207

**Closed by KaelWD** 2018-02-08 10:08 UTC
