### ISSUE TITLE
[Bug Report] Problems with item.name slot and sorting on DataTables

### ISSUE THREAD

**Issue by edwardsph** [vuetifyjs/vuetify#10150] opened 2020-01-08 09:54 UTC
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
The example in the codepen shows 2 problems:
1. 1st column is not capitalised
2. Sort doesn't work on the second column

### Expected Behavior
1. A column name using mixed case can still be modified with a slot
2. If a column name is not the same as the data field used, there still needs to be way for the column to sort

### Actual Behavior
1. The slot definition is not attached so the data is not capitalised
2. The workaround to attach a slot to such a column causes sorting to fail

### Reproduction Link
<a href="https://codepen.io/edwardsph/pen/ExaQLXJ" target="_blank">https://codepen.io/edwardsph/pen/ExaQLXJ</a>

### Other comments
The data I am trying to display has mixed case field names. When I do this and try to modify the presentation with an item.<name> slot nothing happens as the slot is not attached to the column. A workaround is to make the name in the header and the slot both lowercase - this means the slot works and I can then pull out the correct field from the data within the slot rendering but as seen in the second column, it then causes sorting to fail as the header definition doesn't know the correct data field as that is only known in the slot.

I attempted to use the header: "sort?: (a: any, b: any) => number" to fix sorting but couldn't get that to work. The documentation doesn't say what a and b are but I suspect they are the value defined in the header rather than the item which would have allowed me to pull out the correct field for sorting.

**Comment by KaelWD** [comment] 2020-01-08 10:19
> 1st column is not capitalised

duplicate of #10002

> column name is not the same as the data field used

The arguments are the associated header value, not the entire object. You can use the `customSort` prop to override sorting for the entire table, or transform the items in a computed property before passing them to the table.

**Closed by KaelWD** 2020-01-08 10:19 UTC
Labels: triage

**Comment by edwardsph** [comment] 2020-01-10 10:34
Thanks - I didn't find #10002 so that was helpful. I'm enjoying using Vuetify but in general I think the documentation could do we some additional clarity. For example, on headers it says "See the example below for a definition of all the properties". It says what the attribute names and types are but doesn't really define them. Thanks.
