### ISSUE TITLE
[Bug Report][3.1.2] Disabled item does not work on Autocomplete/Select

### ISSUE THREAD

**Issue by vdiaza** [vuetifyjs/vuetify#16475] opened 2023-01-19 14:17 UTC
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a list of items and have the property disabled: true.
Or
Set the item-disabled property within the component.

### Expected Behavior
It should set a specific item as disabled

### Actual Behavior
Nothing happens

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UdtuwjAM/RUrL2xSaQRsD6vYxB72FYSHAmbLaNMocdmmqv8+Jy2iXDYhpPrYPhdn2YhXa9NDjSITc8LSFjnhizIA88M4tzZ+xqLMtemrHslrqjYVryChMoqOvyJfY/GshGY+r8RpByCL2K2ePCrJgVQoOhNzOTDHpd84bQk8Uh3aurSVI2jA4Q5a2LmqhBGnGimzqYwniHpv33lwC8+wDOyKGtJUYAaj2qODySiBQ17UDEzapLNzPjE9TUwT2GqfrwvcZkCuxtsbs9PGLEysonD8D4yxIzZ+NzR5HzJ3KTmfSEQXkW9j009fGX6vJvL0DT5mBhEJGEcPtRIfRNZnUtbG7t9Tfi254J50tSFd4nhblYtZOk1nT5LT0BBP0Zfjtau+OAYrKtHni+Skdz9/CfRt5p2k0462hwLlFZVk/gO6sUOzRYfuX98Xs2feL3pX/oNmq0zLtyy02fuLM258POGSX6gVbSIC9cMjD8ccYvULT98LIg==)

### Other comments
I believe this has never work on vuetify 3

**Comment by bogdanciuca** [comment] 2023-01-22 06:50
Doesn't look like this prop has been ported yet to v3. (see https://next.vuetifyjs.com/en/api/v-select)

**Comment by KaelWD** [comment] 2023-02-23 08:36
Duplicate of #15933

**Closed by KaelWD** 2023-02-23 08:36 UTC
Labels: S: triage
