### ISSUE TITLE
[Bug Report] V-Treeview leaf selection not returning parent node if all children are selected Vuetify 2

### ISSUE THREAD

**Issue by ayush1303** [vuetifyjs/vuetify#10502] opened 2020-02-07 08:44 UTC
### Environment
**Vuetify Version:** 2.2.10
**Last working version:** 1.5.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 69.0.3497.100
**OS:** Linux x86_64

### Steps to reproduce
Create Treeview with leaf selection type. Select the parent node. Check v-modal only children will be there no parent as a parent is also completely selected. 

### Expected Behavior
VTreeView should return the parent node also if all the children are selected in the tree.

### Actual Behavior
The new behavior with Vuetify 2 v-Treeview is not returning the parent node if all the children are selected.

### Reproduction Link
<a href="https://codepen.io/ayush1303/pen/ExjxBaR?editable=true&editors=101" target="_blank">https://codepen.io/ayush1303/pen/ExjxBaR?editable=true&editors=101</a>

### Other comments
According to V-Treeview in Vuetify 1.5.x when we select the parent node it was returning all the nodes including parent (indeed there was no concept of lead/individual) selection.

Based on which I was able to fulfill the requirement of storing parent key only if all children are selected. (By removing children selected using the children object from the selected parent).

The new behavior with Vuetify 2 v-Treeview is not returning the parent node if all the children are selected which makes impossible to determine the parent of all children node are selected. Moreover, I can not go with the independent as I want to show the child node also selected.

**Comment by whoistobias** [comment] 2020-02-22 21:59
The leaf mode of selection is just a fundamentally different type of handling data. It's sort of like a filesystem, where the deepest nodes are files and the containing nodes are folders. When you select everything in leaf node, it's like selecting all the files in a filesystem, but not copying the filesystem itself. 

All the information is available so it would be reasonable to create computed properties to handle all the scenarios where you need to know what parent nodes are selected, or it's always possible to simply use independent and add functionality to select children automatically when a parent is selected.

I'm closing for now as this is working as intended.

**Closed by whoistobias** 2020-02-22 21:59 UTC
Labels: triage
