### ISSUE TITLE
[Feature Request] hovering nested v-menus

### ISSUE THREAD

**Issue by Quizart** [vuetifyjs/vuetify#6963] opened 2019-04-10 18:31 UTC
### Problem to solve
Currently, if you attempt to use nested v-menus with open-on-hover enabled, when navigating to inner menus, the whole thing closes - probably because you aren't hovering over the "base" menu slots anymore.

Example: https://codepen.io/Quizart/pen/rbyqBp

Workaround: Currently, we make all of the menus except one open on click instead, that works. But obviously, we would like all of menus to be open on hover.

### Proposed solution
Perhaps a way to specify a menu has child menus underneath it, so it can read into deeper activator slots. Or an option to expand the activator slot to include parts of the default slot as well.

**Comment by KaelWD** [comment] 2019-04-11 02:29
Duplicate of #1877

**Closed by KaelWD** 2019-04-11 02:29 UTC
