### ISSUE TITLE
[Bug Report] tabs inside v-dialog don't show initial tabs-slider

### ISSUE THREAD

**Issue by BennyAlex** [vuetifyjs/vuetify#4094] opened 2018-05-18 12:29 UTC
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.146
**OS:** Windows 7

### Steps to reproduce
When using tabs inside a dialog, the tabs-slider isn't visible first. When clicking another tab then he appears

### Expected Behavior
Slider is visible

### Actual Behavior
Slider isn't visible

### Reproduction Link
[https://codepen.io/Benny98/pen/YLdPQd?editors=1011](https://codepen.io/Benny98/pen/YLdPQd?editors=1011)

**Comment by KaelWD** [comment] 2018-05-18 12:36
Duplicate of #1978

**Closed by KaelWD** 2018-05-18 12:36 UTC
