### ISSUE TITLE
[Feature Request] Support for segmented keys / passwords in VOtpInput

### ISSUE THREAD

**Issue by Mosaab-Emam** [vuetifyjs/vuetify#15313] opened 2022-06-16 21:35 UTC
### Problem to solve
It adds support to keys / passwords that are segmented into two parts or more, for example:
`abcd-efg-1234`

### Proposed solution
Modifying the behavior of the `length` property in VOtpInput to support segmented values like
`<v-otp-input length="4-4-4" />`
Also adding a prop named `separated` that is a boolean. This prop will dictate whether the value of the otp input will contain dashes or not. For example the input value will be like `abcd-efg-1234` when `separated` prop is present, and like `abcdefg1234` when it is not.

**Comment by KaelWD** [comment] 2022-07-31 09:53
Duplicate of #14532

**Closed by KaelWD** 2022-07-31 09:53 UTC
Labels: S: triage
