### ISSUE TITLE
[Feature Request] Allow multiple snackbar & toasts

### ISSUE THREAD

**Issue by hoangnguyen291** [vuetifyjs/vuetify#3157] opened 2018-02-01 10:17 UTC
### New Functionality
It can allow me to toast multiple message to client, currently it only show one message

### Improvements
no idea

### Bugs or Edge Cases it Helps Avoid
no idea

**Comment by KaelWD** [comment] 2018-02-01 14:45
Duplicate of #2384

**Closed by KaelWD** 2018-02-01 14:45 UTC
