### ISSUE TITLE
[Bug Report] V-text-field height prop doesn't effect the height

### ISSUE THREAD

**Issue by Tyler-Maclachlan** [vuetifyjs/vuetify#9123] opened 2019-09-27 08:45 UTC
### Environment
**Vuetify Version:** 2.1.0-beta.1
**Vue Version:** 2.5.17
**Browsers:** Chrome 77.0.3865.90
**OS:** Linux x86_64

### Steps to reproduce
Create a `v-text-field` component with the `height` set to a different height than default.

### Expected Behavior
The `height` prop changes the height of the `v-text-field`

### Actual Behavior
Style is added for `height: height px` but the height doesn't change.

### Reproduction Link
<a href="https://codepen.io/tyler-maclachlan/pen/ZEzZMER" target="_blank">https://codepen.io/tyler-maclachlan/pen/ZEzZMER</a>

**Comment by KaelWD** [comment] 2019-12-06 06:56
Duplicate of #5216

**Closed by KaelWD** 2019-12-06 06:56 UTC
Labels: C: VTextField, triage
