### ISSUE TITLE
[Bug Report] Tab key in VDialog focuses outside the dialg (regression)

### ISSUE THREAD

**Issue by mshmelev** [vuetifyjs/vuetify#9627] opened 2019-11-08 15:02 UTC
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Windows 10

### Steps to reproduce
1. Have a page with multiple buttons and 1 dialog
2. Click on a button to show the dialog
3. Hit 'Tab' key multiple times

### Expected Behavior
Focus remains on the elements inside the dialog

### Actual Behavior
Focus goes outside the dialog on the overlayed part of the page.

### Reproduction Link
<a href="https://codepen.io/mshmelev/pen/RwwJKyo" target="_blank">https://codepen.io/mshmelev/pen/RwwJKyo</a>

### Other comments
This is a regression introduced by commit https://github.com/vuetifyjs/vuetify/commit/fa0a8936be2411f0739259c7762fec350bd9e082

If you remove that check for `e.target === document.activeElement` everything works as expected.

**Comment by KaelWD** [comment] 2019-11-08 15:07
Duplicate of #9144

**Closed by KaelWD** 2019-11-08 15:07 UTC
Labels: triage
