### ISSUE TITLE
[Bug Report][3.3.3] VImg layout is broken on Safari 14 and older

### ISSUE THREAD

**Issue by ffxsam** [vuetifyjs/vuetify#17654] opened 2023-06-19 22:19 UTC
### Environment
**Vuetify Version:** 3.3.3
**Last working version:** 3.2.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open repro link.

### Expected Behavior
Should see two cat images stacked on each other, with no empty space.

![image](https://github.com/vuetifyjs/vuetify/assets/12532733/0525d666-e8f1-4959-9eed-7ad2463866a2)

### Actual Behavior
Images are being shown at full height? Second image isn't even visible.

![image](https://github.com/vuetifyjs/vuetify/assets/12532733/6de30d70-0015-4b65-90cc-33b92b3e6321)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1kctu2zAQRX9lyo1bwCJbWGgA1SnSXf+giygLmRqnbPgCOVYTGP73DiWlERwECBBkJc3r3JnL66P4EaMcDigasSV00XaE31sPsB2qLsbxdwx08NQZj2lOcbI3A2jb5XzZil24b8X/0jhh3C3kpLn4myjmRimma7wzROilDk59rT+rL5u6FaCeqIqx76LRdDmipip1ZAJP1PLi4kXprTo/uWQmR7Zq4RSHWScTCTLSYTLMuBgSwRES7uEE+xQcrNjkVWkHYG4mcPkWLkvHx9VPtDbAr5Bs/2H1qQhMyBlPD3Z6E8kOwHFacBdSj6mBOt5DDtb0jOq/ldppBMxDYi2mbSrXRfknB88vPSLauZBb0TxCW8FblvjJT917HuvRmiFJj6R8dOqK21Q6eDIOqz64q43cyJrty7RMS8yu2qXwN2NiSCvWCxky+4dXSM2dS4U5Vdlul4vEM7RivQFTldCzR5hee9HZ2FLzrPTsstn4E/ttjb/LZ1brPNp8/bjkm04eYYV0UwRPazE2svL0vfkHvEVBWQ==)

**Comment by ffxsam** [comment] 2023-06-23 16:22
To add onto this, it seems like aspect ratio is also broken as of 3.3.0. All of these image related issues were nonexistent in 3.2.5.

**Comment by KaelWD** [comment] 2023-06-28 09:05
Duplicate of #17413

**Closed by KaelWD** 2023-06-28 09:05 UTC
Labels: S: triage
