### ISSUE TITLE
[Bug Report][3.1.5] v-slider does not detect append and prepend listeners

### ISSUE THREAD

**Issue by Flamenco** [vuetifyjs/vuetify#16714] opened 2023-02-19 16:35 UTC
### Environment
**Vuetify Version:** 3.1.5
**Last working version:** 2.6.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
The events for append and prepend icon are no longer emitted.

### Expected Behavior
event is emitted

### Actual Behavior
event is not emitted.  handler is not detected.  item is not click-enabled.

### Reproduction Link

[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUMtOAjEU/ZWmGyBhWg2yIUgw/oALd5RF6RSp9JW2gzGEf/e2HRIENXHX23PP457VET95Tw6dxDM8T9J4zZNcMIvQ/NBw78uzDIYri4TmMT4ybHgzZbgHCxy1amVAmm+khoVnrcQeve4ketFdZBiBlrRto4Szmd+qxldgKfLqrOIAOVu4gNCzOa3uNRYMNdecXuSFMYqgfEJRps4vEGJ221mRlLOolxyO0DFLcC1DGg7Kn2wHI2ZPWa3yQQuPsTLehQSunrxHZ6GcwmQ9ALlnVSv/QXt5ZniXko8zSjvr929EOEOXgNHQ2aSMbFpnlhMyIXcN137HyQNtVUyXMJHRNJvgPqIMYMzw+MIjqe3nbz49DPL3ZFpl+68seSNFQf8gQxOgchlk+DP+1e5PJ1yt3JyRraHjEzSrld3Hq1JFLIWuzgn/dZ9RlhSBzF5nk9MYf8sIroWH119uNfns)

<img width="684" alt="Screenshot 2023-02-19 at 11 21 03 AM" src="https://user-images.githubusercontent.com/819940/219961297-77c90069-18df-481a-aa45-64ff6b99e30f.png">

**Comment by KaelWD** [comment] 2023-06-07 04:33
Duplicate of #16071

**Closed by KaelWD** 2023-06-07 04:33 UTC
Labels: S: triage
