### ISSUE TITLE
[Feature Request] Sticky header for data table

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#3975] opened 2018-05-01 08:31 UTC
Problem to solve
For tables with a lot of rows it would be nice to have the header remain visible while the rows are scrolling to not lose track what which row is representing

Proposed solution
Allow the body of a data table to scroll while the header remain static.

**Comment by KaelWD** [comment] 2018-05-01 08:50
Duplicate of #1547

**Closed by KaelWD** 2018-05-01 08:50 UTC
