### ISSUE TITLE
[Bug Report][2.6.7] VAutocomplete with server side items at the bottom of the browser aligns wrong

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#15437] opened 2022-07-14 06:42 UTC
### Environment
**Vuetify Version:** 2.6.7
**Vue Version:** 2.6.14
**Browsers:** Chrome 103.0.0.0
**OS:** Windows 10

### Steps to reproduce
Use a serverside paginated autocomplete (not sure why) and make sure the input is near the bottom of the browser. Then search

### Expected Behavior
The results are always directly positioned above the select when there is no room beneath. Not on top of the input and not far away from the input

### Actual Behavior
![image](https://user-images.githubusercontent.com/1246691/178914999-acafa9bd-d3a0-4d4b-b161-c92059b55001.png)
![image](https://user-images.githubusercontent.com/1246691/178915364-1c4349db-17eb-401c-989f-f5b4341d8405.png)
And the video is the most clear:
https://user-images.githubusercontent.com/1246691/178917849-36c2ecf9-c519-4073-9d27-c5d1b7c01b66.mp4

### Reproduction Link
<a href="https://codepen.io/ricardovanlaarhoven/pen/RwMorWL?editors=101" target="_blank">https://codepen.io/ricardovanlaarhoven/pen/RwMorWL?editors=101</a>

### Other comments
The reproduction link does this sometimes (picture 1). You'd have to be patience. But for some reason my autocomplete with a real api request does this all of the time (picture 2). After it's at the top (picture 2) and you press backspace once, an api is called again and then it's aligned correctly, and then the new data comes in and it's still aligned correctly
![image](https://user-images.githubusercontent.com/1246691/178916042-ee268b12-78bb-4329-b529-4ff9836d5d7a.png)

**Comment by KaelWD** [comment] 2022-07-14 09:53
Duplicate of #10375

**Closed by KaelWD** 2022-07-14 09:53 UTC
Labels: S: triage
