### ISSUE TITLE
[Bug Report] Scrolling navigation-drawer with goTo fails silently

### ISSUE THREAD

**Issue by davidmw** [vuetifyjs/vuetify#3914] opened 2018-04-24 06:45 UTC
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.16
**Browsers:** Safari 11.1
**OS:** Mac OS 10.13.4

### Steps to reproduce
Toggle drawer with button. Scroll to bottom and tap last list item to trigger scroll attempt.

### Expected Behavior
Scroll to top

### Actual Behavior
Nop

### Reproduction Link
[https://codepen.io/davidmw/pen/YLqzGL](https://codepen.io/davidmw/pen/YLqzGL)

**Comment by KaelWD** [comment] 2018-04-24 06:55
Duplicate of #3510

**Closed by KaelWD** 2018-04-24 06:55 UTC
