### ISSUE TITLE
[Bug Report] Position of open menu in v-navigation-drawer (aside) changes when scrolling on main window

### ISSUE THREAD

**Issue by petersutter** [vuetifyjs/vuetify#2981] opened 2018-01-10 16:09 UTC
### Versions and Environment
**Vuetify:** 1.0.0-beta.2
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Mac OS 10.13.2

### Steps to reproduce
- Click on v-menu or v-select (in v-navigation-drawer)
- Without closing the menu, scroll on the right side (main window)

### Expected Behavior
The position of the opened selection / menu is relative to the corresponding component

### Actual Behavior
The opened selection / menu scrolls away with the content on the right side

### Reproduction Link
[https://codepen.io/psutter/pen/RxMgNb](https://codepen.io/psutter/pen/RxMgNb)

**Comment by KaelWD** [comment] 2018-01-10 16:21
Duplicate of #1551

**Closed by KaelWD** 2018-01-10 16:21 UTC
