### ISSUE TITLE
[Bug Report][3.0.0-beta.5] Autocomplete on firefox limited field space

### ISSUE THREAD

**Issue by MrPalixir** [vuetifyjs/vuetify#15477] opened 2022-07-20 12:51 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.37
**Browsers:** Chrome 103.0.5060.114
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open the reproduction link on firefox. Write a big sentence, the auto complete field limited the allowed space for writing text. 

### Expected Behavior
Use all the space allowed by the autocomplete field.

### Actual Behavior
The writing text is hide gradually we writing the text.

### Reproduction Link
<a href="https://codepen.io/mrpalixir/pen/RwMVarL?editors=101" target="_blank">https://codepen.io/mrpalixir/pen/RwMVarL?editors=101</a>

<img width="1708" alt="Capture d’écran 2022-07-20 à 21 02 46" src="https://user-images.githubusercontent.com/73360179/180061888-8d4f37cd-e7fc-4b7c-8853-dce7071816fc.png">

<!-- generated by vuetify-issue-helper. DO NOT REMOVE --

>

**Comment by KaelWD** [comment] 2022-08-09 09:11
Duplicate of #15317

**Closed by KaelWD** 2022-08-09 09:11 UTC
Labels: S: triage
