### ISSUE TITLE
[Bug Report][3.3.14] VDatePicker does not show max year in Year dropdown when setting max property

### ISSUE THREAD

**Issue by wambling** [vuetifyjs/vuetify#18132] opened 2023-08-24 06:58 UTC
### Environment
**Vuetify Version:** 3.3.14
**Vue Version:** 3.3.4
**Browsers:** Opera 101.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Set max property as today. Year drop down shows value only till 2022. Does not show 2023.

### Expected Behavior
After the fix for Bug [#18015](https://github.com/vuetifyjs/vuetify/issues/18015), when I set max property as today, though it correctly restricts all future dates, but when selecting a year, it only shows values till maxYear-1 i.e. till 2022. Ideally it should also give max year as option too because if I want to go back to max year, its not available and one has to click nextIcon all the way through.
Additionally keep getting this warning in browser.
```
Invalid prop: type check failed for prop "disabled". Expected Boolean | String, got Array 
 at <VDatePickerControlsviewMode="month"disabled=nextIcon="$next" ...>
 at <VSheetheight=undefinedmaxHeight=undefinedmaxWidth=undefined ...>
 at <VPickerlandscape=falsetitle="Select date"border=false ...>
 at <VDatePickermin="2000-01-01"max="new Date()">
 at <VContainer>
 at <VApp>
 at <App>
```

### Actual Behavior
It shows upto maxYear -1.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkMFuwjAMhl/FywWQaANjp6ogJu2wN9iBcCit2TKaNEpC2YT67nPaIhW4IE3qof7z+/9sb87s1Zi4PiJLWOpRmTLzuBIaIK2jzJj2ty3ySvtMarS91IoFuSMj8wNaUFIvBXuezWbRbE6fYJCo7Ic0jSd4I+d4Itgq5VdtFwCp14SgdAOkfDAYlS630nhw6I/dfFKZyno4g8U9NLC3lYIR7TQKdgDKdR6U+4RlcIxH71iWFXxUtiyeRpMA6CIpjE1ZlxapzMTfrtJ0mHNIEf2DEyyBVgkaUUIt2Jf3xiWc54WmtgJLWdtYo+faKL4mG7dH7aXCqKjUehEv4hdeSOeHcoxORTtbnRxaChFsOsB4uf99ANU7W8K8R/RaVGY7Fxh32ZyANdrIoi7Qon10pZu24Vo3T3erBXojdEMHL6U+uJtb56698+Yy5P92btNC1DYQmylrByV018G2f+cFAnA=)

**Comment by avarixe** [comment] 2023-08-24 17:03
duplicate of #18112

**Comment by wambling** [comment] 2023-08-25 05:53
Closing issue and will follow #18112

**Closed** 2023-08-25 05:53 UTC
Labels: S: triage
