### ISSUE TITLE
[Bug Report] clearable v-text-field, will not trigger v-menu  when clearable icon is hidden

### ISSUE THREAD

**Issue by nmarshall23** [vuetifyjs/vuetify#10611] opened 2020-02-18 21:24 UTC
### Environment
**Vuetify Version:** 2.2.13
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.106
**OS:** Mac OS 10.14.6

### Steps to reproduce
Select a date range.
Click on the clear button on v-text-field.
Click where the clear button was.
The menu will not open, click anywhere else in the v-text-field will open the menu.

### Expected Behavior
When the v-text-field clear button is not visible clicks to where it was should open the v-menu.

### Actual Behavior
The Clear button is capturing clicks even when not visible. 

### Reproduction Link
<a href="https://codepen.io/jkarczm/pen/MWYGrNB" target="_blank">https://codepen.io/jkarczm/pen/MWYGrNB</a>

**Comment by johnleider** [comment] 2021-07-14 17:13
Closing in as a duplicate of #10964 since there is more discussion on it.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-07-14 17:13 UTC
Labels: C: VInput, T: bug
