### ISSUE TITLE
[Bug Report] parent's grid-list style is applied to nested containers

### ISSUE THREAD

**Issue by nkovacs** [vuetifyjs/vuetify#3255] opened 2018-02-12 09:55 UTC
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.119
**OS:** Linux x86_64

### Steps to reproduce
1. Add grid-list-lg to the outer v-container
2. Add grid-list-md to the first inner v-container
3. Don't add any grid-list prop to the second inner v-container

### Expected Behavior
grid-list-md should apply to the v-flexes in the inner container in the first card.
The v-flexes in the second card should not have a padding.

### Actual Behavior
grid-list-lg applies to the v-flexes in the first card because it is later in the css and the specificity of the rules is the same.
The second card's v-flexes are affected by the grid-list-lg rule from the parent container.

### Reproduction Link
[https://codepen.io/anon/pen/qxmgjy](https://codepen.io/anon/pen/qxmgjy)

**Comment by KaelWD** [comment] 2018-02-12 10:23
Duplicate of #2204 and #3017

**Closed by KaelWD** 2018-02-12 10:23 UTC
