### ISSUE TITLE
[Bug Report] Pagination bug on stepper

### ISSUE THREAD

**Issue by Dev1lDragon** [vuetifyjs/vuetify#7210] opened 2019-05-14 16:42 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.8
**Browsers:** Chrome 74.0.3729.131
**OS:** Windows 10

### Steps to reproduce
use pagination on stepper

### Expected Behavior
when lenght is 1 expected (< 1 >)
when lenght is 2 expected (< 1 2 >)
when lenght is 3 expected (< 1 2 3 >)

### Actual Behavior
when lenght is 1 displaied (< 1 ... ... 1 >)
when lenght is 2 displaied (< 1 ... ... 2 >)
when lenght is 3 displaied (< 1 ... ... 3 >)

### Reproduction Link
<a href="https://codepen.io/dev1ldragon/pen/XwNwKd" target="_blank">https://codepen.io/dev1ldragon/pen/XwNwKd</a>

**Comment by Dev1lDragon** [comment] 2019-05-15 11:03
workaround for that bug set  property `total-visible="x"` when x is your number

**Comment by jacekkarczmarczyk** [comment] 2019-07-07 08:34
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2434

**Closed by jacekkarczmarczyk** 2019-07-07 08:34 UTC
Labels: triage
