### ISSUE TITLE
[Bug Report] v-edit-dialog `large` property has no effect

### ISSUE THREAD

**Issue by CameronRedmore** [vuetifyjs/vuetify#10468] opened 2020-02-05 15:36 UTC
### Environment
**Vuetify Version:** 2.2.9
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Edge 81.0.413.0
**OS:** Windows 10

### Steps to reproduce
Attempt to edit the "Iron" field which utilises a `v-edit-dialog` with the `large` property

### Expected Behavior
The dialogue appears with "Cancel" and "Save" buttons.

### Actual Behavior
The dialogue appears, but no buttons are present.

### Reproduction Link
<a href="https://codepen.io/Camzie99/pen/MWwgNEW?editable=true" target="_blank">https://codepen.io/Camzie99/pen/MWwgNEW?editable=true</a>

**Comment by KaelWD** [comment] 2020-02-09 03:51
Duplicate of #10522

**Closed by KaelWD** 2020-02-09 03:51 UTC
Labels: C: VEditDialog, S: has PR, T: bug, T: regression

**Comment by AuspeXeu** [comment] 2020-02-10 17:14
This is still not working in the latest version and it does not seem to me as a duplicate of #10522

**Comment by MajesticPotatoe** [comment] 2020-02-10 18:02
@AuspeXeu It is a duplicate of 10522, as it is a byproduct of the underlying issue outlined in #10522. it hasn't been fixed yet, but has an open PR. 

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
