### ISSUE TITLE
[Bug Report][2.6.11] #prepend-item in VAutoComplete causes incorrect highlighting

### ISSUE THREAD

**Issue by jonatan-mobal** [vuetifyjs/vuetify#15862] opened 2022-10-10 16:25 UTC
### Environment
**Vuetify Version:** 2.6.11
**Vue Version:** 2.7.10
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Open codepen
2. Click on autocomplete component
3. Click on 'c' item

### Expected Behavior
'c' is highlighted (gets v-list-item--highlighted class)

### Actual Behavior
'a' gets highlighted (gets v-list-item--highlighted class)

### Reproduction Link
<a href="https://codepen.io/jonatan-mobal/pen/XWqyVVy" target="_blank">https://codepen.io/jonatan-mobal/pen/XWqyVVy</a>

**Comment by KaelWD** [comment] 2022-10-11 02:22
Duplicate of #14489

**Closed by KaelWD** 2022-10-11 02:22 UTC
Labels: S: triage
