### ISSUE TITLE
[Bug Report][3.1.6] props doesn't contains any data in <template v-slot:headers="props"> in v-data-table.

### ISSUE THREAD

**Issue by DivakarSS** [vuetifyjs/vuetify#16771] opened 2023-02-24 11:30 UTC
### Environment
**Vuetify Version:** 3.1.6
**Vue Version:** 3.2.13
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a v-data-table and need to define a user defined headers using "tr" tags.

### Expected Behavior
I can able to get an props data, if I try to access the props inside the template tag.

### Actual Behavior
I try to access the props inside the template tag, but I can't get the props data. Because the props is empty here.
<img width="326" alt="ref2" src="https://user-images.githubusercontent.com/69146417/221168608-a2bcdb60-c15d-446d-be71-eb5e83e3f10e.PNG">

<img width="897" alt="ref" src="https://user-images.githubusercontent.com/69146417/221177312-6c9e263e-be3e-4b58-9ab0-ab3723e0f49d.PNG">

### Reproduction Link
[https://github.com/DivakarSS/VDataTable](https://github.com/DivakarSS/VDataTable)

**Comment by DivakarSS** [comment] 2023-03-23 06:48
Is there any update on this issue?
Because if we want to use the props inside the template tag for any component like input-value, indeterminate of v-checkbox, How to use it? The props data is empty there.  Is there any alternate options for this scenario?

**Comment by marr** [comment] 2023-04-19 16:22
bump

**Comment by KaelWD** [comment] 2023-09-25 13:38
Duplicate of #17148

**Closed by KaelWD** 2023-09-25 13:38 UTC
Labels: C: VDataTable, S: triage
