### ISSUE TITLE
[Bug Report] Temporary drawer undesired closing

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#3011] opened 2018-01-14 13:21 UTC
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.108
**OS:** Linux x86_64

### Steps to reproduce
- click toggle button
- activate date picker in nav drawer
- pick a date or click any button in dialog

### Expected Behavior
Navigation drawer remains open

### Actual Behavior
Navigation drawer closes on dialog interactions

### Reproduction Link
[https://codepen.io/anon/pen/MrBKYr](https://codepen.io/anon/pen/MrBKYr)

**Comment by KaelWD** [comment] 2018-01-14 13:34
Duplicate of #2147

**Closed by KaelWD** 2018-01-14 13:34 UTC
