### ISSUE TITLE
[Bug Report][3.3.2] Dialog close event

### ISSUE THREAD

**Issue by Ricky816845** [vuetifyjs/vuetify#17550] opened 2023-06-07 07:07 UTC
### Environment
**Vuetify Version:** 3.3.2
**Vue Version:** 3.3.4
**Browsers:** Edge 114.0.1823.37
**OS:** Windows 10

### Steps to reproduce
open a dialog,big area.
open a snack bar message up on  dialog area. 
click to close the snack bar.

### Expected Behavior
just close snack bar,and NOT close dialog.
dialog with no persistent attribute

### Actual Behavior
both dialog and snack bar closed.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVEtv2zAM/iuEThsQ28C2U5AW3eM4YIcd6x4UiUm16uFJtNuiyH8fJduJm3ZobyZF8nuI8vWT+Np19dCjWIsNoeusJLxsPcBGmwGUlSldtILwgSqFnjC2ohxzwVBpI23Yw1C5oNFy3ZhoBdwbTbeckD0FDne9tUlFRD81c/uMxu3JBlpLRWaQFCK3PUEXQ5fgcESbELfkQQVbirponIyPPJ7zxuuS4i7ugV8devgx0ts0pe+E3CyEHpNDpWTUz9FypsraF2mAnyGiA9Ol3oHOXCAZAumQVszNJ1SE1EeQ2nQmKeP3gNbwYULNDctRaPrE3kEmxHOMV0Yb3XuCnsDKLSMB0oiC4OTeS5DW/O1lvRwzGXOlrFF3bEPyUt19k/GCYo/ZjpDtKFnYyvjCkezJ62pnE/LlsLRnPvz3OrY2MNCRzbQlF7CTNjGd5QyAy+82JJzuaiK2rHiN5Dmb+WDeTA5H0NOqFvFZ+2lZZ5cWO/Y7OFz45DAlucfFjrxu8yTsUhUpYz/nn9uco5nF+MIafmL8dbaPG34ophsvAR94Lfj+cSd7S/A0TtKS5IePcwQQ87r5U8wVRf16dHx1ys+Mz08O48ehJDjYNEcSYiWs8Xep/pOC579EQWmFSvzO1nA9NrbilqhL66ZR2nMlG2yGWHukxneu4f8Lmd3j1ef6c/2JVSeaUxUvearLsDzppvUHBjT5NVDlZHeGOh4U5EltK3hSjt+gcMVlTeSXZRxWOrjC5cvIZZGuMblqG8N9wshDWjFZVGAy4XdAvaWWIV6MbhhvwFhF9Bpj/su+T9FZ21LV2dELZdNVH8RhJUobG18oi5t/snf2vw==)

**Comment by KaelWD** [comment] 2023-06-13 07:40
Duplicate of #7310

**Closed by KaelWD** 2023-06-13 07:40 UTC
Labels: S: triage

**Comment by CreeTar** [comment] 2025-02-04 17:13
> Duplicate of [#7310](https://github.com/vuetifyjs/vuetify/issues/7310)

Its not a duplicate. Bug #7310 is regarding Vuetify 1.5 and @johnleider closed it for that reason, saying a new bug for v3 should be created. Now this new bug was created, and it's closed as a duplicate of the bug, that specifically said to create this bug here :D we have a loop here :D

**Comment by KaelWD** [comment] 2025-02-05 02:04
#18384

This was closed first, I don't know why he closed #7310 after someone posted a v3 reproduction.
