### ISSUE TITLE
[Bug Report] v-col xs property not working

### ISSUE THREAD

**Issue by cenyG** [vuetifyjs/vuetify#9233] opened 2019-10-04 17:52 UTC
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Linux x86_64

### Steps to reproduce
I want to make my element to be size of 12 columns on `xs` display, I make:
`<v-col xs="12" sm="12" md="6" lg="6"> </v-col>`
And it's not working.

### Expected Behavior
Should work like:
`<v-col cols="12" sm="12" md="6" lg="6"> </v-col>`

### Actual Behavior
`xs` property not working for `v-col`

### Reproduction Link
<a href="https://codepen.io/cenyGG/pen/MWWWgMZ" target="_blank">https://codepen.io/cenyGG/pen/MWWWgMZ</a>

### Other comments
I think that both code examples should work properly.

**Comment by MajesticPotatoe** [comment] 2019-10-04 17:56
duplicate of #8997
`cols` is the replacement for `xs` in 2.0 grids

**Closed by MajesticPotatoe** 2019-10-04 17:56 UTC
Labels: triage

**Comment by peterkowalsky333** [comment] 2020-11-17 22:52
Then if i want to make my layout  on smallest devices ( < 600px ) to take the full width - each column to be 12 width of the container, how should i do that ?! If i want that for medium devices i would add md="12"

For example:

<v-col v-for="n in 4" :key="n" cols="3" md="12"

but if i add

<v-col v-for="n in 4" :key="n" cols="3" md="12" sm="12" xs="12"

md is working - i have 12 width of the columns
sm is working - i have 12 width of the columns
xs is not working ! i have four columns with 3 width. 
How  should make responsive layut when xs is not working ?

**Comment by Duchynko** [comment] 2020-12-20 11:39
@peterkowalsky333 just as mentioned above, the `xs` breakpoint was replaced by `col`. So if you want to make your columns occupy the whole width on small devices (< 600px), just replace `xs` with `col`.

```html
<v-col cols="12" md="6">Full width on a small device & half of the width on a medium device</v-col>
```
