### ISSUE TITLE
[Bug Report][2.3.10] text field label can't display icons anymore

### ISSUE THREAD

**Issue by inad9300** [vuetifyjs/vuetify#12229] opened 2020-09-15 07:30 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Firefox 80.0
**OS:** Mac OS 10.15

### Steps to reproduce
Go to https://vuetifyjs.com/en/components/text-fields/#label-slot and see.

### Expected Behavior
An icon should be rendered.

### Actual Behavior
An ellipsis is.

### Reproduction Link
<a href="http://codepen.io" target="_blank">http://codepen.io</a>

### Other comments
It is annoying to have the reproduction link be so restrictive.

**Comment by KaelWD** [comment] 2020-09-15 07:31
Looks like an icon to me
![image](https://user-images.githubusercontent.com/16421948/93179582-3590b180-f779-11ea-9c60-c63bdaa958af.png)

**Comment by inad9300** [comment] 2020-09-15 07:32
Maybe some of the items indicated in the environment section above don't match what you use...

<img width="874" alt="image" src="https://user-images.githubusercontent.com/3440331/93179686-5257c580-f736-11ea-821d-335900fca1d3.png">

**Comment by KaelWD** [comment] 2020-09-15 07:37
Firefox is applying `text-overflow: ellipsis` from `.v-label` to the child element even though neither are overflowing.

**Comment by KaelWD** [comment] 2021-07-28 17:22
I had another look and it seems to be caused by the `scale(1.3)` on `.v-icon::after`. v3 uses `font-size: 1.5em` instead, not sure if we should backport this to v2.

**Comment by KaelWD** [comment] 2021-08-04 14:40
This is fixed in v3, potential for breakage is too high so it probably won't be backported.

**Closed by KaelWD** 2021-08-04 14:40 UTC
Labels: C: VTextField, T: bug, platform specific, wontfix
