### ISSUE TITLE
[Feature Request] Keyboard selection does not yet work with select in 3.x beta's

### ISSUE THREAD

**Issue by rotsee** [vuetifyjs/vuetify#15927] opened 2022-10-18 21:00 UTC
### Problem to solve
Apologies if this is on the roadmap, but I could find it in the issue tracker.

In the Vuetify 3 beta versions `<v-select>` menu items can not yet be selected by keyboard (see code examples at https://next.vuetifyjs.com/en/components/selects/)

Minimal example:
```
<v-select
  :items="['California', 'Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming']"
></v-select>
```

### Proposed solution
Fix keyboard listener before releasing 3.0.0

**Comment by KaelWD** [comment] 2022-10-19 06:55
Duplicate of #15428

**Closed by KaelWD** 2022-10-19 06:55 UTC
Labels: S: triage
