### ISSUE TITLE
[Bug Report] v-menu inside of v-select does not respect current theme (does not switch to dark theme)

### ISSUE THREAD

**Issue by pteargryphon** [vuetifyjs/vuetify#7521] opened 2019-06-14 20:58 UTC
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Last working version:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169, Google Chrome, Mozilla Firefox, Safari
**OS:** Mac OS 10.14.5, Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
1. Use a v-select component.
2. Set the v-app theme to dark OR set the dark prop to true directly on the v-select component, the inner v-menu portion of the control will not swap to dark (dark prop on v-menu is null).

### Expected Behavior
The [inner] v-menu component of v-select should respect the dark theme mode.

### Actual Behavior
The [inner] v-menu component of v-select remains fixed to default/light theme.

### Reproduction Link
<a href="https://codepen.io/pteargryphon/pen/XLXMNy?editors=1010#0" target="_blank">https://codepen.io/pteargryphon/pen/XLXMNy?editors=1010#0</a>

**Comment by johnleider** [comment] 2019-07-18 19:44
Fixed in https://github.com/vuetifyjs/vuetify/commit/93aed3251d2825c95e7eb7dc88e7b01c116797b4

https://codepen.io/johnjleider/pen/gVOJyo?editors=1010#0

**Closed by johnleider** 2019-07-18 19:44 UTC
Labels: C: VSelect, T: bug, T: regression

**Comment by KaelWD** [comment] 2019-07-19 00:07
This was working as intended, v-app no longer affects `$vuetify.dark`
