### ISSUE TITLE
[Bug Report] Custom Preset can't override SASS varibles

### ISSUE THREAD

**Issue by jd-0001** [vuetifyjs/vuetify#13191] opened 2021-03-02 11:48 UTC
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.182
**OS:** Linux x86_64

### Steps to reproduce
1. yarn
2. yarn serve

### Expected Behavior
SASS variables defined in src/@core/custom-preset/preset/variables.scss shall override the vuetify variables and gives desired style

### Actual Behavior
SASS variables aren't overriding

### Reproduction Link
<a href="https://github.com/jd-0001/vuetify-custom-preset" target="_blank">https://github.com/jd-0001/vuetify-custom-preset</a>

### Other comments
Preset docs don't mention how can I develop and use it inside my project. There's only mention of how to install available presets. Also pre-made presets aren't working. Check this [issue](https://github.com/vuetifyjs/vuetify/issues/13188).

**Comment by MajesticPotatoe** [comment] 2021-03-02 13:44
duplicate of <https://github.com/vuetifyjs/vue-cli-plugins/issues/222>

**Closed by MajesticPotatoe** 2021-03-02 13:44 UTC
Labels: T: bug, duplicate
