### ISSUE TITLE
[Bug Report] Selection made outside boundaries of drawer closes menus

### ISSUE THREAD

**Issue by NickMBR** [vuetifyjs/vuetify#8388] opened 2019-08-08 10:44 UTC
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.4
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Open the drawer, then open the menu. Select the text inside the textbox and while still selecting, leave the mouse outside the menu and the navigation drawer boundaries, then release the mouse.

### Expected Behavior
Selection (mouseup) should not close the navigation drawer nor the menu

### Actual Behavior
Selection (mouseup) outside the boundaries of the menu and navigation drawer closes both menus.

### Reproduction Link
<a href="https://codepen.io/NickMBR/pen/RXMdQB" target="_blank">https://codepen.io/NickMBR/pen/RXMdQB</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-08 19:26
Possibly duplicate of https://github.com/vuetifyjs/vuetify/issues/6969, problem seems to be with ClickOutside directive, not with the component itself

**Comment by NickMBR** [comment] 2019-08-09 11:08
Also, #8055 mentions this issue on Dialog Components in v2, the workaround is possible on Dialogs via the @click:outside event, this event is missing on Navigation Drawer/Menus. Myabe it's possible to manipulate the stateless and close-on-click props, I'll make some tests.

**Comment by johnleider** [comment] 2019-08-12 20:57
Duplicate of #6969

**Closed by johnleider** 2019-08-12 20:57 UTC
Labels: triage
