### ISSUE TITLE
[Bug Report] Prefix / label misalignment in filled v-text-field

### ISSUE THREAD

**Issue by wolraich** [vuetifyjs/vuetify#13598] opened 2021-05-04 14:03 UTC
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 90.0.4430.93
**OS:** Mac OS 10.15.7

### Steps to reproduce
VTextField with filled, label and prefix props. Field value is blank, and the element does not have focus.

### Expected Behavior
Prefix and label are vertically centered and aligned

### Actual Behavior
Label is centered, prefix is below
<img width="290" alt="Screen Shot 2021-05-04 at 10 00 37 AM" src="https://user-images.githubusercontent.com/1703371/117015472-c6dc7600-acbf-11eb-89f2-694483f93762.png">

### Reproduction Link
<a href="https://codepen.io/wolraich/pen/qBrWrWN" target="_blank">https://codepen.io/wolraich/pen/qBrWrWN</a>

### Other comments
This works fine without the filled prop, when the field is not blank, or when the element has focus.

**Comment by johnleider** [comment] 2021-07-14 19:23
Duplicate of #7872 

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-07-14 19:23 UTC
Labels: C: VTextField, S: triage
