### ISSUE TITLE
[Feature Request] Radial menu

### ISSUE THREAD

**Issue by ruudboon** [vuetifyjs/vuetify#5842] opened 2018-12-07 21:34 UTC
Would it be possible to add a radial menu to the framework?
Currently I'm using this:  https://vuejsexamples.com/simple-radial-menu-for-vue2-apps/
but there is no ssr support and would love to see this as a default feature.

**Comment by jacekkarczmarczyk** [comment] 2018-12-07 23:54
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5231

**Closed by jacekkarczmarczyk** 2018-12-07 23:54 UTC
