### ISSUE TITLE
[Feature Request] Allow the usage of a fallback on VImg if the chosen image fails to load

### ISSUE THREAD

**Issue by phiter** [vuetifyjs/vuetify#10326] opened 2020-01-24 21:10 UTC
### Problem to solve
Currently when we have an `VImg` with a src of a image that may or not exist, we end up having to use a `@error` handler, add to an array of images that failed to load and in its place create another `VImg` with the placeholder (or fallback).

This is what we use:

https://codepen.io/phiter/pen/xxbBdEZ?editors=1010

### Proposed solution
The proposed solution is a prop called `fallback` which accepts a fallback image to load in place of a failed src.

Of course we should still have the `@error` event even if we have a fallback, but maybe we don't need to throw an error in the console like it happens today (could be a global config or another prop, like `omit-error`).

**Comment by jacekkarczmarczyk** [comment] 2020-03-22 03:05
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5876

**Closed by jacekkarczmarczyk** 2020-03-22 03:05 UTC
Labels: C: VImg, T: feature
