### ISSUE TITLE
[Bug Report][3.5.3] Datepicker : Invalid DateTime when using Luxon Adapter

### ISSUE THREAD

**Issue by MaximeSangoi** [vuetifyjs/vuetify#19222] opened 2024-02-13 15:52 UTC
### Environment
**Vuetify Version:** 3.5.3
**Last working version:** 3.5.1
**Vue Version:** 3.4.19
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Use Luxon Adapter in vuetify 3.5.1
2. Use vuetify 3.5.2 or more

### Expected Behavior
Button for choosing month should display the right date

### Actual Behavior
Button for choosing month is showing "Invalid Date"

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVMGO0zAQ/RXLl7aiiSkFIapu1QX2AEKAoOJCOGSTaevdxLZsJy2q+u+M7TSblN1Vb87Mm3lv3kz7+0CNzlhdgeXrv/GdoTPKSyW1JQeSaUgt/Ao5ciRrLUsyaLCDRCSigX6p9lJc56myoBvUMsfSiEtWuJwHw96DMymMJU0XctVnGR4SQYjdQgkzVJDDOq0Kuwrfg4JvtnZAjmMHcgSIcU9C0kA+IwJ2PTnDkQe7kuMoEXTs571WKkYFOOzcQqkKbLVwsHkdpUr5p/9ArTblAnQTwuB2sviI8DnDRxusIz+u4tk9OlBHpcyhuEqoiyZ0MWc9wKk/RvsELhL456yjCz9NprmyxICtgrx2SRrW3dV4pztpp3XFS2gxD/sgzSqcMtwDNhqe0LGQu+EI/ZqzwIycaJ01WLHmG7wTKdA8b35CM1kqXoD+pizHjglt15LQtCjk7rOPWV2BX4av2UJ2/0j8zuxdLKHfNRjQNdrX5myqN2BD+ubnV9jju02i5VWB6GeSP8DIonIaA+x9JXKU3cF5tZ+8d1xsVuZmb0GY01BO6OmYHBrt/vDM6A9yp/HU1+ENeh/DdqIyVWdOhkS/DbIEuVtrlZkxluUCy/DAeK1jAZYJVbIlwpiuhMXtRbksl9P4dTx5x3JubDcegymjWy13aC526cze/CIv4GqQSPEmngSGJhQV6a1xFP+1Zn6ZOtIgctDO9MtGOivrjXWWe3o0f/MXMHqcp5iyF9it06L9P8ukvmgfXfzyVTx5G798suel+voF/a6nA6PHMQ0m4aH5DdE//wDp4vg/)

### Other comments
In playground attached, switch vuetify version between 3.5.2 and 3.5.1 to see the problem.

**Comment by KaelWD** [comment] 2024-02-14 03:28
Duplicate of #19196

**Closed by KaelWD** 2024-02-14 03:28 UTC
Labels: S: triage
