### ISSUE TITLE
[Feature Request] How do I cancel a global or a component water ripple

### ISSUE THREAD

**Issue by jahnli** [vuetifyjs/vuetify#11823] opened 2020-07-09 07:24 UTC
### Problem to solve
I don't need water ripples on every component

### Proposed solution
Whether there is a global configuration or a separate corresponding configuration for a component

**Comment by KaelWD** [comment] 2020-07-09 08:25
Duplicate of #9677

**Closed by KaelWD** 2020-07-09 08:25 UTC
Labels: triage
