### ISSUE TITLE
[Bug Report][2.6.12] Dialogs: if to put 'open-on-hover' feature then endless pop-ups start

### ISSUE THREAD

**Issue by MayaElf** [vuetifyjs/vuetify#16067] opened 2022-11-10 18:57 UTC
### Environment
**Vuetify Version:** 2.6.12
**Vue Version:** 2.6.11
**Browsers:** Chrome 107.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. open Dialogs
2. put 'open-on-hover' feature

### Expected Behavior
1. dialog window opens on hover
2. we can work with this dialog window (e.g. push the buttons)

### Actual Behavior
1. endless pop-ups of dialog window start
2. sometimes these pop-ups stop but we still can't work with dialog window

### Reproduction Link
[https://codepen.io/MaiiaAfanaseva/pen/KKeWzWr?editors=101](https://codepen.io/MaiiaAfanaseva/pen/KKeWzWr?editors=101)

**Comment by KaelWD** [comment] 2022-11-12 04:56
Duplicate of #15738

**Closed by KaelWD** 2022-11-12 04:56 UTC
Labels: S: triage

**Comment by MayaElf** [comment] 2022-11-14 08:17
Thanks a lot :)
