### ISSUE TITLE
[Bug Report] Data table sort icon doesn't work with Font Awesome 5

### ISSUE THREAD

**Issue by Kakulukio** [vuetifyjs/vuetify#3548] opened 2018-03-12 13:45 UTC
### Versions and Environment
**Vuetify:** 1.0.6
**Vue:** 2.5.15
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows 7

### Steps to reproduce
1. Use font awesome icon in data table 'sort-icon' property
2. Click to the header

### Expected Behavior
The icons are only visible on hover or when the table is sorted.

### Actual Behavior
All icons are visible in the header and they do not rotate on click. (The table  is sorted, but there is no visual feedback on the icons.)

### Reproduction Link
[https://codepen.io/anon/pen/GxJeNd](https://codepen.io/anon/pen/GxJeNd)

### Other comments
Maybe the problem is that font awesome 5 uses svg tags instead icon tags and the css selectors did not match? (Just a guess.)

**Comment by jacekkarczmarczyk** [comment] 2018-03-12 13:59
Looks like a duplicate of https://github.com/vuetifyjs/vuetify/issues/3503

**Comment by KaelWD** [comment] 2018-03-12 14:13
yep, the selector is `.datatable thead th.column.sortable.active.desc i`

**Comment by PhilMDev** [comment] 2018-08-16 00:12
I tried the same thing but mine works.  However, the icon is positioned slightly below the header text but it does switch from up to down.  My problem is I used ml-2 to space it out a little from the text and that works perfectly on up.  However, when it switches to down it loses the spacing.

I tried to change the codepen that was connected to this bug report and even with the latest version of Vuetify I could find in the CDN list (1.1.12) it still didn't switch from up to down so I didn't see the loss of spacing either.

**Comment by PhilMDev** [comment] 2018-08-16 15:30
Further.  If you put the ml-x value in the initial Vue.use(Vuetify... setup under icons: { sort: fas fa-arrow-up ml-1 } it puts the spacing in both up and down as it should.  It's only if you specify it in the datatable component that the down spacing is ignored.

**Comment by KaelWD** [comment] 2018-10-18 03:08
We don't support the JS version of fontawesome, you should use the icon font instead: https://github.com/vuetifyjs/vuetify/issues/3505#issuecomment-371560727

**Closed by KaelWD** 2018-10-18 03:08 UTC
Labels: T: bug
