### ISSUE TITLE
[Bug Report][3.1.13] can't use theme colors in VLinearProgress with striped prop

### ISSUE THREAD

**Issue by DeepKumbhare85** [vuetifyjs/vuetify#17135] opened 2023-04-12 08:12 UTC
### Environment
**Vuetify Version:** 3.1.13
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1) Open the playground link given in the issue and open it.
2) You can check that the first progress bar with color prop success, doesn't work with striped but the second progress bar with color='light-green' works properly in striped mode. 

### Expected Behavior
The striped prop should also work with theme colors like success, primary, secondary, etc..

### Actual Behavior
The striped prop doesn't work with theme colors

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUT1PwzAQ/SuRlyy13SoTVYrKzsDE0nRwk6Mx+Eu2E4Sq/nfOaRAhZahg8929d+/e8+5EHpxjfQdkTcoI2ikR4b4yWVb2VDg3PIdCC2nGCuvnJ2+PHkJ4lAaEz1qQxzZuimUWopcOmkzbBhTthepgk6+WeVZbZf0mD11dIy/PvO1Mg8D7ks+2fcscJu+/S6oEpMgFc5Ps6JlPTKfiEkfJJzFVhiyI1M76iFjHXoM1mOQpUapxECqyzoZO6mHUqa5IG6MLa87rxiAND5e9ZwYiN07zLcK470yUGmhj9bZgBVtSoVwr2B1vZIjTMYOg6cHb9wAel1VkMZGL8uXjBskRiUortiouEmOPKnEISeNqN0fBHjz1gJl68Ldam9F+szeDXFlMV5wrc8YPUNK8hVn2dRhy330d+z/vw7a0ap8Uzwvy42A84cIk+09X3ht0)

**Comment by KaelWD** [comment] 2023-04-12 08:14
Duplicate of #17049

**Closed by KaelWD** 2023-04-12 08:14 UTC
Labels: S: triage
