### ISSUE TITLE
[Bug Report] v-label color and class props are ineffective

### ISSUE THREAD

**Issue by marreman** [vuetifyjs/vuetify#11583] opened 2020-06-09 13:17 UTC
### Environment
**Vuetify Version:** 2.2.33
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Mac OS 10.15.4

### Steps to reproduce
Add `color` prop with value `"error"` or a `class` prop with a known class name to a `v-label`.

### Expected Behavior
The v-label should have the error color (usually red) and have the supplied classes applied.

### Actual Behavior
The color does not change and the classes are not applied.

### Reproduction Link
<a href="https://codepen.io/marreman/pen/ZEQbZPa" target="_blank">https://codepen.io/marreman/pen/ZEQbZPa</a>

**Comment by jacekkarczmarczyk** [comment] 2020-06-09 13:18
Duplicate of https://github.com/vuetifyjs/vuetify/issues/11410

**Comment by Munhuggas** [comment] 2020-06-09 13:21
`v-label` is listed in the API-explorer on vuetifyjs.com with the attribute `color` available. How is this not a bug?

**Comment by jacekkarczmarczyk** [comment] 2020-06-09 13:24
`v-label` being listed in API-explorer is a bug in docs, it shouldn't be there
I'll reopen this issue as a docs issue

**Comment by marreman** [comment] 2020-06-09 13:25
Sorry for missing that duplication! Yeah I found it in the API-explorer. `v-messages` is in that explorer as well. Should that go as well then?

**Comment by jacekkarczmarczyk** [comment] 2020-06-09 13:26
Yup, https://github.com/vuetifyjs/vuetify/issues/9857

**Closed** 2020-06-09 13:55 UTC
Labels: T: documentation, duplicate
