### ISSUE TITLE
[Bug Report][3.0.1] VSelect/VAutocomplete/VCombobox - Missing header item handling

### ISSUE THREAD

**Issue by synapse** [vuetifyjs/vuetify#16102] opened 2022-11-16 12:56 UTC
### Environment
**Vuetify Version:** 3.0.1
**Vue Version:** 3.2.45
**Browsers:** Google Chrome
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Add one of the following components: `VSelect`/`VAutocomplete`/`VCombobox`
2. add a `header` or `divider` prop to any of the items

### Expected Behavior
To have a different design of the items marked as `header` or `divider`

### Actual Behavior
The items marked as `header`/`divider` look the same as the other items

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNUMFqhDAU/JVHLrbgul3bXsRdKIX+QI/rHlLzpA9iEuJTCuK/N9FVlxySybyZzOQ6ig/nsqFHUYiyqz05hg65d5fKUOusZxjBYwMTNN62kITRpDKVqa3pGIix7eAcJ56ulQEYGf+4gORTamqsNySTFEgVcJrSyD9MWG29VPbO5yn8olToC2DfYwqKBtrgKt7lX0FNanXP48DtuTLlcSkR4gcQ0jktGQMCKIeDdLFXtAmglWTuaMYdaqw56DguAC1/UJ8r8b3ci50p5tqBmvfILCYw/8eBiTUGNiZdZRs5SN1HktTueCmP6/NrvHCx5YtgSV4eHxqJKRWvWZ69vYt4eMlO4vYPvgaWeg==)

**Comment by jacekkarczmarczyk** [comment] 2022-11-20 21:19
Duplicate of https://github.com/vuetifyjs/vuetify/issues/15721

**Closed by jacekkarczmarczyk** 2022-11-20 21:19 UTC
Labels: S: triage
