### ISSUE TITLE
[Bug Report] v-menu with attach inside relative element has wrong position

### ISSUE THREAD

**Issue by dfreier** [vuetifyjs/vuetify#12092] opened 2020-08-21 06:55 UTC
### Environment
**Vuetify Version:** 2.3.9
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.125
**OS:** Mac OS 10.15.4

### Steps to reproduce
Inside a v-app create the following element hierarchy:
`div#container > v-card > v-menu`

- Use the attach prop: `<v-menu attach="#container">[...]</v-menu>`
- Give the card some position other than `x=0, y=0` to see the effect: `<v-card class="ma-16">`
- Click on the menu trigger

### Expected Behavior
Menu should be positioned at the trigger button (while respecting positioning, nudge and offset props)

### Actual Behavior
Menu appears somewhere else, but not next to the trigger button.

### Reproduction Link
<a href="https://codepen.io/dfreier/pen/abNBWaM" target="_blank">https://codepen.io/dfreier/pen/abNBWaM</a>

### Other comments
This happens not only with v-card. Any element in the DOM between v-menu and the attach-target element with `position: relative;` will cause that problem.

I've found the line in the source which is causing the problem:
https://github.com/vuetifyjs/vuetify/blob/c2734d3e7721ad794de84c89ce0486869580742c/packages/vuetify/src/mixins/menuable/index.ts#L140
When `attach === true`, it's okay to use the `dimensions.activator.offsetTop`, but in case `typeof attach === 'string'`, it should instead use `dimensions.activator.top`

**Comment by KaelWD** [comment] 2020-08-21 08:04
Duplicate of #7703

**Closed by KaelWD** 2020-08-21 08:04 UTC
Labels: triage
