### ISSUE TITLE
[Bug Report] the dialog have scroll after close inner dialog in fullscreen mode

### ISSUE THREAD

**Issue by wizardnet972** [vuetifyjs/vuetify#11459] opened 2020-05-22 06:28 UTC
### Environment
**Vuetify Version:** 2.2.29
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
The page have scroll (height of 4000px)
Click on Open Dialog 1
The dialog have no scroll.
Click on open dialog 2 - still no scroll.
close the dialog 2.
in dialog 1 have scroll and the events pass into the parent.

### Expected Behavior
dialog 1 not have scroll.

### Actual Behavior
dialog 1 have scroll and the events pass to the parents

### Reproduction Link
<a href="https://codepen.io/shlomilevi/pen/LYpqJLX?editors=1010" target="_blank">https://codepen.io/shlomilevi/pen/LYpqJLX?editors=1010</a>

I think its happens because dialog2 is remove `overflow-y-hidden` class from `html` element. - the class should remove if all the dialogs are close.

**Comment by wizardnet972** [comment] 2020-05-22 06:35
any solutions or workarounds for now will be welcome

**Comment by KaelWD** [comment] 2020-05-22 08:56
Duplicate of #5356

**Closed by KaelWD** 2020-05-22 08:56 UTC
Labels: triage
