### ISSUE TITLE
[Bug Report] Navigation drawer doesn't scroll on mini-variant

### ISSUE THREAD

**Issue by derpyerpy** [vuetifyjs/vuetify#4634] opened 2018-07-17 12:33 UTC
### Versions and Environment
**Vuetify:** 1.1.4
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.3

### Steps to reproduce
Add 'app' property to navigation drawer

### Expected Behavior
WHile we add a navigation drawer to the part of the layout by adding 'app' property to it, it should be scrollable.

### Actual Behavior
Doesn't scroll when we set 'app' property.

### Reproduction Link
[https://codepen.io/anon/pen/bjebBe?editors=1010](https://codepen.io/anon/pen/bjebBe?editors=1010)

**Comment by KaelWD** [comment] 2018-07-17 12:38
Duplicate of #3146

**Closed by KaelWD** 2018-07-17 12:38 UTC
