### ISSUE TITLE
[Bug Report] v-text-field solo styling

### ISSUE THREAD

**Issue by John0x** [vuetifyjs/vuetify#3237] opened 2018-02-09 11:35 UTC
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.140
**OS:** Windows 10

### Steps to reproduce
The v-text-field element does not adapt to the dark style if the "solo" attribute is used active.

### Expected Behavior
Adapt styling to dark colors

### Actual Behavior
Styling is still the light one

### Reproduction Link
[https://codepen.io/anon/pen/vdxYLg](https://codepen.io/anon/pen/vdxYLg)

**Comment by philwolstenholme** [comment] 2018-02-12 10:17
The background-color does not pick up the dark style, but the [text] color does - so the inputs are particularly unusable:

![screen shot 2018-02-12 at 10 18 01](https://user-images.githubusercontent.com/6339853/36092064-f6ebf690-0fdd-11e8-8a6d-60833e11bb83.png)

**Comment by philwolstenholme** [comment] 2018-02-12 10:39
@John0x Looks like this is fixed in `1.0.0-beta.6`

Here's a Codepen using the latest beta version: https://codepen.io/philw_/pen/OQmqqz

The 1.0 release is out tomorrow I believe so it might be a good time to switch?

**Comment by KaelWD** [comment] 2018-02-12 11:01
Duplicate of #2705

**Closed by KaelWD** 2018-02-12 11:01 UTC

**Comment by KaelWD** [comment] 2018-02-12 11:04
@John0x, you said you are using beta 6, but the codepen you provided is using 0.17.7
