### ISSUE TITLE
[Bug Report][3.3.5] VInfiniteScroll breaks if the side is still visible after loading

### ISSUE THREAD

**Issue by Starfox64** [vuetifyjs/vuetify#17704] opened 2023-06-27 15:21 UTC
### Environment
**Vuetify Version:** 3.3.5
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
Have a VInfiniteScroll component where the bottom of the list is still visible after items are loaded.
This can be either because of a long VInfiniteScroll or because too few items are loaded per "page".

### Expected Behavior
The VInfiniteScroll should continue loading more pages until the bottom is no longer visible or `done('empty')` is called.

### Actual Behavior
The VInfiniteScroll stops after the first page load

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU8tu2zAQ/JWFikIyqocdtxcjTpNjbjn0ZvnASGubNUUKJKXUMPTvXZJWIDs9BOhJ5u7szHCW3pyjp7bN+w6jVXRvsWkFs/hQSoD7PmNt63/6Q6WkZVyivpR8kcsdl9xiZiqthIBHoVi9LiP3KaN3JGFHbuizndIESWisSYHLGv/M6APubMoIVkc8Ud8dryiIpOY9rCrBjCHAJm5ZdhdfKOAr3MF6vYY5/IT4dZ/tNZ4ywfcHi5JgsII43t4QAjyTCnw5n706DMOVXEF60zsUVwGF0ocMxsSocx2Zq4REr4joSIO8tWDQdiFw3rRKWziDxh0MsNOqgZiWFDs4APEaG/KCtcMkm0UKdykst7OAYOYkK9h1srJcSWAtT2ZwDs40yWgJEt/ghYi5wUSjUaJHWD+MIHBufvEGVWcTmp12HIXHJ09as1Pu7CVnECj39rCCJQwpJMcUej/Ww7dgNe+Z6DBnNskWMyouZmQ28NHAYj6fX86D/9Iq/nET97BIq1YSCTd6Kgp4QU3vqoGnl2eomAj1EBS5pZjYG+M2JBGYQ1sJzIXauwje61O7bWcOSZ7n075TT2J1jEej90VYIS0vSqOwvaxhbf7bKEn/LG+TnrRv0BtfjcbLiLbqzmV0sLY1q6KoakljNQre61yiLWTbFI8EK3QnLW0kq1XzuMyX+Xd6n8ZOyzmaJnvV6s2gJpIySicylu9On5C6IL3Cj6BwKWWCvRon8YG6IL0edaaR/ooa9WdvdDM2vdVN68PNLskPlLfg8mhuoq6Mj3kzmvyvK3syx7R1gkMaeZ+k7Aei7V9FXa52)

### Other comments
This is because the `isIntersecting` value that is being watched by `VInfiniteScrollIntersect` does not go back to false so the `intersect` event is never called.

**Comment by KaelWD** [comment] 2023-06-28 08:39
Duplicate of #17358

**Closed by KaelWD** 2023-06-28 08:39 UTC
Labels: S: triage
