### ISSUE TITLE
[Bug Report] Months don't start from the first day (1) when using persian locale

### ISSUE THREAD

**Issue by CPHM** [vuetifyjs/vuetify#13182] opened 2021-02-28 20:54 UTC
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 88.0.4324.182
**OS:** Linux x86_64

### Steps to reproduce
When setting persian locale either through datepicker locale prop or global vuetify lang the datepicker sorts days and shows them in Gregorian order instead of Jalali, therefore you may get half of one month and half of the next month in the datepicker.
For example if you look at Esfand 1399, it starts at 11 of Esfand and includes the first 10 days of Farvardin that is because 11 Esfand 1399 is equal to 1st March 2021

### Expected Behavior
months start from 1 and go to 30/31

### Actual Behavior
months start from whichever Jalali day is equal to the first day of the current Gregorian month

### Reproduction Link
<a href="https://codepen.io/cphm/pen/GRNxxbd" target="_blank">https://codepen.io/cphm/pen/GRNxxbd</a>

### Other comments
If someone can actually give a hint about how I can fix this, I will work at it myself and submit a pull request if I manage to solve it.

**Comment by jacekkarczmarczyk** [comment] 2021-02-28 22:09
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1892

**Closed by jacekkarczmarczyk** 2021-02-28 22:09 UTC
Labels: triage
