### ISSUE TITLE
[Bug Report] Select dropdown scrolls in long dialogs

### ISSUE THREAD

**Issue by gmeral** [vuetifyjs/vuetify#9186] opened 2019-10-02 15:10 UTC
### Environment
**Vuetify Version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.0

### Steps to reproduce
1. Click on the select in the dialog
2. Hover the text.
3. Scroll Down.

### Expected Behavior
The select dropdown stays attached to the select.

### Actual Behavior
The select dropdown scrolls along with the dialog content.

### Reproduction Link
<a href="https://codepen.io/GuillaumeMeral/pen/yLBmjzX" target="_blank">https://codepen.io/GuillaumeMeral/pen/yLBmjzX</a>

### Other comments
Seems to be related to the fixed position of the parent dialog.

**Comment by KaelWD** [comment] 2019-10-03 07:48
Duplicate of #795

**Closed by KaelWD** 2019-10-03 07:48 UTC
Labels: triage

**Comment by gmeral** [comment] 2019-10-04 12:36
If anyone stumbles upon this, i simply used the `attach` props of v-select (which is propagated to the underlying v-menu) to solve the problem.
I also edited my codepen to demonstrate the difference between attach and no attach.
