### ISSUE TITLE
[Bug Report] In v-date-picker component, Year showing in header is not correct and one year greater than year showing in title.

### ISSUE THREAD

**Issue by momtazmohammad** [vuetifyjs/vuetify#13011] opened 2021-01-26 08:13 UTC
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 3.0.5
**Browsers:** Chrome 87.0.4280.141
**OS:** Windows 10

### Steps to reproduce
In v-date-picker component when date is not between first of January, till end of march In "fa-IR" locale, Year showing in header is not correct and one year greater than year showing in title.

### Expected Behavior
showing 1381 in header of v-date-picker component

### Actual Behavior
should show 1380 as same as year showing in title of v-date-picker

### Reproduction Link
<a href="https://codepen.io/momtaz/pen/GRjVJRq?editors=1010" target="_blank">https://codepen.io/momtaz/pen/GRjVJRq?editors=1010</a>

### Other comments
Another problem is, in Persian calendar month not start in the first day of Persian month , more detail in following link
https://stackoverflow.com/questions/61692409/vuetify-v-date-picker-not-start-by-first-day-of-month-in-persian-locale

**Comment by jacekkarczmarczyk** [comment] 2021-01-26 10:38
Duplicate of https://github.com/vuetifyjs/vuetify/issues/11578

**Closed by jacekkarczmarczyk** 2021-01-26 10:38 UTC
Labels: triage
