### ISSUE TITLE
Bug in Text Field using @keyup.enter.native

### ISSUE THREAD

**Issue by TheGinJiCode** [vuetifyjs/vuetify#1988] opened 2017-10-03 03:44 UTC
### Versions
Vuetify 0.15.7
Vue 2.4.2

### What is expected ?
Text field should be emptied when pressing key enter just like when clicking the button to empty the text field

### What is actually happening ?
Text field is not emptied, but the value in the data is emptied.

### Reproduction Link
https://codepen.io/TheGinJiCode/pen/YQgdwB

**Comment by KaelWD** [comment] 2017-10-03 05:30
Duplicate of#1726

**Closed by KaelWD** 2017-10-03 05:30 UTC
