### ISSUE TITLE
[Bug Report] v-tooltip causes unexpected layout in justify-space-around

### ISSUE THREAD

**Issue by picoeric** [vuetifyjs/vuetify#8581] opened 2019-08-17 00:12 UTC
### Environment
**Vuetify Version:** 2.0.7
**Last working version:** 1.5.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. create a card with v-card-actions
2. use v-layout with justify-space-around within v-card-actions
3. make single v-icon with v-tooltip within v-layout

### Expected Behavior
Icon should be centered horizontally in the card.  If you remove the v-tooltip, it will be. (without v-tooltip: https://codepen.io/exyzzy/pen/vYBKyKo?editors=1010)

### Actual Behavior
Icon is left of center

### Reproduction Link
<a href="https://codepen.io/exyzzy/pen/LYPZbZq?editors=1010" target="_blank">https://codepen.io/exyzzy/pen/LYPZbZq?editors=1010</a>

### Other comments
justify-center does work correctly with a single icon and tooltip in v2.

**Comment by jacekkarczmarczyk** [comment] 2019-08-17 11:34
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6951

**Closed by jacekkarczmarczyk** 2019-08-17 11:34 UTC
Labels: triage
