### ISSUE TITLE
[Feature Request] How import Vuetify as native browser module?

### ISSUE THREAD

**Issue by cawa-93** [vuetifyjs/vuetify#7315] opened 2019-05-28 13:23 UTC
### Problem to solve
I work on simple browser extension. I don't use webpack or any other build tool. I use native browser import for Vue. And how i can import Vuetify the same way? Maybe exist `vuetify.browser.esm.js`?

**Comment by jloewe** [comment] 2019-05-29 05:48
Have a look at this: https://vuetifyjs.com/en/getting-started/quick-start#cdn-install

**Comment by KaelWD** [comment] 2019-05-29 06:27
Duplicate of #5736

**Closed by KaelWD** 2019-05-29 06:27 UTC
Labels: triage
