### ISSUE TITLE
[Feature Request] In v-data-table prevent specific rows from being selected

### ISSUE THREAD

**Issue by SuperDJ** [vuetifyjs/vuetify#11503] opened 2020-05-27 15:04 UTC
### Problem to solve
When adding the `show-select` prop to the `v-data-table` component all rows are automatically selectable. However there are some rows that shouldn't be selectable because a certain condition hasn't been met. For example I would like to email a bunch of users but some haven't validated their email. Now I want all users to be selectable except for those that haven't validated their email.

### Proposed solution
Can think of a few solutions. Adding a key something like `selectable: boolean` in the `items` prop. But this could cause a problem if the items come from an API. 

A other solution would be to have something in the `item.data-table-select` slot. I could think of a disabled checkbox which would prevent selecting it in the first place. But I can image that if a row isn't selectable you don't even want to show a checkbox. So in that case if the isn't a checkbox it can't be selected.

**Comment by jacekkarczmarczyk** [comment] 2020-06-11 10:59
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8915

**Closed by jacekkarczmarczyk** 2020-06-11 10:59 UTC
Labels: triage
