### ISSUE TITLE
[Bug Report] Page unresponsive when viewing mobile data table on statically generated site

### ISSUE THREAD

**Issue by jacothom** [vuetifyjs/vuetify#11139] opened 2020-04-16 13:33 UTC
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Windows 10

### Steps to reproduce
Reproduction repo was created using nuxt-create-app and adding a vuetify plugin.

```bash
# install dependencies
$ npm install

# generate static site
$ npm run generate

# serve static site
$ npx serve dist
```

Open website now running on http://localhost:5000/ in Chrome. 

* Open Chrome DevTools
* Show device toolbar, and select iPhone 6/7/8.
* Refresh the page.

A data table will render, but the page will be unresponsive. 
![Rendered data table](https://user-images.githubusercontent.com/35601699/79462326-546dfa80-7fc5-11ea-8a76-8911e3cbdf9b.png)

The console will show the following errors
![Console errors](https://user-images.githubusercontent.com/35601699/79462278-415b2a80-7fc5-11ea-9280-1fb5e6715e03.png)

TypeError: Cannot read property '_transitionClasses' of undefined

DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### Expected Behavior
Mobile data table component renders correctly and is interactive on static websites. 

### Actual Behavior
Mobile data table component throws the following error and page becomes unresponsive

TypeError: Cannot read property '_transitionClasses' of undefined

### Reproduction Link
<a href="https://github.com/jacothom/vuetify-datatable-transitionClasses-issue" target="_blank">https://github.com/jacothom/vuetify-datatable-transitionClasses-issue</a>

### Other comments
I am only able to recreate the issue using a static site generator (Nuxt) and viewing the page on a mobile form-factor. I have not been able to recreate the issue when viewing the same page on a desktop or when running the site in development mode using `npm run dev`

**Comment by MajesticPotatoe** [comment] 2020-04-16 13:49
Have you tried doing this with the [@nuxtjs/vuetify module](https://github.com/nuxt-community/vuetify-module) ?

**Comment by jacothom** [comment] 2020-04-16 14:09
Yes, I saw the same issue using the @nuxtjs/vuetify module. If it would be helpful I can create another reproduction repo using @nuxtjs/vuetify instead of using vuetify as a plugin.

**Comment by jacothom** [comment] 2020-04-17 03:55
Pushed [branch nuxt-vuetify-module-repro](nuxt-vuetify-module-repro) to the reproduction repo to demonstrate the same issue using the @nuxtjs/vuetify module.

**Comment by KaelWD** [comment] 2020-10-08 17:46
Duplicate of #7410

**Closed by KaelWD** 2020-10-08 17:46 UTC
Labels: triage
