### ISSUE TITLE
v-menu does not close easily when opened by hover

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#1048] opened 2017-07-19 05:37 UTC
### Steps to reproduce
Hover over menu dots

### Versions
Vuetify 0.14.1

### What is expected ?
Hovering over dots will open menu, this happens
Moving mouse away should close menu (maybe after a delay)
Or clicking outside open menu should close menu

### What is actually happening ?
Menu doesnt close at all unless you hover a menu item

### Reproduction Link
https://codepen.io/anon/pen/gRNMZe

You can also reproduce it on the demo pages https://vuetifyjs.com/components/menus
There you have to hover the top few pixels of the HOVER button to have the same effect, but it's alot harder to achieve there

**Comment by nekosaur** [comment] 2017-07-19 09:54
This seems to have been fixed by #1052

**Comment by nekosaur** [comment] 2017-07-19 17:05
Please leave a comment if the issue is not solved by upgrading to 0.14.5

**Comment by Christilut** [comment] 2017-07-19 17:48
It's not quite fixed in 0.14.5 but happens alot less.

In the above codepen it can still do done, just hover the top few pixels of the dots while making sure your mouse does not go above the popup menu.
Seems that if the mouse goes over the popup menu, it will close properly.

**Comment by nekosaur** [comment] 2017-07-19 17:50
Ah. I'll take another look

**Comment by Christilut** [comment] 2017-08-07 18:21
Any news on this? Since issue is closed I thought I'd ask.

This bug happens very easily if a user quickly hovers over the 3 dots. It seems that if the v-menu is open after the mouse is already gone, it won't close.

**Comment by nekosaur** [comment] 2017-08-07 19:19
I'll reopen so as not to forget

**Closed** 2017-08-10 03:01 UTC
Labels: bug
