### ISSUE TITLE
[Bug Report] Vertical tabs first row is indented in responsive mode

### ISSUE THREAD

**Issue by nicmar** [vuetifyjs/vuetify#8628] opened 2019-08-20 11:13 UTC
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.4

### Steps to reproduce
This codepen is straight from the tabs page:
Visit https://vuetifyjs.com/en/components/tabs#tabs 

Visit page in a browser that is so small to the left menu hides, about 1200 px. 

### Expected Behavior
All tabs aligned 

### Actual Behavior
First tab is indented incorrectly

### Reproduction Link
<a href="https://codepen.io/nicmar/pen/pozExBW" target="_blank">https://codepen.io/nicmar/pen/pozExBW</a>

<img width="506" alt="Skärmavbild 2019-08-20 kl  13 08 40" src="https://user-images.githubusercontent.com/3955579/63342497-eeed3f80-c34b-11e9-8b84-5296a7255c71.png">

**Comment by jacekkarczmarczyk** [comment] 2019-08-20 11:15
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8294

**Closed** 2019-08-20 17:01 UTC
Labels: C: VTabs, duplicate
