### ISSUE TITLE
[Bug Report][3.1.6] `VAutocomplete` item-disabled

### ISSUE THREAD

**Issue by ElYaiko** [vuetifyjs/vuetify#16755] opened 2023-02-22 22:46 UTC
### Environment
**Vuetify Version:** 3.1.6
**Last working version:** 2.6.14
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
`itemDisabled` prop is not working

### Expected Behavior
To disable the option

### Actual Behavior
Is not being disabled

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUstu2zAQ/JUtL0oAi6rjogfBDhKgh35AkR4sHxSRTtjwBZJSURj69+5Scus4dYBKB2lnR7M7Q20P7N57PvSS1WydpPG6TfK2sQDroWy9z6+5MK2yc4X1w32fXOeQL5M8omdXrVAwbhqWnw27QKPuN5W0JKZ4l/bQ6p5ow0VWnvlFxfZRS0GCsLkFMddc2U73QsYrxZW4JpEm0V0dbVYnPqmYElhXJ8lgGbugfIIoU09tZbwLCQ4Q5B5G2AdnoMBICyJ3zsYEJj7BhvpXxVeptYPvLmjxobg+EnJEM2VL0w+gRA3LBQw1FMsCxsVf9GZCb16jqwldIdrY3R/lo3kU3y53ZGZaHxdnCzbtjqY9/xGdxb/gQIoYXG7gqdWQEcLQE9UNe07Jx7qqeutfnjj+BtUd9qrQ26SMLIUzdyu+4h/LVvvnln+qcIl02uYymvIxuJ9RBhzcsOxjnpHU/telOXMb5Zf88yQ7QyT5RqpC/UGGMkgrZJDh3fXPuP+ycEZ5Y4NGY/ojJquVfYlnoXYxB5oPmOr/8meU5VmAvsaDHNm4YK92xKn5O7b7DQYANGw=)

### Other comments
I see this prop is not implemented in V3 yet, and it's a very necessary one, I hope it gets implemented,
Thanks!.

**Comment by KaelWD** [comment] 2023-02-23 08:37
Duplicate of #15933

**Closed by KaelWD** 2023-02-23 08:37 UTC
Labels: duplicate, S: triage
