### ISSUE TITLE
[Feature Request] Restore 'position-x' and 'position-y' for v-menu

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#16810] opened 2023-03-01 18:42 UTC
### Problem to solve
Vuetify 3 no longer has the position-x/y props on the v-menu component.  Please bring these props back.

For my use case, let's say I have a table of 10 rows and 10 columns.  Each row has a button in it. When the button is pressed the one instance of the menu that I have should appear at the location of that button.  

Example:

```
<div>
  <v-container>
     <v-row v-for="x in 10" :key="`row_${x}`">
       <v-col v-for="y in 10" :key="`col_${y}`">
          <v-btn @click="showTheMenu($event, `${x}_${y}`)" :id="`${x}_${y}`"/>
       </v-col>
     </row>
  </v-container>
  <v-menu v-model="menu" :position-x="xPos" :position-y="yPos" 
    absolute offset-y :activator="activator">
    <v-list>
      <v-list-item>Some Menu Choice</v-list-item>
    </v-list>
  </v-menu>
</div>

const menu: Ref<boolean> = ref(false);
const xPos: Ref<number> = ref(0);
const yPos: Ref<number> = ref(0);
const activator: Ref<string> = ref('');

function showTheMenu(e:any, actId: string) {
    xPos.value = e.clientX;
    yPos.value = e.clientY;
    menu.value = true;
    // Also tried the following, but I get the error (DOMException: Failed to execute 'querySelector' 
    // on 'Document': '#2_4' is not a valid selector) even though I see that id using a dom inspector
    activator.value = `#${actId}`;
}

```

### Proposed solution
The idea shown above used to work great in Vuetify v2 (using position-x/y) but I cannot find an equivalent way to do this for Vuetify v3 (I tried activator)

**Comment by KaelWD** [comment] 2023-03-02 08:02
Duplicate of #15658

> '#2_4' is not a valid selector

IDs have to begin with a letter

**Closed by KaelWD** 2023-03-02 08:02 UTC
Labels: S: triage
