### ISSUE TITLE
[Feature Request] Keep items and item.raw types in sync in VDataTable

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vuetifyjs/vuetify#17778] opened 2023-07-11 02:32 UTC
### Problem to solve
I have this:
```ts
defineComponent({
  setup() {
    return () => (
      <VDataTable
        items={[{ name: "John" }, { name: "Bob" }]}
        onClick:row={(_event, { item }) => {
          console.log(item.raw);
        }}
      />
    );
  },
});
```

Right now TS thinks that `item.raw` is `any`: 
![image](https://github.com/vuetifyjs/vuetify/assets/7756211/b9a2b036-770f-471b-ae34-a8cf85a6185b)

I want TS to understand that `item.raw` has type `{name: string}` as inferred from `items` prop.

### Proposed solution
![image](https://github.com/vuetifyjs/vuetify/assets/7756211/5ff98767-c692-48ec-af9a-9cae09091c64)

Here's a patch for v3.3.2 that works for me:

```patch
diff --git a/node_modules/vuetify/lib/labs/VDataTable/index.d.mts b/node_modules/vuetify/lib/labs/VDataTable/index.d.mts
index 74ee690..c8be348 100644
--- a/node_modules/vuetify/lib/labs/VDataTable/index.d.mts
+++ b/node_modules/vuetify/lib/labs/VDataTable/index.d.mts
 declare const VDataTable: {
-    new (...args: any[]): {
+    new <T>(...args: any[]): {
         $: vue.ComponentInternalInstance;
         $data: {};
         $props: {
@@ -760,10 +778,10 @@ declare const VDataTable: {
             }) => vue.VNodeChild) | undefined;
             [x: `v-slot:item.${string}`]: false | ((arg: {
                 index: number;
-                item: DataTableItem<any>;
+                item: DataTableItem<T>;
                 columns: InternalDataTableHeader[];
-                isExpanded: (item: DataTableItem<any>) => boolean;
-                toggleExpand: (item: DataTableItem<any>) => void;
+                isExpanded: (item: DataTableItem<T>) => boolean;
+                toggleExpand: (item: DataTableItem<T>) => void;
                 isSelected: (items: SelectableItem | SelectableItem[]) => boolean;
                 toggleSelect: (item: SelectableItem) => void;
             }) => vue.VNodeChild) | undefined;
@@ -778,7 +796,7 @@ declare const VDataTable: {
             itemsPerPageText?: string | undefined;
             sortBy?: readonly SortItem[] | undefined;
             pageText?: string | undefined;
-            items?: any[] | undefined;
+            items?: T[] | undefined;
             density?: Density | undefined;
             modelValue?: readonly any[] | undefined;
             selectStrategy?: "all" | "page" | "single" | undefined;
```
Etc. Search for `DataTableItem<any>` and replace with `DataTableItem<T>`

**Comment by KaelWD** [comment] 2023-08-21 07:06
Duplicate of #17379

**Closed by KaelWD** 2023-08-21 07:06 UTC
Labels: S: triage
