### ISSUE TITLE
[Bug Report][3.0.7] VAutoComplete lazy load items

### ISSUE THREAD

**Issue by yeya** [vuetifyjs/vuetify#16377] opened 2023-01-05 16:00 UTC
### Environment
**Vuetify Version:** 3.0.7
**Last working version:** 2.6.12
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add a VAutoComplete component with more than 20 items and click to open the list

### Expected Behavior
The list should open fast like it used to in version 2, the list get bigger only when scrolling down

### Actual Behavior
It takes 2-4 seconds for the list to open, the location of the list is all over the page

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtU81u4yAQfpURl9hSbKLuVitZ6ap9ib3UPRB7smWDAQFONqry7h1jnKRJ2lN9MMx8H8M3Pzy/sW2PQa735T/PKiY7a1yAWXJyH/YK/azWCXiDxqEI+GfE4QBrZ7ojn4i1xv+R2hjtAyQAHj4ezPJaszl7srYkBl28DNhZRYTftQZYbgthbdxGoxNSJ2sE+2AaQwcwIEz+09coFE6sFF5DSqxQPdRsJ8Or6QN0pkUFBeyM2/iaXR+oJCnzdCKutxj8qCzp5WeCB2NMZcnPUiTTN07aAB5DP8ADYXQN3OMOIJWzxbXoFXVgvKQVQWT5ZAE4CuP0yQaIeit4ck7sy6FLWdxm94tFXm5w77M8n5/oHhU2AdsKZrMb7rsKek0apMZ2Qg/jJi70O9NPrR0HhgphabKMphZHbVTHCFAlq0ltPczgYNfsNQTrK857bTd/S2oxfySMu14H2WHRmu7xR3lX/rznrfTh3F+i74qVMzuPjm6sWUoiBh9G7rMLEkxxF+WvMez0JCjkzVDpWXxTRE6Kt+gKh1Rgh+7LSlxwP1TjAruqSOrTgbqjpN74i8Y0Pmb0/DJQDnM2hiZyzIO9vAN2Ulae)

### Other comments
Looks like vuetify 2 has this lazy load of items that works perfect.
Check this: https://codepen.io/yeya/pen/OJwbNVJ

**Comment by jaysonpotter** [comment] 2023-01-06 21:32
Reported the same performance issue at https://github.com/vuetifyjs/vuetify/issues/16220

**Comment by djeikyb** [comment] 2023-04-19 04:55
Same bad performance with 3.1.12

**Comment by johnleider** [comment] 2023-04-29 19:33
duplicate of #16318
related #2660

**Closed by johnleider** 2023-04-29 19:33 UTC
Labels: duplicate
