### ISSUE TITLE
[Feature Request] Select not preloading all items

### ISSUE THREAD

**Issue by dhcmega** [vuetifyjs/vuetify#16450] opened 2023-01-16 15:25 UTC
### Problem to solve
It's very annoying that the scrollbar reaches the bottom and then moves up and you have to scroll it again when there are many items.

### Proposed solution
Create a prop to force some kind of eager loader that will load all the items into the dropdown list so the scroll will not resize or move upwards.

**Comment by KaelWD** [comment] 2023-01-17 07:45
Duplicate of #2660

**Closed by KaelWD** 2023-01-17 07:45 UTC
Labels: S: triage
