### ISSUE TITLE
[Bug Report] v-tabs slider disappears for nested routes or route with query when optional

### ISSUE THREAD

**Issue by simonbrunel** [vuetifyjs/vuetify#12265] opened 2020-09-21 17:32 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.102
**OS:** Windows 10

### Steps to reproduce
Route with query:
- Click "Go to /bar"
- Click "Go to /bar?q=42"

Nested route:
- Click "Go to /bar/42"
- Click "Go to /bar"

### Expected Behavior
Optional `v-tabs` should ignore the query params and only consider the route path when matching tab items (e.g. `/bar` should match `/bar?q=42`). Additionally, when `v-tab` are not `exact`, the slider should remain when a tab matches the current route as prefix (e.g. `/bar` should match `/bar/42` when `exact: false`).

### Actual Behavior
In both cases, the tabs slider disappears by alternance when navigating between routes starting by `/bar`.

### Reproduction Link
<a href="https://codepen.io/simonbrunel/pen/mdPQBbV" target="_blank">https://codepen.io/simonbrunel/pen/mdPQBbV</a>

**Comment by econic** [comment] 2020-09-25 12:33
Can confirm, we have the same problem here.
Though for us this behaviour is not deterministic: when you randomly switch between subroutes, the slider incorrectly disappears with a ~33% chance.

**Comment by simonbrunel** [comment] 2020-09-25 13:04
If the route `path` (which doesn't include the query `?...` part) stays the same between route changes (e.g. `/bar?q=0` > `/bar?q=42` > `/bar`), the slider disappears and reappears alternatively. This is because of [this check](https://github.com/vuetifyjs/vuetify/blob/020e2e10bd47f0eae996dc471647cf84aef4b58e/packages/vuetify/src/components/VTabs/VTabsBar.ts#L80), where I believe the `else` should be removed. Though, this method should probably return early if `newPath === oldPath` to avoid iterating all items.

For nested routes, `item.to` should be compared using `startsWith` if `!item.exact`, at [these lines](https://github.com/vuetifyjs/vuetify/blob/020e2e10bd47f0eae996dc471647cf84aef4b58e/packages/vuetify/src/components/VTabs/VTabsBar.ts#L79-L80).

**Comment by simonbrunel** [comment] 2020-09-29 14:15
@econic As a workaround, you can explicitly compute the `v-tabs` value: it needs to be the route *full* path but with a trailing `/` added to the route path:

```html
<template>
  <v-tabs :value="value" optional>
    <v-tab v-for="(item, index) in items"  :key="index" :to="item.to" :exact="item.exact">
      {{ item.text }}
    </v-tab>
  </v-tabs>
</template>
```

```ts
  computed: {
    value() {
      const path = this.$route.path;
      const full = this.$route.fullPath;
      return path[path.length - 1] !== '/' ?
        `${path}/${full.substring(path.length)}` :
        full;
    },
  }
```

Codepen: https://codepen.io/simonbrunel/pen/eYZapLP

**Comment by mschoeffmann** [comment] 2021-01-04 11:55
I can confirm this also without query strings.
Navigating from `/entries` to `/entries/1234` back to `/entries` results in a disappeared slider.
`v-tabs` has `optional` set, and the `v-tab` has `nuxt link` set but not `exact`.

**Comment by larzon83** [comment] 2021-08-02 13:53
I have the same problem

**Comment by emptyhere** [comment] 2022-02-22 11:39
Same

**Comment by dom-velloso** [comment] 2022-07-04 18:20
Same here.

**Comment by KaelWD** [comment] 2022-09-15 13:09
Duplicate of #14156

**Closed by KaelWD** 2022-09-15 13:09 UTC
Labels: T: bug, C: VTabs, has workaround
