### ISSUE TITLE
[Bug Report][3.3.0] Cannot find module 'vuetify/lib/util/colors' or its corresponding type declarations.

### ISSUE THREAD

**Issue by LeDemz** [vuetifyjs/vuetify#17417] opened 2023-05-20 22:15 UTC
I get the following error when I try to compile my Vue 3/Vuetify 3 application using the colors module : ```error TS2307: Cannot find module 'vuetify/lib/util/colors' or its corresponding type declarations.``` 

Even with a modified tsconfig.json, I have no luck 
```
  "compilerOptions": {
    "types": ["vuetify"]
  }
```

**Comment by KaelWD** [comment] 2023-05-21 05:53
Duplicate of #16346

**Closed by KaelWD** 2023-05-21 05:53 UTC
Labels: S: triage
