### ISSUE TITLE
[Feature Request] Add validation state change event to form input components that use the validatable mixin

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#11854] opened 2020-07-14 15:37 UTC
### Problem to solve
I would like to be able to reactively get the validation state of each form input field so I can add additional UX for my users when they use my application.

Use Case:
I have several rows of input fields (multiple columns of input fields). I validate all of the input fields at once, but I want to be able to show which row has a validation problem so the user can quickly make their fixes.

### Proposed solution
In `src/mixins/validatable/index.ts` when the `validationState` changes, emit an event with the change in state. If `validationState` is `undefined`, the value that can be returned might be 'none' or something similar.

**Comment by KaelWD** [comment] 2020-07-29 08:40
![image](https://user-images.githubusercontent.com/16421948/88777286-610c0c80-d1ca-11ea-8e5c-5092fa796520.png)

`error.sync` doesn't really work but `@update:error` should.

**Comment by johnleider** [comment] 2020-12-08 20:40
Closing this as a duplicate of #3530 as its solution is going to solve your problem.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-08 20:40 UTC
Labels: triage
