### ISSUE TITLE
[Bug Report] Caret color is incorrect for solo-inverted text fields

### ISSUE THREAD

**Issue by sindrepm** [vuetifyjs/vuetify#9534] opened 2019-11-01 07:02 UTC
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
Create a `v-text-field` component with `solo-inverted` prop.

### Expected Behavior
I expect caret color to be the same as the text color.

### Actual Behavior
In dark mode caret color is white which means it becomes invisible on the white background.
In light mode the caret color is the primary color which doesn't look too good either.

### Reproduction Link
<a href="https://codepen.io/sindrepm/pen/WNNXmJb" target="_blank">https://codepen.io/sindrepm/pen/WNNXmJb</a>

### Other comments
This can be fixed by setting the CSS `caret-color` to `auto` like this:

```
.v-text-field--solo-inverted.v-input--is-focused > .v-input__control>.v-input__slot input {
  caret-color: auto;
}
```

**Comment by dfabreguette-ap** [comment] 2019-12-02 14:03
+1 =)

**Comment by nekosaur** [comment] 2019-12-02 14:35
Please use the thumbs up instead of +1 comments

**Comment by Agendum** [comment] 2020-01-04 07:20
The fix mentioned doesn't work for v-autocomplete text fields. The bug can be reproduced simply by using the "select state" async example at the bottom of: https://vuetifyjs.com/en/components/autocompletes
How can I get this fixed for v-autocomplete?

**Comment by Agendum** [comment] 2020-01-04 07:25
> How can I get this fixed for v-autocomplete?

My situation is localized to a component so I just used this scoped style to work-around the problem:
```
>>> .v-input__slot input {
  caret-color: auto;
}
```

**Comment by jontybrook** [comment] 2020-01-09 13:20
I'm also facing this issue. The solution above doesn't work for me because white--text overrides it with !important. Hope to see this fixed in a future release.

**Closed** 2020-01-23 04:15 UTC
Labels: C: VTextField, T: bug
