### ISSUE TITLE
[Feature Request] Allow add ratio prop on card

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetify#2389] opened 2017-10-31 14:13 UTC
### New Functionality
A `ratio` prop on `v-card-media` to follow [Material Specs](https://material.io/guidelines/components/cards.html#cards-content-blocks)

![16:9 rich media card](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3S05CcXZFOEh5RUU/components-cards35.png)
![1:1 rich media card](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3US1pR2N0OTNIaFE/components-cards37.png)

### Improvements
Most card rich media case scenarios are for 16:9 images.
It could allow to follow the Material Specs 16:9 or 1:1 rich media ratio even when its image has a different ratio.
Media width will be fixed at 100% of the card and its height should be auto, keeping the informed ratio.

Expected behavior:
https://codepen.io/anon/pen/JOdJYX

### Bugs or Edge Cases it Helps Avoid
Will be easier to follow the Material Specs.

**Comment by johnleider** [comment] 2017-11-01 00:14
Would this be similar to the **contain** prop that was added to `v-carousel`?

**Comment by peluprvi** [comment] 2017-11-01 14:01
Current behavior with **contain** prop added to `v-card-media`:
https://codepen.io/anon/pen/RjWamo

PS: remember to play with the slider to simulate the card width

In this example, the first card has white spaces and both doesn't follow the 16:9 or 1:1 ratio.
I think ratio needs to be a prop because Material Specs allow an option to a fixed height or a height depending on the children size. But it always displays a full width rich media.

The requested behavior is more like a background cover, if thinking like and image. But it can also but a chart, a carousel or any element considered "rich".

**Comment by zvory** [comment] 2017-11-06 16:20
I too would like this feature to be implemented. It was a surprise that there is no easy way for card-media to resize nicely.

**Comment by peluprvi** [comment] 2018-04-26 20:40
Related to https://github.com/vuetifyjs/vuetify/issues/1536

**Comment by KaelWD** [comment] 2018-07-03 11:42
Duplicate of #1536

**Closed by KaelWD** 2018-07-03 11:42 UTC
Labels: T: feature
