### ISSUE TITLE
[Bug Report] v-tabs-slider color no applied in opened dialog after page reload 

### ISSUE THREAD

**Issue by r-sokolov** [vuetifyjs/vuetify#5370] opened 2018-10-21 10:42 UTC
### Versions and Environment
**Vuetify:** 1.3.1
**Vue:** 2.5.17
**Browsers:** Chromium 69.0.3497.81
**OS:** Linux

### Steps to reproduce
Load or reload page in browser. 
Click "Open dialog" button.

### Expected Behavior
In my code v-tabs-slider color="yellow"  and should be append active class to current tab.

### Actual Behavior
Active class appended after change tab.

### Reproduction Link
[https://codepen.io/anon/pen/vVrMyz](https://codepen.io/anon/pen/vVrMyz)

### Other comments
It works properly without dialog.

**Comment by jacekkarczmarczyk** [comment] 2018-10-21 10:49
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1978

**Closed by jacekkarczmarczyk** 2018-10-21 10:49 UTC
