### ISSUE TITLE
[Bug Report][3.1.5] v-nagivation-drawer width prop as string breaks functionality and causes layout issues with v-main

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuetifyjs/vuetify#16705] opened 2023-02-17 21:26 UTC
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Open Reproduction link
2. Notice the drawer has a string width of `400px` but the drawer looks collapsed.
3. Look at the source code of the browser via inspect and you will notice the `.v-main` container has a style with `--v-layout-left:NaN;` in it.

### Expected Behavior
The width value should accept both string and integer values.

### Actual Behavior
Using an integer value works, but any string value breaks the functionality.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVc1u2zAMfhXOl7ZAZXdriwFeG3Q79Lbbbk0Piq0kWmRJkOikaZF3HyU7ju2kG7pcQvHn40eKlJ/eku/WputaJHlyh6KyiqOYTDXA3ZoV3JVRjifFt6bG9kyaT4wFtd96imMz7qAwyrj7aVIKYZmtnVUCSu5WQrPraTK5y/reE2CMwDq4NePWBsNeAx2edbLibjtNDibrTCW10LhXdbz6UEzzNZOF0bDmTnKNBIbiBacJPBRKFqvUo7GBseMb4eAePjVSy3YM0+Mb06AxKthRohKTn1uYSyV8iBxaRmHe8kK4ph+NOHKY4QnGgQCdqlKyii+0nFNDIgZ5fxSAeGJX5X/ElwY9WwuHsuBqANNCHJo3vGPqpFxwlEazttNd2jWrTClUdxv9697IEpdkubm6si+DORCu4v05ADg9EUr6ng9ALmkOPUHG/z5kLCa4D6o5Ij6sq+JSg8etEgS5FHKxxBxuA9tv1J4Bk7BVLLS0pwb4tRRwyAHtQG6kUkCNFLRdcxp5QHKbGUQSyctXXCly8/JVgC+cENqnvWTE+zhb0Aa6+80O1R5Wex9Dh7us9yDQkRJI23iJF2scQinmvFYIbw1UyZHncH4B9xM4b3WkjaXkgK4Wl3vlwpna5qBrpTpdvIkcng4FdBjhF1cph7NHY866mDg4XNXBMB8adj35JNAP7k4D0dR+COhRvr6+Q2lk+Ten+j2o2chygHpupd0FCY244Vgs80OK2O5wM72kuJQ+7R6+OVde7I177OZ/F0ahu/zkMpFVuH0aIpv+9kbTpyPC0i5FA21Tl3qa0LclnGkrEK3Ps6zWdrVIC1NlD2TLXK1RVoKelOrhOv2S3nzNSlq+vj4Vnj4Zzmy8cJRxmrT0IjjGh/B0gtZMuJ/T2wa2VQXII6iM8OlRY07oUrjwAv2F98h3wH1kO+LfdnVHvVRSr/yojYWPLWwX4YOF0WcxjQAh+jkk2V0mDTlKFwOS5z9bC2nW)

### Other comments
There are other layout issues that come up due to this bug, but I think once this issue is fix the others will also be fixed because of it.

**Comment by KaelWD** [comment] 2023-02-19 10:24
Duplicate of #16150

**Closed by KaelWD** 2023-02-19 10:24 UTC
Labels: S: triage

**Comment by webdevnerdstuff** [comment] 2023-04-30 23:39
@KaelWD As of v3.21 this is still an issue/bug. Is there any plan on this even getting looked at? The duplicate issue of this hasn't gotten any attention or even a bug flag in almost a half a year, and you close this as "not planned".
