### ISSUE TITLE
[Bug Report] v-data-table fails to reset page number to 1 when searching

### ISSUE THREAD

**Issue by rmirabelle** [vuetifyjs/vuetify#11885] opened 2020-07-18 20:06 UTC
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.89
**OS:** Windows 10

### Steps to reproduce
When using search, pagination fails to reset to page 1

### Expected Behavior
When a search term is entered, prior to filtering, current page is reset to 1

### Actual Behavior
Current page is not reset, search often fails because search filters the results to a total number of pages less than the current page number.

### Reproduction Link
<a href="https://codepen.io/rmirabelle/pen/eYJQVBR?editors=1010" target="_blank">https://codepen.io/rmirabelle/pen/eYJQVBR?editors=1010</a>

### Other comments
Using the veutify module as added by `create-nuxt-app`:
nuxt.config.js includes:

```javascript
buildModules: [
		'@nuxtjs/vuetify'
	],`
```

package.json includes:

```javascript
"dependencies": {
    "@nuxtjs/axios": "^5.12.0",
    "nuxt": "^2.13.0",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "vue": "^2.6.11",
    "vuetify": "^2.3.4",
    "vuex": "^3.5.1",
    "@nuxtjs/vuetify": "^1.11.2",
    "@nuxt/types": "^2.13.3"
  }
```

**Comment by manonthemat** [comment] 2020-07-18 20:57
related to #10949 and #11324

**Comment by Mert75** [comment] 2020-08-14 19:49
Duplicate of #10949 and #11324

Thread will continue on #10949

**Closed by Mert75** 2020-08-14 19:49 UTC
Labels: triage
