### ISSUE TITLE
[Feature Request] Need to provide slot for icon on v-timeline-item

### ISSUE THREAD

**Issue by aizaiz** [vuetifyjs/vuetify#5856] opened 2018-12-10 13:46 UTC
### Problem to solve
Can easily customize the css and html for icon on  v-timeline-item

### Proposed solution
Provide slot for icon instead of icon property

**Comment by jacekkarczmarczyk** [comment] 2018-12-10 23:58
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5538

**Closed by jacekkarczmarczyk** 2018-12-10 23:58 UTC
