### ISSUE TITLE
[Bug Report][3.3.3] VSnackbar cannot router.back when open.

### ISSUE THREAD

**Issue by Ahn-GiHwan** [vuetifyjs/vuetify#18208] opened 2023-09-04 07:13 UTC
### Environment
**Vuetify Version:** 3.3.3
**Vue Version:** 3.2.37
**Browsers:** Chrome 116.0.0.0
**OS:** Mac OSX

### Steps to reproduce
button click -> back(VSnackbar when open // router)

### Expected Behavior
back

### Actual Behavior
not back (in vue-router)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlU8tu2zAQ/JUFL2kBSwKSQwHDKVz0lFMP7S0KEJpa16z5UMmV2sLwv3dJybbktECA2D6Yw9kZzi75eBCf2rbsOxRLsSK0rZGEH2sHsOoL2bb5b14o70hqh2GEGGx0D8rIGO9rQfibCoWOMNTiTMmVG3KgvPGBaQGbopFhj664rQWsldFqz3h0Uu03MsA9UOhwJgHwpUUHX0fKRLvK4kyd+Z21+sL6Bs1Eni1tZ0gXhpPMLA4HSBHgeJyqsd6pKawWjaelVKS9i7Pif8Vkq14GLR2N3flP3K008Tpv+nw2nvG5yTnvFJtN7UI8WVzGVfG8TvNkwnygCRnmPVPkZVRBtwQRqRuug7atDwQHCLiFI2yDt3DDV+hm6BzrRqZfEjLtXU75/rKdez1sDSd6fgBpQU7Gc5Yo69o9gJIOdrJHsD4g0I6XnkmJWcK3nY7AP+k87TBkNHEogT87zeMz3n0vn5MZH2NVDak4j1iIIVBhZVv+iN7xUzgkXj1uxFosISMJ46BpXYsdURuXVaUax2V8z3QfSodUudZWa6ZVoXOkLRaNt+u78ra8+8AjiDTFS4y22AT/K2JglVosJj6kt39e4TUy2YK/g8MIFUZuYrJ4IV2xX4+hCOgaDOnNvi7SVdks1tXei2jJnl/XkTvO89nHq2armBv9eDrlmzJnsaT0lAyPCzEclK1zhXj6C89Nmtw=)

**Comment by KaelWD** [comment] 2023-09-04 18:37
Duplicate of #15140

**Closed by KaelWD** 2023-09-04 18:37 UTC
Labels: S: triage

**Comment by mohamad68** [comment] 2025-07-20 11:22
Add prop ` :close-on-back="false"` on the v-snackbar component
