### ISSUE TITLE
[Bug Report] Navigation Drawer clipped does not work

### ISSUE THREAD

**Issue by hobbeschild** [vuetifyjs/vuetify#12561] opened 2020-11-05 10:12 UTC
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 3.0.2
**Browsers:** Chrome 86.0.4240.111
**OS:** Windows 10

### Steps to reproduce
Click on the hamburger

### Expected Behavior
Navigation drawer should open under the toolbar

### Actual Behavior
Navigation drawer obscures the toolbar

### Reproduction Link
<a href="https://codepen.io/hobbeschild/pen/MWeXpey" target="_blank">https://codepen.io/hobbeschild/pen/MWeXpey</a>

**Comment by KaelWD** [comment] 2020-11-05 10:13
Duplicate of #6141

**Closed by KaelWD** 2020-11-05 10:13 UTC

**Comment by hobbeschild** [comment] 2020-11-05 10:35
@KaelWD thank you, the style solution works.

p.s. I did put this question in the Discord chat first - I didn't want to raise an issue - but no-one answered.

**Comment by HistoryGift** [comment] 2020-11-13 01:55
you  can modify the Navigation Drawer  css (position:fixed -> absolute)
