### ISSUE TITLE
Can't get the new Scrolling techniques feature to work

### ISSUE THREAD

**Issue by smtlk** [vuetifyjs/vuetify#1521] opened 2017-08-29 12:01 UTC
Hello everyone, i can't seem to get the new scrolling toolbar feature to work properly, i've created a **codepen** based on the official template and the code from the Docs.

https://codepen.io/anon/pen/OjayXO

I scroll down but the menu just goes up immediately, i was expecting a delay or something, am i doing anything wrong or is there some kind of bug with this feature? Keep up the awesome work 👍

**Comment by johnleider** [comment] 2017-08-29 13:00
Duplicate of #1511

**Closed by johnleider** 2017-08-29 13:00 UTC
