### ISSUE TITLE
[Bug Report] v-textarea row-height does not affect line height

### ISSUE THREAD

**Issue by gsqrt2** [vuetifyjs/vuetify#9798] opened 2019-11-26 10:40 UTC
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Windows 8.1

### Steps to reproduce
increase the row height of a multiline v-textarea, 

### Expected Behavior
the line-height of the textarea should increase proportionally to the row-height

### Actual Behavior
the overall height of the component will increase, but not the line-height of the  text area. this results in the lines being stacked on top of each other, while white space remains empty below

### Reproduction Link
<a href="https://codepen.io/gsqrt2/pen/MWWMbKy?&editable=true&editors=101#anon-signup" target="_blank">https://codepen.io/gsqrt2/pen/MWWMbKy?&editable=true&editors=101#anon-signup</a>

**Comment by KaelWD** [comment] 2019-11-29 04:51
Duplicate of #7671

**Comment by gsqrt2** [comment] 2019-11-29 07:55
This bug report is based on issue #7671, which was closed with a fix that only addressed the resulting overall height of the component.
Still the bug remains, so this report has a more specific codepen -again based on the codepen of #7671- and is reopened as a new issue instead of being commented on a closed one.

**Comment by johnleider** [comment] 2020-01-09 20:01
This is something that should be addressed in userland. The specification has a line-height set for the input and if you want that to change, you'll need to apply some custom css:

```sass
.custom-class
  textarea
    font-size: 16px
    line-height: initial
```

Or whatever your particular values are.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-09 20:01 UTC
Labels: C: VTextarea, T: bug
