### ISSUE TITLE
[Bug Report][3.3.0] V-Textarea with auto-grow and v-model.trim not displaying correctly

### ISSUE THREAD

**Issue by ggedde** [vuetifyjs/vuetify#17407] opened 2023-05-19 20:23 UTC
### Environment
**Vuetify Version:** 3.3.0
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
When using v-textarea with auto-grow and v-model.trim and hitting return on a new line the text bumps upward instead of extending the textarea field down. This resolves itself once you type in a character, but this looks very buggy. This does not happen when not using `.trim` on v-model. 

### Expected Behavior
Text should not bump upwards and instead stay in place while the textarea box increases height when you hit return or advance to a new line.

### Actual Behavior
Text bumps upward and textarea box does not increase height.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNUk1PwzAM/StRLgNpafi4jYLgPyBxIByy1oNA86HELaBp/x0n21jZhIAb6qV+jt/zs32/5DchVEMPfMZrBBs6jXClHGN1awbWdDqlS8WtFmeKF5wyg4j+dRMopLDx3Sbc5BHeUEfQO3AQ1rfQVRiNJcKF94rvsp2eQ0fwncEndktPxkndoxePJDli09Foh1TRuxZiZxy04xJ6nNs+HWNWv+W+C36yS8jPzmv51cmeseL0W2PEOtfxO0++x39iK0fb7dWSdkx/tRxtvk5NNAFZAuwDxcYGH5EtIyxWbBG9ZRM6l8mFco13CRltkl0yyh5NJsefKM3iC1rLNS0RHn5bK3//41NOQ3pJ1XPyjk54mVOKNykpPmP3mxPlT4ghzaRsWkcvaVtmiJUDlC5YSW7QLN6vz6vz6oQmknALCVphqgpZZnpQbkWC64EIq8Oe6jpRlAuSMWLK8Q8tXNMzGXuHxoJovS29nK57GcEVJCvmedkQiUTx6UgmN/wLqZ/cksQBtSS9AaKIkK8S6Mp/52ivbOxqL3XgLKuv8rxXU17KaPClZf7wAb/SdFM=)

### Other comments
I understand that this might be a limitation when using v-model.trim, but it does seem that this could be addressed to allow for better UI when using `.trim`.

**Comment by KaelWD** [comment] 2023-05-20 06:09
Duplicate of #16743

**Closed by KaelWD** 2023-05-20 06:09 UTC
Labels: S: triage
