### ISSUE TITLE
Option to  disable touch slide in v-tabs

### ISSUE THREAD

**Issue by marijnhurkens** [vuetifyjs/vuetify#3315] opened 2018-02-17 15:45 UTC
### New Functionality
I have slider inputs in the content of my tabs and this interferes with the slide functionality on the tabs itself. This way we see a lot of accidental tab switching. Being able to disable the touch slide on v-tabs would help.

### Improvements
I have no current workarounds.

### Bugs or Edge Cases it Helps Avoid
Accidental tab switching when using slider inputs in tab content.

**Comment by KaelWD** [comment] 2018-02-17 15:49
Duplicate of #2335

**Closed by KaelWD** 2018-02-17 15:49 UTC

**Comment by nkprince007** [comment] 2018-10-27 14:01
It has been marked as a duplicate and #2335 has a been closed. But, this issue still appears.
