### ISSUE TITLE
[Feature Request] Sass 2 support

### ISSUE THREAD

**Issue by Sardor01** [vuetifyjs/vuetify#13703] opened 2021-05-25 08:43 UTC
### Problem to solve
Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

![image](https://user-images.githubusercontent.com/58367523/119467628-21b53a80-bd5f-11eb-9230-ebd44f28e2a9.png)

### Proposed solution
paying attention to sass breaking changes like using ' @use and @forward '  instead of ' @import '

**Comment by jacekkarczmarczyk** [comment] 2021-05-25 09:18
Duplicate of https://github.com/vuetifyjs/vuetify/issues/13694

**Closed by jacekkarczmarczyk** 2021-05-25 09:18 UTC
Labels: triage
