### ISSUE TITLE
[Bug Report] Margin on centered tabs

### ISSUE THREAD

**Issue by olivbau** [vuetifyjs/vuetify#11000] opened 2020-04-01 23:28 UTC
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Set margin on centered tabs

### Expected Behavior
Tabs should be centered

### Actual Behavior
Tabs are not centered

### Reproduction Link
<a href="https://codepen.io/olivbau/pen/xxGeVPp" target="_blank">https://codepen.io/olivbau/pen/xxGeVPp</a>

**Comment by valentingavran** [comment] 2020-04-02 18:58
With the padding helper classes, it works for me.

```
<span>Margin + Centered [BUG]</span>
      <v-tabs centered>
        <v-tab class="px-12">Sleep</v-tab>
        <v-tab class="px-12">Sleep</v-tab>
        <v-tab class="px-12">Sleep</v-tab>
      </v-tabs>
```

Nevertheless, margins can lead to unexpected behavior and it should be fixed.

**Comment by olivbau** [comment] 2020-04-02 19:10
Thank's  ! Cause, padding is not ideal as i want the slider width to be same has the text.
If someone have a temporary solution, I'll take it.

**Comment by jacekkarczmarczyk** [comment] 2020-04-06 17:35
Not sure if this is a bug, you're messing with vuetify styles, we're not able to make everything working when users apply their own css to components

```html
<v-tabs centered>
        <v-tab class="mr-12">Sleep</v-tab>
        <v-tab class="mx-12">Sleep</v-tab>
        <v-tab class="ml-12">Sleep</v-tab>
      </v-tabs>
```

**Closed** 2023-09-20 19:15 UTC
Labels: T: bug, C: VTabs, has workaround
