### ISSUE TITLE
[Bug Report][3.0.6] v-switch track ignores event handlers and toggles state twice

### ISSUE THREAD

**Issue by alifeee** [vuetifyjs/vuetify#16368] opened 2023-01-03 15:40 UTC
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.45
**Browsers:** Firefox 108.0
**OS:** Windows 10

### Steps to reproduce
There are three different areas in the example: the rectangle row, the button handle, and the button inset. Click each of these.

### Expected Behavior
The boolean state should toggle once.

### Actual Behavior
It toggles once for the row and handle, but toggles twice for the inset.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9VNtu2zAM/RXW29AUiO20W/fgJkX2uKcBe60LVLHoVIssCZLiNAj876Nk59qtQGKb5OHhVXraJT+Mydo1JkUy9dgYyTw+lgpg2qbMmPgZhYYJNUhRlsL5SzkVRAELbTla8MJLnJVJfJcJzCspqhUptIIZXGlVJgf/0h+CQ5s6qX1BwVHxY3y3Eb56BaEcengVHFOOngnpyKHRHGVkJs5pvgeT8zQ/Kypykf2Q7DvtUcFFC4ITay3x7STXwdSmtbZkHTlP7GNKjOPbDb0oOee13VLJxQq3BImmM4aBo6gkc44QO2/XWMBAVTPpSLqKYkeOu13/2U1zcjvN5Ey+kNp04dWx7UNas6dnYvyN1MZQM0H2PSbpMOQg9OM/6yCJrrLCeCD3dTCLxmjrYQcW6zFsWJhRB7XVDVzTWl0Hn0or5yGOnVCjUOvNXjtkNZienskQSUZajWHUMklYmD3CLmQVXLTETOrl6OWXggVWrEH4vIu47oWcYc+YRV1m1u51oClVR/9p3lcwVOO3EsFV2mC/a5/CtPtoAFw4qnxbQFA+9LrwmW4sMwWEZ9R24ZGFuvaeC1atllavFU8rLbUtYGkR1Qk6Dvn/cIv8gnp86ROPWQG35g2oK4LDQhLNkGbD7FKoaB00hnEu1LKA+4OK0fiYF5pwNeP4U8Eku7t3x8BzWuDaUo/dHhCDT77QwLVhlfDUnMlDD76dnOtvo55+1PLQ5sdknPTrQntmsj9OK7p1IiGdkWhwZVLs6ysT2p8g0+p6b1yR52tlVsus0k0+J1tu18qLhi4C3cy/ZnfZt3s6AM6f6jN0TbqweuPQUsQyGZ+Qe1HTKf13gMFMvJPse087qALlO6qc+Fu0qaU7Cy3aD/O+wJ7lfmF7l/8wmo56KYVauYs2Vi62kM44Qbpx0lMTONaRPP8F+J/x9A==)

### Other comments
Adding [event modifiers](https://vuejs.org/guide/essentials/event-handling.html#event-modifiers) to @click on the v-list-item does not fix as far as I can tell.

Changing `v-model="on"` to `:modelValue="on"` also has no effect on the behaviour.

A fix is to surround the button with <div @click.stop><v-btn ... /></div>. I don't think this should be required.

**Comment by KaelWD** [comment] 2023-08-08 12:43
Duplicate of #17116

**Closed by KaelWD** 2023-08-08 12:43 UTC
Labels: S: triage
