### ISSUE TITLE
[Bug Report] Applying classes on specific viewport breakpoints behaves weirdly on page refresh 

### ISSUE THREAD

**Issue by begueradj** [vuetifyjs/vuetify#6737] opened 2019-03-15 08:40 UTC
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.6.9
**Nuxt.js:** 2.4.0
**Browsers:** Firefox 65.0
**OS:** Ubuntu undefined

### Steps to reproduce
In **~/components/SubComponent.vue** I want to display text with large font on small screens and over, and colorize my text in red only on small screens:
```
 <v-flex                                                                                                                                    
   xs12                                                                                                                                     
   sm4                                                                                                                                      
   :class="{                                                                                                                                
       'display-3': $vuetify.breakpoint.smAndUp,                                                                                              
        'red--text': $vuetify.breakpoint.xs                                                                                                    
    }">                                                                                                                                          
   Sub component                                                                                                                            
</v-flex>
```

### Expected Behavior
Text should be large (set to display-3) on small screens (my laptop) and red on extra small screens (phone).

### Actual Behavior
Whenever I refresh the page on my laptop, the text gets small and red.

### Reproduction Link
<a href="https://github.com/begueradj/bug-vuetify-apply-classes-breakpoints" target="_blank">https://github.com/begueradj/bug-vuetify-apply-classes-breakpoints</a>

### Other comments
I get weird behaviors with this approach whenever I try to combine more classes carefully, but here I am just providing a minimalist example.
Billal Begueradj

**Comment by KaelWD** [comment] 2019-03-15 08:43
Duplicate of #3436

**Closed by KaelWD** 2019-03-15 08:43 UTC

**Comment by begueradj** [comment] 2019-03-15 09:08
@KaelWD Thank you for linking me to that, but I tried the solutions mentioned there, including yours, and I still face the same problem however.
