### ISSUE TITLE
[Enhancement] v-navigation-drawer mini-variant display issues with expansion lists

### ISSUE THREAD

**Issue by ppatkar** [vuetifyjs/vuetify#6926] opened 2019-04-05 03:44 UTC
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Windows 7

### Steps to reproduce
Expand any list group (with many list items e.g Dining) & minify the navigation drawer. 

### Expected Behavior
When navigation drawer is minified ideally it should display all root level icons only to make it compact

### Actual Behavior
Minified navigation drawer shows spaces for down level list items. Hence root level icons in the minified version are spaced out.

### Reproduction Link
<a href="https://codepen.io/prasmi/pen/gyrvLd" target="_blank">https://codepen.io/prasmi/pen/gyrvLd</a>

**Comment by johnleider** [comment] 2019-04-12 03:12
Duplicate of #2830

**Closed by johnleider** 2019-04-12 03:12 UTC
Labels: C: VNavigationDrawer, T: enhancement
