### ISSUE TITLE
[Bug Report][3.0.0-beta.1] VComboBox wrong handling of model change

### ISSUE THREAD

**Issue by SuperCuber** [vuetifyjs/vuetify#15064] opened 2022-05-07 09:50 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Firefox 100.0
**OS:** Windows 10

### Steps to reproduce
1a. Select "a", "b", "c"
1b. Note that model changes and updates doesn't.
2a. Press backspace twice to delete "c"
2b. Note there is an update with ["a", "b"]
3a. Delete the "myData = $event" part of the handler
3b. Backspace to delete "b"
3c. Note how an update is fired but the model doesn't change
4a. Add "c" back
4b. Note that the model changes still

### Expected Behavior
Additions shouldn't modify modelValue in-place and instead should emit an "update:modelValue" event with a new array, similar to what deletions do

### Actual Behavior
Additions modify modelValue in-place and do not emit an update event

### Reproduction Link
<a href="https://codepen.io/SuperCuber2/pen/eYVJZyy" target="_blank">https://codepen.io/SuperCuber2/pen/eYVJZyy</a>

### Other comments
I need this to have more control over the value that gets updated - for example, I want to lowercase the user's input after they add a tag. Currently there's no way I could find to work around this since addition events don't get emitted.

**Comment by KaelWD** [comment] 2022-05-07 09:52
Duplicate of #15008

**Closed by KaelWD** 2022-05-07 09:52 UTC
Labels: S: triage
