### ISSUE TITLE
[Bug Report] Wrong styles ordering

### ISSUE THREAD

**Issue by Djaler** [vuetifyjs/vuetify#5681] opened 2018-11-21 09:31 UTC
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Linux x86_64

### Steps to reproduce
Launch in a development mode - `vue-cli-service serve --mode development`
You will see that tile-content is aligned by the right side.
Launch in a production mode - `vue-cli-service serve --mode production`
You will see that tile-content is aligned by the left side.

### Expected Behavior
Styles should be the same in development and production mode

### Actual Behavior
Styles looks differently in development and production mode

### Reproduction Link
<a href="https://github.com/Djaler/VuetifyStylesBugSample" target="_blank">https://github.com/Djaler/VuetifyStylesBugSample</a>

### Other comments
Maybe wrong order is not vuetify problem. But, in this case, vuetify should add work-around. For example, in this case, style for `.align-end` should be `align-items: flex-end !important;` instead of just `align-items: flex-end;`

**Comment by Djaler** [comment] 2018-11-21 09:43
Styles in prod mode:
![screenshot_20181121_122253](https://user-images.githubusercontent.com/7964583/48832740-ea7b0280-ed8a-11e8-817b-e8bb8c4d4897.png)

Styles in dev mode:
![screenshot_20181121_122411](https://user-images.githubusercontent.com/7964583/48832774-0088c300-ed8b-11e8-8517-81b9b18e6323.png)

**Comment by jacekkarczmarczyk** [comment] 2018-11-21 10:48
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3583

**Closed by jacekkarczmarczyk** 2018-11-21 10:48 UTC
