### ISSUE TITLE
[Bug Report] FAB Icon Clicked State - Off Centered

### ISSUE THREAD

**Issue by Failcookie** [vuetifyjs/vuetify#3243] opened 2018-02-09 13:24 UTC
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.140
**OS:** Windows 10

### Steps to reproduce
You can find this on the last example on the FAB page. When clicked, the FAB button icon (X) moves to the bottom-right. https://next.vuetifyjs.com/en/components/floating-action-buttons

### Expected Behavior
Icon should be centered within the FAB

### Actual Behavior
Moves to the bottom-right area of the FAB

### Reproduction Link
[https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/floating-action-buttons/speedDial.vue](https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/floating-action-buttons/speedDial.vue)

**Comment by KaelWD** [comment] 2018-02-09 13:29
Duplicate of #3207

Please use the search, this is getting ridiculous

**Closed by KaelWD** 2018-02-09 13:29 UTC
