### ISSUE TITLE
[Bug Report] directives dont work with vuetify loader or when imported explicitly

### ISSUE THREAD

**Issue by aldarund** [vuetifyjs/vuetify#7684] opened 2019-06-27 09:49 UTC
### Versions and Environment
**Vuetify:** 2.0.0-beta.4
**Vue:** 2.6.10
**Browsers:** Chrome 76.0.3809.36
**OS:** Windows 10

### Steps to reproduce
open index page 

### Expected Behavior
v-scroll works in all modes

### Actual Behavior
when treeShake in config enabled e.g. vuetify loader used directive in dev mode is not found
```
client-hook.js:1 [Vue warn]: Failed to resolve directive: scroll

(found in <Pages/index.vue> at pages/index.vue)
```
when its disabled all work fine. When its disabled and directive imported explicitly 
when import small scroll from lib - fail hard on build
```Module '"vuetify/lib/directives"' has no exported member 'scroll'. Did you mean 'Scroll'?```
when import Scroll from lib -
build succesfull but warning 
```
"export 'Scroll' was not found in 'vuetify/lib/directives'
```

### Reproduction Link
<a href="https://codesandbox.io/s/codesandbox-nuxt-4dqmy" target="_blank">https://codesandbox.io/s/codesandbox-nuxt-4dqmy</a>

### Other comments
was working in v1

**Comment by jacekkarczmarczyk** [comment] 2019-06-27 09:54
might be because of upper case in https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/types/lib.d.ts#L9

**Comment by xplodwild** [comment] 2019-07-04 08:02
I can confirm this is due to the uppercase. I had the same issue (note that dynamic loading fails too) with the Ripple directive. I had to do this:

```
import Vuetify from 'vuetify/lib'
import { ripple } from 'vuetify/lib/directives'

Vue.use(Vuetify, {
    directives: {
        Ripple: ripple
    }
});


export default new Vuetify({...})
```

Note the `Ripple: ripple`, as the directive in `vuetify/lib/directives` is lowercase, but the lib expects `Ripple`.

**Comment by jacekkarczmarczyk** [comment] 2019-07-08 12:48
Fixed in https://github.com/vuetifyjs/vuetify/pull/7767

**Closed by jacekkarczmarczyk** 2019-07-08 12:48 UTC
Labels: Framework, S: has PR, T: bug, typescript

**Comment by songololo** [comment] 2019-09-10 12:14
FYI I'm still running into this issue on the latest version of `vuetify-loader`. Workaround for now by using explicit directive import. (With `Resize` as opposed to `resize` etc).

**Comment by Skriptach** [comment] 2019-11-08 02:46
when I try

```javascript
import { Scroll } from 'vuetify/lib/directives';
```

I got error

```shell
 FATAL  Invalid or unexpected token                                                                                                                                                                    
  @import '../../styles/styles.sass'
  ^

  SyntaxError: Invalid or unexpected token
  at Object.compileFunction (vm.js:403:10)
  at Generator.next (<anonymous>)
  at Object.<anonymous> (node_modules\vuetify\lib\directives\ripple\index.js:1)
  at Generator.next (<anonymous>)
```
