### ISSUE TITLE
[Documentation] Clipboard got "undefined" when copying code by clicking the copy button

### ISSUE THREAD

**Issue by lomirus** [vuetifyjs/vuetify#17703] opened 2023-06-27 07:24 UTC
### Environment

**Browsers:** Firefox 115.0
**OS:** Mac OS 10.15

### Steps to reproduce
Scroll to "Installation", find "yarn create vuetify", and click the copy button near it.

### Expected Behavior
Copy "yarn create vuetify" to clipboard

### Actual Behavior
Copy "undefined" to clipboard

### Reproduction Link
[https://vuetifyjs.com/en/getting-started/installation/](https://vuetifyjs.com/en/getting-started/installation/)

**Comment by KaelWD** [comment] 2023-06-27 11:03
Duplicate of #17664

**Closed by KaelWD** 2023-06-27 11:03 UTC
Labels: S: triage
