### ISSUE TITLE
[Bug Report] v-dialog width defaults to 100% not auto

### ISSUE THREAD

**Issue by xon52** [vuetifyjs/vuetify#11644] opened 2020-06-16 01:35 UTC
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.138
**OS:** Windows 10

### Steps to reproduce
Remove any width property of a `v-dialog` box.

### Expected Behavior
Default width of auto (as stated in docs).

### Actual Behavior
Default width of 100%.

### Reproduction Link
<a href="https://codepen.io/xon5/pen/ExPgvOy" target="_blank">https://codepen.io/xon5/pen/ExPgvOy</a>

**Comment by johnleider** [comment] 2020-06-17 00:21
Confirmed this was present in v2.2 as well.

**Comment by MajesticPotatoe** [comment] 2020-06-18 23:15
The value of the prop defaults to `auto` however when the prop value === `auto`, it simply does not set a width style tag on `v-dialog` and its with defaults to v-dialog class width of 100%

**Comment by johnleider** [comment] 2020-12-08 21:47
Duplicate of #6919

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-08 21:47 UTC
Labels: C: VDialog, T: documentation
