### ISSUE TITLE
[Bug Report] Checkbox vertical alignment in table

### ISSUE THREAD

**Issue by mrodal** [vuetifyjs/vuetify#5445] opened 2018-10-26 12:46 UTC
### Versions and Environment
**Vuetify:** 1.3.0
**Last working version:** 1.2.10
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
Checkboxes inside table like in the docs

### Expected Behavior
Checkboxes should be aligned to the center vertically

### Actual Behavior
They are slightly out of center

### Reproduction Link
[https://codepen.io/mrodal/pen/dgaWaJ](https://codepen.io/mrodal/pen/dgaWaJ)

### Other comments
In the codepen I have the css on the 1.3.0, you can change it to 1.2.10 to see that there it is aligned

1.3.0:
![image](https://user-images.githubusercontent.com/20667544/47567046-e088ef80-d903-11e8-98cb-0bf33d44ddd6.png)

1.2.10
![image](https://user-images.githubusercontent.com/20667544/47567070-ef6fa200-d903-11e8-8499-27cab301ff24.png)

**Comment by KaelWD** [comment] 2018-10-26 13:03
This looks like a build problem, `vuetify.css` is fine.

**Comment by SnakeyHips** [comment] 2018-10-26 13:12
`.v-input--selection-controls{
  padding-top: 10px;
}`
That helps align the selection boxes in your codepen better so maybe try that for your app.

**Comment by KaelWD** [comment] 2018-10-26 13:16
![image](https://user-images.githubusercontent.com/16421948/47568702-89276580-d97d-11e8-8d66-f17ba8529c6a.png)

hide-details is supposed to have priority there

**Comment by KaelWD** [comment] 2018-10-26 13:17
Duplicate of #5404

**Closed by KaelWD** 2018-10-26 13:17 UTC
Labels: T: bug, T: regression
