### ISSUE TITLE
[Bug Report] Tooltip open-on-click first click the tips auto close fast.

### ISSUE THREAD

**Issue by freedomljt** [vuetifyjs/vuetify#12090] opened 2020-08-21 02:05 UTC
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.125
**OS:** Mac OS 10.15.6

### Steps to reproduce
just click the tooltip icon and you will see the effect.

### Expected Behavior
normal show the tips

### Actual Behavior
auto close tips

### Reproduction Link
<a href="https://codepen.io/freedomljt/pen/BaKQpQJ?editors=1010" target="_blank">https://codepen.io/freedomljt/pen/BaKQpQJ?editors=1010</a>

**Comment by KaelWD** [comment] 2020-08-21 08:07
Duplicate of #8213

**Closed by KaelWD** 2020-08-21 08:07 UTC
Labels: triage
