### ISSUE TITLE
[Bug Report] Calendar component display bug

### ISSUE THREAD

**Issue by Dev1lDragon** [vuetifyjs/vuetify#8111] opened 2019-07-27 23:32 UTC
### Environment
**Vuetify Version:** 2.0.1
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Every first day of mounth destroy grid representation 

### Expected Behavior
Button used on first day of month had same height as other buttons

### Actual Behavior
Button used on first day of month got default height

### Reproduction Link
<a href="https://codepen.io/dev1ldragon/pen/PMbyzJ" target="_blank">https://codepen.io/dev1ldragon/pen/PMbyzJ</a>

**Comment by nekosaur** [comment] 2019-07-28 07:46
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7992

**Closed by nekosaur** 2019-07-28 07:46 UTC
Labels: duplicate
