### ISSUE TITLE
[Bug Report][3.1.4] click:clear

### ISSUE THREAD

**Issue by laurentmahieu** [vuetifyjs/vuetify#16618] opened 2023-02-08 20:40 UTC
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.2.45
**Browsers:** Firefox 109.0
**OS:** Mac OS 10.15

### Steps to reproduce
    npm i
    npm run dev
    clear button is not working
____
    delete ...aliases in src/plugins/vuetify.ts
    icon clear button missing, but can clear v-text-field

### Expected Behavior
clear button clear v-text-field

### Actual Behavior
clear button don't clear v-text-field

### Reproduction Link
[https://github.com/laurentmahieu/vuetifyClearBroken.git](https://github.com/laurentmahieu/vuetifyClearBroken.git)

**Comment by KaelWD** [comment] 2023-02-09 01:38
Duplicate of #3505

**Closed by KaelWD** 2023-02-09 01:38 UTC
Labels: S: triage
