### ISSUE TITLE
[Bug Report] Group by in data table does not allow null values for the group-by item property

### ISSUE THREAD

**Issue by davidrijsman** [vuetifyjs/vuetify#12501] opened 2020-10-24 15:58 UTC
### Environment
**Vuetify Version:** 2.3.15
**Vue Version:** 3.0.1
**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 10

### Steps to reproduce
Open pen, data table does not display. 

### Expected Behavior
Databable should display, null values of the the item property should not result in error. Also no group should be created for null value

### Actual Behavior
No table is displayed at all.

### Reproduction Link
<a href="https://codepen.io/djr021320/pen/QWEdZpm" target="_blank">https://codepen.io/djr021320/pen/QWEdZpm</a>

### Other comments
Error is raised in groupItems helper function for group for items with null values as no items are added because they have value null.

**Comment by meungo** [comment] 2020-10-30 07:15
Seems to be a duplicate of [#12069](https://github.com/vuetifyjs/vuetify/issues/12069)

**Comment by MajesticPotatoe** [comment] 2020-11-24 19:53
duplicate #12069

**Closed by MajesticPotatoe** 2020-11-24 19:53 UTC
Labels: C: VDataTable, triage
