### ISSUE TITLE
ESLint warning: There are multiple modules with names that only differ in casing

### ISSUE THREAD

**Issue by dinaabramova** [vuetifyjs/vuetify#4912] opened 2018-08-19 11:24 UTC
### Versions and Environment
Vuetify: 1.1.4
Vue: 2.5.16
OS: Mac OS Sierra High

### Previously worked in:
Vuetify: 1.0.0
Vue: 2.5.16

### Steps to reproduce
Run any vue project with ESLint.
My `eslintrc.js`:
`module.exports = {
  root: true,
  parser: 'babel-eslint',
  env: {
    browser: true,
    node: true
  },
  extends: 'standard',
  // required to lint *.vue files
  plugins: [
    'html',
    'chai-friendly'
  ],
  // add your custom rules here
  rules: {
    // allow async-await
    'generator-star-spacing': 'off',
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'semi': ['warn', 'always'],
    'no-console': ['warn', { allow: ['error'] }],
    'no-unused-expressions': 0,
    'chai-friendly/no-unused-expressions': 2
  },
  globals: {}
}`

### Expected Behavior
No ESLint warnings.

### Actual Behavior
ESLint warning:

warning  in ./node_modules/vuetify/es5/components/VTextArea/VTextarea.js

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /node_modules/vuetify/es5/components/VTextArea/VTextarea.js
    Used by 1 module(s), i. e.
    /node_modules/vuetify/es5/components/VTextArea/index.js
* /node_modules/vuetify/es5/components/VTextarea/VTextarea.js
    Used by 1 module(s), i. e.
    /node_modules/vuetify/es5/components/VTextField/index.js

---
### Additional Comments:
Fix the case in folder name, please.

**Comment by KaelWD** [comment] 2018-08-19 11:30
Duplicate of #4736

**Closed by KaelWD** 2018-08-19 11:30 UTC
