### ISSUE TITLE
[Documentation] CDN issue from Canada

### ISSUE THREAD

**Issue by aaronfay** [vuetifyjs/vuetify#10339] opened 2020-01-26 19:40 UTC
### Environment

**Browsers:** Chrome 79.0.3945.117
**OS:** Mac OS 10.14.5

### Steps to reproduce
I am unable to browse the vuetify website from Canada, I get an error page from your CDN provider. [image](https://photos.google.com/share/AF1QipN9NRIRMe8xsceTuxRx4Z-jxmS9MS-DKcTuPVxlxBA0hyI4JK6QsaIvdRVGyMZjGw?key=N1BqQzhKMnZiUzhhdHltUnRXOE5lMWdiN1gtMWh3).

When I browse through a US VPN I have no issues.

### Expected Behavior
The site should load :)

### Actual Behavior
I hit a CDN error: [image](https://photos.google.com/share/AF1QipN9NRIRMe8xsceTuxRx4Z-jxmS9MS-DKcTuPVxlxBA0hyI4JK6QsaIvdRVGyMZjGw?key=N1BqQzhKMnZiUzhhdHltUnRXOE5lMWdiN1gtMWh3)

### Reproduction Link
<a href="https://vuetifyjs.com" target="_blank">https://vuetifyjs.com</a>

**Comment by johnleider** [comment] 2020-01-26 19:52
Duplicate of #10290 

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-26 19:52 UTC
Labels: triage
