### ISSUE TITLE
v-text-fields bottom line is displayed bigger when dpi scaling is enabled.

### ISSUE THREAD

**Issue by Yiin** [vuetifyjs/vuetify#2179] opened 2017-10-14 12:38 UTC
### Steps to reproduce
1. Enable dpi scaling in windows settings. (e.g. 125%).
2. Go to https://vuetifyjs.com/components/forms
3. Some of the fields have bigger line under them. Focus animation's expanding line has inconsistent height also.

### Versions
Windows, Chrome 61

### What is expected ?
Bottom line height to be consistent across text fields.

### What is actually happening ?
They differ.

### Reproduction Link
https://codepen.io/Yiin/pen/xXaeab?&editors=101
https://i.imgur.com/kqJitC8.png

**Comment by ctot-nondef** [comment] 2017-11-10 12:14
I tested this with both settings of 125% as well as 200% and could not reproduce your findings. 

Windows, Chrome 61

Could you post screenshots?
![image](https://user-images.githubusercontent.com/13985903/32658132-e7c9fe6e-c618-11e7-9875-aaae73c7c55d.png)

**Comment by KaelWD** [comment] 2017-11-10 12:51
@Yiin- I'd would also be helpful to know what version of windows you are using, the way it handles scaling has changed significantly since Windows 7.

**Comment by Yiin-** [comment] 2017-11-10 20:08
@KaelWD Windows 10, 1920x1080 15.6'' laptop (Lenovo Y50-70) on 125% scaling.

**Comment by jacekkarczmarczyk** [comment] 2018-06-10 06:11
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3090 (yeah, i know 2179 < 3090)

**Closed by jacekkarczmarczyk** 2018-06-10 06:11 UTC
Labels: T: enhancement, good first issue, help wanted
