### ISSUE TITLE
[Feature Request] [VDateInput] support different date formats

### ISSUE THREAD

**Issue by frederikheld** [vuetifyjs/vuetify#20180] opened 2024-07-17 10:55 UTC
### Problem to solve
Right now, `VDateInput` only supports `MM/DD/YYYY` format which is the worst of all formats as it lacks any logic. It's only useful for a very limited number of people on this planet.

### Proposed solution
Introduce a prop `format` that allows to define the date format to be used in a way that is compatible to the JS Date library. See [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat)

The text field should show the picked date in the defined format and the text field should also accept dates typed in this format.

Related to (but not the same as) #19996

**Comment by KaelWD** [comment] 2024-09-06 09:45
Duplicate of #19803

**Closed by KaelWD** 2024-09-06 09:45 UTC
Labels: S: triage
