### ISSUE TITLE
[Bug Report][2.5.6] Safari reactivity bug

### ISSUE THREAD

**Issue by flow96** [vuetifyjs/vuetify#13930] opened 2021-07-15 14:04 UTC
### Environment
**Vuetify Version:** 2.5.6
**Vue Version:** 2.6.14
**Browsers:** Safari
**OS:** Mac OSX, Mac OS 10.15.7

### Steps to reproduce
- Create a Vue.js project from the vue-cli, add vuetify
- Create a component with a v-btn that is outlined
- Create boolean-property that is set to false
- Bind the buttons :disabled property to the boolean
- In the mounted method set the boolean to true and create a timeout, that sets the boolean back to false after a specific amount of time

### Expected Behavior
The buttons disabled state is in sync with the booleans value.

### Actual Behavior
On Safari (both iOS and MacOS) the button gets disabled but never returns to enabled.
On Chrome everything's working fine.
The text color of the button remains dark. 

### Reproduction Link
<a href="https://codepen.io/flow96/pen/QWvpawR" target="_blank">https://codepen.io/flow96/pen/QWvpawR</a>

### Other comments
The same thing appears when using the date-picker and loading available dates, then setting the :allowed-dates property accordingly. On Chrome it is working fine but on Safari it seems like the components are not re-rendered on state-changes.

**Comment by KaelWD** [comment] 2021-07-15 14:13
Duplicate of #13599

**Closed by KaelWD** 2021-07-15 14:13 UTC
Labels: S: triage
