### ISSUE TITLE
[Bug Report] Color snackbar

### ISSUE THREAD

**Issue by dionysiosarvanitis** [vuetifyjs/vuetify#3219] opened 2018-02-08 11:05 UTC
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Use a snackbar with  :color="error"

### Expected Behavior
color inside snackbar

### Actual Behavior
color outside of snackbar

### Reproduction Link
[https://codepen.io/anon/pen/VQmKgZ?editors=1010#0](https://codepen.io/anon/pen/VQmKgZ?editors=1010#0)

### Other comments
color class (eg. error) should be placed at the level of .snack__content instead of .snack

**Comment by KaelWD** [comment] 2018-02-08 11:26
Duplicate of #3199

**Closed by KaelWD** 2018-02-08 11:26 UTC
