### ISSUE TITLE
[Feature Request] v-data-table add option to resize column and have multi header rows.

### ISSUE THREAD

**Issue by horkimsereirith** [vuetifyjs/vuetify#15222] opened 2022-06-08 04:33 UTC
### Problem to solve
Improve the accessibility of v-data-table by allowing the column to be resizable and table header support multi level rows.

### Proposed solution
Add children property on header object to generate multi rows.

**Comment by websitevirtuoso** [comment] 2022-06-09 07:08
https://primefaces.org/primevue/datatable/colresize
as an example

**Comment by websitevirtuoso** [comment] 2022-06-09 07:09
Personally I would like to add ability to add option set multiheader
https://primefaces.org/primevue/datatable/colgroup

Maybe this is possible to do already. But I am not sure, didn't try

**Comment by KaelWD** [comment] 2022-08-01 10:04
Duplicate of #3278

**Closed by KaelWD** 2022-08-01 10:04 UTC
Labels: S: triage
