### ISSUE TITLE
[Bug Report] When close nest dialog in a fullscreen dialog the fullscreen dialog will closed as well

### ISSUE THREAD

**Issue by hxshandle** [vuetifyjs/vuetify#9850] opened 2019-12-02 14:33 UTC
### Environment
**Vuetify Version:** 2.1.12
**Last working version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
1. click Open dialog 1 button
2. In the popup full screen dialog open dialog 2
3. Click close button in dialog 2
4. The Dialog 1 will close as well

### Expected Behavior
When close nest dialog only the nest dialog will be closed

### Actual Behavior
the parent dialog was closed too

### Reproduction Link
<a href="https://codepen.io/hxshandle/pen/RwNwVKg?&editable=true&editors=101" target="_blank">https://codepen.io/hxshandle/pen/RwNwVKg?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment] 2019-12-02 17:59
This codepen works for me correctly

**Comment by hxshandle** [comment] 2019-12-03 12:49
@jacekkarczmarczyk Thanks for looking at this issue, I add "persistent" property to the Dialog 1, this is the workaround I found. Now I remove the property and you can try again.  The issue is remain.

-Handle

**Comment by KaelWD** [comment] 2019-12-03 12:53
This is effectively a duplicate of #7310, if the other dialog is not a child it counts as an outside click.

**Closed by KaelWD** 2019-12-03 12:53 UTC
Labels: needs more information, triage
