### ISSUE TITLE
[Bug Report] v-data-table slot="page-text" is not propagated to v-data-footer

### ISSUE THREAD

**Issue by konstantinsteinmiller** [vuetifyjs/vuetify#8507] opened 2019-08-13 15:25 UTC
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
add a page-text slot to the v-data-table 

### Expected Behavior
the page text. especially: 1-20 of 500 should display the content of the page-text slot.

### Actual Behavior
slot not propagated (as of 2.0.5)

### Reproduction Link
<a href="https://codepen.io/steinmiller/pen/NWKxaVL?&editable=true&editors=101" target="_blank">https://codepen.io/steinmiller/pen/NWKxaVL</a>

### Other comments

I fixed the issue locally by propagating the scopedSlots to the footer props in the genFooters(props) function

like here on line 483 of VDataFooter.js, I added *scopedSlots: this.$scopedSlots*

     
     genFooters(props) {
       const data = {
          props: {
            options: props.options,
            pagination: props.pagination,
            itemsPerPageText: '$vuetify.dataTable.itemsPerPageText',
            ...this.footerProps
          },
          on: {
            'update:options': value => props.updateOptions(value)
          },
          widths: this.widths,
          headers: this.computedHeaders,
          scopedSlots: this.$scopedSlots
        };

**Comment by nekosaur** [comment] 2019-08-13 16:55
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8120

**Closed by nekosaur** 2019-08-13 16:55 UTC
Labels: duplicate
