### ISSUE TITLE
[Bug Report][2.5.8] Tab from v-autocomplete returns to the first focusable element on page

### ISSUE THREAD

**Issue by ictu-bd** [vuetifyjs/vuetify#14045] opened 2021-08-10 09:52 UTC
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.11
**Browsers:** Safari 14.1.2
**OS:** Mac OSX

### Steps to reproduce
Use tab key to navigate past the first v-autocomplete.

### Expected Behavior
After tabbing to the first v-autocomplete, pressing the tab key again should move focus down to the next v-autocomplete.

### Actual Behavior
After trying to tab from the first v-autocomplete to the next v-autocomplete, focus jumps back to first focusable element on page.

### Reproduction Link
<a href="https://codepen.io/ictu-bd/pen/bGWOvrP" target="_blank">https://codepen.io/ictu-bd/pen/bGWOvrP</a>

### Other comments
Because we use Vuetify for a government website especially tailored to disabled people. Accessibility is extremely important and this issue turns out to be quite a serious one, if not blocking.

Reproducible on the listed codepen, but the issue can also be reproduced on the Vuetify website itself https://vuetifyjs.com/en/components/autocompletes/#usage

**Comment by KaelWD** [comment] 2021-08-10 10:07
Duplicate of #14009

**Closed by KaelWD** 2021-08-10 10:07 UTC
Labels: S: triage
