### ISSUE TITLE
[Bug Report][2.5.7] Layout issue in actual mobile

### ISSUE THREAD

**Issue by jd-0001** [vuetifyjs/vuetify#14005] opened 2021-07-29 06:00 UTC
### Environment
**Vuetify Version:** 2.5.7
**Vue Version:** 2.6.14
**Browsers:** Chrome 92.0.4515.107
**OS:** Linux x86_64

### Steps to reproduce
Steps are written in Readme

### Expected Behavior
There shouldn't be scrolling in mobile device

### Actual Behavior
Page is scrollable in mobile device

### Reproduction Link
<a href="https://github.com/jd-0001/vuetify-layout-issue" target="_blank">https://github.com/jd-0001/vuetify-layout-issue</a>

### Other comments
I guess you can consider it for v3 if it require major changes for v2

**Comment by KaelWD** [comment] 2021-07-29 09:45
Duplicate of #11452

**Closed by KaelWD** 2021-07-29 09:45 UTC
