### ISSUE TITLE
[Bug Report] v-autocomplete readonly problem

### ISSUE THREAD

**Issue by karaozgur** [vuetifyjs/vuetify#10223] opened 2020-01-15 07:22 UTC
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Windows 10

### Steps to reproduce
click combo dropdown button, list menu will show up and select an item

### Expected Behavior
dropdown button should not be clickable while control is `readonly`

### Actual Behavior
Value can be change while control is `readonly`

### Reproduction Link
<a href="https://codepen.io/karaozgur/pen/QWwBmEV" target="_blank">https://codepen.io/karaozgur/pen/QWwBmEV</a>

### Other comments
Value can be changed by clicking combo dropdown button while autocomplete is `readonly`. Codepen example is same with your documentation at https://vuetifyjs.com/en/components/autocompletes#state-selector but somehow combo button works at my pages and Codepen.

**Comment by KaelWD** [comment] 2020-01-15 07:25
Duplicate of #9960

**Closed by KaelWD** 2020-01-15 07:25 UTC
Labels: triage
