### ISSUE TITLE
[Bug Report][3.0.0-beta.13] Buggy v-app-bar onload animation/v-main calc 

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#15880] opened 2022-10-12 21:09 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.13
**Vue Version:** 3.2.40
**Browsers:** Chrome 105.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
This is probably related to SSR because I can not reproduce it in codepen.
There's a Nuxt.js application https://github.com/Kasheftin/nuxt-nest-graphql-auth.
It's deployed & running on https://nuxt-nest-graphql-auth.rag.lt/.
Repro: just open the page. 
There's a short blip when v-app-bar is shown on the top left angle and has width ~100px which is then extended to full width. v-main also initially shown without offset and then is moved down. 

I tried to add `useSsrBoot` styles for v-app-bar, but it did not help. 
I guess the issue related to `layout` composable which does not receive the correct initialization immediately. 

### Expected Behavior
It should load without animations

### Actual Behavior
It loads with buggy animation

### Reproduction Link
<a href="https://github.com/Kasheftin/nuxt-nest-graphql-auth" target="_blank">https://github.com/Kasheftin/nuxt-nest-graphql-auth</a>

![vuetify-onload-bug](https://user-images.githubusercontent.com/379267/195448271-b56b8286-94dd-4344-9008-c97dba8f29c4.gif)

**Comment by nekosaur** [comment] 2022-10-12 21:13
Duplicate of https://github.com/vuetifyjs/vuetify/issues/15202

**Closed by nekosaur** 2022-10-12 21:13 UTC
Labels: duplicate
