### ISSUE TITLE
[Bug Report][3.0.0-beta.2] Combobox content is cutoff when typing and multiple is false

### ISSUE THREAD

**Issue by ThibaultNocchi** [vuetifyjs/vuetify#15157] opened 2022-05-26 14:16 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.2
**Vue Version:** 3.2.36
**Browsers:** Firefox 100.0
**OS:** Linux x86_64

### Steps to reproduce
- Use Firefox
- Type something and the text eventually disappears on the left instead of extending on the right
- Apply `multiple` prop and see that it doesn't disappear

### Expected Behavior
Working as when the `multiple` prop is applied or on other browsers such as Chrome, meaning text typing as normal inputs and extending to the right

### Actual Behavior
Text expends to the left as cursor gets "stuck" in the same position a few characters in. Un-focusing the input puts the text back in the field as normal.

### Reproduction Link
<a href="https://github.com/ThibaultNocchi/combobox-ff-no-multiple" target="_blank">https://github.com/ThibaultNocchi/combobox-ff-no-multiple</a>

### Other comments
I can provide a screen recording if necessary. I also don't remember it working as intended with the v3.

**Comment by KaelWD** [comment] 2022-08-09 17:50
Duplicate of #15317

**Closed by KaelWD** 2022-08-09 17:50 UTC
Labels: T: bug, C: VCombobox
