### ISSUE TITLE
Invalid CSS after "": expected 1 selector or at-rule, was ".cards"

### ISSUE THREAD

**Issue by mfferreira** [vuetifyjs/vuetify#48] opened 2016-12-29 02:27 UTC
I get this error when running any of the build commands: `npm run build` or `npm run build:client` or `npm run build:server`

Not sure where this is coming from, but it doesn't look like there's a problem on the style.

	<style lang="stylus">
		.cards
			flex-flow: row wrap
			justify-content: space-between

		.container
			display: flex
			height: 100%
			justify-content: center
			align-items: center

		.card
			margin-left: auto
			margin-right: auto
			width: 500px
			height: 500px
			flex-basis: 500px
			justify-content: space-between
			display: flex
			padding: 1rem
			flex: 1 0 50%
			@media screen and (max-width: 768px)
				flex: 1 0 100%
	</style>

Full error log:

	⟩ npm run build

	> vuetify-webpack-ssr@0.0.2 build /Users/marcoferreira/Development/Sites/tests/vuetify
	> rimraf dist && npm run build:client && npm run build:server

	> vuetify-webpack-ssr@0.0.2 build:client /Users/marcoferreira/Development/Sites/tests/vuetify
	> cross-env NODE_ENV=production webpack --config build/webpack.client.config.js --progress --hide-modules

	keywords if/then/else require v5 option
	Hash: 7f1f2b315804f4fd07dc
	Version: webpack 2.1.0-beta.28
	Time: 18072ms
																Asset       Size  Chunks           Chunk Names
					app.86c68aed5a95bcb98665.js     395 kB  0[emitted]  [big]app
			 vendor.205471727b5aa87a8d26.js    88.7 kB  1[emitted]  vendor
			styles.7f1f2b315804f4fd07dc.css      89 kB  0[emitted]  app
	styles.7f1f2b315804f4fd07dc.css.map  108 bytes  0[emitted]  app
													 index.html     1.3 kB  [emitted]

	WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB).
	This can impact web performance.
	Assets:
		app.86c68aed5a95bcb98665.js (395 kB)

	WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (250 kB). This can impact web performance.
	Entrypoints:
		app (572 kB)
				vendor.205471727b5aa87a8d26.js
				app.86c68aed5a95bcb98665.js
				styles.7f1f2b315804f4fd07dc.css
				styles.7f1f2b315804f4fd07dc.css.map

	WARNING in webpack performance recommendations:
	You can limit the size of your bundles by using System.import() or require.ensure to lazy load some parts of your application.
	For more info visit https://webpack.js.org/guides/code-splitting/

	ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-4d069b48!./~/stylus-loader!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/views/Login.vue
	Module build failed:
	<template lang="pug">
	^
				Invalid CSS after "": expected 1 selector or at-rule, was ".cards"
				in /Users/marcoferreira/Development/Sites/tests/vuetify/src/views/Login.vue (line 1, column 1)
	 @ ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-4d069b48!./~/stylus-loader!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/views/Login.vue 4:14-306
	 @ ./src/views/Login.vue
	 @ ./src/router/index.js
	 @ ./src/app.js
	 @ ./src/client-entry.js

	ERROR in ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-4d069b48!./~/stylus-loader!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/views/Login.vue
	Module build failed: ModuleBuildError: Module build failed:
	<template lang="pug">
	^
				Invalid CSS after "": expected 1 selector or at-rule, was ".cards"
				in /Users/marcoferreira/Development/Sites/tests/vuetify/src/views/Login.vue (line 1, column 1)
			at /Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/webpack/lib/NormalModule.js:143:35
			at /Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/loader-runner/lib/LoaderRunner.js:359:11
			at /Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/loader-runner/lib/LoaderRunner.js:225:18
			at context.callback (/Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
			at Object.onRender (/Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/sass-loader/index.js:273:13)
			at Object.<anonymous> (/Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/sass-loader/node_modules/async/dist/async.js:2234:31)
			at apply (/Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/sass-loader/node_modules/async/dist/async.js:20:25)
			at Object.<anonymous> (/Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/sass-loader/node_modules/async/dist/async.js:56:12)
			at Object.callback (/Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/sass-loader/node_modules/async/dist/async.js:840:16)
			at options.error (/Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/node-sass/lib/index.js:289:32)

	ERROR in /Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/vue-style-loader/index.js!/Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/css-loader/index.js!/Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/vue-loader/lib/style-rewriter.js?id=data-v-4d069b48!/Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/stylus-loader/index.js!/Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/sass-loader/index.js!/Users/marcoferreira/Development/Sites/tests/vuetify/node_modules/vue-loader/lib/selector.js?type=styles&index=0!/Users/marcoferreira/Development/Sites/tests/vuetify/src/views/Login.vue doesn't export content
	Child html-webpack-plugin for "index.html":

	Child extract-text-webpack-plugin:

	Child extract-text-webpack-plugin:

	Child extract-text-webpack-plugin:

			ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-4d069b48!./~/stylus-loader!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/views/Login.vue
			Module build failed:
			<template lang="pug">
			^
						Invalid CSS after "": expected 1 selector or at-rule, was ".cards"
						in /Users/marcoferreira/Development/Sites/tests/vuetify/src/views/Login.vue (line 1, column 1)
	Child extract-text-webpack-plugin:

	npm ERR! Darwin 16.3.0
	npm ERR! argv "/Users/marcoferreira/.nvm/versions/node/v6.9.1/bin/node" "/Users/marcoferreira/.nvm/versions/node/v6.9.1/bin/npm" "run" "build:client"
	npm ERR! node v6.9.1
	npm ERR! npm  v3.10.8
	npm ERR! code ELIFECYCLE
	npm ERR! vuetify-webpack-ssr@0.0.2 build:client: `cross-env NODE_ENV=production webpack --config build/webpack.client.config.js --progress --hide-modules`
	npm ERR! Exit status 2
	npm ERR!
	npm ERR! Failed at the vuetify-webpack-ssr@0.0.2 build:client script 'cross-env NODE_ENV=production webpack --config build/webpack.client.config.js --progress --hide-modules'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the vuetify-webpack-ssr package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     cross-env NODE_ENV=production webpack --config build/webpack.client.config.js --progress --hide-modules
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs vuetify-webpack-ssr
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls vuetify-webpack-ssr
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /Users/marcoferreira/Development/Sites/tests/vuetify/npm-debug.log

	npm ERR! Darwin 16.3.0
	npm ERR! argv "/Users/marcoferreira/.nvm/versions/node/v6.9.1/bin/node" "/Users/marcoferreira/.nvm/versions/node/v6.9.1/bin/npm" "run" "build"
	npm ERR! node v6.9.1
	npm ERR! npm  v3.10.8
	npm ERR! code ELIFECYCLE
	npm ERR! vuetify-webpack-ssr@0.0.2 build: `rimraf dist && npm run build:client && npm run build:server`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the vuetify-webpack-ssr@0.0.2 build script 'rimraf dist && npm run build:client && npm run build:server'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the vuetify-webpack-ssr package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     rimraf dist && npm run build:client && npm run build:server
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs vuetify-webpack-ssr
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls vuetify-webpack-ssr
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /Users/marcoferreira/Development/Sites/tests/vuetify/npm-debug.log

**Comment by johnleider** [comment] 2016-12-29 03:46
Are you using a vuetify template or your own boilerplate?

**Comment by mfferreira** [comment] 2016-12-29 04:05
Using Vuetify template

**Comment by johnleider** [comment] 2016-12-29 04:24
Do you have a repo that I can clone to test this? I am unable to reproduce the error.

**Comment by mfferreira** [comment] 2016-12-29 04:40
Created: https://github.com/mfferreira/vuetify-test

**Comment by johnleider** [comment] 2016-12-29 05:00
Fixed with https://github.com/vuetifyjs/webpack-ssr/commit/0fb8d761c1a8d970d506bfb2b42bb1a8dbfea981.

To fix this in your local, navigate to <strong>build/webpack.client.config.js:41</strong>

Change:
```javascript
vueConfig.loaders = {
  stylus: ExtractTextPlugin.extract({
    loader: "css-loader!stylus-loader!sass-loader",
    fallbackLoader: "vue-style-loader" // <- this is a dep of vue-loader
  })
}
```
to
```javascript
vueConfig.loaders = {
  stylus: ExtractTextPlugin.extract({
    loader: 'css-loader!stylus-loader',
    fallbackLoader: "vue-style-loader" // <- this is a dep of vue-loader
  }),
  sass: ExtractTextPlugin.extract({
    loader: 'sass-loader',
    fallbackLoader: "vue-style-loader" // <- this is a dep of vue-loader
  })
}
```

**Closed by johnleider** 2016-12-29 05:00 UTC

**Comment by mfferreira** [comment] 2016-12-29 05:08
Awesome! Fixed.
