### ISSUE TITLE
[Feature Request] Add nudge related props to VMenu

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#15725] opened 2022-09-01 10:33 UTC
### Problem to solve
It adds some gap between activator & menu content

### Proposed solution
Nudge props like v2: https://vuetifyjs.com/en/api/v-menu/#props

**Comment by KaelWD** [comment] 2022-09-01 10:36
Duplicate of #14451

**Closed by KaelWD** 2022-09-01 10:36 UTC
Labels: S: triage

**Comment by jd-solanki** [comment] 2022-09-01 10:41
Oh, sorry for the duplicate issue.

But this is not documented, moreover I also checked the source [code](https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VMenu/VMenu.tsx) but there is nothing like `offset` but still it works magically 🪄

**Comment by KaelWD** [comment] 2022-09-01 10:47
https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VMenu/VMenu.tsx#L102
https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VOverlay/VOverlay.tsx#L112
https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VOverlay/locationStrategies.ts#L69
