### ISSUE TITLE
[Bug Report] E2E - Vuetify passes all HTML attributes down to the input

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12097] opened 2020-08-22 11:05 UTC
### Environment
**Vuetify Version:** 2.3.9
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.135
**OS:** Mac OS 10.15.4

### Steps to reproduce
https://vuetifyjs.com/en/getting-started/unit-testing/

![Screenshot 2020-08-22 at 12 56 34](https://user-images.githubusercontent.com/17653648/90954702-ebb4f400-e476-11ea-84c5-63ad13801576.png)

In the docs, it is described that "Vuetify passes the data-* attributes from components to the relevant HTML elements". Thus, from this sentence, I expect that Vuetify **should not** pass other attributes to the relevant HTML elements. They should be placed on the root HTML element.

However, it is not working like this. I noticed that ALL attributes are passed down to the input element.

![Screenshot 2020-08-22 at 12 54 36](https://user-images.githubusercontent.com/17653648/90954772-ceccf080-e477-11ea-81c5-003f9b25dce2.png)

You can verify this behavior in the CodePen. In the DevTools you can check that `xyz` attribute was also passed down to the input element.

### Expected Behavior
Only data-* attributes should be passed down to the input element. Other attributes should be placed on the root element.

### Actual Behavior
All attributes are passed down to the input element.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/JjXbqPv" target="_blank">https://codepen.io/mikilll94/pen/JjXbqPv</a>

### Other comments
Many times it would be useful to place an attribute on the root Vuetify element. I.e. for input

![Screenshot 2020-08-22 at 12 59 05](https://user-images.githubusercontent.com/17653648/90954727-43ebf600-e477-11ea-9776-968e61b755a2.png)

I want to place on attribute on this `div` with `v-input`. However, it is not possible. This problem also applies to other controls.

**Comment by KaelWD** [comment] 2021-06-23 09:54
Duplicate of #7295

**Closed by KaelWD** 2021-06-23 09:54 UTC
Labels: S: triage
