### ISSUE TITLE
[Bug Report][3.3.4] v-select/v-autocomplete/v-combobox: The item slot appends content instead of overriding the item-title

### ISSUE THREAD

**Issue by bjorntrondsen** [vuetifyjs/vuetify#17656] opened 2023-06-20 06:41 UTC
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Use `v-slot:item` on a `v-select`

### Expected Behavior
Item slot replaces the default item appearance

### Actual Behavior
Item slot appends content after item-title

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUtFu2zAM/BVCL9kA20LiPRnZ0P3B3utgUGwW0ybLgiS7Kwz/eynZTpUEBQr0KeSJdxee+Tixn8YU44CsYkePnVHC449aAxzHXBgTy9g0vfZCarQrFEGHChsPY971LarvNTNoXa9/y7ZmUEkSdBfQEdQoFFac1WKxymy2JONU7yONWBOEIgNje+NgrlnCieZKOp+HGSKepW6DU5ilyWkhF1Y8F1p0CPN85AkjtedXay/Qttm2PgHX+wdkieeKT61rrDQLEf+b3npo8UkMysO0iLXCiy9ftw7Aoh+sfusBLiFWoAelstsXV8FjmsUEo1ADVrDPwEuvqNr92u8yCKuHOrJgv4M50Up4h4R3uOMd3uWVCa+845XXvNOlnpdieaTmyC+hsYzJLqSWd8IUf0mGDjNGU68P9HmrLaya0eWGvmZ/vDeu4rxpNdHoGOVoC42ea9PxBxrjdtBedpi3ffdQFmXxjbd0DilcoOvys+2fHVoSqdn6j6ONl08vH7BaJ1OHFcqVOLtgcSfNyW9Em1vULVq0H93ohpZ63jzdbbYmP1PeSup/7ibqxsWY1yv75MpRLCidguGcsThIzsvv6RW5KHDD)

**Comment by KaelWD** [comment] 2023-06-20 07:02
Duplicate of #16490

**Closed by KaelWD** 2023-06-20 07:02 UTC
Labels: S: triage
