### ISSUE TITLE
[Feature Request] Vuetify should work with other libraries.(Bootstrap、TailwindCSS...)

### ISSUE THREAD

**Issue by fmym** [vuetifyjs/vuetify#11698] opened 2020-06-21 10:16 UTC
### Problem to solve
First of all thanks for a great framework.

I am for instance using bootstrap-vue. I then added vuetify,I was just using the v-autocomplete component.

Conflicts row, col-*...

which could limit or completely abandon the usage of this framework for me.

Are there any good solutions?

### Proposed solution
Add specific vuetify prefix to classes declarations？
Load on demand？

**Comment by MajesticPotatoe** [comment] 2020-06-21 21:46
duplicate of #8261 / #5041
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by MajesticPotatoe** 2020-06-21 21:46 UTC
Labels: triage
