### ISSUE TITLE
[Bug Report] v-list-tile-sub-title in v-list with 'three-line' doesn't truncate long text

### ISSUE THREAD

**Issue by junfred** [vuetifyjs/vuetify#6526] opened 2019-02-17 12:24 UTC
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.4
**Browsers:** Mozilla Firefox
**OS:** Mac OS 10.14.1

### Steps to reproduce
See the codepen

### Expected Behavior
v-list-tile-sub-title in list with * two-line * surely works fine, and the same is expected when writing that with *three-line*

### Actual Behavior
*three-line* doesn't truncate long texts

### Reproduction Link
<a href="https://codepen.io/junfred/pen/GzPKjP" target="_blank">https://codepen.io/junfred/pen/GzPKjP</a>

**Comment by Mikilll94** [comment] 2019-02-20 14:19
I can confirm this behavior. On Chrome it works fine but on Firefox text is not truncated.

**Comment by MajesticPotatoe** [comment] 2019-02-20 14:33
duplicate of https://github.com/vuetifyjs/vuetify/issues/5235

**Closed by MajesticPotatoe** 2019-02-20 14:33 UTC
Labels: T: bug
