### ISSUE TITLE
[Bug Report] Item Group behaviour not as expected

### ISSUE THREAD

**Issue by NathanielAJohnson** [vuetifyjs/vuetify#6930] opened 2019-04-05 14:20 UTC
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Windows 10

### Steps to reproduce
https://vuetifyjs.com/en/components/item-groups#chips
Clicking on the first button twice should toggle it. (It doesn't)

### Expected Behavior
Clicking twice toggles highlighted state on then off.

### Actual Behavior
Clicking toggles highlighted state on but second click doesn't change anything.

### Reproduction Link
<a href="https://codepen.io/anon/pen/dLXPeX?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/dLXPeX?&editable=true&editors=101</a>

### Other comments
Click on and off the control seems to reset the control to it's proper highlighted state

**Comment by KaelWD** [comment] 2019-04-05 14:33
Duplicate of #6690

**Closed by KaelWD** 2019-04-05 14:33 UTC
