### ISSUE TITLE
[Bug Report] File Input with Label/Placeholder overlaps

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#12867] opened 2020-12-31 22:01 UTC
### Environment
**Vuetify Version:** 2.4.0
**Last working version:** 2.3.23
**Vue Version:** 3.0.5
**Browsers:** Chrome 87.0.4280.88
**OS:** Windows 7

### Steps to reproduce
Use both simultaneously.

### Expected Behavior
Label goes above.

### Actual Behavior
Label overlaps placeholder.

### Reproduction Link
<a href="https://codepen.io/teellcory/pen/xxEYyez" target="_blank">https://codepen.io/teellcory/pen/xxEYyez</a>

**Comment by KaelWD** [comment] 2021-01-01 08:08
Duplicate of #12864

**Closed by KaelWD** 2021-01-01 08:08 UTC
Labels: triage

**Comment by inane** [comment] 2021-04-20 08:33
Where can I find the fix for this topic?

**Comment by DRoet** [comment] 2021-04-20 08:46
its in release v2.4.5

**Comment by inane** [comment] 2021-04-20 08:50
I am working with the 2.4.9 and same behavior.
