### ISSUE TITLE
[Bug Report][3.7.3] Combobox auto selects first on manual input

### ISSUE THREAD

**Issue by dcrystalj** [vuetifyjs/vuetify#20657] opened 2024-11-02 09:11 UTC
### Environment
**Vuetify Version:** 3.7.3
**Vue Version:** 3.5.12
**Browsers:** Chrome 130.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Type `101` in combobox

### Expected Behavior
I should still be able to type `3` (1013) but it is gone

### Actual Behavior
hides other items and preselects first one

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1UctOwzAQ/JUhF4PUUKreqrQSN/6AQ9uDEzYoyPFa9qZCivLv2EmrpAgufszMzq5mj30WfLV+de750lG2ywqh1hktdDhZoLjk2rnxOX4qtqIbS/4KXcG25JK/bxDQRJNcGjG0P2VWt3TKfpEXbbpEjveS3XmSztucyy+qJCpqbcK9QnfCeSAT+bxufPhbldqEyBxnDOjTMDuozcsGOWpmtcI4woSpYYV/5Nuor7S1LCAr5CGMUvv7+m00mOvP8zyHYj3ndItzhJZ5JmSKu1gv1hC/ofKNE4SYzbSNpnXsBT081RhQe26h4gZVkgPRNwja8Il9UjyqNzKG8c7efDyop9Rgsoxm2bCynTHjcf4B8tWhdw==)

**Comment by KaelWD** [comment] 2024-11-02 09:16
Duplicate of #5479

**Closed by KaelWD** 2024-11-02 09:16 UTC
Labels: S: triage
