### ISSUE TITLE
[Bug Report] Time picker with allowed minutes makes it hard to select minute '00'

### ISSUE THREAD

**Issue by brease-colin** [vuetifyjs/vuetify#10138] opened 2020-01-07 09:37 UTC
### Environment
**Vuetify Version:** 2.2.1
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.88, Google Chrome, Safari
**OS:** Windows 10, Android, iOS

### Steps to reproduce
1. Go to the reproduction link or use the 'Allowed Times' example (use the right one): https://vuetifyjs.com/en/components/time-pickers#allowed-times
2. Pick a random hour
3. Try to pick the minute '00' by clicking (or touching) within the right '0' (a bit on the right side or on the right border of the 0)

### Expected Behavior
The minute '00' is selected and the click:minute event is triggered.

### Actual Behavior
The previously selected minute remains selected and the click:minute event is not triggered.

### Reproduction Link
<a href="https://codepen.io/brease-colin/pen/povpMLQ?editors=1111" target="_blank">https://codepen.io/brease-colin/pen/povpMLQ?editors=1111</a>

### Other comments
This issue also occurs on other minute values, not just 00. What seems to occur is that the picker detects that minute '1' is picked, not minute '0' and then disallows the click. However, this is not user friendly when 00 and 01 are so close to eachother.

A workaround that we use now is that we do allow all minute values, but in the minuteClicked event, we round the selected value to the closest allowed value, but in that case the actually selected value (like 10:01) is displayed for a split second and if you hold the mouse button on 10:01, it also shows that time instead of 10:00.

**Comment by jacekkarczmarczyk** [comment] 2020-01-11 07:36
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7299

**Closed by jacekkarczmarczyk** 2020-01-11 07:36 UTC
Labels: triage
