### ISSUE TITLE
Focused input field does not update when v-model changes

### ISSUE THREAD

**Issue by AleksueiR** [vuetifyjs/vuetify#1859] opened 2017-09-23 22:09 UTC
### Steps to reproduce

1. Create `v-text-field`
2. Use `v-model` to bind a variable
3. Add a `@keypress.13` listener to the field that clears the bound variable
4. Type something in the field
5. Press `Enter`
6. Observe that the input field retained the typed text even though its `v-model` variable was cleared.

![v-model-input-focus](https://user-images.githubusercontent.com/2285779/30777514-e1e05c46-a089-11e7-8b11-88deef6644d0.gif)

### Versions

Vue: __2.4.4__
Vuetify: __0.15.5__

### What is expected ?
The input field text is supposed to change to the value of its `v-model` variable.

### What is actually happening ?
The input field retains the typed text even though its `v-model` variable was cleared.
This seems to happen because the input field has focus when the variable is updated. If a button used to reset the `v-model` variable, the input field behaves as expected.

### Reproduction Link

https://codepen.io/AleksueiR/pen/gGLMdd

**Comment by jacekkarczmarczyk** [comment] 2017-09-23 22:12
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1726
Already fixed in dev branch

**Closed by jacekkarczmarczyk** 2017-09-23 22:12 UTC
