### ISSUE TITLE
[Bug Report][3.3.1] v-img padding-bottom sometimes not computed when using lazy-src

### ISSUE THREAD

**Issue by paul-thebaud** [vuetifyjs/vuetify#17471] opened 2023-05-26 16:00 UTC
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.4
**Browsers:** Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
Create a `v-img` with lazy-src and src.

### Expected Behavior
Image should always be correctly size (using computed padding-bottom on `v-responsive__sizer`).

### Actual Behavior
On Firefox (not on Chrome), image is not correctly size because padding-bottom does not seems to be updated.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVltzozga/Ssu78tuTSfmYmfjvkxNsBE2MTgIJECTeQDEmIvANBAb6Or/vsJJetPdDztVOw8u812PdMSHzu9fpndVdX16iqfvpx/buKhY0Ma/PpaTycfTVVBVl8eLUQRp+WK9Bq/CoJ5ER3asPz1Oqzotgrp/nH5L4mnBJKnjP3n0H4/TSdP2LObP4bGmcf1+IlbdpDmylE7qmH74rvCCkBaHt57JpKkjXp60bdW8n80iWo4Lb9M/+6y5jo7FjB6jZsZXcYibGTsejs3sJX41Wlcn+aphaXHVxl17xdJD0l43p8Pj9HsQFgz91TMSDdrg/aXfjCf+0hXsQxg08c383cMKqI5gIhcrYLsxJdIrFka6YSPjsE2F006MBqu/PUEA1S0wXdjfdbtMPe0EvN+md2mwgUK0Pp52MpVpv5CNfnGKiugEZT2JtKTyZeOERLLZDeqTYS9VrFqnSCal4ahPZAPzbTa/f3jGlYinD4G7fHqwtyNGut0kbagthgdbP9INPO/T2xNHkXdlNOyKZU/6295Y35138li/PcSa2ISlcRNrXRUWzXJbJALd3N3s+iWvip7oYDyFsl7ytSz2Tn56yXvGWVdDpIGMOEIabXQWSbinBeKxw3Kb3aWrVFnwdZ23qSIFLpatYjm/2Ou7g+H44naNxHEvK4f3dEFJbEUOXCgEayG9xFPlSFxWBhuL9+O5qTIPNfYUDNUxKnDB95j7Hkz2BWt9l7KdVJ2JG/3bL8BAHF/YrW4XQXorWAhAJLWBzfTSQrqCEFZcBFZEAApc3Z6IoMrIAfeQARcxBQfFsnQzHVINPFlFF8Ro2zvYEKjA1sEaZEbRiW7JVjYza1+iTqjqGuK2kS9Vy1MMS9DnBFAtkoCPMqzDtVI6IlTs/nYRCQBSAaiWS3WogtJGUKGCqFo5MKGqKxixFcIYcBvbgi77Al1bHt3xXNlRzTISOhU50IFIPTsChqbarWMVeBDpAKtkhTHRkEctWCYlFsiKiKZmMYx3AxssDGSI4Ir/a5f+uQ4xqjTLUQwIxmcyYvN8gOEl9nfY6LRXOc8YcO5Nme+b7xfb/Ex0lAPoYF0h6RJYaDvnPgUiMp7PuMaRA2X0ffvloHR4DGG2tQRQ24IxzpTicLixH4/LDjJXFhLHNUB4qdML3m/kkPfGEGNTH3myimSPGIO+xDLEwIKI1SZQzbWTm4MvYBd7cEuFSnUKloUCu7ekhLgqXQUSuEcie7IFs47QQsWOvo+LSHSkdg+xjt08caDb7bADbMxIQwDzcKl8dnPqhvjYBxslCfP5mYAkMCS8DdekNIGpBdqS2S4jETZrE5tuuFGY64pB5LKTycwm2gAWyiCJPDaYotFRPm/mBqdRbsp7ALV4Yxa2x7KIGec9hq7hwcJ19DwqDgLFSm26OA0z8hCW6pzk3c0eK76R5acgQzV95Z/z7TzPxyv/Lxz+T/4v5znGx9miIti+8g+RmfP3fcXP3UQ5f7/dxOT1vA0BNmA+xFAP8nbFZ8a2pDaBciIjt/3sOMCgAvHsMj8jd+nZOUSBWhUQJxuraBP7ci6tEw5gHxSGwOfrzN9hgHNqG1pyj6Ruz2fBdVnCmegSzoUdgqol2jLBsnJD1MQ1CmsI1pjxPmqgMg9KByFAVRWpLQrVysPSWQxw1Uao/cx9XujdSYGndFHe3lC184zSkgMHi+NMxqroQ/kwD/JqwWPIQAsf829mwI49Rd1nEy390EF1UN5J9Gf+E86fzGecv8cmQEjkfFpzy26PRtrqtGCb2O3KvXorWVniEHU+h2tiRWvQkMyQXU33HOT3e4fmSEzqQGJze1Pt7wdgOVrrQ7UVkccWbg7LqKBKNOhFrMLa8PS5zTkwJNbHG1K4G1wbstnEG2Xg367GRgsASzRHMv+G8bmwcNU4blWaciRDYXGK+VkYAy6htsxR3+rRAIZQ686uliBzo/S22hn+sO3Dtb4JmdpTjRFTpTWfCRKubjuojnNa2YawXBnSUtlviIBUv6arpRZmlmjm8BR6CnNcopEiaU0ngb7DekfKh71bnbCMHTwkeZB3Z+ouvEiq7i2Xz0feFo4L5XjVEnsDHpBIdSvLByRTG6+p5RSVgwGTiWZJZKCeDcBnAygS4jMQ9EtgikTAoiWEfC6IY/J7l3qm0PQUHGWSUcvPdC9iyZ7mROWRk63pJJDMKvKw5xbig1Uyz85IbfDzvBdwjvg5xOriTDLW+W7XE88YnMyfR5mpk7Tp/KKzYZ73pornkacfXbvduozPHwI44HeUL/L7ao35NwPIeLXkM1qtTI3fPxlNTAmdqADnRkHV3aDDB34XPxyO+sNq+XynOlwrrJYDLaJffhQ755S2CVc6wVN7/DH2KteKoLu65HHFdjOvug+jI4lH/fR+spC44/vK2VsBOAv+qxln30Tjq6rknm+y8iXMnz/O3ghRbjZRnVbtpInbp2c9Gh3Lpp0cSyfmf58m//zX5NOvky9fP4ylz8k8bfpumhbVsW45RHWdNceSS9wvY/njS6B5nL6fXDyjj0vF0f5eX2YNjVl6qq/LuJ2VVTH7jafN6qeyTYv4ih6L3+Rr+Xo+o2nTvnVfx01xFdbHcxPXvMnj9N0bmFGR/gWol8wLgviM8E3OBmEzQvzUesbxTnF9Vccll9hx/Vd39EPZ2139EPppZyP618fyK+ebpWXe/EB11Fxo/v11kf/Xli/Nxk5/jIBf300v6+TIl4LpH/8BxyU3kg==)

**Comment by KaelWD** [comment] 2023-05-26 16:13
Duplicate of #10386

**Closed by KaelWD** 2023-05-26 16:13 UTC
Labels: S: triage
