### ISSUE TITLE
[Bug Report][3.2.1] v-autocomplete: entered search text still visible after selection

### ISSUE THREAD

**Issue by haugero** [vuetifyjs/vuetify#17328] opened 2023-05-09 09:56 UTC
### Environment
**Vuetify Version:** 3.2.1
**Vue Version:** 3.3.0-beta.5
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Enter "Ca"
2. Select "California"

### Expected Behavior
The selected text is "*California*"

### Actual Behavior
The selected text is "*California*Ca"

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUctOwzAQ/JXIl0qosXmIS1QQCAl+AIlD3YObLGBwbMveBqoq/87aTVAfHCpxW8/OzuyO5xt27z3vVsAqNkNovVEIt9IWxawrlfe5zI9WaTu8cm+FrnbEB4QBlVgbUEEtTUYkSjRqCeZGsvtdNhu7lSbHSO355EEZ/eqC1WoyLSYPzrigGpfqRyp1k+EncOFty3iGbxVT8bJ2rbZvk0WSTaLjjrTleE/RldE4rCIYqFE7S5ab5N1Ldnu2ySXvlFlB35/NxF4MWUjs3zuGQvBvKpmT89oTYFOmW+8CEtPzj+gsBb3JAQyNKFlVZCRh9BPpLdk7oo+VEHVjaawBo7vALaCwvhV3RBNhZVG3UDauvbviV/y8XAIqfi0aHXG3yyG25TK4rwiBtCSb7rihfl2f4DgwyeiSX2wdBqikP47J4khakF8HoQxgGwgQTj3sYOyP4w4YRwemJXppe0rfaPsZD4KvYw59Pu76r8uzWFJaJMN+ynbXpQXyHFv8AHTXJNg=)

**Comment by KaelWD** [comment] 2023-05-09 10:04
Duplicate of #17291

**Closed by KaelWD** 2023-05-09 10:04 UTC
Labels: S: triage
