### ISSUE TITLE
[Bug Report] V-tab centered issues with Server side rendering (Nuxt)

### ISSUE THREAD

**Issue by amritk** [vuetifyjs/vuetify#8413] opened 2019-08-09 00:27 UTC
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Linux x86_64

### Steps to reproduce
Make sure the browser in codesandbox is big enough to trigger a weblayout. When you press refresh on the browser in codesandbox, you can see that the tabs are initially left aligned. Then they jump to the center when the client loads. I believe this is because there is useage of javascript breakpoints in there somewhere. 
Javascript breakpoints don't work on the server since there's no window width, so you get that jump. Preferentially you should just use CSS breakpoints. 

### Expected Behavior
The tabs should be centered from the beginning.

### Actual Behavior
They initially load on the left from the server, then jump to the centre when the client loads.

### Reproduction Link
<a href="https://codesandbox.io/s/nuxt-vuetify-k7yv9" target="_blank">https://codesandbox.io/s/nuxt-vuetify-k7yv9</a>

### Other comments
I will hack around this with css, but this should be fixed.

**Comment by amritk** [comment] 2019-08-09 00:41
Tracked it down to this sass in VTabs.sass
```sass
  // https://github.com/vuetifyjs/vuetify/issues/6932
  &.v-tabs-bar--is-mobile:not(.v-tabs-bar--show-arrows) > .v-slide-group__wrapper > .v-tabs-bar__content
    & > .v-tab:first-child,
    & > .v-tabs-slider-wrapper + .v-tab
      +ltr()
        margin-left: $tabs-item-mobile-no-arrows-margin

      +rtl()
        margin-right: $tabs-item-mobile-no-arrows-margin

  &.v-item-group > *
    cursor: initial
```
Since this mobile class is added by javascript, it incorrectly thinks its mobile when its on the server.
```
'v-tabs-bar--is-mobile': this.isMobile
```
Maybe a css only fix instead of using `this.isMobile`?

**Comment by jacekkarczmarczyk** [comment] 2019-08-09 05:46
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8294

**Closed by jacekkarczmarczyk** 2019-08-09 05:46 UTC
Labels: triage
