### ISSUE TITLE
[Bug Report][3.3.10] fields are still broken

### ISSUE THREAD

**Issue by yurks** [vuetifyjs/vuetify#17898] opened 2023-07-28 16:52 UTC
### Environment
**Vuetify Version:** 3.3.10
**Last working version:** 3.3.10
**Vue Version:** 3.2.47
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
use fields components as usual with vuetify@3.3.3
update to vuetify@3.3.10

### Expected Behavior
Field components heights and composition remains the same across minor version change

### Actual Behavior
Field components heights was unexpectedly changed and component inner value placement is broken at least between VTextField and VSelect

### Reproduction Link
[https://codepen.io/yurks/pen/xxQQgeY](https://codepen.io/yurks/pen/xxQQgeY)

### Other comments

A number of closed issues attached to #17412, but fields styling is completely broken in comparing to v3.3.3

**3.3.3 -> 3.3.5**
![image](https://github.com/vuetifyjs/vuetify/assets/4581398/36e87ebd-0257-4849-9f24-6b5dc44fbf15)

As you can see with reproduction Link:
- heights are different across different field variants
- heights are different across different field densities 
- heights are different with all versions up to v3.3.3
- VSelect value placement has incorrect position
- default density height was reduced to correct 56px according #17760. But only for default variant and density

**Comment by yuwu9145** [comment] 2023-07-29 02:29
[v3.3.10 demo link](https://play.vuetifyjs.com/#eNrFVs1um0AQfpXtXtxKBlKlysFyrPTWN+gh5IBhSLbdP+0OJJbld+8s0ApDYpkYNSeY2Znvm539FuZ+z79bG9cV8BVfIygrM4RNqhlb11FmbfPaGLnRmAkNjnncSbhN+bMo8GnFbm6u7EvKu8gmtjRO/bMbjzPPTJvosUIE53trHbbc0APhBaNSgCxYnckqcHijIOVkOpFpJIepUFIVBTmTzTppc1+H8yAhx1mgzqms0gW4uWqbBPZ2de8r47Ws4KFDnHiqfQ9jx7Uer7FBEePV8bENYwrQXuCOYnKjSIOYbeUA6lRDxsVOUNDs3Jc3qq+hD2/VkaAvZD+t+TfA33kXpqDNf0emS89mOX6E5C/lnfyF/a+7not5gnJb4DlUewJpqNhg937ebUL332+nAvK0Y8E66Y0LZPrcCYvMA1bt1CCUpevC9sxByQ6sdEaxBU0aixDOGOF6ZMo/stsQ8XnxA6Q07Kdxsvi0+BIIWkgC40veokUqs/EvbzSNK/uAknYLPuUr1niCj1iCnfInROtXSZIXmtIKkKJ2sQZMtFXJHYUlrtIoFESFUXfX8XX8LSmEx747Bq+iLXXJgyOQlC97NCjK3RlUXWTD8PWqpeh8kcy2PnCMsBMirMFFDoL6wJ27pUFaf1uDpdHWAvsh1QdqOKn9tx/0OvdNn+//FnnZnhu0APUQGA9L3hRK1G0Gf/gDiD9CDg==)
- component inner value placement is broken at least between VTextField and VSelect - _resolved since v3.3.6_
- heights are different across different field variants - _underlined variant is different from others_
- heights are different across different field densities - _I think this is expected_
- heights are different with all versions up to v3.3.3 - _please explain bit more as heights are also different in v3.3.10_
- VSelect value placement has incorrect position - _resolved in new version_

**Comment by yurks** [comment] 2023-08-01 13:20
Second and third version of vuetify worked very well with all fields densities. It was expected that underlined fields had a bit less height, but default/outlined/solo variants height should be the same, as it was in all previous version:

**field heights** for default/comfortable/compact densities
vuetify **< 3.3.3**  all variants is **56/48/40** 
vuetify >= 3.3.4 && <= 3.3.8 default/solo is 56/52/44, outlined is 60/52/44 
vuetify >= 3.3.9 all variants is 56/50/44

as you can see, starting from v.3.3.4 field heights changes kind of randomly. It's not possible to update library without breaking the UI. As all versions from the beginning of vuetify dev had field heights **56/48/40** for default/comfortable/compact, it's expected that it *should* be the same across all major versions at least. Otherwise, it's expected to have breaking change in release notes.

**Comment by johnleider** [comment] 2023-08-09 12:51
resolved as of latest version:

https://play.vuetifyjs.com/#eNrFVs1u2zAMfhVNl2xAbW/rDkWQBt1tb7BD3YNjM602/UGi0wZB3n2U5Q2O02Zx4ranhBT5fSStz+bthn+3Nl3VwKd8hqCsLBDmuWZstkoKa5u/jVEajYXQ4JjHtYTrnD+KCh+m7Orqs33KeRvZxC6NU//sxuPMI9Mmua8RwfnOWYst5/SD8ITJUoCs2KqQdeDwRkHOyXSi0EgOU6OkKipyZvNZFnOfh/MgocRRoI6prNYVuLFqGwT2cnWnldHNOn0e3kgzwiQOwAQPXayBN63rYWy3m90z1qtq/3T/KvVjKtBe4JpiSqNIF1gsZA/q0IT2ix1wq0fnPn9Q3Xv97qPaEdmZ7IdV8QL4ieI4Bm3Y4/yv/N782ZzHO/6bYbjgbFHiewj9XN7B37o37Xos5gF6jcBjaPUZpNfU6Ws/i9M5+/oMdmdpjAntvhm3UfLEdXSWddZUMn3phEXmAeu4rQpl6T3BNszBkm3Z0hnFJrThTuKwCdcjU/6eXYeIj5MfIKVhP42T1YfJp0AQIQmMX/CIlqjCpr+80bQmbwJK3h74nE9Z4wk+Ygl2zh8QrZ9mWVlpSqtAipVLNWCmrcpuKCxztUahIKmMurlML9NvWSU8dt0peJUsaEoeHIHk/KJDg2K5PoKqjWwYvnyNFK0vkcXCB4497IwIV+ASB0Fr4I5tqZfWbat3tNdaYN/meksDJ23/9r1Zl76Z8+3fIs/ruUELUHeBcXvBm0KJOmbwuz/e8/5W

**Comment by yurks** [comment] 2023-08-09 13:02
@johnleider what is resolved? 
field heights for default/comfortable/compact densities is still 56/50/44
instead of original **56/48/40**

**Comment by yurks** [comment] 2023-08-09 13:08
can you see the heights differences?

<img width="308" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/4581398/aef7d965-3f82-413e-ab34-eb4ba80110d0">
<img width="309" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/4581398/d2b2f4aa-ae62-4747-86d6-c418a832b9de">

**Comment by johnleider** [comment] 2023-08-09 15:26
Didn't mean to close this issue.

**Comment by yuwu9145** [comment] 2023-09-01 12:47
Have done as much regression testing as I could and it looks good in my eyes.

@yurks could you please help test the changes in your project?

Nightly build link: https://github.com/vuetifyjs/vuetify/pull/18025#issuecomment-1702679636

**Comment by yurks** [comment] 2023-09-06 16:54
@yuwu9145 thanks for fixes! Overall it looks good in our project. Some notices:

chips in select and combobox fields missed vertical margin

`<v-combobox chips`:
![image](https://github.com/vuetifyjs/vuetify/assets/4581398/0348781d-0e8a-42df-a11e-86a987ac4695)

**Comment by yuwu9145** [comment] 2023-09-07 06:25
> chips in select and combobox fields missed vertical margin

This is what combobox chips look in my place, they all have vertical gaps. Could you provide a reproduction code sample that simulates your issue?

![image](https://github.com/vuetifyjs/vuetify/assets/5698884/0c155589-aa9a-4c45-9e50-7f11fb097d50)

**Comment by yurks** [comment] 2023-09-07 07:04
it's weird.

this is vuetify playground 
<img width="1327" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/4581398/65a0becf-3a4a-4c92-bc90-cbc89291bb73">

and this is my local project with vuetify installed with alias: `"vuetify": "npm:@vuetify/nightly@3.4.0-alpha.1-pr-18025.92c2256"`
![image](https://github.com/vuetifyjs/vuetify/assets/4581398/f36a3299-445d-4133-aba0-76bd35ede4e4)

as you can see, `var(--v-input-chips-margin-bottom);` value is different. How this is possible? maybe version you mentioned `3.4.0-alpha.1-pr-18025.92c2256` has some issues with css?

**Comment by yuwu9145** [comment] 2023-09-07 07:08
Its gap is from margin-top

![image](https://github.com/vuetifyjs/vuetify/assets/5698884/82003c56-20ff-4192-a9ed-163c134cff3b)

**Comment by yurks** [comment] 2023-09-07 07:19
ok, got it.

@yuwu9145  With version `3.4.0-alpha.1-pr-18025.92c2256` chips in combobox have a 1px margin vertically. Have no idea why yesterday I sew np margin, but today it looks the same with yours screens
![image](https://github.com/vuetifyjs/vuetify/assets/4581398/24a6dfb4-f58e-44bf-8bd0-b0ca358d4abe)

**Comment by yuwu9145** [comment] 2023-09-07 07:20
All good, thanks for testing ♥️

**Comment by yurks** [comment] 2023-09-07 07:21
another thing is - prevously, margin between chips looked more natural for compact dencity
<img width="541" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/4581398/365c8587-c85e-4db5-bb3c-e2fc8f2501fb">

**Comment by yurks** [comment] 2023-09-07 07:24
I'm able to get similar results locally by setting `--v-input-chips-margin-bottom: 4px;` and `--v-field-padding-bottom: 2px;`
looks niver
![image](https://github.com/vuetifyjs/vuetify/assets/4581398/6b99f2ec-74cb-47d9-af66-6d15a5a191c0)

**Comment by yurks** [comment] 2023-09-07 13:27
@yuwu9145 no, it's not breaking the height, as that vars changing relatively.
Not a big deal, we will tune that props for our needs.
Just mentioned, in case you guys have your own pixel-perfect-issue like me (I see, you haven't))

**Comment by KaelWD** [comment] 2023-09-07 15:28
> Gap cannot be increased as chips margin top/bottom are part of eventual field height.

If we push this to 3.4 we can drop safari 13 and you can use `gap` instead of margin.

**Comment by yuwu9145** [comment] 2023-09-07 23:29
> Just mentioned, in case you guys have your own pixel-perfect-issue like me (I see, you haven't))

I'm targeting pixel-perfect in all cases, if haven't, it's either an issue haven't been found or there was certain restrictions. I will go through chips gap in compact density and let you know what can I do.

**Comment by yuwu9145** [comment] 2023-09-10 12:54
@yurks Try the new night build https://github.com/vuetifyjs/vuetify/pull/18025#issuecomment-1712801426

It's now using css gap to control the gap and it's being defined in a new sass variable `$field-input-row-gap: 3px !default;`. 

With this new css technology, chips gap is now irrelevant to other logics, which means it can be further customised without worrying about breaking default height or introducing any other regressions.


![image](https://github.com/vuetifyjs/vuetify/assets/5698884/26e0ba17-7c20-49c9-bcad-801adaeeb6fb)

**Comment by yurks** [comment] 2023-09-10 13:20
Thank you, will check and let you know!

Based on screens - are you decided to use constant gap for each densities? It works for me, but it could be unexpected, as there was a density modifier before. Also, it looks like 3px applied for horizontal gap, as vertical looks bigger (again, based on screens).

**Comment by yuwu9145** [comment] 2023-09-10 13:32
Good point, making it density-driven shouldn't be hard

**Comment by yuwu9145** [comment] 2023-09-11 05:34
New build: https://github.com/vuetifyjs/vuetify/pull/18025#issuecomment-1713182675

- density-driven row gap
- `$field-input-column-gap: 2px !default;` & `$field-input-row-gap: 8px !default;`

**Comment by yurks** [comment] 2023-09-16 10:53
@yuwu9145 
works, thanks! now we are able to update from vuetify@3.3.3 without breaking ui (almost))

ps: only one suggestion: `$field-input-column-gap: 4px !default;` looks more natural.

**Comment by yurks** [comment] 2023-09-16 11:04
and the last suggestion (or maybe that's for another ticket, just what you can)

this is how chips field looks by default, which is good:
![image](https://github.com/vuetifyjs/vuetify/assets/4581398/04442e5f-9d03-4acc-8ae0-35c99bef28dd)

But visually it looks not optimised. We use some trick for nicer view:
```scss
.v-combobox__selection,
  .v-select__selection {
    margin-inline-start: -8px;
    margin-inline-end: 12px;
    &:last-of-type {
      margin-inline-end: 0;
    }
}
```
![image](https://github.com/vuetifyjs/vuetify/assets/4581398/71f581c1-863e-4f78-a30b-146d5d63deb4)

which looks better. Just as a suggestion for better ui.

**Closed** 2023-10-21 05:45 UTC
Labels: T: bug, C: VField
