### ISSUE TITLE
[Feature Request] a linear loading in bottom of snackbar 

### ISSUE THREAD

**Issue by alamamir** [vuetifyjs/vuetify#11943] opened 2020-07-27 05:30 UTC
### Problem to solve
hi !
vutify is greate but i think snackbar can improve more!
by a linear loading in bottom of snackbar !such as gmail app snackbar
thanks a lot :)

### Proposed solution
update

**Comment by Parakoos** [comment] 2021-03-28 16:04
Would love this. I was about to implement this myself (I've already implemented the queue) but might just wait for this to be done if it is in the queue.

**Comment by KaelWD** [comment] 2022-03-04 05:05
Duplicate of #8451

**Closed by KaelWD** 2022-03-04 05:05 UTC
Labels: maybe, C: VSnackbar
