### ISSUE TITLE
[Bug Report] Vuetify 2.1 controls do not render correctly when compiled as a web component (vue-cli-build --target wc)

### ISSUE THREAD

**Issue by matthughes404** [vuetifyjs/vuetify#9781] opened 2019-11-24 17:38 UTC
### Environment
**Vuetify Version:** 2.1.11
**Last working version:** 1.5.21
**Vue Version:** 2.6.10
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Linux, Windows

### Steps to reproduce
1. Compile (`vue-cli-build --target wc`) and serve Vuetify 2.1 component
2. Import component's js file in separate Vuetify 2.1 application
3. Add component (`<custom-component>`) to App.vue's `<template>` tag

### Expected Behavior
Web component's Vuetify elements render correctly

### Actual Behavior
Web component's Vuetify elements are not rendered, and errors are returned in the JS console:  ```[Vue warn]: Unknown custom element: <v-app>```

### Reproduction Link
<a href="https://github.com/matthughes404/vuetify-web-components" target="_blank">https://github.com/matthughes404/vuetify-web-components</a>

### Other comments
Importing a Vuetify 1.5 component as a web component is working successfully on a current application, but we have not been able to make the same setup work with Vuetify 2.1.

**Comment by jacekkarczmarczyk** [comment] 2019-11-26 03:15
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5054

**Closed by jacekkarczmarczyk** 2019-11-26 03:15 UTC
Labels: triage

**Comment by matthughes404** [comment] 2019-12-03 15:23
This bug report seems more of a duplicate of #7622 than #5054 (after doing a bit more research). 

Unfortunately, this is one of the comments on #7622:
> There are no plans currently to support web components
