### ISSUE TITLE
[Bug Report] v-autocomplete doesn't show default value when bind object to v-model is not present in items

### ISSUE THREAD

**Issue by zihniogmen** [vuetifyjs/vuetify#12462] opened 2020-10-21 10:00 UTC
### Environment
**Vuetify Version:** 2.3.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 86.0.4240.75
**OS:** Windows 10

### Steps to reproduce
- Create a v-autocomplete component
- Assign an object to v-model
- Pass an empty array to items prop

### Expected Behavior
With v-model object is non-null, autocomplete should show default value even if the object is not in the items or items is empty.

### Actual Behavior
Autocomplete shows empty input.

### Reproduction Link
<a href="https://codepen.io/zihniogmen/pen/JjKRzdr" target="_blank">https://codepen.io/zihniogmen/pen/JjKRzdr</a>

### Other comments
When using autocomplete, sometimes there is a need to show initial value while items array is empty. So user can see an initial value but can also search for another.

**Comment by KaelWD** [comment] 2020-10-21 10:02
Duplicate of #4000

**Closed by KaelWD** 2020-10-21 10:02 UTC
