### ISSUE TITLE
[Bug Report][3.1.12] v-select displays item-value instead of item-title when selected if the item-value is an array

### ISSUE THREAD

**Issue by ZakareyaAlatoli** [vuetifyjs/vuetify#17037] opened 2023-03-30 13:31 UTC
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.3.0-alpha.5
**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a v-select component. For whatever key is used for the item-value prop, make it an array in at least one of the listed items.

### Expected Behavior
The item-title is used to display the selected item regardless of item-value.

### Actual Behavior
The item-value is used to display the selected item if the item-value is an array.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUk1v2zAM/SuCLt4AfyQtdjHSobvsT8Q5KDbdapUlgaJdFIH/+yjZGZJ0G9DCB5mPTyTfE/cn+cP7chpB1nJHMHijCL43VojdVCjv028KBqUtRw3Fj+MABloSteZb4aGR6WykiGdBmgww2OOo6QxOyowRbJ1xyKBRRzAc/4ykeHVSqJUlhgJTIlAMrkucXhsCTMxGrkPxWNV5jvOcDKyDLsEiYVddSOMwtKg9iQA0xrQevEMSJ4HQi1n06AaRsSdZJLfOBhIX/cVD5H2xozFfhYiNzqRkAaf3ETwl7bXIAqF6PQLiW5aLpL3OELpszq9oT6g8/GHsN/l2sznccI5s4HWl/XaT3zGvsYekrFqkJZkf+2QuFx/YQF/+Cs7ySpySvDXBT1SLhESM/YlxI5+JfKirarT+5als3VA9cq7C0ZIeoOjc8Hhf3pebQhn/rMpvVacDXaZLCENxRPcaALlxI5PotQfp/u1ffdY0l9+W27ul7ooVvFwhFn5XsOIuE2CBYDtA4EX8j4gb7t+E3FDeiYmt+Xlm9tdo+xJurG1DsjWtTIw/oTKViPd5BWY55/JqSu673JSH308lVas=)

**Comment by KaelWD** [comment] 2023-04-01 05:22
Duplicate of #16494

**Comment by yuwu9145** [comment] 2023-04-20 13:18
`item-value` must be "primitive only". It's the same behaviour as in v2.

**Closed by yuwu9145** 2023-04-20 13:18 UTC
Labels: duplicate
