### ISSUE TITLE
Form validation errors reset automatically if you have snackbar with close button on same page

### ISSUE THREAD

**Issue by eAdnan007** [vuetifyjs/vuetify#4692] opened 2018-07-23 12:12 UTC
If you have a form with validation(I used vee validate) and also a v-snackbar on the same page, the form errors will reset and you will get a clean form when the snackbar closes.

### Versions and Environment
Vuetify: 1.1.1
Vue: 2.5.16 
Browsers: Firefox Developer Edition 62.0b7 (64-bit)
OS: macOS High Sierra (10.13.6)

### Steps to reproduce
Show a snackbar which has close button when form validation fails. 

### Expected Behavior
Form errors should not be affected by snackbar

### Actual Behavior
All form errors go away and form goes to valid state

### Reproduction Link
https://codepen.io/eAdnan007/pen/djvgRW?editors=1010#0

---

Everything works perfectly if you remove just the close button on snackbar
https://codepen.io/eAdnan007/pen/mjWzaK?editors=1010#0

**Comment by KaelWD** [comment] 2018-08-21 08:13
Duplicate of baianat/vee-validate#1431

**Closed by KaelWD** 2018-08-21 08:13 UTC
