### ISSUE TITLE
[Bug Report] VCombobox doesn't show options in web component mode

### ISSUE THREAD

**Issue by TJBrunson** [vuetifyjs/vuetify#12408] opened 2020-10-12 18:40 UTC
### Environment
**Vuetify Version:** 2.3.13
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.6

### Steps to reproduce
1. Make vue app with vuetify.
2. Make component using v-combobox with items and a value
3. build using vue-cli-service with "--target wc" pointing at component
4. Load output  as a web component of a blank html document

### Expected Behavior
When focusing on combobox, Options should appear matching the "items" in the example. 

### Actual Behavior
No options appear. The drop down icon on the right side is also missing in web component builds.

### Reproduction Link
<a href="https://codepen.io/tjbrunson/pen/mdEedwm" target="_blank">https://codepen.io/tjbrunson/pen/mdEedwm</a>

### Other comments
I think this has to do with how Vuetify attempts to attach the options div to the body tag. In the case where this is being used inside a web component, the body tag is out of scope and it should instead be attached to the shadow-dom. 

This bug only exists when inside a web component. vue-cli builds a component as a web component with: 
vue-cli-service build --target wc --name test-component src/to/Component.vue

Also note, when building a component using vuetify as  a web component, the script tag of the .vue file must import vuetify and each vuetify component used in the file. components must be included in the "components" section of the script tag. vuetify must also be declared in the script tag section. Vuetify's min.css file must also be imported in the style tag section.

**Comment by KaelWD** [comment] 2020-10-13 06:39
Duplicate of #7622

**Closed by KaelWD** 2020-10-13 06:39 UTC
