### ISSUE TITLE
[Bug Report] Carousel does not lazy load its content

### ISSUE THREAD

**Issue by niutech** [vuetifyjs/vuetify#4521] opened 2018-07-06 23:15 UTC
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Add a `<v-carousel lazy></v-carousel>`.

### Expected Behavior
VCarousel items should be lazy loaded.

### Actual Behavior
VCarousel items do not use the `showLazyContent()` method.

### Reproduction Link
[https://codepen.io/anon/pen/jKgOZK](https://codepen.io/anon/pen/jKgOZK)

### Other comments
VCarousel uses the Bootable mixin, which provides the `showLazyContent()` method, but unlike VTabItem, VTooltip, VMenu, VListGroup, VDialog, VExpansionPanelContent, it does not use it anywhere.

**Comment by niutech** [comment] 2018-07-06 23:19
The [`lazy`](https://vuetifyjs.com/en/components/carousels#api) attribute is specified in the API, although it is only a [requested feature](https://github.com/vuetifyjs/vuetify/issues/2696), so the API is misleading.

**Comment by KaelWD** [comment] 2018-07-23 07:58
Duplicate of #2696

**Closed by KaelWD** 2018-07-23 07:58 UTC
