### ISSUE TITLE
[Bug Report] Form submission on enter keypress breaks when more than one v-text-field is present

### ISSUE THREAD

**Issue by Kelketek** [vuetifyjs/vuetify#3409] opened 2018-02-27 17:46 UTC
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Mac OS 10.13

### Steps to reproduce
In the codepen, select a field and press enter. Nothing should appear in the console. Remove one of the fields, and then press enter again. You should see 'I ran!' in the console.

### Expected Behavior
Pressing enter in the field should fire the submission event when there is more than one v-text-field

### Actual Behavior
Having more than one v-text-field prevents the submission of the form when pressing enter.

### Reproduction Link
[https://codepen.io/anon/pen/OQaKpR](https://codepen.io/anon/pen/OQaKpR)

**Comment by KaelWD** [comment] 2018-02-28 01:16
Duplicate of #2159

**Closed by KaelWD** 2018-02-28 01:16 UTC
