### ISSUE TITLE
[Bug Report] Search text field not vertical centered anymore and search icon disappearing on focus

### ISSUE THREAD

**Issue by florianrubel** [vuetifyjs/vuetify#4469] opened 2018-07-03 13:55 UTC
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Vivaldi 1.96.1147.47
**OS:** Linux x86_64

### Steps to reproduce
Just view the demo as shown on your page and have a look at the search bar in the toolbar. Also focus it to see the icon disappearing:
https://vuetifyjs.com/en/examples/layouts/googleContacts

### Expected Behavior
Icon changes color, but doesn't disappear. Textfield should be vertical centered.

### Actual Behavior
Icon desappears (or gets colord in primary color). Textbar sticks to the top

### Reproduction Link
[https://github.com/vuetifyjs/vuetifyjs.com/blob/master/src/examples/layouts/googleContacts.vue](https://github.com/vuetifyjs/vuetifyjs.com/blob/master/src/examples/layouts/googleContacts.vue)

### Other comments
happens

**Comment by KaelWD** [comment] 2018-07-03 14:09
Duplicate of #4453

See https://github.com/vuetifyjs/vuetify/issues/4463#issuecomment-402022784

Problems with documentation should be opened on https://github.com/vuetifyjs/vuetifyjs.com

**Closed by KaelWD** 2018-07-03 14:09 UTC
