### ISSUE TITLE
[Feature Request] Accesible v-date-picker with keyboard

### ISSUE THREAD

**Issue by israelfloresdga** [vuetifyjs/vuetify#6859] opened 2019-03-28 22:25 UTC
### Problem to solve
No keyboard key press can open the date/month picker.

### Proposed solution
Other solutions open the picker with the 'space bar', why not use that?

**Comment by jacekkarczmarczyk** [comment] 2019-08-01 20:29
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5629

**Closed by jacekkarczmarczyk** 2019-08-01 20:29 UTC
Labels: C: VDatepicker
