### ISSUE TITLE
Datepicker day circle not centered on iOS 10.3

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#1214] opened 2017-08-02 10:09 UTC
![image](https://user-images.githubusercontent.com/3471363/28868887-25c78bd8-777b-11e7-978a-d2635d65be56.png)

### Steps to reproduce
Screenshot taken on browserstack, iOS 10.3 simulator. I've tried it on an iphone 7 running 10.3 which has the same issue.

### Versions
vuetify 0.14.7

### What is expected ?
text centered in circle

### What is actually happening ?
not properly centered

### Reproduction Link
https://vuetifyjs.com/components/pickers

**Comment by razorfever** [comment] 2017-08-02 18:12
Centering issues with FABs in Safari too:

<img width="443" alt="fab" src="https://user-images.githubusercontent.com/5346684/28887778-1419a992-77c7-11e7-8f31-252b1b9453ce.png">

**Comment by Christilut** [comment] 2017-08-02 18:14
FAB centering is fixed #1162

I don't know if that one solves datepicker too

**Comment by ChavaSobreyra** [comment] 2017-08-02 19:06
Just checked on iPhone 7 plus iOS 10.3.3 on Chrome and Safari. Unable to reproduce FAB or calendar issue.

**Comment by Christilut** [comment] 2017-08-02 19:09
I'll check both again tomorrow and confirm

**Comment by johnleider** [comment] 2017-08-02 22:26
Fixed with #1162

**Closed by johnleider** 2017-08-02 22:26 UTC
Labels: pending review
