### ISSUE TITLE
[Bug Report] Text field's label does not adjust according to prefix

### ISSUE THREAD

**Issue by leonardo-sj** [vuetifyjs/vuetify#3485] opened 2018-03-07 02:14 UTC
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.13.3

### Steps to reproduce
1. Just see the text field in the reproduction link. The prefix is overlapping the label.

### Expected Behavior
1. The label should adjust itself to the right to avoid collision.

### Actual Behavior
1. The prefix overlaps the label.

### Reproduction Link
[https://codepen.io/johnjleider/pen/bgJOrX](https://codepen.io/johnjleider/pen/bgJOrX)

**Comment by jacekkarczmarczyk** [comment] 2018-03-07 02:28
Codepen is empty, you need to save it first

**Comment by leonardo-sj** [comment] 2018-03-07 03:29
@jacekkarczmarczyk Done ! I thought the autosave was enabled.
https://codepen.io/anon/pen/BYXmpz

**Comment by jacekkarczmarczyk** [comment] 2018-03-07 03:44
Weird, regression or it wasn't fixed in 0.17?
https://github.com/vuetifyjs/vuetify/issues/1620#issuecomment-364528407

Also the text in the input is higher than the prefix
![image](https://user-images.githubusercontent.com/15625235/37072461-4a40145c-21f4-11e8-98d3-be25b287a969.png)

Might be already resolved by https://github.com/vuetifyjs/vuetify/pull/3469

**Comment by KaelWD** [comment] 2018-03-07 03:44
There's also #760

**Comment by jacekkarczmarczyk** [comment] 2018-03-08 11:14
If I understand correctly it's intended

![image](https://user-images.githubusercontent.com/15625235/37148303-921a4f64-22fc-11e8-92e8-fe78c2b3a9dd.png)

**Comment by KaelWD** [comment] 2018-03-08 12:41
> Supporting a dynamic prefix length is actually quite difficult

Even with flexbox? Seems like it should be fairly simple at first glance.

**Comment by creativenoobie** [comment] 2018-09-17 15:38
@KaelWD Any updates on this?

**Closed** 2018-11-05 15:22 UTC
Labels: S: has PR, T: bug
