### ISSUE TITLE
Stepper content jumping to top of container on transition.

### ISSUE THREAD

**Issue by dwyer14** [vuetifyjs/vuetify#1423] opened 2017-08-20 02:32 UTC
### Steps to reproduce
1. Visit [the Steppers documentation](https://vuetifyjs.com/components/steppers).
2. In **Example 1**, use the console to adjust the first grey card to `height:300px;`.
3. Click the **Continue** button; the outgoing/taller block jumps, or gets shoved to the top of the container.

### Versions
Windows 10
Chrome (latest)
Vuetify 0.14.11

### What is expected ?
A horizontal transition, with no (or limited) vertical movement from the outgoing stepper-content. It would, in my opinion, be fine to "crop" off the bottom of the outgoing content, but it's jarring to have it hop upwards.

### What is actually happening ?
A horizontal transition, with outgoing stepper-content suddenly jumping to the top of its container. Guessing that its position is switching to `absolute`?

### Reproduction Link
https://vuetifyjs.com/components/steppers
Here's a screenshot, mid-transition:

![grab](https://user-images.githubusercontent.com/13950848/29491605-dbb6f220-852d-11e7-81a2-4911fbe44ce9.jpg)

**Comment by nekosaur** [comment] 2017-08-20 10:02
Duplicate of #943

**Closed by nekosaur** 2017-08-20 10:02 UTC

**Comment by dwyer14** [comment] 2017-08-20 15:20
@nekosaur Ahh, apologies. Searched for this but had filtered to only show bug-labeled issues. Thanks!
