### ISSUE TITLE
[Bug Report] Dialog container has display: none

### ISSUE THREAD

**Issue by yooneskh** [vuetifyjs/vuetify#9176] opened 2019-10-02 05:39 UTC
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Linux x86_64

### Steps to reproduce
Put any dialog in version 2.1.0

### Expected Behavior
Dialog to be shown

### Actual Behavior
We can see only the overlay not the dialog content

### Reproduction Link
<a href="https://codepen.io/yooneskh/pen/zYOgZBR" target="_blank">https://codepen.io/yooneskh/pen/zYOgZBR</a>

**Comment by KaelWD** [comment] 2019-10-02 05:52
Duplicate of #9175

**Closed by KaelWD** 2019-10-02 05:52 UTC
Labels: triage
