### ISSUE TITLE
[Bug Report][3.0.5] v-combobox items not lazy loaded

### ISSUE THREAD

**Issue by mavyfaby** [vuetifyjs/vuetify#16299] opened 2022-12-20 06:48 UTC
### Environment
**Vuetify Version:** 3.0.5
**Last working version:** 2.6.12
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Create a combobox
2. Fill it with many items (e.g. 10 items or up)

### Expected Behavior
1. Items should be lazy loaded upon clicking the combobox.
2. Menu items fills the whole screen.

### Actual Behavior
All items are loaded and causes lag when clicking the combobox.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9Udlu2zAQ/JUtX9ICFhk06YvqFEnv9D7SMwwC2V7HbMQD5Nq1Yfjfu5Tk1HGQ6Ekzs5gZjU6X4igEOZuiKEU/DaMJBAlpGp5oZ2zwkWAJEcewgnH0Fnb4dEc7AO2G3iWCGokwJjgALY6ePnv+4uWr18dv3r57/+Hjp89fvp58+/7j56/fWsgUakP3tdDigXZ91WZxCgNCG+qKkBFAf1ZUIccDPwxsZVyHGjz0duAHfr6mAOpqgPWBFsfsk+AEE3HKlVqaTLPcNf2vqXWI2kjJoM3vq41eDBMt6vwqZ4WfYayrxfk5b0DoiKl1rSsOltnOVvNiguZiQiXs7e6HOdxrZ634Ah5rt2rGaKxFT7QatwnyT/KOf0rjojuBy5etb+b4V2SsxYQopFKpqQuXF5KbqEPWVJw6MhaLkbeHe/Kh3H+kRibRJi8x2WIQ/d+EkRO16G2YkxkvbgvoZPbdlZ1tR2XLG1aK/XmzIqIbYcR4Z++t22vdt7Qb/XMmT7riLWvjLtPWjMPUTHh6lk9WPdFa83HzHeLsH3DSA6w=)

### Other comments
This issue causes lag when clicking the combobox.

**Comment by KaelWD** [comment] 2022-12-20 11:08
Duplicate of #2660

**Closed by KaelWD** 2022-12-20 11:08 UTC
Labels: S: triage
