### ISSUE TITLE
[Bug Report][3.7.5] [V-Combobox] Selection of entry doesnt work for key type string

### ISSUE THREAD

**Issue by mueller-jens** [vuetifyjs/vuetify#20774] opened 2024-12-11 07:48 UTC
### Environment
**Vuetify Version:** 3.7.5
**Vue Version:** 3.5.13
**Browsers:** Edge 131.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a v-combox with objects, where the key is a string. If you set the model-value to a key, the key is shown not the title.

### Expected Behavior
The title will be shown

### Actual Behavior
The key is shown

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdkE1uwyAQha8yYuONXatdIhKpitRLxFlgZ1qhDj8CjFpFuXuB2LXbDYL3zbwZ3vnGgp/6V+ee0oyMMxFRO5IRj4MBEKmTztVrfUzWRKkM+kVaRD3a0X6tEgDX9orUJUkzHgam08A2SHJEyuppbdsxVaZ76/4qXVSRipGRGv+X/075xO894wWGrJ9vmXBonpsWigFvTpLUu/VGyebewoJfVgzNG1mvrhleNsOj6LefroFUaZ9IUR6BiX4XpAiTVy5CwDi7HID5yHvFMLDalC1CBJ3gULYorY/yDNm9NTNRPS4/HGuF7w==)

**Comment by KaelWD** [comment] 2024-12-11 07:49
Duplicate of #5479

**Closed by KaelWD** 2024-12-11 07:49 UTC
Labels: S: triage
