### ISSUE TITLE
v-text-field multi-line placeholder overlaps label

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#1130] opened 2017-07-25 11:17 UTC
### Steps to reproduce
See codepen

### Versions
Vuetify 0.14.6

### What is expected ?
No overlap

### What is actually happening ?
Placeholder text and Label overlap only for multi-line textfields

### Reproduction Link
https://codepen.io/anon/pen/gxbwoW

**Comment by johnleider** [comment] 2017-07-25 17:53
Duplicate of #1119

**Closed by johnleider** 2017-07-25 17:53 UTC
Labels: bug, duplicate
