### ISSUE TITLE
[Bug Report] Outlined Input - outline overlapping label when data set during a transition

### ISSUE THREAD

**Issue by pklitscher** [vuetifyjs/vuetify#8343] opened 2019-08-07 08:22 UTC
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
1.  `<v-window>`  with two windows. First contains button to transition window, second contains `<v-text-field outlined>`,  `<v-window eager>` has eager prop
2. Set window to first window 
3. Set  `<v-window>` to second window and update v-model of `<v-text-field outlined>` in the same call
4. Window transitions and label is overlapped by input's outline

Also achieved by removing "eager" and transitioning the window back and fourth twice. 

Use case: 
Window 1 contains a list of entities
Window 2 contains a form that modifies an entity 
Entity values are set as a entity is selected and window transitions. 

### Expected Behavior
The label should not be overlapped

### Actual Behavior
Outline of input will overlap it's label 

### Reproduction Link
<a href="https://codepen.io/pklitscher/pen/gVvjwZ?editors=1010" target="_blank">https://codepen.io/pklitscher/pen/gVvjwZ?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-07 08:23
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7470

**Closed by jacekkarczmarczyk** 2019-08-07 08:23 UTC
Labels: triage

**Comment by pklitscher** [comment] 2019-08-07 08:36
Sorry guys, I totally missed those, no idea how.

**Comment by usmanarain350** [comment] 2024-10-17 05:49
Vue component method to handle autofill for email and password fields
```
mounted() {
  this.checkAutofill();
},

methods: {
  checkAutofill() {
    // Select only the email and password input fields for autofill detection
    const els = this.$el.querySelectorAll('input[type="email"], input[type="password"]');
    els.forEach((el) => {
      el.addEventListener('animationstart', (event) => {
        if (event.animationName === 'onAutoFillStart') {
          const label = el.parentElement.querySelector('label');
          // Add the active class to the label if it exists
          if (label) {
            label.classList.add('v-label--active');
          }
        }
      });
    });
  },
}
```
Add the following to your CSS:

```
@keyframes onAutoFillStart {}
input:-webkit-autofill {
  animation-name: onAutoFillStart;
  animation-duration: 0.01s;
}
```
