### ISSUE TITLE
[Bug Report] Overlay not clearing immediately. I have used overlay as loader and loader is stopping properly but overlay is still coming with 0 opacity. I've seen this using inspect

### ISSUE THREAD

**Issue by ETSmukesh** [vuetifyjs/vuetify#10678] opened 2020-02-26 07:03 UTC
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 77.0.3865.120
**OS:** Linux x86_64

### Steps to reproduce
Can't reproduce because we're facing it in our local development.

### Expected Behavior
0 Opacity overlay should be removed.

### Actual Behavior
Overlay not removing.

### Reproduction Link
Can't create a reproduction link because we're facing it in our local development. We're getting this error in this vuetify version only.

### Other comments
Also, v-menu not closing with this version.

**Comment by jacekkarczmarczyk** [comment] 2020-02-26 09:33
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10668

**Closed by jacekkarczmarczyk** 2020-02-26 09:33 UTC
Labels: triage
