### ISSUE TITLE
[Feature Request] `mandatory` attribute of v-list should be applied on using `v-list-group` as well

### ISSUE THREAD

**Issue by daenamkim** [vuetifyjs/vuetify#18573] opened 2023-11-01 10:57 UTC
### Problem to solve
I want group list to select the first list item under the group if there is nothing selected.

### Proposed solution
If  `mandatory` is enabled it would be good to select the first group and the first list item of it. And it would be great that it is highlighted and the group is open for the selected.

**Comment by KaelWD** [comment] 2023-11-01 11:24
Duplicate of #7365

**Closed by KaelWD** 2023-11-01 11:24 UTC
Labels: S: triage
