### ISSUE TITLE
not working link inside of the current dev docs

### ISSUE THREAD

**Issue by ram-you** [vuetifyjs/vuetify#819] opened 2017-06-23 07:19 UTC
https://dev.vuetifyjs.com/components/grid-lists 
broken link

**Comment by dohomi** [comment] 2017-06-23 07:26
@ram-you where did you find this link?

**Comment by dohomi** [comment] 2017-06-23 07:26
update: just found it..

**Comment by johnleider** [comment] 2017-06-23 10:52
I haven't created it yet.

**Comment by johnleider** [comment] 2017-06-23 12:58
Thank you for the report, but closing this as it is not a bug, I just haven't had a chance to add those docs to dev yet :)

**Closed by johnleider** 2017-06-23 12:58 UTC
