### ISSUE TITLE
[Bug Report] vtextfield prefix is overlayed with label

### ISSUE THREAD

**Issue by pcornelissen** [vuetifyjs/vuetify#9142] opened 2019-09-28 18:24 UTC
### Environment
**Vuetify Version:** 2.0.19
**Last working version:** 2.0.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Linux x86_64

### Steps to reproduce

 
 
```
                   <v-text-field
                            prepend-icon="mdi-facebook-box"
                            v-model="value.contactInfo.facebook"
                            label="Facebook" prefix="https://facebook.com/"></v-text-field>
 
```

### Expected Behavior
either label is never always above the textfield when a prefix is given or as before it's placed right of the prefix

### Actual Behavior
This leads to a text box where the facebook url is drawn on the same location as the label.

### Reproduction Link
<a href="http://codepen/not/available" target="_blank">http://codepen/not/available</a>

**Comment by pcornelissen** [comment] 2019-09-28 18:28
Hmm, it was broken, I downgraded to 2.0.14, then it was OK and now it's ok for 2.0.19 as well. I'm puzzled!
Sorry for the issue, closing it now!

**Comment by pcornelissen** [comment] 2019-10-01 06:51
![image](https://user-images.githubusercontent.com/1177440/65940368-a5067780-e428-11e9-8c93-cea7fea613fa.png)
I don't know why, but it's back

**Comment by johnleider** [comment] 2019-10-24 17:00
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

You can find information on how to contribute to vuetify [here](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md).

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by pcornelissen** [comment] 2019-11-05 18:23
it's hard to reproduce as it disappears sometimes. I checked the sourcecode and it looks like a race condition when the label.left is calculated and as this doesn't change after the label has been created it will stick there. So it's related with #8176
I have the same component with vtextfields in two locations and the miscalculation seems to happen more often in a dialog, presumably because the left is calculated when the dialog is not visible yet, so left is 0.
I also have an icon in front and when the icon is loaded slowly de to a slow internet connection in the train, the fallback box font-character is shown, which is smaller than the icon, in this case the label is also misaligned by the amount of missing pixels and "collides" with the prefix in front.

**Comment by pcornelissen** [comment] 2019-11-05 19:39
https://codepen.io/pcornelissen/pen/gOOeWew

**Comment by jacekkarczmarczyk** [comment] 2019-11-11 06:33
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7470
As a workaround you can add `:key="step"` to `v-text-field`

**Closed by jacekkarczmarczyk** 2019-11-11 06:33 UTC
Labels: triage
