### ISSUE TITLE
[Feature Request] Expose the screen size ranges

### ISSUE THREAD

**Issue by SmootherSpike** [vuetifyjs/vuetify#4810] opened 2018-08-06 12:05 UTC
### What problem does this feature solve?
The screen sizes for lower and upper bound are not accessible through the $vuetify reference and they has to be defined for each project if someone needs them to do some custom elements/stylings, etc.. E.g. when using the html picture tag to define multiple srcset and stay compatible with the ranges from the framework.

### What is your proposed solution?
Refactor both _variables.styl and breakpoint.ts to read a .json where the bounds are defined to keep them consistent and maintainable in one place. To access the bounds of the defined screen sizes programmatically without declaring it in the project a third time. They can be retrieved via e.g. `$vuetify.screenSizes.xs.lower/upper`

**Comment by KaelWD** [comment] 2018-08-06 12:09
Duplicate of #4675 

Loading from json isn't really something we can do here, that's more an issue for https://github.com/vuetifyjs/vue-cli-plugin-vuetify

**Closed by KaelWD** 2018-08-06 12:09 UTC

**Comment by KaelWD** [comment] 2018-08-06 12:34
> have to be maintained in two places

Not a big deal, they aren't likely to ever be changed by us. Moving the definition to a json file would be a breaking change for anyone currently using the stylus variables. Loading from json is something you can implement into you own build setup with #4675.

**Comment by SmootherSpike** [comment] 2018-08-06 12:36
I do not think, that this would be any breaking change, since they are defined on the top of the _variables.styl

`json("../../config/screenSizes.json")
$grid-breakpoints := {
  xs: 0
  sm: unit(sm-lower, px)`

But i will keep an eye on the other issue

**Comment by KaelWD** [comment] 2018-08-06 13:50
Hmm, didn't realise you could do it like that. Maybe leave a comment on #4675.
