### ISSUE TITLE
[Bug Report][2.6.7] v-autocomplete wrong active item highlighting when using prepend-item slot

### ISSUE THREAD

**Issue by KeterSCP** [vuetifyjs/vuetify#15470] opened 2022-07-19 13:09 UTC
### Environment
**Vuetify Version:** 2.6.7
**Last working version:** 2.5.8
**Vue Version:** 2.7.7
**Browsers:** Chrome 103.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Open reproduction link
2. Expand autocomplete
3. Select from the bottom "fizz" or "buzz" items

### Expected Behavior
The only item that is currently selected is highlighted

### Actual Behavior
Item that is 2 indexes above is highlighted

### Reproduction Link
<a href="https://codepen.io/Keter_SCP/pen/qBoroww?editors=101" target="_blank">https://codepen.io/Keter_SCP/pen/qBoroww?editors=101</a>

### Other comments
Seems like it was broken in 2.5.9

**Comment by zourtney** [comment] 2022-08-23 18:12
Issue is still present in 2.6.9.

**Comment by KaelWD** [comment] 2022-10-11 02:22
Duplicate of #14489

**Closed by KaelWD** 2022-10-11 02:22 UTC
Labels: S: triage
