### ISSUE TITLE
[Bug Report] Stepper Component should match Material specification

### ISSUE THREAD

**Issue by aggarwaldev** [vuetifyjs/vuetify#7056] opened 2019-04-23 18:17 UTC
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Chrome 70.0.3538.77
**OS:** Linux x86_64

### Steps to reproduce
Open reproduction link and switch to mobile view.

### Expected Behavior
Horizontal Stepper should follow material guidelines:

Steps:
<img src="https://material.io/archive/guidelines/assets/0Bzhp5Z4wHba3UU1OWGpoZEZzY0k/components-acux-stepper-mbltypog.png" alt="Steps" width="200"/>

Dots:
<img src="https://material.io/archive/guidelines/assets/0Bzhp5Z4wHba3RmtucktsTHZjZjQ/components-acux-stepper-mbldots.png" alt="Dots" width="200" />

Progress Bar
<img src="https://material.io/archive/guidelines/assets/0Bzhp5Z4wHba3c3B1d3hPclRTYk0/components-acux-stepper-mblprgrssbr.png" alt="progress-bar" width="200" />

### Actual Behavior
Component is not responsive.

### Reproduction Link
<a href="https://codepen.io/anon/pen/ZZMNmK" target="_blank">https://codepen.io/anon/pen/ZZMNmK</a>

**Comment by KaelWD** [comment] 2019-04-24 04:11
Duplicate of #2682

**Closed by KaelWD** 2019-04-24 04:11 UTC
Labels: triage
