### ISSUE TITLE
[Bug Report] Datatable pagination object overwrites custom page

### ISSUE THREAD

**Issue by BorjaRafols** [vuetifyjs/vuetify#4949] opened 2018-08-24 13:55 UTC
### Versions and Environment
**Vuetify:** 1.1.14
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Linux x86_64

### Steps to reproduce
Watch console and see the pagination watcher getting triggered twice when the pagination object starts on a custom page { page: 3 } for example

### Expected Behavior
When I pass a pagination object to the DataTable component with custom initial state, like start on page 3, the pagination object should respect that page 3 and start on page 3

### Actual Behavior
When I pass a pagination object to the DataTable, the watcher of that object gets triggered twice, the first one respects the values I passed, and inmediately after it triggers the watcher again with default data

### Reproduction Link
[https://codepen.io/anon/pen/xawQEz](https://codepen.io/anon/pen/xawQEz)

### Other comments
This feature is important in case you want the table to initialize on another page which is not the first using URL parameters "/users?page=3&rowsPerPage=12

**Comment by ayZagen** [comment] 2019-06-18 12:57
This bug prevents us from querying data from url.

**Comment by VagnerGon** [comment] 2019-08-02 13:50
Possible duplicate of #3687

**Comment by nekosaur** [comment] 2019-08-09 17:49
Fixed in 2.0

**Closed by nekosaur** 2019-08-09 17:49 UTC
Labels: C: VDataTable, P: low, T: bug

**Comment by BRafols** [comment] 2019-08-09 18:01
Please put a notice in upgrade guide. 

I guess lots of users have made various workarounds for this.

**Comment by romucci** [comment] 2020-01-27 19:18
> Fixed in 2.0

How is this fixed in 2.0? I am having the same issue.

**Comment by nekosaur** [comment] 2020-01-27 19:27
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).
