### ISSUE TITLE
[Bug Report] Search not paginate

### ISSUE THREAD

**Issue by IgorDePaula** [vuetifyjs/vuetify#3322] opened 2018-02-18 11:59 UTC
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Ubuntu undefined

### Steps to reproduce
Try search an item, the pagination result is diferent when is no search, the not paginate, show only the per page value.

### Expected Behavior
Paginate the search result

### Actual Behavior
Try search an item, the pagination result is diferent when is no search, the not paginate, show only the per page value.

### Reproduction Link
[https://github.com/brasil-php/project-manager/blob/master/resources/assets/js/components/Project/List.vue](https://github.com/brasil-php/project-manager/blob/master/resources/assets/js/components/Project/List.vue)

### Other comments
When use the search, the datatables not paginate the results. Only paginate on change the perPage property.

**Comment by IgorDePaula** [comment] 2018-02-18 12:20
![captura de tela de 2018-02-18 09-19-06](https://user-images.githubusercontent.com/2833993/36351735-ff4152dc-148c-11e8-80ca-71a81b9aeb69.png)

**Comment by elton182** [comment] 2018-02-18 13:48
I can confirm this behavior.
I think the problem is the totalItems is with value "0".

**Comment by johnleider** [comment] 2018-04-01 20:17
Resolved by https://github.com/vuetifyjs/vuetify/commit/e57229d09e33a920575f0fdaa3c4b2edff513d4f

**Closed by johnleider** 2018-04-01 20:17 UTC
Labels: bug
