### ISSUE TITLE
[Bug Report][3.1.6] VRangeSlider thumb not moving

### ISSUE THREAD

**Issue by Caster000** [vuetifyjs/vuetify#16769] opened 2023-02-24 09:39 UTC
### Environment
**Vuetify Version:** 3.1.6
**Last working version:** 3.0.5
**Vue Version:** 3.2.45
**Browsers:** Chrome 110.0.0.0
**OS:** Linux

### Steps to reproduce
Slide the slider-thumb

### Expected Behavior
The slider-thumb should slide with the mouse

### Actual Behavior
The slider-thumb doesn't slide

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUttu2zAM/RVOe+hLbKdJN2CZV3QYsJ+o+uALk6iVJUGik3RB/n2UFWdJ2g0YAgcmzyHPIc3HvfjuXL7pUSxEGRqvHEFA6t29NKpz1hPsweMSDrD0toMbpt5II01ZJDbzOCDsnK4IOQIoN5m3W3juA6nl6zcpGjSEXooBHfDGauAnMHh3yiek8u0YQuRYz6SPsx+zn/O5FGeQrkKsb6whb3XWoemBcEfZKDdyT+2TtcqsMAtatejvy+IqcXLCQLQyWo6h1Wm8WGO3/F4WZ3NzGOhVI4TGOoyF+YW1faytrWeVBdy6HQTLkrBdK8KvEfuVKdPijsHpFD6k5VeGBuwQ/+KTN9oGzOqeyJrUE8Cr1ZoWMB2oAGTdnyAp8pCt6gOnh98s/7JZXxI0LrnFe75OlNqyaPc+iQ0ONxE3wKOLiUgDZF3l8udgDd/X4FYegSDFYvQvBV9VjKVYE7mwKIreuJcVL7ArHhgrfG9IdZi1tnuY57P87lPRqkDn+RxDl9X8YQJ6VpRictY8HuLfBI4w973NP6e2x1SmqzrEvm/6FSyyiWtF/mQ+Hts/zF9xLwa4wt4McdztgReqlXkJV7tswrDHx9Ha/083dIjlT1HlMBHJHesNFeLpNz0NWpc=)

### Other comments
It seems to bo broken since v3.0.6 (checked in the playground).
Maybe the bug came from modification made on VSlider?
Commits from v3.0.6 about Vslider:
- VSlider: correct first and last ticks position when vertical ([61d6cdb](https://github.com/vuetifyjs/vuetify/commit/61d6cdbb9bb52f99883675b7aaf01a00410dd543))
- VSlider: don't use logical inset to position thumb ([a681c88](https://github.com/vuetifyjs/vuetify/commit/a681c889529108c853cd63c0634d832861036290)), closes #16282 #16283

**Comment by KaelWD** [comment] 2023-02-24 13:16
Duplicate of #16598

**Closed by KaelWD** 2023-02-24 13:16 UTC
Labels: S: triage
