### ISSUE TITLE
[Bug Report] high performance impact when using a lot of v-text-field

### ISSUE THREAD

**Issue by stygmate** [vuetifyjs/vuetify#6201] opened 2019-01-18 17:16 UTC
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Google Chrome
**OS:** Mac OS 10.13.6

### Steps to reproduce
just input one char in one of the field while doing performance recording in chrome devtools.
Mesurement 1: with the exact codepen
Mesurement 2: removing all text-field except one
Mesurement 3 only one text-field but with @input="(value)=>this.field1=value" (for having just one half of the v-model behaviour)
Mesurement 4: with the 20 text-field replaced by standard input

### Expected Behavior
Only have one text-field updated on each keypress.

### Actual Behavior
Mesurement 1: 21,54ms
Mesurement 2: 2,98ms
Mesurement 3: 0,98ms
Mesurement 4: 1,94ms

### Reproduction Link
<a href="https://codepen.io/stygmate/pen/zyVagj" target="_blank">https://codepen.io/stygmate/pen/zyVagj</a>

### Other comments
I test here with only 20 text-field but in my app i have 20 text-field by people concerned by the form and the mesurement are done on a macbook pro 2018. On my phone huawei p9lite typing on keyboard in a field can lag a lot.

**Comment by stygmate** [comment] 2019-01-18 17:19
mesurement 1
![mesurement 1](https://user-images.githubusercontent.com/1467305/51402295-686e4680-1b4d-11e9-842a-df35533f182b.png)
mesurement 2
![mesurement 2](https://user-images.githubusercontent.com/1467305/51402320-73c17200-1b4d-11e9-980a-931e1225a289.png)
mesurement 3
![mesurement 3](https://user-images.githubusercontent.com/1467305/51402345-7f149d80-1b4d-11e9-874c-cd6171042269.png)
mesurement 4
![mesurement 4](https://user-images.githubusercontent.com/1467305/51402359-8a67c900-1b4d-11e9-9ed4-cf379cc27ef7.png)

**Comment by DRoet** [comment] 2019-01-18 21:36
I have noticed this in the past as well with many v-select elements, even when they all had the same `items` value. I worked around it for now but I figured I'd leave this comment here in case someone want to take a look at optimizations.

**Comment by stygmate** [comment] 2019-01-21 08:19
Any news on this? It really blocks my app development as I don’t know if I can rely on classic usage of v-model.

**Comment by StefanFeederle** [comment] 2019-01-22 17:00
I also encountered performance problems when using many v-selects.

**Comment by stygmate** [comment] 2019-01-23 10:48
maybe related to vue: https://github.com/vuejs/vue/issues/6898
will not be fixed until vue 3... any workaround ?

**Comment by stygmate** [comment] 2019-01-23 11:48
We have to found a workaround. it make Vuetify useless in case of consequent forms usage by lambda people. we are developer and many of us have decent computer but it's not always the case for most users.

**Comment by DRoet** [comment] 2019-01-23 11:51
Yeah seems like an upstream vue issue, tracked in https://github.com/vuejs/vue/issues/6351. I guess we will have to wait untill 3.0 : /

**Comment by stygmate** [comment] 2019-01-23 13:21
@MajesticPotatoe Hi ! why removing "critical" tag ? It's a Vuetify usage breaker for big form ! In my case the front as to be used by any surfer with any computer / phone configuration and the laggy input due to this bug are so bad that it will let the users with the filling of no confidence in the service.
if no one resolve this i have two choices: resolve the problem myself (unknown time of work) / pay some of you to work on a workaround for it to work with the actual vue version ... :(

**Comment by stygmate** [comment] 2019-01-23 13:58
@MatthewAry so i think the correct way to react is to code a WorkAround 💡
Discovering that i can't release to production a full App because of that is weird.
we can't wait 6/12/18/... months for vue 3 to maybe correct that.

**Comment by johnleider** [comment] 2019-01-23 14:18
Inputs are being updated as part of v2.0 and I will be looking to see if there are things we can do to alleviate this burden. Thank you for your patience.

**Comment by stygmate** [comment] 2019-01-27 13:09
@johnleider seems that Vue 2.6beta2 can adress our issue.
https://github.com/vuejs/vue/pull/9371#issue-247798326
But it may need some change in Vuetify code. Can you easily make all slots become scoped slot and using new v-slot syntax ?
I let you read the comment on the vue merge.

**Comment by DRoet** [comment] 2019-01-27 13:14
@stygmate John pretty much said on discord that if the changes in 2.6 are significant enough, they might take some parts of the framework and convert them to the new slot syntax for a `1.6` release

**Comment by stygmate** [comment] 2019-01-27 13:50
@DRoet I hope that this update will arrive as soon as possible. It would be like a Christmas gift that will (partially) deliver me from the pressure that I have for the release of my app. And anyway it will make the scaling capacity of Vuetify better for everyone / every project.

**Comment by stygmate** [comment] 2019-02-11 09:41
@johnleider hi, considering the recents change in vue 2.6 (new v-slot), can this issue be moved to 1.6 milestone ?

**Comment by anaxmedia** [comment] 2019-03-17 01:35
@johnleider  Is there a workaround for this in the meantime? I have an app that is heavily form based and one of my forms has approximately 100 fields and performance is extremely laggy. Validation is handled server-side.

**Comment by stygmate** [comment] 2019-03-21 08:09
@johnleider any news ?

**Comment by stygmate** [comment] 2019-03-22 09:29
@MajesticPotatoe @DRoet @StefanFeederle @MatthewAry @anaxmedia @sh7dm Problem still here 2 months later in Vuetify 1.5.7 with Vue 2.6.10. Please @johnleider can you take some time to check if it can be resolved easily now, at least wrote to us a little message to let us know the evolution.

**Comment by johnleider** [comment] 2019-04-01 02:23
Hey everyone, I am tracking the issue. This is an on-going effort that primarily depends upon an upstream change. The 2.6 release of Vue has little effect on this particular component as we aren't even using slots except for labels.

I tested a few things to see how performance was and it is bad, but, unless one of you has a workaround, this will have to wait for changes from Vue as I'm out of ideas..

**Comment by anaxmedia** [comment] 2019-04-01 14:30
@johnleider thanks John , we appreciate the communication. Is there anything we can provide the Vue team? Do we know if this is something that they are tracking/working on, or even know is a performance problem?

**Comment by dojyorin** [comment] 2019-04-10 02:21
My application used more than 50 `<v-text-field>`, and the same problem occurred.
(It's very very heavy :sob:)

So, I tried using `:value=""` binding and `@change=""` event instead of v-model, the performance became some practical.

```html
<v-text-field
    :value="foo.bar"
    @change="v => foo.bar = v"
></v-text-field>
```

**Comment by internalfx** [comment] 2019-04-11 04:11
Why does the `@change` event perform so much better?

**Comment by jacekkarczmarczyk** [comment] 2019-04-11 05:38
Because it's not triggered on every key stroke

**Comment by dojyorin** [comment] 2019-04-11 08:07
> Why does the `@change` event perform so much better?

> Because it's not triggered on every key stroke

Yes.
In the case of "@input", a slow task runs with each key input, but with "@change", it runs only when the focus is out, so stress at key input is reduced.
However, as the problem has not been solved, there is a demerit that it will lag for a moment when the focus goes out.

**Comment by besnikh** [comment] 2019-04-14 04:35
Looking forward for this problem to be solved :( until now I though it's only my issue, so a little google and I found out this. 

My solution at this time for me is just to use @change but many times I need the @input but :( have to wait.

Will be watching this for updates. 

Cheers

**Comment by stygmate** [comment] 2019-04-15 05:46
As we need help to resolve this, can someone of the crew pin this issue on Dashboard ?
It seems we are a lot to be affected without knowing if it's our code or Vuetify's code (my case before writting this issue, case of besnikh).

**Comment by besnikh** [comment] 2019-04-16 02:22
@stygmate I agree

In my case, my web app is published in production, and I have been receiving some complains from people that the app is running slow, me knowing the issue I am blaming their Samsung phone :) 

I tested several times, and that's true though.. this issue is more obvious when used in mobile for Android devices. 

But, would gladly help to fix this issue but not sure as you mentioned where to start, Vueitfiy is saying it's not their code but how Vue works.. so not sure.

Cheers

**Comment by stygmate** [comment] 2019-04-16 14:18
> But, would gladly help to fix this issue but not sure as you mentioned where to start, Vueitfiy is saying it's not their code but how Vue works.. so not sure.

@besnikh it seems a problem with how vue handle slots. in some case (ours) when vue refresh a slot it refresh parents component and then parents and ... 😨 
v-text-field is based on v-input and use slots for all it's sub-components.
excuse me for the short explaination (i don't have time now) but you can found some hints in linked issues.

**Comment by stygmate** [comment] 2019-04-21 16:06
@besnikh @johnleider i have relaunched the discuss at: https://github.com/vuejs/vue/issues/6351#issuecomment-485232248

**Comment by stygmate** [comment] 2019-04-22 07:45
@johnleider It seems this issue will not be resolved before version 3 of Vue ...
Is it difficult to write flattened version of v-text-field / v-select /... not based upon v-input ?
or some kind of precompilation of v-input based components for avoiding using slots ?

**Comment by KaelWD** [comment] 2019-06-07 14:55
I was wrong about the slots thing, it's https://github.com/vuejs/vue/issues/7257 and https://github.com/vuejs/vue/issues/10115 combined with a very large render function. We may be able to improve this by caching as much as possible, but vue is still going to diff the DOM every time the parent updates. 

Workaround isn't ideal, you have to wrap each input in its own component and only pass props and events, without using `$attrs` or `$listeners`.

**Comment by 1010101110** [comment] 2019-06-21 17:49
i use a single page form, users want to see all fields on same page without paginating. 

i was having problems with text input lag as described here so i thought i would provide my real world example.

### using all v-models
big oof  ~150ms per keypress
https://codepen.io/anon/pen/QXpqZG = https://i.imgur.com/8n3pmi4.png

### using all :value and @change
keypress not laggy anymore yay ~5ms per keypress
https://codepen.io/anon/pen/pXedPL = https://i.imgur.com/GlVDBeg.png

**Comment by hereiscasio** [comment] 2019-07-01 15:00
@stygmate 

i made a example below to demo how slow when we want to click on checkbox : 

https://codepen.io/hereiscasio/pen/MMQLwv?&editable=true&editors=101

it so slow that . . . do u know what happened when we click on it ?

why it so slow ? i think my demo related this issue u opened for ?

**Comment by stygmate** [comment] 2019-07-01 15:05
> @stygmate
> 
> i made a example below to demo how slow when we want to click on checkbox :
> 
> https://codepen.io/hereiscasio/pen/MMQLwv?&editable=true&editors=101
> 
> it so slow that . . . do u know what happened when we click on it ?
> 
> why it so slow ? i think my demo related this issue u opened for ?

@hereiscasio It don't seem to be related to this issue. After a very quick look at it: I think you ask for displaying too much img at the same time.

**Comment by hereiscasio** [comment] 2019-07-01 15:14
> > @stygmate
> > i made a example below to demo how slow when we want to click on checkbox :
> > https://codepen.io/hereiscasio/pen/MMQLwv?&editable=true&editors=101
> > it so slow that . . . do u know what happened when we click on it ?
> > why it so slow ? i think my demo related this issue u opened for ?
> 
> @hereiscasio It don't seem to be related to this issue. After a very quick look at it: I think you ask for displaying too much img at the same time.

yes, there're two issues there, what i point out is the later one, after u success to open dialog, u can try to check on checkbox, and u will see what happen, 

Don't u think "use too many v-text-field" & "use too many v-checkbox" are the related issue ?

So did u mean u actually don't know what happen once i check on checkbox ? 
I'm really interest about this, but just don't get the idea what happen

**Comment by 1010101110** [comment] 2019-07-01 15:28
if you take out the v-model the checkbox click works correctly. so yes i think it is the same.

`                  
`
`
                  <v-checkbox @change="check($event,contact)">
                  </v-checkbox>
`

https://codepen.io/anon/pen/MMVJxM

**Comment by hereiscasio** [comment] 2019-07-01 15:33
> if you take out the v-model the checkbox click works correctly. so yes i think it is the same.
> 
> (the overall page performance is still slow by loading so many list tiles instead of paginating.)
> 
> ` <!--<v-checkbox v-model='contactsForForwarding' :value='contact.name' > </v-checkbox> -->`
> `<v-checkbox @change="check($event,contact)"> </v-checkbox>`
> 
> https://codepen.io/anon/pen/MMVJxM

Yes, i know, i

 just curious that what happen when i click on one of thousand of checkboxs if i use v-model on them

**Comment by 1010101110** [comment] 2019-07-01 17:05
in chrome dev tools performance tab, hit record, click checkbox, wait for check to finish, hit stop, then click / zoom into the click event to see what happens.  https://i.imgur.com/e1SLJ2f.png

in the [linked issue](https://github.com/vuejs/vue/issues/6351) it is explained that the whole parent component is re-rendered. (so it takes a while to re-render your list)

[In vue3 update](https://medium.com/the-vue-point/plans-for-the-next-iteration-of-vue-js-777ffea6fabf)  the issue should be fixed:

> Improved slots mechanism: All compiler-generated slots are now functions and invoked during the child component’s render call. This ensures dependencies in slots are collected as dependencies for the child instead of the parent. This means that: 1. when slot content changes, only the child re-renders; 2. when the parent re-renders, the child does not have to if its slot content did not change. This change offers even more precise change detection at the component tree level, so even fewer useless re-renders!

**Comment by KaelWD** [comment] 2019-07-02 00:28
I wish I could pin comments in issues

https://github.com/vuetifyjs/vuetify/issues/6201#issuecomment-499917110

**Comment by hereiscasio** [comment] 2019-07-02 09:12
After looking into @KaelWD & @1010101110 comments just above, 

yap, i think the demo i presented related to this issue
> 
> ignore the large list rendering at once, actually, 
> for some usage scenario, this is be solved by applying virtual-scrolling
> e.g. user want to forward some message 

because, 

when i toggle on one of the thousand of checkboxs ( assume i use ` v-model ` on all of them )
the ` v-model ` bounded reactivity variable is changed in parent component,
ideally, it should only re-render the certain checkbox which i toggle just before 
but, as @KaelWD said, "pretty much everything uses $attrs somewhere"

so it finally cause re-render all the child components, 
and there was a large list, **_Vue_** also re-render it again, 
that's why we will see the toggling speed on checkbox is soooooo slow 😔

**Comment by hereiscasio** [comment] 2019-07-02 09:34
found, see [here](https://github.com/vuetifyjs/vuetify/blob/9f47fe560b73173b07527d4fbb7051b4300fae28/packages/vuetify/src/components/VCheckbox/VCheckbox.js#L69)

**Comment by adrchw** [comment] 2019-08-21 12:09
split big components to couple small to avoid delay in rendering. 
check this: [https://stackoverflow.com/questions/41042641/vue-js-2-0-slow-when-modifying-unrelated-data](https://stackoverflow.com/questions/41042641/vue-js-2-0-slow-when-modifying-unrelated-data)

**Comment by Mikilll94** [comment] 2019-08-26 19:06
@adrchw

And is it really working? I want to see some tests which proves that.

Also, you can't always split your large form into subcomponents. Often I have one giant form which needs to be sent to the server in one piece.

**Comment by Mikilll94** [comment] 2019-08-30 21:13
Hey guys,
I have just found a solution to this problem.

Simply just stop using Vuetify and use Quasar

In Quasar using a lot of text fields does not cause performance issues.
Just look at this code pen:

https://codepen.io/mikilll94/pen/NWKvjXY?&editable=true&editors=111

Everything works like a charm!!!

So if guys in Quasar have achieved nice performance of complex forms, in Vuetify this should be also possible.

**Comment by Mikilll94** [comment] 2019-09-01 09:49
Hey, I don't understand why my previous comment was marked as spam. I think this a serious problem with Vuetify and it is still not solved. However in Quasar, it is somehow working - there are no problems with performance.

**Comment by sh7dm** [comment] 2019-09-01 12:23
@Mikilll94 moving to another framework isn't a solution for issue in Vuetify. This won't fix framework bug!

**Comment by KaelWD** [comment] 2019-09-01 13:02
@Mikilll94 if you run a performance profile on the quasar example you'll see it isn't actually that much faster, and it's a much more basic component. The have the same problem as us just with less features so it isn't as noticeable.

**Comment by mandaputtra** [comment] 2019-09-12 06:44
The issue I still there, the workaround that works for me was split big form components into smaller ones, and use vuex to store form value. It will decrease lot of performance issue.

**Closed** 2019-09-23 14:38 UTC
Labels: C: VTextField, P: critical, T: bug, performance, upstream

**Comment by Mikilll94** [comment] 2019-09-23 17:37
Wow! Congrats! It's awesome that this problem was solved.

Do you plan to include these changes also in Vuetify 1.x? Because for medium and large projects migrating from 1.x to 2.x is very difficult.

**Comment by johnleider** [comment] 2019-09-23 17:52
It's a pretty simple task, just monotonous. I'm very swamped atm with the upcoming release so unless @KaelWD wants to do it, it would have to wait until next month unless someone wants to PR it.

**Comment by dmoebius** [comment] 2019-09-23 19:43
Do you think it's a good idea to close this issue while the PR has 30 tests disabled?

**Comment by userquin** [comment] 2019-09-25 14:00
@johnleider, @KaelWD , can anyone confirm (or NOT) if the FIX will be applied to 1.5 branch?

**Comment by MajesticPotatoe** [comment] 2019-09-25 14:01
@userquin 
> It's a pretty simple task, just monotonous. I'm very swamped atm with the upcoming release so unless @KaelWD wants to do it, it would have to wait until next month unless someone wants to PR it.

**Comment by KaelWD** [comment] 2019-09-26 05:14
> can anyone confirm (or NOT)

No we cannot confirm. It may or may not be done at some point eventually.

**Comment by siegy22** [comment] 2019-10-10 06:56
Is this patch already included in 2.1.2?

**Comment by DRoet** [comment] 2019-10-10 07:44
> Is this patch already included in 2.1.x?

yeah pretty sure this landed in 2.1.0

**Comment by menthos984** [comment] 2020-03-23 01:15
I am currently using 2.1.0 but v-text-field has still performance issues. Input lag starts when I reached 40 and so on (my v-text-field is dynamically appended)

**Comment by vallemar** [comment] 2020-04-03 20:59
I am in the same situation, but my case is with v-select. I think I'm going to make a light homemade component .....

Real solution for this!

**Comment by ggedde** [comment] 2020-05-07 12:49
Same issue, I did change to bind value and use `@change` as mentioned above for many fields, but for others I needed realtime responses and validation so instead of `@change="v => (foo.bar = v)"` I am using `v-debounce="v => (foo.bar = v)"` from https://github.com/dhershman1/vue-debounce

**Comment by stygmate** [comment] 2020-05-07 12:52
@KaelWD why this issue is closed as it don't seems to be resolved ? I understand that it is an upstream issue, but maybe you can provided an integrated workaround.

**Comment by DRoet** [comment] 2020-05-07 16:09
the issue is closed because it did improve a lot in the 2.1.0 release, but maybe it is still not enough for some people. Vue 3.0 might allow for further performance improvements.

**Comment by quroom** [comment] 2020-12-04 00:55
https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model
With this feature, just make your own component.
```
<script>
import VTextArea from 'vuetify/lib/components/VTextarea/VTextarea.js'
export default {
  name: 'LazyTextArea',
  extends: VTextArea,
  model: {
    event: 'change'
  },
}
</script>
```

I made new component that doesn't update model when input event is fired.
It looks well.

**Comment by WieFel** [comment] 2023-02-13 10:28
Still experiencing the same problem on Vue `2.7.14`.

Working solution I came up with is to wrap (at least) the part containing the `v-text-field` with `v-lazy` (more info [here](https://vuetifyjs.com/en/components/lazy/)).
Like this, the v-text-fields are lazily loaded and for me the page works way smoother.
