### ISSUE TITLE
[Feature Request] Data tables component with the fixed toolbar

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#3153] opened 2018-01-31 23:39 UTC
### New Functionality
Maybe there should be another type of data table - the one with the fixed toolbar?

Something like this:

![1](https://user-images.githubusercontent.com/13764106/35653339-d42172a4-06f8-11e8-9c0c-c332288103f3.gif)

### Improvements
You'll be able to see all the filters and titles on data tables without "rows per page" limiter

### Bugs or Edge Cases it Helps Avoid
none

**Comment by KaelWD** [comment] 2018-02-01 01:44
Duplicate of #1547

**Closed by KaelWD** 2018-02-01 01:44 UTC
