### ISSUE TITLE
[Bug Report] Carousel reads every image twice - not a bug, a performance weakness

### ISSUE THREAD

**Issue by ChristianRiedl** [vuetifyjs/vuetify#9153] opened 2019-09-30 17:14 UTC
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
https://vuetifyjs.com/en/components/carousels

Try any of the photo samples and watch network accesses.

### Expected Behavior
Access every image once

### Actual Behavior
Every image is accessed twice

### Reproduction Link
<a href="https://github.com/ChristianRiedl/dummy" target="_blank">https://github.com/ChristianRiedl/dummy</a>

### Other comments
I tried to use it as part of a photo galery. Image load time is critical for this use case.

**Comment by KaelWD** [comment] 2019-10-01 13:07
Not a bug, you have "disable cache" checked in devtools.

**Closed by KaelWD** 2019-10-01 13:07 UTC
Labels: triage

**Comment by sebastianhaberey** [comment] 2021-05-26 10:16
Hey guys, great work on Vuetify. Thanks for that! 

Anyways, I've stumbled across this today and I'm wondering why there must be two requests. I mean sure, they will not matter in practice because of browser cache, but wouldn't it be better to not have two identical requests in the first place? What's the reason behind having them?
