### ISSUE TITLE
[Bug Report] VForm: v-model doesn't enable/disable VButton in Safari

### ISSUE THREAD

**Issue by valentingavran** [vuetifyjs/vuetify#13620] opened 2021-05-08 11:16 UTC
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Safari 14.1, Safari
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create a VForm and bind a variable to it. After that add a VTextField to the form and a VButton. Bind the VForm validation variable to the disabled attribute of the VButton.

### Expected Behavior
If the VForm is valid, then the VButton should be enabled, otherwise it should be disabled.

### Actual Behavior
When I bind a variable to the v-model in a v-form, I can't enable/disable a v-btn in Safari if the form is valid/invalid. In Chrome it works without any problems but in Safari the VButton is always disabled.

### Reproduction Link
<a href="https://codepen.io/valentingavran/pen/dyNxPEg?editors=1010" target="_blank">https://codepen.io/valentingavran/pen/dyNxPEg?editors=1010</a>

**Comment by KaelWD** [comment] 2021-05-08 11:17
Duplicate of #13599

**Closed by KaelWD** 2021-05-08 11:17 UTC
Labels: triage
