### ISSUE TITLE
[Bug Report] v-menu position incorrect with fixed positioning and horizontal scroll

### ISSUE THREAD

**Issue by mvirkkunen** [vuetifyjs/vuetify#12228] opened 2020-09-14 22:57 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 83.0.4103.116
**OS:** Linux x86_64

### Steps to reproduce
Use a `v-menu` inside an element with `position: fixed;` on a page with a horizontal scrollbar, and open the menu after scrolling a bit.

### Expected Behavior
Menu should be positioned correctly next to activator.

### Actual Behavior
Scroll X position is added to menu X position even though the activator is fixed, and the position is incorrect.

### Reproduction Link
<a href="https://codepen.io/mvirkkunen/pen/mdPKvoo" target="_blank">https://codepen.io/mvirkkunen/pen/mdPKvoo</a>

### Other comments
This was probably introduced by #5527. The `activatorFixed` property should be checked and scroll position ignored if it's true.

**Comment by KaelWD** [comment] 2020-09-15 06:33
Duplicate of #12078

**Closed by KaelWD** 2020-09-15 06:33 UTC
Labels: triage
