### ISSUE TITLE
[Bug Report] nested card text is white

### ISSUE THREAD

**Issue by bleakhead** [vuetifyjs/vuetify#8424] opened 2019-08-09 08:12 UTC
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Mac OS 10.14.6

### Steps to reproduce
write a text into a v-card-text in a light variant card, which is nested in a dark variant card

### Expected Behavior
The font-color should be black

### Actual Behavior
the v-card-text is white

### Reproduction Link
<a href="https://codepen.io/bleakhead/pen/rXrmRQ" target="_blank">https://codepen.io/bleakhead/pen/rXrmRQ</a>

### Other comments
v-dialog need a v-card to work, and in my case I need a extra v-card inside this dialog

**Comment by KaelWD** [comment] 2019-08-09 08:20
Duplicate of #7920

**Closed by KaelWD** 2019-08-09 08:20 UTC
Labels: triage
