### ISSUE TITLE
[Bug Report] Error el.contains is not a function when using nested components dialogs

### ISSUE THREAD

**Issue by Akuket** [vuetifyjs/vuetify#8428] opened 2019-08-09 13:31 UTC
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
Make a component that uses a v-menu and with a card inside that can open a modal component.
When clicking outside the modal, the error el.contains is not a function appears.
This error comes from the click-outside directive line 32.

### Expected Behavior
No error

### Actual Behavior
The error appears

### Reproduction Link
<a href="https://github.com/no-code" target="_blank">https://github.com/no-code</a>

### Other comments
Maybe change those lines in the file directives/click-outside/index.js
```
  !elements.some(el => el.contains(e.target)) && setTimeout(() => {
    isActive(e) && binding.value && binding.value(e);
  }, 0);
```
by these
```
  !elements.some(element => typeof element.contains === 'function' && element.contains(e.target)) && setTimeout(() => {
    isActive(e) && binding.value && binding.value(e);
  }, 0);
```

**Comment by jacekkarczmarczyk** [comment] 2019-08-09 15:09
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6976

**Closed by jacekkarczmarczyk** 2019-08-09 15:09 UTC
Labels: triage
