### ISSUE TITLE
[Bug Report] `v-edit-dialog` with empty content is not editable

### ISSUE THREAD

**Issue by satotake** [vuetifyjs/vuetify#8465] opened 2019-08-11 06:57 UTC
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
- init `v-data-table` with `v-edit-dialog` . (you can use the official usage example https://vuetifyjs.com/en/components/data-tables#inline-editing )
- Click editable text, open edit-dialog, and delete all characters
- Finish inputing

### Expected Behavior
Users can start editing again for the empty cell when they click it

### Actual Behavior
The edited cell is not clickable and editable

### Reproduction Link
<a href="https://codepen.io/satotake/pen/ZgqvoE?&editable=true&editors=101" target="_blank">https://codepen.io/satotake/pen/ZgqvoE?&editable=true&editors=101</a>

### Other comments
Although the issue can be avoided if you add 'not-empty' rule,
it is often the case users make cells empty and this leads recoverable change for users.

**Comment by KaelWD** [comment] 2019-08-11 07:00
Duplicate of #1282

**Comment by satotake** [comment] 2019-08-11 09:01
Thanks @KaelWD 
And sorry for duplication
I searched only open issues...
I have read #1282 and #1795 but I cannot judge whether this should be closed or not.

Though it seems at least to me a little bit strange as a default manner,
there are some easy workaround for it as you all pointed

**Comment by KaelWD** [comment] 2019-08-11 09:02
Ah I forgot about #1795, this must be a regression then.

**Comment by satotake** [comment] 2019-08-11 14:57
@KaelWD 
I am trying to solve at https://github.com/vuetifyjs/vuetify/pull/8466

**Closed** 2019-08-12 19:53 UTC
Labels: C: VEditDialog, T: bug, T: regression
