### ISSUE TITLE
[Bug Report] <v-list-tile-action> tags without children trigger error: TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by wjossey** [vuetifyjs/vuetify#5056] opened 2018-09-07 16:44 UTC
### Versions and Environment
Vuetify: 1.2.3
Vue: 2.5.9
Browsers: Chrome 68
OS: Mac OS 10.13.5

### Previously worked in:
Vuetify: 1.0.8
Vue: 2.5.9

### Steps to reproduce

Add a `<v-list-tile-action>` without any children tags, and you'll get an error.

### Expected Behavior

Previously a `<v-list-tile-action>` tag without a child did not error. I would think this should either deprecate for a while before being the new behavior, or have a check to see if any child element exists.

### Actual Behavior

When you create a <v-list-tile-action> and fail to add any children, you get a JS error that breaks the page:
`TypeError: Cannot read property 'filter' of undefined`

### Reproduction Link

https://codepen.io/wjossey/pen/oPoeYm

---

**Comment by KaelWD** [comment] 2018-09-07 17:08
Duplicate of #5037

**Closed by KaelWD** 2018-09-07 17:08 UTC
