### ISSUE TITLE
[Feature Request] Expose theme colors as CSS custom properties/variables

### ISSUE THREAD

**Issue by Xowap** [vuetifyjs/vuetify#4817] opened 2018-08-07 20:09 UTC
### What problem does this feature solve?

Sometimes, you want to apply theme configuration (most notably colors) to custom styled items, however if you need something that is not defined automatically in the (numerous) theme classes by `vApp`, then it's quite difficult to get the color in your own CSS:

- I don't necessarily want to interlink my build system with Vuetify's build system (I'd like to keep using LESS)
- Theme colors can be defined (and changed) at runtime

This however looks like a perfect use case for CSS [custom properties](https://caniuse.com/#feat=css-variables) which are nowdays very well supported (considering the user base of my current app, it's close to 99%).

Please note that I don't propose to replace the current system but simply to give the choice to users to use custom properties. 

### What is your proposed solution?

What I have done so far in my app, is declare this in my `App.vue`:

```javascript
// [...]
    computed: {
        cssTheme() {
            const out = {};

            for (const name of Object.keys(this.$vuetify.theme)) {
                out[`--v-color-${name}`] = this.$vuetify.theme[name];
            }

            out['--v-primary-text-color'] = 'rgba(0,0,0,.87)';
            out['--v-secondary-text-color'] = 'rgba(0,0,0,.54)';

            return out;
        },
    },
// [...]
```

Which is injected in the app's template this way:

```html
<v-app :style="cssTheme">
    <!-- ... -->
</v-app>
```

And allows me to do things like:

```css
    .d-toggle-account {
        a&,
        a&:hover,
        a&:visited {
            color: var(--v-primary-text-color);
            text-decoration: none;
        }
    }
```

What I propose is then a generalization of this concept, with more colors available (like the primary and secondary text color, that I have to add manually here).

From what I imagine, it would be two-fold:

1. Generate the custom properties from the `.styl` files (which I can't do, hence the dirty hardcoded `out['--v-primary-text-color']` in my code)
2. Override them at runtime using a similar technique as the one I present here

This approach of course generates a little bit of code and a uses a little bit of RAM/CPU, but I suppose this is negligible in comparison to everything else. On the other hand, this would be highly practical for users willing to use custom properties and get accurate colors at runtime.

I could provide a PR but I don't know Vuetify very well yet so before contributing anything I'd like some guidance (especially on the exact list of colors to be put inside those custom properties).

**Comment by jacekkarczmarczyk** [comment] 2018-08-07 21:29
duplicate of https://github.com/vuetifyjs/vuetify/issues/827

**Closed by jacekkarczmarczyk** 2018-08-07 21:29 UTC

**Comment by Xowap** [comment] 2018-08-07 23:09
Woops, sorry didn't see it!
