### ISSUE TITLE
[Bug Report] v-autocomplete behavior on ms-edge

### ISSUE THREAD

**Issue by userquin** [vuetifyjs/vuetify#6616] opened 2019-02-26 19:18 UTC
### Versions and Environment
**Vuetify:** 1.5.3
**Vue:** 2.6.7
**Browsers:** Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
Just focus the "First text field", then press tab key, "Autocomplete" must get focus, then press again tab key, the "First text field" get focused!!!

Just focus the "First text field", then press tab key, "Autocomplete" must get focus, then press SHIFT tab key, the "Second text field" get focused!!!

You can also navigate [vuetify autocompletes](https://vuetifyjs.com/en/components/autocompletes), pressing tab on any autocomplete just focus "Become a sponsor".

Microsoft Edge 41.16299.492.0
Microsoft EdgeHTML 16.16299

### Expected Behavior
Just the focus behavior with tab and shift tab.

### Actual Behavior
The focus is wrong.

### Reproduction Link
<a href="https://codepen.io/userquin/pen/rRaYgP" target="_blank">https://codepen.io/userquin/pen/rRaYgP</a>

**Comment by userquin** [comment] 2019-02-26 20:09
also reproducible on safari

**Comment by KaelWD** [comment] 2019-02-27 07:18
Duplicate of #6608

**Closed by KaelWD** 2019-02-27 07:18 UTC
Labels: duplicate
