### ISSUE TITLE
[Bug Report] v-text-field long prefix not rendering well

### ISSUE THREAD

**Issue by dh3wr** [vuetifyjs/vuetify#5490] opened 2018-10-31 10:53 UTC
### Versions and Environment
**Vuetify:** 1.3.4
**Vue:** 2.5.17
**Browsers:** Google Chrome
**OS:** Windows 7

### Steps to reproduce
Open codepen

### Expected Behavior
Start text typing area after prefix

### Actual Behavior
Text typing area is placed over prefix

### Reproduction Link
[https://codepen.io/dh3wr/pen/VEJQNv](https://codepen.io/dh3wr/pen/VEJQNv)
See #4268

**Comment by jacekkarczmarczyk** [comment] 2018-10-31 11:09
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3485

**Closed by jacekkarczmarczyk** 2018-10-31 11:09 UTC
