### ISSUE TITLE
[Bug Report][3.0.0-beta.5] v-select: toRefs() expects a reactive object but received a plain one

### ISSUE THREAD

**Issue by kuroidoruido** [vuetifyjs/vuetify#15500] opened 2022-07-22 12:39 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.36
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Linux, Mac OSX

### Steps to reproduce
- insert a v-select in the template of one component
- add some items to the v-select

### Expected Behavior
- when opening the v-select menu there is no warning/error message

### Actual Behavior
- when opening the v-select menu we get the warning "toRefs() expects a reactive object but received a plain one."

### Reproduction Link
<a href="https://github.com/kuroidoruido/vitejs-vite-y4nlvb" target="_blank">https://github.com/kuroidoruido/vitejs-vite-y4nlvb</a>

### Other comments
seems related to this issue https://github.com/vuetifyjs/vuetify/issues/15434

**Comment by KaelWD** [comment] 2022-07-22 12:40
Duplicate of #15434

**Closed by KaelWD** 2022-07-22 12:40 UTC
Labels: S: triage
