### ISSUE TITLE
V-Tab text-transform has issue on default value

### ISSUE THREAD

**Issue by DebbyLee** [vuetifyjs/vuetify#17990] opened 2023-08-08 08:25 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vuetify@2.7.0` for the project I'm working on.

We are updating our vuetify package from 2.6.* to 2.7.0 today. And we noticed that Tab title no longer uppercase.
After digging into the changelog, https://github.com/vuetifyjs/vuetify/pull/14545 was introduced to make text-transform as configurable. However, it also introduced some error which browser is rejected this css style

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vuetify/src/components/VTabs/_variables.scss b/node_modules/vuetify/src/components/VTabs/_variables.scss
index 3478d3c..57145cb 100644
--- a/node_modules/vuetify/src/components/VTabs/_variables.scss
+++ b/node_modules/vuetify/src/components/VTabs/_variables.scss
@@ -3,7 +3,7 @@
 $tab-disabled-opacity: .5 !default;
 $tab-font-size: map-deep-get($headings, 'subtitle-2', 'size') !default;
 $tab-font-weight: map-deep-get($headings, 'subtitle-2', 'weight') !default;
-$tab-text-transform: 'uppercase' !default;
+$tab-text-transform: uppercase !default;
 $tab-line-height: normal !default;
 $tabs-bar-background-color: 'cards' !default;
 $tabs-bar-height: 48px !default;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by KaelWD** [comment] 2023-08-09 08:05
Duplicate of #17799

**Closed by KaelWD** 2023-08-09 08:05 UTC
Labels: S: triage
