### ISSUE TITLE
[Bug Report][2.6.2] VNavigationDrawer cannot disable expandOnHover

### ISSUE THREAD

**Issue by lgarczyn** [vuetifyjs/vuetify#14575] opened 2022-01-06 22:49 UTC
### Environment
**Vuetify Version:** 2.6.2
**Last working version:** 2.6.1
**Vue Version:** 2.6.14
**Browsers:** Firefox 95.0
**OS:** Linux

### Steps to reproduce
Hover the sidebar, then leave the sidebar

### Expected Behavior
Sidebar should not open, and definitely not close

### Actual Behavior
Expand-on-hover cannot be disabled

### Reproduction Link
<a href="https://codepen.io/lgarczyn/pen/OJxwRWB" target="_blank">https://codepen.io/lgarczyn/pen/OJxwRWB</a>

### Other comments
This worked in 2.6.1: https://codepen.io/lgarczyn/pen/NWaBRaV

**Comment by lgarczyn** [comment] 2022-01-06 22:50
Probably the same issue as https://github.com/vuetifyjs/vuetify/issues/14555

**Comment by rw-leo** [comment] 2022-01-07 03:43
The change introduced for [v2.6.2](https://github.com/vuetifyjs/vuetify/releases/tag/v2.6.2) in this commit https://github.com/vuetifyjs/vuetify/commit/03e683f286e652b942b83a817cecc080d4c4a6eb doesn't work for scenarios in which the drawer is not to be activated via hovering. 

The property `expandOnHover` should be considered before changing the value of `isMouseOver`, as in the previous release. 

See image below:
![image](https://user-images.githubusercontent.com/49159952/148487928-99da8865-94bd-482f-9373-b281139d491e.png)

**Comment by KaelWD** [comment] 2022-01-07 03:47
Duplicate of #14555

**Closed by KaelWD** 2022-01-07 03:47 UTC
Labels: S: triage

**Comment by lgarczyn** [comment] 2022-01-07 03:53
@KaelWD  You stated in the other issue that you needed a new issue with a working example, and closed it. 

This is the new issue, why close it?

**Comment by KaelWD** [comment] 2022-01-07 04:12
That was in response to this comment: https://github.com/vuetifyjs/vuetify/issues/14555#issuecomment-1003732888

This issue has already been fixed.

**Comment by MaxWeisen** [comment] 2022-01-13 22:30
I am still experiencing this behavior. Navigation drawer is expanding on hover even when prop `expand-on-hover= false`

**Comment by lgarczyn** [comment] 2022-01-14 00:53
> I am still experiencing this behavior. Navigation drawer is expanding on hover even when prop `expand-on-hover= false`
> 
> @KaelWD how should we stop navigation drawer expanding on hover?

Wait for v 2.6.3 or rollback to 2.6.1

**Comment by JonWangM** [comment] 2022-01-14 05:01
I got same issue , please fix it in next version ASAP , thanks team.
![image](https://user-images.githubusercontent.com/2102229/149454316-2a1cdff2-ed31-4da3-bd70-66d1f8ec25e1.png)
