### ISSUE TITLE
[Bug Report] v-chip in v-select is always closeable

### ISSUE THREAD

**Issue by shogogg** [vuetifyjs/vuetify#7541] opened 2019-06-17 07:35 UTC
### Versions and Environment
**Vuetify:** 2.0.0-beta.2
**Vue:** 2.6.10
**Browsers:** Firefox 67.0
**OS:** Mac OS 10.14

### Steps to reproduce
Use `v-select` with `chips` or `small-chips` option.

### Expected Behavior
* Chips are deletable when `deletable-chips` is true.
* Chips are not-deletable when `deletable-chips` is false.

### Actual Behavior
Chips are always deletable.

### Reproduction Link
<a href="https://codepen.io/shogogg/pen/BgKxpK" target="_blank">https://codepen.io/shogogg/pen/BgKxpK</a>

### Other comments
* v-chip's close button appears when it has `click:close` listener.
* v-select's method `genChipSelection` always set listener on `click:close` to v-chip component.

**Comment by jacekkarczmarczyk** [comment] 2019-06-17 07:46
This is already fixed on dev branch

**Closed by jacekkarczmarczyk** 2019-06-17 07:46 UTC
Labels: triage

**Comment by KaelWD** [comment] 2019-06-17 09:55
Duplicate of #7494
