### ISSUE TITLE
[Bug Report] v-select custom item slot doesn't respond properly to item selection

### ISSUE THREAD

**Issue by perdidao** [vuetifyjs/vuetify#9229] opened 2019-10-04 14:12 UTC
### Environment
**Vuetify Version:** 2.0.20
**Last working version:** 1.5.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
Add a checkbox to a v-select's item slot

### Expected Behavior
Toggle the checkbox state when item is selected

### Actual Behavior
Can't supply any info to the v-select or to bind the custom checkbox

### Reproduction Link
<a href="https://codepen.io/anon/pen/rPGGMG?editors=1010" target="_blank">https://codepen.io/anon/pen/rPGGMG?editors=1010</a>

### Other comments
The codepen link shows a functional example. The problem is that, when I try to use that solution on vuetify 2.0, I can't make it work.

**Comment by muazmalas** [comment] 2020-02-21 17:31
I thought I had the same issue at first but managed to do. Here is the proper implementation:

`<template v-slot:item="data">
    <v-list-item v-bind="data.attrs" v-on="data.on">
        <v-list-item-action >
            <v-checkbox :value="data.attrs.inputValue" @change="data.parent.$emit('select', data.item)" ></v-checkbox>
        </v-list-item-action>
        <v-list-item-content>
            <v-list-item-title v-html="data.item.first_name"></v-list-item-title>
        </v-list-item-content>
    </v-list-item>
</template>`

**Comment by KaelWD** [comment] 2020-02-22 06:33
This could do with an example implementation.

**Comment by KaelWD** [comment] 2021-12-14 07:41
Duplicate of #6566

**Closed by KaelWD** 2021-12-14 07:41 UTC
Labels: T: documentation, C: VSelect
