### ISSUE TITLE
[Bug Report] Problem with large text in v-textarea with auto-grow prop

### ISSUE THREAD

**Issue by dariogrd** [vuetifyjs/vuetify#13604] opened 2021-05-05 12:00 UTC
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.11
**Browsers:** Google Chrome, Mozilla Firefox, Microsoft Edge
**OS:** Windows, Mac OSX, Linux

### Steps to reproduce
Take a look at the example I created -> https://codepen.io/dariogrd/full/mdWbgNG
Enter a long text to the textarea or click on the button multiple times to add Lorem Ipsum text. The goal is that the textarea grows so that a scroller appears. The amount of text you need to add depends on the size of your screen.
Once the scroller appears, try to manually add text to the end of textarea. You will see that the scroller constantly jumps up and you do not see the text you are typing.

### Expected Behavior
That the browser scroller doesn’t jump up when I type new text.

### Actual Behavior
This works ok only in Safari (MacOS), on other browsers (Chrome, Firefox, Edge) there is a problem when a large amount of text is typed into the textarea with auto-grow property. 
The problem occurs when a scroller appears in the browser, after that, when you are adding more text, scroller constantly jumps up and you do not see the text you are typing.
The problem arises when there is a fixed footer, but even if the footer is removed completely, the scroller still jumps up, but not so much that you can't see what you are typing.

### Reproduction Link
<a href="https://codepen.io/dariogrd/full/mdWbgNG" target="_blank">https://codepen.io/dariogrd/full/mdWbgNG</a>

**Comment by jacekkarczmarczyk** [comment] 2021-05-05 12:08
That looks more like a feature request for me

**Comment by dariogrd** [comment] 2021-05-05 12:17
I wouldn’t quite agree that it’s a feature request. I think it's a bug if I don’t see what I’m typing in the textarea

**Comment by arnKo** [comment] 2021-06-16 06:49
This is obviously a bug. I currently use v-textarea for a large editor and this bug turns it unusable. Every time you start typing, the textarea scrolls until the current line is at the bottom of the page. In case of @dariogrd's example the footer even hides the last line so you cannot even see what you're typing.

**Comment by KaelWD** [comment] 2021-08-19 14:27
Duplicate of #5314

**Closed by KaelWD** 2021-08-19 14:27 UTC
Labels: C: VTextarea, S: triage
