### ISSUE TITLE
v-text-field: Using box property with prefix property vertical alignment issue

### ISSUE THREAD

**Issue by rheckart** [vuetifyjs/vuetify#4587] opened 2018-07-12 03:49 UTC
Using the v-text-field and adding both a box and prefix property results in the prefix text being vertically aligned incorrectly. See this [CodePen example](https://codepen.io/anon/pen/rraXEb?). This is happening in 1.1.4.

**Comment by CodeSkills** [comment] 2018-07-25 06:12
I can confirm, using 1.1.7 and this is still there.

The suffix does the same. 

<img width="303" alt="screen shot 2018-07-25 at 08 12 26" src="https://user-images.githubusercontent.com/3975293/43182654-7e029cc2-8fe2-11e8-93e7-7d35eec4c117.png">

**Comment by empresarrollo** [comment] 2018-08-01 19:11
yep, I see the same using the outline prop.

**Comment by KaelWD** [comment] 2018-08-18 08:47
Duplicate of #4487

**Closed by KaelWD** 2018-08-18 08:47 UTC
