### ISSUE TITLE
Autocomplete menu only contains selected item when using objects

### ISSUE THREAD

**Issue by mirhat** [vuetifyjs/vuetify#1890] opened 2017-09-26 09:03 UTC
### Steps to reproduce
Create select with autocomplete option and specify item-text and item-value
Filter items and lose focus
Click on select
### Versions

"vuetify": "0.15.7"
### What is expected ?

All list items should be shown
### What is actually happening ?

Only the selected item is shown
### Reproduction Link

https://codepen.io/anon/pen/aLpaRV

**Comment by mirhat** [comment] 2017-09-26 09:17
Solution may be to change 
this.searchValue === this.selectedItem to this.searchValue === this.getText(this.selectedItem)

https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VSelect/VSelect.js in 194. line

**Comment by KaelWD** [comment] 2017-09-26 10:24
> Only one item is shown

That was fixed in 2d4fa52c3ad44ad3cf373d66d9d3d961b20106cb, but looks like it's come back for some reason.

> cursor is in random position

I couldn't reproduce this on dev, it must have been fixed already.

**Comment by KaelWD** [comment] 2017-09-28 06:49
Fixed with #1891

**Closed by KaelWD** 2017-09-28 06:49 UTC
Labels: bug
