### ISSUE TITLE
[Bug Report] Incorrect work with tabs inside tabs

### ISSUE THREAD

**Issue by paramid** [vuetifyjs/vuetify#6651] opened 2019-03-01 15:07 UTC
### Versions and Environment
**Vuetify:** 1.0.7
**Vue:** 2.6.7
**Browsers:** Chrome 72.0.3626.119
**OS:** Windows 10

### Steps to reproduce
Look at the second level tabs when clicking first level tabs, slider doesnt display

### Expected Behavior
Underline(slider) tabs button in each tabs

### Actual Behavior
Underline(slider) doesnt work normal with tabs in tabs

### Reproduction Link
<a href="https://codepen.io/paramid/pen/wOMQJZ" target="_blank">https://codepen.io/paramid/pen/wOMQJZ</a>

### Other comments
https://codepen.io/paramid/pen/Wmradg when used one v-model property to each tabs its work correctly, but in real life we need different v-models to each tabs, so https://codepen.io/paramid/pen/wOMQJZ it wont work correctly, underline(slider) doesnt display, only when i clicked some tabs. In the last version of vuetify 1.5.3 slider doesnt work even im using one v-model to all tabs.

**Comment by DRoet** [comment] 2019-03-03 02:52
@johnleider I've tested this against the MD-2 tabs rewrite and the same thing happens

**Comment by KaelWD** [comment] 2019-03-03 06:06
Duplicate of #1978

**Closed by KaelWD** 2019-03-03 06:06 UTC
