### ISSUE TITLE
[Bug Report][3.0.0-beta.11] v-form is null when mounted

### ISSUE THREAD

**Issue by heyimnowi** [vuetifyjs/vuetify#15819] opened 2022-09-28 11:00 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Vue Version:** 3.2.13
**Browsers:** Chrome 105.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
v-form is null when mounted. By default, I set an initial value for the text field so since the only rule is for the text field to be required, the form should be valid. I set the model value to true because the text field is filled but the form changes its model value to null.

### Expected Behavior
Model value to remain true or false. depends on the defined rules.

### Actual Behavior
Model value is null.

### Reproduction Link
<a href="https://codepen.io/noeliablopez-1472141200/pen/OJZQRWJ" target="_blank">https://codepen.io/noeliablopez-1472141200/pen/OJZQRWJ</a>

**Comment by KaelWD** [comment] 2022-09-28 12:00
Duplicate of #15568

**Closed by KaelWD** 2022-09-28 12:00 UTC
Labels: S: triage
