### ISSUE TITLE
[Bug Report] Ripple sticks when opening/closing Dialogs with Keyboard

### ISSUE THREAD

**Issue by awaigand** [vuetifyjs/vuetify#13301] opened 2021-03-19 14:31 UTC
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.6.12
**Browsers:** Firefox 78.0
**OS:** Windows 10

### Steps to reproduce
1. Tab to "Click Me"
2. Press Enter and the Dialog opens
3. Tab to "I Accept"
3. PRess Enter and the Dialog closes
4. Press enter again to open the dialog again
5. Look at "I Accept", which still has active ripple

### Expected Behavior
I accpet should not have active Ripple anymore

### Actual Behavior
"I Accept" still has active ripple.
If you hover over it the ripple disappears.

### Reproduction Link
<a href="https://codepen.io/awaigand/pen/LYbKvZV?editors=101" target="_blank">https://codepen.io/awaigand/pen/LYbKvZV?editors=101</a>

### Other comments
I am guessing it has something todo with the focus being moved when the dialog opens, but I am not sure. 
This is especially troublesome since the remaining ripple-effect looks very similar to focus, which hampers keyboard users and impacts accessibility.
Thank you!

**Comment by KaelWD** [comment] 2021-03-19 15:06
Duplicate of #13189

**Closed by KaelWD** 2021-03-19 15:06 UTC
Labels: triage
