### ISSUE TITLE
VSelect: stop enter propagation in form

### ISSUE THREAD

**Issue by knagyorg** [vuetifyjs/vuetify#5608] opened 2018-11-14 09:11 UTC
Versions and Environment
Vuetify: 1.3.8
Vue: 2.5.17
Browsers: Chrome 70.0.3538.77
OS: Windows 10

Steps to reproduce
Click on v-select to show its popup, select item and press Enter key

Expected Behavior
When v-select's popup is shown, pressing Enter key should close this popup and select active item - not call submit.

Actual Behavior
Pressing Enter key to select active item when v-select's popup is shown call form submit

Reproduction Link
https://codepen.io/anon/pen/VVppoW?editors=1010

**Comment by jacekkarczmarczyk** [comment] 2018-11-14 12:32
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4974

**Closed by jacekkarczmarczyk** 2018-11-14 12:32 UTC
