### ISSUE TITLE
[Bug Report] Error in code example to vuelidade

### ISSUE THREAD

**Issue by VictorCostaOliveira** [vuetifyjs/vuetify#4968] opened 2018-08-28 02:18 UTC
### Versions and Environment
**Vuetify:** 1.1.14
**Vue:** 2.5.17
**Browsers:** Chrome 64.0.3282.140
**OS:** Linux x86_64

### Steps to reproduce
i copy the example code to form with vuelidade, and in this code `!this.$v.checkbox.required && errors.push('You must agree to continue!')`

### Expected Behavior
expected checkbos presence validation

### Actual Behavior
 if this.$v.checkbox.required is denied, the checkbox does't show an error.

### Reproduction Link
[https://codepen.io/victor-costa/pen/MqeaPb](https://codepen.io/victor-costa/pen/MqeaPb)

**Comment by chewy94** [comment] 2018-08-29 16:07
Can you please update your pen? It currently only has javascript filled out

**Comment by christianklauss** [comment] 2018-09-04 19:34
I think I am experiencing the same and it is (at least for me) reproducible (Chromium and Edge) at the offical codepen example:
https://codepen.io/pen/?editors=1010

Checking and unchecking the checkbox does not produce the error message.
The corresponding entry in the form component example gallery works.

**Comment by VictorCostaOliveira** [comment] 2018-09-04 19:48
@chewy94 Hello, here the codepen https://codepen.io/victor-costa/pen/oPwENw with a example

**Comment by KaelWD** [comment] 2018-10-25 06:49
Duplicate of monterail/vuelidate#156

**Closed by KaelWD** 2018-10-25 06:49 UTC
Labels: pending review
