### ISSUE TITLE
[Bug Report] Tooltip on any fixed component moves when scrolling

### ISSUE THREAD

**Issue by anthonysan95** [vuetifyjs/vuetify#2866] opened 2017-12-24 11:33 UTC
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.5.11
**Browsers:** Chrome 63.0.3239.84
**OS:** Windows 10

### Steps to reproduce
1. Create a bottom right fixed fab with a left tooltip.
1. Hover over the fab.
1. Scroll the window.

### Expected Behavior
The tooltip should follow the fixed activator.

### Actual Behavior
The tooltip scrolls with the window.

### Reproduction Link
[https://codepen.io/dEradicated/pen/oGrWPP?editors=1010](https://codepen.io/dEradicated/pen/oGrWPP?editors=1010)

### Other comments
I already saw this marked as duplicate here #2309 and it should have been already solved with the absolute menu, how do I make the tooltip stay in place with the fab?

**Comment by KaelWD** [comment] 2018-02-13 05:43
Duplicate of #2309

Use `attach`

**Closed by KaelWD** 2018-02-13 05:43 UTC
Labels: bug, help wanted
