### ISSUE TITLE
[Bug Report][3.1.5] v-select item slot does not replace the item in the dropdown

### ISSUE THREAD

**Issue by MetRonnie** [vuetifyjs/vuetify#16677] opened 2023-02-15 15:35 UTC
### Environment
**Vuetify Version:** 3.1.5
**Last working version:** 2.6.14
**Vue Version:** 3.2.47
**Browsers:** Edge 110.0.1587.41
**OS:** Windows 10

### Steps to reproduce
Use a custom template in the `item` slot to try and replace the default content of each item in the dropdown, [as shown in the Vuetify 2->3 upgrade guide](https://next.vuetifyjs.com/en/getting-started/upgrade-guide/#v-select-v-combobox-v-autocomplete):
```vue
<template #item="{ props }">
  <v-list-item v-bind="props">
    <!-- content -->
  </v-list-item>
</template>
```

### Expected Behavior
The content you provide replaces the default content

### Actual Behavior
The content you provide is added to the default content

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUUtuwyAQvQpik40NbZOqkuVG6TniLIhNExrzKeBEleW7d8CO5ThtpYoNM/M+zGPb4jdjyLnhOMO559LUzPN1oRDKzykzJl5jIZlQQxVrx2teepQJYLnXAm8XAK/5IkELbZk6xNupkZ8N84tdgUdu4UcjBDK19lEDJFoULgkyVhuHugln8KyF82nAAHEvVAWciJ0hI1aUWq1lJVJWlrpRPqdDb4Z0hql121sTyy6o63IamzfmwB7dJ5Oc3oR2hfbhXMODxpheKPpcb6jh4AQLabT1gDbkw2kFn9IGUjEMYNEMxU7owa+FusBH743LKG2UOR1IqSXdwIxa2FpInlZabpZkSR5SVpsjIytawSbTMeFOpnurL45bMC5wMvHw4v3rN59hDPKP5LmXHVpB8k6Kgv6Z29RyVXHL7Z/Pn2F/WmEGuVsjWHeF6iDZWqiTm4Vauhjo9vrCf+0nhSJRILB3waRL8JI8kdUL2EUC3n0Dg/IVCg==)

**Comment by KaelWD** [comment] 2023-02-15 15:38
Duplicate of #16490

**Closed by KaelWD** 2023-02-15 15:38 UTC
Labels: S: triage
