### ISSUE TITLE
[Feature Request] Mention Featue f.ex. within the autocomplete component or as a whole new component

### ISSUE THREAD

**Issue by paulwer** [vuetifyjs/vuetify#17290] opened 2023-05-04 03:29 UTC
### Problem to solve
Hey everyone, is it possible to add a feature for the autocomplete component, to mention other people and/or use commands within the input itself.

### Proposed solution
Take a look here: 
https://css-tricks.com/so-you-want-to-build-an-mention-autocomplete-feature/

Would be a great addition and a great unique featue as a whole.
An other idea could be to implement this within a component called editor, which can be more customised.

**Comment by KaelWD** [comment] 2023-05-04 03:32
Duplicate of #6820

**Closed by KaelWD** 2023-05-04 03:32 UTC
Labels: S: triage
