### ISSUE TITLE
[Bug Report] TextField component visually breaks with prefix and reverse property combo

### ISSUE THREAD

**Issue by JesusCrow** [vuetifyjs/vuetify#5932] opened 2018-12-18 12:22 UTC
### Versions and Environment
**Vuetify:** 1.3.14
**Vue:** 2.5.21
**Browsers:** Chrome 70.0.3538.110
**OS:** Mac OS 10.14.2

### Steps to reproduce
1. Create TextField;
2. Add label;
3. Add reverse property;
4. Add prefix;

### Expected Behavior
Finding label on the right side;
Finding prefix on the right side, between label and the right side.

### Actual Behavior
1. Label is missing.
2. Adding some text to the box and outline style TextField breaks prefix position.

### Reproduction Link
<a href="https://codepen.io/anon/pen/roMKga?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/roMKga?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment] 2018-12-18 23:38
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4552

Label is missing because of `single-line` prop

**Closed by jacekkarczmarczyk** 2018-12-18 23:38 UTC
