### ISSUE TITLE
[Bug Report] Two results with same item-text show as one result in list

### ISSUE THREAD

**Issue by markon1** [vuetifyjs/vuetify#6657] opened 2019-03-02 03:34 UTC
### Versions and Environment
**Vuetify:** 1.2.9
**Vue:** 2.5.17
**Browsers:** Chrome 72.0.3626.119
**OS:** Windows 10

### Steps to reproduce
Just click on Search field, items are hardcoded to make example simpler (in reality items are pulled from API)

### Expected Behavior
Two items with same `item-text` value (`displayText` function which returns `item.firstName` + `item.lastName`) (like John Smith) should display as two items in result list.

### Actual Behavior
Two items with same `item-text` value (`displayText` function which returns `item.firstName` +  `item.lastName`) (like John Smith) show as only one item in result list

### Reproduction Link
<a href="https://codepen.io/anon/pen/LaNZNL" target="_blank">https://codepen.io/anon/pen/LaNZNL</a>

### Other comments
If you change `displayText` function to return `item.id` for example, it shows both items in result list correctly.

**Comment by KaelWD** [comment] 2019-03-02 04:44
Duplicate of #4633

`item-value="id"`

**Closed by KaelWD** 2019-03-02 04:44 UTC
