### ISSUE TITLE
[Feature Request] Header text for grouping

### ISSUE THREAD

**Issue by GaborTorma** [vuetifyjs/vuetify#10427] opened 2020-02-02 16:35 UTC
### Problem to solve
Now the header.name are on grouping.
[https://www.screencast.com/t/MM2ImHorhMHL](url)

### Proposed solution
Use the header.text for showing the grouping title.

**Comment by whoistobias** [comment] 2020-02-22 21:00
![02 02 2020-17 34](https://user-images.githubusercontent.com/17418102/75099149-f8b66080-5583-11ea-93db-af53b3a92646.png)
The linked photo for brevity.

**Comment by whoistobias** [comment] 2020-02-22 21:09
My understanding of this proposed solution would be to display the highlighted text based on the header text rather than the header name. In that way, it would match what the user sees prior to grouping.

**Comment by KaelWD** [comment] 2022-09-01 08:37
Duplicate of #11516

**Closed by KaelWD** 2022-09-01 08:37 UTC
Labels: T: feature, C: VDataTable
