### ISSUE TITLE
[Feature Request] v-data-table, allow grouping of first column rows

### ISSUE THREAD

**Issue by wouterfovel** [vuetifyjs/vuetify#5829] opened 2018-12-06 09:36 UTC
### Problem to solve
We would like something like https://github.com/vuetifyjs/vuetify/pull/4966
Give the user the possibility to only expand rows for a certain first column value ...

### Proposed solution
Could first column grouping be added to v-data-table ? Or is there a solution you know of we can use ?

**Comment by wouterfovel** [comment] 2018-12-12 09:42
Is in fact same as [Feature Request] Table group rows by header #3180

Any news ?

**Comment by nekosaur** [comment] 2018-12-12 11:31
Duplicate of #3180 

Please follow that issue for any updates

**Closed by nekosaur** 2018-12-12 11:31 UTC
Labels: duplicate
