### ISSUE TITLE
[Bug Report][2.6.0] v-row inside v-footer showing vertical 

### ISSUE THREAD

**Issue by Usama420-git** [vuetifyjs/vuetify#15310] opened 2022-06-16 12:41 UTC
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.14
**Browsers:** Firefox 101.0
**OS:** Windows 10

### Steps to reproduce
I am using v-footer with v-row and you can see the codepen link I want my buttons in horizontal line but it is showing in vertical https://www.awesomescreenshot.com/image/28837879?key=ce81e308626bb9c50f8381753626ec3d see this image it was ok before but it is start happening from today

### Expected Behavior
v-row in horizontal line

### Actual Behavior
v-row in vertical line

### Reproduction Link
<a href="https://codepen.io/usama211/pen/zYRbZgX" target="_blank">https://codepen.io/usama211/pen/zYRbZgX</a>

**Comment by KaelWD** [comment] 2022-08-01 10:01
Closing due to lack of valid reproduction.

**Closed by KaelWD** 2022-08-01 10:01 UTC
Labels: S: needs reproduction, S: triage
