### ISSUE TITLE
[Feature Request] Dialog

### ISSUE THREAD

**Issue by LouisLiu00** [vuetifyjs/vuetify#11108] opened 2020-04-14 05:50 UTC
### Problem to solve
现在的Dialog不能移动，会遮挡背后的区域，希望弹出窗口Dialog能够点击鼠标进行拖拽移动，谢谢！

### Proposed solution
现在的Dialog不能移动，会遮挡背后的区域，希望弹出窗口Dialog能够点击鼠标进行拖拽移动，谢谢！

**Comment by KaelWD** [comment] 2020-04-14 06:05
Duplicate of #4058

Please only use english in this repository, we have language-specific channels in discord if you need help in your native language.

**Closed by KaelWD** 2020-04-14 06:05 UTC
Labels: triage

**Comment by LouisLiu00** [comment] 2020-04-14 06:37
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you very much for your reply, this article is very useful and solved my problem, thanks again!
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    
Louis

        
    
     

    On 4/14/2020 14:06，Kael<notifications@github.com> wrote： 



Duplicate of #4058
Please only use english in this repository, we have language-specific channels in discord if you need help in your native language.
