### ISSUE TITLE
[Bug Report][2.6.2] v-select focus active error

### ISSUE THREAD

**Issue by Ahn-GiHwan** [vuetifyjs/vuetify#15884] opened 2022-10-14 00:33 UTC
### Environment
**Vuetify Version:** 2.6.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Bananas was selected on the [official website of Vietify](https://vuetifyjs.com/en/components/selects/#append-and-prepend-item), but Apricots was activated

### Expected Behavior
Activate only selected places

### Actual Behavior
Activation elsewhere than selection

### Reproduction Link
<a href="https://github.com/Ahn-GiHwan/vuetify_v-select_report.git" target="_blank">https://github.com/Ahn-GiHwan/vuetify_v-select_report.git</a>

**Comment by Ahn-GiHwan** [comment] 2022-10-17 02:28
@jacekkarczmarczyk Updated 'Steps to Reproduce'.

**Comment by KaelWD** [comment] 2022-10-17 02:35
Duplicate of #14489

**Closed by KaelWD** 2022-10-17 02:35 UTC
Labels: S: needs reproduction, S: triage
