### ISSUE TITLE
Server-side pagination does not work (Component: VDataTable)

### ISSUE THREAD

**Issue by arsentver** [vuetifyjs/vuetify#4541] opened 2018-07-09 08:24 UTC
### Versions and Environment
Vuetify: 1.1.1
Vue: latest
Browsers: all
OS: Windows 10

### Previously worked in:
Vuetify: 1.0.19
Vue: latest

### Expected Behavior
the total-items property works fine if I make a request to the server and get the total number of rows, but only in version 1.0.19

### Actual Behavior
In later versions (1.1.1), this property does not go inside the component and is always 0
screenshot: https://yadi.sk/i/3FvG3k0z3YxCCT

### Reproduction Link
In new Version (1.1.1)
https://codepen.io/arsentver/pen/gjYwdz?editors=1010

in old Version (1.0.19)
https://codepen.io/arsentver/pen/GBKNvz?editors=1010

**Comment by arsentver** [comment] 2018-07-10 05:59
added reproduction links

**Comment by jacekkarczmarczyk** [comment] 2018-07-10 06:51
duplicate of #3978 - do not use `search` prop when you're doing searching in backend

**Closed by jacekkarczmarczyk** 2018-07-10 06:51 UTC
Labels: pending review
