### ISSUE TITLE
[Feature Request] Countdown timer to v-alert component

### ISSUE THREAD

**Issue by CoolmanPT** [vuetifyjs/vuetify#12464] opened 2020-10-21 12:09 UTC
### Problem to solve
This would help showing some alerts without user interaction to dismiss them. Example: When I'm trying to login and the credentials are invalid, it would popup a v-alert for like 5 seconds with message "Invalid Credentials, try again" and then it closes

### Proposed solution
make a prop asking for duration of alert and then when the duration reachs 0 it closes v-alert

**Comment by jacekkarczmarczyk** [comment] 2020-10-21 12:27
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10344

**Closed by jacekkarczmarczyk** 2020-10-21 12:27 UTC
