### ISSUE TITLE
[Feature Request] Autocomplete and Combobox Options

### ISSUE THREAD

**Issue by navi35** [vuetifyjs/vuetify#5480] opened 2018-10-29 20:51 UTC
### Problem to solve
On mobile browser, options look really confusing as you can see below links.

http://oi67.tinypic.com/b6pmx4.jpg (mobile)
http://oi68.tinypic.com/xcqjo8.jpg

### Proposed solution
Maybe you can add some prop to select works like this

http://oi64.tinypic.com/15xqudv.jpg
http://oi65.tinypic.com/2ui8y6c.jpg

Here is codepen: https://codepen.io/navi3591/pen/QZPPEy?editors=1010

Thanks,

**Comment by KaelWD** [comment] 2018-10-30 12:02
Not an exact duplicate of #4059, but close enough for me to close it. We're also considering exposing the v-select-list component for custom searchable lists.

**Closed by KaelWD** 2018-10-30 12:02 UTC
