### ISSUE TITLE
[Bug Report][2.6.1] VAutocomplete Error When NULL Found in Items

### ISSUE THREAD

**Issue by rashadrivera** [vuetifyjs/vuetify#14524] opened 2021-12-16 22:10 UTC
### Environment
**Vuetify Version:** 2.6.1
**Vue Version:** 2.6.14
**Browsers:** Chrome 96.0.4664.110, Mozilla Firefox, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
1. In the array bound to VAutocomplete.Items, push NULL or undefined into the array
2. Observe the Console Error logs

### Expected Behavior
The VAutocomplete control will throw only one comprehensive warning/error with the array index, for each offending value in the array.

### Actual Behavior
6 unhandled errors will be emitted in the browser's console.

### Reproduction Link
<a href="https://codepen.io/rashad-rivera/pen/jOGmPOy?editors=1010" target="_blank">https://codepen.io/rashad-rivera/pen/jOGmPOy?editors=1010</a>

### Other comments
In the code example, open your browser's Console and clear all errors.  Then click the "Inject Null Into Array" button to expose the 6 unhandled errors.

**Comment by KaelWD** [comment] 2021-12-27 08:56
Duplicate of #14421

**Closed by KaelWD** 2021-12-27 08:56 UTC
Labels: S: triage
