### ISSUE TITLE
[Bug Report] Grow prop V-Tabs on Mobile

### ISSUE THREAD

**Issue by navi35** [vuetifyjs/vuetify#8610] opened 2019-08-18 15:46 UTC
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Grow prop not working properly for screen resizes.

### Expected Behavior
Tab buttons should fit screen width.

### Actual Behavior
Tab buttons float right on mobile.

### Reproduction Link
<a href="https://codepen.io/navi3591/pen/bGbeQdo?editors=1010" target="_blank">https://codepen.io/navi3591/pen/bGbeQdo?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-18 16:25
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8294

**Closed by jacekkarczmarczyk** 2019-08-18 16:25 UTC
Labels: triage
