### ISSUE TITLE
[Bug Report][3.3.10] VTabs: Default active tab does not receive active class in SSR mode

### ISSUE THREAD

**Issue by mostafaznv** [vuetifyjs/vuetify#17897] opened 2023-07-28 14:19 UTC
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
When using the VTabs component in Vuetify, I noticed that when I pre-select a default active tab, it does not receive the "active" class. This behavior makes it challenging for users to identify which tab is currently selected by default.

1. Create a VTabs component with multiple tabs.
2. Set the v-model or value prop to a specific tab index to make it the default active tab.
3. Run the application (or refresh the page) and inspect the rendered VTabs component.

### Expected Behavior
The default active tab should receive the "active" class, indicating that it is currently selected.

### Actual Behavior
The default active tab does not receive the "active" class by default, causing it to visually resemble inactive tabs.
As a workaround, users must click on non-active tabs to trigger the correct application of the "active" class to the default tab.

### Reproduction Link
[https://stackblitz.com/edit/nuxt-starter-s7fraa](https://stackblitz.com/edit/nuxt-starter-s7fraa)

### Other comments
I use Nuxt 3.6.5 with SSR: true

**Comment by nekosaur** [comment] 2023-07-28 14:27
Works in playground so seems to be nuxt/ssr specific

https://play.vuetifyjs.com/#eNqlU8tu2zAQ/BWCFyWAJdVxL3VlIwWC/kADX6IcaGltsyUpgqTVBob+vcuHVdU+xEAutnZ2doc7XL6caH8Ex3dvxU9Ll5RL3RlHTqQxwBxsYo4MZGc6SbLEzWpVK/gTqE2nrCMpQVb/F96dakVICzt2FM4uSQgJ2Twxx57ZVsD3rnNgxgSmfoCAxk0QghKiQ06mDZfMvGWzc2pIX/E//roDSBjLk/RzBDPB9wcX6z17uK8VndFvWhc4AI5fOZBa4PnXnlL1OdM6fIZAMq5SFGIc3SEEZgQD7NjWEmR3LYhVTTGs6YRx5pCeiSNEQj5HChpC5lUZku/xHxL/4Ub+IvEX1/yEWIQmYMt70ghmLTaQLv+C9U/RS7LxfZekanDA9elEvNYwVGWIqxIr/5mEvS9d8tjopA+ix1U58R5D2xiuHRFM7f0MtqbEgjvG6xjX1MBuupzZ1zhEXEp/sJWnVNYZrvbruyx4l90jrSqjAvbDFYgN8Vwa30GncBXCAtUpgerjStX+xfi4pgfntF2WZdMqLMPr5r0pFLhSaVk+Iq00R+W4hLzt5OOiWBSf0R7rpnABVuZb0/22YLBJTdNOBxn/hm6QSsygMP8UJRKWC7xar3HVu0TBHkxuQLVgwNw60kXZdKyL1NVo4d3hs0PDBVe/7IXXjQ0+v5wP+bGZQzff6tUrDjMaDorSsYK+/gXxQJw5

**Comment by mostafaznv** [comment] 2023-07-28 14:49
Should I follow up on this issue somewhere else?

**Comment by MoeinMirkiani** [comment] 2023-07-29 13:28
I'm having the same struggle :(

**Comment by mostafaznv** [comment] 2023-07-29 23:48
After [cloning](https://vuetifyjs.com/en/getting-started/contributing/) the source code and investigating it, I believe this is a Vuetify bug. However, I haven't been able to pinpoint the exact source of the issue yet.
When I run Vuetify's playground with `ssr: true`, the problem occurs. Therefore, I think the label of `NUXT` you put on this issue is not accurate, and this is a bug with SSR in Vuetify.

I will continue to find the exact reason for this, and if I discover it, I will submit a PR. However, I hope the Vuetify team checks and fixes this before I do :D

**Comment by mostafaznv** [comment] 2023-08-02 19:03
After conducting tests and researching the code, I believe there is something wrong with Vuetify (SSR with vite playground, not Nuxt). Under certain conditions (which were not a true solution and did not completely solve the issue), I was able to activate one of the tabs in SSR mode.

I found that the `transformIn` method in the following function is only called once in SSR mode, but it is called multiple times (number of tab items plus one) in non-SSR mode. This seems to be the cause of the issue, as the first time there are no items in the group.

https://github.com/vuetifyjs/vuetify/blob/c02fda4167eaa18e6c74f0e4add577aad10a7e40/packages/vuetify/src/composables/group.ts#L155-L169

Despite knowing these things, I couldn't fix this issue, and I think it might be related to `suspense`.
Sorry for bothering you, @KaelWD, but do you think this is related to #15215 and #15207?
I noticed you opened a PR to the Vue.js core to fix this issue, but it seems they ignored it. Is there any other workaround?"

**Comment by KaelWD** [comment] 2023-08-03 08:51
Duplicate of #15207

**Closed by KaelWD** 2023-08-03 08:51 UTC
Labels: duplicate
