### ISSUE TITLE
[Bug Report] <v-tooltip> inside open dialogs is not appearing in safari

### ISSUE THREAD

**Issue by erikmode** [vuetifyjs/vuetify#3627] opened 2018-03-20 12:43 UTC
**Versions and Environment**
Vuetify: 1.0.8
Vue: v2.5.16
Browsers: Safari Version 11.0.3 (13604.5.6)
OS: mac OS High Sierra (10.13)

**Steps to reproduce**
Using safari, go to https://vuetifyjs.com/en/components/dialogs. 
Click the first button in the first usage example "Open Dialog 1"
Hover mouse over text "Tool Tip Activator"

**Actual Behavior**
In safari the tool tip does not appear. It is covered by the dialog. It seems that the z-index is not correctly calculated and set on the tool tip, so it ends up behind the open dialog. 

**Reproduction Link**
https://vuetifyjs.com/en/components/dialogs
or 
https://codepen.io/pen/?&editors=101

**Comment by KaelWD** [comment] 2018-03-20 12:49
Duplicate of #3552

**Closed by KaelWD** 2018-03-20 12:49 UTC
