### ISSUE TITLE
[Feature Request] [v-number-input] support locale

### ISSUE THREAD

**Issue by mueller-jens** [vuetifyjs/vuetify#20568] opened 2024-10-11 14:43 UTC
### Problem to solve
The possibility to use other locale (decimal separator, thousend separator) then english

### Proposed solution
react on the locale set by the application or the browser

**Comment by KaelWD** [comment] 2024-10-12 11:43
Duplicate of #20254

**Closed by KaelWD** 2024-10-12 11:43 UTC
Labels: S: triage
