### ISSUE TITLE
[Bug Report][3.1.6] v-select disabled item does not work

### ISSUE THREAD

**Issue by peshanghiwa** [vuetifyjs/vuetify#16744] opened 2023-02-22 06:06 UTC
### Environment
**Vuetify Version:** 3.1.6
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a basic v-select component and pass a normal items array to it including some items that are flagged as disabled like the example below:

``` HTML
<script setup lang="ts">
import { ref } from 'vue'

const items = [
	{
		title: 'Item 1',
		value: 'item1'
	},
	{
		title: 'Item 2',
		value: 'item2',
		disabled: true // Not Working
	},
	{
		title: 'Item 3',
		value: 'item3'
	}
]
</script>

<template>
	<v-app>
		<v-main>
			<v-container>
				<v-select :items="items" placeholder="Select item"/>
			</v-container>
		</v-main>
	</v-app>
</template>
```

### Expected Behavior
To disable the item that is flagged as disabled

### Actual Behavior
Does not disable the item

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVU7GO2zAM/RVCS5bYapqig+E7XMcuXTp0ON2g2EyiRpYEiU5xCPzvpeQgvSbpAV1s8z3xkXyUn0/iSwj1cUTRiDZ10QSChDQGsNrtHpSgpMSjcmYIPhKcIOIWJthGP8CC0xbKKdd5lwgM4ZDgAZ4ZolN+KCJDFhtYfGUOVovljB61HTOaM1ZZgabC3Ev6eC/pAvYm6Y3FvgGKI4KU8M0T/PDxYNzufeH1PeH13I1yL8q1cvaDp+eAyWA1YY6oPVY6hPJZgkEbd45KzIYQQxgvYIETWuwImuIUe1veSgALd7j3tsfI6Pf5VCaVkH9k5a1uxi61czB31cq33bo20atFSJ0P2D/yWDlkRizFvFbWCPXP5B1fArYKgFsrBDfXQEEyxuvOsRJ7opAaKUcXDru684N8Yk7G0ZEZsOr98LSu1/WHStuw1/UnyWuit3SNaag20f9KGLmwEryKSw0y29d/1TnTLL+qP8+yZ6iyepOy7o2e5CJHjFVExwZjfHeGq7P35rg6cjNLLs03aGJ7rXGHdOVsl4qr/JfMHf7/kEUhp/MlncS0FH81yWVLonj5DZyhVxU=)

**Comment by fahmifitu** [comment] 2023-02-22 15:08
You can use it like this:```{
		title: 'Item 2',
		value: 'item2',
    props: {
      disabled: true
    },
	},```

**Comment by KaelWD** [comment] 2023-02-23 08:37
Duplicate of #15933

**Closed by KaelWD** 2023-02-23 08:37 UTC
Labels: duplicate, S: triage
