### ISSUE TITLE
[Bug Report] Transition is invalid when using v-tooltip inside v-speed-dial

### ISSUE THREAD

**Issue by lakxtxue** [vuetifyjs/vuetify#7910] opened 2019-07-22 11:57 UTC
### Versions and Environment
**Vuetify:** 2.0.0-beta.9
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
1.add a tooltip for the sub-button inside v-speed-dial
2.click the v-speed-dial button

### Expected Behavior
animated display

### Actual Behavior
directly shows no animation

### Reproduction Link
<a href="https://codepen.io/lakxtxue/pen/xvwXGj" target="_blank">https://codepen.io/lakxtxue/pen/xvwXGj</a>

**Comment by johnleider** [comment] 2019-07-22 19:15
Duplicate of #6640

**Closed by johnleider** 2019-07-22 19:15 UTC
Labels: duplicate

**Comment by Aymkdn** [comment] 2019-07-24 13:10
Hi @johnleider 

Both of the issues have been closed without information/explanation about the resolution. Is it a bug ? An expected behavior ? Is there a fix you're working on ?

Thanks.

**Comment by MajesticPotatoe** [comment] 2019-07-24 13:14
As stated, there is already an issue for this open.

**Comment by Aymkdn** [comment] 2019-07-24 13:19
Sorry, my bad, I misread the other one and thought it was closed too!
