### ISSUE TITLE
[Bug Report] Prepend Inner Icon issue when using with slots

### ISSUE THREAD

**Issue by HassanMehmood1992** [vuetifyjs/vuetify#9557] opened 2019-11-03 11:14 UTC
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
Create a text field within v-menu with slot

### Expected Behavior
Label should cater for the icon when using outlined

### Actual Behavior
label is not properly adjusted within outline region

### Reproduction Link
<a href="https://codepen.io/DKEMO/pen/VwwyRBX?&editable=true&editors=101" target="_blank">https://codepen.io/DKEMO/pen/VwwyRBX?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment] 2019-11-09 09:01
Most probably duplicate of https://github.com/vuetifyjs/vuetify/issues/9225

**Closed** 2019-11-13 10:55 UTC
Labels: C: VTextField, duplicate
