### ISSUE TITLE
[Feature Request] text-field with type password built-in visibility function

### ISSUE THREAD

**Issue by iliyaZelenko** [vuetifyjs/vuetify#4338] opened 2018-06-19 08:30 UTC
### Problem to solve
to add a password field with visibility control, I have to write everywhere

```
<v-text-field
      v-model="form.password"
      label="Password"
      :type="passwordShow ? 'text' : 'password'"
      :append-icon="passwordShow ? 'visibility' : 'visibility_off'"
      :append-icon-cb="() => (passwordShow = !passwordShow)"
      prepend-icon="security"
      required
/>
```
and add passwordShow to data

### Proposed solution
if v-text-field have type password you can make the built-in addition of the visibility function

**Comment by KaelWD** [comment] 2018-06-19 09:00
Duplicate of #3987

**Closed by KaelWD** 2018-06-19 09:00 UTC
