### ISSUE TITLE
[Bug Report] v-combobox's input event not triggered while typing

### ISSUE THREAD

**Issue by Masa-Shin** [vuetifyjs/vuetify#12893] opened 2021-01-05 05:43 UTC
### Environment
**Vuetify Version:** 2.3.23
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Mac OS 10.15.6

### Steps to reproduce
1. Click combobox.
2. Type something.
3. Input event is not triggered.

### Expected Behavior
Input event is triggered when typing.

### Actual Behavior
it is only triggered when an item is selected from menu.

### Reproduction Link
<a href="https://codepen.io/POPOPON/pen/MWjGJbp?editors=1011" target="_blank">https://codepen.io/POPOPON/pen/MWjGJbp?editors=1011</a>

### Other comments
Keydown event is triggered when typing but it emits a KeyboardEvent object, not an input value. I need an event which triggered when typing and emits input value.

**Comment by KaelWD** [comment] 2021-01-05 05:49
Duplicate of #4679

**Closed by KaelWD** 2021-01-05 05:49 UTC
Labels: triage
