### ISSUE TITLE
[Bug Report] VBtn Ripples remain bug

### ISSUE THREAD

**Issue by RP-KentaroAoki** [vuetifyjs/vuetify#12076] opened 2020-08-19 04:30 UTC
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Windows

### Steps to reproduce
Quickly right-click and left-click on buttons with the mouse

### Expected Behavior
Ripples disappear after clicking

### Actual Behavior
The ripples remain and the button color becomes the ripple color.
<img width="1280" alt="ripple" src="https://user-images.githubusercontent.com/69883661/90592260-21ac6b00-e220-11ea-91a3-28d1c3e664c8.png">

### Reproduction Link
<a href="https://codepen.io/KentaroAoki/pen/MWyjyyV?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fja%2Fcomponents%2Fbuttons%2F" target="_blank">https://codepen.io/KentaroAoki/pen/MWyjyyV?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fja%2Fcomponents%2Fbuttons%2F</a>

**Comment by KaelWD** [comment] 2020-08-19 04:58
Duplicate of #4185

**Closed by KaelWD** 2020-08-19 04:58 UTC
Labels: triage
