### ISSUE TITLE
[Bug Report] Tabs Align right doesn't work in responsive mode

### ISSUE THREAD

**Issue by nicmar** [vuetifyjs/vuetify#8627] opened 2019-08-20 11:08 UTC
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.4

### Steps to reproduce
This codepen is straight from the tabs page:
Visit https://vuetifyjs.com/en/components/tabs#tabs 

Visit page in a browser that is so small to the left menu hides, about 1200 px. 

### Expected Behavior
Tabs aligned to the right

### Actual Behavior
Tabs not aligned to the right

### Reproduction Link
<a href="https://codepen.io/nicmar/pen/BaBLqbz" target="_blank">https://codepen.io/nicmar/pen/BaBLqbz</a>

![Uploading Skärmavbild 2019-08-20 kl. 13.09.15.png…]()

**Comment by jacekkarczmarczyk** [comment] 2019-08-20 11:16
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8294

**Closed by jacekkarczmarczyk** 2019-08-20 11:16 UTC
Labels: triage
