### ISSUE TITLE
[Bug Report][2.6.4] Theme custom property does not work with rgba

### ISSUE THREAD

**Issue by lukaslaskovski** [vuetifyjs/vuetify#14953] opened 2022-04-11 15:15 UTC
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.11
**Browsers:** Chrome 100.0.4896.75
**OS:** Mac OS 10.15.7

### Steps to reproduce
The defined colors work normally apart from rgba e.g.
```
div.test {
   background-color: rgba (var(--v-primary-base), .3);
   color: var(--v-primary-base);
}
```
Text color appears correctly. The background does not render at all.
Maybe I define it incorrectly? In dev-tools, I see a crossed-out text rendering:
```
background-color: var(--v-primary-base);
```

### Expected Behavior
Should render background with opacity 30%.

### Actual Behavior
Not rendering at all.

### Reproduction Link
<a href="https://codepen.io/bufszak/pen/zYpLBNa" target="_blank">https://codepen.io/bufszak/pen/zYpLBNa</a>

**Comment by KaelWD** [comment] 2022-04-11 15:17
Duplicate of #9282

This only work in v3

**Closed by KaelWD** 2022-04-11 15:17 UTC
Labels: S: triage
