### ISSUE TITLE
v-edit-dialog is transparent

### ISSUE THREAD

**Issue by ais-one** [vuetifyjs/vuetify#5145] opened 2018-09-22 11:40 UTC
### Versions and Environment
Vuetify: 1.2.4
Vue: N.A.
Browsers: Chrome, Edge
OS: Windows

### Steps to reproduce

Goto the Vuetify documentation site version 1.2.4

https://vuetifyjs.com/en/components/data-tables

Go to inline editing example, once you click, you can see the dialog is transparent, very irritating. I attach screenshot

![capture](https://user-images.githubusercontent.com/4284574/45916857-1834ef80-be9f-11e8-814f-82faf6a67be7.PNG)

Go to same page with earlier version 1.0.X, you will not see that problem

### Expected Behavior

The edit dialog should not be transparent

### Actual Behavior

The edit dialog is transparent and it is not correct

### Reproduction Link

https://vuetifyjs.com/en/components/data-tables - version 1.2.4

https://vuetifyjs.com/en/components/data-tables - version 1.0.X

**Comment by jacekkarczmarczyk** [comment] 2018-09-22 12:02
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5127

**Closed by jacekkarczmarczyk** 2018-09-22 12:02 UTC
