### ISSUE TITLE
[Bug Report][3.3.10] Ripple elements are sometimes not removed

### ISSUE THREAD

**Issue by Moumirrai** [vuetifyjs/vuetify#17918] opened 2023-07-30 10:54 UTC
### Environment
**Vuetify Version:** 3.3.10
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
Quickly click the right and left mouse buttons alternately on any element with a ripple.

### Expected Behavior
Ripple elements should be removed at the end of the animation.

### Actual Behavior
In this case that they are not removed and they accumulate.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUktu4zAMvQqhTTexnaIzmyATZI4w67oLRWYaTfWDRLsNgty9lOzWRrop0JUl8n34KD9exN8Q6qFHsRFbQhuMJNy1DmA7VDIEUEam9KcVVlb361aUVmkqGTvYK6PVC7dbASfUzyfi8+81A0F54yPfInbcLiyA3USsSJPBT3HCN6oUOsI4Yxn9r2d1c2Ycf4FOCDF7gHQdGDwSWN8nhENP5F2aidKwkuMk5lxvm6XlPMhUHgtzrAO5OTOVzDDIqKXL0XxPRrucaJekRR5Ju+csxbRxa3zmtfF52yzWydekog4ECanPbQBtg48EF4h4hCsco7dwxy9xl7kjmnFiJUZgZWWo/yfv+KUumd9OjdSKDZRKrrFAvrfiRBTSpmlU55jWodFDrB1S44Jt9gxrYu9IW6w6b/cP9UP9q+l0omW5xmSrQ/SvCSOLtGK1sCF9PH/DakIWh/v1aDHVKiMPKXt80W7YcMBYRXQdxvxXfC/SDW0Z66b1JVp2v7buygvnJ35JN7tWqez58WPIn2UualnqKTteV6IMytYjQzy9A1QPMgw=)

### Other comments
This problem is in virtually every version of Vuetify 3

**Comment by KaelWD** [comment] 2023-08-09 08:52
Duplicate of #4185

**Closed by KaelWD** 2023-08-09 08:52 UTC
Labels: S: triage
