### ISSUE TITLE
[Bug Report] Double v-overlay after session is restored from computer sleep

### ISSUE THREAD

**Issue by josh-hemphill** [vuetifyjs/vuetify#10208] opened 2020-01-13 16:46 UTC
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Windows 10

### Steps to reproduce
Have a timed 'logout' running that changes the page of the application and has a logout popup (that's probably where they're coming from), then let the computer go to sleep such that the session gets suspended, and then return to the application.   

### Expected Behavior
Overlays should be cleaned up on page change like everything else did.

### Actual Behavior
The overlays remain while their contents get removed, preventing any interaction with the contents of the current page.

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-routed-auth-app-c8tk6" target="_blank">https://codesandbox.io/s/vuetify-routed-auth-app-c8tk6</a>

**Comment by jacekkarczmarczyk** [comment] 2020-01-13 16:54
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8625

**Closed by jacekkarczmarczyk** 2020-01-13 16:54 UTC
Labels: triage
