### ISSUE TITLE
[Feature Request] Event to be Fired when Snackbar closes after timeout.

### ISSUE THREAD

**Issue by prashant1k99** [vuetifyjs/vuetify#9623] opened 2019-11-08 06:49 UTC
### Problem to solve
Developers can handle the state change after the snackbar closes due to time out.

### Proposed solution
Create an event for the V-Snackbar component which is automatically fired whenever the user closes the Snackbar or by timeout.

**Comment by jacekkarczmarczyk** [comment] 2019-11-08 06:55
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8658
See also https://github.com/vuetifyjs/vuetify/issues/9538

**Closed by jacekkarczmarczyk** 2019-11-08 06:55 UTC
Labels: triage
