### ISSUE TITLE
[Bug Report] Dialog open transition does only on first open

### ISSUE THREAD

**Issue by pepe-github** [vuetifyjs/vuetify#10539] opened 2020-02-11 09:38 UTC
### Environment
**Vuetify Version:** 2.2.11
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.87
**OS:** Windows 10

### Steps to reproduce
- Open CodePen link
- Click on "Click me"
- Close dialog
- Open it again

### Expected Behavior
Recover transition

### Actual Behavior
Dialog open transition does only on first open and never on close

### Reproduction Link
<a href="https://codepen.io/Deepfreeze/pen/NWqqLwX?editors=1010" target="_blank">https://codepen.io/Deepfreeze/pen/NWqqLwX?editors=1010</a>

**Comment by KaelWD** [comment] 2020-02-11 11:24
Duplicate of #10536

**Closed by KaelWD** 2020-02-11 11:24 UTC
Labels: triage
