### ISSUE TITLE
[Bug Report] No open and close animations on Dialog component

### ISSUE THREAD

**Issue by MaciejJanyska** [vuetifyjs/vuetify#10541] opened 2020-02-11 11:07 UTC
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Firefox 73.0
**OS:** Mac OS 10.15

### Steps to reproduce
1. Click button "Click me"
2. Close dialog
3. Open it again

### Expected Behavior
Dialog should be animated every time

### Actual Behavior
When Dialog is opened for the first time everything is fine, but each subsequent opening and closing has no animation except overlay.

### Reproduction Link
<a href="https://codepen.io/MaciejJanyska/pen/jOPPejP" target="_blank">https://codepen.io/MaciejJanyska/pen/jOPPejP</a>

**Comment by jacekkarczmarczyk** [comment] 2020-02-11 11:14
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10539

**Closed by jacekkarczmarczyk** 2020-02-11 11:14 UTC
Labels: triage

**Comment by KaelWD** [comment] 2020-02-11 11:23
Duplicate of #10536
