### ISSUE TITLE
Speed Dial

### ISSUE THREAD

**Issue by fortil** [vuetifyjs/vuetify#515] opened 2017-05-10 18:30 UTC
Hi guys

I will like that you will implement a "Speed dial" like as [vue-material](https://vuematerial.github.io/#/components/speed-dial). while that they implement it, somebody knows how can I do it?

Thanks

**Comment by nekosaur** [comment] 2017-05-10 18:36
Duplicate of https://github.com/vuetifyjs/vuetify/issues/369

**Closed by nekosaur** 2017-05-10 18:36 UTC
Labels: duplicate
