### ISSUE TITLE
Navigation drawer doesn't highlight current route visually

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#1429] opened 2017-08-20 11:01 UTC
### Steps to reproduce
Use vue-router and create a navigation drawer with some links, then navigate to one of them.

### Versions
Vue 2.4.2, Vuetify 0.14.11, Edge 15.

### What is expected ?
The current route should be highlighted visually.

### What is actually happening ?
While `list__tile--active` is applied to the active route that should apply a blue color, the highlight color is overwritten by `.application--light .navigation-drawer .list__tile`. Also, bear in mind that event without that rule, `.application--light .navigation-drawer a, .application--light .navigation-drawer .subheader, .application--light .navigation-drawer .list` would take precendence over `.list__tile--active`

### Reproduction Link
https://codepen.io/anon/pen/qXoaqO

**Comment by jacekkarczmarczyk** [comment] 2017-08-20 11:56
That's already fixed on dev branch

**Comment by smares** [comment] 2017-08-20 12:03
Is it the same as #1374? If yes, sorry, that title was misleading because the class **is** applied, it's just that its style is overriden.

**Comment by johnleider** [comment] 2017-08-20 14:40
Duplicate of #1374

**Closed by johnleider** 2017-08-20 14:40 UTC
