### ISSUE TITLE
[Bug Report] Missing "value" prop for VTab component

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12331] opened 2020-10-01 19:05 UTC
### Environment
**Vuetify Version:** 2.3.12
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.6

### Steps to reproduce
Right now in the `VTabs` component you can only reference tabs by their index. IMO there should be a possibility to reference tabs by some custom `value` like it is implemented for `v-list-item-group`.

In `v-list-item-group` component, you can provide `value` props for `v-list-items` children. Thanks to that you can reference list items by some custom value

### Expected Behavior
There should be a possibility to reference tabs by some custom value like in `v-list-item-group` component.

### Actual Behavior
There is no possibility to reference tabs by custom value.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/WNwqdzy" target="_blank">https://codepen.io/mikilll94/pen/WNwqdzy</a>

**Comment by KaelWD** [comment] 2020-10-02 09:04
Duplicate of #10540

**Closed by KaelWD** 2020-10-02 09:04 UTC
Labels: triage
