### ISSUE TITLE
[Bug Report] Opaque Icons

### ISSUE THREAD

**Issue by hwright08** [vuetifyjs/vuetify#10491] opened 2020-02-06 15:59 UTC
### Environment
**Vuetify Version:** 2.2.10
**Last working version:** 2.2.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Use any icon (including the table column sort icon)

### Expected Behavior
For Icons to be the color I set them to be and not vary from that unless specified.

### Actual Behavior
Icons have an opacity that does not match the expected result.

### Reproduction Link
<a href="https://codepen.io/hrwright08/pen/yLNLvjg?editable=true" target="_blank">https://codepen.io/hrwright08/pen/yLNLvjg?editable=true</a>

**Comment by MajesticPotatoe** [comment] 2020-02-06 16:02
sure you are using 2.2.10? looks fine in codepen
![2210](https://user-images.githubusercontent.com/27827979/73954640-18852d80-48d0-11ea-91c3-aa0dabe0512e.png)

2.2.9 had a bug that had opacity issues like so:
![229](https://user-images.githubusercontent.com/27827979/73954665-25098600-48d0-11ea-85b0-2610369467af.png)

**Comment by KaelWD** [comment] 2020-02-06 16:03
Duplicate of #10466

**Closed by KaelWD** 2020-02-06 16:03 UTC
Labels: triage
