### ISSUE TITLE
[Feature Request] Select type for paths

### ISSUE THREAD

**Issue by tlindener** [vuetifyjs/vuetify#12034] opened 2020-08-11 06:39 UTC
### Problem to solve
Imagine you have a file manager like scenario where the tree shows a folder structure. Now we want to think of this structure as paths and not individual folders. In this case neither independent nor leaf mode work quite right because leaf mode does not allow the respective parent to be selected without its children.

### Proposed solution
Implement another mode (e.g. called path) where when selecting an intermediate node within a tree its parents are selected but not its children.
E.g.:
If I select Node 1.1.1 all nodes to this one are selected (Node 1; Node 1.1.; Node 1.1.1)
If I select Node 1.1 the following nodes are selected (Node 1; Node 1.1)
Root
- Node 1
  - Node 1.1
    - Node 1.1.1
    - Node 1.1.2
- Node 2
  - Node 2.1
    - Node 2.1.1
    - Node 2.1.2

**Comment by KaelWD** [comment] 2020-08-11 06:59
Duplicate of #7799

**Closed by KaelWD** 2020-08-11 06:59 UTC
Labels: triage
