### ISSUE TITLE
[Feature Request] Model data don't bind at onType(Non-blur)

### ISSUE THREAD

**Issue by Revel109** [vuetifyjs/vuetify#10202] opened 2020-01-13 05:18 UTC
### Problem to solve
Some users just type for something to search but the expected data don't get bind at non-blur situations.

### Proposed solution
@input.native="e => modelData = e.target.value"

Here, i did solve my problem.

It should be here as a feature.

**Comment by jacekkarczmarczyk** [comment] 2020-01-13 05:22
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4679

**Closed by jacekkarczmarczyk** 2020-01-13 05:22 UTC
Labels: triage
