### ISSUE TITLE
[Bug Report] When `:menu-props="{ offsetY: true, closeOnClick: true }"` is set to `v-select`, the menu does not open when clicking the `activator`

### ISSUE THREAD

**Issue by imunew** [vuetifyjs/vuetify#12376] opened 2020-10-08 07:35 UTC
### Environment
**Vuetify Version:** 2.3.13
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.6

### Steps to reproduce
1. Add `:menu-props="{ offsetY: true, closeOnClick: true }"` to `v-select`
1. Click `activator`(`v-icon` placed on the right end, arrow-down)

### Expected Behavior
Open menu (item list)

### Actual Behavior
Nothing happens (menu doesn't open)

### Reproduction Link
<a href="https://codepen.io/imunew/pen/abZbPLK" target="_blank">https://codepen.io/imunew/pen/abZbPLK</a>

**Comment by KaelWD** [comment] 2020-10-08 17:41
Duplicate of #11115

**Closed by KaelWD** 2020-10-08 17:41 UTC
