### ISSUE TITLE
[Bug Report] Touch events bleeding through on iOS devices

### ISSUE THREAD

**Issue by daviesdoclc** [vuetifyjs/vuetify#6353] opened 2019-02-04 18:27 UTC
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Safari 12.0.3, Safari
**OS:** Mac OS 10.14.3, iOS

### Steps to reproduce
I'm building a Cordova hybrid app using Vue/Vuetify.  I'm having issues with touch events bleeding through to my content area.  Specifically v-toolbar, v-bottom-nav, and v-navigation-drawer.  I've put a demonstration up at https://codepen.io/funkyvisions/live/OdgqQE.  Open the link on your iOS device and then open the drawer using the menu button.  You'll notice when you swipe up and down in the drawer that the content area also does.  Same if you swipe on the overlay (darkened) area.  The toolbar and navbar do the same thing.  This works fine on Android.

You can also see it happen on vuetifyjs.com when viewing with your iOS device.  Go to getting started and select the hamburger menu.  You'll notice the content doesn't scroll YET when swiping in the menu.  However if you swipe in the overlay zone, it will.  And while that is still scrolling if you swipe over in the menu, it will continue responding over there.  Strange.

### Expected Behavior
Don't scroll content area

### Actual Behavior
Content area scrolls

### Reproduction Link
<a href="https://codepen.io/funkyvisions/live/OdgqQE" target="_blank">https://codepen.io/funkyvisions/live/OdgqQE</a>

### Other comments
On my previous hybrid app I didn't use a UI framework.  I remember having to do something there when I displayed an overlay.  I had to apply something to the body to prevent scrolling.  Although that wouldn't really help with the toolbar and nabber that are always shown.  My previous app I had to make the whole display a Flexbox and then the content area was flex:1 and the toolbar and navbar just pushed themselves to the top and bottom.  I could do that here, but I'm really trying to use <v-container> with fixed toolbar and navbar.

**Comment by johnleider** [comment] 2019-02-04 19:11
I'm in the process of getting browerstack hooked up so that I can better test these conditions.

**Comment by KaelWD** [comment] 2019-02-05 02:59
Duplicate of #3875

**Closed by KaelWD** 2019-02-05 02:59 UTC
Labels: T: bug

**Comment by husayt** [comment] 2019-12-23 01:14
It's not really a duplicate of 3875, that one is specifically about dialog component. This one is about toolbar, navigation drawer and bottom nav. This issue is number one cause of complaints I have from our ios users. Is there a known workaround until this properly resolved here?

Thanks

**Comment by KaelWD** [comment] 2019-12-23 05:53
They all use the same overlay mechanism.
