### ISSUE TITLE
[Feature Request] New Text Field Label Design

### ISSUE THREAD

**Issue by rajagopalx** [vuetifyjs/vuetify#5931] opened 2018-12-18 10:37 UTC
### Problem to solve
Place holder Label occupies space in text field.

### Proposed solution
New Google label design solves space problem.

![48362272_326355641551313_2236919336847540224_n](https://user-images.githubusercontent.com/10378178/50148614-f51fad80-02de-11e9-9435-3328624ec1a2.jpg)

**Comment by jacekkarczmarczyk** [comment] 2018-12-18 10:43
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4364

**Closed by jacekkarczmarczyk** 2018-12-18 10:43 UTC
