### ISSUE TITLE
[Bug Report] [Button] Icons in floating buttons are not centered on project setup with vue-cli-plugin-vuetify

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#6985] opened 2019-04-14 03:51 UTC
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Ubuntu undefined, Windows

![image](https://user-images.githubusercontent.com/1400380/56088068-bc778700-5e2d-11e9-940f-f50554678e0d.png)

### Steps to reproduce
Unknown. I can only reproduce this when using a project setup with the vue-cli plugin.... anytime I use the .css directly this works fine.

### Expected Behavior
Icons would be centered

### Actual Behavior
Icons are not centered, they are at the top of the button.

### Reproduction Link
<a href="https://codepen.io/anon/pen/ZZJNNJ" target="_blank">https://codepen.io/anon/pen/ZZJNNJ</a>  (not an actual reproduction, this works as expected with the css import)

### Other comments
This is caused by the `.material-icons` styling being applied after the `.v-icon` styling. Which causes the `v-icon` to be displayed as an `inline-block` instead of `inine-flex`.

**Comment by johnleider** [comment] 2019-04-14 15:06
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5741

**Closed by johnleider** 2019-04-14 15:06 UTC

**Comment by douglasg14b** [comment] 2019-04-14 18:38
@johnleider 

The `.css` is seemingly not loaded directly by the project setup with `vue-cli-plugin-vuetify`? Changing the order to load icons before vuetify doesn't change the behavior.

Here is what it is doing:

**main.ts:**

```js
import './plugins/vuetify'
import 'material-design-icons-iconfont/dist/material-design-icons.css'
```

**plugins/vuetify.ts:**

```ts
import Vue from 'vue'
import Vuetify from 'vuetify/lib'
import 'vuetify/src/stylus/app.styl'

Vue.use(Vuetify, {
  iconfont: 'md',
})
```


If I swap the order of `import './plugins/vuetify'` and `import material-design-icons...` the issue persists (I also cleared any build cache just to be sure).

**Comment by johnleider** [comment] 2019-04-14 18:44
Then we need an actual reproduction outside of your project.
