### ISSUE TITLE
[Feature Request] Create vertical direction of v-tabs

### ISSUE THREAD

**Issue by oneji** [vuetifyjs/vuetify#4103] opened 2018-05-20 21:01 UTC
### Problem to solve
Please add a vertical mode of v-tabs. I usually have to use another plugin in order to achieve my problem.

### Proposed solution
Creating a new props that makes v-tabs vertical.

**Comment by nekosaur** [comment] 2018-05-21 10:10
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3971

**Closed by nekosaur** 2018-05-21 10:10 UTC
Labels: duplicate
