### ISSUE TITLE
[Bug Report][3.0.4] VSelect Item Header/Divider special properties doesn't work

### ISSUE THREAD

**Issue by vcastro45** [vuetifyjs/vuetify#16241] opened 2022-12-08 14:41 UTC
### Environment
**Vuetify Version:** 3.0.4
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a VSelect with "normal items" and header/dividers (according to the Vuetify 3 doc and Vuetify 2 behavior).

Doc reference: https://vuetifyjs.com/en/api/v-select/#props-items

### Expected Behavior
Expect to add header/divider to the item list

### Actual Behavior
Causes error in console and component crash

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFU8tu2zAQ/BWWKKAW0KNo04ugBAmCNj0UufQUWAaix9pmTJEESSkoBP17l5TkqErd2Ad7Z2dnl7Pkpqc3SsVdCzSlmak0U5YYsK26ygVrlNSW9ETDjgxkp2VDAqQGuchFJYVxVA6VJZeO8qEnxhYWUhJ851KzughCUpSldsDPgAwf5ypmoTFT0SYXZPq8VR/+i3oHUu/Zgnp3s6YeoKjBpX74PxhrIO/OCd5DqQtzXCjefzvHvS0420ktlv1vT/1z6749qVnH/ABWt3C26zN5kPq46Pqw7LpF87JkXBCuBgP0UHEsxoiQrIsK5XbmuBg0BRNT5ONxTzOAeVkDv8zphNM5kx6YsIg/vu/HVOwHHEJyAtx4w+OixG8Ta/zvC+7CyDLLwfVxKqtcV/DW5ZzgS4oXpZ/s12oyBdowY0HYyM04wxrvqhaRLJ8W5zNM7DlEnAkYoassmT2YPULgZJILRvuyZGErDen4BJCp4icjBT6S3m92SuBxU+IRh+HTcHFOD9YqkyZJK9RxH1eySa4xl+hWWNZAVMvm+kv8Ob74mtR4pCUeg2miUstnAxo75nS6AF7cst3vcw2mNOp+ii9G2Qlykq+kEtTvQEcaBN5MQP//M/eK+9fsq9yr+V3PIRcDeonrOJqVjZXxFm62jjKEdJRGsj8H3f4BRw12bw==)

**Comment by ajslater** [comment] 2022-12-09 22:27
Related to https://github.com/vuetifyjs/vuetify/issues/15721

**Comment by johnleider** [comment] 2023-01-23 15:55
Duplicate of #15721

**Closed by johnleider** 2023-01-23 15:55 UTC
Labels: duplicate
