### ISSUE TITLE
[Feature Request] Disable browser autocompletion for select components

### ISSUE THREAD

**Issue by mehr-it** [vuetifyjs/vuetify#8618] opened 2019-08-19 11:29 UTC
### Problem to solve
If you press "Enter" to select an option from the `v-autocomplete` or `v-select` dropdown and submit the form, some browsers (Crhome, etc..) show their autocomplete picker over Vuetify's dropdown list after page reload and focusing the component again

This is very confusing when you focus the field again and two dropdowns open.

### Proposed solution
Add `autocomplete="off"` to the input:

```
{
    genInput() {
      const input = VTextField.options.methods.genInput.call(this);
      input.data.domProps.value = null;
      input.data.attrs.readonly = true;
      input.data.attrs.type = 'text';
      input.data.attrs['aria-readonly'] = true;

      // add this line
      input.data.attrs.autocomplete = 'off';

      input.data.on.keypress = this.onKeyPress;
      return input;
    },
}
```

**Comment by MajesticPotatoe** [comment] 2019-08-19 12:04
This feature already exists and is inherited from `v-text-field`. In 2.0 `autocomplete` prop propagates down to the inner input. (this was called `browser-autocomplete` in 1.5). For selects specifically it no longer defaults to `on`. If you are experiencing issues with this please submit a bug report with a valid reproduction.

**Comment by mehr-it** [comment] 2019-08-19 13:26
thx for your quick response!

Ok, you are right: setting the attribute explicitly works. But I think, for `v-autocomplete` and `v-select` one should not have to explicitly set this attribute. It should default to "off". I can't imagine a usecase where autocompletion makes sense and does not mess up the user interface...

..and if it is not explicitly disabled, at laest chrome shows up the autocompletion...

**Comment by MajesticPotatoe** [comment] 2019-08-19 14:02
Fair enough. For selects/combos/autocomplete would be best to have this default to `off`. Keep in mind however there is still no guarantee that it will have affect. Chrome for example has been know to explicitly ignore it in the past.

**Comment by KaelWD** [comment] 2020-11-19 14:06
Duplicate of #9516

**Closed by KaelWD** 2020-11-19 14:06 UTC
Labels: C: VSelect, T: enhancement
