### ISSUE TITLE
[Bug Report] VTabs margin 

### ISSUE THREAD

**Issue by jasonrhaddix** [vuetifyjs/vuetify#8486] opened 2019-08-12 22:13 UTC
### Environment
**Vuetify Version:** 2.0.5
**Last working version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
Use `grow` property on VTabs and reduce viewport < 1264px

### Expected Behavior
Tabs should not add pagination spacing.

### Actual Behavior
Margin is being added to the left of the tabs under viewport 1264px

### Reproduction Link
<a href="https://codepen.io/Jasonrhaddix/pen/eYOpzzz" target="_blank">https://codepen.io/Jasonrhaddix/pen/eYOpzzz</a>

### Other comments
I'm also seeing this when NOT using the grow prop, and in vertical mode, but this may be the intended functionality?

The issue can also be seen on the examples in the docs for VTabs: https://vuetifyjs.com/en/components/tabs

**Comment by jacekkarczmarczyk** [comment] 2019-08-12 22:14
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8294

**Closed by jacekkarczmarczyk** 2019-08-12 22:14 UTC
Labels: triage

**Comment by jasonrhaddix** [comment] 2019-08-12 22:28
@jacekkarczmarczyk I do not believe this is the same issue - a pre-existing position has not been established as in #8294. 

I explicitly defined `grow` to fill the containing area, but a left margin of 52px gets added regardless (assuming to accommodate pagination control(s)) on viewport sized under 1264px

**Comment by jasonrhaddix** [comment] 2019-08-12 22:30
@jacekkarczmarczyk Nevermind. I see the issue in the additional example in #8294. Disregard my previous comment.
