### ISSUE TITLE
[Feature Request] v-checkbox array model - rules

### ISSUE THREAD

**Issue by ppatkar** [vuetifyjs/vuetify#5627] opened 2018-11-16 04:53 UTC
### Problem to solve
Extension to issue #5467
Rules are triggered for individual check boxes. Instead they should be triggered at a group level.
https://codepen.io/prasmi/pen/rQwzBp

### Proposed solution
Have a component similar to v-radiogroup  like suggested in referred issue v-checkbox-group

**Comment by nekosaur** [comment] 2018-11-16 08:42
This is a duplicate of the referenced issue. Rules validation is included in the scope of the group component.

**Closed by nekosaur** 2018-11-16 08:42 UTC
Labels: duplicate

**Comment by stas-kh** [comment] 2019-04-03 09:41
@ppatkar for now you can check my https://github.com/vuetifyjs/vuetify/issues/5467#issuecomment-479416602
