### ISSUE TITLE
Date picker - wrong month on Chromium based browsers

### ISSUE THREAD

**Issue by elceka** [vuetifyjs/vuetify#2156] opened 2017-10-12 09:01 UTC
See Vuetify docks page for version 0.16 for Date picker component.

Versions:
- Vuetify 0.16.5
- Vue 2.4.4
- OSX 10.11.6
- Chrome 61.0.3163.100
- Opera 48.0.2685.32

Actual month on date picker is not correct (you can check it on Vuetify's components page). In header is showed correct month (for now October), but pagination in the middle show month September.
Issue is on month April, April is not in the list of months pagination, March is there twice.

On Safari 10.1.2 and Firefox 55.0.3 is all OK.

**Comment by jacekkarczmarczyk** [comment] 2017-10-12 09:41
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2022

**Closed by jacekkarczmarczyk** 2017-10-12 09:42 UTC
