### ISSUE TITLE
Encapsulate stylus css

### ISSUE THREAD

**Issue by siamakmirzaie** [vuetifyjs/vuetify#7629] opened 2019-06-21 17:02 UTC
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
trying to encapsulate the styles with into custom class where
.app
  @import './../../node_modules/vuetify/src/stylus/app.styl'

is used, different paths (relative, ~, etc.) and files (main.styl) used, but this will result into an error variables not being found.

One way to get this to work is by:
app = @block {
  @import './../../node_modules/vuetify/src/stylus/app.styl'
}
.app
  {app}

however when using blocks i am missing some classes such as elevations.

### Expected Behavior
Encapsulate the imported style under class name.

### Actual Behavior
Stylus

### Reproduction Link
<a href="https://jsfiddle.net/jso86dz7/" target="_blank">https://jsfiddle.net/jso86dz7/</a>

**Comment by Tostifrosti** [comment] 2019-06-24 07:26
+1, same here

**Comment by johnleider** [comment] 2019-06-24 14:39
Your reproduction link doesn't work. Also, anything involving this would have to be implemented in v2.0 with sass/scss.

**Comment by johnleider** [comment] 2019-07-09 15:17
duplicate of #5041

**Closed by johnleider** 2019-07-09 15:17 UTC
Labels: triage
