### ISSUE TITLE
[Bug Report][3.3.0] Type error when declaring @click events on buttons with no props

### ISSUE THREAD

**Issue by jfrs** [vuetifyjs/vuetify#17404] opened 2023-05-19 14:26 UTC
### Environment
**Vuetify Version:** 3.3.0
**Vue Version:** 3.3.4
**Browsers:** Firefox 113.0
**OS:** Windows 10

### Steps to reproduce
When declaring a click handler on a `v-btn` or a `v-app-bar-nav-icon` without any other props, I get `error TS2559: Type '{ onClick: any; }' has no properties in common with type '{ symbol?: any; replace?: boolean | undefined; flat?: boolean | undefined; exact?: boolean | undefined; block?: boolean | undefined; active?: boolean | undefined; style?: StyleValue | undefined; ... 47 more ...; "v-slot:loader"?: false | ... 1 more ... | undefined; }'`.

### Expected Behavior
No error is shown when using `<v-btn @click="() => {}">`

### Actual Behavior
Type error mentioned above

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUcFOwzAM/ZUoJ5DWBmmcpm4aB/iJZYeuNRDWpJHjFqGp/46Tlal0HCZxy7P93rNfdif55H3edyBXsiCwvikJNtoJUfRZ6X16JmBL40aU8IGc2FaNqY5rLe/uxXojToOWm2fEFguVBi7zM15foikdMbHtqDEOai3/FHvh3m+tiC6rRHBeslCT5RmGCo0nEYA6L5rSvbEuBVaMo+cmP+VCGutbJJb0+UdoHcdwisp6bDBlJVIl1jiniLV8J/JhpVRVO6bV0JgecweknLdqy2MKO0fGQla3drvMl/mjqk2gaTmHYLMDtp8BkEW0XExsyLx+3WA1TiaHh7PDWMqa8hCixZW0Yr8eMENwNSDgrRfNaNOrZq2ry6L7oN3AefNvH8Ms6iqkmHc/S/7r5CQWlfbRcFjItCc7J4LcfwO4P/mW)

### Other comments
It could be related to https://github.com/vuejs/language-tools/issues/3122 but I'm not sure how to investigate further, and the error seems to be different.

**Comment by KaelWD** [comment] 2023-05-19 14:54
Duplicate of #16190

**Closed by KaelWD** 2023-05-19 14:54 UTC
Labels: S: triage
