### ISSUE TITLE
[Bug Report] Navigation drawer unexpected gap if the with parameter is specified

### ISSUE THREAD

**Issue by bzsozsy** [vuetifyjs/vuetify#11076] opened 2020-04-10 06:53 UTC
### Environment
**Vuetify Version:** 2.2.21
**Last working version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Linux x86_64

### Steps to reproduce
Please check the attached codepen link. If you define a with to navigation drawer which is smaller than standard it creates a gap. In the example the width is 200px and there is 56 px gap which came from the full with of the navigation drawer. There is no any issue if the navigation drawer is used with it's standard with though.

### Expected Behavior
Put the content next to the navigation drawer without any gap.

### Actual Behavior
There is a 56 px gap between the content and the navigation drawer.

### Reproduction Link
<a href="https://codepen.io/bzsozsy/pen/YzyKByX" target="_blank">https://codepen.io/bzsozsy/pen/YzyKByX</a>

**Comment by jacekkarczmarczyk** [comment] 2020-04-10 13:30
navigation's width is set correctly, but v-content has default (256px) padding if width is provided with `px`

**Comment by DispatchCommit** [comment] 2020-04-12 05:54
Any workarounds for this?

**Comment by jacekkarczmarczyk** [comment] 2020-04-12 06:17
`width="200"`?

**Comment by KaelWD** [comment] 2020-04-12 06:21
Duplicate of #10968

**Closed by KaelWD** 2020-04-12 06:21 UTC
Labels: C: VNavigationDrawer, T: bug

**Comment by DispatchCommit** [comment] 2020-04-12 11:13
@jacekkarczmarczyk Seems that it has to be passed as a number specifically currently,`:width="200"` (or `:mini-variant-width="64"` in my case). Thank you though.
