### ISSUE TITLE
[Bug Report] Slider not resizing under tab when icons-and-text prop is changed

### ISSUE THREAD

**Issue by Logikgate** [vuetifyjs/vuetify#12524] opened 2020-10-28 21:18 UTC
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.111
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click on the toggle button in the attached codepen. You will see that the slider doesn't resize with the tab.

### Expected Behavior
The slider should resize and be properly placed under the tab

### Actual Behavior
The slider remains the same width and position

### Reproduction Link
<a href="https://codepen.io/logikgate/pen/JjKpOdJ" target="_blank">https://codepen.io/logikgate/pen/JjKpOdJ</a>

**Comment by jacekkarczmarczyk** [comment] 2020-10-28 21:20
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4733, https://github.com/vuetifyjs/vuetify/issues/6466 and others

**Comment by jacekkarczmarczyk** [comment] 2020-10-28 21:29
right, that could be fixed ;)

**Closed** 2020-11-04 09:27 UTC
Labels: C: VTabs, T: bug
