### ISSUE TITLE
[Bug Report][3.3.4] VDatePicker hangs when setting locale with date-fns

### ISSUE THREAD

**Issue by exebetche** [vuetifyjs/vuetify#17612] opened 2023-06-14 18:28 UTC
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Firefox 114.0
**OS:** Ubuntu undefined

### Steps to reproduce
- Import a locale from 'date-fns/locale'
- instanciate date-io/date-fns with it

### Expected Behavior
Should be able to pick a date on `v-date-picker`

### Actual Behavior
`v-date-picker` component freeze when clicking on a date, then work again after this warning:
`Maximum recursive updates exceeded. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdU9tO3DAQ/ZWRXxbUTUy7VR+iBS1S1S+o+oJ5CMmkG3Acy/YGqlX+vePLQggCFp58mTPnnJmxr/Zs2KFrm3/5rWUFazvdGwd7qAyWDv/EGIzQmL6DRcIuhErAnwT6pexlXWqHJqE2Nd1mbc/D2ij7hG+Mz0i4Q5jLviol8sYQUCh8CNCqV9ZBUoTz545O9kIBuC12WJDbGptyJ93veF7I9u/WLWBcepBXIYzfApTRaAEK72fmT/YQfRQHl+NpIADg/K28iPJi46lQbMkutc7JN7Vz7bDTkuAXHrKu2wEqWVp7LlidNRIf4HZnfT1ZhYq4BAtAgg5Z6I5uqzs0F2v+/BzYONHRbs0nIqQuW3VnaZq9IgOhbMEqawUr4CqSC7Z1TtuC86pWhKxRtoPJFTqudMdTyzerfJV/JxHrDleZLG9sHsg80zVVTIJxtFlX6plqDATl1H7hX5s/v2NhQzBudsq1HWZ13029TK5ztF12Y/p7i4ZIBEvzCjLe8BFS71VLEi+oOekNaDKDqkbjx3ZcRbO0qeYs9HplLz7XMeLznM23/OuP/Ix/IZkJ9wcoJ0yrs9eZnr72JzgfcxN7+Gb+zY1LFlpHjy+u1/8BxaKehw==)

**Comment by exebetche** [comment] 2023-06-14 18:42
Same problem with `v-locale-provider` as shown in the example of the doc.

**Comment by KaelWD** [comment] 2023-06-15 11:51
There's a circular dependency between `model` and `inputModel` here: https://github.com/vuetifyjs/vuetify/blob/1673b96480ad557bad742087fc21e89a1544361a/packages/vuetify/src/labs/VDatePicker/VDatePicker.tsx#L85-L102

**Comment by Kroeg93** [comment] 2023-07-06 12:44
Any news here? I got the same problem.

**Comment by yujinlin0224** [comment] 2023-07-22 16:31
Any updates?

**Comment by KaelWD** [comment] 2023-08-09 09:24
Duplicate of #17867

**Closed by KaelWD** 2023-08-09 09:24 UTC
Labels: T: bug, C: VDatePicker, labs
