### ISSUE TITLE
[Bug Report] v-autocomplete field with solo prop in a dark toolbar has white background and white text

### ISSUE THREAD

**Issue by darylteo** [vuetifyjs/vuetify#4462] opened 2018-07-03 05:27 UTC
### Versions and Environment
**Vuetify:** 1.1.1
**Last working version:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.5

### Steps to reproduce
See codepen. The old CSS overrides for the toolbar are no longer present I guess?

### Expected Behavior
prepend-inner-icon (and I assume append-icon) should be dark.

### Actual Behavior
they are white.

### Reproduction Link
[https://codepen.io/anon/pen/ERMpVP?&editors=101](https://codepen.io/anon/pen/ERMpVP?&editors=101)

### Other comments
Regression of https://github.com/vuetifyjs/vuetify/issues/2705

**Comment by KaelWD** [comment] 2018-07-03 05:39
Duplicate of #4453

**Closed by KaelWD** 2018-07-03 05:39 UTC
