### ISSUE TITLE
[Bug Report] Autocomplete on clear sets variable to undefined and not null. This causes some unexpected behaviour when using nested objects as the value

### ISSUE THREAD

**Issue by JamesDeegan** [vuetifyjs/vuetify#6751] opened 2019-03-18 13:50 UTC
### Versions and Environment
**Vuetify:** 2.0.0-alpha.8
**Vue:** 2.6.9
**Browsers:** Chrome 73.0.3683.75
**OS:** Windows 10

### Steps to reproduce
Select a supplier
delete the supplier
notice how that completely deletes the supplier key: value from the form object

### Expected Behavior
I expect the value to be set to null. so, supplier: null. Not for the key value pair to be entirely deleted

### Actual Behavior
because autocomplete sets the bound value to undefined and not null, its deleting the key and value pair bound to it.

### Reproduction Link
<a href="https://codepen.io/anon/pen/bZKjXW" target="_blank">https://codepen.io/anon/pen/bZKjXW</a>

**Comment by KaelWD** [comment] 2019-03-19 05:58
Duplicate of #5722, #4144

> key value pair to be entirely deleted

It isn't, JSON just doesn't have `undefined`: https://codepen.io/anon/pen/mojqmg?editors=1010

**Closed by KaelWD** 2019-03-19 05:58 UTC
