### ISSUE TITLE
[Bug Report][3.0.0-beta.11] v-autocomplete - selection box reopening in incorrect position

### ISSUE THREAD

**Issue by diegocardoso93** [vuetifyjs/vuetify#15799] opened 2022-09-21 12:13 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Vue Version:** 3.2.39
**Browsers:** Chrome 105.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
click inside input autocomplete,
click to lose focus,
click inside input autocomplete

### Expected Behavior
re-render the selection box below the input

### Actual Behavior
selection box reopening over the input

### Reproduction Link
<a href="https://codepen.io/fyrewell/pen/MWGvKbZ" target="_blank">https://codepen.io/fyrewell/pen/MWGvKbZ</a>

**Comment by KaelWD** [comment] 2022-09-21 12:22
Duplicate of #15587

**Closed by KaelWD** 2022-09-21 12:22 UTC
Labels: S: triage
