### ISSUE TITLE
[Feature Request] Add option to disable auto theme injection

### ISSUE THREAD

**Issue by strychnide** [vuetifyjs/vuetify#3806] opened 2018-04-08 00:18 UTC
### Problem to solve
Fine grained control over which assets are bundled and how (basic example: using an external css file to reduce index.html size)

### Proposed solution
An option to disable the auto-injection in the config options while registering the plugin. Maybe a webpack integration in the future.

**Comment by KaelWD** [comment] 2018-04-08 04:09
Duplicate of #3349

**Closed by KaelWD** 2018-04-08 04:09 UTC
