### ISSUE TITLE
[Bug Report][3.1.12] v-chip close click causes unpredictable data loss

### ISSUE THREAD

**Issue by mtermoul** [vuetifyjs/vuetify#17040] opened 2023-03-30 19:46 UTC
### Environment
**Vuetify Version:** 3.1.12
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Open the codepen
- Click on x on the first chip
- Notice that two chips got removed from the list. The first one and the next.

### Expected Behavior
Only the chip that was clicked should be removed

### Actual Behavior
Two chips got removed, the one that was clicked and the one next to it.

### Reproduction Link
[https://codepen.io/mtermoul/pen/BaOewYL](https://codepen.io/mtermoul/pen/BaOewYL)

### Other comments
To compare the issue with regular span component. Try to click on the first yellow span and you will see that only the first one got removed.

**Comment by gitemad** [comment] 2023-03-31 13:17
Why do you assign onItemClose method to onClick of closable v-chip component?
Just write this and everything will be okay:
@click:close.stop.prevent

**Comment by mtermoul** [comment] 2023-03-31 15:14
I have added the `@click:close.stop.prevent` to the `v-chip` `click:close` event, however that didn't stop the event from firing! As a result of that I ended up having two chips removed not just one.
Try to open the codePen and hit the close button on the first chip and you'll see.

**Comment by KaelWD** [comment] 2023-04-03 12:48
Duplicate of #16364

**Closed by KaelWD** 2023-04-03 12:48 UTC
Labels: S: triage
