### ISSUE TITLE
[Bug Report] VCalendar: wrong date for touchmove:time 

### ISSUE THREAD

**Issue by chumakov-azoft** [vuetifyjs/vuetify#13174] opened 2021-02-27 07:34 UTC
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.190
**OS:** Windows 10

### Steps to reproduce
* start a touch operation in calendar times
* continue the touch operation to another day

### Expected Behavior
The value of `event.date` of the event should return the actual day (same as `mousemove` event)

### Actual Behavior
The value of `event.date` of the event returns the same day

### Reproduction Link
<a href="https://codepen.io/Dendroid/pen/abBqxbJ" target="_blank">https://codepen.io/Dendroid/pen/abBqxbJ</a>

**Comment by johnleider** [comment] 2021-07-16 00:15
Duplicate of #12366 

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-07-16 00:15 UTC
Labels: C: VCalendar, S: triage

**Comment by yuwu9145** [comment] 2021-11-01 00:06
@KaelWD As per discussion in pull request #14280, this issue should be re-opened and I will make a dedicated separat pull request for it

**Comment by yuwu9145** [comment] 2021-11-26 12:22
Just a reminder this issue is still broken
