### ISSUE TITLE
[Bug Report] v-autocomplete v-slot:selection is not working when change items props

### ISSUE THREAD

**Issue by enkhtulga** [vuetifyjs/vuetify#7309] opened 2019-05-28 06:09 UTC
### Versions and Environment
**Vuetify:** 1.3.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
I have two kind of items. categoryList and restaurantList. Initial items is categoryList. When i am trying to type any character on input field, ITEMS will change restaurantList. So, when i select one of restaurant from restaurantList, when it will not update s-slot:selection. How can i solve it?

### Expected Behavior
Update data on s-slot:selection template

### Actual Behavior
Do not update data on s-slot:selection template

### Reproduction Link
<a href="https://codepen.io/enkhtulga/pen/wbxKVv" target="_blank">https://codepen.io/enkhtulga/pen/wbxKVv</a>

**Comment by KaelWD** [comment] 2019-05-28 08:34
Duplicate of #4000

**Closed by KaelWD** 2019-05-28 08:34 UTC
Labels: triage
