### ISSUE TITLE
[Bug Report] Blur event for v-combobox adds the current filter text as a new item

### ISSUE THREAD

**Issue by GarrettGeorge** [vuetifyjs/vuetify#6697] opened 2019-03-07 21:32 UTC
### Versions and Environment
**Vuetify:** 1.5.4
**Vue:** 2.5.2
**Browsers:** Chrome 72.0.3626.119
**OS:** Windows 7

### Steps to reproduce
1. Click in Location field
2. Type `B`
3. Click the `B3` item

### Expected Behavior
Expect the `B3` item to be added without anything else.

### Actual Behavior
`B3` item gets added along with a new item `B` from the typed filter text.

### Reproduction Link
<a href="https://codepen.io/anon/pen/GemKrX" target="_blank">https://codepen.io/anon/pen/GemKrX</a>

### Other comments
This is specifically a problem when `menu-props="{ closeOnContentClick: true }"`. Some UX rationale comes from issue !5926 but I don't think this UX rationale applies when `closeOnContentClick` is `true`

**Comment by GarrettGeorge** [comment] 2019-03-08 15:30
I'd be interested in making a PR for this, mostly looking for discussion and direction about how we can approach this.

**Comment by ram33** [comment] 2019-03-26 09:28
@GarrettGeorge As a workaround you can try closing menu manually instead of using menu prop by setting component's `isMenuActive = false`

Codepen: https://codepen.io/ram33/pen/NJmwJX

**Comment by zjgreen** [comment] 2019-06-08 21:53
This also happens with `menu-props="{ closeOnContentClick: false }"`, so I don't think that's related.

Similarly, if I click away it auto-submits the entry even if I have not clicked the item (or submit the form).

**Comment by all4manu** [comment] 2019-10-10 05:28
The current version 2.1.2 also seems to be affected. You can reproduce it by going to the vuetify documentation (https://vuetifyjs.com/en/components/combobox -> examples -> multiple combobox).

1. Click into one of the three fields
2. Enter letter `d` into the field
3. Hit the down cursor to select `Design`
4. Hit enter key

=> `Design` and `d` will be added to the selected items.

**Closed** 2020-01-20 23:16 UTC
Labels: C: VCombobox, S: has PR, T: bug

**Comment by thomas-romuald** [comment] 2020-03-13 13:52
@johnleider I've just installed the latest version of vuetify 2.2.17. But I still have the issue as described here. On the documentation the bug is reproductible as well (https://vuetifyjs.com/en/components/combobox -> examples -> multiple combobox).

**Comment by inad9300** [comment] 2020-09-04 12:22
@johnleider why was this issue closed? The bug is still present in Vuetify's docs as of v2.3.10, as described in previous comments.

**Comment by inad9300** [comment] 2020-11-16 12:00
...

**Comment by ananthachetan** [comment] 2020-12-31 15:07
The issue is present in v2.4.0 as well.

**Comment by AirDur** [comment] 2021-02-16 11:09
Bug stills present on v2.4.4

**Comment by johnleider** [comment] 2021-02-16 17:08
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
