### ISSUE TITLE
[Bug Report][3.3.3] VSelect's option placement is wrongly calculated for the first time

### ISSUE THREAD

**Issue by JCodePeace** [vuetifyjs/vuetify#17589] opened 2023-06-12 13:16 UTC
### Environment
**Vuetify Version:** 3.3.3
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Create a parent element which doesn't have padding or margin with limited width
2. Place v-select inside

### Expected Behavior
To have the correct placement of v-select options for the first time

### Actual Behavior
The placement of v-select options is wrong for the first time and works on further clicks

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkE1qwzAQha8iBCWb2Cqk3Zi0pOeIsnDsKVEryUIzcQjBd+9IdsA4m0B38/u+ebO/ya8Qyv4MspJbAhdsTfCpvRDbvqhDyCEnrekF0tXCh5YX09KpEu+vL1pO/TyOYKEhURnWQZ7b38iQhUqsCJBWw0FLoe6CihVHjrqDtmp2AKfYRBNIINB5bI8FDuVaGhe6SIWrQ/mDnefzb0lNTw3UshK5kmrsL+VanogCVko1ree1FqzpY+mBlA9O7XhMxbMn46BoO7fblJvyjQ9FmpdLQFccY3dBiCyi5XqGIfN9fQI1TWbCZiRMpcLWR0yIB2nFvB5iEcG3ECE+62ixNne1aD04S/RB+4H/bY3/xcWrG8xv3t+P/JflLJaUDgk4rGW+k8l5QR7+AH3z5KI=)

**Comment by KaelWD** [comment] 2023-06-13 07:01
Duplicate of #17126

**Closed by KaelWD** 2023-06-13 07:01 UTC
Labels: S: triage
