### ISSUE TITLE
[Bug Report] Sparkline labels are black with dark theme enabled

### ISSUE THREAD

**Issue by Wakeful-Cloud** [vuetifyjs/vuetify#8557] opened 2019-08-15 18:37 UTC
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
Create a Sparkline with labels and enable the dark theme.

### Expected Behavior
The labels should be white/a lighter color.

### Actual Behavior
The labels are black.

### Reproduction Link
<a href="https://codepen.io/Wakeful-Cloud/pen/rNBeKoP" target="_blank">https://codepen.io/Wakeful-Cloud/pen/rNBeKoP</a>

### Other comments
You can turn the theme on and off with a switch in the pen (Near the bottom).

**Comment by johnleider** [comment] 2020-01-14 01:49
Merged fix is being reverted.

**Comment by lioneaglesolutions** [comment] 2023-05-04 01:48
This issue is being closed due to inactivity and your reproduction no longer works.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).

**Closed by lioneaglesolutions** 2023-05-04 01:48 UTC
Labels: T: bug, help wanted, C: VSparkline
