### ISSUE TITLE
[Feature Request] Allow Select / Autocomplete to show Preselected Object even if not in list of items

### ISSUE THREAD

**Issue by SimplyUnnamed** [vuetifyjs/vuetify#12487] opened 2020-10-23 02:41 UTC
### Problem to solve
Fills a niche where an item was previously selected, but may not be available later. 

At the moment, in order to get around this the following has to be done:
Check to see if the set value is in the list, and if it is not, Add it to the list (possibly with a disabled prop, so as to avoid being able to select it again.

Note: is is understood that his can be handled with Combobox, but combobox also allows a user to enter custom items

Example: 

https://codepen.io/lgullestrup/pen/dyXOxgb

Entering and Editing a course are done using the same component for reusability. A trainer can be set via and autocomplete field fed by a list of active trainers.

When entering a course, a trainer is selected. A month  later a user edits the course, but the trainer who facilitated the training is no longer active and presented in the list, and the autocomplete field is blank.

### Proposed solution
If the bound value or object for the select is set programmatically, render it, regardless of if it is found the in the provided list or not.

**Comment by KaelWD** [comment] 2020-10-23 02:44
Duplicate of #4000

**Closed by KaelWD** 2020-10-23 02:44 UTC
