### ISSUE TITLE
[Feature Request] Navigation Drawer Mini to Full on Mouseover

### ISSUE THREAD

**Issue by srkinyon** [vuetifyjs/vuetify#4002] opened 2018-05-07 17:07 UTC
### Problem to solve
Keep the navigation drawer visible at all times with a smaller profile than having it fully open yet shows all the relevant menu items instead of completely hiding them.  This also means the user isn't required to click anything for the full list to appear as in clicking the menu button.

### Proposed solution
I'm looking to have the navigation drawer be a fixed 'mini-variant' to 'full open' on mouseover then back to 'mini-variant' on mouseout.  It would ideally work in a clipped manner for the label section that appears on mouseover, however, that is optional. Here's a example of this using another framework: https://codepen.io/JFarrow/pen/fFrpg.

**Comment by KaelWD** [comment] 2018-05-07 17:49
Duplicate of #3940

**Closed by KaelWD** 2018-05-07 17:49 UTC
