### ISSUE TITLE
[Feature Request]: Treeview - Is that possible when select parent node only get parent value, not all children value

### ISSUE THREAD

**Issue by waynecz** [vuetifyjs/vuetify#9088] opened 2019-09-25 01:12 UTC
### Problem to solve
I have a countries & divisions select requirement which uses `v-treeview` implement, it's an awesome component, but I met a little bit confusion abt it:

assume the items data looks like:
```js
const items = {
  id: 'AU',
  name: 'Australia',
  children: [{
    id: 'AU-VIC',
    name: 'Victoria',
  }...]
}
```

For example: The goal is when I select Australia, I only want to get `['AU']` as a result, not `['AU-VIC', 'AU-TSM'...]`, I know there's an independent type selection, but it lost parent-child relationship at the same time

### Proposed solution
Add a select-type like `leaf-grouped`?

**Comment by nekosaur** [comment] 2019-09-26 09:54
From what you described I thought you'd want to use `independent` mode but you say it does not fit your use case?

Could you perhaps illustrate what you need with a codepen?

**Comment by Feofilakt** [comment] 2019-09-30 06:09
I can explain what he wants cause now I'm trying to use v-treeview too. So, you can go to https://wwwendt.de/tech/fancytree/demo/sample-select.html and click "Select all" in the last example:
![image](https://user-images.githubusercontent.com/5498396/65852903-e728ae00-e381-11e9-8c2b-e01204b66485.png)
There are "Selected root keys", that are exactly the thing.

By the way, that JQuery library is a greate treeview plugin, you can look at it as a standard when you working on v-treeview. And also, it would be good to always check the existent solutions functionality _before_ implementing your own component and releasing it into production.

**Comment by waynecz** [comment] 2019-10-02 06:03
@nekosaur   Thank you for the reply!

  If I use `independent `, When I select Australia, I could still select Victoria and will get ['AU', 'AU-VIC'] as a result which actually these two values are complicit (AU means the whole country, it already contains AU-VIC)

**Comment by nekosaur** [comment] 2019-10-02 14:39
Hmm. 

- So then what _would_ you expect to happen if you first clicked on AU and then on AU-VIC? What would the selection be?
- And conversely, what would you expect to happen if you only clicked on AU-VIC?

You will need to explain in more detail exactly how you expect this new mode to work.

**Comment by waynecz** [comment] 2019-10-04 01:37
@nekosaur 
- > So then what would you expect to happen if you first clicked on AU and then on AU-VIC? What would the selection be?
 When I clicked AU, the value should be ['AU'], then I clicked AU-VIC, the value should be ['AU-VIC'], as u can see, 'AU' been removed due to I choose its leaf

  The requirement is that when I clicked AU, the value I get should not be ['AU-VIC' ...and other leafs], it should just ['AU'] in this mode

**Comment by nekosaur** [comment] 2019-10-05 08:48
Ah, I see. I guess that's a valid mode.

**Comment by rsaleri** [comment] 2019-10-17 10:19
@waynecz 

As a workaround i used this:
```html
<template>
                <v-treeview
                        v-if="!loading"
                        dense
                        v-model="tree"
                        :items="items"
                        :search="search"
                        :item-children="children"
                        selection-type="all" <---- this does the trick
                        open-on-click
                        selectable
                        transition
                        return-object
                        hoverable
                        item-key="name"
                />
</template>
```

and in the script:
```javascript
  export default {
    name: 'FilteredTree',
    props: {
      items: {
        type: Array,
        default: () => []
      },
      children: {
        type: String,
        default: 'children'
      },
      icon: {
        type: String,
        default: 'mdi-help-rhombus'
      }
    },
    data() {
      return {
        tree: [],
      }
    },
    computed: {
      treeParents: function() { // this will return the nested array parent->children->children
        let tree = [...this.tree];
        // Filter tree with only parents of selections
        tree = tree.filter(elem => {
          for (let i = 0; i < tree.length; i++) {
            // Skip current element
            if (tree[i].id === elem.id) continue;

            // Check only elements with childrens
            if (tree[i][this.children]) {
              let item = this.findTreeItem([tree[i]], elem.id);
              // If current element is a children of another element, exclude from result
              if (item) {
                return false;
              }
            }
          }
          return true;
        });
        return tree;
      }
    },
    methods: {
      findTreeItem(items, id) {
        if (!items) {
          return;
        }

        for (const item of items) {
          // Test current object
          if (item.id === id) {
            return item;
          }

          // Test children recursively
          const child = this.findTreeItem(item[this.children], id);
          if (child) {
            return child;
          }
        }
      }
    }
  }
```

you can use treeParent.map(parent => parent.propertyyouwant) to retrieve only the parents.
Work like a charm, selecting the parent and selecting alla of its children give the same result.

**Comment by wbuc** [comment] 2020-03-29 19:48
I am faced with the same issue described here. The parent node needs to be included in the selection and not just the children. Selection-type 'all' is working, however I get a console error "Invalid prop".

Thanks,

**Comment by derekbekoe** [comment] 2020-03-31 19:26
`selection-type="all"` gave me the output I was looking for as well.

@wbuc The "Invalid prop" console errors will not appear if `NODE_ENV=production`.
If you want to use `NODE_ENV=development`, e.g. for local development, this is a workaround/hack to prevent those error messages if they are a nuisance.

```
Vue.config.warnHandler = function (msg, vm, trace) {
  if (msg !== 'Invalid prop: custom validator check failed for prop "selectionType".') {
    const hasConsole = typeof console !== 'undefined';
    if (hasConsole && !Vue.config.silent) {
      console.error(`[Vue warn]: ${msg}${trace}`);
    }
  }
}
```

It works by overriding the Vue warnHandler, https://vuejs.org/v2/api/#warnHandler.
https://github.com/vuejs/vue/blob/dev/src/core/util/debug.js#L18-L26

Note: **This is a workaround/hack that could break in the future** say if vuetifyjs changes the name of the prop or Vue changes the prop validation error message.

**Comment by wbuc** [comment] 2020-03-31 21:55
Thanks for the great info @derekbekoe ! I'll give this a go for now.

**Comment by rsaleri** [comment] 2020-04-02 10:19
@derekbekoe , just for info ``selection-type="all"`` works only because 'all' is outside of the expected values. It would work with everything outside the expected values, I used 'all' because it would be easier to understand, when reading the code.

It can surely break, since using an unexpected value triggers the "old" 1.5 return value... It would be nice, since the values are already there, if the "all" prop value would became "canon".

**Comment by KaelWD** [comment] 2020-11-10 13:25
Duplicate of #6759

**Closed by KaelWD** 2020-11-10 13:25 UTC
Labels: C: VTreeview, T: feature
