### ISSUE TITLE
[Bug Report][3.1.2] v-file-input cannot input the same file consecutively.

### ISSUE THREAD

**Issue by y-negishi** [vuetifyjs/vuetify#16516] opened 2023-01-25 05:33 UTC
### Environment
**Vuetify Version:** 3.1.2
**Last working version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Add a file
2. Remove files programmatically
3. Add the same file
4. File not inputed (and `update:model-value` not working)

### Expected Behavior
The same file can be input

### Actual Behavior
The same file cannot input

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNp9UctuwjAQ/JWVLwWJxCqlFxQQVT+DcAjJUlz8ku2kqhD/3rUTWh5tb9md2ZnJeH1kL9bmXYtszoqAysoq4LLUAEWXVdamzzSoSuhhSvNOSMyEtm0AAk2DclGyuPQlA37J3AYNq1qK+kAMo1/jV8mWDpXpEHqJdFjwRP65NRJqWXlPd1ZmMzo6QwRKsayaBqp0W3Aar8HkCIPLtg3B6F9YUSLsEXyl8F6p4EaeK6Bw3x3EoW+n4Bet0ehrJ2wAj6GNsFDWuABHyrGDE+ycUfBAdT9Ecm20H34dFpExWm/G5/VQFAGjMSyWcIy+iZt3lWyRgPWm1KcYoTclOzZhvSNFtfm7N5reNV2WA0CvM++14o6SxLlk+xCsn3Peant4y2uj+Iow7lodhMKsMWr1lE/z2TNvhA+X+xy9yrbOfHh05FiyyYV4ELvPvwwGmHQf82kvO6yi5J0UJ/0OXeZQN+jQ/Zv7hnuV/Qa7yx89qdUTdSmFPvibGmufKkzds9OE9dJETv/BNl9dGBTE)

**Comment by floroz** [comment] 2023-01-26 14:18
I can take a look at this.

**Comment by floroz** [comment] 2023-01-26 16:25
I created a [Playground example](https://play.vuetifyjs.com/?preview=false#eNp9UMtuwjAQ/JWVLwWJ2CptLygguPTYH8AcgGwgJX7IdlJVUf696zwqHmp9Ws/szszutmEba3ldIVuwNKCy5T7gSmqpAdKsqKkEemmd5EWJSaFtFaBOlMmwXEoWQS8ZlPtD999kGUSMIDGORpWPSh3Qgck71kPTdEUPe2jbVIxmYyV1Km4Cpf7oChvAY6gsOeoTGQZyJ7ZQ1rgADTjMZ3A0imJiBi3kzih4ov2eosTRaB+GCMvYm75Tvd2tJtvd9LZhjLb8VZtMprBc9dO83pcV8hL1KZxpMhV9uBWbsT5LovaWf3qj6bBN3EsOBAVeQIdEjJLFv2TnEKxfCFFpezlx8hRr4oSrdCgUJplR6xc+569vdB4frnGOXiUHZ748OnKUbHYlHor8+y+DgSbdZz7vZQcoSj5ICdKv0SUOdYYO3b+573pvst9xD/mjZyt1S7csC33xd2c8+u6E211saWesl6bmbg+2+wFr5vUX)

Using the `model-value` / `v-model` prop you can programmatically pass your reactive variable holding the files, but you should let the `v-file-input` mutate or reset its value.

Do you have a specific use case where you need to manually mutate the reactive value and having the `v-file-input` react to that?

I can reproduce the bug, but I cannot tell whether that's a usage that is/should supported, probably someone from the team could best address this

**Comment by y-negishi** [comment] 2023-01-27 01:17
Thank you for confirming.

The use case I am facing is a screen for just uploading icons. When the user selects a file, the image cropping screen is immediately displayed and uploaded after cropping is completed. However, there is no transition of the screen after uploading. In that case, it is not necessary to leave the image in the input, so I would like to reset it programmatically.

It is not a use case that necessarily requires using v-file-input, but it works well in v2.

**Comment by floroz** [comment] 2023-01-27 11:52
> Thank you for confirming.
> 
> The use case I am facing is a screen for just uploading icons. When the user selects a file, the image cropping screen is immediately displayed and uploaded after cropping is completed. However, there is no transition of the screen after uploading. In that case, it is not necessary to leave the image in the input, so I would like to reset it programmatically.
> 
> It is not a use case that necessarily requires using v-file-input, but it works well in v2.

Got it.

I believe I found the issue and opened a PR (https://github.com/vuetifyjs/vuetify/pull/16539) but might require some input from the core team to make sure the fix is genuine and not a "hacky" workaround :)

**Comment by KaelWD** [comment] 2023-01-31 12:27
Duplicate of #16167

**Closed by KaelWD** 2023-01-31 12:27 UTC
Labels: S: triage
