### ISSUE TITLE
[Feature Request] specify columns that can be grouped in Datatable of Vuetify2

### ISSUE THREAD

**Issue by gregluo2019** [vuetifyjs/vuetify#11468] opened 2020-05-22 22:58 UTC
### Problem to solve
When I use "show-group-by", it makes all columns can be grouped. How can I specify columns that can be grouped because I just want some columns can be grouped. How can I change "group" under each column to an icon? I don't know how to use slot to implement these requirements. Please kindly help me and give me an example.

Many thanks!

### Proposed solution
slot

**Comment by jacekkarczmarczyk** [comment] 2020-06-11 11:11
resolved in #11361 (2.3)

Duplicate of https://github.com/vuetifyjs/vuetify/issues/10889

**Closed by jacekkarczmarczyk** 2020-06-11 11:11 UTC
