### ISSUE TITLE
Picker component error in mac 

### ISSUE THREAD

**Issue by shihanjun19** [vuetifyjs/vuetify#2231] opened 2017-10-18 13:28 UTC
chrome version : 61.0.3163.100
macOS : 10.13

![image](https://user-images.githubusercontent.com/10006241/31721153-315537fe-b44b-11e7-896b-713609e8c674.png)

**Comment by jacekkarczmarczyk** [comment] 2017-10-18 13:36
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2022

**Closed by jacekkarczmarczyk** 2017-10-18 13:36 UTC
