### ISSUE TITLE
[Bug Report] v-tabs do not show initial selected underline if used inside of a v-dialog

### ISSUE THREAD

**Issue by ktruong19** [vuetifyjs/vuetify#6789] opened 2019-03-21 17:44 UTC
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.9
**Browsers:** Chrome 72.0.3626.121
**OS:** Windows 10

### Steps to reproduce
Press open dialog
Notice that the first tab "ROUTE" is bold, but there is no selection underline
Select "ROUTE2", notice selection underline appears
Select "ROUTE", now there is a selection underline

### Expected Behavior
Press open dialog
"ROUTE" is bold and shows a selection underline

### Actual Behavior
Press open dialog
Notice that the first tab "ROUTE" is bold, but there is no blue selection underline

### Reproduction Link
<a href="https://codepen.io/snipah19/pen/JzmMym" target="_blank">https://codepen.io/snipah19/pen/JzmMym</a>

### Other comments
Does not work in 1.5.6 either

![image](https://user-images.githubusercontent.com/5474396/54773259-6e70ba00-4bc6-11e9-8fe7-479902615cbb.png)

**Comment by KaelWD** [comment] 2019-03-22 00:53
Duplicate of #1978

**Closed by KaelWD** 2019-03-22 00:53 UTC
