### ISSUE TITLE
[Feature Request] Be able to extend Vuetify classes into scss classes

### ISSUE THREAD

**Issue by Stefanosapk** [vuetifyjs/vuetify#13138] opened 2021-02-19 22:17 UTC
### Problem to solve
If we can use vuetify's classes into the scss classes, the vue template will be much cleaner.

For example, right now we can use only in the template the vuetify's classes:
```
<template>
  <div class="customClass mr-2 pa-5 rounded">Hello Vuetify</div>
</template>

<style lang="scss">
customClass{
*/ css here /*
}
</style>
```

### Proposed solution
Why not be able do this?
```
<template>
  <div class="customClass">Hello Vuetify</div>
</template>

<style lang="scss">
customClass{
*/ css here /*
@extend  .mr-2;
@extend .pa-5;
@extend .rounded;
}
```

**Comment by KaelWD** [comment] 2021-02-20 08:30
Duplicate of #12646

**Closed by KaelWD** 2021-02-20 08:30 UTC
Labels: triage
