### ISSUE TITLE
Distorted text avatars in a <v-list>

### ISSUE THREAD

**Issue by beatgrabe** [vuetifyjs/vuetify#1805] opened 2017-09-19 06:33 UTC
### Steps to reproduce
Trying to have `<v-avatar>` or `<v-list-tile-avatar>` as text avatars in a `<v-list>` leads into distorted avatars.

### Versions

Vue@2.4.4, Vuetify@0.15.7, Windows 7, Chrome  55.0.2883.75 m

### What is expected ?

Support for nicely rendered text avatars in a `<v-list>`

### What is actually happening ?

Having distorted rendered text avatars in a `<v-list>`

### Reproduction Link

https://codepen.io/anon/pen/oGbyoG?editors=1010

I put text and img avatar in this list together to contrast the issue with a working `<img>` example. So please be aware of that I do not want to have both in a `<v-list>`. This is only for demonstration purpose...

**Comment by johnleider** [comment] 2017-09-19 17:20
The distortion is caused by the required area that the avatar must take up and the space that should be around it. Can you show me an example of what you are expecting it to look like?

**Comment by beatgrabe** [comment] 2017-09-20 05:51
I would like to have the opportunity the use them all (icon avatar, text avatar and image avatar) in a list in the same size/shape like e.g. android contact app is doing:

![](http://cdn04.androidauthority.net/wp-content/uploads/2015/12/Contacts-3.png)

**Comment by KaelWD** [comment] 2017-09-20 14:24
https://codepen.io/anon/pen/LzNvzK?editors=1010

**Comment by jacekkarczmarczyk** [comment] 2017-09-20 14:56
The problem seems to be in the `class="red"` in `v-avatar`
https://codepen.io/anon/pen/oGxRzL?editors=1000

**Comment by KaelWD** [comment] 2017-09-20 15:14
Ah

```css
.list__tile .avatar {
  min-width: 56px;
}
```

overrides the inline `height`

**Comment by beatgrabe** [comment] 2017-09-20 18:45
As I already written in the last abstract above, I do not want to have them both in. This is only made for demonstration purpose...

**Comment by beatgrabe** [comment] 2017-09-21 06:09
Ok, I see there is already a solution by tinkering around with css classes. But it would be great to have a understandable and documented way to get a avatar list with text icons. And as KaelWD already said, there are still some artifacts messing up css while using avatars in a list afaik...

**Comment by demkani** [comment] 2017-10-12 15:33
Hey,

was also stumbling over this behaviour. I'm just a few days into Vuetify (just awesome) so I'm not that sure about my solution.
Wouldn't it solve it if you put a `> ` infront of `.avatar` here?

https://github.com/vuetifyjs/vuetify/blob/9b6b0fd321c98d4e7001d13099ed3f762253857a/src/stylus/components/_lists.styl#L87

Seems to work for me so far :)

![avatar_list](https://user-images.githubusercontent.com/1410361/31504691-52b3c136-af73-11e7-9244-fc38358175c4.png)

**Comment by johnleider** [comment] 2017-11-18 01:52
The markup will change very slightly. You cannot use `v-avatar`, you must use `v-list-tile-avatar`. Added colorable to `v-avatar` and `v-list-tile-avatar`, use this instead of class.

This codepen will work after released:
https://codepen.io/johnjleider/pen/oopgoL?editors=1010

And this is what it looks like:
![image.png](https://images.zenhubusercontent.com/5a01a49b8a75884b90865dbf/2be67f76-c979-457e-9c2d-901430d05cac)

**Comment by kabukki** [comment] 2017-11-24 14:58
The codepen doesn't work for me, there is no color on the letter avatar and it is not centered

**Comment by jacekkarczmarczyk** [comment] 2017-11-24 15:13
It will be fixed in 1.0

**Closed** 2017-12-11 11:21 UTC
Labels: enhancement
