### ISSUE TITLE
[Bug Report] v-dialog does not close on escape keydown the first time it shows up

### ISSUE THREAD

**Issue by mtermoul** [vuetifyjs/vuetify#11282] opened 2020-04-30 16:53 UTC
<img width="543" alt="Screen Shot 2020-04-30 at 12 53 31 PM" src="https://user-images.githubusercontent.com/8376035/80737520-a3e21980-8ae1-11ea-85f7-8412f1892ccc.png">
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.122
**OS:** Mac OS 10.14.6

### Steps to reproduce
- Click on the button to open a v-dialog
- Hit the escape key on your keyboard (The dialog would not close, even if you hit escape many times)
- Click anywhere on the dialog to activate it
- Now press the escape key. The dialog will close now.
- Repeat the steps above and you will see that the dialog will close if hit the escape now. So the issue only happens when the dialog show for the first time.

### Expected Behavior
The dialog should close if I press the escape key. I don't need to click on it first on order for the escape to work.

### Actual Behavior
The dialog does not close when I hit the escape key.

### Reproduction Link
<a href="https://codepen.io/mtermoul/pen/rNOzgee?editors=1010" target="_blank">https://codepen.io/mtermoul/pen/rNOzgee?editors=1010</a>

### Other comments
This issue is related to accessibility and people relying on keyboard only. So it's very important that the dialog should respond to the escape key without having to click on it.

**Comment by jacekkarczmarczyk** [comment] 2020-05-02 10:15
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8220, doesn't seem to be resolved though
Same workaround - use `eager` prop on `v-dialog`

**Comment by jacekkarczmarczyk** [comment] 2020-05-02 10:33
https://github.com/vuetifyjs/vuetify/issues/11257

**Closed by jacekkarczmarczyk** 2020-05-02 10:33 UTC
Labels: C: VDialog, duplicate
