### ISSUE TITLE
[Bug Report] Solo text field in a toolbar doesnt reduce the height

### ISSUE THREAD

**Issue by Geowan** [vuetifyjs/vuetify#8537] opened 2019-08-14 22:54 UTC
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
By reducing the height of the text field as per the documentation on the height property of a text field doesnt work.

### Expected Behavior
The solo text field should reduce its height to the set height and center on the toolbar

### Actual Behavior
The toolbar doesnt reduce its height even despite the change

### Reproduction Link
<a href="https://codepen.io/geowan/pen/JjPXKLE" target="_blank">https://codepen.io/geowan/pen/JjPXKLE</a>

### Other comments
I have also tried adding css classes but this still doesnt resolve the issue

**Comment by KaelWD** [comment] 2019-08-15 02:22
Duplicate of #5216

**Closed by KaelWD** 2019-08-15 02:22 UTC
Labels: triage
