### ISSUE TITLE
[Bug Report] v-autocomplete don't show items if I add hide-no-data property

### ISSUE THREAD

**Issue by MaraniMatias** [vuetifyjs/vuetify#10625] opened 2020-02-19 19:26 UTC
### Environment
**Vuetify Version:** 2.2.13
**Last working version:** 2.2.13
**Vue Version:** 2.6.11
**Browsers:** Firefox 73.0, Google Chrome, Mozilla Firefox
**OS:** Linux

### Steps to reproduce
Add hide-no-data on v-autocomplete and then it don't show items 
if you delete hide-no-data the items is be show

### Expected Behavior
Show items

### Actual Behavior
Don't show items

### Reproduction Link
<a href="https://codepen.io/MaraniMatias/pen/mdJrPMJ?editable=true&editors=101" target="_blank">https://codepen.io/MaraniMatias/pen/mdJrPMJ?editable=true&editors=101</a>

**Comment by MajesticPotatoe** [comment] 2020-02-19 19:35
duplicate of #10606
will be fixed in next patch, meanwhile you can use `eager` prop

**Closed by MajesticPotatoe** 2020-02-19 19:35 UTC
Labels: triage
