### ISSUE TITLE
[Bug Report] Sparkline does not show labels when type is "bar"

### ISSUE THREAD

**Issue by jgfoster** [vuetifyjs/vuetify#7763] opened 2019-07-06 01:27 UTC
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
Create Sparkline element with type="trend" and the labels show fine. Change it to "bar" and the values are displayed instead of the labels.

### Expected Behavior
Show labels.

### Actual Behavior
Show values.

### Reproduction Link
<a href="https://codepen.io/jgfoster/pen/bPxLQJ" target="_blank">https://codepen.io/jgfoster/pen/bPxLQJ</a>

### Other comments
I don't see that Sparkline works on Codepen.

**Comment by jacekkarczmarczyk** [comment] 2019-07-06 14:48
Your reproduction doesn't work at all even with "trend" type, please provide a correct one

**Comment by nekosaur** [comment] 2019-07-06 17:44
Also a duplicate of https://github.com/vuetifyjs/vuetify/issues/7584. It has been fixed in 2.0

**Closed by nekosaur** 2019-07-06 17:44 UTC
Labels: S: needs reproduction, triage
