### ISSUE TITLE
[Bug Report] Click outside of dialog wrong behaivour 

### ISSUE THREAD

**Issue by yariksav** [vuetifyjs/vuetify#7451] opened 2019-06-10 16:23 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.13.0

### Steps to reproduce
If start click at dialog window, drag cursor click outside of dialog  and release the button - then dialog will close.

### Expected Behavior
Dialog should not be closed when click starts on it.

### Actual Behavior
It's important when you need to select some text in dialog and occasionally mouse goes outside dialog.
I suppose in this code
https://github.com/vuetifyjs/vuetify/blob/42226659ae1cbb9eb026f71890a948cc87f296eb/packages/vuetify/src/directives/click-outside.ts#L68
we need change event type from click to mousedown

### Reproduction Link
<a href="https://codepen.io/ducdebreme/pen/wroMaVe" target="_blank">https://codepen.io/ducdebreme/pen/wroMaVe</a>

**Comment by jacekkarczmarczyk** [comment] 2019-06-12 06:00
Duplicate of #6969

**Closed by jacekkarczmarczyk** 2019-06-12 06:00 UTC
Labels: triage
