### ISSUE TITLE
[Bug Report] Images are getting flipped on scroll in mobile

### ISSUE THREAD

**Issue by vaishali-ghayal** [vuetifyjs/vuetify#2840] opened 2017-12-20 12:01 UTC
### Versions and Environment
**Vuetify:** 0.15.3
**Vue:** 2.4.2
**Browsers:** Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer, Opera, Other
**OS:** iOS, Android

### Steps to reproduce
1- Open the below link (please refer Reproduction link) on mobile.
2- Scroll the page up and down
3- Observe images in carousel 

### Expected Behavior
The Carousel should only move when either the arrows are pressed or a finger is slide across it or the timer moves it automatically.

### Actual Behavior
If we scroll or touch anywhere on screen, then also images are getting flipped in Carousel.

### Comments
Please check screen cast https://www.screencast.com/t/yCSYUjVt

### Reproduction Link
[https://codepen.io/vaishali-ghayal/details/xpOwmq](https://codepen.io/vaishali-ghayal/details/xpOwmq)

**Comment by KaelWD** [comment] 2017-12-20 12:42
Duplicate of #2125 

You are using a very old version of vuetify, that bug was fixed over a month ago.

**Closed by KaelWD** 2017-12-20 12:42 UTC
