### ISSUE TITLE
[Feature Request] V-Skelton

### ISSUE THREAD

**Issue by RahulVaishnav25** [vuetifyjs/vuetify#16307] opened 2022-12-21 10:08 UTC
### Problem to solve
When will the V-Skelton component will be available in vuetify 3. 

### Proposed solution
-

**Comment by KaelWD** [comment] 2022-12-21 10:10
Duplicate of #13504

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com).

**Closed by KaelWD** 2022-12-21 10:10 UTC
Labels: S: triage
