### ISSUE TITLE
[Bug Report] v-form reloads the page when user press enter while editing v-text-field

### ISSUE THREAD

**Issue by KevinNTH** [vuetifyjs/vuetify#4302] opened 2018-06-14 13:40 UTC
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.79
**OS:** Linux x86_64

### Steps to reproduce
Add a v-form, with one v-text-field.
Press enter while editing the input.
Page is reloaded

### Expected Behavior
Trigger submit event?

### Actual Behavior
Page is reloaded

### Reproduction Link
[https://codepen.io/KevinNTH/pen/bKroLd](https://codepen.io/KevinNTH/pen/bKroLd)

### Other comments
Happens only with one v-text-field in the v-form

**Comment by jacekkarczmarczyk** [comment] 2018-06-14 13:44
Duplicate of #3032

**Closed by jacekkarczmarczyk** 2018-06-14 13:44 UTC

**Comment by MystK** [comment] 2018-10-02 05:16
@jacekkarczmarczyk I've been browsing through the closed issues and I see it is expected behavior. How do I prevent it?

**Comment by dakshshah96** [comment] 2018-11-27 13:18
@MystK Your solution worked for me.

@jacekkarczmarczyk Even with a button of `type=submit` and a `@submit` handler on the `v-form` element, my page was reloading on clicking enter. Doing `onSubmit="return false;"` feels kind of hacky. Any other solutions? 😃

**Comment by MystK** [comment] 2018-11-27 21:15
@dakshshah96

I believe it’s expected behavior because this is how vanilla HTML works. I agree with you that the solution is hacky, but the problem is with the spec, not vue.

**Comment by jofftiquez** [comment] 2019-04-25 07:27
@dakshshah96 if you want to use the `type="submit"` you should use `@submit.prevent="submit` on your `form` or `v-form`.

**Comment by flourigh** [comment] 2019-05-10 14:25
> @dakshshah96 if you want to use the `type="submit"` you should use `@submit.prevent="submit` on your `form` or `v-form`.

put only @submit.prevent
