### ISSUE TITLE
[Bug Report] Missing sass styles for new text-h1,-h2 classes

### ISSUE THREAD

**Issue by Moedav** [vuetifyjs/vuetify#11870] opened 2020-07-16 10:29 UTC
### Environment
**Vuetify Version:** 2.3.4
**Last working version:** 2.2.34
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
1. Install vuetify 2.3
2. a. vue add vuetify-preset-reply    or
 b. add own variables.scss under /src/sass
 -> and change sass variable for $heading-font-family to "Work Sans"
3. add for example following code:
```
<div class="text-h1">Hallo World</div>
```

### Expected Behavior
Hallo World should have set font family to Work Sans. For example:
```
.v-application .text-h1 {
    font-size: 6rem !important;
    font-weight: 300;
    line-height: 6rem;
    letter-spacing: -0.015625em !important;
    font-family: "Work Sans", sans-serif !important;
}
```

### Actual Behavior
But font-family is still Roboto:
```
.v-application .text-h1 {
    font-size: 6rem !important;
    font-weight: 300;
    line-height: 6rem;
    letter-spacing: -0.015625em !important;
    font-family: "Roboto", sans-serif !important;
}
```

### Reproduction Link
<a href="https://codepen.io/moedav/pen/rNxqjyg" target="_blank">https://codepen.io/moedav/pen/rNxqjyg</a>

### Other comments
I found out that this problem occurs in vuetify 2.3.0 because the typographie is deprecated and changed to text-h1, -h2, etc.
And for there is no sass style for these new classes. Because if i use the old classes it still works.

I already postet it at: https://github.com/vuetifyjs/vue-cli-plugins/issues/191
But I think it might be better here.

**Comment by 2oh8** [comment] 2020-07-18 15:56
Can confirm, on 2.3.4 `.text-h1` will work while just `.h1` yields no result.

**Comment by KaelWD** [comment] 2020-07-22 06:12
Duplicate of https://github.com/vuetifyjs/vue-cli-plugins/issues/191

**Closed by KaelWD** 2020-07-22 06:12 UTC
Labels: triage

**Comment by 2oh8** [comment] 2020-08-03 16:32
> Can confirm, on 2.3.4 `.text-h1` will work while just `.h1` yields no result.

How is this off topic?
