### ISSUE TITLE
[Bug Report] v-select on-change event triggering twice

### ISSUE THREAD

**Issue by ksankumar** [vuetifyjs/vuetify#3463] opened 2018-03-04 14:44 UTC
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10, Android, iOS, Mac OSX

### Steps to reproduce
Select any item and watch the event console

### Expected Behavior
on-change event trigger should one time when it was changed or need any callback if item choose from v-select

### Actual Behavior
on-change event triggering twice, because it's emitting the native change event too

### Reproduction Link
[https://codepen.io/ksankumar/pen/qxwQpZ](https://codepen.io/ksankumar/pen/qxwQpZ)

**Comment by Banandrew** [comment] 2018-03-21 14:40
The reproduction link in the OP has got some errors, [here’s another example](https://codepen.io/banandrew/pen/MQLQwX) showcasing the issue: type something to retreive the items from a simulated endpoint, select one, and see the console output or the `:loading` prop switching to `true` again, because the endpoint gets hit when an option is selected. I used the debouncing in the example, hopefully, it’s okay.

I think it happens, because the component expects a developer to watch for an input that’s being used as a search field, and then the same input is updated once an option is selected, which results in an endpoint getting hit again with the data that was just selected. For the record, using the `chips` prop eliminates the behavior. Perhaps, two inputs can be used instead, one for the `search-input` prop, and another to represent the selected data?

**Comment by KaelWD** [comment] 2018-04-07 01:03
See also #3457

`change` isn't currently hooked up very well, use `input` instead to detect changes that would affect v-model.

**Comment by johnleider** [comment] 2018-05-14 23:47
This has been resolved in v1.1

**Closed by johnleider** 2018-05-14 23:47 UTC
Labels: T: bug
