### ISSUE TITLE
[Documentation] Official site doesn`t work. Can`t get any information.

### ISSUE THREAD

**Issue by kisa777zaika** [vuetifyjs/vuetify#14879] opened 2022-03-26 10:43 UTC
### Environment

**Browsers:** Chrome 99.0.4844.74
**OS:** Mac OS 10.15.7

### Steps to reproduce
Homepage works, but other pages I see only white screen and console is full of errors

### Expected Behavior
All pages work correctly

### Actual Behavior
Homepage works, but other pages I see only white screen

### Reproduction Link
<a href="https://vuetifyjs.com/en/introduction/why-vuetify/" target="_blank">https://vuetifyjs.com/en/introduction/why-vuetify/</a>

**Comment by KaelWD** [comment] 2022-03-26 15:10
Duplicate of #14871

**Closed by KaelWD** 2022-03-26 15:10 UTC
Labels: S: triage
