### ISSUE TITLE
[Bug Report] A La Carte import error: Carousel Item not registered

### ISSUE THREAD

**Issue by vonWolfehaus** [vuetifyjs/vuetify#3318] opened 2018-02-18 01:59 UTC
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.9
**Browsers:** Chrome 64.0.3282.167
**OS:** Windows 10

### Steps to reproduce
Import `VCarousel` in any component: `import { VCarousel } from 'vuetify'`

### Expected Behavior
Properly-imported component, including its dependencies (carousel-item in this case, for the carousel component), so that there are no errors.

### Actual Behavior
Vue console warning: `Unknown custom element: <v-carousel-item>`

### Reproduction Link
[https://github.com/vonWolfehaus/a-la-carte](https://github.com/vonWolfehaus/a-la-carte)

**Comment by KaelWD** [comment] 2018-02-18 07:27
Duplicate of #3035

**Closed by KaelWD** 2018-02-18 07:27 UTC
