### ISSUE TITLE
[Bug Report][3.5.9] Typography helpers not overriding style

### ISSUE THREAD

**Issue by francoisauclair911** [vuetifyjs/vuetify#19430] opened 2024-03-18 21:26 UTC
### Environment
**Vuetify Version:** 3.5.9
**Last working version:** 2.7.2
**Vue Version:** 3.4.21
**Browsers:** Chrome 122.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Apply any typography helper like : `text-h6`
Apply a text transform helper like : `text-uppercase`
Apply a breakpoint typography  helper like `text-sm-h3` 
Apply a breakpoint text transform  helper like `text-sm-uppercase` 

### Expected Behavior
`text-{breakpoint}-uppercase` should take precedence over any typography helper and uppercase the text

### Actual Behavior
Text typography helpers take precedence over transform helpers and do not uppercase the text

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUMtKxEAQ/JVyLlFwE3yCkhW86Rd4MB5mk14NZB5MdxZh2X93JjGD6ME9dXV3dXVRr3vFoa0evS93I6l7VQsZP2ihh8YC9W6lvZ/g1LTOiu4the9RHPoFAe2gmdeNEvqU1cctpjp6T6HVTHPLJm8izMtGLTJZGXiGNuDIcUwdxGFDyBcdNqPAOslOqsVocvWPmUYd/eevfl39TiJN5qDq6keAseU29F7AJON83hvvgmCPQFscsA3OoIjZF4keM3SWBYbfsU6M0+KJhsHhxYWhOynO0oNZMoqpw7m6Kq/LywuVwE15p96+AINtk2U=)

### Other comments
Related issues
https://github.com/vuetifyjs/vuetify/issues/15616
https://github.com/vuetifyjs/vuetify/discussions/17354
https://github.com/vuetifyjs/vuetify/issues/18845
https://github.com/vuetifyjs/vuetify/discussions/17354

**Comment by KaelWD** [comment] 2024-04-13 05:48
Duplicate of #18845

**Closed by KaelWD** 2024-04-13 05:48 UTC
Labels: S: triage
