### ISSUE TITLE
[Feature Request] Set caret position on v-text-field

### ISSUE THREAD

**Issue by EvandroLucas** [vuetifyjs/vuetify#14867] opened 2022-03-24 14:58 UTC
### Problem to solve
Every time I change the variable associated to the `v-text-field` outside of the component, the caret position is set to the last character. When implementing a wrapper for the component that does some changes to the text itself as the user types, this can muddle any editing the user does mid-string, given that the caret will move itself to the end of the string every time the user hits a key. 

### Proposed solution
I propose that both an event and a method be created. The event would emit the value of the current caret when it changes, and the method will allow us to set the caret position to any position on the string.

**Comment by EvandroLucas** [comment] 2022-03-24 18:49
To give it a little bit of detail: I'm implementing a wrapper that masks the input as it is typed by the user. The problem is that it requires updating the value passed to the `:value` prop, and therefore the caret moves to the end of the string when this happens. If I could somehow just prevent the caret from moving, it would already be enough.

**Comment by scscgit** [comment] 2022-04-17 10:41
Linking related issue:
* https://github.com/vuetifyjs/vuetify/issues/14935

**Comment by KaelWD** [comment] 2023-02-23 07:22
Duplicate of #14935 (just prevent the caret from moving)

Otherwise `inputRef.value.selectionStart` or [`useEventListener(document, 'selectionchange', ...`](https://vueuse.org/core/useEventListener/)

**Closed by KaelWD** 2023-02-23 07:22 UTC
Labels: S: triage
