### ISSUE TITLE
[Bug Report][3.2.2] VDataTable is not properly imported while importing VDataTable component in Vuetify global instance.

### ISSUE THREAD

**Issue by DeepKumbhare85** [vuetifyjs/vuetify#17272] opened 2023-05-03 05:46 UTC
### Environment
**Vuetify Version:** 3.2.2
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1)Clone the repo and start project by running command `yarn install` and `yarn dev`.
2) Go to the DataTable.vue file in components folder 
3) You can check that VDataTable component looks like a property not like a component and it also doesn't provide any suggestions for props and types.however, Datatable works completely fine in project.
![image](https://user-images.githubusercontent.com/92006556/235840474-949b12b0-ab86-4139-b88a-7cec19865298.png)

4)but when we use local import of Datatable in component file,then it properly gives suggestion for props and types  

### Expected Behavior
VDataTable should also suggest props and types like other component

### Actual Behavior
VDatatable doen't provide any suggestion for props and types.

### Reproduction Link
[https://github.com/DeepKumbhare85/vuetify-datatable-test](https://github.com/DeepKumbhare85/vuetify-datatable-test)

**Comment by KaelWD** [comment] 2023-05-03 06:37
Duplicate of #17269

**Closed by KaelWD** 2023-05-03 06:37 UTC
Labels: S: triage
