### ISSUE TITLE
[Bug Report] [VTabs] Switching out an array results in Tabs becoming unusable

### ISSUE THREAD

**Issue by Bbansjkl** [vuetifyjs/vuetify#6897] opened 2019-04-02 12:05 UTC
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Windows 7

### Steps to reproduce
1) Assign an array of objects to a VTab component, letting v-tab and v-tab-item loop over it via v-for  
2) Replace the array with another, which can contain some of the original or different objects
3) Select different tabs to display

### Expected Behavior
The Tab always switches to the one being clicked on, with the slider, content and text marking reflecting this.

### Actual Behavior
After exchanging the array, the clicked tab doesn't always get selected.  
It seems that VTab remembers the position elements used to have and tries to select that position.  
For example, if the initial array contains the objects "Orange" and "Apple" in that order, after removing "Orange" and pushing "Banana", clicking on the first tab (with the displayed name "Apple") results in VTab selecting the item at index 1, which used to be "Apple", but is now "Banana". Selecting the tab with the displayed name "Banana" results in VTab trying to select a tab with the index 2, which doesn't exist, so the tab at index 0 is selected instead. The slider doesn't change position at all.

### Reproduction Link
<a href="https://codepen.io/anon/pen/ZZGLNE" target="_blank">https://codepen.io/anon/pen/ZZGLNE</a>

### Other comments
Couldn't reproduce this is Vuetify 2.0.0-alpha.11, mostly because I couldn't get a VTabs with the tabs representing objects to work within 15 minutes.

**Comment by KaelWD** [comment] 2019-04-02 12:13
Duplicate of #6278

**Closed by KaelWD** 2019-04-02 12:13 UTC

**Comment by Bbansjkl** [comment] 2019-04-02 12:29
Ah, thanks. No chance of this being fixed in 1.5.x then?

I tried this in 2.0 by modifying one of the example pens in the 2.0 documentation, like I did with this one for 1.5.7, but had some issues with everything displaying correctly.  
Good to see that a straight conversion works, too.
