### ISSUE TITLE
[Feature Request] DEPRECATION WARNING - Dart Sass

### ISSUE THREAD

**Issue by gabesztx** [vuetifyjs/vuetify#13713] opened 2021-05-27 11:53 UTC
### Problem to solve
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### Proposed solution
https://sass-lang.com/d/slash-div

**Comment by KaelWD** [comment] 2021-05-27 11:54
Duplicate of #13694

**Closed by KaelWD** 2021-05-27 11:54 UTC
Labels: triage
