### ISSUE TITLE
[Bug Report][3.4.8] Autocomplete clear template

### ISSUE THREAD

**Issue by qxygene** [vuetifyjs/vuetify#18919] opened 2023-12-22 02:42 UTC
### Environment
**Vuetify Version:** 3.4.8
**Vue Version:** 3.4.0-beta.4
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
not clearing

### Expected Behavior
not clearing

### Actual Behavior
not clearing

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUkFOwzAQ/MrKHApSk0DpAUVpBe9oe3AcFwyOHdmbSFXVv7N2UnBUDpwSz4zt2fHszsw7Ubx1XT70kpWsQtl2mqPc7g1ANWS86+JvXAhrkCsj3QSNih6tsLRLorzCAEPW2kbqzZ61/n3PfolS0RWe8PhNGc3ruAGlxxQXVltHeOdUy90ppRppvMITkeTgaB3yWstUEC7JUKGWpDG8vSUHrvtAqialPlQjs0bStDp4DTOmtJPYO5PZ+lMKTJxqyV20MEE/OVFS12ThLsoSKsZYo0kRSpA7xQ2GwTWFnl7/r9HjhPRi4QkalQlt/Q3/KrQSX+MjwQZMr/Vcsq2KaC0dpJh1ZITmNbg2huB5ZaIwNmp2Ci29cKpD8BTsWDjVdjQUnCnrI1zg6GwLCyrpIshDKYxHGG2T4v4hhWO1JmI3ejlDeP0SFqFdT4slqKaEJ7gs/6BXE72a6AMdXhWjQ/LGLkv2nK/zx6ymguRrNi5f2OEbz/X7gw==)

**Comment by qxygene** [comment] 2024-01-09 21:51
any fix for this issue?

**Comment by KaelWD** [comment] 2024-01-31 08:14
Duplicate of #18032

**Closed by KaelWD** 2024-01-31 08:14 UTC
Labels: S: needs reproduction, S: triage
