### ISSUE TITLE
[Bug Report] Menu created by Combobox is wrongly positioned when is overflowing to top and is filtered or showing no-data slot

### ISSUE THREAD

**Issue by empresarrollo** [vuetifyjs/vuetify#5319] opened 2018-10-12 17:55 UTC
### Versions and Environment
**Vuetify:** 1.2.8
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 8.1

### Steps to reproduce
Go to the pen: 

In the combobox field (bottom left) write a "V", you will see the list filtered only showing "vue" and "vuetify", but wrongly positioned (it stays in the top position that the menu had). 
[Screenshot](https://imgur.com/TcTWpnS)

The autocomplete (bottom right) works OK, if you type "V", it shows the filtered list next to the field. [Screenshot](https://imgur.com/XL8Xx3F)

The same happens if you write some word that is not in the items array, the no-data slot gets wrongly positioned for the combobox

### Expected Behavior
It should position the menu of the combobox the same as the autocomplete, always next to the field

### Actual Behavior
the menu of the combobox wrongly positioned, always on the top position instead of next to the field

### Reproduction Link
[https://codepen.io/anon/pen/rqzYOQ](https://codepen.io/anon/pen/rqzYOQ)

**Comment by jacekkarczmarczyk** [comment] 2018-10-15 06:49
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5082

**Closed by jacekkarczmarczyk** 2018-10-15 06:49 UTC
