### ISSUE TITLE
Fixed button not working properly (get a position:relative on click)

### ISSUE THREAD

**Issue by ThunderAnkh** [vuetifyjs/vuetify#1111] opened 2017-07-24 09:24 UTC
### Steps to reproduce
Creating a button with the fixed attribute and clicking it. 

### Versions
Version 0.14 
I've tried with v 0.13.1 it's working properly so it's the new version which breaks it

### What is expected ?
That the button stays where it is and not get a relative position out of the blue

### What is actually happening ?
Once clicked the button will get a position:relative and will then move and need to be clicked again to activate the action

### Reproduction Link
https://codepen.io/anon/pen/RZwgxw

**Comment by johnleider** [comment] 2017-07-25 01:48
Duplicate of #1057

**Closed by johnleider** 2017-07-25 01:48 UTC
Labels: duplicate
