### ISSUE TITLE
[Bug Report] When use element.select() in v-btn click event,can't select element correctly.

### ISSUE THREAD

**Issue by shadowdreamer** [vuetifyjs/vuetify#12267] opened 2020-09-22 06:52 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 10

### Steps to reproduce
as the codepen link ,when click this copy button,the active element changed to close button ,and then failed to copy,i don't know why

### Expected Behavior
select textarea success,and do copy

### Actual Behavior
focus some v-btn components uncorrectly

### Reproduction Link
<a href="https://codepen.io/curedovahkiin/pen/JjXeQPX?editors=1010" target="_blank">https://codepen.io/curedovahkiin/pen/JjXeQPX?editors=1010</a>

**Comment by KaelWD** [comment] 2020-09-24 05:35
Duplicate of #6892

**Closed by KaelWD** 2020-09-24 05:35 UTC
Labels: triage
