### ISSUE TITLE
[Bug Report][2.5.8] v-menu does not animate in leave transition

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#14122] opened 2021-09-03 16:46 UTC
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 92.0.4515.107
**OS:** Linux x86_64

### Steps to reproduce
Click on "Toggle Visibility" button. <v-menu> activator should fade, but it disappears instantly without animation. The same time show animation works as expected.

### Expected Behavior
Show and hide should work with animation

### Actual Behavior
Hide animation does not work as it should - the <v-menu> activator disappears instantly after <transition> starts leave transition.

### Reproduction Link
<a href="https://codepen.io/kasheftin/pen/rNwLgRp" target="_blank">https://codepen.io/kasheftin/pen/rNwLgRp</a>

### Other comments
There's <transition><v-menu>...</v-menu></transition> construction. For some reason the v-menu content immediately disappears after starting a leave transition. Show transition works as expected.

**Comment by KaelWD** [comment] 2021-09-06 15:56
Duplicate of #7422

**Closed by KaelWD** 2021-09-06 15:56 UTC
Labels: C: VMenu, S: triage
