### ISSUE TITLE
[Bug Report] Enter in VSelect can trigger a "Cannot read property 'click' of undefined" error on large lists

### ISSUE THREAD

**Issue by johnmarian** [vuetifyjs/vuetify#7677] opened 2019-06-26 18:05 UTC
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
1. Use a VSelect with a large `items` list
2. Begin typing an item that has never been rendered in the scroll view
  * Example, use 'U' in the reproduction link
  * *NOTE:* once you have scrolled past an item in the selection list, the issue does not seem to occur - if you scroll through the entire list before making a typed selection, there is no error
3. Hit enter

### Expected Behavior
The item should select without error

### Actual Behavior
```
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'click' of undefined
    at VueComponent.changeListIndex (vuetify.js?ce5b:9822)
    at VueComponent.onKeyDown (vuetify.js?ce5b:12612)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at HTMLInputElement.invoker (vue.runtime.esm.js?2b0e:2179)
    at HTMLInputElement.original._wrapper (vue.runtime.esm.js?2b0e:6911)
```

### Reproduction Link
<a href="https://codepen.io/johnmarian/pen/PrJRZx" target="_blank">https://codepen.io/johnmarian/pen/PrJRZx</a>

### Other comments
This seems to be related to closed issue #3649

**Comment by StefanFeederle** [comment] 2019-06-27 05:59
We also receive this error in our production environment. The data for v-autocomplete contains about 2500 items in this case.

**Comment by jacekkarczmarczyk** [comment] 2019-07-07 09:58
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7440

**Closed by jacekkarczmarczyk** 2019-07-07 09:58 UTC
Labels: triage
