### ISSUE TITLE
[Bug Report] [vMain] Padding doesn't update on window resize

### ISSUE THREAD

**Issue by Tofandel** [vuetifyjs/vuetify#13595] opened 2021-05-03 12:48 UTC
### Environment
**Vuetify Version:** 2.4.11
**Vue Version:** 2.6.12
**Browsers:** Chrome 90.0.4430.85
**OS:** Linux x86_64

### Steps to reproduce
Resize the window so that the footer icons break, reload the page (the button doesn't work unless in debug view in codepen), now resize the window again so that the footer doesn't break anymore.

Notice the white background is visible

### Expected Behavior
The v-main padding to be updated when the window is resized

### Actual Behavior
The v-main padding doesn't change when the window is resized

### Reproduction Link
<a href="https://codepen.io/tofandel-the-typescripter/pen/GRrVdod" target="_blank">https://codepen.io/tofandel-the-typescripter/pen/GRrVdod</a>

### Other comments
This can cause problems for users for example when they rotate their device's viewport

This applies to v-menu and v-footer using the vApplicable  mixin

**Comment by Tofandel** [comment] 2021-05-03 12:53
![Peek 2021-05-03 14-52](https://user-images.githubusercontent.com/6115458/116878183-46fecf00-ac1f-11eb-8e81-849c85711c23.gif)

**Comment by KaelWD** [comment] 2021-05-03 12:53
Duplicate of #11121

**Closed by KaelWD** 2021-05-03 12:53 UTC
Labels: triage

**Comment by linpan** [comment] 2021-05-31 03:01
I have some issues,
