### ISSUE TITLE
[Feature Request] Translate DataTable header "group" text (show-group-by text)

### ISSUE THREAD

**Issue by MarceloLuis1997** [vuetifyjs/vuetify#12496] opened 2020-10-23 14:51 UTC
### Problem to solve
Be able to translate/customize the "group" text on Data Table headers when show-group-by is active.

### Proposed solution
Create a slot to customize the "group" text on DataTable headers where show-group-by is active, being able to change the text or add icons.

**Comment by jacekkarczmarczyk** [comment] 2020-10-24 16:15
duplicate of https://github.com/vuetifyjs/vuetify/issues/12130

**Closed by jacekkarczmarczyk** 2020-10-24 16:15 UTC
