### ISSUE TITLE
[Bug Report] v-select items un-selectable and incorrectly displayed if items contain object with property called header

### ISSUE THREAD

**Issue by nialldorgan** [vuetifyjs/vuetify#11619] opened 2020-06-12 16:11 UTC
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.5.17
**Browsers:** Chrome 83.0.4103.97
**OS:** Windows 10

### Steps to reproduce
use objects in select items array with a property named header

### Expected Behavior
property specified in item-text displayed and select item selectable

### Actual Behavior
select not selectable and item-text showing string in header property

### Reproduction Link
<a href="https://codepen.io/nialldorgan/pen/yLeOGWa" target="_blank">https://codepen.io/nialldorgan/pen/yLeOGWa</a>

**Comment by burgstjo** [comment] 2020-07-28 16:32
I observe a similar behavior when the object of the value contains an attribute named 'text': look at this pen: https://codepen.io/burgstjo/pen/BajerWM

**Comment by johnleider** [comment] 2020-12-08 19:29
Duplicate of #4148

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-08 19:29 UTC
Labels: triage
