### ISSUE TITLE
[Bug Report][2.6.9] v-app-bar-title component incorrectly computes width of itself

### ISSUE THREAD

**Issue by Emo-ti-on** [vuetifyjs/vuetify#15659] opened 2022-08-21 02:28 UTC
### Environment
**Vuetify Version:** 2.6.9
**Vue Version:** 2.6.14
**Browsers:** Edge 104.0.1293.54
**OS:** Windows 10

### Steps to reproduce
Watch code on codepen

### Expected Behavior
Full text 

### Actual Behavior
Cutted text

### Reproduction Link
<a href="https://codepen.io/EmO-Ti-On/pen/eYMxXMQ" target="_blank">https://codepen.io/EmO-Ti-On/pen/eYMxXMQ</a>

### Other comments
Text cut itself if base width was x.5 - x.9 (where "x" is any number)

**Comment by lioneaglesolutions** [comment] 2023-05-03 02:15
This may have been by design however closing this issue as in V3 the title doesn't get cut off

https://play.vuetifyjs.com/#eNqNUk1v2zAM/SuCLrtEFtAF2BBkQfcbdqx7UCym0aYvSLTToMh/HyXPrZp2aH2yHsn3+EjePfGfMXbTCHzDtwguWoWw6z1j20kMKunyy9hgVc4/eu4ehRox9HyGnXoUJ6PxSKH1+vsM1+pab9U5jPjvXREVo9irtCBEHGxIVB2TcSqdF+LyafDZ4JmCQ3BRDfgSfKYk0qVpNolsA25iggheNymtsvBqEmYIfreV74ANr2ym0cAvRWjQwu5XcMBs8A+McEY4qzjDo0J2Cv4Lsj2wYUQWDodWcy5/xX1thVLfcbJHz0qzZR3aCB0wiwkSmkHZnldflPI/Kwv03Ei7HpqDeVBoghc6qRMkJpdtUkGzzvIs10GPhp2vuDX+T+5+5+DpoJ5KKq0v555v2N3M1PMjYswbKQftKVODNVPqPKD00Uk6RTSH8+3X7qa7kdpkXCDS3+eukhWm+95fSNC4GBIKp+KV6hyoyhUpGDGV9wct3FKaTKNH44DG62ov629zMw3eQXZin8IpQyKWnq8andLxJ7Q+sksSb6gl6dHCRaLjgATps5auyl7Zuoq9sVbkL2XilxWf62j2tWl+/xf0QmDg

**Closed by lioneaglesolutions** 2023-05-03 02:15 UTC
Labels: S: triage
