### ISSUE TITLE
[Bug Report][2.6.7] Wrong menu "top" position. "Top" property doesn't update after menu height changes

### ISSUE THREAD

**Issue by cherrybar** [vuetifyjs/vuetify#15524] opened 2022-07-27 08:25 UTC
### Environment
**Vuetify Version:** 2.6.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
V-Autocomplete items is an array of elements that looks like this:
```
[ 
 {
    text: "item",
    id: 0
  },
  {
    text: "item",
    id: 1
  },
...
]
```
1. Type text "item" to autocomplete input
2. Wait for search results
3. Append some another symbol to autocomplete input

### Expected Behavior
"No data available" displayed next to input

### Actual Behavior
"No data available" displayed too far away from input

### Reproduction Link
<a href="https://codesandbox.io/s/modest-satoshi-9bz3h1?file=/src/App.vue" target="_blank">https://codesandbox.io/s/modest-satoshi-9bz3h1?file=/src/App.vue</a>

### Other comments
It looks like this issue reproduced in case when server side search used. In provided example, if you remove setTimeout then everything will works as expected

**Comment by KaelWD** [comment] 2022-07-27 08:27
Duplicate of #10375

**Closed by KaelWD** 2022-07-27 08:27 UTC
Labels: S: triage
