### ISSUE TITLE
[Bug Report] V-Select Keyboard usage

### ISSUE THREAD

**Issue by stefanKuijers** [vuetifyjs/vuetify#12581] opened 2020-11-10 09:06 UTC
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 3.0.2
**Browsers:** Chrome 86.0.4240.183
**OS:** Mac OS 10.15.7

### Steps to reproduce
1) select option 'a' with the mouse. Dropdown option list closes and the option get's selected. Great start.
2) when we hit enter the option list opens again. As expected.
3) when we hit enter again the list closes. As it should.
4) when we hit enter again the option list does not open again. Further enters are ignored. Not as expected.
5) With the focus remaining (and option selected) on the v-select we hit the down array. The selected value switches to the next in the list and we loose focus of the v-select. Not as expected.

### Expected Behavior
4) As long as the v-select has focus I would expect that hitting enter would keep toggeling the visibility of the option list so the user can select a value.

5) This is more of UX question but IMHO; Or the arrow keys should open the option list or they should not do anything at all. Loosing focus of the input element WITHOUT hitting tab or clicking outside of the element is not ok I think.

### Actual Behavior
4) Only toggles (opens and closes) the option list once. Further enters seem ignored.

5) The selected value switches to the next in the list and we loose focus of the v-select.

### Reproduction Link
<a href="https://codepen.io/stefanKuijers/pen/oNLQNgQ" target="_blank">https://codepen.io/stefanKuijers/pen/oNLQNgQ</a>

### Other comments
Again, thank you guys for the great work on Vuetify!
The 'enter' behaviour might be related to: https://github.com/vuetifyjs/vuetify/issues/12567

I still think this deserves a separate issue as the keyboard usage of form element is the goal. Which likely needs to be considered per component regardless of the fact that combobox inherrits some of it features of this component.

**Comment by janKollars** [comment] 2020-12-11 10:37
The issue #12572 is about the up/down-key-interaction on a focused v-select and its focus issue. It also specifies the commit which presumably caused the problem.

**Comment by johnleider** [comment] 2021-01-11 23:09
Duplicate of #12567

**Closed** 2021-01-11 23:09 UTC
Labels: triage
