### ISSUE TITLE
[Feature Request] Allow v-divider to use other tag than hr

### ISSUE THREAD

**Issue by Magiczne** [vuetifyjs/vuetify#10603] opened 2020-02-18 10:50 UTC
### Problem to solve
Right now if we want to have proper semantic HTML list using v-list it can be done like that:
```
<v-list tag="ul">
    <v-list-item tag="li">...</v-list-item>
</v-list>
```
The problem shows up when we want to have divider between elements.

```
<v-list tag="ul">
    <v-list-item tag="li">...</v-list-item>
    <v-divider />
    <v-list-item tag="li">...</v-list-item>
</v-list>
```

This code will render as (simplified), 
```
<ul>
    <li>...</li>
    <hr>
    <li>...</li>
</ul>
```
which is not not correct according to [HTML spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element)

### Proposed solution
Currently i have just inserted this code fragment
```
<li class="v-divider theme--dark" 
     role="separator" 
     aria-orientation="horizontal" 
     tabindex="-1" />
```
into my code.

I think adding **tag** property to v-divider element will make it simple to create fully semantic HTML using vuetify components.

Example proposed solution:
```
<v-divider tag="li" />
```

**Comment by KaelWD** [comment] 2020-02-19 16:00
Duplicate of #5469?

**Comment by johnleider** [comment] 2020-12-16 16:31
Closing this as a duplicate of #5469

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-16 16:31 UTC
Labels: C: Divider, T: feature
