### ISSUE TITLE
[Bug Report][2.5.10] v-calendar mousemove:time hour doesn't change when mouse moves

### ISSUE THREAD

**Issue by mattia-palmieri** [vuetifyjs/vuetify#14378] opened 2021-11-04 11:13 UTC
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Chrome 95.0.4638.69
**OS:** Linux x86_64

### Steps to reproduce
click to add an event, this will be added at the start of the day (12 AM), since mousemove:time hour doesn't change when you move your mouse, it's always set to zero

### Expected Behavior
add event at the hour I click

### Actual Behavior
event is added at 12am

### Reproduction Link
<a href="https://codepen.io/_mattiapalmieri/pen/rNzJBKZ?editors=111" target="_blank">https://codepen.io/_mattiapalmieri/pen/rNzJBKZ?editors=111</a>

### Other comments
the codepen I provided is from the vuetify calendar drag and drop example, without editing, and it seems broken to me.

**Comment by KaelWD** [comment] 2021-11-04 13:56
Duplicate of #14276

**Closed by KaelWD** 2021-11-04 13:56 UTC
Labels: S: triage
