### ISSUE TITLE
RTL Support feature request?

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [vuetifyjs/vuetify#1475] opened 2017-08-26 12:01 UTC
Hello,
i want to HELP by adding RTL Support to this awesome framework.

Wait, what you mean (RTL)?
RTL support means Right-To-Left Support.
its mean that when change the direction of page like this: `<html dir="rtl">`
all the elements get Not beautiful and unorganized well.

  **- What will it allow you to do that you can't do today?**

example when adding `RTL` to `vuetify` docs

![screenshot from 2017-08-26 13-06-56](https://user-images.githubusercontent.com/13006236/29741185-780a4934-8a5f-11e7-8a57-de743c52bdbd.png)

  **- How will it make current work-arounds straightforward?**

as you can see this is big problem since many of developers NOW making (Multi-language) apps, then they need the `RTL feature`.

I can provide RTL Support (i've worked at fiverr long time as freelancer)

the procedure that i follow:

1. i made a clone of this repo.
2. You have separated the `Stylus` from the code. its great. now just RTL each component or anything that need to be RTL'ed.
3. i have started but i want help from you, look at the picture:

![screenshot from 2017-08-26 13-13-59](https://user-images.githubusercontent.com/13006236/29741224-74906d0a-8a60-11e7-8b12-baf82c9aab45.png)

what you can Help ME?
as you can see, the output must be `vuetify.rtl.css` and `vuetify.rtl.min.css` where this file contain only the RTL code.

the RTL code must be compiled from `rtl.styl` like `main.styl`
or
**collect** every stylus file with `.rtl.styl `and compile it to `vuetify.rtl.css`

![screenshot from 2017-08-26 13-19-28](https://user-images.githubusercontent.com/13006236/29741301-aecbe8cc-8a61-11e7-9c2a-d546e26b9897.png)

i made rtl for component that only need it.

**where i stucked!! at config file.**

![screenshot from 2017-08-26 13-24-49](https://user-images.githubusercontent.com/13006236/29741323-f66b835e-8a61-11e7-8682-8ed09ba4f34d.png)

just i want to compile the components or files with example.rtl.styl to be in vuetify.rtl.css.
Note that the order of @import at `main.styl` and `app.styl `is very important.

i can do like this, but its not Good. making the  structure unreadable.

![screenshot from 2017-08-26 13-30-48](https://user-images.githubusercontent.com/13006236/29741364-f70aa064-8a62-11e7-87a8-1317e9142e80.png)

  - What potential bugs and edge cases does it help to avoid?
there is no buge or edges, just i change the direction.

im sorry, if you don't understand me, just ask me. then help then we all get RTL Support.
thank you.

**Comment by johnleider** [comment] 2017-08-27 00:55
Duplicate of #262

**Closed by johnleider** 2017-08-27 00:55 UTC

**Comment by NadhirBoukhenifra** [comment] 2017-08-27 10:28
i read this [#262] (https://github.com/vuetifyjs/vuetify/issues/262),
but i mean that RTL every component need to be RTL'ed.
vuetify not support rtl well. need to fix and seperate the rtl File.

**Comment by NadhirBoukhenifra** [comment] 2017-08-27 10:43
@johnleider look at this, inputs in arabic version, i've changed the direction of the page, 
the issue in the hint text not get to the right when changing page direction, and all components like that need to be fix the rtl.
![screenshot from 2017-08-27 11-40-18](https://user-images.githubusercontent.com/13006236/29749110-d964299e-8b1c-11e7-9809-88abc5c4d824.png)
