### ISSUE TITLE
[Bug Report] v-bottom-sheet is not persistent if hide-overlay is used

### ISSUE THREAD

**Issue by alexandruradovici** [vuetifyjs/vuetify#9242] opened 2019-10-05 17:07 UTC
### Environment
**Vuetify Version:** 2.1.1
**Last working version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Windows, Ubuntu undefined

### Steps to reproduce
Open the bottom sheet and click outside

### Expected Behavior
the bottom sheet should not close

### Actual Behavior
the bottom sheet is closing

### Reproduction Link
<a href="https://codepen.io/msg4alex/pen/QWWWgyx" target="_blank">https://codepen.io/msg4alex/pen/QWWWgyx</a>

**Comment by MajesticPotatoe** [comment] 2019-10-05 19:21
duplicate of #8697

**Closed by MajesticPotatoe** 2019-10-05 19:21 UTC
Labels: triage
