### ISSUE TITLE
[Feature Request] v-btn should have tooltip props

### ISSUE THREAD

**Issue by mr-mad-e** [vuetifyjs/vuetify#11717] opened 2020-06-24 10:13 UTC
### Problem to solve
to easily set a tooltip, just by `<v-button tootip="Button" />`

### Proposed solution
```
<template>
  <div>
    <v-tooltip bottom v-if="tooltip">
      <template v-slot:activator="{ on, attrs }">
        <v-btn v-bind="{...attrs, ...$attrs}" v-on="{...on, ...$listeners}">
          <slot></slot>
        </v-btn>
      </template>
      <span>{{tooltip}}</span>
    </v-tooltip>

    <v-btn v-else v-bind="$attrs" v-on="$listeners">
      <slot></slot>
    </v-btn>
  </div>
</template>


<script>
export default {
  name: "vButton",
  props: {
    tooltip: { type: String, default: "" }
  }
};
</script>
```

**Comment by jacekkarczmarczyk** [comment] 2020-06-24 10:15
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9610

**Closed by jacekkarczmarczyk** 2020-06-24 10:15 UTC
Labels: triage
