### ISSUE TITLE
[Bug Report][3.4.2] data-table not responsive anymore , but it was in vuetify2

### ISSUE THREAD

**Issue by alifaraun** [vuetifyjs/vuetify#18743] opened 2023-11-21 22:30 UTC
### Environment
**Vuetify Version:** 3.4.2
**Last working version:** 2.7.1
**Vue Version:** 3.3.8
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
I upgraded from Vuetify2 to Vuetify3 and noticed that the `v-data-table` component isn't responsive anymore
How can I restore its responsiveness in Vuetify3? 
Any suggestions or code examples would be very helpful

picture of docs vuetify2 , `data-tabel`

[![picture of docs vuetify2][1]][1]

picture of docs vuetify3 , `data-table` not responsive 

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/xl2Od.png
  [2]: https://i.stack.imgur.com/qVqP0.png

### Expected Behavior
data-table responsive on mobile 

### Actual Behavior
data-table not responsive on mobile , just scroll 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdlVFv2jAQx7/KKWMiSBAgwEoRILUP3R42bRrVqgmQahKPWiRO5DhILMp3nx1ik+FESO1DQ+7un9/d+WyvMythXv8hjp1jiq2ZNec4jAPE8XJDAebHno846nG0C7A0AMzeMPIxSxYbq/y1sUoPEVppPxLGUxQ8Rohrp/T1jihIsQigKMRnx3LeryIEdN6vZDBPPEZiDgnmaVxkRMI4Yhwy8KIwTjn2IYc/LAqhLfJvb6iM8SKacCizgwWszylkwAkP8AzaMjN4PsW43QUUkD0VtoQjxsX7AZ/Em8ywDXn3WrmKsUDaBxrxpFNRY+prbSJj6sRfMd3zN7DDJmVQBNRJfzDiYbBbTcpY+uuEvzFiDZqTdJWSbbVzO7lwlb6dHwCyKaoHCcfiu8pTlDyD0URbzqXMwHW1qchRBA3kn7bKLETYwB2WJl3DFfa7hxH9hmrBrgmu5FKCJw1gZWoC/4pOaF8HvXxLQccG9K4eOry/AX1BR/wzpbSGOza5+nOa6xbVmsWq5WjirjB6ZBj/FVvjutyp2WO1Zho7rscOlbYJ+wWxXcQ+p4iJ+bwCa/EFPLkgSvC0oc93t+oNiHd4ItSc5ZE5y2Njlhu6fGuWVzxioegzOtTN1WXL6EZfWlCSP71zmF8I9VeIBGaXzS00Mab5/p3T/CS27TPxzaEaqfWpdNlYW7dY3Fuz/N8RVr2CxEmmLgvb7sBiqdJj4lZhFNaO4zwwhk72cDDoOOJwTOzO1glRbJNKdPV0FJ/MQMiKk3JN4CMMB1vIVaA0O7J0EffayvRrDh9aGclfVVyZgPSXlXTkU/6f989Xn7j0rLxrjZyRM7Xkc+y41vYfxnsoPQ==)

### Other comments
Thanks for your great framework

**Comment by KaelWD** [comment] 2023-11-22 08:21
Duplicate of #16784

**Closed by KaelWD** 2023-11-22 08:21 UTC
Labels: S: triage
