### ISSUE TITLE
[Bug Report] v-window causing unexpected screen scroll

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#6207] opened 2019-01-19 13:59 UTC
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 7

### Steps to reproduce
Run codepen https://codepen.io/anon/pen/aPempb

### Expected Behavior
window-item works normally

### Actual Behavior
screen jumping issue

![2019-01-19_12-58-45](https://user-images.githubusercontent.com/34601970/51427640-85ad1e80-1bfa-11e9-95bd-d229f271c0ec.gif)

### Reproduction Link
<a href="https://codepen.io/anon/pen/aPempb" target="_blank">https://codepen.io/anon/pen/aPempb</a>

### Other comments
Similar bug has been fixed for v-tabs
https://github.com/vuetifyjs/vuetify/issues/5582

**Comment by KaelWD** [comment] 2019-01-29 07:51
Duplicate of #6206

**Closed by KaelWD** 2019-01-29 07:51 UTC
Labels: duplicate
