### ISSUE TITLE
[Documentation] Wireframe examples not working

### ISSUE THREAD

**Issue by bulletmark** [vuetifyjs/vuetify#14054] opened 2021-08-13 23:31 UTC
### Environment

**Browsers:** Chrome 92.0.4515.131
**OS:** Linux x86_64 (current Arch Linux)

### Steps to reproduce
When I click on any of the examples listed on the quoted link here (i.e. the Wireframe examples) all of them showing nothing other than a completely blank page. Happens with the 3 browsers installed on my Arch system, i.e. Chrome, Firefox, and GNOME Web.

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/wireframes/#examples" target="_blank">https://vuetifyjs.com/en/getting-started/wireframes/#examples</a>

**Comment by KaelWD** [comment] 2021-08-14 12:59
Duplicate of #12854

**Closed by KaelWD** 2021-08-14 12:59 UTC
Labels: S: triage

**Comment by bulletmark** [comment] 2021-08-14 23:32
Sorry, can you please explain a little more? I can not see any of those wireframe examples at all, they are all just a blank page (in all browsers as I state above). Are you saying this is just happening for me? This seems a serious issue yet that other bug was raised 8 months ago so must be minor and a different issue.

**Comment by KaelWD** [comment] 2021-08-15 06:59
No it's just regressed recently because of a change I made to the service worker. After that issue was opened we started serving all pages from the cache so it was only a problem if you hadn't visited the main site first.

**Comment by bulletmark** [comment] 2021-08-16 00:43
@KaelWD sorry but I still don't understand what you mean. When I click on that link above I still get nothing more than a blank page for all wireframe examples. How do I fix this?
