### ISSUE TITLE
[Bug Report][3.4.10] v-infinite-scroll executing onLoad even after done('empty') 

### ISSUE THREAD

**Issue by giftimie** [vuetifyjs/vuetify#19042] opened 2024-01-12 22:00 UTC
### Environment
**Vuetify Version:** 3.4.10
**Vue Version:** 3.4.11
**Browsers:** Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
1. Scroll down to execute the three iterations (in a real scenario this could be pages, for example)
2. When the three executions are complete, scroll up and then scroll down
3. The function in onLoad will be executed again, even though we already called the callback with the empty value

### Expected Behavior
The callback is not executed anymore after calling done('empty')

### Actual Behavior
Callback is still being called after done('empty')

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNplUsmO2kAQ/ZUXR5FB2GabbBYQzS2Rcs8BOPSYBlo03U67jWJZ/rEc82Wp9gaeufRSy3v1qmpbeplJps9pGt1y7sXeyvJrKpnlm50CVreQpWn9rD+JVpYJxU1rqo1CHYUSlodZYrSUiM9cnM52vfOWs9nOQ0y+a0bf+nYGrX5qdiCLpGvn9WAE19HjFh61oZCRywog1IH/GdOFHuXCixZ0AEEgB3FDnEiWOdatn7Jw4bcQ+IAF1us1ZvgG/+UUngwvQukK5orCEMP3968AgR/EgvdlWbOjqgZ0U+J71DAd9LAxvWnT3eeq7dT+zrkpnEr3EJx0PgKnm8av/v2lUpp3Va2m3YRe17LKUqaQ2UJywn5hyeVkdK4ONEepTYxUqAsxUFGGWaFVp7D9OWiH0M2fRAwXwFma/Rhopi9pFKlFxm3eFCeuqTYWJQw/osLR6Ct8WjnfhQOEm1lcsxPWLmLkf+dSavzSRh7e+eN7SD39Nmg7D7AIsAzwFOBjgE8BPgf4EuBrgPls/5DVdrPLa1yS13CtWNqIphSWFSrBMVdJbXcrOipx0IqjGqNsetHnTSaNoWWIbkzmPErz7OwWt4mp2SjniLsNKyx7tBrvOki+Tz2KomdjWBG5nlElkquTPcekEFWAEafFHmO9gcBkAMPsKJyPW26gfzglI19fmq6ChsFlxu+lNH6api36EHfRQetQz5Um6lWBt4yeovncax8zb/8frxpSWQ==)

**Comment by giftimie** [comment] 2024-01-12 22:28
My idea of this would be to have this emit called conditionally if the status isn't empty nor error

https://github.com/vuetifyjs/vuetify/blob/520b765c813b68324de75c82e0b78e9fa7376c92/packages/vuetify/src/components/VInfiniteScroll/VInfiniteScroll.tsx#L208

As a workaround we can just manage some kind of flag that keeps track of the scroll status in our own component, so we would have something like:
```js
// pseudocode...
const foundEmptyScroll = ref(false)

async function load({ done }) {
    if (foundEmptyScroll.value) return

    const data = await getEndpointData()
    if (data.length > 0) {
        serverData.value.push(...data)
        done('ok')
    else {
        done('empty')
    }
  }
```

But in my opinion this would make more sense to be managed inside the component

**Comment by JessieVela** [comment] 2024-01-13 21:18
Ran into the same issue. In the mean time I created a flag to stop the calls
`    async load({ done }) {
      if (this.noMorePosts) {
        done('empty');
        return;
      }

      const offset = this.posts.length;
      const limit = 5;
      try {
        const newPosts = await this.getPosts(offset, limit);
        this.posts = this.posts.concat(newPosts);
        if (newPosts.length < limit) {
          this.noMorePosts = true;
          done('empty');
        }
        done('ok');
      } catch (error) {
        done('error');
      }
    },`

**Comment by KaelWD** [comment] 2024-01-14 15:12
Duplicate of #18895

**Closed by KaelWD** 2024-01-14 15:12 UTC
Labels: duplicate, S: triage
