### ISSUE TITLE
[Bug Report] `v-list-item` use the `inactive` with `to` property have error

### ISSUE THREAD

**Issue by MonsterGene** [vuetifyjs/vuetify#11001] opened 2020-04-02 06:17 UTC
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
when component `v-list-item` use `inactive` property , it report error as `The .native modifier for v-on is only valid on components but it was used on <div>.` the reproduction link can see that.

当使用`v-list-item`组件的时候，当组件同时有 `to` 和 `inactive` 属性时，会有报错：`The .native modifier for v-on is only valid on components but it was used on <div>.`

### Expected Behavior
no error

希望不要报错

### Actual Behavior
no error

希望不要报错

### Reproduction Link
<a href="https://codepen.io/monster_gene/pen/LYVvWGp?editable=true&editors=101" target="_blank">https://codepen.io/monster_gene/pen/LYVvWGp?editable=true&editors=101</a>

### Other comments
希望尽快解决这个bug

**Comment by KaelWD** [comment] 2020-04-02 06:28
Duplicate of #9999

**Closed by KaelWD** 2020-04-02 06:28 UTC
Labels: triage
