### ISSUE TITLE
[Feature Request] Stop using codepen for v3 docs

### ISSUE THREAD

**Issue by turbobuilt** [vuetifyjs/vuetify#14488] opened 2021-12-09 16:42 UTC
### Problem to solve
The codepens do not load till you scroll to them, and you have to wait a long time to see the result.  The old documentation system with examples is much better because you don't have to wait for it to load.

### Proposed solution
Go back to the old system of documentation where it shows the result with the ability to click on the code to see it.  It is also easier to see without the code in the way.  The new codepen system seems inferior in every way, except the fact that you can go to codepen to fiddle with it.  But the codepen loading problem is so bad it should be fixed or gotten rid of altogether.

**Comment by KaelWD** [comment] 2021-12-09 16:45
Duplicate of #14242

**Closed by KaelWD** 2021-12-09 16:45 UTC
Labels: S: triage
