### ISSUE TITLE
[Feature Request] Add hold and release events to v-slider

### ISSUE THREAD

**Issue by Hkh12** [vuetifyjs/vuetify#3851] opened 2018-04-14 17:29 UTC
### Problem to solve
probably we'll need events for when the user holds the thumb or releases it;
for example: we have a video that is synced with the slider, and we want it to stop when user starts dragging and continue playing when user releases the thumb.
Our template would look like this:
```vue
<v-slider v-model='duration' @hold='playing = false' @release='playing = true'></v-slider>
```

### Proposed solution
I can submit a PR, if you want. :)

**Comment by nekosaur** [comment] 2018-04-22 07:29
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3116

**Closed by nekosaur** 2018-04-22 07:29 UTC
Labels: duplicate
