### ISSUE TITLE
[Bug Report] Dialog is closed by clicking on Snackbar

### ISSUE THREAD

**Issue by jloewe** [vuetifyjs/vuetify#7310] opened 2019-05-28 06:29 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.108
**OS:** Windows 10

### Steps to reproduce
1.  Open Dialog
2.  Close Snackbar

### Expected Behavior
Only Snackbar closes

### Actual Behavior
Dialog and Snackbar close

### Reproduction Link

![R79d31JbjO](https://user-images.githubusercontent.com/11992962/58455954-38e6d080-8123-11e9-8a6c-c2ac801b35f1.gif)

<a href="https://codepen.io/jloewe/pen/dEjGMw" target="_blank">https://codepen.io/jloewe/pen/dEjGMw (v1.5.14)</a>
<a href="https://codepen.io/jloewe/pen/ZNjQrr" target="_blank">https://codepen.io/jloewe/pen/ZNjQrr (v2.0.0-alpha.20)</a>

**Comment by KaelWD** [comment] 2019-05-28 08:39
Workaround is to add `persistent` to the dialog.

**Comment by jacekkarczmarczyk** [comment] 2019-07-21 11:11
It happens also in normal (not fullscreen) dialogs https://codepen.io/anon/pen/zgGLgK which makes the workaround not so great in this case

**Comment by payammeyer** [comment] 2019-10-10 16:29
Any update on this? The workaround (persistent prop) doesn't work for me either.

**Comment by 185driver** [comment] 2019-10-16 14:52
> Workaround is to add `persistent` to the dialog.

I'm not finding this to be true (#9378). How are you getting this to work?

**Comment by MajesticPotatoe** [comment] 2019-10-16 15:00
@185driver theres another issue at play as well. Conflict between `hide-overlay` and `persistent` #8697
With a `fullscreen` -> `hide-overlay` is assumed thus persistent wont work. on your codepen dialog, if you remove `hide-overlay` it works

**Comment by payammeyer** [comment] 2019-10-16 15:06
@MajesticPotatoe I just tried removing hide-overlay too and it still doesn't work, here are my props:

```html
<v-dialog
        v-model="dialog"
        fullscreen
        persistent
        transition="dialog-bottom-transition"
>
```

**Comment by 185driver** [comment] 2019-10-16 15:08
@MajesticPotatoe Thanks. Indeed, that was noted in the issue I posted. I wasn't aware that `fullscreen` pulled in `hide-overlay` functionality automatically. Good to know, and it makes sense. Actually, to me, `fullscreen` should naturally pull in `persistent` too, then.

**Comment by 185driver** [comment] 2019-10-16 15:10
@payammeyer that's because you're using `fullscreen`, which pulls in `hide-overlay` by default. @MajesticPotatoe was referring to a normal dialog in his comment.

**Comment by payammeyer** [comment] 2019-10-16 15:12
Oh my mistake, thanks for the clarification, either way it’s really not a workaround for me and I would indeed call it a regression.

**Comment by 185driver** [comment] 2019-10-16 15:13
Bless @jacekkarczmarczyk for removing the `p:low` tag. Without a workaround, this issue is a pain. Ha. Thanks for all you guys do!

**Comment by FekihTaoufik** [comment] 2019-11-06 14:10
I'm having the same issue here,
It seems that if the snackbar has been created inside of the dialog or outside (but still in the same component), the persistent prop does fix the problem.
But if you have the snackbar create and managed elsewhere, i'm still getting the closing trigger of any of my dialogs

**Comment by payammeyer** [comment] 2019-11-06 14:19
@FekihTaoufik interesting observation, my snackbars are indeed created elsewhere and triggered to display via an event.

**Comment by FekihTaoufik** [comment] 2019-11-06 16:58
It seems that anything that is has a fixed position and clickable, does trigger the close:outer event of any 
 fullscreen dialog (even with persistent prop).

**Comment by ThomasGauthierr** [comment] 2019-11-07 14:30
I'm facing the very same issue, any help would be greatly appreciated.

**Comment by BloodMotion** [comment] 2019-11-13 15:54
Same issue here :(

**Comment by NavidMitchell** [comment] 2020-02-18 05:05
Found a temporary fix here that worked for me. It is not the marked answer but works nicely.
 
https://stackoverflow.com/questions/49627750/vuetify-closing-snackbar-without-closing-dialog 

"For anyone still looking for a good solution: add <div class="v-menu__content--active" style="display:none; z-index:1000;"></div> as a child of your v-snackbar. This tricks v-dialog to think it was not the active component when click outside happened and prevents closing."

**Comment by 185driver** [comment] 2020-02-18 17:04
@NavidMitchell This is a fantastic workaround. Thanks for sharing it.  This issue affects my apps daily (due to snackbars with clickable buttons) so your solution is a welcome relief. I modified the markup slightly after some testing, but it works the same, in case someone is interested:
```
<v-snackbar
  v-model="snackbar"
  bottom
>
  <div
    v-show="false"
    class="v-menu__content--active"
  />
  {{ snackText }}
</v-snackbar>
```

**Comment by KaelWD** [comment] 2020-02-18 17:12
Damn that's sneaky. Note this will cause the dialog to have a higher z-index than the snackbar if the snackbar is open first.

**Comment by 185driver** [comment] 2020-02-18 17:16
Is the higher z-index issue alleviated by setting it to 1000 as @NavidMitchell suggested?

**Comment by KaelWD** [comment] 2020-02-19 05:31
No, you should set z-index on the dialog instead.

**Comment by yusifk88** [comment] 2020-03-07 21:19
> @MajesticPotatoe Thanks. Indeed, that was noted in the issue I posted. I wasn't aware that `fullscreen` pulled in `hide-overlay` functionality automatically. Good to know, and it makes sense. Actually, to me, `fullscreen` should naturally pull in `persistent` too, then, as clicking outside the dialog isn't practically possible (or shouldn't be).

this would not be practical either, i was facing this issues and thought i could just add persist on the dialog until users started wondering why pressing escape on the keyboard dose not close the dialog, my solution now is remove the persistent from the dialog and also remove the close button from the snackbar so it timeout by it self

**Comment by 185driver** [comment] 2020-06-15 18:24
Some observations after upgrading to v2.3.0...here's an updated [codepen](https://codepen.io/185driver/pen/QWyKEMq) too:

1. The workaround shared by @NavidMitchell no longer seems to work, at least for me. I'm not sure what the issue is, as I'm getting intermittent results in my project, but mostly my `v-snackbar` no longer displays properly when triggered within a fullscreen dialog. The structural changes to `v-snackbar` made in PR [#11542](https://github.com/vuetifyjs/vuetify/pull/11542) seem to be the reason.
1. On the bright side, the workaround is no longer needed if you add the `persistent` prop to `v-dialog`. This was the original workaround that didn't work in some cases. Now it does, but it comes with a side effect...dismissing the snackbar causes the persistent click animation to fire, which is an odd effect on a fullscreen dialog. Adding the `no-click-animation` prop along with the `persistent` prop resolves this.
1. Earlier in this thread, there was discussion of `v-dialog` behavior in `fullscreen` or non-fullscreen mode along with `hide-overlay` and `persistent` prop use. I don't know what the current `v-dialog` status is for these props, but my suggestion for resolving and closing this issue would be to consider automatically adding `hide-overlay`, `persistent` and `no-click-animation` props (their associated classes, actually) anytime the `fullscreen` prop is invoked. It seems natural that they would always be included in a fullscreen scenario, and would eliminate the need to add them manually.

**Comment by albertovincenzi** [comment] 2020-08-17 16:49
@185driver 
1. I tested and works but if dialogs are not fullscreen, the snackbar appears under, so its not fully visible
2. Agree, its not nice to see the animation
3. In my opinion, its not the best choice because I expect that  by default, clicking on dismiss button of snackbar will only generate a single action which doesn't involve other components. Adding all that props will solve the issue but I still consider that as a workaround.

**Comment by mihailovskim** [comment] 2022-08-25 20:40
This issue is still not resolved?

I have case where I use snackbar as notification alert, so some action is done on modal and it's closed, snackbar is shown and starting to count - closed automatically after 5sec. If in meantime any other modal is opened, it closes in the same moment when snackbar disappears and cannot be open anymore because modal `v-model` is not changed to false.

**Comment by MetRonnie** [comment] 2023-10-02 10:26
Why has this been closed? It's still reproduceable in the latest nightly build: [https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFU7FOwzAQ/ZXDS0EiSdsw0CpFIBjYGBATYXAdl1p1Yst2ylD137nETeO0RXhJfPf87vnd+XNHrGHJk9bxtuZkTjLHSy2p4w95BZBtI6p1+9tuSioqYJJau8iJptF9Tg7JNm0ryjZLagCRquASQXatft4P4ZyAEyVXtcNENAnOAnysQa2v4JUbDsIChY6rhxylIb2Vys0pc0JVNmBpVSxdBY9MCrY5qQ8LWFFp+aBws56lwmjIkrQ0ASxLBsZ0oE7lMRi40ejYUiNo1dwXby1FxQs0YSDuRVCpvlGaM/VQ2ZvmFRQ+3fMGyoJaB9jQd0894EQoo6Y4tayJRU442d/Or74fvsKpSX8c7CgvdejfHp0ZEdhxPhWX2xWoO9fQpQad9PfrRh0Dzaz7R4Ab/woGQ4Bby4zQDix3dZMWpVbGwQ4MX8EeVkaVMMJnNWrADDUgNOw4wq7bgbwJ04ETISBLfDWsQ/a3JI3T+I7472SGYq3jJp6Op2k0nkXpmHz9AufJJZw=)

**Comment by johnleider** [comment] 2023-10-02 15:18
This issue references v1.5 of Vuetify. If it's still relevant in Vuetify 3, create a new issue please.

**Closed by johnleider** 2023-10-02 15:18 UTC
Labels: T: bug, C: VDialog, has workaround
