### ISSUE TITLE
[Bug Report] Can not have a components as LTR, when the whole app is set to RTL.

### ISSUE THREAD

**Issue by artmarydotir** [vuetifyjs/vuetify#9716] opened 2019-11-18 13:10 UTC
### Environment
**Vuetify Version:** 2.1.2
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Ubuntu undefined

### Steps to reproduce
I have a part that I need to have both RTL components & LTR component at the same time.
now we can change the direction of whole layout, but
i need to prevent RTL on some components.
But this is not possible. 
if i change a component's dir to ltr when whole layout is rtl
All styles will be shake and broken.

### Expected Behavior
I need to have an LTR component in RTL layout.

### Actual Behavior
![Screenshot from 2019-11-18 16-16-43](https://user-images.githubusercontent.com/11363931/69054948-e75c3600-0a21-11ea-8e32-217d03dd9c2b.png)

I know i can patch to css,
but if it was only one component that was easy to patch.
but there is a lot.

### Reproduction Link
<a href="https://codepen.io/artmarydotir/pen/NWWeMMd" target="_blank">https://codepen.io/artmarydotir/pen/NWWeMMd</a>

### Other comments
As you see the form label is still in rtl mode when i set dir=ltr and the buttons styles are broken.
Is there any way to achieve this please?

**Comment by mhf-ir** [comment] 2019-11-18 13:17
Also same problem using LTR application need RTL component.

Design Must be inherit and each component must be loaded RTL and LTR separately not depend on HTML Direction.

All component must inherit direction from parent until app.
If set overwrite default app / or parent direction.

**Comment by jacekkarczmarczyk** [comment] 2019-11-18 14:40
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7507

**Closed by jacekkarczmarczyk** 2019-11-18 14:40 UTC
Labels: rtl, triage
