### ISSUE TITLE
[Bug Report] v-autocomplete will not select an exact value that was typed in when a longer match exists

### ISSUE THREAD

**Issue by asiFarran** [vuetifyjs/vuetify#5184] opened 2018-09-28 14:33 UTC
### Versions and Environment
**Vuetify:** 1.2.5
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 7

### Steps to reproduce
Type 'item-1' in the autocomplete box and then tab out

### Expected Behavior
The 'item-1' option will be selected

### Actual Behavior
No option is selected

### Reproduction Link
[https://codepen.io/asifarran/pen/LgYXvr](https://codepen.io/asifarran/pen/LgYXvr)

### Other comments
If you select the 'item-1' option from the menu (using mouse or keyboard) the correct option is selected correctly.

If there is only one item matching the typed value the option is selected correctly. (e.g type in 'item-11')

Whenever there are more than a single item that matches the typed value then no selection is made even though we have an item that matches the typed value exactly.

**Comment by KaelWD** [comment] 2018-09-28 15:21
Duplicate of #4207

**Comment by asiFarran** [comment] 2018-09-28 16:12
I can see the similarities with #4207 but it is not a duplicate!

This is not about selecting the first match by default, it is about selecting the ONLY complete and exact match when there are other non-exact matches that contain the selected text as a substring.

I dont know what are the edge-cases that led to the change in 1.1 (#4207 mentions them but without details)  and so they may or may not apply here but the distinction is important.

To use a real world example if I had a country list that has:
```
[...,
'United States',
'united states minor outlying islands',
...] 
```
and I type in` 'United States' `the selection would **not** be accepted even though it is an exact match and a valid selection (as evident by the fact you could select it successfully using the mouse or keyboard).

This is a very different context to _'how shall we handle incomplete/partial matches?'_ which is what it  #4207 seems to be about.

**Comment by felix-pb** [comment] 2019-08-23 16:38
Hey! I think this is more of a feature request than a bug, but it would be very useful.

I don't know if @asiFarran's problem was that you can't press ENTER to select an exact match, when there are other existing matches. If there are just a few options, this is not that bad because you can simply click the checkbox. However, if your search "US" exactly, and if there are 1000s of other matches with "US" embedded at the start, in the middle or at the end of the match, then it is a huge pain to scroll through these 1000s of options.

A simple prop to select an exact match by default would be great.

Otherwise, some special character to indicate that you want the search to be exact (but that seems more complex than the simple prop).

In any case, thanks for this beautiful and time-saving framework!

**Comment by johnleider** [comment] 2024-01-13 16:08
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2024-01-13 16:08 UTC
Labels: T: enhancement, C: VAutocomplete
