### ISSUE TITLE
[Bug Report] Persistent dialog can be closed by clicking on snackbar

### ISSUE THREAD

**Issue by hereiscasio** [vuetifyjs/vuetify#8729] opened 2019-08-26 10:10 UTC
### Environment
**Vuetify Version:** 2.0.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.3

### Steps to reproduce
see codepen

### Expected Behavior
Click on snackbar should not cause dialog to close 

### Actual Behavior
Click on snackbar will let dialog to close 

### Reproduction Link
<a href="https://codepen.io/hereiscasio/pen/gOYmeKb?editors=1000" target="_blank">https://codepen.io/hereiscasio/pen/gOYmeKb?editors=1000</a>

### Other comments
see codepen, it's self-explanation

**Comment by hereiscasio** [comment] 2019-08-29 01:56
Any progress ?

**Comment by KaelWD** [comment] 2019-08-29 02:37
Duplicate of #8697

**Closed by KaelWD** 2019-08-29 02:37 UTC
Labels: triage
