### ISSUE TITLE
[Bug Report] data table pagination uses 10 even when overidden

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#8184] opened 2019-07-30 14:18 UTC
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 10

### Steps to reproduce
see alert

### Expected Behavior
should alert 50

### Actual Behavior
alerts 10

### Reproduction Link
<a href="https://codepen.io/anon/pen/NQRRzY?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/NQRRzY?&editable=true&editors=101</a>

The example has 10 records I believe, but I tested this with hundreds of records, and only 10 shows up, even when pagination options are at least 50.

This was fixed before, but i guess not properly...

**Comment by nekosaur** [comment] 2019-07-31 07:03
The workaround is to simply defined initial `itemsPerPage` value in options object.

**Comment by TheInvoker** [comment] 2019-08-02 03:17
Is this still being looked into?

**Comment by nekosaur** [comment] 2019-08-02 07:33
The issue is not closed

**Comment by nekosaur** [comment] 2019-08-09 17:46
Waiting for https://github.com/vuetifyjs/vuetify/pull/8286 to be merged

**Closed** 2019-08-22 14:29 UTC
Labels: C: VDataTable, S: has PR, T: bug

**Comment by paulvonber** [comment] 2019-08-31 08:32
Seems that with this bug fix another bug was introduced, I'm running nuxt in ssr and everything seems correct except that itemsPerPage being triggered twice first on the server then on the client. Not sure what causing this, but 100% sure that before 2.0.11 release things were working as expected. Or I'm stupid and doing something wrong :)

`
   <v-data-table
        disable-sort
        item-key="id"
        :items="items"
        :items-per-page.sync="setItemsPerPage"
        :server-items-length="total"
      ></v-data-table>
`

`  computed: {
    setItemsPerPage: {
      get() {
        return this.pageSettings.setItemsPerPage
      },
      set(value) {
        this.$store.dispatch('callToServerGetUpdatedData', value)
      }
    }
}`

**Comment by nekosaur** [comment] 2019-08-31 11:58
Create a new issue with a reproduction.
