### ISSUE TITLE
[Bug Report][2.5.10] Calendar drag-and-drop

### ISSUE THREAD

**Issue by y4roc** [vuetifyjs/vuetify#14343] opened 2021-10-30 11:37 UTC
### Environment
**Vuetify Version:** 2.5.10
**Last working version:** 2.5.9
**Vue Version:** 2.6.14
**Browsers:** Chrome 95.0.4638.54, Mozilla Firefox
**OS:** Mac OS 10.15.7

### Steps to reproduce
Click in a column to create an event.

### Expected Behavior
Event block should start at the pointer and will grown by movement of the mouse.

### Actual Behavior
- Chrome: Event starts at the top and can't be moved or expanded.
- Firefox: Event doesn't create by click.

### Reproduction Link
<a href="https://codepen.io/Y4roc/pen/mdMMYdR" target="_blank">https://codepen.io/Y4roc/pen/mdMMYdR</a>

**Comment by KaelWD** [comment] 2021-10-31 15:43
Duplicate of #14276

**Closed by KaelWD** 2021-10-31 15:43 UTC
Labels: S: triage
