### ISSUE TITLE
[Bug Report] fullscreen dialog hide scroll not work

### ISSUE THREAD

**Issue by lansi951** [vuetifyjs/vuetify#9699] opened 2019-11-15 13:05 UTC
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
1. Open fullscreen dialog
2. Scroll

### Expected Behavior
html tag scroll is hidden.

### Actual Behavior
hide scroll not work because overflow-y-hidden class does not exist.

### Reproduction Link
<a href="https://codepen.io/lansi951/pen/NWWERmy" target="_blank">https://codepen.io/lansi951/pen/NWWERmy</a>

**Comment by jacekkarczmarczyk** [comment] 2019-11-15 14:33
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2597

**Closed by jacekkarczmarczyk** 2019-11-15 14:33 UTC
Labels: triage
