### ISSUE TITLE
[Bug Report][3.3.23] Readonly Text  could be cleared

### ISSUE THREAD

**Issue by velly** [vuetifyjs/vuetify#18598] opened 2023-11-05 09:25 UTC
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.7
**Browsers:** Chrome 117.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Open the link
2. Focus the readonly textarea
3. Click the clear button.

### Expected Behavior
Clear button cannot be displayed in readonly mode.
At least, the value cannot be cleared.

### Actual Behavior
The value is cleared by clear btn.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj8EKwjAQRH8l7Nm2YA+CxIJ3/8B62KR7ELZJiGlQxH83TS2xp9l5c9iZ6xseXjdn5+o4ERxBBhodY6CuN0LIWKFz+cxGWxPwbsj/UIaBngE94YqESGawhl+FaCb0qJgKYlTEpx4us/ZQgtEOxFVEnijFqHQJO9mUf2uthLa9ZrLUls3fHPjsoK3b+gCL7lu4fQFfekyn)

**Comment by jacekkarczmarczyk** [comment] 2023-11-05 09:36
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7111

**Closed** 2023-11-05 10:25 UTC
Labels: S: triage
