### ISSUE TITLE
[Bug Report] clearable + readonly text-fields should not get focus after clearing

### ISSUE THREAD

**Issue by qwesda** [vuetifyjs/vuetify#6700] opened 2019-03-08 16:26 UTC
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.6.8
**Browsers:** Google Chrome, Mozilla Firefox, Safari, Microsoft Edge
**OS:** Windows, Mac OSX, Linux, Android, iOS

### Steps to reproduce
- select a date using the date picker
- clear the date using the clear button

### Expected Behavior
the text-field should not be focused, since it can't be edited anyway

### Actual Behavior
the text-field is focused

### Reproduction Link
<a href="https://codepen.io/anon/pen/wxxoYX?editors=1000" target="_blank">https://codepen.io/anon/pen/wxxoYX?editors=1000</a>

### Other comments
This is partially related to https://github.com/vuetifyjs/vuetify/issues/4135

But this issue only addresses the case where the text-field has the `readonly` and giving focus to it makes no sense. This issue should be fixed whether or not the `clearable` prop is extended like proposed there.

_The codepen was originally posted by @jacekkarczmarczyk in https://github.com/vuetifyjs/vuetify/issues/4135#issuecomment-410519836_

**Comment by jacekkarczmarczyk** [comment] 2019-06-01 15:42
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4135

**Closed by jacekkarczmarczyk** 2019-06-01 15:42 UTC
Labels: C: VDatepicker, C: VTextField
