### ISSUE TITLE
[Feature Request] Button active state remains on

### ISSUE THREAD

**Issue by tefa-dev** [vuetifyjs/vuetify#2950] opened 2018-01-06 22:20 UTC
### New Functionality
I would like to give more discretion to users when they press on buttons. I am designing an interface for tablets. My main problem is to disable the active state that remains on after pressing a button. An active state turns the associated element background color to grey with my theme. So if a user presses on a button to input a password, then it will stay active forever giving a hint to a potential observer of what could be the input. This behavior doesn't happen on desktop though.

I forced ```input-value``` attribute to true for fixing my problem knowing this is a hack. However I don't manage to set the active color to the one I like. ```currentColor``` seems immutable to me.

I also tried to set my own ```active-class``` without results.

### Improvements
Make this active behavior uniform between tablets and desktops?

### Bugs or Edge Cases it Helps Avoid
Discretion

**Comment by KaelWD** [comment] 2018-01-13 16:48
duplicate of #2178

**Closed by KaelWD** 2018-01-13 16:48 UTC
Labels: pending review
