### ISSUE TITLE
[Bug Report] Can not type in text field when it is behind a bottom-sheet

### ISSUE THREAD

**Issue by kwindo** [vuetifyjs/vuetify#7286] opened 2019-05-24 11:54 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.5

### Steps to reproduce
https://codepen.io/kimsanka/pen/MdVvWX

### Expected Behavior
Being able to use a text field on a page behind the bottom sheet when the bottom sheet is showing and hide-overlay and persistent are true.

### Actual Behavior
When the bottom sheet is showing (with hide-overlay and persistent on true) it is not possible to type text into a text field on the page behind the bottom sheet.

### Reproduction Link
<a href="https://codepen.io/kimsanka/pen/MdVvWX" target="_blank">https://codepen.io/kimsanka/pen/MdVvWX</a>

**Comment by jacekkarczmarczyk** [comment] 2019-05-24 11:55
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7209

**Closed by jacekkarczmarczyk** 2019-05-24 11:55 UTC
Labels: triage

**Comment by kwindo** [comment] 2019-05-24 14:36
Apologies for the duplicate.
