### ISSUE TITLE
[Bug Report][2.5.8] DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0. 

### ISSUE THREAD

**Issue by kangchengkun** [vuetifyjs/vuetify#14080] opened 2021-08-24 07:05 UTC
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 92.0.4515.159
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. using vue cli to create a new app
2. install vuetify package
3. run the app
A lot of warnings in the console:
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0. 

### Expected Behavior
No such warning

### Actual Behavior
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

**Comment by KaelWD** [comment] 2021-08-24 07:05
Duplicate of #13694

**Closed by KaelWD** 2021-08-24 07:05 UTC
Labels: S: triage
