### ISSUE TITLE
[Bug Report] v-select needs two tabs to change element on Firefox

### ISSUE THREAD

**Issue by renangasperi** [vuetifyjs/vuetify#9155] opened 2019-09-30 18:42 UTC
### Environment
**Vuetify Version:** 1.5.18
**Last working version:** 1.5.18
**Vue Version:** 2.5.22
**Browsers:** Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
During tab navigation, select your option on v-select and try to go to the next element using tab.

### Expected Behavior
Press just one tab to navigate to the next element.

### Actual Behavior
We actually have to press the tab twice to go to the next element.

### Reproduction Link
<a href="https://codepen.io/renangasperi/pen/MWgMYrX" target="_blank">https://codepen.io/renangasperi/pen/MWgMYrX</a>

### Other comments
It's happening at the Vuetify 1.5x documentation too, but only in firefox as said.

**Comment by Qronicle** [comment] 2021-06-11 08:56
Hope it's okay to post this in here, but this is still an issue in the latest Vuetify version

**Vuetify version**: 2.5.3
**Browser**: Firefox 89.0
**OS**: Mac OSX Catalina 10.15.7

It can easily be tested on the component's documentation page: https://vuetifyjs.com/en/components/selects/

I also noticed that after both blur events after trying to tab out of the select, the `event.relatedTarget` is `null`, even though it's still focusing another element. (If I set a timeout of 200 miliseconds and log the `document.activeElement` it shows the object that I would expect to be in `event.relatedTarget`)

**Comment by Qronicle** [comment] 2021-06-11 08:56
Hope it's okay to post this in here, but this is still an issue in the latest Vuetify version

**Vuetify version**: 2.5.3
**Browser**: Firefox 89.0
**OS**: Mac OSX Catalina 10.15.7

It can easily be tested on the component's documentation page: https://vuetifyjs.com/en/components/selects/

I also noticed that after both blur events after trying to tab out of the select, the `event.relatedTarget` is `null`, even though it's still focusing another element. (If I set a timeout of 200 miliseconds and log the `document.activeElement` it shows the object that I would expect to be in `event.relatedTarget`)

**Comment by KaelWD** [comment] 2021-11-07 09:58
This seems to be fixed in firefox 94, can anyone still reproduce?

**Comment by Qronicle** [comment] 2021-11-07 10:32
I was testing it in FireFox 93 just now, and it seems to be fixed in that version already.
My other issue:
> I also noticed that after both blur events after trying to tab out of the select, the event.relatedTarget is null, even though it's still focusing another element. (If I set a timeout of 200 miliseconds and log the document.activeElement it shows the object that I would expect to be in event.relatedTarget)

Also seems to be resolved!

**Closed** 2021-11-07 10:36 UTC
Labels: T: bug, S: needs reproduction, platform specific, C: VSelect
