### ISSUE TITLE
[Feature Request] Submenu within a menu

### ISSUE THREAD

**Issue by max-fletcher** [vuetifyjs/vuetify#13800] opened 2021-06-16 12:41 UTC
### Problem to solve
I wanted to make a submenu inside a menu tab in the navbar component but couldn't find a way to do so. As an example, here in this page :
http://iqac.uiu.ac.bd/InnovationPage.aspx
if I click the "people" tab in the navbar, a menu pops up, which has a submenu called "IQAC(UIU)" nested in it that pops up to the right on clicking on it.

### Proposed solution
 Currently, I couldn't find a way to accomplish this in vuetify, but if there is, I would love to know. I only managed to make a menu inside a navbar tab using a v-btn component. Otherwise, I think there should be an easy way to do this.

**Comment by DRoet** [comment] 2021-06-16 12:52
duplicate of https://github.com/vuetifyjs/vuetify/issues/1877

**Closed** 2021-06-16 13:03 UTC
Labels: triage
