### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] Indeterminate progress bar doesn't animate with custom theme 

### ISSUE THREAD

**Issue by bo-pedersen** [vuetifyjs/vuetify#14475] opened 2021-12-08 11:51 UTC
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.24
**Browsers:** Chrome 96.0.4664.93
**OS:** Windows 10

### Steps to reproduce
Adding a custom theme breaks the animation of the progress bar.

1. Start with the indeterminate progress bar example: https://next.vuetifyjs.com/en/components/progress-linear/#indeterminate
2. Add a custom theme:
```javascript
const theme = {
  dark: false,
  colors: {
    primary: "#E31937",
    "primary-darken-1": "#AA1329",
    secondary: "#5236AB",
    "secondary-darken-1": "#3E2880",
    accent: "#991F3D",
    error: "#A82465",
    info: "#E1E1E1",
    success: "#00C851",
    warning: "#FF6A00",
    background: "#FFFFFF",
    surface: "#FFFFFF"
  },
  variables: {}
};
const vuetify = createVuetify({
  theme: {
    defaultTheme: "defaultTheme",
    themes: { defaultTheme: theme }
  }
});
```
3. The animation stops.

### Expected Behavior
Progress bar continues to animate with custom theme like without adding the custom theme

### Actual Behavior
Animation stops

### Reproduction Link
<a href="https://codepen.io/Bo-Pedersen/pen/JjrXVaG" target="_blank">https://codepen.io/Bo-Pedersen/pen/JjrXVaG</a>

**Comment by KaelWD** [comment] 2021-12-08 11:56
You're missing the variables section: https://codepen.io/kaelwd/pen/ZEXWNQY?editors=1010

Duplicate of #13914

**Closed by KaelWD** 2021-12-08 11:56 UTC
Labels: S: triage

**Comment by bo-pedersen** [comment] 2021-12-08 13:12
Adding content to the variables section fixes my issue. But I had no idea, what to add in this section, only that is was required. Optional like described in #13914 would remove this need.
