### ISSUE TITLE
[Bug Report] Menu with tooltip not position correctly.

### ISSUE THREAD

**Issue by jamesladd** [vuetifyjs/vuetify#9291] opened 2019-10-08 23:15 UTC
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 66.0.3359.181
**OS:** Linux x86_64

### Steps to reproduce
Goto this documentation page https://vuetifyjs.com/en/components/menus#menu-with-activator-and-tooltip then click the example button 'DROPDOWN W/ TOOLTIP' 
The menu appears top left of page and not near the button. 

### Expected Behavior
Expected the menu would be located on the menu button

### Actual Behavior
Menu appears top left of page.

### Reproduction Link
<a href="https://jsfiddle.com" target="_blank">https://jsfiddle.com</a>

### Other comments
https://vuetifyjs.com/en/components/menus#menu-with-activator-and-tooltip

**Comment by MajesticPotatoe** [comment] 2019-10-08 23:25
duplicate of #8846

**Closed by MajesticPotatoe** 2019-10-08 23:25 UTC
Labels: triage
