### ISSUE TITLE
Fab button icon wrong align

### ISSUE THREAD

**Issue by Djaler** [vuetifyjs/vuetify#5411] opened 2018-10-24 07:05 UTC
### Versions and Environment
Vuetify: 1.3.2
Vue: 2.5.17
Browsers: Firefox 62
OS: Debian 9

### Steps to reproduce
Create FAB button with material icon and open page in Firefox

### Expected Behavior
Icon aligned in center

### Actual Behavior
Icon aligned in top

### Additional Comments:
This is how it looks:
![screenshot_20181024_095756](https://user-images.githubusercontent.com/7964583/47412268-ebad1580-d773-11e8-9cfe-030d3de0395b.png)

This is styles. If I disable `display: inline-block;` in `.material-icons`, then it works well. So maybe problem in styles ordering.
![screenshot_20181024_095828](https://user-images.githubusercontent.com/7964583/47412269-ebad1580-d773-11e8-8f46-946903b5ad92.png)

Also, when I open https://vuetifyjs.com/ru/components/buttons in Firefox, FAB looks good. But in this page css files are splitted. In my current build this css was inlined

**Comment by jacekkarczmarczyk** [comment] 2018-10-24 07:08
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3462

**Comment by Djaler** [comment] 2018-10-24 07:08
I think `display: inline-flex !important;` in `.v-icon` can solve the issue

**Closed by jacekkarczmarczyk** 2018-10-24 07:08 UTC

**Comment by fmay** [comment] 2019-01-17 17:41
Same problem here and @Djaler 's suggestion solves it indeed.
