### ISSUE TITLE
[Bug Report][3.3.20] Memory leak in Nuxt SSR

### ISSUE THREAD

**Issue by memic84** [vuetifyjs/vuetify#18393] opened 2023-10-03 18:42 UTC
### Environment
**Vuetify Version:** 3.3.20
**Vue Version:** 3.3.4
**Browsers:** Chrome 116.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- yarn install
- yarn build 
- node --inspect .output/server/index.mjs
- Open localhost:3000
- Go to the Node.js devtools in Chrome (green icon in the top corner)
- Go to Memory and select Heapsnapshot (first option)
- Create a Heapsnapshot
- Collect garbage manually (trash bin icon)
- Simulate traffic: I use Apache Benchmark `ab -n 1000 -c 100 http://localhost:3000/`
- Create a Heapsnapshot
- Collect garbage manually (trash bin icon)
- Simulate traffic: `ab -n 1000 -c 100 http://localhost:3000/`
- Repeat the steps a couple of times, and you'll see that the memory goes up

Currently running Node v18.18.0, but the version doesn't seem to make a difference.

The increase in memory in the application happens a lot faster, from 30 -> 300 in about 200 users, en keeps rising. My best guess is because we have a lot more components then in the reproduction. 

### Expected Behavior
The memory should keep consistant when there is no load on the server, and the garbage should be able to be collected.

### Actual Behavior
After some debugging i can see that there are a lot of computedRefs created, with CSS theme options and kept in memory.
When we remove vuetify, the memory leaks also dissapear, so we are certain that the memory leak is in vuetify when used in SSR mode for Nuxt.

### Additional information
See below for more information on memory profiling.

<img width="197" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/3043840/22712caf-a270-41bc-aefd-4e94f248af9b">
<img width="1254" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/3043840/6346ecee-2114-4287-aba9-8572003048ea">
<img width="1242" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/3043840/20bcfdd3-96a8-409d-9a9f-ce37b1dd5bef">
<img width="1255" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/3043840/31e605d8-e174-4ece-bf45-8c3b6a97315e">
<img width="1250" alt="image" src="https://github.com/vuetifyjs/vuetify/assets/3043840/1588f245-1130-4073-a196-911db056aa52">

### Reproduction Link
[https://github.com/cultuurnet/uiv-nuxt-memoryleak-reproduction](https://github.com/cultuurnet/uiv-nuxt-memoryleak-reproduction)

Any help is welcome, as this is blocking our migration to Nuxt 3. Also open to contribute if someone can point me in the right direction in the vuetify code.

**Comment by memic84** [comment] 2023-10-03 18:56
Could be related to https://github.com/vuetifyjs/vuetify/issues/18339, however when we leave the theme option out of the vuetify plugin, the memory leak is still present but the memory doesn't go quite fast as without it.

**Comment by memic84** [comment] 2023-10-03 19:00
We have checked a couple of other memory leak issue which were reported, and some seem also related (https://github.com/vuetifyjs/vuetify/issues/17917, https://github.com/vuetifyjs/vuetify/issues/17473) but the parsedOptions and the change to the watcher in the composable theme, don't seem to do the trick for us.

**Comment by memic84** [comment] 2023-10-16 10:13
Any chance somebody could review this?

**Comment by memic84** [comment] 2023-11-23 07:50
Even with the #18449 fix, there still remain some memory leaks in vuetify.

Here is a minimal reproduction: https://github.com/memic84/vuetify-memory-leak-reproduction

@johnleider Any chance that somebody from the team could take a look, or guide us in the right direction for a fix? This is really blocking when running a large application in SSR mode.

**Comment by johnleider** [comment] 2023-11-27 16:31
@memic84 Did you mean to close your PR?

**Comment by memic84** [comment] 2023-11-27 16:53
@johnleider No, i wanted to add two new commits to it. After profiling found out the the locale composable leaves a lot of traces when a computed is used in a return function.

https://github.com/vuetifyjs/vuetify/blob/c6f9dc83078fa9037606db7ace76c7bc161dfd1b/packages/vuetify/src/composables/locale.ts#L91

I removed the `ref` from isRtl and rtlClasses, not sure if this needs to be reactive.

https://github.com/vuetifyjs/vuetify/commit/464593fb969a132dade5550e240a074adc05041c

**Comment by johnleider** [comment] 2023-11-27 23:21
Open a new PR

**Comment by oemer-aran** [comment] 2023-11-30 11:21
> @oemer-aran Do you still have minor memory leaks even with the fix?

We switched to a lambda deployment, which basically makes the memory leak problem obsolete. One of the main reasons for this switch was the vuetify memory leak. Otherwise we couldn't go live with our Nuxt 2 to Nuxt 3 migration. It was truly a challenge and very frustrating. Your fix seem to have eliminated the primary and biggest memory leak. 🎉

**Comment by johnleider** [comment] 2023-12-06 17:31
Duplicate of #18339

**Closed by johnleider** 2023-12-06 17:31 UTC
Labels: T: bug, NUXT
