### ISSUE TITLE
[Bug Report] v-expansion-panels - v-model change, animation does not work, on the first pass.

### ISSUE THREAD

**Issue by Dinver** [vuetifyjs/vuetify#11534] opened 2020-06-01 09:14 UTC
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Open reproduction link;
Click button "+1".

### Expected Behavior
Animation is working.

### Actual Behavior
Animation working in from the second pass.

### Reproduction Link
<a href="https://codepen.io/dinver/pen/JjGPKWe?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fexpansion-panels%2F" target="_blank">https://codepen.io/dinver/pen/JjGPKWe?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fexpansion-panels%2F</a>

**Comment by KaelWD** [comment] 2020-06-01 09:29
Duplicate of #10140

**Closed by KaelWD** 2020-06-01 09:29 UTC
Labels: triage
