### ISSUE TITLE
[Bug Report][3.6.9] VDatePicker crash on danish with "date value is not finite in DateTimeFormat.format()"

### ISSUE THREAD

**Issue by Endahl** [vuetifyjs/vuetify#20023] opened 2024-06-18 09:26 UTC
### Environment
**Vuetify Version:** 3.6.9
**Vue Version:** 3.4.29
**Browsers:** Firefox 126.0
**OS:** Ubuntu undefined

### Steps to reproduce
Surround a `VDatePicker` with a `VLocaleProvider` with `locale` set to "da",
or in vuetify.js set locale to "da", ([playgound link](https://play.vuetifyjs.com/#eNqVUstOwzAQ/BXLl4DU2IciBFWoyk9wwRzSeCsMfsl2Q1GVf2fjWNAGDuVieXdmZ9YjPx9pDB3v95DU7pO9RbqiyngXEjmSLkCb4GnCyEB2wRlSFW4lrLBwyNTO2ZhIAcjD+eDVUVhCtOtaDSuSi5+ykm21GFsDnsO1sHSRF3r0nqEebtMkMF6j3HqkNX3dep+vuZAI1F517xDWDT+vMx9700DDT4TQZXplbVqPr3YWnfJqogBR0O9lBcVVxlrQ15R8XHHeSYtjErTqA7OQuPWGb5DGw94mZaCWzmyWbMluuFQxnbYZRFNvg/uIEFBE0BxAsRkTu8CqMNHhlt1PDqVV63YbR4s/pfkU/L8cluyOa7Uto1xZCQdm5uocX9NDqAMgHiBcmtds7DSzGfQrt/xv8NvQYWH3Wufj5QuoffmB)):
```
const vuetify = createVuetify({
    locale: {
      locale: "da"
    }
})
```

### Expected Behavior
Translate to danish or fallback to English

### Actual Behavior
Do not render any dates and console give the error: date value is not finite in DateTimeFormat.format()

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUMtOwzAQ/BXLl4JU24ciBFValZ/ggjmk8VYY/JLthqIq/84m8SENHNqL5Z2dndmdtzNNsRHtEbI+/PDPRNdU2+BjJmfSRKgzvI490pFD9JYsCnchnXRwGqiNdymT0iCby8G7e+nocrB5CYEjCz2qDDYYJG2lI6RqWR3C8B0K45vaAAvRt1pBJGO9kVTVkhbaQFSowIJuviBuK3FZFzVEZ3KjJeKjZyUmu+Ci4/nM1gHj8A6XPfcDsjSSpGsyID2G1/S1pB85h7QWolEOxxQY3UbuIAsXrNghTcSjy9oCU97uVnzFH4TSKU9hDsmyffTfCSKKSLqc2PRRXmFVmOjwyJ9HhwIxU+9Tb/GvtBhDuslhxZ+E0fsyKrRTcOJ2ri7wmhYii4D9CPHavGZj08xmrT+59e6ddB3tlu5ozPC8/wLcagJU)

**Comment by KaelWD** [comment] 2024-09-06 09:45
Duplicate of #19803

**Closed by KaelWD** 2024-09-06 09:45 UTC
Labels: S: triage
