### ISSUE TITLE
[Bug Report] Bad rendering icons

### ISSUE THREAD

**Issue by rifton007** [vuetifyjs/vuetify#10799] opened 2020-03-10 03:09 UTC
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
All icons were rendering correctly since beginning.
But today, all icons in my app are wrong rendering. Vuetify display icons differently.

https://ibb.co/T1K4Q6Y

### Expected Behavior
Good rendering icons

### Actual Behavior
Bad rendering icons

### Reproduction Link
<a href="https://codepen.io/InnovaWEB/pen/yLNpvGj" target="_blank">https://codepen.io/InnovaWEB/pen/yLNpvGj</a>

### Other comments
I already reboot my computer and delete then reinstall all NPM packages of the project.

**Comment by MajesticPotatoe** [comment] 2020-03-10 03:12
Are you using CDN, if so are you explicitly specifying a version?
I can only guess this is a duplicate of #10797.

**Comment by jacekkarczmarczyk** [comment] 2020-03-10 03:21
Probably duplicate but anyway it's missing reproduction

**Comment by rifton007** [comment] 2020-03-10 03:22
No, I don't use CDN, just use default icons on Vuetify.

**Closed by jacekkarczmarczyk** 2020-03-10 03:21 UTC
Labels: triage

**Comment by jacekkarczmarczyk** [comment] 2020-03-10 03:23
Try using 4.x version of MDI

**Comment by rifton007** [comment] 2020-03-10 04:49
I see the issue #10797.
But in my case, I don't use Nutx or any CDN.
Just default icons of Vuetify.

I don't understand what happens with Vuetify since some hours, because it worked fine before this.
I now make a test with a new blank project and I have the same problem.

//package.json
```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.4",
    "vue": "^2.6.11",
    "vuetify": "^2.2.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.2.0",
    "@vue/cli-plugin-eslint": "~4.2.0",
    "@vue/cli-service": "~4.2.0",
    "babel-eslint": "^10.0.3",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.1.2",
    "sass": "^1.19.0",
    "sass-loader": "^8.0.0",
    "vue-cli-plugin-vuetify": "~2.0.5",
    "vue-template-compiler": "^2.6.11",
    "vuetify-loader": "^1.3.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}
```
https://vuetifyjs.com/en/examples/layouts/baseline-flipped/
I just use the pre-made layout and here the result :
![Annotation 2020-03-10 054242](https://user-images.githubusercontent.com/2601347/76280444-2690ea00-6292-11ea-8ee1-41b0cb4a788a.png)

**Comment by liranh85** [comment] 2020-03-10 09:04
Same here, all icons are changed to something random

**Comment by jacekkarczmarczyk** [comment] 2020-03-10 09:42
> But in my case, I don't use Nutx or any CDN.

You don't have any icons in your package.json, then you are using icons from CDN

https://github.com/vuetifyjs/vuetify/issues/10797#issuecomment-596942773

**Comment by liranh85** [comment] 2020-03-10 10:19
This is now fixed for me, all icons are rendered correctly again. Thanks for the quick fix!

**Comment by rifton007** [comment] 2020-03-10 11:13
Thank you @MajesticPotatoe,
I had cleared the cache of browser and this is fixed.
