### ISSUE TITLE
[Bug Report] v-menu improper positioning when using left and nudge-width property

### ISSUE THREAD

**Issue by hxtpoe** [vuetifyjs/vuetify#11548] opened 2020-06-03 14:14 UTC
### Environment
**Vuetify Version:** 2.2.30
**Vue Version:** 2.6.10
**Browsers:** Safari 13.1.1, Google Chrome, Safari, Mozilla Firefox
**OS:** Mac OS 10.15.5

### Steps to reproduce
0. Use :left="true" property to position menu.
1. Click "MENU AS POPOVER"
2. Observe displayed menu position.
3. Close menu
4. Click "MENU AS POPOVER" again
5. Observe again displayed menu position.

### Expected Behavior
Displayed menu should be aligned to the left border of a button. 

### Actual Behavior
Menu is not positioned properly during the first open. Opening menu for the second time gives proper results. Menu is positioned properly. 
Screencast: https://drive.google.com/drive/folders/1b-t9haQoWCyKeSyePJTZmUFkXAa-cD3Y?usp=sharing

### Reproduction Link
<a href="https://codepen.io/hxtpoe/pen/GRoRxma" target="_blank">https://codepen.io/hxtpoe/pen/GRoRxma</a>

**Comment by hxtpoe** [comment] 2020-06-03 14:36
PR #11549

**Comment by MajesticPotatoe** [comment] 2020-06-03 14:42
This seems more of a conflict with `nudge-width` then the left property itself

**Comment by MajesticPotatoe** [comment] 2020-06-03 14:49
related to #5870

**Comment by KaelWD** [comment] 2022-06-30 10:37
Duplicate of #5870

**Closed by KaelWD** 2022-06-30 10:37 UTC
Labels: duplicate
