### ISSUE TITLE
[Bug Report] UX problem with labels on Box-style Inputs

### ISSUE THREAD

**Issue by simshaun** [vuetifyjs/vuetify#2816] opened 2017-12-16 21:06 UTC
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.5.11
**Browsers:** Firefox 57.0
**OS:** Windows 10

### Steps to reproduce
Visit the Vuetify docs, https://vuetifyjs.com/components/text-fields#example-18

Click anywhere in roughly the first 40% vertically of a boxed input.

### Expected Behavior
Clicking the label should focus the input.

### Actual Behavior
The input is not focused.

### Reproduction Link
[https://github.com/vuetifyjs/vuetify](https://github.com/vuetifyjs/vuetify)

**Comment by KaelWD** [comment] 2017-12-17 04:30
Duplicate of #1829

**Closed by KaelWD** 2017-12-17 04:30 UTC
