### ISSUE TITLE
[Bug Report] mini-css-extract-plugin reports conflicting order warnings in a new project

### ISSUE THREAD

**Issue by kevinpoitra** [vuetifyjs/vuetify#11953] opened 2020-07-28 16:12 UTC
### Environment
**Vuetify Version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Firefox 78.0
**OS:** Windows 10

### Steps to reproduce
- Created the test project via `vue create vuetify-order-test`. The default settings (babel, eslint) were used, along with adding vue-router during setup.
- Added Vuetify via `vue add vuetify`. The default settings were used.
- Renamed the Home and About views to ViewA and ViewB, and made changes to router/index.js to point to those new files and name the chunks "viewa" and "viewb".
- Inserted one of the data table examples into ViewA, and one of the radio selection examples into ViewB. The order doesn't seem to matter. The components used may not matter either - these are just two that I'm experiencing issues with.
- Ran `npm run build`, which output those warnings.

### Expected Behavior
The project compiles without warnings.

### Actual Behavior
A few warnings about chunk ordering are produced, seemingly from within Vuetify, like so:

```
chunk viewa~viewb [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/components/VInput/VInput.sass
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/directives/ripple/VRipple.sass
   - couldn't fulfill desired order of chunk group(s) viewb
   - while fulfilling desired order of chunk group(s) viewa
```

```
chunk viewa~viewb [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/components/VIcon/VIcon.sass
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/directives/ripple/VRipple.sass
   - couldn't fulfill desired order of chunk group(s) viewb
   - while fulfilling desired order of chunk group(s) viewa
```

```
chunk viewa~viewb [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/components/VLabel/VLabel.sass
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/directives/ripple/VRipple.sass
   - couldn't fulfill desired order of chunk group(s) viewb
   - while fulfilling desired order of chunk group(s) viewa
```

```
chunk viewa~viewb [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/components/VMessages/VMessages.sass
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/directives/ripple/VRipple.sass
   - couldn't fulfill desired order of chunk group(s) viewb
   - while fulfilling desired order of chunk group(s) viewa
```

### Reproduction Link
<a href="https://github.com/kevinpoitra/vuetify-order-test/" target="_blank">https://github.com/kevinpoitra/vuetify-order-test/</a>

### Comments
I'm working on upgrading a website from Vuetify 1.5 to 2.3. I've got it mostly working, outside of this warning that shows up in that project as well. In that project, the warning is slightly different:

```
chunk viewa~viewb [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/components/VDataTable/VDataTable.sass
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/styles/components/_selection-controls.sass
   - couldn't fulfill desired order of chunk group(s) viewa
   - while fulfilling desired order of chunk group(s) viewb
```
```
chunk viewa~viewb [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/components/VDataIterator/VDataFooter.sass
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/styles/components/_selection-controls.sass
   - couldn't fulfill desired order of chunk group(s) viewa
   - while fulfilling desired order of chunk group(s) viewb
```
```
chunk viewa~viewb [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/components/VDataTable/VDataTableHeader.sass
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/styles/components/_selection-controls.sass
   - couldn't fulfill desired order of chunk group(s) viewa
   - while fulfilling desired order of chunk group(s) viewb
```
```
chunk viewa~viewb [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/components/VDataTable/VSimpleTable.sass
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/styles/components/_selection-controls.sass
   - couldn't fulfill desired order of chunk group(s) viewa
   - while fulfilling desired order of chunk group(s) viewb
```
```
chunk viewa~viewb [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/components/VRadioGroup/VRadio.sass
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!./node_modules/postcss-loader/src??ref--9-oneOf-3-2!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!./node_modules/vuetify/src/styles/components/_selection-controls.sass
   - couldn't fulfill desired order of chunk group(s) viewa
   - while fulfilling desired order of chunk group(s) viewb
```
Both views in that project contain a few data tables and radio selection inputs, amongst other components.

**Comment by KaelWD** [comment] 2020-07-29 08:10
Duplicate of #5271

**Closed by KaelWD** 2020-07-29 08:10 UTC
Labels: triage
