### ISSUE TITLE
[Bug Report] <v-combobox> commits value to its model after validate()

### ISSUE THREAD

**Issue by henriq-88** [vuetifyjs/vuetify#5628] opened 2018-11-16 06:04 UTC
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Mac OS 10.14.1

### Steps to reproduce
1. Type something into the `<v-combobox>`
2. While the cursor is still in the `<v-combobox>`, press the `<v-btn>` which fires the validation check

### Expected Behavior
Text should be commit to its model before being validated

### Actual Behavior
Text is commit to its model after being validated

### Reproduction Link
<a href="https://codepen.io/henriq88/pen/MzoEgz?editors=1111" target="_blank">https://codepen.io/henriq88/pen/MzoEgz?editors=1111</a>

### Other comments
validate-on-blur prop doesn't seem to help

**Comment by KaelWD** [comment] 2018-11-16 08:41
Duplicate of #5203, possible duplicate of #4679

**Closed by KaelWD** 2018-11-16 08:41 UTC
