### ISSUE TITLE
[Bug Report] Tab order resets to start of page on closing v-dialog

### ISSUE THREAD

**Issue by boarnoah** [vuetifyjs/vuetify#12489] opened 2020-10-23 04:36 UTC
### Environment
**Vuetify Version:** 2.3.15
**Vue Version:** 2.6.12
**Browsers:** Firefox 78.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
1) Tab through a site
2) Open a v-dialog by clicking/pressing enter on a button 
2) Close a v-dialog with the escape key (or a close button in the dialog)
4) Continue tabbing

### Expected Behavior
Tab order will continue from the button that was last pressed.

### Actual Behavior
Currently focused tab item resets to the first element on the page (tab order is reset).

### Reproduction Link
<a href="https://codepen.io/boarnoah/pen/XWKprYW" target="_blank">https://codepen.io/boarnoah/pen/XWKprYW</a>

### Other comments
To the best of my knowledge there is nothing on the page with a modified tab order that could be causing this to happen. 

This happens even in the simple codepen environment.

**Comment by KaelWD** [comment] 2020-10-23 04:46
Duplicate of #7907

**Closed by KaelWD** 2020-10-23 04:46 UTC
Labels: C: VDialog, T: bug
