### ISSUE TITLE
[Bug Report] v-select label outlined: fieldset border crosses over the label

### ISSUE THREAD

**Issue by pcalin** [vuetifyjs/vuetify#9225] opened 2019-10-04 04:27 UTC
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90, Safari, Google Chrome, Microsoft Edge
**OS:** Windows 10, Windows, Android, iOS, Mac OSX

### Steps to reproduce
simply expand the expansion panel and observe the label being crossed through.

### Expected Behavior
border should stop next to label

### Actual Behavior
border crosses over label

### Reproduction Link
<a href="https://codepen.io/calin-pirtea/pen/MWWgXQB?&editable=true&editors=101#anon-signup" target="_blank">https://codepen.io/calin-pirtea/pen/MWWgXQB?&editable=true&editors=101#anon-signup</a>

### Other comments
I have not seen this work in vuetify 2.0+

the expansion is not required to get the broken behaviour but it is the easiest way to reproduce.

I was able to get the broken behaviour even using examples from https://vuetifyjs.com/en/components/selects#examples

**Comment by pcalin** [comment] 2019-10-04 04:30
After logging it I found another example of the same thing in 9165

**Comment by ascott18** [comment] 2019-10-15 15:44
This happens for any input component that supports `outlined` - `v-text-field`, `v-select`, and so on.

It also happens when these inputs are used as the activator slot for a `v-menu` or `v-dialog`. For example, add `outlined` to the `v-text-field`s in the date picker menu/dialog examples at https://vuetifyjs.com/en/components/date-pickers#date-pickers-in-dialog-and-menu

**Comment by willemavjc** [comment] 2019-10-30 22:23
For my personal knowledge, does anyone already know where this issue happens? I mean, is this caused by an erroneous JS code from Vuetify called on serve/build-time?

**Comment by willemavjc** [comment] 2019-10-31 20:14
Interestingly, I found out that _sometimes_ label's width is correctly computed while playing on codepen and changing labels and/or placeholders values.
So weird.

**Comment by jcirizar** [comment] 2019-11-08 18:05
Anyone knows a fix for this so far?

**Comment by MrJmpl3** [comment] 2019-11-09 04:25
I see, the problem is in the style width from the legend tag.

**Comment by Dev1lDragon** [comment] 2019-11-11 11:55
Intersection Observer can solve the proplem

**Comment by waynecz** [comment] 2019-11-13 03:25
Me too, when the component is firstly invisible`eg. display: none`, the lagend width would get 0

**Comment by Dev1lDragon** [comment] 2019-11-15 12:17
Google have good solution for that and corrections is easy, and consist in label background color.
[Example above](https://codepen.io/dev1ldragon/pen/QWWJKjp)  is shown how its can be corrected for light theme

**Comment by N3rdP1um23** [comment] 2019-11-22 20:09
I am seeming to have the same issue with having a v-select in a v-expansion-panel.  @MajesticPotatoe linked me to this issue and I thought I'd add a note.  I linked it in the Discord but here's an example of the issue

![image](https://user-images.githubusercontent.com/8093806/69456976-0583a800-0d3a-11ea-859d-54d3cd184b60.png)

**Comment by demonye** [comment] 2019-11-27 23:43
> Google have good solution for that and corrections is easy, consist in label background color.
> [Example above](https://codepen.io/dev1ldragon/pen/QWWJKjp) is shown how its can be corrected for light and dark theme

This fixed border crossing over but it there is prepend-inner-icon on the text-field, the label position is still not right.

**Comment by jacekkarczmarczyk** [comment] 2020-01-11 12:59
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9165

**Closed by jacekkarczmarczyk** 2020-01-11 12:59 UTC
Labels: C: VSelect, T: bug

**Comment by nka212bg** [comment] 2024-02-16 15:57
This works for me, as long the label is not too long.

`.v-text-field  .v-label {
        padding-left: 4px !important;
        padding-right: 12px !important;
    }`
