### ISSUE TITLE
[Bug Report][3.6.1] TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by toughlex-donatas** [vuetifyjs/vuetify#19733] opened 2024-05-01 15:28 UTC
### Environment
**Vuetify Version:** 3.6.1
**Vue Version:** 3.4.24
**Browsers:** Chrome 124.0.0.0
**OS:** Linux

### Steps to reproduce
Just run reproduction snippet and get runtime error.

### Expected Behavior
Don't get runtime error

### Actual Behavior
Get runtime error "TypeError: Cannot convert object to primitive value".

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVj8EOwiAQRH9lw9na6LGpTTyaePRWesBKEyICKZTEEP7dLWJtL4SdnTebaQOxY1+ejdn7iZOK1I6/jGSON1QB1L6Qwrr0T5PTWjphwBeDHk+UCNADtIcdHDtKoHry9yxSkglkfnmIWKldxXonPHOJDmBGbSzEFbAcLQSiSN2FeqA3OdF3xRVc5lUIICDGulz5/3fLTZEkWcNUc8sNFjqpuSBG5Ybf+jkah00eiTs1SZme7gPDFGlE)

_For some reason it mostly works on play.vuetifyjs.com (I reproduced the error few times), but stably fails on my machine._

### Other comments
Error occurs, when [MaybeTransition](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/composables/transition.ts#L22) receives `props.target = Proxy(Array) [ VueComponent ]` instead of HTML element from [VOverlay](https://github.com/vuetifyjs/vuetify/blob/2877ba8baa9e845994180040c370bd4cd05775ae/packages/vuetify/src/components/VOverlay/VOverlay.tsx#L319).
I don't have problems with Vue 3.4.23.

**Comment by habibalkhabbaz** [comment] 2024-05-01 18:06
Same. The issue appeared after upgrading Vue to version 3.4.24 (and above).
Downgrading to 3.4.23 solves the issue for now.

![image](https://github.com/vuetifyjs/vuetify/assets/31035020/c29b9670-1524-4474-a9b3-2b984740f59a)

https://play.vuetifyjs.com/#eNqdVE2PmzAQ/SsjethWwomSTT8UZSP10EOlHnvb7MGAs7VibMseSLeI/94xBrKwiSrVJzzz5s3XM49N4l2+/Grtoq5Esk12KEqrOIr9QQPsaoY88+EToGalKYR6OCRkOyTRmBtlHJkyVQn27MQLK7g7Cc02A+LZmXOPFRqFYzxHWYto8r/MmXFHkC5Jl3RIC9uaEyuRrw5J7+l8MjcaPHKH+7KQLDPmVFLS3TK6RuhP4lj1jOQjyhv86//nX7/l7789XfoZnqUuzHk+wEsx0c8kzX7adGyBhkyD09gxv8L+g2DWlZIex/toiTE1O3ZblGCO8LhKYZ3CfQqbFD6m8CmFzyl8eToksD2JlwB7xRzODyKC74GoaUBC28bOx1SDpuAdt1boYhIc12GMQmlBmZyjNDooyiCacpZpThekxLGrvQHrjPXQXgnpcmQ4qWo4YaUUHjbN89xUGpkoJA7ynZ6aO8k1hhWK3zcwXv4J4/clV+oGC8toYYTpKr6G2YdVU8Fvm19OHujE5S3Xe/hGxROsu8zmHIQZBz3xXOUM4FEgFx311kF6VwR5sdF1Qk1XnztpEbzAKtYgS2scQgNOHKGFozMl3NGv6C5KiHZD0gqP9SEg3q8+BM7IQvFJmyb3i81ivUlSXSn19BecaWbb

And as mentioned by @toughlex-donatas - I don't know why it is not always reproduceable on VPlay however on our local machines or when we run `npm run prod`, the issue is always there

**Comment by jmeij** [comment] 2024-05-23 07:20
Had this issue also. Removing my node_modules locally and running npm ci after fixed it for me.

**Comment by KaelWD** [comment] 2024-07-27 06:29
Duplicate of #19685

**Closed by KaelWD** 2024-07-27 06:29 UTC
Labels: S: triage
