### ISSUE TITLE
how to listen user input on v-select which can search

### ISSUE THREAD

**Issue by miyalee** [vuetifyjs/vuetify#888] opened 2017-07-05 05:10 UTC
https://vuetifyjs.com/components/selects
in this components, '#5 Scoped slots', what i want to do is listen what user has input, and then use the text to search datas with ajax, the points is the data is on server

can anyone help me ಥ_ಥ? 3q!

**Comment by nekosaur** [comment] 2017-07-05 07:03
Duplicate of https://github.com/vuetifyjs/vuetify/issues/879

**Closed by nekosaur** 2017-07-05 07:03 UTC
Labels: duplicate
