### ISSUE TITLE
[Bug Report] v-tab in v-menus can't show active underline rightly

### ISSUE THREAD

**Issue by LoveofRedMoon** [vuetifyjs/vuetify#12008] opened 2020-08-06 11:33 UTC
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
1. click the v-text-field
2. see the v-tab active underline(white)

### Expected Behavior
the underline with show under the left tab icon

### Actual Behavior
the underline did not show rightly

### Reproduction Link
<a href="https://codepen.io/loveofredmoon/pen/OJNJKMv" target="_blank">https://codepen.io/loveofredmoon/pen/OJNJKMv</a>

### Other comments
if i give 'v-if="show"' to  v-card  (expect the tab can render with click instead of the window open)
the active underline will show high probability, but still with none underline in low case

**Comment by jacekkarczmarczyk** [comment] 2020-08-06 11:35
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4733 and others https://github.com/vuetifyjs/vuetify/issues?q=is%3Aissue+callSlider+is%3Aclosed

**Closed by jacekkarczmarczyk** 2020-08-06 11:35 UTC
Labels: triage
