### ISSUE TITLE
[Bug Report] v-select height not same as v-text-field when using dense mode

### ISSUE THREAD

**Issue by mtermoul** [vuetifyjs/vuetify#10877] opened 2020-03-18 15:30 UTC
### Environment
**Vuetify Version:** 2.2.18
**Last working version:** 1.5.24
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Mac OS 10.14.6

<img width="579" alt="Screen Shot 2020-03-18 at 11 31 05 AM" src="https://user-images.githubusercontent.com/8376035/76977730-13be8b00-690c-11ea-9e7c-35a410e3c157.png">

### Steps to reproduce
Add v-text-field next to v-select and v-autocomplete using the dense mode. You will notice that the height of these controls don't lineup perfectly. This use to work fine.

### Expected Behavior
When adding multiple input controls they should all have the same height.

### Actual Behavior
The v-select does not have the same height as the text-field

### Reproduction Link
<a href="https://codepen.io/mtermoul/pen/xxGzWRj" target="_blank">https://codepen.io/mtermoul/pen/xxGzWRj</a>

**Comment by ElijahKotyluk** [comment] 2020-03-18 21:13
Duplicate of #10694

**Comment by amoliski** [comment] 2020-03-18 22:01
The desired outcome is for the text field to be slightly less dense to match select/autocomplete, and not the other way around, correct?

**Comment by ElijahKotyluk** [comment] 2020-03-18 22:10
That was my initial thought, I was checking into it and it has to do with padding being altered on the text field due to a class when dense is present. 
<img width="1336" alt="Screen Shot 2020-03-18 at 12 30 58 PM" src="https://user-images.githubusercontent.com/24883328/77012026-5e4f0000-692a-11ea-8c79-74db53c2ea86.png">

**Comment by MajesticPotatoe** [comment] 2020-03-18 22:10
They should be the same height. Looks like text-field is coming in as 26px, where the select/combo/auto is coming in at 32px. In last version (2.2.17) the difference was less noticeable (only about 2 px off)

**Closed** 2020-03-24 18:58 UTC
Labels: C: VSelect, S: has PR, T: bug

**Comment by viniciushvc** [comment] 2020-04-29 20:46
But now, chips has no padding:
![Padding bug](https://user-images.githubusercontent.com/16567830/80645175-22d34580-8a41-11ea-8a70-615d6a4ec371.jpg)

**Comment by jacekkarczmarczyk** [comment] 2020-04-29 21:44
@viniciushvc Please create a new issue and provide reproduction.Thank you!

**Comment by flaviotsales** [comment] 2020-04-30 00:47
Should the chips be smaller or the dense height bigger?

**Comment by viniciushvc** [comment] 2020-04-30 20:05
chips smaller, if height bigger, can cause this issue problem again
