### ISSUE TITLE
[Bug Report][2.5.8] V-form submits form on keypress enter when only one input element is present but not more

### ISSUE THREAD

**Issue by magic-cal** [vuetifyjs/vuetify#14146] opened 2021-09-10 14:30 UTC
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 92.0.4515.159, Google Chrome
**OS:** Windows 10

### Steps to reproduce
Make a v-form with one input text element. On focus and pressing enter of this form, the page will reload. This is not the case for two or more elements in the form (See Reproduction for example)

### Expected Behavior
The page should not submit or reload

### Actual Behavior
The page submits the form and reloads 

### Reproduction Link
<a href="https://codepen.io/CJMC1/pen/abwWzwa" target="_blank">https://codepen.io/CJMC1/pen/abwWzwa</a>

**Comment by KaelWD** [comment] 2021-09-10 14:33
Duplicate of #2159

**Closed by KaelWD** 2021-09-10 14:33 UTC
Labels: S: triage
