### ISSUE TITLE
TS2322: Type 'true' is not assignable to type 'false'

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#17233] opened 2023-04-26 17:49 UTC
"eslint": "8.39.0",
    "eslint-plugin-vue": "9.11.0",
    "vue": "3.2.47",
    "vuetify": "3.1.15"

After upgrading to the latest Vue3 I am now getting lint errors for return-object.

Ex: `<v-select  ... return-object />` gives me "TS2322: Type 'true' is not assignable to type 'false'"

**Comment by KaelWD** [comment] 2023-04-26 17:50
Duplicate of #17211

**Closed by KaelWD** 2023-04-26 17:50 UTC
Labels: S: triage
