### ISSUE TITLE
[Bug Report] <v-data-iterator> does not set a key on the repeated items

### ISSUE THREAD

**Issue by arielnmz** [vuetifyjs/vuetify#6494] opened 2019-02-13 23:15 UTC
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Chrome 70.0.3538.110
**OS:** Linux x86_64

### Steps to reproduce
Create custom component that loads its state on the mounted stage
Make v-data-iterator repeat it
Mutate the data source (delete an item, reorder, etc)

### Expected Behavior
The repeated component is assigned a key and its data remains consistent

### Actual Behavior
One of the repeated components gets discarded and the props get shifted, but since the internal state is assigned at mount-time, data becomes inconsistent

### Reproduction Link
<a href="https://codepen.io/anon/pen/YBjmxJ?editors=1010" target="_blank">https://codepen.io/anon/pen/YBjmxJ?editors=1010</a>

### Other comments
The expected behaviour occurs when a key is passed to the repeated component e.g. <my-comp ... :key="props.item.id"/> (isn't this what the item-key prop is for?)

**Comment by jacekkarczmarczyk** [comment] 2019-02-15 02:29
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6296

**Closed by jacekkarczmarczyk** 2019-02-15 02:29 UTC
