### ISSUE TITLE
[Bug Report] v-treeview does not return the value of the selected parents

### ISSUE THREAD

**Issue by Rasool-deldar** [vuetifyjs/vuetify#13401] opened 2021-04-10 08:48 UTC
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.6
**Browsers:** Chrome 89.0.4389.114
**OS:** Windows 10

### Steps to reproduce
I have 41 slaves with my children, but I realized that when I select all the categories, 34 items are selected. The problem is that the parents category does not select (only the child categories select). Does anyone know how to solve this problem? ?

![image](https://user-images.githubusercontent.com/58503211/114264309-4d72a000-99ff-11eb-89c8-7b270ef0ce4d.png)

### Expected Behavior
Root
Child #1
Child #2
Child #3
    ->Grandchild #1
Grandchild #1
Grandchild #2

### Actual Behavior
Child #1
Child #2 
Grandchild #1
Grandchild #1
Grandchild #2

### Reproduction Link
<a href="https://codesandbox.io/s/relaxed-gareth-v3fy5?file=/pages/index.vue" target="_blank">https://codesandbox.io/s/relaxed-gareth-v3fy5?file=/pages/index.vue</a>

Problem with selection-type When leaf-independent I use these items, it works properly, but in the browser console it gives the following error

For example

selection-type="all"

![image](https://user-images.githubusercontent.com/58503211/114265581-d0e3bf80-9a06-11eb-9592-07e4b6cad131.png)

Please either help me solve the problem or fix the error

**Comment by David-Crty** [comment] 2021-07-19 17:31
I have the same issue, even if the comment is not very nice, the solution from https://stackoverflow.com/questions/60776489/vuetify-tree-view-get-parent-node-along-with-the-children-node/66187402#66187402 worked for me (at least when you have one node).
With multiple nodes checked I have some inconsistency with the v-model value and warning are spamed in the console

Can we think of a new selection-type ? Including parent in the v-model value when all children are checked ?

**Comment by johnleider** [comment] 2021-07-28 23:29
Possible duplicate of #8791

**Closed** 2023-09-20 19:33 UTC
Labels: T: bug, C: VTreeview
