### ISSUE TITLE
[Bug Report] v-text-field can't be focused if v-bottom-sheet is active when persistent on

### ISSUE THREAD

**Issue by godszerg86** [vuetifyjs/vuetify#7209] opened 2019-05-14 15:27 UTC
### Versions and Environment
**Vuetify:** 1.5.13
**Last working version:** 1.4.2
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.131
**OS:** Windows 10

### Steps to reproduce
1. click on the button to pop up the bottom sheet
2. try to edit the text in the input field

### Expected Behavior
input should receive focus and able to edit the text inside

### Actual Behavior
input doesn't receive focus and not able to edit text

### Reproduction Link
<a href="https://codepen.io/sbelialov/pen/BeQMgB?&editable=true&editors=101" target="_blank">https://codepen.io/sbelialov/pen/BeQMgB?&editable=true&editors=101</a>

**Comment by pecet86** [comment] 2019-05-28 15:01
the last working version is 1.5.7

**Comment by pecet86** [comment] 2019-05-28 15:31
After a short analysis, the problem is the "onFocusin" method from the "VDialog" class.
Forces the acquisition of focus always as open "v-dialog" / "v-bottom-sheet" .

Link: \packages\vuetify\src\components\VDialog\VDialog.js

```
onFocusin (e) {
      const { target } = event

      if (
        // It isn't the document or the dialog body
        ![document, this.$refs.content].includes(target) &&
        // It isn't inside the dialog body
        !this.$refs.content.contains(target) &&
        // We're the topmost dialog
        this.activeZIndex >= this.getMaxZIndex() &&
        // It isn't inside a dependent element (like a menu)
        !this.getOpenDependentElements().some(el => el.contains(target))
        // So we must have focused something outside the dialog and its children
      ) {
        // Find and focus the first available element inside the dialog
        const focusable = this.$refs.content.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])')
        focusable.length && focusable[0].focus()
      }
    },
```

**Comment by kwindo** [comment] 2019-06-22 11:30
Hi guys,

Am I right assuming the bug fix on VDialog in v1.5.16 was not to fix this issue?
https://github.com/vuetifyjs/vuetify/releases/v1.5.16

The issue's still there and I'm not 100% sure it's supposed to.

**Comment by kwindo** [comment] 2019-07-02 09:04
Hi guys,

Any news on this? I'm holding off an update for an otherwise finished new feature. Maybe there's a work around (that does not mean hiding the sheet on any page with an input field) or a temporary fix I could use?

**Comment by KaelWD** [comment] 2019-07-02 09:29
Duplicate of #6892

**Closed by KaelWD** 2019-07-02 09:29 UTC
Labels: duplicate

**Comment by pecet86** [comment] 2019-07-03 09:33
@kwindo 
I apologize for the delay but holiday, just test and edit the comment

**Comment by kwindo** [comment] 2019-08-18 08:08
Hi @pecet86, could it be the version 2.0.7 still does not fix this issue. I updated the pen https://codepen.io/kimsanka/pen/MdVvWX

I'm sorry if I posted this question in the wrong thread. I've gotten all confused by the duplicates and don't really understand how the post this is supposed to be a duplicate from is related to this issue. Anyhow, that post is also closed but the issue remains, it seems.
