### ISSUE TITLE
[Bug Report] vuetify selects only showing first 20 items from the list, If we set hide-selected=true

### ISSUE THREAD

**Issue by PRAJINPRAKASH** [vuetifyjs/vuetify#10750] opened 2020-03-05 15:27 UTC
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
[vuetify selects][1] only showing first 20 items from the list if we set hide-selected=true,

      <v-select
            v-bind:items="test_data"
            v-model="test_modal"
            label="Reader permissions"
            multiple
            chips
            deletable-chips
            :counter="test_data.length"
             hide-selected

      ></v-select>

see complete code on [codepen here][2]

  [1]: https://vuetifyjs.com/en/components/selects
  [2]: https://codepen.io/prajin/pen/dyoVebj

### Expected Behavior
only hide selected items

### Actual Behavior
hide all items if more than 20

### Reproduction Link
<a href="https://codepen.io/prajin/pen/dyoVebj" target="_blank">https://codepen.io/prajin/pen/dyoVebj</a>

**Comment by johnleider** [comment] 2020-03-11 17:39
Duplicate of #2660 unfortunately. We can probably remove that number at this point, this just got swept under the rug. Thank you for your patience.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-03-11 17:39 UTC
Labels: triage
