### ISSUE TITLE
[Feature Request] Add resize API to v-form or/and v-form elements (input, checkbox, etc.)

### ISSUE THREAD

**Issue by Hellek** [vuetifyjs/vuetify#3666] opened 2018-03-25 14:19 UTC
### Problem to solve
Each UI component must perform its function well, the actual styles are good at the task when we are talking about a small number of forms or when there are few elements in one form.

We found a problem in one of our projects. Our task was to create a dashboard wuth 5-6 forms should be placed on one page, and in each form contains from 5 to 30 input fields. All this does not fit in the visible part of the screen, and users have to constantly scroll page, down and up, down and up.

### Proposed solution
As a solution, I propose to add an API changing the size of the form elements. Changes can be applied to all elements of the form, and to each individually. For example, this can be a coefficient that changes the standard sizes through the calc(), for example :size="0.5" will decrease the height, padding, margin of the elements for 2 times.
Here i found and example of input sizing https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/bootstrap-components/forms/#sizing

**Comment by KaelWD** [comment] 2018-03-25 15:00
Duplicate of #1846

**Closed by KaelWD** 2018-03-25 15:00 UTC
