### ISSUE TITLE
[Bug Report] v-autocomplete value does not clear when the v-model is cleared out (set to null)

### ISSUE THREAD

**Issue by mtermoul** [vuetifyjs/vuetify#10765] opened 2020-03-06 15:36 UTC
### Environment
**Vuetify Version:** 2.2.15
**Last working version:** 2.2.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Mac OS 10.14.6

### Steps to reproduce
- add v-autocomplete with v-model="event"
- add button to clear the event variable using @click="event=null"
- select a value from the autocomplete component
- check the value of event variable, it should be equal to selected value.
- hit the clear button
- the event variable value will be cleared, but the autocomplete will still show the previously selected value

### Expected Behavior
when we use v-model on v-autocomplete we should clear the value of the autocomplete whenever the v-model variable is cleared out

### Actual Behavior
The selected value does not clear out

### Reproduction Link
<a href="https://codepen.io/mtermoul/pen/OJVxePv" target="_blank">https://codepen.io/mtermoul/pen/OJVxePv</a>

### Other comments
The same issue with v-combobox

**Comment by Leespiker** [comment] 2020-03-08 06:35
@mtermoul The reproduction link shows the clear button working properly for me.

**Comment by jacekkarczmarczyk** [comment] 2020-03-08 06:37
It uses 2.2.14
@mtermoul please add 2.2.15 codepen as well

**Comment by Leespiker** [comment] 2020-03-08 06:49
@jacekkarczmarczyk You're right. It seems to be broken for 2.2.15. See: https://codepen.io/Leespiker/pen/RwPjegW

**Comment by mtermoul** [comment] 2020-03-08 20:19
Sorry @jacekkarczmarczyk . Here is the link to the latest codepen that is using Vuetify 2.2.15 https://codepen.io/mtermoul/pen/OJVxePv

**Comment by Leespiker** [comment] 2020-03-08 22:19
@mtermoul An easy workaround while we look into the problem is to add a `key` to the autocomplete and combobox components. i.e. `:key="event"` See: https://codepen.io/Leespiker/pen/MWwOdNz

**Comment by cyyssly** [comment] 2020-03-09 03:09
@Leespiker It really works, thanks! I encountered the same problem and wasted hours try to fix it, until found the answer here. But I still think it's a bug need to be fixed.

**Comment by harsha1926** [comment] 2020-03-10 19:15
Work around is not working when we use "search-input.sync" attribute

**Comment by johnleider** [comment] 2020-03-11 16:40
Duplicate of #10688

**Closed by johnleider** 2020-03-11 16:40 UTC
Labels: C: VAutocomplete, triage

**Comment by Gefyaqiilah** [comment] 2021-07-06 06:50
> @mtermoul An easy workaround while we look into the problem is to add a `key` to the autocomplete and combobox components. i.e. `:key="event"` See: https://codepen.io/Leespiker/pen/MWwOdNz

it really works! thank you...

**Comment by vaka99** [comment] 2021-11-28 06:25
Alternatively,  you can press ESC .
