### ISSUE TITLE
[Feature Request] Overwriting Heading variables

### ISSUE THREAD

**Issue by ottz0** [vuetifyjs/vuetify#10546] opened 2020-02-12 06:51 UTC
### Problem to solve
I am trying to overwrite the Vuetify Heading variables. I am using the variables.scss file in the scss folder as per setup and this works correctly as I can update $border-radius-root and $card-elevation variables in which it updates.

Iv'e looked at the vuetify SASS docs and have put the following in my variables doc

$headings: (
  'h1': (
    'size': 8.3125rem,
    'line-height': 1.15em
  )
)

However it doe not update.

What are the steps and process to update and overwrite the $headings variables for H1,H2,body-1 etc as I have tried every approach.

### Proposed solution
Documentation on how to update and overwrite heading variables

**Comment by Tarabass** [comment] 2020-02-13 11:19
Are you also defining the style onto a h1 like this?

```css
h1 {
  font-size: map-deep-get($headings, 'h1', 'size');
  line-height: map-deep-get($headings, 'h1', 'line-height');
}
```

**Comment by ottz0** [comment] 2020-02-14 02:26
$headings: () !default;
h1 {
  font-size: map-deep-get($headings, 'h1', '80');
  line-height: map-deep-get($headings, 'h1', '25');
}

I get a compilation error saying $headings isn't a valid css value

**Comment by Tarabass** [comment] 2020-02-14 11:04
First you declare a sass variable with all your desired values. Then you use that sass variable (object) to set your styling using [map-deep-get](https://sass-lang.com/documentation/values/maps), which is just sass..

This should work:
```
$headings: (
  'h1': (
    'size': 6rem,
    'line-height': 6rem
  ),
  'h2': (
    'size': 2.5rem,
    'line-height': 2.5rem
  )
)

h1 {
  color: map-deep-get($material-light, 'text', 'primary');
  font-size: map-deep-get($headings, 'h1', 'size');
  line-height: map-deep-get($headings, 'h1', 'line-height');
}

h2 {
  color: map-deep-get($material-light, 'text', 'secondary');
  font-size: map-deep-get($headings, 'h2', 'size');
  line-height: map-deep-get($headings, 'h2', 'line-height');
}
```

**Comment by KaelWD** [comment] 2020-02-14 11:05
Duplicate of #9306

**Closed by KaelWD** 2020-02-14 11:05 UTC
Labels: triage
