### ISSUE TITLE
[Bug Report] Vuetify does not work in web component

### ISSUE THREAD

**Issue by albertodiazdorado** [vuetifyjs/vuetify#11752] opened 2020-06-29 15:38 UTC
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Firefox 77.0
**OS:** Linux x86_64

### Steps to reproduce
1. Clone the repo
2. Install dependencies (`yarn install`)
3. Build the web component (`yarn run build-inline`)
4. Open the `demo.html` with the web component (`yarn test`)

### Expected Behavior
The vuetify elements in the web components work correctly

### Actual Behavior
The vuetify elements in the web component do not work 100% right (more in the README of the repository)

### Reproduction Link
<a href="https://github.com/albertodiazdorado/vuetify_web-component" target="_blank">https://github.com/albertodiazdorado/vuetify_web-component</a>

### Other comments
I _do not know_ if this is a bug or I am just not building the web component correctly. The interface to submit an issue is so restrictive that I cannot do much about it.

Is it a bug? Am I doing it wrong? That is what I would like to know!

**Comment by KaelWD** [comment] 2020-06-29 16:08
Duplicate of #7622

**Closed by KaelWD** 2020-06-29 16:08 UTC
Labels: triage
