### ISSUE TITLE
[Bug Report] v-select change events change when using autocomplete

### ISSUE THREAD

**Issue by iamianmiller** [vuetifyjs/vuetify#3796] opened 2018-04-06 20:54 UTC
### Versions and Environment
**Vuetify:** 1.0.13
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
1. Click the select and click on item from the list.  The value of the event should be a list of objects.
2. Type some automcomplete text.
3. Click the select and click on another item from the list.   A bunch of errors appear, and the value that is logged is an Event object.

### Expected Behavior
Not sure?  It should be consistently an event, or consistently a value though.  I think an event is expected.

### Actual Behavior
Some cases the change event value is the value of the event, other times its an event object.

### Reproduction Link
[https://codepen.io/ianmiller/pen/yKQerO](https://codepen.io/ianmiller/pen/yKQerO)

**Comment by KaelWD** [comment] 2018-04-07 01:02
Duplicate of #3463

**Closed by KaelWD** 2018-04-07 01:02 UTC
