### ISSUE TITLE
[Bug Report][3.1.8] Dropdown inside Dialog not showing correctly in first click

### ISSUE THREAD

**Issue by adamskeeled** [vuetifyjs/vuetify#16868] opened 2023-03-09 09:52 UTC
### Environment
**Vuetify Version:** 3.1.8
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Create VDialog
2. Add VSelect or VAutocomplete with items inside the Dialog
3. Open Dialog and click on the dropdowns

### Expected Behavior
The items appear in the correct spot on the first click

### Actual Behavior
On the first click the dropdown is rendered somewhere off-screen. When clicking the dropdown a second time, the dropdown appears correctly.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrNVs1y2jAQfhWNL7QpxkBIkzIkkzQ9NKd2mun0EHIQ9gIKsqRKMmmG4d27kn+wDWnaU8NJ2t9vP++uuNsEV0r11hkE42BiIVWcWriYCkIm65Aq5Y/+klImipu/a/lIHjJj2fzpfBrEICzoabCzTxjlclE6oL9MgKNlIQ9KjQJtmLHoX0oeWWKXaDnoD0el3S5zCRJDGi7tmMaWramVGj02RGmpDNlWQAowMyt2d0Jiyb290iyl+mkHJoc6YyLxWozV1OXenBqD+tSGg35dX8tJyBcFgnxqkIBQIo9lV03U4LxAG1OdNPE7SWiZ5Ts7rzGKigqPhV82XJ5g7d8NaPJVyznjMImcUT0cYjgYr8qDcZppUCGFxQYA3VCUjdASFh58jzlHvEM6GB6glZgUVe/3NXvRfXwDHOKqZ+q/MUNSXZq7Tj8cnHa6pDM4C4cf3OG4H56M3OFk9K5zfwgFIZzOfKdeLeDosIWGnxnTkOzrLhy7ObR9Uhzxkv8PsmhmZSyx08DCC5TdrhgTC0fRTQxkKeMVPLnbrYxj0O70kZoV2Bnl3N0+VxbfgCaF6w/NbHG8lqUQ/eAhS9VLvN+4VQLGHpo9/KUZtwwreYb8eql/+QmctN3FueWhpp+YFEu/OMIlwWKcXFO1A5kz4AkOnDc4NHHNySoHzq0wKUx75nBukfG8o/Jjy6C11XZ7bcYzCBOqVyDCQZvFNdWMClssjLb2MuYsXlV7mpyTOeUGmmYt/q65RIsWefU198rw3tL1C3CrL9b+NKWifOfwmifO38xGI7lb9Wr61vTvaWPn49XEmilLDNjMqVmqpLZkg101J1sy1zIlHXygO84YO9JYUpWKJm98uW9d2DwQhgi6QR4F06veg5ECX/eNQzEtFDhaY+IlTobR3X0aLK1VZhxFmVCrRQ+nKLpEXaQzYVmKX0iml8e9YW90GiX4ZNflPTBpOMPa8eXBjNOgWwvu/iM8l6BQY9xB7ywPW4hC3AfGxd2LF2GSNehQg0hwU+Dfjj+Ab9k2Cmjp9opwObdTsUVCORMr0+IyNp7HuxLav1fnIzj3e5dl2w1ydJjPewT3vwGzF68L)

### Other comments
I couldn't reproduce the issue on the playground, but the issue it currently present in the Vuetify docs:
https://vuetifyjs.com/en/components/dialogs/#form

Open the Form Dialog and try clicking one of the dropdowns

**Comment by whttigress** [comment] 2023-03-09 20:57
I have had this same issue, I have had the dropdowns appear normally sometimes, and sometimes they are either off the screen, or I have also had the menu start at the bottom of the dialog (not near the select).  So far, I have not been able to determine why it behaves differently in a way that I have been able to duplicate in the playground

**Comment by qxygene** [comment] 2023-03-12 00:42
any fix abıut this issue?

**Comment by KaelWD** [comment] 2023-03-12 07:27
Duplicate of #16770

**Closed by KaelWD** 2023-03-12 07:27 UTC
Labels: S: triage
