### ISSUE TITLE
v-select with autocomplete styling issue with long content

### ISSUE THREAD

**Issue by pierredup** [vuetifyjs/vuetify#1982] opened 2017-10-02 14:36 UTC
When using a `v-select` with autocomplete, if you have an item that spans more than 1 line, then there is an extra blank line underneath the selected value. This doesn't happen with normal dropdowns

### Steps to reproduce
Create a v-select with autocomplete set and an item with text that spans multiple lines

### Versions
vue@2.4.4
vuetify@0.15.7

### What is expected ?
The selected value should be inline with the dropdown arrow and the border directly underneath it

### What is actually happening ?
There is an extra blank line underneath the selected value

### Reproduction Link
https://codepen.io/pierredup/pen/WZEWXM

### Screenshot

<img width="1662" alt="screen shot 2017-10-02 at 16 28 57" src="https://user-images.githubusercontent.com/144858/31082592-b9084650-a78f-11e7-991c-30c5479ef021.png">

**Comment by KaelWD** [comment] 2017-10-02 14:44
Duplicate of #1691

**Closed by KaelWD** 2017-10-02 14:44 UTC
