### ISSUE TITLE
[Feature Request] Allow Customization of VVirtualScroll in VSelect

### ISSUE THREAD

**Issue by khamasaki** [vuetifyjs/vuetify#18373] opened 2023-09-30 02:12 UTC
### Problem to solve
We have a VSelect where we make the list items in the menu smaller. This makes the menu behave erratically because the VVirtualScroll is miscalculating the display window.

You can see the problem here: https://play.vuetifyjs.com/#eNp90ztvgzAQB/CvcvJCK5GgNlmKkkrpM30/1iQDJU5wa8C1DQviu9fgtjkx3GTf3z8dx3CrhhmdRgulxnXFWcxmludKJpafrwuAWT1KlOqvfZGWhU1EwfVv1IeGS55aqEd5ueVyvmY+4Ns1g1i4fsZl/emC6K9ZNOzWJf5jswgN4UqTaqEsGG4rP4vIVaktNKD5DlrY6TKHwM0fdBzA9TUd91PAvGNHRSXlMX5XulTGPTaQcbHPbAyn0xByUSz/S2gPvP8Bx1d+/gassJLHECyCEOpEVt09cXfftw2H7gK5D8JdIpcS7gq5LeGukeOEu0FuR7hb5PaEWyKXEe4OOUG4e+Q+CfeA3BfhHpGThHtCLifcM3IF4V6QKwn3ipwi3Bty34R7R04P3KZbOr9mbsFYG7LJeDKeMn+enLHND2j6Q/A=

Try selecting the letter 'K', then closing the menu, then opening it again and scrolling around the menu.

### Proposed solution
If the VSelect would allow specifying properties for the underlying VVirtualScroll, as it does with menu-props for the underlying VMenu, we could specify the item height for the VVirtualScroll to use.

**Comment by KaelWD** [comment] 2023-10-05 11:32
Duplicate of #17801

**Closed by KaelWD** 2023-10-05 11:32 UTC
Labels: S: triage
