### ISSUE TITLE
DataTable should have a prop for changing text "Rows per page"

### ISSUE THREAD

**Issue by KaRkY** [vuetifyjs/vuetify#356] opened 2017-04-13 11:55 UTC
### Versions

v0.10.4

### What is expected ?

Text property on DataTable for changing text "Rows per page"

### What is actually happening ?

Text is fixed and can not be changed.

### Reproduction Link

Third example.
https://vuetifyjs.com/components/datatables

**Comment by johnleider** [comment] 2017-04-13 13:19
Duplicate of #340

**Comment by KaRkY** [comment] 2017-04-13 14:10
Why duplicate i am talking about changing text Rows per page to something like Products per page?

**Comment by johnleider** [comment] 2017-04-13 16:15
My mistake.

**Closed** 2017-04-14 00:39 UTC
Labels: enhancement
