### ISSUE TITLE
[Bug Report] Incorrect styling with v-select solo, multiple, and attach props

### ISSUE THREAD

**Issue by GreenLoofa** [vuetifyjs/vuetify#5697] opened 2018-11-21 16:51 UTC
### Versions and Environment
**Vuetify:** 1.3.9
**Vue:** 2.5.17
**Browsers:** Firefox 63.0
**OS:** Mac OS 10.13

### Steps to reproduce
Click and open the v-select with the solo, multiple, and attach props present

### Expected Behavior
The checkboxes fall in line with the other text in the dropdown

### Actual Behavior
The checkboxes in the dropdown appear to take a different styling

### Reproduction Link
<a href="https://codepen.io/anon/pen/xQYRQy?&editors=101" target="_blank">https://codepen.io/anon/pen/xQYRQy?&editors=101</a>

**Comment by jacekkarczmarczyk** [comment] 2018-11-21 16:53
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5508

**Closed by jacekkarczmarczyk** 2018-11-21 16:53 UTC
