### ISSUE TITLE
[Bug Report] Performance issues in v2

### ISSUE THREAD

**Issue by magyarb** [vuetifyjs/vuetify#8298] opened 2019-08-04 21:43 UTC
### Environment
**Vuetify Version:** 2.0.4
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Just expand the panel.

### Expected Behavior
The expansion of the panel should happen faster, as in v1.5.

### Actual Behavior
The frame rate is 12 fps in v2.0, and 58fps in v1.5.

### Reproduction Link
<a href="https://codepen.io/anon/pen/eqezvV" target="_blank">https://codepen.io/anon/pen/eqezvV</a>

### Other comments
Test results: https://photos.app.goo.gl/G4vKnVHMPb8D3DDz7

And it's not just the expansion panels. The whole app is visibly slower after updating to v2.

**Comment by KaelWD** [comment] 2019-08-05 00:09
Possibly caused by bee69fe20c0e1811e1902116095eaffda93d0b8b, some DOM access was reordered.

**Comment by sh7dm** [comment] 2019-08-05 11:31
40 FPS when opening/closing (GT 720M, i3-3110M)

**Comment by KaelWD** [comment] 2019-10-25 12:37
This is actually due to the more complex animation, which now includes a border-radius change on adjacent panels too. The `accordion` style has very similar performance to the v1.5 design.

**Closed by KaelWD** 2019-10-25 12:37 UTC
Labels: C: VExpansionPanel, T: bug, performance

**Comment by nanolink** [comment] 2021-04-14 09:55
Actually I suspect that this is an old issue with webview css transitions not being hw accellerated. 
The trick can possibly be very simply, just by adding -webkit-transform: translate3d(0, 0, 0); to the initial style, and hardware accelleration will activate. I am not sure if it will work, but it's worth a try: (you would see some improvement in Google desktop as well)
https://davidwalsh.name/translate3d

**Comment by gabrieljbaker** [comment] 2022-07-09 22:09
Hi @nanolink , just finding this and I think you might be on to something here.  But which element do you add that class to?
