### ISSUE TITLE
[Bug Report][2.6.3] V-data-table group-by issue

### ISSUE THREAD

**Issue by mrl1992** [vuetifyjs/vuetify#15335] opened 2022-06-23 09:11 UTC
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.14
**Browsers:** Chrome 102.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
group-by function not grouping on id. If i remove one character from the id in each one it works, but seems like string is too long 

### Expected Behavior
id: 909062133713370002
markus
lars
id: 909062133713370004
thomas

### Actual Behavior
id: 909062133713370002
markus
id: 909062133713370004
thomas
id: 909062133713370002
lars

### Reproduction Link
<a href="https://codepen.io/markusrl/pen/xxYoMPQ?editors=1010" target="_blank">https://codepen.io/markusrl/pen/xxYoMPQ?editors=1010</a>

### Other comments
please help and have a nice day :)

**Comment by KaelWD** [comment] 2022-06-23 09:13
Duplicate of #11349

**Closed by KaelWD** 2022-06-23 09:13 UTC
Labels: S: triage
