### ISSUE TITLE
[Feature Request] manual or reactive trigger of v-text-field rules' validation

### ISSUE THREAD

**Issue by scscgit** [vuetifyjs/vuetify#12768] opened 2020-12-11 14:30 UTC
### Problem to solve
When using `rules` in `v-text-field`, ["When the input value changes, each element in the array will be validated."](https://vuetifyjs.com/en/components/text-fields/#validation) Based on this definition, the validation event occurs only for the specific v-text-field that changes, without an option to trigger it manually; not even by clicking on the input. As a basic use-case, this may be necessary whenever validation conditions depend on any state of other inputs.

#### Repro steps on Vuetify v2.3.21: https://codepen.io/cTAlENtATI/pen/WNGoyvq
```vue
<v-text-field v-model="email1" :rules="[rules.email1]" />
<v-text-field v-model="email2" :rules="[rules.email2]" />
```
```js
rules: {
  email1: value => value !== this.email2 || 'E-mails must differ.',
  email2: value => value !== this.email1 || 'E-mails must differ.',
},
```

1. The validation doesn't initially occur until clicking on the input.
1. When changing one of the values, the error [dis]appears only on the current field, but stays displayed on the other one.
1. Unlike point 1, clicking on the other field doesn't fix the validation issue until you start to type in a new input.

### Proposed solution
At the very least, I would request for a workaround to be officially documented. As a feature suggestion, first option could be some manual trigger/prop to re-compute all validations, and a second option could be to reactively watch (in Vue-style) on the variables used in the (anonymous) rule function, so that it'll re-validate when they change (making it trivial to combine with other reactive component properties).

**Comment by MajesticPotatoe** [comment] 2020-12-11 15:01
you can trigger the validation of all fields by wrapping it in s `v-form` component w/ a ref and triggering the `validation()` function
<https://vuetifyjs.com/en/components/forms/#validation-with-submit-clear>
form validation loops through each input and calls `input.validation(true)` on it. You can perform the same concept on the individual inputs (its just not public api which is why its not documented)
here's an example [codpen](https://codepen.io/majesticpotatoe-the-bashful/pen/LYRbByv) (modified from the above example)

**Comment by scscgit** [comment] 2020-12-11 16:19
@MajesticPotatoe
Nice, I didn't have a clue about this hidden API; it would certainly be worth documenting publicly. Luckily the `v-form` seems to work even if it isn't a direct parent element (unlike countless other Vuetify components), so I was able to handle my specific use-case of emitting the values up and passing them back down by calling validate on `v-form` directly on any change. Due to [a TypeScript limitation of v-form](https://github.com/vuetifyjs/vuetify/issues/5962) (as I don't think pure JS is viable for production), the [decorator](https://github.com/kaorun343/vue-property-decorator#Ref) usage (for simplicity) can look like this:
```ts
@Ref()
readonly form!: {
  validate(): boolean
}
```
However, I needed to call the validation from a parent at the moment of passing the new input values back to its child element (as the standard Vue behavior of `v-text-field` requires prop value to be owned by a parent and synced via emit), but when I tried to watch on the parent's data property, the watch function was executed **before** the prop was passed back to the child; so the user effectively had to make **at least two changes** before this was reflected by the validation. As a workaround, I used [nextTick](https://vuejs.org/v2/api/#Vue-nextTick), so the most readable code I could come up with was this:
```ts
@Watch('inputValues')
async watchInputValues() {
  await this.$nextTick()
  this.form.validate()
}
```
Sadly, I noticed another issue, as the form validation "touches" even the previously untouched inputs, despite Vuetify's standard behavior of hiding errors by default until a first interaction, causing inconsistent UX. I couldn't find a `v-form` usage that doesn't cause this. As the Vuetify docs are quite ambiguous about practical use-cases that scale for larger projects, do you have any better examples? Thanks!

That said, I would still prefer a native reactive approach, which would include the laziness performance benefits ;)

**Comment by MajesticPotatoe** [comment] 2020-12-11 16:44
@scscgit the `v-form` functions are documented as we recommend their use however the individual mixin functions on the input components are not (as we prefer to be able to change these internally without having to wait for a major and by making them public limits us in this aspect). Unsure if they will be documented at this time given that its likely to change in v3 as we overhaul inputs and forms and we plan to do heavier documentation in v3 at least from the dev side as we go through each component.

I unfortunately don't have another example other than the form one above. The touching by `v-form` is likely due to it running the validation method each of the child inputs, but you could not use the v-form and call the individual input validations.

> but when I tried to watch on the parent's data property, the watch function was executed before the prop was passed back to the child

you could try `@input` (or `@change`/`@blur` if you don't want it per typed character) on the text field -> emit event to parent to run validation, or run it in the child

**Comment by scscgit** [comment] 2020-12-11 19:02
@MajesticPotatoe
Of course, making the API public would mean having to deprecate it before any breaking changes, it's just a matter of deciding if there is any other official way to handle a similar use-case, or if the use-case shouldn't be supported. (If the project is transitioning towards v3 and causing breaking changes anyway, maybe this would be a good opportunity to expose more similar internal APIs for v2 LTS users before stopping its development, and you can reconsider the v3 API to remove it again. Many of us won't ever find a functionality if it isn't in the docs.)

I'd prefer to avoid having to build any basic functionality on unstable API if possible, and as far as I see, this situation (of a reactive validation dependency) doesn't seem to be covered by `v-form`. Alternatively, maybe it would make sense to add an overload to VForm's validate, like `validate(onlyTouched: boolean): boolean`? (I still can't find how the touch is named in the docs, as there isn't really even a way to control this behavior.) I'm looking forward to what v3 API will look like, hopefully we'll have more control and it'll be easier to do workarounds on our own :) And by the way, as I'm also still just figuring out how a similar architecture could be made props: is it intentional to have to use $ref to call function despite it being against Vue principles? (At the very least, being able to read&write the validation state could let me exclude the touched fields manually, but the complexity would be definitely way higher.)

And about my `@Watch` workaround, you probably misunderstood what I meant - the issue was caused due to component hierarchy, by a parent (containing `v-form`) triggering validation on one field before the prop value of another field was completely propagated back to it (as a prop, after $emit but before having the value written back to the referenced variable), as the validate rule function was located in a child component, so it read an old variable and returned a stale result (e.g. 'a' !== 'a', then 'aa' === 'a', then 'aaa' !== 'a'). This wasn't impacted by the choice of `@input`/`@change`, but disappeared after a `nextTick` workaround. It should just serve as an illustration of how non-intuitive a solution may be, and maybe it'll help someone who has a same use-case, but it's one of reasons why it'd be preferable to have reactivity supported natively. (I could imagine something like `invalidateValidations()` to call it asynchronously instead of immediately; but that would bloat the API too much, so having a `nextTick` example documented would be more than enough to validate during inter-dependent events.)

**Comment by MajesticPotatoe** [comment] 2020-12-11 19:20
> And about my @Watch workaround, you probably misunderstood what I meant

Most likely. My exposure to forms/inputs outside of the basic functions are rather limited (very simple forms with simple validation needs). If you have the time, I would welcome a codepen reproduction that illustrates this for a clearer picture of what you are requesting, and can consider adding it to the docs.

This will likely be visited and dispositioned further when we begin to look at inputs/forms for v3 which I believe is Phase 2.

**Comment by KaelWD** [comment] 2021-06-23 10:10
Duplicate of #8698 and maybe #3530

**Closed by KaelWD** 2021-06-23 10:10 UTC
Labels: C: VTextField, S: triage, T: feature

**Comment by scscgit** [comment] 2021-06-24 19:31
Note regarding duplicate issues:
* they don't cover the scenario of reactive triggering (native to Vue) when a variable dependency (of a rule) referenced in the function changes
* #8698 probably only requires documenting the API for individual inputs
* #3530 (together with the previous issue) lacks the opposite scenario where we want to avoid 'untouched' inputs also immediately displaying their validation errors, as this side effect always occurs once we start to use the `validate()` workaround

Also about the last `nextTick()`-workaround-requiring issue that I had described (which is caused by Vue, but could be worth addressing if we have to use workarounds), I apologize that I wasn't able to find time to properly analyze the root cause; but for anyone interested, here is my **work-in-progress** codepen where I was debugging how the issue only occurs between different email pairs: https://codepen.io/cTAlENtATI/pen/dypNbze

**Comment by rotsee** [comment] 2024-09-30 08:23
What am I missing here? My `$ref``'s do not seem to have a method called `validate()`?

```
<v-text-field
  v-model="title"
  ref="chartTitle"
  :rules="[validateTitle]"
/>
<v-switch
  v-model="enableSpecialTitleParsing"
  @change="$refs.chartTitle.validate()"
/>
```

In this example, I would have assumed that the text field would be revalidated on flicking the switch, but that does not seem to work.
