### ISSUE TITLE
[Feature Request] Closing v-dialog by browser's "back" btn

### ISSUE THREAD

**Issue by gileneusz** [vuetifyjs/vuetify#5324] opened 2018-10-14 11:27 UTC
### Problem to solve
I've got multiple dialogs in my application. On mobile environment users tend to click "back" button when they want to close dialog. Very bad when user just want to use login/register dialog. This is causing closing the whole app and bad user experience. "Uhm website is closed now, but I wanted only to log in - I quit!" 

### Proposed solution
Implementing default v-dialog closing behaviour for browser's back button. This will solve this problem forever.
suggested solution: make fake browser history:

while opening dialog 
window.history.pushState({}, <some string here>);

window.addEventListener("popstate", event => {
        //close your dialog here and remove this listener
    });

**Comment by jacekkarczmarczyk** [comment] 2018-10-14 11:29
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1793

**Closed by jacekkarczmarczyk** 2018-10-14 11:29 UTC
