### ISSUE TITLE
[Feature Request] Dropdown nested menu

### ISSUE THREAD

**Issue by Scronheim** [vuetifyjs/vuetify#15803] opened 2022-09-22 04:22 UTC
### Problem to solve
This menu should solve the problem of its shortage in the standard set

### Proposed solution
Just do it

**Comment by nekosaur** [comment] 2022-09-22 06:28
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1877

**Closed by nekosaur** 2022-09-22 06:28 UTC
Labels: duplicate
