### ISSUE TITLE
[Bug Report] v-data-table + v-pagination broken

### ISSUE THREAD

**Issue by devoniandave** [vuetifyjs/vuetify#6509] opened 2019-02-15 15:53 UTC
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Firefox 65.0
**OS:** Ubuntu undefined

### Steps to reproduce
click on a different page. 

### Expected Behavior
jumps to the new page, shows data for new page

### Actual Behavior
jumps to new page, snaps back to page 1 

### Reproduction Link
<a href="https://codepen.io/devoniandave/pen/BMqEax?editors=1011" target="_blank">https://codepen.io/devoniandave/pen/BMqEax?editors=1011</a>

### Other comments
it seems that the shared property, pagination, which is used to communicate between the v-data-table element and the v-pagination element is picking up the change to its items property after it is replaced by the fetchDevices() method. Also, note that in the code there are two watchers. Activate each by itself to see noted unexpected behavior.

**Comment by johnleider** [comment] 2019-02-15 15:55
I sit possible to reduce the size of this? It seems like a lot of extra stuff going on, making it difficult to understand what's going on. Reproductions should be as minimal as possible.

**Comment by KaelWD** [comment] 2019-02-15 15:59
Duplicate of #3978

There should definitely be a warning or something about combining search and total-items, just having it bound to an empty string causes unexpected behaviour.

**Comment by devoniandave** [comment] 2019-02-15 16:02
downsized a bit.

**Closed** 2019-02-28 02:47 UTC
Labels: T: documentation
