### ISSUE TITLE
[Bug Report] Speed dial incorrect close transition

### ISSUE THREAD

**Issue by yerzhant** [vuetifyjs/vuetify#13210] opened 2021-03-04 13:45 UTC
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.182
**OS:** Linux x86_64

### Steps to reproduce
1. Click on the +
2. Then click again - you won't see transition on hiding - it'll immediately disappear.

### Expected Behavior
Gradually sliding down and fading out

### Actual Behavior
Immediate hiding

### Reproduction Link
<a href="https://codepen.io/yerzhant/pen/JjbBYEx?editors=1000" target="_blank">https://codepen.io/yerzhant/pen/JjbBYEx?editors=1000</a>

**Comment by yerzhant** [comment] 2021-03-04 13:48
One must note that, I guess, tool tip influences to the outcome.

**Comment by KaelWD** [comment] 2021-03-06 07:03
Duplicate of #3399

**Closed by KaelWD** 2021-03-06 07:03 UTC
Labels: triage
