### ISSUE TITLE
[Feature Request] Tab navigation select treeview leaf

### ISSUE THREAD

**Issue by jasonatball** [vuetifyjs/vuetify#12591] opened 2020-11-11 21:37 UTC
### Problem to solve
You can mostly use the keyboard to navigate activatable treeview. Tab selects folders (probably because they have an arrow button) and space opens folders. However you can't tab to leaf items. This is annoying and makes it impossible to use activatable treeviews (without select boxes) with just the keyboard.

### Proposed solution
Allow tab navigation to leaf nodes in activatable but not selectable treeviews.

**Comment by KaelWD** [comment] 2020-11-12 03:11
Duplicate of #10796

**Closed by KaelWD** 2020-11-12 03:11 UTC
