### ISSUE TITLE
[Feature Request] upgrade ress.css

### ISSUE THREAD

**Issue by Ricky816845** [vuetifyjs/vuetify#20687] opened 2024-11-11 02:41 UTC
### Problem to solve
It's just always has scroll bar left screen,at least remove  html : overflow-y:scroll

### Proposed solution
As title ,upgrade ress.css

**Comment by KaelWD** [comment] 2024-11-11 07:29
Duplicate of #1197

**Closed by KaelWD** 2024-11-11 07:29 UTC
Labels: S: triage
