### ISSUE TITLE
[Bug Report] Click listeners not triggered on elemnts inside v-menu component

### ISSUE THREAD

**Issue by dastiw1** [vuetifyjs/vuetify#9963] opened 2019-12-13 05:07 UTC
### Environment
**Vuetify Version:** 2.1.14
**Vue Version:** 2.5.22
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
add simple code in `mounted` section like this: 
```
 document.body.addEventListener('click', function(e) {
      console.log(e, e.target)
    }, false);
```

### Expected Behavior
On buttons click inside menu messages should be displayed in the console

### Actual Behavior
in console triggered only activator button click

### Reproduction Link
<a href="https://codepen.io/dastiw1/pen/MWYeZMY" target="_blank">https://codepen.io/dastiw1/pen/MWYeZMY</a>

### Other comments
in console triggered only activator button click. On buttons click inside menu nothing happened

**Comment by KaelWD** [comment] 2019-12-13 05:25
Duplicate of #6654

**Closed by KaelWD** 2019-12-13 05:25 UTC
Labels: triage
