### ISSUE TITLE
[Bug Report][3.1.6] VSelect is very slow with a lot of items

### ISSUE THREAD

**Issue by tommasogangemi** [vuetifyjs/vuetify#16804] opened 2023-03-01 09:51 UTC
### Environment
**Vuetify Version:** 3.1.6
**Last working version:** 2.6.11
**Vue Version:** 3.2.47
**Browsers:** Chrome 109.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Open the linked codepen and try to open the v-select menu. It'll be very laggy and slow. It looks like all items get rendered at once and changing the number of items to a higher count will make the issue more severe.

This is a simple example, but in the context of a more complex application it gets even worse.

### Expected Behavior
The VSelect does not lag when rendering long lists of items

### Actual Behavior
The VSelect lags a lot and when used in more complex applications makes the whole page break while trying to render the items list.

### Reproduction Link
[https://codepen.io/tommasogangemi/pen/BaOWBBK?editors=101](https://codepen.io/tommasogangemi/pen/BaOWBBK?editors=101)

### Other comments
I think this didn't occur in version 2 because the VSelect rendered every item in a lazy way, so that it didn't have to mount a high number of components when open.

This also occurs in my company's app with:
- Vue 3.2.47
- Vuetify 3.1.4

**Comment by KaelWD** [comment] 2023-03-01 09:55
Duplicate of #2660

**Closed by KaelWD** 2023-03-01 09:55 UTC
Labels: S: triage

**Comment by subhashbhandarivinove** [comment] 2024-07-22 13:46
Any solution?
