### ISSUE TITLE
[Bug Report][3.1.7] [Checkbox] Style is broken when not wrapped in v-app

### ISSUE THREAD

**Issue by tokidoki11** [vuetifyjs/vuetify#16861] opened 2023-03-08 03:34 UTC
### Environment
**Vuetify Version:** 3.1.7
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Create v-checkbox with color inside div element

### Expected Behavior
color and styles works as in documentation

### Actual Behavior
checkbox style is broken

### Reproduction Link
[https://codesandbox.io/s/objective-ishizaka-zll565?file=/src/App.vue](https://codesandbox.io/s/objective-ishizaka-zll565?file=/src/App.vue)

**Comment by tokidoki11** [comment] 2023-03-08 03:40
Video Example
https://user-images.githubusercontent.com/7564844/223613834-32bd3fa1-02b2-4037-88e1-ffef480538ac.mov

**Comment by KaelWD** [comment] 2023-03-08 06:55
Duplicate of #16751

**Closed by KaelWD** 2023-03-08 06:55 UTC
Labels: S: triage
