### ISSUE TITLE
[Feature Request] Let us use/import interfaces from Vuetify

### ISSUE THREAD

**Issue by Shinigami92** [vuetifyjs/vuetify#8902] opened 2019-09-09 12:54 UTC
### Problem to solve
I want to define `options` for a data table in my project. I have enabled the TSLint rule `typedef` and therefore I need to add a typedef to my variable in my component.

```ts
@Component
export default class MyComponent extends Vue {
  public tableOptions: DataOptions = {
    // ...
  };
}
```

Importing from `import { DataOptions } from 'vuetify/src/components/VData/VData';` results in a ton of errors.

### Proposed solution
Let us import interfaces and types from `.d.ts` files.
In example from `node_modules/vuetify/lib/components/VData/VData.d.ts` and so on.

**Comment by KaelWD** [comment] 2019-09-09 12:55
Duplicate of #5962

**Closed by KaelWD** 2019-09-09 12:55 UTC
Labels: triage
