### ISSUE TITLE
[Bug Report] v-select and v-autocomplete list doesn't update when pushing new items.

### ISSUE THREAD

**Issue by ventikus** [vuetifyjs/vuetify#7908] opened 2019-07-22 09:44 UTC
### Versions and Environment
**Vuetify:** 1.5.8
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Add new items to the list downloaded from the API with pagination

### Expected Behavior
The list and scroll bar are constantly updated

### Actual Behavior
The bar and list do not update. Sometimes only one element is added and the user must scroll through the list to be updated.

### Reproduction Link
<a href="https://codepen.io/anon/pen/odvXVN?editors=1010" target="_blank">https://codepen.io/anon/pen/odvXVN?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment] 2019-07-22 09:47
I don't see you're adding anything in this codepen

**Comment by ventikus** [comment] 2019-07-23 09:24
![image](https://user-images.githubusercontent.com/11295594/61700130-74c19f00-ad3c-11e9-8a9d-970cbf9cd367.png)

**Comment by ventikus** [comment] 2019-07-24 13:19
It will be easier to see what I mean, that's why I recorded this short video. As you can see after adding the elements, the user must scroll the list up to see the updated list.

![select](https://user-images.githubusercontent.com/11295594/61796759-5a63f000-ae26-11e9-87f9-0496e799cc9e.gif)

**Comment by jacekkarczmarczyk** [comment] 2019-07-24 13:24
That's what i see in the codepen
![image](https://user-images.githubusercontent.com/15625235/61797089-0b6a8a80-ae27-11e9-9ee3-1fa3074288ae.png)

**Comment by ventikus** [comment] 2019-07-24 13:29
I will make a new one then. Gimme sec.

**Comment by ventikus** [comment] 2019-07-24 13:48
https://codepen.io/pitpik/pen/pMyqRq?editors=1010

You have to click on button and then scroll up.

**Comment by KaelWD** [comment] 2019-07-24 13:51
This is very similar to #5649

**Comment by ventikus** [comment] 2019-07-25 16:41
Do you have an idea how can I deal with it?

**Comment by johnleider** [comment] 2019-08-05 16:47
Duplicate of #5649

**Closed by johnleider** 2019-08-05 16:47 UTC
Labels: triage
