### ISSUE TITLE
[Documentation] Very Bad search

### ISSUE THREAD

**Issue by bristl** [vuetifyjs/vuetify#11743] opened 2020-06-28 23:50 UTC
### Environment

**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.15.5

### Steps to reproduce
Searching for a component "v-layouts" or any other

I think to find this component you need to write  "v-layouts"

But it doesn't work!

### Expected Behavior
component "v-layouts"

### Actual Behavior
Anything other than "v-layouts"

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/navigation-drawers/#layout" target="_blank">https://vuetifyjs.com/en/components/navigation-drawers/#layout</a>

### Other comments
Why does search work so badly?

**Comment by MajesticPotatoe** [comment] 2020-06-29 00:02
duplicate of #11022
This also will be improved in new docs.

**Closed by MajesticPotatoe** 2020-06-29 00:02 UTC
Labels: triage
