### ISSUE TITLE
[Bug Report] v-speed-dial does not apply animation to buttons inside a menu

### ISSUE THREAD

**Issue by KyleReese** [vuetifyjs/vuetify#10710] opened 2020-03-01 00:13 UTC
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Place a menu with a button activator inside of a speed-dial. Open the speed dial. The menu button will immediately pop in with no animation delay. 

### Expected Behavior
A menu with a button activator should have the same animation delay as a button or tooltip

### Actual Behavior
A menu with a button activator immediately pops in when a speed-dial is opened.

### Reproduction Link
<a href="https://codepen.io/KyleReese/pen/XWbgNmr" target="_blank">https://codepen.io/KyleReese/pen/XWbgNmr</a>

**Comment by johnleider** [comment] 2020-03-04 15:36
Duplicate of #10019

**Closed by johnleider** 2020-03-04 15:36 UTC
Labels: duplicate
