### ISSUE TITLE
[Feature Request] Add prop to change "of" text in v-data-footer within v-data-table

### ISSUE THREAD

**Issue by konstantinsteinmiller** [vuetifyjs/vuetify#8480] opened 2019-08-12 14:50 UTC
### Problem to solve
You can provide a translated text string to the "of" label

### Proposed solution
create a prop like its done for itemsPerPageText

**Comment by nekosaur** [comment] 2019-08-12 15:10
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8110

**Closed by nekosaur** 2019-08-12 15:10 UTC
Labels: duplicate

**Comment by konstantinsteinmiller** [comment] 2019-08-13 08:48
Can we still get the prop for the "of" text? its not really suitable for our project to enforce the user to provide a language file for his app.

**Comment by jeyhunhasanov** [comment] 2021-04-14 15:11
```
footer-props="{
    'items-per-page-text': 'Rows per page:',
    'items-per-page-options': [50, 100, 150, 200, -1],
    'items-per-page-all-text': 'All',
    'page-text': '{0}-{1} of {2}'
}"
```

**Comment by Norge0529** [comment] 2022-12-27 03:10
> footer-props="{
>     'items-per-page-text': 'Rows per page:',
>     'items-per-page-options': [50, 100, 150, 200, -1],
>     'items-per-page-all-text': 'All',
>     'page-text': '{0}-{1} of {2}'
> }"

In page-text how can you add comma if there is a thousand of records?
