### ISSUE TITLE
[Bug Report] Issue with v-bottom-sheet overlay when attaching to v-navigation-drawer

### ISSUE THREAD

**Issue by jtomeck** [vuetifyjs/vuetify#11920] opened 2020-07-23 15:01 UTC
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.1
**Browsers:** Chrome 83.0.4103.116
**OS:** Mac OS 10.15.5

### Steps to reproduce
1. Create `v-navigation-drawer`
2. Create `v-bottom-sheet` with button using `v-model` to activate
3. Add class name to `v-navigation-drawer`
4. Add `attach` prop to `v-bottom-sheet` pointing to the navigation drawer class

### Expected Behavior
Both `v-bottom-sheet` and its overlay should be attached to the `v-navigation-drawer`

### Actual Behavior
The `v-bottom-sheet` moves inside the `v-navigation-drawer` but its overlay is still full screen and on top of the `v-bottom-sheet`. Unsure if this is a bug or if I am doing something wrong. There are no examples using attach in Vuetify docs.

### Reproduction Link
<a href="https://codepen.io/jradicus/pen/KKVEdWa" target="_blank">https://codepen.io/jradicus/pen/KKVEdWa</a>

**Comment by KaelWD** [comment] 2020-07-23 15:39
Duplicate of #6425

**Closed by KaelWD** 2020-07-23 15:39 UTC
Labels: triage
