### ISSUE TITLE
[Feature Request] Option to close Combobox and Select menu when appended content clicked

### ISSUE THREAD

**Issue by xon52** [vuetifyjs/vuetify#10421] opened 2020-02-02 10:54 UTC
### Problem to solve
Sometimes it's desired to append items to the combobox and select menu's which will cause an action that moves focus away from the combobox/select elements.
For example: I have a button that can be pressed when a suitable option was not found and it will open a new form to add their option.
To accommodate for this at the moment I have to use the `menu-props` property and link it to a `menuOpen` data property and manipulate that when it opens or closes.
`:menu-props="{value:menuOpen}"`

### Proposed solution
Add a property to Combobox and Select that will trigger the menu to close if the appended slot is clicked `e.g. append-close-on-click`
Or add a `closeMenu` slot-scope attribute to the `append-item` slot.

EDIT: This is effectively the same as [this](https://github.com/vuetifyjs/vuetify/issues/7418) which has an effective workaround. So not urgent.

**Comment by KaelWD** [comment] 2020-02-03 12:50
Duplicate of #7418

**Closed by KaelWD** 2020-02-03 12:50 UTC
Labels: triage
