### ISSUE TITLE
[Bug Report]  Autocomplete slot not clearing input in official example

### ISSUE THREAD

**Issue by steklopod** [vuetifyjs/vuetify#9439] opened 2019-10-23 07:18 UTC
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Yandex 19.10.3.90
**OS:** Windows 10

### Steps to reproduce
1. Go to Vuetify official examples page:
https://vuetifyjs.com/en/components/autocompletes#slots

2. Start typing `Ali`

3. Choose `Ali Connor` from menu

### Expected Behavior
`Ali` that was typed  cleared from input field and only chip left.

### Actual Behavior
`Ali` that was typed NOT cleared from input field and still in input field as text.

### Reproduction Link
<a href="https://codepen.io/steklopod/pen/QWWpvrv?&editable=true&editors=101" target="_blank">https://codepen.io/steklopod/pen/QWWpvrv?&editable=true&editors=101</a>

I think that is because `multiple` attribute.

**Comment by johnleider** [comment] 2020-01-17 03:16
Duplicate of #10029

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-17 03:16 UTC
Labels: triage
