### ISSUE TITLE
[Bug Report] [VSelect]: not working in IE11 when using a placeholder

### ISSUE THREAD

**Issue by DRoet** [vuetifyjs/vuetify#5225] opened 2018-10-05 08:43 UTC
### Versions and Environment
**Vuetify:** 1.2.6
**Last working version:** 1.1.10
**Vue:** 2.5.17
**Browsers:** Internet Explorer
**OS:** Windows 10

### Steps to reproduce
1. Use the codepen code and select an item
2. Blur the v-select by clicking outside of it

### Expected Behavior
The item gets selected

### Actual Behavior
v-select gets cleared empty

### Reproduction Link
[https://codepen.io/anon/pen/XxKZGe](https://codepen.io/anon/pen/XxKZGe)

### Other comments
https://imgur.com/a/HDxXCtq

caused by: https://github.com/vuetifyjs/vuetify/commit/f37e961f0245ceed5a3ab31a996b2cd292e222fe

**Comment by lzhoucs** [comment] 2018-10-25 17:38
I am having the same issue on IE11.

**Comment by jeremyZX** [comment] 2018-11-15 16:40
Same issue in IE11

**Comment by Meg4mi** [comment] 2018-12-16 20:02
same issue in IE11

**Comment by ccarlton96** [comment] 2018-12-18 19:34
How do you test this in IE11? Codepen wont run nativly within IE11.

I'm having a similar issue I think with placeholders not going away when using an <v-autocomplete> when the field is not in focus with data in the field.

**Comment by salqueng** [comment] 2019-01-31 00:41
Same issue in IE11

And, here is a quick fix. (tested on 1.3.11 and 1.4.4)

```html
<v-select
  v-model="selectVal"
  :placeholder="selectVal ? undefined : 'just placeholder'"
  />
```

I don't know why, but removing placeholder prop when value is set works in IE11

**Comment by SebastianBienert** [comment] 2019-03-19 10:36
The original problem is that IE <input> tag with placeholder triggers "input" event just by clicking it. It is then handled by onInput function in VTextField.js. There are several posts in stackoverflow complaining about it:
[1](https://stackoverflow.com/questions/21406138/input-event-triggered-on-internet-explorer-when-placeholder-changed) [2](https://stackoverflow.com/questions/19289396/jquery-input-event-fired-on-placeholder-in-ie)

**Comment by MajesticPotatoe** [comment] 2019-03-19 12:57
closed this in 9b354fd

**Comment by KaelWD** [comment] 2019-03-19 14:18
Nope

**Comment by freitasskeeled** [comment] 2019-06-18 14:27
Hi, is there any update on this? 
I'm currently experiencing this bug with the latest stable build. 
Thanks

**Comment by chars1205** [comment] 2019-07-24 04:50
i'm same issue IE11 error vuetify version : 1.5.5
How do I fix bugs?

**Comment by perezd** [comment] 2019-11-28 02:31
Confirming this is still a problem 2.1.10

**Comment by huynhquangminh** [comment] 2019-11-28 03:24
I fixed it this way and it works fine on IE11 

label="選択してください"
single-line

**Comment by atos1990** [comment] 2020-08-04 16:46
This problem is happen, 'cause VTextField trigger `input` event. In my case I extend VSelect and create stub on VTextField method onInput:

```
@Component({
   extends: VSelect
})
class Select extends Vue {
   onInput(e: Event) {
      // this is IE11 fix
      e.prvendDefault();
   }
}
```

**Comment by mathew-ferry13** [comment] 2020-08-04 18:57
Still a problem in 2.2.27 --- any update on potential fix?

**Comment by vschimpf** [comment] 2020-09-21 14:25
This is an issue for me, and the workaround proposed by @salqueng is not working anymore (used to work).
Any news?

**Comment by shiho-hoshino** [comment] 2020-10-09 01:22
In my case
Tested on 2.3.10

`
<template>
  <v-select
    v-model="innerValue"
    :placeholder="innerPlaceholder"
    multiple
    color="success"
    outlined
    dense
  />
</template>
`
`
export default {
  props: {
    placeholder: {
      required: false,
      type: [Object, String],
      default: '',
    },
  },
  computed: {
    innerPlaceholder() {
      return this.innerValue == [] | this.innerValue == '' ? 'test' : undefined;
    },
  },
};
`

**Comment by KaelWD** [comment] 2021-03-06 12:57
Can't reproduce this in 2.4.5

**Closed by KaelWD** 2021-03-06 12:57 UTC
Labels: C: VSelect, T: regression, platform specific
