### ISSUE TITLE
[Documentation] Documentation webpage's side navigation drawer won't hide on window size change

### ISSUE THREAD

**Issue by IshmamAbir** [vuetifyjs/vuetify#19847] opened 2024-05-21 09:23 UTC
### Environment

**Browsers:** Chrome 125.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Open your browser in full screen mode.
2. Open the documentation page. 
3. Resize the browser window to smaller size.

### Expected Behavior
It will make the navigation panel as hidden. Or else, When you click the hamburger menu icon or anyplace, the side navigation panel will hide and the contents will be displayed in a medium viewpoint format. 

### Actual Behavior
Navigation panel is not hiding, also not closing  on clicking the hamburger menu icon for medium viewpoint display. Also, not closing on menu item changes nor the overlay. 
![vuetify](https://github.com/vuetifyjs/vuetify/assets/39341039/4d40f4d9-dc25-4a5b-a8e5-b70aac89e513)

### Reproduction Link
[https://vuetifyjs.com/en/getting-started/installation](https://vuetifyjs.com/en/getting-started/installation)

**Comment by KaelWD** [comment] 2024-05-21 11:42
Duplicate of #19800

**Closed by KaelWD** 2024-05-21 11:42 UTC
Labels: S: triage
