### ISSUE TITLE
[Bug Report] v-menu with v-tooltip, position isn't correct

### ISSUE THREAD

**Issue by brucesong08** [vuetifyjs/vuetify#8901] opened 2019-09-09 09:48 UTC
### Environment
**Vuetify Version:** 2.0.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Mac OS 10.14.6

### Steps to reproduce
When using v-tooltip in v-menu, popup position isn't correct.

### Expected Behavior
Display popup at bottom of the button  

### Actual Behavior
Display popup at let top of the div  

### Reproduction Link
<a href="https://codepen.io/brucesong08/pen/rNBJPVM?&editable=true&editors=101" target="_blank">https://codepen.io/brucesong08/pen/rNBJPVM?&editable=true&editors=101</a>

**Comment by KaelWD** [comment] 2019-09-09 13:07
Duplicate of #8846

**Closed by KaelWD** 2019-09-09 13:07 UTC
Labels: triage
