### ISSUE TITLE
[feature enhancement] Additional flexibility in positioning the v-tooltip directive

### ISSUE THREAD

**Issue by keystorm** [vuetifyjs/vuetify#1313] opened 2017-08-11 16:50 UTC
## What will it allow you to do that you can't do today?
Sometimes one might need to dynamically change a tooltip position. This is currently not possible. The modifier is very convenient, but it turns out to be too much of a compromise in some scenarios.

A good approach could be making this possible:
```` html
<v-btn v-tooltip="{html:'Lorem ipsum';position:'top'}">Do something</v-btn>
````
Notice no modifier is used on the directive. Using a modifier could be a way of setting a default position for the tooltip, but would always be overridden by the `position` property.

> Currently this example overlays the tooltip on top of the element. Not sure if a bug or an unintended feature, but it could be a useful behavior when no position is provided. This is not documented though.

## How will it make current work-arounds straightforward?

The only workaround to my best knowledge is to code the 4 alternatives and switch among them programatically. This is a very annoying solution. Especially for something as trivial as positioning a tooltip.

## What potential bugs and edge cases does it help to avoid?
Sometimes you need the ability to change the position of the tooltip conditionally when there's a risk of clipping the tooltip at the edge of its container. This doesn't necessarily prevent the tooltip from showing under siblings, but that is easily fixable with a `:hover{z-index:100}` on the element.

Imagine you're building a component around a `<v-btn>`. This component supercharges that button in some way (maybe you're wrapping a printing procedure into that component, os dispatching the same vuex action across several pages and you want to stay DRY and clean). Since it visually simply wraps a `<v-btn>`, you admit all its usual props, no biggy.

But maybe you want that component to show some tooltip in a given condition (no printer found, or dispatch conditions not met). All is done inside the component and working fine.

However, only you know the position of that component. Maybe it's on the left, maybe it's on the right of a `<v-card-actions>` and maybe it's all wrapped in a `<v-modal>`... so that tooltip *will* clip at some point.

Now, if there was a way of injecting the position into the tooltip object, it would become a no-brainer to fix from outside the component, knowing the position of said component (ultimately just a `<v-btn>`), just add a new prop with a sensible default and call it a day.

**Comment by johnleider** [comment] 2017-08-17 16:21
This is technically a duplicate of #139 but you've done quite a nice write-up, I'm going to favor this one for the feature request instead.

**Comment by keystorm** [comment] 2017-08-18 09:09
Thanks.

I had read that issue, but thought they were seeking a more automated solution to the problem. I would personally have no problem with having to set the position manually; after all you're usually fully aware of where you layout your components.

This approach also seems way easier to implement, imo.

**Comment by jacekkarczmarczyk** [comment] 2017-08-18 09:19
`after all you're usually fully aware of where you layout your components`

Not always, component position on a screen can change during scrollig, when it's on the top you'd like to show tooltip below component, when it's at the bottom you'd like to show it above

Additionaly jqueryui has a bit more flexible model then just top/bottom/left/right, maybe there is some easy was to extend it so that it's aware of the screen borders

**Comment by keystorm** [comment] 2017-08-18 09:27
> Not always, component position on a screen can change during scrollig, when it's on the top you'd like to show tooltip below component, when it's at the bottom you'd like to show it above

You've got a good point right there. I'd prefer an intermediate *easy* solution, than a complex screen offset, tooltip size aware fix that would take a presumably larger effort. Again, it's just tooltips...

Either way, both approaches are compatible with each other. So eventually this could also be a thing:

```` html
<v-btn v-tooltip="{html:'Lorem ipsum'; position:'auto'}"></v-btn>
````

**Closed** 2017-09-17 03:38 UTC
Labels: feature request
