### ISSUE TITLE
[Bug Report] v-navigation-drawer is not always full height in Chrome on Android

### ISSUE THREAD

**Issue by yann3018** [vuetifyjs/vuetify#4384] opened 2018-06-24 11:12 UTC
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Google Chrome, Microsoft Edge
**OS:** Android

### Steps to reproduce
**IMPORTANT INFORMATION!!! It's not possible to reproduce the issue with codepen.**
Create a new Vuetify project with Vue-Cli 3 using the following steps:
*npm install -g @vue/cli // installs @vue/cli@3.0.0-rc.3*
*vue create my-project*
*cd my-project*
*vue add vuetify // installs vuetify 1.0.19*
**(Optional)** You may also install the latest release candidate of Vuetify, I observed the same result.

Edit App.vue. Erase all code and replace with the following:
```
<template>
  <v-app>

    <v-navigation-drawer
      app
      fixed
      temporary
      ></v-navigation-drawer>

    <v-content>
      a<br><br><br>v<br>e<br>r<br>y<br><br><br><br>l<br>o<br>n<br>g<br><br><br><br>t<br>e<br>x<br>t<br><br><br><br>!<br><br><br>!<br><br><br>!<br><br><br>!<br><br><br>!<br><br><br>!<br><br><br>!<br><br><br>!<br><br><br>!<br><br><br>!<br><br><br>!<br><br><br>!<br><br><br>!<br><br><br>!<br><br><br>!
    </v-content>

  </v-app>
</template>
```

We've created a simple page with a long text and a temporary navigation drawer.

Start your server and execute the page on an Android phone with Google Chrome. The page should open with the navigation drawer closed.
Execute carefully the following steps:
- Open the drawer by SWIPING RIGHT with your finger near the left edge of the screen.
- SWIPE UP on the overlay (not on the menu itself), like if you want to scroll down. Nothing should happen on the screen.
- Close the menu by doing a TAP on the overlay. Your page should not have scrolled.
- Scroll down the page with a SWIPE DOWN with your finger, until the Google Chrome address bar disappears.
- Open the drawer by SWIPING RIGHT with your finger near the left edge of the screen.
- Your navigation drawer should have opened again. But this time, it does not take the full height of your screen. Here is a screenshot (https://ibb.co/nkMes8).

This space corresponds to the hidden address bar of the browser.
Executing the same steps with Microsoft Edge for Android will provide the same result. I believe it's the same engine, and it also has UI elements which are hidden when scrolling.
Firefox for Android doesn't do that. It doesn't have any UI elements which hide on scroll.
I did not test other browsers.

Same behaviour observed on my Pixel 2 XL (phone) and my Nexus 9 (tablet)

### Expected Behavior
I expect v-navigation-drawer's height to be equal to 100% viewport height after executing the steps above.

### Actual Behavior
v-navigation-drawer's height is less than 100% viewport height  after executing the steps above.

### Reproduction Link
[https://codepen.io/anon/pen/jKKXyN](https://codepen.io/anon/pen/jKKXyN)

### Other comments
In order to reproduce this, you need to use a browser which had UI elements that hide when scrolling down, such as Google Chrome for Android or Microsoft Edge for Android.
As far as I know, you can't reproduce it when running a browser and Windows or Mac.

**You also can't reproduce this on the codepen. Codepen uses iframes, and therefore doesn't behave the same way when scrolling down.**

**Comment by KaelWD** [comment] 2018-06-24 11:29
https://developers.google.com/web/updates/2016/12/url-bar-resizing

Using `height: 100vh` fixes this, but cuts of the bottom 56px of the drawer.

**Comment by KaelWD** [comment] 2018-06-24 11:35
Looks like this might actually be caused by something else (hidden overflow maybe?), `height: 100%` is supposed to resize when the bar hides: https://bokand.github.io/demo/urlbarsize.html

**Comment by KaelWD** [comment] 2018-06-24 12:06
Removing [`touch-action: none`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) on the overlay also fixes it, but means touchscreens > 960px can still scroll the rest of the page. We can either:

 - leave it, it's a pretty minor visual issue and only happens if you try to scroll the overlay
 - add `overflow-y-hidden` on all screen sizes, which we've said we won't do because it causes layout jumps on desktop browsers

**Comment by yann3018** [comment] 2018-06-24 12:57
Good finding!
I've just tried with `touch-action: auto`. It seems to behave quite good. I can't see problems with touchscreens > 960px so far.
I will keep this in my style sheet for now.

**Comment by yann3018** [comment] 2018-06-24 14:44
Yes, I see it now :(

**Comment by KaelWD** [comment] 2018-07-19 07:12
This was *not* fixed by cc4959f

**Comment by johnleider** [comment] 2018-07-19 14:19
That's my fault. Native results differed from emulated.

**Comment by adarshsrivastava11** [comment] 2019-09-04 22:21
Hey, are there any updates on this?

**Comment by leolux** [comment] 2020-03-30 10:26
> 
> 
> Good finding!
> I've just tried with `touch-action: auto`. It seems to behave quite good. I can't see problems with touchscreens > 960px so far.
> I will keep this in my style sheet for now.

Where did you set `touch-action: auto` on? On `v-overlay__scrim`, `v-overlay` or something more specific?

**Comment by guillemat** [comment] 2020-04-28 13:44
You could add style="height:'' to you navigation-drawing tag

**Comment by johnleider** [comment] 2020-12-16 17:52
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).

**Closed by johnleider** 2020-12-16 17:52 UTC
Labels: C: VNavigationDrawer, T: bug, platform specific

**Comment by moro123** [comment] 2020-12-22 00:18
> You could add style="height:'' to you navigation-drawing tag

You could add will-change: unset;
