### ISSUE TITLE
[Bug Report][3.0.0-beta.1] v-text-field type=number not showing value when the value of the field is 0; hidden by the label

### ISSUE THREAD

**Issue by quiquelhappy** [vuetifyjs/vuetify#15102] opened 2022-05-16 17:09 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Last working version:** 2.6.4
**Vue Version:** 3.2.33
**Browsers:** Chrome 101.0.4951.64
**OS:** Windows 10

### Steps to reproduce
<v-text-field label="a" variant="outlined" hide-details type="number" :value="0" />

### Expected Behavior
show the value even if its 0, unless null

### Actual Behavior
value hidden by the label

### Reproduction Link
<a href="https://codepen.io/quiquelhappy/pen/mdXRKgp" target="_blank">https://codepen.io/quiquelhappy/pen/mdXRKgp</a>

**Comment by KaelWD** [comment] 2022-05-17 06:04
Duplicate of #14942

**Closed by KaelWD** 2022-05-17 06:04 UTC
Labels: S: triage
