### ISSUE TITLE
Date picker container in dialog has extra white space after dialog resizes

### ISSUE THREAD

**Issue by amitailanciano** [vuetifyjs/vuetify#780] opened 2017-06-17 01:10 UTC
### Steps to reproduce

see codepen

### Versions

0.12.7

### What is expected ?

When dialog window resizes, the date picker container should not have extra white space. I set the outer dialog width to 'auto' because longer error messages were sometimes overflowing outside the container.

### What is actually happening ?

Date picker has extra white space after dialog window resizes

### Reproduction Link

https://codepen.io/anon/pen/XgpjNZ

**Comment by johnleider** [comment] 2017-06-17 01:48
The picker components have explicit widths. This is intentional.

**Comment by amitailanciano** [comment] 2017-06-17 01:52
I agree that the picker should stay its initial size, I just think it shouldn't have that extra white space when the dialog window resizes, perhaps it could be centered or something?

**Comment by johnleider** [comment] 2017-06-26 00:59
Coming back to this, I cannot reproduce the issue. Did you change the pen?

**Comment by amitailanciano** [comment] 2017-06-26 01:01
No, that's strange.. I can reproduce it on my end -- are you sure you're hitting the submit button to show the error before opening the picker again?

**Comment by johnleider** [comment] 2017-06-26 01:03
Got it! Thank you.

**Comment by johnleider** [comment] 2017-06-26 01:07
The reason this is happening is your markup is broken. You had an extra </v-dialog> closing tag and was missing a closing </v-menu> tag.

https://codepen.io/johnjleider/pen/Ngawrb

**Closed by johnleider** 2017-06-26 01:07 UTC

**Comment by amitailanciano** [comment] 2017-06-26 01:15
You were right about the tags, sorry to mislead you there, I must have re-typed it for the codepen, but the issue still remains nonetheless. Yours doesn't have `:width="'auto'"` so it will never resize, I forked it and tested again after adding `:width="'auto'"` and made the error really long to make sure it expands the dialog for you.

https://codepen.io/anon/pen/mwBqry

**Comment by johnleider** [comment] 2017-06-26 01:16
You can add **min-width="auto"** next patch to resolve that.

**Comment by amitailanciano** [comment] 2017-06-26 01:20
👍 I'll give it a try on the next release, just to make sure though, we're talking about the extra white space to the right of the date picker, not about the error message getting clipped correct?

<img width="752" alt="screen shot 2017-06-25 at 6 20 17 pm" src="https://user-images.githubusercontent.com/1289466/27521540-fbd1f1e4-59d2-11e7-872d-b006b661a958.png">

**Comment by johnleider** [comment] 2017-06-26 01:21
Yup, tracking that.
