### ISSUE TITLE
[Bug Report] <v-btn dark disabled> completely invisible on white background

### ISSUE THREAD

**Issue by henriq-88** [vuetifyjs/vuetify#5850] opened 2018-12-10 00:38 UTC
### Versions and Environment
**Vuetify:** 1.3.12
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Mac OS 10.14.1

### Steps to reproduce
Create a `<v-btn>` with the `dark` and `disabled` properties and place it on a white background.

### Expected Behavior
To see the disabled button

### Actual Behavior
Invisible button

### Reproduction Link
<a href="https://codepen.io/henriq88/pen/WLNJRe?&editable=true&editors=101" target="_blank">https://codepen.io/henriq88/pen/WLNJRe?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment] 2018-12-10 01:13
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4482

**Closed by jacekkarczmarczyk** 2018-12-10 01:13 UTC
