### ISSUE TITLE
[Feature Request] DataTable Search by columns

### ISSUE THREAD

**Issue by jlfernandesjn** [vuetifyjs/vuetify#3250] opened 2018-02-12 03:05 UTC
### New Functionality
Search by columns indivudualy.

### Improvements
It will avoid to use other dataTable plugins keeping theme integration.

### Bugs or Edge Cases it Helps Avoid
Visual theme bugs caused by other dataTable plugins

**Comment by nekosaur** [comment] 2018-02-12 15:58
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3102

**Closed by nekosaur** 2018-02-12 15:58 UTC
Labels: duplicate
