### ISSUE TITLE
[Feature Request] Date Picker Improvment

### ISSUE THREAD

**Issue by marciojalber** [vuetifyjs/vuetify#4765] opened 2018-07-31 18:30 UTC
### Problem to solve
Selecting a date range sometimes is a complex task

### Proposed solution
I think there could be a date range selection component

**Comment by jacekkarczmarczyk** [comment] 2018-07-31 19:41
duplicate of https://github.com/vuetifyjs/vuetify/issues/1646

**Closed by jacekkarczmarczyk** 2018-07-31 19:41 UTC
