### ISSUE TITLE
[Bug Report] v-text-field as a child/embedded light component still inherit dark theme

### ISSUE THREAD

**Issue by vilipwong** [vuetifyjs/vuetify#4439] opened 2018-07-01 14:33 UTC
### Versions and Environment
**Vuetify:** 1.1.0
**Vue:** 2.5.16
**Browsers:** Chromium 66.0.3359.181
**OS:** Ubuntu undefined

### Steps to reproduce
1. v-app uses dark theme variant
2. v-card with v-form with multiple v-text-field uses light theme variant

### Expected Behavior
v-text-field should follow light theme variant

### Actual Behavior
v-text-field inherits dark theme variant

### Reproduction Link
[https://codepen.io/vilipwong/pen/aKXVbp](https://codepen.io/vilipwong/pen/aKXVbp)

**Comment by KaelWD** [comment] 2018-07-01 14:54
This isn't an exact duplicate of #2494 but it's the same cause. Css cascade only goes so far. Fix in progress #4386

**Closed by KaelWD** 2018-07-01 14:54 UTC
