### ISSUE TITLE
[Bug Report] Input validation error pushes content down by 2px

### ISSUE THREAD

**Issue by joeledenberg** [vuetifyjs/vuetify#7034] opened 2019-04-21 07:19 UTC
### Versions and Environment
**Vuetify:** 1.5.12
**Vue:** 2.5.22
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
Type more than 10 characters into first input field

### Expected Behavior
Nothing should move when error appears

### Actual Behavior
Everything gets pushed down 2px

### Reproduction Link
<a href="https://codepen.io/anon/pen/pBVwBo?editors=1010" target="_blank">https://codepen.io/anon/pen/pBVwBo?editors=1010</a>

**Comment by KaelWD** [comment] 2019-04-21 07:47
Duplicate of #7025

**Closed by KaelWD** 2019-04-21 07:47 UTC
Labels: triage
