### ISSUE TITLE
[Bug Report] "v-stepper": Separating v-stepper-content into single file components do not work

### ISSUE THREAD

**Issue by ResamVi** [vuetifyjs/vuetify#4626] opened 2018-07-16 17:17 UTC
### Versions and Environment
Vuetify: 1.1.4 25:26:1 
Vue: 2.5.16 main.js:20 
Browsers: Firefox 61.0.1, Chrome Version 67
OS: ArchLinux

### Steps to reproduce
I've made a self-contained example here https://github.com/ResamVi/vuetify-stepper-bug

Using Vuetify's v-stepper example:

`App.vue`
```vue
<v-stepper v-model="e1">
    <v-stepper-header>
      (...)
    </v-stepper-header>

    <v-stepper-items>
      
      <v-stepper-content step="1">
        <v-card
          class="mb-5"
          color="grey lighten-1"
          height="200px"
        ></v-card>

        <v-btn color="primary">
          Continue
        </v-btn>

        <v-btn flat>Cancel</v-btn>
      </v-stepper-content>

      <v-stepper-content step="2">
        (...)
      </v-stepper-content>
     ...
```
Works perfectly fine.

However if you extract a single `v-stepper-content` into its own file `Content.vue`
and do it like this

`App.vue`
```vue
<v-stepper v-model="e1">
     <v-stepper-header>
      (...)
    </v-stepper-header>

    <v-stepper-items>
      
      <Content /> <!-- Replace first v-stepper-content here -->

      <v-stepper-content step="2">
        <v-card
          class="mb-5"
          color="grey lighten-1"
          height="200px"
        ></v-card>

        <v-btn color="primary">
          Continue
        </v-btn>

        <v-btn flat>Cancel</v-btn>
      </v-stepper-content>

      <v-stepper-content step="3">
        (...)
      </v-stepper-content>
      ...
```
`Content.vue`
```vue
<template>
  <v-stepper-content step="1">
    <v-card
      class="mb-5"
      color="grey lighten-1"
      height="200px"
    ></v-card>

    <v-btn color="primary">
      Continue
    </v-btn>

    <v-btn flat>Cancel</v-btn>
  </v-stepper-content>
</template>

<script>
export default {
  
}
</script>
```

It suddenly won't work anymore

### Expected Behavior
How it appears when not wrapped as a single file component
![works](http://i.imgur.com/FsxgOqG.png)

### Actual Behavior
How it appears when it is wrapped inside `Content.vue`
![not working](http://i.imgur.com/7IqqEq4.png)

### Reproduction Link
https://github.com/ResamVi/vuetify-stepper-bug

**Comment by jacekkarczmarczyk** [comment] 2018-07-16 17:21
duplicate of https://github.com/vuetifyjs/vuetify/issues/3330

**Closed by jacekkarczmarczyk** 2018-07-16 17:21 UTC

**Comment by ResamVi** [comment] 2018-07-16 17:22
yea i just got rekt damn

**Comment by gerasimvol** [comment] 2018-10-12 09:28
1) update vuetify to 1.2.9
2) use vue-fragments
and get this:
![image](https://user-images.githubusercontent.com/14095526/46861046-5aa47900-ce1a-11e8-83a6-d929eb17b8ac.png)
