### ISSUE TITLE
[Bug Report] v-autocomplete does not preserve the scroll position

### ISSUE THREAD

**Issue by neupauer** [vuetifyjs/vuetify#11969] opened 2020-07-31 09:30 UTC
### Environment
**Vuetify Version:** 2.3.7
**Vue Version:** 2.5.22
**Browsers:** Chrome 84.0.4147.105
**OS:** Mac OS 10.15.6

### Steps to reproduce
Under certain conditions, v-autocomplete starts skipping to the top/bottom of the list and does not preserve the current scroll position.

### Expected Behavior
Should always preserve scroll position

### Actual Behavior
Scroll to top/bottom of the list

### Other comments
See the recording from the current documentation page (v2.3.7) https://drive.google.com/file/d/1FI1o0OOKjQrfO8wwpXI7DFATRVQyI6z-/view

**Comment by KaelWD** [comment] 2020-07-31 09:51
I can't reproduce this in windows or on macos through browserstack.

**Comment by neupauer** [comment] 2020-07-31 10:12
I don't know to provide steps to reproduce it, but sometimes it happens (we have feedback from customers). My first thought was that the problem is on our site, but after a little investigation of the issue, I recorded the same problem on the Vuetify docs page.

In our case, the setting is similar to the setting on `v-autocomplete` in docs.
```
<v-autocomplete ... small-chips deletable-chips multiple>
  <template v-slot:selection="data">
    ...
  </template>
</v-autocomplete
```

**Comment by KaelWD** [comment] 2020-07-31 11:07
This is likely caused by some specific browser/os/settings/extensions, there isn't anything in the component that's directly affecting scroll position in this scenario.

**Comment by neupauer** [comment] 2020-07-31 14:55
I probably figured out the root cause of this problem. This is because some item has a `focus`. E.g. the first item has focus ( due to `tab` or `arrows` navigation—maybe by default? ), and when someone scrolls down and clicks on the item, the browser jumps up to the focused item.

It happens across all select components (probably with `multiple` attribute because the panel will remain open after selecting an item)

Right now I was able to test it only on Mac (Chrome, Safari, Firefox)—all the same issue.

See Firefox on MacOS `<v-select multiple />` https://drive.google.com/file/d/1-X-qvDTnDtoi75rNfwg5I4VAr2AQoRmB/view?usp=sharing

I think that the `focus` should follow the user selection/click, but it stays fixed on the previously focused item.

**Comment by KaelWD** [comment] 2020-07-31 16:01
Ah yeah I see that one. In the original video did you interact with the combobox using the keyboard before the video starts?

**Comment by neupauer** [comment] 2020-07-31 18:31
> In the original video did you interact with the autocomplete using the keyboard before the video starts?

Most likely yes, at the time I thought it had something to do with the searching. Thank you for your help.

**Comment by tomer-epstein** [comment] 2020-08-24 11:05
Hi @KaelWD 

Can you estimate when a fix will be available?

Thanks, Tomer

**Comment by hoseinmirian** [comment] 2020-10-02 11:07
I have the same problem in our project, I have a scrollable container holding all the autocompletes; when opening up one of them, it will show the list of those items and when I try to scroll the container of the autocompletes, the opened autocomplete stays fixed in will not be scrolled by its container. Please take a look at the picture and also the link to the code
![image](https://user-images.githubusercontent.com/25683981/94916964-8c032d00-04a7-11eb-9fce-31a19a4469f3.png)


Autocomplete Component: https://github.com/FAIRsharing/fairsharing.github.io/blob/dev/src/components/Records/Search/Input/FilterAutocomplete.vue

AutoComplete Scrollable Holder: https://github.com/FAIRsharing/fairsharing.github.io/blob/dev/src/components/Records/Search/Input/SearchInput.vue

**Comment by KaelWD** [comment] 2020-10-02 11:16
@hoseinmirian not related, see #795

**Comment by do-web** [comment] 2020-11-10 20:10
When this will be fixed?

**Comment by gunduzemreozer** [comment] 2020-11-16 00:19
Hi everybody. To solve this issue, I follow below steps.

1. I gave ref to my v-autocomplete component as "autoComplete".
2. I started to watch value of autocomplete at wather method and i calculated changing item index at this method.
3. After that, I called autocomplete setMenuIndex method like this: this.$refs.autoComplete.setMenuIndex(changedItemIndex)

I have a little problem, i cannot solve for now. If autoselect is multiple and some string searched and choosen from list, I clear search string. After this menu index is also cleared unfortunately. On the other scenarios, it runs perfectly.

I hope this solution helps someone :) I share my codes below. 

```js
watch: {
    value: function(newVal, oldVal) {
      try {
        this.changedListItemIndex = this.getChangedListItemIndex(newVal, oldVal);
      }
      catch {
        this.changedListItemIndex = -1;
      }

      if (this.multiple) {
        this.innerSearchingValue = undefined;
      }

      this.$refs.autoComplete.setMenuIndex(this.changedListItemIndex);

      if (this.multiple) {
        this.$nextTick(() => {
          this.$refs.autoComplete.setMenuIndex(this.changedListItemIndex);
        });
      }
      else {
        setTimeout(() => {
          this.$refs.autoComplete.setMenuIndex(this.changedListItemIndex);
        }, 100);
      }
    }
  }
```

```js
getChangedListItemIndex(newVal, oldVal) {
      let lastChangedItem;
      if (this.multiple && newVal.length > oldVal.length) {
        lastChangedItem = newVal[newVal.length - 1];
      }
      else if (this.multiple) {
        lastChangedItem = oldVal.find(x => !newVal.includes(x));
      }
      else {
        lastChangedItem = newVal;
      }

      let listItemValue;
      if (this.returnObject) {
        listItemValue = lastChangedItem[this.itemValue];
      }
      else {
        listItemValue = lastChangedItem;
      }

      return this.items.findIndex(item => item[this.itemValue] === listItemValue);
    }
```

```Vue
<v-autocomplete
    ref="autoComplete"
    :value="value"
    @input="onInput"
    :search-input.sync="innerSearchingValue"
    @update:search-input="onSearchInputUpdate"
```

**Comment by yurirolandi** [comment] 2021-07-01 15:18
I managed to solve  this problem using ref=itemScrollTop in my autocomplete and watching the themeComputed  like this:

watch: {
   themeComputed: function (itemOnlyScroll) {
      if (itemOnlyScroll !== null) {
        this.$refs.itemScrollTop.$refs.menu.$refs.content.scrollTop = 0;
      }
   },
}

**Comment by boutils** [comment] 2021-09-02 05:26
I got this issue too with a `v-select` and `multiple` attribute.
The best workaround for me to preserve the scroll position is the following:
```vue
<v-select
  v-model = "selecteditems"
  :items  = "items"
  ref     = "mySelector"
  multiple>
</v-select>
```

```js
watch: {
  selecteditems() {
    this.$refs.mySelector.setMenuIndex(0);
  }      
}
```

Note that https://github.com/vuetifyjs/vuetify/pull/14070 fixes my issue. I will then revert my hack when it will be merged.

**Closed** 2021-09-06 16:25 UTC
Labels: T: bug, C: VSelect

**Comment by AleksanderGjinollari** [comment] 2024-07-16 13:40
I don't know if this will work for you, but adding the attach prop to v-autocomplete solved it for me.

```
<v-autocomplete
  :attach="true"
```
