### ISSUE TITLE
[Bug Report] Tabs: current tab is not highlighted on initial run  

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#6725] opened 2019-03-13 12:17 UTC
### Versions and Environment
**Vuetify:** 1.5.6
**Vue:** 2.6.8
**Browsers:** Chrome 72.0.3626.109
**OS:** Linux x86_64

### Steps to reproduce
1. Click on OPEN button;
2. Notice that the first tab is selected, but it does not have slider-wrapper yellow bottom border (actually it has, but the width is zero).

### Expected Behavior
The first tab should have yellow underline.

### Actual Behavior
There's no yellow underline.

### Reproduction Link
<a href="https://codepen.io/anon/pen/wOparJ?editors=1010" target="_blank">https://codepen.io/anon/pen/wOparJ?editors=1010</a>

### Other comments
Some additional width initialization required here after mount. I suppose, during the tabs component initialization the container width was not set yet. If we resize a window or switch to the other tab, it starts working.

**Comment by KaelWD** [comment] 2019-03-13 12:20
Duplicate of #1978

**Closed by KaelWD** 2019-03-13 12:20 UTC
Labels: duplicate
