### ISSUE TITLE
[Feature Request] Please add the upload file with the preview feature and Draggable feature

### ISSUE THREAD

**Issue by Rasool-deldar** [vuetifyjs/vuetify#13324] opened 2021-03-25 14:29 UTC
### Problem to solve
This feature makes it easy for the user to upload their file and see what they are uploading.

### Proposed solution
My solution is for you to do the same as [dropzonejs ](https://www.dropzonejs.com/) Thanks

**Comment by KaelWD** [comment] 2021-04-09 07:14
Duplicate of #8812

**Closed by KaelWD** 2021-04-09 07:14 UTC
Labels: triage
