### ISSUE TITLE
[Bug Report] Stepper double bounce on switching steps in firefox

### ISSUE THREAD

**Issue by aldarund** [vuetifyjs/vuetify#4154] opened 2018-05-25 23:05 UTC
### Versions and Environment
**Vuetify:** 1.1.0-beta.0
**Vue:** 2.5.16
**Browsers:** Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Click continue and then back.
See this video for demonstration
https://www.dropbox.com/s/azhvau3ho6azf4j/2018-05-26_02-02-30.mp4?dl=0
Wasnt able to reproduce in chrome.
It bounces more noticeable in my real app with more content in steps.
Same behavior in 1.0.18

### Expected Behavior
Never double bounce

### Actual Behavior
Sometime it double bounce 

### Reproduction Link
[https://codepen.io/aldarund/pen/ELqxBe?&editors=101](https://codepen.io/aldarund/pen/ELqxBe?&editors=101)

**Comment by johnleider** [comment] 2018-05-30 01:31
While it is obvious from your provided video there is an issue, I have been unable to reproduce it on any browser in windows 10. Going to need some additional information.

**Comment by johnleider** [comment] 2018-05-31 02:29
I might need some help debugging unless I can reproduce it locally.

**Comment by johnleider** [comment] 2018-06-24 02:32
Any update on this?

**Comment by KaelWD** [comment] 2018-06-24 07:35
Couldn't reproduce in firefox 60.0.2, I don't think this is worth spending time on.
@aldarund if you find a fix for this you're welcome to submit a PR or just post it here.

**Closed by KaelWD** 2018-06-24 07:35 UTC
Labels: S: need reproduction

**Comment by aldarund** [comment] 2018-06-24 10:37
@KaelWD @johnleider  i still can reproduce it. I found what is causing it
https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/generic/_transitions.styl#L93
Which was added by https://github.com/vuetifyjs/vuetify/commit/3a9033111afbd7a65bd23d4f0b3de49af40416e0
But there no reference to the issue so i dont know what weird rendering bug it suppose to fix. 
I tried to just remove that enter-to transition from css and all seems to work fine in ff/chrome/edge


btw, it also reproducible in edge, it have same bounce effect but its waaaay smaller like few pixels only.

**Comment by aldarund** [comment] 2018-06-24 14:13
And as i see there no enter-to transition for tab-reverse-transition. So i guess deleting would be fine

**Comment by anoop-ananthan** [comment] 2018-07-19 12:08
Unfortunately, this issue still prevails!
I'm using Ubuntu 18
Mozilla Version 61.0.1 (64-bit)
the frequency of double bouncing is annoyingly high. But the curious thing is, this does happen only in **cli-generated** code.

**Comment by aldarund** [comment] 2018-07-19 12:11
@anoop-ananthan what version of vuetify? Since fix i cant reproduce it anymore..

**Comment by anoop-ananthan** [comment] 2018-07-24 05:57
@aldarund Hi,

|Component|Version|
|---|---|
|Vuetify|`0.17.7`|
|Vue|`2.5.16`|
|Vue/Cli|`3.0.0-rc1`|
|Ubuntu|18|

**Comment by anoop-ananthan** [comment] 2018-07-24 07:20
Ok Thanks :+1:
