### ISSUE TITLE
[Documentation] MD Menu Icon not working in Code Pens

### ISSUE THREAD

**Issue by six-edge** [vuetifyjs/vuetify#10049] opened 2019-12-27 12:05 UTC
### Environment

**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
1. Open the example in CodePen (Applies to all CodePens under https://next.vuetifyjs.com/en/getting-started/pre-made-layouts) 
e.g. 
https://codepen.io/johnjleider/pen/zgxeLQ
https://codepen.io/johnjleider/pen/WVbPgz
https://codepen.io/johnjleider/pen/pMvGQO
https://codepen.io/johnjleider/pen/QewYYx
https://codepen.io/johnjleider/pen/bXNzZL
https://codepen.io/johnjleider/pen/MNYLdL
https://codepen.io/johnjleider/pen/zgxbYO
https://codepen.io/johnjleider/pen/aezMOO

2. Observe that the "menu" icon is missing

### Expected Behavior
"menu" icon is rendered

### Actual Behavior
"menu" icon is missing

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/getting-started/pre-made-layouts" target="_blank">https://next.vuetifyjs.com/en/getting-started/pre-made-layouts</a>

### Other comments
Possible solutions:

1. Add the missing default mdi icons to the CodePen settings under CSS: 
https://cdn.jsdelivr.net/npm/@mdi/font@4.x/css/materialdesignicons.min.css
or
2. Set the icon font to md... e.g. vuetify: new Vuetify({icons: { iconfont: 'md' }}),

**Comment by jacekkarczmarczyk** [comment] 2019-12-27 12:09
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8032

**Closed by jacekkarczmarczyk** 2019-12-27 12:09 UTC
Labels: triage
