### ISSUE TITLE
[Bug Report][3.3.8] AutoComplete Select Menu show on incorrect position after mounted

### ISSUE THREAD

**Issue by flaming-cl** [vuetifyjs/vuetify#17833] opened 2023-07-19 00:00 UTC
### Environment
**Vuetify Version:** 3.3.8
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Note: This issue especially will happen on bigger screens.

1. When the component is just mounted, click on the autocomplete input. 
(So far this only happens on the first click. When you cancel the select menu and click on the autocomplete input again, the menu is showing on the correct position)

### Expected Behavior
The select menu should align with the left most of the autocomplete input.
![expected](https://github.com/vuetifyjs/vuetify/assets/51183663/bc8af47a-5ccd-43e6-9e82-4bf7f693ab48)

### Actual Behavior
![actual](https://github.com/vuetifyjs/vuetify/assets/51183663/e809da07-967b-476a-80e3-68306ce7271f)
Similar issue also comes with VSelect:
![actural2](https://github.com/vuetifyjs/vuetify/assets/51183663/194db424-b614-424b-8195-7a2b79bbebb8)

### Reproduction Link
[VAutoComplete-playground](https://play.vuetifyjs.com/#eNq1VlFP2zAQ/iunvAwkkqCxh60riElIE9KQJtAeJsKDm1wSg2Nn9iWlQ/3vO6dNm8KAbhVPtc933/fd+XLu9UPwpa6jtsFgFIwJq1oJwpNEA4wz2UKqhHPHSSAaMmFq+BgJeaFJSI02CTpXdm5D79J7LIwAI8mQPr77TYLeLuoadRZKzRihZDh2qTIZVjK1pi6NxoGvp3aoMKUwl9ZRf9BryxXeh3mjVDiVGZXryAy1kzRjF9aVG0tiogbAXlNYM5/rLRXqppez9uOSpFgalaFl+xUKm5bw1ZhCIRgLNKsRBPy4/DYIsfhMgqLQMp+tPa1pdIZZv6USK2RfJYuS1l6tsFJo4gNnlOntJ+N4s+yLe4v54ng1jgfXyVuXWllT54L3NVeD65OLRhE8LOAyQWIEe/twfAJ7SxtbpVCmGEEulMODYe3cCK77PfQgG/mfc+IjeOcTT5VJ70LTkOK+ebfC6XKWpJDdLKaSSzmVVEJayvQO9dBxPljvTjZBR1DKO6kLICukcqD5ZrkF3o6zNFMgA4p5NHeMxikooYtGFG9Ienb+E0pT+VYthJa/BUmjQWYo3NuR+q7j+ubClZ6NLCM8Q3ezWrmSmzJt6IW+8l/SUkXBbdJM/k5/IRyhhc3D0mLuL4GodqM4XsRH/OnEPP2IP8pb16+2KsyWWs6w/W8dMRcO42wTYVdBV90Y3FFT+z50T3B2VXYxg+88xuESfzXcPhsN828aa4Zx8a0ptUJudfty6833u8Xcz8zVlBw7mqnFRI2eef36JLtnZwQfDw/r+89rpGV8cMDTXN+56NYZza9sF8RPkuP3cNXpSdDnlWaaPTNUsrWRRop1vcrw9Cg6ij7xfHfUm0IlJi7qwDzSTaLnTCgrP+D5takfsS4OOual+CRgJL9/RcIpu8W20SQrDDNTdVo+LLQMzBG6KpxYM3VoGSQJljXuaLzgLahey5YpnkDHzNfyW+snDVr/z2S7jB6FDbN6dPQks+VNz4P5QdCFceE7ycHNH9xf4cg=)

[Vselect-playground](https://play.vuetifyjs.com/#eNqNU8tugzAQ/BXLl7RSwJXSSymN+lJ+IuTgwEZxa4xlG/IS/97FQJOC1ORkvI+Z2VmzPNE3rcOqBBrR2EGuJXcwTxQhcSYqkkpu7UtCq8CChNQFaaEcFwpMQn0V1vU5EgkEaKr9mVCSgbLCHTCSFrnmqcOY5GuQGPnoI/OY9QiIOMBsr2QE3cf/MGwK4/hawjl9QTZM/ks7HqVH+oQNL+VINvYy9Au/YnbhIl5taoRuS2CvUQRq9hDk1JJm3PGI3N2Tlzm562KEeN6ILCeLophMyeSdm+ZYiOPRX0s8V9O2ur73H3VD/ksXW3eQ7SbD8fZ68p3I3DYis4cHvX8+g3StdEqlUN82/LKFwgfim9Bqi46gthYioVvntI0YSzOFlRlIUZlQgWNK5wyflhObw+ssnIVP6JF1fShAT23owRqkVaJqJBR5Y1KQcz1gbROeuROPz7LEfUbXJLxiGTOlciKHICtyr+Wx1XIRDsHmwdoUOwsGQRLa2etpGsE3UF2bFilG0Az5KjCBAZWBaf6s2yYatF1ONUiNJus2XdN6Sn0bGu8l09UPMjRZ0Q==)

**Comment by KaelWD** [comment] 2023-11-14 12:45
Duplicate of #17126

**Closed by KaelWD** 2023-11-14 12:45 UTC
Labels: S: triage
