### ISSUE TITLE
[Bug Report][3.0.3] VSelect hide-selected props doesn't work

### ISSUE THREAD

**Issue by vcastro45** [vuetifyjs/vuetify#16227] opened 2022-12-07 09:32 UTC
### Environment
**Vuetify Version:** 3.0.3
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
Write a VSelect with a `hide-selected` prop and select an item in list.
Then, re-open list and see that selected item still visible

### Expected Behavior
selected item must be hidden

### Actual Behavior
selected item is visible

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UctugzAQ/BXLF1op4KqPCyJV+h0hBx5L48Qv2SZVhfj3rg1Rk5A2l7A7w+zMsB3ohzHZqQea08KDNKLy8F4qQopTWhkTH+MgK67mKc4OBDSeIKBbEOuSTgtoS3pm/f5yjtoOSfH/HiMAqedeALJEVYO4x9rzFubLeGgBW/C9VamuD0hYwuychl3ECcMUtGAXBeDoGsuNJw5FA8yl0daTAa90ZCSd1ZIk2FwSyI1WLlAnZ2QdSA+qF+LxjMXkM7ANhwcSY+Yk6bROyLi6XtaVXS73IETglmqHwgWbLKI5uqKTPwxmsoPTCj/oEF7GziOAreckbsIOfYe5pHvvjcsZ65U5fmaNlmyDGLO98lxC2mq5ecmes9c31nLnL/cZOJnWVn85sHixpNHrLO559/3XgRlG3afsZZKdV0FyIcVQ/wQ2taBasGD/9X3DvfJ+gy38h5vY7IhdCq6O7qbGxsUKt7tAGVd0kkZyzEF3P6UwCzs=)

**Comment by KaelWD** [comment] 2022-12-07 09:50
Duplicate of #16226

**Closed by KaelWD** 2022-12-07 09:50 UTC
Labels: duplicate
