### ISSUE TITLE
Tooltip on FAB doesn't stay in place when scrolled

### ISSUE THREAD

**Issue by d3radicated** [vuetifyjs/vuetify#2309] opened 2017-10-24 18:00 UTC
### Steps to reproduce
1. Create a bottom right fixed fab with a left tooltip.
2. Hover over the fab.
3. Scroll the window.

### Versions
Vuetify 0.16.9

### What is expected ?
Tooltip should stay in place with the fab.

### What is actually happening ?
The tooltip also scrolls with the window.

### Reproduction Link
https://codepen.io/dEradicated/pen/oGrWPP?editors=1010

**Comment by KaelWD** [comment] 2017-10-24 18:05
This is basically #1551

**Comment by johnleider** [comment] 2017-11-01 00:48
Seeing as `v-tooltip` inherits the behavior from `v-menu` via the **menuable** mixin, I'm closing this as a duplicate of the above mentioned issues.

**Closed by johnleider** 2017-11-01 00:48 UTC
Labels: pending review
