### ISSUE TITLE
[Feature Request] Add non-selectable (aka readonly) property for v-chip

### ISSUE THREAD

**Issue by Traxo7** [vuetifyjs/vuetify#4656] opened 2018-07-18 17:00 UTC
### Problem to solve
`<v-chip disabled>` currently makes chips non-selectable. 
However, it also greys out the label text which is sometimes not desired.

### Reproduction
https://codepen.io/anon/pen/VBKKLp

### Proposed solution
Add property to v-chip e.g. `readonly` so we can use it like so: `<v-chip readonly>`. 
 It should make chip non-selectable, but not grey out the text (i.e. it would look like "normal" chips).

### Comments
(scroll down to `states`: https://material.io/design/components/chips.html#input-chips)

There is an issue which proposed this to be default state: https://github.com/vuetifyjs/vuetify/issues/3817. Note: afaik at the time of proposal, `disabled` made chips non-selectable, but they looked normal. So we could consider that also.

**Comment by KaelWD** [comment] 2018-07-19 06:50
I'm going to mark this as a duplicate of #3817, disabled chips weren't greyed out when that was opened.

**Closed by KaelWD** 2018-07-19 06:50 UTC
