### ISSUE TITLE
[Bug Report] hideDetails ignored on selection controls

### ISSUE THREAD

**Issue by SeregPie** [vuetifyjs/vuetify#5532] opened 2018-11-06 12:56 UTC
### Versions and Environment
**Vuetify:** 1.3.5
**Last working version:** 1.2.10
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 10

### Steps to reproduce
Set `hide-details` property on a selection control to `true`.

### Expected Behavior
`v-input__slot` has `margin-bottom` set to `0`.

### Actual Behavior
`v-input__slot` has `margin-bottom` set to `12`.

### Reproduction Link
<a href="https://codepen.io/SeregPie/pen/yQNWgr" target="_blank">https://codepen.io/SeregPie/pen/yQNWgr</a>

### Other comments
The order of css rules is wrong.
![](https://puu.sh/BXfBz/770f2dda06.png)

**Comment by KaelWD** [comment] 2018-11-06 13:07
Duplicate of #5404

**Closed by KaelWD** 2018-11-06 13:07 UTC
