### ISSUE TITLE
[Bug Report] Extra space in v-select

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#10106] opened 2020-01-03 07:46 UTC
### Environment
**Vuetify Version:** 2.2.1
**Vue Version:** 2.6.11
**Browsers:** Firefox 71.0
**OS:** Ubuntu undefined

### Steps to reproduce
When I create a v-select with very short text for options, that v-select is very wide with a lot of empty space.

### Expected Behavior
V-select should by default be only as wide as it is necessary by the contents, not more.

### Actual Behavior
It is 200px wide.

### Reproduction Link
<a href="https://codepen.io/mitar/pen/mdyqmyG" target="_blank">https://codepen.io/mitar/pen/mdyqmyG</a>

### Other comments
If I use the following, the width of the select is as I would expect:

```
.v-select__selections input {
    width: 0;
}
```

I am not sure why that `input` is there at all?

**Comment by KaelWD** [comment] 2020-01-03 07:59
Duplicate of #6275

**Closed by KaelWD** 2020-01-03 07:59 UTC
Labels: triage
