### ISSUE TITLE
Autocomplete stays open when bound with v-model

### ISSUE THREAD

**Issue by mi1971** [vuetifyjs/vuetify#5001] opened 2018-08-31 09:11 UTC
### Versions and Environment
Vuetify: 1.2.1
Vue:
Browsers:
OS:

### Steps to reproduce
Put autocomplete on page. Give it a v-model

### Expected Behavior
Should close when selecting an item from list

### Actual Behavior
Stays open

### Reproduction Link
https://codepen.io/mi1971/pen/pORwpq

**Comment by KaelWD** [comment] 2018-08-31 09:28
Duplicate of #4663

**Closed by KaelWD** 2018-08-31 09:28 UTC
