### ISSUE TITLE
[Bug Report] Cannot close v-select or v-autocomplete dropdown with append-icon arrow

### ISSUE THREAD

**Issue by ishutka** [vuetifyjs/vuetify#6650] opened 2019-03-01 10:57 UTC
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.2
**Browsers:** Chrome 72.0.3626.119
**OS:** Windows 10

### Steps to reproduce
1)click on the v-autocomplete or v-select append icon to expand and display the dropdown
2)click on the v-autocomplete or v-select append icon a second time

### Expected Behavior
when dropdown menu is opened click on append icon(arrow)  should close the dropdown .

### Actual Behavior
It is trying...but input(parent) event breaks it

### Reproduction Link
<a href="https://codepen.io/anon/pen/WJJeXr" target="_blank">https://codepen.io/anon/pen/WJJeXr</a>

### Other comments
There was similar [issue](https://github.com/vuetifyjs/vuetify/issues/4033) and it was closed.

**Comment by jacekkarczmarczyk** [comment] 2019-03-10 17:06
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6564

**Closed by jacekkarczmarczyk** 2019-03-10 17:06 UTC
