### ISSUE TITLE
[Bug Report][3.3.1] Problem to Display Booleans on Vuetify3 dataTable

### ISSUE THREAD

**Issue by simonklimek** [vuetifyjs/vuetify#17565] opened 2023-06-09 09:33 UTC
### Environment
**Vuetify Version:** 3.3.1
**Vue Version:** 3.3.0
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
any boolean values are hidden I tried workaround but nothing helps 
  <template v-slot:item.active="{  item }">
     <v-icon >
	{{ getString(item.active) }}
     </v-icon>
</template>

### Expected Behavior
display Booleans in table

### Actual Behavior
doesnt' display Booleans in table

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlUsFOwzAM/RUrl4LUNoJxqgaCI9+w7pC1nghr0yjxiqap/46bpmPaEJrEKfGz4+f3nNVRvFmb93sUhVgStrZRhC+lAVj2mbI2XENQdYaUNugiFMBakcpIbRqE4gNVjc4/lyLeSgGF5p4jFE4G5NxQXnYckYlwKc8G4dBXTlsCj7Sf5tGt7RzBERxuYYCt61pIWEMylgNwX08Qh4BnWE2Ux3lu0tRgAcl7naQztsMDI/qEDPE8nqpVRbrHJI2lMYyF6x/eoJRZeba7mRmm6gK2qvGYgq4LeDjj+CX9+Hd6MRPfj35NDrE3IhWTOVmrbP7pO8N7DcJ5BSHBSyhmK0rBpo0xr4zI+kLKqjb8rMZG9y43SNLYVr5ymXR7Q7rFrO7a10W+yJ9krT2dwzn6Ntu47suj4yaliAICDent4QaqWBkYFhNDhLJGbfxIcdVaMl+PLnNoeOPoblV08exc1UXqStnIPpRmYL8bbXb+wurKB5vj+v8pOTSLn2wQQyrCnMwcHoj1N7NjOs8=)

**Comment by websitevirtuoso** [comment] 2023-06-19 16:29
wrap your boolean to string.  -> 'false' or 'true'

**Comment by KaelWD** [comment] 2023-09-25 13:16
Duplicate of #17810

**Closed by KaelWD** 2023-09-25 13:16 UTC
Labels: S: triage
