### ISSUE TITLE
[Bug Report] v-dialog content-class does not accept object or array

### ISSUE THREAD

**Issue by Flamenco** [vuetifyjs/vuetify#7206] opened 2019-05-14 11:30 UTC
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 76.0.3788.1
**OS:** Mac OS 10.14.4

### Steps to reproduce
 ```html
<v-dialog :value="true" :content-class="{foo:true, bar:true}">
```

### Expected Behavior
```html
<div class="v-dialog foo bar v-dialog--active">
```

### Actual Behavior
```html
<div class="v-dialog [object Object] v-dialog--active">
```

### Reproduction Link
<a href="https://codepen.io/anon/pen/zQoWPJ" target="_blank">https://codepen.io/anon/pen/zQoWPJ</a>

### Other comments
Vuetify documentation states this attribute should accept any type, and the Vue convention for class attributes should be respected.

Vuetify does work for an `array` either.  It inserts a comma separated string of the array values.

**Comment by jacekkarczmarczyk** [comment] 2019-06-12 07:29
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7125

**Closed by jacekkarczmarczyk** 2019-06-12 07:29 UTC
Labels: triage
