### ISSUE TITLE
[Bug Report] Blur event for v-combobox adds the current filter text as a new item

### ISSUE THREAD

**Issue by AirDur** [vuetifyjs/vuetify#13121] opened 2021-02-16 19:04 UTC
### Environment
**Vuetify Version:** 2.4.4
**Vue Version:** 2.6.11
**Browsers:** Firefox 85.0
**OS:** Windows 10

### Steps to reproduce
* Click in Location field
* Type B
* Click the B3 item
* Click everywhere expect the Location field

**OR**

* Click in Location field
* Type B
* Click everywhere expect the Location field

### Expected Behavior
Expect the `B3` item to be added without anything else.
**OR**
The filter text stills show `B` and it is not added until we press Enter.

### Actual Behavior
`B3` item gets added along with a new item `B` from the typed filter text.
**OR**
`B` item gets added from the typed filter text.

### Reproduction Link
<a href="https://codepen.io/AirDur/pen/abBWdVm" target="_blank">https://codepen.io/AirDur/pen/abBWdVm</a>

### Other comments
If you want to keep the "adding an item after blur event" behavior, it can be cool to add an option to switch behavior between "adding after blur event" and "keep the text after blur event".

**Comment by MajesticPotatoe** [comment] 2021-02-16 19:25
Looks like a duplicate of #8842

**Comment by KaelWD** [comment] 2021-02-23 07:35
Duplicate of #8842

**Closed by KaelWD** 2021-02-23 07:35 UTC
Labels: triage
