### ISSUE TITLE
[Bug Report] VDrawer: expand-on-hover bug when modified from the inside of the drawer

### ISSUE THREAD

**Issue by hector** [vuetifyjs/vuetify#11545] opened 2020-06-02 15:56 UTC
### Environment
**Vuetify Version:** 2.2.30
**Last working version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Mac OS 10.15.5

### Steps to reproduce
- Disable expand on hover with the switch INSIDE the drawer (main app content width is reduced correctly)

- Enable expand on hover with the switch INSIDE the drawer (main app content width is NOT expanded correctly)

### Expected Behavior
v-content resizing

### Actual Behavior
v-content NOT resizing

### Reproduction Link
<a href="https://codepen.io/hparra/pen/mdVddrY?editors=1010" target="_blank">https://codepen.io/hparra/pen/mdVddrY?editors=1010</a>

### Other comments
This seem to come from trying to solve this very similar issue:
https://github.com/vuetifyjs/vuetify/issues/10862

**Comment by hector** [comment] 2020-09-14 15:22
I have tried this with v2.3.10 and it is still happening.
I have the suspicion it has to do with having the mouse hovering the v-navigation-drawer because it works correctly it the button triggering the change is outside of the drawer.

**Comment by johnleider** [comment] 2020-12-16 18:22
Duplicate of #8223

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-16 18:22 UTC
Labels: C: VNavigationDrawer, T: bug
