### ISSUE TITLE
[Bug Report] Open a popup from inside a Speed Dial

### ISSUE THREAD

**Issue by tafel** [vuetifyjs/vuetify#8782] opened 2019-08-29 09:47 UTC
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chromium 76.0.3809.100
**OS:** Ubuntu undefined

### Steps to reproduce
Following the codepen:

+ Click on the speed-dial : two buttons popup
+ Click on button 1 : the v-dialog is defined outside of the speeddial, so the popup popups
+ Click on button 2 : the v-dialog is defined inside of the speeddial, only the overlay is visible

### Expected Behavior
Clicking on button 2 should show the popup.

### Actual Behavior
Only the overlay of the popup, not the content, is visible.

### Reproduction Link
<a href="https://codepen.io/rekam/pen/MWgmxYK" target="_blank">https://codepen.io/rekam/pen/MWgmxYK</a>

### Other comments
The thing is I have a component (let's say RemoveBtn) which is a v-dialog with a button activator, which popups a window asking "Are you sure? yes / no".

This component is used at some places with success, and I would like to reuse it inside the speed dial, which is right now not possible.

**Comment by pascalmattes** [comment] 2019-08-30 07:05
Duplicate of #8219

**Closed** 2019-08-30 07:09 UTC
Labels: triage
