### ISSUE TITLE
[Bug Report] VPagination generated redundant "..." if it is placed inside VDialog

### ISSUE THREAD

**Issue by lkrazy** [vuetifyjs/vuetify#2434] opened 2017-11-07 08:46 UTC
### Versions and Environment
**Vuetify:** 0.16.9
**Vue:** 2.5.3
**Browsers:** Chrome 61.0.3163.100
**OS:** Windows 7

### Steps to reproduce
1. Place the VDataTable and VPagination inside VDialog with number of pages is 2.
2. Click on the **Open Dialog** button, you will see that there are 2 pages, but there are 2 redundant "..." between page 1 and 2. I checked with Vue Devtools and found that **maxButtons** value is -3.
3. If we click on **Restore down** button of browser or resize the browser after opening the dialog, the redundant "..." will be disappeared.

### Expected Behavior
1. No redundant "..." is generated if number of pages does not exceed **total-visible**

### Actual Behavior
1. Redundant "..." is generated in VPagination although number of pages does not exceed **total-visible**

### Reproduction Link
[https://codepen.io/lkrazy/pen/EbgWjJ](https://codepen.io/lkrazy/pen/EbgWjJ)

**Comment by johnleider** [comment] 2017-11-12 23:04
This is caused by `v-pagination` trying to be cute and figure out how many buttons it can at max have. Since the pagination is nested inside the menu, when it is not visible, it has no width. This equates to -3 after the calculations are done.

It fixes itself on resize because the calculation is re-done. The easy way around this is to add the **lazy** prop to `v-dialog`. This will cause the contents to not be rendered until the dialog is activated, allowing the pagination component to have a width to compare to. This however, does not solve the issue with the pagination items changing their length after the contents have been rendered.

This is not the only component that suffers from this. `v-tabs` would be another notable one. Aside from one-off hacks, I'm not sure how we should approach this. Potentially we can explain these use-cases and provide some ways to handle it.

Besides the **lazy** way, you can also hook into the internal method handles this and manually call it:

https://codepen.io/johnjleider/pen/xPdWoL

Does the @vuetifyjs/dev-team have a suggestion otherwise?

**Comment by lkrazy** [comment] 2017-11-13 07:35
Thanks for your looking at this issue.

I forgot to let you know that I did used **lazy** as workaround for this issue. My apology for this omission.

**Comment by jacekkarczmarczyk** [comment] 2017-11-24 12:39
This looks like a duplicate of https://github.com/vuetifyjs/vuetify/issues/1924

**Comment by shanemgrey** [comment] 2018-10-29 20:11
I spent some time trying to isolate this behavior today while working with tabs before I looked for an issue on it.  

It's still happening with `v-tabs` in the current version.  Didn't check `v-dialog`.

Using `<v-tab-item lazy>` does work around the issue, but in my case, it also screws up the transition animation on the first load of some tabs (but not all) for some reason.  

I am not going to try to resolve that animation issue for now.  Just wanted to add the detail about where to add `lazy` inside `v-tabs`.  It's added to the `v-tab-item`

**Comment by johnleider** [comment] 2019-06-19 20:37
Unfortunately this did not make the cut for v2.0. We encounter this same type of issue with **autofocus** and inputs where it doesn't work properly when in a menu/dialog. We are going to have to go back to the drawing board and anyone with suggestions are most appreciated.

**Comment by denisemenov** [comment] 2020-03-13 11:17
`lazy` doesnt fix it for expansion-panel.

**Comment by denisemenov** [comment] 2020-03-13 11:17
https://codepen.io/denisemenov/pen/oNXqBaj?editors=1010

**Closed** 2020-04-01 20:19 UTC
Labels: C: VPagination, T: enhancement
