### ISSUE TITLE
[Bug Report] Buggy styling for absolute (v-)labels inside Selection Controls

### ISSUE THREAD

**Issue by FabianSawatzki1234** [vuetifyjs/vuetify#9890] opened 2019-12-05 12:32 UTC
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.14.6

### Steps to reproduce
Since it is a layout bug, you will see the error immediatly.

### Expected Behavior
The label for the v-input needs the style property top: 18px to have the intended look.

### Actual Behavior
The top property gets overriden with 0 by the styles for class `.v-input--selection-controls.v-input .v-label`
Therefore the label is positioned wrong and behaves falsy. The label even moves out of the actual input space when focussing the input field.

### Reproduction Link
<a href="https://codepen.io/fabiansawatzki1234/pen/gObpGbr" target="_blank">https://codepen.io/fabiansawatzki1234/pen/gObpGbr</a>

**Comment by jacekkarczmarczyk** [comment] 2019-12-05 14:04
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9864

**Closed by jacekkarczmarczyk** 2019-12-05 14:04 UTC
Labels: triage
