### ISSUE TITLE
[Feature Request] Support TSX import-based component for next version

### ISSUE THREAD

**Issue by nour-dev** [vuetifyjs/vuetify#12409] opened 2020-10-12 19:45 UTC
### Problem to solve
Allow import Vuetify components as needed in (jsx, tsx) directly . and this will allow:
- support auto complete in typescript enabled editors for component attributes and events.
- component property type validation.

### Proposed solution
simply expose types & interfaces about the components from the component source file

for vue 3 and vuetify 3

**Comment by KaelWD** [comment] 2020-10-13 06:35
Duplicate of #3036, #5962

I don't know if tsx is different in vue 3, but afaik this wasn't possible without depending on vue-tsx-support.

**Closed** 2021-06-19 14:59 UTC
Labels: T: feature, typescript
