### ISSUE TITLE
[Bug Report][3.4.0-alpha.0] min prop is not working on v-date-picker

### ISSUE THREAD

**Issue by bilalmalkoc** [vuetifyjs/vuetify#18102] opened 2023-08-21 11:43 UTC
### Environment
**Vuetify Version:** 3.4.0-alpha.0
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Just check the results. I set min date but it is not working.

### Expected Behavior
It should prevent to selecting old days from now.

### Actual Behavior
It is allowing select all dates.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtkD9vwjAQxb+K5QWQsI0EUxQqKnXp1IGRMITkKC7xH9kmqEL57j0nQU3DwtAlyj3fvd+7293oq7W8vgBNaBpA2SoP8JJpQtKa5da2v21RGB1yqcH1UiuW2M2sLM7gSM2UKaFaZ7TOq4ySREmNBX6xEHcjMXaKSgdKxSAAlr5w0gbiIVy6HFJZ4wK5EQdH0pCjM4pMMPskthOCvj4QhJN17JhOJrNfGWP0soYreUPIdMaDed9+bIOT+nM6w+ZUdEyk0TntcEzlln95o/FCt+iX9Q8+owlplahhjFhn9BSC9YkQRalxDA8ia8c1BKGtEhtsE+6ig1TASqM2S77kK1FKH4YyB6/YwZmrB4cmGZ0PMEEev59A9Z1IWPEFyyt7yvmiI/VPrMoPPqIeEAK5NTjmQJfgwD272WhsuN3o6WHDSG8y3eDdK6nPfnTywrfn3t1D/svqrWl03EdwM6dtXkzwZ5DufwDsrg17)

**Comment by wambling** [comment] 2023-08-22 01:43
I am facing the same issue for max property as well. I am using version 3.3.13 and both min and max accepts a number value. Both works fine when I give just year. But even then I am able to choose future dates by pressing next icon.

`[Vue warn]: Invalid prop: type check failed for prop "max". Expected Number with value NaN, got String with value "2023-08-22T01:40:02.018Z".`

**Comment by avarixe** [comment] 2023-08-22 03:40
I think this is a duplicate of #18015 and should be resolved in the next release? 🤞

**Closed** 2023-08-22 15:14 UTC
Labels: S: triage
