### ISSUE TITLE
[Documentation] Add examples how to test v-selects and v-autocompletes with Cypress

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#12086] opened 2020-08-20 16:30 UTC
### Problem to solve
https://vuetifyjs.com/en/getting-started/unit-testing/#e-2-e-tests

On this page there is only a simple example on how to test `v-text-field` with Cypress. There should be some additional examples showing how to test `v-select` and `v-autocomplete`. These Vuetify controls are very difficult in E2E testing.

### Proposed solution
Add examples how to test `v-select` and `v-autocomplete` in the E2E testing section.

**Comment by johnleider** [comment] 2020-12-08 15:40
Marking this as a duplicate of #7295 as they are closely related and adding documentation is implied with that task.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-12-08 15:40 UTC
Labels: triage
