### ISSUE TITLE
[Bug Report] VSelect drop-down does not disappear on blur event

### ISSUE THREAD

**Issue by andrew-smythe** [vuetifyjs/vuetify#10721] opened 2020-03-02 18:18 UTC
### Environment
**Vuetify Version:** 1.5.23
**Last working version:** 1.5.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
Open VSelect, click anywhere else on screen.

### Expected Behavior
Clicking off of VSelect should close the VSelect drop-down.

### Actual Behavior
Clicking off of VSelect does not close the VSelect drop-down.

### Reproduction Link
<a href="https://codepen.io/andrewsmythe/pen/jOPwgMw?editable=true&editors=101" target="_blank">https://codepen.io/andrewsmythe/pen/jOPwgMw?editable=true&editors=101</a>

### Other comments
This was likely introduced in [this commit](https://github.com/vuetifyjs/vuetify/commit/49cb28b829fd638f1b54c5e0cef2fcd44153101a).

**Comment by KaelWD** [comment] 2020-03-03 07:13
Duplicate of #10660

**Closed by KaelWD** 2020-03-03 07:13 UTC
Labels: triage
