### ISSUE TITLE
[Feature Request] V3 v-sparkline

### ISSUE THREAD

**Issue by pilotkid** [vuetifyjs/vuetify#18448] opened 2023-10-12 03:08 UTC
### Problem to solve
In past versions of vuetify v-sparkline was available. However, I do not see it in the docs, or the roadmap for V3. Is it going to be added?

### Proposed solution
Port V-SparkLine from V2 to V3

**Comment by websitevirtuoso** [comment] 2023-10-20 02:54
Yes I think it will be added but later

**Comment by danielamguerra** [comment] 2023-11-09 14:01
Any prevision? I'm migrating my project from version 1.5 to 3 and we use v-sparkline.

**Comment by johnleider** [comment] 2024-01-22 03:42
duplicate of #13507

**Closed by johnleider** 2024-01-22 03:42 UTC
Labels: S: triage
