### ISSUE TITLE
[Beta] Date pickers menu

### ISSUE THREAD

**Issue by ecencio** [vuetifyjs/vuetify#1954] opened 2017-09-30 00:58 UTC
### Steps to reproduce
Open a Picker in a menu

### Versions
1.16.0-beta2

### What is expected ?
Div of the menu and picker same size

### What is actually happening ?
The div of the menu is bigger than the picker itself, resulting in some empty space with elevation

### Reproduction Link
In the dev site is happening, so...
[https://dev.vuetifyjs.com/components/pickers](https://dev.vuetifyjs.com/components/pickers)

**Comment by jacekkarczmarczyk** [comment] 2017-09-30 04:55
Might be a duplicate of #1949

**Comment by KaelWD** [comment] 2017-09-30 05:47
Duplicate of #1949

**Closed by KaelWD** 2017-09-30 05:47 UTC
