### ISSUE TITLE
[Bug Report] v-range-slider can no longer select range delta of "0", i.e.: [2,2]

### ISSUE THREAD

**Issue by vincentauger** [vuetifyjs/vuetify#9330] opened 2019-10-11 18:24 UTC
### Environment
**Vuetify Version:** 2.1.3
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.15.0

### Steps to reproduce
In code pen example, initial value is [2,2]. Move the slider and you can no longer select [2,2] or any pair with a range delta of "0".

### Expected Behavior
Range slider should be able to select range delta of "0" within the slider.

### Actual Behavior
Minimum range delta is now 1.

### Reproduction Link
<a href="https://codepen.io/vincentauger/pen/Rwwrwdr?&editable=true&editors=101" target="_blank">https://codepen.io/vincentauger/pen/Rwwrwdr?&editable=true&editors=101</a>

### Other comments
Was using the range slider for minimum, maximum functionality where a user could also pick a single number when a range was not wanted.

**Comment by YipingRuan** [comment] 2019-10-12 15:17
https://github.com/vuetifyjs/vuetify/pull/9218

**Comment by KaelWD** [comment] 2019-10-14 05:52
Duplicate of #8756

**Closed by KaelWD** 2019-10-14 05:52 UTC
Labels: triage
