### ISSUE TITLE
v-tabs overflow displays incorrectly at different zoom levels

### ISSUE THREAD

**Issue by jc275** [vuetifyjs/vuetify#1905] opened 2017-09-26 18:34 UTC
### Steps to reproduce

1. Visit [the official docs for v-tabs](https://vuetifyjs.com/components/tabs) and look at example no. 8 'Pagination'.
2. Vary the browser's zoom level (e.g. `ctrl`+`=`  / `ctrl`+`-` ).

### Versions

Vuetify 0.15, Chromium 61 and Firefox 55

### What is expected ?

Reasonably consistent v-tab overflow layout when zooming in/out.

### What is actually happening ?

Overflow caret button ( `>` ) disappears when zoom level exceeds 100% in Chromium (110% in Firefox). Overflowed tabs are therefore unseen and inaccessible.

(Another minor point: the v-tabs overflow caret button appears black in a `dark`-themed bar, which doesn't seem like intended behaviour.)

### Reproduction Link

https://vuetifyjs.com/components/tabs

**Comment by johnleider** [comment] 2017-09-26 20:01
The color is incorrect. In regards to the zoom, I have not used Chromium, nor is it something we explicitly support. I'll have to look into it.

**Comment by jacekkarczmarczyk** [comment] 2017-09-26 20:28
Icon colors are fixed on dev
And icons visibility looks like duplicate of https://github.com/vuetifyjs/vuetify/issues/1789
Closing (feel free to reopen/comment) if I'm wrong

**Closed by jacekkarczmarczyk** 2017-09-26 20:28 UTC
Labels: bug, enhancement
