### ISSUE TITLE
[Bug Report] Cursor pointer on selection control's label appears on empty space

### ISSUE THREAD

**Issue by EvgenTN** [vuetifyjs/vuetify#11070] opened 2020-04-09 14:11 UTC
### Environment
**Vuetify Version:** 2.2.21
**Last working version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.92
**OS:** Linux x86_64

### Steps to reproduce
To reproduce the issue just open https://vuetifyjs.com/en/components/selection-controls// -> section 'usage' or 'examples' and hover the cursor on empty space to the right of the label

### Expected Behavior
Cursor Pointer should appear only on label hover

### Actual Behavior
Cursor pointer on selection control's label appears on empty space

### Reproduction Link
<a href="https://codepen.io/evgentn/pen/OJyJgGd?editable=true&editors=101" target="_blank">https://codepen.io/evgentn/pen/OJyJgGd?editable=true&editors=101</a>

### Other comments
Seem's like the problem is in style 'flex: 1 1 auto;' in ".v-input--selection-controls .v-input__slot > .v-label, .v-input--selection-controls .v-radio > .v-label ", but I'm not sure that removing it will not break anything else.

**Comment by Nettsentrisk** [comment] 2020-04-13 22:09
Good catch, noticed this myself now too. Big usability no-no.

**Comment by emanuelmutschlechner** [comment] 2020-05-12 22:51
This is easily solved by changing the `flex-grow` css property of the label.

https://codepen.io/emanuelmutschlechner/pen/ZEbjWzB

**Comment by KaelWD** [comment] 2021-11-23 18:01
Duplicate of #12278

**Closed by KaelWD** 2021-11-23 18:01 UTC
Labels: T: bug, C: Selection controls
