### ISSUE TITLE
[Bug Report] Word Wrapping in Card Title breaks words before wrapping the line.

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#9130] opened 2019-09-27 14:46 UTC
### Environment
**Vuetify Version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a card and restrict it's width. Put in a long string into the title component of the card. Observe how the words are broken instead of the line.

### Expected Behavior
When the card title component is too narrow to contain it's text, it should line wrap first, then word break if a word is on its own line and is going to overflow.

### Actual Behavior
The card title breaks the word before it wraps the line.

### Reproduction Link
<a href="https://codepen.io/MatthewAry/pen/WNeWmPp" target="_blank">https://codepen.io/MatthewAry/pen/WNeWmPp</a>

### Other comments
A solution is provided in the codepen in the form of a css class.

Also see: https://drafts.csswg.org/css-text-3/#word-break-property and note that this solution might not be appropriate for some languages.

**Comment by dnl13** [comment] 2019-10-16 06:07
Yes, think it is a bug as well. 
I can't imagine that `word-break: break-all;` is intendet. 

affected Components: `v-card-text | v-card-title |  v-card`
affected Class: ` v-card__text | v-card__title | v-card`

 `.v-card__text` is receiving this value from `.v-card` but `.v-card__title` got this value on its own 


temporary solution:
```
/* your css */

.v-card-text, .v-card__title {
  word-break: normal; /* maybe !important  */
}
```

**Comment by johnleider** [comment] 2019-10-24 16:52
It was intended, introduced here https://github.com/vuetifyjs/vuetify/commit/81af19dbd46aa34d017a292f89bc7d91b19bf9ee

Any feedback is appreciated, it was the best option for all browsers. There were a few better options but they were trashed on IE11.

**Comment by MatthewAry** [comment] 2019-10-24 16:58
Was IE11 the only browser holding back a better solution?

**Comment by BotellaA** [comment] 2019-10-25 09:39
I understand the goal to be compliant with all browers. However, it is now quite hugly and hard to read by default.

Maybe a new VCard prop could ease this configuration.

**Comment by lucien-stavenhagen** [comment] 2019-11-03 15:34
I agree, this is highly reprehensible behavior, so in my view this is probably not a good tradeoff for IE 11 support. I agree with the idea of a special prop also.

**Comment by mrodal** [comment] 2019-11-05 03:14
I also agree that this is an ugly default option.. the css workaround should be for those having problems on ie11

**Comment by dnl13** [comment] 2019-11-05 09:11
I am not shure how sass/scss and/or building tools are able to handle CSS-Hacks but maybe we can separate this "special problem" via CSS-Hack? indeed it will not be the best solution. 

eg: 
IE11 only
`_:-ms-fullscreen,
:root .selector {
    property: value;
}`

or IE 9-11
`_::selection,
.selector {
    property: value\0;
}
`


IE11 only SCSS 
```
/*--- Only IE ≤ 11 ---*/
@mixin only_ie11($selector, $map){
	@media all and (-ms-high-contrast:none){
		*::-ms-backdrop, #{$selector} {
			@each $property, $value in ($map) {
				#{$property}: $value+\0;
			}
		}
	}
}
```
this one taken from: [saadeghi/browser-hack-sass-mixins](https://github.com/saadeghi/browser-hack-sass-mixins/blob/master/_hacks.scss)

**Comment by mrodal** [comment] 2019-11-05 14:39
Looking at the [roadmap](https://vuetifyjs.com/en/introduction/roadmap), the 2.3 release with preconfigurable components seems like a good place to add a parameter for this issue

**Comment by MatthewAry** [comment] 2019-11-15 19:08
It's also worth noting that Microsoft won't be installing IE by default on Windows anymore.

**Comment by ErnieAyon** [comment] 2019-11-18 22:52
Thanks for the comments, I thought I was missing something with all my card-titles breaking mid-word.  It makes my app look ugly and hard to read.  I also vote against the word break by default.

**Comment by alatella87** [comment] 2019-11-19 00:09
@dnl13 thanks a bunch.

**Comment by Jonskadev** [comment] 2019-11-20 05:50
Agree with using a prop in v-card to change the word-breaking property, specially because IE is less and less used every day that passes.
I'll stick with the raw css solution for now though, not like I have any other option.

**Comment by MatthewAry** [comment] 2020-01-24 19:55
I think that modern browsers should be supported first and foremost before we try to make special accomodations for IE. There are plenty of ways for doing CSS that is exclusive to IE and CSS that is ignored by IE. This word break behavior is glaring, and makes a distraction for users who encounter it as they have to make extra mental effort to understand the contents of the card title by putting the fragmented words together.

So if support for IE is a serious concern, then there are harder but better paths to solving this. Personally, I think that browsers should use their default text wrapping behavior for something like this.

**Comment by 1beb** [comment] 2020-04-23 02:31
+1 for getting rid of this by default.

**Comment by mrts** [comment] 2020-05-20 10:00
Can we fix this in v3?

**Comment by 1beb** [comment] 2020-05-20 20:24
For passerby, this is how I fixed it on compnents that have the problem: 

```
// someComponent.vue
...

<style>
.v-card__text,
.v-card__title {
  word-break: normal;
}
</style>
```

**Comment by maxiqboy** [comment] 2020-06-12 10:35
please fix that,

**Comment by izman48** [comment] 2020-07-24 11:07
I would love for the prop to be added to fix that

**Comment by manonthemat** [comment] 2020-08-11 17:19
This kinda screwed up my morning. Would love a fix.

**Comment by fergusmeiklejohn** [comment] 2020-08-14 06:48
I just spent some time fixing this bug too :-(

**Comment by tux2nicolae** [comment] 2021-01-20 20:21
Any news on this?

**Comment by clarence89** [comment] 2021-01-25 10:44
I Wonder too.. gives me headache to fix this.. anyone with workaround with this please?

**Comment by OBrown92** [comment] 2021-01-25 11:01
The workaround from @dnl13 is working fine for me.

**Comment by lxr900** [comment] 2021-05-12 10:38
Having the same issue here, hoping it will get fixed soon!

**Comment by johnleider** [comment] 2021-05-22 20:38
fixed in c44edc18f

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-05-22 20:38 UTC
Labels: C: VCard, T: bug, V3: Phase 2

**Comment by YannikWeissenfels** [comment] 2022-08-25 17:57
> Yes, think it is a bug as well. I can't imagine that `word-break: break-all;` is intendet.
> 
> affected Components: `v-card-text | v-card-title | v-card` affected Class: ` v-card__text | v-card__title | v-card`
> 
> `.v-card__text` is receiving this value from `.v-card` but `.v-card__title` got this value on its own
> 
> temporary solution:
> 
> ```
> /* your css */
> 
> .v-card__text, .v-card__title {
>   word-break: normal; /* maybe !important  */
> }
> ```

I'm using Vue 3 and classes changed. This worked for me:

.v-card-text, .v-card-title {
  white-space: normal; /* maybe !important  */
}

**Comment by MartinX3** [comment] 2023-01-28 12:20
Currently the best solution for vuetify 2.6
```
[class*='text'] {
    white-space: normal;
}

.v-card__title {
    word-break: normal;
}
```

**Comment by egorvdovenko** [comment] 2023-12-12 09:12
Actually, there is an appropriate variable:
https://v2.vuetifyjs.com/en/api/v-card/#sass-card-title-word-break
