### ISSUE TITLE
v-select doesn't trigger event change

### ISSUE THREAD

**Issue by jpfong** [vuetifyjs/vuetify#264] opened 2017-03-24 21:56 UTC
Here the [codepen](http://codepen.io/jpfong/pen/XMYVwo).
v-select only trigger an event called 'input' everytime a value is set to it.
It would be better to have an event when a value is changed by the user.

**Comment by mfferreira** [comment] 2017-03-24 22:17
@jpfong Not sure I understand what you're asking for.
Your codepen seems to be doing what you just said it should.

**Comment by jpfong** [comment] 2017-03-24 23:30
The 'change' event is never triggered. The 'input' event is called when the page is loaded, I don't want that. 

When a value is selected, the 'input' event is called 2 times.

This is not what I'm looking for because I want to only call a method when the user selects a value.

**Comment by johnleider** [comment] 2017-03-25 20:11
Can you see if this is fixed for you on the dev branch? I am unable to reproduce what you are talking about. As far as the change event, it's the input event, which is also consequently whatever property you have bound in the model, which you can easily watch for changes on any of those.

**Comment by jpfong** [comment] 2017-03-26 13:20
Have you take a look at the codepen? input event is called with the initial values. And if I select a value it is called 2 times.

**Comment by johnleider** [comment] 2017-03-26 14:08
Yes, the double emit is fixed on dev.

**Comment by jpfong** [comment] 2017-03-27 01:06
Will it emit for the initial value? It would be better not to, what do you think?

**Comment by johnleider** [comment] 2017-03-27 12:20
I'm not sure what your question is.

**Comment by jpfong** [comment] 2017-03-27 12:39
The input event is triggered by:
- mounting a component 
- selecting a different value

The event should only occur when the value of an element has been changed.

**Comment by johnleider** [comment] 2017-03-27 12:41
What I'm saying is this is not present on DEV and may have been fixed.

**Comment by jpfong** [comment] 2017-03-27 12:43
Great 👍

**Comment by johnleider** [comment] 2017-03-28 01:50
Going through this again on DEV, everything seems to be in order. If you want, you can pull down and build locally, or re-open if still present for you after next release.

**Closed by johnleider** 2017-03-28 01:50 UTC
Labels: bug
