### ISSUE TITLE
[Feature Request] Datatable sort by date using different formats

### ISSUE THREAD

**Issue by ireviol** [vuetifyjs/vuetify#4372] opened 2018-06-22 09:31 UTC
### Problem to solve
Datatable default sorting sort date by first number in string.

### Proposed solution
Sorting by date using a selected format for date, without use custom sorting

**Comment by KaelWD** [comment] 2018-06-22 09:45
Duplicate of #3829

**Closed by KaelWD** 2018-06-22 09:45 UTC
