### ISSUE TITLE
[Bug Report] v-footer doesn't work with dynamic content height

### ISSUE THREAD

**Issue by vcavallo** [vuetifyjs/vuetify#11121] opened 2020-04-15 15:58 UTC
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Firefox 75.0
**OS:** Ubuntu undefined

### Steps to reproduce
The issue can be clearly seen in the codpen without taking any steps.

Additional tweaks to help highlight the problem are in the comments below.

### Expected Behavior
The footer height and navigation drawer clipping should be calculated correctly no matter the amount of content in the footer.

### Actual Behavior
The navigation-drawer clipping does not seem to be calculated correctly.

### Reproduction Link
<a href="https://codepen.io/vcavallo/pen/VwvePdY" target="_blank">https://codepen.io/vcavallo/pen/VwvePdY</a>

### Other comments
-  when the `app` prop is used on the `v-navigation-drawer`, the drawer will overlap the footer
- if that prop is removed, the overlap ceases, but the drawer is now too short - and the content layout is messed up, as expected.
- if content is removed from the footer so that it is less tall, the overlap is also resolved. but a tall footer is desired for this project
- it has been suggested to set a height on the footer, but that is not feasible for this project

An additional weird thing I noticed in my dev environment that I can't represent in the codepen is that when the app prop is removed/added and hot module reloading triggers, the clipping **is indeed calculated correctly**, but it breaks again after a page refresh through the browser.

overlap:

![image](https://user-images.githubusercontent.com/3201135/79359284-69d51d00-7f10-11ea-9bc6-eae9d94d550e.png)

**Comment by MajesticPotatoe** [comment] 2020-04-15 16:16
Note: This is being caused by the height of the `v-navigation-drawer` not recalculating its height when the `v-footer` height is changed be its child content. (likely due to the footer not updating `application.footer`)
<https://codepen.io/majesticpotatoe-the-bashful/pen/QWjypKV>

**Comment by basebandit** [comment] 2020-05-03 13:32
Any workaround for this yet

**Comment by abodity** [comment] 2020-06-11 15:40
I have the same problem. Is there a solution to the problem?

**Comment by abodity** [comment] 2020-06-11 16:44
In addition, I saw that when the screen size changes and the footer height changes, the lower padding of v-content is not recalculated.

**Comment by michelsouzafigueiredo** [comment] 2020-06-18 11:47
Same problem here, this started after the 2.3 update. If i remove the app prop from the footer, save, readd and then save again, all comes back to normal, but after the first page refresh the navigation overlap the footer.

![Screenshot_1](https://user-images.githubusercontent.com/26716948/85016553-53318900-b140-11ea-9d87-10fd110d5caa.png)

**Comment by johnleider** [comment] 2020-12-10 16:48
Is anyone able to reproduce this bug without using `v-tooltip`? The workaround I have is to use the **attach** property:

https://codepen.io/johnjleider/pen/ExgNVqY?editors=1010

**Comment by DerSebi96** [comment] 2020-12-11 09:12
You mean like so? https://codepen.io/DerSebi/pen/mdrOpem
This seems not related to `v-navigation-drawer` but to `v-main` being cut off when footer height increases.

**Comment by johnleider** [comment] 2021-03-09 15:38
This is resolved in the new layout system for v3.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-03-09 15:38 UTC
Labels: C: VFooter, C: VNavigationDrawer, Service: Application, T: bug, V3: Phase 1

**Comment by bigsmalloverall** [comment] 2022-10-28 13:01
Is there a workaround for this in Vuetify 2.6? I can't migrate to Vuetify 3.
