### ISSUE TITLE
[Bug Report] v-layout wrap prop is now useless

### ISSUE THREAD

**Issue by vcastro45** [vuetifyjs/vuetify#8005] opened 2019-07-25 09:48 UTC
### Environment
**Vuetify Version:** 2.0.0
**Last working version:** 2.0.0-beta.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Create a `<v-layout row>` and add `wrap` prop. It doesn't change anything because `row` class already add the `flex-wrap: wrap` rule added by the `wrap` prop.

### Expected Behavior
`flex-wrap: wrap` rule should be enable by using `wrap` prop.

### Actual Behavior
`row` class add the `flex-wrap: wrap` rule.

### Reproduction Link
<a href="https://codepen.io/anon/pen/rXLrMY?editors=1010" target="_blank">https://codepen.io/anon/pen/rXLrMY?editors=1010</a>

**Comment by KaelWD** [comment] 2019-07-25 09:49
Duplicate of #7956

**Closed by KaelWD** 2019-07-25 09:49 UTC
Labels: duplicate
