### ISSUE TITLE
[Bug Report] Dropdown menu scrolling not working as expected

### ISSUE THREAD

**Issue by ch-lukas** [vuetifyjs/vuetify#7846] opened 2019-07-16 12:31 UTC
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Safari 12.1
**OS:** Mac OS 10.14.4

### Steps to reproduce
1. Using a mobile phone (portrait mode to reduce the screen length) - open https://vuetifyjs.com/en/
2. Click on the "ecosystem" drop down menu (which should open a long menu that should scroll off the bottom of the screen)
3. Try scrolling to the bottom of the menu

### Expected Behavior
Menu scrolls down

### Actual Behavior
Menu stays static and the web page behind the menu popup scrolls instead. This can also be replicated in the side navigation menu. E.g. 1. Activate side menu. 2. Navigate to bottom of menu. 3. Try scrolling further down. 4. Now try scrolling back up... (same error occurs) (n.b. sometimes you have to deactivate the menu and then reactivate it at this point to get the error).

### Reproduction Link
<a href="https://codepen.io/chluke/pen/ageWOd" target="_blank">https://codepen.io/chluke/pen/ageWOd</a>

**Comment by johnleider** [comment] 2019-07-17 01:23
The particular issue happens in the documentation because I have an explicit max height set which on a smaller phone has the potential to be greater than the screen's vertical height.

If this is not the issue, could you please show a small gif of what is happening? Thank you!

**Comment by ch-lukas** [comment] 2019-07-17 11:00
No worries - attached GIFs below. FYI, I do a lot of testing on mobile and found the same behaviour on real iPhones (and not just the emulators). 

![2019-07-17 20 51 57](https://user-images.githubusercontent.com/20023331/61370292-6bb47600-a8d5-11e9-8908-fd2002174560.gif)

![2019-07-17 20 55 12](https://user-images.githubusercontent.com/20023331/61370299-70792a00-a8d5-11e9-9f18-0ad9af50dcaa.gif)

**Comment by johnleider** [comment] 2019-07-29 21:53
I've resolved the issue with our own docs being messed up, however:

- I can't reproduce what you have in the second gif in v2

**Comment by ch-lukas** [comment] 2019-07-31 00:48
For the second gif - try:
- Open side navigation and scroll to bottom of list
- After reaching the end of the list, try scrolling down further (this should activate the bad behaviour)
- If not, try hiding the navigation and reopen it and try the above steps again

**Comment by KaelWD** [comment] 2019-07-31 01:06
Duplicate of #3875

**Closed by KaelWD** 2019-07-31 01:06 UTC
Labels: help wanted, needs more information, platform specific
