### ISSUE TITLE
[Bug Report] v-date-picker (rang & clearable)，whan clear has a bug

### ISSUE THREAD

**Issue by waynerQiu** [vuetifyjs/vuetify#10897] opened 2020-03-20 16:05 UTC
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.106
**OS:** Mac OS 10.15.3

### Steps to reproduce
1.v-date-picker (rang & clearable)
2.select start date and last date
3.ok
4.clear (clearable) -> has error
5.select start date and …… oh mygad~~

### Expected Behavior
v-date-picker (rang & clearable)，whan clear has a bug

### Actual Behavior
v-date-picker (rang & clearable)，whan clear has a bug

### Reproduction Link
<a href="https://codepen.io/waynerQiu/pen/LYVBBZQ?editors=1011" target="_blank">https://codepen.io/waynerQiu/pen/LYVBBZQ?editors=1011</a>

**Comment by ElijahKotyluk** [comment] 2020-03-20 16:31
Duplicate of #9529

**Closed** 2020-03-21 01:13 UTC
Labels: C: VDatepicker, duplicate
