### ISSUE TITLE
[Documentation] Cannot scroll when overlay enabled on Magento Forests

### ISSUE THREAD

**Issue by Skrayvee** [vuetifyjs/vuetify#15706] opened 2022-08-29 13:01 UTC
### Environment

**Browsers:** Firefox 104.0
**OS:** Android 12

### Steps to reproduce
On mobile:

Tap on card with title Magento Forests

### Expected Behavior
Scroll

### Actual Behavior
Blocked scroll

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/components/overlays/" target="_blank">https://next.vuetifyjs.com/en/components/overlays/</a>

### Other comments
https://www.veed.io/view/3842634b-1bda-483a-92a3-ebe6f08724dc

**Comment by KaelWD** [comment] 2022-08-29 14:19
Duplicate of #15653

**Closed by KaelWD** 2022-08-29 14:19 UTC
