### ISSUE TITLE
[Bug Report] Font-Awesome icon doesn't scale down when used in fab v-btn

### ISSUE THREAD

**Issue by StratusBase** [vuetifyjs/vuetify#3503] opened 2018-03-08 11:15 UTC
### Versions and Environment
**Vuetify:** 1.0.5
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.13.3

### Steps to reproduce
Create a standard fab button and then add an icon that uses the font-awesome library (v5.0.8).

### Expected Behavior
Icon scales according to button size

### Actual Behavior
Icon is much larger than desired size

### Reproduction Link
[https://codepen.io/anon/pen/JLPVLo?&editors=100](https://codepen.io/anon/pen/JLPVLo?&editors=100)

### Other comments
I have the font-awesome icons loaded via their SVG / JS method:
`<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>`

**Comment by StratusBase** [comment] 2018-03-08 11:31
.btn--floating .icon {
    height: inherit;
    **width: inherit;**
}

The width style appears to be the culprit, as soon as I disabled that the buttons looked great with the FA SVG icons.

**Comment by KaelWD** [comment] 2018-03-14 08:30
FA5's js doesn't play nice with vue: https://github.com/vuetifyjs/vuetify/issues/3505#issuecomment-371560727

**Comment by StratusBase** [comment] 2018-06-21 14:30
**My temporary solution (SCSS):**
```
// Temporary Vuetify - FA SVG Icon Fix
.btn--floating .icon {
  height: inherit;
  width: inherit;

  &.svg-inline--fa.fa-w-16 {
    width: 1em;
  }
}
```

**Comment by KaelWD** [comment] 2018-11-07 08:40
I'll count this as a duplicate of #3505, the js version of fontawesome is not supported at this time.

**Closed by KaelWD** 2018-11-07 08:40 UTC
Labels: T: bug
