### ISSUE TITLE
Autocomplete positioning is completely off on mobile devices

### ISSUE THREAD

**Issue by ropmansk** [vuetifyjs/vuetify#2216] opened 2017-10-17 18:53 UTC
### Steps to reproduce

1. Visit https://vuetifyjs.com/components/selects on your mobile device
2. Scroll down to autocomplete example, but make sure you scroll to a position where the select component is at the bottom part of your viewpoint / screen
3. Start typing

### Versions
Reproduced on Chrome 61.0.3163.98, Android 6.0

### What is expected ?
Autocomplete suggestions positioned that the user can see them without further scrolling

### What is actually happening ?
Suggestions are displayed far above the select component, on my screen they are completely invisible without scrolling. 

This is caused by the virtual keyboard and the automatic scrolling a browser performs after displaying the keyboard. The issue is that the internal vertical scroll offset is not updated after the page is scrolled by the keyboard. I fixed this by adding a single line to the beginning of _calculatedTop_ method in **VMenu.js**

`this.checkForWindow();`

### Reproduction Link
https://vuetifyjs.com/components/selects

**Comment by KaelWD** [comment] 2017-10-18 04:15
Duplicate of #2111

**Closed by KaelWD** 2017-10-18 04:15 UTC
