### ISSUE TITLE
[Bug Report] Tab overflow

### ISSUE THREAD

**Issue by AnodoubleA** [vuetifyjs/vuetify#7764] opened 2019-07-06 07:10 UTC
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Windows 10

### Steps to reproduce
Look this:
      In all tab components, when first click the tab title, the tab content will overflow the container, how to fix it?

### Expected Behavior
Look this:
      In all tab components, when first click the tab title, the tab content will overflow the container, how to fix it?

### Actual Behavior
Look this:
      In all tab components, when first click the tab title, the tab content will overflow the container, how to fix it?

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

### Other comments
Look this:
      In all tab components, when first click the tab title, the tab content will overflow the container, how to fix it?

**Comment by jacekkarczmarczyk** [comment] 2019-07-06 14:42
Closing as it's most probably the duplicate of https://github.com/vuetifyjs/vuetify/issues/7102, we'll reopen if you provide a repro and if it's a different issue

**Closed by jacekkarczmarczyk** 2019-07-06 14:42 UTC
Labels: S: needs reproduction, invalid, triage
