### ISSUE TITLE
[Feature Request] Add transform-origin for v-tooltip

### ISSUE THREAD

**Issue by vintprox** [vuetifyjs/vuetify#11043] opened 2020-04-06 19:45 UTC
### Problem to solve
Getting variative appear animations by altering `transform-origin` CSS property of `<v-tooltip>` with help of designated prop.

### Proposed solution
Provide property in `<v-tooltip>` for directly changing `transform-origin` of tooltip.

**Comment by KaelWD** [comment] 2021-08-13 16:59
Duplicate of #7568

**Closed by KaelWD** 2021-08-13 16:59 UTC
Labels: T: feature, C: VTooltip
