### ISSUE TITLE
[Bug Report][2.4.2] v-file-input :multiple property check bug

### ISSUE THREAD

**Issue by ailtariel** [vuetifyjs/vuetify#13881] opened 2021-07-04 16:11 UTC
### Environment
**Vuetify Version:** 2.4.2
**Vue Version:** 2.6.11
**Browsers:** Firefox 90.0
**OS:** Windows 10

### Steps to reproduce
`<v-file-input v-model="value" :multiple="false" />`

### Expected Behavior
value is single File Object.

### Actual Behavior
value is [File Object] array.

### Reproduction Link
<a href="https://codepen.io/ailtariel/pen/GRmpzRX" target="_blank">https://codepen.io/ailtariel/pen/GRmpzRX</a>

### Other comments
current:
isMultiple() {
      return this.$attrs.hasOwnProperty('multiple');
    },

But i think it should be:
isMultiple() {
      return this.$attrs.hasOwnProperty('multiple') && this.$attrs.multiple;
    },

**Comment by KaelWD** [comment] 2021-07-05 08:27
Duplicate of #9530

**Closed by KaelWD** 2021-07-05 08:27 UTC
Labels: triage
