### ISSUE TITLE
[Bug Report] Menu doesn't close when multiple <v-app> on the same page

### ISSUE THREAD

**Issue by d9k** [vuetifyjs/vuetify#13364] opened 2021-04-02 14:52 UTC
### Environment
**Vuetify Version:** 2.4.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 88.0.4324.182
**OS:** Linux x86_64

### Steps to reproduce
Open menu from 1st application, then click to the background of 2nd application. It wouldn't close.

### Expected Behavior
Menu must be closed on click to the background of 2nd application.

### Actual Behavior
Menu isn't closed on click to the background of 2nd application.

### Reproduction Link
<a href="https://codepen.io/d9k/pen/zYNZXzR" target="_blank">https://codepen.io/d9k/pen/zYNZXzR</a>

**Comment by d9k** [comment] 2021-04-02 14:53
#4931 reincarnation

> @MajesticPotatoe
> Closing Issue for inactivity as a suitable workaround is provided and will be implemented in 2.0.

Bug still appears in Vuetify 2

For quick solution I propose changing these lines 

https://github.com/vuetifyjs/vuetify/blob/v2.4.9/packages/vuetify/src/directives/click-outside/index.ts#L55-L56
https://github.com/vuetifyjs/vuetify/blob/v2.4.9/packages/vuetify/src/directives/click-outside/index.ts#L64-L65

to call of function

```
function getApp() {
  return document.querySelector('[data-vuetify-click-outside-listener]')
    || document.querySelector('[data-app]')
    || document.body
}
```

so you will be able to add `data-vuetify-click-outside-listener='true'` attribute to any DOM element in your html page and this element will listen "click outside" event.

**Comment by KaelWD** [comment] 2021-04-02 14:55
Duplicate of #4931

**Closed by KaelWD** 2021-04-02 14:55 UTC
Labels: triage

**Comment by d9k** [comment] 2021-04-03 14:10
@KaelWD, issue isn't solved, see https://codepen.io/d9k/pen/zYNZXzR

**Comment by KaelWD** [comment] 2021-04-03 14:15
https://codepen.io/kaelwd/pen/KKamZea

**Comment by d9k** [comment] 2021-04-04 12:00
@KaelWD, I see, you changed vuetify version from `2.4.9` to `nightly@dev` (`2.5.0-dev-20210329.0` now)

**Comment by d9k** [comment] 2021-04-04 12:18
@KaelWD, which branch, tag or commit refers to `nightly@dev`?

**Comment by KaelWD** [comment] 2021-04-04 14:22
`dev`

**Comment by d9k** [comment] 2021-04-19 11:35
@KaelWD, sorry, but the bug still appears at `2.4.10` version released today
https://codepen.io/d9k/pen/jOyvYXb

When the solution is going to appear in a production build?
