### ISSUE TITLE
[Bug Report][3.6.10] V-Expansion-Panel with many items causes Range Error on close

### ISSUE THREAD

**Issue by sorabito-takano** [vuetifyjs/vuetify#20124] opened 2024-07-08 23:40 UTC
### Environment
**Vuetify Version:** 3.6.10
**Last working version:** 3.6.9
**Vue Version:** 3.4.21
**Browsers:** Chrome 126.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open the panel, then close it.

### Expected Behavior
Panel will close.

### Actual Behavior
Panel won't close with range error.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9Uu1qgzAUfZWLDNYyq2yw/Si2UPoK/TfH6vTaCjYJSZQOybvvJn7Uot2fJDfn3I+Tk8/GUzINd0IEdYXe2os0XkSZaNzGDCDKitod6Fiv8CoSpgrOVrRjqTpkDhugOXClC13i9mDXKHwE/18Br3rEcJw0kRnUq5zLTewVpAMKBnZXsXfHHdhdp6ZxtMBFYIydaQQ/SLUTQJ+acqaRaUqGW/Zkxg4ZS5uTP86bIfSGTJHWkShsXYvCkZcUqlQWoq1cXASXGhqQmIOBXPILPNMHeLZEACpr4QzzpCqJ1jZUqCuxWPYhAIlW2unf84rEb+Dt/aOtcA/vpEx+CXZ7YLstGiiRnfR5Pco3Piy+fXItw+sSNvS6t4eS1Fyy8Q2pyCjbkuEFXv0x4oxbw3Fvv8RTM5DM8Y7WuWaJnX+PuKY/muVUniJp9JCLQSpxetZ0bpcxlO4KG3dBQRQONsUsDOHAqYSQPKtSBH1G+KlOPnCBzEXOdkhYZiMGackVUocgZp7xWVWWbvn6A2WrOoM=)

### Other comments
It seems VDefaultsProvider is causing this problem.

**Comment by sorabito-takano** [comment] 2024-07-12 05:08
If range error won't occur, please try to increase itemCount (i.g. 500).
FYI, it doesn't seem to occur in Safari.

**Comment by sorabito-takano** [comment] 2024-07-29 07:31
It won't happen Vue 3.5.0 alpha-3 or above. With Vue 3.4.x,(At least 3.4.34 or below) it happens.

**Comment by KaelWD** [comment] 2024-08-16 09:41
Duplicate of #20283

**Closed by KaelWD** 2024-08-16 09:41 UTC
Labels: S: triage
