### ISSUE TITLE
[Bug Report][3.0.4] v-combobox renders all items, taking all available vertical space and not allowing to type

### ISSUE THREAD

**Issue by carlesalbasboix** [vuetifyjs/vuetify#16269] opened 2022-12-12 22:34 UTC
### Environment
**Vuetify Version:** 3.0.4
**Last working version:** 2.6.12
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create combobox with many items.

### Expected Behavior
Only some items should get rendered and updated as the user types. The list of items should not take all vertical space and overlap the input.

### Actual Behavior
All items get rendered, list of items takes all vertical space and overlap input.

### Reproduction Link
[https://codepen.io/carlesalbasboix/pen/ZEoqjEB](https://codepen.io/carlesalbasboix/pen/ZEoqjEB)

**Comment by theo-chmbn** [comment] 2022-12-14 10:56
I'm having the same issue. It seems to be the case with both autocomplete and combobox.

**Comment by KaelWD** [comment] 2022-12-14 13:09
Duplicate of #15587

**Closed by KaelWD** 2022-12-14 13:09 UTC
Labels: S: triage
