### ISSUE TITLE
[Bug Report] <v-icon> location problem in fab

### ISSUE THREAD

**Issue by Tabrizian** [vuetifyjs/vuetify#3257] opened 2018-02-12 12:50 UTC
### Versions and Environment
**Vuetify:** 1.0.0-beta.6
**Vue:** 2.5.0
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
As you can see in the examples section in the reproduction link it already shows the problem

### Expected Behavior
The location of the <v-icon> should be in the center

### Actual Behavior
The location of the <v-icon> is sticked to the corner of the <v-btn>

### Reproduction Link
[https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/floating-action-buttons/speedDial.vue](https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/floating-action-buttons/speedDial.vue)

![image](https://user-images.githubusercontent.com/10105175/36097540-a1a54f8c-1010-11e8-9db7-d7ca4630cc38.png)

**Comment by Failcookie** [comment] 2018-02-13 22:11
Duplicate of #3207 that has been fixed and ready to roll in V1!

**Closed** 2018-02-14 00:17 UTC
Labels: bug
