### ISSUE TITLE
[Bug Report][3.3.3] Autocomplete allows selecting the same item multiple time when return-object is true

### ISSUE THREAD

**Issue by nevaan9** [vuetifyjs/vuetify#17555] opened 2023-06-07 16:27 UTC
### Environment
**Vuetify Version:** 3.3.3
**Last working version:** 2.6.15
**Vue Version:** 3.3.4
**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Click auto complete
2. Select "Nevaan"
3. Type "N" in the search
4. Select "Nevaan" again

### Expected Behavior
After search, the items that were selected before should not be able to be added again. If you select it again, if should get de-selected.

### Actual Behavior
The autocomplete starts with some initial data. However, if you search, do some logic and mutate the data passed into "items" (in real life we make an api call to fetch more data), 2 issues happen.
1. If an item was selected before the search, the item that was selected will not appear as "selected" after the new data gets injected
2. If an item was selected before the search, we are able to select that item again; this allows us to select the same item multiple times

Only happens when return-object is true

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVMlu2zAQ/RVWFzuAJTWxexGcpYcup15SoIcoB0qibKYUSZCU0sDQv3e4KNWSFgaqi8SZ92Z5nNHDKfooZdK1JMqivSGNZNiQm5wjtO9iLKX7dIdScIMpJyqYPKI1ohTAIoYMZoS6uBEVYdd5VCtKeKXzaOHMNMGqPALGf4whGYVKNLgkERB67CqPVOrRkQmNC0biuV0woSBAwVoSHxR5iRk9HA3h8dU4ms0TG2oYASzHzSSVc3YYIoCTVmMXw4Vr754wUpqxp2mZobbmV4siplU8FsWThQbzq4ag4qA6KKOZMJltBWKfkFRC6o2rA/V5NOL4CwEccArKKyuVBecRygz5ZWzBwEoUfk58Wzf71DPGmdPJhf+lHBvonHIY1Sa2zrHdXve0wKk3G8S3xFtb720oeIbTbfEG9KBEK6dY1+hrLf/u1kLHEzwMu5VqMu0O6JZhEgWOulRUGqThkr20tJFCGXSCe6836Bmb8vipruHqUY9qJRq0gmVbWa6dUq4NavQBXVv4evWVMCbQD6FY9W518QfiV2RAjT1hwd5y+eUJngff2glZdTO0use8Uni1QU5CMHyxbzjTKkOXqN/M8J8po1LM8egyMK6WjO9KvCzwVwG/XeK/YQVXsWBsA2P3BoN0GPMFYxcYHwLj0Wkyuon1+gJd36CTD0drtPb6Jm7ZLwYHCgp6M+gYNDxPR3wA9+7DXNBzG3D0y/fTTuzz6D96++qhs33qRxCGL9pEfvriBsvkSQsOP3XXDCyNc8D+ZUN7eQSDaM95dDRG6ixNy4oDDX7OtFMJJyblsknvAJaqlhvakLgSzd022Sa7tIIVG5sTopu4UOJZEwVB8ihU7NIYWr+ckSogXYatzxBMMfxxtU2xCJ1Cvo6oWMEaEEXUuR3NaOOuZq5FZ076nPegN6P8p55JXWonc5iW/2zZBXNTbBP2m8jVCZkdIXr8DbFNZ9k=)

**Comment by KaelWD** [comment] 2023-06-07 16:45
Duplicate of #16279

**Closed by KaelWD** 2023-06-07 16:45 UTC
Labels: S: triage
