### ISSUE TITLE
Autocomplete won't autocomplete with more than 1 option

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#4579] opened 2018-07-11 14:27 UTC
### Versions and Environment
Vuetify: 1.1.4
Vue: 2.5.16
Browsers: Firefox, Chrome, likely all others
OS: Windows

### Previously worked in:
Vuetify: Prior to 1.1.0 (as a v-select with autocomplete)
Vue: Unknown

### Steps to reproduce
1. Enter a partial match to multiple items in the list.
2. Press tab to move on to the next input.

### Expected Behavior
The first option to be selected.

### Actual Behavior
Nothing is selected. If an item had been previously selected successfully in an earlier attempt, it will default back to that match, even if it has nothing to do with the current search.

### Reproduction Link
https://codepen.io/anon/pen/zLxpGJ

**Comment by KaelWD** [comment] 2018-07-11 14:31
Duplicate of #4207

**Closed by KaelWD** 2018-07-11 14:31 UTC
