### ISSUE TITLE
[Enhancement] v-edit-dialog responding slow inside large v-data-table

### ISSUE THREAD

**Issue by chameleonlizzard** [vuetifyjs/vuetify#1897] opened 2017-09-26 12:14 UTC
### Steps to reproduce
I build a `v-data-table` with more than 600 rows. Every row exists of 7 columns. 5 of these columns contains a `<v-edit-dialog>` to edit the value.

### Versions

"vuetify": "^0.15.7"

### What is expected ?

On clicking of an editable value the `v-edit-dialog` open and shows a input. On typing inside the input a expect the typed value is visible within milliseconds.

I also see, that the `v-edit-dialog` is preloaded hidden on the DOM, for every content that is editable inside the `v-data-table`. (ex: I have 400 rows, every row has 5 values that can be edited. The DOM contains then 400x5=2000 invisible `v-edit-dialog`'s)

### What is actually happening ?

On typing inside the input, it sometimes takes up to 10 seconds before the types value is shown.

### Reproduction Link

I have copied the Vuetify `v-data-table` with `v-edit-dialog` from the codepen example and adjusted to reproduce the issue:
https://codepen.io/chameleonlizzard/pen/vegbqL

**Comment by johnleider** [comment] 2017-09-27 02:06
After some initial testing, I'll have to get some second opinions. The first issue is the massive amount of complex components you are rendering at once. Normally these would be paginated and not have any issue whatsoever.

However, from what I've been able to test, while using the v-model directive on **any** input (even a regular ``input type="textt"``), this issue will pop up:

![image](https://user-images.githubusercontent.com/9064066/30892430-b727f566-a306-11e7-98f8-cee7ef2ab4cf.png)

Notice the red ticks at the end. Those are timeout handlers that are taking way too long. Is the issue Vuetify? Maybe. I mean, data-table is a very complex component, combined with multiple scoped slots, regular slots, binded models, etc..you have a lot going on here.

I'll leave this to be looked at again later. While you can visibly see an issue, I don't think that this is a reasonable use-case atm.

**Comment by blalan05** [comment] 2019-04-02 01:34
@nekosaur Was this fixed in the VDataTable refactor? I'm guessing not, since it sounds like a VEditDialog issue more than VDataTable.

**Comment by nekosaur** [comment] 2019-06-17 07:53
While the v-edit-dialog is due for a refactor which might somewhat mitigate the poor performance (lazy loading the dialog for example), the underlying issue is most likely a duplicate of https://github.com/vuetifyjs/vuetify/issues/6201

**Closed by nekosaur** 2019-06-17 07:53 UTC
Labels: C: VDatatable, C: VEditDialog, S: on hold, help wanted
