### ISSUE TITLE
v-select has wrong pointer when I re-compile the style files

### ISSUE THREAD

**Issue by haugero** [vuetifyjs/vuetify#5093] opened 2018-09-14 15:02 UTC
### Versions and Environment
Vuetify: 1.2.2
Vue: 2.5.17
Browsers: Chrome  69.0.3497.92
OS: MacOS 10.13.6

### Previously worked in:
Vuetify: 1.1.12
Vue: 2.5.16

### Steps to reproduce
Make npm install and run the attached vue project with npm
Hover of the v-select and you will see a text-cursor 

### Expected Behavior
Onhover the v-select a pointer should be shown

### Actual Behavior
Cursor of v-select is always "text"

### Reproduction Link
See [vuetify-wrong-cursor.zip](https://github.com/vuetifyjs/vuetify/files/2383823/vuetify-wrong-cursor.zip)

### Additional Comments:
This problem only occurs if I @import '~vuetify/src/stylus/main' to be able to modify stylus variables like it is described here: https://vuetifyjs.com/en/style/theme#stylus-guide
If I just import the vuetify/dist/vuetify.min.css: no problem

**Comment by rnenjoy** [comment] 2018-09-26 14:32
Same problem here!

**Comment by rnenjoy** [comment] 2018-10-02 08:32
This is what screws it up:

![image](https://user-images.githubusercontent.com/6672175/46337671-6334cc80-c62e-11e8-9b29-b6a0f0adb161.png)

@ v-input__slot

**Comment by rnenjoy** [comment] 2018-10-02 08:32
This is overwritten:

![image](https://user-images.githubusercontent.com/6672175/46337716-865f7c00-c62e-11e8-8559-917e42785a5b.png)

**Comment by jacekkarczmarczyk** [comment] 2018-12-02 08:40
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3583

**Closed by jacekkarczmarczyk** 2018-12-02 08:40 UTC
Labels: help wanted
