### ISSUE TITLE
[Bug Report] VTextarea auto-grow scroll bug (mobile)

### ISSUE THREAD

**Issue by Staf4** [vuetifyjs/vuetify#10921] opened 2020-03-23 14:24 UTC
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Google Chrome, Safari
**OS:** Android, iOS

### Steps to reproduce
When using self block with a scroll, on phones, when input text in VTextarea, the text jump to up.
This is visible in the video: https://www.youtube.com/watch?v=4MBE4_Sg0yk
Reason in file "\lib\components\VTextarea\VTextarea.js", method "calculateInputHeight", line:
input.style.height = '0';

### Expected Behavior
Lack of jumping up

### Actual Behavior
Jumping top

### Reproduction Link
<a href="https://codepen.io/Staf4/pen/oNXYjVY" target="_blank">https://codepen.io/Staf4/pen/oNXYjVY</a>

### Other comments
Watch the video, the problem is obvious

**Comment by valentingavran** [comment] 2020-03-25 22:16
Related to #5314

**Comment by valentingavran** [comment] 2020-03-25 22:16
Duplicate of #5314

**Closed** 2021-08-19 14:26 UTC
Labels: T: bug, C: VTextarea
