### ISSUE TITLE
[Bug Report] v-text-field outlined with binding label not work : the line is above label value

### ISSUE THREAD

**Issue by awenger63** [vuetifyjs/vuetify#10056] opened 2019-12-27 15:58 UTC
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Firefox 71.0
**OS:** Windows 10

### Steps to reproduce
Bind the label of a v-text-field outlined with a 'value' or a 'placeHolder' in the field. 
On first render, label size it's seem to be 0 than the Label place it's not correct, the line is above.

Simple code to reproduce :

<v-text-field outlined :label="labelTitle" value="test"></v-text-field>

data: function () {
    return {
      labelTitle: 'Title'
    }

![image](https://user-images.githubusercontent.com/16153617/71523620-20fa4980-28ca-11ea-8fcf-85601830c8fb.png)

### Expected Behavior
The line must not be above the title label

### Actual Behavior
Label is barred by the line

### Reproduction Link
<a href="https://codepen.io" target="_blank">https://codepen.io</a>

### Other comments
Label use binding for translation. If you replace the binding by a text, label is correct in his place without line above.

**Comment by MajesticPotatoe** [comment] 2019-12-27 16:08
duplicate of #9225

**Closed by MajesticPotatoe** 2019-12-27 16:08 UTC
Labels: triage
