### ISSUE TITLE
[Feature Request] New DataTable with Treeview

### ISSUE THREAD

**Issue by michaelsogos** [vuetifyjs/vuetify#11871] opened 2020-07-16 10:55 UTC
### Problem to solve
In some case with need to show structured data navigable like a tree.
[like this](https://www.google.it/url?sa=i&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F18006448%2Fnested-tree-view-using-html-table-in-angular-js&psig=AOvVaw0pAFRKSwsmHIA0OKRDVObv&ust=1594982803832000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPDk-o7M0eoCFQAAAAAdAAAAABAI)

### Proposed solution
Theoretically you can add new props to component VDataTable to know which is the field value for parent in order to automatically handle the mechanism to expand or collapse VDataTableRow. In somehow similar to GROUP BY feature, but with potentially infinite levels.

Or you can expect a well-formated array of items which can have an "children" property containing again an array of nested items (the item model should be the same in order to match the column). Like it work in treeview component.

It's up to you identify the better approach i guess :)

**Comment by nekosaur** [comment] 2020-10-09 08:42
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6039

**Closed by nekosaur** 2020-10-09 08:42 UTC
Labels: duplicate

**Comment by TerryLam2010** [comment] 2020-11-03 09:56
Bro,I also need the tree table component
