### ISSUE TITLE
[Feature Request] Add a animation for checkbox

### ISSUE THREAD

**Issue by quank123wip** [vuetifyjs/vuetify#11109] opened 2020-04-14 09:08 UTC
### Problem to solve
Make the checkbox better when clicking

### Proposed solution
Add a CSS animation for it

**Comment by jacekkarczmarczyk** [comment] 2020-04-14 09:41
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10050

**Closed by jacekkarczmarczyk** 2020-04-14 09:41 UTC
Labels: triage
