### ISSUE TITLE
[Bug Report] Add align-self for v-flex and remove wrong alignment-attributes

### ISSUE THREAD

**Issue by BennyAlex** [vuetifyjs/vuetify#3980] opened 2018-05-02 14:52 UTC
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.146
**OS:** Windows 7

### Steps to reproduce
Hey there :)
the v-flex component support all the same alignment-properties (like "justify-space-around") as v-layout. 
This is wrong, because this will not affect a flex item, only the flex container.
But a flex item can use the css-attribute "align-self", which will affect only this flex item.
Also the v-flex doens't need a row/column and wrap attribute...

### Expected Behavior
V-flex supports align-self attributes

### Actual Behavior
No support for align-self, allow wrong attributes on v-flex and v-layout

**Comment by KaelWD** [comment] 2018-05-02 15:01
Duplicate of vuetifyjs/vuetifyjs.com#367

**Closed by KaelWD** 2018-05-02 15:01 UTC
