### ISSUE TITLE
[Bug Report] Data-Table Select All clears previous checked items when using server side pagination

### ISSUE THREAD

**Issue by 06b** [vuetifyjs/vuetify#6473] opened 2019-02-12 17:21 UTC
### Versions and Environment
**Vuetify:** 1.5.0
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.96
**OS:** Windows 10

### Steps to reproduce
1. Create a datatable with "select-all" and pagination.
2. Select a few items on page one, then navigate to the next page.
3. Click select all.
4. Navigate back to the first page.

### Expected Behavior
The select all should not deselect previous checked items on a different page.

### Actual Behavior
Select all will deselect any check items on a previous page of the data table.
![vuetify-selectallclearingpreviousselectedcheckboxes](https://user-images.githubusercontent.com/1302542/52654737-a5b1c400-2ec0-11e9-8d33-9660bd54a34c.gif)

### Reproduction Link
<a href="https://codepen.io/anon/pen/daKmWV" target="_blank">https://codepen.io/anon/pen/daKmWV</a>

**Comment by KaelWD** [comment] 2019-02-12 17:23
Duplicate of #4604

**Closed by KaelWD** 2019-02-12 17:23 UTC
