### ISSUE TITLE
[Bug Report][3.1.6] VAppBar Overlap on VMain

### ISSUE THREAD

**Issue by BlackYuzia** [vuetifyjs/vuetify#16754] opened 2023-02-22 20:18 UTC
### Environment
**Vuetify Version:** 3.1.6
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. You should have SSR mode of your application and enable it.
2. Disable JavaScript in your browser.
3. Open page.

### Expected Behavior
Your content have some padding/margin between VMain and VAppBar.

### Actual Behavior
On SSR VAppBar overlap on VMain and hide some contant. On hydration, this effect is fixed and VappBar not overlap on content anymore.

### Reproduction Link
[https://codepen.io/Black_Yuzia/pen/WNgwBae](https://codepen.io/Black_Yuzia/pen/WNgwBae)

### Other comments
I don't know how I can enable SSR on codepen.io so you should paste snippet from website to your app with enabled SSR mode. Sorry for that :c

### Screenshots
When CSR only (NO SSR)
![image](https://user-images.githubusercontent.com/25010528/220748969-4f1a2195-d5aa-4a2d-a763-7943414d6231.png)

When you use SSR (VAppBar has 50% opacity)
![image](https://user-images.githubusercontent.com/25010528/220749050-7cc914c8-e66a-4673-9253-1ee3ce12ea00.png)

After Hydration 
![image](https://user-images.githubusercontent.com/25010528/220749278-187926ec-55fc-4df4-9342-b0c065c108aa.png)

**Comment by KaelWD** [comment] 2023-02-23 10:16
Duplicate of #15202

**Closed by KaelWD** 2023-02-23 10:16 UTC
Labels: S: triage
