### ISSUE TITLE
[Feature Request] v-menu elevation and border-radius props

### ISSUE THREAD

**Issue by laurent-brisbois** [vuetifyjs/vuetify#10958] opened 2020-03-27 23:34 UTC
### Problem to solve
Add props to customize styling of v-menu components. Currently I use a v-list in a v-menu and I'm not able to customize styling of the v-menu. Maybe I didn't see the proper props ? Or the correct way to do it ?

### Proposed solution
Add `elevation` and `no-border-radius` props (or something like that) to customize v-menu styling (as it is possible to do on v-list).

**Comment by johnleider** [comment] 2020-04-04 17:45
Technically a duplicate of #10397 though, so closing in favor of that.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-04-04 17:45 UTC
Labels: C: VMenu, T: feature
