### ISSUE TITLE
[Bug Report] Simple layout with v-row and fill-height causes vertical overflow of parent v-container

### ISSUE THREAD

**Issue by thomasrosdahl** [vuetifyjs/vuetify#10764] opened 2020-03-06 14:01 UTC
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Windows 10

### Steps to reproduce
Adding class "fill-height" to v-row in order to fill remaining vertical space causes row to overflow height of parent v-container.

### Expected Behavior
v-row height does not overflow parent v-container

### Actual Behavior
v-row height overflows parent v-container

### Reproduction Link
<a href="https://codepen.io/m0lg4n/pen/JjdOYLW?editors=1010" target="_blank">https://codepen.io/m0lg4n/pen/JjdOYLW?editors=1010</a>

**Comment by MajesticPotatoe** [comment] 2020-03-06 14:04
duplicate of  #9773 / #10554

**Closed by MajesticPotatoe** 2020-03-06 14:04 UTC
Labels: triage

**Comment by thomasrosdahl** [comment] 2020-03-06 14:09
Please read and look at the pen. This issue refers to **vertical** overflow not **horizontal** as in #9773.

**Comment by MajesticPotatoe** [comment] 2020-03-06 14:15
it is still a duplicate of 10554 which was reopened
