### ISSUE TITLE
[Documentation] Vuetify Theme Generator Export is broken

### ISSUE THREAD

**Issue by barneylau** [vuetifyjs/vuetify#10178] opened 2020-01-10 06:12 UTC
### Environment

**Browsers:** Firefox 71.0
**OS:** Windows 10

### Steps to reproduce
1) No change to values after it loads.
2) Click Export

### Expected Behavior
Some config to use in the vue app?

### Actual Behavior
Nothing happens, and in the Browser Console it shows errors.
Error: TypeError: "this.colors[r(...)(...)] is undefined"

### Reproduction Link
<a href="https://theme-generator.vuetifyjs.com/" target="_blank">https://theme-generator.vuetifyjs.com/</a>

**Comment by KaelWD** [comment] 2020-01-10 07:04
Duplicate of https://github.com/vuetifyjs/theme-generator/issues/9

**Closed by KaelWD** 2020-01-10 07:04 UTC
Labels: triage
