### ISSUE TITLE
[Bug Report][3.1.8] Elevation does not work on dark mode

### ISSUE THREAD

**Issue by kappaflow** [vuetifyjs/vuetify#16899] opened 2023-03-13 05:43 UTC
### Environment
**Vuetify Version:** 3.1.8
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Add multiple cards on dark mode with elevations from 0 to 24. You will not see any visible difference in the elevation background color for these cards/sheets.

Based on the material design specs from Google:
https://m2.material.io/design/color/dark-theme.html#properties
In a dark theme, components retain the same default elevation levels and shadows as components in light themes. However, in a dark theme, the surfaces of different elevation levels are illuminated differently. The higher surface’s elevation is - the lighter that surface becomes.

### Expected Behavior
Elevation should be very visible on the dark mode like with [my fix](https://play.vuetifyjs.com/#eNq9Wmtv2zYX/iuMXrxI3MWypdi5eG2wZTcMuxRYu2FA1Q+0RMdqJEoTaSdG0f++51CSLdtKp2GSiiaQyKNzP4cPybz7aK1XQoeLjf1BWTMrjNMk0+wj8zPBtfgjn2Of2CJLYnZa0J56siA8tUcBzx6GeiliMRSRWHMdJnK4CJ9sX6nTLz3pSfFkaP1EKs0KFuzVvoizj55kzLCZMfPMWCAWfBXpt/ngKQk6PaepT/j9aQDe1rn1dZra4AndX2oRpxFY3oLmZRCuWRi88iyepp5FQ55+uR7iLX82b1BJ81CKjMboH8ay5LF8M+9+Eu3e8xGeBbAmSjKwTzIu7wUj5YQcXngW8yOuFGZiPpzmknf/iq+HOtSR2FJq8aSHvpBaZIcf4BOyROlNJED5GAZ6OWPOePz/Y0rGtgFg+E8qsTgJBFsrFoX3S23eDtmPwP9AyVFVyz3ji5mKg2hk5yF6rTgQ5qqlEIh9YWl64JPc37vpuZmmmQOXJxF5nGgcFxRlFLYGY2JM46WC9Y7+sFKUbDtff7d1mEyQm6EK5yDnmvEoYqGkhNz58eTk5MA1B9YfKutu9SyzJRMBMmQpKBpkyxhK7xkxgVIT9gUD4c6WplL2+d7KRIr/yoQtUFGGE5Si5//M8CBkuYBxR9xvx61ydMDRaZUjJbPbKke0oNuLVjmanGyVIxX5tFWOl+B42SrHqzI3r1plew1Fr1vleAOON+2mOVWO03LpmNppt3jMUuC0Wz4O1Y/TbgE5VEFOuyXkUA057RaRQ1XktFtGDuro1mm3hhwqIqfdKnKojJx268ilOnLbrSOX6shteREyq1C7deRSHbnt1pFLdeQ+X0fA9Fv8SQg/fzcIdEuzhaRmrwGmBhlXYPshRD3aE/SFSB+T7EGxBbYnhOYJie5A/D/j0J6AaDtItH0o2jEW7QCMdoBGO4CjHeDRDgBpB4i0A0jaFSbtAJR2gEo7gaWd4NJOgGknyLQTaNoJNu0EnHaCTjuBp53g004AaicItROI2glGbR+kHh2SmvcSpJagtXoynY/kJ9flce3LUeW0G6/Kz8JUMyX0KifLB/CIM/L8sH4Y8xSn/InEWbk5YfeKCeVZ2zN3j+4D6N2zllqnajYarWT6cG/7STz6CnOjbCV1iMP+IIm/urBde3IFlZSujttCxcM5TFQig0TPMqf2BXOCu88JKKbB17Gvc7bF0DDic0V8j/iNIGQtsmEmZCAywtCfUf6Ads+Ag7kjI8zNAy4e4NAolA/qwJe47iDR70rV/r11hgN9/j6X8rmbFcgdvfDkq98ED2gbI98uQ9osPLGYPwhWXtyYs2vDQpn9BOO+n2RBKO+ZTtgvSJ8s5BH7VqjwXrIfVmEgYJtQM0+W+seuHRd0dpiMAkM6MvuIyt2PvdRx9L80S1KR6VAoSkrHZj/iJD0IlNm9zLn/cJ8lK1nsQtgCP0U9cQyWG7M9FVUq/HARisrGyvaku+M8B63Iec0TvcwtJnb5Zqm0fSkks3deHLOzcZAOGHyGkmFnXLEQ1bMVhqP/550zgAYXNrvjCpTYmsUbpoXShkWQCCU1m+Nui9TYMPGEOJMxi5X0STaPQr0BB0/+rjhujn5N8DH8DW/hpgshzHBLFvENjEoWW6dUXDVP1uLQoTG2kWzJMbFv5MEOZGCsBS/aRUGHHxdsk6xwuxTiukMKmAOXrxRuQNgS7oMKuxsl8jCvJFS9IiBCFPAhNTDsac+JQBopJf/cy5vKV9Qf8WHM5Qr3LuSctwnzeeSvqMEZEbuMobdM/LUKsTOtqEcSfC5J+0ry+tgrp0JS4v612gi5VukI76MPr3++u4v/9OQbir47nZ4XPwOGVPCs75NMFBZ9Q5LRctiaZ2fDYW1RwhEZQjb8Ezn1AktCzuR1Pspep9xHzLFOUF56EqoimobbumClVtmC+2JQ2Gk+v9t5tdAhz3zKEtypFkmi8rBnAq4K8bDzyKF/86z9SYiU0jsOwVcvcdXlWbSlgHb5gUMio01eLztWKBO6HzOlYiTlkdRlzzHfUHCq2UdlcrfS1ciwtzyMHknyN2/e5GcgKE5Yy41wbrSl9n2Sl/WQ8hSaQRbaJae7uXwCX5ArrRO15EHyWEOXT7CzZy0h9V6MqA5nWYKhYgH8hwg7QTpjY3s8xe1zA3K3IL9qRn5RkF83I58U5DfNyKc5uTNuRn5ZkDvNyK9K8oauuS7o3WbkNyV5Q/YO+rv54KIhfRFZ56KpgCK2zqQhfRFcZ9JUoyK8zqSpRmWAJw3TzSlD3FRAGeNpw6A5ZZCnTW0uwzxt6FW3DPO0aUWWcZ5eNvygjPO0oVfdMtDThmXsloEmjYAw0ZFCdWYXS/85wxOt/IMZOtfZO9M1X2A93zHyrPeDon0dNv0Zy+7n/Kx+tRkYcdWeXS+47I3/jnlhfNHJzV+wzJhKojDYnyn+pgWLidyfqJNRnRqUa/J2OMlXWiPbOLJim1Nv2+dNI1TAdr8aQACk17Ff3X5kI1OPZV/0IxtJfyx70o9s1M+x7Gk/stFzj2Vf9iMb7ftY9lU/srEUHMu+7kc2VpVj2Tf9yMYCdSzbeaZxtt5caNN6LL2v1lbb25yemhvhrRrpPbU3Qm810ntqcAQFa6T31OIIV9ZI76nJEUitkd5TmyPIWyO9p0ZH+LlGek+tjsB4DZbpqdcRsq+R3lOvo21CjfS+gFxtr3N76nW0gamR3lOvo92QkW59Orfy83mchZszc+v934Czexc=).

Zero elevation surfaces should have a border (both dark and light themes) by default according to [Material Design Guidelines](https://m2.material.io/design/color/dark-theme.html#properties) for [both](https://kstatic.googleusercontent.com/files/9976752535996547e4486a11a5e6b17cb0dfc27541bab905752c1c9c725bc3d0d3ca91f6072752b8aff8b96f60aa5e5c4b0af474ac12c45912dce8373c6803cf) [light](https://lh3.googleusercontent.com/lg7Rz0Ji-yv2fpd1wo7SRkWvseJEmBndg0vicbmF6N6OW_D7YPGeQOIxzfIs8anpg5umfzCfLSPMikyEZUvjt5WOrFwD60AgyIxMAg=w1064-v0) and [dark](https://lh3.googleusercontent.com/MZFRD7NVPpsDPgaWSxLb_9rapm7FFMh2kp6nJuAUrIORQadQtlG5BQ5flovINSBW1fCohcC-mZsFQDpSNKPMEEv08at_zHVKHWiU=w1064-v0) themes.

### Actual Behavior
Elevation is not visible on the dark mode which makes the dark mode mostly unusable without some custom tricks.

No border for zero elevation.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9WW1P2zAQ/ism0sSmkaYOjJeuVOzD/sG0L4QPaeLS0MSObLeAUP/77uy8tOnYi7CpEIp958d3Fz/Nk+vtS7BZM10snkcPKpgERVULqckLySRLNftpbWRLFlJU5LjxPU54wtmTcc0EV5o0BnK9v/DjS8IJ0UtWsQkx14TkbJGuS/3DTh7nqVwdn6BpC/+3n74mPDgJvtX1CDAhoqlmVV0C5Ax8pnmxIUV+nQRpXScBTiV6uglhZK/NCELSacGZxDn8wJwUj+3IjDNR9mM7k8ocsimFBHghU37PCAbHeHiaBCQrU6XAUqXhF7tz/2lWh7rQJes8NXvSYca4ZnK4AJZgJko/lww8H4tcLyeEjscfDj0JYSXbpLoQnMAfhkQqkTOyUaQs7pfajIbwEeAPgox2o9xLvrHsFAhn+grhcKeAkK5aMgb3vsm0HtTE1rs3z40ZLYOSixIrjj40Bo/2LnQJg2GM822Avy/0w1rhYetr/b0rGBdwNgtVzME91SQtS1JwPJB9HY+OjgalGWQ/DDbu4mxPi2Q5nJAlw7uBuYwh6L0kziCoM/KZgGOfy7/uso8744Kzt4KQBTDKIEFQeP1mwMEtsxuMPaHPxk4RKSBSp4h4mGOniPAVNDt1imjOpFNEJPkXp4jngHjuFPGiPZsXTmEvIdBLp4hXgHjl9pgjc6hj6hjuuCWPeRRQt/ShyB/qlkAUGUTdUogih6hbElFkEXVLIwo8mlG3HKJIIuqWRRRpRN3yKEYexW55FCOPYscPIfMUcsujGHkUu+VRjDyKX+cRaPpOf6LCt2OjQDufTpKadw0ANcp4R7YPJerBO8F7KdJHIVeKLOD1BNU8KtFexP9dh76TEHWjRN1LUc9a1IMY9aBGPchRD3rUgyD1oEg9SFJfmtSDKPWgSr3IUi+61Isw9aJMvUhTL9rUizj1ok69yFMv+tSLQPWiUL1IVC8a1b1IPWiSmnErUlvRutuZtjO2c922a6fRTrcbhiqTRa2JYnpt3ewEXEKP3PbqwyqtoXcvOPTKTYc9aQwqCbqee4JdfhwnwVLrWk2iaM3r1f0oE1V0A7ZIrrkuKhbmoro5HcWjswsISend+RFTVTiHFBWTsGMSmK59A45y97UNGjPg0tGlhW2mwjKdK8Q9wItgkw2ToWQ8ZxI19B+CH/juJTCwHSRhfnmAHx6goGXBV2pQy0yZOt62of1/dgYBl9/hLtuTwEYH+5kVwd0vtVu/bw==)

### Other comments
[My fix](https://play.vuetifyjs.com/#eNq9Wmtv2zYX/iuMXrxI3MWypdi5eG2wZTcMuxRYu2FA1Q+0RMdqJEoTaSdG0f++51CSLdtKp2GSiiaQyKNzP4cPybz7aK1XQoeLjf1BWTMrjNMk0+wj8zPBtfgjn2Of2CJLYnZa0J56siA8tUcBzx6GeiliMRSRWHMdJnK4CJ9sX6nTLz3pSfFkaP1EKs0KFuzVvoizj55kzLCZMfPMWCAWfBXpt/ngKQk6PaepT/j9aQDe1rn1dZra4AndX2oRpxFY3oLmZRCuWRi88iyepp5FQ55+uR7iLX82b1BJ81CKjMboH8ay5LF8M+9+Eu3e8xGeBbAmSjKwTzIu7wUj5YQcXngW8yOuFGZiPpzmknf/iq+HOtSR2FJq8aSHvpBaZIcf4BOyROlNJED5GAZ6OWPOePz/Y0rGtgFg+E8qsTgJBFsrFoX3S23eDtmPwP9AyVFVyz3ji5mKg2hk5yF6rTgQ5qqlEIh9YWl64JPc37vpuZmmmQOXJxF5nGgcFxRlFLYGY2JM46WC9Y7+sFKUbDtff7d1mEyQm6EK5yDnmvEoYqGkhNz58eTk5MA1B9YfKutu9SyzJRMBMmQpKBpkyxhK7xkxgVIT9gUD4c6WplL2+d7KRIr/yoQtUFGGE5Si5//M8CBkuYBxR9xvx61ydMDRaZUjJbPbKke0oNuLVjmanGyVIxX5tFWOl+B42SrHqzI3r1plew1Fr1vleAOON+2mOVWO03LpmNppt3jMUuC0Wz4O1Y/TbgE5VEFOuyXkUA057RaRQ1XktFtGDuro1mm3hhwqIqfdKnKojJx268ilOnLbrSOX6shteREyq1C7deRSHbnt1pFLdeQ+X0fA9Fv8SQg/fzcIdEuzhaRmrwGmBhlXYPshRD3aE/SFSB+T7EGxBbYnhOYJie5A/D/j0J6AaDtItH0o2jEW7QCMdoBGO4CjHeDRDgBpB4i0A0jaFSbtAJR2gEo7gaWd4NJOgGknyLQTaNoJNu0EnHaCTjuBp53g004AaicItROI2glGbR+kHh2SmvcSpJagtXoynY/kJ9flce3LUeW0G6/Kz8JUMyX0KifLB/CIM/L8sH4Y8xSn/InEWbk5YfeKCeVZ2zN3j+4D6N2zllqnajYarWT6cG/7STz6CnOjbCV1iMP+IIm/urBde3IFlZSujttCxcM5TFQig0TPMqf2BXOCu88JKKbB17Gvc7bF0DDic0V8j/iNIGQtsmEmZCAywtCfUf6Ads+Ag7kjI8zNAy4e4NAolA/qwJe47iDR70rV/r11hgN9/j6X8rmbFcgdvfDkq98ED2gbI98uQ9osPLGYPwhWXtyYs2vDQpn9BOO+n2RBKO+ZTtgvSJ8s5BH7VqjwXrIfVmEgYJtQM0+W+seuHRd0dpiMAkM6MvuIyt2PvdRx9L80S1KR6VAoSkrHZj/iJD0IlNm9zLn/cJ8lK1nsQtgCP0U9cQyWG7M9FVUq/HARisrGyvaku+M8B63Iec0TvcwtJnb5Zqm0fSkks3deHLOzcZAOGHyGkmFnXLEQ1bMVhqP/550zgAYXNrvjCpTYmsUbpoXShkWQCCU1m+Nui9TYMPGEOJMxi5X0STaPQr0BB0/+rjhujn5N8DH8DW/hpgshzHBLFvENjEoWW6dUXDVP1uLQoTG2kWzJMbFv5MEOZGCsBS/aRUGHHxdsk6xwuxTiukMKmAOXrxRuQNgS7oMKuxsl8jCvJFS9IiBCFPAhNTDsac+JQBopJf/cy5vKV9Qf8WHM5Qr3LuSctwnzeeSvqMEZEbuMobdM/LUKsTOtqEcSfC5J+0ry+tgrp0JS4v612gi5VukI76MPr3++u4v/9OQbir47nZ4XPwOGVPCs75NMFBZ9Q5LRctiaZ2fDYW1RwhEZQjb8Ezn1AktCzuR1Pspep9xHzLFOUF56EqoimobbumClVtmC+2JQ2Gk+v9t5tdAhz3zKEtypFkmi8rBnAq4K8bDzyKF/86z9SYiU0jsOwVcvcdXlWbSlgHb5gUMio01eLztWKBO6HzOlYiTlkdRlzzHfUHCq2UdlcrfS1ciwtzyMHknyN2/e5GcgKE5Yy41wbrSl9n2Sl/WQ8hSaQRbaJae7uXwCX5ArrRO15EHyWEOXT7CzZy0h9V6MqA5nWYKhYgH8hwg7QTpjY3s8xe1zA3K3IL9qRn5RkF83I58U5DfNyKc5uTNuRn5ZkDvNyK9K8oauuS7o3WbkNyV5Q/YO+rv54KIhfRFZ56KpgCK2zqQhfRFcZ9JUoyK8zqSpRmWAJw3TzSlD3FRAGeNpw6A5ZZCnTW0uwzxt6FW3DPO0aUWWcZ5eNvygjPO0oVfdMtDThmXsloEmjYAw0ZFCdWYXS/85wxOt/IMZOtfZO9M1X2A93zHyrPeDon0dNv0Zy+7n/Kx+tRkYcdWeXS+47I3/jnlhfNHJzV+wzJhKojDYnyn+pgWLidyfqJNRnRqUa/J2OMlXWiPbOLJim1Nv2+dNI1TAdr8aQACk17Ff3X5kI1OPZV/0IxtJfyx70o9s1M+x7Gk/stFzj2Vf9iMb7ftY9lU/srEUHMu+7kc2VpVj2Tf9yMYCdSzbeaZxtt5caNN6LL2v1lbb25yemhvhrRrpPbU3Qm810ntqcAQFa6T31OIIV9ZI76nJEUitkd5TmyPIWyO9p0ZH+LlGek+tjsB4DZbpqdcRsq+R3lOvo21CjfS+gFxtr3N76nW0gamR3lOvo92QkW59Orfy83mchZszc+v934Czexc=) maybe isn’t perfect, but it makes the dark theme usable and work according to Material Design Guidelines.

Ideally, the surface color should be converted to HSL values (and stored in this way in css variables), then the lightness could be adjusted by CSS calculations based on the elevation level. I think it’s the easiest solution to implement:
https://stackoverflow.com/a/55267265

Similar issues:
#10584
#7147

**Comment by KaelWD** [comment] 2023-03-13 05:45
Duplicate of #14198

**Closed by KaelWD** 2023-03-13 05:45 UTC
Labels: S: triage
