### ISSUE TITLE
[Bug Report] The label is crossed out with border in VTextField with outlined property, if label is updated dynamically and v-model has value

### ISSUE THREAD

**Issue by dzhamshed** [vuetifyjs/vuetify#8253] opened 2019-08-01 16:47 UTC
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
1. Create a *v-text-field* with outlined property:
```html
 <v-text-field
                  :label="theLabel"
                  v-model="theModel"
                  outlined
></v-text-field>
```

2. Configure the component:

```typescript
public theModel: string = 'Some value';
public theLabel: string | null = null;

// When the component is created set the timeout to change theLabel value (i. e. fetching from server takes time)

public created() {
    const that = this;
    setTimeout(() => that.theLabel = 'Input name', 3000);
}
```

### Expected Behavior
It shouldn't cross out the label.

### Actual Behavior
It crosses out the label if the label updated dynamically and the v-model has some value.

### Reproduction Link
<a href="https://codepen.io/dzhamshed/pen/eqEpGx" target="_blank">https://codepen.io/dzhamshed/pen/eqEpGx</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-01 16:48
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7470

**Closed by jacekkarczmarczyk** 2019-08-01 16:48 UTC
Labels: triage

**Comment by anjayluh** [comment] 2019-11-01 05:34
I am still having this isssue. Did someone here figure out how to fix the crossed out label
![image](https://user-images.githubusercontent.com/13086425/68004367-5136ba80-fc82-11e9-84d2-48a7d7bf1496.png)

**Comment by wendelicious** [comment] 2019-12-12 06:34
Yeah. It seems that you only need a text input with a label and a prepend inner icon to see this happen.

I don't use prepend inner icon anymore.
