### ISSUE TITLE
[Bug Report][3.3.4] V-tab breaking nested route navigation

### ISSUE THREAD

**Issue by rachitpant** [vuetifyjs/vuetify#17614] opened 2023-06-14 19:57 UTC
### Environment
**Vuetify Version:** 3.3.4
**Vue Version:** 3.3.4
**Browsers:** Firefox 114.0
**OS:** Mac OS 10.15

### Steps to reproduce
Open the shared code repo and Click on Activity ( You would see two links applications and post review forms ),
Clicks on applications - You would get a list of applications.
Click on "First app"
This loads an app with route param 1. The app has different tabs (v-tabs ). You can navigate between the tabs. However , now if you try clicking on applications, you no longer can go the applications page listing the two applications.

While the console log error indicates it is probably an issue with `vue-router` , it is not because the same code works if i comment out  `v-tabs` in `Application.vue` and uncomment/replace it with `v-router` ( its already there above it , just uncomment it and everything starts working )

### Expected Behavior
You should be able to navigate back to the parent route.

### Actual Behavior
If you try clicking on applications list page after opening an application, you no longer can go the applications page listing the two applications

### Reproduction Link
[https://codesandbox.io/p/sandbox/misty-meadow-m746dw?file=%2Fpackage.json%3A16%2C23](https://codesandbox.io/p/sandbox/misty-meadow-m746dw?file=%2Fpackage.json%3A16%2C23)

**Comment by rachitpant** [comment] 2023-06-14 20:10
Also even if i replace the v-tab with v-toolbar-items ( inside v-toolbar in Application.vue ) , the issue still persists. Like i said in the original bug , the issue does not happen if the reproduction codebase doesn't use vuetify and if the application links in Application.vue are simply router-links. ( instead of v-tabs or v-toolbar-items )

**Comment by KaelWD** [comment] 2023-06-15 03:02
Duplicate of #17176

**Closed by KaelWD** 2023-06-15 03:02 UTC
Labels: S: triage
