### ISSUE TITLE
[Feature Request] Use callback for form validation.

### ISSUE THREAD

**Issue by lipei86** [vuetifyjs/vuetify#5392] opened 2018-10-23 08:23 UTC
### Problem to solve
vuetify native form validation does not support remote api.

### Proposed solution
please visit to http://element-cn.eleme.io/#/en-US/component/form, it's validation is fine.

**Comment by KaelWD** [comment] 2018-10-25 14:31
Duplicate of #4231

**Closed by KaelWD** 2018-10-25 14:31 UTC
