### ISSUE TITLE
[Feature Request] [Feature Request] add components v-upload-image with preview

### ISSUE THREAD

**Issue by little3201** [vuetifyjs/vuetify#11958] opened 2020-07-29 11:32 UTC
### Problem to solve
add a new components v-upload-image with preview, this v-file-input could not preview result if the file is a image

### Proposed solution
add a new components v-upload-image with preview, this v-file-input could not preview result if the file is a image

**Comment by KaelWD** [comment] 2020-07-29 11:38
Duplicate of #8812

**Closed by KaelWD** 2020-07-29 11:38 UTC
Labels: triage
