### ISSUE TITLE
[Bug Report] Problem with vuetify Persian datepicker year selection

### ISSUE THREAD

**Issue by mohammadmrd74** [vuetifyjs/vuetify#11578] opened 2020-06-08 13:02 UTC
### Environment
**Vuetify Version:** 2.3.0-beta.8
**Vue Version:** 2.6.11
**Browsers:** Chromium 83.0.4103.61
**OS:** Linux, Windows, Linux x86_64

### Steps to reproduce
Put the selected year directly in the year showing in the top left of the calendar.

### Expected Behavior
**Top left year should be the same as the correct selected year.**

### Actual Behavior
When loading date picker in Persian mode ( locale = "fa-IR" ), the year in the top left of the calendar is not the same with the selected year. The top left year is one year less than the correct one.

### Reproduction Link
<a href="https://codepen.io/mohammadmrd74/pen/vYLNGbx?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdate-pickers%2F" target="_blank">https://codepen.io/mohammadmrd74/pen/vYLNGbx?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fdate-pickers%2F</a>

**Comment by jacekkarczmarczyk** [comment] 2020-06-08 13:54
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1892

**Closed by jacekkarczmarczyk** 2020-06-08 13:54 UTC
Labels: triage

**Comment by mohammadnadr** [comment] 2024-08-26 13:48
Same Problemmmmmmmmmmmmmmmmmmmm

**Comment by jamaljalali68** [comment] 2025-02-20 16:35
sameeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by jamaljalali68** [comment] 2025-02-22 09:53
// Import MDI font for icons
import '@mdi/font/css/materialdesignicons.css'

import DayJsJalaliAdapter from "@date-io/date-fns-jalali";
import { faIR } from "date-fns-jalali/locale/fa-IR";

// Import Vuetify
import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import { fa } from 'vuetify/locale'
import { VDateInput } from 'vuetify/labs/VDateInput'

export default defineNuxtPlugin((app) => {
  const vuetify = createVuetify({
    theme: {
      defaultTheme: 'dark',
    },
    components: {
      VDateInput,
    },
    date: {
      adapter: DayJsJalaliAdapter,
      locale: {
        fa: faIR,
      }
    },
    locale: {
      locale: 'fa',
      fallback: "en",
      messages: {
        fa,
      },
    },

  })

  app.vueApp.use(vuetify)
})
