### ISSUE TITLE
[Bug Report] Not support spread ... operator with babel.It's not work on Chrome 57

### ISSUE THREAD

**Issue by ikarosu** [vuetifyjs/vuetify#8992] opened 2019-09-18 03:57 UTC
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
1. run
2. open on Chrome 57

### Expected Behavior
work

### Actual Behavior
```
Uncaught SyntaxError: Unexpected token ...
    at Object../node_modules/vuetify/lib/util/mergeData.js (chunk-vendors.js:5253)
    at __webpack_require__ (app.js:791)
    at fn (app.js:151)
    at eval (VContainer.js?a523:1)
    at Module../node_modules/vuetify/lib/components/VGrid/VContainer.js (chunk-vendors.js:2997)
    at __webpack_require__ (app.js:791)
    at fn (app.js:151)
    at eval (index.js?9910:1)
    at Module../node_modules/vuetify/lib/components/VGrid/index.js (chunk-vendors.js:3069)
    at __webpack_require__ (app.js:791)
```

### Reproduction Link
<a href="https://github.com/ikarosu/testvuetify" target="_blank">https://github.com/ikarosu/testvuetify</a>

### Other comments
If I not use Vuetify, I can use spread (...) operator on the project.This means that the babel works fine.

**Comment by KaelWD** [comment] 2019-09-18 06:43
Duplicate of https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/107

**Closed by KaelWD** 2019-09-18 06:43 UTC
Labels: triage
