### ISSUE TITLE
[Bug Report] <v-simple-table> does not work properly

### ISSUE THREAD

**Issue by desthercz** [vuetifyjs/vuetify#8410] opened 2019-08-08 22:47 UTC
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Linux x86_64

### Steps to reproduce
1) Go to https://vuetifyjs.com/en/components/simple-tables#simple-tables
2) Click codepen icon at any example
3) Table wont show up

### Expected Behavior
Expecting to see the same table as shown in documentation.

### Actual Behavior
At codepen it shows nothing. In my local application it just spew any content as string without any html tags.

### Reproduction Link
<a href="https://codepen.io/miloslav-janouek/pen/BXxXye?" target="_blank">https://codepen.io/miloslav-janouek/pen/BXxXye?</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-09 05:44
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8099

**Closed by jacekkarczmarczyk** 2019-08-09 05:44 UTC
Labels: triage
