### ISSUE TITLE
[Bug Report][3.1.4] using @use 'vuetify' with ($utilities: false, $color-pack: false); error

### ISSUE THREAD

**Issue by mavyfaby** [vuetifyjs/vuetify#16640] opened 2023-02-11 10:39 UTC
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. Create vuetify project with **vite** and **yarn**.
2. Add the the code from the official [docs](https://next.vuetifyjs.com/en/features/sass-variables/) to the project `styles/main.scss`:

```scss
@use 'vuetify' with (
  $utilities: false,
  $color-pack: false,
);
```
3. Import `main.scss` from `main.js`
3. Run `yarn dev` and go the the local dev URL.

### Expected Behavior
Should have no errors and the styles should apply with the given custom scss variables given from the official docs.

### Actual Behavior
An error saying: `Error: Failed to resolve entry for package "vuetify". The package may have incorrect main/module/exports specified in its package.json.`

### Reproduction Link
[https://github.com/mavyfaby/vuetify-scss-repro](https://github.com/mavyfaby/vuetify-scss-repro)

**Comment by KaelWD** [comment] 2023-02-11 10:45
Duplicate of #16593

**Closed by KaelWD** 2023-02-11 10:45 UTC
Labels: S: triage

**Comment by mavyfaby** [comment] 2023-02-11 10:50
Thanks for your immediate response! I'm still puzzled as to why the official documentation was not updated.

**Comment by KaelWD** [comment] 2023-02-11 10:58
Because it's a bug in vite
