### ISSUE TITLE
[Bug Report] !important rules in classes .v-btn--icon and .v-chip > .v-avatar causes unexpected behaviour

### ISSUE THREAD

**Issue by Equals182** [vuetifyjs/vuetify#4653] opened 2018-07-18 12:14 UTC
### Versions and Environment
**Vuetify:** 1.1.6
**Vue:** 2.5.16
**Browsers:** Firefox 61.0
**OS:** Windows 10

### Steps to reproduce
Create *small* `v-chip` with `v-avatar`
Create `v-btn` with 'icon' attribute and 'elevation-{n}' class

### Expected Behavior
I expect `v-avatar`'s size to automatically change with the size of `v-chip`. I also expect `v-avatar` to respect 'size' attribute in any case. 
When I set `elevation-{n}` class I expect element to respect this class and have box-shadow property set, even if it's `v-btn` with 'icon' attribute.

### Actual Behavior
`v-avatar`'s size not changing automatically or manually via 'size' attribute when it's inside `v-chip`
`v-btn`'s class 'v-btn--icon' doesn't let 'elevation-{n}' class set box-shadow rule

### Reproduction Link
[https://codepen.io/equals182-wtf/pen/OwRLLY](https://codepen.io/equals182-wtf/pen/OwRLLY)

### Other comments
Tbh, I'm not sure if using !important in css rules is a good idea at all

**Comment by KaelWD** [comment] 2018-07-18 12:32
Duplicate of #3225

**Closed by KaelWD** 2018-07-18 12:32 UTC
