### ISSUE TITLE
[Bug Report] Prefix text still in black when disabling input

### ISSUE THREAD

**Issue by ThomasFerro** [vuetifyjs/vuetify#5634] opened 2018-11-16 15:56 UTC
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Mac OS 10.13.6

### Steps to reproduce
Simply add a v-text-field disabled with a prefix.

### Expected Behavior
The prefix should have the color of the input (gray).

### Actual Behavior
The prefix is still black.

### Reproduction Link
<a href="https://codepen.io/anon/pen/xQroGg" target="_blank">https://codepen.io/anon/pen/xQroGg</a>

**Comment by jacekkarczmarczyk** [comment] 2018-11-16 16:20
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5481

**Closed by jacekkarczmarczyk** 2018-11-16 16:20 UTC

**Comment by vincentauger** [comment] 2019-02-22 20:41
I am having this issue with Vuetify 1.5.2, Vue: 2.6.6. Problem still reproducing in link above. prefix remains black, does not go grey.
