### ISSUE TITLE
[Bug Report][2.5.5] v-dialog content horizontal scroll not working on iOS devices with trackpad (Macbook) 

### ISSUE THREAD

**Issue by prod1992** [vuetifyjs/vuetify#14351] opened 2021-11-01 12:54 UTC
### Environment
**Vuetify Version:** 2.5.5
**Vue Version:** 2.6.11
**Browsers:** Chrome 95.0.4638.54
**OS:** Mac OS 10.15.7

### Steps to reproduce
Open the dialog 

### Expected Behavior
When using macbook's trackpad, user should be able to scroll it horizontally using gesture

### Actual Behavior
It is either very hard to scroll the inner content horizontally or is impossible. 
Only possible when the dialog itself has vertical scroll

### Reproduction Link
<a href="https://codepen.io/prod1992/pen/porWYGy" target="_blank">https://codepen.io/prod1992/pen/porWYGy</a>

**Comment by KaelWD** [comment] 2021-11-02 14:26
Duplicate of #3765

**Closed by KaelWD** 2021-11-02 14:26 UTC
Labels: S: triage
