### ISSUE TITLE
[Bug Report][3.2.3] `v-btn` with icon doesn't work if any element is inside

### ISSUE THREAD

**Issue by kappaflow** [vuetifyjs/vuetify#17360] opened 2023-05-11 20:38 UTC
### Environment
**Vuetify Version:** 3.2.3
**Vue Version:** 3.3.1
**Browsers:** Chrome 112.0.0.0
**OS:** Windows 10

### Steps to reproduce
For example you can insert `v-snackbar` inside `v-btn` that has `icon` set

### Expected Behavior
Suppose to see the icon inside the button

### Actual Behavior
The button is blank

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNU01O6zAQvsrIG0Cq4752FwXEO8A7AWbh2uZhmtiWPQ1UVe7OxElLVZBKNpnMz/czdp4O7G+MVb+zrGYN2i62Cu2D9ACNcT3oVuV8LxnaD+TaerRJslKmhp5v0E8x6NCGRI0hKf/fcqPS1nq+kmyuOx08lTvjOEVISPSO+1P9iCkK6E8MVymuccygBTZ7pbcblY4ppdH1Cgt+VIlGv2BrdJ0NO6TSerlcnvyPz+EA42pgGE7g5OCIXholnptqBK2VokacLbvJOrmIpcF+xJAQjH1RuxbhMOEahaqG2zu4f4DbOQeFuoabf3uYJYLLkC0CBliR1OpmMbUOdyUgkY2YudiCtc5vc/WWg6fDL6CS6Zwlq+FpmpPsFTHmWghtPHUa27o+Vd6i8LETdG3Qvewf19WqWpOxjMcUb9UmVwVsRHqWfiBC143eeKfiBetUKMyzOckIafy+IuGR2kTa+XEB3ISOtKyrP5OWs3Rlc8c3KbxnmwhEsnkxhWYU/Auqa26J4hu0IL7eJk43ytg0/jy/c3Qxdu7qovTN2XzQAxsWrIzR4otk9vwJRk9Fdg==)

### Other comments
Not sure if its a bug itself, but it would be convenient to use elements inside `v-btn` without breaking the icon button functionality.

**Comment by kappaflow** [comment] 2023-05-11 22:56
@marjev to use an advantage of [activator API](https://vuetifyjs.com/en/api/v-snackbar/#props-activator) and avoid using `v-model` (`snackbar: false`) where it is unnecessary.

Also, it works just fine with a button that has **prepend-icon** or **append-icon**.

**Comment by KaelWD** [comment] 2023-05-12 02:14
Duplicate of #16060

**Closed by KaelWD** 2023-05-12 02:14 UTC
Labels: S: triage
