### ISSUE TITLE
[Bug Report][3.7.4] [Bug Report][3.7.3] VCheckbox skips next update:modelValue when modelValue is not updated

### ISSUE THREAD

**Issue by tobias-rondin** [vuetifyjs/vuetify#20697] opened 2024-11-14 11:33 UTC
### Environment
**Vuetify Version:** 3.7.4
**Vue Version:** 3.5.12
**Browsers:** Chrome 130.0.0.0
**OS:** Windows 10

### Steps to reproduce
Click the checkbox twice

### Expected Behavior
The checkbox should change value every other click

### Actual Behavior
The checkbox changes value every third click

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1UstugzAQ/JUVF0BKwx0BatVTLz30dSk9EGMaFGNbYNJWlH/v2sYBkvTix3pmd3a874PXtSS6k3J77KkXe0lH2loq6KjqJbCCf6a5p7rcy3IOUDdStAoGaGm1AfUjKTzpExGN7BUtYYSqFQ34mMzPuaYY0KssC0UfeCUgBf95L3pW2pgPvy7wKNQUs0wieKeA7Ck5YOZU1wyqgnU0nF/7U+JYK0nmQtnEuEiO7GV+bPRel9iJ77eC9RRpwVEfYtgJwWjBQ0gzGDQDDaggmGtuDRDS9Lyp0OGxitXvoGB293iZ6poZGjkCxc7ntP8z1zS94bLwk9Xk8PJVE+raRqr7vyAwzQZTmUl7vG5iYx+X1p+rMVVDdDqJ7Dzh9OBF0UYyBJpZSo43hZTmaC4oTxU1p+0UssFJowsBjuSOMpxJpz735re4ESVl5hsRMYleAm6t0DXufAJmQpZEs4STrGG4ZuJorEbRmrJqRUdsp0m0cMAbN7xnzCwffywILTQ=)

### Other comments
Same issue as https://github.com/vuetifyjs/vuetify/issues/20673, but since there was a misunderstanding of what the issue was, I have recreated it with clearer instructions.

**Comment by MatthewAry** [comment] 2024-11-16 19:07
I believe the source of this behavior is caused by the vuetify's `proxiedModel` composable. [Specifically here.](https://github.com/vuetifyjs/vuetify/blob/797cd88691e813b9e1c4c41323c5e8aaa7f9b356/packages/vuetify/src/composables/proxiedModel.ts#L58-L60). This composable it a core part of how vuetify handles values for input fields as it provides vuetify with additional lifecycle hooks to manage the model value depending on the functional requirements of the input field. I'm not really sure if this should be classified as a bug. The benefit from having this guard is to prevent infinite update cycles in certain scenarios. It also yields some potential performance gains by possibly eliminating unnecessary re-renders when the actual value does not change.

However `proxiedModel` is an impure function and also violates the principle of least surprise.

[I was able to make the behavior work by using the component that lies underneath the VCheckbox component, VSelectionControl. ](https://play.vuetifyjs.com/#eNp1U01vgzAM/SsemlQqdeVeQbVpp102aV+XsQOkZkMNSQSh28T473MSKOnHLkCen5/tF/PWBU3NohullrsWg1UQN6wulYYGdauAZ+IjSQPdpME6FQBlpWStoYMaiwXoH4XwaL6YrFSrcQM9FLWsYEZis1SYFEt6UZtM450oJCQwe/qULd84bAa/I3Av9YC5TCZFo4F9ItuScmJqhkXGG5xP0XYvvDKdxFOh9ZBxIu5ls3wgiZZzwv26ZMCtKZ3L79eMt0jMcA7JGjrDcSzJccnlR8jy5c5wrDS5VEA4NeZCkCTHk89HKRJzQ45UuDgARtap5jnrDLMHJJ8m/f8zD9KokWGSPe1MI7150cPzkZds+/xVMhwtM5nDToTOtnD0zQmuDpUXLuhf53HPtuqcLI4jt6O0kXTQWClORLuf8e4qU8p+2gO1p7NSYD1AFmyQI9OlFDZcSz7GwOwCrTvL02DCeJYjJ3QczY+tKrlBbvfD5LmJfMK1tYZix+vkk+xS31EzxLu0IsR6KAqfo+v2lCImRrSfsOvO3Udvb43mj45dMYgzLY48M4N+Yf4K+3j/A8biXWs=) but my implementation is without the benefits of being wrapped in the VInput component, thus wouldn't work with the VForm validators. I will raise this with the team to see how they would want to classify this.

On one hand, an argument could be made that this is not really a bug because what you're doing is forcing a checkbox component which is fundamentally designed to only have 2 possible value states that can be activated on it, to act as if it has 3 states, by requiring a double click to change the state.

But on the other, the behavior the `proxiedModel` composable is producing leads to unexpected results like the one you bring up, however any changes we make to this composable could have undesired side effects elsewhere. Stay tuned!

**Comment by MatthewAry** [comment] 2024-11-16 19:59
@johnleider suggested a sort of cheat for this as well. https://play.vuetifyjs.com/#eNp1Uk1vgzAM/SsWF0Dqxh0B2rTTLjvs6zJ2oGBW1EAiCN0qxn+fE0gDbXeBxH7P9nvxx+B0bR7cC3F76NEJnajL20pI6FD2AljWfMWpI7vUSdIGoKoFbyUM0GK5AXkUCM/qlPNa9BILGKFseQ0uFXPTRlE06E0UmcTHpuQQg/uy4z0rppgLvybwxOUcm5g5bzoJ+Q7zPVWOVU+vzFiHvs32p8KhmiSyjZKZcVGc2Mv6JPRBtdjyn/eM9Ug076AOIWw5Z5g1PsQJDIpBBpTg2Z63GghxfC7KN3jqMs1voKD/JnlZ6poZCjkCknJb9n/mmqZ+9Fn4yap8//pd5WhkE9W8n+dpsd7cZp49XIvYTMml9efT6K4+OR0F0z7R9tBFYi0YAfUuRYebTAh91BcaT2ZVg+0cmoLzjCYEEO7xSCtpO6aOTbJsi4yyRtoyF9a8QKbfmBCzoiXgbqq5xp2vhyUkUWDnO808DNccHvU7kCJFWelUkcmGKFjY44ybpmdMfz7/AA8VNck=

**Comment by KaelWD** [comment] 2024-11-17 06:06
Duplicate of #15666, it's a vue limitation: https://github.com/vuejs/rfcs/pull/188

**Closed by KaelWD** 2024-11-17 06:06 UTC
Labels: layer 8 issue, C: VCheckbox, has workaround, E: proxiedModel
