### ISSUE TITLE
[Bug Report] Vuetify Email Rule Hangs the complete Webpage

### ISSUE THREAD

**Issue by dhaneshagrawal** [vuetifyjs/vuetify#4416] opened 2018-06-28 14:32 UTC
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.1
**Browsers:** Chrome 67.0.3396.99
**OS:** Mac OS 10.13.3

### Steps to reproduce
Please do not copy paste the email. You reproduce the issue only when you type it manually.

Example Email Input on CodePen : 
testnewlongemail@veryverylongemail.com

### Expected Behavior
Should not hang the webpage even if the email typed is invalid

### Actual Behavior
Hangs the complete webpage and freezes the email field

### Reproduction Link
[https://codepen.io/dhnsh/pen/rKQpGb](https://codepen.io/dhnsh/pen/rKQpGb)

**Comment by KaelWD** [comment] 2018-06-28 15:11
Duplicate of #2588

**Closed by KaelWD** 2018-06-28 15:11 UTC
