### ISSUE TITLE
[Bug Report] Keyboard does not close on selecting an entry in v-autocomplete 

### ISSUE THREAD

**Issue by liujiajun** [vuetifyjs/vuetify#10072] opened 2019-12-29 14:24 UTC
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Safari, Google Chrome
**OS:** iOS

### Steps to reproduce
- Click on AutoComplete box
- Select an entry from the dropdown list **or**
- Enter some text in AutoComplete box and press Enter in keyboard

### Expected Behavior
Keyboard closes

### Actual Behavior
Keyboard does not close

### Reproduction Link
<a href="https://codepen.io/jiajun_liu/pen/KKwvGga" target="_blank">https://codepen.io/jiajun_liu/pen/KKwvGga</a>

**Comment by johnleider** [comment] 2020-01-13 06:44
The simple fix for this would be to call `document.activeElement.blur()` after a selection. This would only apply in a non multiple select and would probably use a **mobileBreakpoint** prop.

**Comment by liujiajun** [comment] 2020-01-15 12:36
> The simple fix for this would be to call `document.activeElement.blur()` after a selection. This would only apply in a non multiple select and would probably use a **mobileBreakpoint** prop.

Thanks. This works. And would be good if there is a permanent fix to this issue.

**Comment by bad4iz** [comment] 2020-02-08 10:32
Duplicate of #5950

**Closed by bad4iz** 2020-02-08 10:32 UTC
Labels: C: VAutocomplete, T: bug, help wanted
