### ISSUE TITLE
v-tooltip directive hiding behind navigation drawer in mini mode

### ISSUE THREAD

**Issue by thisDOTname** [vuetifyjs/vuetify#1728] opened 2017-09-14 06:49 UTC
### Steps to reproduce

1. Use tool-tip on v-icon inside navigation drawer which is set to **mini** mode
2. Hover over the icon with tool-tip

### Versions
**Vuejs**: 2.4.3
**Vuetifyjs**: 0.15.2
**OS**: All
**Browser**: All

### What is expected ?
The tool-tip should be displayed in the specified position

### What is actually happening ?
The tool-tip is only partially visible in the area available to the navigation drawer in mini mode

### Reproduction Link
https://codepen.io/anon/pen/eGmewq

**Comment by nekosaur** [comment] 2017-09-14 19:44
Duplicate of #999

**Closed by nekosaur** 2017-09-14 19:44 UTC
