### ISSUE TITLE
[Bug Report][3.1.9] autocomplete menu dont appear in write position in rtl

### ISSUE THREAD

**Issue by mrkayo** [vuetifyjs/vuetify#16917] opened 2023-03-15 14:07 UTC
### Environment
**Vuetify Version:** 3.1.9
**Vue Version:** 3.2.13
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
click on autocomplete

### Expected Behavior
show menu

### Actual Behavior
dont show but appear on the second click

### Reproduction Link
[https://codepen.io/sasran/pen/qBMYmJW?editors=101](https://codepen.io/sasran/pen/qBMYmJW?editors=101)

**Comment by KaelWD** [comment] 2023-03-20 11:00
Duplicate of #16628

**Closed by KaelWD** 2023-03-20 11:00 UTC
Labels: duplicate
