### ISSUE TITLE
[Feature Request] item-value in V-Combobox doesn't work

### ISSUE THREAD

**Issue by nabizadeh84** [vuetifyjs/vuetify#13314] opened 2021-03-24 09:12 UTC
### Problem to solve
item-value in V-Combobox doesn't work.
I set items, item-text, item-value and v-model correctly but when i want to update a record, combobox  shows item-value instead of item-text

### Proposed solution
.

**Comment by KaelWD** [comment] 2021-03-24 09:14
Duplicate of #5479

**Closed by KaelWD** 2021-03-24 09:14 UTC
Labels: triage
