### ISSUE TITLE
[Feature Request] injected notify function

### ISSUE THREAD

**Issue by SeregPie** [vuetifyjs/vuetify#4427] opened 2018-06-29 19:53 UTC
### Problem to solve
This feature is implemented in almost all other Vue frameworks. Snackbar is the only possible solution for now. But it's always one message at a time and you have to define a component.

### Proposed solution
This is how it is implemented in other Vue frameworks.

- https://lusaxweb.github.io/vuesax/components/notifications.html
- https://www.iviewui.com/components/notice-en
- https://vuecomponent.github.io/ant-design/components/notification/
- http://element.eleme.io/#/en-US/component/notification
- https://quasar-framework.org/components/notify.html

In Vuetify this could be something like this:

```js
this.$vuetify.notify({
  type: 'info',
  title: '...',
  message: '...',
  closable: true,
  timeout: 2000,
});
```

**Comment by KaelWD** [comment] 2018-06-29 20:02
Duplicate of #3037, maybe also #2384

**Closed by KaelWD** 2018-06-29 20:02 UTC

**Comment by qinkaiyuan** [comment] 2019-02-22 14:55
> 重复[＃3037](https://github.com/vuetifyjs/vuetify/issues/3037)，也许[＃2384](https://github.com/vuetifyjs/vuetify/issues/2384)
> 
> > snackbar [...]一次只有一条消息
> 
> 这永远不会改变

why? 

This is a strong demand from everyone. Why should we refuse? And don't give reasons
