### ISSUE TITLE
[Bug Report] Component Data table (Paginate and sort server-side)

### ISSUE THREAD

**Issue by Alexeykhr** [vuetifyjs/vuetify#3711] opened 2018-03-30 08:56 UTC
### Versions and Environment
**Vuetify:** 1.0.11
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
1. Open the Developer Console
2. Click the link Codepen
3. Look at the boot process

### Expected Behavior
After initializing the component, 1 request is sent to the server

### Actual Behavior
3 times request is sent to the server (2 without mounted)

### Reproduction Link
[https://codepen.io/anon/pen/MVVpBZ?editors=1010](https://codepen.io/anon/pen/MVVpBZ?editors=1010)

### Other comments
The code is taken from the documentation - https://vuetifyjs.com/en/components/data-tables#example-server
What is the correct way to solve this problem?

**Comment by KaelWD** [comment] 2018-03-30 09:27
Duplicate of #3585 

And you're getting three instead of two because you're calling it in two places.

**Closed by KaelWD** 2018-03-30 09:27 UTC
