### ISSUE TITLE
[Feature Request] Type support when create custom component with VInput

### ISSUE THREAD

**Issue by Ricky816845** [vuetifyjs/vuetify#18555] opened 2023-10-27 11:19 UTC
### Problem to solve
I want to create some custom input component ,but I dont't know how to inherit the prop deine of VInput.porps. 
Using Typescript

### Proposed solution
Expose some prop type or build functions?

**Comment by websitevirtuoso** [comment] 2023-10-27 19:29
Duplicated. We have ticket about export TS types to reuse in own code. Still in progress

**Comment by KaelWD** [comment] 2023-11-13 16:09
Duplicate of #16680

**Closed by KaelWD** 2023-11-13 16:09 UTC
Labels: S: triage
