### ISSUE TITLE
[Bug Report][3.1.5] VSelect position

### ISSUE THREAD

**Issue by RadBe** [vuetifyjs/vuetify#16663] opened 2023-02-14 19:07 UTC
### Environment
**Vuetify Version:** 3.1.5
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
When I create multiply forms, VSelect position on first click is far from element

### Expected Behavior
Normal position

### Actual Behavior
Far position

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVc1u2zAMfhXBl3RAZLfNejHSocOw+0671D0ospKqkSVBot0GQd59pH/z1wEDpostfhTJjyKp533y3fu0qVWSJ0tQlTcC1LfCMrZsuPC+/W03ldCWSSNifCySd/5wy6oPLmpwRdIroZp0lWf5Vu1QRxcJy50H7Swd6f9Q2PC1C6TA0OL9LZ4XK7nM6OzgLuv8dYHgpotkmR1FiNsog/bAooLaMyPsBo0CekBUV94FYHsW1Jod2Dq4is2Q5myEflConTzNaENZQLiwEsME1sfLHtnznukyZ3dzZkWlcjbTGMbdjB3maJ+Q+xPkHpEXCrYLD4NJ5knnFEn59C06i9neEzdMQgtg0DlrJSTDQGhfJK8APuZZVlu/3aSYoOwJsSzUFnSleOmqp0W6SG+5MP5VpF+zUkc4hlMVK74K7j2qgI6LZH7kA/R695mfHkbzd+lDZ7YXkckLUxnab1TgQdlSBRX+Gv6Z7jUKZyoXNMj1obAHzKzRdhvPkipjm9DnIcJ/4ldpm7YG6DReJDkZ6uOsSwpYlroZu6Lka6M+2FsdyRCPXkjFVwrelbJMGL2xXCoLlJ6h0KNxwLJ+18vQ5NRRDV+BZU/SaLklF1oYt8GihEBFMuox9rPUMO3wHDhnQPtJRktI0I2Atv+8wPxCx3NaxklBlU+95Pw5Kp1pz64MuT/FQH0AQhRImqbH6ECwa2YkNPb5xHUcND1F7ELA8Pg0chaLaeTgEKlcqcyYkpNcoBUpQslAg1FEREXkOd6T3/GHE/3xBCcOJ0AL4byqzqStPCqj5FHWhzUFp62v4be4ki1aOc2Lk+F4qUMqfCBCY+ZTpYbckM/ymkojghaWLqimpsK2UVf1Ak7TYLlbvV2lpsQG6/dCbMSq5dt+z80WMBXAVAYXSSXh9UsYkElIku7i+zeiK6T/80JQMZZqjRn6FZyPN+1U6a8IxzQNni+dVvdUjE2Jpm7WwkSFcAdN99/DtjYG0fF1SA7z5GQA4rRph1Ly8geKuVSb)

### Other comments
![demo](https://i.imgur.com/nxEKbcd.gif)

**Comment by joel-wenzel** [comment] 2023-02-15 18:31
Seems like this has to do with the body scroll height. If there is no scroll on the body or you are at the top then it works ok

**Comment by benoitkugler** [comment] 2023-02-21 12:46
I've encountered the same issue : [playground repro](https://play.vuetifyjs.com/#eNqVUk2P0zAQ/SsjXwJSkywsXEoXFS4cOHBYcWp6cB2nNfWXbKcLqvrfGTtpG3cXBJco8+b5vXmjWR3JJ2urQ8/JnCwCV1bSwD82GmBxKKm16TcVigo9VqluBZVmC9gwLZcPDfE789SQCyWRGHXtBGnCiJWB/wyTxkj3XHIWQNLNoJjKhsBc4GgekVVBixkUm/hhxTrahak8GtRnmUw+wi8Zn/FrMgSGaFfWJPUmaFgyKdh+TAwPEFzPs+BNeIydcUNz+PY1N0SR6Sal8NlIA1LGzLjezji0EiA0vL3LbAAejeLgLWXcQzDgmTNS5l4XqSxhZvlP8YAZmSYxjuptnjdP+/n7l6nVNWysLlcUi+G+FvXk7rDEFMIG8Dz0sS2UNS7AERzv4ASdMwoKPNgikpnRHqnDoEh41VHp+esPUXXQQQUyI4MIutvqhzcaj/0Yh8C9poZvyBwSEjEUj3VDdiFYP6/rXtv9tmJG1Uvs1a7XQShetkYt76v76q6k0u5o9a5uca3TdsW9KjfOPHnu0Lghs4lHEN2vP/mMbZR/U70fZEcoSj6TqlH/wF3puG654+6v499wX4pwQ3kWI1qfGn3CzUqh9/5mqcynha7OE/5XPiV0lQTi63U0Oc1INiO6pndk/RtwsHis)

**Comment by KaelWD** [comment] 2023-03-07 13:40
Duplicate of #16770

**Closed by KaelWD** 2023-03-07 13:40 UTC
Labels: S: triage

**Comment by qxygene** [comment] 2023-03-12 00:48
any fix yet?
