### ISSUE TITLE
[Bug Report] v-text-field type="number" not working

### ISSUE THREAD

**Issue by opahopa** [vuetifyjs/vuetify#9577] opened 2019-11-05 11:49 UTC
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Ubuntu undefined

### Steps to reproduce
https://codepen.io/opahopa/pen/GRRxRxx

### Expected Behavior
console.log(typeof v); output `number`

### Actual Behavior
console.log(typeof v); output `string`

### Reproduction Link
<a href="https://codepen.io/opahopa/pen/GRRxRxx" target="_blank">https://codepen.io/opahopa/pen/GRRxRxx</a>

**Comment by jacekkarczmarczyk** [comment] 2019-11-05 11:54
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6096

**Closed by jacekkarczmarczyk** 2019-11-05 11:54 UTC
Labels: triage
