### ISSUE TITLE
[Bug Report] Floating Action Button hides under bottom navigation

### ISSUE THREAD

**Issue by joshas** [vuetifyjs/vuetify#3337] opened 2018-02-19 18:55 UTC
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Firefox 58.0
**OS:** Windows 7

### Steps to reproduce
Add FAB to view with bottom navigation component.

### Expected Behavior
FAB vertical position (not z-index) is adjusted to keep button above bottom navigation.

### Actual Behavior
FAB is positioned in corner and bottom navigation partially covers it.

### Reproduction Link
[https://codepen.io/anon/pen/oEEVQp?&editors=111](https://codepen.io/anon/pen/oEEVQp?&editors=111)

**Comment by johnleider** [comment] 2018-02-20 22:25
I'm not sure if I agree that it is a bug. There is nothing that explicitly states that the above is the intended behavior, unless I'm mistaken.

**Comment by chewy94** [comment] 2018-02-20 22:36
@johnleider If you look closely you can see that the FAB appears translucent. Not sure if you saw this and still think this is not a bug

**Comment by KaelWD** [comment] 2018-02-22 03:34
The fab isn't translucent, the bottom nav is transparent and covering the FAB. 

Duplicate of #2895

**Closed by KaelWD** 2018-02-22 03:34 UTC
Labels: pending review
