### ISSUE TITLE
Need help: v-tab-item content not displayed

### ISSUE THREAD

**Issue by KingKnecht** [vuetifyjs/vuetify#4536] opened 2018-07-08 17:41 UTC
Vuetify: 1.1.1
Vue: 2.5.16
Browsers: Electron 2.0.4
OS: Win10 x64

### Previously worked in:
Vuetify: 1.0.0
Vue: 2.5.16

Sorry, can not provide a codepen because it's working there.

With version 1.1.1 the content of v-tab-item is not rendered.
The error message with 1.1.1 is:

```
vue.esm.js?efeb:591 [Vue warn]: Error in callback for watcher "activeIndex": "TypeError: Cannot set property 'transition' of undefined"

found in

---> <VTabsItems>
       <VTabs>
         <VContent>
           <VApp>
             <VuetifyTest02> at src\renderer\App.vue
               <Root>
```

and the result looks like:

![image](https://user-images.githubusercontent.com/4339172/42422458-971ed508-82e6-11e8-8869-b3aa3bc903d9.png)

where with 1.0.0 I get:

![image](https://user-images.githubusercontent.com/4339172/42422464-d01e8cfe-82e6-11e8-9602-ad04d951f59f.png)

Any ideas?
Thanks,
Sven

**Comment by KaelWD** [comment] 2018-07-08 18:15
Duplicate of #4068

**Closed by KaelWD** 2018-07-08 18:15 UTC
