### ISSUE TITLE
Unknown html tag on PhpStorm when upgrade version from 1.1.x to 1.2.x

### ISSUE THREAD

**Issue by baksosapi** [vuetifyjs/vuetify#5421] opened 2018-10-25 00:55 UTC
**Versions and Environment**
**Vuetify**: 1.2.x and 1.3.x
**Last** working version: 1.1.17
**Vue**: 2.5.17
**Browsers**: Version 70.0.3538.67 (Official Build) (64-bit)
**OS**: Mac OS 10.13.4
**IDE**: PhpStorm 2018.2

**Steps to reproduce**
Upgrade vuetify version on package.json

**Expected Behavior**
Same behavior when using 1.1.17 version, PhpStorm recognize the html tag produced by Vuetify

**Actual Behavior**
PhpStorm .vue file, unknown html tag when click on vuetify tag.

Other comments
Trying with 1.2.x version and 1.3.x version , get same failed..

**Comment by KaelWD** [comment] 2018-10-25 01:04
Duplicate of #1256

**Closed by KaelWD** 2018-10-25 01:04 UTC

**Comment by jacekkarczmarczyk** [comment] 2018-10-25 01:07
I'd say https://github.com/vuetifyjs/vuetify/issues/4590
