### ISSUE TITLE
[Bug Report] Default v-text-field cuts off error message

### ISSUE THREAD

**Issue by nmagee-akiri** [vuetifyjs/vuetify#6785] opened 2019-03-21 12:57 UTC
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 2.6.9
**Browsers:** Firefox 65.0
**OS:** Mac OS 10.14

### Steps to reproduce
Create a default text field, the provided codepen is a modification of an example in the vuetify docs. Add an error message to it. It is easier to see it cutting the text off if the message contains the letter 'g'.

### Expected Behavior
Should not cut off the error message.

### Actual Behavior
takes a couple of pixels off the bottom of the text

### Reproduction Link
<a href="https://codepen.io/nmagee12/pen/BbGKpR" target="_blank">https://codepen.io/nmagee12/pen/BbGKpR</a>

### Screenshot
<img width="924" alt="default-text-field-cut-off" src="https://user-images.githubusercontent.com/39836317/54753366-a0cae900-4bbf-11e9-828a-65f1c7537755.png">

**Comment by nmagee-akiri** [comment] 2019-03-21 13:07
this appears to be related to the line height. increasing it to `1.5` stops the cutoff

**Comment by KaelWD** [comment] 2019-03-21 13:47
Duplicate of #4655

**Closed by KaelWD** 2019-03-21 13:47 UTC
Labels: duplicate
