### ISSUE TITLE
Datepicker Dialog with Disabled Text Field Shouldn't Display Dialog when It is Clicked

### ISSUE THREAD

**Issue by jefrydco** [vuetifyjs/vuetify#4885] opened 2018-08-16 09:53 UTC
### Versions and Environment
Vuetify: 1.1.12
Vue: 2.15.6
Browsers: Chrome 68.0.3440.106
OS: Ubuntu 18.04

### Steps to reproduce

Create a datepicker dialog with disabled textfield as its activator.

### Expected Behavior

When the datepicker dialog clicked, it shouldn't display the dialog.

### Actual Behavior

It is displaying the dialog.

### Reproduction Link

https://codepen.io/jefrydco/pen/NBZdKo

---

**Comment by jacekkarczmarczyk** [comment] 2018-08-16 10:06
duplicate of https://github.com/vuetifyjs/vuetify/issues/765

**Closed by jacekkarczmarczyk** 2018-08-16 10:06 UTC
