### ISSUE TITLE
[Bug Report] v-select, secondary event comes 

### ISSUE THREAD

**Issue by sg21210** [vuetifyjs/vuetify#3872] opened 2018-04-18 02:37 UTC
### Versions and Environment
**Vuetify:** 1.0.15
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
1. Create v-select with combobox
2. Bind them with a dictionary value
3. Type a value in the form, with variations such as
 - Custom input with keyboard / Select one option with mouse(keyboard)
 - Switch to next v-select with mouse click, keyboard 'Tab' key, or just leave the form with clicking another area in the page.
 - Copy-paste / manual typing

### Expected Behavior
Every method should be work correctly, without occurring any rule violation

### Actual Behavior
Some of them raises the exception: the field is still empty. You can notice that by 'rules' in v-select.
Also, from the console log, you can see that another event having no input also comes in.

### Reproduction Link
[https://codepen.io/anon/pen/jxONLy?editors=1111](https://codepen.io/anon/pen/jxONLy?editors=1111)

**Comment by KaelWD** [comment] 2018-04-20 07:06
Duplicate of #3811

**Closed by KaelWD** 2018-04-20 07:06 UTC
