### ISSUE TITLE
[Bug Report][3.7.5] VAutocomplete: "Multiple nodes with the same ID" error - with just 7 simple items

### ISSUE THREAD

**Issue by hseip** [vuetifyjs/vuetify#20767] opened 2024-12-07 17:27 UTC
### Environment
**Vuetify Version:** 3.7.5
**Vue Version:** 3.5.13
**Browsers:** Chrome 129.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Enter 'nut' and select the 2nd item '111336 Fruit and Tree Nut Combination Farming'

### Expected Behavior
No error in console

### Actual Behavior
"Multiple nodes with the same ID" error

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp1U8Fu2zAM/RXOF7dAs8xN2q2BW6Dr0G2HZQMybIc4B0VmWwGyJFBStiLIv49WksVF6ostke89EuLjfJ15ksNb596uImaTrAzYOC0C3lQGoFwNhHPpmC7SmiCUQdqFtogYrLTMwoD7MMBq0Nga9XWVpX+VHVITxUU8Z+aVWbdhVU+gGJ+1x0/oJSkXlDUTyIuiGI3O4TMJh/CLCz8Lqn1emQ2DD9SLPuoIZoHEnyUSPcO9oEaZxyP2ZR97DB8T8QT/SnSho3W6F4Mjtfd9ahfwkxBhGkNvJx/6uJdwT1EFEKY+qNzZZqmMaHG9ild9ilfwPTwhwdQaqQJFv6vQI3T+7nWhcVHAt+ifyNoGfpCto0z97PiL7tjbqQ+CChp59B2lI8xK6NhiVN1NabFMdpqhRslPAdPbr3czkOyuLszGoNko9SEiNQoSS/3fnDfl8KVr9wbn8EuHJ2BagHLYWQy+brsHjyFu90M1zlKANRA+wAYeiB8k553il2jTrOsDNP4RrlvESf4Ftbbw25Ku3+SnLYQ7gbQrO8h8weFyuK3ENbLNmYlap8/iHzRXMTo=)

The issue was introduced with Vuetify version 3.7.2

**Comment by J-Sek** [comment] 2024-12-07 18:21
Duplicate of #20516

**Closed by J-Sek** 2024-12-07 18:21 UTC
Labels: S: triage
