### ISSUE TITLE
[Feature Request] Smaller V-select

### ISSUE THREAD

**Issue by johnsutor** [vuetifyjs/vuetify#5510] opened 2018-11-02 00:08 UTC
### Problem to solve
The v-select comes in one standard size, which can only come altered via the height styling

### Proposed solution
Create a mini v-select similar to that on youtube's mobile app (view videos/ videos and posts)

**Comment by KaelWD** [comment] 2018-11-02 03:03
I can't see the select you're talking about in the app, but this looks like a duplicate of #1846

**Closed by KaelWD** 2018-11-02 03:03 UTC
