### ISSUE TITLE
[Bug Report] trailing list-tile-action right aligned when in mini navigation-drawer

### ISSUE THREAD

**Issue by mattnathan** [vuetifyjs/vuetify#6732] opened 2019-03-14 15:17 UTC
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.6.8
**Browsers:** Chrome 73.0.3683.75
**OS:** Windows 10

### Steps to reproduce
Create a `v-navigation-drawer` using a `v-list` that has `v-list-tile-content` followed by `v-list-tile-action` with a `v-icon` in it. Specify the `mini-variant` property on the nav-drawer.

### Expected Behavior
The action icon should be center aligned.

### Actual Behavior
The action icon is right-aligned (`justify-content: flex-end`)

### Reproduction Link
<a href="https://codepen.io/anon/pen/BbYJdM" target="_blank">https://codepen.io/anon/pen/BbYJdM</a>

**Comment by mattnathan** [comment] 2019-03-14 15:19
I have this in my `main.styl`

```stylus
.v-navigation-drawer
  &--mini-variant
    .v-list__tile__content ~ .v-list__tile__action:not(.v-list__tile__action--stack)
      // Make sure that the list tile action is centered when the content is hidden as part of mini-variant
      // see https://github.com/vuetifyjs/vuetify/issues/6732
      justify-content: center
```

Though don't know if there are some other edge cases that this is including/excluding as part of the override

**Comment by johnleider** [comment] 2019-04-12 03:09
Duplicate of #2606

**Closed by johnleider** 2019-04-12 03:09 UTC
Labels: C: VList, C: VNavigationDrawer
