### ISSUE TITLE
[Bug Report] Dialog/Menu/Tooltip output an extra element and break layout

### ISSUE THREAD

**Issue by augustoborn** [vuetifyjs/vuetify#6951] opened 2019-04-09 10:58 UTC
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Linux x86_64

### Steps to reproduce
Add a dialog inside a nav drawer, using a v-list-tile in the activator slot of the dialog.

### Expected Behavior
The dialog activator should have the exact spacing as the other drawer items.

### Actual Behavior
The dialog activator has extra spacing below it.

### Reproduction Link
<a href="https://codepen.io/anon/pen/ROKPZo" target="_blank">https://codepen.io/anon/pen/ROKPZo</a>

### Other comments
Poking around the inspector, it looks like the problem stems from the v-dialog__container div right under the v-list-tile activator. Setting its style to display: none fixes the issue.

**Comment by blalan05** [comment] 2019-04-10 02:52
Possible solution: There is an "extra" div added after the first v-list-tile with the inline style of display: inline-block; changing it to display: none fixes the styling.

**Comment by usb248** [comment] 2019-06-19 08:00
Any fix ?

**Comment by augustoborn** [comment] 2019-06-19 16:47
> Any fix ?

My workaround was using this in my app's main CSS file:

.v-dialog__container {
  display: none !important;
}

**Comment by ipluser** [comment] 2019-06-28 00:54
how to fix it?

**Comment by matthewma7** [comment] 2019-07-07 10:37
The question here is why it needs to be inline-block? https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDialog/VDialog.js#L331

**Comment by usb248** [comment] 2019-07-11 19:17
> 
> 
> > Any fix ?
> 
> My workaround was using this in my app's main CSS file:
> 
> .v-dialog__container {
> display: none !important;
> }

@augustoborn  very dirty ...

**Comment by gorsat** [comment] 2019-08-20 19:51
Same problem in v-menu with the activator slot. The same dirty fix works: 
.v-menu--inline {
  display: none !important;
}
1. Is there a real fix coming? 
2. Should I open a different bug for this one?

**Comment by jessielaf** [comment] 2019-09-05 12:39
Is there a fix coming this or is this intended behavior?

**Comment by johnleider** [comment] 2019-09-05 13:52
I'm working on a fix for this right now. In the meantime, here is a workaround: https://codepen.io/johnjleider/pen/oNvpXrv

**Comment by xyannik** [comment] 2019-09-24 09:00
Hi, I posted [this issue](https://github.com/vuetifyjs/vuetify/issues/8777) which was marked as duplicate of 6951. But I didn't get a real response on my question: Is it expected behaviour, that in 2.0 dialogs/menus/tooltips in the HTML get added as a sibling of the activator? In 1.5 they got added as child-elements instead of siblings. Since I often use them in Grid-/Flex-Layouts, this has caused a couple of render issues. I'd like to know if this will be reverted in the next release, before I change all my related CSS (either way is fine, I just don't want to change all my CSS, only to have to change it back in the next release). Thanks

**Comment by KaelWD** [comment] 2019-10-01 12:55
Um yeah that doesn't really fix this @johnleider, the elements are still visible so throw off the layout in a flex element.

**Closed** 2019-10-01 18:01 UTC
Labels: C: VDialog, C: VMenu, C: VTooltip, T: bug, has workaround
