### ISSUE TITLE
[Feature Request] add tree -select component

### ISSUE THREAD

**Issue by index-xiao** [vuetifyjs/vuetify#15334] opened 2022-06-23 01:21 UTC
### Problem to solve
Sometimes the selected data may be in tree structure

### Proposed solution
Add a tree drop-down option on the basis of the v-select component,It supports single selection, multiple selection and cascade selection

**Comment by websitevirtuoso** [comment] 2022-06-23 03:58
What about this one?
https://vuetifyjs.com/en/components/treeview/#item-disabled
You always can modify it

**Comment by KaelWD** [comment] 2022-06-23 07:32
Duplicate of #3049

**Closed by KaelWD** 2022-06-23 07:32 UTC
Labels: S: triage
