### ISSUE TITLE
[Documentation] [3.1.8] The Labs v-data-table Codepen examples do not work

### ISSUE THREAD

**Issue by lukasrossa** [vuetifyjs/vuetify#16905] opened 2023-03-14 07:29 UTC
### Environment

**Browsers:** Chrome 111.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Open the Labs data tables documentation
2. Click 'Edit in Codepen' option

### Expected Behavior
example opens in Codepen and data table shows described functionality

### Actual Behavior
Codepen runs but the data table does not show up in any of the examples. There is an warning in the console: [Vue warn]: Failed to resolve component: v-data-table

### Reproduction Link
[https://vuetifyjs.com/en/components/data-tables/basics/](https://vuetifyjs.com/en/components/data-tables/basics/)

### Other comments
Although the v-data-table is in labs, one should still be able to view and play with the examples in a Codepen. If this requires tweaking the Codepen, document somewhere what is required.

**Comment by KaelWD** [comment] 2023-05-27 07:00
Duplicate of #17386

**Closed by KaelWD** 2023-05-27 07:00 UTC
Labels: C: VDataTable, S: triage
