### ISSUE TITLE
request: hope v-text-field can be given different sizing options to fit a multitude of scenarios

### ISSUE THREAD

**Issue by kyorry** [vuetifyjs/vuetify#2151] opened 2017-10-12 02:47 UTC
hope v-text-field can be given different sizing like buttons, eg. small, normal, large...

**Comment by KaelWD** [comment] 2017-10-12 03:27
Please update your issue using the provided template for issues, including a reproduction link, or the issue will be closed.

Duplicate of #1846

**Closed by KaelWD** 2017-10-12 03:27 UTC
