### ISSUE TITLE
[Bug Report] Misaligned outlined text field label when reversed

### ISSUE THREAD

**Issue by chaptergy** [vuetifyjs/vuetify#13037] opened 2021-01-31 20:10 UTC
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.11
**Browsers:** Firefox 85.0
**OS:** Linux

### Steps to reproduce
Create a vuetify text field and add the `outlined` and `reverse` property to it. 

### Expected Behavior
The label and gap for the label will be on the right

### Actual Behavior
While the label is on the right, the gap remains on the left side

### Reproduction Link
<a href="https://codesandbox.io/s/quiet-hooks-w51w0" target="_blank">https://codesandbox.io/s/quiet-hooks-w51w0</a>

**Comment by dchinu97** [comment] 2021-02-03 15:11
@KaelWD @MajesticPotatoe Seems like an interesting issue to work on, can you please assign it to me?
I think just assigning align= reverse ? "right" : "left" to <legend> should solve the Issue

**Comment by KaelWD** [comment] 2021-02-03 15:14
Duplicate of #10798

**Closed by KaelWD** 2021-02-03 15:14 UTC
Labels: triage
