### ISSUE TITLE
[Feature Request] Option to change language snippet in Data Iterable

### ISSUE THREAD

**Issue by shopfreelancer** [vuetifyjs/vuetify#3927] opened 2018-04-25 08:42 UTC
Hey there,
I´m working with the Data Tables component and need to translate some texts. Which works pretty neat with props like rowsPerPageText. 

I found a snippet which is not really easy to change athough and it is the amount of results "1-5 of 75".

The code is generated in the mixin data-iterable.js in line 436 in a private variable for the pagination
``${this.pageStart + 1}-${stop} of ${this.itemsLength}``
The word "of" is hard coded here and to change it there needs to be jQuery-ish scraping of innerHtml plus an watcher whenever the pagination changes again. Kind of bloated.

So my request is: it would be good to have a prop to override the word here.

Thanks for your excellent work though!

**Comment by KaelWD** [comment] 2018-04-25 08:50
Duplicate of #2428

**Closed by KaelWD** 2018-04-25 08:50 UTC

**Comment by shopfreelancer** [comment] 2018-04-25 09:14
...and it´s even in the documentation. My bad, sorry. Works like a charm with the slot, thanks for the hint.
