### ISSUE TITLE
[Bug Report][2.5.10] v-calendar display width of event is wrong when use custom-daily type

### ISSUE THREAD

**Issue by sondt1610** [vuetifyjs/vuetify#14333] opened 2021-10-28 11:59 UTC
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 95.0.4638.54
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Open codepen of v-calendar type week (https://vuetifyjs.com/en/components/calendars/#type-week)
2. Edit calendar type to custom-daily
3. Edit start=2021-10-16, end=2021-10-22,
4. Edit Weekly Meeting event with start: 2021-10-15, end: 2021-10-22

### Expected Behavior
Weekly Meeting event will display span from 2021-10-16 to 2021-10-22

### Actual Behavior
Weekly Meeting event only display span from 2021-10-17 to 2021-10-22

### Reproduction Link
<a href="https://codepen.io/sondt1610/pen/OJjgEyv" target="_blank">https://codepen.io/sondt1610/pen/OJjgEyv</a>

**Comment by KaelWD** [comment] 2021-11-03 10:09
Duplicate of #13059

**Closed by KaelWD** 2021-11-03 10:09 UTC
Labels: S: triage
