### ISSUE TITLE
[Documentation] Simple tables

### ISSUE THREAD

**Issue by logliveru** [vuetifyjs/vuetify#8776] opened 2019-08-29 07:20 UTC
### Environment
**Vuetify Version:** 2.0.11
**Vue Version:** 2.6.10
**Browsers:** Chromium 76.0.3809.100
**OS:** Ubuntu undefined

### Steps to reproduce
link to source does not work - 404
https://github.com/vuetifyjs/vuetify/tree/master/packages/vuetify/src/components/VSimpleTablethe 

example does not work on codepen.io

### Expected Behavior
preview in the example works

### Actual Behavior
example does not render preview

### Reproduction Link
<a href="https://vuetifyjs.com/ru/components/simple-tables" target="_blank">https://vuetifyjs.com/ru/components/simple-tables</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-29 08:27
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8099

**Closed by jacekkarczmarczyk** 2019-08-29 08:28 UTC
Labels: triage
