### ISSUE TITLE
[Bug Report][3.1.1] Autocomplete doesn't work when items coming from API are objects in Firefox 108

### ISSUE THREAD

**Issue by djcaesar9114** [vuetifyjs/vuetify#16443] opened 2023-01-14 21:16 UTC
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.45
**Browsers:** Firefox 108.0
**OS:** Ubuntu undefined

### Steps to reproduce
Follow what is written in the documentation. Even the example doesn't work in Firefox although it works with Chrome.

### Expected Behavior
I expect the items to be filtered with the string written depending on a key of the objects.

### Actual Behavior
Nothing is found, the items are fetched (I see the response in the console), but I have to blur then focus again in the input to see the items.

### Reproduction Link
[https://codepen.io/djcaesar9114/pen/GRBvgYN?editors=101](https://codepen.io/djcaesar9114/pen/GRBvgYN?editors=101)

**Comment by sebastienbredard** [comment] 2023-01-16 08:32
I've tried on others browsers : iridum (Chrome based) and Vivaldi, I have the exact same behavior.
Back to 3.0.x everything is OK.

NB : It seems to behave like this only when working with objects. If you give an array of strings to the v-autocomplete, it's OK.

**Comment by KaelWD** [comment] 2023-01-16 08:34
Duplicate of #16403

**Closed by KaelWD** 2023-01-16 08:34 UTC
Labels: S: triage
