### ISSUE TITLE
[Bug Report] Build fails due to errors in VFooter.js with both 1.2.0 and 1.2.4

### ISSUE THREAD

**Issue by henon** [vuetifyjs/vuetify#5144] opened 2018-09-21 17:25 UTC
### Versions and Environment
**Vuetify:** 1.2.4
**Last working version:** 1.0.17
**Vue:** 2.5.17
**Browsers:** Chrome 64.0.3282.140
**OS:** Windows 10

### Steps to reproduce
npm run serve

### Expected Behavior
build goes through

### Actual Behavior
build fails with the error:

### Reproduction Link
[https://github.com/henon/vuetify_build_error01](https://github.com/henon/vuetify_build_error01)

### Other comments
ERROR  Failed to compile with 4 errors19:02:16

These relative modules were not found:

* ../../mixins/applicationable in ./node_modules/vuetify/src/components/VFooter/VFooter.js
* ../../mixins/colorable in ./node_modules/vuetify/src/components/VFooter/VFooter.js
* ../../mixins/themeable in ./node_modules/vuetify/src/components/VFooter/VFooter.js
Failed to resolve loader: stylus-loader
You may need to install it.
 ERROR  Build failed with errors.

Note: after installing stylus-loader, the other three errors will remain.

**Comment by henon** [comment] 2018-09-21 17:30
Here is what I tried that did NOT help:

* deleted node_modules and reinstalled all using "npm install"
* created a new vuetify project from scratch using "vue create my-app" and "vue add vuetify", then added my code in that new project. still the same errors.
* commented out the <v-footer> tag in App.vue. Still fails to build in VFooter.js

I am out of ideas. This is way over my head.

**Comment by jacekkarczmarczyk** [comment] 2018-09-21 17:39
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4674

**Closed by jacekkarczmarczyk** 2018-09-21 17:39 UTC

**Comment by henon** [comment] 2018-09-21 20:19
I wasn't aware the IDE had automatically imported VFooter from "vuetify/src". Thank you so much for the quick help.
