### ISSUE TITLE
[Bug Report][3.0.6] VChipGroup: disabled does not stop emit when v-model has a value

### ISSUE THREAD

**Issue by ErikProresult** [vuetifyjs/vuetify#16454] opened 2023-01-17 06:54 UTC
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.38
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a v-chip-group with a value in the v-model and add disabled. When clicking on the chip that has that value (as in deselect the chip) the v-model will update.

### Expected Behavior
According to docs, disabled v-chip-group should not emit changes. So it shouldn't be possible to deselect while v-chip-group is disabled.

### Actual Behavior
When deselecting a chip, v-model is updated. Only happens when v-model has a value while disabled.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUstu2zAQ/JUFL3ZQPWA7vaiykZ56LNBDL1EOirS22VAkQVIyCkH/3iVlK67VBkhu3MfM7A73sWdftU66FlnGcoeNFqXDXSEB8i4utQ7PEDQll+coxNWR6/hgVKuBiqpGsS2YRYGVw/qbz/8sRYsFg5rb8llgPaEnPHSl4aV0hFStE1xiTf1Z54Hb1e67dlxJWOXp2P5OgvWFYP1Bgs2FYDMjuCRGB17TGipRWkt0WsT3BbtSDHZk0PcwdwmG4ZV5Mp00Jtd9MP5Hnl79E4W2Mlw7InVhEN5oZRz0YHAfwal01REG2BvVwIL+eeExlZLWI2ZjbD1qub774iULGdDL5R1sd//oToJLESwlnkIi9PUe6gWUwESow3LxAyvkHdaAHUoHJ+6OGSw+TSgSGy6KeTquQ4uwiI27kAk6+WWVpBsN7MW5YAtGfo5mFYyW83HBjs5pm6VpK/XLIalUkz5QLTWtdLzBuFbNwyZZJ/efU7pMd51P0Dbxs1Eni4YUCxZdkTu+//0/gXOZeFfJaqQ9pzzljCol/g5NbFDWaNC8OfdN71+z39Rm83tNuqyBvKTbfrE3NlY2WPj45FuGiI3U1Bz2YE9/AF5HXCs=)

### Other comments
Bug also appears on vue-version 3.2.45 and vuetify-version 3.1.1 in the reproduction link

**Comment by KaelWD** [comment] 2023-01-31 12:51
Duplicate of #15923

**Closed by KaelWD** 2023-01-31 12:51 UTC
Labels: S: triage
