### ISSUE TITLE
[Bug Report][3.4.0] v-virtual-scroller doesn't render items past the initial array length

### ISSUE THREAD

**Issue by mhio** [vuetifyjs/vuetify#18658] opened 2023-11-12 03:43 UTC
### Environment
**Vuetify Version:** 3.4.0
**Vue Version:** 3.3.8
**Browsers:** Mozilla Firefox, Google Chrome, Safari
**OS:** Mac OSX

### Steps to reproduce
Create v-virtual-scroller with items of array length x
Push item onto end of array

### Expected Behavior
Items beyond initial array length render

### Actual Behavior
Items cut off at length of initial array (or less). 
Sometime the number of rendered items can be shorter, the scroll detection inconsistently renders to the end, often stopping in the 45-49 range.  The number changes when you scroll back up the item list high enough to move the last items out of the buffer (i.e when I can see the scroll bar height changing)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFUt1umzAUfpUja1JhSghpiSaxJFovd7EnaCrFI6ZYM7ZlG9QO8e47tqELrapyg338/Zy/h4FYU23utc76jpGS7B1rtaCOHU8SYN+vqdbhGC6Vko5yycwUCsHfTsKPSvDqz+FEOmkbXrufKHMix+m23wTUhyTd2WZi+ONncMtcsUVssX2H1MdhAI5SBsZxv5lTDxo9N66jYm0ro4SA0sMsygX4iUDZMP7UOIwUee7v/mFt+V+GodsdGs5iKDe3Cfq1FcqVF1bTTnhy9F8Blxf2DOOChsQL78G6F+FFo2EJtzv9jDifeiSNJfh+wFRMqAWJ1wlsFoOKobc1zoPDh+XkfCQOdqGDVyRy7QBb3GkQVD5hms5ORfBWK+NgAMNo5XjPYITaqBZucHluPAJtrJsGcHiFJXBvDH1Jdnma1VyIBP8t1UnSr3h6OPIUUk+uO4lwJcFQeUlSb+M6I+H8ZfhFXZPVQimThKNHqDZJv25z/NLx/B07fS1xtYeoFPsQ0sqmlySaBOMldd7GNzwf/pgUdnLJeCi2j9gEzD6yRg86v1IXGfrAf18/ljgIbDsZV+Quu8u+Ef8vspw8/gODSzL5)

**Comment by KaelWD** [comment] 2023-11-13 16:08
Duplicate of #18648

**Closed by KaelWD** 2023-11-13 16:08 UTC
Labels: S: triage
