### ISSUE TITLE
[Bug Report][3.0.0-beta.5] Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode') When using v-menu with Nuxt 3 rc.6

### ISSUE THREAD

**Issue by bubundas17** [vuetifyjs/vuetify#15493] opened 2022-07-21 18:33 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** Nuxt 3 rc.6
**Browsers:** Chrome 103.0.0.0
**OS:** Windows 10

### Steps to reproduce
Open up this StackBlitz  Project
https://stackblitz.com/edit/github-znktdt?file=app.vue,layouts%2Fdefault.vue,layouts%2Ftest.vue

Run the app and then open the Live preview URL.
and click on "Page-2" Link 
![image](https://user-images.githubusercontent.com/26280146/180287872-03b5f8d5-de29-48a5-9deb-3ff7453f651c.png)

### Expected Behavior
It should navigate to page-2 and also change the Layout.

### Actual Behavior
Nothing happens, The whole view stucks with the following error:
TypeError: Cannot read properties of null (reading 'parentNode')
![image](https://user-images.githubusercontent.com/26280146/180287961-030be5c6-345f-4f18-bc20-bd3f7d61c9b7.png)

### Reproduction Link
<a href="https://stackblitz.com/edit/github-znktdt?file=layouts/default.vue" target="_blank">https://stackblitz.com/edit/github-znktdt?file=layouts/default.vue</a>

**Comment by KaelWD** [comment] 2022-08-01 09:42
The reproduction link doesn't work, it just gets stuck in a refresh loop. Probably a duplicate of #15323 though.

**Closed by KaelWD** 2022-08-01 09:42 UTC
Labels: S: triage
