### ISSUE TITLE
[Bug Report] V-Select NVDA Screen Reader Reads "blank"

### ISSUE THREAD

**Issue by rkrasnan** [vuetifyjs/vuetify#9702] opened 2019-11-15 16:19 UTC
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows

### Steps to reproduce
Using NVDA 2019.2.1 
Tab to a v-select
Press space to open the menu. 
Press down to go to the first option.

### Expected Behavior
NVDA should read the item in the dropdown, 
eg. "2017", "2018"

### Actual Behavior
NVDA reads "blank" on each option in the dropdown

### Reproduction Link
<a href="https://codepen.io/rkrasnan/pen/bGGQWXZ" target="_blank">https://codepen.io/rkrasnan/pen/bGGQWXZ</a>

### Other comments
Is there a specific screen reader that vuetify is compatible with?

**Comment by KaelWD** [comment] 2019-11-16 02:06
Duplicate of #9680

**Closed by KaelWD** 2019-11-16 02:06 UTC
Labels: C: VSelect, a11y, triage
