### ISSUE TITLE
[Feature Request] Component Page to show up first when searching instead of the API documentation

### ISSUE THREAD

**Issue by tylerhadx-github** [vuetifyjs/vuetify#13586] opened 2021-04-30 16:31 UTC
### Problem to solve
Extra click to getting where the examples are.

### Proposed solution
Going back to your old search that had the components and api seperated out.

**Comment by KaelWD** [comment] 2022-03-04 04:24
Duplicate of #13922

**Closed by KaelWD** 2022-03-04 04:24 UTC
Labels: S: triage
