### ISSUE TITLE
[Bug Report] date-picker event-color does not accept hexadecimal values.

### ISSUE THREAD

**Issue by azampagl** [vuetifyjs/vuetify#3911] opened 2018-04-23 18:38 UTC
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Windows 10

### Steps to reproduce
Create a datepicker and provide a hexadecimal color value to the event-color prop.

### Expected Behavior
event-color prop should be able to accept hexadecimal values / a function that returns hexadecimal values.

### Actual Behavior
event-color prop only works if the value is a string (e.g. "red", "blue", "green").

### Reproduction Link
[https://codepen.io/anon/pen/mLVLjE?&editors=101](https://codepen.io/anon/pen/mLVLjE?&editors=101)

**Comment by praveenpuglia** [comment] 2018-04-24 06:37
So why this happens is because the color that you pass as event color, actually gets added as the `class` for that particular event instead of a `style` declaration.

This is probably done this way so that you can select a color out of the material palette and use that class name as the color for the event.

I agree that the documentation doesn't mention it in the prop description. 

Changing it won't be straight forward though as the component has to decide whether it should go as class or style and we'll probably need a way to differentiate between those two. or only allow class names to be passed like it is right now and mention in the docs that `event-color` works that way.

@KaelWD thoughts?

**Comment by KaelWD** [comment] 2018-04-24 07:38
Duplicate of #3416

**Closed by KaelWD** 2018-04-24 07:38 UTC
