### ISSUE TITLE
[Bug Report] tooltip with :open-on-click="true" issue

### ISSUE THREAD

**Issue by razliberman-bv** [vuetifyjs/vuetify#11236] opened 2020-04-26 15:25 UTC
### Environment
**Vuetify Version:** 2.2.25
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.113
**OS:** Mac OS 10.15.2

### Steps to reproduce
in the examples there are 3 tooltips (I've used your example code)
on each tooltip I've added :open-on-click="true" and :open-on-hover="false"

### Expected Behavior
the tooltip should appear on click

### Actual Behavior
with the span tooltip it works ok.
however, with the button and icon, the tooltip - only on the first click - appear and immediately disappears. the next clicks work ok.

### Reproduction Link
<a href="https://codepen.io/razuli/pen/qBOmXzY?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftooltips%2F" target="_blank">https://codepen.io/razuli/pen/qBOmXzY?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Ftooltips%2F</a>

**Comment by jacekkarczmarczyk** [comment] 2020-04-26 15:34
workaround https://codepen.io/jkarczm/pen/mdemBPY?editors=1000

**Comment by KaelWD** [comment] 2020-08-21 07:58
Duplicate of #8213

**Closed by KaelWD** 2020-08-21 07:58 UTC
Labels: C: VTooltip, has workaround, triage
