### ISSUE TITLE
[Feature Request] Date-time component 

### ISSUE THREAD

**Issue by MapleWithoutWords** [vuetifyjs/vuetify#20432] opened 2024-09-06 07:05 UTC
### Problem to solve
I hope there is a date and time component, because I have a lot of list queries that need to choose a date time range, and I must be accurate to time

### Proposed solution
I hope to increase the function of choosing time based on VDATEINPUT expansion

**Comment by KaelWD** [comment] 2024-09-06 09:29
Duplicate of #459

**Closed by KaelWD** 2024-09-06 09:29 UTC
Labels: S: triage
