### ISSUE TITLE
[Bug Report][2.5.8] Press the left and right mouse buttons simultaneously several times in a row on “v-btn” ，the background color will be abnormal.

### ISSUE THREAD

**Issue by Lilac-Dream** [vuetifyjs/vuetify#14104] opened 2021-09-01 07:30 UTC
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 92.0.4515.159
**OS:** Windows 10

### Steps to reproduce
Press the left and right mouse buttons simultaneously several times in a row on “v-btn” ，the background color will be abnormal.

### Expected Behavior
don't change background
![image](https://user-images.githubusercontent.com/49761134/131630613-d7c0f8b1-385d-4f1b-ade1-a79f1d12178e.png)

### Actual Behavior
The background color will be abnormal
![image](https://user-images.githubusercontent.com/49761134/131630481-cc2e4952-78fe-4ab3-9475-418adf8c0c39.png)

### Reproduction Link
<a href="https://codepen.io/qq1535649370/pen/qBjZqjQ" target="_blank">https://codepen.io/qq1535649370/pen/qBjZqjQ</a>

**Comment by KaelWD** [comment] 2021-09-01 07:53
Duplicate of #4185

**Closed by KaelWD** 2021-09-01 07:53 UTC
Labels: S: triage
