### ISSUE TITLE
[Bug Report] Wrong position of label for inputs with outline style

### ISSUE THREAD

**Issue by JesusCrow** [vuetifyjs/vuetify#5623] opened 2018-11-15 16:12 UTC
### Versions and Environment
**Vuetify:** 1.3.8
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.102
**OS:** Mac OS 10.14.1

### Steps to reproduce
Add some text to input field

### Expected Behavior
Label should be on border line.
![image](https://user-images.githubusercontent.com/6717694/48565719-e326a580-e901-11e8-93f1-24808153c2ba.png)

### Actual Behavior
Label moves above input text (below border).
![image](https://user-images.githubusercontent.com/6717694/48565697-d5712000-e901-11e8-909c-e14f673df4ef.png)

### Reproduction Link
<a href="https://codepen.io/anon/pen/MzmdKR" target="_blank">https://codepen.io/anon/pen/MzmdKR</a>

**Comment by jacekkarczmarczyk** [comment] 2018-11-15 18:50
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4073

**Closed by jacekkarczmarczyk** 2018-11-15 18:50 UTC
