### ISSUE TITLE
[Documentation] I cannot able to uncheck the list components

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#19436] opened 2024-03-19 15:54 UTC
### Environment

**Browsers:** Chrome 122.0.0.0
**OS:** Windows 10

### Steps to reproduce
Try to interact with above demo link

### Expected Behavior
It should be unchecked

### Actual Behavior
It does not unchecked.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrVVsFu2zAM/RXC5zntsO7QoitQbMCwyzCs2GnZgZGYWJgseRKdNCj676NkO7VzyIakPfQUWXx8FPlIKT8fihjU2W3TzNYtFVfFNVPdWGS6mTuA63WpMOi0BFAWY/wwL+r7Elv286LbrvG+3BjNlZguzs+77eyd/dl7u8AAylsfBNK0obE0L3pExizYgVHeJXJtyppcK4Drs2wR4Aja05Vs2NLNHTEbt4oJOrVMnGKDikIm7JcT8354XDmz3E5OkJFPQXb+4m1NZLDGUaoNV4H2kkv2MraLilBL5B+RAnz0joO3+dx79snJss2IJDvC6XafbKIjx7A0lilIQXa8I9AT8R6HxB4Qgx1AKgtckci2Rw2W1mSBPQSKHIxiwKbhKGhkUOhgQaD9xlkv+fStM5TvQNCJ+agqfJP23PigT0/+O/1pTSBoekZY+gDSuKrCSCDrVn52xnEpBtDRaY/3xl2mzdqk9ki2Yf2PJoRIlpT0FgeZ59VWLHmEjTrYoJ/JUUD7360Ja7QtCbnzbJZGIRvv4iiEwIdLBWQAreerJlBDTovTA5h4q9isCR6zz1iHiVIoKO8gMoZUmSdUd01VpH4v/H0e5qvaa7LlcLAhQj/RY+iEaCpVF2+cxdnobjzYiV/HlTi9HTPdFmoCXPiWoW20HEImzqfRi6khV1injTSCX15q+nZCR986fbTAr1/eu5T/6bLeyiNadlp2Oop46LbApqYZfEJGkLskrETYGrcJYrcvI6g83yvi42f29UuatUCtoS/F86hbyw2g0FoRT6grLxMcldzNbggDm0o+hnmN8trKcYmf7fnoPtJfOPkYVaN4fFO8m13M3l4WafF+dln8+gu0ZD6u)

![image](https://github.com/vuetifyjs/vuetify/assets/80033712/f111333c-3a3a-4cbf-b1d2-0a7947005121)

**Comment by KaelWD** [comment] 2024-03-20 12:49
Duplicate of #19425

**Closed by KaelWD** 2024-03-20 12:49 UTC
Labels: S: triage
