### ISSUE TITLE
[Bug Report][3.5.1] v-vitual-scroll performance issue when used with pinia-jsonapi

### ISSUE THREAD

**Issue by Bartheleway** [vuetifyjs/vuetify#19121] opened 2024-01-29 21:00 UTC
### Environment
**Vuetify Version:** 3.5.1
**Vue Version:** 3.4.15
**Browsers:** Chrome 121.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. Replace the toggle button by a router navigation
2. Display a virtual scroller on each page
3. Navigate to second page
4. Navigate back to first page using "previous" button on the browser

### Expected Behavior
Load time almost equals for first page (1st load & 2nd load)

### Actual Behavior
2nd loading is almost crashing my browser with CPU peak for 20s sometimes.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrdVdtu2zAM/RXVw5AUje1c1oemadFtKLAO2AVbsT0kfXBsOlErS4Ykux2C/PsoyXbt9LJheysQwBZ5eEgekc584ykZh2/zPCgL8KbeTEOWs0jD6YITMiv9KM/tqz0sNSdnMaPxzcnC02K1YvCDKrqkjOpfC+/00ppmoUViWBPIqNLkliZ6jYGj4fA1gp3TuksqdRExX8VSMEbWQFdrjcjJcLjwyJRiUQqPSkgNyYU5obn0aYrG0hTAoEWIlHUX5FUCaVQwQ7YhhodsO0jEKiY04VEGiDGIOmNz7MCbdnzjPCWbjXlut8R0fW/vZAhNinZ5YUdlZ9pVoZHvHxUa30u094I1qh2G1s0sHtzQdijwiDE010SBLtxM0yxHvciGSEgHRPBPouAoH9mSVIqM9HAleu4WYsFxgDO1IicG3O99AMYE+SkkS/Z6+21Q6woq8PwKAY+4x4/5q6uqXGnEFFT0acFjTQUnu4vX3ycbJ0QVHJQRKwxFffHOYDBbx9X02sfgE7whF+9KsMOE0fOregRTIUmfAbrQPDzGx4yMjo6OjsnBAW2yo6AmMsgLte5T21OTsMNtGn+CfDwcVvyTp/jHTyRoKdsIYAMeuMdd/9gKg3Q4hHZEcDi8gacVlpzSVXCtBMdPo61i4cUiyykD+SU3l4Efomld38KLcChuP1qblgUManu8hvjmEfu1ujO2hfdVggJZ4oY2Ph3JFWjnPv/+Ge7wvXFmIinMPj/j/AZKsMLU6GDvCp5g2S2crfbC7gDlq0t1fqeBq7opU6gVxuLxO1vA+2davy93EkyqScMf6ui2zM+ifEdJ5+jSYBZX7lrrXE3DME44hiXAaCkDDjrkeRaeISyUOMA0Az8R2dkkeBOMDsMEPwJtewAq85dS3KK4yNLqHQk0TfE/64+5KiSmOAxGLkNl8lm0VCbFA+rQXqb0JfAEpBH971raCeu0teN70FpHc0b5jdodXGWlnv9nv5YGl9ck2g48VyKmtHjv6jcOg65g)

### Other comments
Reproduction link isn't really demonstrating the bug as I failed to add vue-router to playground.

I didn't find any help on how to do a playground with navigation so I did something as close as possible to reality. If it doesn't help, I will try to setup a small git repo as my code is private so I can't directly share my project.

**Comment by Bartheleway** [comment] 2024-03-17 00:05
I tried a more complex example but i really can't reproduce the issue on the playground.
I updated the libs and I still have the issue.
I also notice the issue is happening with:
- v-autocomplete
- v-select
- v-combobox (I assume)

They all use virtual-scroller internally so I think it is related to this. Maybe I will start a git repo to show the issue instead of trying in the playground.

**Comment by KaelWD** [comment] 2024-07-20 07:11
Duplicate of #18806

**Closed by KaelWD** 2024-07-20 07:11 UTC
Labels: S: triage
