### ISSUE TITLE
[Bug Report] VCheckbox(:ripple="false") - No longer responds when clicking on checkbox area

### ISSUE THREAD

**Issue by ManbokLee** [vuetifyjs/vuetify#10479] opened 2020-02-06 01:43 UTC
### Environment
**Vuetify Version:** 2.2.10
**Last working version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.14.6

### Steps to reproduce
create v-checkbox with :ripple="false" and try clicking checkbox

### Expected Behavior
Can click on the check box area to interact with the control.

### Actual Behavior
You must click on the label area to the control to interact with it.

### Reproduction Link
<a href="https://codepen.io/manbok/pen/vYOYKog?editors=1111" target="_blank">https://codepen.io/manbok/pen/vYOYKog?editors=1111</a>

**Comment by Gugu42** [comment] 2020-02-06 10:13
I have a similar issue - except Ripple is on.

I can click the edges on the ripple "circle" when hovering the button, but I cannot click the checkbox "square" itself.

**Comment by KaelWD** [comment] 2020-02-06 12:43
Duplicate of #10462 - the fix wasn't good enough

**Closed** 2020-02-06 13:13 UTC
Labels: C: Selection controls, P: high, T: bug
