### ISSUE TITLE
[Bug Report] v-tab-item renders nothing

### ISSUE THREAD

**Issue by sunmoonone** [vuetifyjs/vuetify#4537] opened 2018-07-09 02:08 UTC
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.16
**Browsers:** Other
**OS:** Windows 10

### Steps to reproduce
after clone my repo:
yarn
yarn run dev 
after having the app opend in electron, the tabs has no content coresponds to the tab item, the html rendered is ```<!---->```

### Expected Behavior
tab item's content got rendered

### Actual Behavior
renders : ``` <!---->```

### Reproduction Link
[https://github.com/sunmoonone/notebot-pc](https://github.com/sunmoonone/notebot-pc)

### Other comments
I use electron-vue and  for fixing this error I rebuilded all node_modules for the electron version I use 1.8.7 but without any help.
a pieceof error trace in electron dev console:
```
vue.esm.js?efeb:591 [Vue warn]: Error in callback for watcher "activeIndex": "TypeError: Cannot set property 'transition' of undefined"

found in

---> <VTabsItems>
       <VTabs>
         <VContent>
           <NbMain> at src\renderer\components\Main.vue
             <VApp>
               <Notebot> at src\renderer\App.vue
vue.esm.js?efeb:1741 TypeError: Cannot set property 'transition' of undefined
    at VueComponent.toggle (C:\Users\sunmoonone\ws-me\notebot-pc\node_modules\vuetify\dist\vuetify.js:11731)
    at VueComponent.updateItems (C:\Users\sunmoonone\ws-me\notebot-pc\node_modules\vuetify\dist\vuetify.js:12121)
    at VueComponent.activeIndex (C:\Users\sunmoonone\ws-me\notebot-pc\node_modules\vuetify\dist\vuetify.js:12076)
    at Watcher.run (vue.esm.js?efeb:3233)
    at flushSchedulerQueue (vue.esm.js?efeb:2981)
    at Array.eval (vue.esm.js?efeb:1837)
    at flushCallbacks (vue.esm.js?efeb:1758)
    at <anonymous>
```

**Comment by KaelWD** [comment] 2018-07-09 04:00
Duplicate of #4068

See https://github.com/vuetifyjs/vuetify/issues/4068#issuecomment-393123259 for a fix.

**Closed by KaelWD** 2018-07-09 04:00 UTC
