### ISSUE TITLE
[Bug Report] Dark mode is not propagated through the app

### ISSUE THREAD

**Issue by builder7777** [vuetifyjs/vuetify#9777] opened 2019-11-24 01:40 UTC
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.13.6

### Steps to reproduce
1. `vue create new-project`
2. `cd new-project`
3. `vue add vuetify`
4. set `dark` attribute on the v-app

### Expected Behavior
all components should inherit the "dark" attribute

### Actual Behavior
none of them do

### Reproduction Link
<a href="https://codepen.io/andreibc/pen/VwwOYry" target="_blank">https://codepen.io/andreibc/pen/VwwOYry</a>

### Other comments
this used to work in Vuetify 1.5

**Comment by jacekkarczmarczyk** [comment] 2019-11-24 01:48
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8021

**Closed by jacekkarczmarczyk** 2019-11-24 01:48 UTC
Labels: triage
