### ISSUE TITLE
[Documentation] Disable Ripple Globally

### ISSUE THREAD

**Issue by atilkan** [vuetifyjs/vuetify#9913] opened 2019-12-08 11:44 UTC
### Problem to solve
Give people information. Even API explorer doesn't mention this. It is really hard to like this library. 
**FYI:** I always avoid using this library. But clients come to me with half-baked apps and i have to deal with this. Always trying to find information on docs. 

### Proposed solution
Document.

**Comment by jacekkarczmarczyk** [comment] 2019-12-08 12:33
There's no information in docs because there is no support for disabling ripple globally at the moment, follow https://github.com/vuetifyjs/vuetify/issues/9677

**Comment by KaelWD** [comment] 2019-12-08 12:33
It isn't documented because it doesn't exist. 

Effectively a duplicate of #5521, that's probably the only thing that'll be added from there. We're already working on this for 2.3: #9677

**Closed by jacekkarczmarczyk** 2019-12-08 12:33 UTC
Labels: triage
