### ISSUE TITLE
[Feature Request] Add extra grid helpers css 

### ISSUE THREAD

**Issue by websitevirtuoso** [vuetifyjs/vuetify#17591] opened 2023-06-12 20:12 UTC
### Problem to solve
It make ability to adjust size for v-row.

Let's check bootstrap.
https://getbootstrap.com/docs/5.3/layout/gutters/#horizontal-gutters
https://github.com/twbs/bootstrap/blob/bb92ec707aa607fa4a43f49e75d69ebd67132e2e/scss/mixins/_grid.scss#L113
line 113

It has great option to set gutters space like gx-0 gy-0.

Right now we have to use something like - padding helpers but it a bit messy
 ```
<v-container>
    <v-row>
      <v-col cols="4" class="pl-4 pr-2">
        <!-- Content for column 1 -->
      </v-col>
      <v-col cols="4" class="pl-2 pr-2">
        <!-- Content for column 2 -->
      </v-col>
      <v-col cols="4" class="pl-2 pr-4">
        <!-- Content for column 3 -->
      </v-col>
    </v-row>
  </v-container>
```

### Proposed solution
Extend file
node_modules/vuetify/lib/components/VGrid/_mixins.sass and in the end add of file add
```
      @each $key, $value in $columns
        .g#{$infix}-#{$key},
        .gx#{$infix}-#{$key}
          --v-gutter-x: #{$value}
        .g#{$infix}-#{$key},
        .gy#{$infix}-#{$key}
          --v-gutter-y: #{$value}
```

**Comment by KaelWD** [comment] 2023-06-13 06:48
Duplicate of #15282

**Closed by KaelWD** 2023-06-13 06:48 UTC
Labels: S: triage
