### ISSUE TITLE
[Bug Report] Icons are off by 1 pixel on rounded buttons

### ISSUE THREAD

**Issue by salomvary** [vuetifyjs/vuetify#3880] opened 2018-04-19 14:46 UTC
![screen shot 2018-04-19 at 16 36 48](https://user-images.githubusercontent.com/193923/38999001-1aaa7db2-43f1-11e8-9f4d-bf364892e668.png)

### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.16
**Browsers:** Firefox 59.0
**OS:** Mac OS 10.12

### Steps to reproduce
Check the screenshot or the reproduction link for a visualization of the issue.

### Expected Behavior
Icons should be precisely centered inside rounded buttons.

### Actual Behavior
Pixels are off by one pixel towards the bottom.

### Reproduction Link
[https://codepen.io/anon/pen/MGYQwa](https://codepen.io/anon/pen/MGYQwa)

### Other comments
This is a very subtle visual bug, only noticable with symmetric icons and icons that are relatively large compared to the button itself. Tested in Firefox, Chrome and Safari on macOS.

**Comment by KaelWD** [comment] 2018-04-29 08:48
Duplicate of #3433

**Closed by KaelWD** 2018-04-29 08:48 UTC
Labels: pending review
