### ISSUE TITLE
Datatable Search

### ISSUE THREAD

**Issue by donPuerto** [vuetifyjs/vuetify#308] opened 2017-04-06 02:15 UTC
CSS issue,

![image](https://cloud.githubusercontent.com/assets/9329005/24734774/cf300000-1ab1-11e7-82a0-4205b3a99cb2.png)

**Comment by johnleider** [comment] 2017-04-06 02:30
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by mfferreira** [comment] 2017-04-06 07:28
duplicate of #310

**Closed by mfferreira** 2017-04-06 07:28 UTC
Labels: need reproduction
