### ISSUE TITLE
[Feature Request] A  ScrollBar Component would be nicer

### ISSUE THREAD

**Issue by Arkitect-z** [vuetifyjs/vuetify#15464] opened 2022-07-18 18:09 UTC
### Problem to solve
I used to use other UI frameworks, but now I prefer Vuetify. However, I found the ScrollBar Component is missing in Vuetify, which is really a pity (Maybe you developers have some reasons or solutions, please tell me).

### Proposed solution
Add ScrollBar Component and different UI styles for users to choose.

**Comment by KaelWD** [comment] 2022-07-19 06:35
Duplicate of #5196

**Closed by KaelWD** 2022-07-19 06:35 UTC
Labels: S: triage
