### ISSUE TITLE
[Bug Report][2.6.4] Dialog scroll jumps when typing in auto-grow textarea

### ISSUE THREAD

**Issue by atomiomi** [vuetifyjs/vuetify#14877] opened 2022-03-25 14:49 UTC
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Chrome 99.0.4844.51
**OS:** Mac OS 10.15.7

### Steps to reproduce
Video of reproducing the bug https://imgur.com/m8jr2qA

- Inside scrollable dialog put v-textarea component with auto-grow property.
- Insert long text into textarea so dialog can be scrolled
- Scroll the dialog al the way down
- Type anything in the end of the textarea

### Expected Behavior
No jumping of the scrollbar

### Actual Behavior
Scroll starts to jump while typing text

### Reproduction Link
<a href="https://codepen.io/yopyaatom/pen/OJzpVXL" target="_blank">https://codepen.io/yopyaatom/pen/OJzpVXL</a>

**Comment by KaelWD** [comment] 2022-03-26 06:21
Duplicate of #5314

**Closed by KaelWD** 2022-03-26 06:21 UTC
