### ISSUE TITLE
[Feature Request] Add white-space: nowrap to DataTable headers

### ISSUE THREAD

**Issue by NicoAiko** [vuetifyjs/vuetify#13278] opened 2021-03-17 08:40 UTC
### Problem to solve
When the table gets smaller (e.g. resizing) or is small in general, and has sortable columns, the sort indicator icon is moved to the next line. This looks inconsistent with e.g. unsortable columns as the alignment is off.

### Proposed solution
Add `white-space: nowrap` to VDataTable `thead th` elements

**Comment by jacekkarczmarczyk** [comment] 2021-12-04 22:00
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10164

**Closed by jacekkarczmarczyk** 2021-12-04 22:00 UTC
Labels: S: triage
