### ISSUE TITLE
[Bug Report] Adjacent sliders move when target of mouseup

### ISSUE THREAD

**Issue by bradstewart** [vuetifyjs/vuetify#4174] opened 2018-05-31 23:47 UTC
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.117
**OS:** Linux x86_64

### Steps to reproduce
Create two sliders. Click and drag one, and without releasing the mouse button, move the pointer on top of the other slider, then release the mouse button.

See https://imgur.com/a/vqs0F09.

### Expected Behavior
The second slider is not affected.

### Actual Behavior
The second slider moves.

### Reproduction Link
[https://codepen.io/anon/pen/MXwGry](https://codepen.io/anon/pen/MXwGry)

**Comment by KaelWD** [comment] 2018-06-01 03:20
Duplicate of #3567

**Closed by KaelWD** 2018-06-01 03:20 UTC
