### ISSUE TITLE
[Documentation] useGoTo: Could not find injected goto instance

### ISSUE THREAD

**Issue by flashpanel** [vuetifyjs/vuetify#19245] opened 2024-02-20 03:54 UTC
### Environment
**Vuetify Version:** 3.5.4
**Vue Version:** 3.4.19
**Browsers:** Chrome 121.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Access https://vuetifyjs.com/en/features/scrolling/
2. Click button GO TO in example (it working)
3. Open playground example: https://play.vuetifyjs.com/#eNrtWm1v2zYQ/itXb0BawHIc2xk2zwm2ZkU3YFjRrd+SfKClc8xFElWJcmIE/u87kpJF6iWu3Q0bOn9IbPGOx+Nzdw8p0tdPvR+TZLDKsTftzSRGScgkXt7EALOVly0RJaQijwMMLm5685sezEUaYKo1tI4vYsl4jCkswpwHhUCLUvGwfSx0Q6C/jEydjchWpIx+c9OztMy4GKIv7UaAlReJAEPqIFl6h/Km58qnnLxXlo04q8uXPEAvQPI1zFxJyOba7odWu0mKCcaBx2Oao8dpuqQaBdyb52GY4RrrHVYs5SyWpCVyGRIygatxOTstZ2ijQ40EDbUchJjER+ktOIZBHTW+2GICFxcXcPJ6Db/l0RzTk4bnBuJBrMXUzXzZH0ljv94vYo8kGw2Hw4aEK1AbzZ3Qk1+Ycr+un0lMFFD1drlOsHM2u8IF8MM9rgPxEA8wlhoWEV+F3L9vCWsVBieQzyQ1Ug61xuh9juka/tCdRGesqN9HpdhZDUrK8YBqcMf/5NAsRBox6S2REUt4jVDsVxyfjGAXNr6IEhFT3Drx2WocANFV2RdO4U2IUcs4nTj5LA00haBsZty/QiHPky6yjMd3nTAa8QEYvmm12wkbKaP3wFb/ddatEWmQp0xyEe+Pz08dPXeR6fmns6nkxKZexuJGHv4jhNokyv2i0cjbkEBMu/JWLBZZc1FniYGiAoE98sxjKW1Z9o/Ru9YxTITOugLktUg68V4S0p4erpnTevq7UQz4SimCH7JMQRmtvTFEj15Mo2lDhcJz6JPDVX/pxS3RmEuHtQHmoaCl0mkic0JVRZanC+ajV2RMdyItaFPawIQyiERvBXwQjRXbV+vzsys1+blX5ika+BumXnj9O7YkzO6dSAkcUp426q4+6ZYxnp159Vzt24202OBv0amyqTVxZtRQmuOKOe+EFJUZDx8ZvWZYDF7iKlaYLkLx4LFcWjHN5DpUdEMFRfsKfreUU5gMh8nj96WO/dKh31mq+ZW2E+ZNbDDqORgqu5WCjRBNx8xDbWposVK7mq1dTWTLc8qGn40Uzman1MNNpeTyV5FiBDzJ8ggCNTZkXAKLaMdHyGS0LKHMUyATCc+4rwxhyOUAaJNBXMb7YNYBhADnXPIMPub0DzOpaIiMw0qEeSJJaZ5nL+ANo50f+HnCA06NqFiHR6wPTAK94/lIn1JIFvWJqO5ibpzCSPVaYcxZBDGqh0RQskHIiekFpJiS/+p1cDscRi9mp4k73XmTRWi7Y2fiNEW15+VxJlnsI1xcglLJBur/GVxAKXETWBOB9Sy51KlxRb2gRptFqX3JwMOXPDk7mppnVGq4eaUqs2SHLTOMDDNQl0YZNirZZvVmJY+OlfyZlTw6rJIpLMdKPlbyPpU8fraSx8dK/sxKHh9WyRSWYyUfK3mfSqZt+jOVPDlW8mdW8uSwSnbeno6V/D+t5LNvuyu5cQLScsqmDti8PPHmgs5M2xLqNfPvaZJ0qJO48up0RIqYha5we/ZxJz6Il8M+PKkImfOGKZx81X4CcQKbVw0c7OMRfb6mzhO2xyFm0q5kdmrdm9Jj5qc8MV04XRCkkrzJM3xLrsEGFqmI4IQuXCVfrE8MgPio1QJcsDwkdTNawCSDl6/KR6BIUrrF1TOpFKfDUxgPh/2q3ZzMTuHcaTVnoVOw2zQvTG2bpu1sSkbC0NI07aOO9nFH+6TRvrFHL29QKEjaykmbkPy7tu0+GWaiPua9/6RP2RHmqkG7TnF1/Kjpj2r6ox365JSjP96hP6npT1z9W+u7vrtTCbrdxtoAFHd3tdlXyjTxdgHNsF3gmLcF5HO7h+ZWklysro0b0oaHrbqmvXat2ZC33Kl1uWbunMg1+oK/xO9yeZXPuW+rF9dSdf/U4SqrD26svM9Z0CIg4x0SPXCnrOFRZa9L1D4T28HUgcTxsFVUutghfJ9zF2TbYruosFgTVsHZmC9l2qtKzume0+IZkSjeyhx+a2M41Xk3kTseVqQolzwblI+OTpk7WsM8OPKSKrXcPNgUtp1n0Vh+0tZgKRw+LQ7ja/NU2wcJarGizVixNrx8Vcn5Al7qodt/uOHYAm3HqBve7xduG4gtsxvan2TYab1Wm52jaNY6dJC2Au8cSa9O1+Zr2e928DWG3aPXQ7MNgb4PqcXBtUyxKAi+plGmECnQOlsTmuxRfWvVW9MzsSE9WpRrIpNgJKoLNNLKtMXgNZUSXueHPdY2bFeq7b9jas19wn12Wux8ev0eMex9NvgzEzH9ruyJfmaR0W8Dpte3G5KZTZEXscRSMI1K6Wmz6W36vfFgMjj7jtTHg/PBpNeXaY63fwH0ssWk
4. Click GO TO button ([Vuetify] Could not find injected goto instance error)

### Expected Behavior
go to working

### Actual Behavior
error with message

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtWm1v2zYQ/is3b4BTwHIc2xk2zwm2ZkU3YFjRrd+afqClc0xUElWJcmwU+e87kpJF6sWu3Q0bOn9IIvGOx+Nzdw8pMm8/9rLUv/wpSYbrHHuz3lxilIRM4u19DDBfe9kKUUIq8jjA4Oa+t7jvwUKkAaZaQ+v4IpaMx5jCMsx5UAi0KBWPu9dCNwT6ycjU1ZhsRcrot/c9S8uMiyH60m4EWHuRCDCkDpKlDyjve658xsl7ZdmIs7p8xQP0AiRfw8yVhGyh7b5ptZukmGAceDymOXqcpkuqUcC9RR6GGW6x3mHNUs5iSVoilyEhE7gat/PLcoY2OtRI0FDLSYhJ3EhvyTEM6qjx5Q4TuLm5gf7zLfyeRwtM+w3PDcTDWIupm3k4Hkljv94vYhuSjUejUUPCFaiN5k7oyS9MuV/XzyQmCqh6u9wm2DmbQ+EC+PE9bgPxGA8xlhoWEd+F3H/fEtYqDE4g9yQ1Ug61xuh1jukW/tSdRGesqN8HpdhZDUrK8YRqcMf/5NAsRRox6a2QEUt4jVAcVxyfjGAXNr6IEhFT3Drx2WmcANFd2Rcu4UWIUcs4nTj5LA00haBsZty/QiH7SRdZxuOHThiN+AQMX7Ta7YSNlNF7ZOv/OuvWiDTIUya5iI/H5+eOnofI9PrT2VRyYlMvY3EjD/8RQm0S5XHRaORtSCCmXXkrlsusuaizxEBRgcA2PPNYSluW42P0qnUME6GrrgB5LZJOvFeEtKeHa+a0nv5hFAO+VorghyxTUEZbbwLRxotpNG2oUNiHPjlc9Zde3BKNhXRYG2ARCloqnSYyJ1RVZHm6ZD56RcZ0J9KSNqUNTCiDSPRSwBvRWLF9tT7vXanJz6MyT9HA3zD1wus/sCVhDu9ESuCQ8rRRd/VJt4yxd+bVe7VvN9Jig79Dp8qm1sSZU0NpjivmfBBSVGY83DD6zLAYvMRVrDFdhuLRY7m0YprJbajohgqK9hX8YSVnMB2Nks0PpY790aG/War5lbYT5k1tMOo5GCq7lYKNEE3HzENtamixUruanV1NZKtryoZfjBSu5pfUw02l5PY3kWIEPMnyCAI1NmRcAotox0fIZLQsocxTIBMJz7ivDGHI5RBok0Fcxgdg1gGEABdc8gw+5PQLM6loiIzDWoR5IklpkWdfwQtGOz/w84QHnBpRsQ6P2ACYBPrG85H+SiFZNCCieoi5cQoj1WuNMWcRxKheEkHJBiEnpheQYkr+q8/B3XAYfTW/TNzpLposQtsdOxNnKao9L48zyWIf4eYWlEo2VL+v4AZKiZvAmgisd8mlTo076gU12ixK7UsGHr7kydnR1DyjUsPNK1WZJTvsmGFsmIG6NMqwUck2qzcreXyu5M+s5PFplUxhOVfyuZKPqeTJ3kqenCv5Myt5clolU1jOlXyu5GMqmbbpeyp5eq7kz6zk6WmV7Hw9nSv5f1rJV991V3LjBKTllE0dsHl54i0EnZm2JdRz5r+nSdKhTuLKq9MRKWIWusLd2ceDeCMuRgP4qCJkzhtm0P+6/QSiD0/PGjjYxyP6fE2dJ+yOQ8ykXcn80ro3pdfMT3liunC6IEgleZNn+JJcgydYpiKCPl24Sr7c9g2AuNFqAS5ZHpK6GS1gksHFs/IVKJKUbnH1TirF6fAMJqPRoGo3J7MzuHZazVnoDOw2zQsz26Zpu5qRkTC0NE37uKN90tE+bbQ/2aOXNygUJG2l3yYk/97adj8aZqI+5ru/P6DsCHPVoF2nuDp+1PTHNf3xAX1yytGfHNCf1vSnrv4761nf3akE3W1jbQCKu7va7Ctlmni7gGbYLnDM2wLyud1DcytJLlbXxg1pw8NWXdNeu9ZsyFvu1LpcM3dO5Bo94K/xq1ze5Qvu2+rFtVTdP3W4yuqDGyuvcxa0CMh4h0QP3ClreFTZ6xK1z8R2MHUgcTxsFZUudghf59wF2bbYLios1oRVcJ7MQ5n2qpJzuue0eEYkircyh9/aGE51PkzkjocVKcoVz4blq6NT5o7WMC+OvKRKLTcvNoXt5lk0ln9pa7ASDp8Wh/G1eartgwS1WNFmrFgbLp5Vcr6ECz10+z9uOLZA2zHqhvcHhdsGYsvsE+1PMuy0XqvNzlE0a506SFuBd46kV6e35rHs9274DYbdo9dDswuBvg+pxcG1TLEoCL6mUaYQKdA6WxOa7FF9a9Vb0zOxIT1alGsik2Akqgs00sq0xeA1lRJe5x97rG3YoVQ7fsfUmvuE+/yy2Pn0nga9yXA6vPq+px6uh9Peu78A3h+u+Q==)

**Comment by MajesticPotatoe** [comment] 2024-02-20 04:05
seems to be an issue with the options api portion of the example. no error when using the composition api example

**Comment by KaelWD** [comment] 2024-02-20 04:30
Duplicate of #19163

**Closed by KaelWD** 2024-02-20 04:30 UTC
Labels: T: documentation
