### ISSUE TITLE
[Bug Report][3.2.1] 'vuetify/lib/util/colors' not exporting types

### ISSUE THREAD

**Issue by Bassadin** [vuetifyjs/vuetify#17256] opened 2023-04-29 20:41 UTC
### Environment
**Vuetify Version:** 3.2.1
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Windows

### Steps to reproduce
import colors from 'vuetify/lib/util/colors'; in my vuetify plugin definition file

### Expected Behavior
Expected types to be detected automatically

### Actual Behavior
Types are not being detected.

### Reproduction Link
[https://github.com/Bassadin/ttn-locator-frontend/blob/1f693a5a717e9aee04500ebcb3bfcff17dcfe290/src/plugins/vuetify.ts#L13](https://github.com/Bassadin/ttn-locator-frontend/blob/1f693a5a717e9aee04500ebcb3bfcff17dcfe290/src/plugins/vuetify.ts#L13)

### Other comments
Perhaps related to #5163?

**Comment by KaelWD** [comment] 2023-05-02 08:43
Duplicate of #16346

**Closed by KaelWD** 2023-05-02 08:43 UTC
Labels: duplicate
