### ISSUE TITLE
[Feature Request] Provide additional information on v-dialog click:outside event

### ISSUE THREAD

**Issue by milost1982** [vuetifyjs/vuetify#8654] opened 2019-08-21 09:35 UTC
### Problem to solve
Currently when you click outside v-dialog it will be dismissed but dismiss will happen on mouseup event. I'd like to have option to do this on mousedown event. 

I tried doing this by handling click:outside event and trying to get additional info about whether it is mouseup or mousedown. However no additional information is provided as parameter to event handler.

The reason I need to do this is following: when you have v-dialog open and some v-text-field in it, when you use mouse to select text in v-text-field (eg. click on v-text-field and while holding left mouse button you move cursor to select text) but you accidentally move mouse outside of v-dialog (eg. on overlay) the dialog will close. This is not intended behavior from the user perspective.

See this for more info: https://stackoverflow.com/questions/57574376/how-to-dismiss-vuetify-v-dialog-when-clicked-outside-of-it-but-do-it-on-mousedow

### Proposed solution
Either add prop to select whether mouseup or mousedown will be used to dismiss dialog. Or provide additional info when raising click:outside event so that I can detect this and handle it myself.

**Comment by KaelWD** [comment] 2019-08-21 11:18
Sounds like your real problem is #6969

**Comment by KaelWD** [comment] 2019-12-08 12:41
Duplicate of #8055

**Closed by KaelWD** 2019-12-08 12:41 UTC
Labels: triage
