### ISSUE TITLE
[Bug Report][3.0.2] v-select doesn't highlight default value with custom object (return-object) on init

### ISSUE THREAD

**Issue by ivan-mihalic** [vuetifyjs/vuetify#16215] opened 2022-12-05 10:16 UTC
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Basic implementation of v-select with custom object (return-object prop) does not highlight selected value when value is selected on init. It highlights after manual selecting value. In example is copied code from doc.

### Expected Behavior
highlight selected value that is set on init

### Actual Behavior
no highlighting selected value on init

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFU8tu2zAQ/JUFUcAtYEmF21xUxUjgurkEuaSXIAoQylo7jCWSICkHhaF/75JSbfmRRhdhd2Znn3zcsmut402DLGWZXRihHVh0jZ7mUtRaGQdbMLiEFpZG1TAi6iiXuVwoaR0Ih7WFS8/4/JhLILJ13GEKo1+VMqLkozHwojDecTuCdnxIukFlVmJAurk+Jd1hYbhdD1h381PWjFdiqYwcqs3Oqr3BgzLrgdpDx3r68oOo++YsVrhwfXcfNRZiKThLuinS/Mig8eiKwsgCyDYR136wQB8ZNReyt8guxQYWFbf2MmeaRxc522GB3VWzdwGQgiqxIn6PsSGavgjpCHv+tO3gODTQjmHn8PW3z0dhYaUUF/6HmHdFTrgKfU6vdgbf8KrxuBc/hCtehGrvz1Sr0VhhHUoX+bqHkKFzNDJSxetR/1bIVYVRJSQO3bvxcCN4GEEjSzSeVg6TTrPk31T3W0hoDe/uZHKwk/v57Xz2e/4zhUwbnG77qbZtlnj7nKTPuNu6N7p7yJLBnbAx6x4eMXX8apWkp7kNx9UDtJUUgsf76EF6O2cvzmmbJkkj9XoVL1SdXBGWmEY6UWNUqvrqWzyJv19QQdYN/THaOiqMerNoKGPOwpPpxZ1Y/nkvQQ+T7td40sn2Li95IpWQ/gZNZNAvBOk8/lP3Efeg9iPspH6fs81ly9ox6+JoqqFI9vQX++aJhA==)

### Other comments
tried version vuetify 3.0.3 and it has some other issue (doesn't showing dropdown)

**Comment by whttigress** [comment] 2022-12-08 17:54
This also affects v-autocomplete, and is especially noticeable with the 'multiple' prop where you can not unselect the previously selected value

[Reproduction with autocomplete and multiple prop](https://play.vuetifyjs.com/#eNqFU8Fu2zAM/RVBl2xAbA/devHcoEWW9VL00l2KOAfZZlI1siRIdIoh8L+PsrPGTtLNF4N8j4/kk7Tc8ztr410DPOWZL520yDxgY2e5lrU1DtmeOVizlq2dqdmEqJNc57o02iOTCLVnN4HxaZlrRmSPAiFlk5/KOFmJyZSJonAh8TBh7XRMugfjNnJAur87Jz1C4YTfDliPi3PWXCi5Nk4P1eYX1d7Ys3Hbgdpzz1p9/k7U43IeFJT4d7v/bdZXU3mW9D6SgxSQQVZRHUWMZbtI2GAto4+CWkh9iCiu5I6VSnh/k3Mrouucv2N9aYOmNCQHCEeAMdIxFSiq6ifO+RBNuzMisPuPsZCKUKKCUBzWu4DvhGoCHpYdw0oUXdunC20tOC89gsboRWocQo7ul9ORKV5D1QDwUm8URErq8X7CSaGRGjW6AhfgatysbhRK8uWYm2XJ2LCjzQn5/KHpVyPTnxYPi/mvxY+UZdbBbL/vDW7bLAnxJcnQ9/1YuyG6A8+SwUXgU96/LWLa+NUbTa9v392eA0DnlLIuE3L05kKc8xdE69MkabTdbmJaLbklLHGNRllDVJn69mt8FX+7poE8DvMx+DoqnHnz4KhjzrtXcRBHuf79UYMDTLpf4qte9pAKkmdSCenvwEUOwlEBXZh/zH3CHc1+gp3NH3q2uW7JS7oQW39iY+k7C5erQGmnvJcmcrcHX/0BsCONaA==)

**Comment by KaelWD** [comment] 2023-06-07 16:44
Duplicate of #16279

**Closed by KaelWD** 2023-06-07 16:44 UTC
Labels: T: bug, C: VList, C: VListItem
