### ISSUE TITLE
[Feature Request] Export functionality in Data Table

### ISSUE THREAD

**Issue by ayush987goyal** [vuetifyjs/vuetify#3128] opened 2018-01-29 06:09 UTC
### New Functionality
It would allow us to export the Data Table data in a CSV (or any other) format.

### Improvements
This will not cause any breaking changes as this will be an independent addition.

### Bugs or Edge Cases it Helps Avoid
None

**Comment by KaelWD** [comment] 2018-01-29 06:16
Duplicate of #316

This has also come up in the discord and we decided that it's outside the scope of this project. You are welcome to write your own plugin and submit it to https://github.com/vuetifyjs/awesome-vuetify

**Closed by KaelWD** 2018-01-29 06:16 UTC
