### ISSUE TITLE
[Feature Request] call a simple dialog using fast functions

### ISSUE THREAD

**Issue by ebolavirus** [vuetifyjs/vuetify#8346] opened 2019-08-07 10:01 UTC
### Problem to solve
when developing and writing logics, we need to call a simple dialog for warning or error message to show, like other UI frameworks ,there are these kinds of functions like this.$alert("error message"), or this.$confirm("confirm message").

### Proposed solution
add these functions.

**Comment by KaelWD** [comment] 2019-08-07 10:06
Duplicate of #3037

**Closed by KaelWD** 2019-08-07 10:06 UTC
Labels: triage
