### ISSUE TITLE
[Bug Report] i18n: v-data-table: "group" link is not translated

### ISSUE THREAD

**Issue by alexnb** [vuetifyjs/vuetify#12647] opened 2020-11-19 10:10 UTC
### Environment
**Vuetify Version:** 2.3.18
**Vue Version:** 2.6.12
**Browsers:** Firefox 79.0
**OS:** Ubuntu undefined

### Steps to reproduce
Setup v-data-table to group, switch vuetify locale, the group link is not translated.

### Expected Behavior
Group link is translatable by i18n files in src/locale/

### Actual Behavior
Link title is fixed.

### Reproduction Link
<a href="https://codepen.io/alexnb/pen/XWKwjza" target="_blank">https://codepen.io/alexnb/pen/XWKwjza</a>

**Comment by jacekkarczmarczyk** [comment] 2020-11-19 10:17
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8186

**Closed by jacekkarczmarczyk** 2020-11-19 10:17 UTC
