### ISSUE TITLE
[Feature Request] feature(VDatePicker):I want to provide a display slot for each date

### ISSUE THREAD

**Issue by MapleWithoutWords** [vuetifyjs/vuetify#20779] opened 2024-12-14 05:39 UTC
### Problem to solve
I want to provide a display slot for each date, sometimes I want to display both the solar calendar and the Chinese lunar calendar on each date

### Proposed solution
The vdatepicker component provides a slot for each date item, gives the corresponding data item, and then chooses what to display for each item

**Comment by MapleWithoutWords** [comment] 2024-12-14 05:46
![image](https://github.com/user-attachments/assets/60f2b0e2-4f69-4ace-8477-127dff7ea965)

**Comment by KaelWD** [comment] 2024-12-15 08:42
Duplicate of #20236

**Closed by KaelWD** 2024-12-15 08:42 UTC
Labels: S: triage
