### ISSUE TITLE
[Bug Report][3.0.0-beta.14] [Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom.

### ISSUE THREAD

**Issue by brandondtaylor01** [vuetifyjs/vuetify#15939] opened 2022-10-20 13:52 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Vue Version:** 3.0.0-rc.12
**Browsers:** Chrome 106.0.0.0
**OS:** Windows 10

### Steps to reproduce
Clone repo, yarn install, yarn dev, open console window.

### Expected Behavior
Expected to render correctly both on server and on client.

### Actual Behavior
Children incorrectly hydrates on the server and client, resulting in error messages in console window.

### Reproduction Link
<a href="https://github.com/brandondtaylor01/dialog-test" target="_blank">https://github.com/brandondtaylor01/dialog-test</a>

### Other comments
Using Nuxt 3.0.0-rc.12.

**Comment by KaelWD** [comment] 2022-10-22 09:33
Duplicate of #15323

**Closed by KaelWD** 2022-10-22 09:33 UTC
Labels: S: triage
