### ISSUE TITLE
[Feature Request] The ability to use v-autocomplete inside v-textarea

### ISSUE THREAD

**Issue by Dorgam** [vuetifyjs/vuetify#13242] opened 2021-03-10 11:43 UTC
### Problem to solve
It would be useful when building a comment text section that needs to reference certain elements or users using "@" or "#" symbols.

### Proposed solution
To be able to nest v-autocomplete inside v-textarea as a template for possible autocompletion with the ability to specify the symbol that activates it as wells as the list where the autocompletion searches in.

**Comment by jacekkarczmarczyk** [comment] 2021-03-10 12:03
That would be useful in text fields as well

**Comment by nekosaur** [comment] 2021-03-10 12:07
This kind of functionality already exists in packages such as https://github.com/mitsuyacider/vue-hashtag-textarea or https://pggalaviz.github.io/vue-highlights/#/.

**Comment by Dorgam** [comment] 2021-03-10 12:23
> This kind of functionality already exists in packages such as https://github.com/mitsuyacider/vue-hashtag-textarea or https://pggalaviz.github.io/vue-highlights/#/.

The closest thing that I found that kinda works with vuetify is this: https://github.com/Akryum/vue-mention
I can wrap the v-textarea component within a "Mentionable" component. The displayed popup styling however is missed up and makes it not useable. (see image)
![bug](https://user-images.githubusercontent.com/6091467/110628850-9216db80-81b4-11eb-9fa8-9b1f7a1e268f.png)

**Comment by KaelWD** [comment] 2021-10-05 11:38
Duplicate of #6820

**Closed by KaelWD** 2021-10-05 11:38 UTC
Labels: S: triage
