### ISSUE TITLE
[Feature Request] Create a combined date and time picker.

### ISSUE THREAD

**Issue by bigal41** [vuetifyjs/vuetify#5630] opened 2018-11-16 06:28 UTC
### Problem to solve
Currently there needs to be separate components on a form if you want to collect the date and time. 

### Proposed solution
When the user clicks on the component, the date picker pops up first. After they select the date the picker should transition to the time picker.

**Comment by jacekkarczmarczyk** [comment] 2018-11-16 06:59
Duplicate of https://github.com/vuetifyjs/vuetify/issues/459

**Closed by jacekkarczmarczyk** 2018-11-16 06:59 UTC
