### ISSUE TITLE
[Bug Report][3.1.11] Clicking close button of `VSnackbar` opened after `VDialog` closes the dialog too

### ISSUE THREAD

**Issue by MetRonnie** [vuetifyjs/vuetify#17013] opened 2023-03-27 17:14 UTC
### Environment
**Vuetify Version:** 3.1.15
**Last working version:** 3.1.8
**Vue Version:** 3.2.47
**Browsers:** Edge 111.0.1661.51
**OS:** Windows 10

### Steps to reproduce
1. Have a `v-snackbar` that opens after a `v-dialog` (e.g. showing an error message after submitting a form in the dialog).
1. Click the close button in the snackbar

### Expected Behavior
The snackbar closes.

### Actual Behavior
Both the snackbar and the dialog close.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVE2P2yAQ/StTLttKsa20lVpF2SpVe+ith6qn9R4IJhsaDAhwVlWU/74D2Bts74e0PoWZ4b03j5ncnMh3Y8pjx8mKrD1vjaSef6sVwPpYUGPiz3hoqVDAJHXuuiaGFl9r0idj2inKDltqASt1wyUWub2+/9OHawJetFx3HhPFMrsL8HcPev8OfnHLQTigMGBdSh6lIbyT2q8o80Irl6FEFVuvYMOkYIcJP1zDjkrHR8Th+yE1RnOUKsJkZetqZMxQNKh8DGZuBB1HagVVoV/sWgrFGzRhJO6noFLfoTRvu7Gy34YraFL6gpspy7j6srHvCXqEiaWM2mZqWYgVXnh56S59l/dIDFOTnrk4QD71Qq++0cyIzI75VDz9XJm6uYYhNXrJ1N8w6hgIs56WAA9pC0ZDgEfHrDAeHPddSIvWaOvhBJbv4Aw7q1u4wrW6CsUMNWBp/uJY9j4O5Ic8nTmRF6yrxIY8ZEESFWo05T+nFS7uKU5En3A1WUGMhBhKCOea7L03blVVnTKHu5LpttpgrrKdCntZNLrdfCo/lp+/VI1wPo+X3LXF1up7xy0y1mSRgXux+/8cQZ9G3GW5XCbcPlZIunUBeAZYIcuR28Jy1eAA4h/HC+ontaMOJrlZF4HzXKszOorLeXATM5mLRt4M0t7QXoQI928DzXlBkjwkTFfI7QOh3rTi)

### Other comments
Probably related to the fix for https://github.com/vuetifyjs/vuetify/issues/16893.

I tried using `@click.stop` in the snackbar's close button but that didn't do anything.

**Comment by MarekNguyen** [comment] 2023-04-04 13:24
I have similar situation when i have a datepicker in the dialog. When select the date then the dialog close also

**Comment by KaelWD** [comment] 2023-06-13 07:40
Duplicate of #7310

**Closed by KaelWD** 2023-06-13 07:40 UTC
Labels: S: triage
