### ISSUE TITLE
[Bug Report][3.1.13] Select height issue when chip is used in compact variant

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify#17130] opened 2023-04-11 10:49 UTC
### Environment
**Vuetify Version:** 3.1.13
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Select chip and notice select's height increases. Deselect chip and height changes again

### Expected Behavior
Height shouldn't change

### Actual Behavior
Height changes

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUctuwjAQ/BXLF0AicSmVKkWAqPoZhINJNsKt7Vi2kxZQ/r1rJ5EoHOBk7+xjZnZ3F/phTNo2QDO68qCM5B42uSZk1SYOJBQ+BIS0iapLkOuctlw2kNMezgQ2OUTjO6LFURjXfyU/xK7PCA151UgvjIShWnIXRiieLF7GkhK0E/6EcFErw1FGTGxWbNSFKlfsSjKGrrDChAQh8Gtq63FMxZGMXIap3POMTGdkvSHTASMkas/IblLV9WROJgduw1OJ8zmGDb77+Vgd/WP1iHSz+OmCnEEAnVMp9LdLv1ytcbORCZ043AB29n05PXpvXMZYUWqsxO2K1qYaPNNGMbyJF9Vpu0wX6WLJSuH8iCW4VJfGaWHUPtcdMgoVHCeKmxvaPhGpB8t4xHDC7JGGLZYx22gvFCRlrVDMa/r23ou5wlNwKjnY+seBxSk5HVYTeYLiJ7ge+kWOu9kMCVuwiQVdggX7rKebtn++bnJ33oZjd7Sb074Pl9+rpvs/+HsWJg==)

**Comment by yuwu9145** [comment] 2023-04-17 03:03
maybe related #17146

**Comment by lioneaglesolutions** [comment] 2023-05-02 21:50
Duplicate of https://github.com/vuetifyjs/vuetify/issues/15980

**Closed by lioneaglesolutions** 2023-05-02 21:50 UTC
Labels: S: triage
