### ISSUE TITLE
[Bug Report] possible EventEmitter memory leak detected after upgrading to Vuetify 2.0.2

### ISSUE THREAD

**Issue by mazerab** [vuetifyjs/vuetify#8269] opened 2019-08-02 18:20 UTC
### Environment
**Vuetify Version:** 2.0.3
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
Upgraded my web application from Vuetify 1.5.16 to 2.0.2, after running the command "npm run serve", I get new warnings:

INFO  Starting development server...
 40% building 106/115 modules 9 active ...al-catalog/src/components/Publisher.vue(node:30936) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
 40% building 109/125 modules 16 active ...dules/core-js/modules/_object-create.js(node:30936) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
(node:30936) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
(node:30936) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
 40% building 113/130 modules 17 active ...vue-style-loader/lib/addStylesClient.js(node:30936) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
 40% building 116/133 modules 17 active ...alog/node_modules/vuex/dist/vuex.esm.js(node:30936) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
 40% building 171/194 modules 23 active ...uetify/lib/components/VToolbar/index.js(node:30936) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
 40% building 171/202 modules 31 active .../Repos/digital-catalog/src/util/util.js(node:30936) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
 40% building 172/209 modules 37 active ...lib/components/VExpansionPanel/index.js(node:30936) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
 40% building 176/209 modules 33 active ...lib/components/VExpansionPanel/index.js(node:30936) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
 66% building 753/798 modules 45 active .../lib/components/VDataTable/MobileRow.js(node:30936) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit

### Expected Behavior
With 1.5.16 I did not have such errors, please indicate why those errors are now thrown and if there is a real problem behind my web app.

### Actual Behavior
Warning of possible memory leak

### Reproduction Link
<a href="https://github.com/autodesk-forge/forge-digital-catalog" target="_blank">https://github.com/autodesk-forge/forge-digital-catalog</a>

### Other comments
Is this a hot reloader bug with dev server? And can it be ignored?

**Comment by KaelWD** [comment] 2019-08-03 04:37
Duplicate of https://github.com/mysticatea/vue-eslint-parser/pull/44

**Closed by KaelWD** 2019-08-03 04:37 UTC
Labels: triage
