### ISSUE TITLE
[Feature Request] make global message component 

### ISSUE THREAD

**Issue by onloadcc** [vuetifyjs/vuetify#5929] opened 2018-12-18 07:51 UTC
### Problem to solve
hello. we need to show a gloabl message component sometime, but i can't write this component in the vue file. like this view: https://www.iviewui.com/components/message-en . 

### Proposed solution
i hope add like  this component .thank you.

**Comment by jacekkarczmarczyk** [comment] 2018-12-18 08:30
Kinda duplicate of https://github.com/vuetifyjs/vuetify/issues/3037 or https://github.com/vuetifyjs/vuetify/issues/2384, choose one

**Closed by jacekkarczmarczyk** 2018-12-18 08:30 UTC
