### ISSUE TITLE
[Bug Report] v-select suite item dropdown stuck when items updated w/ v-switch

### ISSUE THREAD

**Issue by cramk** [vuetifyjs/vuetify#4830] opened 2018-08-09 12:51 UTC
### Versions and Environment
**Vuetify:** 1.1.10
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106, Google Chrome, Internet Explorer
**OS:** Windows 7, Windows

### Steps to reproduce
Open the v-select items dropdown.
Toggle the v-switch (to compute new item list).
v-select item dropdown is now stuck open regardless of focus.

### Expected Behavior
v-select item dropdown should either:
a) hide on loss of focus (the toggle of v-switch)
b) hide on item list change

### Actual Behavior
v-select item dropdown becomes stuck open (and cannot be closed) when item data changed using v-switch.

### Reproduction Link
[https://codepen.io/anon/pen/QBJXgm](https://codepen.io/anon/pen/QBJXgm)

### Other comments
This does not seem to occur when switching to a v-radio, possibly related to how v-switch handles focus on click.
Does not occur 100% of the time when toggling v-switch, but often enough to be an issue.

Google Chrome & Internet Explorer affected. Mozilla Firefox excluded.

**Comment by KaelWD** [comment] 2018-08-09 12:53
Duplicate of #4663

**Closed by KaelWD** 2018-08-09 12:53 UTC
