### ISSUE TITLE
[Bug Report] size v-tabs-slider not updated after downloading fonts

### ISSUE THREAD

**Issue by TreVld** [vuetifyjs/vuetify#10039] opened 2019-12-25 11:19 UTC
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
disable the cache, and verify that the size of the active tab and v-tabs-slider 

### Expected Behavior
the width of the slider should match the width of the active tab

### Actual Behavior
the width of the slider is determined, after which the font is loaded and the width of the active tab changes, and the width of the slider remains the same

### Reproduction Link
<a href="https://codesandbox.io/s/vuetify-playground-nr547" target="_blank">https://codesandbox.io/s/vuetify-playground-nr547</a>

**Comment by TreVld** [comment] 2019-12-25 11:20
![image](https://user-images.githubusercontent.com/42523020/71444332-08532d80-272a-11ea-9325-04d79b09b8cc.png)

**Comment by jacekkarczmarczyk** [comment] 2020-01-11 09:53
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4733

We don't have a reasonable solution for now, you may try to solve it in userland with
```js
  mounted () {
    const initial = this.$refs.tab.$el.offsetWidth;
    const interval = setInterval(() => {
      if (this.$refs.tab) {
        if (this.$refs.tab.$el.offsetWidth !== initial) {
          clearInterval(interval)
          this.$refs.tabs.callSlider()
        }
      }
    }, 1000)
  }
```

where `$refs.tabs` is the ref for the `v-tabs` and `$refs.tab` is the ref for the first `v-tab` (you may want to wrap the tab text in a `<span>` and check the `span` width instead of `v-tab` for more reliable effect)

**Closed by jacekkarczmarczyk** 2020-01-11 09:53 UTC
Labels: triage
