### ISSUE TITLE
[Bug Report] Navigation drawer jumping on navigation

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#7653] opened 2019-06-24 20:44 UTC
### Versions and Environment
**Vuetify:** 2.0.0-beta.3
**Last working version:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.90
**OS:** Linux x86_64

### Steps to reproduce
Go to the pen above.  Change the position to the left, and set expand on hover: true.  Now, hover over the menu.  Notice the icons jump around.

### Expected Behavior
Them to not jump around

### Actual Behavior
Them jumping.

### Reproduction Link
<a href="https://codepen.io/gabaum10/pen/WqOdWY?&editable=true&editors=101" target="_blank">https://codepen.io/gabaum10/pen/WqOdWY?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment] 2019-07-07 09:32
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2606#issuecomment-482429042

**Closed by jacekkarczmarczyk** 2019-07-07 09:32 UTC
Labels: triage
