### ISSUE TITLE
[Bug Report] Expansion Panel v-model / value doesn't work correctly when using SSR 

### ISSUE THREAD

**Issue by victor-perez** [vuetifyjs/vuetify#5910] opened 2018-12-16 07:48 UTC
### Versions and Environment
**Vuetify:** 1.3.14
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.80
**OS:** Windows 10

### Steps to reproduce
Create a page in for example `nuxt` using this https://vuetifyjs.com/en/components/expansion-panels#example-expand example code you will see when SSR is used that the icon is in the correct state but the panel doesn't open.

### Expected Behavior
That beside the icon change also the panel opens
![image](https://user-images.githubusercontent.com/672958/50051277-5abd3f80-010f-11e9-9187-191ba3c82d3b.png)

### Actual Behavior
Only the icon change but the panel doesn't open
![image](https://user-images.githubusercontent.com/672958/50051268-44af7f00-010f-11e9-9788-dd74dc8c9bc6.png)

### Reproduction Link
<a href="https://codesandbox.io/s/v6nq140w3l?view=preview" target="_blank">https://codesandbox.io/s/v6nq140w3l?view=preview</a>

**Comment by johnleider** [comment] 2018-12-16 15:56
Duplicate of #5795

**Closed by johnleider** 2018-12-16 15:56 UTC
