### ISSUE TITLE
[Feature Request] Text Field append-icon, prepend-icon tooltip

### ISSUE THREAD

**Issue by AlexanderZon** [vuetifyjs/vuetify#4922] opened 2018-08-20 14:41 UTC
### Problem to solve
I need to show a tooltip when put the mouse over a textfield's appended icon

### Proposed solution
Create a property append-icon-tooltip-text the shows the text when put mouse over the appended icon

**Comment by KaelWD** [comment] 2018-08-20 14:43
Duplicate of #4582

**Closed by KaelWD** 2018-08-20 14:43 UTC
