### ISSUE TITLE
[Bug Report] Select menu scrolls with document

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#3301] opened 2018-02-16 13:51 UTC
### Versions and Environment
**Vuetify:** 1.0.1
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132, Google Chrome
**OS:** Mac OS 10.13.3

### Steps to reproduce
Open the day select menu in the link and scroll the main content. The menu scrolls with it and does not stay in position relative to the bottom-sheet

### Expected Behavior
The select menu should stay in place relative to the bottom-sheet

### Actual Behavior
The select menu scrolls with the main content

### Reproduction Link
[https://codepen.io/anon/pen/MQOZwr/](https://codepen.io/anon/pen/MQOZwr/)

**Comment by KaelWD** [comment] 2018-02-16 14:06
Duplicate of #795

**Closed by KaelWD** 2018-02-16 14:06 UTC
