### ISSUE TITLE
[Bug Report] Tab slider width is not changed when tab content changes dynamically

### ISSUE THREAD

**Issue by nickgr6** [vuetifyjs/vuetify#7061] opened 2019-04-24 08:37 UTC
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Linux x86_64

### Steps to reproduce
1. Click button 'Toggle extra tab content'

### Expected Behavior
The slider underneath the active tab (Item 1) width, grows as large as the new width of the tab

### Actual Behavior
The tab grows in width. The slider underneath doesn't.
Only when changing the active tab, the slider get's the correct width

### Reproduction Link
<a href="https://codepen.io/nickgr6/pen/rbqpaP" target="_blank">https://codepen.io/nickgr6/pen/rbqpaP</a>

**Comment by jacekkarczmarczyk** [comment] 2019-04-24 08:44
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4733

**Closed by jacekkarczmarczyk** 2019-04-24 08:44 UTC
Labels: triage
