### ISSUE TITLE
[Feature Request] VDataTable‘s slot "item.<name>",Why doesn't have "index" ScopProp?

### ISSUE THREAD

**Issue by MonsterGene** [vuetifyjs/vuetify#15460] opened 2022-07-18 16:06 UTC
### Problem to solve
I want to add an index field to the table, but I only find one way to achieve this requirement, that is, to use the "item" slot. But if so, I have to rewrite the code of the whole table row by myself. In fact, I only want to rewrite the code of one cell.

Therefore, I hope to add the prop of "index" to the "scopeprop" in the "item.<name>" slot, or it is also very good that the component can support the display of index serial number, just like the "data table select" slot.

Thank you very much!

我想在表格中添加一个index栏位，但是我只找到一个方法实现这个需求，那就是使用“item”插槽。但如果这样的话我就要自己去重写整个表格行的代码，而事实上我只想要重写一个单元格的代码。
所以，我希望能在“item.<name>”插槽的“scopeProp”中添加“index” 这个prop，或者说组件能支持显示index序号也是很不错的，就像“data-table-select”插槽一样。

非常感谢！

### Proposed solution
1. Add "index" or "rowIndex" prop to item.<name> slot.
2. Add “item.data-table-index” slot to support show index.

**Comment by KaelWD** [comment] 2022-07-18 16:37
Duplicate of #13064

**Closed by KaelWD** 2022-07-18 16:37 UTC
Labels: S: triage

**Comment by MonsterGene** [comment] 2022-07-18 22:05
Ok， Thank you for your answer.
After my test, I found that the `item.<name>` slot already has the prop of index, but it is not explained in the document. Would you like to add this to the document?

好的，非常感谢您的回复。
经过我的测试，发现`item.<name>`插槽已经带有index这个prop，但是在文档上没有说明。请问是否将这个补充到文档上吗？

![image](https://user-images.githubusercontent.com/32955859/179624788-c3d2c6ec-e6ff-4b5f-8202-305c4f92d8a7.png)

![image](https://user-images.githubusercontent.com/32955859/179624867-30989647-c5e1-4c43-ac29-d827c47d744f.png)
