### ISSUE TITLE
[Bug Report] TextField height prop only resize input with an higher height

### ISSUE THREAD

**Issue by avelaine** [vuetifyjs/vuetify#12555] opened 2020-11-04 17:56 UTC
### Environment
**Vuetify Version:** 2.3.16
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.121
**OS:** Mac OS 10.15.6

### Steps to reproduce
- Displayed 2 outlined inputs, only the one at 80 is really resized. I suspect that it does not resize if the height is below the default one
Example:
- Input on the left `:height="40"`
- Input on the right `:height="80"`

Other thing:
1. An input with a prepend-inner slot is not aligned with the text inside
Example:
- Input on the right
- "FR" > not aligned with "Resized"

2. Also if the width of the slot change (For example with a dropdown and the value change), the label is not placed well with an outlined input
Example:
- Input on the right
- Click on "FR"
- Click on "USA" in the menu
- Click back into the input

### Expected Behavior
- Height prop must resize the input with the value passed or the documentation should be more explicit with the way of using it

- Prepend-inner slot should be aligned with the input text
- The label is well placed even if the slot have changed size

### Actual Behavior
- Height only resize with an height > 56 (default height)

- Prepend inner slot is not aligned with the input text
- If slot size change, the label position is not recalculated

### Reproduction Link
<a href="https://codepen.io/avelaine/pen/PozBwBg" target="_blank">https://codepen.io/avelaine/pen/PozBwBg</a>

### Other comments
Tell me if I should open a second ticket for the slot issue. Thanks for your time ~

**Comment by KaelWD** [comment] 2020-11-05 09:10
Duplicate of #5216

**Closed by KaelWD** 2020-11-05 09:10 UTC
