### ISSUE TITLE
Need date range picker

### ISSUE THREAD

**Issue by prakashgp** [vuetifyjs/vuetify#1808] opened 2017-09-19 12:02 UTC
- What will it allow you to do that you can't do today?
We can select  date ranges with predefined ranges, and custom ranges which is most commonly used in dashboard and reporting pages

  - How will it make current work-arounds straightforward?   
 - What potential bugs and edge cases does it help to avoid?

Currently we need to define two date picker components and link them, But still since current date picker component doesn't provide much option for customization such as ability to highlight dates, ability to select multiple dates, disable left/right navigations, etc, it is difficult to do a workaround

**Comment by smares** [comment] 2017-09-19 12:03
Duplicate of #1646

**Closed** 2017-09-19 12:08 UTC
