### ISSUE TITLE
[Bug Report] Creating a custom container class breaks overrides v-container after build

### ISSUE THREAD

**Issue by TJBrunson** [vuetifyjs/vuetify#13230] opened 2021-03-08 17:58 UTC
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.192
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Create a project using vuetify.
2. use ```<v-container fluid> </v-container>``` anywhere
3. create a global class named .container for whatever use you want with a max width less than whatever fluid gives v-container

### Expected Behavior
.container should not conflict with v-container and they should operate independently.

### Actual Behavior
in the codepen, the .container class overrides v-container. in practice on my machine, it works fine in "npm run serve" mode but when I build the project for deployment, the .container class overrides any v-container and breaks styles. 

I would think developers should be able to define their own .container class for specific use cases because it is such a commonly used class name. Not to mention, in dev mode, nothing seems to break but after building, it breaks.

### Reproduction Link
<a href="https://codepen.io/rahulonsong/pen/VwZqPJb" target="_blank">https://codepen.io/rahulonsong/pen/VwZqPJb</a>

**Comment by KaelWD** [comment] 2021-03-09 06:22
Duplicate of #7039

**Closed by KaelWD** 2021-03-09 06:22 UTC
Labels: triage
