### ISSUE TITLE
[Bug Report] Keyboard arrow down/up not consistent in v-select

### ISSUE THREAD

**Issue by stemann** [vuetifyjs/vuetify#8985] opened 2019-09-17 07:57 UTC
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Mac OS 10.13.6

### Steps to reproduce
* Tab to v-select
* Keyboard arrow down

### Expected Behavior
Next item in select is selected

### Actual Behavior
Nothing happens

### Reproduction Link
<a href="https://codepen.io/stemann/pen/RwbYLPr" target="_blank">https://codepen.io/stemann/pen/RwbYLPr</a>

### Other comments
Subsequent keyboard arrow up/down works as expected - even after tabbing to and from other focus item (e.g. v-text-field).

**Comment by johnleider** [comment] 2020-02-05 19:33
Duplicate of #8361

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-02-05 19:33 UTC
Labels: C: VSelect, T: bug
