### ISSUE TITLE
Lazy Load Images in <v-card-media>

### ISSUE THREAD

**Issue by kamleshkatpara** [vuetifyjs/vuetify#4614] opened 2018-07-14 13:34 UTC
Hi @johnleider 

### What problem does this feature solve?

How can we implement lazy load images feature in <v-card-media> ?
It will be useful for better U/X

I tried some of the lazy load modules, but none of them worked.

### What is your proposed solution?

add a data-src property to lazy load images

**Comment by KaelWD** [comment] 2018-07-14 13:37
Duplicate of #2951

**Closed by KaelWD** 2018-07-14 13:37 UTC

**Comment by kamleshkatpara** [comment] 2018-07-14 15:37
@KaelWD  I didn't find any solutions there

**Comment by johnleider** [comment] 2018-07-14 16:43
That is because they are currently in development. Kael was simply stating that this request has already been made.
