### ISSUE TITLE
[Bug Report][3.0.0-beta.3] Broken validation css

### ISSUE THREAD

**Issue by zorn-v** [vuetifyjs/vuetify#15210] opened 2022-06-05 04:42 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Last working version:** 3.0.0-beta.2
**Vue Version:** 3.2.36
**Browsers:** Firefox 101.0
**OS:** Linux x86_64

### Steps to reproduce
Enter something to "Affect validation" field. Error appear in "Error messages" but no `error` classes on input. 
For trigger validation on "Rules" field you should enter something to it and clear input.

### Expected Behavior
`*--error` css class should be applied to input even with no `:rules`

### Actual Behavior
Error is shown but with no `error` class on input. 

### Reproduction Link
<a href="https://codesandbox.io/s/stupefied-mendeleev-p4ppcy?file=/src/App.vue" target="_blank">https://codesandbox.io/s/stupefied-mendeleev-p4ppcy?file=/src/App.vue</a>

### Other comments
Bug introduced by this PR https://github.com/vuetifyjs/vuetify/pull/15144
As workaround you can set `:rules="[true]"`

**Comment by KaelWD** [comment] 2022-06-05 16:26
Duplicate of #15209

**Closed by KaelWD** 2022-06-05 16:26 UTC
Labels: S: triage
