### ISSUE TITLE
[Bug Report] V-Select options are off with auto-complete when they pop up above the drop-down

### ISSUE THREAD

**Issue by smares** [vuetifyjs/vuetify#2496] opened 2017-11-14 09:16 UTC
### Versions and Environment
**Vuetify:** 0.17.0
**Vue:** 2.5.3
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 10

### Steps to reproduce
Place a V-Select with auto-complete on the page and scroll down so that the options have to open above the select and not beneath it, then start typing to filter the list

### Expected Behavior
As the container with the available options shrinks, it should remain right above the select

### Actual Behavior
The container with the available options shrinks, but the remaining options are way off

### Reproduction Link
[https://codepen.io/anon/pen/Xzgyar?editors=1010](https://codepen.io/anon/pen/Xzgyar?editors=1010)

### Other comments
See the following screenshot: https://pasteboard.co/GTAhepm.png

**Comment by Traxo7** [comment] 2017-11-14 09:24
It's reported already:
https://github.com/vuetifyjs/vuetify/issues/2269

**Comment by KaelWD** [comment] 2017-11-14 10:07
Duplicate of #2269

**Closed by KaelWD** 2017-11-14 10:07 UTC
