### ISSUE TITLE
[Bug Report][3.1.2] VDivider : setting color prop makes the divider blank

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#16551] opened 2023-01-30 10:40 UTC
### Environment
**Vuetify Version:** 3.1.2
**Last working version:** 2.6.12
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Set color prop on VDivider

### Expected Behavior
The divider to be colored

### Actual Behavior
Divider is blank

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kE1uwjAQha8y9SatRGIB7SYNiO56gy4wC5oY6hL/yHZSIZS7d2xHFQVaZZOZN/7ezFufyIsxRd9xUpLKc2naredLpgCqPt8aE39jIbdCYcV8+KapHYVG9KLhFmrdartgxPKGkWVFf5SRATC7fnVzbn6D7vyx5UiPLiWgyfNNl9AZV01FOqKiZ8dh6WorjAfHfRdkIY22Hk7I3cEAO6slZJhKFoZrrZwH6fawCPp99srbVsObtm1zlz0EeMIhiExIYuESpvh0WmGwp7ALGwXHSAmxE3roEWpGPrw3rqS0U+awL2ot6Qo1ajvlheR5o+VqXsyKxyfaCOfP+wV3Mn+3+stxi46MTM7gXuyOfxmMMnKnxSxhx1ZAXqEo8ntuc8sVxs3tv3tfzP7a/UK72j94DkwNmGUr1MFdxFi7GOF6E0aGCUloHI53kM03kGHuCg==)

**Comment by KaelWD** [comment] 2023-01-30 10:47
Duplicate of #16517

**Closed by KaelWD** 2023-01-30 10:47 UTC
Labels: S: triage
