### ISSUE TITLE
Inconsistent behaviour on v-select with autocomplete for object/string arrays

### ISSUE THREAD

**Issue by brenogazzola** [vuetifyjs/vuetify#1950] opened 2017-09-29 16:36 UTC
### Steps to reproduce
Create a v-select with autocomplete, supply it with an array of objects. Choose one of the options
Create another v-select with autocomplete, supply it with an array of strings. Choose one of the options

### Versions
Vuetify: 0.15.7
Vue: 2.4.4
OS: Windows 10
Browsers: Chrome

### What is expected ?
When clicked the v-select using the object array should show all available options, like the v-select using the string array does.

### What is actually happening ?
When clicked the v-select using the object array shows only the option that matches the displayed text

### Reproduction Link
https://codepen.io/bspg/pen/oGwpxb

**Comment by KaelWD** [comment] 2017-09-29 16:37
Duplicate of #1890

**Closed by KaelWD** 2017-09-29 16:37 UTC
