### ISSUE TITLE
[Bug Report] How to pass index using  vuetify datatable <v-data-table>

### ISSUE THREAD

**Issue by bhavinichauhan-easternts** [vuetifyjs/vuetify#12165] opened 2020-09-03 04:20 UTC
### Environment
**Vuetify Version:** 2.2.26
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4183.83
**OS:** Windows 10, Windows

### Steps to reproduce
1. Simple vuetify datatable 
2.  I want to pass index in edit and delete button

### Expected Behavior
I want to pass index in edit and delete button

### Actual Behavior
Not able to pass index 

### Reproduction Link
<a href="https://codepen.io/pistol/pen/PowZGmX" target="_blank">https://codepen.io/pistol/pen/PowZGmX</a>

**Comment by hellBackFire** [comment] 2020-09-03 07:33
i tried it but found that there is no other way  to do this for now ,other than adding the index value directly to array of elements you are passing to data table.

For this you can use computed property for that array and add index for each of them

May be this will help 
https://codepen.io/akshat-jaitly/pen/Yzqrgod

**Comment by KaelWD** [comment] 2020-09-03 07:36
Duplicate of #11850

**Closed by KaelWD** 2020-09-03 07:36 UTC
Labels: triage
