### ISSUE TITLE
[Bug Report][2.5.7] Input autofill broken html

### ISSUE THREAD

**Issue by JokerMartini** [vuetifyjs/vuetify#13977] opened 2021-07-23 14:33 UTC
### Environment
**Vuetify Version:** 2.5.7
**Last working version:** 2.1.15
**Vue Version:** 2.6.14
**Browsers:** Chrome 91.0.4472.164
**OS:** Windows 10

### Steps to reproduce
When a user begins to type in the first field, chrome populates and autocomplete select, when the user selects one of the items and hits enter, it populates the forms fields. However it keeps a 'light-blue' div inside each input field. Never removing it. This light-blue div did not appear in earlier versions of vuetify.

### Expected Behavior
I expect the light-blue div not to exist

### Actual Behavior
Remove the light-blue div after selecting autocomplete option

### Reproduction Link
<a href="https://codepen.io/jokermartini/pen/mdmqWWV" target="_blank">https://codepen.io/jokermartini/pen/mdmqWWV</a>

**Comment by KaelWD** [comment] 2021-07-23 14:39
Duplicate of #5269

**Closed by KaelWD** 2021-07-23 14:39 UTC
Labels: S: triage
