### ISSUE TITLE
[Feature Request] VDataTable`s item.name slots need item index of data.

### ISSUE THREAD

**Issue by garrettjavalia** [vuetifyjs/vuetify#12122] opened 2020-08-26 11:10 UTC
### Problem to solve
When you look for the sample code of VDataTable, there is a CRUD sample of it, which makes a item.action slot for delete and edit button. however, because the slot has no information about index of item in datalist, it has to do ugly IndexOf in the logic to find which index it was meant to be removed or edited.
(it could even not work if there are multiple duplicated data.)

### Proposed solution
when you see 
genDefaultRows (items: any[], props: DataScopeProps) {
      return this.$scopedSlots['expanded-item']
        ? items.map(item => this.genDefaultExpandedRow(item))
        : items.map(item => this.genDefaultSimpleRow(item))
    },
it doesnt pass index even it is just second argument of items.map function.
so we have to pass it and let those data exposed in gen*Rows` item slots` property.

**Comment by garrettjavalia** [comment] 2020-08-26 13:05
#12123 is my poor code proposal. it shows me that it failed to pass lint test.

**Comment by jacekkarczmarczyk** [comment] 2020-08-26 13:17
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10646

**Closed by jacekkarczmarczyk** 2020-08-26 13:17 UTC
Labels: triage
