### ISSUE TITLE
[Bug Report] vue/valid-v-slot "v-slot" directive doesn't suppport any modifier. eslint-plugin-vue

### ISSUE THREAD

**Issue by GustavoFenilli** [vuetifyjs/vuetify#13331] opened 2021-03-26 19:37 UTC
### Environment
**Vuetify Version:** 2.4.8
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
1. Install Vue using vue-cli 3 using typescript, and eslint.
2. Install decorator properties.
3. Install vuetify

### Expected Behavior
Not throwing any error as the documentation uses like this.

### Actual Behavior
Its working fine, but vscode eslint gives an error.

### Reproduction Link
<a href="https://codepen.io/gustavofenilli/pen/wvgGdYM" target="_blank">https://codepen.io/gustavofenilli/pen/wvgGdYM</a>

**Comment by jacekkarczmarczyk** [comment] 2021-03-26 20:58
Duplicate of https://github.com/vuetifyjs/vue-cli-plugins/issues/235

might be added to docs though

**Comment by GustavoFenilli** [comment] 2021-03-26 22:00
I think this should be added as a caveats to the docs at least until there is a proper fix in the next versions of vue/vuetify/eslint-plugin-vue.

Thanks by mentioning the duplicate, I will try the fix by adding to the rules instead.

**Closed** 2021-04-30 19:26 UTC
Labels: T: documentation
