### ISSUE TITLE
[Bug Report][3.1.4] Transparent Select options inside navigation-drawer

### ISSUE THREAD

**Issue by alexpancak3** [vuetifyjs/vuetify#16658] opened 2023-02-13 21:32 UTC
as title says

**Comment by alexpancak3** [comment] 2023-02-13 21:48
Environment
Vuetify Version: 3.1.4
Last working version: 3.0.0
Vue Version: 3.2.13
Browsers: Chrome 109.0.5414.120
OS: Windows 10

Steps to reproduce
[v-select] inside [v-navigation-drawer]

Expected Behavior
[v-select] options should be on the top layer

Actual Behavior
I have a [v-select] dropdown inside [v-navigation-drawer], all the options are transparent

**Comment by KaelWD** [comment] 2023-02-14 05:46
Duplicate of #16615

**Closed by KaelWD** 2023-02-14 05:46 UTC
Labels: S: triage
