### ISSUE TITLE
[Bug Report][3.3.22] v-combobox clears all values when a duplicate value is entered

### ISSUE THREAD

**Issue by lwalter-ax** [vuetifyjs/vuetify#18550] opened 2023-10-26 22:58 UTC
### Environment
**Vuetify Version:** 3.3.22
**Last working version:** 2.6.12
**Vue Version:** 3.3.4
**Browsers:** Chrome 118.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
You can actually reproduce this using the example on the combobox docs page.

1. Enable "multiple" prop
- can enable "chips" but it will behave the same either way
2. Type in an option and hit enter- if using the example on the docs page type in "Colorado" and hit enter
Result: the item is selected
3. Type in the same option and hit enter again -- for example, type in "Colorado" and hit enter
Result: The term (ex: Colorado) is cleared from the selection entirely

### Expected Behavior
The search term should remain selected but no duplicate values should be listed.
Reproduction of the expected behavior we get when using this component in vuetify version 2
https://github.com/vuetifyjs/vuetify/assets/63066002/bc9be8bd-c963-4c3f-95b0-68f32898fc4b

### Actual Behavior
Both search terms, the original and the duplicate, are removed. The terms are no longer applied at all. This is a change in behavior from vuetify v2.
v3 behavior:
https://github.com/vuetifyjs/vuetify/assets/63066002/38fe0a20-6bec-4f6d-afed-9a52794c2053

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpNkMsKgzAQRX8lzMaNVdCuxApFaH+g0IW6iJraQMyE+MBS+u/VqMTV3DnzYO5kX+h05V+V8saBQQRxz1olaM+SXBISjyeqlJEmqVD2lEumN7TBtsQSpx0RUr256mzaDqLnSjBLBC2ZuOSQ7qNgaxGfT+jmYuakVPAXasmp4xInRYGa1rjo2yx5bfCdoW7WjgebaLeI5wdbLhunsIuT2Len7o4MOlpayOo49g+fgJ8LoRd6Z1hjEEDxB4UUXvg=)

**Comment by miroslavgeorgiev** [comment] 2023-10-28 15:12
In fact it behaves the same way as you have clicked on already selected item aka. it unselects it.
Which is exaclty the normal behavior to me.

I'm not sure - why you would need two duplicate values there?

**Comment by websitevirtuoso** [comment] 2023-11-03 05:21
yes this is expected behaviour. because we use flag multiple
and when you type "colorado" second time it just deselect this value.
For me this is not bug

**Comment by Ali-Nasir-01** [comment] 2023-11-12 13:08
I think there might be a bug because when the user enters the word "duplicate," both instances of the word are deleted. It would be better if only one of them is deleted so that only one word remains.

**Comment by lwalter-ax** [comment] 2023-11-17 17:07
Think about this in the context of a lot of items selected. If you don't realize that you already have "Colorado" selected and try to add it again, you won't understand why it's not applied. It's easy to understand what this is doing when you're just typing in the same word twice in a row, but that is not a normal use case. You wouldn't type the same word twice in a row. You'd type in a few words, maybe forget you already applied one, and then look at the result assuming that all of the words you entered are applied when in fact you actually removed one. Plus it's a change in functionality from the previous version.

**Comment by lwalter-ax** [comment] 2023-11-17 17:10
> In fact it behaves the same way as if you click on already selected item - it unselects it. Which is exaclty the normal behavior to me.
> 
> I'm not sure - why would you need two duplicate values there?

The expected behavior does not state there should be two duplicate values. It states that only the duplicate value should be removed -- therefore leaving just one value (but one value, not zero).

**Comment by lwalter-ax** [comment] 2023-11-17 17:26
I added videos of the expected behavior (from vuetify version 2) and the bug (vuetify version 3) for clarification.

**Comment by miroslavgeorgiev** [comment] 2023-11-17 20:15
> > In fact it behaves the same way as if you click on already selected item - it unselects it. Which is exaclty the normal behavior to me.
> > I'm not sure - why would you need two duplicate values there?
> 
> The expected behavior does not state there should be two duplicate values. It states that only the duplicate value should be removed -- therefore leaving just one value (but one value, not zero).

In the context you described - I understand better what you're assuming and now I agree with you.
In a case of typing - it should't remove already selected value and just do nothing if it is duplicated one 👍

**Comment by KaelWD** [comment] 2023-11-19 13:24
Duplicate of #16100

**Closed by KaelWD** 2023-11-19 13:24 UTC
Labels: S: triage
