### ISSUE TITLE
[Bug Report] ".v-icon.v-icon" overrides ".v-btn__content .v-icon--left, .v-btn__content .v-icon--right"

### ISSUE THREAD

**Issue by TamirosC** [vuetifyjs/vuetify#11596] opened 2020-06-10 14:43 UTC
### Environment
**Vuetify Version:** 2.2.33
**Last working version:** 2.0.0-beta.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97, Google Chrome
**OS:** Windows 10, Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
in production build ".v-icon.v-icon" overrides ".v-btn__content .v-icon--left, .v-btn__content .v-icon--right"

the commit that ruined it:
https://github.com/vuetifyjs/vuetify/commit/3d9dc507ecaeedb3def0b93f7ad41ba6d2419a45

steps to fix:
change .v-icon.v-icon back to .v-icon
or put the '&--right' '&--left' etc under .v-icon.v-icon

### Expected Behavior
".v-btn__content .v-icon--left" overrides ".v-icon.v-icon"

### Actual Behavior
".v-icon.v-icon" overrides ".v-btn__content .v-icon--left"

### Reproduction Link
<a href="https://github.com/vuetifyjs/vuetify/commit/3d9dc507ecaeedb3def0b93f7ad41ba6d2419a45" target="_blank">https://github.com/</a>

**Comment by oraant** [comment] 2020-06-19 08:29
Same error, the icons now is very big than the normal size.

## Normal Size:
![TIM截图20200619162711](https://user-images.githubusercontent.com/12079340/85113439-dc80b280-b249-11ea-8c2a-7a6ffceb0741.png)
![TIM截图20200619162731](https://user-images.githubusercontent.com/12079340/85113444-de4a7600-b249-11ea-8e00-a6bf0f9e5d22.png)

---
## Wrong Size:
![TIM图片20200619162634](https://user-images.githubusercontent.com/12079340/85113446-dee30c80-b249-11ea-9759-e339ec3b0393.png)

**Comment by oraant** [comment] 2020-06-19 08:35
It's weird because it's still occurs in v2.3.1, and the official excamples seems fine.
I'm thinking if there are something we missed.

**Comment by oraant** [comment] 2020-06-19 08:47
Ah …… I see. They said it's a change for v-btn in [release 2.2.0](https://github.com/vuetifyjs/vuetify/releases?after=v2.2.1) like this:

Changes: v-btn
- increased font-weight
- increased icon sizes
- thicker border when using the outlined prop

But they didn't update the official documents and examples.
So I guess we should specify the icon size by ourself.

**Comment by KaelWD** [comment] 2020-06-19 09:23
Duplicate of #11294

**Closed by KaelWD** 2020-06-19 09:23 UTC
Labels: triage
