### ISSUE TITLE
v-select with autocomplete not correct styling of list avatar

### ISSUE THREAD

**Issue by lucafaggianelli** [vuetifyjs/vuetify#1824] opened 2017-09-20 16:25 UTC
The select automplete list is not correctly styled for list items with avatar,

### Steps to reproduce
Run codepen, open the select, see the first group is correctly styled, the second is not. It appears that the correct CSS avatar class is added only if the item objects contains the property `avatar`. It would be better to let the user specify the avatar option or not

### Versions

Vue 2.4
Vuetify 0.5.7

### What is expected ?

List item should be correctly styled for avatar

### What is actually happening ?

Avatars in list items are not styled correctly if the property holding the image src is not called `avatar`

### Reproduction Link

https://codepen.io/lucafaggianelli/pen/VMaoKJ?editors=1010

**Comment by johnleider** [comment] 2017-09-20 16:44
We will need to add an "avatar" value within the select. Currently, the system uses that property name to determine if it should automatically add the **avatar** prop to the ```v-list-tile``` element.

**Comment by johnleider** [comment] 2017-09-23 01:04
I'm moving this out of the release cycle and will be looking for help on this one. I have tried multiple approaches to alleviate the issue, however, every solution yields a new potential issue.

- Increasing debounce on resize
- Creating an additional debounce for onResize method along with deactivating and reactivating the menu

This bug is caused by the width of the content menu being calculated before it has initiated its resize. You'll notice, that when increasing the window size, the issue is not reproduce-able. This is because the menu has a minimum width of its activator width.

**Comment by johnleider** [comment] 2017-09-23 02:33
Removed milestone from wrong issue.

**Comment by johnleider** [comment] 2017-09-23 02:35
While the change I'm adding does not allow for the reproduced functionality in its current state, you now have the ability to set the **item-avatar** prop to whatever corresponds from the **items** array.

This means, however, that every item passed through must share the same avatar property.

**Closed** 2017-09-23 02:38 UTC
Labels: bug, enhancement

**Comment by lucafaggianelli** [comment] 2017-09-23 12:17
@johnleider perfect! to me it's fine, the reproduction functionality was just for testing purpose and to show you the difference with and without 'avatar' prop, I would use just 1 prop for avatar

**Comment by lucafaggianelli** [comment] 2017-10-06 22:33
It works great in 0.16, but the prop is missing from the docs, could you add it for others to use it?
