### ISSUE TITLE
[Documentation] v-alert prominent example does not render in doc as it does in codepen, missing halo

### ISSUE THREAD

**Issue by someone1** [vuetifyjs/vuetify#13195] opened 2021-03-02 23:07 UTC
### Environment

**Browsers:** Chrome 88.0.4324.190
**OS:** Windows 10

### Steps to reproduce
Load the linked document and view the example in a codepen, the results are different.

### Expected Behavior
doc to reflect how the example loads in codepen

### Actual Behavior
doc loads an example with no halo around icon

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/alerts/#prominent" target="_blank">https://vuetifyjs.com/en/components/alerts/#prominent</a>

**Comment by KaelWD** [comment] 2021-03-04 07:03
Duplicate of #12181

**Closed by KaelWD** 2021-03-04 07:03 UTC
Labels: triage
