### ISSUE TITLE
[Bug Report] Opacity helper classes not inheriting theme from subcomponents

### ISSUE THREAD

**Issue by KRaymundus** [vuetifyjs/vuetify#13352] opened 2021-03-31 09:03 UTC
### Environment
**Vuetify Version:** 2.4.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.90
**OS:** Windows 10

### Steps to reproduce
A components with a theme different than the app has it's text opacity classes still using the colors of the app.

### Expected Behavior
Text should turn white

### Actual Behavior
Text stays dark

### Reproduction Link
<a href="https://codepen.io/Raymundus/pen/zYNoQbK" target="_blank">https://codepen.io/Raymundus/pen/zYNoQbK</a>

### Other comments
The text color is inherited from the root theme instead of the component at hand.

You can also simply click the 'invert example colors' icon of the text-opacity example in the docs:
https://vuetifyjs.com/en/styles/text-and-typography/#opacity

**Comment by nekosaur** [comment] 2021-03-31 09:07
Duplicate of https://github.com/vuetifyjs/vuetify/issues/12179 (which is a duplicate of https://github.com/vuetifyjs/vuetify/issues/12010)

**Closed by nekosaur** 2021-03-31 09:07 UTC
Labels: duplicate
