### ISSUE TITLE
[Bug Report] v-autocomplete opens when clicking close icon of v-chip in selection slot

### ISSUE THREAD

**Issue by starkfree** [vuetifyjs/vuetify#11824] opened 2020-07-09 08:23 UTC
### Environment
**Vuetify Version:** 2.3.4
**Vue Version:** 2.6.11
**Browsers:** Firefox 79.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
1. Find the select box in the codepen (identical to the example shown under `slots` on this page in the documentation (https://vuetifyjs.com/en/components/autocompletes/#slots). The version shown is the `filled` variant of the v-autocomplete.

2. Click the `x` icon for the v-chip for `Britta Holt`, the menu will incorrectly open as well as the chip will be removed (expected). This is likely due to the `click:close` event propagating into the v-autocomplete triggering a menu opening.

3. Scroll to line `95` in the HTML side of the codepen, change `filled` to `solo` or `outlined` and you will experience the same issue when removing `Britta Holt` (or any other chip)

4. Scroll to line `95` in the HTML side of the codepen, remove `filled` (or solo/outlined) and it will revert to the `standard` variant of the v-autocomplete. Click the `x` on `Britta Holt` now and you will notice that in this variant, the menu does not open.

### Expected Behavior
I would expect that clicking the close button on a customized v-chip, modified via the correct v-slot:selection functionality, would only remove the chip and nothing else in the solo, outlined, and filled variants, just like it does in the standard variant.

### Actual Behavior
On the three custom variants of the v-autocomplete (solo, outlined, filled), clicking the close button on a customized v-chip, causes the menu to open.

### Reproduction Link
<a href="https://codepen.io/starkfree/pen/zYrjWGN?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fautocompletes%2F" target="_blank">https://codepen.io/starkfree/pen/zYrjWGN?editable=true&editors=101%3Dhttps%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fautocompletes%2F</a>

### Other comments
This only seems to happen if you customize the v-chip layout via the v-slot:selection. If you simply use the built in v-chip layouts, it works as expected.

**Comment by johnleider** [comment] 2020-10-07 14:46
duplicate of #10774

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-10-07 14:46 UTC
Labels: C: VAutocomplete, C: VSelect, T: bug
