### ISSUE TITLE
[Feature Request] Allow snackbars to be closed by pushing them to the side

### ISSUE THREAD

**Issue by P4sca1** [vuetifyjs/vuetify#6535] opened 2019-02-18 14:06 UTC
### Problem to solve
Implementing a close button does not look that clean sometimes.

### Proposed solution
It would be very cool if we could allow closing snackbars by pushing them to a side.
Exactly like it is possible in MacOS when you get a notification.

**Comment by KaelWD** [comment] 2019-03-01 08:32
Duplicate of #3509

**Closed by KaelWD** 2019-03-01 08:32 UTC
Labels: duplicate
