### ISSUE TITLE
Breakpoints and Nuxt broken with 1.1

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#4785] opened 2018-08-03 06:41 UTC
I upgrade vuetify to 1.1 in my Nuxt project and my conditional class depending on breakpoints are now broken. 

When the page is rendered, the wrong class are applied. 

### Versions and Environment
Vuetify: 1.1.8
Nuxt: 1.4.0

### Previously worked in:
Vuetify: 1.0.19
Nuxt: 1.4.0

### Steps to reproduce
```
<div 
  :class="{'small': $vuetify.breakpoint.xsOnly}" 
>Hello World</div>
```

### Expected Behavior
class "small" to appear only on small screen only (at page load, without resizing the window)

### Actual Behavior
class "small" is set on large screens (at page load, without resizing the window), but disappear after window resizing.

related to : https://stackoverflow.com/questions/50991071/vuetify-breakpoints-not-working-in-nuxt-js

**Comment by KaelWD** [comment] 2018-08-03 07:05
Duplicate of #3436 

Dunno how you had it working before, this has been around for a while. I guess I'll look into it this weekend, I've got some other SSR problems to solve too.

**Closed by KaelWD** 2018-08-03 07:05 UTC

**Comment by ThomasKientz** [comment] 2018-08-03 07:29
@KaelWD Was working great before  ! Don't hesitate if you need any details. Is there a workaround atm ?
