### ISSUE TITLE
[Bug Report][3.0.1] v-select with disabled items - short delay before disabled style is applied

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#16091] opened 2022-11-14 19:29 UTC
### Environment
**Vuetify Version:** 3.0.1
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Please see the reproduction link.
Open the v-select dialog. Note that the disabled style is applied ~500ms+ after the list is rendered.

### Expected Behavior
The disabled style should already be applied when the drop-down list is rendered

### Actual Behavior
There is a short moment when the rendered list items do not appear to be disabled.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kLFuwyAQhl/ldEtaybGbtF0sJ1KfoEu3kIHaZwkJAwJMB8vv3sNOrHTpAnz/cT//cZnww7kyjYQ1NqH1ykUIFEd3FkYNzvoIE3jqYYbe2wF2fHUnjDCtNSFCkhpOuf5kRq2f77KKNIRb4TIJAxBV1FSDwE9DAossce/I0mEB560LNSx3AToV5LemroZe6kBZnIWZi7W+eX392L9ex3+9oh83qytnbap1YB6VgSM7LSMxATRpL13+g+zAMEhlbsTcqXRuqrxuUtoH0tRGqJfZTwKXXSBws+1Is8Ihmau7a/Vgm2F9sKkeguBc4Gt5LN/eMR9eygNefwGI14vv)

**Comment by paul-thebaud** [comment] 2022-12-23 09:26
Experencing the same issue on Vuetify `3.0.5`.

**Comment by danielkerwin** [comment] 2023-01-17 02:27
Experiencing the same with Vuetify `3.1.0`

**Comment by KaelWD** [comment] 2023-01-17 09:08
Duplicate of #16394

**Closed by KaelWD** 2023-01-17 09:08 UTC
Labels: S: triage
