### ISSUE TITLE
v-text-field v-model changes don't update value in text field

### ISSUE THREAD

**Issue by ajsutton** [vuetifyjs/vuetify#1841] opened 2017-09-23 04:17 UTC
### Steps to reproduce
See https://codepen.io/ajsutton/pen/veXMwB

With a <v-text-field v-model="value"></v-text-field> any programmatic change to "value" should update the value in the text field, but if the text field currently has focus it does not. The value in the text field remains unchanged.

Updates are correctly reflected when the text field doesn't have focus. Works as expected with a normal <input> field.

### Versions
Vuetify 0.15.7, Vue 2.4.4.  OS X 10.12.6, Safari 11.0 and Chrome 60.0.3112.113.

### What is expected ?
Updating the value referenced by v-model for a text area should update the text in the text field.

### What is actually happening ?
The value in the text field is unchanged.

### Reproduction Link
https://codepen.io/ajsutton/pen/veXMwB

**Comment by KaelWD** [comment] 2017-09-23 05:15
Duplicate of #1726

**Closed** 2017-09-23 07:59 UTC
