### ISSUE TITLE
[Bug Report] Right drawer opens on route change 

### ISSUE THREAD

**Issue by siddiqabbasi** [vuetifyjs/vuetify#3218] opened 2018-02-08 10:10 UTC
### Versions and Environment
**Vuetify:** 0.15.7
**Vue:** 1.0.0
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 8.1

### Steps to reproduce
I can share my project link only
https://link-assignment.firebaseapp.com/#/app/progress

### Expected Behavior
I have two navigation drawer right and left.On left drawer, routes have defined, when I clicked on any route,  a right drawer opens but the right drawer should not open.
On localHost it works as expected but after deploy bug has produced.

### Actual Behavior
It has to work after deploy same like on localhost

### Reproduction Link
[https://codepen.io/johnjleider/pen/bgJOrX](https://codepen.io/johnjleider/pen/bgJOrX)

### Other comments
I can share the link if it helps.

**Comment by KaelWD** [comment] 2018-02-08 11:29
Duplicate of #2894

**Closed by KaelWD** 2018-02-08 11:29 UTC
