### ISSUE TITLE
[Bug Report] Tabs slider not showing

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#11558] opened 2020-06-04 12:21 UTC
### Environment
**Vuetify Version:** 2.2.32
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.61
**OS:** Mac OS 10.15.3

### Steps to reproduce
1. Hide a VTabs with `v-show`
2. Show the Vtabs

### Expected Behavior
The tab slider to be visible.

### Actual Behavior
Tab slider is not visible until we click on a tab.

### Reproduction Link
<a href="https://codepen.io/thomaskientz/pen/JjGoGOq" target="_blank">https://codepen.io/thomaskientz/pen/JjGoGOq</a>

**Comment by jacekkarczmarczyk** [comment] 2020-09-08 15:16
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4733

**Closed by jacekkarczmarczyk** 2020-09-08 15:16 UTC
Labels: triage
