### ISSUE TITLE
v-pagination not working

### ISSUE THREAD

**Issue by Andarius** [vuetifyjs/vuetify#426] opened 2017-04-24 10:10 UTC
**Steps to reproduce**

Go [here](https://vuetifyjs.com/components/pagination) and click on an other page number than the one selected

**Versions**

Vuetify 0.11.0

**What is expected ?**

Clicking on the button should focus the new page number

**What is actually happening ?**

The page number is not focused

**Comment by johnleider** [comment] 2017-04-24 11:44
duplicate of #414

**Closed by johnleider** 2017-04-24 11:44 UTC
