### ISSUE TITLE
[Bug Report] SSR v-responsive

### ISSUE THREAD

**Issue by usb248** [vuetifyjs/vuetify#5945] opened 2018-12-19 23:01 UTC
### Versions and Environment
**Vuetify:** 1.3.15
**Vue:** 2.5.17
**Browsers:** Firefox 64.0
**OS:** Windows 10

### Steps to reproduce
Use v-responsive component and specify just height (for example)

### Expected Behavior
getting just style property of specified properties and not all other property with undefined

### Actual Behavior
See source code of codesandbox

### Reproduction Link
<a href="https://codesandbox.io/s/o95x14r0xz" target="_blank">https://codesandbox.io/s/o95x14r0xz</a>

**Comment by KaelWD** [comment] 2018-12-20 04:58
Duplicate of vuejs/vue#9231

**Closed by KaelWD** 2018-12-20 04:58 UTC
