### ISSUE TITLE
[Bug Report][3.3.22] autocomplete auto-adjust is adjusting the width while scrolling

### ISSUE THREAD

**Issue by SeRoCon** [vuetifyjs/vuetify#18567] opened 2023-10-31 15:58 UTC
### Environment
**Vuetify Version:** 3.3.22
**Vue Version:** 3.3.4
**Browsers:** Google Chrome, Mozilla Firefox, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
Click on the autocomplete element to pull up the overlay and scroll all the way down.

### Expected Behavior
The overlay is *already* at proper size to also display the long text directly from the start (before scrolling down).

### Actual Behavior
The overlay will jump to a larger size once the long text comes up.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtkkFuwjAQRa9ieZMNTVDoKkqROAdhMdgT1YlxLOzQoqrX4gJcrOO4oaZcgdV8vz8zluW//eLuKIqNtflpRF7x2uPBavC4bgxj9ekFrJ3kdBCD8aAMHpnzZ41vDf9Q0r9XrFwu7WfDfzvj4OgHMdAy9DhjxpSkoT0YMNjwP1y1gxgdBrMF7e48icYpfyYrrAPhU1PDHjVZm/S2dLGiBzlq2GZBZQv2rP/q9QJO6r7t4HrRTnatDqQnQWfoXScD6SEIIlHcyKOIU3GcCIlsl37JYdRe0UfNZF0X92mZ80b4FrgYx9A45bEukpzy7wVf5av8lcdalnz3A05m6c0=)

### Other comments
If the actual functionality is desired, then please add property to the v-autocomplete / v-select component to toggle between the described funciontalities.

**Comment by KaelWD** [comment] 2023-10-31 16:00
Duplicate of #17751

**Closed by KaelWD** 2023-10-31 16:00 UTC
Labels: S: triage
