### ISSUE TITLE
[Feature Request] Validating custom components

### ISSUE THREAD

**Issue by no0by5** [vuetifyjs/vuetify#11234] opened 2020-04-25 13:23 UTC
### Problem to solve
In my app I have a form with my own components that I need to validate. I want to use the Vuetify validation and don't want to add a package for validation, but as far as I can tell, there is no way to add the Vuetify validation to my own components.

### Proposed solution
A way to use Vuetify validation for my own components. Am I correct in assuming that if I import the Vuetify mixin for validation, undocumented changes to the mixin could break my app? So maybe an additional mixin with a documented API could solve the problem.

**Comment by jacekkarczmarczyk** [comment] 2020-04-26 19:13
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5486

**Closed by jacekkarczmarczyk** 2020-04-26 19:13 UTC
Labels: triage
