### ISSUE TITLE
[Bug Report] VDataTable doesn't render all items from server when pagination is hidden

### ISSUE THREAD

**Issue by gkatsanos** [vuetifyjs/vuetify#8801] opened 2019-08-30 11:48 UTC
### Environment
**Vuetify Version:** 2.0.11
**Last working version:** 1.5.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Mac OS 10.14.6

### Steps to reproduce
Loading a big number of items (more than 10) from an API.
Pass the items array to the VDataTable.
Hide the footer/pagination.
Only 10 items are displayed

### Expected Behavior
All items should be displayed

### Actual Behavior
10 items displayed

### Reproduction Link
<a href="https://codepen.io/gkatsanos-the-bold/pen/VwZzLpa?editors=1011" target="_blank">https://codepen.io/gkatsanos-the-bold/pen/VwZzLpa?editors=1011</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-30 11:51
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8657

**Closed by jacekkarczmarczyk** 2019-08-30 11:51 UTC
Labels: triage
