### ISSUE TITLE
[Bug Report] Swipe gesture permanently hides a side menu

### ISSUE THREAD

**Issue by MrLewBrew** [vuetifyjs/vuetify#9625] opened 2019-11-08 10:22 UTC
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Mozilla Firefox, Google Chrome
**OS:** Windows

### Steps to reproduce
On a touch-screen device, or using web developer tools to mock a touch-screen device, swiping left on the screen will hide a left side menu and swiping right will hide a right side menu.
The menus can be brought back by a page refresh only.

### Expected Behavior
Menus aren't hidden.

### Actual Behavior
Menus are permanently hidden until page refresh.

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/quick-start" target="_blank">Vuetify documentation website</a>

### Other comments
This issue can most easily be recreated on the Vuetify documentation website: https://vuetifyjs.com/en/getting-started/quick-start

**Comment by jacekkarczmarczyk** [comment] 2019-11-10 07:06
I can get the menu back by swiping right (starting near the the left edge)

**Comment by MrLewBrew** [comment] 2019-11-11 09:43
@jacekkarczmarczyk, I can get the menu back like this too. However, if both left and right menus are closed and I swipe to get one back, then swipe to get the other back, the second gesture will close one of the menus whilst bringing back the other. So I am unable to get both menus back together.

**Comment by jacekkarczmarczyk** [comment] 2019-11-11 09:47
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5838

**Closed by jacekkarczmarczyk** 2019-11-11 09:47 UTC
Labels: needs more information, triage
