### ISSUE TITLE
[Bug Report] VSlideGroup does not reset to start when bind data after trigger next

### ISSUE THREAD

**Issue by pasteusernamehere** [vuetifyjs/vuetify#11964] opened 2020-07-30 19:44 UTC
### Environment
**Vuetify Version:** 2.3.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 84.0.4147.105
**OS:** Mac OS 10.15.6

### Steps to reproduce
Using the codepen link:
1. Click the next arrow to slide to options 5 - 9.
2. Click the toggle binding button.
3. Notice that the slide group items are **not** visible.
4. Click the toggle binding button.
5. Click the previous arrow.
6. Click the toggle binding button.
7. Notice that the slide group items are visible.

### Expected Behavior
When the slide group is bound to a new datasource it should scroll to the first item in the slide group.  Currently no items are visible.

### Actual Behavior
When binding new data to the slide group the scroll to first item is not set.

### Reproduction Link
<a href="https://codepen.io/pasteusernamehere/pen/bGEPOYV" target="_blank">https://codepen.io/pasteusernamehere/pen/bGEPOYV</a>

### Other comments
I assume this is a defect.  If not can you please provide a potential workaround?

**Comment by pasteusernamehere** [comment] 2020-08-02 22:08
I found a workaround for now until a permanent fix is implemented in the API.

Within my component that implements v-slide-group I have added an additional interface:


`
interface SlideGroup {
  scrollOffset: number;
}
`

Then with a watcher I can reset the scrollOffset when the data binding changes:

```
  @Watch("adminView")
  resetSlideGroupHack() {
    ((this.$refs.chipGroup as unknown) as SlideGroup).scrollOffset = 0;
  }
```

If anyone has any better suggestions I am all ears.

**Comment by Stelikas** [comment] 2020-10-14 20:32
Does anyone have a better explanation or solution for a newbie? This issue has been bothering me too. 
Thanks and regards!

**Comment by stephenbeckett** [comment] 2020-10-19 09:17
@Stelikas A similar hack to above but a bit simpler perhaps is doing something like this:
`this.$refs.slideGroup._data.scrollOffset = 0;`

When the bound data changes (detected via a watcher)

**Comment by Stelikas** [comment] 2020-10-27 18:01
@stephenbeckett Thank you sir, made it work like a charm! 👍

**Comment by KaelWD** [comment] 2022-06-19 08:04
Duplicate of #10971

**Closed by KaelWD** 2022-06-19 08:04 UTC
Labels: T: bug, has workaround, C: VSlideGroup
