### ISSUE TITLE
Text box search per column

### ISSUE THREAD

**Issue by schippcj** [vuetifyjs/vuetify#5078] opened 2018-09-12 13:32 UTC
**Problem to solve**
Currently, there is not an option to have a text box under every column header that can be used for searching the table per column. Having per-column search boxes can be more intuitive for users in some situations than a master search bar.

**Proposed solution**
Add an option to allow for per-column search boxes.

**Comment by nekosaur** [comment] 2018-09-13 09:43
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3102

**Closed by nekosaur** 2018-09-13 09:43 UTC
Labels: duplicate
