### ISSUE TITLE
[Bug Report] v-textarea outlined style display abnormal in v-expansion-panels

### ISSUE THREAD

**Issue by recrute** [vuetifyjs/vuetify#8582] opened 2019-08-17 02:19 UTC
### Environment
**Vuetify Version:** 2.0.7
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 7

### Steps to reproduce
click v-expansion-panel-header icon to open v-expansion-panel-content，
just that

### Expected Behavior
label will display on textarea border

### Actual Behavior
label cover by textarea border

### Reproduction Link
<a href="https://codepen.io/recrute/pen/KKPMNLR" target="_blank">https://codepen.io/recrute/pen/KKPMNLR</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-17 11:28
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7470

**Closed by jacekkarczmarczyk** 2019-08-17 11:28 UTC
Labels: triage
