### ISSUE TITLE
[Bug Report][2.6.3] Setting :host font-size does not fix rem sizes if used as web-component

### ISSUE THREAD

**Issue by euberdeveloper** [vuetifyjs/vuetify#14793] opened 2022-03-06 13:11 UTC
### Environment
**Vuetify Version:** 2.6.3
**Vue Version:** 2.6.14
**Browsers:** Chrome 97.0.4692.99
**OS:** Linux x86_64

### Steps to reproduce
The steps to reproduce are written in the README of the linked github repo.
In addition, there is [this stack-overflow question](https://stackoverflow.com/questions/71324123/vuetify-changing-font-size-of-host-does-not-change-rem-behaviour), with a non-working answer.

### Expected Behavior
Changing :host should adjust the rem displayed sizes

### Actual Behavior
Changing :host does nothing and the rem size is determined just by the `<html>` tag

### Reproduction Link
<a href="https://github.com/euberdeveloper/test-webcomponent-vuetify-issue" target="_blank">https://github.com/euberdeveloper/test-webcomponent-vuetify-issue</a>

### Other comments
This issue was initially answered in this issue: #14781

The answer was not working and it was not ever reopened...

**Comment by KaelWD** [comment] 2022-03-06 14:18
Duplicate of #14781

**Closed by KaelWD** 2022-03-06 14:18 UTC
Labels: S: triage
