### ISSUE TITLE
[Bug Report][3.1.8] v-select dropdown wrong position at first time opening

### ISSUE THREAD

**Issue by mohammad-zr** [vuetifyjs/vuetify#16885] opened 2023-03-10 18:17 UTC
### Environment
**Vuetify Version:** 3.1.8
**Vue Version:** 3.2.47
**Browsers:** Edge 110.0.1587.63
**OS:** Windows 10

### Steps to reproduce
set vuetify rtl option to true
put v-select in a custom width div or inside v-row / v-col

### Expected Behavior
Expect to open dropdown below v-select

### Actual Behavior
dropdown opened at left side of window first and then at second time it gets opened in proper position

### Reproduction Link
[https://codepen.io/Mohammad-Zare/pen/rNZpyQP?editors=101](https://codepen.io/Mohammad-Zare/pen/rNZpyQP?editors=101)

**Comment by yeya** [comment] 2023-03-13 14:54
Duplicate of #16628

**Closed** 2023-03-14 04:13 UTC
Labels: S: triage
