### ISSUE TITLE
[Bug Report] Problem with activator with VMenu and VTextField

### ISSUE THREAD

**Issue by rsb5003** [vuetifyjs/vuetify#10720] opened 2020-03-02 15:38 UTC
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Safari 13.0.4
**OS:** Mac OS 10.15.2

### Steps to reproduce
If a `v-text-field` is in outline mode and is the activator for a `v-menu`, if you click on the outline of the `v-text-field` it will not activate the menu. 

### Expected Behavior
I would expect clicking the outline of the `v-text-field` to activate the menu so that I can see the items in the menu.

### Actual Behavior
The `v-text-field` is 'focused` and the text field label will move to the top of the outline as if you would expect. But the menu items are not displayed unless you click inside the outline

### Reproduction Link
<a href="https://codepen.io/rsb5003/pen/JjdJVNz" target="_blank">https://codepen.io/rsb5003/pen/JjdJVNz</a>

**Comment by KaelWD** [comment] 2020-03-02 15:53
Duplicate of #7610

**Closed by KaelWD** 2020-03-02 15:53 UTC
Labels: triage
