### ISSUE TITLE
Can't close side bar in mobile-like size?

### ISSUE THREAD

**Issue by jerrychen1013** [vuetifyjs/vuetify#27] opened 2016-12-23 05:48 UTC
It seems can't close side bar in mobile-like size. Does anyone have idea?
<img width="593" alt="2016-12-23 1 25 13" src="https://cloud.githubusercontent.com/assets/10149969/21447859/59cea880-c916-11e6-8cf1-1b89b564a32c.png">

**Comment by johnleider** [comment] 2016-12-23 07:50
Can you please post your markup. Thank you.

**Comment by gluons** [comment] 2016-12-23 14:33
If the issue is related to document site, please place your issue at [vuetifyjs/docs](https://github.com/vuetifyjs/docs). 🙂

**Comment by jerrychen1013** [comment] 2016-12-23 15:56
https://vuetifyjs.com/quick-start

I just open official website and found it.
My env. is maxOS Sierra 10.22.2 with Chrome 55.0.2883.95 (64-bit)).

But on the other after posting this issue, it works normally in other computer(window 10, chrome 55.0.2883.95 (64-bit)).

It still can't work in my iMac, so strange...

**Comment by johnleider** [comment] 2016-12-23 16:02
This appears to be an iOS issue. I will take a look, thank you.

**Comment by jerrychen1013** [comment] 2016-12-23 17:55
Just for your reference.
[video](https://youtu.be/4DWDjdIj8cc)

**Comment by johnleider** [comment] 2016-12-25 02:32
I was recently sponsored by BrowerSync and should be able to squash this once I receive my access, thanks again.

**Comment by johnleider** [comment] 2016-12-26 19:09
Fixed with 3ed9c88dc959b0e7f257b53bc386d8d86e7ef607.

**Closed by johnleider** 2016-12-26 19:09 UTC
Labels: bug
