### ISSUE TITLE
[Feature Request] Why there is no function to provide Snackbar?

### ISSUE THREAD

**Issue by HeyCrab3** [vuetifyjs/vuetify#16445] opened 2023-01-15 11:57 UTC
### Problem to solve
Who thinks use ref is a good idea? It is VERY DUMB! You want to CtrlC CtrlV so many times just for a little snackbar? Who want?

### Proposed solution
PLS, add a function like this one
```
import { VSnackbar } from 'vuetify'
const SnackbarInstance = new VSnackbar();
SnackbarInstance.Show('There is a good text’, 'Hey!', <maybe theme?>, <maybe icon?>)
```

**Comment by KaelWD** [comment] 2023-01-15 12:33
Duplicate of #2384

**Closed by KaelWD** 2023-01-15 12:33 UTC
Labels: S: triage
