### ISSUE TITLE
[Bug Report][3.0.0-beta.5] navigation drawe

### ISSUE THREAD

**Issue by omerkimel** [vuetifyjs/vuetify#15457] opened 2022-07-18 08:51 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.36
**Browsers:** Chrome 103.0.0.0
**OS:** Windows 10

### Steps to reproduce
Adding a local provider with a local of rtl true, to the app. Toggling the drawer

### Expected Behavior
Drawer should slide to the right when set to flase, in order to be hidden

### Actual Behavior
Drawer slides to the left, thus to the middle of the screen.

### Reproduction Link
<a href="https://codepen.io/kimel/pen/QWmdRwR?editors=1010" target="_blank">https://codepen.io/kimel/pen/QWmdRwR?editors=1010</a>

**Comment by KaelWD** [comment] 2022-07-18 08:52
Duplicate of #15364

**Closed by KaelWD** 2022-07-18 08:52 UTC
Labels: S: triage
