### ISSUE TITLE
[Bug Report][3.0.0-beta.3] v-list-item cannot always be made inactive via the "active" prop

### ISSUE THREAD

**Issue by kpturner** [vuetifyjs/vuetify#15302] opened 2022-06-15 11:10 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.3
**Vue Version:** 3.2.37
**Browsers:** Chrome 102.0.5005.61
**OS:** Mac OS 10.15.7

### Steps to reproduce
If you have a list item and specify the "active" property you can set the active state of the list item by changing that property (as per the docs).  If, however, you subsequently make the list item active by simply clicking on it, then changing the value of the active property to false afterwards does it deactivate the list item.  The property is false, but the list item retains its active appearance (the classes defining its active appearance are not removed).

### Expected Behavior
Clicking the list item or changing the active property should always behave in the same way.

### Actual Behavior
If you make an item active by clicking it, the active property ceases to have the desired effect.

### Reproduction Link
<a href="https://codepen.io/kpturner/pen/vYdbzXY" target="_blank">https://codepen.io/kpturner/pen/vYdbzXY</a>

### Other comments
There are documentation issues too.  The default slot exposes an "isActive" property but in the Vuetify 3 docs it is defined as an "active" property:
https://next.vuetifyjs.com/en/api/v-list-item/#slots-default

**Comment by KaelWD** [comment] 2022-07-25 16:04
Duplicate of #15042

**Closed by KaelWD** 2022-07-25 16:04 UTC
Labels: T: bug, C: VListItem
