### ISSUE TITLE
[Bug Report][3.1.1] Autocomplete items do not update on type when using objects

### ISSUE THREAD

**Issue by peteklein23** [vuetifyjs/vuetify#16410] opened 2023-01-10 22:30 UTC
### Environment
**Vuetify Version:** 3.1.1
**Vue Version:** 3.2.38
**Browsers:** Chrome 108.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Type something, the results are empty, e.g. "Min"
Click outside the autocomplete (lose focus)
Click back inside the autocomplete (regain focus)
The results that should have populated on type will show up (Minnesota, Wyoming)
This DOES NOT HAPPEN when using strings instead of objects.

### Expected Behavior
When using objects instead of strings with the autocomplete and dynamically updating items, the list should update without having to lose and regain focus.

### Actual Behavior
When using objects instead of strings with the autocomplete and dynamically updating items, one must unfocus and refocus to see the updated items in the list.

### Reproduction Link
[https://codepen.io/peteklein23/pen/abjJMvK?editors=1010](https://codepen.io/peteklein23/pen/abjJMvK?editors=1010)

**Comment by KaelWD** [comment] 2023-01-11 06:43
Duplicate of #16403

**Closed by KaelWD** 2023-01-11 06:43 UTC
Labels: S: triage
