### ISSUE TITLE
[Bug Report] v-navigation-drawer : synchronize the resize of the tool

### ISSUE THREAD

**Issue by tsound88** [vuetifyjs/vuetify#13345] opened 2021-03-30 14:47 UTC
### Environment
**Vuetify Version:** 2.4.8
**Vue Version:** 2.6.11
**Browsers:** Firefox 87.0
**OS:** Windows 10

### Steps to reproduce
See the code

### Expected Behavior
Resize correctly the v-app-bar when expand-on-hover go from true to false then to true.

### Actual Behavior
expand-on-hover from true to false then to true doesnt resize the v-app-bar computedLeft until a mouse hover is done

### Reproduction Link
<a href="https://codepen.io/tsound/pen/ZELBQmP" target="_blank">https://codepen.io/tsound/pen/ZELBQmP</a>

### Other comments
To correct :
 - When expandOnHover goes to true => reset the data isMouseover (set to false)

**Comment by johnleider** [comment] 2021-07-16 00:21
Duplicate of #13289

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-07-16 00:21 UTC
Labels: S: triage
