### ISSUE TITLE
[Feature Request] Aria attributes for Autocomplete/Combobox components

### ISSUE THREAD

**Issue by TuntematonSotilas** [vuetifyjs/vuetify#5394] opened 2018-10-23 11:35 UTC
### Problem to solve
Hello in Autocomplete and Combobox components, I can't see any of aria attributes describe in W3C :
https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html

### Proposed solution
It would be nice to have have aria attributes in the components Autocomplete/Combobox

On the combobox container : 
• role="combobox" 
• aria-haspopup="listbox"
• aria-expanded="true/false" (compute ?)
• aria-owns="IDREF"

On the Input :
• aria-autocomplete="list"
• aria-activedescendant="IDREF" : (compute ?)

On the listbox Popup :
• role="listbox" 
• aria-labelledby="IDREF" :  (compute ?)
• role="option"

**Comment by jacekkarczmarczyk** [comment] 2018-10-23 12:00
Actually this is duplicate of https://github.com/vuetifyjs/vuetify/issues/3999
Please add your comment with proposed solution to that issue. Thank you

**Closed by jacekkarczmarczyk** 2018-10-23 12:00 UTC
Labels: T: enhancement
