### ISSUE TITLE
[Bug Report] V-Data-Table heading text vertical alignment glitch with sort arrows.

### ISSUE THREAD

**Issue by jaunt** [vuetifyjs/vuetify#11113] opened 2020-04-14 17:36 UTC
### Environment
**Vuetify Version:** 2.2.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.163
**OS:** Mac OS 10.13.6

### Steps to reproduce
Note the table headings are not aligned vertically.  Also, if the table is resized horizontally, the header text items can seem to jump up and down (remove the max-width constraint in the codepen to experiment).  

### Expected Behavior
Header items should be aligned vertically.

### Actual Behavior
They seem to randomly move up or down.

### Reproduction Link
<a href="https://codepen.io/jauntcode/pen/jObbvaR" target="_blank">https://codepen.io/jauntcode/pen/jObbvaR</a>

### Other comments
On discord, dhonx suggested this workaround which seems to work great:

.v-data-table .v-data-table-header__icon.v-icon {
    position: absolute;
}

**Comment by jacekkarczmarczyk** [comment] 2020-04-14 17:38
Duplicate of https://github.com/vuetifyjs/vuetify/issues/10164

**Closed by jacekkarczmarczyk** 2020-04-14 17:38 UTC
Labels: triage
