### ISSUE TITLE
[Bug Report][3.2.3] v-chip goes 100% width(parent with display flex) in 3.2.3 release

### ISSUE THREAD

**Issue by hanifrodili** [vuetifyjs/vuetify#17356] opened 2023-05-11 15:19 UTC
### Environment
**Vuetify Version:** 3.2.3
**Last working version:** 3.2.2
**Vue Version:** 3.3.1
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
<div class="d-flex">
        <v-chip>Im in flex parent</v-chip>
      </div>

### Expected Behavior
<div class="d-flex">
        <v-chip>Im in flex parent</v-chip>
      </div>

### Actual Behavior
<div class="d-flex">
        <v-chip>Im in flex parent</v-chip>
      </div>

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkctuwjAQRX9laqmilUgMZYcCorv2C7ogLEIygFu/ZJu0FeLfOw4BIhASUrPKvM6duZ7v2Ku1ab1FNmZZQGVlEXCaa4CsTgprm98mUIXQbUTxsRC/Oik3wsLaoIfhYPAIQsNK4s+pmZ+7s6U7/1eihlIW3k9yViXNCOtwSTSCp+/qSARbONQh423lrEComxo3kdo4Vch7oLF4MiAGB2sy3rGMQl86YQN4DNtYFsoaF2AHDlewh5UzCnrkdS82l0b7AMqvYRLrT703lNLAh3Gyeug9R/gBRyDWZwcWLWHTT280Pdcu7pK3BZ+zMTSZmCONGOdsE4L1Y87LStNYhVLULtUYuLaKz6iNu60OQmFSGTUbpaN0SFf70E2n6FWydObboyNIzvodmSBWv3dItZ2k8JKODgptKpHF0keJKzQnvRpdQo9ToUN370UXY92rLkpXl0X1fa735LcU+stfWF36xub5ccl/ndzAImkRBfd91uxJys0AW/wBGJMphw==)

**Comment by KaelWD** [comment] 2023-05-12 02:16
Duplicate of #17344

**Closed by KaelWD** 2023-05-12 02:16 UTC
Labels: S: triage
