### ISSUE TITLE
[Bug Report] Input element inside v-menu won't focus on second time

### ISSUE THREAD

**Issue by digitalniweb** [vuetifyjs/vuetify#12872] opened 2021-01-02 16:14 UTC
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Firefox 84.0
**OS:** Windows 10

### Steps to reproduce
If you click the button once it focuses the inside input correctly. If you close the menu it won't focus again after second click.

### Expected Behavior
It should focus again...

### Actual Behavior
It doesn't...

### Reproduction Link
<a href="https://codepen.io/digitalniweb/pen/PoGRGqm" target="_blank">https://codepen.io/digitalniweb/pen/PoGRGqm</a>

**Comment by KaelWD** [comment] 2021-01-03 10:55
Duplicate of #4454

It doesn't focus the first time either.

**Closed by KaelWD** 2021-01-03 10:55 UTC
Labels: triage
