### ISSUE TITLE
[Bug Report][2.6.4] Vuetify causes freeze/hang due to an external library

### ISSUE THREAD

**Issue by Troplo** [vuetifyjs/vuetify#14864] opened 2022-03-24 09:22 UTC
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.13
**Browsers:** Edge 99.0.1150.46, Google Chrome, Mozilla Firefox, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
This issue can be observed by any default installations of Vuetify, upon opening the served URL via the devserver, or production build, you'll see the webpage hang for a few seconds (4-7s) before responding again on Chromium, it can take up to a minute on Firefox showing the entire web browser isn't responding, apparently this is due to the external icon library used which ends up hanging the main thread (long task).

### Expected Behavior
Loads without problem.

### Actual Behavior
Vuetify hangs main thread upon initial load.

### Reproduction Link
<a href="https://github.com/Troplo/template-vuetify-crash" target="_blank">https://github.com/Troplo/template-vuetify-crash</a>

### Other comments
![Lighthouse](https://i.troplo.com/i/619f3d90.png)
![Firefox halt](https://i.troplo.com/i/23e10fb1.png)

**Comment by KillenX** [comment] 2022-03-24 10:01
I have the same issue

**Comment by v-jovan** [comment] 2022-03-24 10:01
Same here.

**Comment by penumbra23** [comment] 2022-03-24 10:27
Works with an older version of mdi (`@mdi/font: "6.1.95"`) and importing it locally (`import '@mdi/font/css/materialdesignicons.css'` before `Vue.use(vuetify)`)

**Comment by KaelWD** [comment] 2022-03-24 10:28
Duplicate of https://github.com/Templarian/MaterialDesign-Webfont/issues/84

**Closed by KaelWD** 2022-03-24 10:28 UTC
Labels: S: triage
