### ISSUE TITLE
[Bug Report] v-combobox emits `change` event too late

### ISSUE THREAD

**Issue by downace** [vuetifyjs/vuetify#5203] opened 2018-10-02 03:25 UTC
### Versions and Environment
**Vuetify:** 1.2.5
**Vue:** 2.5.17
**Browsers:** Chromium 69.0.3497.81
**OS:** Ubuntu undefined

### Steps to reproduce
1. Enter "bar"
2. Click "Submit"

### Expected Behavior
Console output:

```
"change" "bar"
"submit" "bar"
```

### Actual Behavior
Console output:

```
"submit" null
"change" "bar"
"change" "bar"
```

### Reproduction Link
[https://codepen.io/downace/pen/wYKzXw?editors=1011](https://codepen.io/downace/pen/wYKzXw?editors=1011)

### Other comments
With `v-text-field` all works as expected

Also, `change` event is emitted twice

**Comment by KaelWD** [comment] 2018-10-29 10:55
Possible duplicate of #4679

**Comment by KaelWD** [comment] 2018-11-16 08:42
Workaround: https://codepen.io/anon/pen/YRQawa?editors=1011

**Comment by MatthewAry** [comment] 2018-11-26 14:44
This workaround seems to work. I look forward to a fix though. Thanks!

**Comment by bviala** [comment] 2018-11-28 15:56
The workaround works for me too.  
A fix would be very nice tho. 
A lot of people seem to have this issue, and it's known for quite a long time now: https://github.com/vuetifyjs/vuetify/issues/3424

**Comment by jacekkarczmarczyk** [comment] 2019-11-13 07:46
Duplicate of 4679

**Closed by jacekkarczmarczyk** 2019-11-13 07:46 UTC
Labels: C: VCombobox, T: bug
