### ISSUE TITLE
[Feature Request] Dialog, messagebox, notification service

### ISSUE THREAD

**Issue by ThinhVu** [vuetifyjs/vuetify#15497] opened 2022-07-22 03:31 UTC
### Problem to solve
Simplify dialog, message & notification usage. Clean code.

### Proposed solution
Please view the video below:
https://www.youtube.com/watch?v=nUjVrP-e1aQ

**Comment by KaelWD** [comment] 2022-07-22 07:50
Duplicate of #2384, #3037

**Closed by KaelWD** 2022-07-22 07:50 UTC
Labels: S: triage
