### ISSUE TITLE
Calendar layout glitched

### ISSUE THREAD

**Issue by JapSeyz** [vuetifyjs/vuetify#8076] opened 2019-07-26 21:02 UTC
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.5

### Steps to reproduce
Look at the documentation

### Expected Behavior
The timed event-bars should be aligned nicely across multiple days

### Actual Behavior
They're jumping up and down

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/calendars" target="_blank">https://vuetifyjs.com/en/components/calendars</a>

### Other comments
Have .a look here: https://imgur.com/a/Quhno9a

**Comment by nekosaur** [comment] 2019-07-27 09:16
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8076

**Closed by nekosaur** 2019-07-27 09:16 UTC
Labels: C: VCalendar, T: bug
