### ISSUE TITLE
[Feature Request] DatePicker Range Header

### ISSUE THREAD

**Issue by navi35** [vuetifyjs/vuetify#10185] opened 2020-01-10 12:00 UTC
### Problem to solve
Firstly, thanks for range functionality for pickers :) 

### Proposed solution
After selecting date interval, it could be better to show start and end dates on header instead of "2 selected".

This could be better 

![image](https://user-images.githubusercontent.com/17800881/72151648-ca0c6e00-33b9-11ea-873c-e788254a4e53.png)

instead of below

![image](https://user-images.githubusercontent.com/17800881/72151513-7568f300-33b9-11ea-857a-a582b20345cf.png)

Thanks :)

**Comment by YipingRuan** [comment] 2020-01-10 13:55
https://github.com/vuetifyjs/vuetify/issues/9586

**Comment by jacekkarczmarczyk** [comment] 2020-01-11 05:11
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9586

**Closed by jacekkarczmarczyk** 2020-01-11 05:11 UTC
Labels: C: VDatepicker, triage
