### ISSUE TITLE
[Feature Request] support import a single component

### ISSUE THREAD

**Issue by lynzz** [vuetifyjs/vuetify#3988] opened 2018-05-04 14:32 UTC
### Problem to solve
```
// code
import {VSnackbar} from 'vuetify'
console.log(VSnackbar)
//VSnackbar is undefined
```

not support import a single component

### Proposed solution
```
// code
import {VSnackbar} from 'vuetify'
// code
```

can support import component on demand

**Comment by KaelWD** [comment] 2018-05-04 14:37
Duplicate of #330

**Closed by KaelWD** 2018-05-04 14:37 UTC
