### ISSUE TITLE
[Bug Report] Wrong Behaviour when using v-combobox with keyboard

### ISSUE THREAD

**Issue by OToNaShiAKi** [vuetifyjs/vuetify#12781] opened 2020-12-14 05:01 UTC
### Environment
**Vuetify Version:** 2.3.21
**Vue Version:** 2.6.11
**Browsers:** Chrome 87.0.4280.88
**OS:** Windows 10

### Steps to reproduce
1.Use the backspace key to remove the selected "Vue" option.
2.Make the v-combobox lose focus.
3.Enter the complete "Vue" letter.
4.Select the "Vue" option from the search results.
5.Make the v-combobox lose focus.

### Expected Behavior
1.Remove the "Vue" option.
2.The v-combobox loses focus.
3.Search out the "Vue" options.
4.Check the "Vue" option.
5.Keep the "Vue" option in the v-combobox.

### Actual Behavior
1.As expected.
2.As expected.
3.As expected.
4.As expected.
5.It disappeared.

### Reproduction Link
<a href="https://codepen.io/otonashiaki/pen/PoGbEbE" target="_blank">https://codepen.io/otonashiaki/pen/PoGbEbE</a>

**Comment by vibhash-singh** [comment] 2020-12-16 15:52
I debugged this issue a little bit. The problem is when the menu is opened in step 3, the below code is called in function onMenuActiveChange in VSelect.ts

```
 // When menu opens, set index of first active item
    for (let i = 0; i < menu.tiles.length; i++) {
      if (menu.tiles[i].getAttribute('aria-selected') === 'true') {
        this.setMenuIndex(i)
        break
      }
    }
```

This sets the menuIndex to the first active item.

And after that when Combobox closes below code is called in function updateTags() in VCombobox.ts

```
      // If menu index is greater than 1
      // the selection is handled elsewhere
      // TODO: find out where
      if (menuIndex > -1) return (this.internalSearch = null)

      this.selectItem(this.internalSearch)
      this.internalSearch = null
```

As the menuItem is set to a number greater than -1 the function returns setting internalSearch to null and the selected option is not added. 

The issue does not happen if we perform the above steps without closing the Combobox as in that case onMenuActiveChange is not called in between which in turn does not change the menuIndex value from -1.

One of the fixes is to reset menuIndex to -1 in the blur event of VSelect.ts

**Closed** 2020-12-31 20:03 UTC
Labels: C: VCombobox, T: bug
