### ISSUE TITLE
[Bug Report] Data table pagination by server side is not working with the 'search' prop.

### ISSUE THREAD

**Issue by rubang** [vuetifyjs/vuetify#6167] opened 2019-01-16 12:30 UTC
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.2

### Steps to reproduce
1. Use the default example from the vuetifyjs website for v-data-table "Paginate and sort server-side"
2. Just simply pass a variable to the search prop in v-data-table

### Expected Behavior
Pagination should be working.

### Actual Behavior
Pagination is not working (a total item count is not shown and next / prev buttons are disabled.)

### Reproduction Link
<a href="https://codepen.io/rubang/pen/MZRagP" target="_blank">https://codepen.io/rubang/pen/MZRagP</a>

### Other comments
The pagination by server side is working fine by simply removing the search prop. There might be a bug or this information should be marked in the doc.

**Comment by jacekkarczmarczyk** [comment] 2019-01-16 12:34
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3978

**Closed by jacekkarczmarczyk** 2019-01-16 12:34 UTC
