### ISSUE TITLE
[Bug Report][3.0.0-beta.15] v-menu + v-tooltip don't close correctly

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#16018] opened 2022-11-02 10:33 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.15
**Vue Version:** 3.2.41
**Browsers:** Chrome 105.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
- Click on the first menu
- Click on the second menu

### Expected Behavior
The first menu should be closed when the second menu is opened. 

### Actual Behavior
Both menus are opened.

### Reproduction Link
[https://codepen.io/kasheftin/pen/zYaqGKR?editors=1010](https://codepen.io/kasheftin/pen/zYaqGKR?editors=1010)

### Other comments
The reason is v-tooltip used for v-menu activator button. 
When the first menu is opened, the stack has one value, and the globalTop.value is true for v-overlay component of the first menu.
Then the mouse goes over the second menu activator. It shows the tooltip for the second button. Now the stack has 2 values: first for the first menu, second - for the tooltip. globalTop.value for the first menu becomes false, then second menu click happens, and the first menu is not closed because closeConditional there is false.

**Comment by KaelWD** [comment] 2022-11-02 11:16
Duplicate of #15784

**Closed by KaelWD** 2022-11-02 11:16 UTC
Labels: S: triage
