### ISSUE TITLE
[Bug Report] v-text-field labels need to raise when browser autofill completes the field

### ISSUE THREAD

**Issue by phifa** [vuetifyjs/vuetify#7004] opened 2019-04-16 12:20 UTC
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Windows 10

### Steps to reproduce
Fill in a dummy email and password such as

johndoe@example.com
testtest

Allow Chrome browser to offer autosave. Re-visit the page and you will see that the v-text-field labels are rendered over the top of the input text.

### Expected Behavior
Expect the labels to raise above the input field.

### Actual Behavior
Labels are rendered over the top of the input field text.

### Reproduction Link
<a href="https://codepen.io/andyfusniak/pen/geXxZQ" target="_blank">https://codepen.io/andyfusniak/pen/geXxZQ</a>

### Other comments
Why was #3679 closed? Check out the CodePen. It is not working properly.

**Comment by blalan05** [comment] 2019-04-16 12:21
As mentioned several times in that issue reference. The bug is from Chrome, they do not fire a @input or @change event when auto-filling.

**Comment by blalan05** [comment] 2019-04-16 12:22
Duplicate of #3679

**Closed by blalan05** 2019-04-16 12:22 UTC
Labels: triage

**Comment by phifa** [comment] 2019-04-16 12:49
Why then does this error only happen with vuetify? Should we not provide a decent workaround, even if it is a chrome bug?

**Comment by blalan05** [comment] 2019-04-16 12:51
As previously mentioned: 
> To be fair, even google's own login form has the same problem. I believe that was the justification for closing the other issues as wontfix.
https://github.com/vuetifyjs/vuetify/issues/3679#issuecomment-381306995

**Comment by phifa** [comment] 2019-04-16 12:55
Do you have a link?

**Comment by blalan05** [comment] 2019-04-16 12:55
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

  
Thank you for your contribution and interest in improving Vuetify.

**Comment by phifa** [comment] 2019-04-16 12:57
`If you believe that this issue has not been correctly resolved, please create a new issue`
I did exactly this. But ok, I will try to build a workaround.
