### ISSUE TITLE
Datatable Inline editors have transparent background

### ISSUE THREAD

**Issue by husayt** [vuetifyjs/vuetify#5226] opened 2018-10-05 12:26 UTC
### Versions and Environment
Vuetify: 1.2.6 and 1.3.0.Alpha.1
Vue:
Browsers:
OS:

### Previously worked in:
Vuetify: 1.1.x
Vue:

### Steps to reproduce

https://vuetifyjs.com/en/components/data-tables
Go to inline editing grid demo and activate any of inline editors. Background will be transparent.

### Expected Behavior

Should be white background like here:
https://v1.vuetifyjs.com/en/components/data-tables

### Reproduction Link

[v.1.2.6](https://vuetifyjs.com/en/components/data-tables)
[v.1.3.0-alpha.1](https://next.vuetifyjs.com/en/components/data-tables)
---

**Comment by jacekkarczmarczyk** [comment] 2018-10-05 12:28
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5127

**Closed by jacekkarczmarczyk** 2018-10-05 12:28 UTC
