### ISSUE TITLE
[Feature Request] RTL support helper class

### ISSUE THREAD

**Issue by miladmeidanshahi** [vuetifyjs/vuetify#7148] opened 2019-05-07 13:03 UTC
### Problem to solve
Fix all helper class in RTL mode

### Proposed solution
no idea

**Comment by ibrahimBeladi** [comment] 2019-05-07 22:11
You issue is unclear.
However, RTL support is improving gradually. The earlier versions support RTL mainly in the form elements, other non-form elements are less supported. Not much going to change in v1.5, but in v2, there is a big room for improvements, since the grid are being rewritten as will as other components. Also, v2 will bring more RTL support.

**Comment by miladmeidanshahi** [comment] 2019-05-08 06:13
I should say exactly the main problem is that in `RTL` space classes not working very well for example:

```
in LTR mode
.ml-1: {
  margin-left: 5px;
}

but in RTL mode should be
.ml-1: {
  margin-right: 5px;
}
```
because the direction of the page has been changed in RTL, space classes must be vice Versa

**Comment by jacekkarczmarczyk** [comment] 2019-05-08 15:27
could be "s"(tart) and "e"(nd), ms-1, pe-3 etc

**Comment by ibrahimBeladi** [comment] 2019-06-09 10:24
Possibly a duplicate of #4660.

**Comment by jacekkarczmarczyk** [comment] 2019-06-09 10:32
Duplicate of #4660

**Closed by jacekkarczmarczyk** 2019-06-09 10:32 UTC
Labels: triage
