### ISSUE TITLE
[Bug Report] VSelect unnecessary growth

### ISSUE THREAD

**Issue by Teellcory** [vuetifyjs/vuetify#8311] opened 2019-08-05 21:56 UTC
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 7

### Steps to reproduce
Select the longer text and watch as it grows, even though there's absolutely no need for it.

### Expected Behavior
Select doesn't grow/grows to accommodate text being nearly the length of the select

### Actual Behavior
Select always grows.

### Reproduction Link
<a href="https://codepen.io/anon/pen/xvXzyj" target="_blank">https://codepen.io/anon/pen/xvXzyj</a>

### Other comments
The select contains a div with the visible text and an input. The input width is set at the start and does not seem to change. The longer the div text becomes, the more unnecessary white space is displayed. While this is a quick demo of it, in real use cases it is even more pronounced, pushing other flexes onto a new line when it is definitely unnecessary.

**Comment by johnleider** [comment] 2019-08-06 15:47
I believe this is simply a product of how flex works. I'm not sure what we can do besides recommending that you use the breakpoint columns. @vuetifyjs/core-team any thoughts?

**Comment by KaelWD** [comment] 2019-08-07 05:27
Duplicate of #6275

**Closed by KaelWD** 2019-08-07 05:27 UTC
Labels: pending team review, triage
