### ISSUE TITLE
[Bug Report] V-text-field with properties 'outlined' and 'icon' override the Label

### ISSUE THREAD

**Issue by edeuxk** [vuetifyjs/vuetify#8198] opened 2019-07-30 20:15 UTC
### Environment
**Vuetify Version:** 2.0.3
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Use v-stepper and within it try to insert a v-text-field with a prepend-inner-icon="place" outlined.
Then, the label will not work

### Expected Behavior
The label should not be erased by the line
![image](https://user-images.githubusercontent.com/8247995/62162271-2d2cab80-b318-11e9-98c2-83a1588f9a23.png)

### Actual Behavior
It's working but the line erase the label and it's not clean.
![image](https://user-images.githubusercontent.com/8247995/62162024-a37cde00-b317-11e9-8bdc-65f795fd2ea8.png)

### Reproduction Link
<a href="https://codepen.io/edeuxk/pen/BXRKwW" target="_blank">https://codepen.io/edeuxk/pen/BXRKwW</a>

**Comment by KaelWD** [comment] 2019-07-31 01:01
Duplicate of #7470

**Closed by KaelWD** 2019-07-31 01:01 UTC
Labels: C: VStepper, C: VTextField, P: low, T: bug

**Comment by edeuxk** [comment] 2019-07-31 05:17
@KaelWD I tried your solution for the past 2 hours and my conclusion is that it can not be a fix for a v-stepper.

If I change my icon from "prepend-inner-icon" to "append-icon" it works perfectly.
Or if I remove my icon, it works perfectly too.

I tried the :key solution, but it only works for the 1st step-content and not the others steps.

**Comment by wendelicious** [comment] 2019-12-12 06:35
still does this with a outlined text input with a label and prepend inner icon.  I don't use prepend inner icon anymore.

**Comment by tmcdos** [comment] 2021-04-10 12:21
The problem arises when the icon comes from a webfont - the width of the "prepend-inner" slot is calculated in `vuetify/lib/components/VTextField/VTextField.js` at function `setPrependWidth()`. But this function is called before the browser has completed loading the webfont - so we get wrong width which is not updated unless the browser window is resized.
To fix the issue, `prependWidth` should be converted to a computed property:
```javascript
computed:
{
      prependWidth() {
      if (this.$el && this.outlined)
      {
        const prepend = this.$el.querySelector('.v-input__prepend-inner');
        if (prepend) return prepend.offsetWidth;
      }
      return 0;
    },
  .....
}
```
and the body of the original `setPrependWidth()` function should be commented out.
The patch is attached.
[vuetify#2.4.6.patch.txt](https://github.com/vuetifyjs/vuetify/files/6289817/vuetify.2.4.6.patch.txt)
