### ISSUE TITLE
[Feature Request] error happened using vuetify3 in electron

### ISSUE THREAD

**Issue by git4sum** [vuetifyjs/vuetify#14596] opened 2022-01-13 03:17 UTC
### Problem to solve
Actually this link isn't very related to my problem. It's unnecessary to access it.

The problem is that I cannot use vuetify3 in electron(v13.6.7).

When I try to do electron-build, I get the error "Unknown node type in node creation" at these files below.
 - VBtn.css
 - VExpansionPanel.css
 - VCard.css
 - VListItem.css
What they have in common is that they use the "selector(:focus-visible)".

And as far as I found, to use "selector(:focus-visible)" then I have to install "autoprefixer" version above 10.2.5, but the latest vue@cli (v4.5.0) uses "autoprefixer@9.8.0".
So my question is that is there other way to use vuetify3 without the element "selector(:focus-visible)"?
Thank you.

### Proposed solution
way to use vuetify3

**Comment by KaelWD** [comment] 2022-01-13 06:49
Duplicate of #14179

The most recent version of vue-cli is 5.0.0-rc.1 which uses autoprefixer 10.

**Closed by KaelWD** 2022-01-13 06:49 UTC
Labels: S: triage
