### ISSUE TITLE
[Bug Report][3.6.13] Vuetify treeview component doesn't show icons for items with children

### ISSUE THREAD

**Issue by liulysk** [vuetifyjs/vuetify#20222] opened 2024-07-25 06:56 UTC
### Environment
**Vuetify Version:** 3.6.13
**Vue Version:** 3.5.0-alpha.4
**Browsers:** Chrome 126.0.0.0
**OS:** Windows 10

### Steps to reproduce
        {
          title: 'node_modules',
          file: 'png',
        },
        {
          title: 'public',
          file: 'png',
          children: [
            {
              title: 'static',
              children: [
                {
                  title: 'logo.png',
                  file: 'png',
                },
              ],
            },
            {
              title: 'favicon.ico',
              file: 'png',
            },
            {
              title: 'index.html',
              file: 'html',
            },
          ],
        }

### Expected Behavior
Icons are visible next to item with children items

### Actual Behavior
Example in vuetify playground doesn't show default "folder" icon 

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtVVFv2jAQ/iteXtJK2GzquoeIMlVaH6dJewU0mdgJLo4dJQ4FIf77zoYkNg1jSM0D2N99993Zd5fM9lFdpePnsiSbhkdJNDG8KCU1fDpXCE022FScbwR/s1uENrjQjMuneWTxeXREEwFeNYDuv0N1yRVnFlbCCCrl7hcgrdly8ZrvwK5o0WnR1IgNNXQp+RGwKlgrnEqRri3kMoPc2kwhqVpqk5QVB6qNt3fiI+eKDvPo5OHOI1KtwENkwPtkaSQTEKrnILTfHz2/o7hgAmdaMl5hC8Uo8bEYHQ6d9PioPRCLy5pPraqNVM+6oAtwP/ebjMMCgLWtAACBFbZ1WonSOCbflroyiPGMNtKg/VGOwU0m6O4ePU3R3QmDq/frkaBZXDZLuN14MWoZLtOkVbHPyhTydHhJVd7QnGOLPcadE0Kv4OMoCrrktQ5NGkI5YwpGbPe+vWDn6gWt1ky/BaySZW0FIEMMW7zU24Chcp8hCpDy7WZrfDvTaVNwZbBujBQqoG5lexxH5duUy95+6Fa2QHCL/e25MQDEa6l+CXxhJDjEJBfGj9crXnCwt/oHBrCB4tzkeKqvR0MoXQnJKld/Hz5T8FVqQ825yj+VBtV8RalzTaBi7zXbJrTJD9v9Qx+fvgDDjIsHy+jGjiCBn/eRLmfx3/pCMb4ldlouyg8ZQ33/dFcLbltL5EpXQUN30WAIbuqfJV1ySeCKMpGTcK47zRC+3pI0XcNoglr4HvD0QsNVxd8vzz9+vpCCDcqF8FUx+Bp+7Hl3tFJE6nR9W0Haqh/u3QI+N5Nx99aPDqPogTySz5jKckXJ18juv5EvD9HiLyxsGwU=)

### Other comments
Supposed to be fixed in release: 3.6.9, https://github.com/vuetifyjs/vuetify/issues/20009

**Comment by KaelWD** [comment] 2024-07-25 06:59
Duplicate of #20009

![Screenshot_20240725_165918](https://github.com/user-attachments/assets/05182df3-0632-4f89-9a3b-44348cd1827d)

**Closed by KaelWD** 2024-07-25 06:59 UTC
Labels: duplicate, S: triage
