### ISSUE TITLE
[Bug Report] VOverflowBtn prepend-inner-button problematic alignment

### ISSUE THREAD

**Issue by Tzahile** [vuetifyjs/vuetify#9449] opened 2019-10-24 07:01 UTC
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
Create a segmented overflow-btn (simply take [this](https://vuetifyjs.com/en/components/buttons#button-dropdown-variants) example by vuetify into codepen).
Add a prepend-inner-icon prop to it

### Expected Behavior
Everything should be aligned together (by default to the center)

### Actual Behavior
The prepended inner icon is not aligned with the rest of the button (label and caret)

### Reproduction Link
<a href="https://codepen.io/Tzahile/pen/jOOmPPW?editors=1011" target="_blank">https://codepen.io/Tzahile/pen/jOOmPPW?editors=1011</a>

**Comment by johnleider** [comment] 2020-01-14 01:25
Duplicate of #9448

**Closed by johnleider** 2020-01-14 01:25 UTC
Labels: C: VOverflowBtn, P: low, T: bug
