### ISSUE TITLE
[Documentation] No testing docs for v3 and the Vue Test Utils

### ISSUE THREAD

**Issue by gabaum10** [vuetifyjs/vuetify#17684] opened 2023-06-23 14:36 UTC
### Environment

**Browsers:** Chrome 113.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
The link above doesn't have a comparable page for Vuetify v3.  We're having tremendous difficulty getting Vuetify 3 to play nicely with the Vue Test Utils V3, which is unfortunately necessary for Vue 3.  VTU3 no longer exposes the global Vue instance so the old bootstrapping method is no longer appropriate.  

I have attempted to use the new `global.config.plugins` to define the Vuetify instance, but for some reason that isn't working correctly.  None of the components are registering.  Some first party documentation working with VTU3/Vuetify 3 would go a long way to easing that pain.

Here is some migration documentation related to installing plugins.  https://test-utils.vuejs.org/migration/#no-more-createlocalvue

### Expected Behavior
Docs for using Vuetify 3, Vue 3 and Vue Test Utils.  Or really any unit testing docs in general.

### Actual Behavior
No docs exist.

### Reproduction Link
[https://v2.vuetifyjs.com/en/getting-started/unit-testing/#test-runners](https://v2.vuetifyjs.com/en/getting-started/unit-testing/#test-runners)

**Comment by illuminate3** [comment] 2023-08-09 22:04
Is there any dates to as when this might be cleared?

**Comment by KaelWD** [comment] 2023-08-10 07:49
Duplicate of #14749

**Closed by KaelWD** 2023-08-10 07:49 UTC
Labels: S: triage
