### ISSUE TITLE
[Feature Request] Body.append in VDataTable Vuetify3

### ISSUE THREAD

**Issue by Wwwolfgang** [vuetifyjs/vuetify#17553] opened 2023-06-07 13:23 UTC
### Problem to solve
In Vuetify 2 we had a body.append slot in the v-data-table component. Are there plans to add this slot in Vuetify 3?

### Proposed solution
Just add the slot ;-)

**Comment by corradopetrelli** [comment] 2023-08-01 14:22
+1

**Comment by KaelWD** [comment] 2023-11-03 12:23
Duplicate of #17128

**Closed by KaelWD** 2023-11-03 12:23 UTC
Labels: S: triage
