### ISSUE TITLE
[Bug Report] x-small property for v-ratings is broken (or mistakenly included in docs)

### ISSUE THREAD

**Issue by xon52** [vuetifyjs/vuetify#9356] opened 2019-10-15 08:00 UTC
### Environment
**Vuetify Version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
Try: `<v-rating v-model="rating" x-small></v-rating>`

### Expected Behavior
Icons appearing smaller than using the `x-small` property

### Actual Behavior
Icons appearing same size as when no sizing property is used (default size)

### Reproduction Link
<a href="https://codepen.io/xon5/pen/GRRZdNZ" target="_blank">https://codepen.io/xon5/pen/GRRZdNZ</a>

**Comment by ibrahimBeladi** [comment] 2019-10-15 08:13
Duplicate of #9350.

**Closed** 2019-10-15 10:53 UTC
Labels: triage
