### ISSUE TITLE
[Bug Report] v-list-tile-sub-title no longer truncating in 1.0.7

### ISSUE THREAD

**Issue by scp-nm** [vuetifyjs/vuetify#3569] opened 2018-03-14 10:43 UTC
### Versions and Environment
**Vuetify:** 1.0.7
**Vue:** 2.5.14
**Browsers:** Chrome 65.0.3325.146
**OS:** Mac OS 10.13.3

### Steps to reproduce
Create a `v-list` that contains a `v-list-tile-sub-title` with long content, the truncation no longer happens on the `v-list-tile-sub-title`.

### Expected Behavior
The long text should be truncated

### Actual Behavior
The long text is forcing the width of the list to expand

### Reproduction Link
[https://codepen.io/scp-nm/pen/XEXGZr](https://codepen.io/scp-nm/pen/XEXGZr)

### Other comments
Here's a link to the same code using 1.0.6 - https://codepen.io/scp-nm/pen/MVKxQR

**Comment by KaelWD** [comment] 2018-03-14 10:56
Duplicate of #3563

**Closed by KaelWD** 2018-03-14 10:56 UTC
