### ISSUE TITLE
[Bug Report] Can't set null to TimePicker, always reset to current time (beta.5)

### ISSUE THREAD

**Issue by AlexKovynev** [vuetifyjs/vuetify#3093] opened 2018-01-24 14:22 UTC
Versions and Environment

Vuetify: 1.0.0-beta.5
Vue: 2.5.13
Browsers: Chrome 63.0.3239.132
OS: Ubuntu

Maybe change

return this.inputHour == null ? this.firstAllowed('hour', new Date().getHours()) : this.inputHour

to something like 

return (this.allowedHours && this.inputHour == null) ? this.firstAllowed('hour', new Date().getHours()) : this.inputHour

and minutes also.

**Comment by jacekkarczmarczyk** [comment] 2018-01-24 14:25
Duplicate of #2616

**Closed by jacekkarczmarczyk** 2018-01-24 14:25 UTC
