### ISSUE TITLE
[Bug Report][3.7.2] VSelect overlay shift to right when no padding for parent container

### ISSUE THREAD

**Issue by abumalekFayed** [vuetifyjs/vuetify#20507] opened 2024-09-20 21:38 UTC
### Environment
**Vuetify Version:** 3.7.2
**Vue Version:** 3.5.7
**Browsers:** Chrome 128.0.0.0
**OS:** Windows 10

### Steps to reproduce
when remove padding from parent container of v-select component the menu open with shift to right side 

### Expected Behavior
v-select menu should be opened in correct position

### Actual Behavior
v-select menu  opened with shift to right side

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrVksFOwzAMhl/FyqWXQhHHqlRCk+ABQOKw7hAab7OUxiFJu02Idydp13YXHoBDkj+xld/+5O238K4tnq29H3oUpagCdlbLgHVjAKrhTlo7ynhRNFxlvFjw4aLxqREta3YlOFSNWOIAJwpH4D6AlQ5NOpQic4AOTQ9s0UwZ/kj7AIFBYzw9KVwsitl5LMSjxjas/2v5iTrav03vYo2UFJvwMbTNNlLTnp0hmeWQbVKlUnHSL1GSGp9fkd1hynjHs/RJfFy4i9VmeXaKC+NK+ivbrUZ1VcxVzYSKCdHKa4F07b6Exwd7vuFU2XrE8CckMtCyc9EELHsKxGYC8z/RJDUPVVXcDJv4yU2v9bjtfgFJCstH)

**Comment by KaelWD** [comment] 2024-09-21 07:13
Duplicate of #19732

**Closed by KaelWD** 2024-09-21 07:13 UTC
Labels: S: triage
