### ISSUE TITLE
[Bug Report] v-toolbar CSS overrides v-btn size

### ISSUE THREAD

**Issue by HeadAdmiral** [vuetifyjs/vuetify#8145] opened 2019-07-29 13:13 UTC
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
Put a v-btn inside of a v-toolbar and compare it's size when to a v-btn outside of a toolbar

### Expected Behavior
v-btn size props should not be overridden by other components

### Actual Behavior
If a v-btn is nested inside of a v-toolbar, the v-toolbar's CSS will set the height and width of the v-btn to 48px regardless of if the v-btn has size props applied to it.

### Reproduction Link
<a href="https://codepen.io/anon/pen/gVgBXx" target="_blank">https://codepen.io/anon/pen/gVgBXx</a>

**Comment by jacekkarczmarczyk** [comment] 2019-07-30 21:45
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8035

**Closed by jacekkarczmarczyk** 2019-07-30 21:45 UTC
Labels: triage
