### ISSUE TITLE
[Bug Report][3.0.0-beta.14] intelisense missing in beta.14

### ISSUE THREAD

**Issue by LeaderbotX400** [vuetifyjs/vuetify#15966] opened 2022-10-24 23:19 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Last working version:** 3.0.0-beta.13
**Vue Version:** 3.2.41
**Browsers:** Edge 106.0.1370.52
**OS:** Windows 10

### Steps to reproduce
1. Install the latest version of vuetify
2. Check any component

### Expected Behavior
Intellisense should show up when you hover over components

### Actual Behavior
No intellisense appears

### Reproduction Link
[https://github.com/LeaderbotX400/vuetify-intelisense-missing](https://github.com/LeaderbotX400/vuetify-intelisense-missing)

**Comment by KaelWD** [comment] 2022-10-25 02:37
Duplicate of #15942

**Closed by KaelWD** 2022-10-25 02:37 UTC
Labels: S: triage
