### ISSUE TITLE
[Bug Report] Column filters in v-data-table do not work

### ISSUE THREAD

**Issue by zeroinformatique** [vuetifyjs/vuetify#12136] opened 2020-08-28 14:18 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.135
**OS:** Windows 10

### Steps to reproduce
- Type "you" in the search bar, it will find the second record based on column B's filter lambda.
- Type "ello", it won't find the first record because column A doesn't have a custom filter defined.
- Remove the attribute ":custom-filter" in the datatable, nothing works anymore.

### Expected Behavior
- Filters should be an override of the default search system. If you don't define them, they should work with the native datatable algorithm and return all the results matching your search, in an union.
- You shouldn't have to redefine the global ":custom-filter" attribute to have column's dedicated filters to work. Column filters should just be a way to teach Vuetify how to search in complex fields (ie. slots).
- You shouldn't have to redefine all column's filters if you use a single one; currently this is the case: add one filter column, and it breaks the whole system.

### Actual Behavior
- The filters seems to be an intersection between the global ":custom-filter" and each column's filter.
- If at least one column filter is defined, it breaks the other columns.
- If one column filter is defined but no global ":custom-filter" is defined, the behavior is totally unpredicable since it generates an intersection between the standard global filter and the defined column filters (this should be an union).

### Reproduction Link
<a href="https://codepen.io/OzoneGrif/pen/ExKXxRd" target="_blank">https://codepen.io/OzoneGrif/pen/ExKXxRd</a>

### Other comments
How I see the filter system:
- ":custom-filter" is a pre-pass, it's used to globally limit the number of results based on an algorithm using the whole record. Column filters are applied after this one.
then for each column:
- if a column filter is defined: use it to decide if yes or no the row should be returned. A single "true" in any column is enough to display the row.
- if a column filter is **not** defined: use the default Vuetify filter instead
- if a column filter is "false" instead of a function: ignore this column (similar to a function ()=>false)

On a side note, I don't understand why the filter is called when the search variable is undefined, null or empty. If there's no filter, you shouldn't call the filter functions at all (?)

**Comment by KaelWD** [comment] 2021-10-10 14:56
Duplicate of #11600

**Closed by KaelWD** 2021-10-10 14:56 UTC
Labels: T: bug, C: VDataTable
