### ISSUE TITLE
[Bug Report] V-Select - Label text doesn't show if it is set by slot and the style is "filled"

### ISSUE THREAD

**Issue by Pnem** [vuetifyjs/vuetify#12262] opened 2020-09-21 14:42 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 85.0.4183.102
**OS:** Windows 10

### Steps to reproduce
Set the label text on the V-Select component to "filled" and use the "v-slot:label" for setting the label text.

### Expected Behavior
The label text should show.

### Actual Behavior
The label text doesn't show.

### Reproduction Link
<a href="https://codepen.io/hjmd/pen/XWdyzxp" target="_blank">https://codepen.io/hjmd/pen/XWdyzxp</a>

**Comment by jacekkarczmarczyk** [comment] 2020-09-21 14:43
Duplicate of https://github.com/vuetifyjs/vuetify/issues/11533

**Closed by jacekkarczmarczyk** 2020-09-21 14:43 UTC
Labels: triage
