### ISSUE TITLE
[Documentation] Tooltips help page Usage section incorrectly states support for all components

### ISSUE THREAD

**Issue by lukasrossa** [vuetifyjs/vuetify#9752] opened 2019-11-21 10:26 UTC
### Environment

**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Go to: https://vuetifyjs.com/en/components/tooltips#usage

It says 'Tooltips can wrap any element.'

### Expected Behavior
Only some components support tooltips as per https://github.com/vuetifyjs/vuetify/issues/8647 .
The documentation should make it explicit which are supported.
Working examples of the supported ones should be provided.

### Actual Behavior
The documentation is incorrect / misleading.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/tooltips#usage" target="_blank">https://vuetifyjs.com/en/components/tooltips#usage</a>

**Comment by johnleider** [comment] 2020-01-16 16:55
Duplicate of #8647

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-16 16:55 UTC
Labels: triage
