### ISSUE TITLE
title class conflicts with my app's css

### ISSUE THREAD

**Issue by daviesdoclc** [vuetifyjs/vuetify#6356] opened 2019-02-04 20:04 UTC
### Versions and Environment
**Vuetify:** 1.4.4
**Vue:** 2.5.22
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
There was an old issue addressing this https://github.com/vuetifyjs/vuetify/issues/980.  It's closed and it was mentioned the classes with general names (like title, container, etc.) were renamed.  However I'm still having a conflict.  I had to rename all my title classes to _title for now.  Did I miss something or is this still an issue?  Is it agreeable that these names should be made less general so the chance of conflict is less?  (maybe md-title or something)

### Expected Behavior
css classes in Vuetify should be renamed to prevent conflict

### Actual Behavior
Some css classes have too general of names.

### Reproduction Link
<a href="https://codepen.io/funkyvisions/live/OdgqQE" target="_blank">https://codepen.io/funkyvisions/live/OdgqQE</a>

**Comment by johnleider** [comment] 2019-02-04 20:24
This will happen in v2.0 with the typography updates.

**Comment by johnleider** [comment] 2019-06-19 20:33
Duplicate of #5041

**Closed by johnleider** 2019-06-19 20:33 UTC
Labels: T: enhancement
