### ISSUE TITLE
[Bug Report][3.1.10] VSelect in VDialog component, options are flickered when first time clicked on VSelect

### ISSUE THREAD

**Issue by DeepKumbhare85** [vuetifyjs/vuetify#16960] opened 2023-03-20 13:24 UTC
### Environment
**Vuetify Version:** 3.1.10
**Vue Version:** 3.2.47
**Browsers:** Chrome 111.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Open the playground link given in issue
2. Scroll down to end, you will find a button "Open Dialog".Click on the button and this will open a dialog
3. In dialog, try opening the city list from VSelect component and you will find that first time options are not shown. 

### Expected Behavior
VSelect component should show options every time when clicked on the component

### Actual Behavior
When first time clicked on VSelect component, options are flickered. on second time onwards, mostly it works properly.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVclu2zwQfpWBLmoAW0r+FPgB1zbS5VKgRVG06CXKYSyOY9YUyZKU2sDwu3eoJV7k9lD5IHG+4SzfLL7fJa+tzZqakllS6HmgyioMtCw0wLyZorXtZ3uoUGo+9WchGygVer8okkC/wrQkHcgVSX+BVezw1UzXxrGeBKnh5vq6YF8dMtvSUwQGyfPlD8ZRBdL6ugJhlHHgZQCsKEBptKcyUKgdoJBWellK/QikZMjgc20E/KilB7NeM4BgnWmk4OgAlWREQGNUbQPn6YGcY9sWncRoz6OVMY/OJ1U/app0XjnTuiItMAaF1cFGBh/xUbMEa6YPhCwDHrQn4MgNObA/R2XtkQF69pX1jOYD1wDnb2Z/FXrm41NGa8ybdbJC93Tg89kCwCdLGt5JVObxIJx/6ySAZZANhs4KOo6jSLhOlRGkFqlolVL4KUXYLFLOzKRHpqOdt+jEiWgQfuVmWLbkAfXlY4alDqZPdHiKMP/2hRSXEhSuottShqcUZpJ59Iu0fZ267Xjqb42Q83OM6E3QY7ZObr4emDjN7yPp+iJLo6Q/SD+OpRO/5xTGUQ3j8CJmOGFqBP26iqNxn/LAKUonkK5Q8y9+lRvu0af04VDkwzOMT7RwEW9Q1fRnjVHYx4F/lUHRcreDGCbs90z8KXShMoPCOUkdctpCecvxkYwlXK7x1eeuutRusXy8EM6w2Fux9HelkuWWCeg6erFG5Ylr+FYZT3/zd8lsD51G3M3T8jCqeTurw9rMeU8eliZj/RbtDt1+nedHe5ePvnTSBvC84SIsK2tcgB3vjjXsYe1MBSmv7DQqx2UYeOm02UWNF22KV68GqJ0i6CDur01FAlco0knqa4eB3w0KI9Bxs6UOv29NSB+uYlBdGMtkknQRcOg2++6N5v+KXcyA26oFfJHMoJVEGUcWz0WyCcH6WZ7X2m4fs9JU+R1juat1kBVNhanubrPb7HqKym4we8lU+XAMZ+Sr6cqZn54cOy6SyZGPINc8yZf99DCbv8lurju7vWzKq8ZHwyODOXtpyE15ygXx0v5rEme6lxI5UxklE13vC71nfpXUW39GbelbWu+HCP8hy9ZEvP8Q3ewnyW32X/byf3bYXUkefgMdYm8r)

**Comment by KaelWD** [comment] 2023-03-21 05:59
Duplicate of #16770

**Closed by KaelWD** 2023-03-21 05:59 UTC
Labels: S: triage
