### ISSUE TITLE
[Bug Report] Button stays in hover state after being pressed on mobile device

### ISSUE THREAD

**Issue by WIStudent** [vuetifyjs/vuetify#6497] opened 2019-02-14 09:07 UTC
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Safari / Chrome for Android 72.0.3626.105
**OS:** iOS 12.1 / Android 8.1.0

### Steps to reproduce
Press the regular button or the toolbar button on a mobil device

### Expected Behavior
After pressing the button is done, it should have the same state/color as before pressing it.

### Actual Behavior
After the button was pressed, it stays in the hover state until I press somewhere else on the page.

### Reproduction Link
<a href="https://codepen.io/wistudent/pen/JxBmje" target="_blank">https://codepen.io/wistudent/pen/JxBmje</a>

**Comment by WIStudent** [comment] 2019-02-14 13:50
Update: Also happens in Chrome on Android

**Comment by WIStudent** [comment] 2019-02-14 13:58
I think this CSS rule is causing the issue:
```
.v-btn:hover:before {
  background-color: currentColor;
```
When I remove this rule, then the button will no longer get stuck in the hover state on mobile devices. But just removing it then breaks the hover effect on desktop.

**Comment by sh7dm** [comment] 2019-02-14 14:26
it's browser issue. virtual "pointer" move on touch and it's default JS behavior.

**Comment by KaelWD** [comment] 2019-02-14 14:45
Duplicate of #2178

**Closed by KaelWD** 2019-02-14 14:45 UTC
Labels: duplicate, platform specific, working as intended
