### ISSUE TITLE
[Bug Report][3.0.2] Problem switching from permanent to temporary v-navigation-drawer

### ISSUE THREAD

**Issue by norx85** [vuetifyjs/vuetify#16147] opened 2022-11-23 08:59 UTC
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Firefox 107.0
**OS:** Windows

### Steps to reproduce
1) Make a v-navigation-drawer that switch between permanent and temporary behavior, based on display breakpoints: permanent on large display and temporary on small display.
2) Resize the browser window to a small width

### Expected Behavior
The navigation drawer become temporary, and is either open or closed based on v-model value, without an overlay over application if closed.

### Actual Behavior
The navigation drawer disappear, but an overlay over the whole application remains, making it unusable.

### Reproduction Link
[https://codepen.io/norx85/pen/XWYEXMy](https://codepen.io/norx85/pen/XWYEXMy)

**Comment by KaelWD** [comment] 2022-11-23 09:58
Duplicate of #15807

**Closed by KaelWD** 2022-11-23 09:58 UTC
Labels: S: triage
