### ISSUE TITLE
[Feature Request] Select a range of rows in data table

### ISSUE THREAD

**Issue by florealcab** [vuetifyjs/vuetify#10686] opened 2020-02-27 14:58 UTC
### Problem to solve
Click to select a row. Press shift and click another row. All rows between should be selected too.

### Proposed solution
Click to select a row. Press shift and click another row. All rows between should be selected too

**Comment by nekosaur** [comment] 2020-02-27 16:00
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9958

**Closed by nekosaur** 2020-02-27 16:00 UTC
Labels: duplicate
