### ISSUE TITLE
[Bug Report][3.0.0-beta.10] `v-file-input`'s label and text alignment not proper in outlined variant

### ISSUE THREAD

**Issue by alokVishu** [vuetifyjs/vuetify#15729] opened 2022-09-02 05:31 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Vue Version:** 3.2.38
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
Try to use outlined `variant` of `file-input`

### Expected Behavior
the text and label should be properly aligned same as other components

### Actual Behavior
label and text are not aligned and it aligns to the bottom.

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/yLjLOmQ?editors=101" target="_blank">https://codepen.io/Alokdev/pen/yLjLOmQ?editors=101</a>

**Comment by KaelWD** [comment] 2022-09-05 10:23
Duplicate of #15484

**Closed by KaelWD** 2022-09-05 10:23 UTC
Labels: S: triage
