### ISSUE TITLE
[Bug Report] Cannot read property 'contains' of undefined (in VMenu.js closeConditional)

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#6976] opened 2019-04-12 10:04 UTC
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Mac OS 10.14.3

### Steps to reproduce
Click on the first button, then click on the second button

### Expected Behavior
No error in the console

### Actual Behavior
Error in the console: 
Uncaught TypeError: Cannot read property 'contains' of undefined at VueComponent.closeConditional

### Reproduction Link
<a href="https://codepen.io/everhardt/pen/rbwKGG?editors=1010" target="_blank">https://codepen.io/everhardt/pen/rbwKGG?editors=1010</a>

### Other comments
The issue is in https://github.com/vuetifyjs/vuetify/blob/0160a40220a754a5cd1b72620a085bbadbcbf1e8/packages/vuetify/src/components/VMenu/VMenu.js#L203

this.$refs.content is undefined when closeConditional is called

**Comment by everttrollip** [comment] 2019-04-18 14:07
Just to confirm, I am experiencing the same bug.

**Comment by ajorquera** [comment] 2019-04-23 12:30
+1

**Comment by jinuem** [comment] 2019-04-24 15:01
+1  Same Issue

**Comment by nekosaur** [comment] 2019-04-24 15:11
Please just use the thumbs up if you have nothing else to contribute to the issue.

**Comment by jinuem** [comment] 2019-06-06 05:38
Any fixes yet?

**Comment by mayank-shaan** [comment] 2019-06-07 08:55
+1

**Comment by mojodev** [comment] 2019-07-02 14:58
**Temporary solution:**
Just replace 
`if (_this2.$refs.content.contains(e.relatedTarget)) return;`

with this snippet
`if (_this2.$refs.content && _this2.$refs.content.contains(e.relatedTarget)) return;`

in VMenu.js

full code snippet:
```
mouseLeaveHandler: function mouseLeaveHandler(e) {
      var _this2 = this;
      this.runDelay('close', function () {
        if (_this2.$refs.content && _this2.$refs.content.contains(e.relatedTarget)) return;
        requestAnimationFrame(function () {
          _this2.isActive = false;
          _this2.callDeactivate();
        });
      });
    }

```

**Comment by shadow-light** [comment] 2019-07-31 05:27
This still affects Vuetify 2.0.1. It is especially an issue with Vue router as if the user opens a menu and then moves to a different route before closing it, this error occurs.

**Comment by shadow-light** [comment] 2019-07-31 05:58
The previous reproduction example doesn't appear to work anymore. [So here's a new one](https://codepen.io/anon/pen/GVmmYN)

**Comment by evgmel** [comment] 2019-08-01 14:11
This bug can be reproduced on the VuetifyJS site. These are the steps to reproduce an error:
1) [Open a page](https://vuetifyjs.com/en/components/menus) where `v-menu` component is described;
2) Click on any menu button to open a menu (for today most of the buttons contains DROPDOWN text) and leave the menu opened;
3) Click/Choose another page at the left sidebar so that `vue-router` changed the contents of the page (e.g. open _Lists_ page).
4) The error occurred at DevTools console: 

> **Uncaught TypeError: Cannot read property 'contains' of undefined**

**Comment by KaelWD** [comment] 2019-08-12 06:44
This is caused by the `setTimeout(..., 0)` in ClickOutside meaning the callback is fired after destruction: https://github.com/vuetifyjs/vuetify/blob/d912f825bc510ebc54bc54d9b5fe70a6208e3f48/packages/vuetify/src/directives/click-outside/index.ts#L50-L52

**Closed** 2019-08-12 19:48 UTC
Labels: C: VMenu, T: bug, lts

**Comment by rohrii** [comment] 2023-04-28 21:00
This issue is happening to me again in newest Version.
