### ISSUE TITLE
[Bug Report] Breakpoint xs won't work

### ISSUE THREAD

**Issue by washanhanzi** [vuetifyjs/vuetify#9592] opened 2019-11-06 09:03 UTC
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
1. Change screen size

### Expected Behavior
follow the
```
xs='6'
```
class

### Actual Behavior
not working

### Reproduction Link
<a href="https://codepen.io/washanhanzi/pen/QWWmVWX" target="_blank">https://codepen.io/washanhanzi/pen/QWWmVWX</a>

### Other comments
the
```
xs='6'
```
class won't compile to the right class like other breakpoints

**Comment by jacekkarczmarczyk** [comment] 2019-11-06 09:14
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8997

**Closed by jacekkarczmarczyk** 2019-11-06 09:14 UTC
Labels: triage
