### ISSUE TITLE
[Bug Report] v-file-input not displaying name of added files, not updating v-model and not triggering change event

### ISSUE THREAD

**Issue by JDClementi** [vuetifyjs/vuetify#11382] opened 2020-05-12 21:18 UTC
### Environment
**Vuetify Version:** 2.3.0-beta.3
**Vue Version:** 2.6.11
**Browsers:** Safari, Google Chrome
**OS:** iOS

### Steps to reproduce
Click the file input and select one or more photos

### Expected Behavior
See the name of the files and have them in the related model

### Actual Behavior
Name is not displayed, related model is not updated and change event not triggered

### Reproduction Link
<a href="https://codepen.io/jdclementi/pen/gOajabM" target="_blank">https://codepen.io/jdclementi/pen/gOajabM</a>

### Other comments
I know it sounds weird but it happens really often, sometimes allways.

It happens also in the documentation page: https://vuetifyjs.com/en/components/file-inputs/#file-inputs

I don't know what's related

**Comment by MajesticPotatoe** [comment] 2020-05-12 21:50
duplicate of #10832

**Closed by MajesticPotatoe** 2020-05-12 21:50 UTC
Labels: triage
