### ISSUE TITLE
[Bug Report] Height misclick on multiple <v-checkbox> when height = 1  

### ISSUE THREAD

**Issue by mjrc** [vuetifyjs/vuetify#5011] opened 2018-09-01 12:39 UTC
### Versions and Environment
**Vuetify:** 1.2.1
**Vue:** 2.5.17
**Browsers:** Chrome 68.0.3440.106
**OS:** Mac OS 10.12.6

### Steps to reproduce
Position the mouse pointer exactly between two checkboxes and click, or try checking a checkbox by clicking in the lower half of a checkbox. 

### Expected Behavior
One would expect the checkbox to be checked where the mouse pointer is, i.e the tip of the arrow or the end of the index finger if the icon is a hand. This also happens in HTML checkboxes. 

### Actual Behavior
The checkbox to the bottom of the mouse pointer is selected. Either because the checkbox seems to correspond to the center of the mouse index, or the surface area of the checkbox is too large and overlaps other check box areas since it does not scale when heigh values lower. This also happens on other low value heights. I suspect the latter one to be the issue, as checkboxes can also be checked when clicking slightly outside of the checkbox. 

### Reproduction Link
[https://codepen.io/anon/pen/EeWKKo](https://codepen.io/anon/pen/EeWKKo)

**Comment by KaelWD** [comment] 2018-09-01 12:42
Duplicate of #2661

**Closed by KaelWD** 2018-09-01 12:42 UTC
