### ISSUE TITLE
[Bug Report] .lazy modifier does not apply to v-text-field

### ISSUE THREAD

**Issue by bhaeussermann** [vuetifyjs/vuetify#12894] opened 2021-01-05 07:35 UTC
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.11
**Browsers:** Firefox 84.0
**OS:** Windows 10

### Steps to reproduce
See the codepen. Bind a property to a v-text-field like so:
```
<v-text-field v-model.lazy="text"></v-text-field>
```

### Expected Behavior
Like the &lt;input&gt; in the codepen, typed-in changes apply only when pressing Enter or when the element is blurred.

### Actual Behavior
Changes apply as you type.

### Reproduction Link
<a href="https://codepen.io/bernhardgh/pen/PoGemoR" target="_blank">https://codepen.io/bernhardgh/pen/PoGemoR</a>

**Comment by KaelWD** [comment] 2021-01-05 07:43
Duplicate of #5759

**Closed by KaelWD** 2021-01-05 07:43 UTC
Labels: triage
