### ISSUE TITLE
[Bug Report] v-chip/v-chip-group layout issue (no scroll, no ellipse)

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#8404] opened 2019-08-08 19:49 UTC
### Environment
**Vuetify Version:** 2.0.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Windows 10

### Steps to reproduce
Look at chips

### Expected Behavior
The long chip with "tech" inside it, should look better, probably stay in 1 line and put elipses.

The chip under that one is 1 giant word, it should cause a horizontal scroll bar on the chip group. There is close icons on the chip and you can't see the close icon on this chip.

### Actual Behavior
Chip gets clipped, and text wraps going outside the chip.

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/bXMYyX" target="_blank">https://codepen.io/sneaky666/pen/bXMYyX</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-08 19:59
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8160

**Closed by jacekkarczmarczyk** 2019-08-08 19:59 UTC
Labels: triage
