### ISSUE TITLE
Tabs-content isn't scrollable correctly on mobile

### ISSUE THREAD

**Issue by BennyAlex** [vuetifyjs/vuetify#2166] opened 2017-10-13 09:37 UTC
### Steps to reproduce
Use tabs on mobile (just tested in chrome debugger) and scroll down to will switch switch to the right tab
### Versions

I upgraded to latest vuetify version
### What is actually happening ?

content will switch to the right tab instead of scrolling down

### Reproduction Link

https://codepen.io/Benny98/pen/LzJNpy
Use mobile view (chrome debugger)

**Comment by jacekkarczmarczyk** [comment] 2017-10-13 09:38
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2125

**Closed by jacekkarczmarczyk** 2017-10-13 09:38 UTC
