### ISSUE TITLE
[Bug Report] v-treeview with selection-type="independent". Last selection drops when loading async children

### ISSUE THREAD

**Issue by temyer** [vuetifyjs/vuetify#11015] opened 2020-04-03 13:31 UTC
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.162
**OS:** Linux x86_64

### Steps to reproduce
1. Create treeview component with selection-type="independent" and with load-children function prop.
2. Select checkbox of loaded node.
3. Click on node with children which are NOT loaded to trigger load-children function.

### Expected Behavior
Selection of last selected node is not changed

### Actual Behavior
Selection of last selected node is changed to opposite value

### Reproduction Link
<a href="https://codepen.io/alp8hrd/pen/NWqVprw?editable=true&editors=101" target="_blank">https://codepen.io/alp8hrd/pen/NWqVprw?editable=true&editors=101</a>

**Comment by alexkleinwaechter** [comment] 2021-01-24 15:27
This is really a very annoying bug. Here is my hacky workaround using a watcher:
`    async loadChildren(item: FileInfo) {
      this.loadedChildren = true;
      const result = await fileService.getDirectory(item.path);
      item.children = result;
      return item;
    }

    @Watch("selectedNodes")
    onSelected(oldVal: Array<FileInfo>, newVal: Array<FileInfo>) {
      if (this.loadedChildren === true) {
        this.loadedChildren = false;
        this.selectedNodes = newVal.concat(oldVal);
      }
    }`

**Comment by skylord220** [comment] 2021-01-25 08:59
Actually it's inherited from previous Vuetify version where "selection-type" didn't exist and can be fixed in sources (sorry, no time for pull request):
```
--- a/src/components/VTreeview/VTreeview.ts     2020-12-18 15:48:29.764067341 +0300
+++ b/src/components/VTreeview/VTreeview.ts     2020-12-18 15:49:56.763438320 +0300
@@ -228,7 +228,7 @@

         this.nodes[key] = node

-        if (children.length) {
+        if (children.length && this.selectionType !== 'independent') {
           const { isSelected, isIndeterminate } = this.calculateState(key, this.nodes)

           node.isSelected = isSelected

```

**Comment by johnleider** [comment] 2021-07-28 23:16
Duplicate of #8791

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-07-28 23:16 UTC
Labels: C: VTreeview, T: bug
