### ISSUE TITLE
V-Text-Field does not emit change event on user interaction

### ISSUE THREAD

**Issue by bjschwa2** [vuetifyjs/vuetify#5007] opened 2018-08-31 20:34 UTC
### Versions and Environment
Vuetify: 1.2.1
Vue: 2.5.17
Browsers: Google Chrome
OS: Linux Ubuntu 16.04

### Steps to reproduce
Click the arrows to the right side of the V-Text-Field.

### Expected Behavior
Change event is emitted (Emitted when the input is changed by user interaction).

### Actual Behavior
No change event is emitted, only input events are emitted.

### Reproduction Link
https://codepen.io/bjschwa2/pen/XPpQpd

**Comment by 185driver** [comment] 2018-09-10 04:42
If I understand the spec correctly, this is intended behavior, rather than a bug.

From MDN [change event](https://developer.mozilla.org/en-US/docs/Web/Events/change)

> It's fired for `<input>`, `<select>`, and `<textarea>` elements when a change to the element's value is committed by the user. Unlike the input event, the change event is not necessarily fired for each change to an element's value.

**Comment by bjschwa2** [comment] 2018-09-10 11:49
@185driver I could be mistaken but take a look at the codepen I provided. I believe the change event should be emitted when a change is committed by the user. This works correctly when enter is pressed. 

I was expecting the arrows to the right to emit a change event as well, since they are also user triggered events.

**Comment by 185driver** [comment] 2018-09-11 09:18
You may be right. It probably depends on the definition of "committed by the user".  If you remove vuetify from the equation and just have vuejs, it works like you mention is the expected behavior above. 

Here's a pen of that for comparison:
https://codepen.io/185driver/pen/wEyLzy

MDN's phrase, "the change event is not necessarily fired for each change to an element's value" doesn't exactly have a definitive ring to it.  Ha. Cheers.

**Comment by jacekkarczmarczyk** [comment] 2018-09-14 15:07
@185driver is right, this is to match html specs

**Closed by jacekkarczmarczyk** 2018-09-14 15:07 UTC
