### ISSUE TITLE
[Bug Report] v-alert text prominent incorrect css for icon opacity

### ISSUE THREAD

**Issue by ndesorden** [vuetifyjs/vuetify#12181] opened 2020-09-04 23:37 UTC
### Environment
**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
**Browsers:** Chrome 85.0.4183.83
**OS:** Mac OS 10.14.6

### Steps to reproduce
Using latest vue-cli (4.5.4) and latest vuetify (2.2.11), and creating a new project with defaults or any custom configuration.

```
<v-alert type="info" text prominent>Bla,bla,bla</v-alert>
```
Opacity around icon doesn't appears.

Rule .v-icon.v-icon::after overwrittes .v-alert--prominent .v-alert__icon:after so:

```
.v-icon.v-icon:after {
    background-color: currentColor;
    border-radius: 50%;
    content: "";
    display: inline-block;
    height: 100%;
    left: 0;
    opacity: 0;
    pointer-events: none;
    position: absolute;
    top: 0;
    transform: scale(1.3);
    width: 100%;
    transition: opacity .2s cubic-bezier(.4,0,.6,1);
}

.v-alert--prominent .v-alert__icon:after {
    background: currentColor!important;
    border-radius: 50%;
    bottom: 0;
    content: "";
    left: 0;
    opacity: .16; <-- overwritten
    position: absolute;
    right: 0;
    top: 0;
}
```

### Expected Behavior
With opacity

### Actual Behavior
Without opacity

### Reproduction Link
<a href="https://codepen.io/ndesorden/pen/QWNOoew" target="_blank">https://codepen.io/ndesorden/pen/QWNOoew</a>

Well, codepen is ok because **with webpack install or cdn everything is ok**. Problem is with vue-cli install

Expected: 
![Captura de pantalla 2020-09-05 a las 1 24 23](https://user-images.githubusercontent.com/5400676/92291307-573b9e80-ef18-11ea-8fd8-b52a48db4751.png)

Current:
![Captura de pantalla 2020-09-05 a las 1 21 53](https://user-images.githubusercontent.com/5400676/92291319-63276080-ef18-11ea-84d4-ec600e3f23db.png)

![Captura de pantalla 2020-09-05 a las 0 54 50](https://user-images.githubusercontent.com/5400676/92291433-e8127a00-ef18-11ea-80b5-18e17c2d942c.png)

**Comment by NabeelAhmed314** [comment] 2020-12-07 05:31
I have tried recreating this issue in latest version of vue-cli but i'm getting the expected behaviour. I think you are using older version of vue-cli because of which you are getting this issue. It has been resolved in latest version. If the issue persists than let us know.

This is snap of code:

![code](https://user-images.githubusercontent.com/43681543/101313007-002aca00-3877-11eb-88c7-0c2ea86cceaa.PNG)
This is the output:

![output](https://user-images.githubusercontent.com/43681543/101313011-015bf700-3877-11eb-84b4-b00f03c78377.PNG)

**Comment by johnleider** [comment] 2020-12-08 19:08
I can't reproduce this, even on the listed version of v2.3.10.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by MajesticPotatoe** [comment] 2021-01-25 22:16
Happens with current version, using new cli install. Only seems to effect cli-installs.
Seems last working version was vuetify 2.2.9. issue can also be seen in docs.
`.v-icon.v-icon:after` is overriding `.v-alert--prominent .v-alert__icon:after`
possible relation to #11294

**Comment by jblachly** [comment] 2021-01-31 00:15
Instead of opening a new issue, I want to comment that I have the opposite problem:

Expected:
No halo

Results:
Halo

In the documentation for v-alert[0], there is **no halo** around the icon. However, when opening this same example in a codepen, the halo is there -- just as it is in my vue-cli installed project.

[0] https://vuetifyjs.com/en/components/alerts/#prominent

**Comment by ndesorden** [comment] 2021-02-18 11:12
@jblachly , i think is not the opposite problem, now documentation is NOT WORKING as expected.
Meanwhile im using this to restore halo:

```
<style lang="scss">
.v-alert--prominent .v-alert__icon {
  &:after {
    opacity: 0.16;
  }
}
</style>
```

**Comment by warmfire540** [comment] 2021-04-19 17:03
so the halo should be there?  I want it to match the docs as they show w/o the halo like @jblachly is saying

**Comment by johnleider** [comment] 2021-04-20 16:19
This is a CSS specificity issue spawned from ordering when built for production.

**Closed** 2021-04-20 16:25 UTC
Labels: C: VAlert, CSS specificity, T: bug
