### ISSUE TITLE
[Feature Request] <v-color-picker> % width not working

### ISSUE THREAD

**Issue by henriq-88** [vuetifyjs/vuetify#7151] opened 2019-05-08 00:50 UTC
### Versions and Environment
**Vuetify:** 2.0.0-beta.0
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Mac OS 10.14.5

### Steps to reproduce
Create a `<v-color-picker>` with `width="100%"`

### Expected Behavior
Canvas stretches to the full width of its parent container

### Actual Behavior
Canvas is set to 100px
Controls are set to full width though

### Reproduction Link
<a href="https://codepen.io/henriq88/pen/PvqXNo?&editable=true&editors=101" target="_blank">https://codepen.io/henriq88/pen/PvqXNo?&editable=true&editors=101</a>

**Comment by henriq-88** [comment] 2019-05-09 00:31
Sorry, didn't know. So should I've reported this on Discord itself?

And to prevent others from making the same mistake as I did, when reporting bugs at https://issues.vuetifyjs.com/, maybe the alpha versions shouldn't be selectable, or a warning should show.

**Comment by ibrahimBeladi** [comment] 2019-05-09 01:51
No. Just close it.
The beta release will be soon. If this bug persists after the beta release, then resubmit it.

**Comment by henriq-88** [comment] 2019-05-29 01:49
Reopening the issue since it still remains in beta.0 version.

**Comment by nekosaur** [comment] 2019-05-29 07:10
This is not a bug, but a limitation of the current implementation. The `<canvas>` element does not allow % widths. The bug part would actually be that the controls are not limited to px as well.

**Comment by sh7dm** [comment] 2019-05-30 18:07
@nekosaur we can calculate %s in JS.

**Comment by nekosaur** [comment] 2019-05-30 19:53
px you mean. I didn't say we couldn't restructure it to allow it, just pointing out that it's not technically a bug.

**Closed** 2023-02-21 11:02 UTC
Labels: T: bug, T: enhancement, C: VColorPicker
