### ISSUE TITLE
[Bug Report][3.1.15] Vuetify and Tailwind CSS bug - outlined field input

### ISSUE THREAD

**Issue by GabrielTrigo** [vuetifyjs/vuetify#17223] opened 2023-04-25 17:03 UTC
### Environment
**Vuetify Version:** 3.1.15
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
Have installed TailwindCSS and Vuetify in the same project.

### Expected Behavior
Bottom edge of input correctly aligned

### Actual Behavior
Bottom edge of input is slightly misaligned

### Reproduction Link
[Code Sandbox](https://codesandbox.io/p/github/GabrielTrigo/vuetify-tailwindcss-outlined-field-input-bug/master?layout=%257B%2522activeFilepath%2522%253A%2522%252FREADME.md%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522fullScreenDevtools%2522%253Afalse%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522vertical%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522DEVTOOLS_PANELS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clgwiezyp0009356l7ivvxqsj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clgwiezyp0009356l7ivvxqsj%2522%253A%257B%2522id%2522%253A%2522clgwiezyp0009356l7ivvxqsj%2522%252C%2522activeTabId%2522%253A%2522clgwifa7y00c3356lnxh80os3%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clgwif8mf007h356loddsmewq%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clgwifa7y00c3356lnxh80os3%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showSidebar%2522%253Atrue%252C%2522showDevtools%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%252C%2522editorPanelSize%2522%253A35.09114583333333%252C%2522devtoolsPanelSize%2522%253A47.825520833333336%257D)

### Other comments
The bottom edge of the outlined input is floating at a certain part

**Comment by websitevirtuoso** [comment] 2023-04-25 21:40
You should fix it with overriding css. current framework can't care about all compatibilities. I think this is obvious

**Comment by KaelWD** [comment] 2023-04-25 22:04
Duplicate of #17220

**Closed by KaelWD** 2023-04-25 22:04 UTC
Labels: S: triage
