### ISSUE TITLE
<v-menu> is not working with SSR

### ISSUE THREAD

**Issue by runetvilum** [vuetifyjs/vuetify#175] opened 2017-02-28 10:41 UTC
I am getting the error window is not defined when trying to use <v-menu> and using server side rendering.

**Comment by iqbalsafian** [comment] 2017-02-28 16:26
may you paste your codes in the v-list?

**Comment by fuzzybook** [comment] 2017-02-28 18:27
emergency trick:
data () {
    return {
      isClient: process.BROWSER_BUILD,

<v-menu bottom left offset-y origin="top right" transition="v-slide-y-transition" v-if="isClient">
      <v-btn icon dark slot="activator">
        <v-icon>more_vert</v-icon>
      </v-btn>
      <v-list>
        <v-list-item v-for="item in dropdown_items">
          <v-list-tile>
            <v-list-tile-title v-text="item"></v-list-tile-title>
          </v-list-tile>
        </v-list-item>
      </v-list>
    </v-menu>
    <div v-else></div>

**Comment by johnleider** [comment] 2017-02-28 18:35
This is a known bug that is being fixed for 0.9.0.

**Comment by smith64fx** [comment] 2017-03-02 16:43
the v-if does not work.. 
Now I have to downgrade to 0.87... :(

**Comment by johnleider** [comment] 2017-03-02 17:15
The issue is due to the window attempting to be accessed on initial load. It is currently fixed in the feature/select branch and will be releasing asap.

A quick workaround:

Create a variable and use it in a v-if on the modal.
In the mounted () lifecycle hook, call ```this.$vuetify.load(() => this.modal = true)```.

**Comment by prograhammer** [comment] 2017-03-03 10:21
This fix is now in `dev` branch. The 0.9.0 release would include it and is due to be released any minute now, most likely in the next day or so.

**Closed** 2017-03-09 01:05 UTC
Labels: bug
