### ISSUE TITLE
[Bug Report][3.0.0-beta.0] VAutocomplete with object datasource broken

### ISSUE THREAD

**Issue by Tomdanizer** [vuetifyjs/vuetify#14905] opened 2022-03-31 15:47 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.31
**Browsers:** Edge 99.0.1150.55
**OS:** Windows 10

### Steps to reproduce
All of the examples with objects for the data source in the beta documentation are broken. 
The dropdown/lookup menu is empty for any autocomplete that is using objects. 
https://next.vuetifyjs.com/en/components/autocompletes/#filter
https://next.vuetifyjs.com/en/components/autocompletes/#slots
https://next.vuetifyjs.com/en/components/autocompletes/#asynchronous-items

### Expected Behavior
Object mapping using item-text / item-value to work and dropdown/lookup menu to populate whether or not using slots.

### Actual Behavior
The dropdown/lookup menu is empty for any autocomplete that is using objects. The item/selection slot does not seem to be getting passed the necessary data.

### Reproduction Link
<a href="https://codepen.io/tomdanizer/pen/BaJwzOy?editors=1010" target="_blank">https://codepen.io/tomdanizer/pen/BaJwzOy?editors=1010</a>

### Other comments
This appears to be the case for nightly and the beta releases

**Comment by KaelWD** [comment] 2022-04-01 08:48
Duplicate of #14783

**Closed by KaelWD** 2022-04-01 08:48 UTC
Labels: S: triage
