### ISSUE TITLE
[Bug Report][3.0.5] v-list-item prepend-icon and prepend alignment issues

### ISSUE THREAD

**Issue by sschaub** [vuetifyjs/vuetify#16287] opened 2022-12-17 18:22 UTC
### Environment
**Vuetify Version:** 3.0.5
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Windows 10

### Steps to reproduce
Alignment looks fine when lines prop is not set on v-list-item.

### Expected Behavior
Prepended icon has a reasonable alignment with respect to the item contents

### Actual Behavior
Prepended icon does not have a reasonable alignment

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9kk1PwzAMhv+KCYeBtDZ8XqaB4AZnDhwIh9F6W6D5kJMOoWn/HaftPtoJcuprO4+d131bi0fv81WNYiKmoSDtIwSMtb9XVhvvKMIaCOewgTk5AyMuHSmrbOFsiGDCAu5S/mz0hFXl4NVRVZ6MzpWdyhbHIBYRja9mEVkBTFfZzKcOwIeFmWnbqUZXOqRrrd5FMs0QqLTFcKdEXBKiEhB1rJD1c0peciDUH9vYS/epxAGNedth4NQTerRlL9001Pw+KFzliDnalnrhBpR0TKmzYokrcjYjvVjGAUe2oH532fNiX7l7496KLrp1iuXOqiRaE3tAMRbt2rjS55/BWV7sOl3gZzSJoMQEmkiK8TqTVmIZow8TKWvrvxZ54Yx84Jyk2kZtMCudebjOr/KbW1nyRIfxHIPJPsh9ByTuqMT4AB71/OevBl2auRd5h+1CCXmEksxfIWXEC0NC+nfuQW1v9kHuaP7Uc6Pshr3kv+0rDGwsQmPh23sq2YxFi+bi5h3i/ReKuA92)

**Comment by KaelWD** [comment] 2022-12-18 01:31
Duplicate of #15764

**Closed by KaelWD** 2022-12-18 01:31 UTC
Labels: S: triage
