### ISSUE TITLE
[Bug Report] Various actions breaking within v-expension-panel

### ISSUE THREAD

**Issue by JollyBrackets** [vuetifyjs/vuetify#5849] opened 2018-12-10 00:03 UTC
### Versions and Environment
**Vuetify:** 1.3.12
**Vue:** 2.5.19
**Browsers:** Chrome 70.0.3538.110
**OS:** Windows 10

### Steps to reproduce
using v-tabs or v-textarea or v-if inside a v-expansion-panel

### Expected Behavior
1. expect v-textarea to resize according to content when setting auto-grow and row-size
2. expect v-tabs to have a slider when used inside v-expansion-panel
3. expect smooth animation when using conditional content with v-if inside a v-expansion panel

### Actual Behavior
1. v-textarea keeps initial row-size when used inside v-expansion-panel
2. v-tabs does not have a slider when used inside v-expansion-panel
3. the animation of v-expansion-panel is jumps

### Reproduction Link
<a href="https://codepen.io/anon/pen/roNdEe?editors=1010" target="_blank">https://codepen.io/anon/pen/roNdEe?editors=1010</a>

### Other comments
I bundled those three issues, because I figured they all might have the same underlying issue.
Something I noticed during testing for this issue: When using v-if on v-tabs and v-textarea inside the v-expansion-panel, issue 1 and 2 go away

**Comment by jacekkarczmarczyk** [comment] 2018-12-10 02:15
Please add only 1 bug per issue
Also:
1 is duplicate of https://github.com/vuetifyjs/vuetify/issues/5526 
2 is duplicate of https://github.com/vuetifyjs/vuetify/issues/1978
3 the opening animation could be fixed by 
```diff
index 1a03f310c..f2b838be5 100644
--- a/packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.ts
+++ b/packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.ts
@@ -91,7 +91,7 @@ export default mixins(Themeable, RegistrableProvide('expansionPanel')).extend({
         open = v
       }

-      this.updatePanels(open)
+      this.$nextTick(() => this.updatePanels(open))
     },
     updatePanels (open: boolean[]) {
       this.open = open
@@ -108,7 +108,6 @@ export default mixins(Themeable, RegistrableProvide('expansionPanel')).extend({
         }
       }

-      this.updatePanels(open)
       if (this.expand) this.$emit('input', open)
     },
     register (content: VExpansionPanelContentInstance) {
``` 
but it breaks the closing animation and the userland solution that comes to my mind would be to set the `v-if` condition to false when then transition has finished. Vuetify solution would be to add `keep-content-alive` prop (see https://github.com/vuetifyjs/vuetify/pull/4518)

There's however another bug - 1 & 2 should be fixed by `lazy` prop in `<v-expansion-panel-content>` (and it actually fixes them) but it breaks the opening animation same as 3

**Comment by JollyBrackets** [comment] 2018-12-11 11:45
@jacekkarczmarczyk I see.. So is there no way fix this problem without causing any other issues?
My best solution is currently to use `v-if `(fixes 1 &2) and use `min-height` style to reduce the impact of jumpy animations.
However I think there is an underlying problem, as issue 1 will, also occurs on **window-resize**.

**Comment by johnleider** [comment] 2019-03-04 04:55
Can you please update this to reflect only #3 as it is the only actionable issue, ty!

**Comment by johnleider** [comment] 2019-03-13 14:42
The margin bottom of the paragraph is what is causing the extra jump as this would be the case with or without a conditional item.

https://codepen.io/anon/pen/roNdEe?editors=1010

The extra little jump is resolved on `next`.

**Closed by johnleider** 2019-03-13 14:42 UTC
