### ISSUE TITLE
[Feature Request] Touch support for v-range-slider

### ISSUE THREAD

**Issue by pianistprogrammer** [vuetifyjs/vuetify#7639] opened 2019-06-23 01:49 UTC
### Problem to solve
I am not sure this feature is implemented already, if it is done, I will like know how to enable this in my project, but right now, on the mobile device, the range slider doesn't work while it works on the desktop

### Proposed solution
I tried adding Jquery touch to my project but didn't make any difference

**Comment by KaelWD** [comment] 2019-06-23 06:31
Duplicate of #4356

**Closed by KaelWD** 2019-06-23 06:31 UTC
Labels: triage
