### ISSUE TITLE
[Bug Report] Calendar events are broken

### ISSUE THREAD

**Issue by pumpknhd** [vuetifyjs/vuetify#8379] opened 2019-08-08 03:34 UTC
### Environment
**Vuetify Version:** 2.0.1
**Last working version:** 1.5.16
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0, Google Chrome, Mozilla Firefox
**OS:** Windows 10, Windows

### Steps to reproduce
No steps needed.

Also on: https://next.vuetifyjs.com/en/components/calendars

### Expected Behavior
Multi-day events should be continuous from one date to the other.

### Actual Behavior
The events get broken up

### Reproduction Link
<a href="https://codepen.io/pumpknhd/pen/MNVeLp" target="_blank">https://codepen.io/pumpknhd/pen/MNVeLp</a>

**Comment by jacekkarczmarczyk** [comment] 2019-08-08 21:15
Duplicate of https://github.com/vuetifyjs/vuetify/issues/7992

**Closed by jacekkarczmarczyk** 2019-08-08 21:15 UTC
Labels: triage
