### ISSUE TITLE
CPU usage on progress page

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#553] opened 2017-05-17 15:04 UTC
I was just reading the API and my CPU started running at 150% permanently while on [this](https://vuetifyjs.com/components/progress) page.
I'm not very experienced with animations but maybe some optimizing can be done here?

Using Chrome 58.0.3029.110 on Linux Mint 18

**Comment by cawa-93** [comment] 2017-05-17 15:44
I agree. The load is very high
![screenshot_20170517_184308](https://cloud.githubusercontent.com/assets/1662812/26162903/afa7a298-3b30-11e7-85d2-7ef4c79a9a24.png)

**Comment by johnleider** [comment] 2017-05-19 00:31
I've made a few tweaks on the new docs to help alleviate this a bit. I went through both components to confirm no memory leaks or unnecessary re-rendering of the components due to properties changed and it all looked in order. While I did not experience the level of CPU usage that you have shown, that page on average was 1% higher CPU utilization, from 2% to 3% than other pages. This is primarily due to how many animations are rendering at once and is not indicative of real world performance.

In light of that, with the changes I've made, I'm going to close this ticket pending any additional information can be found to expedite additional dev time into this.

**Closed by johnleider** 2017-05-19 00:31 UTC
Labels: pending review

**Comment by Brimstedt** [comment] 2017-08-06 06:43
I experience the same problem, and if i use progress-circular or progress-linear (only one), my app uses lots of cpu as well.

Chrome performance tab shows lots of activity in 'Update layer tree'

This is on Chrome Version 59.0.3071.109 (Official Build) (64-bit) on Linux.

**Comment by nekosaur** [comment] 2017-08-06 08:35
This issue is closed. Please feel free to open a new issue with a reproduction of the problem. Thank you.
