### ISSUE TITLE
[Bug Report] V-menu activator property not working for selector or ref

### ISSUE THREAD

**Issue by mju516** [vuetifyjs/vuetify#7824] opened 2019-07-14 14:43 UTC
### Versions and Environment
**Vuetify:** 1.5.16
**Vue:** 2.6.10
**Browsers:** Firefox 60.0
**OS:** Windows

### Steps to reproduce
Attempt to click on the button to open the menu.
The v-menu doesn't open when setting *activator* property to be a querySelector.

### Expected Behavior
The v-menu component should open.

### Actual Behavior
The v-menu doesn't open when setting *activator* property to be a querySelector.

### Reproduction Link
<a href="https://codepen.io/anon/pen/jjoZZW" target="_blank">https://codepen.io/anon/pen/jjoZZW</a>

### Other comments
An example was provided to me on the Discord that specifying a DOM node directly appears to work at the moment. https://codepen.io/anon/pen/PrvQBM

**Comment by KaelWD** [comment] 2019-07-15 00:32
Duplicate of #5890

**Closed by KaelWD** 2019-07-15 00:32 UTC
Labels: triage
