### ISSUE TITLE
[Bug Report][3.0.0-beta.7] Field label being cut in variant outlined

### ISSUE THREAD

**Issue by trikarai** [vuetifyjs/vuetify#15620] opened 2022-08-11 07:50 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.7
**Last working version:** 3.0.0-beta.6
**Vue Version:** 3.2.30
**Browsers:** Chrome 104.0.0.0
**OS:** Windows 10

### Steps to reproduce
1. VTextField / VTextArea / VSelect
2. set props variant="outlined"

### Expected Behavior
label can be read

### Actual Behavior
label being cut in half

### Reproduction Link
<a href="https://codepen.io/trikarai/pen/abYaOBo" target="_blank">https://codepen.io/trikarai/pen/abYaOBo</a>

**Comment by KaelWD** [comment] 2022-08-11 07:51
Duplicate of #15613

**Closed by KaelWD** 2022-08-11 07:51 UTC
Labels: S: triage
