### ISSUE TITLE
Data Table Inline Editing Dialog Shouldn't be Transparent

### ISSUE THREAD

**Issue by jefrydco** [vuetifyjs/vuetify#5174] opened 2018-09-26 20:16 UTC
### Versions and Environment
Vuetify: 1.2.1
Vue: 2.5.17
Browsers: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
OS: Fedora 28

### Previously worked in:
Vuetify:
Vue:

### Steps to reproduce

Take a look on the image below
![ta](https://user-images.githubusercontent.com/20434351/46106620-67fb1a00-c203-11e8-88f6-0cb6604d89cb.png)

### Expected Behavior

Inline editing dialog shouldn't be transparent.

### Actual Behavior

Inline editing dialog is transparent.

### Reproduction Link

For reproduction link, just take a look on the Vuetify data table components example on inline edit dialog section.
https://vuetifyjs.com/en/components/data-tables#example-editdialog

---

**Comment by jacekkarczmarczyk** [comment] 2018-09-26 20:37
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5127

**Closed by jacekkarczmarczyk** 2018-09-26 20:37 UTC
