### ISSUE TITLE
[Feature Request] Auto Component Loader For Vuetify 3 With Vite.js

### ISSUE THREAD

**Issue by yooneskh** [vuetifyjs/vuetify#13834] opened 2021-06-21 16:44 UTC
### Problem to solve
Currently Vite.js template for Vuetify 3 imports all components and directives even if not used. @antfu has made a brilliant job in making a auto component importer for Vite.js and already made a Vuetify 3 importer for it too. Can you please check it and intergrate it in the Vuetify 3?

### Proposed solution
Use this to auto import only the needed components (and maybe directives) in Vuetify 3 for Vite.js.
[vite-plugin-components](https://github.com/antfu/vite-plugin-components)
[Vuetify 3 auto importer](https://github.com/antfu/vite-plugin-components/blob/master/src/resolvers/vuetify.ts)

**Comment by KaelWD** [comment] 2021-06-21 16:46
Duplicate of #13229

**Closed by KaelWD** 2021-06-21 16:46 UTC
Labels: triage
