### ISSUE TITLE
[Bug Report][3.0.0-beta.0] V-window kills default density

### ISSUE THREAD

**Issue by tve** [vuetifyjs/vuetify#14881] opened 2022-03-26 18:10 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.0
**Vue Version:** 3.2.30
**Browsers:** Chrome 98.0.4758.136
**OS:** Linux x86_64

### Steps to reproduce
See codepen:
- in createVuetify a default density of compact is specified
- button 1 and chip 1 have the compact density as expected
- button 2 and chip 2 have lost the density unexpectedly
- button 3 and chip 3 restore it explicitly

### Expected Behavior
all buttons and chips should look the same

### Actual Behavior
button 2 and chip 2 look different

### Reproduction Link
<a href="https://codepen.io/codesurfr/pen/VwypEBR" target="_blank">https://codepen.io/codesurfr/pen/VwypEBR</a>

**Comment by AnthonyWeston** [comment] 2022-03-26 20:40
This seems to be happening with `v-avatar` inside `v-app-bar` as well, and when using either the `defaults` option in `createVuetify()` or with `v-defaults-provider`

**Comment by KaelWD** [comment] 2022-03-27 04:20
Duplicate of #14844

**Closed by KaelWD** 2022-03-27 04:20 UTC
Labels: S: triage
