### ISSUE TITLE
[Feature Request] Provide static methods and callbacks for Snackbars

### ISSUE THREAD

**Issue by webees** [vuetifyjs/vuetify#9897] opened 2019-12-06 06:44 UTC
### Problem to solve
Display global messages as feedback in response to user operations.

### Proposed solution
Provide static methods and callbacks for Snackbars，like: https://www.antdv.com/components/message/

**Comment by KaelWD** [comment] 2019-12-06 06:47
Duplicate of #2384

**Closed by KaelWD** 2019-12-06 06:47 UTC
Labels: triage
