### ISSUE TITLE
v-card-media img alt

### ISSUE THREAD

**Issue by andrewharvey** [vuetifyjs/vuetify#4762] opened 2018-07-31 12:13 UTC
### What problem does this feature solve?
I'd like to be able to set the `alt` value for a `v-card-media` image, for accessibility.

### What is your proposed solution?
Add an `alt` prop to `v-card-media`.

**Comment by KaelWD** [comment] 2018-07-31 12:17
Duplicate of #3595

**Closed by KaelWD** 2018-07-31 12:17 UTC
