### ISSUE TITLE
Vuetify Electron boilerplate doesn't work anymore

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#4753] opened 2018-07-30 19:32 UTC
### Problem
Vuetify Electron boilerplate doesn't work anymore. Errors:

- `[Vue warn]: Unknown custom element: <router-link>`
- `[Vue warn]: $listeners is readonly`
- `[Vue warn]: $attrs is readonly`

### Versions and Environment
Vuetify: 1.1.8 (Vuetify Electron boilerplate)
OS: Windows 10

### Previously worked in:
`Vuetify 1.0.19`
It broke somewhere in `1.1.0-x`

### Steps to reproduce

1. Create a new project with **Vuetify Electron boilerplate**

```
vue init vuetifyjs/electron my-project
cd my-project
yarn
yarn run dev 
```

```
? Application Name my-project
? Project description An electron-vue project
? Select which Vue plugins to install vue-electron, vue-router, vuex
? Use linting with ESLint? No
? Setup unit testing with Karma + Mocha? No
? Setup end-to-end testing with Spectron + Mocha? No
? What build tool would you like to use? builder
? author noname
```

2. Upgrade Vuetify to the latest version (v1.1.8): `yarn upgrade vuetify --latest`
3. Look in the console

**Comment by KaelWD** [comment] 2018-08-01 05:49
Duplicate of vuetifyjs/electron#8

**Closed by KaelWD** 2018-08-01 05:49 UTC

**Comment by phiter** [comment] 2019-01-08 13:18
The duplicate doesn't seem to exist anymore. I still have this issue.

**Comment by phiter** [comment] 2019-01-08 13:22
Ok I found the solution, it's actually this: https://github.com/vuetifyjs/vuetify/issues/4068#issuecomment-393123259
