### ISSUE TITLE
[Bug Report]  IOS: when dialog scroll, background is scrolling sync

### ISSUE THREAD

**Issue by jiangwei007** [vuetifyjs/vuetify#5606] opened 2018-11-14 06:01 UTC
**Versions and Environment**
Vuetify: 1.3.8

**Steps to reproduce**
On a iOS mobile device ,open a modal dialog, srolling the dialog ,then the contend behind dialog is scrolling sync, and scrolling is very non-smooth!!

**Expected Behavior**
Background content doesn't scroll!!!
Dialog scrolling will smooth!!!

**Comment by jacekkarczmarczyk** [comment] 2018-11-14 06:12
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment.

Also possible duplicate of https://github.com/vuetifyjs/vuetify/issues/3875

Thank you for your contribution and interest in improving Vuetify.

**Closed by jacekkarczmarczyk** 2018-11-14 06:12 UTC

**Comment by natxocc** [comment] 2019-01-03 22:17
I have the same problem.
Using IOS 12 with my IPhone, when I open a scrollable dialog, background scroll nor the dialog content.
Using the Document page than jiangwei007 linked, on official page, it doesn't work well.
