### ISSUE TITLE
[Bug Report] VTextField Error Message Cut Off

### ISSUE THREAD

**Issue by jeffpohlmeyer** [vuetifyjs/vuetify#12660] opened 2020-11-23 04:48 UTC
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 86.0.4240.198
**OS:** Windows 10

### Steps to reproduce
Use a font like Nunito instead of Roboto and the top of an error message in a v-text-field gets cut off.  See the Pen for details.

### Expected Behavior
Nothing, this is not default behavior

### Actual Behavior
N/A

### Reproduction Link
<a href="https://codepen.io/JVP3122/pen/pobMgjm" target="_blank">https://codepen.io/JVP3122/pen/pobMgjm</a>

### Other comments
If there were a custom variable, something like $text-field-details-padding-top: 0px !default; that we could modify it would be helpful.

**Comment by KaelWD** [comment] 2020-11-23 05:14
Duplicate of #4655, #12401

**Closed by KaelWD** 2020-11-23 05:14 UTC

**Comment by jeffpohlmeyer** [comment] 2020-11-23 13:20
Apologies for the duplication @KaelWD 

I only set up the issue so that I could create the PR
