### ISSUE TITLE
[Bug Report] Filtering a treeview does not run all items through the filter

### ISSUE THREAD

**Issue by James-Hudson3010** [vuetifyjs/vuetify#12027] opened 2020-08-07 20:40 UTC
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Safari 13.1.2
**OS:** Mac OS 10.15.6

### Steps to reproduce
In the search field, type Core . 

### Expected Behavior
The *Core team* node would be visible, but would have no children since none of the children passed the filter.

### Actual Behavior
The *Core team* node is visible along with all of its children.

### Reproduction Link
<a href="https://codepen.io/james-hudson3010/pen/vYGEQyY" target="_blank">https://codepen.io/james-hudson3010/pen/vYGEQyY</a>

### Other comments
This can be illustrated with the example code for the *Searching a directory* example --  https://vuetifyjs.com/en/components/treeview/#searching-a-directory

I am not sure if this is a bug, expected behavior, or if there is a prop (or other standard method) to get the behavior I want.

If this is not considered a bug or there isn't a prop to modify the behavior, please consider this a feature request.

**Comment by KaelWD** [comment] 2020-08-09 08:38
I believe this is intentional, if a node matches all its parents and children are also shown. If the node you're looking for has children you should still be able to expand it to see them.

**Comment by James-Hudson3010** [comment] 2020-08-10 12:06
Looking around, the behavior I see is that every item it passed through the filter regardless. If a node matches, but none of it's descendants do, it will no longer be expandable. This is, for example, how the Quasar tree can behave. 

Please consider this to be a feature request.

I can work around it by not using the built-in filter functionality and instead filtering the data myself, but I would rather use what it built in.

**Comment by James-Hudson3010** [comment] 2020-08-10 12:06
Looking around, the behavior I see is that every item it passed through the filter regardless. If a node matches, but none of it's descendants do, it will no longer be expandable. This is, for example, how the Quasar tree can behave. 

Please consider this to be a feature request.

I can work around it by not using the built-in filter functionality and instead filtering the data myself, but I would rather use what it built in.

**Comment by James-Hudson3010** [comment] 2020-08-10 12:07
Looking around, the behavior I see is that every item it passed through the filter regardless. If a node matches, but none of it's descendants do, it will no longer be expandable. This is, for example, how the Quasar tree can behave. 

Please consider this to be a feature request.

I can work around it by not using the built-in filter functionality and instead filtering the data myself, but I would rather use what is built in.

**Comment by James-Hudson3010** [comment] 2020-08-10 12:07
Looking around, the behavior I see is that every item it passed through the filter regardless. If a node matches, but none of it's descendants do, it will no longer be expandable. This is, for example, how the Quasar tree can behave. 

Please consider this to be a feature request.

I can work around it by not using the built-in filter functionality and instead filtering the data myself, but I would rather use what is built in.

**Comment by James-Hudson3010** [comment] 2020-08-10 12:16
Looking around, the behavior I see is that every item it passed through the filter regardless. If a node matches, but none of its descendants do, it will no longer be expandable. This is, for example, how the Quasar tree can behave. 

Please consider this to be a feature request.

I can work around it by not using the built-in filter functionality and instead filtering the data myself, but I would rather use what is built in.

**Comment by James-Hudson3010** [comment] 2020-08-10 12:16
Looking around, the behavior I see is that every item it passed through the filter regardless. If a node matches, but none of its descendants do, it will no longer be expandable. This is, for example, how the Quasar tree can behave. 

Please consider this to be a feature request.

I can work around it by not using the built-in filter functionality and instead filtering the data myself, but I would rather use what is built in.

**Comment by KaelWD** [comment] 2020-11-10 13:27
Duplicate of #9452

**Closed by KaelWD** 2020-11-10 13:27 UTC
Labels: C: VTreeview, triage
