### ISSUE TITLE
[Bug Report][2.6.13] Data Table Header filter must all validate to true

### ISSUE THREAD

**Issue by Bjo-Frei** [vuetifyjs/vuetify#16337] opened 2022-12-27 23:19 UTC
### Environment
**Vuetify Version:** 2.6.13
**Last working version:** 2.6.13
**Vue Version:** 2.7.14
**Browsers:** Firefox 108.0, Google Chrome
**OS:** Ubuntu undefined, Windows

### Steps to reproduce
Run Reproduction Link
Create a header definition with a custom filter. 
We use a more complex data table definition and create this easy one.

### Expected Behavior
All three items rows must be shown, because the custom filter will evaluate to "true" for each item.

### Actual Behavior
Currently no rows will be shown, because rows without custom filter will evaluate to false, but this must be ignored at this point.

### Reproduction Link
[https://codepen.io/Bjo-Frei/pen/mdjVMgr](https://codepen.io/Bjo-Frei/pen/mdjVMgr)

### Other comments
The filter logic is a little bit confusing:
1. Header with Custom filter must be all evaluate to true if more than one used
2. Header without custom filter must be at least one evaluate with true or search is not set
Otherwise the item will be not shown anymore.

The best filter option is for showing a row:
1. no search is set
2. if one column is evaluate to true than the row of the item will be shown (default or custom filter)

This logic is the same without custom filter.

**Comment by KaelWD** [comment] 2022-12-28 14:53
Duplicate of #11600

**Closed by KaelWD** 2022-12-28 14:53 UTC
Labels: S: triage
