### ISSUE TITLE
[Feature Request] Text inside v-progress-linear 

### ISSUE THREAD

**Issue by Halo-Josh** [vuetifyjs/vuetify#4354] opened 2018-06-20 16:03 UTC
### Problem to solve
If the user wants to have text inside the div of the v-progress-linear vuetify component. Here's a roundabout way of doing it https://codepen.io/jashoop/pen/yEKLZa

### Proposed solution
v-progress-linear value="75" height="20" color="error"> inside text </v-progress-linear

**Comment by KaelWD** [comment] 2018-06-20 16:23
Duplicate of #3768

**Closed by KaelWD** 2018-06-20 16:23 UTC
