### ISSUE TITLE
[Bug Report] Data table sorting is not correct

### ISSUE THREAD

**Issue by projectseahawks** [vuetifyjs/vuetify#9908] opened 2019-12-07 06:50 UTC
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
1. Click 'Calories' header (icon shows asc order), Calories list is 20, 1001, 2008, which is correct.
2. Click 'Calories' header (icon shows desc order), Calories list is 2008, 1001, 20, which is correct.
3. Click 'Calories' header (icon shows asc order), Calories list is 1001, 2008, 20, which is incorrect.
4. Click 'Calories' header (icon shows asc order, which is incorrect), Calories list is 20, 1001, 2008, which is correct.

### Expected Behavior
1. Click 'Calories' header (icon shows asc order), Calories list is 20, 1001, 2008.
2. Click 'Calories' header (icon shows desc order), Calories list is 2008, 1001, 20.
3. Click 'Calories' header (icon shows asc order), Calories list is 20, 1001, 2008.
4. Click 'Calories' header (icon shows desc), Calories list is 2008, 1001, 20.

### Actual Behavior
As shown in repro steps.

### Reproduction Link
<a href="https://codepen.io/jun2020/pen/WNbQXqB?&editable=true&editors=101#anon-signup" target="_blank">https://codepen.io/jun2020/pen/WNbQXqB?&editable=true&editors=101#anon-signup</a>

**Comment by projectseahawks** [comment] 2019-12-07 06:51
@jun2014

**Comment by KaelWD** [comment] 2019-12-07 07:08
Duplicate of #4894

Step 3 is showing the original order from the items array.

**Closed by KaelWD** 2019-12-07 07:08 UTC
Labels: triage
