### ISSUE TITLE
[Bug Report][2.5.0] VSelect not showing persistent placeholder

### ISSUE THREAD

**Issue by jvbianchi** [vuetifyjs/vuetify#13666] opened 2021-05-17 14:46 UTC
### Environment
**Vuetify Version:** 2.5.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 90.0.4430.212
**OS:** Linux x86_64

### Steps to reproduce
Open codepen

### Expected Behavior
Show placeholder when prop `persistent-placeholder` is set

### Actual Behavior
Is not showing the placeholder

### Reproduction Link
<a href="https://codepen.io/jenaxi/pen/NWpRxmG" target="_blank">https://codepen.io/jenaxi/pen/NWpRxmG</a>

**Comment by zetaraku** [comment] 2021-05-26 09:26
The placeholder of **VFileInput** is also not showing when `persistent-placeholder` is set.

I make a demo to reproduce these problems, please take a look :)

https://github.com/zetaraku/vuetify-demo

**Comment by KaelWD** [comment] 2021-06-21 18:11
Duplicate of #13792

**Closed by KaelWD** 2021-06-21 18:11 UTC
Labels: C: VSelect, T: bug

**Comment by zetaraku** [comment] 2021-06-26 04:01
@KaelWD The placeholder of VFileInput is not showing when `persistent-placeholder` is set as I mentioned above.
Should I open a new issue to handle it?
