### ISSUE TITLE
[Bug Report][3.0.0-beta.10] Header and divider on a v-select not displaying

### ISSUE THREAD

**Issue by rnenjoy** [vuetifyjs/vuetify#15778] opened 2022-09-13 15:46 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Vue Version:** 3.2.39
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
In the API docs its says there is still available to implement header and divider on the items in a v-select. But it doesnt seem to work. Is it removed for 3.0?

### Expected Behavior
That a header item is showed and not selectable. Or a divider is showed and not selectable.

### Actual Behavior
An item appears with empty text.

### Reproduction Link
<a href="https://codepen.io/rightnow/pen/abGmMZm?editors=101" target="_blank">https://codepen.io/rightnow/pen/abGmMZm?editors=101</a>

**Comment by KaelWD** [comment] 2022-09-14 08:10
Duplicate of #15721

**Closed by KaelWD** 2022-09-14 08:10 UTC
Labels: S: triage
