### ISSUE TITLE
[Bug Report] Drawer border should have been on 100% height

### ISSUE THREAD

**Issue by QQ34205037** [vuetifyjs/vuetify#6496] opened 2019-02-14 06:23 UTC
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.96
**OS:** Mac OS 10.14.3

### Steps to reproduce
![](https://raw.githubusercontent.com/QQ34205037/resources/master/issues/vuetify/drawer-border.png)

I know this is a duplicate issue(https://github.com/vuetifyjs/vuetify/issues/1076),  but the issue has been closed.
What's the best way to do it now?

### Expected Behavior
...

### Actual Behavior
...

### Reproduction Link
<a href="https://raw.githubusercontent.com/QQ34205037/resources/master/issues/vuetify/drawer-border.png" target="_blank">https://raw.githubusercontent.com/QQ34205037/resources/master/issues/vuetify/drawer-border.png</a>

**Comment by jacekkarczmarczyk** [comment] 2019-03-10 16:19
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3498

**Closed by jacekkarczmarczyk** 2019-03-10 16:19 UTC
Labels: T: bug
