### ISSUE TITLE
[Feature Request] IntersectionObserver for v-img

### ISSUE THREAD

**Issue by TheRoccoB** [vuetifyjs/vuetify#7242] opened 2019-05-20 00:17 UTC
### Problem to solve
Loading a large gallery on my front page is pretty slow. It would be great if I could use IntersectionObserver with my v-img 's 

### Proposed solution
A <v-img> prop like useIntersectionObserver that would lazy load images as the user scrolls down the page.

As a stopgap I'm using v-lazy-image here https://github.com/alexjoverm/v-lazy-image

Also it seems a polyfill is sometimes necessary for this. I think it would be OK to suggest that the user of this feature would need to install the polyfill to support older browsers.

https://caniuse.com/#search=intersectionObserver

**Comment by KaelWD** [comment] 2019-05-20 00:48
Duplicate of #4983

**Closed by KaelWD** 2019-05-20 00:48 UTC
Labels: triage
