### ISSUE TITLE
[Bug Report] Menu position breaks if use with tooltip

### ISSUE THREAD

**Issue by Kosalexei** [vuetifyjs/vuetify#9180] opened 2019-10-02 11:35 UTC
### Environment
**Vuetify Version:** 2.1.0
**Last working version:** 2.0.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Try to call menu in reproduction link.

### Expected Behavior
The menu should open next to the button.

### Actual Behavior
The menu opens in the left corner of the screen.

### Reproduction Link
<a href="https://codepen.io/kosalexei/pen/zYOgPqq?&editable=true&editors=101" target="_blank">https://codepen.io/kosalexei/pen/zYOgPqq?&editable=true&editors=101</a>

**Comment by KaelWD** [comment] 2019-10-02 11:38
Duplicate of #8846

**Closed by KaelWD** 2019-10-02 11:38 UTC
Labels: triage
