### ISSUE TITLE
[Bug Report] v-container has no styles in npm run build

### ISSUE THREAD

**Issue by alexanderjanke** [vuetifyjs/vuetify#8013] opened 2019-07-25 13:21 UTC
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Execute "npm run build"

### Expected Behavior
Displayed correctly
![Working](https://i.imgur.com/A5gtC7e.png)

### Actual Behavior
CSS Class .container doesn't seem to be generated in build
![Not Working](https://i.imgur.com/yt3no3A.png)

### Reproduction Link
<a href="https://codepen.io/anon/pen/eqzXGy" target="_blank">https://codepen.io/anon/pen/eqzXGy</a>

### Other comments
Workaround:
Add following CSS to App.vue (copied from the working "npm run serve" version)

```
.container {
  width: 100%;
  padding: 12px;
  margin-right: auto;
  margin-left: auto;
}
@media (min-width: 960px) {
  .container {
    max-width: 960px;
  }
}
@media (min-width: 1264px) {
  .container {
    max-width: 1264px;
  }
}
@media (min-width: 1904px) {
  .container {
    max-width: 1904px;
  }
}
.container--fluid {
  max-width: 100%;
}
```

**Comment by KaelWD** [comment] 2019-07-25 13:22
Duplicate of #7978

**Closed by KaelWD** 2019-07-25 13:22 UTC
Labels: triage
