### ISSUE TITLE
[Bug Report][3.1.10] v-btn ignores max-width, max-height props

### ISSUE THREAD

**Issue by kappaflow** [vuetifyjs/vuetify#16947] opened 2023-03-18 09:28 UTC
### Environment
**Vuetify Version:** 3.1.10
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a button with an icon, try to change parent `font-size` (`:style="{fontSize:'16px'}"` in the provided example) with `max-width`, `max-height` or fixed `size` set.

### Expected Behavior
The button shouldn't grow after reaching `max-width` and `max-height`.
The button should ignore the parent `font-size` if `size` prop is defined as a number, because according to the [docs](https://vuetifyjs.com/en/api/v-btn/#props-size) "_Default unit is **px**._" ).

### Actual Behavior
The button always grows in case of increasing the parent `font-size`

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdUk1v2zAM/SuCLm6B2G66YgOydOh+w4Zdqh4Um6m1WB+QGCdZ4P8+ynK8Jtl26MUWH58eySc+H3m3BVTrQ/Ez8AVX2lmP7MgqDxLhR8qxnq291SwbuZkwwsB+oFbWBGRjgj2eX7w5CsMYNqBhwYYzYzWs5bbF7wnMauk32Symevr2t5+F4TP+1bmCNKmjZai8cvglMsaSo8IkKFGym9tTyJgH3HrzJ+7TIeoPwbKcNJcI2rXUcNRf1qpjqn4UXDoneIQELrucIrYIeGiBUse1NfhN/YJFNv/o9lmfiIx4KyRbYqVAaaLe3wmeAEUuEaBrlcuqsluDp4yW+3ynamwoPZ/4EW1AvTZ4Bl8T/0KqwQSFB8Iqq52splKd9EqaSEbYT2hlW+sJ2zUKYQJbGUJsWOYPCUszlsOQdCZf6EzGRA9L8m34vzGTwmQyC/QaiTa5Tg+cFi3X0tHiWUMPPTyXGBNB8GlhRFzRGAveILqwKMutcZvXguYrnyhXejJUachrq58+FPfFwydqKeBbvICg85W3uwCeKgo+LMMoHlf1XwXGNOnOi/ld0h2xvJWrEIWvBEuq0oHPPZgaPPj/dn/BPZvgInc1xbjRPTnaKrMJF2ZWYTDy+dTaO8YbJOL9l1imn/HUHhVMV/jLbx6MZ/E=)

**Comment by kappaflow** [comment] 2023-03-18 11:42
Fixed the initial link.
Also, [this is](https://play.vuetifyjs.com/#eNqdUk1v2zAM/SuCLm6B2G7aYgOydOh+w4Zdqh4Um6m1WB+QGCdZ4P8+ynK8Jtl22MUWH58eySe+HHm3BVTrQ/Ej8AVX2lmP7MgqDxLhe8qxnq291SwbuZkwwsB+oFbWBGRjgj2dX7w5CsMYNqBhwYYzYzWs5bbFbwnMauk32Symevr2t5+E4TP+xbmCNKmjZai8cvg5MsaSo8IkKFGym9tTyJgH3HrzO+7TIeoPwbKcNJcI2rXUcNRf1qpjqn4SXDoneIQELrucIrYIeGiBUse1NfhV/YRFNn/44PZZn5iMiCskX2KpQHni3t8JngBFNhGga5XLqrJbg6eMlvt8p2psKD2f+BFtQL01eAZfE/9AqsEEhQfCKqudrKZSnfRKmkhG2E9oZVvrCds1CmECWxlCbFjmjwlLM5bDkHQmY+hMzkQTSzJu+L9zk8LkMgv0HIk22U4vnDYt19LR5llDLz28lxgTQfBpY0Tc0RgL3iC6sCjLrXGbt4LmK58pV3oyVGnIa6ufH4r74vEjtRTwPV5A0PnK210ATxUFH7ZhFI+7+rcCY5p058X8LumOWN7KVYjCV4IlVenA5x5MDR78P7u/4J5NcJG7mmJc6Z4cbZXZhAszqzAY+XJq7T/GGyTi/ddYpp/x1B4VTFf46y8kXWgk) an example with a big `font-size` set

Also its a bit related to #12532

**Comment by KaelWD** [comment] 2023-03-18 11:45
Thanks.

Duplicate of #16288

**Closed by KaelWD** 2023-03-18 11:45 UTC
Labels: S: needs reproduction, S: triage
