### ISSUE TITLE
[Bug Report] v-tooltip inside v-menu reinitialization error

### ISSUE THREAD

**Issue by Kasheftin** [vuetifyjs/vuetify#10153] opened 2020-01-08 13:52 UTC
### Environment
**Vuetify Version:** 2.2.3
**Vue Version:** 2.6.11
**Browsers:** Chrome 72.0.3626.109
**OS:** Linux x86_64

### Steps to reproduce
- Hover on the menu button;
- Tooltip appears;
- Click on the menu button;
- Menu appears alongside with the tooltip as well;

Now click on `Text Mode` switch. This action replaces the tooltip activator with no-tooltip v-btn activator.  But instead of this the activator disappears entirely. Clicking on the switch again does not restore it as well.

### Expected Behavior
v-menu activator should not disappear

### Actual Behavior
v-menu activator disappears

### Reproduction Link
<a href="https://codepen.io/kasheftin/pen/WNbMYmR?editors=1010" target="_blank">https://codepen.io/kasheftin/pen/WNbMYmR?editors=1010</a>

**Comment by KaelWD** [comment] 2020-01-10 04:04
Duplicate of #9377

**Closed by KaelWD** 2020-01-10 04:04 UTC
Labels: triage
