### ISSUE TITLE
[Bug Report][3.3.11] VDatatable custom sort function declared in headers is not called

### ISSUE THREAD

**Issue by nct124** [vuetifyjs/vuetify#18029] opened 2023-08-10 15:05 UTC
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Windows 10

### Steps to reproduce
click on "Calories" header 

### Expected Behavior
should trigger the console.log

### Actual Behavior
it did not

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNV21v6jYU/itWpImwkfBO26jt7l23bl0n3Wq7mjSVfjDBhayJHdmGjlX893vs2HESgoAvJOc8Pn7Oq+PnD+9znofbDfEi71qSLE+xJLdzitD1NlhiiQOJFylRAoS2QcaWJI0SAIogJzzI8YrczD0teCL8CV7nXgGO1gQvCRegNk+lRsNBLgjfEv6g3kqdIJjHa61UD1Yep1ioJSQlWywTRoOhVSlrwRanG8WE4swxMOwM8va6X3UJnLzuVzyGVxHzJJfa+5hRIdGSCOAoBbpBz4XNj+IPIbVRhDr3nP1PKPqHrTZcdnpWG+OU8YSICA2nV6X0FcsIzcJBBcYXgBlNSknOmSQJjdCkAks4A0lnaO3vzX+TzO8kTXdoQTBtYzK+mNaZDA6ZXLUwqcIMk8EpJo+JfMSt8ZgOL+ssRi0BmTmmJY2LJonZKRK/QNEkvI3EaDaqkxi2ZWV8SKIKMzQuTtH4NaErwhccmqA1LdPZaS4TV0Qll3HohLZCTsbkISYoBioZEpgu35N43RqfsYu25nR1SKkCqRSti9m5RfsHS9MkZ3lrbK4aeRqETmBL1tWTK9kmi9EpFnebPMZvpJXEoNE349C5bgv2vGBcnqLxG6NkF7Ns0UZkMmi0zvgwGpctRGahc8AQmUxPMfmZ0U1rA0+mjZyMpofFMR22xeOgXkeNvLyoMWyH7z3k4/PTA8xeww2LHY3RK5Hx2v9Aarj39PC3J08PCcblTzu07zp3OJEbThEl7+iJsywRxOdEsHRL0M2tgyEkiPyaZIRtpO93GzpLSUjMJRDy1eYoQMMu+r5G4XAJoUtYUCz84QRWawFtj51QpElM/G4RFftLXpFfOBqmhK7kuuJtjSxgHslO7a7Rz4OX8I3sjkG/cDija2CmJHW4ZhgqiO/jHlocBsoZxX+rMxks4mdDBdLbBlxY4OIo0GSxwvPmBnUgTnEH/WgNBHbLyD4ERlU3t4eAVt7q0S0oQX4TCt8FKnfGZ50KnceeSmojKaamoC41PHIWekgyidPI2ClSVuOw76HpYFAKrKpoCUOP/JeD71AZr3iTShtyNclhC6jXMgdyncAmDC/1Z5XpEzhU6q0CHWq7JULPL409EVKfSREq+sAvbTctWLn5vgNLzqlaUchEpnqoFIWN/OFgsIKO41s4G7tuyuguT5OVmg061HWVIqw+3SIYPKkgNR1UNixSw6u6xvpzlNGdmWv1jQpjdua184MaOGQHMTvWFqqwWEogNyu/89eXP792ekhj6zBT6cNaiR7zqHTjHkNQVSQNdRjMynyF6pGFd2pe15bqCX7eYhioarTXlptxf56BBzgGkP+dW63OheNLX8qn4nIACJeCymVClXQpV70AVRYhyTeuZHRPGrA9vfZd85ARuWZL0JQpbDbUGQdPI+OlBXBPWaikvWxZoAnzRvF0SnMKhmcde6FcE+pXS8cOJDOFFMPD0tQEKvGzQ68F5eKmmKqXFpDzRfdpY9raRzfwat8AgLjulzcxr+elCX0T4b+CUbijauZzLxZwYyznDdwwpcxF1O/HSwpIuKMmWx5SIvs0z/pwu5XJ6+7TOByHw2F/mQhpZUGKFyLU1sz3xx52TDI1bIMM541tC4Xe2oRw7oEl9X6CwyeA9fmGSvjECJYs02QmBZeKOCQiCxacvUM2wMjcM6HR2yjCZ2x10l3Y48B2v0h/wKHlCIdj/0yXGsuqbjVUB66ZZO+9fc/TyyDyBWfv5Rvl8MJi)

**Comment by KaelWD** [comment] 2023-08-11 07:28
Duplicate of #17588

**Closed by KaelWD** 2023-08-11 07:28 UTC
Labels: S: triage
