### ISSUE TITLE
[Bug Report] Bottom-sheet does not persist when computed value is true

### ISSUE THREAD

**Issue by pantagruel964** [vuetifyjs/vuetify#9178] opened 2019-10-02 10:00 UTC
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Select a row, select another one and another one

### Expected Behavior
The Bottom-sheet will persist when value is true

### Actual Behavior
The Bottom-sheet does not persist when value is true

### Reproduction Link
<a href="https://jsfiddle.net/pantagruel964/jfvbonwm/13/" target="_blank">https://jsfiddle.net/pantagruel964/jfvbonwm/13/</a>

**Comment by KaelWD** [comment] 2019-10-02 11:40
Duplicate of #8679

**Closed by KaelWD** 2019-10-02 11:40 UTC
Labels: triage

**Comment by pantagruel964** [comment] 2019-10-02 12:16
@KaelWD What relation with [#8679](https://github.com/vuetifyjs/vuetify/issues/8679)?

**Comment by KaelWD** [comment] 2019-10-02 14:42
ugh #8697
