### ISSUE TITLE
New Vuetify app in vue cli 3 won't render in IE11

### ISSUE THREAD

**Issue by albertlinga** [vuetifyjs/vuetify#5544] opened 2018-11-08 12:26 UTC
I followed https://vuetifyjs.com/en/getting-started/quick-start#ie11-support after adding Vuetify from my vue app created from vue cli3. However arrow function in main.js e.g. render: h => h(App) is not transpiled properly so it didn't work on IE 11. Function shorthands in App.js and HelloWorld.js was also not transpiled properly.

I also imported a file whose export defaul is a es6 class and it didn't work as well.

**Comment by KaelWD** [comment] 2018-11-08 12:35
Duplicate of https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/55

**Closed by KaelWD** 2018-11-08 12:35 UTC

**Comment by albertlinga** [comment] 2018-11-08 13:37
@KaelWD  I did modify my vue.config.js to look like this 

module.exports = {
  transpileDependencies: ['vuetify']
}

now I'm getting errors Cannot assign to read only property 'exports' of object '#<Object>
