### ISSUE TITLE
[Bug Report] Type Error after closing snackbar

### ISSUE THREAD

**Issue by Moedav** [vuetifyjs/vuetify#6536] opened 2019-02-18 14:06 UTC
### Versions and Environment
**Vuetify:** 1.5.1
**Vue:** 2.6.6
**Browsers:** Chrome 71.0.3578.80
**OS:** Windows 10

### Steps to reproduce
1) Open DevTools
2) Open snackbar
3) close snackbar
4) Uncaught TypeError: Cannot set property 'touched' of undefined occured

### Expected Behavior
No TypeError

### Actual Behavior
TypeError occured, but Component works still fine.

### Reproduction Link
<a href="https://codepen.io/anon/pen/xMmNLr?&editable=true&editors=101" target="_blank">https://codepen.io/anon/pen/xMmNLr?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment] 2019-02-18 15:23
Duplicate of https://github.com/vuetifyjs/vuetify/issues/6477

**Closed by jacekkarczmarczyk** 2019-02-18 15:23 UTC
