### ISSUE TITLE
[Bug Report][3.3.12] Date picker keyboard input mode does not work well for other locales

### ISSUE THREAD

**Issue by eguvenc** [vuetifyjs/vuetify#18040] opened 2023-08-13 17:09 UTC
### Environment
**Vuetify Version:** 3.3.12
**Vue Version:** 3.3.4
**Browsers:** Edge 115.0.1901.203
**OS:** Windows 10

### Steps to reproduce
When I set the date to Turkish in keyboard input mode, the date picker formats the date in en-US format. 

### Expected Behavior
![image](https://github.com/vuetifyjs/vuetify/assets/482833/a2184736-f0b3-44ad-89fe-05eebcc5d9ed)

### Actual Behavior
![image](https://github.com/vuetifyjs/vuetify/assets/482833/66ac95af-bced-4aa9-a325-0793cc887716)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlVH9r2zAQ/SqHGTTpartZxxhZ2nUwCvtjDDoYjLpQ1b4sWvULWU5WSr77TrIdK27LBv3L1t3Te3fvJF09JJ+MydYNJvNk4VAawRyeFQpgsU6ZMeE3LEqtHOMKbRcKQaFLJjA1Vq95hRba9WmROFskO2CAVkScGl7eoR3iAKUW2tIGY7lk9r5I4iRXpnGp1JWnvMP7W81stQ+Z+6z4wUTjMb/QfSadfch5Y7z4PrKNjcFni3yv0qFXio+a7a2hzL43PtJat8gjS2lZl5YbF0B5DlwabR08gNOXbANbWFot4YCGcfDBwwHwT0BUuGSNIGSruGGuXM37FcDatxStAVZMVQLthDLTOA7gVrzOgq1w6jcOue3R8M+lxIp7z8DZBneZHtN/ySk2iRQsusaqWFGiauawZKIeWLq5zkE1Qgzc+9SlloTBKurLz+VCW8kcxWNZj1Y1+UQAaivq8SMo3ICf8mSIToGk+/B0IBHoQNIkV8Qxg9eBLqMT9dXHYiBfwqQFLmB2PHK4Z7g5fvUQ/rc3kcn7ahW7J2SvM67Hy3jEEyLtRi9Bf88IdMO4aTFpXw399IIX5P9PZHYyHSiGY7CrKJbODw+jOg7hshX58v0bvH93PItz+bjXFw2n68azPHcaJbqVruroxAyX/NFVCIr+dFJN4XiOUk/eEX/MtMAMrdXt7Xq6FprCIt9d9uQoaa96KpnJftda0WMbSim6RF0ku6qLhB4Avy6SlXOmnud5WSnaRo8XX9tMocuVkfk5wXLbKMclppWW5yfZSfY2r3jt4nCGtUxvrd7UaImkSLpCg4zjS3px/ynVIYPC7E0r0cVSwW5rr/GIOyfBNdrUoqLHkh79/2xptC1ua5R61Fpn/ZYMF1zd1SOvyzr4fNUX+bKeA5unuvaK26MkFErS7Y7k+i9eKD6P)

**Comment by KaelWD** [comment] 2023-08-15 09:11
Duplicate of #17615

**Closed by KaelWD** 2023-08-15 09:11 UTC
Labels: S: triage
