### ISSUE TITLE
[Bug Report] Testing with Vue-Test-Utils - Mount fails on Second Attempt

### ISSUE THREAD

**Issue by relief-melone** [vuetifyjs/vuetify#9820] opened 2019-11-28 17:33 UTC
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Other
**OS:** Windows 10

### Steps to reproduce
1. Clone Repository
2. npm install
3. npm run test:unit

### Expected Behavior
Four tests have been written each just wrapping a component utilizing Vuetify and mounting it.

As all tests are exactly the same it is expected for them all to succeed and behave in the same way.

### Actual Behavior
mount is failing on the second execution reproducible producing the error 

TypeError: Cannot read property '$scopedSlots' of undefined

Test Executions 1,3 and 4 behave as expected

### Reproduction Link
<a href="https://github.com/relief-melone/rm-test-mount-fails-on-second-exec.git" target="_blank">https://github.com/relief-melone/rm-test-mount-fails-on-second-exec.git</a>

### Other comments
I cannot be 100% sure if this issue is caused by Vuetify or the Test Utils (So i created this issue in both Projects). I have been trying alot of different configurations of using localVue Vuetify or vuetify created from new Vuetify but had no luck. There is also a thread open on StackOverflow. 
(https://stackoverflow.com/questions/59070770/testing-vuetify-vue-js-second-call-on-mount-throws-error)

Another user mentioned he did not get the wrong behaviour on version 1.5.21

### Versions:

**Vue:** 2.6.10
**Vue-Test-Utils:** 1.0.0-beta.29    
**Vuetify:** 2.1.12

**Comment by KaelWD** [comment] 2019-11-29 00:39
Duplicate of #9151

**Closed by KaelWD** 2019-11-29 00:39 UTC
Labels: triage

**Comment by relief-melone** [comment] 2019-11-29 07:19
Thanks for the quick reply. I am not quite sure if this is a duplicate though. Issue #9151 states it has problems using shallowMount after mount, but this example doesn't use shallowMount. And I think it is a serious bug, that you cannot expect for 2 identical tests to behave in the same way. 

Also #9151 states that it might be the problem described in vue-test-utils [#1130](https://github.com/vuejs/vue-test-utils/issues/1130). But here a workaround that should work is using sync true. In this case, the behaviour with sync: true is exaclty the same.

I'm also getting the feeling though that this might be more of a test-utils issue so you can leave this one closed for now. I'll drop info if it's not caused by vue-test-utils

**Comment by KaelWD** [comment] 2019-11-29 07:43
Duplicate doesn't necessarily mean the symptoms are the same.
