### ISSUE TITLE
[Bug Report] Can't select an item in combobox when pressing enter

### ISSUE THREAD

**Issue by zbyju** [vuetifyjs/vuetify#8154] opened 2019-07-29 15:54 UTC
### Environment
**Vuetify Version:** 2.0.2
**Vue Version:** 2.6.10
**Browsers:** Firefox 68.0
**OS:** Windows 10

### Steps to reproduce
Select an option from the item list using arrow keys and press ENTER

### Expected Behavior
The item gets selected and displayed in the combobox and menu closes.

### Actual Behavior
The menu closes without changing the value/displaying the item

### Reproduction Link
<a href="https://codepen.io/TuruMan/pen/jgyRLy" target="_blank">https://codepen.io/TuruMan/pen/jgyRLy</a>

### Other comments
This exact behaviour works with the v-autocomplete just fine. It even works with the combobox when using chips

**Comment by hyvyys** [comment] 2019-07-31 22:18
https://codepen.io/hyvyys/pen/gVRgRx Actually the value is changed but then reverted to what is typed.

**Comment by zbyju** [comment] 2019-08-01 15:01
https://codepen.io/TuruMan/pen/aeybXO So what I meant with the comment is that selecting the item from the dropdown is broken only for v-combobox. Works fine with v-autocomplete and even with v-combobox when it's using chips.

**Comment by goeh** [comment] 2019-08-03 11:33
I have a codepen https://codepen.io/goeh/pen/bXrBMe that's more complicated, I will verify with that once this issue is fixed.

**Comment by sh7dm** [comment] 2019-08-06 05:58
Issue is caused by https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VCombobox/VCombobox.ts#L182

**Comment by egeersoz** [comment] 2019-08-30 18:58
This is a major regression that broke large parts of our app. Hope it gets fixed soon!

**Comment by egeersoz** [comment] 2019-10-17 05:27
This seems to be fixed. On the current latest version (2.1.4) I cannot reproduce it inside my own app or in the Codepen provided in the OP. @zbyju Can you confirm?

**Comment by KaelWD** [comment] 2021-03-06 14:09
This was fixed in eab8d329c33bf9eb8c22b1038e614c105c7b05d9

**Closed by KaelWD** 2021-03-06 14:09 UTC
Labels: C: VCombobox, P: high, T: bug, T: regression
