### ISSUE TITLE
[Bug Report][2.2.18] v-overflow-button has unexpected bottom space

### ISSUE THREAD

**Issue by ghost** [vuetifyjs/vuetify#10884] opened 2020-03-19 13:54 UTC
### Environment
**Vuetify Version:** 2.2.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Just create any **v-overflow-btn** and try to center align it with other elements in a **v-row**. You will observe a misalignment caused by a bottom space with an invisible **v-message**.

### Expected Behavior
**v-overflow-btn** should not have asymetrical margin unless required by a prop.

### Actual Behavior
**v-overflow-btn** has an extra bottom space that makes it hard tu use aligned with other elements.

### Reproduction Link
<a href="https://codepen.io/zebnastienx/pen/YzXjPeq" target="_blank">https://codepen.io/zebnastienx/pen/YzXjPeq</a>

### Other comments
Hi there ! I am new to Git so correct me if my report is lacking in something...

**Comment by ElijahKotyluk** [comment] 2020-03-22 01:54
I noticed something in your reproduction link, your second `v-col` is not closed(ie `</v-col>`, if you close it, it should align correctly inside the row.

**Comment by jacekkarczmarczyk** [comment] 2020-03-22 02:00
It still has issues with closed v-col, `hide-details` doesn't help, needs to remove the margin-top of the btn

https://codepen.io/jkarczm/pen/zYGJByp

**Comment by johnleider** [comment] 2020-03-22 17:16
All inputs share the same baseline structure and are affected by this. I'm inclined to believe that all inputs should share the removal of margin. Although this would be quite a chance and I'm uncertain if it would fall under a minor or a major feature.

@vuetifyjs/core-team @vuetifyjs/contributors

**Comment by ZebnastienX** [comment] 2020-03-22 17:22
Corrected v-vol in codepen. Still misaligned as said before.

**Comment by johnleider** [comment] 2021-11-30 16:28
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2021-11-30 16:28 UTC
Labels: T: bug, T: enhancement, C: VTextField
