### ISSUE TITLE
[Bug Report] Tooltips not properly aligned with speed-dial buttons

### ISSUE THREAD

**Issue by smanji** [vuetifyjs/vuetify#3474] opened 2018-03-05 19:13 UTC
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.13.3

### Steps to reproduce
1. Open the reproduction link in codepen
2. Click on the floating button in the bottom right corner of the page
3. Observe the speed-dial buttons pop up
4. Observe that the tool tips to the left of each speed-dial button are not vertically aligned with the speed-dial buttons

### Expected Behavior
I would expect that the vertical center of each tool-tip would be vertically centered with each speed dial button

### Actual Behavior
The tool tip does appear to the left of each speed dial button, but the top of the tool tip is aligned with the center of the button instead of the vertical center of the tool tip being aligned with the center of the button. So it looks off...

### Reproduction Link
[https://codepen.io/smanji/pen/oErXzM?&editors=111](https://codepen.io/smanji/pen/oErXzM?&editors=111)

**Comment by nekosaur** [comment] 2018-03-08 11:02
This is because the tooltip detaches to app root, so when the buttons get transformed the tooltips don't follow. Adding `attach` prop to tooltip fixes that problem, but it seem like the position calculation is off.

**Comment by KaelWD** [comment] 2018-03-08 12:39
See #3399

**Comment by smanji** [comment] 2018-03-09 18:02
Thanks @KaelWD -- that workaround works for me too! It would be great if that could be added as an example in the Vuetify docs, assuming you're not going to support this in a cleaner way in the future.

**Comment by johnleider** [comment] 2020-01-19 18:18
I'm going to classify this as a wontfix. The issue is due to the animation and less about tooltip itself. We will handle this functionality in #3399

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-01-19 18:18 UTC
Labels: C: VBtn, T: bug
