### ISSUE TITLE
[Bug Report] Scrollbar is enabled when opening a dialog

### ISSUE THREAD

**Issue by sagikarni** [vuetifyjs/vuetify#3648] opened 2018-03-22 12:20 UTC
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.16
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
click the button to open a dialog

### Expected Behavior
Page scroll shoud not be enabled while the dialog is open.

### Actual Behavior
Scroll is disabled

### Reproduction Link
[https://codepen.io/pen/?&editors=101](https://codepen.io/pen/?&editors=101)

### Other comments
Look how facebook imlemented it , just go to any post and share it : a dialog will open wehile the page scroll bars are visible but not active.

**Comment by Revln9** [comment] 2018-03-22 15:32
The html tag has the overflow-y property set to scroll , just change it to auto 

```
<style>
html { overflow-y:auto !important } ;
</style>
```

**Comment by sagikarni** [comment] 2018-03-23 04:12
setting the scroll overflow-y to auto does not seems to do the work,
Take a look : 
![overflow](https://user-images.githubusercontent.com/16361670/37811180-92ef673a-2e69-11e8-87f3-33526c2cd087.png)

**Comment by Revln9** [comment] 2018-03-23 04:40
Sorry , i misread the title and  was talking about another bug  , sidebar toggle with a layout triggers the scroll . Now about this one  i don't think this is a bug , i think it was done intentionally to let you scroll while having a dialog open.

**Comment by nekosaur** [comment] 2018-03-23 07:41
You need to save the codepen and paste the new URL

**Comment by sagikarni** [comment] 2018-03-23 09:05
Hi,
1. I have explored some popular web apps (facebook , linkedin , pinterst and more) and I have never seen case where the scroll is still enabled while a dialog is open.
It seems a bit stramge since the idea of a dialog is to block al other behaviours and funcationalities.
If you have large sites that do you since pattern (scroll still enabled while dialog is open) I'd be glad if you can share.
2. when setting the overflow-y : auto !important though chrome developer toolbar nothing really happened... (Code pen creates an inner scroll and not page level scroll and thts why I can repreduce it there)

Thanks
Sagi

**Comment by nekosaur** [comment] 2018-03-23 10:02
As I mentioned in my previous comment, you need to give us a proper link to a codepen reproduction. The one in your original issue links to an empty codepen.

**Comment by tim7004** [comment] 2018-03-27 07:16
I also have this problem in mobile safari. When I visit https://vuetifyjs.com/en/components/dialogs in ios safari and open the dialog, I can still scroll the background.

**Comment by sagikarni** [comment] 2018-03-27 09:46
I can not post it in codepen as the presentation mode is not enabled for my account. Without presentation mode I'm unable to repreduce it on codepen.
However you can clearly see it in action on https://vuetifyjs.com/en/components/dialogs 
Click on "Open Dialog 2"  - and you will be able to scroll Take a look on facebook implementation 👍 
![facebook_1](https://user-images.githubusercontent.com/16361670/37959887-dfd8cffe-31bc-11e8-9112-81a795897dc5.png)
![facebook_2](https://user-images.githubusercontent.com/16361670/37959897-e2d4eca6-31bc-11e8-81a0-5380b3e8abaf.png)

**Comment by johnleider** [comment] 2018-06-24 02:31
Closing due to lack of reproduction environment.

**Closed by johnleider** 2018-06-24 02:31 UTC
Labels: S: need reproduction
