### ISSUE TITLE
[Bug Report][2.5.8] item-text breaks v-combobox when used in conjunction with v-model

### ISSUE THREAD

**Issue by goofy654** [vuetifyjs/vuetify#14023] opened 2021-08-04 07:07 UTC
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 92.0.4515.107
**OS:** Windows 10

### Steps to reproduce
Creating a combobox with three different options like in the following code works just fine ([Codepen A](https://codepen.io/jdoe2442/pen/OJmwGWQ?editors=1011)):

```html
<div id="app">
  <v-app>
    <v-container fluid>
          <v-combobox
              v-model="selectedItem"
              :items="items"
              item-text="label"
              label="Item"
              filled
          ></v-combobox>
    </v-container>
  </v-app>
</div>
```

```javascript
const myVue = new Vue({
  el: '#app',
  vuetify: new Vuetify(),
  data() {
    return {
      selectedItem: null,
      items: [
        {id: 1, label: "one"},
        {id: 2, label: "two"},
        {id: 3, label: "three"}
      ]
    };
  }
});
```

However, changing the `item-text` to something like this will break the combobox ([Codepen B](https://codepen.io/jdoe2442/pen/abWjMEM?editors=1011)):

```html
<v-combobox
    :item-text="item => item.label.toUpperCase()"
    ...
></v-combobox>
```

### Expected Behavior
Other than the combobox options now appearing in uppercase letters, everything should work the same.

### Actual Behavior
Selecting a combobox option will now only work on the first try. It's impossible to select a different option after that.

### Reproduction Link
<a href="https://codepen.io/jdoe2442/pen/abWjMEM?editors=1011" target="_blank">https://codepen.io/jdoe2442/pen/abWjMEM?editors=1011</a>

### Other comments
This issue originates from the following StackOverflow question: https://stackoverflow.com/questions/68642863/vuetify-item-text-attribute-breaks-v-combobox
The suggested solution to use `:value` rather than `v-model` works just fine. But I'm not sure whether it shouldn't work with `v-model` as well.

**Comment by KaelWD** [comment] 2021-09-25 08:51
Duplicate of #13544

**Closed by KaelWD** 2021-09-25 08:51 UTC
Labels: C: VCombobox, S: triage
