### ISSUE TITLE
[Bug Report] Expansion-panel. Dont work autofocus (scroll)

### ISSUE THREAD

**Issue by sinitsyn-alex** [vuetifyjs/vuetify#5004] opened 2018-08-31 13:00 UTC
### Versions and Environment
**Vuetify:** 1.2.1
**Last working version:** 1.2.1
**Vue:** 2.5.17
**Browsers:** Chrome 67.0.3396.99
**OS:** Linux x86_64

### Steps to reproduce
1. Open moscow panel
2. Scroll to samara panel
3. Open samara panel

### Expected Behavior
Autoscroll to samara header

### Actual Behavior
Dont work autofocus (scroll)

### Reproduction Link
[https://codepen.io/anon/pen/pORaZd](https://codepen.io/anon/pen/pORaZd)

**Comment by KaelWD** [comment] 2018-08-31 13:05
Duplicate of #3947

**Closed by KaelWD** 2018-08-31 13:05 UTC
