### ISSUE TITLE
[Bug Report][3.3.23] VSelect itemChildren doen't work

### ISSUE THREAD

**Issue by RadekBucki** [vuetifyjs/vuetify#18939] opened 2023-12-27 17:07 UTC
### Environment
**Vuetify Version:** 3.3.23
**Vue Version:** 3.3.7
**Browsers:** Chrome 120.0.0.0
**OS:** Windows 10

### Steps to reproduce
Click on select

### Expected Behavior
Category tree should be displayed

### Actual Behavior
Only root categories are displayed

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNU02PmzAQ/SuWL7RSwG23hwolm11tjz2u9hJycGDSdeUv2SZtFeW/d2ygEGjUlZBgZt57M56Hd2fqXc0erS1OLdCSrgMoK3mA+0oTsj7l3Nr0mYLa6MCFBtenMPny2AZTGyRBgCFLyClXpgG5qagHCXWA5glFvxv3u6IjSvJDwqT3tKDNVx74M/wKWO2Cb3OMaYPEWZoxUwqc3iOj7noJ8FNCLYE7fpCTMRPj6VXIxoFGYgzJ5p7E97ao+wLZbsluP5VKvGcRJCxImiuIhGwydrbgvnDZzrkjiA0rZ/Odx0xnyZpNrMLQ107YQDyEtnNMKGtcIGfi4Egu5OiMIhm6nEU4bsNoH+HX7pBNhL/TrZTvR9S4z76+6+Y7DwPHQ5ck+6vyMVsNpWGJJelJV8R/kosJ/abEQuaG1FyMkMtVvJ9EY2XIDplbJ/00iHfAPS5tzTor0AS6op0LueK2+OGNxiuWpND5VMAftBzEK4ruxLiiryFYXzJWNxppeJHEyRUaAtNWsQeEMdfqIBTkjVEPd8Xn4kPu6uKONcKHaa0Ar/KDMz89OFSqaD9u6hXEEa/jf/v1yNTmS9ehT+V4cX1ssZBm2O8ELkfXGnDg3nqsGW1xtFl9cbw4wqXS+NDLio5sdCKNT/d/AKRnhj8=)

**Comment by KaelWD** [comment] 2023-12-29 05:47
Duplicate of #3049

**Closed by KaelWD** 2023-12-29 05:47 UTC
Labels: S: triage

**Comment by RadekBucki** [comment] 2023-12-29 21:11
> Duplicate of #3049

If this is open feature request why I can see this in documentation and why IDE give me hint that this option is available in VSelect?

**Comment by KaelWD** [comment] 2023-12-30 04:15
The prop is inherited from VList but not used.
