### ISSUE TITLE
[Bug Report][3.5.1] Selecting a date for Feb 2023 selects Mar 2023

### ISSUE THREAD

**Issue by ExaltedJim** [vuetifyjs/vuetify#19114] opened 2024-01-29 08:56 UTC
### Environment
**Vuetify Version:** 3.5.1
**Vue Version:** 3.4.15
**Browsers:** Edge 121.0.0.0
**OS:** Windows

### Steps to reproduce
Use the month navigator to navigate back to Feb 2023
Select a day of the month
The date displayed will be for Mar 2023 instead of Feb 2023
Only seems to happen for Feb (though I haven't exhaustively tested every month).

### Expected Behavior
Month set to Feb 2023

### Actual Behavior
Month set to Mar 2023

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVjlsKAjEMRbdS8u20qCOCVMF1WD9KJ0J1bEtfIuLejfWBfiVcTs7N7gYpGrENgdeCsAKZ8RxGnXGjHGOydsa7rK3D2IIWRX9hx5KyPVzXClLQBjsdfXGDgjfVuIE0XbDmhJHhiFVn6x1dzHripPgDPnZKSf8qp/23XYrvb3CfwJz3fAnPueBT2D8ArVhA4Q==)

### Other comments
This happens with date pickers displayed in the documentation, for any that have a month navigator.

**Comment by KaelWD** [comment] 2024-01-30 11:34
Duplicate of #19087

**Closed by KaelWD** 2024-01-30 11:34 UTC
Labels: duplicate
