### ISSUE TITLE
[Feature Request] v-simple-table

### ISSUE THREAD

**Issue by manimovassagh** [vuetifyjs/vuetify#14513] opened 2021-12-14 23:30 UTC
### Problem to solve
I want to disable the Hover Effect and Default behavior of Vue simple Table.
i want to make each row highlited after click of user and keep the highlighted rows.

### Proposed solution
I just tried every options but it can not be disabled.
with this css
 tbody tr:hover { 
background-color: transparent !important; 
} 
it seems to be clear but after making custom classes this hover is still there .
Thanks if somebody have a soloution for that

**Comment by KaelWD** [comment] 2021-12-16 18:13
Duplicate of #5787

**Closed by KaelWD** 2021-12-16 18:13 UTC
Labels: S: triage

**Comment by manimovassagh** [comment] 2021-12-20 21:16
Thanks Kael,
Note that Number #5787 is for Data Table . Mein Issue was with Simple Table .
