### ISSUE TITLE
[Bug Report] Unknown custom element: <sheet-footer>

### ISSUE THREAD

**Issue by gimyboya** [vuetifyjs/vuetify#6314] opened 2019-02-01 00:15 UTC
### Versions and Environment
**Vuetify:** 1.5.0-beta.3
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
invoke `v-sheet` as by the docs examples

### Expected Behavior
everything should work fine and the `v-sheet` component renders normally

### Actual Behavior
throws an error
```
Unknown custom element: <sheet-footer>
```

### Reproduction Link
<a href="https://codepen.io/gimyboya/pen/ErWyLw" target="_blank">https://codepen.io/gimyboya/pen/ErWyLw</a>

**Comment by jacekkarczmarczyk** [comment] 2019-02-01 03:14
I don't see any error like this in the codepen. Closing until the reproduction that show the problem is provided

**Closed by jacekkarczmarczyk** 2019-02-01 03:14 UTC
