### ISSUE TITLE
[Bug Report] Label not shown on v-text-field with type "color"

### ISSUE THREAD

**Issue by pSchaub** [vuetifyjs/vuetify#3467] opened 2018-03-05 11:07 UTC
### Versions and Environment
**Vuetify:** 1.0.4
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Mac OS 10.13.3

### Steps to reproduce
See reproduction link (codepen).
1. Open link.
2. See that the label of the text field is not shown.
3. Click on text field to open browser color selection and see label.

### Expected Behavior
Label should not be outside view because of browser color selection

### Actual Behavior
Label is outside view ("behind color selection of the browser")

### Reproduction Link
[https://codepen.io/anon/pen/mXYjLm](https://codepen.io/anon/pen/mXYjLm)

**Comment by KaelWD** [comment] 2018-03-05 13:13
You can use `class="input-group--dirty"` to force the label to rise.  
I don't think we officially support `type` at this stage, possible duplicate of #2717?

**Comment by jacekkarczmarczyk** [comment] 2018-03-05 13:41
Looks like https://github.com/vuetifyjs/vuetify/issues/1309

**Comment by KaelWD** [comment] 2018-03-05 14:01
yep, just need to add to that array
![image](https://user-images.githubusercontent.com/16421948/36978882-cf147590-20d9-11e8-84e2-85354394599f.png)

**Closed** 2018-03-10 16:06 UTC
Labels: bug, good first issue
