### ISSUE TITLE
[Bug Report][3.3.11] Directive "v-click-outside" does not respond correctly to the right mouse button

### ISSUE THREAD

**Issue by kuyoru-kamikisho** [vuetifyjs/vuetify#17942] opened 2023-08-02 02:10 UTC
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.2.46
**Browsers:** Edge 114.0.1823.43
**OS:** Windows

### Steps to reproduce
Just see the [codepen](https://codepen.io/kuyoru-kamikisho/pen/MWzLYEJ)

### Expected Behavior
The right mouse button should also be considered a click event in many scenarios

### Actual Behavior
v-livk-outside does not respond to the right mouse button

### Reproduction Link
[https://codepen.io/kuyoru-kamikisho/pen/MWzLYEJ](https://codepen.io/kuyoru-kamikisho/pen/MWzLYEJ)

**Comment by KaelWD** [comment] 2023-08-09 08:50
Duplicate of #11982

**Closed by KaelWD** 2023-08-09 08:50 UTC
Labels: S: triage
