### ISSUE TITLE
[Bug Report] v-autocomplete component with readonly property enabled is not readonly

### ISSUE THREAD

**Issue by lowerends** [vuetifyjs/vuetify#5524] opened 2018-11-05 12:54 UTC
### Versions and Environment
**Vuetify:** 1.3.5
**Vue:** 2.5.17
**Browsers:** Google Chrome
**OS:** Mac OSX

### Steps to reproduce
The linked codepen is the official example from the docs.

1. Put the cursor in the "State" field
2. Enter some text
3. Press spacebar or hit enter key

### Expected Behavior
1. The text field is focussed
2. No text nor a dropdown is visible
3. No text nor a dropdown is visible 

### Actual Behavior
1. Ok
2. Ok
3. Dropdown is opened and value can be selected

### Reproduction Link
<a href="https://codepen.io/anon/pen/XyJoqL" target="_blank">https://codepen.io/anon/pen/XyJoqL</a>

**Comment by jacekkarczmarczyk** [comment] 2018-11-05 13:04
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5005

**Closed by jacekkarczmarczyk** 2018-11-05 13:04 UTC

**Comment by lowerends** [comment] 2018-11-05 13:14
Sorry for the duplicate. I looked for autocomplete and readonly in the issue list. Didn't think of the select component as well.
