### ISSUE TITLE
[Bug Report] Checkboxes not working with FontAwesome 5 Kits

### ISSUE THREAD

**Issue by P4sca1** [vuetifyjs/vuetify#11020] opened 2020-04-04 09:47 UTC
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Mac OS 10.15.4

### Steps to reproduce
Toggle the checkbox.

### Expected Behavior
It should show an icon inside when the checkbox is checked.

### Actual Behavior
The checkbox looks identical to an unchecked checkbox when it is checked.

### Reproduction Link
<a href="https://codepen.io/p4sca1/pen/oNXROax" target="_blank">https://codepen.io/p4sca1/pen/oNXROax</a>

### Other comments
FontAwesome 5 Kits are a new feature of FontAwesome where icons are loaded async when they are needed, so that you don't have to import the whole FontAwesome library.
This might not be an issue with Vuetify, but with the Font Awesome Loader not being able to detect a change to the icon due to the way Vue works.

**Comment by KaelWD** [comment] 2020-04-04 11:06
Duplicate of #3505

**Closed by KaelWD** 2020-04-04 11:06 UTC
Labels: triage

**Comment by P4sca1** [comment] 2020-04-04 11:11
@KaelWD In how far is this issue related tot he mentioned issue? I can’t find a resolution to this issue in it.

**Comment by KaelWD** [comment] 2020-04-04 11:35
There isn't one, you can't use fontawesome JS with vuetify. If you only want to load a subset of icons you have to use SVGs manually.

**Comment by P4sca1** [comment] 2020-04-04 12:20
@KaelWD Alright thank you for the clarification. I did find a way to use Font Awesome 5 Kits with Vuetify. I greatly prefer them over `vue-fontawesome` because you dont have to import each item manually and it doesn't pollute your dev `vendors.app.js` (when using nuxt.js) with 30MB of icons.

Create a wrapper component `v-fa-icon`:
```vue
<template>
  <i :class="icon" />
</template>

<script>
  export default {
    props: {
      icon: { type: String, required: true },
    },
  }
</script>
```

And then where you initiate vuetify:
```js
import VFaIcon from 'path/to/the/wrapper/component.vue'
Vue.component('v-fa-icon', VFaIcon)

const ICONS_FONTAWESOME: VuetifyIcons = {
  complete: { component: 'v-fa-icon', props: { icon: 'fas fa-check' } },
  cancel: { component: 'v-fa-icon', props: { icon: 'fas fa-times-circle' } },
  close: { component: 'v-fa-icon', props: { icon: 'fas fa-times' } },
  delete: { component: 'v-fa-icon', props: { icon: 'fas fa-times-circle), ' } }, // delete (e.g. v-chip close
  clear: { component: 'v-fa-icon', props: { icon: 'fas fa-times-circle), ' } }, // delete (e.g. v-chip close
  success: { component: 'v-fa-icon', props: { icon: 'fas fa-check-circle' } },
  info: { component: 'v-fa-icon', props: { icon: 'fas fa-info-circle' } },
  warning: { component: 'v-fa-icon', props: { icon: 'fas fa-exclamation' } },
  error: {
    component: 'v-fa-icon',
    props: { icon: 'fas fa-exclamation-triangle' },
  },
  prev: { component: 'v-fa-icon', props: { icon: 'fas fa-chevron-left' } },
  next: { component: 'v-fa-icon', props: { icon: 'fas fa-chevron-right' } },
  checkboxOn: {
    component: 'v-fa-icon',
    props: { icon: 'fas fa-check-square' },
  },
  checkboxOff: { component: 'v-fa-icon', props: { icon: 'far fa-square' } }, // note 'far'
  checkboxIndeterminate: {
    component: 'v-fa-icon',
    props: { icon: 'fas fa-minus-square' },
  },
  delimiter: { component: 'v-fa-icon', props: { icon: 'fas fa-circle' } }, // for carousel
  sort: { component: 'v-fa-icon', props: { icon: 'fas fa-sort-up' } },
  expand: { component: 'v-fa-icon', props: { icon: 'fas fa-chevron-down' } },
  menu: { component: 'v-fa-icon', props: { icon: 'fas fa-bars' } },
  subgroup: { component: 'v-fa-icon', props: { icon: 'fas fa-caret-down' } },
  dropdown: { component: 'v-fa-icon', props: { icon: 'fas fa-caret-down' } },
  radioOn: { component: 'v-fa-icon', props: { icon: 'far fa-dot-circle' } },
  radioOff: { component: 'v-fa-icon', props: { icon: 'far fa-circle' } },
  edit: { component: 'v-fa-icon', props: { icon: 'fas fa-edit' } },
  ratingEmpty: { component: 'v-fa-icon', props: { icon: 'far fa-start' } },
  ratingFull: { component: 'v-fa-icon', props: { icon: 'fas fa-star' } },
  ratingHalf: { component: 'v-fa-icon', props: { icon: 'fas fa-star-half' } },
  loading: { component: 'v-fa-icon', props: { icon: 'fas fa-sync' } },
  first: { component: 'v-fa-icon', props: { icon: 'fas fa-step-beckward' } },
  last: { component: 'v-fa-icon', props: { icon: 'fas fa-step-forward' } },
  unfold: { component: 'v-fa-icon', props: { icon: 'fas fa-arrows-alt-v' } },
  file: { component: 'v-fa-icon', props: { icon: 'fas fa-paperclip' } },
}

new Vuetify({
    // ... your vuetify config
    icons: {
      values: ICONS_FONTAWESOME,
    },
})
```
