### ISSUE TITLE
[Bug Report] Textfield no longer working on mobile

### ISSUE THREAD

**Issue by rh78** [vuetifyjs/vuetify#11201] opened 2020-04-23 08:07 UTC
### Environment
**Vuetify Version:** 2.2.23
**Last working version:** 2.1.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.111
**OS:** Android 9

### Steps to reproduce
Just try on your own components documentation page :) Enter text to a text box - on solo hint does not go away. When you click outside of the textbox text is lost. Somehow it seems the textfield is just not accepting the input.

Works fine on desktop (even using Chrome touch emulation).

### Expected Behavior
Should work normally

### Actual Behavior
Does not work (does not store value)

### Reproduction Link
<a href="https://codepen" target="_blank">https://codepen</a>

**Comment by BernardoBernal** [comment] 2020-04-25 15:34
The problem is also in v-text-area, the value not refresh and sometimes the value disappear. When I debugging in Chrome inspect devices, the input works correctly.
Vuetify Version: 2.2.23
Vue Version: 2.6.11
Browsers: 81.0.4044.122
OS: Android 7.1.1.

I think that problem is for the new Google Keyboard update.

**Comment by rh78** [comment] 2020-04-25 16:23
Definitely it is, as 2.2.22 works.

**Comment by jacekkarczmarczyk** [comment] 2020-04-25 17:49
how about 2.2.25?

**Comment by BernardoBernal** [comment] 2020-04-25 17:58
I'm testing on 2.2.25 and for now it works.

**Comment by rh78** [comment] 2020-04-25 18:48
2 releases a day? :) I will test on Monday but I already saw the fix PR and I am confident it will work!

**Comment by VetBoard** [comment] 2020-05-01 11:26
I had v2.2.22 and I was having the same problem. Updated today to 2.2.26 and it's fixed. Thank you

**Comment by johnleider** [comment] 2020-05-06 04:30
Closing as resolved.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2020-05-06 04:30 UTC
Labels: C: VTextField, triage
