### ISSUE TITLE
[Feature Request] v-data-table GroupBy icon, text and align

### ISSUE THREAD

**Issue by michaelsogos** [vuetifyjs/vuetify#12130] opened 2020-08-27 21:14 UTC
### Problem to solve
The possibility to place an icon instead of the word "group", or at least change the label "group" to a language specific word.
Also good to set its position, actually is very close to the SORT ARROW. Eventually it could be align to the right of the header cell.

### Proposed solution
An idea could be to add the following options to v-data-table-header.options:
- group-by-icon
- group-by-text
- group-by-position -> [left, center, right] (where right should be the default, on RTL it should be on the left)

**Comment by jacekkarczmarczyk** [comment] 2020-10-24 16:18
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8186

**Closed by jacekkarczmarczyk** 2020-10-24 16:18 UTC
Labels: C: VDataTable, T: feature
