### ISSUE TITLE
v-select: Initially set selected value is not selected, if item's data is dynamically loaded

### ISSUE THREAD

**Issue by srinivasayellapu** [vuetifyjs/vuetify#1864] opened 2017-09-24 09:34 UTC
### Steps to reproduce
1) Set value selected before item's data loading
2)  `v-select` with items being loaded dynamically. Now the initially set selected value is not shown as selected in `v-select`

### Versions

Vue@2.4.4
Vuetify@0.15.7
OS: Windows-10
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### What is expected ?

`v-select` needs to show initially selected value even though item's data is dynamically loaded

### What is actually happening ?

`v-select` is not showing initially selected value when item's data is dynamically loaded

### Reproduction Link

[https://codepen.io/anon/pen/YrpVjq?editors=1010](https://codepen.io/anon/pen/YrpVjq?editors=1010)
Description about example:
1) Static List: Initial value is set & its static item's data, so everything works fine
2) Dynamic List Loading: Initial value is set before Item's data loading
3) Dynamic List Loading (Multiselect): Initial value is set before Item's data loading

**Comment by KaelWD** [comment] 2017-09-24 09:40
Duplicate of #1743

**Closed** 2017-09-24 09:47 UTC
