### ISSUE TITLE
Include in a single component date and time together

### ISSUE THREAD

**Issue by fgutr** [vuetifyjs/vuetify#1168] opened 2017-07-28 15:40 UTC
What will it allow you to do that you can't do today?
Select date and time in a single component
How will it make current work-arounds straightforward?
Reduce the code in the view
What potential bugs and edge cases does it help to avoid?
None at the moment

**Comment by johnleider** [comment] 2017-07-28 15:58
Duplicate of #459

**Closed by johnleider** 2017-07-28 15:58 UTC
