### ISSUE TITLE
[Bug Report] Outlined date picker text field labels are misplaced

### ISSUE THREAD

**Issue by Kotoriii** [vuetifyjs/vuetify#9373] opened 2019-10-16 08:52 UTC
### Environment
**Vuetify Version:** 2.1.4
**Last working version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.14.5

### Steps to reproduce
- Observe label being crossed out by outline
- Same behavior when text field is focused

### Expected Behavior
- Label is aligned properly within the empty space between outline

### Actual Behavior
- Label is misplaced / crossed out by outline

### Reproduction Link
<a href="https://codepen.io/kotoriii/pen/XWWKpQV" target="_blank">https://codepen.io/kotoriii/pen/XWWKpQV</a>

### Other comments
It's even worse in my actual application
![Issue is even worse in my application](https://i.imgur.com/ra13EYZ.png)

**Comment by ascott18** [comment] 2019-10-16 15:34
Similar to https://github.com/vuetifyjs/vuetify/issues/9225

**Comment by jacekkarczmarczyk** [comment] 2019-11-09 06:08
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9225
(and nothing to do with datepicker, https://codepen.io/jkarczm/pen/ExxRLGZ)

**Closed by jacekkarczmarczyk** 2019-11-09 06:08 UTC
Labels: C: VTextField, duplicate

**Comment by gcho91** [comment] 2020-04-15 22:04
For everyone else: updating your Vuetify dependency to the latest version seems to fix this problem. went from 2.1.0 to latest @ 2.2.11 and the problem no longer persists.
