### ISSUE TITLE
[Bug Report] v-img with svg is not loading in Firefox

### ISSUE THREAD

**Issue by Owen-Tsai** [vuetifyjs/vuetify#11426] opened 2020-05-18 03:21 UTC
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 2.6.11
**Browsers:** Mozilla Firefox
**OS:** Windows 10

### Expected Behavior
Expect Vuetify to get the correct size of the SVG file and set it as the background

### Actual Behavior
SVG image is not displayed

### Reproduction Link
<a href="https://codepen.io/Lem0/pen/bGVQVqV?editors=1000" target="_blank">https://codepen.io/Lem0/pen/bGVQVqV?editors=1000</a>

### Other comments
- Works fine when the source image is in png/jpg format.
- Works fine when using Safari, Chrome
- Works fine when `aspect-ratio` attribute is specified
- Works fine when using `img` tag instead.

**Comment by michael-harrison** [comment] 2020-07-27 22:57
@ElijahKotyluk looks like the problem is not platform specific but more browser specific.  We're experiencing the same problem on OSX: 

__Vuetify Version:__ 2.2.31
__Vue Version:__ 2.6.11
__Browsers:__ Mozilla Firefox 78.0.2 (64-bit)
__OS:__ MacOS 10.15.6

Until a fix is in place we're having to set the `aspect-ratio` on `v-img` elements.

**Comment by kp2356** [comment] 2020-09-17 07:26
Solution for time being would be to provide `height` & `width` both

**Comment by YipingRuan** [comment] 2020-12-14 12:24
Seems width is correct, but height is 0
![image](https://user-images.githubusercontent.com/5492274/102080921-47522580-3e4a-11eb-9e78-bb8a5622b72c.png)

By setting height:
![image](https://user-images.githubusercontent.com/5492274/102080862-2ab5ed80-3e4a-11eb-84cf-aec7c7b1ae76.png)

**Closed** 2020-12-21 07:39 UTC
Labels: C: VImg, T: bug, V3: Phase 1, platform specific
