### ISSUE TITLE
[Bug Report] Lists with sub group closing and opening

### ISSUE THREAD

**Issue by jd-0001** [vuetifyjs/vuetify#13186] opened 2021-03-01 15:24 UTC
### Environment
**Vuetify Version:** 2.4.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 88.0.4324.182
**OS:** Linux x86_64

### Steps to reproduce
1. Open both subgroups (admin & actions)
2. Close container group (users)
3. Reopen container group (users)

### Expected Behavior
When we reopen the container group (users) both subgroups (admin & actions) shall be collapsed from the start.

### Actual Behavior
When we reopen the container group (users), both subgroups collapse (admin & actions) at the time container group (users) is expanding.

Giving weird height change and animation.

### Reproduction Link
<a href="https://codepen.io/jd-0001/pen/MWbGWzd" target="_blank">https://codepen.io/jd-0001/pen/MWbGWzd</a>

**Comment by KaelWD** [comment] 2021-03-04 07:11
Duplicate of #5120

**Closed by KaelWD** 2021-03-04 07:11 UTC
Labels: triage
