### ISSUE TITLE
[Bug Report][3.7.3] The placeholder is not displayed when the value is changed to null

### ISSUE THREAD

**Issue by VitalyCharov** [vuetifyjs/vuetify#20589] opened 2024-10-17 14:27 UTC
### Environment
**Vuetify Version:** 3.7.3
**Vue Version:** 3.5.12
**Browsers:** Chrome 128.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1. choose any value
2. click on the Clear button

### Expected Behavior
placeholder should be displayed

### Actual Behavior
placeholder is not displayed

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpVUMFuwjAM/RUrl2wSrHdUqk37DMohBFeLliZR4vQA4t9xUqDlEufZz37PPlxFirr5CeFryih2oiUcg1WEXe8A2mmrQqjfCrR3pIzD+EjNjExee+5CwmcaYNqO/ox234tJ2YypF0ttZ1glcanGdYWlNf55e8bI5RVaSF3bvGuuvZzIwbe2Rv+/hGEPLlvbi+7Xooqlm1nPnRi9L1Wn153bZnULhklHEwgSUp5PYsbgI8EVIg5wgyH6ESSfURY6AM9NBHVF9nCQg/dyA/KkYgmDuVwqzByPC/9lmod+FOOfxcmszaritinJ+hzvrHeRhw==)

**Comment by MatthewAry** [comment] 2024-11-15 14:13
Duplicate of #20660

**Closed by MatthewAry** 2024-11-15 14:13 UTC
Labels: S: triage
