### ISSUE TITLE
[Bug Report] Input text prefix fixed width - doesn't move input value

### ISSUE THREAD

**Issue by Raiven66** [vuetifyjs/vuetify#4632] opened 2018-07-17 10:43 UTC
### Versions and Environment
**Vuetify:** 1.1.4
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
add multiple characters into the prefix prop

### Expected Behavior
the prefix will be fully visible and the field value will be next to it

### Actual Behavior
prefix is obscured by the value of the input field

### Reproduction Link
[https://codepen.io/anon/pen/ajNgJb?&editors=100](https://codepen.io/anon/pen/ajNgJb?&editors=100)

**Comment by jacekkarczmarczyk** [comment] 2018-07-17 10:48
Duplicate of https://github.com/vuetifyjs/vuetify/issues/3485

**Closed by jacekkarczmarczyk** 2018-07-17 10:48 UTC
