### ISSUE TITLE
[Bug Report] Textfield Autofocus in Popover Menu

### ISSUE THREAD

**Issue by jingzheshan** [vuetifyjs/vuetify#2631] opened 2017-11-24 22:11 UTC
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.8
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 10

### Steps to reproduce
Please use codepen link and gif as a reference

### Expected Behavior
It should autofocus into the textfield properly.

### Actual Behavior
Focus sequence is wrong.

### Reproduction Link
[https://codepen.io/jingzheshan/pen/wPXNjq](https://codepen.io/jingzheshan/pen/wPXNjq)

![1](https://user-images.githubusercontent.com/2770401/33224711-433f3f8e-d1d1-11e7-9021-2e3e8333e60d.gif)

**Comment by jacekkarczmarczyk** [comment] 2017-11-25 04:13
Duplicate of #1731, #1587 and few others

**Closed by jacekkarczmarczyk** 2017-11-25 04:13 UTC
