### ISSUE TITLE
[Bug Report] rounded v-text-field inside v-stepper has issue with line through label when it raises to the top

### ISSUE THREAD

**Issue by DedicatedManagers** [vuetifyjs/vuetify#9884] opened 2019-12-05 06:26 UTC
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Put v-text-field with rounded attribute inside v-stepper.  With no v-model or placeholder, it works properly.  With v-model or placeholder set, the label raises to the top and has a line through it.

### Expected Behavior
Label should not have line through it.

### Actual Behavior
Label has line through it.

### Reproduction Link
<a href="https://codepen.io/DedicatedManager/pen/wvBazbo?editors=1011" target="_blank">https://codepen.io/DedicatedManager/pen/wvBazbo?editors=1011</a>

### Other comments
Issue happens in Firefox as well as chrome.

**Comment by jacekkarczmarczyk** [comment] 2019-12-05 06:29
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9225

**Closed by jacekkarczmarczyk** 2019-12-05 06:29 UTC
Labels: triage
