### ISSUE TITLE
[Bug Report] v-carousel with transitions adds divs that push content up and down (appears to scroll on transition)

### ISSUE THREAD

**Issue by oscarmrom** [vuetifyjs/vuetify#13247] opened 2021-03-10 16:45 UTC
### Environment
**Vuetify Version:** 2.4.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 88.0.4324.182
**OS:** Mac OS 11.2.3

### Steps to reproduce
https://codepen.io/oscarmrom/pen/abBQgyW

Scroll down in the page a bit but keep the carousel visible. 
Wait for the cycle timer to go to the next slide or manually click forward/backward. 

You will either be scrolled down or up on the page depending on if you're restarting the deck or moving forward. 

It appears to be the manner in which new slides are added in as <divs> which pushes the content "down" in a way. 

### Expected Behavior
Have transitions without being "scrolled' up or down on the page. 

### Actual Behavior
"Scrolls" you down or up on the page when the carousel goes to the next slide.

### Reproduction Link
<a href="https://codepen.io/oscarmrom/pen/abBQgyW" target="_blank">https://codepen.io/oscarmrom/pen/abBQgyW</a>

### Other comments
current vue version is actually 2.6.12 it is being used through gridsome version 0.7.23

**Comment by oscarmrom** [comment] 2021-03-10 16:48
current workaround is to exclude the `transition` and `reverse-transition` from the `v-carousel-item` definition. 

ex: `<v-carousel-item cycle></v-carousel>` (this is fine)

vs 

`<v-carousel-item cycle reverse-transition="fade-transition" transition="fade-transition"></v-carousel>` (this is not fine)

**Comment by KaelWD** [comment] 2021-07-30 06:48
Duplicate of #10613

**Closed by KaelWD** 2021-07-30 06:48 UTC
Labels: C: VCarousel, S: triage
