### ISSUE TITLE
[Feature Request] reopen #1516

### ISSUE THREAD

**Issue by mathiasleroy** [vuetifyjs/vuetify#9981] opened 2019-12-16 17:15 UTC
### Problem to solve
that issue was not solved, it's different than the solution that closed it #5551.
Adding touchless to the to v-tabs-items is a different solution.

Issue #1516 is about the v-tabs, that can be dragged left or right on small touchscreens.

### Proposed solution
Add a tag to disable touch scroll on mobile devices

**Comment by KaelWD** [comment] 2019-12-16 17:20
#5551 is not related to #1516

#1516 was fixed with #2838 and I cannot reproduce it any more.

**Closed by KaelWD** 2019-12-16 17:20 UTC
Labels: triage

**Comment by mathiasleroy** [comment] 2019-12-16 21:01
@KaelWD could you quickly try this?

https://codepen.io/Tardigrad/pen/vYEyJRXvYEyJRX
What I see is this: when opened in dev mode in 320x568 (= iPhone 5/SE) the tabs are horizontally scrollable.
when then moved to 375x667 this behaviour stays, (this behaviour doesn't appear when refreshing from 375x667)

when playing with the width, this behaviour appears <=372px and disappears >=420px 

I thought #1516 whas about being able to disable that horizontal scroll in any width.
Maybe we don't speak about the same thing and I misunderstood #1516.
My apologies if that's not the case.

**Comment by KaelWD** [comment] 2019-12-18 04:53
That looks correct aside from the bugged arrow on the left. There's still a small amount of overflow at 375px so it remains scrollable.
