### ISSUE TITLE
[Bug Report] v-autocomplete; the no-data slot button doesn't execute the function 

### ISSUE THREAD

**Issue by lucky993** [vuetifyjs/vuetify#5882] opened 2018-12-13 09:15 UTC
### Versions and Environment
**Vuetify:** 1.3.13
**Vue:** 2.5.17
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
1. open autocomplete
2. click on NO ITEMS button

### Expected Behavior
'SOMETHING' is written in the console

### Actual Behavior
Nothing is written in the console

### Reproduction Link
<a href="https://codepen.io/lucky993/pen/roOBdG" target="_blank">https://codepen.io/lucky993/pen/roOBdG</a>

**Comment by KaelWD** [comment] 2018-12-13 09:23
Duplicate of #5871 

Please make sure you've checked the latest version before opening an issue.

**Closed by KaelWD** 2018-12-13 09:23 UTC
