### ISSUE TITLE
[Bug Report]  v-time-picker emits 'change' after only selecting a new hour

### ISSUE THREAD

**Issue by riemervdzee** [vuetifyjs/vuetify#6045] opened 2019-01-03 16:27 UTC
### Versions and Environment
**Vuetify:** 1.4.0
**Last working version:** 1.3.15
**Vue:** 2.5.21
**Browsers:** Chromium 71.0.3578.80
**OS:** Linux

### Steps to reproduce
1. Use a v-time-picker in a menu as in the example https://vuetifyjs.com/en/components/time-pickers#time-pickers-in-dialog-and-menu
1. Open the menu by clicking the textfield, select a hour and a minute in the timepicker (expected behavior is observed only when the time is still null)
1. Open the menu again, select a hour and the menu will close right away

### Expected Behavior
After selecting a hour, the menu should remain open so the user has the option to change the minute as well. This behavior was observed properly in vuetify 1.3.15

### Actual Behavior
The menu closes directly after selecting a hour

### Reproduction Link
<a href="https://codepen.io/riemervdzee/pen/XoZMqE" target="_blank">https://codepen.io/riemervdzee/pen/XoZMqE</a>

### Other comments
It seems that 'change' is emitted directly when selecting a hour?

**Comment by jacekkarczmarczyk** [comment] 2019-01-04 02:56
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5951

**Closed by jacekkarczmarczyk** 2019-01-04 02:56 UTC
Labels: T: bug
