### ISSUE TITLE
[Feature Request] Improve v-pagination usability

### ISSUE THREAD

**Issue by tagorecaue** [vuetifyjs/vuetify#5136] opened 2018-09-21 02:57 UTC
### What problem does this feature solve?
When user clicks at last page before "..." they need to use next button at the end of pagination component to continue navigation. Example:
![bad pagination](https://user-images.githubusercontent.com/7309715/45857656-43e59780-bd30-11e8-99b4-d88d61d00c02.gif)

The same happen when is going back from last page.

### What is your proposed solution?
I propose to change this behavior by opening the middle pages when user clicks at last page before "..."
This will improve the navigation experience especially when dealing with lots of pages

**Comment by jacekkarczmarczyk** [comment] 2018-09-21 04:42
Duplicate of https://github.com/vuetifyjs/vuetify/issues/4760

**Closed by jacekkarczmarczyk** 2018-09-21 04:42 UTC
