### ISSUE TITLE
Datatables manipulates state of a vuex store

### ISSUE THREAD

**Issue by kpilard** [vuetifyjs/vuetify#332] opened 2017-04-08 09:41 UTC
### Steps to reproduce
- enable stirct mode in vuex
- set an Array from the store as v-model in a datatable

you can the the error message in the console

### Versions
v0.10.03

### What is expected ?
the datatable shoudn't manipulate the state in the store

### What is actually happening ?
the datatable manipulates the store directly and not with mutiations

### Reproduction Link
http://codepen.io/anon/pen/XMLejO?editors=1010

**Comment by johnleider** [comment] 2017-04-08 18:30
I'm not sure what the issue is.
The data table only uses v-model, the behavior is no different than if you were to use v-model on an input.

**Comment by kpilard** [comment] 2017-04-08 18:38
Its not allowed to manipulate the data in a store directly. You have to do it with mutations. Im only passing the data from the vuex store to the datatable and then i get an error message in the console: `Do not mutate vuex store state outside mutation handlers.`

Maybe the sort and filter functions mutate the v-model directly instead of an local copy?

**Comment by johnleider** [comment] 2017-04-08 18:44
Nope, it uses a computed property to generate the filtered results and only sends a mutation input when select-all is selected and used. From your example provided, I don't know what I'm looking for.

**Comment by nekosaur** [comment] 2017-04-08 18:48
The reason for the error is the sorting and/or search filtering that gets done in the data table. In filteredItems the v-model is reassigned.

```javascript
let items = this.value 
...
items = items.filter(etc etc)
...
items = items.sort(etc etc)
```
This will throw the vuex error

**Comment by kpilard** [comment] 2017-04-08 18:51
With the vuex strict mode (https://vuex.vuejs.org/en/strict.html) you can see an error in the browserconsole.

Example1 passes store data as v-model to datatable and throws an error:
http://codepen.io/anon/pen/XMLejO?editors=1010

Example2 doesnt pass the data to the datatable and there is no error in the console:
http://codepen.io/anon/pen/YZoBZy?editors=1010

**Closed** 2017-04-08 18:54 UTC
