### ISSUE TITLE
[Feature Request] Select menu items with space key

### ISSUE THREAD

**Issue by andreseloysv** [vuetifyjs/vuetify#4512] opened 2018-07-06 13:16 UTC
### Problem to solve
Today you use the key enter (key code 13) to select an item in the v-select component.
You can not use other letter for that task.

### Proposed solution
Have a props to set other key for example (space)

**Comment by KaelWD** [comment] 2018-07-06 13:28
Duplicate of #3287?

**Comment by andreseloysv** [comment] 2018-07-06 13:39
No, I mean when you have a multiselect and you want to select a item with the keyboard you press key arrowDown to come to the list and in the list you need press Enter to select an item. My question/feature is: Can I use other key for select an item like space key?

**Comment by KaelWD** [comment] 2018-07-07 09:53
No, but space should probably be supported for menus: https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20161214/examples/menu-button/menu-button-1/menu-button-1.html

**Comment by johnleider** [comment] 2022-04-06 15:15
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Closed by johnleider** 2022-04-06 15:15 UTC
Labels: T: enhancement, C: VSelect
