### ISSUE TITLE
[Bug Report] v-carousel height adjusted when device is rotated using breakpoints, v-carousel-item doesn't render the new height until the page is refreshed.

### ISSUE THREAD

**Issue by TechWACO** [vuetifyjs/vuetify#6090] opened 2019-01-09 19:05 UTC
### Versions and Environment
**Vuetify:** 1.4.1
**Vue:** 2.5.18
**Browsers:** Firefox 64.0, Google Chrome, Safari
**OS:** Mac OS 10.13

### Steps to reproduce
Visit the Codepen link on any mobile device, portrait orientation. Then rotate the device.

### Expected Behavior
The carousel should fit the whole screen in landscape along with the v-carousel-item image.

### Actual Behavior
The carousel should fit the whole screen in landscape, v-carousel updates properly but v-carousel-item doesn't render the new height and the image is crop. I works when the page is refreshed.

### Reproduction Link
<a href="https://codepen.io/waco/full/XoBRJp" target="_blank">https://codepen.io/waco/full/XoBRJp</a>

### Other comments
I think the injected data of internalHeight is not being updated.

**Comment by KaelWD** [comment] 2019-02-03 15:08
Duplicate of #6067

**Closed by KaelWD** 2019-02-03 15:08 UTC
Labels: T: bug, duplicate
