### ISSUE TITLE
[Feature Request] Validation rules to return a promise

### ISSUE THREAD

**Issue by mobsense** [vuetifyjs/vuetify#7071] opened 2019-04-24 23:01 UTC
### Problem to solve
I need to determine if a field is unique when validating a form. To do this, I need to access the IndexedDB which is an async API. So I would like validation rules to be able to return a Promise.

### Proposed solution
Allow rules to return a Promise which when fulfilled will return true | Validation message | Exception. A rejected promise could be mapped into a generic 'validation failed' message.

**Comment by KaelWD** [comment] 2019-04-25 00:36
Duplicate of #4231

**Closed by KaelWD** 2019-04-25 00:36 UTC
Labels: triage
