### ISSUE TITLE
[Bug Report] Enter in VSelect can trigger a "Cannot read property 'click' of undefined" error

### ISSUE THREAD

**Issue by everhardt** [vuetifyjs/vuetify#3649] opened 2018-03-22 14:09 UTC
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.162
**OS:** Mac OS 10.13.3

### Steps to reproduce
* Click on the select box with your mouse. "A" will then be selected.
* Type `B`
* Press the down arrow
* Press enter

### Expected Behavior
The dropdown will close and B will be selected

### Actual Behavior
The following error pops up in the console:
> vuetify.min.js:6 Uncaught TypeError: Cannot read property 'click' of undefined

That is a reference to https://github.com/vuetifyjs/vuetify/blob/f85456684bd7ef4e91ea34d297d6d1f3be7a98ad/src/components/VMenu/mixins/menu-keyable.js#L62

### Reproduction Link
[https://codepen.io/everhardt/pen/GxmaYv](https://codepen.io/everhardt/pen/GxmaYv)

**Comment by KaelWD** [comment] 2018-03-25 16:50
@chewy94 can you check this? I can't reproduce it on windows.

**Comment by jacekkarczmarczyk** [comment] 2018-03-25 17:06
I can reproduce on windows with the provided steps (click, "B", "Arrow down", "Enter")

**Comment by DaleBeckles** [comment] 2018-05-18 10:53
I can confirm that I am experiencing the same behavior as the OP.

**Comment by KaelWD** [comment] 2018-05-18 11:43
Fixed in 1.1

**Closed by KaelWD** 2018-05-18 11:43 UTC
Labels: pending review
