### ISSUE TITLE
[Feature Request] New v-chip selectable prop

### ISSUE THREAD

**Issue by laurent-brisbois** [vuetifyjs/vuetify#10983] opened 2020-03-31 14:38 UTC
### Problem to solve
When we don't want the `v-chip` component to be selectable, it would be nice to have a `selectable=false` option. As far as I'm concerned, I sometimes want to only have the `close`  that is clickable.
It would result in an unclickable `v-chip`, which wouldn't change on `hover` or on `click`. Because it triggers `active` changes,...

### Proposed solution
Add a `selectable` prop, true by default if you want, which would enables developpers to chose if it can be clicked/selected or not.

**Comment by ElijahKotyluk** [comment] 2020-04-02 13:29
The `v-chip` component has a `disabled` prop that gives the result you are looking for.

**Comment by laurent-brisbois** [comment] 2020-04-02 14:20
> The `v-chip` component has a `disabled` prop that gives the result you are looking for.

No you're wrong. Do you think I didn't try ? When setting the `disabled` prop, the `close` icon is no longer clickable.

Thanks for the `layer 8 issue` by the way..

**Comment by laurent-brisbois** [comment] 2020-04-02 14:33
Here is the `v-chip` I use :

<v-chip
   v-for="group in user.groupIds"
   :key="group.id"
   close
   @click:close="removeGroupFromUser(group)">
   {{ group.name }}
</v-chip>

It does this : 
![image](https://user-images.githubusercontent.com/48165976/78261167-2edded00-74ff-11ea-9263-403098f468e9.png)

The thing is when I hover on it, the pointer is the little hand and it looks clickable (it even change color on hover) and so it looks like a button that doesn't work.
What I'd like with the `selectable=false` thing, is that it doesn't change on hover (color and pointer) except for the `close` button.

Note that with the disabled it gives this :
![image](https://user-images.githubusercontent.com/48165976/78261529-9d22af80-74ff-11ea-9c06-8fc4f804a522.png)
and the icon is no longer clickable.

**Comment by ElijahKotyluk** [comment] 2020-04-02 14:37
Your initial request was a bit confusing for me to understand, it seemed like you were requesting the functionality that the disabled prop provides already, thank you for the clarification.

**Comment by laurent-brisbois** [comment] 2020-04-02 14:40
> thank you for the clarification.

You're welcome. Sorry if it wasn't clear from the start.

**Comment by MajesticPotatoe** [comment] 2020-04-02 14:44
something like this: <https://codepen.io/majesticpotatoe-the-bashful/pen/jOPRKVN>?

**Comment by laurent-brisbois** [comment] 2020-04-02 14:50
> something like this: https://codepen.io/majesticpotatoe-the-bashful/pen/jOPRKVN?

Pointer : yes it is no longer the little hand
background-color : it still changes (I guess the 'none' grey is slightly different from the default grey)

**Comment by KaelWD** [comment] 2020-04-02 14:51
Duplicate of #10115, dunno why that was closed.

**Comment by laurent-brisbois** [comment] 2020-04-02 14:54
The background color could be okay though. It can be seen as a visual indicator of 'where is your pointer' or whatever. The main concern is the pointer in my opinion.

**Comment by MajesticPotatoe** [comment] 2020-04-02 15:05
@laurent-brisbois hmm, might be browser diff, because i only get mini hand over the icon, and the background changed (win 10/chrome80). This is what I was seeing:
![chip](https://user-images.githubusercontent.com/27827979/78265008-e1975680-74d1-11ea-8150-7c2f00dfc9dc.gif)

**Comment by laurent-brisbois** [comment] 2020-04-02 15:07
> @laurent-brisbois hmm, might be browser diff, because i only get mini hand over the icon, and the background changed (win 10/chrome80). This is what I was seeing:
> ![chip](https://user-images.githubusercontent.com/27827979/78265008-e1975680-74d1-11ea-8150-7c2f00dfc9dc.gif)

Well that's weird.. I'm using Win10 and Chrome Version 80.0.3987.162 too.

**Comment by laurent-brisbois** [comment] 2020-04-02 15:23
I used "chrome capture" to do a small .gif too, using your codepen, so that you can see. (However we don't see the pointer but he acts as yours did).

![v-chip](https://user-images.githubusercontent.com/48165976/78266922-b0854900-7506-11ea-8548-f23695d8dab6.gif)

**Closed** 2021-07-02 08:11 UTC
Labels: duplicate
