### ISSUE TITLE
[Bug Report] V-edit-dialog broke content aligment 

### ISSUE THREAD

**Issue by AlexKovynev** [vuetifyjs/vuetify#5025] opened 2018-09-04 04:46 UTC
### Versions and Environment
Vuetify: 1.2.1
Vue: 2.5.17
Browsers: Chrome
OS: Linux

### Previously worked in:
Vuetify: 1.0.14
Vue: 2.5.16

### Steps to reproduce

Create datatable, align column right

### Expected Behavior

align right

### Actual Behavior

align left

### Reproduction Link

https://codepen.io/anon/pen/zJwyZY?&editors=101

**Comment by jacekkarczmarczyk** [comment] 2018-09-04 06:29
Can you provide a screenshot? I don't see anything wrong here

**Comment by KaelWD** [comment] 2018-09-04 06:35
Duplicate of #4450

The iron column is supposed to be aligned right, idk where you got the wrapping thing from @jacekkarczmarczyk

**Comment by jacekkarczmarczyk** [comment] 2018-09-04 06:40
Oh I see, and wrapping was there but it just showed under some circumstances (hard to say precisely what)

**Comment by AlexKovynev** [comment] 2018-09-04 07:32
For now i use this workaround

    .v-small-dialog .v-menu__activator {
        display: block
    }

**Comment by KaelWD** [comment] 2018-09-04 09:32
That `display: flex` can be removed now anyway, v-select no longer uses the activator slot.

**Comment by AlexKovynev** [comment] 2018-10-29 05:45
Maybe someone fix it finally!:(

**Comment by wubzz** [comment] 2018-12-11 11:49
Using vuetify 1.3.8 I had to do this which feels a bit awkward:

```javascript
	/deep/ td.text-xs-right > .v-small-dialog > .v-menu__activator {
		display: block;
	}
	
	/deep/ td.text-xs-right > .v-small-dialog > .v-menu__activator > a {
		display: block;
		line-height: 47px;
	}
```

**Comment by lioneaglesolutions** [comment] 2023-05-04 01:08
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).

**Closed by lioneaglesolutions** 2023-05-04 01:08 UTC
Labels: T: bug, duplicate, T: regression, C: VEditDialog
