### ISSUE TITLE
[Feature Request] Please add Draggable to DataTable

### ISSUE THREAD

**Issue by croatialu** [vuetifyjs/vuetify#18206] opened 2023-09-04 05:46 UTC
### Problem to solve
Sorting for multiple rows can be done through the draggable handle column in each tr

### Proposed solution
use [vuedraggable](https://sortablejs.github.io/vue.draggable.next/#/table-example)

DataTable Props: 
```
/**
* 
* @default false
* */
itemDraggable?: boolean
```

[DataTable.tsx](https://github.com/vuetifyjs/vuetify/blob/b26a9731c40083af3abebc976cf10026e986a8b2/packages/vuetify/src/labs/VDataTable/VDataTable.tsx#L217)

``` 

<VueDraggable v-model={props.items} tag="tbody">
{{
  item(){
    return <DataTableRow {...props} />
  }
}}
</VueDraggable>

```

**Comment by websitevirtuoso** [comment] 2023-09-05 17:02
This request doesn't will be implemented. you can use slots and implement it on your side. 
2nd this lib doesn't support properly and better to use vue use composables like useSortable or useDragable

**Comment by KaelWD** [comment] 2023-09-06 11:38
Duplicate of #2234

**Closed by KaelWD** 2023-09-06 11:38 UTC
Labels: S: triage
