### ISSUE TITLE
[Bug Report] Snackbar default timeout should be 5 seconds

### ISSUE THREAD

**Issue by phiter** [vuetifyjs/vuetify#10365] opened 2020-01-28 17:33 UTC
### Environment
**Vuetify Version:** 2.2.6
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
1. Create a snackbar without a defined timeout.

### Expected Behavior
It should dismiss after five seconds, according to the [Material Design specs for web](https://material.io/develop/web/components/snackbars/).

### Actual Behavior
It dismisses after six seconds. This is the default timeout by Vuetify.

### Reproduction Link
<a href="https://codepen.io/phiter/pen/zYxQOoX" target="_blank">https://codepen.io/phiter/pen/zYxQOoX</a>

### Other comments
Material Design also recommends using a timeout between 4 and 10 seconds. Perhaps we should have this information in the docs so our users conform better to the MD recommendations.

**Comment by jacekkarczmarczyk** [comment] 2020-01-28 17:43
Duplicate of https://github.com/vuetifyjs/vuetify/issues/9298

**Closed by jacekkarczmarczyk** 2020-01-28 17:43 UTC
Labels: C: VSnackbar, T: bug, md2
