### ISSUE TITLE
[Feature Request] Add touch support to color picker

### ISSUE THREAD

**Issue by Joebayld** [vuetifyjs/vuetify#13313] opened 2021-03-23 22:11 UTC
### Problem to solve
Makes the color picker easier to use on mobile devices. 

### Proposed solution
The most recent release (2.4.8)  improved support for sliders on mobile devices. https://github.com/vuetifyjs/vuetify/issues/13259

What would be useful is if this same behavior applied to the color picker. As it stands now, the color picker doesn’t work that well on touch screens. Most of the events don’t fire unless you grab the small handle with a mouse. 

The color picker should allow you to grab anywhere on the gradient and it starts a drag session at that point.

**Comment by KaelWD** [comment] 2021-08-17 15:30
Duplicate of #9765

**Closed by KaelWD** 2021-08-17 15:30 UTC
Labels: S: triage, C: VColorPicker
