### ISSUE TITLE
[Bug Report] Bottom drawer overlay not covering app bar

### ISSUE THREAD

**Issue by ThomasKuhlmann** [vuetifyjs/vuetify#8040] opened 2019-07-26 09:28 UTC
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.13.6

### Steps to reproduce
Reduce the browser size so that the bottom prop of the navigation drawer gets active and then open the drawer

### Expected Behavior
Drawer opens and overlay covers all visible elements outside the drawer.

### Actual Behavior
Drawer opens but overlay covers everything except the app bar when you use the app prop in the bar. if you remove the app prop, the overlay covers everything as expected. 
 [Looking at the MD specs](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-design%2F1563837804615%2Fassets%2F11vvo5YFOWBVxYchQG46nS-fcQHwhdFny%2Fusage-types-bottom.png), this shouldn't be the case - the overlay should cover the app bar

### Reproduction Link
<a href="https://codepen.io/anon/pen/qeayqY" target="_blank">https://codepen.io/anon/pen/qeayqY</a>

**Comment by sh7dm** [comment] 2019-08-03 11:06
Workaround: https://codepen.io/sh7dm/pen/zgEpBO

**Comment by fmeyertoens** [comment] 2019-08-07 17:12
Somehow this isn't fixed. When the navigation drawer has a z-index of 6 then the overlay gets z-index of 5 which is the same as the app bar, so the overlay doesn't cover it (because the overlay is defined before in the DOM).

**Comment by sh7dm** [comment] 2019-08-07 17:18
@fmeyertoens could you provide a reproduction for this?

**Comment by fmeyertoens** [comment] 2019-08-07 17:20
The original reproduction link above should do as it uses the latest vuetify version (https://unpkg.com/vuetify/dist/vuetify.min.js)
https://codepen.io/anon/pen/qeayqY

**Comment by fmeyertoens** [comment] 2019-09-03 17:29
This was fixed in https://github.com/vuetifyjs/vuetify/commit/db84347

**Closed** 2019-09-03 17:35 UTC
Labels: Framework, T: bug, has workaround
