### ISSUE TITLE
[Bug Report] open range selectable v-datepicker in dropdown menu not set the date-table correct

### ISSUE THREAD

**Issue by geminiyellow** [vuetifyjs/vuetify#13071] opened 2021-02-08 04:36 UTC
### Environment
**Vuetify Version:** 2.4.3
**Vue Version:** 3.0.5
**Browsers:** Chrome 88.0.4324.146
**OS:** Mac OS 10.15.7

### Steps to reproduce
just modify the sample code in the docs.

- set value as [2021-01-10, 2021-01-20], open dropdown, you can see the right range
- turn the date table to [2020-01-10, 2020-01-20]
- set value as  [2021-01-10, 2021-01-20] again, open dropdown, the page still in 2020.

### Expected Behavior
when open dropdown, hope show what you selected

### Actual Behavior
if last date exist, the date table will not change

### Reproduction Link
<a href="https://codepen.io/geminiyellow/pen/BaQjYXg?editors=101" target="_blank">https://codepen.io/geminiyellow/pen/BaQjYXg?editors=101</a>

### Other comments
read the source code, i found that:

https://github.com/vuetifyjs/vuetify/blob/3c5a9234a752104590fc18c1c7889e997addcb76/packages/vuetify/src/components/VDatePicker/VDatePicker.ts#L273-L278

if set value=[] and wait this.$nextTick() and then set it again, it will working.
could you please tell more detail why not use a flag to control this flow?

**Comment by jacekkarczmarczyk** [comment] 2021-02-08 12:24
> open dropdown

i don't see any dropdown in the reproduction

**Comment by FarhatMaher** [comment] 2021-03-18 15:39
I have the same issue !

**Comment by AymericLeFeyer** [comment] 2021-03-18 20:34
Same here ..

**Comment by AymericLeFeyer** [comment] 2021-04-22 13:37
My problem was resolved with the 2.4.11 Vuetify version !
@geminiyellow Update your app, maybe yours is solved too !

**Comment by jacekkarczmarczyk** [comment] 2021-04-22 13:39
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

**Closed by jacekkarczmarczyk** 2021-04-22 13:39 UTC
Labels: C: VDatepicker, S: needs reproduction, triage
