### ISSUE TITLE
[Bug Report][3.3.3] VSelect multiple Type true is not assignable to type false | undefined

### ISSUE THREAD

**Issue by nowaysgit** [vuetifyjs/vuetify#17600] opened 2023-06-14 06:34 UTC
### Environment
**Vuetify Version:** 3.3.3
**Vue Version:** 3.3.4
**Browsers:** Chrome 114.0.0.0
**OS:** Windows 10

### Steps to reproduce
Set VSelect multiple to true with typescript `:multiple="true"`
my TS 5.1.3

### Expected Behavior
use true, false and undefined

### Actual Behavior
can't use true

### Reproduction Link
[https://codesandbox.io/s/agitated-water-vltxh3?file=/src/App.vue](https://codesandbox.io/s/agitated-water-vltxh3?file=/src/App.vue)

**Comment by KaelWD** [comment] 2023-06-14 06:37
Duplicate of #17211

Your sandbox is using 3.1.1

**Closed by KaelWD** 2023-06-14 06:37 UTC
Labels: S: triage

**Comment by nowaysgit** [comment] 2023-06-14 06:57
> Duplicate of #17211
> 
> Your sandbox is using 3.1.11

It is closed, but the error still exists. I don't understand

**Comment by KaelWD** [comment] 2023-06-14 07:05
It was fixed in vuetify 3.2.0, you're using 3.1.11

**Comment by nowaysgit** [comment] 2023-06-14 07:07
> It is closed, but the error still exists. I don't understand
I'm using Vuetify 3.3.3 as above, but the codeandbox site only has version 3.1.11.
