### ISSUE TITLE
[Bug Report][3.0.0-beta.5] v-tab slider not showing

### ISSUE THREAD

**Issue by Michael2109** [vuetifyjs/vuetify#15392] opened 2022-07-06 21:58 UTC
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 2.7.3
**Browsers:** Chrome 103.0.0.0
**OS:** Windows 10

### Steps to reproduce
Select a tab. No slider shows

### Expected Behavior
Slider to appear and move when selecting different tabs

### Actual Behavior
Slider doesn't show

### Reproduction Link
<a href="https://codepen.io/Michael2109/pen/zYWrWjN" target="_blank">https://codepen.io/Michael2109/pen/zYWrWjN</a>

**Comment by KaelWD** [comment] 2022-07-07 08:48
Duplicate of #15376

**Closed by KaelWD** 2022-07-07 08:48 UTC
Labels: S: triage
