### ISSUE TITLE
[Bug Report] active tab inside dialog

### ISSUE THREAD

**Issue by atilkan** [vuetifyjs/vuetify#5847] opened 2018-12-09 04:05 UTC
### Versions and Environment
**Vuetify:** 1.3.12
**Vue:** 2.5.18
**Browsers:** Chrome 70.0.3538.110
**OS:** Mac OS 10.14.0

### Steps to reproduce
After opening the dialog, active item is not underlined.

### Expected Behavior
open second time to see.

### Reproduction Link
<a href="https://codepen.io/atilkan/pen/BvajMo?editors=1011" target="_blank">https://codepen.io/atilkan/pen/BvajMo?editors=1011</a>

**Comment by KaelWD** [comment] 2018-12-09 04:05
Duplicate of #1978

**Closed by KaelWD** 2018-12-09 04:05 UTC
