### ISSUE TITLE
[Bug Report] Setting v-text-field to the same value twice doesn't work (even if input changed)

### ISSUE THREAD

**Issue by SuspendedPhan** [vuetifyjs/vuetify#9924] opened 2019-12-10 00:46 UTC
### Environment
**Vuetify Version:** 2.2.0-beta.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Linux x86_64

### Steps to reproduce
type in the text fields in the jsfiddle

### Expected Behavior
badname should always reset to "hihi"

### Actual Behavior
typing in badname sets it to hihi once, and then always ignores the value update afterward. goodname doesn't suffer from this because it's changing every time

### Reproduction Link
<a href="https://jsfiddle.net/sj80ok1g/5/" target="_blank">https://jsfiddle.net/sj80ok1g/5/</a>

**Comment by SuspendedPhan** [comment] 2019-12-10 00:47
Oops, the reproduction link is actually: https://jsfiddle.net/sj80ok1g/5/

**Comment by KaelWD** [comment] 2019-12-10 03:58
Duplicate of #2931

**Closed by KaelWD** 2019-12-10 03:58 UTC
Labels: triage

**Comment by KaelWD** [comment] 2019-12-10 03:59
Actually no it isn't you aren't even using v-model. Vue can't detect changes if you haven't actually changed anything.
