### ISSUE TITLE
[Bug Report] Text field autofocus not working inside menu

### ISSUE THREAD

**Issue by 4eveRS** [vuetifyjs/vuetify#3634] opened 2018-03-20 21:02 UTC
### Versions and Environment
**Vuetify:** 1.0.9
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.162
**OS:** Mac OS 10.12.6

### Steps to reproduce
Click on menu
Check for text-field focus

### Expected Behavior
Text-field should autofocus when autofocus prop is defined to true

### Actual Behavior
Text-field is not autofocusing in a particular case, when it's created inside a menu component.

### Reproduction Link
[https://codepen.io/anon/pen/XEMprj](https://codepen.io/anon/pen/XEMprj)

### Other comments
Sometimes the text-field gets the "focus" css markdown, but it doesn't have the actual focus (cursor is not focused on the text-field)

**Comment by johnleider** [comment] 2018-03-20 22:58
Duplicate of #2631, #1870, #1731, #1587 and plenty more.

**Closed by johnleider** 2018-03-20 22:58 UTC
