### ISSUE TITLE
[Bug Report] v-chip selected it not working

### ISSUE THREAD

**Issue by armadillo-dev** [vuetifyjs/vuetify#7016] opened 2019-04-18 01:42 UTC
### Versions and Environment
**Vuetify:** 1.5.5
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.103
**OS:** Mac OS 10.14.3

### Steps to reproduce
1. toggle v-chip selected(false -> true)  - it work
2. toggle v-chip selected(true -> false)  - it work, but still show as selected 
3. click any other area, finally show unselected v-chip

### Expected Behavior
when step2, show unselected v-chip

### Actual Behavior
when step2, still show selected v-chip

### Reproduction Link
<a href="https://codepen.io/armadillo-dev167/pen/axqexX?editors=1011" target="_blank">https://codepen.io/armadillo-dev167/pen/axqexX?editors=1011</a>

**Comment by KaelWD** [comment] 2019-04-18 01:56
Duplicate of #3817

**Closed by KaelWD** 2019-04-18 01:56 UTC
Labels: triage
