### ISSUE TITLE
[Bug Report] v-content not using the right height - poor user experience

### ISSUE THREAD

**Issue by rav84** [vuetifyjs/vuetify#2901] opened 2017-12-30 12:30 UTC
### Versions and Environment
**Vuetify:** 0.17.5
**Vue:** 2.5.2
**Browsers:** Safari, Google Chrome
**OS:** Mac OS 10.13.2

### Steps to reproduce
Open any of the the pre defined layout examples on iPhone from the Layout section of the documentation.
For example:
https://vuetifyjs.com/examples/layouts/google-keep
In my case I am using iPhone X but I have tried it on my wife's iPhone 6 and it has the same problem. I have tried it on both chrome and safari.

### Expected Behavior
App toolbars should stick to the top (always visible). 
Content should not be scrollable if there is no content! Or if the content is within the visible window of the browser.
On my website even though I just have a list of one item. I can scroll up and down, which is annoying.

### Actual Behavior
The content is scrollable beyond the page height. This means the "fixed" app toolbar goes hiding behind the browser url bar. This is very annoying for user.
In layout samples the content is in the centre.
You can see the screenshots for safari and chrome here:
https://drive.google.com/drive/folders/1sBLqNFdwP7NOCECaWO_OzJzVCyleF0v6?usp=sharing

### Reproduction Link
[https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/layouts/googleKeep.vue](https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/layouts/googleKeep.vue)

### Other comments
In my guess, I think v-content is calculating wrong height and thus allowing user to scroll up and down.

**Comment by johnleider** [comment] 2017-12-31 00:50
You are going to need to provide some additional details. You link the official example, but I'm not fully understanding what behavior you are mentioning. A fixed toolbar is always visible. Please create an actual reproduction with steps to observe the behavior or provide a gif/screenshot displaying the issue.

**Comment by KaelWD** [comment] 2017-12-31 05:25
Probably this: https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html

It happens on android too, it's more obvious what's going on in the baseline layout because it has a footer.

**Comment by rav84** [comment] 2018-01-13 00:46
Can you look at the screenshots? 
They clearly show the problem.

**Comment by johnleider** [comment] 2018-01-13 00:47
I did look at the screenshots. I'm not debugging an issue that I cannot reproduce.

**Comment by rav84** [comment] 2018-01-13 11:28
If you have an iPhone:
1. Open ios Safari.
2. Go to google keep predefined layouts url on vuetify documentation page [(or click me)](https://vuetifyjs.com/examples/layouts/google-keep) and scroll the content up.
3. Bingo!

You can use webinspector to debug ios safari on mac.

This can also be reproduced on ios simulator on mac.

I can spend some time with it, but it wont be soon I am afraid.

:)

**Comment by KaelWD** [comment] 2018-07-19 07:11
cc4959f didn't actually fix this, but I can't reproduce it any more in 1.1.6

This clearly isn't going anywhere so I'll close it anyway.

**Closed by KaelWD** 2018-07-19 07:11 UTC
Labels: help wanted
